### ISSUE TITLE
[v7] update `npm ci` command

### ISSUE THREAD

**Issue by mikemimik** [npm/cli#1025]
Update `npm ci` command.

- `rimraf` the `node_modules/` folder
- run `arborist.reify()`

#### Branches
- https://github.com/npm/cli/tree/mikemimik/feature/npm-ci-update

#### References
- Epic: https://github.com/npm/cli/issues/971
- Blocked by: https://github.com/npm/arborist/pull/53

**Comment by claudiahdz** [comment]
PR has been merged: https://github.com/npm/cli/pull/1100
