### ISSUE TITLE
[QUESTION] npm publish, 403 forbidden error

### ISSUE THREAD

**Issue by prozanne** [npm/cli#1026]
# What / Why
I was supposed to publish my module as public.
(It might be my mistake since I am trying to publish for the first time)

`npm login`
// I succeed to login with the message "Logged in as rozanne on https://registry.npmjs.org/."

But the issue has happened this step.
`npm publish`
// After this command, I got these error.

npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/Wits
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.

## Where
403 Forbidden - PUT https://registry.npmjs.org/Wits
I think this url is blocked.

## Who
I am using this account for trying to publish.
@rozanne

## References
- Since my developing environment is behind proxy, I've already set http/https proxy config on npm.
But unfortunately it didn't work.
- FYI, my email was already approved.

Would you please help me to solve this problem?

**Comment by prozanne** [comment]
I've checked for publishing with an empty project, there was no issue. so I think it's not a proxy issue....

**Comment by prozanne** [comment]
After I had removed the specific folder in my project, finally I could publish the module.
But still I don't know why....
And actually I have to upload the deleted folder with my project.
Is there anybody who could solve the issue?

**Comment by prozanne** [comment]
https://github.com/npm/cli/issues/805#issuecomment-600345531

**Comment by JohnVazguz** [comment]
no, i cant
