### ISSUE TITLE
Migrate to a better matching engine

### ISSUE THREAD

**Issue by jamesgeorge007** [npm/cli#1032]
As of now [meant](https://www.npmjs.com/package/meant) is made use for finding the closest match to an unknown command which isn't actively maintained anymore.
https://github.com/npm/cli/blob/ab3c62aa83375a7d4a21e396129ae5679ee86646/lib/utils/did-you-mean.js#L4

A better replacement would be [leven](https://github.com/sindresorhus/leven)

**Comment by jamesgeorge007** [comment]
@isaacs this would be a good candidate for `v7` release. I can work on a PR 👍

**Comment by isaacs** [comment]
It's relatively isolated, and the core team doesn't have any plans to get to it as a v7 beta release blocker, so yeah!  go for it!

- New implementation should have tests, with full coverage of all newly added lib code.  (Even if the old implementation _doesn't_ have full coverage, or any tests at all.)
- It would be good to understand why leven would be better.  What's "better" about it?  Faster?  Closer matches?  Fewer bugs?  (Do those bugs affect us?) etc.

**Comment by watilde** [comment]
I just noticed https://github.com/npm/cli/pull/1071 is merged and I'm curious about this part: `What's "better" about it?` asked by @isaacs and would love to get feedback for further improvements as meant was designed to use in npm at https://github.com/npm/npm/pull/10382. I'm sharing some facts I gathered in the below and still believe that it's hard to find a strong reason why it's already migrated so far.

**Size**
+ leven: 224b
+ meant: 288b
  + By deleting test file, `.github` directory and CHANGELOG as same as leven, it becomes 192b. Can be quickly done if this is a critical.

**Last update**
+ leven: 2 years ago - https://npm.im/leven
+ meant: 3 months ago - https://npm.im/meant


**Coverage**
+ leven: 94.59%
+ meant: 100%
Log: https://gist.github.com/watilde/de79754055d627f485a61656f37f72de

**Perfomance**
+ Cannot directly compare as leven does only distance calc and meant does suggestion of a similar command(Refs: [added loop by the migration](https://github.com/npm/cli/pull/1071/files#diff-e00f2f0319b3257c7c0e5ca07376b0264119325a06699ee2c13a35c7d5e47642)). For the distance calc, it should be almost the same.

**Closer matches**
+ Should be the same as it uses the same algo for calc part.

In addition, I'm happy to migrate meant repository to npm's org + provide npm members with its publish permission on registry if it helps npm community :)

cc @isaacs @jamesgeorge007 @ruyadorno

**Comment by watilde** [comment]
I wish I could hear back any feedback
