### ISSUE TITLE
$ npm login fails with: That email has already been registered.

### ISSUE THREAD

**Issue by blaasvaer** [npm/cli#1035]
# What / Why
I'm trying to login to npm to update a package.
> n/a

## When
All the time

## Where
In the Terminal on Mac OS X

### Current Behavior
When doing:
$ npm login
Get prompted for username ... type it in.
Get prompted for password ... type it in.
Get prompted for e-mail ... type it in.

Get: 400 Bad Request - PUT https://registry.npmjs.org/-/user/org.couchdb.user:blaasvaer - That email has already been registered.

### Steps to Reproduce
See above steps

### Expected Behavior
Well, to get logged in and be able to do $ npm publish

## Who
Erhm, me?

Why does npm make me think I'm trying to sign UP instead of IN?

**Comment by ljharb** [comment]
the CLI only has one action, "sign up or sign in".

http://npmjs.com/~blaasvaer is an org, not a user, so you *can't* log in as it. Perhaps you're trying to log in as https://www.npmjs.com/~samblaasvaer ?

**Comment by vufrontend** [comment]
I have the same problem

**Comment by hzhu** [comment]
You won't be able to login with your original npm username anymore if you _[converted](https://docs.npmjs.com/converting-your-user-account-to-an-org)_ your npm user to an npm organization. During the process of the conversion, npm should have asked you to create a new username. This is the new username that you will have to log in with. 

⭐ If you forgot the new username, you can find it on https://www.npmjs.com/ by logging in with your email.

⭐ If you don't know the new username's password, [use this form](https://www.npmjs.com/forgot) to create a new password.

**Comment by simesy** [comment]
If in fact you are using a user not an org, change your password seems to fix it.

**Comment by hend-elsahli** [comment]
Use `> npm adduser` instead of `> npm login`

**Comment by ljharb** [comment]
Those are the same.

**Comment by hend-elsahli** [comment]
> 

For some reason, "after resetting password "... `npm adduser` worked ... and `npm login` didn't

**Comment by ljharb** [comment]
One is an alias for the other. Maybe it was just running it twice.

**Comment by hend-elsahli** [comment]
> One is an alias for the other. Maybe it was just running it twice.

Yes ... it could be it

**Comment by MouraVocal** [comment]
> You won't be able to login with your original npm username anymore if you _[converted](https://docs.npmjs.com/converting-your-user-account-to-an-org)_ your npm user to an npm organization. During the process of the conversion, npm should have asked you to create a new username. This is the new username that you will have to log in with.
> 
> star If you forgot the new username, you can find it on https://www.npmjs.com/ by logging in with your email.
> 
> star If you don't know the new username's password, [use this form](https://www.npmjs.com/forgot) to create a new password.

This was my case, thank you!!
