### ISSUE TITLE
[BUG] install not working

### ISSUE THREAD

**Issue by smilebasti** [npm/cli#1040]
# What / Why
I am using Pterodactyl and after the resent update i wanted to restart wings and i only got this Error Log.

## When
when i follow these three steps: https://pterodactyl.io/daemon/upgrade/0.6.html

## Where
It says report to  * npm/npm

### Current Behavior
Error:
1956 verbose cwd /srv/daemon
1957 error Linux 4.15.0-88-generic
1958 error argv "/usr/bin/node" "/usr/bin/npm" "install" "--only=production"
1959 error node v8.10.0
1960 error npm  v3.5.2
1961 error code EMISSINGARG
1962 error typeerror Error: Missing required argument #1
1962 error typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
1962 error typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
1962 error typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
1962 error typeerror     at /usr/share/npm/lib/install/deps.js:457:7
1962 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
1962 error typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
1962 error typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
1962 error typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
1962 error typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
1962 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
1963 error typeerror This is an error with npm itself. Please report this error at:
1963 error typeerror     <http://github.com/npm/npm/issues>
1964 verbose exit [ 1, true ]

### Steps to Reproduce
https://pterodactyl.io/daemon/upgrade/0.6.html

### Expected Behavior
should connect panel with Daemon

## References

* n/a

**Comment by maggieyu-segment** [comment]
Looks like you need node v10 or higher?

According to the page https://pterodactyl.io/daemon/upgrade/0.6.html,

> Version 0.6.13 requires Nodejs v10 or higher in order to compile the mmmagic dependency. Please ensure you are running at least version 10. You can run node -v to check, upgrade if it is v6 or v8.

**Comment by smilebasti** [comment]
Thanks for the reply. 

My version of node.js is v12

**Comment by maggieyu-segment** [comment]
The error message says node is at 8.10.0. Maybe for some reason there were two node versions installed, and the v8 one is in use?
I came across the same error recently (but for installing a different module). I was able to fix it by updating npm to a newer version. According to the error message, npm is at 3.5.2 which is pretty old. You could try either the latest or maybe a 3.x that is higher than 3.5.

> 1959 error node v8.10.0
> 1960 error npm v3.5.2

**Comment by smilebasti** [comment]
Ok thanks for your help
