### ISSUE TITLE
Once you install jest as a dev dependency, you cannot add it as a dependency

### ISSUE THREAD

**Issue by lovefamilychildrenhappiness** [npm/cli#1046]
# What / Why

if I run 

```
npm i jest
```

it installs jest as a dependency, which is right. However, if I run 

```
npm i -D jest
```

first. It will correctly install jest as a dev dependency. But then if I run

```

npm i jest
```

there is no changes. I would expect that it would also install jest as a dependency. 

### Steps to Reproduce

It's very easy to reproduce this. 

```
  $ npm -v
  6.9.0
  $ mkdir jesttest
  $ cd jesttest
  $ npm i -D jest
  $ npm i jest
```

### Expected Behavior

I expected just to be installed as both dependency and dev-dependency.

**Comment by ljharb** [comment]
yes, you can - `npm install --save-prod jest`. I'm not sure what the shortcut is, maybe `-P`?
