### ISSUE TITLE
[BUG] ACCORDIAN IS NOT WORKING WITH ELEMENT PREOJECTION

### ISSUE THREAD

**Issue by RajRawat02** [npm/cli#1067]
APP.JS
--------
import React, { Component } from "react";
import { Container, Header, Content, Accordion } from "native-base";
import Test from './TEST';
import {
  StyleSheet,
  TouchableOpacity,
  Text,
  View,
} from 'react-native'

const dataArray = [
  {id:1, title: "First Element", content:<Test/>},
  { id:2,title: "Second Element", content: "Lorem ipsum dolor sit amet" },
  { id:3,title: "Third Element", content: "Lorem ipsum dolor sit amet" }
];
export default function  App() {
 
    return (
      <Container>
        <Header />
        <Content padder >
          <Accordion dataArray={dataArray} key={dataArray.id}/>
        </Content>
      </Container>
    );
  
}

TEST.JS
--------------
import React, { Component } from 'react'
import {
  StyleSheet,
  TouchableOpacity,
  Text,
  View,
} from 'react-native'

class Test extends React.Component {
  
  render() {
    return (
      <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
        <Text>Hello, world!</Text>
      </View>
    );
  }
}

export default Test;

TEXT INSIDE TEST IS NOT SHOWING IN SIMULATOR

**Comment by RajRawat02** [comment]
NATIVE BASE# LIBARARY

**Comment by ljharb** [comment]
Sounds like you want to file an issue on native-base instead, not here.

**Comment by douira** [comment]
First of all, I agree with @ljharb, this doesn't seem to be a npm issue. also, WHY ARE YOU YELLING?

**Comment by sankshitpandoh** [comment]
Agreed with both @douira and @ljharb , this doesn't seem like a npm issue. WHY ARE YOU HERE?
How does it feel to get yelled back at? :p
