### ISSUE TITLE
[BUG] npm ERR! cb() never called!

### ISSUE THREAD

**Issue by ldelaprade** [npm/cli#1069]
# What / Why

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     ...\AppData\Roaming\npm-cache\_logs\2020-03-27T14_55_12_267Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'core-js@3'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose npm-session e0a615111d2a8cdf
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/core-js 683ms (from cache)
8 silly pacote range manifest for core-js@3 fetched in 702ms
9 timing stage:loadCurrentTree Completed in 758ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 51ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule core-js@3.6.4 checking installable status
17 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 8ms
18 timing stage:loadIdealTree Completed in 66ms
19 silly currentTree no-name@
20 silly idealTree no-name@
20 silly idealTree `-- core-js@3.6.4
21 silly install generateActionsToTake
22 timing stage:generateActionsToTake Completed in 518ms
23 silly diffTrees action count 1
24 silly diffTrees add core-js@3.6.4
25 silly decomposeActions action count 8
26 silly decomposeActions fetch core-js@3.6.4
27 silly decomposeActions extract core-js@3.6.4
28 silly decomposeActions preinstall core-js@3.6.4
29 silly decomposeActions build core-js@3.6.4
30 silly decomposeActions install core-js@3.6.4
31 silly decomposeActions postinstall core-js@3.6.4
32 silly decomposeActions finalize core-js@3.6.4
33 silly decomposeActions refresh-package-json core-js@3.6.4
34 silly install executeActions
35 silly doSerial global-install 8
36 verbose correctMkdir C:\Users\ldelaprade\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
37 verbose makeCacheDir UID & GID are irrelevant on win32
38 verbose lock using C:\Users\ldelaprade\AppData\Roaming\npm-cache\_locks\staging-20dcc2231688dfca.lock for Z:\ldelaprade\GIT\E3\SmartWP-WebApp\node_modules\.staging
39 timing audit submit Completed in 384ms
40 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 383ms
41 timing audit body Completed in 1ms
42 silly doParallel extract 1
43 silly extract core-js@3.6.4
44 silly tarball trying core-js@3 by hash: sha512-4paDGScNgZP2IXXilaffL9X7968RuvwlkK3xWtZRVqgd8SYNiVKRJvkFd1aqqEuPfN7E68ZHEp9hDj6lHj4Hyw==
45 warn tar ENOENT: no such file or directory, open 'Z:\ldelaprade\GIT\E3\SmartWP-WebApp\node_modules\.staging\core-js-24ec1c47\es\symbol\description.js'
...
1122 warn tar ENOENT: no such file or directory, open 'Z:\ldelaprade\GIT\E3\SmartWP-WebApp\node_modules\.staging\core-js-24ec1c47\modules\web.url.js'
1123 timing npm Completed in 1481032ms
1124 error cb() never called!
1125 error This is an error with npm itself. Please report this error at:
1126 error <https://npm.community>

## When

* n/a

## Where

* n/a

### Current Behavior

* n/a

### Steps to Reproduce

* n/a

### Expected Behavior

* n/a

## Who

* n/a

## References

* n/a

**Comment by lalits1996t** [comment]
https://www.canadaposttrackingg.com/canada-post-lost-tracking-number
https://www.canadaposttrackingg.com/how-long-can-customs-hold-my-package-held-in-customs
https://www.canadaposttrackingg.com/canada-post-registered-mail-canada-post-registered-mail-international
https://www.canadaposttrackingg.com/canada-post-sunday-hours-canada-post-open-sunday
https://www.canadaposttrackingg.com/canada-post-hours-shoppers-calgary-edmonton
https://www.canadaposttrackingg.com/canada-post-shipping-rates-international-postage-rates
https://www.canadaposttrackingg.com/canada-post-delivery-times-canada-post-delivery-hours
https://www.canadaposttrackingg.com/canada-post-express-post-xpresspost-international
https://www.canadaposttrackingg.com/canada-post-hold-mail-request
https://www.canadaposttrackingg.com/canada-post-mail-forwarding-service-mail-forwarding-request
https://www.canadaposttrackingg.com/canada-post-saturday-delivery-canada-post-weekend-delivery
https://www.canadaposttrackingg.com/is-canada-post-open-today-or-is-there-mail-delivery-today-in-canada
https://www.canadaposttrackingg.com/canada-post-lettermail-rates-size-delivery-time
https://www.canadaposttrackingg.com/canada-post-flex-delivery-how-to-use-flex-delivery
https://www.canadaposttrackingg.com/how-to-properly-address-an-envelope-or-how-to-address-mail
https://www.canadaposttrackingg.com/canada-post-refund-for-late-delivery-refund-request-package-claim
https://www.canadaposttrackingg.com/canada-post-personalized-mail-rates-delivery-standards
https://www.canadaposttrackingg.com/canada-post-neighbourhood-mail-rates
https://www.canadaposttrackingg.com/canada-post-undeliverable-mail
https://www.canadaposttrackingg.com/canada-post-priority-mail-priority-mail-express-international
https://www.canadaposttrackingg.com/canada-post-post-office-box-rental
https://www.canadaposttrackingg.com/canada-post-holidays-2020-canada-post-holiday-hours
https://www.canadaposttrackingg.com/canada-post-flat-rate-box-shipping-boxes-flat-rates
https://www.canadaposttrackingg.com/canada-post-prepaid-envelope-canada-post-flat-rate-envelope
https://www.canadaposttrackingg.com/canada-post-expedited-parcel-delivery-standards-delivery-times
https://www.canadaposttrackingg.com/purolator-holidays-2020-purolator-holiday-hours/
https://www.canadaposttrackingg.com/australia-post-holidays-aus-post-holiday-hours/
https://www.canadaposttrackingg.com/royal-mail-holidays-public-holidays/
