### ISSUE TITLE
[BUG] <title>error cb() never called!

### ISSUE THREAD

**Issue by atishay-aj** [npm/cli#1070]
# What / Why

npm ERR! cb() never called!

## When
running this command to create react app
npx create-react-app my-app

C:\Users\MY>npx create-react-app my-app
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MY\AppData\Roaming\npm-cache\_logs\2020-03-27T15_56_26_743Z-debug.log
Install for [ 'create-react-app@latest' ] failed with code 1

file cache-
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   '--save-exact',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   'react',
1 verbose cli   'react-dom',
1 verbose cli   'react-scripts',
1 verbose cli   'cra-template'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v13.12.0
4 verbose npm-session 2f38cb1f39598541
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/cra-template 1154ms
8 http fetch GET 200 https://registry.npmjs.org/react 1238ms
9 http fetch GET 200 https://registry.npmjs.org/cra-template/-/cra-template-1.0.3.tgz 316ms
10 silly pacote tag manifest for cra-template@latest fetched in 1497ms
11 http fetch GET 200 https://registry.npmjs.org/react/-/react-16.13.1.tgz 2517ms
12 silly pacote tag manifest for react@latest fetched in 3806ms
13 http fetch GET 200 https://registry.npmjs.org/react-scripts 7883ms
14 http fetch GET 200 https://registry.npmjs.org/react-dom 8301ms
15 http fetch GET 200 https://registry.npmjs.org/react-scripts/-/react-scripts-3.4.1.tgz 1099ms
16 silly pacote tag manifest for react-scripts@latest fetched in 9025ms
17 http fetch GET 200 https://registry.npmjs.org/react-dom/-/react-dom-16.13.1.tgz 2455ms
18 silly pacote tag manifest for react-dom@latest fetched in 10785ms
19 timing stage:loadCurrentTree Completed in 10847ms
20 silly install loadIdealTree
21 silly install cloneCurrentTreeToIdealTree
22 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
23 silly install loadShrinkwrap
24 timing stage:loadIdealTree:loadShrinkwrap Completed in 2ms
25 silly install loadAllDepsIntoIdealTree
26 silly resolveWithNewModule cra-template@1.0.3 checking installable status
27 silly resolveWithNewModule react@16.13.1 checking installable status
28 silly resolveWithNewModule react-scripts@3.4.1 checking installable status
29 silly resolveWithNewModule react-dom@16.13.1 checking installable status
30 http fetch GET 200 https://registry.npmjs.org/object-assign 153ms
31 http fetch GET 200 https://registry.npmjs.org/loose-envify 181ms
32 http fetch GET 200 https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz 245ms
33 silly pacote range manifest for loose-envify@^1.1.0 fetched in 446ms
34 silly resolveWithNewModule loose-envify@1.4.0 checking installable status
35 http fetch GET 200 https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz 753ms
36 silly pacote range manifest for object-assign@^4.1.1 fetched in 924ms
37 silly resolveWithNewModule object-assign@4.1.1 checking installable status
38 http fetch GET 200 https://registry.npmjs.org/prop-types 2153ms
39 http fetch GET 200 https://registry.npmjs.org/prop-types/-/prop-types-15.7.2.tgz 739ms
40 silly pacote range manifest for prop-types@^15.6.2 fetched in 2908ms
41 silly resolveWithNewModule prop-types@15.7.2 checking installable status
42 http fetch GET 200 https://registry.npmjs.org/js-tokens 163ms
43 http fetch GET 200 https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz 150ms
44 silly pacote range manifest for js-tokens@^3.0.0 || ^4.0.0 fetched in 339ms
45 silly resolveWithNewModule js-tokens@4.0.0 checking installable status
46 http fetch GET 200 https://registry.npmjs.org/react-is 669ms
47 http fetch GET 200 https://registry.npmjs.org/react-is/-/react-is-16.13.1.tgz 171ms
48 silly pacote range manifest for react-is@^16.8.1 fetched in 860ms
49 silly resolveWithNewModule react-is@16.13.1 checking installable status
50 http fetch GET 200 https://registry.npmjs.org/scheduler 757ms
51 http fetch GET 200 https://registry.npmjs.org/scheduler/-/scheduler-0.19.1.tgz 346ms
52 silly pacote range manifest for scheduler@^0.19.1 fetched in 1121ms
53 silly resolveWithNewModule scheduler@0.19.1 checking installable status
54 http fetch GET 200 https://registry.npmjs.org/@babel%2fcore 552ms
55 http fetch GET 200 https://registry.npmjs.org/@svgr%2fwebpack 771ms
56 http fetch GET 200 https://registry.npmjs.org/babel-loader 835ms
57 http fetch GET 200 https://registry.npmjs.org/babel-preset-react-app 1058ms
58 http fetch GET 200 https://registry.npmjs.org/babel-jest 1102ms
59 http fetch GET 200 https://registry.npmjs.org/babel-loader/-/babel-loader-8.1.0.tgz 718ms
60 silly pacote version manifest for babel-loader@8.1.0 fetched in 1573ms
61 silly resolveWithNewModule babel-loader@8.1.0 checking installable status
62 http fetch GET 200 https://registry.npmjs.org/babel-preset-react-app/-/babel-preset-react-app-9.1.2.tgz 530ms
63 silly pacote range manifest for babel-preset-react-app@^9.1.2 fetched in 1607ms
64 silly resolveWithNewModule babel-preset-react-app@9.1.2 checking installable status
65 http fetch GET 200 https://registry.npmjs.org/babel-jest/-/babel-jest-24.9.0.tgz 517ms
66 silly pacote range manifest for babel-jest@^24.9.0 fetched in 1644ms
67 silly resolveWithNewModule babel-jest@24.9.0 checking installable status
68 http fetch GET 200 https://registry.npmjs.org/@svgr/webpack/-/webpack-4.3.3.tgz 1061ms
69 silly pacote version manifest for @svgr/webpack@4.3.3 fetched in 1854ms
70 silly resolveWithNewModule @svgr/webpack@4.3.3 checking installable status
71 http fetch GET 200 https://registry.npmjs.org/case-sensitive-paths-webpack-plugin 391ms
72 http fetch GET 200 https://registry.npmjs.org/css-loader 565ms
73 http fetch GET 304 https://registry.npmjs.org/dotenv 551ms (from cache)
74 http fetch GET 200 https://registry.npmjs.org/dotenv/-/dotenv-8.2.0.tgz 15ms (from cache)
75 silly pacote version manifest for dotenv@8.2.0 fetched in 581ms
76 silly resolveWithNewModule dotenv@8.2.0 checking installable status
77 http fetch GET 200 https://registry.npmjs.org/babel-eslint 2291ms
78 http fetch GET 200 https://registry.npmjs.org/case-sensitive-paths-webpack-plugin/-/case-sensitive-paths-webpack-plugin-2.3.0.tgz 524ms
79 silly pacote version manifest for case-sensitive-paths-webpack-plugin@2.3.0 fetched in 930ms
80 silly resolveWithNewModule case-sensitive-paths-webpack-plugin@2.3.0 checking installable status
81 http fetch GET 200 https://registry.npmjs.org/css-loader/-/css-loader-3.4.2.tgz 530ms
82 silly pacote version manifest for css-loader@3.4.2 fetched in 1118ms
83 silly resolveWithNewModule css-loader@3.4.2 checking installable status
84 http fetch GET 200 https://registry.npmjs.org/dotenv-expand 1199ms
85 http fetch GET 200 https://registry.npmjs.org/@babel/core/-/core-7.9.0.tgz 2506ms
86 silly pacote version manifest for @babel/core@7.9.0 fetched in 3080ms
87 silly resolveWithNewModule @babel/core@7.9.0 checking installable status
88 http fetch GET 200 https://registry.npmjs.org/eslint-config-react-app 820ms
89 http fetch GET 200 https://registry.npmjs.org/eslint-loader 880ms
90 http fetch GET 304 https://registry.npmjs.org/camelcase 3782ms (from cache)
91 http fetch GET 200 https://registry.npmjs.org/dotenv-expand/-/dotenv-expand-5.1.0.tgz 918ms
92 silly pacote version manifest for dotenv-expand@5.1.0 fetched in 2136ms
93 silly resolveWithNewModule dotenv-expand@5.1.0 checking installable status
94 http fetch GET 200 https://registry.npmjs.org/eslint-config-react-app/-/eslint-config-react-app-5.2.1.tgz 985ms
95 silly pacote range manifest for eslint-config-react-app@^5.2.1 fetched in 1823ms
96 silly resolveWithNewModule eslint-config-react-app@5.2.1 checking installable status
97 http fetch GET 200 https://registry.npmjs.org/eslint-loader/-/eslint-loader-3.0.3.tgz 945ms
98 silly pacote version manifest for eslint-loader@3.0.3 fetched in 1843ms
99 silly resolveWithNewModule eslint-loader@3.0.3 checking installable status
100 http fetch GET 200 https://registry.npmjs.org/camelcase/-/camelcase-5.3.1.tgz 987ms
101 silly pacote range manifest for camelcase@^5.3.1 fetched in 4784ms
102 silly resolveWithNewModule camelcase@5.3.1 checking installable status
103 http fetch GET 200 https://registry.npmjs.org/eslint-plugin-jsx-a11y 1143ms
104 http fetch GET 200 https://registry.npmjs.org/eslint-plugin-react 1425ms
105 http fetch GET 200 https://registry.npmjs.org/eslint 3814ms
106 http fetch GET 200 https://registry.npmjs.org/eslint-plugin-jsx-a11y/-/eslint-plugin-jsx-a11y-6.2.3.tgz 2398ms
107 silly pacote version manifest for eslint-plugin-jsx-a11y@6.2.3 fetched in 3593ms
108 silly resolveWithNewModule eslint-plugin-jsx-a11y@6.2.3 checking installable status
109 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2fparser 8061ms
110 http fetch GET 200 https://registry.npmjs.org/file-loader 242ms
111 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint/parser/-/parser-2.25.0.tgz 796ms
112 silly pacote range manifest for @typescript-eslint/parser@^2.10.0 fetched in 8902ms
113 silly resolveWithNewModule @typescript-eslint/parser@2.25.0 checking installable status
114 http fetch GET 304 https://registry.npmjs.org/fs-extra 549ms (from cache)
115 http fetch GET 200 https://registry.npmjs.org/fs-extra/-/fs-extra-8.1.0.tgz 16ms (from cache)
116 silly pacote range manifest for fs-extra@^8.1.0 fetched in 584ms
117 silly resolveWithNewModule fs-extra@8.1.0 checking installable status
118 http fetch GET 200 https://registry.npmjs.org/eslint-plugin-react/-/eslint-plugin-react-7.19.0.tgz 5079ms
119 silly pacote version manifest for eslint-plugin-react@7.19.0 fetched in 6522ms
120 silly resolveWithNewModule eslint-plugin-react@7.19.0 checking installable status
121 http fetch GET 200 https://registry.npmjs.org/html-webpack-plugin 2718ms
122 http fetch GET 200 https://registry.npmjs.org/eslint/-/eslint-6.8.0.tgz 6953ms
123 silly pacote range manifest for eslint@^6.6.0 fetched in 10823ms
124 silly resolveWithNewModule eslint@6.8.0 checking installable status
125 http fetch GET 200 https://registry.npmjs.org/jest 12573ms attempt #2
126 http fetch GET 200 https://registry.npmjs.org/identity-obj-proxy 14596ms attempt #2
127 http fetch GET 200 https://registry.npmjs.org/jest/-/jest-24.9.0.tgz 154ms
128 silly pacote version manifest for jest@24.9.0 fetched in 12745ms
129 silly resolveWithNewModule jest@24.9.0 checking installable status
130 http fetch GET 200 https://registry.npmjs.org/jest-environment-jsdom-fourteen 234ms
131 http fetch GET 200 https://registry.npmjs.org/identity-obj-proxy/-/identity-obj-proxy-3.0.0.tgz 541ms
132 silly pacote version manifest for identity-obj-proxy@3.0.0 fetched in 15150ms
133 silly resolveWithNewModule identity-obj-proxy@3.0.0 checking installable status
134 http fetch GET 200 https://registry.npmjs.org/jest-resolve 484ms
135 http fetch GET 200 https://registry.npmjs.org/jest-environment-jsdom-fourteen/-/jest-environment-jsdom-fourteen-1.0.1.tgz 805ms
136 silly pacote version manifest for jest-environment-jsdom-fourteen@1.0.1 fetched in 1058ms
137 silly resolveWithNewModule jest-environment-jsdom-fourteen@1.0.1 checking installable status
138 http fetch GET 200 https://registry.npmjs.org/jest-resolve/-/jest-resolve-24.9.0.tgz 164ms
139 silly pacote version manifest for jest-resolve@24.9.0 fetched in 665ms
140 silly resolveWithNewModule jest-resolve@24.9.0 checking installable status
141 http fetch GET 200 https://registry.npmjs.org/mini-css-extract-plugin 365ms
142 http fetch GET 200 https://registry.npmjs.org/mini-css-extract-plugin/-/mini-css-extract-plugin-0.9.0.tgz 185ms
143 silly pacote version manifest for mini-css-extract-plugin@0.9.0 fetched in 574ms
144 silly resolveWithNewModule mini-css-extract-plugin@0.9.0 checking installable status
145 http fetch GET 200 https://registry.npmjs.org/optimize-css-assets-webpack-plugin 159ms
146 http fetch GET 200 https://registry.npmjs.org/file-loader/-/file-loader-4.3.0.tgz 21100ms attempt #2
147 silly pacote version manifest for file-loader@4.3.0 fetched in 21359ms
148 silly resolveWithNewModule file-loader@4.3.0 checking installable status
149 http fetch GET 200 https://registry.npmjs.org/jest-watch-typeahead 2810ms
150 http fetch GET 200 https://registry.npmjs.org/jest-watch-typeahead/-/jest-watch-typeahead-0.4.2.tgz 189ms
151 silly pacote version manifest for jest-watch-typeahead@0.4.2 fetched in 3014ms
152 silly resolveWithNewModule jest-watch-typeahead@0.4.2 checking installable status
153 http fetch GET 200 https://registry.npmjs.org/postcss-flexbugs-fixes 261ms
154 http fetch GET 200 https://registry.npmjs.org/pnp-webpack-plugin 936ms
155 http fetch GET 200 https://registry.npmjs.org/postcss-flexbugs-fixes/-/postcss-flexbugs-fixes-4.1.0.tgz 157ms
156 silly pacote version manifest for postcss-flexbugs-fixes@4.1.0 fetched in 432ms
157 silly resolveWithNewModule postcss-flexbugs-fixes@4.1.0 checking installable status
158 silly fetchPackageMetaData error for @typescript-eslint/eslint-plugin@^2.10.0 Response timeout while trying to fetch https://registry.npmjs.org/@typescript-eslint%2feslint-plugin (over 30000ms)
159 http fetch GET 200 https://registry.npmjs.org/optimize-css-assets-webpack-plugin/-/optimize-css-assets-webpack-plugin-5.0.3.tgz 3376ms
160 silly pacote version manifest for optimize-css-assets-webpack-plugin@5.0.3 fetched in 3549ms
161 silly resolveWithNewModule optimize-css-assets-webpack-plugin@5.0.3 checking installable status
162 http fetch GET 200 https://registry.npmjs.org/postcss-loader 1125ms
163 http fetch GET 200 https://registry.npmjs.org/pnp-webpack-plugin/-/pnp-webpack-plugin-1.6.4.tgz 1409ms
164 silly pacote version manifest for pnp-webpack-plugin@1.6.4 fetched in 2357ms
165 silly resolveWithNewModule pnp-webpack-plugin@1.6.4 checking installable status
166 http fetch GET 200 https://registry.npmjs.org/postcss-safe-parser 234ms
167 http fetch GET 200 https://registry.npmjs.org/postcss-normalize 1378ms
168 http fetch GET 200 https://registry.npmjs.org/postcss-normalize/-/postcss-normalize-8.0.1.tgz 150ms
169 silly pacote version manifest for postcss-normalize@8.0.1 fetched in 1541ms
170 silly resolveWithNewModule postcss-normalize@8.0.1 checking installable status
171 http fetch GET 200 https://registry.npmjs.org/postcss-safe-parser/-/postcss-safe-parser-4.0.1.tgz 495ms
172 silly pacote version manifest for postcss-safe-parser@4.0.1 fetched in 742ms
173 silly resolveWithNewModule postcss-safe-parser@4.0.1 checking installable status
174 http fetch GET 200 https://registry.npmjs.org/react-app-polyfill 642ms
175 http fetch GET 200 https://registry.npmjs.org/postcss-preset-env 1781ms
176 http fetch GET 200 https://registry.npmjs.org/react-app-polyfill/-/react-app-polyfill-1.0.6.tgz 242ms
177 silly pacote range manifest for react-app-polyfill@^1.0.6 fetched in 897ms
178 silly resolveWithNewModule react-app-polyfill@1.0.6 checking installable status
179 http fetch GET 200 https://registry.npmjs.org/postcss-preset-env/-/postcss-preset-env-6.7.0.tgz 238ms
180 silly pacote version manifest for postcss-preset-env@6.7.0 fetched in 2033ms
181 silly resolveWithNewModule postcss-preset-env@6.7.0 checking installable status
182 http fetch GET 200 https://registry.npmjs.org/react-dev-utils 722ms
183 http fetch GET 200 https://registry.npmjs.org/resolve 521ms
184 http fetch GET 200 https://registry.npmjs.org/resolve/-/resolve-1.15.0.tgz 361ms
185 silly pacote version manifest for resolve@1.15.0 fetched in 906ms
186 silly resolveWithNewModule resolve@1.15.0 checking installable status
187 http fetch GET 200 https://registry.npmjs.org/resolve-url-loader 829ms
188 silly fetchPackageMetaData error for eslint-plugin-flowtype@4.6.0 Response timeout while trying to fetch https://registry.npmjs.org/eslint-plugin-flowtype (over 30000ms)
189 http fetch GET 200 https://registry.npmjs.org/resolve-url-loader/-/resolve-url-loader-3.1.1.tgz 297ms
190 silly pacote version manifest for resolve-url-loader@3.1.1 fetched in 1142ms
191 silly resolveWithNewModule resolve-url-loader@3.1.1 checking installable status
192 http fetch GET 200 https://registry.npmjs.org/sass-loader 444ms
193 http fetch GET 200 https://registry.npmjs.org/sass-loader/-/sass-loader-8.0.2.tgz 262ms
194 silly pacote version manifest for sass-loader@8.0.2 fetched in 723ms
195 silly resolveWithNewModule sass-loader@8.0.2 checking installable status
196 http fetch GET 304 https://registry.npmjs.org/semver 927ms (from cache)
197 silly pacote version manifest for semver@6.3.0 fetched in 932ms
198 silly resolveWithNewModule semver@6.3.0 checking installable status
199 silly fetchPackageMetaData error for eslint-plugin-import@2.20.1 Response timeout while trying to fetch https://registry.npmjs.org/eslint-plugin-import (over 30000ms)
200 http fetch GET 200 https://registry.npmjs.org/style-loader 763ms
201 http fetch GET 200 https://registry.npmjs.org/style-loader/-/style-loader-0.23.1.tgz 304ms
202 silly pacote version manifest for style-loader@0.23.1 fetched in 1079ms
203 silly resolveWithNewModule style-loader@0.23.1 checking installable status
204 silly fetchPackageMetaData error for babel-plugin-named-asset-import@^0.3.6 Response timeout while trying to fetch https://registry.npmjs.org/babel-plugin-named-asset-import (over 30000ms)
205 http fetch GET 200 https://registry.npmjs.org/postcss-loader/-/postcss-loader-3.0.0.tgz 4565ms
206 silly pacote version manifest for postcss-loader@3.0.0 fetched in 5706ms
207 silly resolveWithNewModule postcss-loader@3.0.0 checking installable status
208 silly fetchPackageMetaData error for eslint-plugin-react-hooks@^1.6.1 Response timeout while trying to fetch https://registry.npmjs.org/eslint-plugin-react-hooks (over 30000ms)
209 http fetch GET 200 https://registry.npmjs.org/workbox-webpack-plugin 1163ms
210 http fetch GET 200 https://registry.npmjs.org/react-dev-utils/-/react-dev-utils-10.2.1.tgz 4484ms
211 silly pacote range manifest for react-dev-utils@^10.2.1 fetched in 5226ms
212 silly resolveWithNewModule react-dev-utils@10.2.1 checking installable status
213 http fetch GET 200 https://registry.npmjs.org/workbox-webpack-plugin/-/workbox-webpack-plugin-4.3.1.tgz 481ms
214 silly pacote version manifest for workbox-webpack-plugin@4.3.1 fetched in 1660ms
215 silly resolveWithNewModule workbox-webpack-plugin@4.3.1 checking installable status
216 http fetch GET 200 https://registry.npmjs.org/webpack-manifest-plugin 2633ms
217 http fetch GET 200 https://registry.npmjs.org/fsevents 1224ms
218 http fetch GET 200 https://registry.npmjs.org/fsevents/-/fsevents-2.1.2.tgz 17ms (from cache)
219 silly pacote version manifest for fsevents@2.1.2 fetched in 1254ms
220 silly resolveWithNewModule fsevents@2.1.2 checking installable status
221 http fetch GET 200 https://registry.npmjs.org/url-loader 4011ms
222 http fetch GET 200 https://registry.npmjs.org/webpack-manifest-plugin/-/webpack-manifest-plugin-2.2.0.tgz 353ms
223 silly pacote version manifest for webpack-manifest-plugin@2.2.0 fetched in 2999ms
224 silly resolveWithNewModule webpack-manifest-plugin@2.2.0 checking installable status
225 http fetch GET 200 https://registry.npmjs.org/webpack-dev-server 3492ms
226 http fetch GET 200 https://registry.npmjs.org/webpack 6175ms
227 http fetch GET 200 https://registry.npmjs.org/url-loader/-/url-loader-2.3.0.tgz 2833ms
228 silly pacote version manifest for url-loader@2.3.0 fetched in 6857ms
229 silly resolveWithNewModule url-loader@2.3.0 checking installable status
230 http fetch GET 200 https://registry.npmjs.org/webpack/-/webpack-4.42.0.tgz 3780ms
231 silly pacote version manifest for webpack@4.42.0 fetched in 10010ms
232 silly resolveWithNewModule webpack@4.42.0 checking installable status
233 http fetch GET 200 https://registry.npmjs.org/ts-pnp 10884ms attempt #2
234 http fetch GET 200 https://registry.npmjs.org/ts-pnp/-/ts-pnp-1.1.6.tgz 153ms
235 silly pacote version manifest for ts-pnp@1.1.6 fetched in 11050ms
236 silly resolveWithNewModule ts-pnp@1.1.6 checking installable status
237 http fetch GET 200 https://registry.npmjs.org/webpack-dev-server/-/webpack-dev-server-3.10.3.tgz 12395ms
238 silly pacote version manifest for webpack-dev-server@3.10.3 fetched in 15915ms
239 silly resolveWithNewModule webpack-dev-server@3.10.3 checking installable status
240 silly fetchPackageMetaData error for terser-webpack-plugin@2.3.5 Response timeout while trying to fetch https://registry.npmjs.org/terser-webpack-plugin (over 30000ms)
241 http fetch GET 200 https://registry.npmjs.org/babel-eslint/-/babel-eslint-10.1.0.tgz 83515ms attempt #3
242 silly pacote version manifest for babel-eslint@10.1.0 fetched in 85824ms
243 silly resolveWithNewModule babel-eslint@10.1.0 checking installable status
244 timing npm Completed in 102590ms
245 error cb() never called!
246 error This is an error with npm itself. Please report this error at:
247 error <https://npm.community>

**Comment by zachsa** [comment]
I get this same error after running the command `expo init my-project` as directed in the expo tutorial: https://reactnative.dev/docs/environment-setup. 

However, I then changed directory into `my-project` (`cd my project`), and then `npm install` worked.

(npm V6.14.4)

**Comment by atishay-aj** [comment]
Use command for cache clear , it will make it right . After compression of
cache my command runs well.
Thank you
