### ISSUE TITLE
[BUG] npm install crashes: EMISSINGARG

### ISSUE THREAD

**Issue by richtone** [npm/cli#1074]
# What / Why

npm install crashes with the following messages:

38005 error Linux 5.3.0-40-generic
38006 error argv "/usr/bin/node" "/usr/bin/npm" "install"
38007 error node v8.10.0
38008 error npm  v3.5.2
38009 error code EMISSINGARG
38010 error typeerror Error: Missing required argument #1
38010 error typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
38010 error typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
38010 error typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
38010 error typeerror     at /usr/share/npm/lib/install/deps.js:457:7
38010 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
38010 error typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
38010 error typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
38010 error typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
38010 error typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
38010 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
38011 error typeerror This is an error with npm itself. Please report this error at:

## When

* When I run "npm install"

## Where

* On my machine

### Current Behavior

* I doesn't run, it crashes

### Steps to Reproduce

* run "npm install"

### Expected Behavior

* To install all dependencies in package.json

## Who

* Me

## References

* I have hopefully included the log file that was generated.

**Comment by richtone** [comment]
Seems like the problem was caused by the following record in package.json:


  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }

These lines added by react-scripts when launching first time.

**Comment by PankajGadia16** [comment]
How did you solve this?
