### ISSUE TITLE
Optional Non-installed Dependencies

### ISSUE THREAD

**Issue by fishcharlie** [npm/cli#1085]
# What / Why

> It would be great instead of `optionalDependencies` in the `package.json` options, if there was an option just like `optionalDependencies` but that the package wouldn't be installed by default. This would be especially useful for things like the [debug npm package](https://www.npmjs.com/package/debug). An example of this would be, I want users to be able to use `debug` and get information provided by it from my NPM package, but not all users will need to take advantage of that `debug` functionality, so it shouldn't be installed by default, and should be completely optional.

## When

* n/a

## Where

* npm/cli

### Current Behavior

* `optionalDependencies` installs automatically

### Expected Behavior

* Option to mark optionalDependency as not installed automatically, it'd be great if the CLI alerted users that these are additional packages that can be installed manually for more functionality.

## Who

* n/a

## References

* n/a

**Comment by ljharb** [comment]
I believe you can already do this with peer deps + peerDependenciesMeta?

**Comment by fishcharlie** [comment]
@ljharb Any documentation on that? All I see is info for `peerDependencies` under the [package.json docs](https://docs.npmjs.com/files/package.json). Looks more like for use with plugins, I'm not sure if that is the same use case as what I'm trying to do. But maybe adding `peerDependenciesMeta` gives more flexibility? But never heard of the `peerDependenciesMeta` option before.

**Comment by abdonrd** [comment]
I have created an issue about document the `peerDependenciesMeta` property: #1247

**Comment by RemyRylan** [comment]
For anyone stumbling on this same problem, `peerDependencies` + marking as optional using `peerDependenciesMeta` still automatically installs and is not currently a solution.

I've opened an issue here to discuss: https://github.com/npm/rfcs/issues/221

**Comment by RemyRylan** [comment]
@fishcharlie fyi, this was implemented here: https://github.com/npm/arborist/commit/e13ba3bb66a7f7619c3baaa03cc7bccb5201e1ce and I presume it will be in the next npm v7 beta, but that's up to the npm team.

It relies on using the `peerDependenciesMeta` field, paired with `{ "optional": true }`.

Example `package.json`:

```json
{
  "peerDependencies": {
     "react": "^16.0.0"
  },
  "peerDependenciesMeta": {
     "react": {
        "optional": true
     }
  }
```

In this case, `react` will not be automatically installed.
