### ISSUE TITLE
[QUESTION] npm scripts not running

### ISSUE THREAD

**Issue by thinkverse** [npm/cli#1086]
# What / Why
So I'm having an issue with npm, no matter what node version I run, or which folder the project is in, `npm run` won't execute the script, there are no errors in the console, no indication to what the problem might be, checking the `PATH` the node version and npm are always in the same `PATH` so no symlink issues?

Running `npm run-script` shows the list of all scripts, and when running `npm run` all I get is nothing, no feedback at all.

Tried using the default `test` script
```json
"test": "echo \"Error: no test specified\" && exit 1"
```
but no, no `echo` it won't do anything.

I'm out of ideas on what to do, figured I'd ask here.

## System
- macOS High Sierra v10.13.6
- node: v12.16.1
- npm v6.14.4

**Comment by vijay9993** [comment]
Dear all
 I'm having an issue with NPM, issues on My angular 9 when i am trying to install Bootstrap (npm i bootstrap) im facing this issues continuously. **im a MacBook Pro user**


> fsevents@1.2.11 install /Users/vijaysiva/Downloads/vijay_new/boots/respons/node_modules/watchpack/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> fsevents@1.2.11 install /Users/vijaysiva/Downloads/vijay_new/boots/respons/node_modules/webpack-dev-server/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
**npm WARN bootstrap@4.4.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.4.1 requires a peer of popper.js@^1.16.0 but none is installed. You must install peer dependencies yourself.**

+ bootstrap@4.4.1
added 139 packages from 33 contributors, updated 1 package and audited 15584 packages in 17.936s

36 packages are looking for funding
  run `npm fund` for details

found 51 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
[Vijays-MacBook-Pro:vijay_new/boots/respons]

**Comment by thinkverse** [comment]
Update, apparently my `.npmrc` had `ignore-scripts` set to `true` all of a sudden, setting that to `false` fixed my issue.
