### ISSUE TITLE
Can not install any packages through `npm install`

### ISSUE THREAD

**Issue by firehudson** [npm/cli#1102]
# What / Why

> I can not install npm packages e.g. reselect, redux-mock-store and many more.

Npm install just fails with the following message

> error An unexpected error occurred: "http://78.186.26.36:34969/@types%2fredux-mock-store/-/redux-mock-store-1.0.2.tgz: ETIMEDOUT".

The error can not only be reproduced on the pipeline (where highspeed connection is obvious) but also at local.

## Where

* Possible it's npm public registry

## References

* Attaching a screen shot of the same
![Screenshot from 2020-04-03 17-20-15](https://user-images.githubusercontent.com/18103669/78358361-b0518000-75d0-11ea-84f7-ec1e736fed38.png)

**Comment by ljharb** [comment]
That IP address suggests you’re using a private registry that you can’t reach. Do you have “registry” set in an `.npmrc` file?

**Comment by firehudson** [comment]
Thanks for response @ljharb 

No, I was not using any private registry. The packages were directly added from the npm-registry.
I'm still not sure what/why that issue was but thankfully it was resolved automatically on the same day later in the evening.

I'm closing this issue. Thanks for responding
