### ISSUE TITLE
npm install -g mup throws "error cb() never called!"

### ISSUE THREAD

**Issue by Frustrated-Programmer** [npm/cli#1105]
# What / Why
Ran `npm install -g mup` and recieved an error.
I also ran `npm cache clean --force` yesterday so I should be in the clear there.

## When
* n/a

## Where
* n/a

### Current Behavior
Recieved errors. Here's the debug.log
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'mup'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v13.12.0
4 verbose npm-session 8f75f85bdb16b5a4
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/mup 10068ms
8 timing npm Completed in 26621ms
9 error cb() never called!
10 error This is an error with npm itself. Please report this error at:
11 error <https://npm.community>
```
* n/a

### Steps to Reproduce
run `npm install -g mup`
I made sure this wasn't a one-time error by trying again in a different directory, same error.

### Expected Behavior
installed the mup module globally

## Who
* n/a

## References
* n/a

**Comment by Orestes120** [comment]
I had the same issue "npm cache clear --force", worked for me.

**Comment by Frustrated-Programmer** [comment]
Well something changed since yesterday as I decided to try again a few mins ago... And no error happened. No idea why or what caused it.
