### ISSUE TITLE
This is an error with npm itself

### ISSUE THREAD

**Issue by Patil-Madhuri** [npm/cli#1115]
# What / Why
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Dekstop/.npm/_logs/2020-04-06T12_54_38_176Z-debug.log
✖ Package install failed, see above.
> n/a

## When
creating angular project
* n/a

## Where

* n/a

### Current Behavior

* n/a

### Steps to Reproduce

* n/a

### Expected Behavior

* n/a

## Who

* n/a

## References

* n/a

**Comment by Gursimran07316** [comment]
i have this issue while creating a react-app can anyone please tell me how to fix that
