### ISSUE TITLE
No matching version found for @babel/helper-validator-identifier@^7.9.5

### ISSUE THREAD

**Issue by munjakarnakar** [npm/cli#1127]
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/helper-validator-identifier@^7.9.5
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@babel/types'
npm ERR! notarget

**Comment by epitomz** [comment]
Any update on this?
