### ISSUE TITLE
Unable to install grunt cypress

### ISSUE THREAD

**Issue by ajay4250** [npm/cli#1130]
I am trying to run my cypress tests using grunt and I came across grunt cypress

When I run npm install grunt-cypress cypress --save-dev

I get this following error:

> grunt-cypress@1.1.2 postinstall C:\workspace\eventManagementCypressTests\main\node_modules\grunt-cypress
> ./scripts/postinstall.js

'.' is not recognized as an internal or external command,
operable program or batch file.
npm WARN grunt-copy@0.1.0 requires a peer of grunt@~0.4.2 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grunt-cypress@1.1.2 postinstall: `./scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grunt-cypress@1.1.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by bumper-yusuf-ozunlu** [comment]
Same issue
