### ISSUE TITLE
[BUG] Non-helpful error message when running npm install

### ISSUE THREAD

**Issue by topaztee** [npm/cli#1136]
# What / Why
Ran `npm install` and received this message
`Unhandled rejection Error: Invalid package name "_bin": name cannot start with an underscore`

I name the package name `some-other-thing` not `_bin` like the message showed.

## When
running npm install with a package name that includes an underscore

the error message should have shown the package name i set it to instead of ` _bin`

**Comment by momchilov7** [comment]
hey folks I have this error somebody help me 
12:34:27.999 [error] gen_server riak_core_capability terminated with reason:\
no function clause matching orddict:fetch('riak@192.168.2.81', []) line 72
you can contact me here [diseño web](https://www.diseñoweb.expert)
appreciate your help thanks in advance

**Comment by DanielRuf** [comment]
@momchilov7 please open a new issue in the right project. This does not seem to be related to npm at all.

@topaztee please provide the npm version that you use.

**Comment by topaztee** [comment]
6.14.4
