### ISSUE TITLE
[BUG] Error installing react-scripts

### ISSUE THREAD

**Issue by ChaboCode** [npm/cli#1137]
# What / Why

I was installing the dependencies of a React project, and when it tries to install react-scripts, it throw an error

### Steps to Reproduce

The project is on this GitHub account, it's "upgraded-potato". I tried to run npm install on db_implementation branch. So:

- git clone https://gtihub.com/TheBesterCode/upgraded-potato.git
- cd upgraded-potato/client
- npm install

And this is the npm-debug file that npm generated due to the error
[npm-debug.log](https://github.com/npm/cli/files/4462961/npm-debug.log)

**Comment by DanielRuf** [comment]
Hi @TheBesterCode,

please try to upgrade npm to the latest available release to see if this improves / fixes this.

**Comment by ChaboCode** [comment]
Now it works. Thanks!

**Comment by DanielRuf** [comment]
Thanks for the feedback. Then please close the issue as this is resolved now.
