### ISSUE TITLE
[BUG] Cant install discord.js

### ISSUE THREAD

**Issue by reisxd** [npm/cli#1139]
When i want to install discord.js (npm install discord.js) 
It gives error

Logs:

**Comment by DanielRuf** [comment]
Hi @GramingFoxTeam,

this might be due to the space in the username.

Duplicate of #417

Please also move this long output to a gist or into a code block.

**Comment by GramingFoxTeam** [comment]
> Hi @GramingFoxTeam,
> 
> this might be due to the space in the username.
> 
> Duplicate of #417
> 
> Please also move this long output to a gist or into a code block.

Did you mean İbrahim Bozkurt
If its i will try to install other folder.
If it works i will close the issue.

**Comment by DanielRuf** [comment]
> C:\Users\İbrahim BOZKURT

This might be the problem.

**Comment by reisxd** [comment]
Ok it worked.Thanks!
