### ISSUE TITLE
[QUESTION] Any reason why npm run test is treated differently when it's not defined?

### ISSUE THREAD

**Issue by bentinata** [npm/cli#1153]
https://github.com/npm/cli/blob/656bce7dd0f9753a273912e803261ed246593924/lib/run-script.js#L141

**Comment by textbook** [comment]
`test` is a special case elsewhere, I guess this reflects that; it's also an input to the interactive [`init`](https://github.com/npm/cli/blob/656bce7dd0f9753a273912e803261ed246593924/lib/run-script.js#L141), for example, and set to `echo \"Error: no test specified\" && exit 1` by default (e.g. with `npm init -y`). It's a [built-in command](https://docs.npmjs.com/cli/test), whereas many of the other `run-scripts` will be custom.
