### ISSUE TITLE
[QUESTION] Cannot deprecate package

### ISSUE THREAD

**Issue by tstewart-klaudhaus** [npm/cli#1155]
I wish to deprecate `@klaudhaus/lit-up` as I have now been made an owner of the unscoped package name `lit-up` which I will use going forward.

There are 15 versions of `@klaudhaus/lit-up` but when I use any of the following commands, only the versions starting with 0.1.x are flagged as deprecated in the NPM web UI. How can I also deprecate the @latest version (1.0.0-beta-1) and several other previous 1.0.x versions?

Here's what I've tried:

```bash
npm deprecate @klaudhaus/lit-up "Please use unscoped module name lit-up instead"
npm deprecate @klaudhaus/lit-up@1.0.0-beta-1 "Please use unscoped module name lit-up instead"
npm deprecate @klaudhaus/lit-up@"*" "Please use unscoped module name lit-up instead"
```

Thanks for your help

**Comment by ghost** [comment]
I see that you only have one [undeprecated](npmjs.com/package/@klaudhaus/lit-up) version as indicated in the web UI, which points to the new repo.

I'm guessing you've resolved your issue. Can you post a resolution?

**Comment by tstewart-klaudhaus** [comment]
Yep it looks good now, maybe it took a while for a cache somewhere to refresh. I'll close the Github issue.

Many thanks
Tim
________________________________
