### ISSUE TITLE
npm ENOENT:can not create Development dependencies

### ISSUE THREAD

**Issue by chenjuexu** [npm/cli#1156]
Hi I want to use the popular JavaScript Linting tool eslint and I  called NPM as shown:

npm install eslint --save-dev
but something wrong like this:
![screen](https://user-images.githubusercontent.com/53376000/79366442-33040480-7f1a-11ea-9525-a263b451fdf6.png)

in the package.json,I could not find any script about dependencies between eslint and my app.
thanks very much

**Comment by ljharb** [comment]
Look in `devDependencies`.

You have to manually add a script like `"lint": "eslint ."` in the "scripts" section of package.json.

**Comment by chenjuexu** [comment]
@ljharb thanks ,done
