### ISSUE TITLE
[QUESTION] Do --cache and --no-cache options to `npm install` exist? What do they do?

### ISSUE THREAD

**Issue by spencerwilson-optimizely** [npm/cli#1159]
# What / Why

I see a `--cache` option to `npm install` referenced in the output of `npm cache clean`:
> $ npm cache clean
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead. On the other hand, if you're debugging an issue with the installer, you can use `npm install --cache /tmp/empty-cache` to use a temporary cache instead of nuking the actual one.

I see a `--no-cache` option referenced in https://github.com/npm/cli/issues/390.

Questions:

1. Do these options exist? What is their [stability](https://nodejs.org/api/documentation.html#documentation_stability_index)? (I know npm may not use the same system as Node.js—but roughly, maybe?)
2. What do they do?
3. Will they be documented? Presently `npm help install` doesn't mention the word "cache" _at all_. This seems like a big omission, as the effects of `npm install` are definitely impacted by cached state. If one isn't aware that there exists a cache, it can make debugging issues or "resetting" much more difficult to do.

## Where

* npm/cli

## Who

* n/a

## References

* Related to #390

**Comment by isaacs** [comment]
`--cache` is how you can set the folder to use as a cache.  `--no-cache` is nonsense, it sets your cache folder to the string `false` (as the user reporting the problem in #390 was finding).

`npm help 7 config`

Then search for `prefer-online`, `prefer-offline`, and `offline`.  They're very stable, at least through npm versions 5, 6, and 7.

**Comment by ljharb** [comment]
@isaacs i mean, to be fair, `--no-cache` should be an error if `--cache` isn't a boolean option :-)

**Comment by spencerwilson-optimizely** [comment]
> `--cache` is how you can set the folder to use as a cache.

Yep, that's implied by the `npm cache clean` ERR message. My question was: If it's a stable and supported option, should it be documented at `npm help install`?

I'm unsure which part of the original questions the `prefer-online` et al. references were intended to help answer; they don't appear to have much to do directly with the `--cache` string-valued option.

In any event, thanks for the response! This will at least help the next person that googles it.

**Comment by isaacs** [comment]
I mean, if `npm install --no-cache` is intended to mean "install without using data from the cache", then the correct way to express that is `npm install --prefer-online`.  There is no way for npm to operate without having any cache at all, but `--prefer-online` tells it to always re-check responses against the registry, rather than using a cached value.

**Comment by isaacs** [comment]
So, @spencerwilson-optimizely, is your request here for links in the documentation from `npm help install` to the relevant caching options?

**Comment by spencerwilson-optimizely** [comment]
I think that'd be valuable, yes! I know at least I got utility out of `npm install --cache` via the trick of giving it e.g. /tmp/empty-cache. That option, alongside `--prefer-{online,offline}`, I'm sure there are good use cases for them all.

To be really explicit, my original question sprang from the premise that something that isn't documented ought not be relied upon in any serious capacity. My interest was piqued when there was undocumented `npm` functionality—`--cache <path>`—whose use was being encouraged by the `cache clean` error message. I'm unsure how common that "if it's not documented it's not reliable" sentiment is, though; if it's unusually strict then I can see how this question might have been a bit puzzling.

**Comment by milahu** [comment]
@ljharb said

> @isaacs i mean, to be fair, `--no-cache` should be an error if `--cache` isn't a boolean option :-)

yes, `npm run` should throw an error on unrecognized options

otherwise this silently fails

```sh
npm run test-script --pass-this-to-test-script

# .... should be
npm run test-script -- --pass-this-to-test-script
```
<details>

package.json

```json
{
  "scripts": {
    "test-script": "echo argv = \"$0\" \"$@\""
  }
}
```
results

```sh
$ npm run test-script --pass-this-to-test-script
argv = sh

$ npm run test-script -- --pass-this-to-test-script
argv = sh --pass-this-to-test-script
```

</details>

**Comment by AndrewEastwood** [comment]
seems `--no-cache` is making a folder named `false`. so weird

**Comment by isaacs** [comment]
> seems --no-cache is making a folder named false. so weird

It is.

The `cache` config option expects a string, so anything it finds gets stringified. The argument parser turns any `--no-{option}` into `{ [option]: false }` in the result. So you end up with `String(false)` which is of course, `'false'`.

A better approach would be to define the type of each config option explicitly, and raise an error (or ignore it with a warning) if the option doesn't match the expected type. But, any improvement is a change, and that might be somewhat disruptive, so would have to be approached carefully.

**Comment by eabase** [comment]
BUMP! 

What happened to the `--clean` switch? 
Where is the documentation?
