### ISSUE TITLE
npm ERR! cb() never called! <npm install --global --production windows-build-tools>

### ISSUE THREAD

**Issue by vipinrv** [npm/cli#1164]
npm WARN tar ENOENT: no such file or directory, open 'C:\Program Files\nodejs\node_modules\.staging\sshpk-93e12b45\lib\identity.js'
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Vipin\AppData\Roaming\npm-cache\_logs\2020-04-16T05_56_54_077Z-debug.log

**Comment by DanielRuf** [comment]
Please try to force-install the dependencies with `npm i --force`.

Also see #417.
