### ISSUE TITLE
[BUG] cb() never called

### ISSUE THREAD

**Issue by seezee** [npm/cli#1174]
# What / Why
I received this error when exiting. See debug log.
[2020-04-17T20_07_16_604Z-debug.log](https://github.com/npm/cli/files/4495059/2020-04-17T20_07_16_604Z-debug.log)

```
npm ERR! cb() never called!

npm ERR! This is an error with npm itself.
```

## When

Exiting a routine that uses sass-build, compile-sass, prefix-css, combine-media, & compress-css

## Where
* n/a

## How
* n/a

### Current Behavior

* n/a

### Steps to Reproduce

* n/a

### Expected Behavior

* n/a

## Who

* n/a

## References

* n/a

**Comment by isaacs** [comment]
This is fixed in teh latest npm release.  Please update.

**Comment by l01391313** [comment]
but use the latest npm still has the error
