### ISSUE TITLE
Package.json with dependencies "latest" does not download latest

### ISSUE THREAD

**Issue by MaddyTryToCode** [npm/cli#1204]
**npm version**: 3.10.10
**Scenario**: I uploaded a jar to my private npm repo with version 1.2.0. Now for some reason, I added a new jar with version 1.1.0. 
My package.json has a dependency "XYZ": "latest". But it downloads 1.1.0? Is this a bug or I am doing something not right? I was expecting it to download 1.2.0 always.

**Comment by ljharb** [comment]
what's a jar? npm deals in tarballs.

"latest" is a dist-tag; a version has to be explicitly set to it. When backporting (as you've done), it's easy to accidentally set the older version as "latest".

I'd suggest using https://npmjs.com/safe-publish-latest to avoid this in the future; to fix this now, run `npm dist-tag add $pkg@1.2.0 latest`

**Comment by MaddyTryToCode** [comment]
Sorry my bad, I meant tarballs (and not jars).

**Comment by MadhuriGurumurthy11** [comment]
I tried to add safe-publish-latest and I get the following error.
`npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.12: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
> dependency-name@1.4.2 prepublish /home/node
> safe-publish-latest
sh: 1: safe-publish-latest: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! dependency-name@1.4.2 prepublish: `safe-publish-latest`
npm ERR! spawn ENOENT

**Comment by MaddyTryToCode** [comment]
That solution works. Thanks a lot.
