### ISSUE TITLE
Can we do npm-install without transitive dependencies?

### ISSUE THREAD

**Issue by MaddyTryToCode** [npm/cli#1205]
I have a scenario where I want to download a dependency (dependency is a react app) through npm install without downloading any of its transitive dependencies.

`"dependencies": {
    "my-react-app": "latest"
  }`
and under node_modules I am expecting only my-react-app. Is this possible?

**Comment by ljharb** [comment]
Not that I know of, nor does it make any sense to me. If you depend on a thing, why would you want it in a broken state (missing its own deps)?

**Comment by MaddyTryToCode** [comment]
So I took the react-app alone, deployed the app, and it works. So I didn't understand why the transitive dependencies are required.  I am beginner in react. But I am assuming react bundles the required dependencies when we build the app.

So there is no way to avoid transitive dependencies?

**Comment by ljharb** [comment]
not that i know of.
