### ISSUE TITLE
npm install expo-cli

### ISSUE THREAD

**Issue by Murunb1** [npm/cli#1212]
C:\Users\User>npm install expo-cli
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated joi@14.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2020-04-27T15_18_33_207Z-debug.log

C:\Users\User>npm cache clear --force
npm WARN using --force I sure hope you know what you are doing.

C:\Users\User>npm install expo-cli
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2020-04-27T15_20_24_774Z-debug.log

**Comment by lakshyatyagi24** [comment]
Try `npm i expo-cli`

**Comment by yash03112000** [comment]
having  same issue tried npm i expo-cli too

**Comment by ezengold** [comment]
Try to install using the **current LTS version of Node**. I removed node npm and npx files in `/usr/bin` directory and downloaded the LTS v12 package that I installed by extracting the compressed file in `/usr/local/lib/nodejs`.
And then I added the directory to the PATH and tried `npm version` in commande line.

Now you can retry to install expo-cli using : `npm install --global expo-cli`
