### ISSUE TITLE
npm ci used with engine-strict true doesn't work as npm install

### ISSUE THREAD

**Issue by uittorio** [npm/cli#1219]
# What / Why

> When using npm ci in combination with engine-strict true in the npm config settings I was expecting to fail if I was using an outdated version of node or npm

## Steps to Reproduce

  * Given I've created a file .npmrc with this content next to the package.json
```
engine-strict = true
```
  * And I have an engine section in the package.json
```
"engines": {
        "node": ">=12.0.0"
    }
```
  * And I'm using node 10.X.X
  * When run npm i
  * Then I receive an error
```
 Unsupported engine for repo-name@0.0.1: wanted: {"node":">=12.0.0"} (current: {"node":"10.17.0","npm":"6.11.3"})
```

* When I run npm ci
* I don't receive the error

### Expected Behavior
* When running npm ci with engine strict true it should error when using a version that is not in range of the strict rules

**Comment by spjtls9** [comment]
Is this closed with a resolution? I'm running into the same issue.

**Comment by pniederlag** [comment]
Why was this ticket closed? I can also confirm the issue, engines and config engine-strict are ignored when running npm ci. That's not what I'd expect.

**Comment by Qvatra** [comment]
confirm this as well. Can the reason of the ticket being closed be provided please?

**Comment by ljharb** [comment]
Is this still an issue on npm 7 latest?

**Comment by satyanash** [comment]
Yep, can confirm that this is an issue.
Only `npm install` seems to respect `engines` inside `package.json` and `engine-strict` in the `.npmrc`.
`npm ci` seems to happily move on with installing it even if there is a node version mismatch.

**Comment by Sufiane** [comment]
Do we have an ETA about this ?

**Comment by black-snow** [comment]
Ran into this as well. I'm puzzled why this has been open for so long and with so little attention o.Ò

**Comment by mcelestini** [comment]
Running into this as well, `npm i` enforces an engine version but `npm ci` doesn't. This is especially frustrating since we commit our `package-lock` files and encourage new developers to use `npm ci` so they don't overwrite the `package-lock` on every install

**Comment by rodmax** [comment]
The same problem as described in comment above https://github.com/npm/cli/issues/1219#issuecomment-962009210

We force to use `npm ci` in all our projects
and now got the issue with no possibility to check engine.

I will be grateful if someone from community updates the status. Thanks

**Comment by ruyadorno** [comment]
I can't reproduce this problem, I tried with both installing a [dep with an impossible to satisfy node.js version](https://www.npmjs.com/package/unnatainable-engines-node) and also tweaking the root `package.json` `"engines.node"` value and in both cases `npm ci` behaves exactly the same as `npm install` (exits with an error code), here's an overview of my quick reproduction setup:

```
$ cat package.json
{
  "name": "ci-engine-strict",
  "version": "1.0.0",
  "engines": {
    "node": ">=99999"
  }
}

$ cat .npmrc
engine-strict=true

$ npm install
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: ci-engine-strict@1.0.0
npm ERR! notsup Not compatible with your version of node/npm: ci-engine-strict@1.0.0
npm ERR! notsup Required: {"node":">=99999"}
npm ERR! notsup Actual:   {"npm":"8.1.2","node":"v16.13.2"}

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ruyadorno/.npm/_logs/2022-01-24T22_09_40_067Z-debug.log

$ npm ci
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: ci-engine-strict@1.0.0
npm ERR! notsup Not compatible with your version of node/npm: ci-engine-strict@1.0.0
npm ERR! notsup Required: {"node":">=99999"}
npm ERR! notsup Actual:   {"npm":"8.1.2","node":"v16.13.2"}

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ruyadorno/.npm/_logs/2022-01-24T22_10_06_550Z-debug.log
```

If anyone is still affected by this issue, it would be super helpful if you can provide more info about your setup and specially appreciated if you can provide a minimal reproduction such as mine just above.

**Comment by ankon** [comment]
@ruyadorno one note: I believe you have a `package-lock.json` available, which wouldn't have been there if you had `engine-strict=true` before running `npm install` for the first time. 

I think what happens for us is actually related, and it has to do with gradually moving towards the problem. In other words, it might well be that this issue had been fixed.

```
$ npm -v
8.3.0

$ cat .npmrc package.json 
engine-strict=true
{
  "name": "ci-engine-strict",
  "version": "1.0.0",
  "engines": {
    "npm": ">=8.3.0"
  }
}

$ npm install

up to date, audited 1 package in 173ms

found 0 vulnerabilities

$ cat package-lock.json 
{
  "name": "ci-engine-strict",
  "version": "1.0.0",
  "lockfileVersion": 2,
  "requires": true,
  "packages": {
    "": {
      "name": "ci-engine-strict",
      "version": "1.0.0",
      "engines": {
        "npm": ">=8.3.0"
      }
    }
  }
}
```

So at this point everything is fine, and `npm ci` will work. Of course, I added the restriction, so I want an _older_ npm to barf.

```sh
$ npm -v
7.0.14

$ npm ci

up to date in 146ms

found 0 vulnerabilities
```

Not good. But, that's an old version, so maybe the issue had been there at one point, and fixed since then. Counter-test with a newer npm:

```
$ npm -v
8.3.1

$ npm install

up to date, audited 1 package in 171ms

found 0 vulnerabilities

$ cat package.json package-lock.json 
{
  "name": "ci-engine-strict",
  "version": "1.0.0",
  "engines": {
    "npm": ">=8.3.1"
  }
}
{
  "name": "ci-engine-strict",
  "version": "1.0.0",
  "lockfileVersion": 2,
  "requires": true,
  "packages": {
    "": {
      "name": "ci-engine-strict",
      "version": "1.0.0",
      "engines": {
        "npm": ">=8.3.1"
      }
    }
  }
}
```

So, back to npm 8.3.0 to check:

```
$ npm -v
8.3.0

$ npm ci
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: ci-engine-strict@1.0.0
npm ERR! notsup Not compatible with your version of node/npm: ci-engine-strict@1.0.0
npm ERR! notsup Required: {"npm":">=8.3.1"}
npm ERR! notsup Actual:   {"npm":"8.3.0","node":"v17.3.1"}

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/andreas/.npm/_logs/2022-01-25T10_06_47_141Z-debug-0.log
```

So maybe this indeed has been fixed since, but still affects previous versions?

**Comment by ruyadorno** [comment]
Thank you so much for testing this all out @ankon!

In case anyone runs into a similar problem again, please open a new issue with a reproduction and we can look into it 😊
