### ISSUE TITLE
[BUG] <title> cb() never called

### ISSUE THREAD

**Issue by Jam-zed** [npm/cli#1231]
sudo npm install -g @aws-amplify/cli
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

[2020-05-01T08_48_57_157Z-debug.log](https://github.com/npm/cli/files/4563135/2020-05-01T08_48_57_157Z-debug.log)

**Comment by estubmo** [comment]
Had this error too running npm 6.14.4. Solved by updating npm to 6.14.5.

**Comment by mikeyc-mikeydo** [comment]
Encountered this error too while installing a react app.
Also solved by updating npm:

`npm install -g npm`
