### ISSUE TITLE
[QUESTION] How Can I remove my account?

### ISSUE THREAD

**Issue by UedaTakeyuki** [npm/cli#1237]
# What / Why
I've sing up to npmjs.com by misunderstanding and want to delete this account.
But I can't fine appropriate UI to delete account.
Would you please show me the appropriate URL to delete my account? Thank you.

**Comment by jamime** [comment]
https://docs.npmjs.com/deleting-your-npm-user-account

**Comment by UedaTakeyuki** [comment]
Thank you!
