### ISSUE TITLE
[BUG] npm ERR! cb() never called!

### ISSUE THREAD

**Issue by sbkWebDev** [npm/cli#1239]
# What / Why
I ran "npm install command"

## Where
![Screenshot from 2020-05-04 13-38-33](https://user-images.githubusercontent.com/61972636/80946858-a196fc80-8e0c-11ea-80f1-d5e3c3d1dd9b.png)

### Current Behavior

You may see the error in image

### Steps to Reproduce

-> Run "npm install"

### Expected Behavior

-> Modules must be installed without any errors

**Comment by soczysty7** [comment]
had the same issue today after doing npm cache clean --force and running npm install
