### ISSUE TITLE
[QUESTION] loglevel for `npm ci`?

### ISSUE THREAD

**Issue by DaveShuckerow** [npm/cli#1246]
Is there an equivalent to `npm install --silent` for `npm ci`?  Searching the docs I'm not able to find any params for this command.

To make CI logs easier to read, I'm interested in setting `npm ci` up so that it does not output anything except when a build fails.

Thanks very much!

**Comment by ljharb** [comment]
`npm ci > /dev/null`?

**Comment by DaveShuckerow** [comment]
> `npm ci > /dev/null`?

That does build silently.  I was hesitant about that in case npm ci for some reason generated error-relevant output to stdout.

If there's no such caveats, I'm fine to close with `npm ci > /dev/null` as a resolution.

**Comment by ljharb** [comment]
If it did that'd be a bug; error-relevant output belongs on stderr.
