### ISSUE TITLE
npm not installing firebase 

### ISSUE THREAD

**Issue by OmairSohail** [npm/cli#1262]
# What / Why
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\myname\AppData\Roaming\npm-cache\_logs\2020-05-08T13_37_00_739Z-debug.log 
> n/a

## When

  * Whenever i try to install firebase and firebase tools , by running vs code as administrator
  

* n/a

## Where

  * npm itself

![NPm Error](https://user-images.githubusercontent.com/52859052/81412177-e7c9c400-915c-11ea-8af4-1a0555c81cfa.PNG)

**Comment by sahilraj-developer** [comment]
Same problem , what is the solution .
did you solve it
