### ISSUE TITLE
cb() never called!

### ISSUE THREAD

**Issue by Saurabh-ux-92199** [npm/cli#1272]
Creating a new React app in E:\myapp.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2020-05-10T11_24_52_824Z-debug.log

Aborting installation.
  npm install --save --save-exact --loglevel error react react-dom react-scripts cra-template has failed.

Deleting generated file... package.json
Deleting myapp/ from E:\
Done.

**Comment by umaryusuf11** [comment]
Yes I am getting the same error. Trying to run
`npm install --global expo-cli`

**Comment by ivonnegattringer** [comment]
I got the same error.....

**Comment by vchewjs** [comment]
I got the same error.....

**Comment by vchewjs** [comment]
$ npm install --global expo-cli
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @expo/config@3.2.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'expo-cli'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-05-11T16_37_58_136Z-debug.log

**Comment by vksgautam1** [comment]
Getting same error for react native
![IMG_20200512_150657](https://user-images.githubusercontent.com/4745491/81681537-f58b8c00-9471-11ea-9962-c77527ee2e79.jpg)

**Comment by visak-se** [comment]
Getting same error for ng new and npm install npm@latest -g

**Comment by alecStewart1** [comment]
Duplicate issues for this error it seems.

Here's the log file I have for this issue (though it tells you effectively nothing)

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'i', '-g', 'pnpm' ]
2 info using npm@6.13.1
3 info using node@v13.2.0
4 verbose npm-session 8d92d997c820c4bd
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 timing npm Completed in 715ms
8 error cb() never called!
9 error This is an error with npm itself. Please report this error at:
10 error <https://npm.community>
```

**Comment by alecStewart1** [comment]
_Allegedly_ some people have seen the issue fixed running `npm cache clean` (or with `--force` as well). That has not fixed the issue for me.

**Comment by martinlockett** [comment]
> 5706 timing npm Completed in 20364ms
> 5707 error cb() never called!
> 5708 error This is an error with npm itself. Please report this error at:
> 5709 error <https://npm.community>

`npm cache verify` fixed it for me

**Comment by visak-se** [comment]
> Getting same error for ng new and npm install npm@latest -g

This fixed it for me:
Uninstalled Node.js
Reboot
Installed latest stable Node.js
Reboot
