### ISSUE TITLE
Trying to install NPM on my Windows PC.  NodeJS is version 12.16.3, but installer says to get newer version.  This was the newest.

### ISSUE THREAD

**Issue by skywatchbob** [npm/cli#1278]
# What / Why
When attempting to install NPM on my Windows PC (Windows 10 Pro) I get an error that I need to get a newer version of NodeJS, although I just downloaded the latest version (12.16.3).  Does anyone know if there are issues with this version of NodeJS?  How do I install NPM?
> n/a

**Comment by ljharb** [comment]
npm only comes with node; how are you trying to install it? (`npm install -g npm` is how you'd update it)

**Comment by skywatchbob** [comment]
I am taking a class and the instructor had me do an upgrade to v. 5.5.1 but that wasn't working.  I tried upgrading to the latest and this is what I got.
![image](https://user-images.githubusercontent.com/62062987/81742615-ff0ef700-9465-11ea-892c-1f67b8ce3ee9.png)

**Comment by ljharb** [comment]
@skywatchbob that's because that's not an upgrade; npm 5 is very old. your instructor isn't giving you good instructions.

**Comment by skywatchbob** [comment]
The upgrade command isn't working now.  What can I do to fix this?

**Comment by ljharb** [comment]
You'll have to reinstall node. By replacing your working/new npm with an old/broken one, you've broken your copy of node.

**Comment by skywatchbob** [comment]
I have uninstalled node and re-installed it, but when I check npm, it remains at version 5.5.1.
How do I get rid of that version and get the installer to use what is in the Node package?

**Comment by ljharb** [comment]
I’m not sure; make sure both node and npm are completely uninstalled before reinstalling node.

**Comment by skywatchbob** [comment]
Looks like I finally fixed it.  Had to find the npm folder in C:/users/(user name)/AppData/ and delete the npm folders that remain after uninstalling node.  Once this was done I re-installed node and got the new version of npm. Thanks for your help.
