### ISSUE TITLE
[BUG] npm converts tabs to spaces if used in package.json

### ISSUE THREAD

**Issue by Newbytee** [npm/cli#1285]
# What / Why

If one uses tabs to indent their package.json file, npm will overwrite these tabs with spaces. It does not warn you that you used tabs instead of spaces, and [the documentation for package.json](https://docs.npmjs.com/files/package.json) does not mention how it should be indented.

## When

* When an npm command is issued that mutates package.json (for example, installing a package).

## Where

* n/a

### Current Behavior

* npm will replace tabs with spaces as it mutates package.json.

### Steps to Reproduce

* Write a skeleton package.json using tabs for indentation
* Install a package
* Observe that the tabs have been replaced by spaces (1 space for each tab)

### Expected Behavior

* npm sees that package.json is indented with tabs and continues to indent with tabs.

## Who

* n/a

## References

* n/a

**Comment by ljharb** [comment]
What version of npm are you using? In my experience this long-standing bug was fixed in npm 6.

**Comment by Newbytee** [comment]
Hmm, seems I can't reproduce it now. Maybe I forgot some space somewhere. 

For the record, I'm using npm 6.14.4.
