### ISSUE TITLE
[BUG] Website not available

### ISSUE THREAD

**Issue by RubenVerg** [npm/cli#1301]
> Sorry for posting here, but i can't find a place for reporting website errors while the website is down

# What / Why

> Any page of the website returns a JSON saying `{"error":"Service Unavailable"}`

## When

* When I opened the NPM website (10.00 am CET, 2020.5.15)

## Where

* <https://npmjs.com>
* Latest Chrome Canary release as of now

### Current Behavior

* n/a

### Steps to Reproduce

* navigate to <https://npmjs.com>

### Expected Behavior

* It should open the website, like it has always done before.

## Who

* n/a

## References

* n/a

**Comment by BubbleBear** [comment]
same here.

**Comment by m-nathani** [comment]
same here getting:

npm ERR! code E503
npm ERR! 503 Service Unavailable - PUT https://registry.npmjs.org/@umai%2fshop-dashboard - Service Unavailable

**Comment by Boelroy** [comment]
I got same error when I publish the package

>npm ERR! code E503
>npm ERR! 503 Service Unavailable - PUT https://registry.npmjs.org/@alicloud%2fconsole-os->react-portal - Service Unavailable

**Comment by RubenVerg** [comment]
(works now)
