### ISSUE TITLE
[BUG] Cannot read property 'match' of undefined when inflating shrinkwrap 

### ISSUE THREAD

**Issue by daxeh** [npm/cli#1322]
# What / Why

The title error occurs when executing `npm install` command. The cause is identified in recursive function `inflateShrinkwrap`  returning an external function call to `inflatableChild` (side effect) in a Promise.each() iteration.

Error: **TypeError: Cannot read property 'match' of undefined**
At: **tarballToVersion (.../npm/lib/install/inflate-shrinkwrap.js:87:20)**

 
## When

Undeternined

## Where

npm public registry
npm/lib/install/inflate-shrinkwrap.js

## How

Promise call side effect error  

### Current Behavior

In `inflateShrinkwrap` when iterating dependency tree to resolve diffs in Promise.each. Instead of resolving within scope, the recursion returns an external dependency, `inflatableChild` causing this side effect. 

### Steps to Reproduce

$ npx create-react-app project

```
{
    ...
   "dependencies": {
        "@material-ui/core": "^4.9.14",
        "@material-ui/icons": "^4.9.1",
        "@testing-library/jest-dom": "^4.2.4",
        "@testing-library/react": "^9.5.0",
        "@testing-library/user-event": "^7.2.1",
        "core-js": "^3.6.5",
        "react": "^16.13.1",
        "react-dom": "^16.13.1",
        "react-scripts": "3.4.1"
    },
    ...
    "devDependencies": {
        "@babel/cli": "^7.8.4",
        "@babel/core": "^7.9.6",
        "@babel/preset-env": "^7.9.6",
        "@types/jest": "^25.2.2",
        "babel-plugin-styled-components": "^1.10.7",
        "standard": "^14.3.4",
        "styled-components": "^5.1.0"
    },
    "peerDependencies": {
        "typescript": "^2.8.0"
    }
    ...
}
```

### Expected Behavior

npm install|audit executes successfully

**Comment by sscholle** [comment]
Got the same error here: except i'm using a specific package that is causing the issue: https://github.com/npm/cli/issues/1610
