### ISSUE TITLE
Semver cannot be used with Github gists

### ISSUE THREAD

**Issue by cyberbiont** [npm/cli#1329]
[Official documentation](https://github.com/npm/cli/blob/latest/docs/content/cli-commands/npm-install.md) implies that one can use semver syntax with gists
`npm install gist:[<githubname>/]<gistID>[#<commit-ish>|#semver:<semver>]:`

It doesn't seem to be true.

**Comment by cyberbiont** [comment]
github-tools/github#610

**Comment by ljharb** [comment]
gists are just GitHub repos, so I’m not sure why it wouldn’t work.

**Comment by cyberbiont** [comment]
You are right.
The problem is that Github for some reason doesn't provide a possibility to tag the gist though web interface, like it does for regular repos. It seems to work though if I clone the gist locally, tag a commit and push it back on Github, then I am able to update with npm install. Very inconvenient, but I think that this is not npm's problem, so i will close it.
