### ISSUE TITLE
[BUG] npm audit generates invalid payload with deduped git dependencies

### ISSUE THREAD

**Issue by wraithgar** [npm/cli#1334]
# What / Why
When a package.json file has a package listed in its `dependencies` that has a git link for its version (i.e. `github:npm/node-semver`), it will obfuscate that package when it sends the payload for npm audit.

There are certain cases where the cli builds a payload from this scenario that is unparseable as a logical tree.  Those cases are when the version in the package being installed from a git url falls under the same semver range as another subdependency w/ the same package name.  It will dedupe, but the package that requires this git-referenced package will contain the real package name, and not the obfuscated one.

## Where
npm public registry

### Current Behavior
npm audit fails

### Steps to Reproduce
```sh
$ mkdir dummy
$ cd dummy
$ npm init -y
$ npm i jsonwebtoken
$ npm i github:npm/node-semver#v5.7.1
$ npm audit
npm ERR! code ENOAUDIT
```

The payload sent to npm audit contains the following (I cleaned out non-relevant info)

```json
{
  "name": "dummy",
  "version": "1.0.0",
  "requires": {
    "jsonwebtoken": "^8.5.1",
    "8eec50f3eb0297f3a62dc27d42359ae94e3586a1591c60117ee90eb0cf0aa79c": "git+ssh://9f8d00a70e7263d1f27f1ef21a0029806308383b361bacf01d0547b79cb3d8fa"
  },
  "dependencies": {
    "jsonwebtoken": {
      "version": "8.5.1",
      "integrity": "sha512-XjwVfRS6jTMsqYs0EsuJ4LGxXV14zQybNd4L2r0UvbVnSF9Af8x7p5MzbJ90Ioz/9TI41/hTCvznF/loiSzn8w==",
      "requires": {
        "jws": "^3.2.2",
        "lodash.includes": "^4.3.0",
        "lodash.isboolean": "^3.0.3",
        "lodash.isinteger": "^4.0.4",
        "lodash.isnumber": "^3.0.3",
        "lodash.isplainobject": "^4.0.6",
        "lodash.isstring": "^4.0.1",
        "lodash.once": "^4.0.0",
        "ms": "^2.1.1",
        "semver": "^5.6.0"
      }
    },
    "8eec50f3eb0297f3a62dc27d42359ae94e3586a1591c60117ee90eb0cf0aa79c": {
      "version": "git+ssh://7ebe36194968fce20b8afafba1ef9609023b6705199ad5b3518db7735a7961b8"
    }
  }
```

As you can see, `jsonwebtoken` lists `semver` as a dependency, but `semver` is not in the tree anywhere, it was obfuscated to a hash because it's not a public npm package, it's from a git url.

### Expected Behavior
npm audit should succeed

**Comment by isaacs** [comment]
Fixed in v7 already.  Changing the redacting of git deps would be a breaking change.  As you know, I agree that the choice was regrettable.
