### ISSUE TITLE
[FEATURE] Add field "preferDev" to package.json

### ISSUE THREAD

**Issue by Ginden** [npm/cli#1337]
# What / Why

Certain packages are used almost exclusively for development. Eg. `typescript`, `tslint` etc. It's usually a mistake to add them as normal dependencies.

I suggest to add field "preferDev": boolean (with default `false`) to package.json. User can't install `preferDev` package without specyfing `--production` flag.

## When
* On adding new package

## Where
* npm/cli

### Current Behavior

Packages are installed as `dependencies` by default.

### Expected Behavior

To choose:
* Warn user about installing `preferDev` package as production one.
* Ask for confirmation if installing `preferDev` package as production one
* Require `--production` flag explicitly set to install `preferDev` package as production one

**Comment by ljharb** [comment]
Please file this as an RFC.

**Comment by Ginden** [comment]
@ljharb Where?

**Comment by ljharb** [comment]
https://github.com/npm/rfcs

**Comment by ruyadorno** [comment]
Thanks @Ginden I see you submitted an RFC. Let's follow up with the discussion over there and I'll close this issue 😊
