### ISSUE TITLE
[FEATURE] npm fund --depth=0

### ISSUE THREAD

**Issue by fishcharlie** [npm/cli#1345]
# What / Why

> npm cli should support `npm fund --depth=0` to only get funding information of direct dependencies

## When
* `npm fund --depth=0`

## Where
* n/a

### Current Behavior
* Prints funding information for all dependencies

### Expected Behavior
* Print only funding information for direct dependencies (not nested dependencies)

## Who
* n/a

## References
* n/a

**Comment by ljharb** [comment]
Please file this on https://github.com/npm/rfcs/

**Comment by fishcharlie** [comment]
https://github.com/npm/rfcs/pull/152
