### ISSUE TITLE
[QUESTION] Not able to update tag name

### ISSUE THREAD

**Issue by vinamramunot-tech** [npm/cli#1367]
# Issue

<img width="746" alt="Screen Shot 2020-06-02 at 12 22 12 AM" src="https://user-images.githubusercontent.com/56406734/83443555-92d15300-a467-11ea-9b78-a2b7501b885e.png">
In this image, I am facing the error of updating the tag
I am working on the DIST TAG of the "how-to-npm" path
[https://nodeschool.io/]
<hr>
Things I already did:
1. uploaded to git
2. npm publish
3. I haven't published anywhere but I have uploaded to the git

**Comment by ljharb** [comment]
What is `localhost:15443`? do you have a private registry set up?

**Comment by vinamramunot-tech** [comment]
@ljharb I am not uploading it anywhere, just trying to add another tag. How can I check if I have a private registry setup?

**Comment by ljharb** [comment]
@vinamramunot-tech what does `npm config get registry` say? Do you have `registry` in `~/.npmrc`, or `publishConfig` set in package.json?

**Comment by vinamramunot-tech** [comment]
### npm config get registry
http://localhost:15443/
### registry in ~/.npmrc
file is empty
### publishConfig
I don't see that option in package.json

@ljharb

**Comment by ljharb** [comment]
Do you have that URL in your env vars, then? Perhaps one called “registry” or “NPM_CONFIG_REGISTRY”?

**Comment by vinamramunot-tech** [comment]
I do not have a URL in the env vars. I also do not have a registry for the "NPM_CONFIG_REGISTRY". Just to clarify here, by "env vars" you mean env from the terminal output right? Should I set a private registry before if I am testing my module? @ljharb thanks!

**Comment by ljharb** [comment]
Yes, i mean `env`. You should *not* need a private registry.

The default registry is `https://registry.npmjs.org/` - that other URL has to come from somewhere on your system, either an env var, an `.npmrc` file (at any level), or in your `package.json`.

**Comment by vinamramunot-tech** [comment]
@ljharb Ohkay, I'll work on that. Will keep you updated. I'll watch a video and restart with making the npm package from scratch. Should I close this issue for now? Is there any other way to contact you @ljharb without re-opening an issue here?

**Comment by ljharb** [comment]
You're welcome to ping me here, whether you close the issue or not.
