### ISSUE TITLE
[BUG] `npm link` deleted entire CWD after failing due to permission issue. 

### ISSUE THREAD

**Issue by justintaddei** [npm/cli#1394]
# What / Why

I ran `npm link` from the _VS Code integrated terminal_. The command failed because it was not running with elevated privileges (as expected). Immediately after the command failed I watched as every file and folder was deleted from the working directory (I had a backup from ~5 minutes before this so luckily I didn't really lose much). Below is a screenshot of the terminal and I have attached the relevant `.log` file. I have also confirmed this is happening every time (I restored the files and ran the command again... same problem).

[2020-06-04T18_51_10_636Z-debug.log](https://github.com/npm/cli/files/4732244/2020-06-04T18_51_10_636Z-debug.log)

![image](https://user-images.githubusercontent.com/16705594/83800393-ff696f00-a66c-11ea-8c99-4eec16ff35c2.png)

## When

* Immediately following the `npm link` command when run with insufficient permissions.

## Where

* Source folder of [npm/v-shared-element](https://www.npmjs.com/package/v-shared-element) (On Windows 10 19041.264)

### Current Behavior

* It deletes the current directory and gives you a heart attack.

### Steps to Reproduce

* Unknown. It doesn't happen in my other projects.

### Expected Behavior

* Fail without deleting everything.
![image](https://user-images.githubusercontent.com/16705594/83801815-62f49c00-a66f-11ea-95f9-3fa1cb31687c.png)

**Comment by isaacs** [comment]
Can you share the debug.log file it generated?

Also, copying and pasting the actual terminal output is much more helpful for others, so that they can find the error message in searches.  Screenshots aren't as accessible in that way.

**Comment by isaacs** [comment]
Also, what is the current state of `C:\Program Files\nodejs\node_mules\v-shared-element`?  Is it a junction or symlink of any sort?

My gut guess is that somehow it's already linked to `C:\dev\npm\v-shared-element`, but not in a way that npm can properly determine.  If that's the case, then when it tries to `rmdir` the existing global dir, it looks like just a normal directory.  So it removes all the contents (which works, because you own those, and you get a heart attack as it succeeds without issue), and then when it tries to `rmdir` the now-empty directory, it gets the `EPERM`.

**Comment by justintaddei** [comment]
I attached the log file but I suppose I should've just included the contents. Sorry about that. Here it is:

```cmd
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\justi\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'link'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.16.3
4 verbose linkPkg C:\dev\npm\v-shared-element
5 silly gently link deleting existing link forcefully {
5 silly gently link   link: 'C:\\Program Files\\nodejs\\node_modules\\v-shared-element',
5 silly gently link   target: 'C:\\dev\\npm\\v-shared-element',
5 silly gently link   force: false,
5 silly gently link   gently: false,
5 silly gently link   clobberLinkGently: undefined
5 silly gently link }
6 verbose stack Error: EPERM: operation not permitted, rmdir 'C:\Program Files\nodejs\node_modules\v-shared-element'
7 verbose cwd C:\dev\npm\v-shared-element
8 verbose Windows_NT 10.0.19041
9 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\justi\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "link"
10 verbose node v12.16.3
11 verbose npm  v6.14.5
12 error code EPERM
13 error syscall rmdir
14 error path C:\Program Files\nodejs\node_modules\v-shared-element
15 error errno -4048
16 error Error: EPERM: operation not permitted, rmdir 'C:\Program Files\nodejs\node_modules\v-shared-element'
16 error  [Error: EPERM: operation not permitted, rmdir 'C:\Program Files\nodejs\node_modules\v-shared-element'] {
16 error   errno: -4048,
16 error   code: 'EPERM',
16 error   syscall: 'rmdir',
16 error   path: 'C:\\Program Files\\nodejs\\node_modules\\v-shared-element'
16 error }
17 error The operation was rejected by your operating system.
17 error It's possible that the file was already in use (by a text editor or antivirus),
17 error or that you lack permissions to access it.
17 error
17 error If you believe this might be a permissions issue, please double-check the
17 error permissions of the file and its containing directories, or try running
17 error the command again as root/Administrator.
18 verbose exit [ -4048, true ]
```

And my bad on the screenshots.

Just checked `C:\Program Files\nodejs\node_modules\v-shared-element` and it appears to be a symlink.

![image](https://user-images.githubusercontent.com/16705594/83825192-3e63e880-a69e-11ea-9973-2516712c419c.png)

So I think your gut is right. Maybe this isn't necessarily a bug but rather something that should be safeguarded?

**Comment by isaacs** [comment]
Oh!  Sorry, I glossed over the link, my bad.

> So I think your gut is right. Maybe this isn't necessarily a bug but rather something that should be safeguarded?

You get burned enough times by file system weirdness, you start to suspect them by default :)

Before you delete it, can you run this node script and share the output?

```js
const {statSync, lstatSync, realpathSync} = require('fs')
const dir = 'C:\\Program Files\\nodejs\\node_modules\\v-shared-element'
console.error([
  statSync(dir),
  lstatSync(dir),
  lstatSync(dir).isSymbolicLink(),
  realpathSync(dir),
])
```

Thanks!

**Comment by justintaddei** [comment]
> You get burned enough times by file system weirdness, you start to suspect them by default :)  

I've been burned a few times myself... that why I have my backup set to run every 10 minutes 😂


---

Here's the output you requested
```js
[
  Stats {
    dev: 4209967347,
    mode: 16822,
    nlink: 1,
    uid: 0,
    gid: 0,
    rdev: 0,
    blksize: 4096,
    ino: 6755399442974282,
    size: 0,
    blocks: 8,
    atimeMs: 1591322586674.8992,
    mtimeMs: 1591307151157.923,
    ctimeMs: 1591307151157.923,
    birthtimeMs: 1585085697431.0186,
    atime: 2020-06-05T02:03:06.675Z,
    mtime: 2020-06-04T21:45:51.158Z,
    ctime: 2020-06-04T21:45:51.158Z,
    birthtime: 2020-03-24T21:34:57.431Z
  },
  Stats {
    dev: 4209967347,
    mode: 41398,
    nlink: 1,
    uid: 0,
    gid: 0,
    rdev: 0,
    blksize: 4096,
    ino: 5629499534441648,
    size: 28,
    blocks: 0,
    atimeMs: 1591118606609.8628,
    mtimeMs: 1591118606609.8628,
    ctimeMs: 1591118606609.8628,
    birthtimeMs: 1591118606609.8628,
    atime: 2020-06-02T17:23:26.610Z,
    mtime: 2020-06-02T17:23:26.610Z,
    ctime: 2020-06-02T17:23:26.610Z,
    birthtime: 2020-06-02T17:23:26.610Z
  },
  true,
  'C:\\dev\\npm\\v-shared-element'
]
```

**Comment by luiguild** [comment]
I faced the same problem here, but in my case I didn't have any backup... `npm link` just deleted my entire project...

Thank you... 👌
