### ISSUE TITLE
[BUG] Git dependencies from same repo with different branch names are considered equal in v6.14.5

### ISSUE THREAD

**Issue by mcclenney** [npm/cli#1400]
# What / Why
`npm install` is generating different dependencies in v6.14.5 vs v6.14.4. If I have child dependencies that refer to different branches of the same repo, the different branches are considered equivalent and only one will be used.

I believe this is due to the change here where it returns true for doesChildVersionMatch if fetchSpec is equivalent. This check on fetchSpec is new. See the change here: https://github.com/npm/cli/pull/1230/commits/33ec41f18f557146607cb14a7a38c707fce6d42c 

The problem is that the fetchSpec property does not use branch name of the git dependency. 

Example:

"rawSpec": "git+https://enterprise-bitbucket.com/scm/prj/myrepo.git#v3.0.0",
"saveSpec": "git+https://enterprise-bitbucket.com/scm/prj/myrepo.git#v3.0.0",
"fetchSpec": "https://enterprise-bitbucket.com/scm/prj/myrepo.git",

and 

"rawSpec": "git+https://enterprise-bitbucket.com/scm/prj/myrepo.git#v2.0.0",
"saveSpec": "git+https://enterprise-bitbucket.com/scm/prj/myrepo.git#v2.0.0",
"fetchSpec": "https://enterprise-bitbucket.com/scm/prj/myrepo.git",

So, it considered these versions as the same, and only uses the 2.0.0 dependency, breaking the child modules that need the 3.0.0 dependency.

**Comment by akoutmos** [comment]
I am able to reproduce this error as well. I thought I was going crazy today haha.

While I am not targeting branches, I can confirm that npm is having difficulty with tag changes as well. I.e when you change the git tag for a dependency, your lock file does not update and you pull down the old version.

Repro steps that I took:
1. Change dependency git tag
2. npm install -g npm@6.14.5
3. npm install
4. No change in dependency version
5. npm install -g npm@6.14.4
6. npm install
7. New dependency version installed

**Comment by mcclenney** [comment]
Issue was fixed in v6.14.7 with commit 36e6c01d334c4db75018bc6a4a0bef726fd41ce4
