### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by shuwedha** [npm/cli#1404]
1246 error cb() never called!
1247 error This is an error with npm itself. Please report this error at:
1248 error <https://npm.community>

**Comment by gwennlbh** [comment]
I got the same error just now. Retrying worked. Here's the content of my debug log:

```log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/ewen/.config/nvm/13.5.0/bin/node',
1 verbose cli   '/home/ewen/.config/nvm/13.5.0/bin/npm',
1 verbose cli   'i',
1 verbose cli   '-g',
1 verbose cli   'pnpm'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v13.5.0
4 verbose npm-session 0ec686bd65599670
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/pnpm 307ms
8 timing npm Completed in 3604ms
9 error cb() never called!
10 error This is an error with npm itself. Please report this error at:
11 error <https://npm.community>
```

**Comment by shuwedha** [comment]
> I got the same error just now. Retrying worked. Here's the content of my debug log:
> 
> ```
> 0 info it worked if it ends with ok
> 1 verbose cli [
> 1 verbose cli   '/home/ewen/.config/nvm/13.5.0/bin/node',
> 1 verbose cli   '/home/ewen/.config/nvm/13.5.0/bin/npm',
> 1 verbose cli   'i',
> 1 verbose cli   '-g',
> 1 verbose cli   'pnpm'
> 1 verbose cli ]
> 2 info using npm@6.13.4
> 3 info using node@v13.5.0
> 4 verbose npm-session 0ec686bd65599670
> 5 silly install loadCurrentTree
> 6 silly install readGlobalPackageData
> 7 http fetch GET 200 https://registry.npmjs.org/pnpm 307ms
> 8 timing npm Completed in 3604ms
> 9 error cb() never called!
> 10 error This is an error with npm itself. Please report this error at:
> 11 error <https://npm.community>
> ```

Thank you @ewen-lbh  for the debug log. I tried to downgrade from @3.0.0 to react-scripts @2.1.8 which also resolved this issue.
