### ISSUE TITLE
npm ERR! request to https://registry.cnpmjs.org/karma-coverage-istanbul-reporter failed, reason: Hostname/IP doesn't match certificate's altnames: "Host: registry.cnpmjs.org. is not in the cert's altnames: DNS:r.cnpmjs.org"[BUG] <title>

### ISSUE THREAD

**Issue by Aswani05** [npm/cli#1407]
# What / Why

> n/a

## When

* n/a

## Where

* n/a

### Current Behavior

* n/a

### Steps to Reproduce

* n/a

### Expected Behavior

* n/a

## Who

* n/a

## References

* n/a

**Comment by ljharb** [comment]
What is "registry.cnpmjs.org"? npm's registry is registry.npmjs.org.
