### ISSUE TITLE
[BUG] npm install ignores tag from config

### ISSUE THREAD

**Issue by mattjohnson** [npm/cli#1408]
# What / Why
From https://docs.npmjs.com/misc/config#tag
> If you ask npm to install a package and don’t tell it a specific version, then it will install the specified tag.

npm config set tag next
npm config ls -l
```
; cli configs
long = true
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.7.0 node/v11.15.0 darwin x64"

; userconfig /Users/matt/.npmrc
tag = "next"

; default values
access = null
...
strict-ssl = true
; tag = "latest" (overridden)
tag-version-prefix = "v"
...
```
npm install react
`+ react@16.13.1`

Installs 16.13.1 instead of the next tag.
```    
    "dist-tags": {
        "latest": "16.13.1",
        "next": "0.0.0-33c3af284",
        "experimental": "0.0.0-experimental-33c3af284",
        "canary": "0.0.0-57333ca33",
        "unstable": "0.0.0-da834083c"
    },
```
# Expected
It should try to use the tag to resolve the version.

**Comment by ljharb** [comment]
If that worked, it would fail on every package that didn't have a "next" tag. That doesn't seem desirable.

**Comment by mattjohnson** [comment]
True! For most people this wouldn't be desirable. At a minimum the documentation is wrong/misleading.

Some context for why I would consider something like this:
Some organizations have policies that disallow the latest tag, or any version that hasn't been "approved", and instead might have a different way of allowing certain versions. Those organizations usually proxy https://registry.npmjs.org and/or host their own registires internally. It would be valuable to have configuration that allows the cli to discern what version should be used in the absence of a tag or version. What I was hoping for is allowing configuration to specify how that resolution might happen.

One way of looking at it would be to overwrite the latest tag in the metadata with the latest "approved" version but that seems misleading to users, since it might not match their expectations. Instead, I'd prefer to augment the metadata with an alternate default tag that the cli can be configured to use.

**Comment by ljharb** [comment]
I'd think a much, much better solution is a CI check that ensures that all deps in the graph are "approved", rather than trying to hijack the way `install` works. Sometimes people add deps manually, for example.

**Comment by mattjohnson** [comment]
It is an attempt to shift some of the responsibility/visibility to the developers. Debugging failed CI builds can be painful and catches the error later in the process, which can slow things down overall.

What I've interpreted as a bug based on the documentation might not make sense for most (or maybe all!) developers. I still think there is some friction that is felt in these organizations that could be alleviated with more metadata control. 

Npm has vulnerability data, and if it was able to provide a convention, similar to the latest tag, that represented a policy of latest version that has been scanned and deemed to have no known vulnerabilities, that seems like it would be a convention worth adopting in the community.

I'll close this since its probably just a documentation issue.
