### ISSUE TITLE
[BUG] <npm uninstall --save [packages] does not remove from package.json>

### ISSUE THREAD

**Issue by hrkazemi** [npm/cli#1425]
# try to `uninstall` a package and also remove from `package.json`
none of these working:
`npm uninstall --save package`
`npm uninstall package --save`
`npm uninstall -s package`
`npm uninstall package -s`

**Comment by ljharb** [comment]
Can you elaborate? These all work for me.

**Comment by hrkazemi** [comment]
I tried to uninstall the `react-to-pdf` package using the above commands and it was removed from the node_module folder but not from the package.json.
node version `12.16.1`
npm version `6.14.5`
what details I give will help better?

**Comment by ljharb** [comment]
What's the log output? What if you try `npm uninstall --loglevel=silly --save react-to-pdf`?

**Comment by hrkazemi** [comment]
I had deleted the package from package.json manually so I installed it again and ran `npm uninstall --loglevel=silly --save react-to-pdf`.
it did remove it from package.json.
here is the log file:
[log.txt](https://github.com/npm/cli/files/4774165/log.txt)

**Comment by ljharb** [comment]
Seems like the issue is fixed then?

**Comment by hrkazemi** [comment]
I hope so 😊
