### ISSUE TITLE
[BUG] 502 Bad Gateway

### ISSUE THREAD

**Issue by Mentors4EDU** [npm/cli#1452]
# What / Why

>Downloads aren't showing up and it has a 502 Bad Gateway for many of NPM's API and its nginx server/cache

## When

* Currently as of the time writing this

## Where

* https://nodei.co/npm/*Enter Package Name Here*

### Current Behavior

* Has a bad gateway, wondering if NPM is just being updated

### Steps to Reproduce

* n/a

### Expected Behavior

* n/a

## Who

* n/a

## References

* n/a

**Comment by jonchurch** [comment]
I'm not able to reproduce this at this time with the provided info

**Comment by Mentors4EDU** [comment]
Hi, the NodeCI team fixed this error in the morning w/ their server update
