### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by CholoTook** [npm/cli#1461]
Hi,

I'm trying to run the download  app from here:
https://github.com/jgraph/drawio-desktop/tree/v13.3.1

npm install in the two locations seems to return fine, but npm start gives me:
Unable to find Electron app at .../drawio-desktop-13.3.1/drawio/src/main/webapp

Full log here:
https://termbin.com/.1loqj

Not sure what I'm doing wrong. I tried googling, but no joy.

Many thanks

**Comment by ljharb** [comment]
`npm start` is part of a local application's package.json, and doesn't have anything to do with npm. you'll need to file an issue on that project.

**Comment by ljharb** [comment]
This is a duplicate of https://github.com/npm/rfcs/discussions/172

**Comment by CholoTook** [comment]
Right, but that community is tiny, so I thought I'd ask here.

**Comment by ljharb** [comment]
a) it's not; b) it doesn't belong in either place; c) please don't ask in more than one place, it's rude to the folks who are in both.

**Comment by CholoTook** [comment]
Well.. they don't have IRC. IMHO this is a perfect question for #npm, if it were open. I always thought it was a FOSS project without much central control, but I realise I had the wrong idea. Sorry for being rude, I was frustrated by the locked channel but I shouldn't have taken a scatter gun approach in response.

**Comment by ljharb** [comment]
`#node.js` exists - this isn't an npm-related question, so an official npm channel is irrelevant.

**Comment by CholoTook** [comment]
Sorry, I was talking about the draw.io project.
