### ISSUE TITLE
[FEATURE] <title>

### ISSUE THREAD

**Issue by CholoTook** [npm/cli#1462]
Please create an IRC channel.

IRC is supa useful for debugging quick questions.

I got redirected here:
https://npm.community/

But nothing like IRC seems to exist here.

Why wouldn't you want people chatting in IRC?

Thanks,

**Comment by ljharb** [comment]
npm used to have an IRC channel on freenode; it was shut down many years ago. You can certainly ask npm questions in `#node.js` on freenode, but i believe the npm team only monitors their repos and their support@npmjs.com email address.

**Comment by ljharb** [comment]
This is a duplicate of https://github.com/npm/rfcs/discussions/171
