### ISSUE TITLE
[BUG] <bad interpreter>

### ISSUE THREAD

**Issue by jiang-hr** [npm/cli#1465]
# What / Why
While I was using wsl2 , I found I can't use npm to do anything.

## When
always

## Where
wsl2 ubuntu18.04 LTS
```
root@DESKTOP-XXXXX:~# uname -srmo
Linux 4.19.104-microsoft-standard x86_64 GNU/Linux
```

### Steps to Reproduce
```
root@DESKTOP-XXXXX:~# apt install npm
.......
Processing triggers for man-db OK.
```
then, I try to use npm to do something, but I found that I can't do anything.
```
root@DESKTOP-XXXXX:~# npm
-bash: /mnt/c/Program Files/nodejs/npm: /bin/sh^M: bad interpreter: No such file or directory
root@DESKTOP-XXXXX:~# npm install -g typescript
-bash: /mnt/c/Program Files/nodejs/npm: /bin/sh^M: bad interpreter: No such file or directory
```

**Comment by ljharb** [comment]
Don't install npm from apt, or separately - npm only ever comes with node.

**Comment by jiang-hr** [comment]
Thank you.
I uninstall all the package in wsl2 and windows10.
Use `apt remove nodejs` in wsl2 and uninstall win10's Nodejs in windows control panel.
Then reinstall Nodejs in win10, and surprisingly, npm can be used normally in wsl2.
