### ISSUE TITLE
[Bug] NPM 6.15 is shipping self-signed certs in version 6.14.5

### ISSUE THREAD

**Issue by CieloVistaSoftware** [npm/cli#1485]
# What / Why
 I'm working on a library.  All of a sudden I'm getting self-signed certs warnings.
I tracked it down to a single package in agent-base and any others that use it or a cloned copy. NPM 6.14.5 is defective as a result.

## Where

 [npm repository for agent-base](https://www.npmjs.com/package/agent-base) and any of it's consumers.  A simple npm i agent-base@latest will not get all of the packages that have this.

## Who

[The github repo](https://github.com/TooTallNate/node-agent-base)
 
## Impact
Self-signed cert warnings when building NPM Packages.  They shouldn't be ignored.  I have no idea how this made it into my node_modules folder. Is there a way I can find dependencies?

**Comment by shadowspawn** [comment]
You can see the dependency chain using `npm ls`:

From your package:
```
npm ls agent-base
```

**Comment by CieloVistaSoftware** [comment]
Found out today it's in npm 6.14.5 too, the latest NPM version.  Does anyone know how to replace it and it's dependency chain for the entire node_modules folder?

**Comment by CieloVistaSoftware** [comment]
Upgrading to Angular 10 solved the issue.
