### ISSUE TITLE
test and refactor lib/npm.js and bin/npm-cli.js

### ISSUE THREAD

**Issue by isaacs** [npm/cli#1506]
- Remove some affordances that are no longer relevant (WScript messaging, onload-script support, `npm.commandName` instead of `npm.commands['command-name']()`, optional callback/args lists, etc.)
- unit test up to 100% coverage
- modernize code (make `npm` an instance of a class, const/let/arrow-functions, organize and clean up, etc.)

**Comment by isaacs** [comment]
Also going to update `help.js` in this, since the changes to the `npm` object have a pretty significant impact there.

**Comment by isaacs** [comment]
Note: this should land _after_ the lib/ls.js refactor, and remove the `REMOVEME` commit.

**Comment by ashward** [comment]
Apologies for jumping on an old issue, but I wondered why `onload-script` support had been removed, and whether there is another way to do achieve a similar thing (hooking into the npm script whenever it's invoked) on a per-repository basis?

The reason I ask is that my security wrapper relies on this functionality, and as it stands this doesn't work with npm 7: https://github.com/ashward/jsinstallguard
