### ISSUE TITLE
[QUESTION] npm peer dependcies version check incorrect

### ISSUE THREAD

**Issue by kkmuffme** [npm/cli#1510]
# What / Why
npm complains about missing, but required peer dependencies even though they exist.

e.g. eslint ^7 is needed, eslint 7.4.0 is installed, but still it complains:
`npm WARN @wordpress/eslint-plugin@7.1.0 requires a peer of eslint@^6 || ^7 but none is installed. You must install peer dependencies yourself.`

More details:

```
npm list -g | grep eslint
├─┬ @wordpress/eslint-plugin@7.1.0
│ ├─┬ babel-eslint@10.1.0
│ │ ├── eslint-visitor-keys@1.3.0
│ ├─┬ eslint-config-prettier@6.11.0
│ ├─┬ eslint-plugin-jest@23.18.0
│ │ └─┬ @typescript-eslint/experimental-utils@2.34.0
│ │   ├─┬ @typescript-eslint/typescript-estree@2.34.0
│ │   │ ├── eslint-visitor-keys@1.3.0 deduped
│ │   ├─┬ eslint-scope@5.1.0
│ │   └─┬ eslint-utils@2.1.0
│ │     └── eslint-visitor-keys@1.3.0 deduped
│ ├─┬ eslint-plugin-jsdoc@26.0.2
│ ├─┬ eslint-plugin-jsx-a11y@6.3.1
│ ├─┬ eslint-plugin-prettier@3.1.4
│ ├─┬ eslint-plugin-react@7.20.3
│ ├── eslint-plugin-react-hooks@4.0.7
├─┬ eslint@7.4.0
│ ├─┬ eslint-scope@5.1.0
│ ├─┬ eslint-utils@2.1.0
│ │ └── eslint-visitor-keys@1.3.0 deduped
│ ├── eslint-visitor-keys@1.3.0
│ │ └── eslint-visitor-keys@1.3.0 deduped
├── eslint-config-wordpress@2.0.0
├─┬ eslint-plugin-html@6.0.2
├─┬ eslint-plugin-jsdoc@29.1.3
├── eslint-plugin-php-markup@6.0.0
├─┬ eslint-plugin-unicorn@20.1.0
│ ├─┬ eslint-ast-utils@1.1.0
│ ├─┬ eslint-template-visitor@2.0.0
│ │ ├── eslint-visitor-keys@1.3.0
│ │ │ └── eslint-visitor-keys@1.3.0 deduped
│ ├─┬ eslint-utils@2.1.0
│ │ └── eslint-visitor-keys@1.3.0 deduped

# npm install -g @wordpress/eslint-plugin
npm WARN @wordpress/eslint-plugin@7.1.0 requires a peer of eslint@^6 || ^7 but none is installed. You must install peer dependencies yourself.
npm WARN babel-eslint@10.1.0 requires a peer of eslint@>= 4.12.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-jsx-a11y@6.3.1 requires a peer of eslint@^3 || ^4 || ^5 || ^6 || ^7 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react@7.20.3 requires a peer of eslint@^3 || ^4 || ^5 || ^6 || ^7 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-prettier@3.1.4 requires a peer of eslint@>=5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-prettier@6.11.0 requires a peer of eslint@>=3.14.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react-hooks@4.0.7 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-jest@23.18.0 requires a peer of eslint@>=5 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-jsdoc@26.0.2 requires a peer of eslint@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/experimental-utils@2.34.0 requires a peer of eslint@* but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
```

**Comment by ljharb** [comment]
That's because they're global; peer deps don't work properly with global installs.

eslint should only ever be installed locally anyways.

**Comment by kkmuffme** [comment]
I only have this issue when installing @wordpress/eslint-plugin - didn't have this issue for any other npm package.

What can I do to resolve this issue (except installing locally which isn't an option for my use case) so that I can use @wordpress/eslint-plugin?
All other eslint things work perfectly fine, even with -g

**Comment by ljharb** [comment]
What's your use case where installing locally, per-project, isn't an option?

(Separately, you're also missing typescript)

**Comment by kkmuffme** [comment]
we use eslint in our CI/CD pipeline server with ~50 worker processes, which handle a variety of projects. if I have to install npm things locally I have to keep track of 500 eslint/npm installations (50x10 projects). Additionally since it's used on a pure cli basis I think global is preferred here too

>(Separately, you're also missing typescript)

Thanks for the info (I was aware of that though)

**Comment by ljharb** [comment]
i wouldn’t expect you have to keep track of anything. You’d always run npm install in every project anyways, and you just run `npx eslint` in each one.

**Comment by kkmuffme** [comment]
We tried that and it was a failure as it required a lot of manual intervention, as one had to always hardcode the versions as otherwise it would update to some newer version that then had some install issues, which made the pipeline's fail,...
From a usability point of view, using npm globally for this use case is much better, unless you have a dedicated DevOps engineer who has time to take care of these things.
With the global installation I install it once and am sure it works - dont need to npx/npm everywhere locally all the time and then things may break, need to debug,...

**Comment by ljharb** [comment]
Yes, each project should be hardcoding the versions it needs.

At any rate, I’m not sure why this wouldn’t be working - what’s `npm -g --depth=0` print out?

**Comment by kkmuffme** [comment]
I get:

```
npm -g --depth=0

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, fund, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

Specify configs in the ini-formatted file:
    /root/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@6.14.4 /usr/lib/node_modules/npm
```

**Comment by samusstrike** [comment]
@kkmuffme Did you find a resolution to this issue? I have the same type of warning message.
Message: npm WARN eslint-plugin-jsdoc@30.4.2 requires a peer of eslint@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.

The command to list top level global npm packages is: npm list -g --depth=0
My list is:
+-- @types/mssql@4.0.15
+-- babel-eslint@10.0.1
+-- eslint@7.9.0
+-- eslint-plugin-jsdoc@30.4.2
+-- express-generator@4.16.0
+-- generator-code@1.2.9
+-- gulp-cli@2.1.0
+-- handlebars@4.1.2
+-- markdown-pdf@10.0.0
+-- npm@6.14.7
+-- typescript@3.8.3
+-- vsce@1.76.1
`-- yo@3.1.1

**Comment by kkmuffme** [comment]
@samusstrike You need to manually install all dependencies globally too and then the error message can be ignored (since the dependencies are there anyway)

**Comment by samusstrike** [comment]
@kkmuffme If that is the case, then it would seem this is a bug with NPM since it apparently does not recognize the dependency is installed. I suspect there is a nuance with specific version numbers vs range of version numbers. Thanks for the follow up.

**Comment by kkmuffme** [comment]
Yes exactly
