### ISSUE TITLE
[Can any one help me out with this ?] <Error>

### ISSUE THREAD

**Issue by Anustup900** [npm/cli#1570]
![npm error](https://user-images.githubusercontent.com/60361231/88633490-b664f280-d0d2-11ea-84e1-5e9aaaf87286.PNG)

**Comment by darcyclarke** [comment]
Closing: we don't support the `amplify` project; If you think you've found a bug in `npm` itself, please use one of our issue templates to file a ticket: https://github.com/npm/cli/issues/new/choose
