### ISSUE TITLE
[QUESTION] Information missing about licensing at docs

### ISSUE THREAD

**Issue by flikkes** [npm/cli#1580]
# What / Why

In [the documentation](https://docs.npmjs.com/files/package.json#license) regarding license information in package.json it is stated, that the deprecated multi license format 
```
{ "licenses" :
  [
    { "type": "MIT",  "url": "https://www.opensource.org/licenses/mit-license.php"}, 
    { "type": "Apache-2.0", "url": "https://opensource.org/licenses/apache2.0.php"}
  ]
}
```
Should be replaced with an SPDX expression like so: 
`{ "license": "(MIT OR Apache-2.0)" }`. 
I don't think that this is accurate as you can't really say if it was originally intended to let users comply with only one of the licenses given in the array. I'd suggest to change `{ "license": "(MIT OR Apache-2.0)" }` to `{ "license": "(MIT AND Apache-2.0)" }`. Shouldn't it be assumed that if the developer doesn't tell you any other, the 'strongest' form of licensing (which would be the conjunction of both licenses) must apply when stumbling across such deprecated expressions? Did I miss anything on that topic? Or is the according provider (npm) deciding how it should be interpreted?

## References

* [https://docs.npmjs.com/files/package.json#license](https://docs.npmjs.com/files/package.json#license)

**Comment by ljharb** [comment]
I'm not sure why you can't? It's *always* been the case that when multiple licenses exist, *any* of them can be chosen, and although I'm not a lawyer I believe that's how most corporate lawyers I've spoken to have indicated it'd be legally interpreted.

**Comment by flikkes** [comment]
Ok that's interesting. In this case the issue would be solved for me. It's just that I didn't find any reliable information on that topic. [A Wikipedia article](https://en.wikipedia.org/wiki/Multi-licensing) says that 

> the simple presence of multiple licenses in a software package or library does not necessarily indicate that the recipient can freely choose one or the other

but they also don't provide specific sources for that statement. @ljharb could you point me somewhere where one can read about this in detail or did you just _hear_ about that from mentioned lawyers?

**Comment by ljharb** [comment]
As you might expect, none of my employers' lawyers have ever provided legal advice to me around this in writing, so I can only relate it anectodally.
