### ISSUE TITLE
npm ERR! cb() never called! on installing dependencies using npm install on Ionic Project

### ISSUE THREAD

**Issue by akashpandey1310** [npm/cli#1581]
On setting up a pre-build ionic app for some changes, on using npm install command to install node modules, it throws no. of errors,

 Mobile App Code V1.0>npm install
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\TechWorld\AppData\Roaming\npm-cache\_logs\2020-07-29T18_14_59_843Z-debug.log 

Please help !!!!!

**Comment by casssiahaluu** [comment]
The same here. But I am using React.js and some other ecosystem packages. It doesn't happen every time, but it happens several times.

NPM Version: 6.14.4
Version node: v12.18.0

I'm using a ZSH terminal. I have no possibility to try on other terminals

**Comment by akashpandey1310** [comment]
SOLVED!!

just try downgrading version of your npm ,

Try,  npm install npm@5

This work for me.
