### ISSUE TITLE
[BUG] cb() never called!

### ISSUE THREAD

**Issue by zmd219-zz** [npm/cli#1605]
tried to install package.json file with `npm install`

`npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:`

logs:
`8993 timing npm Completed in 20505ms
8994 error cb() never called!
8995 error This is an error with npm itself. Please report this error at:
8996 error <https://npm.community>`

**Comment by ChildishGiant** [comment]
I also got this error when running an npx command but a simple system restart has fixed it for me.

**Comment by ChildishGiant** [comment]
And it's back.
