### ISSUE TITLE
cli: `make docs` in clean checkout prior to v7.0.0-beta.0 doesn't build gatsby bin

### ISSUE THREAD

**Issue by isaacs** [npm/cli#1621]
It looks like, when we have a v6 lockfile and no `node_modules` folder, `npm install` will fail to create bins, because it does not re-check the package manifest to see that there's a `bin` entry, since it gets the nodes from the `virtualTree`.

`loadVirtual` will re-check the actual `node_modules/.../package.json` files for extra data when encountering a v6 lockfile.  However, if they're not there, then we just have to deal with the incomplete data.

In this case, `reify()` (or `buildIdealTree({ complete: true })`) should fetch updated manifests from the registry, and fill in the blanks like `loadVirtual` would have from the `node_modules/.../package.json` files.

**Comment by isaacs** [comment]
Actually this only happens if you do `npm i --package-lock-only` ahead of doing `npm install`.  I think we can potentially raise a warning if doing a `package-lock-only` install with an old lockfile, or even just `WONTFIX` this, but upon further investigation, it's not as high a priority as I initially thought.

**Comment by isaacs** [comment]
The complete "fix" would be pretty costly, too.  Basically, any `arborist.buildIdealTree({ complete: true })` in the presence of a `v1` lockfile will have to call `pacote.manifest` on the `name@version` of each item in the tree if the `resolved` value looks like the expected registry tarball, or on `resolved` if not (which means a lot more temp unpacks).

**Comment by isaacs** [comment]
Closing as `WONTFIX`.  Pretty hard to hit (since someone would have to run `npm install --package-lock-only`, which is somewhat obscure), the most likely workaround to try (running `npm update`, or deleting and re-installing) fixes the problem entirely, and any reasonable fix would be costly and complicated.

**Comment by ljharb** [comment]
So if i do npm install first, and then do package-lock-only, and then rimraf node_modules and npm install, it’s fine?
