### ISSUE TITLE
npm is down

### ISSUE THREAD

**Issue by egoroof** [npm/cli#1624]
open https://www.npmjs.com/package/@2gis/tiny-map got 503 {"error":"Service Unavailable"} or sometimes 
> ESOCKETTIMEDOUT
> id: 22e8c953-b92e-4626-96c3-66857626c11b

also 404's sometimes on packages install

**upd see current status on** https://status.npmjs.org/

**Comment by mark-beeby** [comment]
We're also receiving erroneous 404's from a variety of packages, different package each time...

> npm ERR! code E404

**Comment by rexchoppers** [comment]
Hi,

We're also having the same problem with the following package: [https://www.npmjs.com/package/@nestjs/typeorm](https://www.npmjs.com/package/@nestjs/typeorm). We cannot access this package on the site and via npm install.

The following shows on the website:

ESOCKETTIMEDOUT

id: 72632f72-98ce-441b-80ac-335af76b4766

![image](https://user-images.githubusercontent.com/52251127/89509171-e002d580-d7c6-11ea-8bb5-fa422c079dd4.png)


The following shows on our CI/CD:

npm ERR! 404  '@nestjs/typeorm@6.2.0' is not in the npm registry.

**Comment by greg-md** [comment]
MS :trollface:

**Comment by dvantourout** [comment]
Same here, 403 and 404 errors

**Comment by SilentImp** [comment]
> MS :trollface:

Just wait. GitHub is also MS, so … :trollface:

**Comment by rained23** [comment]
maybe you forgot to renew your  npm subscription :trollface:

**Comment by greg-md** [comment]
> > MS :trollface:
> 
> Just wait. GitHub is also MS, so … :trollface:

Soon TikTok will join the squad. :trollface:

**Comment by InCorCadit16** [comment]
Heh, I can't run CI jobs on my project at work because of this(

**Comment by rexchoppers** [comment]
> Heh, I can't run CI jobs on my project at work because of this(

Join the queue

**Comment by JrontEnd** [comment]
same issue

**Comment by tuxounet** [comment]
idem

**Comment by chanyounghur** [comment]
> Heh, I can't run CI jobs on my project at work because of this(

so I pushed node_modules to github lol

**Comment by otonck** [comment]
Same here  :)

**Comment by ujlbu4** [comment]
https://status.npmjs.org/ 

> Update - The ongoing issue may also affect installation of scoped packages. We continue investigating these issues.
Aug 6, 08:55 UTC

**Comment by zyudneko** [comment]
> 
> 
> https://status.npmjs.org/
> 
> > Update - The ongoing issue may also affect installation of scoped packages. We continue investigating these issues.
> > Aug 6, 08:55 UTC

For me https://status.npmjs.org/ is down

**Comment by vMReal** [comment]
same issue

https://registry.npmjs.org/...-> registry responds with 404

https://www.npmjs.com/package/.... -> dashboard responds with ESOCKETTIMEDOUT

**Comment by ziimakc** [comment]
+1

**Comment by lartheon** [comment]
This couldn't have happened at a better time for me.... 🤦‍♂️
Someone call IT, tell them to turn it off and on again

**Comment by RosenTomov** [comment]
Any news whats going on? When is it getting resolved?

**Comment by igorbaranovmd** [comment]
https://status.npmjs.org/

**Comment by ziimakc** [comment]
Latest news from npm: https://status.npmjs.org/

We have identified the problematic component and the team is working on a fix.
Aug 6, 09:09 UTC

**Comment by edmooney** [comment]
Getting 404's as well: npm ERR! 404 Not Found - GET https://registry.npmjs.org/@polka%2furl - Not found

**Comment by ohadch** [comment]
Same here

```
(base) ohadchaet@Ohads-MacBook-Pro main % npm i -g firebase-tools
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@google-cloud%2fpubsub - Not found
npm ERR! 404 
npm ERR! 404  '@google-cloud/pubsub@^1.7.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'firebase-tools'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ohadchaet/.npm/_logs/2020-08-06T09_29_56_322Z-debug.log
(base) ohadchaet@Ohads-MacBook-Pro main % 
```

**Comment by altbdoor** [comment]
Ditto, builds with Angular is also failing, with `@angular-devkit/build-angular`.

```
$ npm i @angular-devkit/build-angular
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@angular-devkit%2fbuild-angular - Not found
npm ERR! 404
npm ERR! 404  '@angular-devkit/build-angular@~0.1000.5' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2020-08-06T09_35_02_319Z-debug.log
```

**Comment by ziimakc** [comment]
Latest news from npm: https://status.npmjs.org/

Update - The issue with the npm website was resolved. We are still looking into error telemetry for installation of scoped packages but are seeing signs of improvement.
Aug 6, 09:33 UTC

**Comment by greg-md** [comment]
> > Heh, I can't run CI jobs on my project at work because of this(
> 
> so I pushed node_modules to github lol

![lol](https://user-images.githubusercontent.com/10551984/89516977-c7ec7f80-d7e1-11ea-989f-1a79e7d4461d.jpg)

**Comment by tuphamdev96** [comment]
The same :) 
![image](https://user-images.githubusercontent.com/60084784/89517129-7f45be00-d803-11ea-9e31-1b3eacc5cf4d.png)

**Comment by xoryouyou** [comment]
Same for @hapi/bourne@latest 
![2020-08-06_11-25-26](https://user-images.githubusercontent.com/777569/89519765-26632f00-d7dd-11ea-94ab-75f4f5c6ed30.png)

**Comment by MagedMYoussef** [comment]
Same for @rollup/pluginutils
![image](https://user-images.githubusercontent.com/12249157/89520755-a3db6f00-d7de-11ea-88f9-f0768d13f361.png)

**Comment by snowjang24** [comment]
still not work...

**Comment by lartheon** [comment]
> still not work...

just keep an eye on the status page https://status.npmjs.org/
latest update just a moment ago, they are making some progress with the faulty cache

**Comment by RosenTomov** [comment]
`
Errors are decreasing while we re-populate a faulty cache. We are working to speed up that process to fully resolve the remaining issues quickly. 
`

**Comment by lartheon** [comment]
@egoroof update your post with the status page link, save people just posting me toos
here - https://status.npmjs.org/

**Comment by egoroof** [comment]
> @egoroof update your post with the status page link, save people just posting me toos

done

**Comment by wahyualfarisi** [comment]
![image](https://user-images.githubusercontent.com/25720712/89523826-bae58580-d80d-11ea-873e-edee2c5d32be.png)


yaa, im not alone

**Comment by rbelmega** [comment]
hm, subscribing to this page for a new portion of memes

**Comment by SaeedSoltoon** [comment]
Same for @yarnpkg/lockfile
![Screenshot from 2020-08-06 15-18-46](https://user-images.githubusercontent.com/4473680/89525294-32f68000-d7fb-11ea-9963-505388ef6774.png)

**Comment by azamara** [comment]
Same for @nestjs/common
![](https://user-images.githubusercontent.com/726979/89525398-15d4a800-d821-11ea-9947-9c592f754bd0.png)

**Comment by astandrik** [comment]
same for @webpack-contrib/schema-utils

**Comment by komlodin** [comment]
same for @material-ui/core

**Comment by jurr90** [comment]
Random packages are failed

**Comment by devilmayhorny** [comment]
same here.
![image](https://user-images.githubusercontent.com/21995601/89526105-70660800-d811-11ea-8ed6-302de853eeaa.png)

**Comment by RosenTomov** [comment]
Are there any registry mirrors we can use?

**Comment by gengjiawen** [comment]
> Are there any registry mirrors we can use?

You can try taobao: `yarn install --registry=https://registry.npm.taobao.org`

**Comment by egoroof** [comment]
![](https://pics.me.me/when-you-write-the-npm-install-command-this-little-manoeuvre-44486115.png)

**Comment by maxamorim** [comment]
![c0b4c695-e227-4d7f-b5c7-1efe470fdf21](https://user-images.githubusercontent.com/16763184/89527073-09345d80-d7e9-11ea-9801-759cd9e363fd.jpg)

**Comment by egoroof** [comment]
> We replaced the faulty cache and our telemetry indicates a significant improvement in error rates. We'll continue to monitor the situation and make sure all issues are fully resolved.
Aug 6, 11:36 UTC

https://status.npmjs.org/

**Comment by seankonig** [comment]
back up and running. thank you

**Comment by abdelaziz321** [comment]
yes, it works now for me.

**Comment by komlodin** [comment]
yarn install finished without errors!

Done in 250.75s.

**Comment by egoroof** [comment]
> Done in 250.75s.

try `npm ci` :)

**Comment by maxamorim** [comment]
Ladies and gentlemen, it's alive!

**Comment by godkun** [comment]
mark

**Comment by E-jarod** [comment]
![image](https://user-images.githubusercontent.com/57091681/89528448-531e4300-d7eb-11ea-8641-4aded2e4ce7f.png)
It 's working !!!!

**Comment by egoroof** [comment]
more than 3.5 hours of outage - cool uptime

**Comment by wildmichael** [comment]
I still see the problem:
```
npm i @tuxc/long
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@tuxc%2flong - Not found
npm ERR! 404
npm ERR! 404  '@tuxc/long@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
````

**Comment by rexchoppers** [comment]
@egoroof Agreed, leaving us without CI/CD for 3.5 hours is ridiculous. This problem has been resolved however and if you're experiencing issues I'd give it another 30 minutes or so

**Comment by wildmichael** [comment]
Still waiting.

**Comment by SRNV** [comment]
https://status.npmjs.org/incidents/cksjqc1w11v5?u=clfvn2m9yb5p
this is considered as resolved @wildmichael

**Comment by wildmichael** [comment]
Well, it ain't for me:
```
$ npm i @tuxc/long
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@tuxc%2flong - Not found
npm ERR! 404
npm ERR! 404  '@tuxc/long@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by otonck** [comment]
I don't see any trace of a @tuxc/long package on npmjs.com.
My guess is that this is another issue, may be should you search for a replacement package ([long](https://www.npmjs.com/package/long) ?).

**Comment by pumano** [comment]
Guys please check detailed info about today outage, don't spam here: https://status.npmjs.org/incidents/cksjqc1w11v5

**Comment by wildmichael** [comment]
Thanks for being patronizing. Where else should I complain that the issue isn't fixed for this package then? Because the "detailed info" doesn't allow me to provide any feedback.

@otonck this particular package is a transitive dependency somewhere in angular, not my choice.

**Comment by otonck** [comment]
@wildmichael ok, i guess you just mistyped the package name (should be xtuc and not tuxc from angular's yarn.lock)

**Comment by wildmichael** [comment]
Banging my head against the wall. Very sorry for the noise.

**Comment by Nyameliaaaa** [comment]
:trollface:

**Comment by alamenai** [comment]
` npm i firebase
npm ERR! Response timeout while trying to fetch http://registry.npmjs.org/firebase (over 30000ms)`

The same issue with firebase.

**Comment by Nyameliaaaa** [comment]
:trollface:
