### ISSUE TITLE
[BUG] npm install ends with a 404 error

### ISSUE THREAD

**Issue by goutham1706-dev** [npm/cli#1629]
# What / Why

> npm was working fine until a few minutes ago, but started trhowing 404 errors when I tried to install packages

> npm i apollo-server-micro

>npm WARN deprecated accept@3.1.3: This module has moved and is now available at @hapi/accept. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm ERR! code E404
npm ERR! 404 Not Found - GET http://registry.npmjs.org/@wry%2fequality - Not found
npm ERR! 404
npm ERR! 404  '@wry/equality@^0.1.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'apollo-utilities'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

## When

* 06-08-2020 @ 15:56 IST

## Where

* n/a

### Current Behavior

* n/a

### Steps to Reproduce

* n/a

### Expected Behavior

* n/a

## Who

* n/a

## References

* n/a

**Comment by yelizariev** [comment]
see https://github.com/npm/cli/issues/1626 and close this issue please
