### ISSUE TITLE
[BUG] `npm view --json` with range giving incorrect results

### ISSUE THREAD

**Issue by MylesBorins** [npm/cli#1640]
### Current Behavior:
```bash
$ npm view --json omg-i-pass@^2.0.0
{
  "_id": "omg-i-pass@2.0.0",
...
}
```

Only a single result is returned for 2.0.0

### Expected Behavior:
```bash
$ npm view --json omg-i-pass@^2.0.0
[
 {
        "_id": "omg-i-pass@2.0.0",
  ...
  },
  {
    "_id": "omg-i-pass@2.0.1",
  }
]
```

npm 6 returns an array of results that satisfy the semver range.

### Steps To Reproduce:
Use commands as seen above

### Environment:
OSX 10.15.6
Node.js v14.6.0
npm v7.0.0-beta.2

**Comment by isaacs** [comment]
Fixed in latest v7 beta.  Thanks!
