### ISSUE TITLE
[BUG] Unexpected token = in JSON at position 291227

### ISSUE THREAD

**Issue by micahlt** [npm/cli#1644]
### Current Behavior:

I'm installing an NPM package `cordova-android@^9.0.0` and I get the following error: 
```
npm ERR! Unexpected token = in JSON at position 291227 while parsing near '...TAEQ=="
npm ERR!     }
npm ERR!   }
npm ERR! }
npm ERR! =======
npm ERR! {
npm ERR!   "require...'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/micahlt/.npm/_logs/2020-08-08T03_55_51_875Z-debug.log
```

### Expected Behavior:
`cordova-android@^9.0.0` is installed.

### Steps To Reproduce:
Run `npm install --save-dev cordova-android@^9.0.0`

### Environment:
- OS: Ubuntu 20.04
- Node: 12.18.2
- NPM: 6.14.5

**Comment by ljharb** [comment]
Looks like maybe your package.json has git diff conflict markers in it?

**Comment by micahlt** [comment]
Yep, sorry about that 👍
