### ISSUE TITLE
[BUG] <cb() never called!>

### ISSUE THREAD

**Issue by skyfall17** [npm/cli#1647]
### Current Behavior:
Ran npm install on React app within git bash. Ran into this error.

### Expected Behavior:
Expected npm to install packages

### Environment:
- OS: Windows 10
- Node: 14.3.0
- NPM: 6.14.5

[2020-08-09T20_23_42_549Z-debug.log](https://github.com/npm/cli/files/5048361/2020-08-09T20_23_42_549Z-debug.log)

**Comment by bivas6** [comment]
Same for me, trying to install microsoft-cognitive-services-speech-sdk.

NPM: 6.14.4
NODE: 12.18.0
OS: WIN 10

**Comment by orgads** [comment]
That would be `microsoft-cognitiveservices-speech-sdk`. Works for me.
