### ISSUE TITLE
[BUG] Im new and started learning how to code in node

### ISSUE THREAD

**Issue by Vardhan142** [npm/cli#1653]
### Current Behavior:
an error occurred while trying to install lite server

### Expected Behavior:
installing lite server

Debug log:
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'audit',
1 verbose cli   'fix'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose config Skipping project config: C:\Users\vardh/.npmrc. (matches userconfig)
5 verbose npm-session e493788ba3ebc660
6 verbose stack Error: No package.json found: Cannot audit a project without a package.json
6 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\audit.js:164:19
6 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
6 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:514:35)
6 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:574:18)
6 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:619:10)
6 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:699:18)
6 verbose stack     at Promise._fulfill (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:643:18)
6 verbose stack     at PromiseArray._resolve (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise_array.js:126:19)
6 verbose stack     at PromiseArray._promiseFulfilled (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise_array.js:144:14)
6 verbose stack     at PromiseArray._iterate (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise_array.js:114:31)
6 verbose stack     at PromiseArray.init [as _init] (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise_array.js:78:10)
6 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:571:21)
6 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:619:10)
6 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:699:18)
6 verbose stack     at Promise._fulfill (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:643:18)
6 verbose stack     at PromiseArray._resolve (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise_array.js:126:19)
7 verbose cwd C:\Users\vardh
8 verbose Windows_NT 10.0.18362
9 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "audit" "fix"
10 verbose node v12.18.3
11 verbose npm  v6.14.6
12 error code EAUDITNOPJSON
13 error audit No package.json found: Cannot audit a project without a package.json
14 verbose exit [ 1, true ]

### Environment:
- OS: Windows 10
- Node: 12.18.3
- NPM: 6.14.6
-->

**Comment by darcyclarke** [comment]
`Error: No package.json found: Cannot audit a project without a package.json` - looks like you haven't set up your project yet. Before installing a package, you should run `npm init` in the directory you'd like to start your project in; And/or manually create a `package.json` file so that `npm` can add/audit the dependency you'd like to install. If you'd like to install a dependency [globally](https://docs.npmjs.com/downloading-and-installing-packages-globally), you can run `npm` with `-g` or `--global` (ex. `npm install -g http-server` where ["http-server"](https://npmjs.com/package/http-server) is the name of the package I'm installing globally)
