### ISSUE TITLE
[BUG] npm v7 does not preserve indentation style

### ISSUE THREAD

**Issue by valtlai** [npm/cli#1662]
### Current Behavior:
The indentation style in `package.json` and `package-lock.json` is not preserved.

### Expected Behavior:
For example, if `package.json` is indented using tabs, the tabs should be preserved and `package-lock.json` should use tabs too. Similarly, the number of the spaces used for indentation should be preserved.

This is the behavior in npm v6.

### Steps To Reproduce:
1. Create a `package.json` with tab indentation:
```json
{
	"private": true
}
```
2. Install a package:
```json
npm install globals
```
3. See how the tabs have gone:
```json
{
  "private": true,
  "dependencies": {
    "globals": "^13.2.0"
  }
}
```

### Environment:
- OS: macOS 10.15.6
- Node: 14.7.0
- NPM: 7.0.0-beta.4

**Comment by ljharb** [comment]
oof, this is a critical showstopper regression :-/

**Comment by MylesBorins** [comment]
I've seen this reproduce locally

**Comment by isaacs** [comment]
Yep, that's a bug.

**Comment by valtlai** [comment]
The indentation style of the existing files is now preserved, but a newly created `package-lock.json` does not use the indentation style of `package.json`.

**Comment by ruyadorno** [comment]
hi @valtlai thanks for reporting these issues :smile: the `package-lock.json` auto-format using same indentation style from `package.json` have now landed in the latest beta release `v7.0.0-beta.13` - as usual you can try it out with:

```
npm i -g npm@next-7
```

Let us know if you find more issues 😊 Thanks again!

**Comment by 9oelM** [comment]
I am using npm@7.18.1 and able to reproduce this issue. For example: https://github.com/9oelM/youtube-lite/commit/71043202956059430d08dfa9a9c7b3c3af3574f9. This is actually a commit made by Renovate bot, and it uses npm 7. You can see that package-lock.json has the same number of lines added and deleted.. which just means that it does not preserve indentation.

![image](https://user-images.githubusercontent.com/22465806/122777462-051d0b80-d2e7-11eb-9a75-1824acbbb775.png)

If you are in doubt of the version Renovate uses, there are also other commits that I made; for example: https://github.com/9oelM/youtube-lite/commit/f3d1460486312b905b90e592984642614bd667be 
This commit was made by myself and it still does not respect existing indent.
![image](https://user-images.githubusercontent.com/22465806/122777892-6d6bed00-d2e7-11eb-99c7-fb4964322b9c.png)

**Comment by gjoseph** [comment]
@ruyadorno This issue seems to have popped back up (I'm using 7.24.2)

**Comment by gjoseph** [comment]
... and reverting to 7.24.1 fixes that problem

**Comment by gjoseph** [comment]
(I've also tried 8.1.1 without success)

**Comment by isaacs** [comment]
@gjoseph In npm v8, it will format `package-lock.json` to match `package.json`.

I'm not saying that's the right thing to do, and I somewhat agree that, in lieu of an explicit format option, is should preserve whatever is there.  But that's what's happening now.  If you want your package-lock.json to be indented a particular way, then you have to have your package.json indented in the same fashion, and it will keep them in sync.

If you'd like it to do a different thing, please open a new issue.  The OP here is fixed, and what you're proposing (while imo reasonable) is a new change from that design.

**Comment by gjoseph** [comment]
Thanks for the response @isaacs - the odd thing is, both my `package-lock.json` and `package.json` are formatted by the same prettier rules, as far as I know (I have a prettier-check in CI, which is how I noticed this change)

I did open #3948 btw 😬

**Comment by gjoseph** [comment]
Well, I don't know what I was doing differently the other day, because I'm not able to reproduce now -- this may have been related to Lerna, which I had (probably wrongly) assumed was only causing different lock issues in the sub-packages lock files (i.e after reverting to 7.24.1, only the issues in sub-packages remained, so I assumed npm itself was causing the issues I saw in the root look file)

I've now gotten rid of Lerna altogether and don't see this issue again.

**Comment by ephemer** [comment]
I am experiencing this bug with 8.1.0.

Normally our `package-lock.json` is indented with 2 spaces (no idea why) and `package.json` is indented with 4 spaces. If I add a package `npm i some-package` then `npm` will rewrite `package-lock.json` with 4 spaces (presumably to match `package.json`) but if I run `npm install` by itself then it will re-format to the 2 spaces version. I don't really mind which it stays with, but it's quite annoying to have to catch this in every PR before merge.

@isaacs FYI
