### ISSUE TITLE
[BUG] error cb() never called!

### ISSUE THREAD

**Issue by vo-mary-PFG** [npm/cli#1671]
### Current Behavior:
When attempting to run: npm install -g aws-azure-login, I received the following error:
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'npmc@latest',
1 verbose cli   '--global',
1 verbose cli   '--prefix',
1 verbose cli   'C:\\Users\\v123361\\AppData\\Roaming\\npm-cache\\_npx\\17092',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--json'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose npm-session ad9b7e47a70f69d7
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 407 https://registry.npmjs.org/npmc 174ms
8 timing npm Completed in 964ms
9 error cb() never called!
10 error This is an error with npm itself. Please report this error at:
11 error <https://npm.community>

I have tried:
npm cache clean --force

### Steps To Reproduce:
Open command prompt
Execute: npm install -g aws-azure-login

**Comment by ne-cgi** [comment]
The same occurs in trying to install "newman"

**Steps to Reproduce**
Open command prompt
Execute command: npm install -g newman

**Comment by Jay-Shu** [comment]
This same occurs when installing oidc-provider
With a mess of 2130 warn tar ENOSPC: no space left on device

Execute command: npm install oidc-provider

**Comment by vo-mary-PFG** [comment]
I uninstalled npm and nodejs and reinstalled. This seem to fix my issue
