### ISSUE TITLE
cb() never Called

### ISSUE THREAD

**Issue by cyberblitz** [npm/cli#1696]
reporting error as suggested by error information . 
Tried uploading log file but it won't let me.. Here's whats was in the log:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   '-g',
1 verbose cli   'powerbi-visuals-tools'
1 verbose cli ]
2 info using npm@6.14.7
3 info using node@v14.8.0
4 verbose npm-session fb296c27df366263
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 500 https://registry.npmjs.org/powerbi-visuals-tools 79252ms attempt #3
8 timing npm Completed in 80146ms
9 error cb() never called!
10 error This is an error with npm itself. Please report this error at:
11 error <https://npm.community>
```

**Comment by 1brian987654** [comment]
seems like npm cannot fetch required packages from the current registry.
maybe you should try to set another registry, it's easy to get one by googling.

**Comment by darcyclarke** [comment]
**Closing:** Please use one of our issue templates if you believe you've found a bug in npm itself; As well, please check to ensure that there is no existing duplicate issue for that problem (ref. https://github.com/npm/cli/issues/new/choose)
