### ISSUE TITLE
[HELP] 'koa2-session-redis' Connect Retry mechanism is not working 

### ISSUE THREAD

**Issue by jainath23** [npm/cli#1705]
I have used 'koa2-session-redis' NPM to connect Azure Redis with below config-
{
  "host": "MyInsightsProdRedis.redis.cache.windows.net",
  "port": "6380",
  "password": "XXXX",
  "connect_timeout": "5000",
  "tls": "{\"servername\":\"MyInsightsProdRedis.redis.cache.windows.net\"}",
  "retry_max_delay": "500",
  "max_attempts": "9"
}

But above config still unable to reconnect and time exceeded, and the connection closed with Redis.

Can you please suggest a better approach to Reconnect with Azure Redis using 'koa2-session-redis'??

Thanks,
Jai

**Comment by darcyclarke** [comment]
Closing: We do not provide support for `koa`. Sorry.
