### ISSUE TITLE
[BUG] package.json is removed from my monorepo

### ISSUE THREAD

**Issue by ghost** [npm/cli#1710]
### Current Behavior:
`npm install` will tell dependency has no package.json. You can see this dependency [q.helpers](https://github.com/hydroper/q.x/tree/master/q.helpers) has a package.json.

Log:

> npm ERR! code ENOPACKAGEJSON
> npm ERR! package.json Non-registry package missing package.json: q.x@https://github.com/hydroper/q.x/tree/master/q.helpers.
> npm ERR! package.json npm can't find a package.json file in your current directory.

### Expected Behavior:
`npm install` without Error.

### Steps To Reproduce:
- `npm init -y`
- Write this in `package.json`:

```json
"dependencies": {
    "q.x": "https://github.com/hydroper/q.x/tree/master/q.helpers"
}
```

(I did also try some other times making q.x rely on q.helpers by a `file:` URL and, when I relied on q.x, NPM again told package.json doesn't exist in q.helpers.)

- `npm install`

### Environment:

OS: Windows 10
Node: 12.18.1
npm: 6.14.5

**Comment by alasdairhurst** [comment]
@hydroper  the git URL can be http/ssh and resolve a particular tag, commit or branch as noted in https://docs.npmjs.com/files/package.json, but pretty sure that you can't point to a specific directory like you're trying to do. It has to be the root of the repository.

I think the only other way you can do it via git is committing a tar.gz file containing your module and using the git+file protocol (i presume that's how it's used), but there's no examples of this that i can find.

**Comment by ghost** [comment]
@alasdairhurst Interesting, but archiving the subpackage complicates maintenance. I've used Lerna instead, which allows to publish all subpackages in a single command...
