### ISSUE TITLE
npm ERR!, npm  v3.10.10, node v12.18.3

### ISSUE THREAD

**Issue by cmdntd** [npm/cli#1712]
I have this error when run any npm command

npm ERR! Linux 3.10.0-1127.10.1.el7.x86_64
npm ERR! argv "/usr/local/n/versions/node/12.18.3/bin/node" "/bin/npm" "update"
npm ERR! node v12.18.3
npm ERR! npm  v3.10.10
npm ERR! cb.apply is not a function
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/npm-debug.log

**Comment by ljharb** [comment]
node 12 ships with npm v6.14.6; npm 3 won't ever work with it, and I have no idea how you got such an ancient version of npm installed with a modern version of node.

**Comment by cmdntd** [comment]
Ok, I removed and reinstalled all of them. And now it is ok in lastest version
