### ISSUE TITLE
[BUG] <cb() never called!>

### ISSUE THREAD

**Issue by hych007** [npm/cli#1720]
### Steps To Reproduce:
steps to reproduce the behavior:
1.git clone https://github.com/jitsi/jitsi-meet-electron
2. npm install --global --production windows-build-tools
3.npm install -g node-gyp
4.npm install
5.see error 
error cb() never called!
This is an error with npm itself. Please report this error at:<https://npm.community>

### Environment:
- OS: win10 - x64
- Node: 14.8.0 -x64
- npm: 6.14.7 -x64

**Comment by hych007** [comment]
npm i --force seems fixed it!

**Comment by AKASHGJHKJ** [comment]
F:\CD\dev\projects>npm install -g create-react-app
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\akash das\AppData\Roaming\npm-cache\_logs\2020-08-25T09_41_00_429Z-debug.log

**Comment by 1brian987654** [comment]
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tanz/.npm/_logs/2020-08-26T06_50_49_637Z-debug.log

**Comment by 1brian987654** [comment]
> npm i --force seems fixed it!

I tried this command but doesn't work.


```
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR! https://npm.community

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/tanz/.npm/_logs/2020-08-26T06_50_49_637Z-debug.log
```

from log I saw fetch GET 504.
```
2 info using npm@6.14.7
3 info using node@v14.7.0
4 verbose npm-session 15580dea96615ff5
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 504 https://registry.npmjs.org/create-react-app 250143ms attempt #3
8 timing npm Completed in 250364ms
9 error cb() never called!
10 error This is an error with npm itself. Please report this error at:
11 error <https://npm.community>
```
I run `npm get registry` to check its registry, it is `https://registry.npmjs.org/`
then I remember, there is a "WALL" that stop npm fetching components.
so I set another mirror to support npm. you can google and get what you want.
**finally, it works.**

**Comment by lewsea** [comment]
> I run `npm get registry` to check its registry, it is `https://registry.npmjs.org/`
> then I remember, there is a "WALL" that stop npm fetching components.
> so I set another mirror to support npm. you can google and get what you want.
> **finally, it works.**

how ?

**Comment by hych007** [comment]
cross the wall
