### ISSUE TITLE
[BUG] Hippocratic license incorrectly identified as invalid SPDX expression

### ISSUE THREAD

**Issue by codemacabre** [npm/cli#1724]
# What / Why
Packages using the [Hippocratic License]() output the following warning when installed:
```sh
npm WARN [package name] license should be a valid SPDX license expression
```
## Where
This has been tested on [numerous repos](https://github.com/search?q=hippocratic-2.1&type=Code) using the  valid `Hippocratic-2.1` license expression, all with the same npm warning. This occurred on earlier verions of node, but also when upgrading to the latest 14.8.0 & npm 6.14.7.

### Steps to Reproduce
1. `git clone` [any repo with the Hippocratic license](https://github.com/search?q=hippocratic-2.1&type=Code)
2. `npm install`

### Expected Behavior
The Hippocratic License is a valid license, listed in the SPDX license list with the expression `Hippocratic-2.1`. This should be recognised by npm's license parser and should not produce a warning.

## References
+ [Hippocratic License](https://firstdonoharm.dev/)
+ [Hippocratic License in the SPDX license list](https://spdx.org/licenses/Hippocratic-2.1.html)
+ [npm package.json license documentation](https://docs.npmjs.com/files/package.json#license)

**Comment by jmannanc** [comment]
This is dependent on https://github.com/shinnn/spdx-license-ids/pull/19 being merged and then eventually https://github.com/kemitchell/validate-npm-package-license.js getting updated.

**Comment by codemacabre** [comment]
Thanks @SneakyFish5, that's opened my eyes to the fact that there's a bit of a larger issue here in that npm licensing is dependent on the [spdx-license-ids](https://github.com/shinnn/spdx-license-ids) package being kept up-to-date, which is managed by a lone maintainer. This single point of failure is clearly a bit of a bottleneck as it appears there are [PRs going back to Feb](https://github.com/shinnn/spdx-license-ids/pull/17) that haven't been merged and the repo's last update was 14 months of go at time of writing.

@kemitchell makes [a very good suggestion](https://github.com/shinnn/spdx-license-ids/pull/19#issuecomment-668306486) in his PR of either others being added to this repo (which may not be possible given @shinnn's absence), or moving the repo to an organisation. Perhaps a fork of his repo and maintaining elsewhere is a more suitable option?

~~How would we even go about this given the [5 million+ dependents](https://github.com/shinnn/spdx-license-ids/network/dependents?package_id=UGFja2FnZS0xNDQ2OTk1Mw%3D%3D)?~~ To keep the scope focused here, I'm retracting this final musing. The issue at hand is npm's use, not the other 5 million.

**Comment by kemitchell** [comment]
I am happy to move the package into @jslicense, but people come first, code second.

@CodeMacabre you mentioned @shinnn's absence. Do you know if he's okay, or needs support? I haven't been able to reach him.

**Comment by codemacabre** [comment]
> people come first, code second

100% agree and no, unfortunately I'm new to this whole situation and looking at the history it looks like @shinnn has disappeared as of November 2019 and their website appears to be down. I don't know who they are but I'm also concerned, particularly given the current climate.

If anyone does know them, please do ping us; I'd be willing to support any way I can.

**Comment by kemitchell** [comment]
https://www.npmjs.com/package/spdx-license-identifiers

All the intermediate packages are mine. But I'm out of time for today.

**Comment by codemacabre** [comment]
> This is dependent on [jslicense/spdx-license-ids#19](https://github.com/jslicense/spdx-license-ids/pull/19) being merged and then eventually https://github.com/kemitchell/validate-npm-package-license.js getting updated.

@kemitchell I can see spdx-license-ids has been updated but `Hippocratic-2.1` doesn't appear to be recognised as valid yet. Does validate-npm-package-license.js need updating too?

**Comment by kemitchell** [comment]
@CodeMacabre if the issue is npm behavior, please let npm know.

**Comment by kemitchell** [comment]
npm@7.0.1 is shipping spdx-license-ids@3.0.6, which has `Hippocratic-2.1`. Check your npm version?

**Comment by codemacabre** [comment]
🤦🏼‍♂️ That would explain it. Thank you!
