### ISSUE TITLE
[BUG] Remove update npm message

### ISSUE THREAD

**Issue by Aditya94A** [npm/cli#1727]
![image](https://user-images.githubusercontent.com/13274079/91321761-96f9dc00-e7dc-11ea-8194-acd750ad1b0f.png)

This is likely contributing to cognitive overload equivalent to tens of thousands of hours each day across the world and sucking developers in "busy work" that leads to nothing.

I have ~6 active projects in three programming languages, collectively using perhaps >200 direct dependencies. If I actively track minor version upgrades of each of those then that is all I will be able to do all day.

npm is wonderful and wonderfully stable for long periods. Please disable this attention-deficit-inducing message by default.

**Comment by ljharb** [comment]
npm is global, you’d only have to run it once.

(Most projects do actively update every minor or patch version of deps, btw, by using services like dependabot)

**Comment by ruyadorno** [comment]
@AdityaAnand1 there's an option to remove this prompt, you can add a `update-notifier=false` line to your `.npmrc` file OR run any npm command with that option set to false, e.g: `npm install --update-notifier=false`
