### ISSUE TITLE
[BUG] 7.x npm prune --production removes dev deps but leaves .bin symlink to dep (breaks serverless packaging in our case)

### ISSUE THREAD

**Issue by scamden** [npm/cli#1728]
### Current Behavior:
running `npm prune --production` removes dev deps as expected but leaves symlinks in `node_modules/.bin`

### Expected Behavior:
symlinks are removed for packages that are removed

### Steps To Reproduce:
1. Create a empty package
2. `npm i -D acorn`
2. `npm prune --production`
3. `ls node_modules/.bin/acorn`
4.  notice that it exists but `ls node_modules/acorn` doesn't exist

### Environment:
node 10
mac os
npm 7 beta7

**Comment by scamden** [comment]
`find . -type l -exec test ! -e {} \; -delete`

our current work around for any who shamble in here before the bug is fixed ^

**Comment by ruyadorno** [comment]
Thanks for the bug report @scamden 😄 This should have been fixed in the latest pre-release `v7.0.0-beta.9` 😊 let me know if you get a chance to test it.

**Comment by scamden** [comment]
> Thanks for the bug report @scamden 😄 This should have been fixed in the latest pre-release `v7.0.0-beta.9` 😊 let me know if you get a chance to test it.

thanks so much! will test as soon as I find the time!

**Comment by scamden** [comment]
yep looks fixed to me thanks again!
