### ISSUE TITLE
NPM is not working

### ISSUE THREAD

**Issue by cathy812** [npm/cli#1731]
Continuously getting this error when using NPM-cli, executing the command "npm ci":
10:58:07  + npm ci
10:58:34  npm ERR! cb() never called!
10:58:34  
10:58:34  npm ERR! This is an error with npm itself. Please report this error at:
10:58:34  npm ERR!     <https://npm.community>

Would you please take a look? This is not the first time notice that.

**Comment by cathy812** [comment]
This issue happened again today.

**Comment by darcyclarke** [comment]
**Closing:** Please use one of our issue templates if you believe you've found a bug in npm itself; As well, please check to ensure that there is no existing duplicate issue for that problem (ref. https://github.com/npm/cli/issues/new/choose)
