### ISSUE TITLE
[BUG] postinstall not exec when run npm install xxx, but npm install do

### ISSUE THREAD

**Issue by zitup** [npm/cli#1732]
### Current Behavior:
postinstall don't exec when run `npm install xxx`, but just run `npm install` trigger execution 
AND, script in node_modules/.hooks/postinstall will exec both in `npm install xxx` and `npm install`

### Expected Behavior:
postinstall exec too when run `npm install xxx`

### Steps To Reproduce:
package.json
```json
 "scripts": {
    "postinstall": "node script.js"
  },
```
script
```js
#!/usr/bin/env node

console.log("postinstall...");

console.log("    " + process.env.npm_package_name);

console.log("    " + process.env.PWD);
```

### Environment:

- OS: macOS 10.15.5
- Node: 12.15.0
- npm: 6.13.4

**Comment by zitup** [comment]
Nobody answered, closed.

**Comment by karlhorky** [comment]
I think this is known behavior for the npm CLI: https://npm.community/t/preinstall-npm-hook-doesnt-execute-when-installing-a-specific-package/2505

Yarn does run the `postinstall` after every install (which seems like the better option).

**Comment by zitup** [comment]
YES, yarn does well, I would love to see npm upgrade :)  
  
And FYI @karlhorky , I discovered this problem when i was developing a [module](https://github.com/zitup/type-sync) like typesync, but npm's problems stuck me

I mentioned above is one of these, another one is when you install two package use `npm install xxx1 xxx2`, script in `./hooks/postinstall ` will only process one, so strange...

In addition, i use `exec('npm install @types/xxx')` to install types package, but don't know why it executes very slowly, maybe add `@types/xxx` to `package.json` and exec `npm install` is a good idea.

And, 
> in npm v6, a postinstall hook script, for example, runs once for every package that has been installed. So this means that with a node_modules/.hooks/postinstall script, if you run npm install with your package.json containing 20 dependencies, this script will run at least 20 times, and even more if those dependencies specify transitive dependencies...

It's true...
