### ISSUE TITLE
[BUG] Remove or change unhelpful logging message from npm audit fix --force

### ISSUE THREAD

**Issue by furkle** [npm/cli#1736]
### Current Behavior:
The CLI emits an unhelpful message when one attempts to force-resolve a security issue with `npm audit fix --force`.

The message is as follows:

`npm WARN using --force I sure hope you know what you are doing.`

### Expected Behavior:
One or more of the following:
- A clear description of the failure cases one might encounter in force-resolving a security issue;
- A link to similar materials, like Google often does with Chrome errors;
- A removal of the log line in question entirely.

### Steps To Reproduce:
- Force resolve a security issue.
- This message always comes up.

### Environment:
Everywhere.

**Comment by ruyadorno** [comment]
hi @furkle thanks for the feedback!

We got this same feedback in the past and now that WARN log message is no longer present in **npm7**, here's an example of how it looks like in the latest beta pre-release:

```
$npm i -f
npm WARN using --force Recommended protections disabled.

up to date, audited 1 package in 501ms

found 0 vulnerabilities
```

**Comment by furkle** [comment]
Thanks so much!
