### ISSUE TITLE
[BUG]  cb() never called!

### ISSUE THREAD

**Issue by zhangXuanhao996** [npm/cli#1737]
cb() never called!

**Comment by meilZhu** [comment]
I also encountered this problem and asked to solve it

**Comment by RCVarley** [comment]
I got this error when adding storybook to a new VueJS project using the `@vue/cli` (`vue add storybook`).

```
9686 http fetch GET 200 https://cdn.npm.taobao.org/polished/-/polished-3.6.5.tgz 335209ms
9687 silly extract polished@^3.4.4 extracted to C:\Users\[user]\code\address-manager\node_modules\.staging\polished-d941e2b9 (335211ms)
9688 timing npm Completed in 389597ms
9689 error cb() never called!
```

This error was generated while attempting to use NPM. 
I also tried Yarn and it failed to fetch `polished-3.6.5.tgz`. I wonder if this was happening in the background.

Weirdly, I'm in the UK, yet `@vue/cli` seems to default to a Chinese NPM mirror... Do you think this could be the issue? 

I'll try to force it to use a different NPM mirror and see if that fixes anything.

**Comment by RCVarley** [comment]
I got it working for VueJS! 

You can change the registry to use with `vue create address-manager -r https://registry.npmjs.org`.

There is also a setting in `.vuerc` that you can change (`"useTaobaoRegistry": false,`).

Try changing the NPM registry in `.npmrc`.  The default is `https://registry.npmjs.org`.

### Links:
https://docs.npmjs.com/using-npm/registry.html
https://cli.vuejs.org/guide/creating-a-project.html#vue-create
https://medium.com/vuetify/productivity-in-vue-part-2-1dc209062cae

**Comment by deniz-blue** [comment]
I'm having this issue too, and I'm not even using vue... This happens when I try to install any package

**Comment by darcyclarke** [comment]
**Closing:** Please use one of our issue templates if you believe you've found a bug in npm itself; As well, please check to ensure that there is no existing duplicate issue for that problem (ref. https://github.com/npm/cli/issues/new/choose)
