### ISSUE TITLE
[Question] Rename Sill

### ISSUE THREAD

**Issue by JeswinSunsi** [npm/cli#1754]
I do understand that terms like sill for silly add fun to the program on the dev side, but as a new learner I found it pretty hard to understand what sill meant. I wonder if the devs could change that.

**Comment by darcyclarke** [comment]
Hey @JeswinSunsi! Thanks for the feedback!

Apologize you had a hard time understanding the flag's intents. We do have aliases for these flags as well: `-d` for `--info`, `-dd` for `--verbose` & `-ddd` for `--silly` (ref: https://docs.npmjs.com/misc/config#shorthands-and-other-cli-niceties). 

As you can tell by the aliases, we allude to the idea that you're getting more of the same *kind* of information with more of the same character. We probably won't be adding yet another alias for the loglevel `silly` & changing it's name outright would be a breaking change, so I'm going to close this for now.
