### ISSUE TITLE
[BUG] npm react-datepicker alignment issue in iOS devices

### ISSUE THREAD

**Issue by SureshSSI** [npm/cli#1759]
There is an alignment issue in iOS devices like iPad, iPhone when the device goes from landscape to portrait mode.

The react-datepicker is working fine when the device is rotated from portrait to landscape, but it is not working fine when it is again rotated from landscape to portrait.

I have attached the screenshot of the issue below..

Portrait mode 👍 
![image](https://user-images.githubusercontent.com/65526680/92068341-4ed24f00-edc4-11ea-99e9-bf09162859e3.png)

Landscape mode 👍 
![image](https://user-images.githubusercontent.com/65526680/92068416-788b7600-edc4-11ea-8eac-d219abf52eea.png)

Again Portrait mode 👎 
![image](https://user-images.githubusercontent.com/65526680/92068439-8c36dc80-edc4-11ea-827e-c4d6081c87aa.png)

**Environment :** 
Windows 10 64-bit
Node v12.10.0
npm 6.10.3
iPad Mini (Safari 13 version, Chrome latest version)
iPhone (Safari 13 version)

**Comment by darcyclarke** [comment]
Closing: we don't do support for specific npm packages.
