### ISSUE TITLE
[BUG] npm update fails with workspace dependencies

### ISSUE THREAD

**Issue by jimfranke** [npm/cli#1763]
### Current Behavior:
Running ``npm update`` in a directory where ``package.json`` contains dependencies to local workspace packages, results in a HTTP 404 error because npm tries incorrectly to install from the remote registry.

### Expected Behavior:
Expecting ``npm update`` to succeed when ``package.json`` contains local workspace dependencies.

### Steps To Reproduce:
- Create ``package.json`` with dependencies or devDependencies containing local workspace package.
- Run ``npm update`` in directory.

### Environment:
- OS: Windows 10
- Node: 14.9.0
- npm: 7.0.0-beta-8

**Comment by ruyadorno** [comment]
This should have been fixed in the current pre-release `v7.0.0-beta.9` @jimfranke 😊 let me know if you get a change to test it 😄
