### ISSUE TITLE
[BUG] `npm install` does not sort dependencies alphabetically

### ISSUE THREAD

**Issue by valtlai** [npm/cli#1766]
### Current Behavior:
`npm install` saves a newly installed dependency at the end of the dependency array.

### Expected Behavior:
The dependency should be saved so that the array is sorted in alphabetical order.

### Steps To Reproduce:
1) Run `npm install prismjs`.
2) Run `npm install globals`.
3) See how `globals` is sorted after `prismjs` although `globals` comes before `prismjs` in alphabetical order.

### Environment:
- OS: MacOS 10.15.6
- Node: 14.8.0
- npm: 7.0.0-beta.9

**Comment by ruyadorno** [comment]
fixed in `v7.0.0-beta.11` 😄 thanks for the feedback!

**Comment by JoshMcCullough** [comment]
I'm still seeing this behavior, "randomly" with NPM v7.6.0.

**Comment by ljharb** [comment]
@JoshMcCullough try with v7.14.0, v7.6 is quite out of date at this point.
