### ISSUE TITLE
When I execute npm install got this errornpm ERR! cb() never called! 

### ISSUE THREAD

**Issue by AvinashShwe** [npm/cli#1768]
When I execute npm install got this errornpm ERR! cb() never called!

**Comment by Innovandco** [comment]
http://www.innovandco.net
http://www.wms-conseil.fr
http://www.functionalprog.fr

www.innovandco.net
www.wms-conseil.fr
www.functionalprog.fr

**Comment by darcyclarke** [comment]
Closing: This is duplicative to a few other issues we already are tracking, doesn't use our bug template &, ultimately, we believe we have a fix we're about the release that should resolve many of those errors.
