### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by ruslankakhramanov** [npm/cli#1771]
Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2020-09-06T11_22_24_685Z-debug.log

Aborting installation.
  npm install --save --save-exact --loglevel error react react-dom react-scripts cra-template has failed.

Deleting generated file... package.json
Deleting my-app/ from F:\react-kabzda-kak-prosto
Done.

**Comment by darcyclarke** [comment]
**Closing:** Please use one of our issue templates if you believe you've found a bug in npm itself; As well, please check to ensure that there is no existing duplicate issue for that problem (ref. https://github.com/npm/cli/issues/new/choose)
