### ISSUE TITLE
npm cb() never called

### ISSUE THREAD

**Issue by MJMarkjohn** [npm/cli#1774]
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:

**Comment by communque** [comment]
Received a possibly related error...

`npm install -g npm-check-updates`

results in...

```
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>
```

**Comment by Noha-Ismail** [comment]
I have the same issue now

**Comment by cardoX007** [comment]
I have the same issue too

**Comment by Samiksha-C** [comment]
I am facing the same issue too.

**Comment by emmsdan** [comment]
Same issue, but mine happened even before any dependency was installed...
That's the only error I am having.

```
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-10T08_32_39_466Z-debug.log
The command '/bin/sh -c npm install' returned a non-zero code: 1
```

Am having this issue when running this in a Docker instance...

**Comment by darcyclarke** [comment]
**Closing:** Please use one of our issue templates if you believe you've found a bug in npm itself; As well, please check to ensure that there is no existing duplicate issue for that problem (ref. https://github.com/npm/cli/issues/new/choose)
