### ISSUE TITLE
[BUG] Refusing to install discord.js as a dependency of itself

### ISSUE THREAD

**Issue by PMP-Studios** [npm/cli#1778]
I was trying to install the package **discord.js** and I get this error every time:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'i', 'discord.js@^11.5.1' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData discord.js@^11.5.1
8 silly fetchNamedPackageData discord.js
9 silly mapToRegistry name discord.js
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/discord.js
13 verbose request uri https://registry.npmjs.org/discord.js
14 verbose request no auth needed
15 info attempt registry request try #1 at 9:23:38 AM
16 verbose request id ea4348a284cdea0f
17 http request GET https://registry.npmjs.org/discord.js
18 http 200 https://registry.npmjs.org/discord.js
19 verbose headers { date: 'Tue, 08 Sep 2020 14:23:39 GMT',
19 verbose headers   'content-type': 'application/json',
19 verbose headers   'transfer-encoding': 'chunked',
19 verbose headers   connection: 'keep-alive',
19 verbose headers   'set-cookie':
19 verbose headers    [ '__cfduid=d01b4942d23eff7499defbf70a22626a21599575018; expires=Thu, 08-Oct-20 14:23:38 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
19 verbose headers   'cf-ray': '5cf9541cbfd9e222-ORD',
19 verbose headers   age: '2776',
19 verbose headers   'cache-control': 'public, max-age=300',
19 verbose headers   etag: 'W/"46bd2a18c3aef582b9085486accb260c"',
19 verbose headers   'last-modified': 'Sat, 15 Aug 2020 18:39:23 GMT',
19 verbose headers   vary: 'accept-encoding, accept',
19 verbose headers   'cf-cache-status': 'HIT',
19 verbose headers   'cf-request-id': '050fb2e5ef0000e2229f8a8200000001',
19 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
19 verbose headers   server: 'cloudflare',
19 verbose headers   'content-encoding': 'gzip' }
20 silly get cb [ 200,
20 silly get   { date: 'Tue, 08 Sep 2020 14:23:39 GMT',
20 silly get     'content-type': 'application/json',
20 silly get     'transfer-encoding': 'chunked',
20 silly get     connection: 'keep-alive',
20 silly get     'set-cookie':
20 silly get      [ '__cfduid=d01b4942d23eff7499defbf70a22626a21599575018; expires=Thu, 08-Oct-20 14:23:38 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
20 silly get     'cf-ray': '5cf9541cbfd9e222-ORD',
20 silly get     age: '2776',
20 silly get     'cache-control': 'public, max-age=300',
20 silly get     etag: 'W/"46bd2a18c3aef582b9085486accb260c"',
20 silly get     'last-modified': 'Sat, 15 Aug 2020 18:39:23 GMT',
20 silly get     vary: 'accept-encoding, accept',
20 silly get     'cf-cache-status': 'HIT',
20 silly get     'cf-request-id': '050fb2e5ef0000e2229f8a8200000001',
20 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
20 silly get     server: 'cloudflare',
20 silly get     'content-encoding': 'gzip' } ]
21 verbose get saving discord.js to /root/.npm/registry.npmjs.org/discord.js/.cache.json
22 verbose makeDirectory /root/.npm creation not in flight; initializing
23 silly makeDirectory /root/.npm uid: 0 gid: 0
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly rollbackFailedOptional Starting
37 silly rollbackFailedOptional Finishing
38 silly runTopLevelLifecycles Starting
39 silly runTopLevelLifecycles Finishing
40 silly install printInstalled
41 verbose stack Error: Refusing to install discord.js as a dependency of itself
41 verbose stack     at checkSelf (/usr/share/npm/lib/install/validate-args.js:40:14)
41 verbose stack     at Array.<anonymous> (/usr/share/npm/node_modules/slide/lib/bind-actor.js:15:8)
41 verbose stack     at LOOP (/usr/share/npm/node_modules/slide/lib/chain.js:15:14)
41 verbose stack     at chain (/usr/share/npm/node_modules/slide/lib/chain.js:20:5)
41 verbose stack     at /usr/share/npm/lib/install/validate-args.js:15:5
41 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:35
41 verbose stack     at Array.forEach (<anonymous>)
41 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:11
41 verbose stack     at Array.forEach (<anonymous>)
41 verbose stack     at asyncMap (/usr/share/npm/node_modules/slide/lib/async-map.js:51:8)
42 verbose cwd /home/pmpyonix
43 error Linux 4.15.0-117-generic
44 error argv "/usr/bin/node" "/usr/bin/npm" "i" "discord.js@^11.5.1"
45 error node v8.10.0
46 error npm  v3.5.2
47 error code ENOSELF
48 error Refusing to install discord.js as a dependency of itself
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]

[message (1).txt](https://github.com/npm/cli/files/5188904/message.1.txt)

**Comment by PMP-Studios** [comment]
Forget it! - I solved the problem

**Comment by oksouhhhhhhhhh** [comment]
how did u fix that problem? i have been having that issue for months! pls help me
