### ISSUE TITLE
Type 'MatCalendar<D>' is not assignable to type 'MatCalendar<ExtractDateTypeFromSelection<D>>

### ISSUE THREAD

**Issue by Rashmin-kaur** [npm/cli#1787]
using    
   "@angular/cdk": "^10.1.3",
    "@angular/common": "~10.0.14",
    "@angular/compiler": "~10.0.14",
    "@angular/core": "~10.0.14",
    "@angular/flex-layout": "^10.0.0-beta.32",
    "@angular/forms": "~10.0.14",
    "@angular/material": "^10.1.3", versions and simply install and imported, then getting error on ng-serve while it is working fine in angular 9. Please resolve.

Error
![Screenshot 2020-09-10 175856](https://user-images.githubusercontent.com/60466994/92729028-562ec500-f38f-11ea-9b42-ad0f0d579bc8.png)

**Comment by darcyclarke** [comment]
@Rashmin-kaur are you having issues **installing** a package? OR is this a problem with the package itself? It sounds like it may be the latter. The type error seems to be coming from starting your Angular project & some kind of type configuration issue with [`mat-daterangepicker`](https://www.npmjs.com/package/mat-daterangepicker)

If you run `npm ls mat-daterangepicker` you can figure out which of your dependencies - that you listed - is pulling that in & then you should check to see if things are configured & up-to-date (ex. you can run `npm outdated --depth=9999` to see all your deps & which could be safely updated or just `npm outdated mat-daterangepicker --depth=9999` to see that individual dep).

**Comment by xzegga** [comment]
Did you resolve this issue? I am experimenting the same issue on angular 10

**Comment by ljharb** [comment]
It has nothing to do with npm; it’s a typescript error.
