### ISSUE TITLE
[BUG] public couchdb mirror for html-to-draftjs is stale

### ISSUE THREAD

**Issue by SlNPacifist** [npm/cli#1790]
https://skimdb.npmjs.com is listed as official public couchdb mirror in https://docs.npmjs.com/using-npm/registry.html#can-i-run-my-own-private-registry. It is expected to have same information on packages as https://registry.npmjs.org/.

### Current Behavior:
Result for package `html-to-draftjs` is different.
https://registry.npmjs.org/html-to-draftjs responds with version 1.5.0
https://skimdb.npmjs.com/html-to-draftjs responds with version 1.4.0
https://replicate.npmjs.com/html-to-draftjs responds with version 1.4.0

### Expected Behavior:
All repositories respond with same version

### Steps To Reproduce:
Just go to https://skimdb.npmjs.com/html-to-draftjs in your browser

### Environment:
any

Sorry for submitting this issue here, I could not find a better place.
https://github.com/npm/registry sent me to https://npm.community/c/support/7
https://npm.community/c/support/7 said it is read-only: https://npm.community/t/these-forums-have-being-archived/10924/2
blog post https://blog.npmjs.org/post/188841555980/updates-to-community-docs-more?_ga=2.83881238.1848766798.1599744699-2104158000.1599744699 has nothing to say about registry and only place for submitting bug is here

**Comment by Innovandco** [comment]
http://www.innovandco.net
http://www.wms-conseil.fr
http://www.functionalprog.fr

www.innovandco.net
www.wms-conseil.fr
www.functionalprog.fr

**Comment by darcyclarke** [comment]
If you're having issues with the website and/or the registry, the right place to submit a bug report or get help is by filing a ticket with support at https://npmjs.com/support
