### ISSUE TITLE
Exito 

### ISSUE THREAD

**Issue by apprentable** [npm/cli#1798]
# What / Why

> n/a

## When

* n/a

## Where

* n/a

### Current Behavior

* n/a

### Steps to Reproduce

* n/a

### Expected Behavior

* n/a

## Who

* n/a

## References

* n/a

**Comment by Innovandco** [comment]
http://www.innovandco.net
http://www.wms-conseil.fr
http://www.functionalprog.fr

www.innovandco.net
www.wms-conseil.fr
www.functionalprog.fr
