### ISSUE TITLE
npm ci

### ISSUE THREAD

**Issue by apurv-thakur** [npm/cli#1803]
npm WARN prepare removing existing node_modules/ before installation
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\APURV\AppData\Roaming\npm-cache\_logs\2020-09-14T21_50_10_722Z-debug.log

**Comment by darcyclarke** [comment]
Please use the bug template.
