### ISSUE TITLE
[BUG] https://npmjs.com always gives internal server error, but not npmjs.com/package/x

### ISSUE THREAD

**Issue by Milo123459** [npm/cli#1804]
### Environment:

don't know what to put here it just gives errors whenever I go to https://npmjs.com but not when I go to a package

**Comment by darcyclarke** [comment]
If you're having issues with the website or registry, please file a ticket with support at https://npmjs.com/support or https://twitter.com/npm_support You can also see the current status of those properties at: https://status.npmjs.org
