### ISSUE TITLE
[BUG] npm ERR! cb() never called!

### ISSUE THREAD

**Issue by Gustavo10Destroyer** [npm/cli#1806]
Transtale it from PT BR

Eu estava instalando as dependêcias de um projeto(https://github.com/englercj/lttp) e estava correndo bem até que aparece:
--------------------------------------
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>
--------------------------------------
Então eu resolvi vir reportar isso aqui, alguém pode me ajudar?
![Screenshot_20200915-214450_Termux](https://user-images.githubusercontent.com/66029954/93279506-d2fddc80-f79d-11ea-8323-9f9d788f9545.jpg)

**Comment by Gustavo10Destroyer** [comment]
Nota: Eu uso o Node.JS no Termux e ele funciona muito bem, consigo instalar tudo na home do Termux, algumas dependêcias não podem ser instaladas fora da home do Termux, como o GIMP, Express, plugapi | Porque o armazenamento do android proíbe a criação de symlinks...

**Comment by darcyclarke** [comment]
Closing: Please use one of our issue templates if you think you've found an issue in the npm CLI itself: https://github.com/npm/cli/issues/new/choose
