### ISSUE TITLE
 react-material-ui-form-validator issue vision 2.1.1

### ISSUE THREAD

**Issue by adul-mo** [npm/cli#1807]
No CSS, incomplete screen rendering
```
<div class="**No CSS**">
</div>
```

**Comment by suiyun39** [comment]
Is this a problem with npm?
I think maybe should add issue in [react-material-ui-form-validator](https://github.com/NewOldMax/react-material-ui-form-validator)

**Comment by darcyclarke** [comment]
Closing: this isn't an issue with the `npm` cli.
