### ISSUE TITLE
[BUG] `npm ci` changes package.json

### ISSUE THREAD

**Issue by targos** [npm/cli#1811]
### Current Behavior:

Running `npm ci` updates the `dependencies` in `package.json` (key ordering).

### Expected Behavior:

`npm ci` should either error or ignore the wrong ordering. I expect only `npm install` to modify files like `package.json` or `package-lock.json`.

### Steps To Reproduce:

See https://github.com/targos/npm7-cra#issue-1-npm-ci-changes-packagejson

### Environment:

- OS: CentOS 8, Windows 10
- Node: 14.11.0
- npm: 7.0.0-beta.11 (note that this did not happen with v70.0-beta.10)

**Comment by isaacs** [comment]
Fixed by 24f3a5448

Sorry, didn't notice you'd posted issues, so the ref in the commit is pointing at your repro repo.  Thanks!
