### ISSUE TITLE
[BUG] `npm ci` prints an error without context

### ISSUE THREAD

**Issue by targos** [npm/cli#1812]
### Current Behavior:

Running `npm ci` prints `npm WARN Error: Unsupported engine` but there is no other information about the error (which package it comes from, for example).

### Expected Behavior:

There should be more information printed about the error, to allow fixing it.

### Steps To Reproduce:

See https://github.com/targos/npm7-cra#issue-2-npm-ci-prints-an-error-without-context

### Environment:

- OS: CentOS 8, Windows 10
- Node: 14.11.0
- npm: 7.0.0-beta.11

**Comment by isaacs** [comment]
Fixed by npm/arborist@0edf2ed, will be in next v7 release.
