### ISSUE TITLE
[BUG] `npm i react@17` never ends

### ISSUE THREAD

**Issue by targos** [npm/cli#1814]
### Current Behavior:

Running `npm i react@17` in the reproduction project seems to result in an infinite loop and it is not possible to stop the process with CTRL+C.

### Expected Behavior:

Like with npm@6, the command should end with an error, because there is no matching version.

### Steps To Reproduce:

See https://github.com/targos/npm7-cra#issue-4-npm-i-react17-never-ends

### Environment:

- OS: CentOS 8, Windows 10
- Node: 14.11.0
- npm: 7.0.0-beta.11

**Comment by isaacs** [comment]
Fixed by npm/arborist@789f9bc, will be in next v7 release.
