### ISSUE TITLE
[BUG] Search box preview and search results do not correspond

### ISSUE THREAD

**Issue by mtrucc** [npm/cli#1815]
### Current Behavior:

Search for _request_ in the search box
![image](https://user-images.githubusercontent.com/16724665/93437806-fd1ae000-f8fe-11ea-9be1-2827938ef457.png)
**It should not appear in the preview of the search box**

> request has been deprecated, see https://github.com/request/request/issues/3142

### Expected Behavior:

There is no _request_ option in the preview of the search box

### Steps To Reproduce:

Search for _request_ in the search box
![image](https://user-images.githubusercontent.com/16724665/93437806-fd1ae000-f8fe-11ea-9be1-2827938ef457.png)
You can see the _request_ in the search preview
![image](https://user-images.githubusercontent.com/16724665/93438079-5d118680-f8ff-11ea-9419-4e4147908ac6.png)
There is no _request_ in the search results after pressing enter
![image](https://user-images.githubusercontent.com/16724665/93438394-d0b39380-f8ff-11ea-8176-aa98bdb6d501.png)

> request has been deprecated, see https://github.com/request/request/issues/3142

### Environment:
Chrome in Windows 10

**Comment by darcyclarke** [comment]
Unfortunately, this issue tracker is only for `cli` related bugs. Please feel free to reach out to our [support](https://www.npmjs.com/support) team if you're having issues with our website or the registry.
