### ISSUE TITLE
Couldn't find package "package-name" on the "npm" registry.

### ISSUE THREAD

**Issue by myckhel** [npm/cli#1816]
npm has not been working for me for some hours now, both publishing and installing packages.
Am i the only one getting these errors?

SOS. Someone please rescue me before i commit suicide.

### Current Behavior:
Throws 404 Error

### Expected Behavior:
Should install the package But Throws Error

### Steps To Reproduce:
Intsall any package using `npm` or `yarn` command 

`npm install lodash`:
### NPM Error:
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://github.com/npm/npm-registry-couchapp/npm - Not Found
npm ERR! 404
npm ERR! 404  'npm@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/####/.npm/_logs/2020-09-17T08_22_07_766Z-debug.log
```

`yarn add axios`
### YARN Error:
```
yarn add v1.22.4
warning ../../package.json: No license field
[1/4] 🔍  Resolving packages...
error Couldn't find package "axios" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

`npm publish`
### NPM Publish Error:
```
npm notice
npm notice 📦  use-redux-state-hook@0.0.1
npm notice === Tarball Contents ===
npm notice 177B  dist/index.css
npm notice 6.1kB dist/index.js
npm notice 5.8kB dist/index.modern.js
npm notice 1.8kB package.json
npm notice 9.9kB dist/index.js.map
npm notice 9.9kB dist/index.modern.js.map
npm notice 2.1kB README.md
npm notice === Tarball Details ===
npm notice name:          use-redux-state-hook

npm notice version:       0.0.1
npm notice package size:  6.3 kB
npm notice unpacked size: 35.8 kB
npm notice shasum:        3d6b31afe47743631b005cafa42da14e7f607a74
npm notice integrity:     sha512-Kn8SsY3+vWifx[...]KaTgEQew8Kmsw==
npm notice total files:   7
npm notice
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://npm.pkg.github.com/use-redux-state-hook
npm ERR! 404
npm ERR! 404  'use-redux-state-hook@0.0.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/martinsosodi/.npm/_logs/2020-09-17T08_38_43_332Z-debug.log
```

### Environment:
- Mac OS Catalina: 10.15.6
- Node: 12.10.0
- npm: 6.10.13

**Comment by myckhel** [comment]
Some how my npm registry was changed

so i solved the issue by running this command `npm config set registry https://registry.npmjs.org/`;

**Comment by adirz** [comment]
Hi I am having the same issue and your solution does not work for me.
kinvey-nativescript-sdk has changed locations: https://github.com/thomasconner/javascript/tarball/67b7944366453a87226389d483ac1ad861e0e129 is now deleted so 

> npm -i kinvey-nativescript-sdk

 gets 404. IDK where I change it to take the new version (it's not the version number. I tried)

**Comment by Pablograu** [comment]
@myckhel `npm config set registry https://registry.npmjs.org/` worked for me! thanks!

**Comment by dinerf** [comment]
> Some how my npm registry was changed
> 
> so i solved the issue by running this command `npm config set registry https://registry.npmjs.org/`;

Worked for me too! Thanks!

**Comment by KMKDataSolutionsLLC** [comment]
Thanks for the help - I wasted 3 hours trying to find another solution - but this worked!

**Comment by minKri** [comment]
> Some how my npm registry was changed
> 
> so i solved the issue by running this command `npm config set registry https://registry.npmjs.org/`;

芜湖！

**Comment by SolindekDev** [comment]
I have the same problem but setting the registry doesn't work either. I don't know what to do, I reinstalled nodejs and npm like a thousand times and still nothing seems to help. 

I went on a example package link from my browser (https://registry.npmjs.org/express-static-gzip) and it shows:
{"error":"Not found"}

Is it something with my network or what?
