### ISSUE TITLE
[QUESTION] where is the source code of the documentation website(https://docs.npmjs.com/)?

### ISSUE THREAD

**Issue by badeggg** [npm/cli#1823]
# What / Why
I want to make a pull request to cli to enable socks proxy, so I need update cli docs website(https://docs.npmjs.com/) source code to show the enabling. 
[CONTRIBUTING.md](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#code-structure) says ./docs folder has website source code. I run ./docs folder locally and find that it does not look like the same as of https://docs.npmjs.com/.
By the way, I use ./docs folder in tag v7.0.0-beta.11.
So, where should I update the doc before making a pull request?

**Comment by darcyclarke** [comment]
@badeggg the source of https://docs.npmjs.com isn't currently public (we'll be shipping a new version of that soon which *should be* public so it can stay up-to-date) - the view of the docs you found inside the cli will probably change a bit in the months to come (it was originally supposed to become it's own domain, and we have a preview of that here: https://preview-docs.npmjs.com - that said, this view will also be changing in the months to come). 

Ultimately, the connection between the cli project & the docs website lives primarily through the content itself; Our current & future docs portal will pull from https://github.com/npm/cli/tree/latest/docs/content to generate that part of the experience. If you want to make any updates/changes to that, it should get reflected now & into the future of our docs websites.
