### ISSUE TITLE
NPM 3.5.2 on Ubuntu Server 18.04 on Raspberry Pi Fatal Error

### ISSUE THREAD

**Issue by andrewhenke** [npm/cli#1835]
Hello, I was building the package for mattermost following the instructions [here](https://docs.mattermost.com/deployment/customize-mattermost.html), and it gave me an error message and said that it was an error within npm itself, and to create a report here. Thus, I am doing likewise. Here is what it says: 

```npm ERR! Linux 5.4.0-1018-raspi
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/mattermost-webapp/npm-debug.log
Makefile:41: recipe for target 'node_modules' failed
make: *** [node_modules] Error 1
```

The contents of the `npm-debug.log` are too large to include here, so you can download and view the file [here](https://anonfiles.com/z6D3f5X2o7/npm-debug_log) (I only uploaded with Anonfiles because they have a API upload which makes things much faster :) )

I would greatly appreciate any help I could receive, as this s directly impacting the deployment of the mattermost communications platform I am looking to deploy. Thank you for your time!

**Comment by darcyclarke** [comment]
We only support the latest `npm@6` or `npm@7` versions at the moment. Please update your version of npm before submitting a bug: `npm i -g npm`
