### ISSUE TITLE
[BUG] slow npm commands

### ISSUE THREAD

**Issue by b0rr4ch4** [npm/cli#1840]
# What / Why
Invoking the command `npm i express` the process hangs or takes longer than it should to return

## When
Whenever to try install a package.
> *It is believed that other commands may have the same behavior.*

## Where
Local Machine, Windows 10 Pro, CMD.
```shell
npm i express
```
> * Tested on PowerShell and working normally
> * When PowerShell is opened by Windows Explorer or Windows Run, npm works normally.
> * When PowerShell runs in the same cmd window, the bug happens, example:
>> ```shell
>> C:\>
>> C:\> powershell.exe
>> PS C:\> npm i express
>> ```

### Current Behavior
Exorbitant slowness of the window that ran the command, cmd.exe

### Steps to Reproduce
Open the CMD;
Access the window's context menu;
Click Properties;
Layout tab;
Buffer size of the screen. See the image below;
Test the command.

Whenever the command prints a text that exceeds the window limit, the command hangs or takes a long time to respond.

![image](https://user-images.githubusercontent.com/11152752/77480568-b2615500-6e00-11ea-8143-3256699de295.png)
![image](https://user-images.githubusercontent.com/11152752/77480616-ca38d900-6e00-11ea-9130-a8119b2e1134.png)
![image](https://user-images.githubusercontent.com/11152752/77480592-bc835380-6e00-11ea-8bb9-5d672e297b94.png)

### Expected Behavior
The window shouldn't crash and the command was to end in seconds

## Who
* n/a

## References
[![Example Video](https://img.youtube.com/vi/JO_p2OPZC6s/0.jpg)](https://www.youtube.com/watch?v=JO_p2OPZC6s)

**Comment by darcyclarke** [comment]
@rossifw can you let us know which version of node you're using and which specific version of `npm` you were on when you ran, or are still running, into this?

**Comment by nlf** [comment]
effectively your configuration is creating an enormous buffer, that buffer is redrawn in its entirety every time we update the progress bar on the screen. with it being that large, redrawing like that is slow. there's nothing we can do to speed up redrawing the terminal for you.

you may find that disabling the progress bar by running commands with `--no-progress` will improve your experience
