### ISSUE TITLE
ERR cb() never called when running npm publish

### ISSUE THREAD

**Issue by maryiababinova** [npm/cli#1842]

**Comment by xorpix** [comment]
i've just ran into the same issue

**Comment by xorpix** [comment]
Here's the log:
https://ghostbin.co/paste/2tacp

**Comment by bejoysvijayan-code** [comment]
npm cache verify 
fixed my issue

**Comment by darcyclarke** [comment]
Closing as this doesn't use our bug template & is duplicative to other threads we're already tracking.
