### ISSUE TITLE
No command of npm is running after I deleted node_module folder. npm install not working

### ISSUE THREAD

**Issue by tbikash62** [npm/cli#1844]
I am very new to npm. I installed two packages 'moment' and 'loadash'
it got reflected in node_modules folder. 
Then I deleted the folder 

now when I run 
npm install moment , it shows no response. 

![image](https://user-images.githubusercontent.com/58831041/93858091-e6d4a180-fcbb-11ea-8bce-6865643b08bd.png)

Basically it is not giving any output and jumps to new command line. 
it is happening with all commands mostly. 

I followed this 
https://stackoverflow.com/questions/20711240/how-to-completely-remove-node-js-from-windows

but not able to fix it

### Expected Behavior:
it should install the node module

**Comment by darcyclarke** [comment]
In a new folder, try running `npm init --yes` & then `npm install` with whatever package you'd like to install. If you're still seeing issues, try running `npm -v` to output the version of npm you're using. If you're still having problems then, I would head to https://nodejs.org/en/ & try reinstalling `node` which comes with `npm` by default. Once installed, I'd try the process of creating a new project and installing some packages again with `npm`.
