### ISSUE TITLE
[BUG] invalid comparison in json-schema validate.js

### ISSUE THREAD

**Issue by VaeterchenFrost** [npm/cli#1851]
# What / Why

`typeof` is compared to **undefined**. This comparison is invalid, because `typeof` always returns strings.

## When

when `typeof schema.maximum` is `undefined` in 

## Where

* npm/cli

https://github.com/npm/cli/blob/bd2721dbc3de13a5ba889eba50644475d80f6948/node_modules/json-schema/lib/validate.js#L173

https://github.com/npm/cli/blob/bd2721dbc3de13a5ba889eba50644475d80f6948/node_modules/json-schema/lib/validate.js#L177
### Current Behavior

The comparison always leads to true.
This can be seen with
`console.log(typeof undeclaredVariable!==undefined);`
`true`

### Steps to Reproduce
* n/a

### Expected Behavior

Either this comparison is intended to never be used, or should result in a comparison with "undefined":
`console.log(typeof undeclaredVariable!=="undefined");`
`false`

## Who
* @npm/cli

**Comment by ljharb** [comment]
This fix needs to go in the json-schema module directly, not in npm's vendored copy.

**Comment by VaeterchenFrost** [comment]
Oh I see. I will have a look for that then. Thank you for the comment.

**Comment by darcyclarke** [comment]
Closing: as @ljharb noted, this is an issue in `json-schema` & not `npm` itself.
