### ISSUE TITLE
[BUG] OOM exit status inconsistent

### ISSUE THREAD

**Issue by howshit** [npm/cli#1855]
Hi there,

We've encountered something weird recently:

We are running a script with docker image node:12.18.3-alpine, the script is causing OOM.

if we run it in "npm run oom" (oom is the script name, and the definition of this script is node scriptFileName.js), the exit code is 0, and if we are running it in "node scriptFileName.js" directly, the exit code is 139.

I happen to know that when running node js with npm will create two process, the parent process is npm and the child process is node.

Is there any mechanism that cause the exit code to be 0 when running with npm.

Please kindly help.

Best regards,
Felix

**Comment by darcyclarke** [comment]
Closing: Please use our bug report template & reopen if you think you've found an issue in the CLI.
