### ISSUE TITLE
Node Module Isn't Install Properly

### ISSUE THREAD

**Issue by mustafaAly** [npm/cli#1874]
when I run any npm install these files are installed and expand in the project directory i didn't understand what happen and these files make errors to me  when i run the project i have windows 10 node version 14 npm version 6

![Screenshot (3)](https://user-images.githubusercontent.com/16977942/94567790-21b27880-026c-11eb-9fed-321128b9a8e2.png)
![Screenshot (4)](https://user-images.githubusercontent.com/16977942/94567803-24ad6900-026c-11eb-918a-54050e71bf16.png)

**Comment by darcyclarke** [comment]
Closing: Please use our default bug issue template; If you're experiencing issues with a specific project/package we don't support that. If you're wondering how npm works, or the details of a specific command/usage, definitely feel try reading through some of our docs here: https://docs.npmjs.com

**Comment by mustafaAly** [comment]
I don't experience issues with a specific project, it happens to me in all project with a specific pc, on my laptop, it doesn't appear with me I can't run any project has npm module on my work pc please give to
 me the link to your bug issue template;
