### ISSUE TITLE
[BUG] npm audit backwards compatibility against third party tools

### ISSUE THREAD

**Issue by doddi** [npm/cli#1875]
### Current Behavior:
When performing an npm audit using a third party tool that currently audits successfully when using npm cli v6, the response using npm v7 is 0 vulnerabilities.

The third party tool does not currently implement the new endpoint [/-/npm/v1/security/advisories/bulk](https://github.com/npm/cli/blob/2f8d11968607a74c8def3c05266049bee5e313eb/node_modules/@npmcli/arborist/lib/audit-report.js#L303) and as such the cli defaults back to using the quick audit implementation.

The quick audit response is converted to a bulk advisory but there is no `vulnerable_versions` entry and therefore no vulnerabilities are surfaced. Previously, `vulnerable_versions` was not a required entry to surface vulnerabilities.

### Expected Behavior:
An npm audit using v6 and v7 should surface the same vulnerabilities or as a minimum fail safely and error if no `vulnerable_versions` entry is present an a response.

### Steps To Reproduce:
Run an npm audit using v6/v7 cli and ensure in a quick audit response there is no `vulnerable_versions` entry in the response
v6: vulnerability information is surfaced
v7: no vulnerability information is surfaced

### Environment:
- OS: MacOS
- Node: 14.2.0
- npm: v7.0.0-beta.12 commit https://github.com/npm/cli/commit/9bc69667f01d2a571cb2ce36927057b099863882

**Comment by darcyclarke** [comment]
Thanks for catching this @doddi!

**Comment by isaacs** [comment]
Hmm, so it seems like, if there's no `vulnerable_versions` field, then it should effectively be `vulnerable_versions: "*"`?

That would be quite easy to do.

**Comment by darcyclarke** [comment]
@isaacs this has definitely sat for a while, I'm going to make it a `Priority 2` & pull it up into our Sprint so we at least can keep some eyes on it - maybe someone else can take it on & sync with you if you've got more context.
