### ISSUE TITLE
Documentation missing for `npm login`

### ISSUE THREAD

**Issue by jameshfisher** [npm/cli#1880]
### Current Behavior:
https://docs.npmjs.com/cli-documentation/cli lists commands sans `login`

### Expected Behavior:
Page lists all commands listed by:

```
$ npm --help

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, fund, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami
```

### Steps To Reproduce:
Visit https://docs.npmjs.com/cli-documentation/cli

**Comment by darcyclarke** [comment]
Hey @jamesgeorge007, unfortunately, `npm login` is actually just an alias of `npm adduser` so the docs do indeed exist. We'll keep this open & make it a point to add a duplicate ref to the existing doc/info.

**Comment by jameshfisher** [comment]
Thanks @darcyclarke - weird, `adduser` sounds like "sign up" rather than "log in", but OK!

**Comment by ljharb** [comment]
@darcyclarke tbh it's always seemed weird to me that "login" isn't the primary command, "adduser" is weird. Could the relationship be switched?

**Comment by Celtian** [comment]
Can you add also here
https://docs.npmjs.com/cli/v6/commands/npm-unpublish
information that you should **run first command "npm login"** before you try to unpublish something. If you are not logged cli gives me irrelevant 404 error.

**Comment by wraithgar** [comment]
This was fixed in npm 8, "login" and "adduser" were separated.
