### ISSUE TITLE
[BUG] Unable to install any package after cleaning cache

### ISSUE THREAD

**Issue by Aniganesh** [npm/cli#1885]
I cleared my npm cache using `npm clean cache --force` and have since been unable to install any packages. Running npm i in my project gives a long list of files that are not in my node_modules in the following format:
`npm WARN tar ENOENT: no such file or directory, open '/home/path-to-project-folder/node_modules/.staging/@material-ui/icons-71185f08/esm/IndeterminateCheckBoxSharp.js'`
 and finally ends with this error:
`npm ERR! cb() never called!`
along with this message:
`npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>`

**Comment by Aniganesh** [comment]
Restarting my pc, reinstalling npm and using different versions of npm have not solved this problem.

**Comment by darcyclarke** [comment]
Closing: If you believe you have found a bug in the `cli` itself, please use one of our issue templates found here: https://github.com/npm/cli/issues/new/choose If you have a usage question, please refer to our docs https://docs.npmjs.com or use https://github.com/npm/rfcs/discussions to discuss the project.
