### ISSUE TITLE
[BUG] npm install <dep>@versionOrTag does not honor save prefix

### ISSUE THREAD

**Issue by aliatsis** [npm/cli#1888]
### Current Behavior:
On the heels of https://github.com/npm/cli/issues/1849, npm v7.0.0-rc.0 does not include my configured `^` save prefix in devDependencies version when running an `npm i <dep>@versionOrTag`.

### Expected Behavior:
`npm i <dep>@versionOrTag` should include my configured `^` save prefix on the updated version in package.json devDependencies

### Steps To Reproduce:
1. Install npm v7.0.0-rc.0
2. `npm i <dep>@prev-version` where `prev-version` is the exact number version of a previous version
3). observe no save prefix in package.json devDependencies for `<dep>`
4). `npm i <dep>@latest`
5). observe no save prefix in package.json devDependencies for `<dep>`

### Environment:
Node: v10.15.3
NPM: v7.0.0-rc.0

**Comment by darcyclarke** [comment]
@aliatsis can you try testing if this is still a problem after installing the latest version? (ie. `7.0.15`)

**Comment by aliatsis** [comment]
@darcyclarke I can still reproduce with 7.0.15

**Comment by wraithgar** [comment]
I was not able to reproduce this in npm `v7.4.1`

I tried with both an `.npmrc` file in the project folder, and my `~/.npmrc` file.  I tried with both setting `save-prefix=~` and `save-prefix=^` and also with no `save-prefix` (which fell back to the default which is `save-prefix=^`

In each case I started with a package.json with no dependencies.  Then ran

```sh
$ npm install lodash@1.0.0 -D
$ npm install lodash@latest
```

I also tried

```sh
$ npm install lodash@4.0.0 -D
$ npm install lodash@latest
```

To test updating without crossing a semver major boundary

In each case, the expected prefix was present in my `package.json` file
