### ISSUE TITLE
[BUG] Verification email is not sent to my professional domain mailbox

### ISSUE THREAD

**Issue by di-mr-di** [npm/cli#1901]
### Current Behavior:
Unable to verify the newly registered account with professional mailbox. If I switch to a gmail account it seems to work.

### Expected Behavior:
I need to verify my email in order to accept private invites

**Comment by darcyclarke** [comment]
Hey @dms-seqvoia! Appreciate you bringing this up; Unfortunately, we only deal with `cli` related bugs in this repo. If you're running into a website/service/registry problem, please submit a ticket to our support team who can then work with our registry engineering team to help resolve any issues: https://npmjs.com/support
