### ISSUE TITLE
[Docs] Update package docs don't describe how to update over major versions

### ISSUE THREAD

**Issue by ericandrewlewis** [npm/cli#1909]
Hello! It's my first time contributing to this repo. Thanks for npm!

I was trying to update a dependency over major versions recently. I found this page ["Updating packages downloaded from the registry](https://docs.npmjs.com/updating-packages-downloaded-from-the-registry)" in the NPM docs which describes how to update to the latest stable within a major version range.

The docs don't specify how to update over a major version but I believe `npm install package@latest` does the trick.

Is this the correct repository for suggesting issues for docs? I could not find the corresponding source file for [this docs page](https://docs.npmjs.com/updating-packages-downloaded-from-the-registry), and the links in that page suggest opening discussion on [the forums](https://npm.community/c/support/docs-needed) which have been archived.

**Comment by darcyclarke** [comment]
Hey @ericandrewlewis! Thanks for reaching out. Unfortunately, the docs you referenced aren't open source at the moment but should be soon. They're also getting a bit of a refresh so keep a watch out in the weeks/month to come. 

In terms of your change in reference to "Updating packages downloaded from the registry", [`npm update`](https://docs.npmjs.com/cli/update) will actually satisfy whatever the defined package spec provided is or whatever is in `package.json` (ex. `>1.0.0` can & would update to `2.0.0`); If you were to run `npm install package@latest` on the other hand, you'll get the very latest version of the package no matter what & it'll update your `package.json` to `package@^x`. This may or may not be what you wanted to do. In terms of globally installed packages, `npm update -g x` does function similar, if not the same, as `npm install -g x@latest`.
