### ISSUE TITLE
cb() never called on npm install 

### ISSUE THREAD

**Issue by joaoleite1998** [npm/cli#1910]
(base) Joaos-MacBook-Air:client joaoleite$ npm install
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/joaoleite/.npm/_logs/2020-10-07T00_38_52_364Z-debug.log
(base) Joaos-MacBook-Air:client joaoleite$

**Comment by darcyclarke** [comment]
Closing: Please use one of our bug templates.
