### ISSUE TITLE
a couple of issues

### ISSUE THREAD

**Issue by celesteking** [npm/cli#1922]
Hi. there are a couple of issues I'm facing.
~~1. npm.community doesn't resolve when using bind recursor. Either you fail dnssec or have cname @ apex. Either way, you should fix it.~~
2. lack of docs. I wanted to try npm v7 because v6 can't cope with symlinked deps (file: handler) . I 've installed it, but I don't see the docs. `npm ls --help` gives 0 help. This is wrong in UNIX world. Compare to `ls --help` in your terminal.
I have recently discovered I could use `npm ls --all` and that would show all deps, like in old npm. 
There should be v7 documentation put somewhere.

3.  v7 is better dealing with symlinked stuff, that's for sure, but there are still issues. E.g., I couldn't make it install nested deps.

```
$ npm list --all
... irrelevant....
+-- daemon@1.1.0
+-- UNMET DEPENDENCY eslint-plugin-haraka@^1.0.13
+-- generic-pool@2.5.4
+-- haraka-config@1.0.19 -> /code/nodejs/hk-plugins/haraka-config
| +-- UNMET DEPENDENCY eslint-plugin-haraka@* deduped
| +-- UNMET DEPENDENCY eslint@* deduped
| +-- UNMET DEPENDENCY hjson@^3.2.0 deduped
| +-- UNMET DEPENDENCY js-yaml@^3.13.1 deduped
| `-- UNMET DEPENDENCY mocha@* deduped
+-- haraka-constants@1.0.5
+-- haraka-dsn@1.0.3
+-- haraka-net-utils@1.2.0
... irrelevant....
```
You see **UNMET** over there? I'd like npm to take care of that and install those deps either into `haraka-config`'s node_modules or into this project's node_modules. In any case, it should do something with that  as basically otherwise you end up with a non-working app. `npm install` currently does nothing in this situation.

```
  "dependencies": { ...
    "haraka-config": "file:../hk-plugins/haraka-config",
...}
```

node 12.x
npm 7.0.0-rc.3

Thanks.

**Comment by celesteking** [comment]
1. solved because it's been archived / unusable.

**Comment by darcyclarke** [comment]
Hey @celesteking! Thanks for filing this & I'm sorry for the confusion - We're currently cleaning up the npm v7 docs. We had a note about this in our initial beta/rc release's [CHANGELOG.md](https://github.com/npm/cli/blob/release/v7.0.0/CHANGELOG.md#docs). We should have a more up-to-date version of our docs shipped early next week (although it won't be 100% clean, it will be MUCH more accurate & improved).

Could you make separate issues for the other bugs you've run into? It's hard for us to track a single issue with many bugs.
