### ISSUE TITLE
[BUG] Strange non user friendly behavior controlled by the package itself  

### ISSUE THREAD

**Issue by SwapCursor** [npm/cli#1944]
I created an throughout issue for this at [stackoverflow](https://stackoverflow.com/questions/64298287/npm-install-go-nuts-in-this-vscode-project-please-advice/64301464#64301464)

### Expected Behavior:
When installing using NPM install on a Reactjs project errors should be user-friendly and easy to spot. 

### Steps To Reproduce:
Here is a [link](https://docs.google.com/document/d/16C9_rpYP17INZEO6do_I6pXBaNSq0qchMPDDMWJhE6Q/edit?usp=sharing) to complete 300.000 letters long error message produced by NPM since stackoverflow above only could handle 30.000.
Read the SO question for details 
-->

### Environment:
OS: Win 10
Node: v12.8.1.
npm: 6.10.2
VSCode latest

**Comment by isaacs** [comment]
In npm 7, we only print install script output when the install script fails in such a way that it breaks the install.  Changing this was be a breaking change, so we cannot do it in the v6 release line.
