### ISSUE TITLE
cb() never called when running npm install

### ISSUE THREAD

**Issue by maryiababinova** [npm/cli#1952]

**Comment by citrusoft** [comment]
me too!!!

> `
$ cdk --version
1.62.0 (build 8c2d7fc)
(.venv379)
tahv@VPEG01B003868 MINGW64 /c/users/tahv/git/cscoe-config-rules (tahv/CLOUDCOE-7307)
$ node --version
v14.13.1
(.venv379)
tahv@VPEG01B003868 MINGW64 /c/users/tahv/git/cscoe-config-rules (tahv/CLOUDCOE-7307)
$ npm --version
6.14.8
(.venv379)
tahv@VPEG01B003868 MINGW64 /c/users/tahv/git/cscoe-config-rules (master)
$ pwd
/c/users/tahv/git/cscoe-config-rules
(.venv379)
tahv@VPEG01B003868 MINGW64 /c/users/tahv/git/cscoe-config-rules (master)
$ npm install
npm ERR! cb() never called!
npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tahv\AppData\Roaming\npm-cache\_logs\2020-10-13T16_20_50_098Z-debug.log
(.venv379)
tahv@VPEG01B003868 MINGW64 /c/users/tahv/git/cscoe-config-rules (master)
$ 
`

**Comment by prKassad** [comment]
Same error after `npm i`. Win10.0.18363/Node14.13.1/Npm7.
```
17402 http fetch GET 200 https://registry.npmjs.org/acorn-globals/-/acorn-globals-4.3.4.tgz 266776ms attempt #3
17403 timing reifyNode:node_modules/react-scripts/node_modules/acorn-globals Completed in 275955ms
17404 http fetch GET 200 https://registry.npmjs.org/whatwg-url/-/whatwg-url-7.1.0.tgz 267157ms attempt #3
17405 timing reifyNode:node_modules/react-scripts/node_modules/data-urls/node_modules/whatwg-url Completed in 276326ms
17406 http fetch GET 200 https://registry.npmjs.org/schema-utils/-/schema-utils-1.0.0.tgz 285846ms attempt #3
17407 timing reifyNode:node_modules/react-scripts/node_modules/webpack/node_modules/schema-utils Completed in 295371ms
17408 http fetch GET 200 https://registry.npmjs.org/resolve-from/-/resolve-from-3.0.0.tgz 285959ms attempt #3
17409 timing reifyNode:node_modules/lerna/node_modules/resolve-from Completed in 295527ms
17410 http fetch GET 200 https://registry.npmjs.org/react-dom/-/react-dom-16.13.1.tgz 306715ms attempt #3
17411 timing reifyNode:node_modules/react-dom Completed in 316263ms
17412 timing npm Completed in 449934ms
17413 error cb() never called!
17414 error This is an error with npm itself. Please report this error at:
17415 error <https://github.com/npm/cli/issues>
```


UPD: After downgrading to Npm v6.14.8 no mistake.

**Comment by seth-church** [comment]
Same error here.
node --version
v14.14.0
npm --version
6.14.8

Here's the end of the log file:
45907 http fetch GET 200 https://our-repo/npm-ics/aws-sdk/-/aws-sdk-2.778.0.tgz 71573ms
45908 silly extract aws-sdk@^2.601.0 extracted to /home/seth-church/Projects/areabook-web/node_modules/.staging/aws-sdk-034831bb (71589ms)
45909 timing npm Completed in 513789ms
45910 error cb() never called!
45911 error This is an error with npm itself. Please report this error at:
45912 error <https://npm.community>

**Comment by enaSo97** [comment]
Same error here!
node version v14.12.0
npm version 6.14.7

`6786 error cb() never called!
6787 error This is an error with npm itself. Please report this error at:
6788 error <https://npm.community>
`

On command 

`npm install aws-amplify aws-amplify-react-native @react-native-community/netinfo`

**Comment by darcyclarke** [comment]
Closing: Please use our issue template when filing a bug & confirm that there isn't a duplicate issue already filed: https://github.com/npm/cli/issues/new/choose
