### ISSUE TITLE
[BUG] npm version --no-git-tag-version doesn't work

### ISSUE THREAD

**Issue by protyposis** [npm/cli#1973]
### Current Behavior:
Executing `npm version --no-git-tag-version` creates a Git tag and a Git commit with the incremented version in `package[-lock].json`. Same behavior with `--git-tag-version false` and `--git-tag-version=false`.

### Expected Behavior:
It only changes the `version` in `package[-lock].json` and does not create a Git commit/tag, as the docs suggest (https://github.com/npm/cli/blob/latest/docs/content/cli-commands/npm-version.md#git-tag-version), and like done by npm v6.

### Steps To Reproduce:
1. Enter the root directory of a package
2. Execute `npm version --no-git-tag-version patch`
3. Find version tag and commit in Git history

### Environment:
- OS: Windows 10, Ubuntu 18.04 (via WSLv1, Windows 10)
- Node: 12.19.0, 12.13.0
- npm: 7.0.1

**Comment by pablote** [comment]
same here for macOS, reverted to npm 6.x.x fixed the issue for me

**Comment by nlf** [comment]
we published 7.0.6 today that should resolve this, can you try updating with `npm install -g npm@7` and let us know how it goes?

**Comment by protyposis** [comment]
Confirming that it's resolved, thanks!
