### ISSUE TITLE
cli hangs when running `npm install`

### ISSUE THREAD

**Issue by aks-** [npm/cli#1991]
### Current Behavior:
I am trying to migrate a repository from yarn to npm, until now I was seeing output and resolving all the peer deps. But every now and then the cli hangs and does not output anything whatsoever. I have to kill the process to get out of it.

### Expected Behavior:
Either an error output or deps should be installed.

### Steps To Reproduce:
Because I am working on private repo, I can not provide the package.json
1. when I run 'npm i'
2. I see and it hangs here
```
⸨░░░░░░░░░░░░░░░░░░⸩ ⠧ idealTree:xxx-frontend: sill idealTree buildDeps
⸨        ░░░░░░░░░░⸩ ⠋ idealTree:warning: timing idealTree:node_modules/react-router/node_modules/warning Completed in 0ms
```

### Environment:
- OS: OS X v10.14.4
- Node: v10.18.1
- npm: 7.0.0

**Comment by ljharb** [comment]
Can you try with npm v7.0.2?

**Comment by aks-** [comment]
> Can you try with npm v7.0.2?

That seems to work! :s thank you

**Comment by klesun** [comment]
I have same problem with `7.13.0` and `7.15.1` on ubuntu with such `package.json` in a clean working copy without `package.lock` or `node_modules`:
```json
{
  "name": "npm-seven-issue",
  "version": "0.0.1",
  "devDependencies": {
    "npm-seven-issue-dep": "git+ssh://git@gitlab.com/klesun/npm-seven-issue-dep#5f1b313978986974d4364585e6bd3689276f1697"
  }
}
```
It just freezes at:
```
[....................] \ idealTree.pql-box: still idealTree buildDeps
```

In npm `6.14.13` `npm install` of this project worked without problems

Upd.: oh, it does eventually end on `7.13.0`, after `1m13,013s`. Some network timeout perhaps?
```
klesun@kunkka:~/gits/pql-box$ time npm i
added 1 package, and audited 2 packages in 1m
found 0 vulnerabilities
real	1m13,013s
user	0m1,555s
sys	0m0,253s
```
On `6.14.13` same project clean install ends in `0m2,474s`:
```
klesun@kunkka:~/gits/pql-box$ time npm i
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ololo@0.0.1 No repository field.
npm WARN ololo@0.0.1 No license field.
added 1 package and audited 1 package in 2.004s
found 0 vulnerabilities
real	0m2,474s
user	0m0,694s
sys	0m0,100s
```

@ljharb, `npm install` became 30 times slower, it's a regression introduced in npm `v7`, is it?

**Comment by klesun** [comment]
Filed a minimal reproduction repo: https://gitlab.com/klesun/npm-seven-issue/-/blob/main/README.md

**Comment by ljharb** [comment]
@klesun can you file a new issue for this?

**Comment by klesun** [comment]
@ljharb yes!
https://github.com/npm/cli/issues/3359
