### ISSUE TITLE
[BUG] npm 7.x ignores publishConfig.registry scope is provided

### ISSUE THREAD

**Issue by ohardy** [npm/cli#1994]
### Current Behavior:
npm publish does not follow publishConfig.registry scoped registry configured in publishConfig.registry

### Expected Behavior:
npm publish publish to defined scoped publishConfig.registry

### Steps To Reproduce:

1. Install npm@latest-7
2. Set publishConfig.registry IE: "publishConfig": { "@my-scope:registry": "https://..." }
3. Run `npm publish`

### Environment:
OS: Max OS 10.15.7
Node: 14.14.0
npm: 7.0.2

**Comment by isaacs** [comment]
Fixed in latest release.

**Comment by thw0rted** [comment]
Is it possible that the fix for this could have re-broken https://github.com/npm/cli/issues/1937 ?  As I commented there, as of 7.3.0, `publish` is ignoring my `publishConfig.registry`.
