### ISSUE TITLE
[BUG] issue installing dependency when specified in both dev & peer

### ISSUE THREAD

**Issue by mjeanroy** [npm/cli#1998]
### Current Behavior:
When a dependency is specified as a `devDependency` **and** as a `peerDependency`, it is not installed. I tested it with npm@7.0.2, everything worked well with npm < 7.

### Expected Behavior:
I expect that all dev dependencies should be installed.

### Steps To Reproduce:
I created a very small repository to reproduce the issue, so you can just checkout it and install dependencies:

```
git clone git@github.com:mjeanroy/npm-7-bug-peer-dev.git
cd npm-7-bug-peer-dev
npm install
```

### Environment:
- OS: MacOS 10.15.7
- Node: 15.0.0
- npm: 7.0.2

**Comment by isaacs** [comment]
This appears to be working as of npm 7.0.3 and 7.0.2.  I get the same results in each.

```
$ git clone git@github.com:mjeanroy/npm-7-bug-peer-dev.git
Cloning into 'npm-7-bug-peer-dev'...
Krypton ▶ Requesting SSH authentication from phone
Krypton ▶ Success. Request Allowed ✔
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 4 (delta 0), pack-reused 0
Receiving objects: 100% (4/4), done.

$  cd npm-7-bug-peer-dev
/Users/isaacs/dev/npm/arborist/npm-7-bug-peer-dev

$ npm install

added 6 packages, and audited 6 packages in 658ms

found 0 vulnerabilities

$ npm ls react
npm-7-bug-peer-dev@1.0.0 /Users/isaacs/dev/npm/arborist/npm-7-bug-peer-dev
└── react@16.14.0


$ ls -laF node_modules/react/package.json
-rw-r--r--  1 isaacs  staff  882 Oct 26  1985 node_modules/react/package.json
```

Is it possible that `--omit=peer` or `--omit=dev` is set on your system, or `--legacy-peer-deps`?

**Comment by lpinca** [comment]
@isaacs it does not work with `npm@7.0.2` shipped with Node.js v15.0.0.

```
$ node -v
v15.0.0
```

```
$ npm -v
7.0.2
```

```
$ git clone git@github.com:websockets/ws.git
Cloning into 'ws'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 14388 (delta 1), reused 5 (delta 0), pack-reused 14379
Receiving objects: 100% (14388/14388), 10.67 MiB | 1.77 MiB/s, done.
Resolving deltas: 100% (11784/11784), done.
```

```
$ cd ws
```

```
$ npm i
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 352 packages, and audited 352 packages in 16s

33 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

```
$ npm ls utf-8-validate
ws@7.3.1 C:\Users\luigi\Desktop\ws
└── (empty)
```

`utf-8-validate` is a [dev dependency](https://github.com/websockets/ws/blob/d972c33cb47c87439a1c68c7cf06d9a2aa9f7141/package.json#L55) and an [optional peer dependency](https://github.com/websockets/ws/blob/d972c33cb47c87439a1c68c7cf06d9a2aa9f7141/package.json#L41-L43).

**Comment by lpinca** [comment]
The same happens with Node.js v15.0.1 and `npm@7.0.3`.

**Comment by mjeanroy** [comment]
@isaacs You're right, I had `omit=peer` in my ~/.npmrc, I did not see that.
