### ISSUE TITLE
[BUG] After update to npm 7 it seems no global packages are recognized 

### ISSUE THREAD

**Issue by charles-dexter-ward** [npm/cli#2002]
Upgraded from node 14 to node 15.0.0
Upgraded npm to 7.0.3

### Current Behavior:
1) npm --outdated -g
only shows a DOWNGRADE from npm 7 to 6
![image](https://user-images.githubusercontent.com/2855255/96681470-9b271d80-1377-11eb-84fc-6c302d1e1c54.png)

2) npm list -g --depth= 0
it does not show the intalled global packages, but only npm
![image](https://user-images.githubusercontent.com/2855255/96681605-d7f31480-1377-11eb-8e0c-a056c7042944.png)

### Expected Behavior:
the complete list of installed global packages should be listed.

### Environment:
- OS: Windows 10
- Node: 15.0.0
- npm: 7.0.3

**Comment by charles-dexter-ward** [comment]
In addition there is also the issue https://github.com/npm/cli/issues/1962 
![image](https://user-images.githubusercontent.com/2855255/96751209-326a9000-13cd-11eb-96f0-a8c09be07329.png)

**Comment by WraithKenny** [comment]
I had this same problem on my MacOS system, but fixed it with
`brew rm node`
`brew install node`
Which doesn't explain why the problem also happens on Windows, but maybe it points to where the problem is. 

(It seems on upgrade it loses track of where the global node_modules folder is, but install knows where it is? I dunno.)

Didn't fix the "global requires an add or rm option" tho.

**Comment by WraithKenny** [comment]
What's also strange is that `npm i npm@^6 -g` didn't fix the issue, only an uninstall and reinstall of `node`

**Comment by funfunction** [comment]
After installing node 15 and npm 7, the npm global modules install into this path...
C:\Program Files\nodejs\node_modules

instead of....
C:\Users\USER\AppData\Roaming\npm\node_modules

Which path should be made the canonical path to use?

**Comment by charles-dexter-ward** [comment]
https://github.com/npm/cli/issues/1962#issuecomment-715911549

could solve the problem for someone (not for me https://github.com/npm/cli/issues/1962#issuecomment-716357702)

**Comment by jonathanmarvens** [comment]
https://github.com/npm/cli/issues/1962#issuecomment-716954993

**Comment by funfunction** [comment]
Installing Node 15 fresh (uninstall first) still installs only npm 6 (not npm 7)

Is this the expected behavior or a bug?




![node, npm, older version](https://user-images.githubusercontent.com/37894007/98282701-758f3c00-1f53-11eb-90a8-c5c2943d6d6f.jpg)

**Comment by charles-dexter-ward** [comment]
@funfunction 
Npm 7 is not the latest, I suppose. I think you must explictly require the version 7.

**Comment by ljharb** [comment]
@funfunction if you have installed node 15 properly, it will always come with npm 7. If it doesn't, your install method is likely broken.

**Comment by nickserv** [comment]
I think it's more about npm 7's global package linking being broken (since npm itself is an npm package)

**Comment by ljharb** [comment]
@nickmccurdy on a fresh install of node, npm isn’t linked, and on any node 15, it’s always npm 7.

**Comment by funfunction** [comment]
I fixed it by cd-ing into AppData\Roaming\npm

then running: npm link npm

After 10 years of using node, this is the first time I had to do this.

**Comment by charles-dexter-ward** [comment]
Installed npm 7.0.10 (which should fix https://github.com/npm/cli/issues/1962) :

npm outdated -g
![image](https://user-images.githubusercontent.com/2855255/98779990-b922f380-23f4-11eb-9761-a2b126b85692.png)

npm list -g --depth=0
![image](https://user-images.githubusercontent.com/2855255/98780311-dc4da300-23f4-11eb-88ec-7959760a496d.png)

npm link npm
![image](https://user-images.githubusercontent.com/2855255/98780472-16b74000-23f5-11eb-90b0-ef60a36b8806.png)

`
42 verbose stack Error: ELOOP: too many symbolic links encountered, stat 'C:\Users\XXXXX\node_modules\npm'

42 verbose stack     at eloop (C:\Users\XXXXX\node_modules\npm\node_modules\@npmcli\arborist\lib\realpath.js:57:17)

42 verbose stack     at C:\Users\XXXXX\node_modules\npm\node_modules\@npmcli\arborist\lib\realpath.js:82:15

42 verbose stack     at async Arborist.[loadActual] (C:\Users\XXXXX\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\load-actual.js:118:13)

`

**Comment by charles-dexter-ward** [comment]
I had to reinstall all global packages. Now they are listed by npm and executable.
Before reinstalling them, there were no binaries in the node_modules folder even if the packages were previously installed.

**Comment by WraithKenny** [comment]
So I had
 `which npm` > `/usr/local/bin/npm`, 
`npm -v` > `7.0.10` 
`npm -g ls --depth=0` shows `usr/local/lib`
and `npm config list` showed
```
; "builtin" config from /usr/local/lib/node_modules/npm/npmrc

prefix = "/usr/local" 

; "cli" config from command line options

omit = [] 
user-agent = "npm/7.0.10 node/v15.2.1 darwin x64" 

; node bin location = /usr/local/Cellar/node/15.2.1/bin/node
[...]
```

Then I run `npm install -g npm@7.0.12`
Now...
 `which npm` > `/usr/local/bin/npm`, 
`npm -v` > `7.0.12` 
`npm -g ls --depth=0` shows `/usr/local/Cellar/node/15.2.1/lib`
and `npm config list` shows
```
; "cli" config from command line options
[...]
```
...which fails to load the previous (default) `prefix`. (`npm config list -l` will show `prefix = "/usr/local/Cellar/node/15.2.1"`)

This still seems like it's off. I've fixed mine by adding a `.npmrc` (by running `npm config set prefix /usr/local`) but if a user upgrades without that file, things are weird.

**Comment by playpiano** [comment]
even last version 7.3.0 not listing globally installed packages: is it a new Arborist tree list bug?

**Comment by charles-dexter-ward** [comment]
Yes. I had installed 7.2.0 and it has screwed up the packages again. :(
What the hell!
