### ISSUE TITLE
[BUG] Protocol "https:" not supported. Expected "http:"

### ISSUE THREAD

**Issue by Aw3same** [npm/cli#2003]
Upgraded from node 14 to node 15.0.0
Upgraded npm to 7.0.3

### Current Behavior:
Running the command 
`npm install -g npm-check-updates`
I get the following that doesn't happened in v6.14 
![image](https://user-images.githubusercontent.com/10500082/96687507-476d0200-1380-11eb-90eb-6ee56139a4b7.png)

The error log is: 

```
 TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
    at new NodeError (node:internal/errors:258:15)
    at new ClientRequest (node:_http_client:155:11)
    at request (node:https:313:10)
    at C:\Users\<USER>\AppData\Roaming\npm\node_modules\npm\node_modules\minipass-fetch\lib\index.js:80:17
    at new Promise (<anonymous>)
    at fetch (C:\Users\<USER>\AppData\Roaming\npm\node_modules\npm\node_modules\minipass-fetch\lib\index.js:39:10)
    at C:\Users\<USER>\AppData\Roaming\npm\node_modules\npm\node_modules\make-fetch-happen\index.js:297:14
    at C:\Users\<USER>\AppData\Roaming\npm\node_modules\npm\node_modules\promise-retry\index.js:29:24
```

My npm config doesn't change too:

`proxy=http://my.proxycompany.com:80/`
`http-proxy=http://my.proxycompany.com:80`
`https-proxy=http://my.proxycompany.com:80/`
`registry=https://registry.npmjs.org/`
`strict-ssl=false`

**EDIT**
Changing registry to http it works, but I don't know why.
`registry=http://registry.npmjs.org/`

### Expected Behavior:
Run npm install and install the library successfully.

### Environment:

- OS: Windows 10 v1909
- Node: 15.0.0
- npm: 7.0.3

**Comment by ShenHongFei** [comment]
This PR might help:
https://github.com/TooTallNate/node-agent-base/pull/47
fix ERR_INVALID_PROTOCOL in NodeJS 15 when connect https url through http proxy

**Comment by bjansen** [comment]
Using `HTTPS_PROXY` as a workaround for https://github.com/npm/cli/issues/2060 does not work because of this second bug, outstanding.

**Comment by maxsxu** [comment]
I got the same error in my macOS with the same node/npm version.

I've fixed this error by unset all the proxy environment:

```
unset http_proxy; unset https_proxy; unset all_proxy;
```

You can run `npm install` correctly after that.

**Comment by nlf** [comment]
updating npm to anything newer than 7.0.6 should correct this as that's when we brought in the updated agent-base dependency

**Comment by AbhijeetAnand45** [comment]
change the url to https:// instead of http:// , Mine was type mistake

**Comment by rafis** [comment]
Downgrading npm from 8.1.4 to 6.14.15 fixes issue.

**Comment by IzharUlhaque** [comment]
> change the url to https:// instead of http:// , Mine was type mistake

Thank you Bro This work for me
