### ISSUE TITLE
[BUG] hapijs/lab repo fails to install

### ISSUE THREAD

**Issue by kanongil** [npm/cli#2005]
### Current Behavior:

npm install fails to install all dependencies, and installing specific dependency fails with npm error.

```
npm ERR! Cannot read property 'version' of undefined
```

From log:
```
71 verbose stack TypeError: Cannot read property 'version' of undefined
71 verbose stack     at Arborist.[saveIdealTree] (/home/node-15/.nvm/versions/node/v15.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:800:33)
71 verbose stack     at /home/node-15/.nvm/versions/node/v15.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:124:39
71 verbose stack     at async Arborist.reify (/home/node-15/.nvm/versions/node/v15.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:121:5)
71 verbose stack     at async install (/home/node-15/.nvm/versions/node/v15.0.0/lib/node_modules/npm/lib/install.js:40:5)
```

### Expected Behavior:

Npm installs all dependencies, and `npm install typescript` works.

### Steps To Reproduce:

```
git clone https://github.com/hapijs/lab.git && cd lab
npm install
npm install typescript
```

### Environment:

- Node: 15.0.0
- npm: 7.0.2

**Comment by kanongil** [comment]
While it this issue could be similar to the one in #1998, it appears to be unique since this fails a direct install. Also, if I remove the `peerDependenciesMeta` entry from `package.json`, it will work as expected.

It is interesting that the result depends on a third-party package.json property, which npm does not officially support. At least according to https://github.com/npm/cli/blob/v7.0.3/docs/content/configuring-npm/package-json.md.

**Comment by ljharb** [comment]
@kanongil npm definitely officially supports peerDependenciesMeta, it just appears to be missing from the docs.

**Comment by isaacs** [comment]
The issue here is that, while we do install `peerDependencies` by default, we _don't_ install _optional_ `peerDependencies`, as those are used more for plugins and typically the user does not wish for them to be installed.

We do officially support the `peerDependenciesMeta[pkgname].optional` boolean, but the docs are lagging behind the code, unfortunately.  They'll be updated ahead of moving v7.0.0 to GA status on the `latest` dist-tag.

What's happening here is that we're loading the peer edge ahead of the dev edge, and then skipping it.  And since the peer edge is optional, we don't install it.  For the root project at least, `dev` should take priority, I agree, so this is a bug.

**Comment by isaacs** [comment]
Also, even if it's _not_ a dev dependency, if you explicitly tell it to install a package, it should do that, even if it's an optional peer.

So, two bugs :)

**Comment by wadethomastt** [comment]
I have a similar issue trying to install Strapi with a mongo db atlas database

**Comment by wadethomastt** [comment]
0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'install',
0 verbose cli   '--prefix',
0 verbose cli   '/var/folders/z4/53h7lvg109x6r9hf2frjdgxm0000gn/T/strapi6de616a20ae9',
0 verbose cli   'strapi-connector-mongoose@3.0.0-beta.18.7'
0 verbose cli ]
1 info using npm@7.6.0
2 info using node@v15.11.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 0ms
5 timing config:load:builtin Completed in 0ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/var/folders/z4/53h7lvg109x6r9hf2frjdgxm0000gn/T/strapi6de616a20ae9/.npmrc Completed in 1ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/adaptactive/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 1ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 6ms
19 verbose npm-session bf9fa015b5e1ea25
20 timing npm:load Completed in 25ms
21 timing arborist:ctor Completed in 0ms
22 timing arborist:ctor Completed in 0ms
23 timing idealTree:init Completed in 14ms
24 timing idealTree:userRequests Completed in 3ms
25 silly idealTree buildDeps
26 silly fetch manifest strapi-connector-mongoose@3.0.0-beta.18.7
27 http fetch GET 304 https://registry.npmjs.org/strapi-connector-mongoose 596ms (from cache)
28 silly placeDep ROOT strapi-connector-mongoose@3.0.0-beta.18.7 OK for:  want: 3.0.0-beta.18.7
29 silly fetch manifest lodash@^4.17.11
30 silly fetch manifest mongoose@5.8.0
31 silly fetch manifest mongoose-float@^1.0.4
32 silly fetch manifest mongoose-long@^0.2.1
33 silly fetch manifest pluralize@^7.0.0
34 silly fetch manifest strapi-utils@3.0.0-beta.18.7
35 http fetch GET 304 https://registry.npmjs.org/mongoose 179ms (from cache)
36 http fetch GET 304 https://registry.npmjs.org/mongoose-long 386ms (from cache)
37 http fetch GET 304 https://registry.npmjs.org/pluralize 387ms (from cache)
38 http fetch GET 304 https://registry.npmjs.org/lodash 412ms (from cache)
39 http fetch GET 304 https://registry.npmjs.org/strapi-utils 409ms (from cache)
40 http fetch GET 304 https://registry.npmjs.org/mongoose-float 872ms (from cache)
41 timing idealTree:#root Completed in 1476ms
42 silly placeDep ROOT lodash@4.17.21 OK for: strapi-connector-mongoose@3.0.0-beta.18.7 want: ^4.17.11
43 silly placeDep ROOT mongoose@5.8.0 OK for: strapi-connector-mongoose@3.0.0-beta.18.7 want: 5.8.0
44 silly placeDep ROOT mongoose-float@1.0.4 OK for: strapi-connector-mongoose@3.0.0-beta.18.7 want: ^1.0.4
45 silly placeDep ROOT mongoose-long@0.2.1 OK for: strapi-connector-mongoose@3.0.0-beta.18.7 want: ^0.2.1
46 silly placeDep ROOT pluralize@7.0.0 OK for: strapi-connector-mongoose@3.0.0-beta.18.7 want: ^7.0.0
47 silly placeDep ROOT strapi-utils@3.0.0-beta.18.7 OK for: strapi-connector-mongoose@3.0.0-beta.18.7 want: 3.0.0-beta.18.7
48 silly fetch manifest bson@~1.1.1
49 silly fetch manifest kareem@2.3.1
50 silly fetch manifest mongodb@3.3.5
51 silly fetch manifest mongoose-legacy-pluralize@1.0.2
52 silly fetch manifest mpath@0.6.0
53 silly fetch manifest mquery@3.2.2
54 silly fetch manifest ms@2.1.2
55 silly fetch manifest regexp-clone@1.0.0
56 silly fetch manifest safe-buffer@5.1.2
57 silly fetch manifest sliced@1.0.1
58 silly fetch manifest sift@7.0.1
59 silly fetch manifest date-fns@^2.8.1
60 silly fetch manifest pino@^4.7.1
61 silly fetch manifest shelljs@^0.8.3
62 silly fetch manifest yup@^0.28.0
63 http fetch GET 304 https://registry.npmjs.org/regexp-clone 209ms (from cache)
64 http fetch GET 304 https://registry.npmjs.org/ms 211ms (from cache)
65 http fetch GET 304 https://registry.npmjs.org/bson 217ms (from cache)
66 http fetch GET 304 https://registry.npmjs.org/mongoose-legacy-pluralize 221ms (from cache)
67 http fetch GET 304 https://registry.npmjs.org/mpath 220ms (from cache)
68 http fetch GET 304 https://registry.npmjs.org/kareem 223ms (from cache)
69 http fetch GET 304 https://registry.npmjs.org/yup 305ms (from cache)
70 http fetch GET 304 https://registry.npmjs.org/mongodb 329ms (from cache)
71 http fetch GET 304 https://registry.npmjs.org/shelljs 327ms (from cache)
72 http fetch GET 304 https://registry.npmjs.org/sliced 444ms (from cache)
73 http fetch GET 304 https://registry.npmjs.org/pino 443ms (from cache)
74 http fetch GET 304 https://registry.npmjs.org/sift 452ms (from cache)
75 http fetch GET 304 https://registry.npmjs.org/date-fns 454ms (from cache)
76 http fetch GET 304 https://registry.npmjs.org/mquery 477ms (from cache)
77 http fetch GET 304 https://registry.npmjs.org/safe-buffer 475ms (from cache)
78 timing idealTree:node_modules/strapi-connector-mongoose Completed in 495ms
79 timing idealTree:node_modules/lodash Completed in 0ms
80 silly fetch manifest mongoose@*
81 silly placeDep ROOT bson@1.1.6 OK for: mongoose@5.8.0 want: ~1.1.1
82 silly placeDep ROOT kareem@2.3.1 OK for: mongoose@5.8.0 want: 2.3.1
83 silly placeDep ROOT mongodb@3.3.5 OK for: mongoose@5.8.0 want: 3.3.5
84 silly placeDep ROOT mongoose-legacy-pluralize@1.0.2 OK for: mongoose@5.8.0 want: 1.0.2
85 silly placeDep ROOT mpath@0.6.0 OK for: mongoose@5.8.0 want: 0.6.0
86 silly placeDep ROOT mquery@3.2.2 OK for: mongoose@5.8.0 want: 3.2.2
87 silly placeDep ROOT ms@2.1.2 OK for: mongoose@5.8.0 want: 2.1.2
88 silly placeDep ROOT regexp-clone@1.0.0 OK for: mongoose@5.8.0 want: 1.0.0
89 silly placeDep ROOT safe-buffer@5.1.2 OK for: mongoose@5.8.0 want: 5.1.2
90 silly placeDep ROOT sift@7.0.1 OK for: mongoose@5.8.0 want: 7.0.1
91 silly placeDep ROOT sliced@1.0.1 OK for: mongoose@5.8.0 want: 1.0.1
92 silly fetch manifest saslprep@^1.0.0
93 silly fetch manifest require_optional@^1.0.1
94 silly fetch manifest bluebird@3.5.1
95 silly fetch manifest debug@3.1.0
96 http fetch GET 304 https://registry.npmjs.org/debug 193ms (from cache)
97 http fetch GET 304 https://registry.npmjs.org/saslprep 200ms (from cache)
98 http fetch GET 304 https://registry.npmjs.org/bluebird 200ms (from cache)
99 http fetch GET 304 https://registry.npmjs.org/require_optional 204ms (from cache)
100 timing idealTree:node_modules/mongoose Completed in 216ms
101 timing idealTree:node_modules/bson Completed in 0ms
102 timing idealTree:node_modules/kareem Completed in 0ms
103 silly placeDep ROOT require_optional@1.0.1 OK for: mongodb@3.3.5 want: ^1.0.1
104 silly placeDep ROOT saslprep@1.0.3 OK for: mongodb@3.3.5 want: ^1.0.0
105 silly fetch manifest semver@^5.1.0
106 silly fetch manifest resolve-from@^2.0.0
107 silly fetch manifest sparse-bitfield@^3.0.3
108 http fetch GET 304 https://registry.npmjs.org/sparse-bitfield 161ms (from cache)
109 http fetch GET 304 https://registry.npmjs.org/resolve-from 167ms (from cache)
110 http fetch GET 304 https://registry.npmjs.org/semver 171ms (from cache)
111 timing idealTree:node_modules/mongodb Completed in 176ms
112 timing idealTree:node_modules/mongoose-float Completed in 0ms
113 timing idealTree:node_modules/mongoose-legacy-pluralize Completed in 0ms
114 timing idealTree:node_modules/mongoose-long Completed in 0ms
115 timing idealTree:node_modules/mpath Completed in 0ms
116 silly placeDep ROOT bluebird@3.5.1 OK for: mquery@3.2.2 want: 3.5.1
117 silly placeDep ROOT debug@3.1.0 OK for: mquery@3.2.2 want: 3.1.0
118 silly fetch manifest ms@2.0.0
119 timing idealTree:node_modules/mquery Completed in 5ms
120 timing idealTree:node_modules/bluebird Completed in 0ms
121 silly placeDep node_modules/debug ms@2.0.0 OK for: debug@3.1.0 want: 2.0.0
122 timing idealTree:node_modules/debug Completed in 1ms
123 timing idealTree:node_modules/ms Completed in 0ms
124 timing idealTree:node_modules/pluralize Completed in 0ms
125 timing idealTree:node_modules/regexp-clone Completed in 0ms
126 silly placeDep ROOT resolve-from@2.0.0 OK for: require_optional@1.0.1 want: ^2.0.0
127 silly placeDep ROOT semver@5.7.1 OK for: require_optional@1.0.1 want: ^5.1.0
128 timing idealTree:node_modules/require_optional Completed in 2ms
129 timing idealTree:node_modules/resolve-from Completed in 0ms
130 timing idealTree:node_modules/safe-buffer Completed in 0ms
131 silly placeDep ROOT sparse-bitfield@3.0.3 OK for: saslprep@1.0.3 want: ^3.0.3
132 silly fetch manifest memory-pager@^1.0.2
133 http fetch GET 304 https://registry.npmjs.org/memory-pager 136ms (from cache)
134 timing idealTree:node_modules/saslprep Completed in 138ms
135 timing idealTree:node_modules/semver Completed in 0ms
136 timing idealTree:node_modules/sift Completed in 0ms
137 timing idealTree:node_modules/sliced Completed in 0ms
138 silly placeDep ROOT memory-pager@1.5.0 OK for: sparse-bitfield@3.0.3 want: ^1.0.2
139 timing idealTree:node_modules/sparse-bitfield Completed in 1ms
140 timing idealTree:node_modules/memory-pager Completed in 0ms
141 silly placeDep ROOT date-fns@2.21.0 OK for: strapi-utils@3.0.0-beta.18.7 want: ^2.8.1
142 silly placeDep ROOT pino@4.17.6 OK for: strapi-utils@3.0.0-beta.18.7 want: ^4.7.1
143 silly placeDep ROOT shelljs@0.8.4 OK for: strapi-utils@3.0.0-beta.18.7 want: ^0.8.3
144 silly placeDep ROOT yup@0.28.5 OK for: strapi-utils@3.0.0-beta.18.7 want: ^0.28.0
145 silly fetch manifest chalk@^2.4.1
146 silly fetch manifest fast-json-parse@^1.0.3
147 silly fetch manifest fast-safe-stringify@^1.2.3
148 silly fetch manifest flatstr@^1.0.5
149 silly fetch manifest pino-std-serializers@^2.0.0
150 silly fetch manifest pump@^3.0.0
151 silly fetch manifest quick-format-unescaped@^1.1.2
152 silly fetch manifest split2@^2.2.0
153 silly fetch manifest glob@^7.0.0
154 silly fetch manifest interpret@^1.0.0
155 silly fetch manifest rechoir@^0.6.2
156 silly fetch manifest @babel/runtime@^7.9.6
157 silly fetch manifest fn-name@~3.0.0
158 silly fetch manifest lodash-es@^4.17.11
159 silly fetch manifest property-expr@^2.0.2
160 silly fetch manifest synchronous-promise@^2.0.10
161 silly fetch manifest toposort@^2.0.2
162 http fetch GET 304 https://registry.npmjs.org/chalk 207ms (from cache)
163 http fetch GET 304 https://registry.npmjs.org/fast-safe-stringify 223ms (from cache)
164 http fetch GET 304 https://registry.npmjs.org/rechoir 218ms (from cache)
165 http fetch GET 304 https://registry.npmjs.org/split2 224ms (from cache)
166 http fetch GET 304 https://registry.npmjs.org/quick-format-unescaped 231ms (from cache)
167 http fetch GET 304 https://registry.npmjs.org/glob 230ms (from cache)
168 http fetch GET 304 https://registry.npmjs.org/fast-json-parse 237ms (from cache)
169 http fetch GET 304 https://registry.npmjs.org/fn-name 230ms (from cache)
170 http fetch GET 304 https://registry.npmjs.org/@babel%2fruntime 233ms (from cache)
171 http fetch GET 304 https://registry.npmjs.org/interpret 235ms (from cache)
172 http fetch GET 304 https://registry.npmjs.org/pump 239ms (from cache)
173 http fetch GET 304 https://registry.npmjs.org/pino-std-serializers 241ms (from cache)
174 http fetch GET 304 https://registry.npmjs.org/lodash-es 305ms (from cache)
175 http fetch GET 304 https://registry.npmjs.org/toposort 305ms (from cache)
176 http fetch GET 304 https://registry.npmjs.org/synchronous-promise 308ms (from cache)
177 http fetch GET 304 https://registry.npmjs.org/property-expr 316ms (from cache)
178 http fetch GET 304 https://registry.npmjs.org/flatstr 358ms (from cache)
179 timing idealTree:node_modules/strapi-utils Completed in 365ms
180 timing idealTree:node_modules/date-fns Completed in 0ms
181 silly placeDep ROOT chalk@2.4.2 OK for: pino@4.17.6 want: ^2.4.1
182 silly placeDep ROOT fast-json-parse@1.0.3 OK for: pino@4.17.6 want: ^1.0.3
183 silly placeDep ROOT fast-safe-stringify@1.2.3 OK for: pino@4.17.6 want: ^1.2.3
184 silly placeDep ROOT flatstr@1.0.12 OK for: pino@4.17.6 want: ^1.0.5
185 silly placeDep ROOT pino-std-serializers@2.5.0 OK for: pino@4.17.6 want: ^2.0.0
186 silly placeDep ROOT pump@3.0.0 OK for: pino@4.17.6 want: ^3.0.0
187 silly placeDep ROOT quick-format-unescaped@1.1.2 OK for: pino@4.17.6 want: ^1.1.2
188 silly placeDep ROOT split2@2.2.0 OK for: pino@4.17.6 want: ^2.2.0
189 silly fetch manifest ansi-styles@^3.2.1
190 silly fetch manifest escape-string-regexp@^1.0.5
191 silly fetch manifest supports-color@^5.3.0
192 silly fetch manifest end-of-stream@^1.1.0
193 silly fetch manifest once@^1.3.1
194 silly fetch manifest through2@^2.0.2
195 http fetch GET 304 https://registry.npmjs.org/end-of-stream 163ms (from cache)
196 http fetch GET 304 https://registry.npmjs.org/supports-color 165ms (from cache)
197 http fetch GET 304 https://registry.npmjs.org/through2 164ms (from cache)
198 http fetch GET 304 https://registry.npmjs.org/once 175ms (from cache)
199 http fetch GET 304 https://registry.npmjs.org/ansi-styles 182ms (from cache)
200 http fetch GET 304 https://registry.npmjs.org/escape-string-regexp 191ms (from cache)
201 timing idealTree:node_modules/pino Completed in 202ms
202 silly placeDep ROOT ansi-styles@3.2.1 OK for: chalk@2.4.2 want: ^3.2.1
203 silly placeDep ROOT escape-string-regexp@1.0.5 OK for: chalk@2.4.2 want: ^1.0.5
204 silly placeDep ROOT supports-color@5.5.0 OK for: chalk@2.4.2 want: ^5.3.0
205 silly fetch manifest color-convert@^1.9.0
206 silly fetch manifest has-flag@^3.0.0
207 http fetch GET 304 https://registry.npmjs.org/color-convert 144ms (from cache)
208 http fetch GET 304 https://registry.npmjs.org/has-flag 159ms (from cache)
209 timing idealTree:node_modules/chalk Completed in 164ms
210 silly placeDep ROOT color-convert@1.9.3 OK for: ansi-styles@3.2.1 want: ^1.9.0
211 silly fetch manifest color-name@1.1.3
212 http fetch GET 304 https://registry.npmjs.org/color-name 162ms (from cache)
213 timing idealTree:node_modules/ansi-styles Completed in 164ms
214 silly placeDep ROOT color-name@1.1.3 OK for: color-convert@1.9.3 want: 1.1.3
215 timing idealTree:node_modules/color-convert Completed in 0ms
216 timing idealTree:node_modules/color-name Completed in 0ms
217 timing idealTree:node_modules/escape-string-regexp Completed in 0ms
218 timing idealTree:node_modules/fast-json-parse Completed in 0ms
219 timing idealTree:node_modules/fast-safe-stringify Completed in 0ms
220 timing idealTree:node_modules/flatstr Completed in 0ms
221 timing idealTree:node_modules/pino-std-serializers Completed in 0ms
222 silly placeDep ROOT end-of-stream@1.4.4 OK for: pump@3.0.0 want: ^1.1.0
223 silly placeDep ROOT once@1.4.0 OK for: pump@3.0.0 want: ^1.3.1
224 silly fetch manifest wrappy@1
225 http fetch GET 304 https://registry.npmjs.org/wrappy 137ms (from cache)
226 timing idealTree:node_modules/pump Completed in 140ms
227 timing idealTree:node_modules/end-of-stream Completed in 0ms
228 silly placeDep ROOT wrappy@1.0.2 OK for: once@1.4.0 want: 1
229 timing idealTree:node_modules/once Completed in 1ms
230 timing idealTree:node_modules/quick-format-unescaped Completed in 0ms
231 silly placeDep ROOT glob@7.1.6 OK for: shelljs@0.8.4 want: ^7.0.0
232 silly placeDep ROOT interpret@1.4.0 OK for: shelljs@0.8.4 want: ^1.0.0
233 silly placeDep ROOT rechoir@0.6.2 OK for: shelljs@0.8.4 want: ^0.6.2
234 silly fetch manifest fs.realpath@^1.0.0
235 silly fetch manifest inflight@^1.0.4
236 silly fetch manifest inherits@2
237 silly fetch manifest minimatch@^3.0.4
238 silly fetch manifest path-is-absolute@^1.0.0
239 silly fetch manifest resolve@^1.1.6
240 http fetch GET 304 https://registry.npmjs.org/minimatch 165ms (from cache)
241 http fetch GET 304 https://registry.npmjs.org/inherits 168ms (from cache)
242 http fetch GET 304 https://registry.npmjs.org/fs.realpath 171ms (from cache)
243 http fetch GET 304 https://registry.npmjs.org/path-is-absolute 170ms (from cache)
244 http fetch GET 304 https://registry.npmjs.org/resolve 180ms (from cache)
245 http fetch GET 304 https://registry.npmjs.org/inflight 223ms (from cache)
246 timing idealTree:node_modules/shelljs Completed in 228ms
247 silly placeDep ROOT fs.realpath@1.0.0 OK for: glob@7.1.6 want: ^1.0.0
248 silly placeDep ROOT inflight@1.0.6 OK for: glob@7.1.6 want: ^1.0.4
249 silly placeDep ROOT inherits@2.0.4 OK for: glob@7.1.6 want: 2
250 silly placeDep ROOT minimatch@3.0.4 OK for: glob@7.1.6 want: ^3.0.4
251 silly placeDep ROOT path-is-absolute@1.0.1 OK for: glob@7.1.6 want: ^1.0.0
252 silly fetch manifest brace-expansion@^1.1.7
253 http fetch GET 304 https://registry.npmjs.org/brace-expansion 167ms (from cache)
254 timing idealTree:node_modules/glob Completed in 172ms
255 timing idealTree:node_modules/fs.realpath Completed in 0ms
256 timing idealTree:node_modules/inflight Completed in 0ms
257 timing idealTree:node_modules/inherits Completed in 0ms
258 timing idealTree:node_modules/interpret Completed in 0ms
259 silly placeDep ROOT brace-expansion@1.1.11 OK for: minimatch@3.0.4 want: ^1.1.7
260 silly fetch manifest balanced-match@^1.0.0
261 silly fetch manifest concat-map@0.0.1
262 http fetch GET 304 https://registry.npmjs.org/concat-map 141ms (from cache)
263 http fetch GET 304 https://registry.npmjs.org/balanced-match 180ms (from cache)
264 timing idealTree:node_modules/minimatch Completed in 181ms
265 silly placeDep ROOT balanced-match@1.0.2 OK for: brace-expansion@1.1.11 want: ^1.0.0
266 silly placeDep ROOT concat-map@0.0.1 OK for: brace-expansion@1.1.11 want: 0.0.1
267 timing idealTree:node_modules/brace-expansion Completed in 3ms
268 timing idealTree:node_modules/balanced-match Completed in 0ms
269 timing idealTree:node_modules/concat-map Completed in 0ms
270 timing idealTree:node_modules/path-is-absolute Completed in 0ms
271 silly placeDep ROOT resolve@1.20.0 OK for: rechoir@0.6.2 want: ^1.1.6
272 silly fetch manifest is-core-module@^2.2.0
273 silly fetch manifest path-parse@^1.0.6
274 http fetch GET 304 https://registry.npmjs.org/is-core-module 149ms (from cache)
275 http fetch GET 304 https://registry.npmjs.org/path-parse 151ms (from cache)
276 timing idealTree:node_modules/rechoir Completed in 153ms
277 silly placeDep ROOT is-core-module@2.2.0 OK for: resolve@1.20.0 want: ^2.2.0
278 silly placeDep ROOT path-parse@1.0.6 OK for: resolve@1.20.0 want: ^1.0.6
279 silly fetch manifest has@^1.0.3
280 http fetch GET 304 https://registry.npmjs.org/has 260ms (from cache)
281 timing idealTree:node_modules/resolve Completed in 263ms
282 silly placeDep ROOT has@1.0.3 OK for: is-core-module@2.2.0 want: ^1.0.3
283 silly fetch manifest function-bind@^1.1.1
284 http fetch GET 304 https://registry.npmjs.org/function-bind 136ms (from cache)
285 timing idealTree:node_modules/is-core-module Completed in 138ms
286 silly placeDep ROOT function-bind@1.1.1 OK for: has@1.0.3 want: ^1.1.1
287 timing idealTree:node_modules/has Completed in 0ms
288 timing idealTree:node_modules/function-bind Completed in 0ms
289 timing idealTree:node_modules/path-parse Completed in 0ms
290 silly placeDep ROOT through2@2.0.5 OK for: split2@2.2.0 want: ^2.0.2
291 silly fetch manifest readable-stream@~2.3.6
292 silly fetch manifest xtend@~4.0.1
293 http fetch GET 304 https://registry.npmjs.org/xtend 147ms (from cache)
294 http fetch GET 304 https://registry.npmjs.org/readable-stream 245ms (from cache)
295 timing idealTree:node_modules/split2 Completed in 248ms
296 silly placeDep ROOT has-flag@3.0.0 OK for: supports-color@5.5.0 want: ^3.0.0
297 timing idealTree:node_modules/supports-color Completed in 1ms
298 timing idealTree:node_modules/has-flag Completed in 0ms
299 silly placeDep ROOT readable-stream@2.3.7 OK for: through2@2.0.5 want: ~2.3.6
300 silly placeDep ROOT xtend@4.0.2 OK for: through2@2.0.5 want: ~4.0.1
301 silly fetch manifest core-util-is@~1.0.0
302 silly fetch manifest isarray@~1.0.0
303 silly fetch manifest process-nextick-args@~2.0.0
304 silly fetch manifest string_decoder@~1.1.1
305 silly fetch manifest util-deprecate@~1.0.1
306 http fetch GET 304 https://registry.npmjs.org/process-nextick-args 147ms (from cache)
307 http fetch GET 304 https://registry.npmjs.org/string_decoder 166ms (from cache)
308 http fetch GET 304 https://registry.npmjs.org/core-util-is 169ms (from cache)
309 http fetch GET 304 https://registry.npmjs.org/isarray 171ms (from cache)
310 http fetch GET 304 https://registry.npmjs.org/util-deprecate 201ms (from cache)
311 timing idealTree:node_modules/through2 Completed in 207ms
312 silly placeDep ROOT core-util-is@1.0.2 OK for: readable-stream@2.3.7 want: ~1.0.0
313 silly placeDep ROOT isarray@1.0.0 OK for: readable-stream@2.3.7 want: ~1.0.0
314 silly placeDep ROOT process-nextick-args@2.0.1 OK for: readable-stream@2.3.7 want: ~2.0.0
315 silly placeDep ROOT string_decoder@1.1.1 OK for: readable-stream@2.3.7 want: ~1.1.1
316 silly placeDep ROOT util-deprecate@1.0.2 OK for: readable-stream@2.3.7 want: ~1.0.1
317 timing idealTree:node_modules/readable-stream Completed in 5ms
318 timing idealTree:node_modules/core-util-is Completed in 0ms
319 timing idealTree:node_modules/isarray Completed in 0ms
320 timing idealTree:node_modules/process-nextick-args Completed in 0ms
321 timing idealTree:node_modules/string_decoder Completed in 0ms
322 timing idealTree:node_modules/util-deprecate Completed in 0ms
323 timing idealTree:node_modules/wrappy Completed in 0ms
324 timing idealTree:node_modules/xtend Completed in 0ms
325 silly placeDep ROOT @babel/runtime@7.13.10 OK for: yup@0.28.5 want: ^7.9.6
326 silly placeDep ROOT fn-name@3.0.0 OK for: yup@0.28.5 want: ~3.0.0
327 silly placeDep ROOT lodash-es@4.17.21 OK for: yup@0.28.5 want: ^4.17.11
328 silly placeDep ROOT property-expr@2.0.4 OK for: yup@0.28.5 want: ^2.0.2
329 silly placeDep ROOT synchronous-promise@2.0.15 OK for: yup@0.28.5 want: ^2.0.10
330 silly placeDep ROOT toposort@2.0.2 OK for: yup@0.28.5 want: ^2.0.2
331 silly fetch manifest regenerator-runtime@^0.13.4
332 http fetch GET 304 https://registry.npmjs.org/regenerator-runtime 166ms (from cache)
333 timing idealTree:node_modules/yup Completed in 170ms
334 silly placeDep ROOT regenerator-runtime@0.13.7 OK for: @babel/runtime@7.13.10 want: ^0.13.4
335 timing idealTree:node_modules/@babel/runtime Completed in 1ms
336 timing idealTree:node_modules/fn-name Completed in 0ms
337 timing idealTree:node_modules/lodash-es Completed in 0ms
338 timing idealTree:node_modules/property-expr Completed in 0ms
339 timing idealTree:node_modules/regenerator-runtime Completed in 0ms
340 timing idealTree:node_modules/synchronous-promise Completed in 0ms
341 timing idealTree:node_modules/toposort Completed in 0ms
342 timing idealTree:node_modules/debug/node_modules/ms Completed in 0ms
343 timing idealTree:buildDeps Completed in 5322ms
344 timing idealTree:fixDepFlags Completed in 1ms
345 timing idealTree Completed in 5342ms
346 timing reify:loadTrees Completed in 5343ms
347 timing reify:diffTrees Completed in 0ms
348 silly reify moves {}
349 timing reify:retireShallow Completed in 1ms
350 timing reify:createSparse Completed in 0ms
351 timing reify:loadBundles Completed in 0ms
352 timing reify:unpack Completed in 1ms
353 timing reify:unretire Completed in 0ms
354 timing build:queue Completed in 0ms
355 timing build:deps Completed in 0ms
356 timing build Completed in 0ms
357 timing reify:build Completed in 1ms
358 timing reify:trash Completed in 0ms
359 timing command:install Completed in 5355ms
360 verbose stack TypeError: Cannot read property 'version' of undefined
360 verbose stack     at Arborist.[saveIdealTree] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:893:33)
360 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:134:39
360 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:130:5)
360 verbose stack     at async install (/usr/local/lib/node_modules/npm/lib/install.js:38:3)
361 verbose cwd /Users/adaptactive/Reach/ReaCh-Gatsbyv3
362 verbose Darwin 20.3.0
363 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--prefix" "/var/folders/z4/53h7lvg109x6r9hf2frjdgxm0000gn/T/strapi6de616a20ae9" "strapi-connector-mongoose@3.0.0-beta.18.7"
364 verbose node v15.11.0
365 verbose npm  v7.6.0
366 error Cannot read property 'version' of undefined
367 verbose exit 1
