### ISSUE TITLE
[BUG] `npm rebuild` should take path, breaks `npm edit`

### ISSUE THREAD

**Issue by isaacs** [npm/cli#2018]
After running the editor, `npm edit` runs `npm rebuild <arg>` to rebuild the package that had been edited.  However, this fails when editing a nested package as an argument like `npm edit write/mkdirp`, because `npm rebuild` only takes version/range specifiers, and `write/mkdirp` isn't one of those.

Also, using `npm edit foo/bar` to edit the package at `./node_modules/foo/node_modules/bar` is just super weird anyway, and supporting `npm rebuild foo/bar` is probably a bad idea as well.  Since this has been broken for who knows how long, I don't think it should be considered a breaking change to replace the semantics with something more sensible.

### Current Behavior:

`npm edit` attempts to rebuild a package by passing in the same argument that it got.  However, it takes `foo/bar` to refer to the package at `node_modules/foo/node_modules/bar`, so the `npm rebuild` call fails.

### Expected Behavior:

`npm rebuild <location>` should work as expected, rebuilding the package at that location.

`npm edit` should have a better syntax for specifying nested packages, which doesn't cause the subsequent rebuild to fail.

### Steps To Reproduce:

In the npm cli repo, run `npm edit write/mkdirp`.  Close the editor, and see the error

```
npm ERR! `npm rebuild` only supports SemVer version/range specifiers
```

### Environment:

npm 7.0.3

**Comment by isaacs** [comment]
Also, running `npm rebuild semver` will rebuild _all_ instances of semver, not just the one edited.  So that's definitely a bug as well.

**Comment by 1Maty** [comment]
Muchas gracias flaco! :)
