### ISSUE TITLE
[BUG] `sudo npm start` is not enough to listen on port 80 (access denied, EACCES -13)

### ISSUE THREAD

**Issue by ilyaigpetrov** [npm/cli#2027]
### Current Behavior:

`sudo npm start` script which starts http server on port 80 throws an error `Error: listen EACCES: permission denied 0.0.0.0:80`.

### Expected Behavior:

`sudo npm start` must work without errors.

### Steps To Reproduce:

1. vim ./test.mjs:
```js
import http from 'http';
http.Server().listen(80);
```
2. Add a start script to package.json that runs `node ./test.mjs`
3. Run `sudo npm start` and see it fails `EACCES -13` (access denied).
4. Run `sudo node ./test.mjs` and see it works without errors.

### Environment:
- OS: Linux Mint 20
- Node: v15.0.1
- npm: 7.0.3

### Did it work before?

Yes, it worked as desired for the previous version of npm (6.x) and NodeJS 14.x.

**Comment by ioslh** [comment]
Same issue occurs

**Comment by darcyclarke** [comment]
@ilyaigpetrov The folder you're running `npm start` in must be a root-owned directory if you use `sudo`; Can you try `chown`ing the directory to give permissions/ownership to `root` & trying again.

**Comment by cdoublev** [comment]
I confirm it's working after `chown`ing root as the owner of the directory from where `sudo npm start` is run (node v15.5.0, npm v7.3.0, Debian Buster). It also works (without `chown`ing or `sudo`ing) if listening on port 8080.

StackOverflow might be more appropriate for the following, but if `sudo` privilege is not forwarded from the command line to the script file when the process working directory is not owned by root (can you confirm it's a change that happened in npm v7?), do you think that adding NodeJS to the Nginx group is the more appropriate workaround when trying to create a socket file to communicate between NodeJS and Nginx while running a server start script (which sets Nginx as the owner of the socket file) run from a Vagrant shared folder, ie. whose ownership can't be set to root?

**Comment by sahilrajput03** [comment]
Why is this issue closed, I still can't run my server via `sudo npm start`, and its only running if I use port 8080.

This is not good behaviour from npm at all!!!

Please fix this..!!!!

**Comment by sahilrajput03** [comment]
I think I need to revert to npm to previous version :( !!
I can't believe this issue is there in `npm v7.6.3` .

**Comment by sahilrajput03** [comment]
`sudo chown root .`
Running above command in the directory and then I can use any port I want, yikes!!!
But its something bad to remember always, :(

**Comment by itssamuelrowe** [comment]
Why is this issue closed? I'm facing the same issue with v7.6.3.

Anyone looking for a solution, `sudo node ./app/start.js` resolved the issue for me. It appears that npm isn't "passing down" the sudo privilege to the node instance for some reason.

**Comment by mhdtahawi** [comment]
This should be reopened !
I don't want chown all my code to root for my server to run on port 80.

The solution proposed (`chown`) is a hack, not a solution !

@darcyclarke , where does it say that a folder has to be owned by root to be run as root ?

**Comment by cdoublev** [comment]
I agree that something in the documentation would be appropriated. I only found [this](https://docs.npmjs.com/cli/v7/using-npm/scripts):

> Don't prefix your script commands with "sudo". If root permissions are required for some reason, then it'll fail with that error, and the user will sudo the npm command in question.

The above documentation does not address this issue, but I think not forwarding root privilege to npm scripts is a good security measure. I would advise to use another port on a local machine and to use a process manager in production.

**Comment by mhdtahawi** [comment]
Yes, I agree. However, sometimes there are situations where passing root privilege's is the better solution. 
 I am completely aware of the risk and I don't see why my runtime environment should dictate how I should work.
 The change that was made is a breaking change that was not documented nor stated in the change log as far as I can see, the current behavior is not aligned with the doc and it should be changed. 
 Permissions of an invoked script should be defined by the invoking process (and its parents) not by the owner user.
 
 Or at least change the doc

**Comment by parmleyhunt** [comment]
Agreed how it starts should dictate. However chowning what directory exactly the module that is the parent or the module that needs to have root? Very confused on the need for this change and the intended behaviour. This is kind of feature breaking like I almost just want to remove npm from my project all together.

**Comment by woohling** [comment]
Issue is still there in npm 8.15.0. Anyone fixing this issue? Or anyone in NPM team treating it as a bug?

**Comment by adminy** [comment]
```bash
serve -l 80
```
 works no problem
```bash
npm start
```
gives
```javascript
Error: listen EACCES: permission denied ::1:80
    at Server.setupListenHandle [as _listen2] (node:net:1468:21)
    at listenInCluster (node:net:1533:12)
    at GetAddrInfoReqWrap.doListen [as callback] (node:net:1682:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:113:8) {
  code: 'EACCES',
  errno: -13,
  syscall: 'listen',
  address: '::1',
  port: 80
}
```

sounds like its an npm issue to me.
Why should the admin user on the mac need sudo to do anything? this wasn't an issue in the past and it is now.
