### ISSUE TITLE
[BUG] Add `"max-len": ["error", 80]` to .eslintrc.json and make it work

### ISSUE THREAD

**Issue by isaacs** [npm/cli#2029]
We have a lot of long lines, let's shorten them.

Be smart about making the choices to split lines, no fake internet points for cutting strings and making them unreadable!

**Comment by ljharb** [comment]
You can configure max-len to ignore lines with long strings or regexes or urls; i suggest doing so. Example: https://github.com/airbnb/javascript/blob/2c5c88d0487db3024e8a20bb20f46933a03dd8aa/packages/eslint-config-airbnb-base/rules/style.js#L205

**Comment by dominguetigs** [comment]
@isaacs 
Is anyone doing this issue?

**Comment by Gurinderp** [comment]
Could I take on this issue if no one is currently working on it? @isaacs 
Not sure if @dominguetigs still wants it.

**Comment by dominguetigs** [comment]
You can do it @Gurinderp

**Comment by tutur0001** [comment]
Me I can if you want

**Comment by codexofc** [comment]
Can you assign me on this issue ? @isaacs

**Comment by Edu93Jer** [comment]
Hi @isaacs is anyone still working on the case? If no, could you please explain to me a little more about the project, I'm a newbie and would like to contribute, or is the issue is closed?

**Comment by Edu93Jer** [comment]
@darcyclarke - @isaacs, so I just added the "max-len" to the .eslintrc.json, but what do you mean with make it work?
It should be working right, just adding this rules...
`"max-len": ["error", 80, {
      "ignoreUrls": true,
      "ignoreComments": false,
      "ignoreRegExpLiterals": true,
      "ignoreStrings": true,
      "ignoreTemplateLiterals": true
    }]`

**Comment by isaacs** [comment]
Well, there are quite a few places (iirc?) that are longer than 80 chars.  So `npm run lint` should not raise any errors with that option.

**Comment by a2br** [comment]
Looks like https://github.com/npm/cli/pull/2361 has been merged. Shouldn't this issue be closed too?
