### ISSUE TITLE
[BUG] Can't install new dependencies into workspace package with workspace dependencies

### ISSUE THREAD

**Issue by justinfagnani** [npm/cli#2035]
### Current Behavior:
`npm i some-package` fails if run in a workspace package that depends on another workspace package. The error is that the other workspace package is not found in the registray:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/other-package - Not found
```

Here `other-package` is a private package in the same workspace.

You also can't add a dependency manually and run `npm i` in the root of the workspace due to #1984 

So there appears to be no way to add new dependencies in a workspace, aside from deleting the top-level node_modules folder and package-lock.

### Expected Behavior:
`npm i` inside a workspace package should update the package.json file and install the dependency.

### Steps To Reproduce:
1. In a workspace with packages `a` and `b`, with `a` depending on `b`
2. Do an initial install at the workspace root to set everything up
3. cd to `packages/a`
4. Run `npm i {some-package}`
5. See error...

### Environment:
- OS: macOS
- Node: 15
- npm: 17.0.5

**Comment by protyposis** [comment]
This is probably related to what I described in https://github.com/npm/cli/issues/2036#issuecomment-716739306. The current answer in https://github.com/npm/cli/issues/2036#issuecomment-716762752 is that `npm install` does not support workspace packages yet and we need to edit the `package.json` manually (which, as you already said, doesn't work: https://github.com/npm/cli/issues/1984).

**Comment by samscodes** [comment]
I have the same issue

**Comment by darcyclarke** [comment]
@justinfagnani we're working on improving the workspace experiences for these types of scenarios this quarter.

**Comment by ruyadorno** [comment]
Starting from **npm@7.14.0** `npm install` now supports adding dependencies to configured workspaces using the following syntax:

```
$ npm install <pkg> -w <workspace-name>
```

It's also possible to install a workspace into another, e.g:

```
npm init -y
Wrote to <path>/test-new-workspaces/package.json

$ npm init -w packages/a -y
Wrote to <path>/test-new-workspaces/packages/a/package.json

$ npm init -w packages/b -y
Wrote to <path>/test-new-workspaces/packages/b/package.json

$ npm i b -w a

added 2 packages, and audited 5 packages in 723ms

found 0 vulnerabilities

$ npm ls
test-new-workspaces@1.0.0 <path>/test-new-workspaces
├─┬ a@1.0.0 -> <path>/test-new-workspaces/packages/a
│ └── b@1.0.0 deduped -> <path>/test-new-workspaces/packages/b
└── b@1.0.0 -> <path>/test-new-workspaces/packages/b
```

**Comment by craigphicks** [comment]
@ruyadorno - I found that `npm i b -w a` would install the external package 'b' from npm.
To get it to work properly the exact version is necessary:
```
npm i b@1.0.0 -w a

```
in this case.

-------------------------------------------
EDIT:  adding exact procedure to recreate the error when NOT using the exact version, but the commands that @ruyadorno provided.  I am using 

- npm 7.21.1
- node v14.7.4

In an empty folder execute a shell script as follows: 
```
npm init -y
npm init -w packages/a -y
npm init -w packages/b -y
npm i b -w a
npm ls
```
The output (ending in a error ) is a as follows - 
```
Wrote to /home/craig/tmp/package.json:

{
  "name": "tmp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


Wrote to /home/craig/tmp/packages/a/package.json:

{
  "name": "a",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


Wrote to /home/craig/tmp/packages/b/package.json:

{
  "name": "b",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}



added 2 packages, and audited 4 packages in 562ms

found 0 vulnerabilities
tmp@1.0.0 /home/craig/tmp
├─┬ a@1.0.0 -> ./packages/a
│ └── b@2.0.1
└── UNMET DEPENDENCY b@file:/home/craig/tmp/packages/b

npm ERR! code ELSPROBLEMS
npm ERR! missing: b@file:/home/craig/tmp/packages/b, required by tmp@1.0.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/craig/.npm/_logs/2021-10-02T21_45_42_165Z-debug.log
```

**Comment by jamiebarrow** [comment]
I had the same issue on npm 7.24.1 and it turned out because I was using a name other than "packages" for the folder that the workspace packages are in, e.g. the below structure with "modules" as the folder name caused an error:

```
repo/
|__ modules/
|   |__ core/
|   |   |__ package.json
|   |
|   |__ app/
|       |__ package.json
|
|__ package.json
```

whereas the below with the 'standard' name of "packages" seems to work successfully:

```
repo/
|__ packages/
|   |__ core/
|   |   |__ package.json
|   |
|   |__ app/
|       |__ package.json
|
|__ package.json
```

**Comment by Brennvo** [comment]
> @ruyadorno - I found that `npm i b -w a` would install the external package 'b' from npm. To get it to work properly the exact version is necessary:
> 
> ```
> npm i b@1.0.0 -w a
> ```
> 
> in this case.

This works when adding the dependency in the lerna monorepo. I am running into issues, however, when I try installing a tarball that has this internal dependency. For example:

```
repo/
|__ packages/
|   |__ a/
|   |   |__ package.json
|   |
|   |__ b/
|       |__ package.json
|       |__ b-1.0.0.tgz
|
|__ package.json
```
If workspace `b` has a direct dependency on workspace `a`, when I go to install the workspace `b` tarball file in *another* external application (locally), I get a new error related to the `node_modules` in workspace `a`.

**Comment by craigphicks** [comment]
@Brennvo  - Can you show the working commands you used, including the `lerna` commands?

**Comment by iSuslov** [comment]
Unbelievable. Look at this.
`npm -v //8.1.2
` 

```bash
npm init -y
npm init -w packages/a -y
npm init -w packages/b -y
```

...Everything is OK

```bash
npm i b@1.0.0 -w a
```

`added 2 packages, and audited 5 packages in 908ms` also works great

```bash
npm init -w packages/c -y
```
Created package `c`

```bash
npm i c@1.0.0 -w a
```
Added package `c` to `a`.

**Now magic happens**

```bash
npm init -w packages/z -y
```
Created package `z`

```bash
npm i z@1.0.0 -w a
```

```bash
npm ERR! code ETARGET
npm ERR! notarget No matching version found for z@1.0.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:

```

**How is that possible?**

It turns out that package name matters when you work with workspaces. 

@wraithgar @fritzy @lukekarrys  could you please comment on this?

**Comment by kacper-serewis** [comment]
I'm having the same problem; Package with name: `a-style-flex` inside `packages/components/styles/flex` is not recognised. 

It works only when I change `styles` in path to **style**

**Comment by iSuslov** [comment]
I created separated issue https://github.com/npm/cli/issues/4379
