### ISSUE TITLE
[npm update] won't save updated versions to package.json

### ISSUE THREAD

**Issue by emeryao** [npm/cli#2039]
### Current Behavior:

with npm v7 the versions in `package.json` file won't be updated anymore after running `npm update`

### Expected Behavior:

with npm v6 `6.14.8` those versions are updated and save to the file of `package.json` as well as `package-lock.json`

### Steps To Reproduce:
1. create a working folder with a `package.json` and `package-lock.json` file with an outdated dependency and a `node_modules` folder contains the outdated package folder
1. can be created with `npm init -y && npm i @angular/core@10.1.6`
1. the file of `package.json` should be like:
```json
{
    "dependencies": {
        "@angular/core": "^10.1.6"
    },
    "version": "1.0.0"
}
```
1. run the command of `npm outdated` and it shows that the package has a `Wanted` and `Latest` version
1. after running the command of `npm update` and file of `package-lock.json` has been updated with the new version of the package but the `package.json` file has **not** been updated with the new version which behaves differently from npm v6.14.8 or earlier and the `package.json` file should be like below in `v6`:
```json
{
    "dependencies": {
        "@angular/core": "^10.2.0"
    },
    "version": "1.0.0"
}
```

I'm not sure this is a bug or a *breaking change* by design so just file a bug issue here

### Environment:
- OS: Windows 10
- Node: 15.0.1
- npm: 7.0.5

---
Sorry for my poor English 😜

**Comment by emeryao** [comment]
the *auto updated* versions to `package.json` is the feature that I preferred npm so please bring it back if possible

**Comment by WuglyakBolgoink** [comment]
same

**Comment by samscodes** [comment]
I have the same problem.

**Comment by WuglyakBolgoink** [comment]
in my case I can't upgrade angular from v10.1.4 to v10.2.0 because old version already was installed... after removing package-lock file and node_modules folder nothing changed. `npm install` break the installing process

**Comment by emeryao** [comment]
> in my case I can't upgrade angular from v10.1.4 to v10.2.0 because old version already was installed... after removing package-lock file and node_modules folder nothing changed. `npm install` break the installing process

with npm `v6.14.8` the versions updated in both `package.json` and `package-lock.json` after running `npm update`  but with npm `v7.0.5` only `package-lock.json` have the updated version

**Comment by WuglyakBolgoink** [comment]
> > in my case I can't upgrade angular from v10.1.4 to v10.2.0 because old version already was installed... after removing package-lock file and node_modules folder nothing changed. `npm install` break the installing process
> 
> with npm `v6.14.8` the versions updated in both `package.json` and `package-lock.json` after running `npm update` but with npm `v7.0.5` only `package-lock.json` have the updated version

correct, downgrade to node@14.x and npm@6.x fix the problem

**Comment by dan-mba** [comment]
If the change in npm update between v6 & v7 with regards to package.json is working as designed, then the [documentation](https://docs.npmjs.com/cli/v7/commands/npm-update) should be updated.

It currently states:

> As of npm@5.0.0, the npm update will change package.json to save the new version as the minimum required dependency. To get the old behavior, use npm update --no-save.

**Comment by mlippert** [comment]
I upgraded npm to v7 today and immediately ran into this problem, also. The documentation for v7 does remove the statement mentioned by @dan-mba but if the functionality is deliberately changed that really needs to be noted as a **breaking change**.

**Comment by willstott101** [comment]
The documentation still seems to refer to a `save` option: https://docs.npmjs.com/cli/v7/commands/npm-update#package-lock

**Comment by darcyclarke** [comment]
Closing: As of [`npm@8.3.2`](https://github.com/npm/cli/releases/tag/v8.3.2) you can now run `npm update --save` to save changes back to `package.json` like you could in v6.
