### ISSUE TITLE
issue from npm

### ISSUE THREAD

**Issue by sindhurgowda** [npm/cli#2041]
npm ERR! code EINVALIDTYPE
npm ERR! typeerror Error: Argument #2: Expected array but got string
npm ERR! typeerror     at EventEmitter.install (C:\Program Files\nodejs\node_modules\npm\lib\install.js:195:3)
npm ERR! typeerror     at Object.commandCache.<computed> (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:156:13)
npm ERR! typeerror     at C:\Program Files\nodejs\node_modules\npm\lib\link.js:93:24
npm ERR! typeerror     at callback (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:295:20)
npm ERR! typeerror     at FSReqCallback.oncomplete (fs.js:176:21)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2020-10-26T05_51_40_360Z-debug.log

**Comment by sindhurgowda** [comment]
let me know how to solve issue

**Comment by ljharb** [comment]
What version of node and npm are you using?

**Comment by sindhurgowda** [comment]
npm : 6.14.7
node : v14.7.0

**Comment by ljharb** [comment]
Can you try two things:
1. `npm install -g npm@6`, and see if it happens with the latest npm 6?
1. if that still fails, `npm install -g npm@7` and see if it happens with npm 7?

**Comment by sindhurgowda** [comment]
npm install -g npm@6 and npm install -g npm@7 tried installing but still failed

**Comment by ljharb** [comment]
If both of those failed, could you try installing the latest version of node 14, 14.13?

**Comment by wraithgar** [comment]
If this is still a bug please open a new issue following the new issue template, including steps to reproduce so we can try to debug this better.
