### ISSUE TITLE
[BUG] default registry in .npmrc isn't used during npm install

### ISSUE THREAD

**Issue by gboston** [npm/cli#2043]
### Current Behavior:
I'm setting a different default registry in my project .npmrc file. via

```sh
echo 'https://registry_url' > .npmrc
```

I would expect this results in packages only taken from my registry instead of npmjs.org. When I do an npm install, I see all packages referred to npmjs.org instead of the custom registry in my package-lock.json. When I do an install which explicitly mentions the registry everything is working as expected. I only see references to the registry_url in package-lock.json. So the following command works fine:

```
npm install --registry https://registry_url
```
### Expected Behavior:
I would expect that the default registry defined in the npmrc file is used instead of npmjs.org

### Steps To Reproduce:
1. Init new nodejs project
2. touch .npmrc
3. echo 'https://registry_url' > .npmrc
4. npm install
5. Check package-lock.json all references are still pointing to npmjs.org (this is not the case when installing explicitly with the registry parameter)

### Environment:

Os: Mac 10.15.6
Nodev: 12.18.2
npm: 6.14.5

**Comment by ljharb** [comment]
The way to set a registry in .npmrc is with `registry=https://registry_url`, not with a bare URL.
