### ISSUE TITLE
Error code E404 @bug

### ISSUE THREAD

**Issue by joaogrgomes** [npm/cli#2053]
joao@samsung:~/apf-apj-gfn-base-online-master$ npm start

> apf-apj-gfn-base-online@1.4.1 start /home/joao/apf-apj-gfn-base-online-master
> http-server

sh: 1: http-server: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! apf-apj-gfn-base-online@1.4.1 start: `http-server`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the apf-apj-gfn-base-online@1.4.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/joao/.npm/_logs/2020-10-27T11_34_42_595Z-debug.log

**Comment by darcyclarke** [comment]
@joaogrgomes this doesn't look like it's a bug with npm itself; Potentially you need to install [`http-server`](https://www.npmjs.com/package/http-server) before running `npm start` (but there may be other issues with your project that I can't determine with the above at the moment). If you find a bug in npm itself, please use our issue template in the future: https://github.com/npm/cli/issues/new/choose
