### ISSUE TITLE
[BUG] npm ls, prune do not respect workspaces(?)

### ISSUE THREAD

**Issue by markmckenna** [npm/cli#2056]
### Current Behavior:
```
$ find .
.
./package.json
./project-a
./project-a/package.json
./project-b
./project-b/package.json

$ cat package.json
{
  "name": "root",
  "workspaces": [
    "project-a",
    "project-b"
  ]
}

$ cat project-a/package.json
{
  "name": "project-a",
  "dependencies": {
    "webpack": "^4.41",
    "webpack-dev-server": "^3.9"
  }
}

$ cat project-b/package.json
{
  "name": "project-b",
  "dependencies": {
    "webpack": "^4.41",
    "webpack-dev-server": "^3.9"
  }
}

$ npm install
<unrelated warnings>

added 591 packages in 25s

$ ls
node_modules package.json project-a    project-b

$ npm ls
root@ /tmp
├── anymatch@3.1.1 extraneous
├── binary-extensions@2.1.0 extraneous
├── bindings@1.5.0 extraneous
├── chokidar@3.4.3 extraneous
├── file-uri-to-path@1.0.0 extraneous
├── fsevents@2.1.3 extraneous
├── glob-parent@5.1.1 extraneous
├── is-binary-path@2.1.0 extraneous
├── nan@2.14.2 extraneous
├── picomatch@2.2.2 extraneous
├── project-a@ -> /tmp/project-a
├── project-b@ -> /tmp/project-b
├── readdirp@3.5.0 extraneous
└── watchpack-chokidar2@2.0.0 extraneous

npm ERR! code ELSPROBLEMS
npm ERR! extraneous: anymatch@3.1.1 /tmp/node_modules/anymatch
npm ERR! extraneous: binary-extensions@2.1.0 /tmp/node_modules/binary-extensions
npm ERR! extraneous: bindings@1.5.0 /tmp/node_modules/bindings
npm ERR! extraneous: chokidar@3.4.3 /tmp/node_modules/chokidar
npm ERR! extraneous: file-uri-to-path@1.0.0 /tmp/node_modules/file-uri-to-path
npm ERR! extraneous: fsevents@2.1.3 /tmp/node_modules/fsevents
npm ERR! extraneous: glob-parent@5.1.1 /tmp/node_modules/glob-parent
npm ERR! extraneous: is-binary-path@2.1.0 /tmp/node_modules/is-binary-path
npm ERR! extraneous: nan@2.14.2 /tmp/node_modules/nan
npm ERR! extraneous: picomatch@2.2.2 /tmp/node_modules/picomatch
npm ERR! extraneous: readdirp@3.5.0 /tmp/node_modules/readdirp
npm ERR! extraneous: watchpack-chokidar2@2.0.0 /tmp/node_modules/watchpack-chokidar2

$ cd project-a
$ npm ls
project-a@ /tmp/project-a
├── UNMET DEPENDENCY webpack-dev-server@^3.9
└── UNMET DEPENDENCY webpack@^4.41 deduped

npm ERR! code ELSPROBLEMS
npm ERR! missing: webpack-dev-server@^3.9, required by project-a@
npm ERR! missing: webpack@^4.41, required by project-a@

$ cd ..
$ npm prune

removed 26 packages in 1s
```

### Expected Behavior:

I think that if I'm using workspaces, and `npm install` can hoist duplicates into the root, then:
* `npm ls` should recognize child projects' demands when run from the root and not list them as extraneous;
* `npm ls` should cope with being run from a non-root project (showing me my dep tree as the current project cares about it, seeing packages available through tree-walking); and
* `npm prune` should not prune dependencies that are actually in use within the workspace you've run it against.

The extraneous warnings aren't so bad; not seeing parent available packages is kind of painful; pruning resources that are actually in use is more painful.

### Environment:
OSX Catalina `10.15.7`
NPM version `7.0.3`

**Comment by darcyclarke** [comment]
Hey @markmckenna! Can you try updating to `v.7.4.0`? You shouldn't see these deps marked as "extraneous" anymore. In terms of commands being run against workspaces, unfortunately, today - we're still flushing out the details of running commands inside/against workspaces over on our RFCs repo (ref. [`Workspace v2`](https://github.com/npm/rfcs/pull/117))

**Comment by markmckenna** [comment]
Thanks for the response @darcyclarke ! I'll take a look at this as soon as I get back to that part of my project.

**Comment by ruyadorno** [comment]
As of **npm@7.14.0** the `npm ls` and `npm prune` commands are now aware of workspaces, this should no longer be a problem - let us know if you still running into it with a version greater than `7.14.0`.
