### ISSUE TITLE
[BUG] Attempting to publish an updated version of an existing package whilst not authenticated fails in a 404

### ISSUE THREAD

**Issue by fluffynuts** [npm/cli#2057]
### Current Behavior:
I tried to publish an updated version of a package I own (`exec-steps`, not that it matters -- I had the same problem with a brand-new package about 20 min later) and received a 404 and a message that the package didn't exist.

We use a private registry, so I have to log in to both. I have built a util which helps with setting up creds (meant for password reset day), and this _may_ have cleared out the existing npmjs creds. At any rate, the workaround was to `npm login` and ensure that I was, once again, logged in.

### Expected Behavior:
I would expect a 401 (unauthorized), though this may be problematic since it's also used to prompt for 2FA. A 403 would have also been acceptable and led me to log back in again pronto. The 404 led me down a rabbit-hole and I eventually deferred the updated publish until my brand-new package also failed to publish. That's when I logged an issue, and, about 10 min later, took a guess at logging in to npmjs via `npm login` again... which resolved the issue.

### Steps To Reproduce:
1. Attempt to publish a package (could be existing, but my second attempt was brand-new)
2. Observe a 404, instead of an expected 403

I'm not sure if there's some piece of cached information that would have been stored based on having been successfully logged in before, so if the steps don't repro, try that, and then delete your ~/.npmrc

### Environment:
OS: Windows
Node: 12.18.0
NPM: 6.14.4

**Comment by isaacs** [comment]
So, to be clear, is the package you're getting a 404 from on the public registry, or on your private registry?

if the package is private, and you're not logged in, then a 404 is an appropriate response, because a 403 would leak the existence of an object that you may not be allowed to know about.

**Comment by fluffynuts** [comment]
the packages I was having trouble with are all public, on npmjs.com. I mention the private repo only because I assume that my login to that repo caused the loss of credentials to npmjs. That's why I mention logging back in to npmjs.com as the step that resolved the issue for me -- but it wasn't obvious because of the 404.
