### ISSUE TITLE
[BUG] `npm start` no longer runs `node server.js`

### ISSUE THREAD

**Issue by rumpl** [npm/cli#2058]
### Current Behavior:

With npm 7.x, running `npm start` when there is no `"scripts": { "start": "... }` but a `server.js` file is present throws an error:

```
npm ERR! missing script: start
```

### Expected Behavior:

When I run `npm start` **and** a `server.js` file is present, `npm start` should run `node server.js`

### Steps To Reproduce:

With a directory like this:
```
$ ls -1
package.json
server.js
```

Contents of the package.json file:
```json
{
  "name": "npme",
  "version": "1.0.0",
  "description": "",
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```

Contents of server.js:
```javascript
console.log('hello');
```

Run `npm start`

### Environment:

Reproduced in MacOS and in a docker container

**Comment by isaacs** [comment]
https://github.com/npm/run-script/pull/10

**Comment by isaacs** [comment]
This is (actually) fixed in the latest v7 release.
