### ISSUE TITLE
[Feature] Print registry config value before on npm login

### ISSUE THREAD

**Issue by ruyadorno** [npm/cli#2071]
### Problem:
It is opaque which service will receive credentials for "npm login". This can lead to leaked credentials.

Logging into a non-standard registry is a 2-command process. Not only that, but one can be logged into multiple registries for various scopes. Give a multitude of registries, when I perform "npm login", depending on the flags, my credentials can be sent to a number of services. It would be nice to know exactly which one before credentials are entered.

### Solution:

Currently:
````
$ npm config set registry https://npm.fury.io/USERNAME/
$ npm login
Username: <user>
Password: <pass>
Email: (this IS public) <email>
Logged in as <user> on https://npm.fury.io/USERNAME/.
````

Proposed:
````
$ npm config set registry https://npm.fury.io/USERNAME/
$ npm login
Log in on https://npm.fury.io/USERNAME/
Username: <user>
Password: <pass>
Email: (this IS public) <email>
Logged in as <user> on https://npm.fury.io/USERNAME/.
````

**Comment by shuang2411** [comment]
To whom it may concern, would that be ok to assign this issue to me?

**Comment by ruyadorno** [comment]
Thanks for the interest @shuang2411 but we already have a PR for it over at #2075 😊
