### ISSUE TITLE
[BUG] husky command failed code 1

### ISSUE THREAD

**Issue by amaster507** [npm/cli#2082]
### Current Behavior:
Just installed npm7 npm install -g npm@7 and did a install of our previous working app. We use husky to run some scripts on push to take a graphql schema and push it to the graph database if it changes. Without changing the schema and just trying to push the new package.json and package-lock.json files updated with npm@7, the push fails with the error message:

```
PS C:\Users\[path to my app dir]> git push
husky > pre-push (node v12.8.0)
sh: prepush-if-changed: command not found
husky > pre-push hook failed (add --no-verify to bypass)
npm ERR! code 1
npm ERR! path C:\Users\[path to my app dir]
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c "husky-run "pre-push" "origin https:\github.com\[path to my .git]""

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\[my user]\AppData\Local\npm-cache\_logs\2020-10-29T16_47_51_633Z-debug.log
error: failed to push some refs to 'https://github.com/[path to my .git]'
```

### Expected Behavior:
For the husky command to run.

### Steps To Reproduce:
section of package.json
```
  "husky": {
    "hooks": {
      "pre-commit": "node ./.githooks/preCommit.js",
      "pre-push": "prepush-if-changed"
    }
  },
  "prepush-if-changed": {
    "src/schema.graphql": "node ./.githooks/updateSlash.js"
  },
```

### Environment:
- OS: Windows 10
- Node: 12.8.0
- npm: 7.0.6
- husky: 4.3.0

debog.log:
```0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\[my user]\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--yes=false',
0 verbose cli   '--',
0 verbose cli   'husky-run',
0 verbose cli   'pre-push',
0 verbose cli   'origin https://github.com/[path to my .git]'
0 verbose cli ]
1 info using npm@7.0.6
2 info using node@v12.8.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:C:\Users\[my user]\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 3ms
5 timing config:load:builtin Completed in 3ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:C:\Users\[path to my app dir]\.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:C:\Users\[my user]\.npmrc Completed in 2ms
11 timing config:load:user Completed in 2ms
12 timing config:load:file:C:\Users\[my user]\AppData\Roaming\npm\etc\npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 12ms
19 verbose npm-session 673485e9f219397b
20 timing npm:load Completed in 28ms
21 timing command:exec Completed in 827ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (C:\Users\[my user]\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:69:27)
22 verbose stack     at ChildProcess.emit (events.js:203:13)
22 verbose stack     at maybeClose (internal/child_process.js:1021:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
23 verbose pkgid [my app name]@0.1.0
24 verbose cwd C:\Users\[path to my app dir]
25 verbose Windows_NT 10.0.19041
26 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\[my user]\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "exec" "--yes=false" "--" "husky-run" "pre-push" "origin https://github.com/[path to my .git]"
27 verbose node v12.8.0
28 verbose npm  v7.0.6
29 error code 1
30 error path C:\Users\[path to my app dir]
31 error command failed
32 error command C:\WINDOWS\system32\cmd.exe /d /s /c "husky-run "pre-push" "origin https:\github.com\[path to my .git]""
33 verbose exit 1
```

**Comment by kmr29499** [comment]
Same here when starting the react-native example from its homepage (https://reactnative.dev/docs/environment-setup)

```
P:\playground\react native\testapp>npx react-native run-android
error Unrecognized command "run-android".
info Run "react-native --help" to see a list of all available commands.
npm ERR! code 1
npm ERR! path P:\playground\react native\testapp
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c react-native run-android

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\%user%\AppData\Local\npm-cache\_logs\2020-11-19T16_11_45_769Z-debug.log
```

Environment:
- OS: Windows 10
- Node: 15.2.1
- NPM: 7.0.12

```
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\nxp29499\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   'react-native',
0 verbose cli   'run-android'
0 verbose cli ]
1 info using npm@7.0.12
2 info using node@v15.2.1
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:C:\Users\nxp29499\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:P:\playground\react native\testapp\.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:C:\Users\nxp29499\.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:C:\Program Files\nodejs\etc\npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 11ms
19 verbose npm-session 0f4f74760a8f6a7e
20 timing npm:load Completed in 28ms
21 http fetch GET 304 https://registry.npmjs.org/react-native 231ms (from cache)
22 timing arborist:ctor Completed in 0ms
23 timing arborist:ctor Completed in 0ms
24 timing arborist:ctor Completed in 0ms
25 timing command:exec Completed in 1604ms
26 verbose stack Error: command failed
26 verbose stack     at ChildProcess.<anonymous> (C:\Users\nxp29499\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
26 verbose stack     at ChildProcess.emit (node:events:329:20)
26 verbose stack     at maybeClose (node:internal/child_process:1055:16)
26 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
27 verbose cwd P:\playground\react native\testapp
28 verbose Windows_NT 10.0.18363
29 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nxp29499\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "exec" "--" "react-native" "run-android"
30 verbose node v15.2.1
31 verbose npm  v7.0.12
32 error code 1
33 error path P:\playground\react native\testapp
34 error command failed
35 error command C:\WINDOWS\system32\cmd.exe /d /s /c react-native run-android
36 verbose exit 1
```

**Comment by carcokaresz** [comment]
I have same issue, but I did not use husky, just native node js server. If the process.exit runned, or an error caused what of the end the process stopping, it got:

0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'run',
0 verbose cli   'mypackage start',
0 verbose cli   '--scripts-prepend-node-path=auto'
0 verbose cli ]
1 info using npm@7.0.14
2 info using node@v15.3.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:C:\User\work\2021\mypackage_master\src\mypackage\.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:C:\Users\User\.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:C:\Users\User\AppData\Roaming\npm\etc\npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 7ms
19 verbose npm-session 8b905ac2568fe624
20 timing npm:load Completed in 14ms
21 timing command:run-script Completed in 9373ms

**22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
22 verbose stack     at ChildProcess.emit (node:events:376:20)
22 verbose stack     at maybeClose (node:internal/child_process:1055:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
23 verbose pkgid mypackage@1.0.0
24 verbose cwd C:\User\work\2021\mypackage_master\src\mypackage
25 verbose Windows_NT 10.0.19041
26 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "mypackage start" "--scripts-prepend-node-path=auto"
27 verbose node v15.3.0
28 verbose npm  v7.0.14
29 error code 1
30 error path C:\User\work\2021\mypackage_master\src\mypackage
31 error command failed
32 error command C:\WINDOWS\system32\cmd.exe /d /s /c mypackage-cli start
33 verbose exit 1**

It looks like the when the process is stopping, it call (cmd.exe / d / s / c ...) with the same runned command what was started.

**Comment by JGFMK** [comment]
I suspect this is an npm 7 issue.
I am experiencing similar issues with `npm i -D webpack-dev-server` and then doing `npm run dev` after adding a "dev" script pointing to "webpack-dev-server".
I am using 
1 info using npm@7.3.0
2 info using node@v13.14.0
Also using nvm on a Mac.

**Comment by darcyclarke** [comment]
@amaster507 can you try running this with npm v6 & see what the output is. We think this may be a problem with `husky` itself (ref. https://github.com/typicode/husky)

**Comment by amaster507** [comment]
We reversed this updgrade and are now running:

- node v12.8.0
- npm 6.14.8
- husky 4.3.6

With this setup, we are no longer seeing this error.

It looks like there is a new husky version 5, which may have fixed this with npm 7. I have not tested though, and don't have the time or resources to stop and test ATM.

**Comment by wraithgar** [comment]
If you do get a chance to test this with the latest npm and husky, and it is still not working, feel free to reopen or make a new issue.
