### ISSUE TITLE
[BUG] when uninstall of package fails, renamed folders remain so subsequent removal attempts fails

### ISSUE THREAD

**Issue by rekna1** [npm/cli#2088]
### Current Behavior:
- try to uninstall a package
- uninstall fails because some other program has locked the file or folder
- close the program that locks 
- retry uninstall package
- it fails again but this time on rename folder 
apparently , the first uninstall creates a copy of the package folder with a temporary name by appending some id string to the folder, but when uninstall fails this folder is not removed.
subsequent uninstall tries to rename the package folder again to the same name which fails because de folder already exists.

npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'xxx\\node_modules\\d3-dispatch',
npm ERR!   dest: 'xxx\\node_modules\\.d3-dispatch-NVhPyRXo'

.d3-dispatch-NVhPyRXo folder stil existed after first uninstall attempt.

### Expected Behavior:
I would expect npm to cleanup temporary folders when uninstall fails.

### Steps To Reproduce:
see current behavior
### Environment:
- OS: Windows 10
- Node: v12.19.0
- npm: 7.0.1

**Comment by wraithgar** [comment]
Is this still happening in the newest npm version?

**Comment by rekna1** [comment]
I don't know. Currently i had to revert to npm lower version (6), because npm7 has a bug which causes angular install to fail.
From the angular team :

> While we do support NPM 7, this has a number of defects related SemVer dependency ranges.

**Comment by wraithgar** [comment]
I do know that the rollback functionality in arborist has been updated since 7.0.1 so I'll close this. If folks experience this w/ the newest npm version feel free to file a new issue.
