### ISSUE TITLE
[DOCS] - missing --omit, difference between include

### ISSUE THREAD

**Issue by MirKml** [npm/cli#2089]
First - new documentation site is nice, thanks!

Problem: 
1.) In the config documentation - https://docs.npmjs.com/cli/v7/using-npm/config#legacy-peer-deps  - `--omit` is mentioned but no such option is presented in the list of option on the right side. Please add documentation for _omit_ option.

2.) It seems there is related option to _omit_ - _include_. Are these options targeted for same usage? E.g. Is `include=[prod,dev,optional]` same as `omit=[peer]`? Behavior of resolving dependency graph and installing packages is same for both options?

**Comment by wraithgar** [comment]
Added this to https://github.com/npm/statusboard/issues/265
