### ISSUE TITLE
[BUG] cannot install local package.json bin

### ISSUE THREAD

**Issue by Milo123459** [npm/cli#2093]
### Current Behavior:

gives a missing perm error
### Expected Behavior:

installs the cli
### Steps To Reproduce:
create a script, add a bin fields then run npm i -g . 

### Environment:
OS: Windows 1909
Node: 15.0.1
npm: 7.0.5

**Comment by darcyclarke** [comment]
@Milo123459 can you provide any other information (ex. logs) to try & help determine the cause of the permissions issue? Also, can you try updating to the latest version of npm (ie. `npm i -g npm@7`)

**Comment by Milo123459** [comment]
No logs just a eperm error

**Comment by wraithgar** [comment]
We need more info to debug this. If it is still happening please open a new issue and follow the prompts to give as much detail as possible
