### ISSUE TITLE
npm v6.14.8 Cli typo

### ISSUE THREAD

**Issue by obtusedev** [npm/cli#2094]
Minor [Typo]

### Current Behavior:
`npm intall -h` is outputting => aliases: i, isntall, add. install is misspelled.

### Expected Behavior:
should be aliases: i, install, add

### Steps To Reproduce:
ex. steps to reproduce the behavior:
1. run `npm install -h`
2. On output where it says alias: i, install, add. install is misspelled as isntall.

### Environment:
- OS: Windows 10 2004
- Node: 14.15.0
- npm: 6.14.8

**Comment by ljharb** [comment]
This isn't a bug - it's intentionally supporting a common typo as an alias.
