### ISSUE TITLE
[BUG] npx create-react-app not working

### ISSUE THREAD

**Issue by mainnnamdi** [npm/cli#2098]
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\NNAMDI PC\AppData\Roaming\npm-cache\_logs\2020-10-31T15_36_44_937Z-debug.log

**Comment by ljharb** [comment]
What version of node/npm?

**Comment by ciobiano** [comment]
Having the same problem, any fix yet?

**Comment by darcyclarke** [comment]
@mainnnamdi this doesn't give us enough information to help you with this problem; Please follow/[fill out one of our issue templates](https://github.com/npm/cli/issues/new/choose) & ensure you've searched our existing issues for the same or similar bugs before submitting.

**Comment by isaacs** [comment]
https://github.com/npm/cli/wiki/%22cb()-never-called%3F--I'm-having-the-same-problem!%22

Happy to dig into this.  But we'll need that debug.log file, as well as details about your environment (npm version, node version, configs, what you were doing, etc.)
