### ISSUE TITLE
Trouble installing Firebase  

### ISSUE THREAD

**Issue by spazax** [npm/cli#2099]
![Capture](https://user-images.githubusercontent.com/8529857/97807759-ba755300-1c73-11eb-92b9-b2c770d4bced.PNG)

**Comment by darcyclarke** [comment]
Closing: Please use one of our [issue templates when filing a bug](https://github.com/npm/cli/issues/new/choose) &, before filing, ensure that an existing issue doesn't already exist for the problem you're submitting.
