### ISSUE TITLE
npm isn't installed

### ISSUE THREAD

**Issue by VictorPro007** [npm/cli#2100]
Hello, I recently installed NodeJS and  when I check if npm is installed, it says this:
```
C:\Users\victo>npm -v
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'C:\Users\victo\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}
```
and here's my OS and NodeJS version:
* **Node.js Version**: 14.15.0
* **OS**: Windows 10 64-bit
Can someone help me, please?

**Comment by ljharb** [comment]
How did you install node?

**Comment by VictorPro007** [comment]
By the official page (https://nodejs.org/en/download/)

**Comment by darcyclarke** [comment]
@VictorPro007 can you... 

- try manually removing npm (ie. `C:\Users\victo\AppData\Roaming\npm`)
- restart your computer
- try `npm -v` again...
