### ISSUE TITLE
Unable to run npm ping after adding cafile

### ISSUE THREAD

**Issue by jasuri-iz** [npm/cli#2102]
I am unable to run `npm ping` after adding cafile certificates, getting below error:

**npm ERR! Bearer **** (token value)
npm ERR! /usr/local/etc/openssl@1.1/cert.pem is not a legal HTTP header value**

It was running perfectly fine before setting the **cafile** config.

I have already done below steps:

- npm config set cafile=/usr/local/etc/openssl@1.1/cert.pem
- export NODE_EXTRA_CA_CERTS=/usr/local/etc/openssl@1.1/cert.pem

OS: MacOS 10
Node: 12.18.4
NPM: 6.14.6

Am I missing anything?

**Comment by ljharb** [comment]
What node and npm version?

**Comment by jasuri-iz** [comment]
> What node and npm version?

Updated in the original description

**Comment by ljharb** [comment]
Can you try the same thing on the latest npm 7?

**Comment by darcyclarke** [comment]
Closing* please let us know if you're still experiencing any issues on v7
