### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by sushil8383** [npm/cli#2111]
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\abc\AppData\Roaming\npm-cache\_logs\2020-11-03T13_58_52_163Z-debug.log

please help me to get fix this

**Comment by nkhekhels** [comment]
getting the same error too.

**Comment by nardiyansah** [comment]
I got the same error too

**Comment by darcyclarke** [comment]
Closing: Please use one of our bug templates - https://github.com/npm/cli/issues/new/choose
