### ISSUE TITLE
[ERROR] Migration failed. See above for further details.

### ISSUE THREAD

**Issue by himanshurajputx** [npm/cli#2113]
### Steps To Reproduce:
1. i have upgrade angular version 8.3 to 9.0. then first step is  **ng update**
2. **ng update @angular/core@8 @angular/cli@8**
3. **ng update @angular/core@9 @angular/cli@9**

then i have show this error **Migration failed. See above for further details.**

### Environment:
- OS: Ubuntu 20.04
- Node: 13.14.0
- npm: 6.4.12

**Comment by darcyclarke** [comment]
Closing this as it seems like it's an error with the angular CLI & not with npm. Please post your bug/issue in their repo to get support (ref. https://github.com/angular/angular). If you believe I'm wrong, feel free to reopen an issue with more details about how this error relates to `npm` itself.
