### ISSUE TITLE
[BUG] unable to resolve dependency tree

### ISSUE THREAD

**Issue by lornally** [npm/cli#2119]
there is another bug, but has been closed.

### Current Behavior:
`npm install --save-dev webpack-dev-server`

output: 
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: webpack@5.3.2
npm ERR! node_modules/webpack
npm ERR!   dev webpack@"^5.3.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^4.0.0" from webpack-dev-middleware@3.7.2
npm ERR! node_modules/webpack-dev-middleware
npm ERR!   webpack-dev-middleware@"^3.7.2" from webpack-dev-server@3.11.0
npm ERR!   node_modules/webpack-dev-server
npm ERR!     dev webpack-dev-server@"^3.11.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/bergman/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bergman/.npm/_logs/2020-11-04T06_31_48_517Z-debug.log

```

### Environment:

- OS: macos 10.15.7
- Node: 15.0.1
- npm: 7.0.3

**Comment by ljharb** [comment]
What happens with npm v7.0.8?

**Comment by lornally** [comment]
> What happens with npm v7.0.8?

how can i install it? i install node, the  npm is 7.0.3, how can i update it to 7.0.8?

**Comment by jonleopard** [comment]
@lornally You can grab the latest version of npm by running `npm install npm@latest -g`. After that's finished, run `npm -v` to confirm you have v7.0.8 installed.

**Comment by nlf** [comment]
we haven't actually tagged npm 7 as `latest` yet, but `npm install -g npm@7` should do the trick for you

**Comment by billyjanitsch** [comment]
This seems like expected behavior. You have `webpack@5.3.2` installed and you're trying to install `webpack-dev-server@3.11.0` which transitively peer-depends on `webpack@^4.0.0`. These webpack ranges are incompatible, as the error mentions.

You can fix it by using `webpack@4` instead of `webpack@5`. `webpack-dev-server@3` is [not compatible](https://github.com/webpack/webpack-dev-server/issues/2807) with `webpack@5`.

(IMO, npm's output here is not very friendly. It's nice that it identifies all of the relevant packages, but if I didn't know much about peer dependencies, I could imagine being quite confused about what's wrong and what to do next. The message doesn't explicitly mention that it's a peer dependency issue -- it says "peer" but it also says "dev" and many other things -- and "fix the upstream dependency conflict" is not actionable.)

**Comment by isaacs** [comment]
Working as designed, and better error messaging and handling in latest npm v7.

**Comment by mvyunko** [comment]
i had the same prob

npm install npm@latest -g 
then 
npm install webpack-dev-server --save-dev

working for me

**Comment by mihailthebuilder** [comment]
@nlf 's solution doesn't work for me but @mvyunko 's does. The latter downgrades npm from version 7 to 6 however.

**Comment by hosseinGanjyar** [comment]
I had same problem and have done these steps:

1. **uninstall  & install nodejs**
2. **npm install npm**
3. **npm install webpack-dev-server --save-dev**

**Comment by tienphamminh** [comment]
retry this command with --force:
npm install webpack-dev-server --save-dev --force

**Comment by AdamAtri** [comment]
atrico:~ /Documents/clients/browser/src/mobile$ npm --version
7.5.6
atrico:~ /Documents/clients/browser/src/mobile$ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: karma@4.4.1
npm ERR! node_modules/karma
npm ERR!   dev karma@"4.4.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer karma@"5.x || 6.x" from karma-summary-reporter@2.0.0
npm ERR! node_modules/karma-summary-reporter
npm ERR!   dev karma-summary-reporter@"^2.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/atrico/.npm/eresolve-report.txt for a full report.

**Comment by Moise10** [comment]
// This solved my problem 
npm config set legacy-peer-deps true
