### ISSUE TITLE
[BUG] TRANSLATE function with an expression argument

### ISSUE THREAD

**Issue by mlapenna7** [npm/cli#2131]
# What / Why
I supplied a SQL stmt to the parser and I received an error from the parser.astify(sq).
It seems that supplying an expression inside a TRANSLATE causes an error.
For example
select ....
cast(TRANSLATE(substr(a.report_timestamp as string),0,10), ' |-|:','') as decimal(8,0) as report_date,
...
.
If I remove this line, the astify call works.

The first attachment shows the **error** printed by astify.
The second attachment shows the source **code** and sql that causes it.
![error](https://user-images.githubusercontent.com/16414318/98318104-df3b3480-1fab-11eb-871e-8177f8b0b85c.jpg)

## When
First time Nov 5 12:00.  Repeatable on demand.

![code](https://user-images.githubusercontent.com/16414318/98318119-e6fad900-1fab-11eb-8ac3-436e57780d0b.jpg)
![error](https://user-images.githubusercontent.com/16414318/98318135-f24e0480-1fab-11eb-80c9-380cea37dacb.jpg)

**Comment by darcyclarke** [comment]
Closing: Please use one of our bug templates - https://github.com/npm/cli/issues/new/choose
