### ISSUE TITLE
[BUG] Deadlinks in documentation search results

### ISSUE THREAD

**Issue by shaklin-box8** [npm/cli#2133]
### Current Behavior:
While i search for devdependencies in docs.npmjs.com the first result takes me to `https://docs.npmjs.com/packages-and-modules/contributing-packages-to-the-registry/specifying-dependencies-and-devdependencies-in-a-package-json-file` which is a dead link, I am not sure if this is the only dead link or there are many that we are yet to find.

### Expected Behavior:
The link should have taken me to `https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file`

### Steps To Reproduce:

described in Current Behavior  section

### Environment:

Any browser

**Comment by isaacs** [comment]
This seems to work now?
