### ISSUE TITLE
[BUG] <cb() never called>

### ISSUE THREAD

**Issue by Hazc93** [npm/cli#2135]
### Current Behavior:
I am running Windows 10 using npm version 6.14.8 and node version 14.15.0. When I run npx create-react app my-app I get the following error: 

npm ERR! cb() never called!
npm ERR! This is an error with npm itself. Please report this error at: <https://npm.comunity>

I have tried running npm i--no-package-lock
npm cache clean --force
npm cache verify
uninstalling and reinstalling node

### Expected Behavior:
Expected behaviour is for a create react app called my-app to be made when running npx create-react-app my-app

### Steps To Reproduce:
Steps to Reproduce:

Download npm version 14.15.0 using the Windows installer (.msi) 64-bit.
using git-bash in VisualStudioCode run npx create-react-app my-app 

### Environment:
OS: Windows 10
Node: 14.15.0
npm: 6.14.8
editor: VisualStudioCode
Terminal: Gitbash
<img width="554" alt="npm_error" src="https://user-images.githubusercontent.com/62154018/98397090-17e81600-205f-11eb-8d50-f02a822086cb.PNG">

**Comment by soumya232329** [comment]
Same error

**Comment by ghost** [comment]
Ok, I manage to solve my probleme by disabling my Antivirus....

**Comment by soumya232329** [comment]
@Titoineis still not resolved, I received a new error. May I send you the pic?

**Comment by soumya232329** [comment]
Still not resolved, I received a new error.
Please do check.
Thankyou

**Comment by ghost** [comment]
Did you tried that ?
https://stackoverflow.com/questions/15393821/npm-err-cb-never-called

**Comment by alesniak303** [comment]
Environment:
MacBook Air 2020 i5 16GB 
macOS 10.15.7
npm -v 
6.14.4

Steps:
> rm -rf node_modules
> npm install
npm ERR! cb() never called!

--- 
Subsequent rerun completed without error.
 I'm including the logs.
[2020-11-10T19_05_57_231Z-debug.log](https://github.com/npm/cli/files/5519661/2020-11-10T19_05_57_231Z-debug.log)

**Comment by CoderFX** [comment]
same error, windows 10

**Comment by hmnshgpt455** [comment]
Same error, Windows 10.
npm - 6.14.8

**Comment by edgardmessias** [comment]
Try edit the environment variable `PATH`.

A fast test:
```cmd
set PATH=%APPDATA%\npm;%PATH%
npm install
```

**Comment by ghost** [comment]
npm ERR! cb() never called!

**Comment by Tomato6966** [comment]
Bot
Hey Leute
Checkt auf jeden Fall @Tomato ab und seine Coolen Bots

Server : https://discord.gg/3ep6e3vEJf

Website : https://x10-gaming.eu/service/dc

**Comment by Beenhakker** [comment]
We had the same error, within our TFS v15 pipeline, Windows, NodeJS 14.15.4, NPM 6.

Eventually doing a global install of NPM v7.5 from within our pipeline, adding it to the shell path, and use that version to do the install solved this tedious error.

**Comment by Arhan13** [comment]
Try doing  - 
`npm cache verify`
And then run your command, worked for me.

**Comment by visruth** [comment]
> Try doing -
> `npm cache verify`
> And then run your command, worked for me.

it worked for me! Thanks!

**Comment by george-bobby** [comment]
I had the same error.  I updated NPM and node. That solved the problem.

**Comment by diwakarstha** [comment]
mine got fixed after downgrading npm tp 6.14.6
 npm install -g npm@6.14.6
