### ISSUE TITLE
add `--default-command` config option

### ISSUE THREAD

**Issue by isaacs** [npm/cli#2136]
Right now, effectively the default command is `help`.

```
$ npm package-lock
Top hits for "package-lock"
————————————————————————————————————————————————————————————————————————————————
npm help install                                                 package-lock:11
npm help config                                                  package-lock:10
npm help package-lock-json                                        package-lock:9
npm help package-locks                                            package-lock:8
npm help shrinkwrap-json                                          package-lock:8
npm help shrinkwrap                                               package-lock:8
npm help ci                                                       package-lock:7
npm help audit                                                    package-lock:6
npm help prune                                                    package-lock:2
npm help version                                                  package-lock:1
————————————————————————————————————————————————————————————————————————————————
(run with -l or --long to see more context)
```

Why not making that configurable?

Then anyone who wants yarn-style "run-scripts are top level commands" behavior can do `npm config set default-command run-script`, and be done with it.

Default value could just be `"help"`, and we could require that it be one of the commands we know about.

**Comment by ljharb** [comment]
What happens when someone does that, and has a script called “magic”, and then npm later adds a top-level “magic” command? I understand npm can safely rest on “you changed the default command, so, tough”, but how would that user even know that command was newly arrived? What happens when a dependency, or another developer who doesn’t have that set, runs `npm magic` and a script gets run instead of the command they expect?

**Comment by isaacs** [comment]
> What happens when someone does that, and has a script called “magic”, and then npm later adds a top-level “magic” command?

I'd make it work like how `npm help` currently does (well, more precisely, `npm help-search`, but `npm help` calls that when the term doesn't match any known help topic).  If you run `npm something`, which is not a known command or alias, then it'll try running `npm help` with that argument.

But if the argument _is_ a known command, alias, or unique abbrev, then it'll just run that command.

So if someone creates a `magic` script, and runs `npm magic --default-command=run-script`, and then later we create a `magic` command, then tough potatoes, `npm magic` runs the `npm magic` command now, not `npm run-script magic`.

Also, we'd restrict the `default-command` config value to the set of known commands.  So you could (for example) set `npm config set default-command exec` and then `npm create-react-app` would run the `create-react-app` package, but `npm install` would still install, it wouldn't try to run `npm exec install`.  (Setting it to `help` makes the most sense by default, which is effectively what the default-command has _been_ for years now, but `run-script` and `exec` are both pretty cool and useful options, imo.)

**Comment by ljharb** [comment]
Ok - so in that case, it’s a potential breaking change to add any new top-level command (which it’s not now), because “tough potatoes”?

Certainly i agree that it should only be settable to “an existing top-level command”.

**Comment by wraithgar** [comment]
Is this something we still want? If so please add the `Agenda` label to discuss it in an rfc meeting. Otherwise let's close it.

**Comment by darcyclarke** [comment]
Closing: we chose not to go down this route for numerous reasons discussed in the Open RFC calls.
