### ISSUE TITLE
[BUG] publish node.JS package on npm

### ISSUE THREAD

**Issue by clementbolin** [npm/cli#2142]
### Current Behavior:

I try to publish public package on npm but I have this error

```
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/@clem_b%2fweather - Forbidden
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.
```
So in first watch my ```package.json```below.

```json
{
  "name": "@clem_b/weather",
  "author": "clem_b",
  "version": "6.1.3",
  "license": "MIT",
  "description": "weather cli",
  "homepage": "https://github.com/ClementBolin/weatherCLI#readme",
  "main": "./build/main.js",
  "typings": "./build/main.d.ts",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/ClementBolin/weatherCLI.git"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "rimraf ./build && tsc",
    "start": "npm run build && node build/mai.js"
  },
  "bin": {
    "weatherCLI": "./bin/weatherCLI"
  },
  "engines": {
    "node": ">=4.2.0"
  },
  "keywords": [
    "weather",
    "today",
    "rain",
    "sun"
  ],
  "devDependencies": {
    "@types/minimist": "^1.2.0",
    "@types/node": "^14.14.6",
    "@types/node-emoji": "^1.8.1",
    "@types/oauth": "^0.9.1",
    "@types/ora": "^3.2.0",
    "rimraf": "^3.0.2",
    "tslint": "^6.1.3",
    "typescript": "^4.0.5"
  },
  "prepublish": "npm run build",
  "dependencies": {
    "minimist": "^1.2.5",
    "node-emoji": "^1.10.0",
    "oauth": "^0.9.15",
    "ora": "^0.3.0"
  }
}
```

So after end to write my code, I decide to publish my code on npm, so I create npm account, I use ```npm login```for connect to my account. After this I run the following command ```npm publish --access public```and I have error write in top.
I search on many topics, but I don't find solution

### Expected Behavior:

so I would like to be able to publish my package on npm. 

### Environment:

- OS: MacOs Catalina 10.15.7
- Node: v15.0.1
- npm: 7.0.3

**Comment by ljharb** [comment]
Are you logged in as clem_b? What does `npm whoami` print out?

**Comment by clementbolin** [comment]
```npm whoami```
output:
```
clem_b
```

**Comment by ljharb** [comment]
Can you try with npm v7.0.9?

**Comment by clementbolin** [comment]
@ljharb  I update npm but after update I have npm v7.0.8 and I had same error

**Comment by calvin-uc** [comment]
I'm encountering the same problem `pnpm` which calls `npm`. I'm able to repro this problem with a test repo that I created
https://github.com/calvin-uc/publish-test

Node 15.x which uses npm 7.x 
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V15.md#npm-7---35631

has the same issue. Our current resolution is just not to use 15.x but that doesn't seem like a long term solution.

**Comment by emilia66** [comment]
> @ljharb I update npm but after update I have npm v7.0.8 and I had same error
I also encountered this problem. I tried to change the package name, NPM login verification, keep the image address of NPM synchronized, and upgrade node and NPM to the latest version. Anyway, none of these works. How did you solve it in the end? I really do not know which server or package I do not have access to
