### ISSUE TITLE
install typescript: cb() never called!

### ISSUE THREAD

**Issue by yigecaib** [npm/cli#2149]
cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:

**Comment by EnderMega** [comment]
same problem when trying to install the discord library

**Comment by darcyclarke** [comment]
Closing: Please use one of our bug templates - https://github.com/npm/cli/issues/new/choose
