### ISSUE TITLE
[BUG] npm update does not physically update the version

### ISSUE THREAD

**Issue by bricss** [npm/cli#2158]
### Current Behavior:
Synthetic update instead of physically updated package.

### Expected Behavior:
Get the exact version in `node_modules` you updated to.

### Steps To Reproduce:
1. run `npm update` or even `npm install <already_installed_pkg> --save`
2. check version in `package-lock.json`
3. check **actual** version in `node_modules` dir
4. smile

### Environment:
- OS: win 10
- Node: 15.2.0
- npm: 7.0.8

**Comment by ljharb** [comment]
Can you reproduce with npm v7.0.10?

**Comment by bricss** [comment]
Yes, just checked.

Moreover, `npm update` does not update version in `package.json` itself as well.

**Comment by zdm** [comment]
npm v7.0.15 - bug is present

**Comment by ljharb** [comment]
What about v7.1.1?

**Comment by zdm** [comment]
v7.1.1 - same problem

**Comment by zdm** [comment]
Also, if npm v7 now respects peer dependencies, I think it has sense to update peerDeps versions to the latest available matched version too.

**Comment by ljharb** [comment]
Updating peer deps is not safe, because that would be a breaking change, that a package author wouldn’t likely realize.

**Comment by zdm** [comment]
I mean, if you are the package maintainer, and you run `npm update` for your package.
```
peerDeps: { "glob": ">=6" }
```
will be updated to 
```
peerDeps: { "glob": ">=7.1.6" }
```
It is safe, because it is not breaks initial version criteria. 
Same algorithm, how regular dependencies versions updated.

**Comment by ljharb** [comment]
That is absolutely not safe - it makes v6 invalid, which is a breaking change. Peer deps are *very different* than deps in this way.

**Comment by zdm** [comment]
Ah, ok. Maybe you are right.

**Comment by darcyclarke** [comment]
@bricss 🤔 In terms of what you're seeing on disk - if you can, try updating to the latest `v7` (ie. `npm i -g npm@7`) - then running `npm update` & checking which version of your deps have been installed (ie. `npm ls`). I've tested this a bit & it seems to be working for me fine as of `v7.4.0`. The only caveat to this might be that you've previously saved **exact** versions of a package (ie. using `--save-exact` which would generate `foo@1.0.0` vs. `foo@^1.0.0` in `package.json`) which would cause `update` & `install` to seemingly do nothing (yet we're just respecting the existing package range you previously specified).

As a quick aside, 

- `npm update` won't update your `package.json` just your `package-lock.json`
- If you run `npm install <pkg>@<version>` you should be able to install the **exact** version of the package you want today, alongside updating `package.json` (`--save` is no longer needed as of `v5`) 
- If you're running `npm install <pkg>` (ie. without a specific version/range) then it will use `latest` **OR** respect the previously installed version/range defined in `package.json`, `package-lock.json`, or physically on disk inside `node_modules/`
- If you want to get the most recent version of a previously installed package, within the range defined, you can use `npm update <pkg>` (updating `package-lock.json`)
- If you want to get the most recent version of a previously installed package, no matter what range was previously specified, you can use `npm install <pkg>@latest` (updating `package.json` & `package-lock.json`)

Let me know if the above is helpful at all & if you're still running into issues.

**Comment by jorrit** [comment]
> npm update won't update your package.json just your package-lock.json

npm did update package.json in v6 and I liked that behavior.

**Comment by zdm** [comment]
@darcyclarke 
This is how v6 works. Could we just implement this behavior without invent new schemes?

1. npm should respect `save-prefix` option. If i have `save-prefix=">="` and run `npm i test` - it will write `"test": >=5.0.0` to the package.json.
2. When I run `npm update` and package `test` was updated - it will update it version in package.json: `"test": >=10.0.0`.

**Comment by timothyallan** [comment]
Just to clarify, as I've been struggling with this since updating to v7: With v6, we would just run `npm update` and `package.json` would be updated with our range of versions. 

With v7, we now run `npm-check-updates` to get a list of packages which have updates, note which ones have updates,  manually edit the version number(s) in each of our `package.json` files, then run `npm update` **OR** do `npm install` for each specific package, with the specific version number we want.

We have `package.json` files with 150+ entries in them, so I'm hoping we're missing something simple, as this is extremely tedious at the moment!

**Comment by darcyclarke** [comment]
@timothyallan you can use `npm outdated` to get the list of outdated dependencies in your project. Running `npm update` will update dependencies based on the previous range specified (by default, if you `install` a package without specifying a semver range it will use a carot to imply future updates to be within the same major range - ie. minor & patch versions - ex. `^1.0.0` - ref. https://github.com/npm/node-semver#caret-ranges-123-025-004); That is to say, pulling in minor/patch updates should be as simple as running `npm update` if your dependencies are already saved this way (the key here is that you're in control of defining what versions of this depency you want now & into the future). 

Alternatively, you can specify a greedy semver range (ex. `>=1.0.0` or `*`) when installing a dependency which would allow `npm update` to grab whatever version is `latest` (including majors); **Note:** this is **not recommended** as major version bumps are a sign of breaking changes & will most likely break your usage of that dependency. You should take a mindful/manual approach when updating majors.

`npm update` should still be updating your `package-lock.json` (although, as noted before, it will not update `package.json`), unless you are specifically opting out of generating one (ie. running with the `--no-package-lock` or `--no-save` flags/config). 

If you're finding that you _have to_ manually update or install dependencies it may be that you are specifying dependency versions explitely & not using ranges (ex. `1.0.0`).

**Comment by timothyallan** [comment]
^ That's the thing. These are multi year old projects, which have been updating using ranges just fine for many years, up until v7. `npm update` no longer updates the package.json or installs updated dependencies, regardless of version ranges in the package.json.

**Comment by Allain55** [comment]
I don't see why this had to change, I think it's bad for teams.
I don't plan to update to npm v7+ if this will be the default behaviour.
When I realized this change I was looking into why did 1 npm package stop working. The local and prod versions were the same in package.json but it didn't work locally. After 1+ hours of debugging I realized that a new minor release broke the package for me and it was only updated locally. I switched back to npm v6 ever since and waited for this fix to happen

**Comment by zdm** [comment]
How it will work if `package-lock=false`?
In this case when I run `npm update` - it will not update package version anywhere.
I think it must work exactly like v6. New behavior is not handy and not well tested.
Please, don't close this issue.

**Comment by bricss** [comment]
No wukkas 👌 I will create new one, as soon as it will hit RTM, coz bug 🐛 is still there.
Files ain't updated on the file system in `node_modules` after running **npm update** at all, as well as versions. Toasted on several machines with no luck. 🤠
