### ISSUE TITLE
[BUG] Removing dependency from workspace package leads to invalid lockfile

### ISSUE THREAD

**Issue by protyposis** [npm/cli#2162]
### Current Behavior:
When removing a dependency from a workspace package's `package.json` and executing `npm install` in the workspace root to update its `package-lock.json` (as discussed in #2036 and #1984), the file structure ends up in an invalid state where the `version` property holds the URL from the `resolved` property, instead of removing the whole dependency block. See this changeset after `npm install`:

![image](https://user-images.githubusercontent.com/189372/98937207-5d389780-24e6-11eb-9ed7-b6a6c59b4b28.png)

### Expected Behavior:
`package-lock.json` is in a valid state and all artifacts of the removed dependency are removed from the lockfile.

### Steps To Reproduce:
 * remove dependency from `workspaceRoot/packages/package-a/package.json`
 * execute `npm install` in `workspaceRoot/`
 * investigate changes to lockfile

### Environment:
- OS: Windows 10
- Node: 12.19.0
- npm: 7.0.10

**Comment by protyposis** [comment]
Fixed in 7.1.1, thanks!

**Comment by petermikitsh** [comment]
I'm observing this in 7.5.4; see https://github.com/npm/cli/issues/2706
