### ISSUE TITLE
[BUG] v6 - npm install deletes linked module's dependencies

### ISSUE THREAD

**Issue by trusktr** [npm/cli#2166]
### Current Behavior:

`npm install` removes dependencies from `npm link`ed packages.

For example, if I am working on project A, which depends on project B

- cd projectB
- `npm link` in project B (also does install)
- build project B
- cd ../projectA
- `npm link projectB` into project A
- `npm install` BOOM, deletes packages from `../projectB/node_modules` while (presumably) trying to dedupe dependencies in project A's `node_modules`.
- `cd ../projectB`
- try to build project B again (because we made some changes to the source), the build fails, because dependencies were deleted.

### Expected Behavior:

`npm install` in a project does not deleted dependencies modules are linked into the project.

### Steps To Reproduce:

Basically the above

**Comment by trusktr** [comment]
Oops, meant for v6, label needs to be changed

**Comment by ljharb** [comment]
npm v6 is basically frozen; what happens in v7.0.10?

**Comment by trusktr** [comment]
Looks like the issue is fixed in v7.0.10. I'll test drive it for a while.
