### ISSUE TITLE
npm ERR!

### ISSUE THREAD

**Issue by maria20castro** [npm/cli#2170]
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR! https://npm.community

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\abc\AppData\Roaming\npm-cache_logs\2020-11-03T13_58_52_163Z-debug.log

please help me to get fix this

**Comment by cotocortes** [comment]
Hey, I have the same problem. Were you able to fix it?

**Comment by cotocortes** [comment]
I tried to install npm in Windows

**Comment by ihernandez13** [comment]
Having the same issue when trying to install. Any resolution yet?

**Comment by wraithgar** [comment]
Closing as duplicate of https://github.com/npm/cli/issues/417
