### ISSUE TITLE
npm install create-react-app 

### ISSUE THREAD

**Issue by AhmadSalihu** [npm/cli#2173]
if i run npm install create-react-app  is referring me to another directory on my computer. pls help

**Comment by dominguetigs** [comment]
@Ahmadzayd 
Could you print out the logs that gives in the terminal for more information?

**Comment by darcyclarke** [comment]
Closing: please use one of our bug templates if you think you've found an issue with `npm` itself (ref. https://github.com/npm/cli/issues/new/choose)

If you're having problems with `create-react-app`, please file a bug on their project (ref. https://github.com/facebook/create-react-app)

**Comment by AhmadSalihu** [comment]
C:\Users\AHMED\Desktop>npx create-react-app my-app

Creating a new React app in C:\Users\AHMED\Desktop\my-app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...

npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! errno ERR_SOCKET_TIMEOUT
npm ERR! request to https://registry.npmjs.org/workbox-window failed, reason: Socket timeout

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AHMED\AppData\Local\npm-cache\_logs\2020-11-17T22_14_44_898Z-debug.log

Aborting installation.
  npm install --save --save-exact --loglevel error react react-dom react-scripts cra-template has failed.

Deleting generated file... package.json
Deleting my-app/ from C:\Users\AHMED\Desktop
Done.
npm ERR! code 1
npm ERR! path C:\Users\AHMED\Desktop
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c ""create-react-app" "my-app""

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AHMED\AppData\Local\npm-cache\_logs\2020-11-17T22_14_45_244Z-debug.log

this is the issues am having with installing create-react-app. and also if, I want to install some packages from npm, it resulte in the same issues.
Sorry for taking too long to response. I will really appreciate it if you help me solved this issue.  But am thankful for giving me your attention.@dominguetigs

**Comment by AhmadSalihu** [comment]
> @Ahmadzayd
> Could you print out the logs that gives in the terminal for more information?



C:\Users\AHMED\Desktop\robohash\trove-app>npx create-react-app trove

You are running `create-react-app` 4.0.0, which is behind the latest release (4.0.1).

We no longer support global installation of Create React App.

Please remove any global installs with one of the following commands:
- npm uninstall -g create-react-app
- yarn global remove create-react-app

The latest instructions for creating a new app can be found here:
https://create-react-app.dev/docs/getting-started/

npm ERR! code 1
npm ERR! path C:\Users\AHMED\Desktop\robohash\trove-app
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c ""create-react-app" "trove""

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AHMED\AppData\Local\npm-cache\_logs\2020-11-24T00_04_00_794Z-debug.log

C:\Users\AHMED\Desktop\robohash\trove-app>

these is the problem, can you please help? i would really appreciate it @dominguetigs

**Comment by AhmadSalihu** [comment]
> @Ahmadzayd
> Could you print out the logs that gives in the terminal for more information?
This is the directory the are referring me to always, can you please help me look? may be is the setting from my dependencies folder or somethin else. Thanks you @dominguetigs 
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   '--force',
0 verbose cli   'i',
0 verbose cli   'react-tilt'
0 verbose cli ]
1 info using npm@7.0.8
2 info using node@v15.2.1
3 timing config:load:defaults Completed in 3ms
4 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 4ms
5 timing config:load:builtin Completed in 4ms
6 timing config:load:cli Completed in 5ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:C:\Users\AHMED\Desktop\react-deploy\.npmrc Completed in 0ms
9 timing config:load:project Completed in 2ms
10 timing config:load:file:C:\Users\AHMED\.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:C:\Users\AHMED\AppData\Roaming\npm\etc\npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 2ms
17 timing config:load:setEnvs Completed in 4ms
18 timing config:load Completed in 23ms
19 warn using --force Recommended protections disabled.
20 verbose npm-session 46b179e4013bf7ed
21 timing npm:load Completed in 57ms
22 timing arborist:ctor Completed in 2ms
23 timing idealTree:init Completed in 2804ms
24 timing idealTree:userRequests Completed in 6ms
25 silly idealTree buildDeps
26 silly fetch manifest react-tilt@*
27 timing arborist:ctor Completed in 0ms
28 http fetch GET 200 https://registry.npmjs.org/react-tilt 2333ms (from cache)
29 silly fetch manifest react@^17.0.1
30 http fetch GET 304 https://registry.npmjs.org/react 715ms (from cache)
31 silly fetch manifest react-dom@^17.0.1
32 http fetch GET 304 https://registry.npmjs.org/react-dom 386ms (from cache)
33 silly placeDep ROOT react-tilt@0.1.4 OK for: react-deploy@0.1.0 want: *
34 silly placeDep ROOT react@17.0.1 KEEP for: react-tilt@0.1.4 want: ^15.0.0 || ^16.0.0-beta || ^16.0.0
35 warn ERESOLVE overriding peer dependency
36 timing idealTree Completed in 6295ms
37 timing command:install Completed in 6303ms
38 verbose stack TypeError: Cannot read property 'length' of undefined
38 verbose stack     at explainDependents (C:\Program Files\nodejs\node_modules\npm\lib\utils\explain-dep.js:68:19)
38 verbose stack     at explainNode (C:\Program Files\nodejs\node_modules\npm\lib\utils\explain-dep.js:13:3)
38 verbose stack     at explainEresolve (C:\Program Files\nodejs\node_modules\npm\lib\utils\explain-eresolve.js:24:24)
38 verbose stack     at explain (C:\Program Files\nodejs\node_modules\npm\lib\utils\explain-eresolve.js:64:38)
38 verbose stack     at EventEmitter.log.warn (C:\Program Files\nodejs\node_modules\npm\lib\utils\setup-log.js:20:23)
38 verbose stack     at Arborist.[warnPeerConflict] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1044:14)
38 verbose stack     at Arborist.[placeDep] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1115:32)
38 verbose stack     at Arborist.[placeDep] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1232:41)
38 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:772:46
38 verbose stack     at Array.map (<anonymous>)
39 verbose cwd C:\Users\AHMED\Desktop\react-deploy
40 verbose Windows_NT 10.0.10240
41 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "--force" "i" "react-tilt"
42 verbose node v15.2.1
43 verbose npm  v7.0.8
44 error Cannot read property 'length' of undefined
45 verbose exit 1

**Comment by dominguetigs** [comment]
@Ahmadzayd Use one of the bug templates as @darcyclarke said.
