### ISSUE TITLE
[BUG] <title> cb() never called !!

### ISSUE THREAD

**Issue by shubhankartarkar** [npm/cli#2177]
`cb()` never called !! while downloading create react app and other packages
![Capture](https://user-images.githubusercontent.com/29594617/99150120-611c1380-26b8-11eb-9a4f-01557ed79c30.PNG)
Following is log generated

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Shubham\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   '--save-exact',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   'react',
1 verbose cli   'react-dom',
1 verbose cli   'react-scripts',
1 verbose cli   'cra-template'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v13.2.0
4 verbose npm-session b08eda6cd6a31e02
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/cra-template 358ms (from cache)
8 silly pacote tag manifest for cra-template@latest fetched in 374ms
9 http fetch GET 304 https://registry.npmjs.org/react 3463ms (from cache)
10 http fetch GET 304 https://registry.npmjs.org/react-scripts 3478ms (from cache)
11 silly pacote tag manifest for react@latest fetched in 3573ms
12 silly pacote tag manifest for react-scripts@latest fetched in 3510ms
13 http fetch GET 304 https://registry.npmjs.org/react-dom 3525ms (from cache)
14 silly pacote tag manifest for react-dom@latest fetched in 3541ms
15 timing stage:loadCurrentTree Completed in 3853ms
16 silly install loadIdealTree
17 silly install cloneCurrentTreeToIdealTree
18 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
19 silly install loadShrinkwrap
20 timing stage:loadIdealTree:loadShrinkwrap Completed in 0ms
21 silly install loadAllDepsIntoIdealTree
22 silly resolveWithNewModule cra-template@1.1.0 checking installable status
23 silly resolveWithNewModule react@17.0.1 checking installable status
24 silly resolveWithNewModule react-scripts@4.0.0 checking installable status
25 silly resolveWithNewModule react-dom@17.0.1 checking installable status
26 http fetch GET 304 https://registry.npmjs.org/loose-envify 156ms (from cache)
27 http fetch GET 304 https://registry.npmjs.org/object-assign 140ms (from cache)
28 silly pacote range manifest for loose-envify@^1.1.0 fetched in 172ms
29 silly resolveWithNewModule loose-envify@1.4.0 checking installable status
30 silly pacote range manifest for object-assign@^4.1.1 fetched in 156ms
31 silly resolveWithNewModule object-assign@4.1.1 checking installable status
32 http fetch GET 304 https://registry.npmjs.org/js-tokens 47ms (from cache)
33 silly pacote range manifest for js-tokens@^3.0.0 || ^4.0.0 fetched in 62ms
34 silly resolveWithNewModule js-tokens@4.0.0 checking installable status
35 http fetch GET 304 https://registry.npmjs.org/scheduler 47ms (from cache)
36 silly pacote range manifest for scheduler@^0.20.1 fetched in 62ms
37 silly resolveWithNewModule scheduler@0.20.1 checking installable status
38 warn registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-ZMIzVMoTbxX+PpEoZr0PcwOfkDo+PZy1mZZybmuGdb421usqHPXv1gW/0y1FlWYzYRkCTlh66s+ZRj5WaP3KQw== integrity checksum failed when using sha512: wanted sha512-ZMIzVMoTbxX+PpEoZr0PcwOfkDo+PZy1mZZybmuGdb421usqHPXv1gW/0y1FlWYzYRkCTlh66s+ZRj5WaP3KQw== but got sha512-55/bGxp9XB15IRHH41DOR/JIlDPRV8Gl6YzmIJTbwwjo1PNIdsSIOZO/W+mzaEIbl5JbqqaRlpUat/F5D2QlEg==. (75278 bytes)
39 warn registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
40 silly fetchPackageMetaData error for @pmmmwh/react-refresh-webpack-plugin@0.4.2 Invalid response body while trying to fetch https://registry.npmjs.org/@pmmmwh%2freact-refresh-webpack-plugin: Integrity verification failed for sha512-ZMIzVMoTbxX+PpEoZr0PcwOfkDo+PZy1mZZybmuGdb421usqHPXv1gW/0y1FlWYzYRkCTlh66s+ZRj5WaP3KQw== (C:\Users\Shubham\AppData\Roaming\npm-cache\_cacache\content-v2\sha512\64\c2\3354ca136f15fe3e912866bd0f73039f903a3e3d9cb59996726e6b8675be36d6eb2a1cf5efd605bfd32d459566336119024e587aeacf99463e5668fdca43)
41 http fetch GET 304 https://registry.npmjs.org/@svgr%2fwebpack 452ms (from cache)
42 http fetch GET 304 https://registry.npmjs.org/@babel%2fcore 468ms (from cache)
43 silly pacote version manifest for @svgr/webpack@5.4.0 fetched in 499ms
44 silly resolveWithNewModule @svgr/webpack@5.4.0 checking installable status
45 silly pacote version manifest for @babel/core@7.12.3 fetched in 531ms
46 silly resolveWithNewModule @babel/core@7.12.3 checking installable status
47 silly fetchPackageMetaData error for babel-jest@^26.6.0 Invalid response body while trying to fetch https://registry.npmjs.org/babel-jest: Integrity verification failed for sha512-ammCEEjSxYiCFLlmPJybwnRPHn2Dx3DYOk2xw98Qr3xRYaGw/hVW5mmptFtp6RoNOgZrC6vIju5S8DgpIXCMfQ== (C:\Users\Shubham\AppData\Roaming\npm-cache\_cacache\content-v2\sha512\6a\69\821048d2c5888214b9663c9c9bc2744f1e7d83c770d83a4db1c3df10af7c5161a1b0fe1556e669a9b45b69e91a0d3a066b0babc88eee52f0382921708c7d)
48 http fetch GET 304 https://registry.npmjs.org/babel-eslint 624ms (from cache)
49 http fetch GET 304 https://registry.npmjs.org/babel-loader 624ms (from cache)
50 http fetch GET 304 https://registry.npmjs.org/babel-plugin-named-asset-import 655ms (from cache)
51 http fetch GET 304 https://registry.npmjs.org/babel-preset-react-app 671ms (from cache)
52 silly pacote range manifest for babel-eslint@^10.1.0 fetched in 702ms
53 silly resolveWithNewModule babel-eslint@10.1.0 checking installable status
54 silly pacote version manifest for babel-loader@8.1.0 fetched in 717ms
55 silly resolveWithNewModule babel-loader@8.1.0 checking installable status
56 silly pacote range manifest for babel-plugin-named-asset-import@^0.3.7 fetched in 733ms
57 silly resolveWithNewModule babel-plugin-named-asset-import@0.3.7 checking installable status
58 silly pacote range manifest for babel-preset-react-app@^10.0.0 fetched in 733ms
59 silly resolveWithNewModule babel-preset-react-app@10.0.0 checking installable status
60 http fetch GET 304 https://registry.npmjs.org/bfj 468ms (from cache)
61 http fetch GET 304 https://registry.npmjs.org/@typescript-eslint%2fparser 873ms (from cache)
62 silly pacote range manifest for bfj@^7.0.2 fetched in 577ms
63 silly resolveWithNewModule bfj@7.0.2 checking installable status
64 silly fetchPackageMetaData error for css-loader@4.3.0 Invalid response body while trying to fetch https://registry.npmjs.org/css-loader: Integrity verification failed for sha512-X3yjHGsr/64cu6hTJls/arNhnTto9zmm2yhDXRr0BiwInekdRAxDix1DRBhmu4RHxkeuCWZTUtte2pRKZPp4Ww== (C:\Users\Shubham\AppData\Roaming\npm-cache\_cacache\content-v2\sha512\5f\7c\a31c6b2bffae1cbba853265b3f6ab3619d3b68f739a6db28435d1af4062c089de91d440c438b1d43441866bb8447c647ae09665352db5eda944a64fa785b)
65 silly pacote range manifest for @typescript-eslint/parser@^4.5.0 fetched in 983ms
66 silly resolveWithNewModule @typescript-eslint/parser@4.7.0 checking installable status
67 http fetch GET 304 https://registry.npmjs.org/case-sensitive-paths-webpack-plugin 530ms (from cache)
68 http fetch GET 304 https://registry.npmjs.org/camelcase 530ms (from cache)
69 silly pacote version manifest for case-sensitive-paths-webpack-plugin@2.3.0 fetched in 561ms
70 silly resolveWithNewModule case-sensitive-paths-webpack-plugin@2.3.0 checking installable status
71 silly pacote range manifest for camelcase@^6.1.0 fetched in 561ms
72 silly resolveWithNewModule camelcase@6.2.0 checking installable status
73 http fetch GET 304 https://registry.npmjs.org/@typescript-eslint%2feslint-plugin 1170ms (from cache)
74 silly pacote range manifest for @typescript-eslint/eslint-plugin@^4.5.0 fetched in 1279ms
75 silly resolveWithNewModule @typescript-eslint/eslint-plugin@4.7.0 checking installable status
76 http fetch GET 304 https://registry.npmjs.org/dotenv-expand 562ms (from cache)
77 http fetch GET 304 https://registry.npmjs.org/dotenv 562ms (from cache)
78 silly pacote version manifest for dotenv-expand@5.1.0 fetched in 609ms
79 silly resolveWithNewModule dotenv-expand@5.1.0 checking installable status
80 silly pacote version manifest for dotenv@8.2.0 fetched in 609ms
81 silly resolveWithNewModule dotenv@8.2.0 checking installable status
82 http fetch GET 304 https://registry.npmjs.org/eslint-config-react-app 639ms (from cache)
83 http fetch GET 304 https://registry.npmjs.org/eslint 686ms (from cache)
84 silly pacote range manifest for eslint-config-react-app@^6.0.0 fetched in 733ms
85 silly resolveWithNewModule eslint-config-react-app@6.0.0 checking installable status
86 silly pacote range manifest for eslint@^7.11.0 fetched in 749ms
87 silly resolveWithNewModule eslint@7.13.0 checking installable status
88 http fetch GET 304 https://registry.npmjs.org/eslint-plugin-import 608ms (from cache)
89 http fetch GET 304 https://registry.npmjs.org/eslint-plugin-flowtype 640ms (from cache)
90 silly pacote range manifest for eslint-plugin-import@^2.22.1 fetched in 733ms
91 silly resolveWithNewModule eslint-plugin-import@2.22.1 checking installable status
92 silly pacote range manifest for eslint-plugin-flowtype@^5.2.0 fetched in 749ms
93 silly resolveWithNewModule eslint-plugin-flowtype@5.2.0 checking installable status
94 silly fetchPackageMetaData error for eslint-webpack-plugin@^2.1.0 Invalid response body while trying to fetch https://registry.npmjs.org/eslint-webpack-plugin: Integrity verification failed for sha512-6Hhe/TB3T/lJE+KiF69LA92GORF4zcQZeJ2i/7JvRiRMyEpQ2JpGfiE757gL1tP6PvlrnA8RfabLddWV/xfx3w== (C:\Users\Shubham\AppData\Roaming\npm-cache\_cacache\content-v2\sha512\e8\78\5efd30774ff94913e2a217af4b03dd86391178cdc419789da2ffb26f46244cc84a50d89a467e213be7b80bd6d3fa3ef96b9c0f117da6cb75d595ff17f1df)
95 http fetch GET 304 https://registry.npmjs.org/eslint-plugin-jsx-a11y 717ms (from cache)
96 http fetch GET 304 https://registry.npmjs.org/eslint-plugin-react 717ms (from cache)
97 http fetch GET 304 https://registry.npmjs.org/eslint-plugin-testing-library 515ms (from cache)
98 http fetch GET 304 https://registry.npmjs.org/eslint-plugin-react-hooks 562ms (from cache)
99 silly pacote range manifest for eslint-plugin-jsx-a11y@^6.3.1 fetched in 764ms
100 silly resolveWithNewModule eslint-plugin-jsx-a11y@6.4.1 checking installable status
101 silly pacote range manifest for eslint-plugin-react@^7.21.5 fetched in 764ms
102 silly resolveWithNewModule eslint-plugin-react@7.21.5 checking installable status
103 silly pacote range manifest for eslint-plugin-testing-library@^3.9.2 fetched in 546ms
104 silly resolveWithNewModule eslint-plugin-testing-library@3.10.0 checking installable status
105 silly pacote range manifest for eslint-plugin-react-hooks@^4.2.0 fetched in 593ms
106 silly resolveWithNewModule eslint-plugin-react-hooks@4.2.0 checking installable status
107 http fetch GET 304 https://registry.npmjs.org/file-loader 437ms (from cache)
108 http fetch GET 304 https://registry.npmjs.org/fs-extra 437ms (from cache)
109 silly pacote version manifest for file-loader@6.1.1 fetched in 468ms
110 silly resolveWithNewModule file-loader@6.1.1 checking installable status
111 silly pacote range manifest for fs-extra@^9.0.1 fetched in 468ms
112 silly resolveWithNewModule fs-extra@9.0.1 checking installable status
113 silly fetchPackageMetaData error for html-webpack-plugin@4.5.0 Invalid response body while trying to fetch https://registry.npmjs.org/html-webpack-plugin: Integrity verification failed for sha512-ACKSx4pcaJAcXNF3oYDqYQ1FfWJiDg/weuGqopW/+56es/L9xEjwhMRyEW65atYUZ3QSKmI/uMHVU8Uk8KdJhA== (C:\Users\Shubham\AppData\Roaming\npm-cache\_cacache\content-v2\sha512\00\22\92c78a5c68901c5cd177a180ea610d457d62620e0ff07ae1aaa295bffb9e9eb3f2fdc448f084c472116eb96ad6146774122a623fb8c1d553c524f0a74984)
114 silly fetchPackageMetaData error for mini-css-extract-plugin@0.11.3 Invalid response body while trying to fetch https://registry.npmjs.org/mini-css-extract-plugin: Integrity verification failed for sha512-wpSZRKbogwBX57EWBwiP3T1lwE7nC5c0sqP5A5+FchF+DeioauJrnuzr3nhZhkV7F8FXw6JUYrxuSfmd92dKUw== (C:\Users\Shubham\AppData\Roaming\npm-cache\_cacache\content-v2\sha512\c2\94\9944a6e8830057e7b11607088fdd3d65c04ee70b9734b2a3f9039f8572117e0de8a86ae26b9eecebde785986457b17c157c3a25462bc6e49f99df7674a53)
115 http fetch GET 304 https://registry.npmjs.org/identity-obj-proxy 327ms (from cache)
116 silly pacote version manifest for identity-obj-proxy@3.0.0 fetched in 358ms
117 silly resolveWithNewModule identity-obj-proxy@3.0.0 checking installable status
118 silly fetchPackageMetaData error for jest@26.6.0 Invalid response body while trying to fetch https://registry.npmjs.org/jest: Integrity verification failed for sha512-vr8HFUZOd9dSXwKPVAKNab6MOfFSE/eexrRFZl3pbmKAyEzmxjmfGPm2392Dd/HO2Hn+4p9NH8hkV2Fss28PZg== (C:\Users\Shubham\AppData\Roaming\npm-cache\_cacache\content-v2\sha512\be\bf\0715464e77d7525f028f54028d69be8c39f15213f79ec6b445665de96e6280c84ce6c6399f18f9b6dfdd8377f1ced879fee29f4d1fc86457616cb36f0f66)
119 silly fetchPackageMetaData error for jest-resolve@26.6.0 Invalid response body while trying to fetch https://registry.npmjs.org/jest-resolve: Integrity verification failed for sha512-Amu+MhOgvMR6KZsr2eL99A9WgDunH9ZLuSmRDJ17kKRSFqGG0CpL31kcHxHIl9dsBkt7qRGBB+NraNPUNRNomg== (C:\Users\Shubham\AppData\Roaming\npm-cache\_cacache\content-v2\sha512\02\6b\be3213a0bcc47a299b2bd9e2fdf40f56803ba71fd64bb929910c9d7b90a45216a186d02a4bdf591c1f11c897d76c064b7ba9118107e36b68d3d43513689a)
120 http fetch GET 304 https://registry.npmjs.org/jest-watch-typeahead 296ms (from cache)
121 http fetch GET 304 https://registry.npmjs.org/jest-circus 328ms (from cache)
122 silly pacote version manifest for jest-watch-typeahead@0.6.1 fetched in 312ms
123 silly resolveWithNewModule jest-watch-typeahead@0.6.1 checking installable status
124 silly pacote version manifest for jest-circus@26.6.0 fetched in 375ms
125 silly resolveWithNewModule jest-circus@26.6.0 checking installable status
126 http fetch GET 304 https://registry.npmjs.org/optimize-css-assets-webpack-plugin 281ms (from cache)
127 silly pacote version manifest for optimize-css-assets-webpack-plugin@5.0.4 fetched in 312ms
128 silly resolveWithNewModule optimize-css-assets-webpack-plugin@5.0.4 checking installable status
129 http fetch GET 304 https://registry.npmjs.org/pnp-webpack-plugin 328ms (from cache)
130 http fetch GET 304 https://registry.npmjs.org/postcss-loader 219ms (from cache)
131 http fetch GET 304 https://registry.npmjs.org/postcss-flexbugs-fixes 281ms (from cache)
132 silly pacote version manifest for postcss-loader@3.0.0 fetched in 234ms
133 silly resolveWithNewModule postcss-loader@3.0.0 checking installable status
134 http fetch GET 304 https://registry.npmjs.org/postcss-normalize 203ms (from cache)
135 silly pacote version manifest for pnp-webpack-plugin@1.6.4 fetched in 343ms
136 silly resolveWithNewModule pnp-webpack-plugin@1.6.4 checking installable status
137 silly pacote version manifest for postcss-flexbugs-fixes@4.2.1 fetched in 281ms
138 silly resolveWithNewModule postcss-flexbugs-fixes@4.2.1 checking installable status
139 http fetch GET 304 https://registry.npmjs.org/postcss-safe-parser 187ms (from cache)
140 silly pacote version manifest for postcss-normalize@8.0.1 fetched in 219ms
141 silly resolveWithNewModule postcss-normalize@8.0.1 checking installable status
142 http fetch GET 304 https://registry.npmjs.org/postcss-preset-env 218ms (from cache)
143 silly pacote version manifest for postcss-safe-parser@5.0.2 fetched in 202ms
144 silly resolveWithNewModule postcss-safe-parser@5.0.2 checking installable status
145 http fetch GET 304 https://registry.npmjs.org/react-app-polyfill 188ms (from cache)
146 silly pacote version manifest for postcss-preset-env@6.7.0 fetched in 250ms
147 silly resolveWithNewModule postcss-preset-env@6.7.0 checking installable status
148 silly pacote range manifest for react-app-polyfill@^2.0.0 fetched in 234ms
149 silly resolveWithNewModule react-app-polyfill@2.0.0 checking installable status
150 http fetch GET 304 https://registry.npmjs.org/resolve 187ms (from cache)
151 http fetch GET 304 https://registry.npmjs.org/resolve-url-loader 187ms (from cache)
152 http fetch GET 304 https://registry.npmjs.org/react-refresh 250ms (from cache)
153 http fetch GET 304 https://registry.npmjs.org/react-dev-utils 296ms (from cache)
154 http fetch GET 304 https://registry.npmjs.org/sass-loader 187ms (from cache)
155 silly pacote version manifest for resolve@1.18.1 fetched in 234ms
156 silly resolveWithNewModule resolve@1.18.1 checking installable status
157 http fetch GET 304 https://registry.npmjs.org/semver 218ms (from cache)
158 silly pacote range manifest for resolve-url-loader@^3.1.2 fetched in 234ms
159 silly resolveWithNewModule resolve-url-loader@3.1.2 checking installable status
160 silly pacote range manifest for react-refresh@^0.8.3 fetched in 297ms
161 silly resolveWithNewModule react-refresh@0.8.3 checking installable status
162 silly pacote range manifest for react-dev-utils@^11.0.0 fetched in 343ms
163 silly resolveWithNewModule react-dev-utils@11.0.0 checking installable status
164 silly pacote version manifest for sass-loader@8.0.2 fetched in 234ms
165 silly resolveWithNewModule sass-loader@8.0.2 checking installable status
166 http fetch GET 304 https://registry.npmjs.org/style-loader 218ms (from cache)
167 silly pacote version manifest for semver@7.3.2 fetched in 249ms
168 silly resolveWithNewModule semver@7.3.2 checking installable status
169 silly pacote version manifest for style-loader@1.3.0 fetched in 250ms
170 silly resolveWithNewModule style-loader@1.3.0 checking installable status
171 http fetch GET 304 https://registry.npmjs.org/ts-pnp 296ms (from cache)
172 http fetch GET 304 https://registry.npmjs.org/terser-webpack-plugin 390ms (from cache)
173 http fetch GET 304 https://registry.npmjs.org/url-loader 234ms (from cache)
174 silly pacote version manifest for ts-pnp@1.2.0 fetched in 359ms
175 silly resolveWithNewModule ts-pnp@1.2.0 checking installable status
176 silly pacote version manifest for terser-webpack-plugin@4.2.3 fetched in 405ms
177 silly resolveWithNewModule terser-webpack-plugin@4.2.3 checking installable status
178 http fetch GET 304 https://registry.npmjs.org/webpack-manifest-plugin 218ms (from cache)
179 http fetch GET 304 https://registry.npmjs.org/workbox-webpack-plugin 218ms (from cache)
180 http fetch GET 304 https://registry.npmjs.org/fsevents 234ms (from cache)
181 silly pacote version manifest for url-loader@4.1.1 fetched in 265ms
182 silly resolveWithNewModule url-loader@4.1.1 checking installable status
183 silly pacote version manifest for webpack-manifest-plugin@2.2.0 fetched in 249ms
184 silly resolveWithNewModule webpack-manifest-plugin@2.2.0 checking installable status
185 http fetch GET 304 https://registry.npmjs.org/webpack-dev-server 249ms (from cache)
186 silly pacote version manifest for workbox-webpack-plugin@5.1.4 fetched in 265ms
187 silly resolveWithNewModule workbox-webpack-plugin@5.1.4 checking installable status
188 silly pacote range manifest for fsevents@^2.1.3 fetched in 250ms
189 silly resolveWithNewModule fsevents@2.2.1 checking installable status
190 silly pacote version manifest for webpack-dev-server@3.11.0 fetched in 281ms
191 silly resolveWithNewModule webpack-dev-server@3.11.0 checking installable status
192 http fetch GET 304 https://registry.npmjs.org/webpack 296ms (from cache)
193 silly pacote version manifest for webpack@4.44.2 fetched in 343ms
194 silly resolveWithNewModule webpack@4.44.2 checking installable status
195 timing npm Completed in 9188ms
196 error cb() never called!
197 error This is an error with npm itself. Please report this error at:
198 error <https://npm.community>

**Comment by ljharb** [comment]
Can you try with npm v7.0.11?

**Comment by shubhankartarkar** [comment]
My Os is windows 7 ,so never versions of node and npm are not compatible

**Comment by ljharb** [comment]
In that case it's unlikely your bug would ever be fixed; npm 6 is basically frozen, and the oldest version of node that has support is node 10. Windows 7 itself is EOL as of January.

**Comment by shubhankartarkar** [comment]
ok then i should close this issue btw thanks ☺️
