### ISSUE TITLE
[BUG] npm ci fails when trying to install private git dep

### ISSUE THREAD

**Issue by aks-** [npm/cli#2181]
### Current Behavior:
`npm ci` fails with following error log when trying to install a private git dep. I have tried protocols `https` and `git+https` but the result is same
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/private-service - Not found
npm ERR! 404
npm ERR! 404  'private-service@1.0.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

### Expected Behavior:
should install private git dep from github 

### Steps To Reproduce:
I am not sure if it's reproducable but try
1. add private git repo to package.json `https://github.com/user/myrepo.git`
2. npm ci

**Comment by jacoscaz** [comment]
I have just stumbled into this, reverting to `6.x` fixes the issue. It seems that any package referenced via `https` or `git+https` results in `npm` trying to download a package with the same name from the official registry.

**Comment by wraithgar** [comment]
Private git repos via https auth would only work with a token, and the bug that caused this fallback was fixed here https://github.com/npm/pacote/pull/61 and will be part of npm `v7.4.3` https://github.com/npm/cli/pull/2522
