### ISSUE TITLE
[BUG] npm v7 not using EXDEV aware move so failes upgrade running in docker

### ISSUE THREAD

**Issue by tlbdk** [npm/cli#2182]
### Current Behavior:

npm install failes in docker because it's doing EXDEV unaware rename, docker is using overlay filesystems so the new file will be in a new mount point even if it's in the same folder.

```
Step #1: npm notice 
Step #1: npm notice New patch version of npm available! 7.0.8 -> 7.0.11
Step #1: npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.0.11>
Step #1: npm notice Run `npm install -g npm@7.0.11` to update!
Step #1: npm notice 
Step #1: npm ERR! code EXDEV
Step #1: npm ERR! syscall rename
Step #1: npm ERR! path /opt/node-v15.2.1-linux-x64/lib/node_modules/npm
Step #1: npm ERR! dest /opt/node-v15.2.1-linux-x64/lib/node_modules/.npm-dMIHb7ie
Step #1: npm ERR! errno -18
Step #1: npm ERR! EXDEV: cross-device link not permitted, rename '/opt/node-v15.2.1-linux-x64/lib/node_modules/npm' -> '/opt/node-v15.2.1-linux-x64/lib/node_modules/.npm-dMIHb7ie'
Step #1: 
Step #1: npm ERR! A complete log of this run can be found in:
Step #1: npm ERR!     /root/.npm/_logs/2020-11-16T19_13_41_120Z-debug.log
Step #1: The command '/bin/sh -c /opt/node-v$NODE_VERSION-linux-x64/bin/npm install -g npm@$NPM_VERSION' returned a non-zero code: 238
```

This was fixed before in an older version of npm:

* https://github.com/npm/npm/issues/13306
* https://github.com/npm/npm/pull/15901

### Expected Behavior:

Be able to upgrade/downgrade npm while running in a docker image with npm preinstalled by using EXDEV aware rename.

### Steps To Reproduce:

```
# Extract nodejs and npm in layer
RUN tar -xJf "node-v15.2.1-linux-x64.tar.xz" -C /opt --no-same-owner 
# Install npm in a new layer
RUN /opt/node-v15.2.1-linux-x64/bin/npm install -g npm@6.14.8
```

### Environment:

- OS: Ubuntu 20.04 docker image
- Node: 15.2.1
- npm: 7.0.8

**Comment by tlbdk** [comment]
A workaround for this is to either force docker to fetch the files to same layer:

```
find . -type f -exec touch {} +
```

Or do nodejs extract and npm upgrade in same step:
https://github.com/connectedcars/docker-node/pull/43/files

**Comment by darcyclarke** [comment]
@tlbdk thanks for flagging this. We should have a patch out here shortly (ie. [`v7.4.2`](https://github.com/npm/cli/releases/tag/v7.4.2) should resolve this)
