### ISSUE TITLE
[BUG] NPM Error while terminating a running job or script

### ISSUE THREAD

**Issue by BalakrishnaRBhat** [npm/cli#2188]
### **Current Behavior**:
When closing a running custom npm script script using ^C the following error occurs:
`npm ERR! Cannot destructure property 'code' of 'object null' as it is null.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\brbrb\AppData\Local\npm-cache\_logs\2020-11-17T14_34_23_940Z-debug.log
Terminate batch job (Y/N)? Y`

### **Expected Behavior**:
The script should terminate properly.

### **Environment**:
- OS: Windows 10
- Node: 15.0.1
- npm: 7.0.6

**Comment by ljharb** [comment]
Can you try with npm v7.0.11?

**Comment by BalakrishnaRBhat** [comment]
I reverted back to the stable 6.14.8

**Comment by BalakrishnaRBhat** [comment]
The error does not occur in 7.0.12
