### ISSUE TITLE
[BUG] No "postinstall" on global packages anymore

### ISSUE THREAD

**Issue by voltuer** [npm/cli#2194]
### Current Behavior:

I'm making a global cli tool that asks you for your language preference upon install but since NPM 7 it doesn't run the postinstall script anymore

### Expected Behavior:

In NPM 6 it works just fine

### Steps To Reproduce:

npm i -g dnd

### Environment:

macOS Big Sur, npm 7

**Comment by ljharb** [comment]
Are you sure it’s not running it, as opposed to not displaying any output?

**Comment by voltuer** [comment]
Apparently it is running, but I need to show staff to the user, as it worked before v7

**Comment by ljharb** [comment]
That was intentionally suppressed in v7, to prevent spamming users with ads and similar messages. You’ll have to wait to show the users the output until the first time they use your tool.

**Comment by voltuer** [comment]
Could you please share a link to an official announcement of this change? I will need to explain this to my client

**Comment by ljharb** [comment]
https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major is the announcement, but it may not mention this one specifically.

**Comment by ljharb** [comment]
Ah, I didn’t realize it wasn’t actually running them globally.

**Comment by voltuer** [comment]
So how am I supposed to run a script that needs user input when installing my script?

**Comment by ljharb** [comment]
Generally speaking, installs aren't a place where user input is available - consider installs in CI.

**Comment by voltuer** [comment]
good point, hadn't seen it that way

**Comment by Apollon77** [comment]
We also have the same issue on non-global but "npm i in a directly by using the local package.json" ... it seems that postinstall and install is not executed

**Comment by sinedied** [comment]
The issue can be replicated also with [Decktape](https://github.com/astefanutti/decktape) with `npm i -g decktape@3.1.0`
- On NPM v6, the `pupeeter` dependency postinstall script works fine (downloads a chromium bin)
- On NPM v7, the `pupeeter` dependency postinstall script is NOT executed - not just muted, as install finishes quickly instead of donwloading a huge bin on my machine.

**Comment by darcyclarke** [comment]
The originating issue is actually the intended experience in v7; If you want to see when scripts are run, you can add the flag `--foreground-scripts`.
