### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by simsam0502** [npm/cli#2198]
### Environment:

OS: Windows 10
Node: 14.15.1
npm: 6.14.8

On running npm i/npm install
I am getting the following error-
npm WARN tar EPERM: operation not permitted, open 'C:\Users\admin\Desktop\git\express-locallibrary-tutorial\node_modules\.staging\cliui-ab78b072\LICENSE.txt'
npm WARN tar EPERM: operation not permitted, open 'C:\Users\admin\Desktop\git\express-locallibrary-tutorial\node_modules\.staging\wordwrap-fc5971cc\test\idleness.txt'
npm WARN tar EPERM: operation not permitted, open 'C:\Users\admin\Desktop\git\express-locallibrary-tutorial\node_modules\.staging\nodemon-929dba68\doc\cli\authors.txt'
npm WARN tar EPERM: operation not permitted, open 'C:\Users\admin\Desktop\git\express-locallibrary-tutorial\node_modules\.staging\nodemon-929dba68\doc\cli\config.txt'
npm WARN tar EPERM: operation not permitted, open 'C:\Users\admin\Desktop\git\express-locallibrary-tutorial\node_modules\.staging\nodemon-929dba68\doc\cli\help.txt'
npm WARN tar EPERM: operation not permitted, open 'C:\Users\admin\Desktop\git\express-locallibrary-tutorial\node_modules\.staging\nodemon-929dba68\doc\cli\logo.txt'
npm WARN tar EPERM: operation not permitted, open 'C:\Users\admin\Desktop\git\express-locallibrary-tutorial\node_modules\.staging\nodemon-929dba68\doc\cli\options.txt'
npm WARN tar EPERM: operation not permitted, open 'C:\Users\admin\Desktop\git\express-locallibrary-tutorial\node_modules\.staging\nodemon-929dba68\doc\cli\topics.txt'
npm WARN tar EPERM: operation not permitted, open 'C:\Users\admin\Desktop\git\express-locallibrary-tutorial\node_modules\.staging\nodemon-929dba68\doc\cli\usage.txt'
npm WARN tar EPERM: operation not permitted, open 'C:\Users\admin\Desktop\git\express-locallibrary-tutorial\node_modules\.staging\tslib-6e1de9af\CopyrightNotice.txt'
npm WARN tar EPERM: operation not permitted, open 'C:\Users\admin\Desktop\git\express-locallibrary-tutorial\node_modules\.staging\nodemon-929dba68\doc\cli\whoami.txt'
npm WARN tar EPERM: operation not permitted, open 'C:\Users\admin\Desktop\git\express-locallibrary-tutorial\node_modules\.staging\tslib-6e1de9af\LICENSE.txt'
npm WARN tar EPERM: operation not permitted, open 'C:\Users\admin\Desktop\git\express-locallibrary-tutorial\node_modules\.staging\emoji-regex-1e23ecff\LICENSE-MIT.txt'
npm WARN tar EPERM: operation not permitted, open 'C:\Users\admin\Desktop\git\express-locallibrary-tutorial\node_modules\.staging\set-blocking-e7ccdc13\LICENSE.txt'
npm WARN tar EPERM: operation not permitted, open 'C:\Users\admin\Desktop\git\express-locallibrary-tutorial\node_modules\.staging\sift-aa6cc4ae\MIT-LICENSE.txt'
npm WARN tar EPERM: operation not permitted, open 'C:\Users\admin\Desktop\git\express-locallibrary-tutorial\node_modules\.staging\signal-exit-c274b652\LICENSE.txt'
npm WARN tar EPERM: operation not permitted, open 'C:\Users\admin\Desktop\git\express-locallibrary-tutorial\node_modules\.staging\needle-f398f2d1\license.txt'
npm WARN tar EPERM: operation not permitted, open 'C:\Users\admin\Desktop\git\express-locallibrary-tutorial\node_modules\.staging\mkdirp-0b71ece8\bin\usage.txt'
npm WARN tar EPERM: operation not permitted, open 'C:\Users\admin\Desktop\git\express-locallibrary-tutorial\node_modules\.staging\emoji-regex-bfefe21d\LICENSE-MIT.txt'
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2020-11-19T04_12_33_833Z-debug.log

**Comment by csvan** [comment]
The error is clear - the user you are running NPM as does not have the correct permissions for that folder.
