### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by BenBera** [npm/cli#2201]
### Current Behavior:

When Running npm install  this is the error:
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:

### Expected Behavior:

To download all the dependencies correctly

**Comment by davusmolina** [comment]
A mi también me esta pasando, alguien por favor ayuda.

**Comment by davusmolina** [comment]
A mi también me esta pasando, por favor alguien ayúdenos.
