### ISSUE TITLE
[BUG] Local packages in "optionalDependencies" are copied to "dependencies". Optional local package is symlinked/removed.

### ISSUE THREAD

**Issue by o2genum** [npm/cli#2203]
- I have some local packages
- They are Windows-only (marked as `"os": [ "win32" ]` in their `package.json` files)
- The main package's `package.json` refers these packages as `"optionalDependencies"`

### Current Behavior:
- I'm using MacOS
- On `npm install` in main package, all `"optionalDependencies"` are added to `"dependencies"`
- The the packages are symlinked into main package's `node_modules` directory, even though their `npm install` scripts are not properly run
- With `npm install --no-optional`, the local packages are not symlinked, but __they are deleted from the repo__.

### Expected Behavior:
On MacOS, optional dependencies that turn out to be `win32` only, are ignored.

### Steps To Reproduce:
```
mkdir main; cd main; npm init; cd ..;
mkdir optional; cd optional; npm init; cd ..;
```
Then add to `main/package.json`:
```
  "optionalDependencies": {
    "optional": "file:../optional"
  },
```

And add to `optional/package.json`:
```
  "os": ["win32"],
```

```
cd main
npm install    # Or npm install --no-optional for optional folder to vanish
```

### Environment:
- OS: MacOs Big Sur
- Node: 15.2.1
- npm: 7.0.10

**Comment by darcyclarke** [comment]
@o2genum we've fixed several issues in this vein since you first reported, can you try updating to the latest v7 (ie. `npm i -g npm@7`) & see if you can reproduce this?

**Comment by ruyadorno** [comment]
same as: https://github.com/npm/cli/issues/724
