### ISSUE TITLE
[BUG] <title>npm can't find discord .js

### ISSUE THREAD

**Issue by Derygo** [npm/cli#2211]
### Environment:
<!--
ex.
- OS: Ubuntu 20.04
- Node: 13.14.0
- npm: [6.4.12]
(url)
![Screenshot 2020-11-20 193513](https://user-images.githubusercontent.com/74788497/99832338-0deb0a80-2b69-11eb-9ae0-c1ad8d726502.png)

**Comment by ljharb** [comment]
This seems unrelated to npm; can you please fill out the issue template, and this can be reopened?
