### ISSUE TITLE
[BUG] Errors with command: npm install discord.js

### ISSUE THREAD

**Issue by Derygo** [npm/cli#2214]
### Environment:

![Screenshot 2020-11-20 214043](https://user-images.githubusercontent.com/74788497/99843675-9c1bbc80-2b7a-11eb-8999-af293c7aa208.png)

**Comment by John67gr** [comment]
I have the same problem how can I fix that?

**Comment by Derygo** [comment]
Hey,

 just try to reinstall. It worked for me.

2020-12-13, sk, 22:54 John67gr <notifications@github.com> rašė:
