### ISSUE TITLE
[BUG] little-state-machine / npm install / incorrect path

### ISSUE THREAD

**Issue by AntekWartecki** [npm/cli#2216]

**Comment by ljharb** [comment]
What does "doesn't work" mean? Please provide detailed log output.

Also, please try with npm v7.0.13.

**Comment by AntekWartecki** [comment]
> What does "doesn't work" mean? Please provide detailed log output.
> 
> Also, please try with npm v7.0.13.

I received error, that `unable to resolve dependency tree`.

**Comment by AntekWartecki** [comment]
-

**Comment by AntekWartecki** [comment]
-
