### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by ArnavK-09** [npm/cli#2217]
### Current Behavior:

C:\Users\DELL>npm i -g expo-cli
npm WARN deprecated @hapi/joi@17.1.1: Switch to 'npm install joi'
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DELL\AppData\Roaming\npm-cache\_logs\2020-11-21T04_49_47_991Z-debug.log

### Expected Behavior:
I was Installing expo client but there i some errror PLease Help

### Steps To Reproduce:
PLease Help

### Environment:

- OS:Windows 10 
- Node: v14.15.1
- npm: 6.14.8

**Comment by isaacs** [comment]
We will definitely need that debug log that was generated, and anything else you can share about your environment, package.json file, lockfile, etc.

For others with the "same" problem: https://github.com/npm/cli/wiki/%22cb()-never-called%3F--I'm-having-the-same-problem!%22
