### ISSUE TITLE
Cannot update dependencies in monorepo with npm 7

### ISSUE THREAD

**Issue by cyberalien** [npm/cli#2218]
### Current Behavior:
When running `npm update` in monorepo root directory, NPM 7 tries to update all workspaces, not just current directory. That crashes due to issue in one of packages in sub-directory.

### Expected Behavior:
Expected NPM to update dependencies only in package.json in current directory, not traverse the entire monorepo.

If this is expected behaviour in version 7, I think there should be an option to `npm update` to ignore workspaces, but there isn't one in documentation.

### Steps To Reproduce:

```
git clone git@github.com:iconify/iconify.git
cd iconify
git checkout df883b6b84f6d18f5b725dd1903d1f07ed1209c6
npm update
```

### Environment:

OS: OSX 11.0.1
Node: 15.2.0
npm: 7.0.13

**Comment by darcyclarke** [comment]
@cyberalien appreciate the suggestion; If you can, please join or add enhancements in our [RFCs](https://github.com/npm/rfcs) repo/forum/calls as this is something we're currently looking into & how to improve the overall Workspace implementation
