### ISSUE TITLE
[BUG] `npm outdated --global` fails if the global library directory is missing

### ISSUE THREAD

**Issue by slippycheeze** [npm/cli#2219]
### Current Behavior:
If the `--global` directory does not exist:
1. `npm outdated --global` fails hard, `ENOENT` acting on the directory.
2. `npm install --global` works fine, creating the directory.

### Expected Behavior:
`npm outdated --global` works successfully even when the `--global` directory doesn't exist; it should report there are no outdated packages, just as if there was an empty directory.  Creating the directory is optional.

#### using standard, unmodified nodejs / npm

1. `# rm -rf /tmp/empty ; mkdir /tmp/empty`   # optional, to show that the target is an empty directory
1. `/usr/local/bin/npm outdated --global --prefix=/tmp/empty`

#### using graalvm

*Note:* graalvm uses an unmodified npm running on their own nodejs implementation.  See the original bug report at https://github.com/graalvm/graaljs/issues/247 for full details, but what is included here is sufficient to reproduce:

1. `brew cask install graalvm/tap/graalvm-ce-java11`  # or whatever method you like
2. `npm outdated --global`  # using the graalvm install of npm, of course.

Transcript with all commands from my system, using a clean install

```shell
] brew cask zap graalvm/tap/graalvm-ce-java11
# output elided

] ls /Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.3.0/Contents/Home
ls: /Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.3.0/Contents/Home: No such file or directory

] brew cask install graalvm/tap/graalvm-ce-java11
# output elided

] export JAVA_HOME=$(/usr/libexec/java_home -v 11.0.9) ; echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.3.0/Contents/Home

] hash -r ; type npm
npm is /Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.3.0/Contents/Home/bin/npm

] npm --version ; node --version ; java --version
6.14.6
v12.18.4
openjdk 11.0.9 2020-10-20
OpenJDK Runtime Environment GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06)
OpenJDK 64-Bit Server VM GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06, mixed mode, sharing)

] npm outdated --global
npm ERR! code ENOENT
npm ERR! syscall lstat
npm ERR! path /Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.3.0/Contents/Home/languages/js/lib
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, lstat '/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.3.0/Contents/Home/languages/js/lib'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

### Environment:
```
] sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H15
```

for stock npm:
```
] /usr/local/bin/node --version ; /usr/loca/bin/npm --version
v15.2.1
7.0.10
```

for graalvm npm:
```
] npm --version ; node --version ; java --version
6.14.6
v12.18.4
openjdk 11.0.9 2020-10-20
OpenJDK Runtime Environment GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06)
OpenJDK 64-Bit Server VM GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06, mixed mode, sharing)
```

**Comment by ljharb** [comment]
What happens with npm v7.0.15?

**Comment by slippycheeze** [comment]
sorry, I've been unable to test this because real life.  I hope to get you a response in the next week, but it depends how much of a mess the moves make delivering things.  not ideal, but sometimes life isn't.
