### ISSUE TITLE
[BUG] nofix

### ISSUE THREAD

**Issue by MichaelWheldon** [npm/cli#2221]

**Comment by ljharb** [comment]
It’s not a link - you scan it with an Authenticator app like Google Authenticator, or 1Password.

**Comment by MichaelWheldon** [comment]
@ljharb yeah I scanned the code but it doesn’t generate anything for me, per step 3 above. I’ll try one of the above apps 👀 

edit: yep that works, im dumb hahaha. ok to close this one out.
