### ISSUE TITLE
[BUG]Fails installing dependencies, reason: getaddrinfo ENOTFOUND packages.bethel.jw.org

### ISSUE THREAD

**Issue by approvedpr** [npm/cli#2222]

**Comment by nlf** [comment]
that indicates that your registry has been set to `https://packages.bethel.jw.org` which, indeed, does not resolve. try running `npm config set registry https://registry.npmjs.org` which will set your registry back to the default and should work correctly.

if you need your third party registry for something, it's possible you have a typo in the hostname or there's an outage that you'll have to wait out, neither of those are things we can help with unfortunately.
