### ISSUE TITLE
[BUG] npm init exposes git secrets

### ISSUE THREAD

**Issue by ariesclark** [npm/cli#2230]
### Current Behavior:

`npm init` exposes git secrets by default when a repo is cloned with the username and token within the url.

### Expected Behavior:

`npm init` removes username:token from the remote url when including it in the package.json

### Steps To Reproduce:

```
git clone https://username:token@github.com/example/repository
npm init -y
```

```json
// package.json
...
"repository": {
   "type": "git",
   "url": "git+https://username:token@github.com/example/repository.git"
},
...
```

### Environment:

- OS: Debian 10
- Node: v15.2.1
- npm: 6.14.9

**Comment by ariesclark** [comment]
it's actually 6.x, sorry!

**Comment by ljharb** [comment]
What happens with npm v7.14.0?

**Comment by Just-Moh-it** [comment]
Please fix this, I had secretly exposed my full-access key online.

**Comment by tooleks** [comment]
It can still be reproduced using npm `v11.4.2`. Are there any updates on this?
