### ISSUE TITLE
[BUG] Can't change the version of a workspace package and use the new version as a dependency (ETARGET)

### ISSUE THREAD

**Issue by AlCalzone** [npm/cli#2231]
### Current Behavior:
If I update the version of a workspace package and update the dependencies of another to depend on the new version, `npm install` fails with `ETARGET`.

### Expected Behavior:
If I update the version of a workspace package and update the dependencies of another to depend on the new version, `npm install` should not fail and update the `package-lock` accordingly.

### Steps To Reproduce:

1. `git clone https://github.com/zwave-js/node-zwave-js/tarball/a429fc0`
2. `npm install`
3. Open `packages\core\package.json`, change version to `5.4.1`
4. Open `packages\zwave-js\package.json`, change `@zwave-js/core` dependency to `"^5.4.1"`
5. `npm install`

```
$ npm i
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @zwave-js/core@^5.4.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

### Workaround:
```
rm package-lock.json
npm install
```

### Environment:

- OS: Windows 10 (x64)
- Node: v12.19.0
- npm: 7.0.14

**Comment by darcyclarke** [comment]
@AlCalzone we've fixed several issues in this area since you first reported, can you try updating to the latest v7 (ie. `npm i -g npm@7`) & see if you can reproduce this still?

**Comment by AlCalzone** [comment]
Can't reproduce with 7.5.1 👍🏻
