### ISSUE TITLE
[BUG] docz install failure on v6.14.9

### ISSUE THREAD

**Issue by mazanand1976** [npm/cli#2232]
[2020-11-24T11_40_56_733Z-debug.log](https://github.com/npm/cli/files/5589627/2020-11-24T11_40_56_733Z-debug.log)

### Current Behavior:

sh-5.0$ npm install docz
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated eslint-loader@2.2.1: This loader has been deprecated. Please use eslint-webpack-plugin
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated highlight.js@8.9.1: Version no longer supported. Upgrade to @latest
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/u0_a7/.npm/_logs/2020-11-24T11_40_56_733Z-debug.log
sh-5.0$ npm -version
6.14.9

### Expected Behavior:

It probably should have called cb() and completed the installation without breaking any thing else. Not sure though, we are about the WARN messages. Coming from C programming we like to have zero errors and zero warnings.

### Environment:

sh-5.0$ cat /etc/redhat-release 
Fedora release 33 (Thirty Three)
sh-5.0$ which npm
/usr/local/bin/npm
sh-5.0$ rpm -qa | grep "^npm"
npm-6.14.8-1.14.14.0.2.fc33.x86_64
sh-5.0$ id
uid=41497(u0_a7) gid=41497(u0_a7) groups=41497(u0_a7),7(lp),10(wheel),18(dialout),54(lock),63(audio),371(pkg-build),373(wireshark) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
sh-5.0$ 
sh-5.0$ Node
sh: Node: command not found
sh-5.0$

I hope this helps.

**Comment by ljharb** [comment]
What happens on the latest npm v6, and also on v7.14?

**Comment by mazanand1976** [comment]
sh-5.0$ npm --version
6.14.9
sh-5.0$ sudo npm install npm -g
[sudo] password for u0_a7:
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.14.9
updated 1 package in 20.886s
sh-5.0$ npm --version
6.14.9
sh-5.0$

**Comment by ljharb** [comment]
@mazanand1976 ah ok, what about with `sudo npm install -g npm@7`?

**Comment by mazanand1976** [comment]
Sorry for the delay.

sh-5.0$ sudo npm install -g npm@7
[sudo] password for u0_a7: 
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
+ npm@7.0.15
added 54 packages from 20 contributors, removed 241 packages and updated 194 packages in 71.228s
sh-5.0$ npm --version
7.0.15
sh-5.0$ npm install docz
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ERR_SOCKET_TIMEOUT: request to https://registry.npmjs.org/gatsby-plugin-page-creator failed, reason: Socket timeout
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/u0_a7/.npm/_logs/2020-12-02T15_12_41_020Z-debug.log
sh-5.0$ 
[2020-12-02T15_12_41_020Z-debug.log](https://github.com/npm/cli/files/5630236/2020-12-02T15_12_41_020Z-debug.log)

**Comment by mazanand1976** [comment]
Triage: So I know one kind of Age. Its in is a Japanese science fiction mecha space opera[1] anime. More Details at : https://en.wikipedia.org/wiki/Heroic_Age_(TV_series)
.
Thanks and Regards
D.

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
