### ISSUE TITLE
[BUG] Mac Os Big Sur is crashed on publish

### ISSUE THREAD

**Issue by tfedyanin** [npm/cli#2236]
### Current Behavior:
NPM is crashed my Big Sur on publishing, in docker work as expected.

### Expected Behavior:
No crashes

### Steps To Reproduce:
https://youtu.be/S1-xhEUY-wA
ex. steps to reproduce the behavior:
1. Use file in attachment
2. Do publish into a repository with command `npm publish css-loader-3.2.0.tgz --registry $REPO_URL`
3. MacOS crashed
[tgz_inside.zip](https://github.com/npm/cli/files/5591290/tgz_inside.zip)

### Environment:
- OS: Mac OS Big Sur 11.0.1 (20B29)
- Node: v12.19.0
- npm: 6.14.9

This happens only on one from 2694 tgz. Now I use the docker image `node` to do the same task, it works correctly.

**Comment by ljharb** [comment]
What happens on npm v7.14?

**Comment by tfedyanin** [comment]
@ljharb sorry for the delay.
➜  - npm -v                                                                                             
7.0.14
Works as expected.

**Comment by ljharb** [comment]
Since v6 is effectively frozen, and it works in v7, I’m going to close this as “fixed”.
