### ISSUE TITLE
[BUG] `npm i %moduel_name%` doesn't work (sill idealTree buildDeps)

### ISSUE THREAD

**Issue by pubmikeb** [npm/cli#2239]
### Current Behavior:
I try to execute `npm i uuid` and get:

```
>npm i uuid
[..................] / idealTree:WEB-48403: sill idealTree buildDeps
```

### Steps To Reproduce:
The `uuid` (any any other module) should be installed.

ex. steps to reproduce the behavior:
1. Install [`v16.0.0-nightly202011254f0f2e7138`](https://nodejs.org/download/nightly/v16.0.0-nightly202011254f0f2e7138/)
2. Open a `cmd` under admin and go to the project root, where `package.json` and `package-lock.json` are located
3. Run `npm i uuid`
4. See error:
```
>npm i uuid
[..................] / idealTree:WEB-48403: sill idealTree buildDeps
```

![25_191620](https://user-images.githubusercontent.com/17231333/100266837-c2fb3980-2f52-11eb-843c-a386ae6e0a5c.png)

No `uuid` is added to the `package.json` and to the `node_modules`.

**Comment by wraithgar** [comment]
I am able to install uuid just fine w/ `v7.4.1`.  If this is still an ongoing issue please enter your node version, npm version, and operating system type in the `Environment` info so we can try to debug further.

**Comment by pubmikeb** [comment]
I've just tried to reproduce the issue on `node-v16.0.0-nightly20210122a35b32ec1e-x64`, it works as expected.
The ticket can be marked as obsolete.
