### ISSUE TITLE
[BUG] npm start ignores empty argument on windows

### ISSUE THREAD

**Issue by highmtworks** [npm/cli#2249]
### Current Behavior:
package.json
```
{
  "scripts": {
    "start": "node index.js"
  }
}
```
index.js
```
console.log(process.argv.slice(2));
```

then,
```
npm start -- a "" b
```

npm 6.14.9, 7.0.11 prints
```
[ 'a', '', 'b' ]
```

but npm 7.0.12 - 7.0.14 prints
```
[ 'a', 'b' ]
```

### Expected Behavior:
should be
```
[ 'a', '', 'b' ]
```

### Steps To Reproduce:
see Current Behavior section

### Environment:
- OS: Windows 10 Pro 2004 (19041.630)
- Node: 15.13.0
- npm: 7.0.14

maybe caused by https://github.com/npm/cli/blob/ab0b932f7117419cc7de2f4438300651f729b413/node_modules/%40npmcli/run-script/lib/make-spawn-args.js#L13

**Comment by darcyclarke** [comment]
@highmtworks can you try updating to the latest v7 (ie. `npm i -g npm@7`) & try reproducing this?

**Comment by highmtworks** [comment]
Thank you for the response.
It still happens:
```
>npm --version
7.5.0

>node --version
v15.7.0

>npm start -s -- a "" b
[ 'a', 'b' ]
```

**Comment by highmtworks** [comment]
```
>npm --version
7.5.2

>node --version
v15.8.0

>npm start -s -- a "" b
[ 'a', 'b' ]
```

**Comment by highmtworks** [comment]
I created https://github.com/npm/run-script/pull/20 .
I hope it resolves this.

**Comment by wraithgar** [comment]
Closed by https://github.com/npm/run-script/pull/22
