### ISSUE TITLE
[BUG] npm 7.x executes package.json preinstall script after installing dependencies 

### ISSUE THREAD

**Issue by Ngorror** [npm/cli#2253]
### Current Behavior:
when you run `npm install`, `package.json` `preinstall` script will be executed after dependencies installation

### Expected Behavior:
`package.json` `preinstall` script must be executed before dependencies installation.

### Steps To Reproduce:
Execute the following commands to clone [my test repository](https://github.com/Ngorror/npm-preinstall-bug.git)  and run `npm install` to reproduce the problem
```
git clone https://github.com/Ngorror/npm-preinstall-bug.git
cd npm-preinstall-bug
npm install
```
OR
1. create `package.json` file in empty directory with the following content:
```
{
  "name": "npm-preinstall-bug",
  "version": "1.0.0",
  "dependencies": {
    "mongodb": ">=3.6.0"
  },
  "description": "",
  "main": "index.js",
  "scripts": {
    "preinstall": "rm -f -R node_modules"
  },
  "author": "",
  "license": "ISC"
}
```
2. execute `npm install`
3. npm will install dependencies and then it will execute `preinstall` script. as result `node_modules` directory will be deleted.

### Environment:
- OS: Linux Mint 20.04, Windows 10
- Node: >=17.0.0
- npm: >= 7.0.2

**Comment by ljharb** [comment]
Can you confirm the bug still happens in v7.0.15?

**Comment by Ngorror** [comment]
yep
I stumbled on this on my first install of node 15.0.0, npm 7.0.2 few months ago.
Since then I procrastinated to report the problem.
yesterday I installed node 15.3.0, npm 7.0.14
now I installed 7.0.15 - the problem is still here.

**Comment by darcyclarke** [comment]
@Ngorror this is actually working as intended; If, as your example alludes, you want to do a clean install - you can/should use `npm ci`

**Comment by pmunin** [comment]
Can someone reopen this issue? `preinstall` still not running before dependencies installation

**Comment by bugsounet** [comment]
Not always fixed ? (and same bug in v8)
