### ISSUE TITLE
[BUG] npm ERR! cb() never called!

### ISSUE THREAD

**Issue by ghost** [npm/cli#2254]
I'm getting an error while creating a react app with "create-react-app"

I Finded the cause of the error. I splitted my HDD into partitions and I'm trying to create a react app in one of those partitions (disk W:)

Error Screenshot:
![Screenshot (8)](https://user-images.githubusercontent.com/42522330/100527875-3d94b500-31f0-11eb-8d9a-f5e65f70e4eb.png)

On error log says "no space left on device" but my W: disk have 21.4GB free space
![Screenshot 2020-11-29 031215](https://user-images.githubusercontent.com/42522330/100527951-d0355400-31f0-11eb-9cca-00a398acd6c1.png)

![Screenshot 2020-11-29 031407](https://user-images.githubusercontent.com/42522330/100527974-feb32f00-31f0-11eb-8aae-8d91cd0dc4f8.png)

Error Log:
[2020-11-28T22_43_36_965Z-debug.log](https://github.com/npm/cli/files/5611394/2020-11-28T22_43_36_965Z-debug.log)

When I try to create a project on C: disk (SSD), project creating successfully:

![Screenshot 2020-11-29 031527](https://user-images.githubusercontent.com/42522330/100528005-50f45000-31f1-11eb-8051-543fde2657e7.png)

### Environment:
- OS: Windows 10 Version 20H2 Build: 19042.630
- Node: v14.4.0
- npm: 6.14.9

**Comment by ghost** [comment]
I discovered something new. There are only "react, redux, react-redux, firebase" packages in the project and the project is higher than 40gb
![Screenshot 2020-11-29 033522](https://user-images.githubusercontent.com/42522330/100528256-1d66f500-31f4-11eb-8c5b-273ceaf99828.png)


package.json file:
[package.txt](https://github.com/npm/cli/files/5611412/package.txt)

**Comment by ljharb** [comment]
That seems highly unlikely to be intended; i don’t have 40 gigs worth of node_modules on my entire machine.

**Comment by ghost** [comment]
I found what the problem is:
My disk's cluster size is 2048. I formatted my disk with smaller cluster size like 64K and... valala problem is solved
![Screenshot 2020-11-29 152258](https://user-images.githubusercontent.com/42522330/100540473-01e10600-3257-11eb-96e7-d0a70371712d.png)
