### ISSUE TITLE
Git packages can be semver-compatible with official releases

### ISSUE THREAD

**Issue by conartist6** [npm/cli#2256]
In my project I use a particular module (`sane`) directly (as a `devDependency`). I had to fork it to fix an issue, so in my `package.json` I depend directly on `conartist6/sane#branch`. I did not change the semver in my forked branch because I have an open PR against the base package, and they have a CI-based process for semver incrementing.

Now other of my dev dependencies use sane themselves and the version my fork claims to be is in their specified semver range. What I didn't realize is that these other packages are now using my forked version of sane. This didn't actually cause issues in my case right up until I tried to uninstall my forked version. It appeared to be gone -- it's no longer in my `package.json`, but actually it is not gone at all. It's still being used by all those dependencies! And what's worse, some other behavior caused it to go from being a `git+https` resolution to a `git+ssh` resolution (breaking CI), and then I got stuck in a loop because as soon as I added the package back with the correct `git+https` URL it was still deemed to be compatible with what was in `package-lock.json` and kept the old resolution even as I tried to explicitly force the new one.

I therefore propose that all git-based packages are assumed to be incompatible with packages published in registries. I believe this is in keeping with the wording and intent of the semver spec.

**Comment by wraithgar** [comment]
Changing the behavior of npm is done via the RFC process, which you can find more about [here](https://github.com/npm/rfcs)

**Comment by conartist6** [comment]
Are you suggesting that this behavior is part of the official
specification? I solved my problem by switching to yarn (which handles the
situation much better), so there's not much incentive for me to shepherd
this through an involved process anymore.
