### ISSUE TITLE
[BUG] Can't npm publish even after "npm login" and running as admin (Windows)

### ISSUE THREAD

**Issue by tadeaspaule** [npm/cli#2257]
### Current Behavior:

I try ```npm publish 0.5.5``` (or other version numbers) and get the -4048 EPERM unlink error seen frequently after googling for npm publish bugs. Pretty much all of those issues / SE pages just conclude with "you need to npm login". But I already did that. Running ```npm whoami``` confirms I am logged in as the correct user.

Moreover, everything was working fine for me just yesterday. The only difference compared to yesterday that I can recall was reinstalling Docker for Windows (which shouldn't be related, but mentioning just in case...

![image](https://user-images.githubusercontent.com/33228844/100550014-277e0780-3277-11eb-9b1a-6da9d06dff0d.png)

And when I check the ```AppData/Local/.../package.json``` folder, the folder is empty, with no ```package.json```

![image](https://user-images.githubusercontent.com/33228844/100550037-54321f00-3277-11eb-8c60-c9eb94e5167a.png)

Attached the error log file:
[2020-11-29T18_12_17_817Z-debug.log](https://github.com/npm/cli/files/5612678/2020-11-29T18_12_17_817Z-debug.log)

### Expected Behavior:

I expected ```npm publish``` to work like it did yesteday

### Steps To Reproduce:

I honestly don't know, I wasn't changing anything related to node or npm since the last time ```npm publish``` worked (yesterday).

### Environment:

- OS: Windows 10 Home
- Node: 14.15.1
- npm: 6.14.9

**Comment by ljharb** [comment]
The version number goes in package.json, not in the publish command.

**Comment by tadeaspaule** [comment]
@ljharb Oh my, you just saved my sanity. Thank you! I don't know why I remembered from yesterday that I was putting the version there. Instead I should've done ```npm version <new_version>``` followed by ```npm published```. Did that now and worked like a charm. Thanks again and sorry for wasting time haha
