### ISSUE TITLE
ERROR IN CREATING NEW PROJECT

### ISSUE THREAD

**Issue by RVT123123** [npm/cli#2258]
[2020-11-29T19_15_09_981Z-debug.log](https://github.com/npm/cli/files/5612726/2020-11-29T19_15_09_981Z-debug.log)

### Current Behavior:
When ever i used to create a new project/App

### Expected Behavior:
IT should create a project without any error 

### Steps To Reproduce:

1. open cmd
2. type ng new project name
3. 
4. 

### Environment:

- OS: Window 32 X64
- Node: 13.14.0
- npm: 6.4.12

**Comment by ljharb** [comment]
Please fill out the issue template.

**Comment by RVT123123** [comment]
Getting error whenever i used to create a new app/project in angular.

[2020-11-29T19_15_09_981Z-debug.log](https://github.com/npm/cli/files/5612720/2020-11-29T19_15_09_981Z-debug.log)

**Comment by ljharb** [comment]
Seems like a duplicate of #2130 and a duplicate of #1207, and a number of others.

You’re using node 13; you should try node 14 or 15.

**Comment by RVT123123** [comment]
node 14 or node 15 is not compatible with windows 7. I am using windows 7

**Comment by ljharb** [comment]
Windows 7 is EOL as of January 2020.

**Comment by RVT123123** [comment]
God I am outdated now...I can not live on this planet.
