### ISSUE TITLE
Cannot run ng serve

### ISSUE THREAD

**Issue by RVT123123** [npm/cli#2259]
[angular-errors.log](https://github.com/npm/cli/files/5612817/angular-errors.log)

### Current Behavior:
ng serve is not working for me

### Expected Behavior:
It should run perfectly ok

### Steps To Reproduce:
1.Make a new angular project
2.Try to run ng serve inside the project folder

### Environment:

ex.
- OS: Win32 x64
- Node: 13.14.0
- npm: 6.14.9

**Comment by ljharb** [comment]
Then you’ll need to file an issue on angular - this repo is for npm itself.

**Comment by RVT123123** [comment]
Alas!! ok close my issue here
