### ISSUE TITLE
cb() never called : npm install -g @angular/cli@latest

### ISSUE THREAD

**Issue by RVT123123** [npm/cli#2260]
### Current Behavior:
I am trying to install angular using npm

### Expected Behavior:
It should install successfully

### Steps To Reproduce:
1.Install node.js
2.Open cmd
3.Try to install angular using npm

### Environment:

- OS: Win  32 X64
- Node: 13.14.0
- npm: 6.14.9

[2020-11-29T21_47_18_170Z-debug.log](https://github.com/npm/cli/files/5612897/2020-11-29T21_47_18_170Z-debug.log)

**Comment by Tomato6966** [comment]
Bot
Hey Leute
Checkt auf jeden Fall @Tomato ab und seine Coolen Bots

Server : https://discord.gg/3ep6e3vEJf

Website : https://x10-gaming.eu/service/dc
