### ISSUE TITLE
[BUG] < using start and close whit ctrl+c >

### ISSUE THREAD

**Issue by ghost** [npm/cli#2261]
in a blank project(whit just app.js file), if i do the following command:
-npm init
-npm install --save-dev nodemon

and add in the scripts the "start":"nodemon app.js"

it works just fine(whit npm start), but when i stop nodemon whit ctrl+c, i have the following errors message:
npm ERR! path C:\Users\amine\Desktop\es_nodejs\sezione_5\234
npm ERR! command failed
npm ERR! signal SIGINT
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c "nodemon app.js"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\amine\AppData\Local\npm-cache\_logs\2020-11-29T23_14_25_908Z-debug.log

this error happens when i add "start":"nodemon app.js" or "start":"node app.js" (and then using npm start) 
if i use directly in the cmd: "node app.js", it works fine whit no errors when i ctrl+c
### Environment:
- OS: Windows 10
- Node: 15.2.1
- npm: 7.0.8

**Comment by ljharb** [comment]
This isn’t a bug, this is normal npm error output from run-scripts (like “start”).

**Comment by nlf** [comment]
the above comment is correct. if we exit due to a signal or a non-0 exit code, we print the error banner. this isn't a bug as we have no other way to determine if a process we ran failed for some reason.
