### ISSUE TITLE
[BUG] `~/.npmrc @scope:registry=http://def.com` has higher priority than command line param '--registry http://abc.com'

### ISSUE THREAD

**Issue by blesstosam** [npm/cli#2268]
I searched other issues, but I didn't find anything that was specifically this issue.

### Current Behavior:

`~/.npmrc @scope:registry=http://def.com` has higher priority than command line param '--registry http://abc.com'
Npm request http://def.com to get info

### Expected Behavior:

Command line shoud has higher priority
Npm should request http://abc.com to get info

### Steps To Reproduce:

my config: 
path: ~/.npmrc
```
@scope:registry=http://def.com 
```
command line in shell:
```shell
npm view @scope/pkg --registry http://abc.com
```

### Environment:

- OS: macos 10.14.2
- Node: v11.10.1
- npm: 6.13.6

**Comment by ljharb** [comment]
Why should it? Those are different configs.

**Comment by blesstosam** [comment]
> Why should it? Those are different configs.

So how can i use command line to override `registry` in `~/.npmrc` when i want to view a pkg with a scope like `@wl/ button`

**Comment by ljharb** [comment]
I don't know the command-line syntax off hand, but something like `NPM_CONFIG_@scope:registry=http://def.com npm view @scope/pkg` should do it.

**Comment by blesstosam** [comment]
i found  `npm view @scope/pkg --@scope:registry=http://abc.com` is working, but  `NPM_CONFIG_@scope:registry=http://abc.com npm view @scope/pkg` throw an err =>  zsh: no such file or directory:xxx
thanks anyway!
