### ISSUE TITLE
[FEATURE] Warn on npm i --save-dev with no package?

### ISSUE THREAD

**Issue by sistemd** [npm/cli#2272]
# What / Why
I always thought that `npm i` is equivalent to `npm i --production`, and that in order to install dev dependencies I have to run `npm i --save-dev`. Today I found out this is not the case. I thought it might be kind of nice to tell the user that in `npm i --save-dev`, the `--save-dev` flag has no effect.

**Comment by sistemd** [comment]
I'd be happy to implement this change in a PR if you guys think it's worthwhile

**Comment by ljharb** [comment]
I would expect `npm i --save` and `npm i --save-dev` and `npm i --save-peer` etc to all error out, since presumably they don't do anything without a specifier arg.

However, I think you'd need to suggest this as an RFC: https://github.com/npm/rfcs

**Comment by sistemd** [comment]
> I would expect `npm i --save` and `npm i --save-dev` and `npm i --save-peer` etc to all error out, since presumably they don't do anything without a specifier arg.
> 
> However, I think you'd need to suggest this as an RFC: https://github.com/npm/rfcs

Well, I wouldn't dare to go so far as erroring out at this point, since that could break other people's scripts... but at least let people know, maybe they actually meant to install a new package instead, or something
