### ISSUE TITLE
Error while running command ng serve

### ISSUE THREAD

**Issue by pihoo19** [npm/cli#2274]
npm install -D @schematics/angular @angular-devkit/core @angular-devkit/schematics
>>
>>
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ERR_SOCKET_TIMEOUT: request to https://registry.npmjs.org/semver failed, reason: Socket timeout
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dell\AppData\Local\npm-cache\_logs\2020-12-01T17_09_57_947Z-debug.log

Tried reinstalling angular cli but same error occurs everytime.

**Comment by csvan** [comment]
> npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ERR_SOCKET_TIMEOUT: request to https://registry.npmjs.org/semver failed, reason: Socket timeout

You cannot connect to the NPM registry. Check your proxy settings.

**Comment by pihoo19** [comment]
@csvan I checked my proxy settings it is fine but still the same error occurs.

**Comment by drake076** [comment]
Yes, I also face this kind of problem too, can any one suggest me the right way to [debugging](https://bestgolfiron2021.com/).
