### ISSUE TITLE
cb() never called error

### ISSUE THREAD

**Issue by PHPGuus** [npm/cli#2280]
System: Windows 10 Home, WSL2, Ubuntu 20.04, node v12.20.0, npm v6.14.8

npm install gave me this output:
npm WARN tar EPERM: operation not permitted, futime
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! virkivent@0.1.0 install: `npm install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the virkivent@0.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/leeuwg/.npm/_logs/2020-12-03T14_13_11_966Z-debug.log

The log file:
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'install',
1 verbose cli   '--scripts-prepend-node-path=auto'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.20.0
4 verbose run-script [ 'preinstall', 'install', 'postinstall' ]
5 info lifecycle virkivent@0.1.0~preinstall: virkivent@0.1.0
6 info lifecycle virkivent@0.1.0~install: virkivent@0.1.0
7 verbose lifecycle virkivent@0.1.0~install: unsafe-perm in lifecycle true
8 verbose lifecycle virkivent@0.1.0~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/mnt/d/Users/leeuwg/Work/VirKiVent/virkivent_webapp/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files (x86)/Intel/iCLS Client/:/mnt/c/Program Files/Intel/iCLS Client/:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files (x86)/Plantronics/Spokes3G/:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/leeuwg/AppData/Local/Microsoft/WindowsApps
9 verbose lifecycle virkivent@0.1.0~install: CWD: /mnt/d/Users/leeuwg/Work/VirKiVent/virkivent_webapp
10 silly lifecycle virkivent@0.1.0~install: Args: [ '-c', 'npm install' ]
11 silly lifecycle virkivent@0.1.0~install: Returned: code: 1  signal: null
12 info lifecycle virkivent@0.1.0~install: Failed to exec install script
13 verbose stack Error: virkivent@0.1.0 install: `npm install`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid virkivent@0.1.0
15 verbose cwd /mnt/d/Users/leeuwg/Work/VirKiVent/virkivent_webapp
16 verbose Linux 4.19.128-microsoft-standard
17 verbose argv "/usr/bin/node" "/usr/lib/node_modules/npm/bin/npm-cli.js" "run" "install" "--scripts-prepend-node-path=auto"
18 verbose node v12.20.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error virkivent@0.1.0 install: `npm install`
22 error Exit status 1
23 error Failed at the virkivent@0.1.0 install script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Am I doing something wrong (permissions, perhaps)?

Best,
Guus

**Comment by csvan** [comment]
> npm WARN tar EPERM: operation not permitted, futime

Your file system permissions do not permit NPM to execute what it needs, you should fix them.

**Comment by PHPGuus** [comment]
Thanks. I'll have a look-see... Might be because of WSL2 rather than native...
