### ISSUE TITLE
[BUG] Can't seem to use "npm ci" for a production install.

### ISSUE THREAD

**Issue by kramarz** [npm/cli#2286]
### Current Behavior:
I am reopening bug from archived npm repository: https://github.com/npm/npm/issues/20125
After generating `npm install --only=production --package-lock-only` where devDependencies are private and not accessible in production `npm ci --only=production` is failing. Error is `cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.`.

### Expected Behavior:

I would like to generate lock file in production and use it with `npm ci` even if devDependencies are unavailable. Could ci ignore mismatches in devDependencies if is running in production mode?

### Steps To Reproduce:
package.json:
```
{
  "dependencies": {
    "polka": ">=0.5.2"
  },
  "devDependencies": {
    "@internal/private": "0"
  }
}
```
commands:
```
$ npm install --only=production --package-lock-only
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @internal/private@0 (node_modules/@internal/private):
npm WARN 404 SKIPPING OPTIONAL DEPENDENCY: Not Found - GET https://registry.npmjs.org/@internal%2fprivate - Not found
npm WARN private_dev_dependency_npm No description
npm WARN private_dev_dependency_npm No repository field.
npm WARN private_dev_dependency_npm No license field.

added 5 packages and audited 5 packages in 2.012s
found 0 vulnerabilities

$ npm ci --only=production
npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! 
npm ERR! Missing: @internal/private@0
npm ERR! 
```
### Environment:

- Node: 12.19.0
- npm: 6.14.9

**Comment by ljharb** [comment]
What happens with npm v7.0.15?

**Comment by kramarz** [comment]
7.0.15 does not allow to even create lock without access to the package:
```
$ npm install --only=production --package-lock-only
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@internal%2fprivate - Not found
npm ERR! 404 
npm ERR! 404  '@internal/private@0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     [...]/.npm/_logs/2020-12-07T12_13_29_859Z-debug.log
```

**Comment by GrosSacASac** [comment]
I belive the correct way to do it is:

npm i --production

npm ci never supported --production only (nothing in the doc)

**Comment by kramarz** [comment]
But it works as long as you have a lock that includes devDependencies. In such situation If you then use `npm ci --only=production` then it skips devDependencies. It fails on check phase if lock does not contain devDependencies which would be skipped anyway.

**Comment by olehdevua** [comment]
`npm ci --only=production` works. Why it's not described in the docs in such case :question:
