### ISSUE TITLE
cb() never called!

### ISSUE THREAD

**Issue by faruk-gkc** [npm/cli#2289]
I cannot install any packages. I always get the same error. What should I do?

""npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\FARUK GÖKCEGÖZ\Desktop\JavaScriptDemos\ornekler\ORNEKLER\ORNEK1\JAVASCRİPT\npm_ders\_logs\2020-12-05T13_40_31_804Z-debug.log""

- Windows 10 Pro
- Node: 12.19.0
- npm: 6.14.8

**Comment by cmanning96** [comment]
For whatever it's worth, I ran into the same error but installing the package with sudo worked. Obviously still a bug that needs to be fixed but it'll work as a temporary workaround for me.

**Comment by faruk-gkc** [comment]
Thank you for your reply. I know that 'sudo' is not a valid command on windows. It gives an error because there are spaces in the file names and the characters are wrong. I guess I figured it out. Thank you again.

**Comment by faruk-gkc** [comment]
Thank you for your reply. I know that 'sudo' is not a valid command on windows. It gives an error because there are spaces in the file names and the characters are wrong. I guess I figured it out. Thank you again.
