### ISSUE TITLE
Register Button

### ISSUE THREAD

**Issue by drake070** [npm/cli#2290]
Hi
Can anyone tell [me](https://bestrunningshoes2021.com/) how to create a simple sign in/sign up button for this website? I'm waiting for your kind reply.

**Comment by david0709** [comment]
I also face this issue but I got a solution.
Steps
Click the green Create an account button. It's below the form.
Complete the CAPTCHA puzzle. ...
Click the Choose button for your desired plan. ...
Click the Verify email address button in the message from GitHub. ...
Review your plan selection and click [Continue](http://bestairfryers2021.com/). ...
Select your preferences and click Submit.
