### ISSUE TITLE
[BUG] NPM Install File System - No Peers/Deps Installed

### ISSUE THREAD

**Issue by leepowelldev** [npm/cli#2299]
### Current Behavior:
Currently with NPM@6 if I install via the filesystem `file:` then the dependencies of the package I am installing are also installed, however no attempt is made with NPM@7.

### Expected Behavior:
NPM@7 should attempt to install the dependencies of the package installed via the filesystem - should it also attempt to install the peer dependencies to the top level?

### Steps To Reproduce:
1. npm install path/to/local/package

### Environment:
- OS: Mac OS 10.15.5
- Node: 14.13.1
- npm: 7.1.0

**Comment by darcyclarke** [comment]
@leepowelldev npm v7 should install any peerDeps defined by a local `file:` dep if it's nested inside the root of the project. If, for instance, you reference a path outside the root (ex. `../x`) we won't install that packages deps (this was indeed a change from v6 - and something we're discussing already in https://github.com/npm/cli/issues/2443 & in our [Open RFC](https://github.com/npm/rfcs/) calls)
