### ISSUE TITLE
How to Run Codelyzer Code From Command Prompt

### ISSUE THREAD

**Issue by MohdRashid01** [npm/cli#2308]
Hi All,

I got below error when i execute npm run lint command (ERROR : angular-seed@1.0.0 lint: `gulp tslint)

Actually i want to run my code through codelyzer and im following this link https://www.npmjs.com/package/codelyzer for installation or setup codelyzer in ubuntu.
image
![image](https://user-images.githubusercontent.com/7812871/101654634-bef90c80-3a66-11eb-95df-4b67e908297c.png)

Here is the screenshot of npm, nodejs, gulp and angular version showing.

image
![image](https://user-images.githubusercontent.com/7812871/101654615-baccef00-3a66-11eb-8ef8-bba2935d251a.png)

and
image
![image](https://user-images.githubusercontent.com/7812871/101654597-b7396800-3a66-11eb-9591-2517bb317500.png)

when i type ng serve below is the screenshot it showing in my browser
![image](https://user-images.githubusercontent.com/7812871/101654577-b30d4a80-3a66-11eb-84a8-80116acc4958.png)

My company want to run code in local and output should show in command prompt or in terminal NOT FROM BROWSER or UI.

Please help me im new in codelyzer ..i dont know how to use it and how to execute it.
And how to solve above issue.

**Comment by isaacs** [comment]
Hi, @MohdRashid01.

Unfortunately, there is little I can do to help you.  This is a problem you are encountering with the packages you have installed with npm, but not with npm itself.  We do not maintain angular or codelyzer, and have no knowledge of how they work or why they might not be working in your case.

I recommend that you try running `npm bug codelyzer` and post an issue there.

**Comment by MohdRashid01** [comment]
For that issue i have solved it.

But i want to know how to run codelyzer code ...how they scan the code and how it show output in terminal or command prompt NOT IN BROWSER.

Please tel me how can i do it.
