### ISSUE TITLE
[BUG] uninstall does not remove --no-save installed package from node_modules

### ISSUE THREAD

**Issue by raphinesse** [npm/cli#2309]
### Current Behavior:
If I install a package using the `--no-save` option, **it is not removed** from `node_modules/` upon its uninstallation.

### Expected Behavior:
If I install a package using the `--no-save` option, **it should get removed** from `node_modules/` upon its uninstallation.

_NB_: this is also how npm 6 behaves.

### Steps To Reproduce:
1. Run the following
  ```bash
  cd $(mktemp -d)
  mkdir node_modules
  npm i q --no-save
  npm un q --no-save
  ```
2. Observe that `node_modules/q` still exists.

Omitting the `--no-save` option for the uninstallation command yields the same result. Substituting `mkdir node_modules` with `npm init --yes` makes no difference either.

### Environment:
- OS: Ubuntu `18.04.5` & `19.10`
- Node: `12.19.0` & `15.4.0`
- npm: `7.0.15` & `7.1.1`

**Comment by isaacs** [comment]
Confirmed.  This appears to be a bug in how we're handling the fake `{}` package we use when there's no package.json in the root project, combined with using the `actualTree` as the effective starting `idealTree` when there's no package-lock.json present.  If there's either a package.json _or_ a package-lock.json that declares the deps present, it does properly remove them.  If neither of those are there, it doesn't properly remove the dependency.

**Comment by miafan23** [comment]
Is there any plan to fix this bug in npm6 also? Would love to see it.
