### ISSUE TITLE
[BUG] npm 7.x installed but 6.x still shows as wanted

### ISSUE THREAD

**Issue by cehenriques** [npm/cli#2310]
### Current Behavior:
I installed npm 7 using the following command:
```
npm i -g npm@7.1.1
```

But if I check the global outdated packages I get one record about npm with:

- Current: 7.1.1
- Wanted: 6.14.9
- Latest: 6.14.9 

### Expected Behavior:
The docs say that:
"If there's no available semver range (i.e. **you're running npm outdated --global**, or the package isn't included in package.json), then **wanted shows the currently-installed version**."

https://docs.npmjs.com/cli/v7/commands/npm-outdated

And in this case it's not doing that.

### Steps To Reproduce:
1. Have npm 6.x installed in the machine
2. Force install npm 7.x globally
3. Check for global outdated packages
4. It should display a record about npm installed on v7 but wanted v6

### Environment:
ex.
- OS: macOS 11.0.1 (Big Sur)
- Node: 15.4.0
- npm: 7.1.1

**Comment by isaacs** [comment]
This is because it prefers the `latest` dist-tagged version, and `npm@latest` is still v6.  Please be patient, we'll make it the default approved release very soon :D

**Comment by JakobJingleheimer** [comment]
This is not fixed, so why is the issue closed? (I just spent ~15 minutes typing up another bug report because a search of open issues for this had none).

This is very confusing behaviour and, it seems like the output of `outdated` in this case is effectively misinformation.
