### ISSUE TITLE
[BUG] `npm install --prefix` doesn't install node_modules

### ISSUE THREAD

**Issue by meehow** [npm/cli#2315]
### Current Behavior:
`npm install --prefix tmp xxx.tar.gz` works as expected, but when I try to install from local directory `npm install --prefix tmp .`, then whole node_modules folder is not included there.

### Expected Behavior:

I expect to have node_modules folder with dependencies no matter if I install from directory or from archive.

### Steps To Reproduce:
`npm install -g --user root --production --prefix /tmp/xxx archive.tar.gz` <- works as expected
`npm install -g --user root --production --prefix /tmp/xxx ./` <- doesn't install dependencies

### Environment:

- OS: Ubuntu 20.04
- Node: v12.20.0
- npm: 6.14.8

**Comment by ljharb** [comment]
What happens with npm v7.1.1?

**Comment by meehow** [comment]
@ljharb npm v7.1.1 installed package [root](https://www.npmjs.com/package/root) as a bonus, but nothing from actual dependencies.

**Comment by ljharb** [comment]
Typically, `--` commands require `=` - ie, `--user=root`. What happens if you use an `=` to attach each `--foo` to its value?

**Comment by meehow** [comment]
@ljharb with `--user=root` there is no extra dependency installed, but needed dependencies are still not there
