### ISSUE TITLE
[BUG] common dependency maybe installed to the wrong place

### ISSUE THREAD

**Issue by 0xAC7** [npm/cli#2326]
### Current Behavior:
uuid@3.4.0 install inside the root node_modules folder.

### Expected Behavior:
uuid@3.4.0 installed inside request/node_modules folder.

### Steps To Reproduce:
1. Run 'npm init -y'
2. copy the following json to package.json
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "test",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "request": "2.88.2",
    "sockjs": "0.3.20",
    "react-native-uuid": "1.4.9"
  }
}
```
3. Run 'npm install'
4. both request@2.88.2 and sockjs@0.3.20 need uuid@3.4.0，so it should be install inside root node_modules. however it installed inside request/node_modules and  sockjs/node_modules.

### Environment:
- OS: Windows 10
- Node: 12.15.0
- npm: 6.14.9

**Comment by ljharb** [comment]
Do you perhaps have another uuid in the root?

What happens with npm v7.1.1?

**Comment by 0xAC7** [comment]
> Do you perhaps have another uuid in the root?
> 
> What happens with npm v7.1.1?

I tried npm@v7.1.1, it's right.
It should be noticed that 'react-native-uuid's bin name in package.json is same with 'uuid' (all called 'uuid').

**Comment by ljharb** [comment]
If npm v7 works, then i'd say the bug is fixed - v6 isn't going to be fixed at this point.

`react-native-uuid` having a name of `uuid` is very strange, and i'd even say that's a bug in that package.

**Comment by 0xAC7** [comment]
> If npm v7 works, then i'd say the bug is fixed - v6 isn't going to be fixed at this point.
> 
> `react-native-uuid` having a name of `uuid` is very strange, and i'd even say that's a bug in that package.

got it. thanks for your reply.
