### ISSUE TITLE
[BUG] Abort npm-commands that modify package.json if file is not writeable

### ISSUE THREAD

**Issue by wsdt** [npm/cli#2327]
### Current Behavior:
When installing or removing packages, the npm-cli installs/removes the package and just "tries" to add/remove it from package.json. 

### Expected Behavior:
Developers should be at least notified when package.json is not writeable, to avoid later confusion. Even better would be that command fails, as modifying the package.json could be considered more important than the actual local installation (e.g. when using a VCS in collaboration with multiple developers). This is also a problem, when using e.g. Docker (copying the package.json in there & building the image with insufficient dependencies. 

### Steps To Reproduce:
E.g. when using TFS, non-checked out files are write-protected (thus package.json cannot be modified). 

### Environment:
Windows 10 Pro
Visual Studio Code
TFS

**Comment by darcyclarke** [comment]
@wsdt it sounds like you may want to be using [`npm ci`](https://docs.npmjs.com/cli/v7/commands/npm-ci) & ensuring you're installing dependencies from a `package-lock.json`. You can ensure you aren't saving back to `package.json` or a lockfile by running install with `--no-save` (or using `ci` as mentioned). One further option is to run `install` with the option [`--dry-run`](https://docs.npmjs.com/cli/v7/using-npm/config#dry-run) if you really don't want to be saving/writing to anything & just learning what would have been changed.

**Comment by wsdt** [comment]
Please re-open. 

I want to save the dependencies. 

There is just no TFS support.

**Comment by ljharb** [comment]
What's TFS?

**Comment by wsdt** [comment]
TFS is used by some companies as an obsolete alternative to git.
