### ISSUE TITLE
[BUG] npm exec does not pass switches to the inner function

### ISSUE THREAD

**Issue by redfire75369** [npm/cli#2337]
### Current Behavior:
When entering this command, `npm exec --no babel --watch src --out-dir dist`, the output is all of the compiled files in text, which is the behaviour of `npm exec --no babel src`. This command, `npm exec --no -c "babel --watch src --out-dir dist"` has to be run for the expected behaviour.

### Expected Behavior:
Console Output of `Successfully compiled 21 files with Babel`.
All scripts are compiled and output to the `dist` directory

### Steps To Reproduce:
1. In this environment, run `npm exec --no babel --watch src --out-dir dist`
2. See console output of compiled files as text

### Environment:
- OS: Windows 10 Home v1909
- Node: 15.4.0
- npm: 7.1.2
- @babel/cli: 7.12.10
- @babel/core: 7.12.10

**Comment by darcyclarke** [comment]
@Redfire75369 I think you're missing a `--` between your args (ex. `npm exec --no -- babel --watch src --out-dir dist`)
