### ISSUE TITLE
[BUG] npm ERR! cb() never called!

### ISSUE THREAD

**Issue by Man-RP** [npm/cli#2338]
### Current Behavior:
I'm getting:
```
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     ..\AppData\Roaming\npm-cache\_logs\2020-12-12T09_42_18_360Z-debug.log
```
when trying to `npm install` to complete without errors

### Expected Behavior:
Finish install without errors

### Steps To Reproduce:
cloned repo from gitlab and typed `npm install`.
tried to `npm cache clean --force` , clone the repo in alternative directory, reinstall node and update npm.

### Environment:

- OS: MS Windows 10
- Node: 14.15.1
- npm: 6.14.9

the full error log attached.
[2020-12-12T09_42_18_360Z-debug.log](https://github.com/npm/cli/files/5682840/2020-12-12T09_42_18_360Z-debug.log)

**Comment by eoinion** [comment]
I got this resolved on my end.
My .npmrc file had proxy and https-proxy set up, not sure how they got in there.
I commented out both lines, saved file and working again as normal.

**Comment by Tomato6966** [comment]
First use this:     `npm cache clean --force`

Then it should work!

**Comment by Man-RP** [comment]
> First use this: `npm cache clean --force`
> 
> Then it should work!

actually, I had mentioned I tried this on issue's details.
