### ISSUE TITLE
Error message when running create-react-app

### ISSUE THREAD

**Issue by Hy-light** [npm/cli#2341]
I get this error anytime i run "npx create-react-app my-app"

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Walter\AppData\Local\npm-cache\_logs\2020-12-13T22_24_53_249Z-debug.log

Aborting installation.
  npm install --save --save-exact --loglevel error react react-dom react-scripts cra-template has failed.
![Screenshot (12)](https://user-images.githubusercontent.com/48451931/102026067-d18b8280-3d93-11eb-926c-2fa863c8d008.png)

**Comment by ljharb** [comment]
What version of node/npm?

**Comment by Hy-light** [comment]
> What version of node/npm?

v15.2.0/v7.0.8 respectively

**Comment by ljharb** [comment]
Can you also try npm v7.1.2?

**Comment by Hy-light** [comment]
> Can you also try npm v7.1.2?

Yes i just did, and i still have the same error message



npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Walter\AppData\Local\npm-cache\_logs\2020-12-14T01_46_02_115Z-debug.log

Aborting installation.
  npm install --save --save-exact --loglevel error react react-dom react-scripts cra-template has failed.

Deleting generated file... node_modulesnpm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Walter\AppData\Local\npm-cache\_logs\2020-12-14T01_46_02_115Z-debug.log

Aborting installation.
  npm install --save --save-exact --loglevel error react react-dom react-scripts cra-template has failed.

Deleting generated file... node_modules

**Comment by wraithgar** [comment]
npm `v7.20.0` added some things that should catch more of the problems this was causing, can you try with the latest npm?

**Comment by lukekarrys** [comment]
**Closing:** We suspect this has to do with a combination of resource constraints within the device/program being used and the large amount of transient dependencies being installed by this command.

We've opened https://github.com/npm/statusboard/issues/395 for us to look deeper into this and track the discussion and fixes around it. You can also read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) for more information on why this issue might be happening currently and ways to debug it.
