### ISSUE TITLE
[BUG] <title>npm error cb() never called!

### ISSUE THREAD

**Issue by dclifestyle** [npm/cli#2346]
Your environment has been set up for using Node.js 15.4.0 (x64) and npm.

C:\Users\Dylan>cd desktop

C:\Users\Dylan\Desktop>cd Robert Bot

C:\Users\Dylan\Desktop\Robert Bot>npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help init` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (robert-bot)
version: (1.0.0)
description:
entry point: (index.js) main.js
test command:
git repository:
keywords:
author: dctrades
license: (ISC)
About to write to C:\Users\Dylan\Desktop\Robert Bot\package.json:

{
  "name": "robert-bot",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "dctrades",
  "license": "ISC"
}

Is this OK? (yes) yes

C:\Users\Dylan\Desktop\Robert Bot>code .

C:\Users\Dylan\Desktop\Robert Bot>npm install discord.js
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, open 'C:\Users\Dyla
n\Desktop\Robert Bot\node_modules\setimmediate\LICENSE.txt'
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, open 'C:\Users\Dyla
n\Desktop\Robert Bot\node_modules\discord.js\webpack\discord.js.LICENSE.txt'
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dylan\AppData\Local\npm-cache\_logs\2020-12-14T17_40_55_42
4Z-debug.log

C:\Users\Dylan\Desktop\Robert Bot>

**Comment by Zr0-Con** [comment]
that keeps happening to me

**Comment by Zr0-Con** [comment]
when do people resopnd

**Comment by hugodupont** [comment]
You can try disabling your antivirus, worked for me

**Comment by RWUBAKWANAYO** [comment]
Yes  it's true that all issues depends on your antivirus, open your antivirus in the setting you'll see where node.js or others are blocked, after allow, it will work fine
