### ISSUE TITLE
[BUG] npm run [command] -- [--arg] does not pass the arg

### ISSUE THREAD

**Issue by Admiralfeb** [npm/cli#2350]
### Current Behavior:
Attempting to run this command against create-react-app `npm run test -- --coverage --watchAll=false`
When npm registers and begins the execution, it states that it is running `react-scripts test` with neither flag

### Expected Behavior:
I should be getting `react-scripts test "--coverage" "--watchAll=false"`

### Steps To Reproduce:
1. npx create-react-app test
2. cd to new project
3. run `npm run test -- --coverage --watchAll=false`
4. `coverage` and `watchAll=false` should both be passed to the test execution

### Environment:
- OS: Windows 10 19042.608
- Node: 15.3.0
- npm: 7.1.2

### Note
I can add `"test:coverage": "react-scripts test --coverage --watchAll=false"` to package.json and it works with no issue.

**Comment by darcyclarke** [comment]
@Admiralfeb this should be fixed in a newer version of v7; Grab the latest via `npm i -g npm@7`
