### ISSUE TITLE
[BUG] when using npm install, package.json has no change, but package-lock.json automatically changed

### ISSUE THREAD

**Issue by 1036875207** [npm/cli#2351]
![image](https://user-images.githubusercontent.com/25496705/102183300-92227a80-3ee8-11eb-9373-364ed7041d02.png)
devDependencies @vue/cli-service
@vue/cli-service requires "vue-loader-v16": "npm:vue-loader@^16.0.0-beta.7"

while using npm install, package-lock.json auto updated vue-loader-v16,
for keeping exactly the same dependencies, package-lock.json should not get auto updated

npm version 6.14.8

**Comment by ljharb** [comment]
What happens in npm v7.1.2?

**Comment by 1036875207** [comment]
> What happens in npm v7.1.2?

npm v7.1.2

vue-loader-v16 also get auto updated to @16.1.1
