### ISSUE TITLE
npm cli v7 doesn't find/install newly released packages that are in the registry

### ISSUE THREAD

**Issue by jeremy-coleman** [npm/cli#2359]
### Current Behavior:
NPM cli version 7 doesn't install packages that are recently released. It's almost like npm 7 is pointing to a different registry that is a delayed mirror of the registry used for v6. 

### Expected Behavior:
The package that's shown available in the registry should install. For example, typescript 4.0.13 didnt install for a couple days after release. @fluentui/react never installs using the latest release , because they update so often - so it's a pretty reproducible library to use.

npm cli v6, pnpm and yarn will install successfully.

### Steps To Reproduce:
Just update any package.json dependency version of a package that was recently released. Unsure on exact timeframe of the delay, it seems more popular packages will start to install sooner.

![image](https://user-images.githubusercontent.com/25135855/102274757-60aeac80-3ef2-11eb-9f01-3839b924e351.png)

yet

![image](https://user-images.githubusercontent.com/25135855/102275819-f860ca80-3ef3-11eb-9937-fb89a3a916c0.png)

### Environment:
- OS: Windows 10 
- Node: 15 latest
- npm: 7.1.0

**Comment by darcyclarke** [comment]
@jeremy-coleman Sorry to hear you've been seeing this delay. We believe theres been some improvements here but the right place to bring up any registry-specific issues you're seeing would either be filing a ticket with our [support](https://npmjs.com/support) team or giving feedback [here](https://github.com/npm/feedback)

**Comment by jeremy-coleman** [comment]
@darcyclarke this is not registry specific, it's CLI specific. This does not happen with v6 of the NPM cli, yarn, or pnpm. I'm curious what makes you think this is something wrong with the registry?

**Comment by darcyclarke** [comment]
@jeremy-coleman When you say `"npm 7 is pointing to a different registry that is a delayed mirror of the registry used for v6"`, this is incorrect. v7 points at the exact same registry as v6 (ie. `registry.npmjs.org`). What *has* been seen recently though, is an increased delay by the registry itself to invalidate it's cache once a package is published (we've seen, anecdotally, significant wait times between publishing a package & being able to fetch/access that same package). We've flagged this already with our peers & hope it's resolved & delays don't persist. From our standpoint, we've even considered introducing a new, opt-in, flag like `--wait` to be added to `npm publish` - where we'd recursively poll & not exit the process until you're actually able to fetch the package you've published; This is obviously a workaround, with the hope here being that we'll just get faster all around. 

If you're running into caching issues yourself, or are configuring a third-party registry, then there may be problems with your configuration (ref. [`--prefer-online`](https://docs.npmjs.com/cli/v7/using-npm/config#prefer-online) may be something you're looking for along with a [whole bunch of other cache configuration](https://docs.npmjs.com/cli/v7/using-npm/config)). Again, v7 is not pointing at a different, or mirrored, registry then v6.

**Comment by jeremy-coleman** [comment]
I said "It's almost like..". To better describe the behavior. IE: maybe the cause is from slow replications. But, thank you for the explanation. This happened again to me as recently as yesterday (Feb20 2021)
