### ISSUE TITLE
[BUG] npm ERR! cb() never called!

### ISSUE THREAD

**Issue by ghost** [npm/cli#2364]
### Current Behavior:
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>
[2020-12-16T17_19_50_540Z-debug.log.txt](https://github.com/npm/cli/files/5704369/2020-12-16T17_19_50_540Z-debug.log.txt)

### Expected Behavior:
creating new angular project

### Environment:
- OS: Windows 10
- Node: 14.15.2
- npm: 6.14.9

**Comment by DCarvalho44** [comment]
Hi, I have the same problem and I wondering if  you have could solved, I already tried to clean the cache but the problem continuous.

**Comment by Tomato6966** [comment]
First use this:     `npm cache clean --force`

Then it should work!

**Comment by ghost** [comment]
> First use this: `npm cache clean --force`
> 
> Then it should work!

already tried several times.

**Comment by WebXHZ** [comment]
您好 最后怎么解决的

**Comment by itzhak91** [comment]
> 您好 最后怎么解决的
Hi WebXHZ, I wanted to reset the OS but decided to switch to StackBlitz for now.
