### ISSUE TITLE
[BUG] npm ERR! cb() never called!

### ISSUE THREAD

**Issue by wujingquan** [npm/cli#2374]
### Current Behavior:

[2020-12-17T17_04_14_325Z-debug.log](https://github.com/npm/cli/files/5711034/2020-12-17T17_04_14_325Z-debug.log)

**Comment by wujingquan** [comment]
### Steps To Reproduce:
1. nrm use taobao
2. git clone git@github.com:NG-ZORRO/ng-zorro-antd.git
3. npm install

### Environment:

- OS: Windows10 pro 2004 19041.685
- Node: v14.15.1
- npm: 6.14.8

**Comment by Tomato6966** [comment]
First use this:     `npm cache clean --force`

Then it should work!
