### ISSUE TITLE
[BUG] Suddenly bluetooth-serial-port fails to compile... 

### ISSUE THREAD

**Issue by DougAnsonAustinTX** [npm/cli#2379]
### Current Behavior:

Literally 8 hours ago, this package was working great... now... no bueno.  Is this a supported npm package?

### Expected Behavior:

arm@pelion-edge-xavier:~/MotorVibrationSensor$ npm install .
npm ERR! code 1
npm ERR! path /home/arm/MotorVibrationSensor/node_modules/bluetooth-serial-port
npm ERR! command failed
npm ERR! command sh -c node-gyp configure build
npm ERR! make: Entering directory '/home/arm/MotorVibrationSensor/node_modules/bluetooth-serial-port/build'
npm ERR!   CXX(target) Release/obj.target/BluetoothSerialPort/src/linux/BluetoothSerialPort.o
npm ERR!   CXX(target) Release/obj.target/BluetoothSerialPort/src/linux/DeviceINQ.o
npm ERR!   CXX(target) Release/obj.target/BluetoothSerialPort/src/linux/BTSerialPortBinding.o
npm ERR! BluetoothSerialPort.target.mk:115: recipe for target 'Release/obj.target/BluetoothSerialPort/src/linux/BTSerialPortBinding.o' failed
npm ERR! make: Leaving directory '/home/arm/MotorVibrationSensor/node_modules/bluetooth-serial-port/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.4.0 | linux | arm64
npm ERR! gyp info find Python using Python version 3.6.9 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/arm/MotorVibrationSensor/node_modules/bluetooth-serial-port/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/arm/.cache/node-gyp/15.4.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/arm/.cache/node-gyp/15.4.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/arm/.cache/node-gyp/15.4.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/arm/MotorVibrationSensor/node_modules/bluetooth-serial-port',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! ../src/linux/DeviceINQ.cc: In static member function ‘static void DeviceINQ::EIO_AfterSdpSearch(uv_work_t*)’:
npm ERR! ../src/linux/DeviceINQ.cc:139:28: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
npm ERR!      baton->cb->Call(1, argv);
npm ERR!                             ^
npm ERR! In file included from ../src/linux/DeviceINQ.cc:14:0:
npm ERR! ../../nan/nan.h:1742:3: note: declared here
npm ERR!    Call(int argc, v8::Local<v8::Value> argv[]) const {
npm ERR!    ^~~~
npm ERR! ../src/linux/DeviceINQ.cc: In static member function ‘static void DeviceINQ::Init(v8::Local<v8::Object>)’:
npm ERR! ../src/linux/DeviceINQ.cc:166:98: warning: ignoring return value of ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’, declared with attribute warn_unused_result [-Wunused-result]
npm ERR!      target->Set(ctx, Nan::New("DeviceINQ").ToLocalChecked(), t->GetFunction(ctx).ToLocalChecked());
npm ERR!                                                                                                   ^
npm ERR! In file included from ../src/linux/DeviceINQ.cc:12:0:
npm ERR! /home/arm/.cache/node-gyp/15.4.0/include/node/v8.h:3716:37: note: declared here
npm ERR!    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
npm ERR!                                      ^~~
npm ERR! ../src/linux/DeviceINQ.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE DeviceINQ::InquireSync(Nan::NAN_METHOD_ARGS_TYPE)’:
npm ERR! ../src/linux/DeviceINQ.cc:251:26: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
npm ERR!        found->Call(2, argv);
npm ERR!                           ^
npm ERR! In file included from ../src/linux/DeviceINQ.cc:14:0:
npm ERR! ../../nan/nan.h:1742:3: note: declared here
npm ERR!    Call(int argc, v8::Local<v8::Value> argv[]) const {
npm ERR!    ^~~~
npm ERR! ../src/linux/DeviceINQ.cc:255:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
npm ERR!      callback->Call(0, argv);
npm ERR!                            ^
npm ERR! In file included from ../src/linux/DeviceINQ.cc:14:0:
npm ERR! ../../nan/nan.h:1742:3: note: declared here
npm ERR!    Call(int argc, v8::Local<v8::Value> argv[]) const {
npm ERR!    ^~~~
npm ERR! ../src/linux/DeviceINQ.cc: In member function ‘virtual void InquireWorker::HandleOKCallback()’:
npm ERR! ../src/linux/DeviceINQ.cc:284:26: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
npm ERR!        found->Call(2, argv);
npm ERR!                           ^
npm ERR! In file included from ../src/linux/DeviceINQ.cc:14:0:
npm ERR! ../../nan/nan.h:1742:3: note: declared here
npm ERR!    Call(int argc, v8::Local<v8::Value> argv[]) const {
npm ERR!    ^~~~
npm ERR! ../src/linux/DeviceINQ.cc:288:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
npm ERR!      callback->Call(0, argv);
npm ERR!                            ^
npm ERR! In file included from ../src/linux/DeviceINQ.cc:14:0:
npm ERR! ../../nan/nan.h:1742:3: note: declared here
npm ERR!    Call(int argc, v8::Local<v8::Value> argv[]) const {
npm ERR!    ^~~~
npm ERR! ../src/linux/DeviceINQ.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE DeviceINQ::ListPairedDevices(Nan::NAN_METHOD_ARGS_TYPE)’:
npm ERR! ../src/linux/DeviceINQ.cc:366:83: warning: ignoring return value of ‘v8::MaybeLocal<v8::Value> v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*)’, declared with attribute warn_unused_result [-Wunused-result]
npm ERR!      cb->Call(Nan::GetCurrentContext(), Nan::GetCurrentContext()->Global(), 1, argv);
npm ERR!                                                                                    ^
npm ERR! In file included from ../src/linux/DeviceINQ.cc:12:0:
npm ERR! /home/arm/.cache/node-gyp/15.4.0/include/node/v8.h:4514:43: note: declared here
npm ERR!    V8_WARN_UNUSED_RESULT MaybeLocal<Value> Call(Local<Context> context,
npm ERR!                                            ^~~~
npm ERR! ../src/linux/BTSerialPortBinding.cc: In static member function ‘static void BTSerialPortBinding::EIO_AfterConnect(uv_work_t*)’:
npm ERR! ../src/linux/BTSerialPortBinding.cc:83:32: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
npm ERR!          baton->cb->Call(0, NULL);
npm ERR!                                 ^
npm ERR! In file included from ../src/linux/BTSerialPortBinding.cc:14:0:
npm ERR! ../../nan/nan.h:1742:3: note: declared here
npm ERR!    Call(int argc, v8::Local<v8::Value> argv[]) const {
npm ERR!    ^~~~
npm ERR! ../src/linux/BTSerialPortBinding.cc:90:33: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
npm ERR!          baton->ecb->Call(1, argv);
npm ERR!                                  ^
npm ERR! In file included from ../src/linux/BTSerialPortBinding.cc:14:0:
npm ERR! ../../nan/nan.h:1742:3: note: declared here
npm ERR!    Call(int argc, v8::Local<v8::Value> argv[]) const {
npm ERR!    ^~~~
npm ERR! ../src/linux/BTSerialPortBinding.cc: In static member function ‘static void BTSerialPortBinding::EIO_Write(uv_work_t*)’:
npm ERR! ../src/linux/BTSerialPortBinding.cc:114:62: warning: pointer of type ‘void *’ used in arithmetic [-Wpointer-arith]
npm ERR!              int bytesSent = write(rfcomm->s, data->bufferData+data->result, bytesToSend);
npm ERR!                                               ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
npm ERR! ../src/linux/BTSerialPortBinding.cc: In static member function ‘static void BTSerialPortBinding::EIO_AfterWrite(uv_work_t*)’:
npm ERR! ../src/linux/BTSerialPortBinding.cc:143:33: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
npm ERR!      data->callback->Call(2, argv);
npm ERR!                                  ^
npm ERR! In file included from ../src/linux/BTSerialPortBinding.cc:14:0:
npm ERR! ../../nan/nan.h:1742:3: note: declared here
npm ERR!    Call(int argc, v8::Local<v8::Value> argv[]) const {
npm ERR!    ^~~~
npm ERR! ../src/linux/BTSerialPortBinding.cc: In static member function ‘static void BTSerialPortBinding::EIO_AfterRead(uv_work_t*)’:
npm ERR! ../src/linux/BTSerialPortBinding.cc:206:117: error: no matching function for call to ‘v8::Object::Get(v8::Local<v8::String>)’
npm ERR!          Local<Function> bufferConstructor = Local<Function>::Cast(globalObj->Get(Nan::New("Buffer").ToLocalChecked()));
npm ERR!                                                                                                                      ^
npm ERR! In file included from ../src/linux/BTSerialPortBinding.cc:12:0:
npm ERR! /home/arm/.cache/node-gyp/15.4.0/include/node/v8.h:3763:43: note: candidate: v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)
npm ERR!    V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
npm ERR!                                            ^~~
npm ERR! /home/arm/.cache/node-gyp/15.4.0/include/node/v8.h:3763:43: note:   candidate expects 2 arguments, 1 provided
npm ERR! /home/arm/.cache/node-gyp/15.4.0/include/node/v8.h:3766:43: note: candidate: v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)
npm ERR!    V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
npm ERR!                                            ^~~
npm ERR! /home/arm/.cache/node-gyp/15.4.0/include/node/v8.h:3766:43: note:   candidate expects 2 arguments, 1 provided
npm ERR! ../src/linux/BTSerialPortBinding.cc:215:28: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
npm ERR!      baton->cb->Call(2, argv);
npm ERR!                             ^
npm ERR! In file included from ../src/linux/BTSerialPortBinding.cc:14:0:
npm ERR! ../../nan/nan.h:1742:3: note: declared here
npm ERR!    Call(int argc, v8::Local<v8::Value> argv[]) const {
npm ERR!    ^~~~
npm ERR! ../src/linux/BTSerialPortBinding.cc: In static member function ‘static void BTSerialPortBinding::Init(v8::Local<v8::Object>)’:
npm ERR! ../src/linux/BTSerialPortBinding.cc:242:103: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::Function>)’
npm ERR!      target->Set(Nan::New("BTSerialPortBinding").ToLocalChecked(), t->GetFunction(ctx).ToLocalChecked());
npm ERR!                                                                                                        ^
npm ERR! In file included from ../src/linux/BTSerialPortBinding.cc:12:0:
npm ERR! /home/arm/.cache/node-gyp/15.4.0/include/node/v8.h:3716:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
npm ERR!    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
npm ERR!                                      ^~~
npm ERR! /home/arm/.cache/node-gyp/15.4.0/include/node/v8.h:3716:37: note:   candidate expects 3 arguments, 2 provided
npm ERR! /home/arm/.cache/node-gyp/15.4.0/include/node/v8.h:3719:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
npm ERR!    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
npm ERR!                                      ^~~
npm ERR! /home/arm/.cache/node-gyp/15.4.0/include/node/v8.h:3719:37: note:   candidate expects 3 arguments, 2 provided
npm ERR! ../src/linux/BTSerialPortBinding.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE BTSerialPortBinding::Read(Nan::NAN_METHOD_ARGS_TYPE)’:
npm ERR! ../src/linux/BTSerialPortBinding.cc:392:25: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
npm ERR!          nc->Call(2, argv);
npm ERR!                          ^
npm ERR! In file included from ../src/linux/BTSerialPortBinding.cc:14:0:
npm ERR! ../../nan/nan.h:1742:3: note: declared here
npm ERR!    Call(int argc, v8::Local<v8::Value> argv[]) const {
npm ERR!    ^~~~
npm ERR! ../src/linux/BTSerialPortBinding.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE BTSerialPortBinding::Close(Nan::NAN_METHOD_ARGS_TYPE)’:
npm ERR! ../src/linux/BTSerialPortBinding.cc:363:14: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
npm ERR!          write(rfcomm->rep[1], "close", (strlen("close")+1));
npm ERR!          ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! make: *** [Release/obj.target/BluetoothSerialPort/src/linux/BTSerialPortBinding.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:284:12)
npm ERR! gyp ERR! System Linux 4.9.140-tegra
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
npm ERR! gyp ERR! cwd /home/arm/MotorVibrationSensor/node_modules/bluetooth-serial-port
npm ERR! gyp ERR! node -v v15.4.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/arm/.npm/_logs/2020-12-18T06_51_08_461Z-debug.log
arm@pelion-edge-xavier:~/MotorVibrationSensor$ 

Somehow the API has been changed or depricated... this does not seem to be a well-coordinated effort.

**Comment by tzukpolinsky** [comment]
hi
for anyone who had the same trouble as me
there is a branch that compiles
just install by this command:

npm i https://github.com/tinyprinter/node-bluetooth-serial-port.git
