### ISSUE TITLE
[BUG] npm link <package-name> installs package in global node_modules

### ISSUE THREAD

**Issue by rafgraph** [npm/cli#2390]
### Current Behavior:
`npm link <package-name>` automatically installs the package in global `node_modules` if it doesn't exist.

### Expected Behavior:
To receive an error that the package can't be linked because it doesn't exist in global `node_modules`.

I use `npm link` frequently for developing packages, which relies on running `npm link` in the package directory to link it to global `node_modules` and then running `npm link <package-name>` in the app. If I forget to link the package first, the `npm link <package-name>` will install the package from the registry and link to that version without informing me.

### Steps To Reproduce:
```zsh
npm init --yes
# run npm link with any package not already installed in global node_modules
npm link detect-it
npm ls -g
# detect-it will now be installed in global node_modules
```

### Environment:
- OS: MacOS 10.15.7
- Node: 14.15.0
- npm: 7.3.0

Thanks for all the great work on npm v7, I'm really enjoying using it!

**Comment by darcyclarke** [comment]
`npm link` should be working as intended. If you have a suggestion about changing how that works we'd encourage you to open up a new [RFC](https://github.com/npm/rfcs)

**Comment by rafgraph** [comment]
Okay, [the docs](https://docs.npmjs.com/cli/v7/commands/npm-link) don't mention this behavior.
