### ISSUE TITLE
[BUG] npm unlink <package> removes it from package.json dependencies

### ISSUE THREAD

**Issue by rafgraph** [npm/cli#2392]
### Current Behavior:
`npm unlink <package>` removes the package from `package.json` even if it was previously installed from the registry.

### Expected Behavior:
To remove the symlink and install the package version that's listed in `package.json` from the registry.

### Steps To Reproduce:
```zsh
mkdir test && cd test
git clone git@github.com:rafgraph/rollpkg-example-package.git
# rollpkg-example-package is a dependency of rollpkg-example-package-demo
git clone https://github.com/rafgraph/rollpkg-example-package-demo
# link rollpkg-example-package to global node_mod
cd rollpkg-example-package && npm i && npm link
# in the demo app link to rollpkg-example-package from global node_mod
cd ../rollpkg-example-package-demo && npm i && npm link rollpkg-example-package
# note that package.json is unchanged, it still lists "rollpkg-example-package": "^0.2.1" as a dep
# running unlink will remove rollpkg-example-package from package.json
# instead of just removing the symlink and installing the registry version
npm unlink rollpkg-example-package
```

### Environment:

- OS: MacOS 10.15.7
- Node: 14.15.0
- npm: 7.3.0

Thanks for all the great work on npm v7, I'm really enjoying using it!

**Comment by rafgraph** [comment]
Just a thought, but there seems to be some complexities around linking created by overloading the dependency field in package.json. I've used `npm link` for a number of years for local development, and most of the time it's awesome, but some of the time it can be frustrating usually because it's not clear what the current state is, or the state changes in unexpected ways. 

What if linked packages were tracked separately from installed packages? Maybe linked packages could have a leading underscore in package.json, `"_some-package": "../path/to/link"`, while installed packages stay the same `"some-package": "^1.0.0"`, so that both can be present in package.json dependencies.

Each can have independent `install`/`uninstall` and `link`/`unlink` commands. If just one of `"_some-package": "../path/to/link"` or `"some-package": "^1.0.0"` is present then that source is used. And if both are present then the link version overrides the install version.

This would allow a package only to be installed, or only be linked. As well as for a default + override behavior where the override can be added/removed without affecting the default.

**Comment by darcyclarke** [comment]
`npm unlink` should be working as intended. If you'd like to suggest different behavior we encourage you to open an [RFC](https://github.com/npm/rfcs)
