### ISSUE TITLE
[BUG] NPM doesn't render checkboxes when showing markdown

### ISSUE THREAD

**Issue by Yash-Singh1** [npm/cli#2393]
### Current Behavior:

![Screenshot from 2020-12-20 15-55-51](https://user-images.githubusercontent.com/53054099/102727670-ddb79880-42db-11eb-83ad-b3b62d318229.png)

### Expected Behavior:

Checkboxes to appear (non-editable)

### Steps To Reproduce:

1. https://www.npmjs.com/package/@muratoner/semantic-ui-react-native
2. See the checkboxes as `[ ]` and `[x]`

**Comment by Yazeed0712** [comment]
Good 1

**Comment by csvan** [comment]
This is the npm website, it has nothing to do with the CLI

**Comment by wraithgar** [comment]
Please open a ticket up through https://www.npmjs.com/support for registry/website related issues.  This repo's issue tracker is for the CLI itself.

**Comment by VityaSchel** [comment]
> Please open a ticket up through https://www.npmjs.com/support for registry/website related issues. This repo's issue tracker is for the CLI itself.

I opened 2 tickets, opened a discussion thread in feedback and no response. Support told me to open issue here. Please do something, it's been 2 years and still no support for checkboxes. GitHub supports it, any markdown render engine supports it, npm doesn't!
