### ISSUE TITLE
[BUG] npm ERR! cb() never called!

### ISSUE THREAD

**Issue by start2018** [npm/cli#2397]
### Current Behavior:
Repeatedly showing **TAR_ENTRY_ERROR ENOENT: no such file or directory** by scanning every directory.

### Expected Behavior:
Wanted to install modules.

### Steps To Reproduce:
1. In Windows 10 / NPM+Nodejs lastest with LTS,
2. You enter `npm install` with  `"scripts": {
		"build": "node .electron-vue/build.js && electron-builder",
		"build:dir": "node .electron-vue/build.js && electron-builder --dir",
		"build:noasar": "node .electron-vue/build.js && electron-builder --dir --asar=false",
		"build:clean": "cross-env BUILD_TARGET=clean node .electron-vue/build.js",
		"dev": "cross-env NODE_ENV=development node .electron-vue/dev-runner.js",
		"e2e": "npm run pack && mocha test/e2e",
		"lint": "eslint ./src/renderer/ --ext js,vue --max-warnings 0",
		"lint:fix": "eslint ./src/renderer/ --ext js,vue --fix",
		"pack": "npm run pack:main && npm run pack:renderer",
		"pack:main": "cross-env NODE_ENV=production webpack --progress --colors --config .electron-vue/webpack.main.config.js",
		"pack:renderer": "cross-env NODE_ENV=production webpack --progress --colors --config .electron-vue/webpack.renderer.config.js",
		"test": "npm run unit && npm run e2e",
		"unit": "karma start test/unit/karma.conf.js",
		"postinstall": "npm rebuild --target=4.0.3 --runtime=electron",
		"start": "npm run dev"
	}`
package.json's script look like this
3. See error!

### Environment:

OS : Windows 10 Pro 20H2
Node: 14.15.3 LTS
NPM: 7.0.15

**Comment by wraithgar** [comment]
npm v7.20.0 added some things that should catch more of the problems this was causing, can you try with the latest npm?  If it is still happening please open a new issue and be sure to include the debug log.
