### ISSUE TITLE
[BUG] discord-player, resume function

### ISSUE THREAD

**Issue by nixsmz** [npm/cli#2407]
### Current Behavior:
Resume function of discord-player module does not work properly with linux subsystems ! Resuming the music 1/2 times and getting sounds bug after music is resumed.

### Expected Behavior:
resume the music properly when entering resume command on discord. 
NB: Works fine when starting it with versions [node : 14.15.1, npm : 6.14.8] with 'node .' command. Didn't try it on Linux, should be intresting to know...

### Steps To Reproduce:
1. cd command to discord bot project
2. start bot with command node .
3. when bot is online on discord pause a music 
4. Then enter the resume command

### Environment:
- OS: Windows 10, Ubuntu 20.04 LTS Linux Subsystem (WSL Bash)
- Node: 15.4.0
- npm: 7.0.15

**Comment by shadowspawn** [comment]
This sounds like an issue with your discord-player module and not with npm itself, so you probably want to report the issue against the discord-player module instead of here.
