### ISSUE TITLE
ngx-slickJS initial slide option not working in angular 8 

### ISSUE THREAD

**Issue by rahulh11041996** [npm/cli#2416]
i created a slider in angular using ngx-slickJS and its working fine, but i need to show 3rd slide initialy but its not working
  
newsDetails: Slick.Config = {
    infinite: false,
    slidesToShow: 1,
    slidesToScroll: 1,
    dots: false,
    autoplay: false,
    fade: true,
    speed: 300,
    easing: 'linear',
    mouseWheelMove: false,
    initialSlide: 2
  }

**Comment by ljharb** [comment]
You'll need to file an issue on that project's repo; this repo is for the npm CLI itself.
