### ISSUE TITLE
[BUG]Error while installing react-currency-format

### ISSUE THREAD

**Issue by kehinsoft** [npm/cli#2418]
**Please I'm getting the below error while I'm trying to install react-currency-format in my react app inside VSCode. I tried to install another package and it worked. How do I resolve this issue? stuck for 3 days.**

PS C:\Users\Administrator\***> npm i react-currency-format
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: vmart-xpress@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14 || ^15.0.0-rc || ^15.0.0 || ^16.0.0-rc || ^16.0.0" from react-currency-format@1.0.0
npm ERR! node_modules/react-currency-format
npm ERR!   react-currency-format@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Administrator\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Local\npm-cache\_logs\2020-12-27T09_32_32_050Z-debug.log

**Comment by wraithgar** [comment]
Have you retried the command with either `--force` or `--legacy-peer-deps`?  The issue here is that there are irresolvable conflicts in the peer dependencies here, and npm@7 tries to install them now whereas npm@6 didn't.

If this still fails when using either of those flags, let us know.

**Comment by azedine-batouche** [comment]
use it like this: npm install react-currency-format --save --force

**Comment by xavleon** [comment]
This worked for me thank you

**Comment by swetasrinaidu** [comment]
> use it like this: npm install react-currency-format --save --force

Worked for me. Thanks

**Comment by Pavanviky** [comment]
will their be any problem if i use -save - force

**Comment by Victor-Malhotra** [comment]
> will their be any problem if i use -save - force

Yes the single dash would result in it not working and telling you those commands are not registered

**Comment by ljharb** [comment]
(That’s not a single dash, that’s a Mac autocorrecting two dashes to an em dash)

**Comment by Debbykalu** [comment]
I am having this same issue, even with the npm install react-currency-format --save --force there is still conflicts.

npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14 || ^15.0.0-rc || ^15.0.0 || ^16.0.0-rc || ^16.0.0 || ^17.0.0" from react-currency-format-latest@1.0.1

**Comment by akgagare** [comment]
yes even after using the --save --force facing the same issue
