### ISSUE TITLE
[BUG] Installable package not showing up on NPM

### ISSUE THREAD

**Issue by fireflysemantics** [npm/cli#2429]
https://www.npmjs.com/package/@fireflysemantics/material-base-module

It will install when running `npm i @fireflysemantics/material-base-module` but it is not showing up on the NPM site ...

**Comment by ljharb** [comment]
That link is showing up just fine for me.

**Comment by fireflysemantics** [comment]
Me too now.  It took about 2 hours before it showed up on NPM ... But it was immediately available for installation and it showed up in NPM search results.  

I guess we can close.  Might be worth checking into what is causing the latency.

I also just updated the minor version to 11.  When I search for the package on NPM the results show that it has been updated to 11, but when I click on the link, the main page still shows version 5.  This happens after durations of 10-15 minutes.  I have not monitored how much longer it takes.

**Comment by wraithgar** [comment]
Sorry to hear that your publishes are taking awhile to show up on the registry and website.

For issues related to the registry/website itself, please use https://www.npmjs.com/support to open a support ticket.  The issue tracker in this repo is only for CLI related/specific bugs.
