### ISSUE TITLE
[BUG] Potential error in messaging for `npm org`

### ISSUE THREAD

**Issue by snuggs** [npm/cli#2432]
### Current Behavior:
@ruyadorno @darcyclarke @nlf pardon the nit. Was doing some package housekeeping and noticed something that just looks a little off with the messaging. _"**You now 3** members"_? 🤔

Also wondering how the tests from #2353 are passing. 

Thanks in advance!  And let me know where I can help. ❤️ tests🙏🏽 

See below: 

### Expected Behavior:
_"Added bar to foo. You now **have** 1 member in this org."_

### Steps To Reproduce:

```bash
npm org set foo @bar admin
```

### Environment:

- OSX
- Node: 14.15.3
- npm: 6.14.10

![Capture d’écran 2021-01-01 à 01 06 43](https://user-images.githubusercontent.com/38223/103434359-697bcf80-4bce-11eb-805b-dc925b3157cf.png)

**Comment by alexa2140** [comment]
Are these issues about [websites](https://apksclub.com/netboom-mod-apk/)?

**Comment by YC** [comment]
I think https://github.com/npm/cli/pull/2353/files#diff-6853bcc6c7c067c12466503a6b1610bed8dddd128537a07fc6c90e2bda154c78R78 (https://github.com/npm/cli/commit/996a2f6b130d6678998a2f6a5ec97d75534d5f66#) fixed this problem.

**Comment by snuggs** [comment]
@YC thanks!
