### ISSUE TITLE
--ignore-scripts flag is being ignored by npm ci

### ISSUE THREAD

**Issue by satbirbains** [npm/cli#2434]
### Current Behavior:
npm ci is not respecting the '--ignore-scripts' flag. The postintsall script is being executed regardless.

### Expected Behavior:
I would expect 'npm ci --ignore-scripts' to behave in the same way as 'npm install --no-scripts' and not run any scripts. The two commands worked in the same way in 6.14.9 but no longer after updating to 7.3.0.

### Steps To Reproduce:

1. Create a package.json with postinstall:"echo running post install"
2. Run npm install --ignore-scripts
3. Run npm ci --ignore-scripts
3. Post install script has been executed once but should not have executed at all.

### Environment:
- OS: Debian 10
- Node: 15.5.0
- npm: 7.3.0

**Comment by wraithgar** [comment]
The cli/ci.js file is missing the same constraints that cli/install.js has,  cf:

https://github.com/npm/cli/blob/latest/lib/ci.js#L41
and
https://github.com/npm/cli/blob/latest/lib/install.js#L42

**Comment by wraithgar** [comment]
Fixed in `v7.4.0`

**Comment by jedahan** [comment]
Has this been backported to v6 ?

**Comment by ljharb** [comment]
i don't believe so, and if not, it's not likely to, since v8 is already out.

**Comment by wraithgar** [comment]
This shouldn't need to? It was working in v6 according to the OP
