### ISSUE TITLE
[BUG] npm link and npm package aliasing don't work well together

### ISSUE THREAD

**Issue by Stvad** [npm/cli#2458]
### Current Behavior:
When I have a package installed under alias
```
 "foo": "npm:@scope/bar^0.1.0",
```

**Option 1**:
When I do `npm link` in the package `@scope/bar` and then do `npm link foo` in target package I get

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@scope%2fbar - Not found
npm ERR! 404
npm ERR! 404  '@scope/bar*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Option 2**:
If I have target and `@scope/bar` side by side and do `npm link ../bar` - npm will create `@scope` directory in `node_modules` and link `bar` inside it to the directory specified in command, but would not touch the `foo` directory in `node_modules`

### Expected Behavior:
`foo` directory in `node_modules` links to the directory containing `@scope/bar` package

### Environment:
- OS: macOS 10.15.7
- Node: v15.5.0
- npm: 7.3.0

**Comment by darcyclarke** [comment]
@Stvad `npm link` doesn't work this way today but you could propose changes over in our [RFCs](https://github.com/npm/rfcs) repo.
