### ISSUE TITLE
[BUG] 7.x breaks git behaviour (caches remote repositories?)

### ISSUE THREAD

**Issue by alexhochreiter** [npm/cli#2465]
### Current Behavior:

When working with a simple git dependency, like this:
```
{
  "dependencies": {
    "my-package": "git+ssh://git@gitlab.com:mygroup/mypackage.git"
  }
}
```
`npm 6.x` used to always pull the latest version/commit of the dependency git repository specified when (re-)installing the packages with `npm i` when there was a `rm -rf node_modules` beforehand.
Now with `npm 7.x` it appears the repository is not pulled, but served from a cache instead.
I could not find anything mentioning this in the changelogs.

### Expected Behavior:
Expected npm to pull/clone from dependency git repo when no `node_modules` dir is present.
Or have some official way to tell npm to re-fetch/pull a git repository dependency.

### Steps To Reproduce:
When working with a simple git dependency, like this:
```
{
  "dependencies": {
    "my-package": "git+ssh://git@gitlab.com:mygroup/mypackage.git"
  }
}
```
1. Start with a clean project (no `node_modules` dir yet).
2. Install dependencies, like the git repo mentioned above, with `npm i`
3. Git-Repository is pulled and installed correctly.
4. Make a new commit in the git repository of the git-repo-dependency.
5. delete `node_modules` *1
6. reinstall dependencies with `npm i`
7. old version of git-dependency without the new commit from 4. is installed

*1 was a workaround for npm never re-pulling from dependency git repos upon re-installing for `6.x` when the package was already in the `node_modules` dir.

### Environment:
- OS: Fedora 33
- Node: v14.15.1
- npm: 7.3.0

**Comment by wraithgar** [comment]
This was fixed [here](https://github.com/npm/arborist/pull/211) and was included in `v7.5.1`.

If this is still not working, feel free to update the `Environment` section with the new npm version you were using and re-open the issue.
