### ISSUE TITLE
[BUG] Packages with Native Addon Modules not being installed in Electron Main Process

### ISSUE THREAD

**Issue by hrueger** [npm/cli#2469]
### Current Behavior:
My application needs to install packages at runtime. The code I'm using is the following:
```TypeScript
import * as npm from "npm";

npm.load({
    prefix: config.path,
    logstream: npmProgressbarParser((progress) => {
        // do something with the progress
    }),
}, () => {
    npm.commands.install([packageName], (error) => {
        if (error) {
            // it worked
            reject(error);
        } else {
            // it worked
            resolve();
        }
    });
});
```
The `npmProgressbarParser` looks like this:
```TypeScript
const npmProgressbarParser = (cb: (p: number) => void) => {
    let progress = 0;
    return new Duplex({
        read: () => undefined,
        write: (chunk: any,
            encoding: BufferEncoding, callback: (error?: Error | null) => void) => {
            const line = chunk.toString() as string;
            if (line && line.startsWith("[")) {
                const done = /\[(.*?)(\.*)\]/g.exec(line)[1];
                const newProgress = ((20 - done.split(".").length) / 20) * 100;
                if (progress !== newProgress) {
                    cb(progress);
                    progress = newProgress;
                }
            }
            callback();
        },
    });
};
```
But it is only used to parse the progress bar output as I didn't find any api option for that.

The installation is working fine if I run the script with `ts-node myScript.ts`. The package is installed into the correct folder. However, when this function is run inside an Electron Main Process, only packages without native addon modules are installed. If a package has a dependencie which requires a native addon module to be rebuilt with node gyp, it does not work.

The logs of the script if it is run "standalone" look like this:
```
> midi@1.0.0 install C:\Users\Hannes\AppData\Roaming\glue\data\features\node_modules\@hrueger\glue-feature-simple-midi\node_modules\midi
> node-gyp rebuild


C:\Users\Hannes\AppData\Roaming\glue\data\features\node_modules\@hrueger\glue-feature-simple-midi\node_modules\midi>if not defined npm_config_node_gyp (node "A:\_Source\GLUE\Glue\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Hannes\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "-m" hinzufügen.
  RtMidi.cpp
  input.cpp
  output.cpp
  midi.cpp
  win_delay_load_hook.cc
...
```
Note that `npm` outputs this to the console directly, it is not coming from `console.log` calls in my script. Once the rebuild is done, the callback function of `npm.commands.install` is called and the package has been installed correctly.

However, when run in the electron main process, the output looks like this:
```
> midi@1.0.0 install C:\Users\Hannes\AppData\Roaming\glue\data\features\node_modules\@hrueger\glue-feature-simple-midi\node_modules\midi
> node-gyp rebuild
```
And then the callback is called. So there is no node-gyp rebuild happening. The folder where the package was supposed to be installed to is empty.

Any idea?

### Expected Behavior:
It should work inside the electron main process just like "standalone".

### Steps To Reproduce:
If you need a test repo with this issue, just tell me.

### Environment:
Standalone:
- OS: Windows 10 20H2
- Node: `v14.13.0`
- npm: `v6.14.10`

Inside Electron:
- Node: `v12.18.3`
- npm: `v6.14.10`

**Comment by hrueger** [comment]
Any update on this? Could this be an electron-specific problem?

**Comment by ljharb** [comment]
What happens with npm 7?

**Comment by hrueger** [comment]
Thanks for the reply, I'll check that.
Is there any docs how to use the npm 7 api programatically?
My old implementation seems to not work anymore. As far as I can tell, the `npm.load(config, cb)` function changed to `npm.load(cb)`?

**Comment by ljharb** [comment]
The programmatic npm API hasn't followed semver nor been recommended since like npm 3, as far as I'm aware - i'd suggest shelling out to the `npm` cli.

**Comment by hrueger** [comment]
Thanks, unfortunately, I won't be able to just run `npm i` in a child process as the end user won't have NodeJS installed. Maybe I can somehow require the cli bin script and "fake" the cli arguments. I'll look into that tomorrow.

**Comment by ljharb** [comment]
If they don't have node installed, then how can your node code work and access the `npm` programmatic API? If the API is available, so's the CLI.

**Comment by hrueger** [comment]
The application runs inside ElectronJS (https://www.electronjs.org/). The Electron binary includes a chromium framework as well as a node.js runtime. 
Maybe I can run execute the script by calling it from inside Electron using its absolute path. I'll check tomorrow.

**Comment by hrueger** [comment]
Ok, I did some tests and calling `npm install` with the `child_process` module did not work great/at all. While running in development mode, it works fine, but once the app is packaged, the child process immediately exits. I'd need some more time to figure out, why that happens.
However, I'd really prefer requireing the module and running it without involving child processes. I also need to get the current installation process status, which I previously got by parsing the stdout (counting the different characters the progressbar consists of). This worked in dev mode, but not in packaged mode. 

As arguments I need to specify a registry and a folder prefix. Do you have any idea how I can accomplish that?
Are there any plans for a JS API? Or should I use Arborist directly?

**Comment by hrueger** [comment]
I just tried using Arborist directly and now I can see an error in the terminal: It says that `the command node-gyp could not be located`. Here's the error message (it's in German as that's the language windows is set to):
```
Unhandled Rejection at: Promise Promise {
  <rejected> Error: command failed
      at ChildProcess.<anonymous> (C:\Users\Hannes\AppData\Local\Programs\glue\resources\app.asar\node_modules\@npmcli\promise-spawn\index.js:64:27)
      at ChildProcess.emit (events.js:315:20)
      at maybeClose (internal/child_process.js:1021:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
    cmd: 'C:\\WINDOWS\\system32\\cmd.exe',
    args: [
      '/d',
      '/s',
      '/c',
      'prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild'
    ],
    code: 1,
    signal: null,
    stdout: '',
    stderr: 'Der Befehl "node-gyp" ist entweder falsch geschrieben oder\r\n' +
      'konnte nicht gefunden werden.\r\n',
    event: 'install',
    script: 'prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild',
    pkgid: '@serialport/bindings@8.0.8',
    path: 'C:\\Users\\Hannes\\AppData\\Roaming\\glue\\data\\features\\node_modules\\@serialport\\bindings'
  }
} reason: Error: command failed
    at ChildProcess.<anonymous> (C:\Users\Hannes\AppData\Local\Programs\glue\resources\app.asar\node_modules\@npmcli\promise-spawn\index.js:64:27)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  cmd: 'C:\\WINDOWS\\system32\\cmd.exe',
  args: [
    '/d',
    '/s',
    '/c',
    'prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild'
  ],
  code: 1,
  signal: null,
  stdout: '',
  stderr: 'Der Befehl "node-gyp" ist entweder falsch geschrieben oder\r\n' +
    'konnte nicht gefunden werden.\r\n',
  event: 'install',
  script: 'prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild',
  pkgid: '@serialport/bindings@8.0.8',
  path: 'C:\\Users\\Hannes\\AppData\\Roaming\\glue\\data\\features\\node_modules\\@serialport\\bindings'
}
```

**Comment by hrueger** [comment]
Closing this as it will be tracked in npm/arborist/issues/218
