### ISSUE TITLE
[BUG] <Documentation not sync with v7>

### ISSUE THREAD

**Issue by ghost** [npm/cli#2472]
Docs are not updated with newest functionality when generating models.

"Interface" now changed to "type".  Docs should be updated.
Check example below.

By syncing with backend, the models are now updated on the form
// Model
export type Order {
    id?: number;
    quantity?: number;
    status?: Order.status;
}

By reading the docs, the models are supposed to be
// Model
export interface Order {
    id?: number;
    quantity?: number;
    status?: Order.status;
}

**Comment by ljharb** [comment]
This seems like a question about a specific package, rather than about npm itself. npm doesn’t create “models”. Happy to reopen if I’m mistaken.
