### ISSUE TITLE
[BUG] publishing: --registry flag is overridden by .npmrc for scoped packages

### ISSUE THREAD

**Issue by JeremyLoy** [npm/cli#2473]
### Current Behavior:
Given you are working on package `@MyScope:MyPackage`
and
Given the following `.npmrc`:

```
@MyScope:registry=AAAAA
```

Run the following command:
```
npm publish --registry=BBBBBB
```

Observe that the `npm` cli makes a PUT request to `AAAAA`

### Expected Behavior:
The `npm` cli should instead honor the explicit `--registry` flag and publish to `BBBBB`

### Steps To Reproduce:
see above

### Environment:
Tested both
```
- OS: macOS Catalina 10.15.17
- Node: 12.16.1
- npm: 6.13.4
```
and 
```
- OS: macOS Catalina 10.15.17
- Node: 15.5.1
- npm: 7.3.0
```

**Comment by JeremyLoy** [comment]
Note: this may also affect 7.x, I haven't tested it myself as no project I am on uses that version of the CLI

**Comment by ljharb** [comment]
Given that 6 is unlikely to receive any fixes at this point, it'd be helpful if you could test with v7 latest.

**Comment by JeremyLoy** [comment]
Tested with the following:
```
OS: macOS Catalina 10.15.17
Node: 15.5.1
npm: 7.3.0
```

The issue still persists

**Comment by ljharb** [comment]
Thanks, v7.4.0 is out as well but that’s a useful data point.

**Comment by wraithgar** [comment]
There is no way for the cli to know if `registry` in its config was set through the cli or from an npmrc file. The scope-specific registry is a setting that overrides `registry` in the config.

In order for you to override a scope-specific registry you will have to do it via that scope-specific setting, i.e.

```sh
$ npm publish --@MyScope:registry=BBBB
```

```sh
~/D/n/foo $ npm config list  --@wraithgar:registry=asdf|grep wraithgar:registry
; @wraithgar:registry = "https://npm.pkg.github.com" ; overridden by cli
@wraithgar:registry = "asdf"
