### ISSUE TITLE
[BUG] updating npm in Docker fails with EISDIR

### ISSUE THREAD

**Issue by targos** [npm/cli#2476]
### Current Behavior:

Running `npm i -g npm@7` in a Dockerfile fails with EISDIR, trying to use `fs.copyFile` on `/usr/local/lib/node_modules/npm`, which is a directory.

### Expected Behavior:

It should be possible to update npm in a Dockerfile

### Steps To Reproduce:

1. Create a Dockerfile:

```
FROM node:15.5.1
RUN npm i -g npm@7
```

1. Run `docker build .`

1. Output:

```
# docker build .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM node:15.5.1
15.5.1: Pulling from library/node
Digest: sha256:6498b11c4f3aa5288518a6b84f33981e6470c7068c1b8fa5b48f649937d6cc40
Status: Downloaded newer image for node:15.5.1
 ---> 8bc1fccfb494
Step 2/2 : RUN npm i -g npm@7
 ---> Running in 66566a21722d
npm notice 
npm notice New minor version of npm available! 7.3.0 -> 7.4.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.4.0>
npm notice Run `npm install -g npm@7.4.0` to update!
npm notice 
npm ERR! code EISDIR
npm ERR! syscall copyfile
npm ERR! path /usr/local/lib/node_modules/npm
npm ERR! dest /usr/local/lib/node_modules/.npm-i9nnxROI
npm ERR! errno -21
npm ERR! EISDIR: illegal operation on a directory, copyfile '/usr/local/lib/node_modules/npm' -> '/usr/local/lib/node_modules/.npm-i9nnxROI'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-12T08_46_46_463Z-debug.log
The command '/bin/sh -c npm i -g npm@7' returned a non-zero code: 235
```

**Comment by Lishenga** [comment]
i encounter the same bug with docker. Any solutions available?

**Comment by mnr73** [comment]
user lts tag

**Comment by mnr73** [comment]
use lts tag

**Comment by darcyclarke** [comment]
@targos thanks for flagging this. We've queued up a release to resolve this ([`v7.4.2`](https://github.com/npm/cli/releases/tag/v7.4.2) should resolve)

**Comment by ghost** [comment]
Using [`docker` v20.10.11](https://github.com/moby/moby/releases/tag/v20.10.11) and [`npm` v7.5.2](https://github.com/npm/cli/releases/tag/v7.5.2) (installed from a Debian bookworm host and Debian bullseye container respectively) it looks like this error is replicable:

```
npm ERR! code EISDIR
npm ERR! syscall copyfile
npm ERR! path /chronophage/assets/node_modules/adjust-sourcemap-loader
npm ERR! dest /chronophage/assets/node_modules/.adjust-sourcemap-loader-k6PZhyAT
npm ERR! errno -21
npm ERR! EISDIR: illegal operation on a directory, copyfile '/chronophage/assets/node_modules/adjust-sourcemap-loader' -> '/chronophage/assets/node_modules/.adjust-sourcemap-loader-k6PZhyAT'
```

And one additional finding: this occurred when a local `node_modules` directory from the working directory was copied into the container before the `docker build` took place.  The error **does not** occur if that local `node_modules` directory is removed.

**Comment by ljharb** [comment]
What about with npm 8?

**Comment by saper44rus** [comment]
Same problem

**Comment by spookyuser** [comment]
Same

**Comment by jiahui-xin** [comment]
same
