### ISSUE TITLE
[BUG] npm ERR! cb() never called!

### ISSUE THREAD

**Issue by SDESkowronski** [npm/cli#2489]
### Current Behavior:
I ran "npm i" AND got an error "ERR! cb() never called!"

Here is what it shows on my windows command line:

  C:\repos\my-repo>npm i
  npm ERR! cb() never called!

  npm ERR! This is an error with npm itself. Please report this error at:
  npm ERR!     <https://npm.community>

  npm ERR! A complete log of this run can be found in:
  npm ERR!     C:\Users\my-name\AppData\Roaming\npm-cache\_logs\2021-01-14T02_37_07_786Z-debug.log

### Expected Behavior:
Normally this just works, it just installs and I get no error.

### Steps To Reproduce:
Sorry but "nmp i" is all the help I can give you without giving you access to my repository

### Environment:
Windows 10 Pro
  npm: '6.14.8',
  ares: '1.16.1',
  brotli: '1.0.9',
  cldr: '37.0',
  icu: '67.1',
  llhttp: '2.1.3',
  modules: '83',
  napi: '7',
  nghttp2: '1.41.0',
  node: '14.15.1',
  openssl: '1.1.1g',
  tz: '2020a',
  unicode: '13.0',
  uv: '1.40.0',
  v8: '8.4.371.19-node.17',
  zlib: '1.2.11'

**Comment by SDESkowronski** [comment]
I re-ran it and it worked the second time.

**Comment by liaoliaots** [comment]
same issue

**Comment by darcyclarke** [comment]
https://github.com/npm/cli/wiki/%22cb()-never-called%3F--I'm-having-the-same-problem!%22
