### ISSUE TITLE
[BUG] cb() never called!

### ISSUE THREAD

**Issue by Omotayewo** [npm/cli#2493]
# What / Why
I wanted to create-react-app with npx and some way through the installation, it stopped and gave the 'cb() never called error'

### Current Behavior
Ran the command twice which gave the error at both times

### Steps to Reproduce
npx create-react-app profile

### Expected Behavior
It should create a react app with directories and files

###Environment
node: v14.11.0
npm: 6.14.8
Windows10

**Comment by liaoliaots** [comment]
same, when I install @vue/cli -g

**Comment by GSMare** [comment]
I have the same issue.
![npmErr](https://user-images.githubusercontent.com/39889428/104698798-8f4ebb80-571a-11eb-8668-8fcc25dbb2ef.JPG)

I have tried to clear npm cache and re-installed node.

**Comment by darcyclarke** [comment]
Please review #417 & [this doc](https://github.com/npm/cli/wiki/%22cb()-never-called%3F--I'm-having-the-same-problem!%22).
