### ISSUE TITLE
npm error: cb() never called!

### ISSUE THREAD

**Issue by MichaelGreisberger** [npm/cli#2496]
got this error while installing vue-google-charts with the following command: npm i vue-google-charts
was asked to post this here.

log:
[2021-01-15T19_23_15_753Z-debug.log](https://github.com/npm/cli/files/5822577/2021-01-15T19_23_15_753Z-debug.log)

hope this helps

**Comment by darcyclarke** [comment]
Please review #417 & [this doc](https://github.com/npm/cli/wiki/%22cb()-never-called%3F--I'm-having-the-same-problem!%22). For future reference, we ask that people fill out/use one of our [issue templates](https://github.com/npm/cli/issues/new/choose) when filing new tickets.
