### ISSUE TITLE
[BUG] NPM terminal command broken but not node

### ISSUE THREAD

**Issue by kxmndz** [npm/cli#2503]
### Current Behavior:
NPM terminal command is broken, but Node isn't.
![image](https://user-images.githubusercontent.com/71072915/104860264-843b9b80-5965-11eb-87a0-f8e21deed7bb.png)

When I run a node app from a Git bash, it throws this
```
FATAL ERROR: Zone Allocation failed - process out of memory
 1: 00007FF710A6540F v8::internal::Isolate::ArchiveSpacePerThread+4447
 2: 00007FF710A002E6 DSA_meth_get_flags+65078```

But in my WebStorm terminal, it shows this
```
Process finished with exit code -1073740791 (0xC0000409)```

And nothing happens. I am on Windows 10 Home 64-bit (10.0, Build 19042) with 12 GB of RAM. RAM usage is around ~80 MB for the Node runtime, which is normal for the program I'm running.

I've tried reinstalling Node and NPM, rolling back to old versions, restarting my PC after every time. The problem persists even with older versions of node (I tested 15.6.0, 14.15.4, and 9.0.0)

If it helps, this is the program I'm running:
[program.zip](https://github.com/npm/cli/files/5827167/program.zip)

### Expected Behavior:
Node app runs normally and continues to run until cancelled by the user

### Steps To Reproduce:
1. Install/log in to the Discord app if not already present
1. Unpack program.zip
2. `cd` into the folder
1. Run `npm i` (note: I can't do this because my `npm` terminal command is unresponsive)
2. Run `npm run start`
3. This should output `RPC set` and wait until you cancel it, but on my system it crashes itself after a few seconds.

### Environment:
- OS: Windows 10 64-bit (10.0, Build 19042)  
- Node: 15.6.0  
- npm: `npm -v` is unresponsive

**Comment by kxmndz** [comment]
I just did some more testing, using this *very* small program:
```js
console.log('Hello World!');

setTimeout(() => {
    console.log('timeout')
}, 2000);

console.log('done');
```
It crashes before it logs 'timeout', with the same exit code as before (-1073740791). Playing around with the timing, it logs and finishes properly if the delay is changed to 1200 ms, but things get weird at 1250 ms: it logs 'timeout' but crashes with the exit code -1073740791, and at 1270 ms it just crashes without logging 'timeout'.

**Comment by darcyclarke** [comment]
@kxmndz do you happen to know which versions of `npm` were being run with the older versions of `node` you tried?

**Comment by kxmndz** [comment]
@darcyclarke sorry but no, I didn't check. The problem fixed itself after updating Windows and reinstalling both node and npm though.
