### ISSUE TITLE
[BUG] Prune command adds packages?

### ISSUE THREAD

**Issue by SpenceUK** [npm/cli#2509]
### Current Behavior:
running npm prune --json shows that it is adding packages.  The documentation does not explain why. It states that this command is to remove extraneous packages not listed in package json file.

My question is for an explanation as to why it is adding additional packages? 
If it should not then this is a bug.  If it is the correct behaviour can it be explained and also added to the prune documentation please.

Thank you.

### Expected Behavior:
I would expect this command to only remove extraneous packages and to add nothing.

### Steps To Reproduce:
Command and output below:

`npm prune --dry-run --json`

`
npm WARN bootstrap@4.5.3 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.5.3 requires a peer of popper.js@^1.16.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@6.0.0 requires a peer of eslint-plugin-import@^2.22.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@6.0.0 requires a peer of eslint-plugin-jsx-a11y@^6.3.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-import@2.9.0 requires a peer of eslint@2.x - 4.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-jsx-a11y@6.2.1 requires a peer of eslint@^3 || ^4 || ^5 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-watch@5.1.2 requires a peer of eslint@>=4 <6.0.0 but none is installed. You must install peer dependencies yourself.

{
  "added": [
    {
      "action": "add",
      "name": "babel-plugin-jest-hoist",
      "version": "26.6.2",
      "path": "node_modules/react-scripts/node_modules/babel-plugin-jest-hoist"
    },
    {
      "action": "add",
      "name": "babel-preset-jest",
      "version": "26.6.2",
      "path": "node_modules/react-scripts/node_modules/babel-preset-jest"
    }
  ],
  "removed": [],
  "updated": [],
  "moved": [],
  "failed": [],
  "warnings": [
    "bootstrap@4.5.3 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.",
    "bootstrap@4.5.3 requires a peer of popper.js@^1.16.1 but none is installed. You must install peer dependencies yourself.",
    "eslint-config-react-app@6.0.0 requires a peer of eslint-plugin-import@^2.22.0 but none is installed. You must install peer dependencies yourself.",
    "eslint-config-react-app@6.0.0 requires a peer of eslint-plugin-jsx-a11y@^6.3.1 but none is installed. You must install peer dependencies yourself.",
    "eslint-plugin-import@2.9.0 requires a peer of eslint@2.x - 4.x but none is installed. You must install peer dependencies yourself.",
    "eslint-plugin-jsx-a11y@6.2.1 requires a peer of eslint@^3 || ^4 || ^5 but none is installed. You must install peer dependencies yourself.",
    "eslint-watch@5.1.2 requires a peer of eslint@>=4 <6.0.0 but none is installed. You must install peer dependencies yourself."
  ],
  "audit": {
    "actions": [],
    "advisories": {},
    "muted": [],
    "metadata": {
      "vulnerabilities": {
        "info": 0,
        "low": 0,
        "moderate": 0,
        "high": 0,
        "critical": 0
      },
      "dependencies": 2510,
      "devDependencies": 782,
      "optionalDependencies": 32,
      "totalDependencies": 3316
    }
  },
  "funding": "151 packages are looking for funding",
  "elapsed": 10742
}
`

### Environment:

- OS: Macbook Pro Big Sur v11.1
npm: '6.13.4',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  llhttp: '2.0.1',
  modules: '72',
  napi: '5',
  nghttp2: '1.40.0',
  node: '12.14.1',
  openssl: '1.1.1d',
  tz: '2019c',
  unicode: '12.1',
  uv: '1.33.1',
  v8: '7.7.299.13-node.16',
  zlib: '1.2.11'
-->

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
