### ISSUE TITLE
[BUG] NPM audit fix --prefix not respected in combination with dryrun

### ISSUE THREAD

**Issue by vo55** [npm/cli#2512]
### Current Behavior:
Running `npm audit fix --dry-run --json` from the same directory as the package.json and package-lock.json works fine, going into another directory (e.g. one hierarchy level up) and running `npm --prefix ./<repo_path>/package-lock.json audit fix --dry-run --json` results in an  EEXIST: file already exists, mkdir '<package-lock-path>' 

### Expected Behavior:
The dry run should run for the file specified in the prefix.

### Steps To Reproduce:
Reproduce mentioned steps above with npm 6.14.8

### Environment:
npm 6.14.8
node v14.15.1
OS Win10

**Comment by vo55** [comment]
nevermind, i just guess it would be a new feature and the prefix would have to be called with a directory instead of the file obviously.

**Comment by ljharb** [comment]
What happens with npm 7?
