### ISSUE TITLE
E405 - Method not allowed: Get https://registry.npmjs.org/newman

### ISSUE THREAD

**Issue by Qualityinmate** [npm/cli#2515]
Could not install newman using "npm install -g newman" in cmd

### Current Behavior:
E405 - Method not allowed: Get https://registry.npmjs.org/newman

### Expected Behavior:
Expecting newman to be installed on my machine.

### Environment:
node -v
v12.18.3
npm -v
6.14.6
<img width="1432" alt="Newman installation issue" src="https://user-images.githubusercontent.com/77757493/105252768-d0871580-5bc9-11eb-8612-c54bdb0ab6c7.png">
C:\Users\Mrkarri>npm install -g newman
npm ERR! code E405
npm ERR! 405 Method Not Allowed - GET https://registry.npmjs.org/newman/newman

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mrkarri\AppData\Roaming\npm-cache\_logs\2021-01-20T23_17_48_862Z-debug.log

**Comment by Qualityinmate** [comment]
Any update would be highly appreciated.

**Comment by darcyclarke** [comment]
Looks like you may have a registry configuration issue. Try running `npm config ls` to see if you've defined a registry/scope other then the defaults.

`npm install newman --registry=https://registry.npmjs.org` should work just fine...

Registry reference: https://registry.npmjs.org/newman/ 
npmjs.com reference: https://www.npmjs.com/package/newman
