### ISSUE TITLE
[BUG] preshrinkwrap, shrinkwrap and postshrinkwrap scripts are not executed

### ISSUE THREAD

**Issue by LeSuisse** [npm/cli#2520]
### Current Behavior:
With a `package.json` looking like that, `preshrinkwrap`, `shrinkwrap` and `postshrinkwrap` scripts are not executed when running `npm install`:

```json
{
  "name": "mypackage",
  "version": "1.0.0",
  "dependencies": {
    "somedep": "^1.0.0"
  },
  "devDependencies": {},
  "scripts": {
    "preshrinkwrap": "mypreshrinkwrapscript",
    "shrinkwrap": "myshrinkwrapscript",
    "postshrinkwrap": "mypostshrinkwrapscript"
  }
}
```

### Expected Behavior:
 `preshrinkwrap`, `shrinkwrap` and `postshrinkwrap` scripts to be executed when running `npm install` as described in the documentation https://docs.npmjs.com/cli/v7/configuring-npm/package-locks

Note that this behavior works on npm 6.x.

### Environment:
Node: 15.6.0
npm: 7.4.0

**Comment by wraithgar** [comment]
Those events went away in `npm7` because there is no specific `shrinkwrap` event anymore.   The cli command either renames the package-lock, or generates it and saves it with the shrinkwrap name.

**Comment by dgreif** [comment]
@wraithgar Is there any new hook available to detect general changes to package-lock, regardless of how they happen (install, uninstall, update, etc)?  We used to use `postshrinkwrap` to kick off our license check, but have to do this in a custom `npm` script with npm@8.

**Comment by wraithgar** [comment]
No, but we know there is a need for it.  It's currently an item in our [backlog](https://github.com/npm/statusboard/issues/399).
