### ISSUE TITLE
[BUG] missing docs around package-lock.json inside the /node_modules/ dir

### ISSUE THREAD

**Issue by Pomax** [npm/cli#2521]
### Current Behavior:
I can't for the life of me find something that lets me let you know about docs problems, as the [official list of options](https://github.com/npm/cli/issues/new/choose) has nothing relating to docs issues (only a way to open the docs site), so I'm filing this as an npm bug instead: running `npm install` generates a `package-lock.json` file not just in the project dir, but also in the `./node_modules/` dir.

The docs don't mention (1) that it'll do this, (2) what the purpose of this file is, and (3) why and how it's different (because it's about half the size as the regular package-lock.json file).

### Expected Behavior:
No `package-lock.json` gets written to `./node_modules/`

### Steps To Reproduce:

Run `npm install`

**Comment by valtlai** [comment]
@Pomax, see [docs/content/configuring-npm/package-lock-json.md#hidden-lockfiles](../blob/latest/docs/content/configuring-npm/package-lock-json.md#hidden-lockfiles)

**Comment by Pomax** [comment]
Handy: but where is that found on the actual site? It's not under https://docs.npmjs.com/cli/v7/configuring-npm/package-json nor is it under https://docs.npmjs.com/cli/v7/using-npm/config, so even though it looks like that information exists, it's basically not discoverable.

**Comment by valtlai** [comment]
It seems it has now been published on the actual site: https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#hidden-lockfiles

**Comment by Pomax** [comment]
fantastic, then that closes this issue =)
