### ISSUE TITLE
[BUG] npm ci --dry-run deletes node_modules folders

### ISSUE THREAD

**Issue by ASDFGerte** [npm/cli#2524]
### Current Behavior:
Executing `npm ci --dry-run` deletes all folders in `node_modules`.

### Expected Behavior:
Optimally, just the text output, as `--dry-run` describes, or an error, that it's incompatible with `npm ci`.

### Environment:
- OS: Windows 7
- Node: 15.6.0
- npm: 7.4.0

**Comment by darcyclarke** [comment]
@ASDFGerte I just tried this with the latest v7 (ie. `npm i -g npm@7`) & could not replicate. Can you try installing the latest version & trying again? If you're still experiencing this issue, I'll reopen.

**Comment by dave-kennedy** [comment]
@darcyclarke this is still happening on npm version 9.2.0.
