### ISSUE TITLE
[BUG] npm 7.x ignores publishConfig.registry

### ISSUE THREAD

**Issue by MikaelX** [npm/cli#2525]
**Current Behavior:**
npm publish does not follow publishConfig.registry, if registry is .npmrc it will try to publish to that, if not npm.org.

**Expected Behavior:**
npm publish publish to defined publishConfig.registry as it did in 6.x.

**Steps To Reproduce:**
Install npm@7
Set publishConfig.registry IE: "publishConfig": { "registry": "https://..." }
Run npm publish
Environment:
OS: Mac OS BigSur
Node: 15.4.0
npm: 7.4.3

Same bug as 
[Bug 1937](https://github.com/npm/cli/issues/1937)

Reverting back to npm@6 will solve the issue

**Comment by wraithgar** [comment]
#1937 has been fixed, and the related `ENEEDAUTH` bug is tracked in https://github.com/npm/cli/issues/2567 and will be closed by https://github.com/npm/cli/pull/2602
