### ISSUE TITLE
[BUG] <title>npm ERR! cb() never called!

### ISSUE THREAD

**Issue by AsherZEngel** [npm/cli#2533]
# What / Why

> npm ERR! cb() never called!

## When

* whenever I do npx create-react-app my-app

## Where

* git/bash & Windows Command Prompt
* I'm using node -v14.15.4
* npm -v6.14.10, -v6.14.11

### Current Behavior

* the terminal says it's installing the app, it creates the files, then it gives me the npm ERR message, then it deletes all the files it created.

### Steps to Reproduce

* when I type npx create-react-app my-app

### Expected Behavior

* it should create a new app

## Who

* @AsherZEngel

## References

* n/a

*I am new to the terminal, reporting bugs, and web dev in general. is it helpful to submit the debug log? if so how do I do that?
Any guidance in this area would be really helpful. Thanks! @<AsherZEngel> <asherzelig501@gmail.com>

**Comment by SuryaSachan** [comment]
https://github.com/npm/cli/issues/2555
I faced the same issue, It worked for me by updating npm.
try the following command
npm install -g npm@latest
