### ISSUE TITLE
[Typo] npm update -h update is spelled wrong

### ISSUE THREAD

**Issue by Totoro700** [npm/cli#2535]
To reproduce:
Open `cmd` and type `npm update -h` and the last line which is:
```
aliases: up, upgrade, udpate
```
which "udpate" should be "update":
```
aliases: up, upgrade, update
```

Whole output:
```
npm update [-g] [<pkg>...]

aliases: up, upgrade, udpate
```

to:

```
npm update [-g] [<pkg>...]

aliases: up, upgrade, update
```

![image](https://user-images.githubusercontent.com/68616592/105654083-e3783f00-5e82-11eb-8c86-231871fa1527.png)

**Comment by ljharb** [comment]
This is very intentional, to help people that misspell it.
