### ISSUE TITLE
“npm install” error on an Azure App / Web Service: EPERM: operation not permitted, lchown

### ISSUE THREAD

**Issue by nmvega** [npm/cli#2540]
Hello Friends:

- `npm version: 6.14.8`
- `node version: 12.19.0 `
- `O/S: Linux / Debian`
- `Platform: Azure App / Web Service`

On a `Linux` `Azure App / Web Service` configured for `Node 12 LTS`, after uploading code assets to `/home/site/wwwroot/`, which includes a `package.json` file, I run `npm install` as `root`. I get the exception shown further below.

This same exception happens across two different `Azure App / Web Services`, one for a `UI` and another for a `API` (so two different code-sets). But the error-pattern is the same:

It cannot change the ownership of a directory beneath `/home/site/wwwroot/node_modules/[...]/build-optimizer/node_modules/.bin/`, but only because the `.../.bin/` sub-directory itself never gets created.

Again, I'm running `npm install` as `root` in both cases.

Any ideas? Please see below and thank you.

```
24380 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
24381 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
24382 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
24382 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
24382 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
24382 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
24383 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.1 (node_modules/karma/node_modules/fsevents):
24384 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
24385 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
24385 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
24385 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
24385 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
24386 verbose stack Error: EPERM: operation not permitted, lchown '/home/site/wwwroot/node_modules/@angular-devkit/build-optimizer/node_modules/.bin/tsserver'
24387 verbose cwd /home/site/wwwroot
24388 verbose Linux 4.15.0-112-generic
24389 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
24390 verbose node v12.19.0
24391 verbose npm  v6.14.8
24392 error code EPERM
24393 error syscall lchown
24394 error path /home/site/wwwroot/node_modules/@angular-devkit/build-optimizer/node_modules/.bin/tsserver
24395 error errno -1
24396 error Error: EPERM: operation not permitted, lchown '/home/site/wwwroot/node_modules/@angular-devkit/build-optimizer/node_modules/.bin/tsserver'
24396 error  [OperationalError: EPERM: operation not permitted, lchown '/home/site/wwwroot/node_modules/@angular-devkit/build-optimizer/node_modules/.bin/tsserver'] {
24396 error   cause: [Error: EPERM: operation not permitted, lchown '/home/site/wwwroot/node_modules/@angular-devkit/build-optimizer/node_modules/.bin/tsserver'] {
24396 error     errno: -1,
24396 error     code: 'EPERM',
24396 error     syscall: 'lchown',
24396 error     path: '/home/site/wwwroot/node_modules/@angular-devkit/build-optimizer/node_modules/.bin/tsserver'
24396 error   },
24396 error   errno: -1,
24396 error   code: 'EPERM',
24396 error   syscall: 'lchown',
24396 error   path: '/home/site/wwwroot/node_modules/@angular-devkit/build-optimizer/node_modules/.bin/tsserver',
24396 error   parent: '@angular-devkit/build-optimizer'
24396 error }
24397 error The operation was rejected by your operating system.
24397 error It is likely you do not have the permissions to access this file as the current user
24397 error
24397 error If you believe this might be a permissions issue, please double-check the
24397 error permissions of the file and its containing directories, or try running
24397 error the command again as root/Administrator.
24398 verbose exit [ -1, true ]
```

**Comment by ljharb** [comment]
What happens with npm 7?

**Comment by nmvega** [comment]
> What happens with npm 7?

Hi. I didn't try that. I'd have to check with developers to see if that is supported. But I can try it for debug purposes since nothing is live. =:) I will try and post back.

**Comment by nmvega** [comment]
> What happens with npm 7?
@ljharb

Actually, `npm 7` isn't selectable as an option (on Azure App / Web Service). I can only select the version of `node` from `v12 LTS` (currently selected) to `v14 LTS (Early access)`, which may not be allowed.

**Comment by ljharb** [comment]
@nmvega Not sure what you mean by selectable - can you run `npm install -g npm@7` inside one of those node versions and then try?

**Comment by nmvega** [comment]
> @nmvega Not sure what you mean by selectable - can you run `npm install -g npm@7` inside one of those node versions and then try?

@ljharb I'll try that and post back. Thank you.

**Comment by nmvega** [comment]
> > @nmvega Not sure what you mean by selectable - can you run `npm install -g npm@7` inside one of those node versions and then try?
> 
> @ljharb I'll try that and post back. Thank you.

The upgrade command itself worked, but sadly the code can't use `npm7`.

**Comment by ljharb** [comment]
Why can't it? Code generally doesn't use npm at all.

**Comment by nmvega** [comment]
I agree 100%. You're correct, but it's not my environment to tinker with unfortunately (it's a client environment). I should have at least pasted the error before killing the session (sigh), but it basically bombed out on requiring something in between version 5 and version 6 (maybe it was `npm` itself). Unfortunately I can't tinker with it. ☹️

**EDIT**: Let me be more precise because I see your confusion: It was `npm install` that failed with the range requirement above. Sorry for not being precise earlier.

**Comment by ljharb** [comment]
I wouldn’t expect npm install to work on npm 5 or 6 and fail on 6 or 7. The error would be helpful.

**Comment by nmvega** [comment]
@ljharb This week when I get a moment, I'll stand up an identical environment and reproduce the error and paste it here. It only takes about 5 minutes. :relaxed:

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
