### ISSUE TITLE
React Native Text to Speech - Languages are not working on iOS device.

### ISSUE THREAD

**Issue by bhavinshah2016** [npm/cli#2547]
### Current Behavior:
In Online and Offline Mode in iOS devices below languages are not working. 
 Arabic, Urdu, Tamil, Malayāḷaṁ, Bengali 

Previously its was working on iOS devices.

### Expected Behavior:
In Online and Offline Mode in iOS devices, all the below-mentioned languages MUST be working. 
 Arabic, Urdu, Tamil, Malayāḷaṁ, Bengali

**Comment by ljharb** [comment]
Seems like an issue for React Native, not for npm.
