### ISSUE TITLE
SyntaxError: Unexpected token { when running npm run build

### ISSUE THREAD

**Issue by codinghedgehog-python** [npm/cli#2550]
### Current Behavior:
I'm trying to build my app with `npm run build` and even after updating versions of Node, npm and V8 I'm still facing
this issue.

### Expected Behavior:
Build directory created without errors.

### Steps To Reproduce:

ex. steps to reproduce the behavior:
1. `npm i --no-optional`
2.  `npm run build`
3.  Error output:

```
2:52 ~/blog/client $ npm run build
> client@0.1.0 build /home/markalexa/blog/client
> react-scripts build
/home/markalexa/blog/client/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
      } catch {
              ^
SyntaxError: Unexpected token {
```

### Environment:

- OS:  Linux 5.4.0-1020-aws  (ran on PythonAnywhere)
- Node: 8.6.0
- npm:  6.14
- V8:  6.0.287

**Comment by ljharb** [comment]
Your node version is too old to support the optional catch binding syntax react-scripts is using.

**Comment by codinghedgehog-python** [comment]
> Your node version is too old to support the optional catch binding syntax react-scripts is using.

Yep. I've already bumped up Node to 10.19 and it fixed the problem. Cheers !
