### ISSUE TITLE
Angular7-pubSub is not working with ng-packagr getting error .

### ISSUE THREAD

**Issue by dkatare** [npm/cli#2552]
**ERROR: : Unexpected value '[object Object]' imported by the module 'AppModule in C:/Project/TestAngularApplication/src/app/app.module.ts'. Please add a @NgModule annotation.** . This issue happened after import angular7-pubsub library.

### Current Behavior:
 getting above error after execute npm run packagr cmd

### Expected Behavior:
 after executing npm run packagr cmd application should convert into library 

### Steps To Reproduce:
1) Create angular application using angular 7.
2) Do configuration to convert angular application using ng-packagr(ng-packagr-5.5.0).
3) installed angular7-pubsub latest library and try to import in app.module.ts
4) execute npm run packagr.
5) you should see above mentioned error.

**Comment by darcyclarke** [comment]
Please file an issue with the specific package you're having problems with (ex. https://github.com/ng-packagr/ng-packagr)
