### ISSUE TITLE
[BUG] Impossible to link more than one local module dependency one at a time.

### ISSUE THREAD

**Issue by tristanls** [npm/cli#2554]
### Current Behavior:
Running `:/moduleA $ npm link moduleB` seems to attempt to install moduleA before linking moduleB. If moduleA depends on another local moduleC, linking moduleB into moduleA is impossible.

### Expected Behavior:
Running `:/moduleA $ npm link moduleB` links moduleB into `moduleA/node_modules/moduleB`. (just like `npm@6` does)

### Steps To Reproduce:
Overview:
1. Create moduleB and moduleC that are not in npm registry.
2. Use moduleB and moduleC as a dependency in moduleA.
3. Execute `:/moduleA $ npm link moduleB`. It will result in failing to find moduleC in npm registry.

Details:
```
$ ll
total 0
drwxr-xr-x  3 tristan  wheel   96 Jan 27 08:24 moduleA
drwxr-xr-x  3 tristan  wheel   96 Jan 27 08:23 moduleB
drwxr-xr-x  3 tristan  wheel   96 Jan 27 08:23 moduleC
```
```
$ cat moduleA/package.json 
{
  "name": "modulea",
  "version": "1.0.0",
  "dependencies": {
    "moduleb": "1.0.0",
    "modulec": "1.0.0"
  }
}
```
```
$ cat moduleB/package.json 
{
  "name": "moduleb",
  "version": "1.0.0"
}
```
```
$ cat moduleC/package.json 
{
  "name": "modulec",
  "version": "1.0.0"
}
```
```
$ cd moduleB/
:/moduleB $ npm link

up to date, audited 3 packages in 476ms

found 0 vulnerabilities
```
```
$ cd ../moduleC
:/moduleC $ npm link

up to date, audited 3 packages in 778ms

found 0 vulnerabilities
```
Please note that in the below step we attempt to link moduleB, but it complains about not finding _**moduleC**_.
```
$ cd ../moduleA
:/moduleA $ npm link moduleb
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/modulec - Not found
npm ERR! 404 
npm ERR! 404  'modulec@1.0.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
```

For contrast, it works just fine using `npm@6`:
```
:/moduleA $ npm i -g npm@6

removed 57 packages, changed 194 packages, and audited 436 packages in 2s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
:/moduleA $ npm link moduleb
/moduleA/node_modules/moduleb -> /Users/tristan/.nvm/versions/node/v15.7.0/lib/node_modules/moduleb -> /moduleB
:/moduleA $ npm link modulec
/moduleA/node_modules/modulec -> /Users/tristan/.nvm/versions/node/v15.7.0/lib/node_modules/modulec -> /moduleC
```

### Environment:
MacOS
npm@7

**Comment by Shadowfiend** [comment]
We just found an issue that may be related to this in npmv7: it looks like `npm link` now clears existing links if run for several modules in sequence. If you run one command, as in `npm link moduleb modulec`, it appears to link everything in one step---it's possible that may fix the issue you're seeing.

**Comment by tristanls** [comment]
Confirmed that `npm link moduleb modulec` is a valid workaround:

```
:/moduleA $ npm link moduleb
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/modulec - Not found
npm ERR! 404 
npm ERR! 404  'modulec@1.0.0' is not in the npm registry.
...
:/moduleA $ npm link modulec
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/moduleb - Not found
npm ERR! 404 
npm ERR! 404  'moduleb@1.0.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
...
:/moduleA $ npm link moduleb modulec

added 2 packages, and audited 5 packages in 635ms

found 0 vulnerabilities
```

Thank you.

**Comment by tristanls** [comment]
What's the reason for closing?

**Comment by joebnb** [comment]
same problem

if link a scoped module @scope/name1 at  dir1 it will remove all dir1/node_modules/@scope/*

i just want add a link moudle, not rm -rf @scope/ dir then link this one

**Comment by CodeTroopers** [comment]
Could you reopen this issue?
I have the same problem  with npm 7.6.3

- from depency @mycompany/B:

`cd dist && npm link`

-  from depency @mycompany/C:

`cd dist && npm link`

-  from main project @mycompany/A:

   `npm link @mycompany/B`
    Symlink @mycompany/B exists in node_modules
   `npm link @mycompany/C`
    Symlink @mycompany/C exists in node_modules
    **but Symlink @mycompany/B is deleted in node_modules**

This works well with npm 6.14.11

**Comment by livthomas** [comment]
> We just found an issue that may be related to this in npmv7: it looks like `npm link` now clears existing links if run for several modules in sequence. If you run one command, as in `npm link moduleb modulec`, it appears to link everything in one step---it's possible that may fix the issue you're seeing.

@darcyclarke Could you please at least document this before closing this issue? There is nothing like that mentioned in the documentation of [npm link](https://docs.npmjs.com/cli/v7/commands/npm-link) command.

**Comment by darcyclarke** [comment]
@tristanls apologies - I must have closed this while doing a larger sweep of issues (note: I rarely close without commenting unless it's obviously a bad issue or it's apart of a larger automated sweep); Apologese for the confusion. We'll dig in here & either do a better job at explaining how this works in the docs or get `npm link` to behave more like v6.

**Comment by mycodedig** [comment]
I am also experiencing the same!

**Comment by ruyadorno** [comment]
hi @tristanls thanks for the thorough report! 

I'm proposing a change that should fix the fact that other linked deps were being removed from the install tree when running `npm link <pkg>` multiple times. 

With that in mind, I believe you should tweak your workflow to use `npm link <pkg> --save` if you want to avoid linked deps being pruned - it's a [documented breaking change](https://docs.npmjs.com/cli/v7/commands/npm-link#caveat) in **npm7** for `npm link` not to store linked deps to `package.json`, so you should use that option in order to get a workflow similar to npm6.

Please let us know if you find any new problems! Thanks again 😊

**Comment by CodeTroopers** [comment]
@ruyadorno I don't undertstand why we should save linked package in the `package.json`. This is a bad workflow. Linking a package is used principaly in develop time to debug packages or sub packages. If the developper must save the linked package in the package.json, it could commit unintentionally the package as link instead of as real package.
