### ISSUE TITLE
cb() never called!

### ISSUE THREAD

**Issue by SuryaSachan** [npm/cli#2555]
# What / Why

> 
I was creating a new react app in my windows 10 
using cmd
 C:\Users\Username\Desktop>npx create-react-app nobita
Creating a new React app in C:\Users\Username\Desktop\nobita.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>
Aborting installation.
  npm install --save --save-exact --loglevel error react react-dom react-scripts cra-template has failed.

Deleting generated file... package.json
Deleting nobita/ from C:\Users\Username\Desktop
Done.
npm -v
6.14.11
node -v
v15.6.0

## When

* 

## Where

* n/a

### Current Behavior

* n/a

### Steps to Reproduce

* n/a

### Expected Behavior

* n/a

## Who

* n/a

## References

* n/a

**Comment by JoePotentier** [comment]
We are seeing this same error in our pipelines.

**Comment by JoePotentier** [comment]
> We are seeing this same error in our pipelines.

Seems it was a version mismatch with Node/npm. Investigating further.

**Comment by JoePotentier** [comment]
@SuryaSachan Your issue is with your node version. The create-react-app docs note the following, "You’ll need to have Node >= 8.10 and npm >= 5.6 on your machine."

**Comment by SuryaSachan** [comment]
Thank you for your response. It would be great if the issue is resolved. In the meantime, which version would you suggest me to go ahead with?

**Comment by SuryaSachan** [comment]
It worked for me by updating npm.
npm install -g npm@latest
