### ISSUE TITLE
[BUG] npm outdated no longer exits with code 1 if outdated

### ISSUE THREAD

**Issue by gfyoung** [npm/cli#2556]
### Current Behavior:

Exits with code `0`.

### Expected Behavior:

Exits with code `1`.

### Steps To Reproduce:

~~~bash
#!/usr/bin/env bash

FOLDER=`mktemp -d`

echo $FOLDER

cd $FOLDER

# https://www.npmjs.com/package/@npmcli/arborist
npm install @npmcli/arborist@2.0.5 --save

npm outdated

echo $?
~~~

This echos `0` and not `1`.

### Environment:
OS: MacOS Catalina
Node: v15.7.0
npm: 7.4.3

When I run the same script with:

OS: MacOS Catalina
Node: v13.0.1
npm: 6.14.0

I get the output of `1` at the end as expected.

**Comment by metasean** [comment]
I'm running into the same bug with:
OS: MacOS Catalina
Node: v14.16.0
npm: 7.6.0

edited: I was in the wrong terminal when I initially ran my node -v and npm -v 😞 ; these values are from the same terminal as the non-responsive command.

**Comment by metasean** [comment]
Based on a cursory search, it looks like this is the PR where the exitCode was removed - https://github.com/npm/cli/commit/3743a42c854d9ea7e333d7ff86d206a4b079a352#diff-fcab44373f1f924f030ce92d009f10ab53d45e7a55422870b55f3c7f8af1796d

**Comment by gfyoung** [comment]
@metasean: Nice catch!

@claudiahdz @ruyadorno: Was there a reason for the exit code change?

**Comment by db-developer** [comment]
Not sure, if this is the same feature.
See the difference in ERRORLEVEL 1 vs 0 (0 in actual versions)

nodejs version:     v14.16.0
npm version:        6.14.11
src\test\tmp\project-04>npm outdated & echo %ERRORLEVEL%
Package              Current  Wanted  Latest  Location
grunt                MISSING   1.4.1   1.4.1  example-project-00
1

nodejs version:     v15.14.0
npm version:        7.7.6
src\test\tmp\project-04>npm outdated & echo %ERRORLEVEL%
Package              Current  Wanted  Latest  Location  Depended by
grunt                MISSING   1.4.1   1.4.1  -         project-04
0

Besides "Location" should be "project-04" where as "Dependend by" should be "example-project-00" I guess. The later is the projects name within package.json in directory project-04.

**Comment by PatrickSpies** [comment]
Any updates on this?

**Comment by db-developer** [comment]
Did not check.
I switched to using this: https://www.npmjs.com/package/check-outdated.
For my grunt builds I wrote this: https://www.npmjs.com/package/grunt-check-outdated (which is based on the previous)
... I'm sure there are even more alternatives.

**Comment by gfyoung** [comment]
Finally got around to just doing it myself 🙂

https://github.com/npm/cli/pull/3799

**Comment by gfyoung** [comment]
#3799 has been merged!  Closing.
