### ISSUE TITLE
npm install throwing error -- how do I get around this?

### ISSUE THREAD

**Issue by matthewnaldzin** [npm/cli#2577]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install'
1 verbose cli ]
2 info using npm@6.14.10
3 info using node@v14.15.4
4 verbose npm-session 693f5127a39e816c
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall braintreetutorial@0.0.0
7 info lifecycle braintreetutorial@0.0.0~preinstall: braintreetutorial@0.0.0
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 timing stage:loadCurrentTree Completed in 17ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 2ms
16 silly install loadAllDepsIntoIdealTree
17 http fetch GET 407 https://registry.npmjs.org/cookie-parser 277ms
18 http fetch GET 407 https://registry.npmjs.org/hbs 274ms
19 http fetch GET 407 https://registry.npmjs.org/debug 277ms
20 http fetch GET 407 https://registry.npmjs.org/express 284ms
21 http fetch GET 407 https://registry.npmjs.org/morgan 281ms
22 http fetch GET 407 https://registry.npmjs.org/http-errors 286ms
23 timing npm Completed in 1298ms
24 error cb() never called!
25 error This is an error with npm itself. Please report this error at:
26 error <https://npm.community>

**Comment by shadowspawn** [comment]
407 is a proxy error, and probably something about your local access to the internet. Try accessing one of the URLs listed directly in your browser or using a tool like `curl` and you might see more information about what authentication the proxy is expecting.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/407

Related issue with example of setting proxy authentication for npm: #544

There are not any outages showing on the npm status page: https://status.npmjs.org
