### ISSUE TITLE
[BUG] bundleDependencies missing from workspace

### ISSUE THREAD

**Issue by jsg2021** [npm/cli#2580]
### Current Behavior:

Within a workspace project, have a subproject that echos all its devDependencies in the bundleDependencies list... when you install the workspace, the dependencies for that project are not installed/found.

### Expected Behavior:

dependencies should be installed/found.

### Environment:
- OS: Fedora 33
- Node: 15.6.0
- npm: 7.5.0

**Comment by jsg2021** [comment]
You can reproduce it with this workspace: https://github.com/jsg2021/npm7-workspace-test

**Comment by darcyclarke** [comment]
@jsg2021 if you specify that you're bundling dependencies, then we expect them to already be there, ie. installed into `node_modules` (https://docs.npmjs.com/cli/v7/configuring-npm/package-json#bundleddependencies). You should run `npm install --no-save` inside each of your workspaces to pull down whatever dependencies you want to bundle & then potentially be hoisted by the root.

**Comment by jsg2021** [comment]
I'm confused. @darcyclarke how could they already be there? If I clone and run `npm install` in a project like this, npm happily installs those dependencies. The workspace around this project should not make a difference. I could understand a special workflow for publishing/packaging but for general development, I would expect the install of the workspace to give me everything I need to run.

**Comment by jsg2021** [comment]
If I rename the key so npm ignores it, and install the workspace everything is fine (for running, not necessarily for packaging)
