### ISSUE TITLE
[BUG] Problem updaiting ^version

### ISSUE THREAD

**Issue by zdm** [npm/cli#2582]
### Current Behavior:

Npm doesn't installs latest available minor version when version specified with `^` prefix.

### Expected Behavior:

Expecting, that latest minor version with the latest patch will be installed.

### Steps To Reproduce:

`package.json`
```
{
    "dependencies": {
        "@softvisio/core": "^0.80.0"
    }
}
```

Latest `@softvisio/core` version in the npm registry is `0.125.0`.

When I exec `npm i` I am expecting, that latest minor version `0.125.0` will be installed, but it installs `0.80.2` (latest patch for `0.80`). Why?
I have no `package-lock.json`.

### Environment:

npm 7.5.0
node 15.7.0
windows, linux

**Comment by ljharb** [comment]
For v0.0.x, every `x` is semver-major; for `v0.x.y`, every `x` is semver-major, for `x.y.z`, every `x` is semver-major.

In other words, `v0.80.2` to `v0.81.0` is a breaking change, as such, going to `v0.125.0` is also a breaking change (a lot of them) - and so `^` is correctly not updating to it.

**Comment by zdm** [comment]
thanks, i didn't knew this.
