### ISSUE TITLE
[BUG] npm_package_main variable is always empty

### ISSUE THREAD

**Issue by jotafeldmann** [npm/cli#2585]
### Current Behavior:
- When I set the package.json file with "main": "index.js"
- Set the "start" property from scripts to "start": "node $npm_package_main"
- Then run npm start

**Problem**: the CLI executes the Node REPL mode, ignoring the "main" variable from package.json.

### Expected Behavior:
Execute the command as `node index.js`.

### Steps To Reproduce:
- Create an "app" directory and enter the new directory
- Create an "index.js" file with the following content
`console.log('HELLO');`
- Run `npm init` and hit ENTER for all questions
- Edit the `package.json` file and add the following line to the "scripts" property:
`"start": "node $npm_package_main",`
- now your package.json must look like this
```
    {
      "name": "app",
      "version": "1.0.0",
      "description": "",
      "main": "index.js",
      "devDependencies": {},
      "scripts": {
        "start": "node $npm_package_main",
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "author": "",
      "license": "ISC"
    }
```

- Run "npm start"
- File "index.js" is not executed and Node enters the REPL mode.

### Environment:
- Linux Ubuntu 20.04.1
- `npm -v` = 7.3.0
- `node -v` = v15.5.0
- `npm run env | grep npm_package_name` = `npm_package_name=app` 
- `npm run env | grep npm_package_main` = EMPTY

## Attempts

Set "start" and running "npm start" for:
- "echo $npm_package_main" prints nothing
- "echo $npm_package_name" prints "app"
- "echo $npm_package_version" prints "1.0.0"

### References
- Stackoverflow issue: https://stackoverflow.com/questions/65982127/npm-npm-package-main-variable-is-always-empty

**Comment by ljharb** [comment]
This was an intentional change in npm 7. Try `node .`?

**Comment by jotafeldmann** [comment]
Hi @ljharb thanks. How can I point that in the documentation? Add some warning on https://docs.npmjs.com/cli/v7/using-npm/scripts, maybe?

Something like:

"Everything works for $npm_package_*, except for `$npm_package_main` due to REASONS_HERE."

**Comment by jotafeldmann** [comment]
Found the issue: https://github.com/npm/cli/pull/2446

**Comment by ljharb** [comment]
I think there’s very few that actually remain set - it definitely seems like a good idea to update the docs.

**Comment by jotafeldmann** [comment]
Anyway, yes we can always use "node ." or just set `"start": "node index.js"`.

I understand that Is just a small behavior/feature to take care of.

But there's no clear answer explaining why $npm_package_main is empty, the reasons behind that decision.

Closing the issue.
