### ISSUE TITLE
[BUG] <title> npm ERR! cb() never called!

### ISSUE THREAD

**Issue by Eeebru** [npm/cli#2586]
### Current Behavior:
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

### Expected Behavior:
To install all the projects dependencies

### Steps To Reproduce:

steps to reproduce the behaviour:
1. In VSCode integrated terminal
2. Run 'npm install'
3. See error: This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

### Environment:
- OS: Windows
- Node: 14.15.4
- npm: 6.4.12

**Comment by isaacs** [comment]
https://github.com/npm/cli/wiki/%22cb()-never-called%3F--I'm-having-the-same-problem!%22

Try this with the latest npm v6 (or upgrade to npm v7, which will be the default soon anyway).

If that doesn't work, then we'd definitely need (at minimum) the set of dependencies being installed (ie, your package.json/package-lock.json files) and the debug log file that was generated (the filename is at the bottom of the error message).

Happy to re-open if that doesn't fix it, and more information is provided. :)
