### ISSUE TITLE
[BUG] Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by TunaGKLP** [npm/cli#2589]
### Current Behavior:
Cannot read property 'version' of undefined

### Expected Behavior:
Install the module called "discord.js"

### Steps To Reproduce:

1. Run 'npm i discord.js'
2. Error

### Environment:

Node: 15.7.0
npm: 7.4.3

### Additional Info

It gives me the same error even if i try to open a new folder and try to install.

**Comment by darcyclarke** [comment]
Closing: As I can't seem to replicate this at all. Try updating to the latest version of `npm` (ie. `npm i -g npm@7`) & see if you can still replicate this issue. If you're still having problems, try putting together a reproduction case/[gist](https://gist.github.com/)
