### ISSUE TITLE
[BUG] Recursive npm install error

### ISSUE THREAD

**Issue by ruyadorno** [npm/cli#2598]
Seems to be related to having a cycle of git deps with prepare scripts. Although in preliminary tests that also seems to cause the same issue in npm@6 which is no the case in the provided repro.

### Current Behavior:

Install enters into a cycle of `npm install`s

![example image](https://pbs.twimg.com/media/ErS8I9GXMAA8E5m?format=jpg&name=large)

### Expected Behavior:

Should be able to complete an install successfully, repro works fine in npm@6.

### Steps To Reproduce:

```sh
nvm use 15.5.1 && git clone --depth=10 https://github.com/mongodb-js/mongosh.git && cd mongosh && git checkout d1688c3c4 && npm run bootstrap-ci
```

### Refs:

https://twitter.com/addaleax/status/1348660250270904326

**Comment by isaacs** [comment]
This should be fixed in the latest release of npm v7.
