### ISSUE TITLE
🐞 [BUG] npm@7 is broken on node@8 or older

### ISSUE THREAD

**Issue by jcuna** [npm/cli#2599]
### Current Behavior:
Running `npm install -g npm@7.5.1`
Running `npm install -g npm` on version 7.5.2

produces the following output.
~~~

TypeError: Cannot destructure property `stat` of 'undefined' or 'null'.
--
92 | at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/node-gyp/lib/index.js:2:29)
93 | at Module._compile (module.js:652:30)
94 | at Object.Module._extensions..js (module.js:663:10)
95 | at Module.load (module.js:565:32)
96 | at tryModuleLoad (module.js:505:12)
97 | at Function.Module._load (module.js:497:3)
98 | at Module.require (module.js:596:17)
99 | at require (internal/module.js:11:18)
100 | at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:4:55)
101 | at Module._compile (module.js:652:30)
102 | /usr/local/lib/node_modules/npm/node_modules/@npmcli/config/lib/index.js:163
103 | throw new Error('call config.load() before reading values')
104 | ^
105 |  
106 | Error: call config.load() before reading values
107 | at Config.get (/usr/local/lib/node_modules/npm/node_modules/@npmcli/config/lib/index.js:163:13)
108 | at process.errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:171:32)
109 | at emitOne (events.js:116:13)
110 | at process.emit (events.js:211:7)
111 | at process._fatalException (bootstrap_node.js:375:26)

~~~

### Expected Behavior:
Packages installed successfully

### Steps To Reproduce:

ex. steps to reproduce the behavior:
1. aws/codebuild/nodejs:8.11.0
2. With this config...
3. Run '...'
4. See error...
### Environment:

- OS: Amazon Linux 2 | aws/codebuild/amazonlinux2-aarch64-standard:1.0
- Node: 8.11.0
- npm: 7.5.1 and 7.5.2

**Comment by wraithgar** [comment]
If you are still running node 8 you are going to want to use npm v6,  You can use the `latest-6` tag to install the latest version of 6.

```sh
$ npm install npm@latest-6
```

If you have installed npm 7 on node 8 you can run this command to get back to a working npm 6

```shell
$ curl -qs https://www.npmjs.com/install.sh|npm_install=6.14.11 sh
```

**Comment by joshuasaunders** [comment]
Running into the exact same issue and installing latest version of 6 isn't working for me with node 8. When I run `npm install npm@latest-6` or `npm install -g npm@latest-6` I still get the same error `TypeError: Cannot destructure property 'stat' of 'undefined' or 'null'.` Any ideas?

**Comment by ljharb** [comment]
If you're using nvm, you can also `nvm install-latest-npm`, and you'll always be guaranteed to get the latest working version (but you have to start with a working node/npm, ofc)

**Comment by tuchidoghostmaster** [comment]
Hi all, 

I have the same error,

I deployed from Gitlab to Heroku and had the same error,

Is there a way to fix it?

![image](https://user-images.githubusercontent.com/49369979/106696257-e60b2f00-660e-11eb-8ce9-3fdf98b181b1.png)

**Comment by slavoroi** [comment]
We have the same issue in our Jenkins pipilines.
Running `npm i -g npm` installs npm 7.5.2 when i'm on node 8.
It also breaks our usage of `nvm` in our local computers (nvm 33).
Also I tried using npm 7 and it failed on many libraries, like rollup and many more!
Didn't you promise npm 7 would be for node 15+, no?

**Comment by eAi** [comment]
I'm also having this error when I upgraded from 5.6.0 to 7.5.2. Reinstalling node from nodejs.org (with npm 6.14.10) fixed this.

**Comment by guilhermesad** [comment]
Getting same error trying to deploy to Heroku:
<img width="999" alt="Screen Shot 2021-02-03 at 10 51 38 AM" src="https://user-images.githubusercontent.com/1436748/106756231-d4755780-660d-11eb-9e5e-b851d4919e73.png">

**Comment by ljharb** [comment]
@slavoroi https://github.com/npm/cli/issues/2599#issuecomment-772159414

**Comment by joshuasaunders** [comment]
I am really stuck here and this is on my production server. I can't get nvm installed, get the same error installing nvm `TypeError: Cannot destructure property `stat` of 'undefined' or 'null'.` I can't figure out a way to upgrade node, and npm isn't working for anything. Can't even tpye `npm -v` without the error. I don't want to uninstall npm completely to reinstall it, as that may take down my production server in the process. Anyone have any other ideas to fix this problem?

**Comment by tekstrand** [comment]
We're seeing this issue in our pipeline. As far as I can tell downgrading to npm 6 does fix it, but that is quite a pain.

**Comment by joshuasaunders** [comment]
@tekstrand How did you downgrade to npm 6?  I get the same error trying to downgrade with the normal install command `npm install -g npm@6`. Did you have to completely uninstall npm first?

**Comment by joshuasaunders** [comment]
Yeah, thanks. Had to manually do the install of lower version of npm. Then upgrade node. Then was able to update npm.

**Comment by wraithgar** [comment]
If you have installed npm 7 on node 8 you can run this command to get back to a working npm 6

```sh
$ curl -s https://www.npmjs.com/install.sh|npm_install=6.14.11 sh
```

**Comment by zenigate** [comment]
> If you have installed npm 7 on node 8 you can run this command to get back to a working npm 6
> 
> ```shell
> $ curl -s https://www.npmjs.com/install.sh|npm_install=6.14.11 sh
> ```

Thank you, This help me fix this issue

**Comment by ljharb** [comment]
@wraithgar heads up that that's not working for me; curl doesn't output anything to the pipe unless i add `-o-`, and inside the script, the curl to get the tarball URL has the same problem.

**Comment by wraithgar** [comment]
@ljharb that sounds like a curl version issue maybe? If I remember correctly older versions of curl didn't automatically handle being piped correctly.

The [readme example](https://github.com/npm/cli#direct-download) has `-L` as a parameter but that's only for following redirects, of which there aren't any on that url.

What version of curl were you using? I am on `curl 7.64.1`

**Comment by ljharb** [comment]
@wraithgar i'm using whatever `curl` comes with Mac OS Big Sur, which is indeed v7.64.1. Do you perhaps have a `~/.curlrc` that is altering how curl behaves?

**Comment by wraithgar** [comment]
Nope, no curlrc, and same version but I'm not on Big Sur, still on Catalina.

**Comment by nlf** [comment]
I just tried on Big Sur in both `fish` and the default `zsh` and had no issues, also with no curlrc

fwiw I tested on an m1 mbp and in both rosetta and with a native node, no issues anywhere for me

**Comment by ljharb** [comment]
oooops, lol, i had a curlrc with `--remote-name-all`, specifically to trigger this scenario for when nvm forgets to use `-q` (to bypass the curlrc). Perhaps the curls inside the script could use that?

**Comment by nlf** [comment]
we can patch the script to pass a `-q` in the calls there and change our advised command to install to include it

**Comment by tuchidoghostmaster** [comment]
> Getting same error trying to deploy to Heroku:
> <img alt="Screen Shot 2021-02-03 at 10 51 38 AM" width="999" src="https://user-images.githubusercontent.com/1436748/106756231-d4755780-660d-11eb-9e5e-b851d4919e73.png">

Hi, I have solved it.

- In the file`package.json` please using :

```
...
"engines": {
    "node": "8.11.3",
    "npm": "6.14.11"
 },
...
```
Then it will work for you.

**Comment by ljharb** [comment]
@tuchidoghostmaster the `npm >= 3.10` is what's broken - npm 7+ can't ever work on node 8. Try fixing the "engines" field's "npm" property in your package json to be `^3 || ^4 || ^5 || ^6`, for example.

**Comment by tuchidoghostmaster** [comment]
@ljharb yes, i'm updated, using node 8 and npm 6+ working for me now. see comment https://github.com/npm/cli/issues/2599#issuecomment-773004723

**Comment by phil-warner** [comment]
I'm getting the exact same error. I was running Node 12.18 and tried upgrading to 14.15.4, which came with npm 6.14.1, which didn't fix it. Then tried to upgrade npm, but got the error again.

**Comment by denzelWashington** [comment]
I'm getting the same problem too.
I have **node 8.9.4** installed but when i run in jenkinsfile `npm -v `, im getting this error 
![Annotation 2021-02-08 095631](https://user-images.githubusercontent.com/953867/107197318-06aefc80-69f4-11eb-9d0c-6bfac7b15501.jpg)

**Comment by valdiss** [comment]
I don't know if this is allowed or not to talk about third party packages but I discovered npm-check-updates today, it solves the npm update problem for me... If that can help anyone!
