### ISSUE TITLE
[BUG] Issues when using workspaces

### ISSUE THREAD

**Issue by lee5i3** [npm/cli#2600]
We are having issues with our monorepo project, our package.json has

```
{
  "private": true,
  "workspaces": [
    "common",
    "base-tests",
    "ttic-fl-ho3",
    "ttic-fl-af3",
    "hcpc-sc-af3",
    "hcpc-nj-af3",
    "ttic-ga-ho3"
  ]
}
```

When we ran `npm install`, it use to run fine.. now says
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: common@1.1.1
npm ERR! Found: sinon@9.0.1
npm ERR! node_modules/sinon
npm ERR!   dev sinon@"^9.0.1" from common@1.1.1
npm ERR!   common
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer sinon@"5 - 7" from sinon-mongoose@2.3.0
npm ERR! node_modules/sinon-mongoose
npm ERR!   dev sinon-mongoose@"^2.3.0" from common@1.1.1
npm ERR!   common
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/lhull/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lhull/.npm/_logs/2021-02-02T22_00_46_902Z-debug.log
```

This worked on v7.5.0 but now errors on 7.5.1+

[2021-02-02T22_00_46_902Z-debug.log](https://github.com/npm/cli/files/5914770/2021-02-02T22_00_46_902Z-debug.log)

**Comment by plotka** [comment]
I had a similar issue, I solved it by deleting the `node-modules` folder in the root and by running `npm install --legacy-peer-deps`

**Comment by darcyclarke** [comment]
@lee5i3 can you try installing the latest v7 & see if you can reproduce it? (ie. `npm install -g npm` - `7.6.0`)

**Comment by ruyadorno** [comment]
I'm going to go ahead and close this one due to inactivity, for more context we have been fixing a lot of these `ERESOLVE` edge case problems during `npm install` in the last few months and it's very likely that this one might already have been fixed.

In case anyone arrives here with the same problem, feel free to create a new issue and reference/link to this one.

Thanks!
