### ISSUE TITLE
[BUG] Doesn't use SSH agent for git+ssh

### ISSUE THREAD

**Issue by strarsis** [npm/cli#2614]
### Current Behavior:
`npm` doesn't use the available SSH agent (`SSH_AUTH_SOCK` environment variable) when installing from git+ssh repositories (e.g. self-hosted private GitLab). `~/.ssh/config` is used, hence the workaround consists of providing a private key file and force its usage in `~/.ssh/config` for the paritcular connections.

### Expected Behavior:
`npm` should use the SSH agent when connecting over `git+ssh`.

### Steps To Reproduce:
1. Ensure a SSH agent is running that provides private keys for accessing a private git repository over SSH.
2. Install from the private git repository over SSH using `npm`:
`npm install git+ssh://git@gitlab.example.com/tooling/some-lib.git`
An authentication error should occur.

### Environment:
- OS: Windows 10 x64 (WSL 2 Ubuntu 20.x)
- Node: v14.15.3
- npm: 7.5.2

**Comment by darcyclarke** [comment]
@strarsis this doesn't sound like `npm` would be doing anything to prevent the `ssh` client from properly using your creds. Potentially, this is a problem with WSL? Not quite sure. That said, I don't think there's anything we can do in this case. Let me know if you think there's something specific that `npm` could do here....

**Comment by strarsis** [comment]
Just encountered this issue today again – in WSL 2 and latest `node` and `npm`.

I had to add an exception for this particular private GitLab server in `~/.ssh/config` to not 
use the SSH agent but rather a private key:
````
Host gitlab.example.com
  # Workaround for `npm` not using the SSH agent
  # (@see https://github.com/npm/cli/issues/2614)
  IdentityFile ~/.ssh/dev_id_ed25519

  # still add this key to SSH agent (when SSH agent forwarding)
  AddKeysToAgent yes
````
This "workaround" at least allows `npm` to install everything.

@darcyclarke: Please re-open this issue as it it is still there with latest WSL 2, `node` and `npm`.
`ssh` and `git` work fine and use the SSH agent, but the `git` spawned by `npm` does not.
