### ISSUE TITLE
[BUG] cb() never called!

### ISSUE THREAD

**Issue by ghost** [npm/cli#2616]
It exists, but for v6...

### Current Behavior:

When I'm installing anything (probably when with `-g` or `link`) after npm installing, it stops in the middle, and shows the error `cb() never called!`
### Expected Behavior:

Should install pkgs normally.
### Environment:

(I just installed npm@latest yesterday, and from that time, installing pkgs globally is showing that problem.
Also, when I was doing `npm link` in my pkg repo, it showed that error, also doing `npm i image-to-ascii-cli -g` also showed that same error. So I can confirm that it's not a bug of any pkg, but with the npm itself.

**Comment by isaacgannon** [comment]
I have experienced the same bug this is my log.
[2021-02-04T10_12_16_652Z-debug.log](https://github.com/npm/cli/files/5925080/2021-02-04T10_12_16_652Z-debug.log)

**Comment by wraithgar** [comment]
This is being tracked in the issue we have pinned here https://github.com/npm/cli/issues/417
