### ISSUE TITLE
[BUG] Transitive production dep is incorrectly marked as dev dep in package-lock.json

### ISSUE THREAD

**Issue by justincy** [npm/cli#2622]
### Current Behavior:

A transitive dependency is incorrectly marked in package-lock.json as a dev dep. This prevents it from being installed when `NODE_ENV=production`.

#### More detail

In my case, the problem occurs with `@babel/core`. Here's the output of `npm list @babel/core`:

```
my-project@1.0.0
├─┬ @svgr/webpack@5.5.0
│ ├── @babel/core@7.12.3 
│ └─┬ @svgr/plugin-jsx@5.5.0
│   └── @babel/core@7.12.3 
└─┬ jest@26.6.3
  └─┬ @jest/core@26.6.3
    ├─┬ @jest/reporters@26.6.2
    │ └─┬ istanbul-lib-instrument@4.0.3
    │   └── @babel/core@7.12.13  deduped
    ├─┬ @jest/transform@26.6.2
    │ └── @babel/core@7.12.13 
    └─┬ jest-config@26.6.3
      └── @babel/core@7.12.13  deduped
```

`@babel/core` is a dep of both [@svgr/webpack](https://github.com/gregberge/svgr/blob/ec17865c5d26c5e7e5cb6b91c650c143543f5243/packages/webpack/package.json#L33) and jest libraries. For `@svgr/webpack` it is a production dep while it's a dev dep for jest.

It's also interesting to note that though `@babel/core` appears 5 times in `npm list`, it is only marked as deduped twice.

I am unable to reproduce the error when I setup a [simple repo](https://github.com/justincy/npm-dev-dep-test) with just `@svgr/webpack@5.5.0` and `jest@26.6.3` as deps. Perhaps there's some other interaction going on with other deps. Also, in that scenario, `npm list` shows `@babel/core` and being deduped 4 times instead of just 2:

```
npm-dep-test@1.0.0
├─┬ @svgr/webpack@5.5.0
│ ├── @babel/core@7.12.13 
│ └─┬ @svgr/plugin-jsx@5.5.0
│   └── @babel/core@7.12.13  deduped
└─┬ jest@26.6.3
  └─┬ @jest/core@26.6.3
    ├─┬ @jest/reporters@26.6.2
    │ └─┬ istanbul-lib-instrument@4.0.3
    │   └── @babel/core@7.12.13  deduped
    ├─┬ @jest/transform@26.6.2
    │ └── @babel/core@7.12.13  deduped
    └─┬ jest-config@26.6.3
      └── @babel/core@7.12.13  deduped
```

### Expected Behavior:

Because `@babel/core` is a transitive production dependency, it should not be marked as a dev dep in package-lock.json and should be installed even when `NODE_ENV=production`.

### Steps To Reproduce:

I'm trying to create a reproducible example, but just setting up the simple dependency chart shown above doesn't reproduce the error.

### Environment:

- OS: macOS 10.15.7
- Node: 12.18.2
- npm: 6.14.5

**Comment by ljharb** [comment]
(Not that this affects the bug, but why would anything webpack-related be a production dep?)

**Comment by justincy** [comment]
I tried copying most of the other dependencies from my main project into the [test project](https://github.com/justincy/npm-dev-dep-test/blob/ae523f3336f0c53a566e77e16b28e00c71f36501/package-lock.json#L20), and I still wasn't able to reproduce the bug. I couldn't copy all deps because some are in a private repository, so maybe that's the problem.

**Comment by justincy** [comment]
Removing the private deps in my main project didn't solve the problem either. I don't know what else to test.

**Comment by justincy** [comment]
The problem went away after clearing the npm cache and regenerating the npm cache. 🤷🏼‍♂️
