### ISSUE TITLE
[BUG] npx appears broken in 7+ with PATH

### ISSUE THREAD

**Issue by dl748** [npm/cli#2627]
[test.zip](https://github.com/npm/cli/files/5930021/test.zip)
### Current Behavior:
Version 6+
```
export PATH=$(pwd)/node_modules/.bin:$PATH
$ webpack --version
4.44.2
$ npx webpack --version
4.44.2
$ cd common
$ webpack --version
4.44.2
$ npx webpack --version
4.44.2
```

Version 7+
```
export PATH=$(pwd)/node_modules/.bin:$PATH
$ webpack --version
4.44.2
$ npx webpack --version
4.44.2
$ cd common
$ webpack --version
4.44.2
$ npx webpack --version
Need to install the following packages:
  webpack
Ok to proceed? (y)
```

### Expected Behavior:

Should not ask to install as it already exists in the PATH

### Environment:

OS: Linux 5.7.9
Node: v14.15.4
npm: 7.5.2

**Comment by dl748** [comment]
[test.zip](https://github.com/npm/cli/files/5930023/test.zip)

Sample

**Comment by darcyclarke** [comment]
@dl748 does the `common` folder happen to have a `node_modules` folder there? Sounds like that could be the issue.

**Comment by dl748** [comment]
@darcyclarke No it does not

**Comment by dl748** [comment]
Is NPX following its own rules now and NOT following the PATH variable like the documentation says?
```
PATH=/myproject/node_modules/.bin:/usr/.local/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/var/lib/snapd/snap/bin
```
if i put webpack into /usr/bin/webpack.   npx works... if i put it in /usr/.local/bin/webpack.. it doesn't work.. which seems to me that its building it OWN path to look for the program and completely ignoring the PATH variable which is way different than the 6 and the documentation.

```
By default, npx will check whether <command> exists in $PATH, or in the local project binaries, and execute that. If <command> is not found, it will be installed prior to execution.
```

which is NOT what its doing

**Comment by dl748** [comment]
Simple script to replicate

test123
```
#!/usr/bin/env node

console.log('test')
```

```
$ chmod 755 test123 # make executable
$ mkdir x
$ mv test123 x/.
$ export PATH=$(pwd)/x:$PATH
$ test123
test
# Above works
$ npx test123
npx test123
npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in:
npm ERR!     /User123/.npm/_logs/2021-03-04T05_12_18_738Z-debug.log
$ npx --version
7.6.0
$ sudo npm install -g npm@6.14.11
$ npx --version
6.14.11
$ npx test123
test
# works with 6.14.11
```

**Comment by dl748** [comment]
Note: the reason I use npx instead of just calling the script is for windows support `webpack` works for *nix/osx but not for windows since it needs to run `webpack.cmd` instead on windows

**Comment by wraithgar** [comment]
npm will not look in the `PATH` environment variable for things to run. IT will only check the folders it knows about that are related to npm itself.  Adding the `node_modules/.bin` folder to your `PATH` is not recommended. You should run npm scripts from npm/npx.
