### ISSUE TITLE
[BUG] Package-lock v2 (npm v7) is attempting to install optional and non-platform libraries causing CI builds to fail using npm 6.

### ISSUE THREAD

**Issue by holmok** [npm/cli#2633]
### Current Behavior:

We have a project that builds fine locally (mac os dev machines) and on our CI (git lab Linux containers) that worked end to end with npm v6.  This includes libraries that have a dependency on fsevents v1.x.  Currently, our build containers are built with node v12 and npm v6, so as to not break the things using fsevents 1.x.  I upgraded a local dev machine to node v15 and npm 7.  All the package-lock files were upgraded to v2, which included the platform info for fsevent (darwin).  On the build now with the package-lock v2 we get the following output and error.

![image](https://user-images.githubusercontent.com/2625433/107053008-f13b9780-6793-11eb-831d-3ed71e132455.png)

diff in the lock files:

```
// NPM v6 lock file

"fsevents": {
	"version": "1.2.13",
	"resolved": "https://registry.npmjs.org/fsevents/-/fsevents-1.2.13.tgz",
	"integrity": "sha512-oWb1Z6mkHIskLzEJ/XWX0srkpkTQ7vaopMQkyaEIoq0fmtFVxOthb8cCxeT+p3ynTdkk/RZwbgG4brR5BeWECw==",
	"optional": true,
	"requires": {
		"bindings": "^1.5.0",
		"nan": "^2.12.1"
	}
},

// NPM v7 lock file

"node_modules/fsevents": {
	"version": "1.2.13",
	"resolved": "https://registry.npmjs.org/fsevents/-/fsevents-1.2.13.tgz",
	"integrity": "sha512-oWb1Z6mkHIskLzEJ/XWX0srkpkTQ7vaopMQkyaEIoq0fmtFVxOthb8cCxeT+p3ynTdkk/RZwbgG4brR5BeWECw==",
	"optional": true,
	"os": [
		"darwin"
	],
	"dependencies": {
		"bindings": "^1.5.0",
		"nan": "^2.12.1"
	},
	"engines": {
		"node": ">= 4.0"
	}
},
```

### Expected Behavior:

What I would hope would happen is that the CI build would ignore the unsupported platform packages, with maybe a warning rather than exiting with an error.

### Steps To Reproduce:

1) On the dev machine with NPM v7 run `npm i` with an optional darwin platform dependency 
2) `package-lock.json` is upgraded to v2.
3) Code is checked into the repo, and CI kicks off
4) When the build attempts to run `npm i` it fails with the above error.

### Environment:

dev machine :
* Mac OS (Big Sur 11.2) Apple M1
* node v15.7.0
* npm v7.4.3

CI container:
* gitlab-runner 13.8.0
* node 12.20.1
* npm 6.14.10

**Comment by isaacs** [comment]
Hmm, I cannot reproduce this.

When I install chokidar (which has an optional dependency on fsevents) with npm 7, I get [this lockfile](https://gist.github.com/isaacs/bb57f0ef8ea77588acbf3aecd39c03da).  Note the [new-style entry for fsevents](https://gist.github.com/isaacs/bb57f0ef8ea77588acbf3aecd39c03da#file-package-lock-json-L74-L85):

```js
    "node_modules/fsevents": {
      "version": "2.3.2",
      "resolved": "https://registry.npmjs.org/fsevents/-/fsevents-2.3.2.tgz",
      "integrity": "sha512-xiqMQR4xAeHTuB9uWm+fFRcIOgKBMiOBP+eXiyT7jsgVCq1bkVygt00oASowB7EdtpOHaaPgKt812P9ab+DDKA==",
      "optional": true,
      "os": [
        "darwin"
      ],
      "engines": {
        "node": "^8.16.0 || ^10.6.0 || >=11.0.0"
      }
    },
```

and the [old-style entry that npm v6 uses](https://gist.github.com/isaacs/bb57f0ef8ea77588acbf3aecd39c03da#file-package-lock-json-L220-L225):

```js
    "fsevents": {
      "version": "2.3.2",
      "resolved": "https://registry.npmjs.org/fsevents/-/fsevents-2.3.2.tgz",
      "integrity": "sha512-xiqMQR4xAeHTuB9uWm+fFRcIOgKBMiOBP+eXiyT7jsgVCq1bkVygt00oASowB7EdtpOHaaPgKt812P9ab+DDKA==",
      "optional": true
    },
```

which both show `"optional": true`.  That _should_ be enough for either npm v6 or v7 to properly avoid installing it when the engine doesn't match (or ignore the crash and move on if they try and it fails).

Is it possible that something is depending on fsevents in a way that is _not_ optional?

What do you see when you run `npm ls fsevents` on your mac environment?

**Comment by isaacs** [comment]
Also, if there is any diff in the `dependencies` portion of the package-lock.json files, then that would be relevant.  npm v6 does not know about or do anything with the `packages` section.

Same results with chokidar@2 instead of latest, but then `fsevents` is version 1.2.7 [lockfile](https://gist.github.com/isaacs/5987e4a8eb464f211b01817c5db73d64)

I see this when I install with npm v6:

```
$ npm i
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm WARN choki No description
npm WARN choki No repository field.
npm WARN choki No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 141 packages from 104 contributors and audited 145 packages in 2.884s
found 0 vulnerabilities
```

**Comment by holmok** [comment]
...interesting...

```
% npm ls fsevents
root@ [path-removed]
├─┬ @project/app1@0.0.7 -> [path-removed]/packages/app1
│ ├─┬ nodemon@2.0.7
│ │ └─┬ chokidar@3.5.1
│ │   └── fsevents@1.2.13 deduped invalid
│ └─┬ tap@14.11.0
│   ├─┬ chokidar@3.5.1
│   │ └── fsevents@2.3.1 deduped
│   └── fsevents@2.3.1 extraneous
├─┬ @project/app2@0.0.1 -> [path-removed]/packages/app2
│ └─┬ webpack@4.29.6
│   └─┬ watchpack@1.7.5
│     ├─┬ chokidar@3.5.1 extraneous
│     │ └── fsevents@2.3.1 deduped
│     └── fsevents@2.3.1 extraneous
├── fsevents@1.2.13 extraneous
└─┬ watchpack-chokidar2@2.0.1 extraneous
  └─┬ chokidar@2.1.8
    └── fsevents@1.2.13 deduped
```

I don't know why the extraneous `fsevents@1.2.13` is in the root project.  All we have in the root project are dev dependencies (lerna, typescript, linting, etc).  It may be pulling it in because we are hoisting our lerna bootstrap?

**Comment by holmok** [comment]
I will try to recreate this in a simpler 'non-work' project this weekend.

**Comment by isaacs** [comment]
Maybe dumb question: is it possible that fsevents is checked in, and npm v6 is just trying to rebuild it?

Yes, it is indeed strange that there is an extraneous fsevents in there.  Perhaps it is a (non-optional) peer dep that got pulled in by npm v7, added to the package-lock, and then dutifully put back by npm v6?

It might be informative to run this on your machine that has npm 7 installed:

```js
// fsevents-dependents.js
const Arborist = require(process.argv[2] + '/npm/node_modules/@npmcli/arborist')
const arb = new Arborist()
arb.loadActual().then(tree => {
  for (const fsevents of tree.inventory.query('name', 'fsevents')) {
    console.log(fsevents.path, fsevents.version, fsevents.resolved)
    for (const {from, type, spec, error} of fsevents.edgesIn) {
      console.log([from.location, type, spec, error])
    }
  }
})
```

and then run with:

```
node fsevents-dependents.js "$(npm root -g)"
```

and share the output.

**Comment by holmok** [comment]
Here is the output...

```
[path_omitted]/node_modules/fsevents 1.2.13 https://registry.npmjs.org/fsevents/-/fsevents-1.2.13.tgz
[ 'node_modules/chokidar', 'optional', '^1.2.7', null ]
[
  'packages/api/node_modules/chokidar',
  'optional',
  '~2.3.1',
  'INVALID'
]
[path_omitted]/node_modules/watchpack/node_modules/fsevents 2.3.1 https://registry.npmjs.org/fsevents/-/fsevents-2.3.1.tgz
[
  'node_modules/watchpack/node_modules/chokidar',
  'optional',
  '~2.3.1',
  null
]
[path_omitted]/node_modules/tap/node_modules/fsevents 2.3.1 https://registry.npmjs.org/fsevents/-/fsevents-2.3.1.tgz
[
  'node_modules/tap/node_modules/chokidar',
  'optional',
  '~2.3.1',
  null
]
```

**Comment by holmok** [comment]
guh... after a couple of attempts, I was unable to recreate in a "lab" environment.  We bumped our build containers to node v15 and resolved the issue.  Thanks for looking into this.

**Comment by mlippert** [comment]
For what it's worth, when I saw npm v7 available I upgraded to it also and ran into this exact problem w/ fsevents, and the only dependency I could see for it was optional. This wasn't a CI build, it was on my local linux dev machine.

I didn't try to track it as far as @holmok did (thanks for that and this bug report, even if it did go away for you eventually), I just rolled back to npm v6 which is working fine. I may try npm v7 again, but I'm a little busy currently so I'm not sure when I'll get to it.

**Comment by raymond-h** [comment]
Hey, we are currently hitting this exact issue too. The lockfiles are generated by npm v7, but our CI uses npm v6 to install dependencies, leading to the exact same error as mentioned in the OP.

One of several commits where the issue occurs: https://github.com/CryptoBlades/cryptoblades/commit/8853e90dedc1b8b096c021f920e8d68f55447078 (specifically in the `frontend/` folder)

EDIT 1: After downgrading to lockfileVersion 1 by running `npm install -f` with npm v6 and then upgrading it again to lockfileVersion 2 by running `npm install` with npm v7, the lockfile was fixed in some way such that it now works properly with npm v6 again? https://github.com/CryptoBlades/cryptoblades/compare/aed709d011ef3fd579a59cc8c5e2c334b0144b64...3844f71fb5382f2d2cab86ac0d39ac441edffb7f

**Comment by e-cloud** [comment]
Same problem encountered. here is the log

I was running `npm ci`

```
37 verbose stack Error: Unsupported platform
37 verbose stack     at checkPlatform (/var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_v16/lib/node_modules/npm/node_modules/npm-install-checks/index.js:35:25)
37 verbose stack     at Arborist.[checkPlatform] (/var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_v16/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:244:5)
37 verbose stack     at /var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_v16/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:237:33
37 verbose stack     at async Arborist.buildIdealTree (/var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_v16/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:221:7)
37 verbose stack     at async Promise.all (index 1)
37 verbose stack     at async Arborist.reify (/var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_v16/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:134:5)
37 verbose stack     at async CI.ci (/var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_v16/lib/node_modules/npm/lib/ci.js:73:5)
38 verbose pkgid fsevents@2.3.2
39 verbose cwd /var/jenkins_home/workspace/hx_front_feature_branch
40 verbose Linux 3.10.0-957.el7.x86_64
41 verbose argv "/var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_v16/bin/node" "/var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_v16/bin/npm" "ci"
42 verbose node v16.5.0
43 verbose npm  v7.19.1
44 error code EBADPLATFORM
45 error notsup Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin"} (current: {"os":"linux","arch":"x64"})
46 error notsup Valid OS:    darwin
46 error notsup Valid Arch:  undefined
46 error notsup Actual OS:   linux
46 error notsup Actual Arch: x64
```
