### ISSUE TITLE
[BUG] Update global package, even as root, causes EACCESS

### ISSUE THREAD

**Issue by thany** [npm/cli#2639]
### Current Behavior:
`npm update -g` to update global packages, eider with sudo or as logged in as root, will fail with EACCESS.

### Expected Behavior:
It should update global packages.

### Steps To Reproduce:
1. Run Ubuntu 20.04 on WLS
2. Have Node.js 14.15.4 & NPM 6.14.10 installed via apt ([using this method](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions))
3. Run `sudo npm update -g`, or `sudo -i` followed by `npm update -g`
4. See error:

```
root@Earth2:~# npm -g update
npm ERR! code EACCES
npm ERR! syscall rename
npm ERR! path /usr/lib/node_modules/.staging/npm-18aca6f9/node_modules/yargs-parser
npm ERR! dest /usr/lib/node_modules/.staging/yargs-parser-b095ed45
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, rename '/usr/lib/node_modules/.staging/npm-18aca6f9/node_modules/yargs-parser' -> '/usr/lib/node_modules/.staging/yargs-parser-b095ed45'
npm ERR!  [OperationalError: EACCES: permission denied, rename '/usr/lib/node_modules/.staging/npm-18aca6f9/node_modules/yargs-parser' -> '/usr/lib/node_modules/.staging/yargs-parser-b095ed45'] {
npm ERR!   cause: [Error: EACCES: permission denied, rename '/usr/lib/node_modules/.staging/npm-18aca6f9/node_modules/yargs-parser' -> '/usr/lib/node_modules/.staging/yargs-parser-b095ed45'] {
npm ERR!     errno: -13,
npm ERR!     code: 'EACCES',
npm ERR!     syscall: 'rename',
npm ERR!     path: '/usr/lib/node_modules/.staging/npm-18aca6f9/node_modules/yargs-parser',
npm ERR!     dest: '/usr/lib/node_modules/.staging/yargs-parser-b095ed45'
npm ERR!   },
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rename',
npm ERR!   path: '/usr/lib/node_modules/.staging/npm-18aca6f9/node_modules/yargs-parser',
npm ERR!   dest: '/usr/lib/node_modules/.staging/yargs-parser-b095ed45'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-06T16_01_06_807Z-debug.log
```

The `.staging` directory in the above error doesn't exist (anymore?) after this command has finished. So either it wasn't able to create it (the root user absolutely can) or it wasn't able to rename it for some reason - but then it's weird that it could be deleted but not renamed.

I've already tried a seemingly popular fix:
```
sudo chown -R $(whoami) /usr/local/lib/node_modules/
```
To no avail.

Permissions seem to be correct:
```
root@Earth2:~# ls -las /usr/local/lib/node_modules/
total 0
0 drwxr-xr-x 1 root root 4096 Aug 28 20:53 .
0 drwxr-xr-x 1 root root 4096 Nov  3 21:53 ..
```

### Environment:
- OS: Ubuntu 20.04 on WLS
- Node: 14.15.4
- npm: 6.14.10

Oh and it might help to [have that log](https://github.com/npm/cli/files/5937170/2021-02-06T16_12_49_852Z-debug.zip) mentioned in the output.

**Comment by robross0606** [comment]
I'm seeing something similar on Windows but the error is _slightly_ different:
```
C:\Code>npm install -g npm@latest
npm ERR! code EPERM
npm ERR! syscall rename
npm ERR! path C:\Program Files\nodejs\node_modules\npm
npm ERR! dest C:\Program Files\nodejs\node_modules\.npm-QXjMEw5N
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Program Files\nodejs\node_modules\npm' -> 'C:\Program Files\nodejs\node_modules\.npm-QXjMEw5N'
npm ERR!  [Error: EPERM: operation not permitted, rename 'C:\Program Files\nodejs\node_modules\npm' -> 'C:\Program Files\nodejs\node_modules\.npm-QXjMEw5N'] {
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Program Files\\nodejs\\node_modules\\npm',
npm ERR!   dest: 'C:\\Program Files\\nodejs\\node_modules\\.npm-QXjMEw5N'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rross\AppData\Local\npm-cache\_logs\2021-02-08T21_55_49_459Z-debug.log
```
[2021-02-08T21_55_49_459Z-debug.log](https://github.com/npm/cli/files/5947071/2021-02-08T21_55_49_459Z-debug.log)

**Comment by robross0606** [comment]
This last time it failed, it completely wiped `npm` from my system.  Now I cannot even run npm at all:
```
C:\Code>npm
'npm' is not recognized as an internal or external command,
operable program or batch file.
```
I had to completely reinstall node.js to get `npm` working again.

**Comment by thany** [comment]
@robross0606 
> I'm seeing something similar on Windows but the error is slightly different

Slightly as in the British nuance of the word 😀
Your problem seems to be quite a different one, mate. It's probably best to open a new issue.

1. I'm having this problem on Linux, which works very differently under the hood. Not better or worse, just different, mind you.
2. The error codes are different. Why it's ACCES (misspelled even) for me and EPERM for you, might seem like the same thing, but I think there's a distinction between the two. Don't quote me on it though.
3. And most importantly, the files where it goes wrong are completely different ones. Where in my case it tried to do stuff in `.staging`, a directory npm itself had created (**and deleted** afterwards!) -- In your case it's to do with npm itself, as you're trying to install npm through npm (a valid thing to do, but different in function). No wonder it's touching different files then, innit.

**Comment by danse** [comment]
Same issue here, with NPM 6.14.11. In my case the error is triggered when trying to downgrade NPM
```
$ sudo npm install -g npm@6.13.4
npm ERR! code EACCES
npm ERR! syscall rename
npm ERR! path /usr/lib/node_modules/.staging/npm-18aca6f9/node_modules/yargs
npm ERR! dest /usr/lib/node_modules/.staging/yargs-765698bc
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, rename '/usr/lib/node_modules/.staging/npm-18aca6f9/node_modules/yargs' -> '/usr/lib/node_modules/.staging/yargs-765698bc'
npm ERR!  [OperationalError: EACCES: permission denied, rename '/usr/lib/node_modules/.staging/npm-18aca6f9/node_modules/yargs' -> '/usr/lib/node_modules/.staging/yargs-765698bc'] {
npm ERR!   cause: [Error: EACCES: permission denied, rename '/usr/lib/node_modules/.staging/npm-18aca6f9/node_modules/yargs' -> '/usr/lib/node_modules/.staging/yargs-765698bc'] {
npm ERR!     errno: -13,
npm ERR!     code: 'EACCES',
npm ERR!     syscall: 'rename',
npm ERR!     path: '/usr/lib/node_modules/.staging/npm-18aca6f9/node_modules/yargs',
npm ERR!     dest: '/usr/lib/node_modules/.staging/yargs-765698bc'
npm ERR!   },
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rename',
npm ERR!   path: '/usr/lib/node_modules/.staging/npm-18aca6f9/node_modules/yargs',
npm ERR!   dest: '/usr/lib/node_modules/.staging/yargs-765698bc'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-08T15_24_07_278Z-debug.log
```
The detailed log doesn't seem to add much info in this case

**Comment by danse** [comment]
Turns out that my Ubuntu was running on WSL 1:
```
> wsl.exe --list -v
  NAME      STATE           VERSION
* Ubuntu    Running         1
```
After updating the version, the `npm` command worked without problems:
```
> wsl.exe --set-version Ubuntu 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Conversion complete.
```

**Comment by thany** [comment]
WSL2 is a no-go, because it uses Hyper-V, which blocks all other virtualization tools.

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
