### ISSUE TITLE
[BUG]  NPX uses cached GIST instead of latest 

### ISSUE THREAD

**Issue by asears** [npm/cli#2641]
### Current Behavior:
Installing from Gist using package.json and js file is a really interesting use of npx.  

Trying this out on Windows, I found it cached the first gist version of the package and any changes to the gist weren't picked up.  

Deleting the cache fixes this.  Is there a command line option to delete the cache?  

### Expected Behavior:

Updating the code in a gist should be picked up by the installer as a difference or change, or installed each time npx is run.

### Steps To Reproduce:

Running npx 7.5.1 from a Windows command line, I was able to replicate by simply creating a basic gist with an error, then trying to fix it.

https://gist.github.com/asears/cf8d95776e13f6472c1fb56b57659400

1. Create a gist with a bug.
2. npx https://my-gist-url
3. Fix the gist
4. npx https://my-gist-url

Cached version will be used rather than latest.

### Environment:

Windows 19041.746.
Node 15.8.0
npm/npx: 7.5.1

**Comment by wraithgar** [comment]
This was fixed in `v7.5.2` https://github.com/npm/cli/issues/2329
