### ISSUE TITLE
`--save-dev` updates peer dep also

### ISSUE THREAD

**Issue by ljharb** [npm/cli#2647]
### Current Behavior:
1. package that has:
```json
"peerDependencies: {
  "webpack": ">=1.11.0"
},
"devDependencies": {
  "webpack": "^4"
},
```

2. run `npm install --save-dev webpack@3`
3. see package.json updated to:
```json
"peerDependencies: {
  "webpack": "^3.12.0"
},
"devDependencies": {
  "webpack": "^3"
},
```

### Expected Behavior:
The package.json should become:
```json
"peerDependencies: {
  "webpack": ">=1.11.0"
},
"devDependencies": {
  "webpack": "^3"
},
```
or:
```json
"peerDependencies: {
  "webpack": ">=1.11.0"
},
"devDependencies": {
  "webpack": "^3.12.0"
},
```

but since i didn't use `--save-peer` (or `--save` by itself, even), the peer dep *must not be touched*.

Separately, this is an entirely unexpected breaking change in my package, since some potential valid peer versions are now invalid, so this could be quite dangerous.

### Steps To Reproduce:
see "current behavior"

### Environment:
- Node: 15.8.0
- npm: 7.5.3

**Comment by ljharb** [comment]
This is still occurring in npm v7.11.2; when I have eslint as a devDep and peerDep with identical ranges, running `npm install --save-dev eslint` updates the peerDep range and does not update the devDep range.

**Comment by wraithgar** [comment]
There is a PR linked that addresses this and many other save-type bugs discovered while triaging this.
