### ISSUE TITLE
Cannot installing the github (ssh request and http request) repositories

### ISSUE THREAD

**Issue by nonusx** [npm/cli#2658]
### Current Behavior:
Try `npm i -S git@github.com:368573607/scratch_file_analyze.git` return a error, error code: -4068.

Detailed:
```
PS I:\repositories\web_scratch_file_analyze> npm i -S git@github.com:368573607/scratch_file_analyze
npm ERR! code EISDIR
npm ERR! syscall symlink
npm ERR! path I:\repositories\web_scratch_file_analyze\github.com:368573607\scratch_file_analyze
npm ERR! dest I:\repositories\web_scratch_file_analyze\node_modules\git
npm ERR! errno -4068
npm ERR! EISDIR: illegal operation on a directory, symlink 'I:\repositories\web_scratch_file_analyze\github.com:368573607\scratch_file_analyze' -> 'I:\repositories\web_scratch_file_analyze\node_modules\git'

npm ERR! A complete log of this run can be found in:
npm ERR!     E:\Program Files\nodejs\node_cache\_logs\2021-02-09T13_53_18_893Z-debug.log
```

### Expected Behavior:
I hope the npm can install my repository correctly.

### Steps To Reproduce:
1. Open powershell of windows.10 .
2. Run `npm i -S git@github.com:368573607/scratch_file_analyze`
4. See error...

### Environment:
- OS: Windows 10
- Node: v14.4.0
- npm: 7.5.2

**Comment by ljharb** [comment]
Can you try with npm v7.5.3?

**Comment by nlf** [comment]
this is a bug that's causing the cli to think you're trying to install a dependency named `git` from a directory named `github.com:368573607/scratch_file_analyze` which is clearly wrong. we'll get that fixed!

as a workaround, you can do any of the following:
- `npm i git+ssh://git@github.com:368573607/scratch_file_analyze`
- `npm i github:368573607/scratch_file_analyze`
- `npm i 368573607/scratch_file_analyze`
