### ISSUE TITLE
[BUG] Custom install script of bundled dependency fails when parent package is globally installed with prefix

### ISSUE THREAD

**Issue by t1m0thyj** [npm/cli#2659]
### Current Behavior:

NPM v7 fails to find bins called in the custom install script of a package, under these conditions:
* The package with a custom install script (e.g., keytar) is included as a bundled dependency
* The package that includes it is installed with both the `--global` and `--prefix` flags specified
```
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c prebuild-install || node-gyp rebuild
npm ERR! 'prebuild-install' is not recognized as an internal or external command,
npm ERR! operable program or batch file.
```

### Expected Behavior:

Packages with custom install scripts should always install successfully, even when bundled as part of a package being installed with the `npm install -g --prefix . <pkgName>` command.

### Steps To Reproduce:

Download TGZ from [this minimal sample repo](https://github.com/t1m0thyj/npm7-bundled-dep-issue/releases/tag/v1.0.0) and install with `npm install -g --prefix . <tgzName>`. Or follow the steps below:
1. Create an NPM project: `npm init -y`
2. Install a dependency with custom install script: `npm install keytar`
3. Define the `bundledDependencies` property in package.json:
  `"bundledDependencies": [ "keytar" ]`
4. Package the NPM project: `npm pack`
5. Copy the TGZ to another folder and run `npm install -g --prefix . <tgzName>`
6. Install fails with error that "prebuild-install" command was not found

### Environment:

- OS: fails on Windows 10 2004, works on Ubuntu 18.04
- Node: 14.15.4
- npm: 7.5.3

**Comment by darcyclarke** [comment]
@t1m0thyj thanks for filing! We're going to double-check if this was fixed or not in the latest release (ie. `npm i -g npm@latest` - `7.5.4`) as we made some changes here to resolve other Windows/symlink issues we've seen

**Comment by t1m0thyj** [comment]
@darcyclarke FYI this issue still exists in npm@latest (7.24).

**Comment by t1m0thyj** [comment]
This seems to have been fixed, thanks 😀 The earliest version containing the fix is:
* Node.js 16.14.0 if using the bundled version of npm
* npm@8.5.5 if using a globally installed version of npm
