### ISSUE TITLE
[BUG] Running an npm command in a script is running it under the npm version installed with node

### ISSUE THREAD

**Issue by ymor** [npm/cli#2665]
### Current Behavior:
Running an npm command in a script is using the npm version installed with node and not the globally installed version

### Expected Behavior:
The npm command in the script should use the globally installed npm version

### Steps To Reproduce:
Install node v14.15.5.
Install npm 7.5.3
Running `npm --version` reports 7.5.3

Then run `npm test` against the following package.json 
`{
  "scripts": {
    "test": "npm --version"
  }
}
`
You will receive the following output 

> test
> npm --version
6.14.11

### Environment:

- OS: Windows 10 x64
- Node: v14.15.5
- npm: 7.5.3

**Comment by ljharb** [comment]
What do you mean, installed with node? Does your local node_modules contain npm? What happens if your test script outputs `which npm`?

**Comment by ymor** [comment]
I'm on windows so which isn't available.  If I run it with verbose I get the following:

>npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Users\\USERNAME\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'test',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@7.5.3
npm info using node@v14.15.5
npm timing config:load:defaults Completed in 3ms
npm timing config:load:file:C:\Users\USERNAME\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 3ms
npm timing config:load:builtin Completed in 3ms
npm timing config:load:cli Completed in 5ms
npm timing config:load:env Completed in 1ms
npm timing config:load:file:E:\Source\.npmrc Completed in 0ms
npm timing config:load:project Completed in 1ms
npm timing config:load:file:C:\Users\USERNAME\.npmrc Completed in 2ms
npm timing config:load:user Completed in 2ms
npm timing config:load:file:C:\Program Files\nodejs\etc\npmrc Completed in 1ms
npm timing config:load:global Completed in 1ms
npm timing config:load:cafile Completed in 0ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:setUserAgent Completed in 2ms
npm timing config:load:setEnvs Completed in 2ms
npm timing config:load Completed in 20ms
npm verb npm-session 0f6d7cdc5dc34c03
npm timing npm:load Completed in 77ms
[..................] \ : timing npm:load Completed in 77ms
 > test
 > npm --version

>npm info it worked if it ends with okoad Completed in 77ms
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'prefix',
npm verb cli   '-g'
npm verb cli ]
npm info using npm@6.14.11
npm info using node@v14.15.5
npm verb exit [ 0, true ]timing npm:load Completed in 77ms
npm timing npm Completed in 81ms
npm info ok
6.14.11............] \ : timing npm:load Completed in 77ms
npm timing command:run-script Completed in 876ms
npm timing command:test Completed in 886ms
npm verb exit 0
npm timing npm Completed in 1326ms
npm info ok


As you can see the first part was using npm installed under my user profile, but the second was using the node_modules under the nodejs install.

**Comment by wandyezj** [comment]
@ymor The following script should allow you to report the versions.

versions.cmd

```batch
@echo off
setlocal

call :check npm --version
call :check node --version
call :check git --version

goto :eof

:check

set name=%1
set version=%2

echo.
echo.
echo %name%
call %name% %version%
where %name%


```

**Comment by ymor** [comment]
Just a quick update, it looks like between 7.5.3 and 7.6.0 my issue has been resolved.  It is now reporting the version I would expect.

> npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Users\\USERNAME\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'test',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@7.6.0
npm info using node@v14.15.5
npm timing config:load:defaults Completed in 2ms
npm timing config:load:file:C:\Users\USERNAME\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 4ms
npm timing config:load:builtin Completed in 4ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 1ms
npm timing config:load:file:E:\Source\.npmrc Completed in 0ms
npm timing config:load:project Completed in 1ms
npm timing config:load:file:C:\Users\USERNAME\.npmrc Completed in 1ms
npm timing config:load:user Completed in 1ms
npm timing config:load:file:C:\Users\USERNAME\AppData\Roaming\npm\etc\npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:cafile Completed in 1ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:setUserAgent Completed in 1ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 14ms
npm verb npm-session cb4db13da6d55683
npm timing npm:load Completed in 538ms
[..................] \ : timing npm:load Completed in 538ms
> test
> npm --version

> npm info it worked if it ends with okoad Completed in 538ms
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'prefix',
npm verb cli   '-g'] \ : timing npm:load Completed in 538ms
npm verb cli ].....] \ : timing npm:load Completed in 538ms
npm info using npm@6.14.11iming npm:load Completed in 538ms
npm info using node@v14.15.5ing npm:load Completed in 538ms
 verb exit [ 0, true ]] \ : timing npm:load Completed in 538ms
npm timing npm Completed in 469ms
npm info ok
npm verb cli [.....] \ : timing npm:load Completed in 538ms
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Users\\USERNAME\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   '--version'iming npm:load Completed in 538ms
npm verb cli ]
npm info using npm@7.6.0
npm info using node@v14.15.5
npm timing config:load:defaults Completed in 3ms
npm timing config:load:file:C:\Users\USERNAME\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 3ms
npm timing config:load:builtin Completed in 3ms
npm timing config:load:cli Completed in 3ms
npm timing config:load:env Completed in 2ms
npm timing config:load:file:E:\Source\.npmrc Completed in 0ms
npm timing config:load:project Completed in 1msted in 538ms
npm timing config:load:file:C:\Users\USERNAME\.npmrc Completed in 2ms
npm timing config:load:user Completed in 2mspleted in 538ms
npm timing config:load:file:C:\Users\USERNAME\AppData\Roaming\npm\etc\npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:cafile Completed in 0ms
npm timing config:load:validate Completed in 1msed in 538ms
npm timing config:load:setUserAgent Completed in 0ms
npm timing config:load:setEnvs Completed in 1msted in 538ms
npm timing config:load Completed in 17ms
npm verb npm-session 1ef54ee56f789be5
npm timing npm:load Completed in 472msad Completed in 538ms
7.6.0
npm verb exit 0
npm timing npm Completed in 777ms
 pm info ok[..................] \ : timing npm:load Completed in 538ms
npm timing command:run-script Completed in 2367ms
npm timing command:test Completed in 2431ms
npm verb exit 0
npm timing npm Completed in 3392ms
npm info ok
