### ISSUE TITLE
[BUG] Undocumented (?) change in prepublishOnly/prepare behavior in v7

### ISSUE THREAD

**Issue by Conduitry** [npm/cli#2668]
### Current Behavior:
If there are both `prepare` and `prepublishOnly` scripts, then `npm publish` runs them in a different order in v7 than it did in v6.

### Expected Behavior:
v7 should run these in the same order as v6, or this difference should be documented somewhere.

### Steps To Reproduce:
1. In an empty directory, create a `package.json` containing:
```json
{
        "name": "test",
        "version": "0.0.0",
        "scripts": {
                "prepare": "echo prepare >> scripts.log",
                "prepublishOnly": "echo prepublishOnly >> scripts.log"
        }
}
```
2. Run `npm publish` (aborting out of 2FA prompt, etc.)
3. `cat scripts.log`

On npm@6.14.11, this file contains:
```
prepare
prepublishOnly
```

On npm@7.5.3, this file contains:
```
prepublishOnly
prepare
```

Is this an intended change or is it a bug? I didn't see anything in the 7.0.0 changelog about this, nor did I see any relevant differences between https://docs.npmjs.com/cli/v6/using-npm/scripts and https://docs.npmjs.com/cli/v7/using-npm/scripts.

### Environment:
- OS: Ubuntu 20.04
- Node: 15.8.0
- npm: 7.5.3

**Comment by wraithgar** [comment]
Updating the scripts to reflect the new lifecycle is in our backlog now. https://github.com/npm/statusboard/issues/267
