### ISSUE TITLE
[BUG] npm ls no longer displays full tree

### ISSUE THREAD

**Issue by jpike88** [npm/cli#2669]
I have to add this annoying --depth flag every time. When would I NOT want to see the full tree, it's why I'm doing npm ls to start with...

This in addition to having to use --force half the time with my angular projects is starting to make v7 feel like a downgrade than an upgrade. Peer dependency mismatch is a fact of life. 

It's feeling like these are 'improvements/tweaks' for the sake of them. Can this be an opportunity to review whether this is a case of trying to fix what's not broken?

**Comment by darcyclarke** [comment]
@jpike88 Appreciate you filing this; We introduced a new flag `--all` in v7 (ie. `npm ls --all` would be how you see all your deps)

**Comment by ljharb** [comment]
@darcyclarke it is unfortunate tho, that it’s not the default on npm ls :-/

**Comment by darcyclarke** [comment]
@ljharb we should start creating a list of "opt-in" configs we'd like to consider for being the "defaults" come v8 tbh (maybe a good RFC call note/issue)
