### ISSUE TITLE
[BUG] <npm ERR! cb() never called!>

### ISSUE THREAD

**Issue by srikrishnaseshadri** [npm/cli#2673]
#I am getting cb() never call error and the following ! 

npm WARN deprecated package.json@2.0.1: Use pkg.json instead.
npm ERR! cb() never called!

**Comment by ploconsoleAltea** [comment]
Resolved?

**Comment by isaacs** [comment]
https://github.com/npm/cli/wiki/%22cb()-never-called%3F--I'm-having-the-same-problem!%22

We need much more information to even get started on this.

Start with filling out the sections in the issue template, and including the entire error message.  It would also be good to share the `npm-debug.log` file that was generated when it failed.

Closing for now, happy to re-open if more info is provided.  Thanks!
