### ISSUE TITLE
[BUG] Bad time unit symbol in messages

### ISSUE THREAD

**Issue by PhiLhoSoft** [npm/cli#2674]
### Current Behavior:

After removing and updating some versions (with ncu), I see the following message:

> added 1 package, removed 32 packages, changed 26 packages, and audited 3210 packages in 3m

I don't understand this three meters result!

### Expected Behavior:

> added 1 package, removed 32 packages, changed 26 packages, and audited 3210 packages in 3min

I guess it was about minutes (the computer froze for a while…).
Please, check the SI units on Wikipedia for accurate unit abbreviations… 😎

### Steps To Reproduce:

ncu -u -i
npm i

### Environment:

- Windows 10
- node -v
v15.6.0
- npm -v
7.4.0

Yes, I am nitpicking, but it was really puzzling for a while.

**Comment by darcyclarke** [comment]
@PhiLhoSoft appreciate this... we thought we got pretty **far** with v7... but we have more work to do to go the **distance**... we didn't mean to give you a bad **time**... looks like a quick/simple win for a first contribution -> the right place to update this is in: https://github.com/vercel/ms#readme

**Comment by ruyadorno** [comment]
ref: https://github.com/vercel/ms/issues/134

**Comment by getsnoopy** [comment]
@PhiLhoSoft thanks for this. If you upvote the issue linked above (in vercel/ms), it's more likely to get fixed.
