### ISSUE TITLE
While deleting multiple user from Client people picker "@types/sharepoint": "^2016.1.9"

### ISSUE THREAD

**Issue by shashikeshmishra** [npm/cli#2675]
Hello,

I am facing an issue while deleting the users from multiple client people picker and it through below error. but If there is only one user then there no issue.

clientpeoplepicker.js:1 Uncaught TypeError: Cannot read property 'id' of undefined
    at SPClientPeoplePicker.IterateEachProcessedUser (clientpeoplepicker.js:1)
    at eval (Utility.ts:561)
    at EnsureScript (init.js?rev=CTlEK1ishYGuWd%2B3Naie2A%3D%3DTAG0:1)
    at Object.EnsureScriptFunc [as executeFunc] (init.js?rev=CTlEK1ishYGuWd%2B3Naie2A%3D%3DTAG0:1)
    at Function.Utility.setPicker (Utility.ts:554)
    at Function.Utility.SetControlsValue (Utility.ts:936)
    at Function.Utility.SaveRequestDetails (Utility.ts:915)
    at Function.events.SaveClick (events.ts:115)
    at eval (events.ts:58)

**Comment by shashikeshmishra** [comment]
public static setPicker(ppElement: string, userName: string): void {

        var ppId = ppElement + "_TopSpan";
        SP.SOD.executeFunc('clientpeoplepicker.js', 'SPClientPeoplePicker', function () {
            let peoplePicker: SPClientPeoplePicker = SPClientPeoplePicker.SPClientPeoplePickerDict[ppId];
            let c: number = peoplePicker.TotalUserCount;
            if (c > 0) {

                for (let i = 0; i < c; i++) {
                    eval("peoplePicker.DeleteProcessedUser()");
                }
                // peoplePicker.IterateEachProcessedUser(function (index, user) {
                //     peoplePicker.DeleteProcessedUser(document.getElementById(user.UserContainerElementId));                    
                // });
            }

            peoplePicker.AddUserKeys(userName, false);

        });
    }

below code work fine but that is exists in @SharePoint module.

for (let i = 0; i < c; i++) {
    eval("peoplePicker.DeleteProcessedUser()");
}

**Comment by shadowspawn** [comment]
These do not look like problems with the npm utility. You probably want to report them or ask about them somewhere else. (sharepoint?)
