### ISSUE TITLE
npm install -g @vue/cli ERROR

### ISSUE THREAD

**Issue by Fcscanf** [npm/cli#2677]
### Current Behavior:

npm install -g @vue/cli
### Expected Behavior:

Install Success
### Steps To Reproduce:

npm install -g @vue/cli
![image](https://user-images.githubusercontent.com/27654200/107659818-8bcf3580-6cc2-11eb-8b59-0b4b25d79e8f.png)

### Environment:

OS：Window10
Node：v14.2.0
npm：7.5.2

**Comment by darcyclarke** [comment]
@Fcscanf can you try reproducing this on the latest version of `v7` (ie. `npm i -g npm`)?

**Comment by Fcscanf** [comment]
@darcyclarke Yes, I have recovered, thank you
