### ISSUE TITLE
NPM on Windows is borked - Multiple fixes failed

### ISSUE THREAD

**Issue by GibMirDieFlasche** [npm/cli#2694]
NPM version 7.5.1 on Windows - Trouble started when an old project folder was deleted. All I get is error messages with npm start. npm init works fine, but cannot get npm start to work.

Have tried three uninstall/reinstalls
Have done npm cache clean --force, and also just npm install in the terminal.
Have also tried creating new project folders with npm init and the npm install. These both go through with no bother. But then npm start and errors.

Here's the latest error message from npm start attempt followed by the output n the debug log:

The error message after npm start:

npm ERR! code ENOENT
npm ERR! syscall spawn bash
npm ERR! path C:\cp\urc\project
npm ERR! errno -4058
npm ERR! enoent spawn bash ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

Debug log:

0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'start'
0 verbose cli ]
1 info using npm@7.5.1
2 info using node@v15.8.0
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 4ms
5 timing config:load:builtin Completed in 4ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:C:\cp\urc\project\.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:C:\Users\<username>\.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:C:\Users\<username>\AppData\Roaming\npm\etc\npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 11ms
19 verbose npm-session 712ca28904566069
20 timing npm:load Completed in 23ms
21 timing command:run-script Completed in 39ms
22 timing command:start Completed in 218ms
23 verbose stack Error: spawn bash ENOENT
23 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
23 verbose stack     at onErrorNT (node:internal/child_process:480:16)
23 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:81:21)
24 verbose pkgid package.json@1.0.0
25 verbose cwd C:\cp\urc\project
26 verbose Windows_NT 6.3.9600
27 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
28 verbose node v15.8.0
29 verbose npm  v7.5.1
30 error code ENOENT
31 error syscall spawn bash
32 error path C:\cp\urc\project
33 error errno -4058
34 error enoent spawn bash ENOENT
35 error enoent This is related to npm not being able to find a file.
36 verbose exit -4058

**Comment by kevin-lane** [comment]
I am having the exact same issue and get the exact same error. I have also done what you have done to try to solve the problem without any luck. Did you find a solution to this problem? Thanks
