### ISSUE TITLE
[BUG] npm should use PowerShell by default on Windows

### ISSUE THREAD

**Issue by Stanzilla** [npm/cli#2699]
The problem here is that cmd does not work with a few things that are now part of a Windows developer's daily workflow, like using WSL and it's network shared file system. cmd does not understand UNC file paths and therefore npm is broken by default when you first try to use it. Yes the default shell and default script shell can be changed but there is no reason why the default should still be cmd in the first place, imo.

### Current Behavior:

npm on Windows uses the old cmd instead of PowerShell

### Expected Behavior:

npm should use PowerShell by default

**Comment by nlf** [comment]
changing the default shell would constitute a breaking change so this is unlikely to happen in npm 7 without further discussion. you might consider putting this suggestion through our rfc process, described here: https://github.com/npm/rfcs#rfc-process

**Comment by wraithgar** [comment]
Closing, as per nlf's comments. This would need to be an RFC to change the default like this, and would also be a breaking change.
