### ISSUE TITLE
[BUG] incomplete lock file is generated for workspaces on first install

### ISSUE THREAD

**Issue by targos** [npm/cli#2700]
### Current Behavior:

After installing the dependencies in an npm workspace for the first time, running npm install a second time changes the package-lock.json: a "name" field is added to the sub-packages metadata.

### Expected Behavior:

Running `npm install` right after creation of the package-lock.json shouldn't change it.

### Steps To Reproduce:

You can reproduce with the following repo: the last commit contains the package-lock.json created by the first `npm install` call.

```
git clone https://github.com/targos/npm-workspace-lock.git
cd npm-workspace-lock
npm install
git diff
```

```diff
diff --git a/package-lock.json b/package-lock.json
index 4ab3edc..57665a3 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -21611,12 +21611,14 @@
       }
     },
     "one": {
+      "name": "npm-workspace-lock-one",
       "version": "1.0.0",
       "dependencies": {
         "got": "^11.8.1"
       }
     },
     "two": {
+      "name": "npm-workspace-lock-two",
       "version": "1.0.0",
       "devDependencies": {
         "react-scripts": "^4.0.1"
```

### Environment:

- OS: Windows 10, macOS
- Node: 15.8.0
- npm: 7.5.4

**Comment by targos** [comment]
FWIW I can still reproduce with v7.6.3

**Comment by darcyclarke** [comment]
@targos can you try replicating on latest again? (ie. `npm i -g npm`) latest should be `v7.16.0` at the moment.

**Comment by targos** [comment]
Seems fixed!

**Comment by JanMisker** [comment]
I still have the same problem, I'm on npm 7.20.2

**Comment by danielpza** [comment]
I have the same problem on npm 8.10.0
