### ISSUE TITLE
[BUG] cpu and os properties not respected

### ISSUE THREAD

**Issue by eduardoboucas** [npm/cli#2707]
At Netlify, we publish [a module](https://www.npmjs.com/package/@netlify/traffic-mesh-agent) that relies on a platform-specific binary.

In order to only install the appropriate binary for the user's machine, we publish [several platform-specific modules](https://www.npmjs.com/search?q=%40netlify%2Ftraffic-mesh-agent), with `package.json` appropriately tagged with the right `cpu` and `os` properties. The main module lists all the platform-specific modules as `optionalDependencies`, so that when installed, any platform-specific module that doesn't apply to the user's machine will be skipped, leaving them only with the right module installed in the end.

This behaviour broke with npm v7.

### Current Behavior:
When installing `@netlify/traffic-mesh-agent`, all the optional dependencies are installed, regardless of whether they apply to the user's platform.

### Expected Behavior:
When installing `@netlify/traffic-mesh-agent`, only the optional dependencies that apply to the user's platform are actually installed. The others are skipped at the installation process.

### Steps To Reproduce:
1. Run `npm install @netlify/traffic-mesh-agent`
2. Verify that 3 platform-specific modules are present inside `node_modules`: `@netlify/traffic-mesh-agent-darwin-x64`, `@netlify/traffic-mesh-agent-win32-x64` and `@netlify/traffic-mesh-agent-linux-x64`

### Environment:
- OS: macOS Big Sur 11.2
- Node: 15.8.0
- npm: 7.5.0

**Comment by ljharb** [comment]
I’ve never known “cpu” or “os” properties to matter - i see them [here](https://www.unpkg.com/browse/@netlify/traffic-mesh-agent-darwin-x64@0.27.10/package.json), but can you link to the docs that indicate these are supported properties in package.json?

**Comment by eduardoboucas** [comment]
> I’ve never known “cpu” or “os” properties to matter - i see them here, but can you link to the docs that indicate these are supported properties in package.json?

Sure: [cpu](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#cpu) and [os](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#os).

**Comment by ljharb** [comment]
TIL, thank you :-)
