### ISSUE TITLE
[BUG] (Security issue) npm install always uses registry version of package even when git+ssh is used 

### ISSUE THREAD

**Issue by tlbdk** [npm/cli#2712]
### Current Behavior:

npm install --verbose sd-notify@git@github.com:connectedcars/node-sd-notify.git

Will install the registry version of package even though git url is used.

This means that if you are using private git+ssh dependencies someone can uploads a package with the same name/alias to npmjs it will get installed instead of the private git+ssh version you are expecting. 

This issue was also reported back in 2019 for npm 6.x when using npm ci:

https://npm.community/t/npm-ci-uses-registry-version-of-package-even-if-it-has-resolved-custom-git-url/9153

Also why this is a problem explained a bit more sensational:
https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610

### Expected Behavior:

Install the git+ssh version as "npm install" in npm 6.x.

### Steps To Reproduce:

1. npm init -y
2. npm install --verbose sd-notify@git@github.com:connectedcars/node-sd-notify.git
3. verify that the package installed is the npmjs version

### Environment:

Tested on Mac and Linux

**Comment by nlf** [comment]
i'm unable to reproduce this in npm 7.5.4, but you're missing some information from the environment section of our issue template. what version of node are you using? what version of npm?

how are you verifying that what you're getting is the registry version and not the one from the git repo?

if i create a new directory and run your exact command above, i get a package-lock.json that shows that it resolved to the correct git repo, and the package on disk matches what i see in that repo.

**Comment by tlbdk** [comment]
@nlf I'm also unable to reproduce it now, we were having other issues with git+ssh dependencies not building on install so we were trying a lot of different things including downgrading to older npm versions so it's likely I was testing against an older version. Sorry and thanks for looking at it, I will close the issue for now.
