### ISSUE TITLE
[BUG] Running `npm install` updates package.json timestamp

### ISSUE THREAD

**Issue by coreyfarrell** [npm/cli#2714]
### Current Behavior:
Running `npm install` with no arguments causes the timestamp of package.json to be touched.

### Expected Behavior:
package.json should not be written.

### Steps To Reproduce:

1. Enter a directory with a valid `package.json`, observe the timestamp.
2. Run `npm install`
3. See that the package.json timestamp is updated.
4. Wait a minute and repeat step 2-3, you see will se timestamp update again.

### Environment:
- OS: Fedora 32
- Node: 15.8.0
- npm: 7.5.4

### Additional comment

This creates problems/annoyances for other programs that are watching for file updates.  In my case running `npm install` causes my text editor to ask if I want to reload the file.

**Comment by lumaxis** [comment]
Looks like this should have been fixed in 7.5.5, can this issue be closed?
@coreyfarrell Have you had a chance to validate that you're not seeing this anymore with the latest fixes?

**Comment by coreyfarrell** [comment]
Yes this appears to be resolved (tested with 7.6.0).
