### ISSUE TITLE
[BUG] Using `--` to pass additional arguments incorrectly wraps those arguments in quotes

### ISSUE THREAD

**Issue by Pomax** [npm/cli#2720]
### Current Behavior:

Using `--` to pass additional arguments incorrectly wraps those arguments in quotes

### Expected Behavior:

Using `--` to pass additional arguments does what https://docs.npmjs.com/cli/v6/commands/npm-run-script claims it will do:

> npm will pass all the arguments after the -- directly to your script:

I take "directly" here to mean "without any kind of rewriting"

### Steps To Reproduce:

a package.json with:

```json
"scripts": {
  "x": "echo test",
  "y": "npm run x -- --flag"
}

```

shows:

```
npm run y               

> y
> npm run x -- --flag

> x
> echo test "--flag"

test --flag
```

instead of

```
npm run y               

> y
> npm run x -- --flag

> x
> echo test --flag

test --flag
```

### Reason this is a bug

this makes it impossible to forward flags with escaped quotes. For example, passing a quoted string (in which the quotes must be preserved) to `esbuild` becomes impossible:

```json
"scripts": {
    "esbuild:base": "esbuild --bundle --loader:.js=jsx --loader:.jsx=jsx",
    "esbuild:base:main": "npm run esbuild:base -- ./source/js/main.js --outfile=./network-api/networkapi/frontend/_js/main.js",
    "esbuild:dev:main": "npm run esbuild:base:main -- --define:process.env.NODE_ENV=\\\"development\\\" --watch"
}
```

Note the escaped `development` string, which is escaped once so `"` doesn't break the script string, and escaped a second time so that it's passed correctly as CLI argument.

This should run, but instead because things get wrapped in quotes, this errors out:

```
npm run esbuild:dev:main

> esbuild:dev:main
> npm run esbuild:base:main -- --define:process.env.NODE_ENV=\"development\" --watch


> esbuild:base:main
> npm run esbuild:base -- ./source/js/main.js --outfile=./network-api/networkapi/frontend/_js/main.js "--define:process.env.NODE_ENV=\\development\\" "--watch"


> esbuild:base
> esbuild --bundle --loader:.js=jsx --loader:.jsx=jsx "./source/js/main.js" "--outfile=./network-api/networkapi/frontend/_js/main.js" "--define:process.env.NODE_ENV=\\\\development\\\\" "--watch"

> error: Invalid define value (must be valid JSON syntax or a single identifier): \\\\development\\\\
```

Note the line above the error: we suddenly have quoted arguments in which `--define:process.env.NODE_ENV=\\\"development\\\"` has been rewritten such that it actually _loses quotes_: `"--define:process.env.NODE_ENV=\\\\development\\\\"` no longer has a quote preceding the `d` in `development`. 

Nothing should be rewriting args passed further along with `--`, those should stay exactly as they were.

### Environment:

Windows 10 Pro x64
Node 15..8.0
npm 7.3.0

**Comment by EdisonHarada** [comment]
NPM is removing double quotes from any part of the command:

In my case I have:
```
....
  "scripts": {
    "download": "FOR /F \"tokens=*\" %i IN ('git rev-parse --abbrev-ref HEAD') DO crowdin download --branch %i"
  },
...
```

It tries to execute as:
`FOR /F tokens=* ^%i IN ("git rev-parse --abbrev-ref HEAD") DO crowdin download --branch ^%i`

Instead of:
`FOR /F "tokens=*" ^%i IN ("git rev-parse --abbrev-ref HEAD") DO crowdin download --branch ^%i`

I tried escaping in other ways but didn't work :/

**Comment by Pomax** [comment]
That does not look like it's related to using `--` for runtime argument forwarding, so you might want to file that as a new, separate issue (it _might_ be related, but that's something that the npm folks can determine).

**Comment by wraithgar** [comment]
This was fixed in run-script here: https://github.com/npm/run-script/pull/22 and should be included w/ the next npm release (going out this week)

**Comment by EdisonHarada** [comment]
@wraithgar It's working like a charm.

I think you can close this one 👍

**Comment by cyberbiont** [comment]
I am on npm 7.11.0 and problem with arguments passed in quotes is still here.
Not sure if this is directly related, but I cannot pass arguments to the executable that is called in the npm script.
For example
```npm
.... 
"scripts": { 
    "g": "gulp"
    "tasks": "npm run g -- --tasks"
}
```
If I run `npm run tasks`, a list of gulp tasks is shown.
In contrast, executing `npm run g -- --tasks` directly from the command line (that I believe in this case should invoke gulp with --tasks argument) and gulp starts executing default gulp task.

if I change 'g' task to `echo gulp`, `npm run g -- --tasks` from CLI prints `gulp "--tasks"`

**Comment by wraithgar** [comment]
@cyberbiont please open a new issue for this, as this was specifically a windows wrapping bug, and yours may be different in ways the issue template should show us.
