### ISSUE TITLE
run 'npm install' can not setup dependencies

### ISSUE THREAD

**Issue by githubczy** [npm/cli#2722]
message is:
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t https://github.com/jlisee/protobuf.js.git
npm ERR! 
npm ERR! fatal: unable to access 'https://github.com/jlisee/protobuf.js.git/': Couldn't connect to server
npm ERR! 
npm ERR! exited with error code: 128

the log is:
4432 verbose stack Error: exited with error code: 128
4432 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/util/finished.js:12:19)
4432 verbose stack     at ChildProcess.emit (events.js:315:20)
4432 verbose stack     at maybeClose (internal/child_process.js:1048:16)
4432 verbose stack     at Socket.<anonymous> (internal/child_process.js:439:11)
4432 verbose stack     at Socket.emit (events.js:315:20)
4432 verbose stack     at Pipe.<anonymous> (net.js:673:12)
4433 verbose cwd /Users/zhiyongchen/Czy/ow-client
4434 verbose Darwin 19.6.0
4435 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
4436 verbose node v14.15.4
4437 verbose npm  v6.14.10
4438 error Error while executing:
4438 error /usr/bin/git ls-remote -h -t https://github.com/jlisee/protobuf.js.git
4438 error
4438 error fatal: unable to access 'https://github.com/jlisee/protobuf.js.git/': Couldn't connect to server
4438 error
4438 error exited with error code: 128
4439 verbose exit [ 1, true ]

what should I do to fixed it ?

**Comment by ystz999** [comment]
Yes i have this problem too

**Comment by nlf** [comment]
i can't reproduce this in the latest npm 7 (7.5.4)

```
> npm i https://github.com/jlisee/protobuf.js.git

added 14 packages, removed 4 packages, and audited 206 packages in 15s

found 0 vulnerabilities
```

please reopen this issue and be sure to fill out our template with as much information as possible.
