### ISSUE TITLE
[BUG]  the --long command is not giving expected results

### ISSUE THREAD

**Issue by PhilipAbed** [npm/cli#2724]
### Current Behavior:
im trying to run these flags: 
C:\tests\projects\npm\npm7LsSS>npm ls --all --json --long
`npm ERR! Cannot destructure property 'dependencies' of 'node.package' as it is undefined.
{
  "error": {
    "code": null,
    "summary": "Cannot destructure property 'dependencies' of 'node.package' as it is undefined.",
    "detail": ""
  }
}

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\PhilipAbed\AppData\Local\npm-cache\_logs\2021-02-18T15_01_37_387Z-debug.log`

1) the --long --json --all parameters were giving me "_deduped" field in the json result.. now it doesnt!
2) the error you see above is shown differently without the --long flag

### Expected Behavior:
on the same project im running npm ls --all --json
without `--long`

im gettting tree +  error stream:
```
npm ERR! code ELSPROBLEMS
npm ERR! missing: node-sass@^4.0.0, required by sass-loader@8.0.2
npm ERR! missing: sass@^1.3.0, required by sass-loader@8.0.2
{
  "error": {
    "code": "ELSPROBLEMS",
    "summary": "missing: node-sass@^4.0.0, required by sass-loader@8.0.2\r\nmissing: sass@^1.3.0, required by sass-loader@8.0.2",
    "detail": ""
  }
}

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\PhilipAbed\AppData\Local\npm-cache\_logs\2021-02-18T15_01_23_184Z-debug.log
```
### Steps To Reproduce:
install any dependency using npm install [package]
delete it manually from node_modules
run "npm ls --all --json --long"

### Environment:
- OS: windows
- Node: 1.15.7
- npm: 7.5.1

**Comment by nlf** [comment]
i want to be sure i'm understanding your issue correctly, is the problem only the missing `_deduped` field in the json result?

i believe that if you update to the latest npm 7 release (7.9.0 as of this moment) that the error you were getting should be fixed, but i want to make sure we're not missing anything here.

**Comment by PhilipAbed** [comment]
yes its those 2 issues, the error  and the missing deduped... i dont care about the deduped anymore i worked around that manually using paths..
so if error is fixed thank you
