### ISSUE TITLE
[BUG] unsupported engine yet installed

### ISSUE THREAD

**Issue by alanpurple** [npm/cli#2728]
### Current Behavior:

warnings - unsupported engine

### Expected Behavior:

no such warnings

### Environment:

```
alan@AlanWS:~$ sudo npm install -g @angular/cli
[sudo] password for alan:
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular/cli@11.2.1',
npm WARN EBADENGINE   required: { node: '>= 10.13.0', npm: '^6.11.0', yarn: '>= 1.13.0' },
npm WARN EBADENGINE   current: { node: 'v15.9.0', npm: '7.5.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/architect@0.1102.1',
npm WARN EBADENGINE   required: { node: '>= 10.13.0', npm: '^6.11.0', yarn: '>= 1.13.0' },
npm WARN EBADENGINE   current: { node: 'v15.9.0', npm: '7.5.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/core@11.2.1',
npm WARN EBADENGINE   required: { node: '>= 10.13.0', npm: '^6.11.0', yarn: '>= 1.13.0' },
npm WARN EBADENGINE   current: { node: 'v15.9.0', npm: '7.5.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/schematics@11.2.1',
npm WARN EBADENGINE   required: { node: '>= 10.13.0', npm: '^6.11.0', yarn: '>= 1.13.0' },
npm WARN EBADENGINE   current: { node: 'v15.9.0', npm: '7.5.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@schematics/angular@11.2.1',
npm WARN EBADENGINE   required: { node: '>= 10.13.0', npm: '^6.11.0', yarn: '>= 1.13.0' },
npm WARN EBADENGINE   current: { node: 'v15.9.0', npm: '7.5.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@schematics/update@0.1102.1',
npm WARN EBADENGINE   required: { node: '>= 10.13.0', npm: '^6.11.0', yarn: '>= 1.13.0' },
npm WARN EBADENGINE   current: { node: 'v15.9.0', npm: '7.5.3' }
npm WARN EBADENGINE }
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

changed 242 packages, and audited 243 packages in 3s

20 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
alan@AlanWS:~$ npm -v
7.5.3
alan@AlanWS:~$ yarn -v
1.22.10
```

**Comment by ljharb** [comment]
The engines field is purely advisory, so it won’t block an install.

**Comment by vbt-tech** [comment]
I'm really tired, now I have nightmares at night, npm and update processes are breaking my psychology.

**Comment by kzaytsev** [comment]
Just downgrade your node version, it was exactly like topic starter said with node 14+, after downgrade to node v12.16.1 (npm v6.13.4) it's ok.

**Comment by j-alonso-guerra** [comment]
tengo exactamente el mismo error, y ya tengo mucho tiempo de estar intentando, pero no solo es este, tambien es con el npm start, react, etc..., pienso ahora que es mi pc :/

**Comment by marcuspaulo** [comment]
I had this same problem. In my case, it's work with:

###  Downgrade npm version
```sh
npm install npm@6.11.0 -g 
````
instead 

```sh
npm install npm@lastest -g
```

**Comment by alanpurple** [comment]
fixed with npm 7.6.0, closing

**Comment by ranautomationtool** [comment]
It is not fixed. I have npm 7.14 and still have the problem.

**Comment by alanpurple** [comment]
@ranautomationtool 

Yep, I've seen this again too

**Comment by jackpinto** [comment]
Same warning. I have npm 7.16

**Comment by wraithgar** [comment]
By default the engines field is only a WARN.

If you want this to result in a failure you need to configure `engines-strict` flag to true.

**Comment by Sascha-Block** [comment]
Still an issue with dead lock effect...

**Comment by balarayen-blippar** [comment]
Still happens with npm 7.20.0

**Comment by chrisui** [comment]
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '*',
npm WARN EBADENGINE   required: { node: '~14.9.0', npm: '~7.20.0' },
npm WARN EBADENGINE   current: { node: 'v14.17.1', npm: '7.22.0' }
npm WARN EBADENGINE }

**Comment by TonioloF** [comment]
pm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   required: { node: '14.15.5', npm: '6.14.11' },
npm WARN EBADENGINE   current: { node: 'v14.18.0', npm: '7.20.2' }
npm 7.20.2 - 
downgrade cannot be the solution for this error

**Comment by ljharb** [comment]
@TonioloF in your case, the project has precisely pinned the required node/npm versions, so either downgrading to match, or updating what the project requires, are your only options.

**Comment by RS-DU34** [comment]
Same here with 7.24.1
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@schematics/update@0.1101.4',
npm WARN EBADENGINE   required: { node: '>= 10.13.0', npm: '^6.11.0', yarn: '>= 1.13.0' },
npm WARN EBADENGINE   current: { node: 'v16.6.2', npm: '7.24.1' }
npm WARN EBADENGINE }
```

**Comment by ljharb** [comment]
@lflfm that package explicitly requires npm 6, not 7, so you have to downgrade npm to 6, or fix the engines.npm field to allow 7.

**Comment by RS-DU34** [comment]
@ljharb you're right; I misinterpreted the output... my bad. Thanks!

**Comment by robertshort5511** [comment]
this error still occurs 
whatever the required package requires you have to specify that version in the package.json
for example
  "engines": {
    "node": "16.x",
    "npm": "6.x"
  },
this worked for me

**Comment by nimishgoel5600** [comment]
> I had this same problem. In my case, it's work with:
> 
> ### Downgrade npm version
> ```shell
> npm install npm@6.11.0 -g 
> ```
> 
> instead
> 
> ```shell
> npm install npm@lastest -g
> ```

npm install npm@latest -g
