### ISSUE TITLE
Error in creating a react project

### ISSUE THREAD

**Issue by 2180-gideon** [npm/cli#2733]
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Local\npm-cache\_logs\2021-02-19T12_49_01_489Z-debug.log

Aborting installation.
  npm install --save --save-exact --loglevel error react react-dom react-scripts cra-template has failed.

Deleting generated file... node_modules
Deleting generated file... package.json
Deleting bsas-v1/ from D:\
Done.
npm ERR! code 1
npm ERR! path D:\
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c create-react-app bsas-v1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Local\npm-cache\_logs\2021-02-19T12_49_48_722Z-debug.log

**Comment by nlf** [comment]
see https://github.com/npm/cli/issues/417

also please use our issue templates and be sure to fill them out completely or we're pretty limited in what we can do to help you
