### ISSUE TITLE
[BUG] npm 7.5.x is deleting all packages when one package is updated (global)

### ISSUE THREAD

**Issue by JoeUX** [npm/cli#2736]
### Current Behavior:
All my global packages are being deleted when I run an `npm update -g ...` command, except for the package that I'm updating. This has been happening for at least a month. Currently it's happening with npm 7.5.4, but I think it was also happening with earlier 7.5.x releases. See the screenshot below.

### Expected Behavior:
It should just update the specified package. It should not delete any packages.

### Steps To Reproduce:
1. Start with Node 14.15.5 (LTS) on Windows 10 Pro 64-bit.
2. Install the latest npm globally with `npm install -g npm@latest`. Currently this installs **npm 7.5.4**.
3. Install a bunch of packages globally with `npm install -g ...`.
4. Wait a few days for updates to some packages to become available. Check with `npm -g outdated`.
5. Update a package, e.g. `npm update -g eslint`.
6. List your installed packages with `npm ls -g --depth=0`.
7. They're all gone except for the one you just updated (in this case eslint).
8. Check `C:\Users\Joe\AppData\Roaming\npm\node_modules`. All module folders are gone, except for the package you just updated.
9. Check npm version with `npm -g -v`. It says **npm 6.14.10**, probably the version that shipped with Node 14.15.5. npm deleted itself too, at least the updated version.

Screenshot captures everything:

![npm deletion bug](https://user-images.githubusercontent.com/8071692/108539586-0b499f80-7295-11eb-98e0-11dc3ecdd484.JPG)

### Environment:

- OS: Windows 10 Pro 64-bit 20H2
- Node: 14.15.5
- npm: 7.5.4

**Comment by ljharb** [comment]
to update a global eslint, you'd run `npm install -g eslint` - there's no global lockfile, so `npm update` doesn't do anything for you there.

that said, there shouldn't ever be any auto-pruning on `npm root -g`, and this does seem like a bug.

**Comment by greg-hornby-roam** [comment]
This happened to me on version 8.1

**Comment by Michal-Zablocki** [comment]
Just happened to me, never would've expected such behaviour.

I ran `npm install -g @google/gemini-cli`, got information in the process

> npm warn deprecated glob@10.5.0: Old versions of glob are not supported, and contain widely publicized security vulnerabilities, which have been fixed in the current version. Please update. Support for old versions may be purchased (at exorbitant rates) by contacting i@izs.me

So then I ran `npm update -g glob`

Lo and behold, all packages are gone, "npm is not recognized as an internal or external command,
operable program or batch file."

Npm 11.11.0
