### ISSUE TITLE
Error with using create-react-app

### ISSUE THREAD

**Issue by larabakr** [npm/cli#2745]
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenovo\AppData\Roaming\npm-cache\_logs\2021-02-20T16_28_44_860Z-debug.log

**Comment by nlf** [comment]
please see this issue: https://github.com/npm/cli/issues/417 and be sure to complete our issue template
