### ISSUE TITLE
[BUG] error cb() never called! - npm install with windows and docker (node:14.15.5 + npm 6.14.11)

### ISSUE THREAD

**Issue by andycandy-de** [npm/cli#2751]
### Current Behavior:
I get the 'error cb() never called!' when I try to install the project. This error occurs very often, but sometimes it works. I have no idea, sometimes it works and sometimes it fails.

**Logs**
[2021-02-22T10_34_04_555Z-debug.log](https://github.com/npm/cli/files/6021491/2021-02-22T10_34_04_555Z-debug.log)
```
21932 silly extract rxjs@6.6.3 extracted to /usr/src/app/node_modules/.staging/rxjs-9c133a19 (106455ms)
21933 timing npm Completed in 309089ms
21934 error cb() never called!
```
The error occurs after the extract of rxjs!

<img width="947" alt="install" src="https://user-images.githubusercontent.com/68217449/108699973-4272b780-7506-11eb-946c-36e8a1e88c27.png">

### Expected Behavior:
Install should finish without any error.

### Steps To Reproduce:
 - Extract [any-project.zip](https://github.com/npm/cli/files/6021429/any-project.zip)
 - execute install.bat (Docker is needed!)

### Environment:
 - OS : Windows 10 Enterprise 64 bit (v 19.09 Build 18262.418)
 - Docker : Docker Desktop v 3.1.0
 - Image: node:14.15.5-stretch (npm 6.14.11)

**Comment by Swissman1** [comment]
I am also encountering this same error starting recently as well. I tried running `npm cache clean --force` to no avail. appears to complete the npm i with no apparent error in the log file besides `cb() never called` then errors upon attempting to serve(missing angular lib packages)

**Comment by andycandy-de** [comment]
Hey @darcyclarke, thanks for adding the labels. I was not able to add them after creating the issue. I am not sure if the 'windows' is correct. The node and npm runs inside docker, so it's a linux environment in which the 'npm install' is executed.

**Comment by darcyclarke** [comment]
https://github.com/npm/cli/wiki/%22cb()-never-called%3F--I'm-having-the-same-problem!%22

**Comment by andycandy-de** [comment]
I added the '--loglevel verbose' argument to the npm install ([install.zip](https://github.com/npm/cli/files/6122826/install.zip)). Unfortunately, the log is no more helpful for me. Maybe it helps someone else with the analysis.

[2021-03-11T11_58_19_324Z-debug.log](https://github.com/npm/cli/files/6122822/2021-03-11T11_58_19_324Z-debug.log)
```
21945 http fetch GET 200 https://registry.npmjs.org/rxjs/-/rxjs-6.6.3.tgz 106233ms
21946 http fetch GET 200 https://registry.npmjs.org/typescript/-/typescript-4.1.3.tgz 135744ms
21947 silly extract typescript@4.1.3 extracted to /usr/src/app/node_modules/.staging/typescript-dcdf15f5 (136451ms)
21948 silly extract rxjs@6.6.3 extracted to /usr/src/app/node_modules/.staging/rxjs-9c133a19 (108401ms)
21949 timing npm Completed in 340372ms
21950 error cb() never called!
21951 error This is an error with npm itself. Please report this error at:
21952 error <https://npm.community>
```

The only thing I can say is that the error always occurs after or with the extraction of rxjs.
Please let me know if I can provide more data.

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
