### ISSUE TITLE
Nodejs-pptx works for PPTX and not for PPT

### ISSUE THREAD

**Issue by dorinionescu** [npm/cli#2764]
the following instruction
`let newSlide = await pres.addSlide();`
works for PPTX and for PPT gives the error
"Cannot read property 'Relationships' of undefined"

### Environment:
- OS: Windows 10.0.18363 N/A Build 18363
- Node: 12.4.0
- npm: 6.9.0
- npm -v Nodejs-pptx
6.9.0

**Comment by ljharb** [comment]
You'll need to file an issue on that project; this repo is for npm itself.
