### ISSUE TITLE
[BUG] package latest version is wrong

### ISSUE THREAD

**Issue by SoloJiang** [npm/cli#2768]
I have published `rax-text@2.0.7`, but I couldn't find it.
![image](https://user-images.githubusercontent.com/14757289/108979873-0f772200-76c6-11eb-842e-049b0ca0d493.png)
![image](https://user-images.githubusercontent.com/14757289/108979905-169e3000-76c6-11eb-8683-48c230827880.png)

**Comment by nlf** [comment]
this looks right to me now. sometimes publishes take a few minutes to show up correctly. sorry about that!
