### ISSUE TITLE
[BUG] I cannot make changes to my deprecated package

### ISSUE THREAD

**Issue by ghost** [npm/cli#2776]
### Current Behavior:
I once published the npm package,  ["ravioli"](https://www.npmjs.com/package/ravioli). It is now deprecated.

If I try to make changes to it, I get a 403 (Forbidden) response:

```bash
$ npm whoami
opvasger

npm owner add flipsasser ravioli
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/ravioli/-rev/9-d5a93408eca1aa8173e2037973fce584 - You do not have permission to publish "ravioli". Are you logged in as the correct user?
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.

```

I have tried undepricating it, and other things, but it ultimately all leads back to getting 403 (Forbidden) responses whenever I try to make changes.

I have looked on the NPM website, and my account-page doesn't list "ravioli" as one of my packages. it is available in spite of this: https://www.npmjs.com/package/ravioli

### Expected Behavior:
I would like to add @flipsasser as owner of the package

### Steps To Reproduce:
you cannot reproduce this behaviour unless I share my personal credentials

### Environment:

- OS: Windows 10
- npm: 7.5.6 (also tried 6.?.? before updating)

**Comment by flipsasser** [comment]
Thank you, @opvasger!

To the helpful npm triage folks: please let me know if I can help! My npm username is also `flipsasser`.

**Comment by wraithgar** [comment]
This looks like it is an issue w/ the registry itself. As far as I can tell the cli is doing what it is supposed to here.  You can file an issue w/ the registry team here: https://www.npmjs.com/support

**Comment by ghost** [comment]
I contacted NPM support, and finally got the problem resolved @flipsasser 

Best wishes with your project :) you are now officially the owner - feel free to remove me in the process!
