### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by Gobinath90** [npm/cli#2777]
Installing packages (npm)...npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:

**Comment by Khizarkhattak999** [comment]
I also have this same issue.........I uninstall my npm and git and again install it....but the error remains constant.

**Comment by sattarulwariqirohmani** [comment]
$ npx create-react-app my-app

Creating a new React app in D:\javascript\node_modules\my-app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ARUL\AppData\Local\npm-cache\_logs\2021-02-26T01_26_40_891Z-debug.log

Aborting installation.
  npm install --save --save-exact --loglevel error react react-dom react-scripts cra-template has failed.

Deleting generated file... package.json
Deleting my-app/ from D:\javascript\node_modules
Done.
