### ISSUE TITLE
"Vue create" command failed

### ISSUE THREAD

**Issue by sjmondal** [npm/cli#2786]
2749 silly pacote range manifest for domelementtype@^2.0.1 fetched in 214ms
2750 http fetch GET 304 https://registry.npmjs.org/copy-descriptor 220ms (from cache)
2751 silly pacote range manifest for copy-descriptor@^0.1.0 fetched in 223ms
2752 timing npm Completed in 152000ms
2753 error cb() never called!
2754 error This is an error with npm itself. Please report this error at:
2755 error <https://npm.community>

Please inform what the actual issue is. Why the "Vue Create" command failed? The same happened in Windows 10 Pro

**Comment by sjmondal** [comment]
Please inform what the actual issue is. Why the "Vue Create" command failed? The same happened in Windows 10 Pro

**Comment by ljharb** [comment]
Duplicate of #2785.
