### ISSUE TITLE
[BUG] search is ignoring `--searchopts`

### ISSUE THREAD

**Issue by wraithgar** [npm/cli#2791]
### Current Behavior:
`--searchopts` is not making it into the options passed to search

### Expected Behavior:
`--searchopts` is added to the options passed into search

### Steps To Reproduce:
They are passed into `prepareIncludes`
https://github.com/npm/cli/blob/113b1319f9e9c90694454bebc9dc12111a441ecf/lib/search.js#L23

And then ignored
https://github.com/npm/cli/blob/113b1319f9e9c90694454bebc9dc12111a441ecf/lib/search.js#L70-L74

### Environment:
npm v7.6.0

**Comment by darcyclarke** [comment]
Closing as this should have gotten resolved in https://github.com/npm/cli/pull/2803  (ie. `v7.6.1`) Please let us know if there are any other issues

**Comment by ackvf** [comment]
Am I doing it wrong? When I do `npm search alfons --json --searchopts react --searchlimit 2` it gives exactly same result as `npm search alfons --json --searchlimit 2` and the found package isn't even react related.

On the other hand, this gives the expected result `npm search alfons react --json --searchlimit 2`
