### ISSUE TITLE
[BUG] NPM 7 erroneously tries to access private registry and fails with 401

### ISSUE THREAD

**Issue by fetis** [npm/cli#2799]
### Current Behavior:
`npm install` fails with 
```
npm ERR! code E401
npm ERR! Incorrect or missing password.
```

### Expected Behavior:
should just work 🤷 

### Steps To Reproduce:
We have a private registry served by Artifactory (v7.11.5), after upgrade to npm v7 installation process fails locally and on Jenkins with 401 error. We use token authentication stored in `.npmrc`.

Our `.npmrc` in the project directory points to the private registry _only for the company packages_
```
@company:registry=https://company.jfrog.io/company/api/npm/npm/
@company-cat:registry=https://company.jfrog.io/company/api/npm/npm/
```

but what I see in the logs, that NPM tries to download normal public packages from a private registry
```
➜ npm i --loglevel=http
npm http fetch GET 401 https://company.jfrog.io/company/api/npm/npm/sourcemap-codec/-/sourcemap-codec-1.4.6.tgz 7584ms
npm http fetch GET 401 https://company.jfrog.io/company/api/npm/npm/karma-chrome-launcher/-/karma-chrome-launcher-3.1.0.tgz 7510ms
```
which is very confusing

the dependency tree for these packages looks like this
```
 ➜ npm ls karma-chrome-launcher
package@0.0.1
└── karma-chrome-launcher@3.1.0
```

and for the second package
```
➜ npm ls sourcemap-codec
package@0.0.1
├─┬ @company/material-theme@1.29.0
│ └─┬ @schematics/angular@9.1.12
│   └─┬ @angular-devkit/core@9.1.12
│     └─┬ magic-string@0.25.7
│       └── sourcemap-codec@1.4.6  deduped
└─┬ @angular/compiler-cli@10.1.2
  ├─┬ magic-string@0.25.7
  │ └── sourcemap-codec@1.4.6
  └── sourcemap-codec@1.4.8
```

This might be related to #2508, but I don't understand why private packages are downloaded without error but the public ones generate a 401 (even if they are downloaded from a different repo). Of course, it works fine and correct with npm6

### Environment:
- OS: MacOS 10.14.6
- Node: v12 and v14
- npm: 7.6.0

**Comment by ljharb** [comment]
I believe dependencies of a package are assumed to come from the same registry. In other words, a properly configured internal registry serves as a proxy for external packages as well.

**Comment by fetis** [comment]
@ljharb this might be true for `sourcemap-codec`, but `karma-chrome-launcher` is a direct dev dependency

**Comment by leepowelldev** [comment]
What are the resolved urls for those packages failing in your `package-lock.json` file?

**Comment by sarin1234** [comment]
#2799

**Comment by fetis** [comment]
> What are the resolved urls for those packages failing in your `package-lock.json` file?

both point to https://company.jfrog.io/

**Comment by leepowelldev** [comment]
The issue seems to be similar to what I have discovered in https://github.com/npm/cli/issues/2619, where npm v7 seems to ignore any set registry flags/config on using `npm install/ci` and instead just uses the previously resolved urls found in the `package-lock.json` file. My guess is that if you changed your `package-lock.json` urls for the failing packages to the public npm registry then it would work.

**Comment by darcyclarke** [comment]
@fetis we're currently fixing up some issues with auth in `npm-registry-fetch` & should have an update here once those land

**Comment by wraithgar** [comment]
Can you try this again w/ the latest npm?

**Comment by darcyclarke** [comment]
Closing as there's no response.

**Comment by b2whats** [comment]
Still does not work in version 7.11.2
when install or ci, packages are taken from the resolve field in package-lock, not from the set registry in npmrc or --registry

**Comment by fetis** [comment]
> Closing as there's no response.

sorry, can't check this atm

**Comment by marinpurgar** [comment]
Still not working in npm 7.17.0.
