### ISSUE TITLE
[BUG] --scripts-prepend-node-path doesn't populate PATH

### ISSUE THREAD

**Issue by Gerrit-K** [npm/cli#2808]
### Current Behavior:
The flag `--scripts-prepend-node-path`, which is supposed to add the calling `node` executable to the `PATH` variable, doesn't seem to work. The directory isn't added.

### Expected Behavior:
The directory of the calling `node` executable should be added to `PATH`.

### Steps To Reproduce:
* Download NodeJS and npm via nvm (in my case `14.15.5` and `7.6.0` respectively)
* Create some skeleton with a `package.json` (in my case `npm init nx-workspace`)
* Call `node` and `npm` in isolation to any shell environment:
  ```bash
  env -i bash --noprofile --norc -c '/path/to/.nvm/versions/node/v14.15.5/bin/node /path/to/.nvm/versions/node/v14.15.5/lib/node_modules/npm/bin/npm-cli.js --scripts-prepend-node-path run nx'
  ```
  (note: in order to fix `sh: nx: command not found` I've prepended the node call with `PATH=$PATH:/path/to/.nvm/versions/node/v14.15.5/lib/node_modules/nx/bin`)

#### Expected Behavior:
The help message of `nx`

#### Current Behavior: 
`env: node: No such file or directory`

If you add a script with `env` or `echo $PATH` to the `package.json` you can see that `PATH` doesn't contain the directory to the calling `node` executable, so I assume it's not a bug of `nx`.

### Environment:
- macOS 11.1
- NodeJS 14.15.5
- npm 7.6.0

**Comment by ljharb** [comment]
I’m confused, how would npm run if node wasn’t in the PATH already?

**Comment by Gerrit-K** [comment]
As commented by calling `npm-cli.js` with a `node` binary, both referenced with the full path

**Comment by ljharb** [comment]
ok - why would you do that tho, if you already have the full path?

**Comment by Gerrit-K** [comment]
I'm not actively doing that. It's the way IDEs like WebStorm call scripts with a node and npm version that you can select in the preferences or on a per-project basis. For reference, see [this issue](https://youtrack.jetbrains.com/issue/WEB-49835#focus=Comments-27-4728121.0-0) (and feel free to comment there, too).

**Comment by ljharb** [comment]
Running npm or node without `node` and `npm` in the PATH is a bad idea, because many things will expect it to be there - *especially* npm run-scripts. The comment that "that's what npm does" isn't really relevant, because WebStorm isn't npm.

**Comment by Gerrit-K** [comment]
Well, I agree that it's probably not the _intended_ way to run it and also that npm is not responsible for any failing sub script, _but_ the [docs](https://docs.npmjs.com/cli/v7/commands/npm-run-script) clearly define how `--scripts-prepend-node-path` should work:

> `npm run` sets the `NODE` environment variable to the `node` executable with which `npm` is executed. Also, if the `--scripts-prepend-node-path` is passed, the directory within which `node` resides is added to the `PATH`. If `--scripts-prepend-node-path=auto` is passed (which has been the default in `npm` v3), this is only performed when that `node` executable is not found in the `PATH`.

And as far as I can see it, that's not working in my (maybe exotic, but still valid) case. (edit: of course that's assuming that `npm-cli.js` should be able to be run via an arbitrary `node` executable)

Another edit:
> The comment that "that's what npm does" isn't really relevant, because WebStorm isn't npm.

I believe the JetBrains employee was referencing [this line](https://github.com/npm/cli/blob/0c881fc3e12c34fabf6225b1f5c0200d424f996c/bin/npm#L37) from the `npm` shell wrapper.

**Comment by ljharb** [comment]
right - that’s not something anything else should be doing. npm is part of the platform, webstorm is not.

**Comment by Gerrit-K** [comment]
Okay, let's put WebStorm aside for a moment and look at the simple question: "Is calling `npm-cli.js` with an arbitrary `node` version supported or not?". 

If not and if you could point me to some sort of documentation about this, I'd gladly pass that information on to JetBrains and ask them to change how they call `npm`.

**Comment by Gerrit-K** [comment]
I just noticed [npm/statusboard#117](https://github.com/npm/statusboard/issues/117). If I interpret that correctly, the flag in question isn't even in the code anymore (which would explain why I wasn't able to find it after all). Can you confirm that?

**Comment by darcyclarke** [comment]
@Gerrit-K apologize for the confusion here; `--scripts-prepend-node-path` was actually removed for npm `v7` & that doc you referenced is out-of-date (will leave this open until we fix that reference). If you'd like us to reintroduce this flag, can you create an RRFC of RFC over at https://github.com/npm/rfcs

**Comment by Gerrit-K** [comment]
@darcyclarke thanks, that clarification helps a lot. I'll point JetBrains to this issue and let them know that they need to adjust their calling code.

**Comment by Fryuni** [comment]
Quite odd, an RFC is required to put the flag back but there is no RFC or even a mention on a commit message anywhere in that repository about removing it. It was just gone breaking every development environment that uses more than one node version.

It is also not mentioned in any changelog here since 2016 when it was added. The problem here is clearly not about docs, that option should not have been removed
