### ISSUE TITLE
angular new app

### ISSUE THREAD

**Issue by Syed-Zakriya-Mushtaq** [npm/cli#2813]
E:\opensourcetest\lerna-repo\packages>ng new lerna-angular
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? SCSS   [ https://sass-lang.com/documentation/syntax#scss
 ]
CREATE lerna-angular/angular.json (3710 bytes)
CREATE lerna-angular/package.json (1256 bytes)
CREATE lerna-angular/README.md (1021 bytes)
CREATE lerna-angular/tsconfig.json (458 bytes)
CREATE lerna-angular/tslint.json (3185 bytes)
CREATE lerna-angular/.editorconfig (274 bytes)
CREATE lerna-angular/.gitignore (631 bytes)
CREATE lerna-angular/.browserslistrc (853 bytes)
CREATE lerna-angular/karma.conf.js (1025 bytes)
CREATE lerna-angular/tsconfig.app.json (287 bytes)
CREATE lerna-angular/tsconfig.spec.json (333 bytes)
CREATE lerna-angular/src/favicon.ico (948 bytes)
CREATE lerna-angular/src/index.html (298 bytes)
CREATE lerna-angular/src/main.ts (372 bytes)
CREATE lerna-angular/src/polyfills.ts (2835 bytes)
CREATE lerna-angular/src/styles.scss (80 bytes)
CREATE lerna-angular/src/test.ts (753 bytes)
CREATE lerna-angular/src/assets/.gitkeep (0 bytes)
CREATE lerna-angular/src/environments/environment.prod.ts (51 bytes)
CREATE lerna-angular/src/environments/environment.ts (662 bytes)
CREATE lerna-angular/src/app/app-routing.module.ts (245 bytes)
CREATE lerna-angular/src/app/app.module.ts (393 bytes)
CREATE lerna-angular/src/app/app.component.html (25757 bytes)
CREATE lerna-angular/src/app/app.component.spec.ts (1078 bytes)
CREATE lerna-angular/src/app/app.component.ts (218 bytes)
CREATE lerna-angular/src/app/app.component.scss (0 bytes)
CREATE lerna-angular/e2e/protractor.conf.js (869 bytes)
CREATE lerna-angular/e2e/tsconfig.json (294 bytes)
CREATE lerna-angular/e2e/src/app.e2e-spec.ts (646 bytes)
CREATE lerna-angular/e2e/src/app.po.ts (301 bytes)
| Installing packages...npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Prosigns\AppData\Roaming\npm-cache\_logs\2021-03-03T00_42_46_775Z-debug.log
× Package install failed, see above.
The Schematic workflow failed. See above.

**Comment by sandeepdussa** [comment]
Node 14.16.0 NPM 6.14.11

I'm facing same issue. Do we have a fix for this yet?

npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

**Comment by sandeepdussa** [comment]
Upgrading NPM to 7.6.0 fixed this issue for me.
