### ISSUE TITLE
[BUG] cb() never called!

### ISSUE THREAD

**Issue by Brlaney** [npm/cli#2814]
[2021-03-03T23_54_15_907Z-debug.log](https://github.com/npm/cli/files/6080030/2021-03-03T23_54_15_907Z-debug.log)
[windows-terminal.txt](https://github.com/npm/cli/files/6080031/windows-terminal.txt)

### Current Behavior:
Following the steps instructed of me that work for others I was unable to successfully deploy a serverless next.js web-app because of this dependency.

### Expected Behavior:
I expected to run: npm i @sls-next/serverless-component and be able to download the dependency for this next.js app.

### Steps To Reproduce:

1. From windows terminal run: `mkdir nxt-app then: cd nxt-app`
2. Then run: `npx create-next-app my-aws-app` and then: `cd my-aws-app`
3. Then run: `npx serverless create --template aws-nodejs`
4. From the current directory open a text editor (I used `code .`) and remove all boilerplate code contained in the **serverless.yml** file
5. Add the following two lines of code to serverless.yml: `myNextApp: `<-- line 1
  `component: "@sls-next-serverless-component@1.18.0"` <-- line 2 (indent two spaces)
6. Lastly, I ran the following which yielded the error-log I have provided with this Issue submission: `npm i @sls-next/serverless-component`

### Environment:

- OS: Windows 10 x 64-based PC
- Node: v14.15.4
- npm: 7.4.2

### **Successfully deployed my serverless Next JS App to AWS Amplify without receiving the above error.**

In the context described above, I was able to find a solution to my error. 

### **What I did wrong:** 

- There was no need for me to run `npm i @ sls-next/serverless-component`

### Changes I made to successfully deploy my next.js app on AWS amplify serverless: 

    1.) In the serverless.yml file, I ended up changing the 1.18.0 to 1.16.0 (I don't believe this is what solved my issue)

    2.) What I believe solved my issue was editing the "build" script in my package.json file 
        from --> "build": next build",
        to     --> "build": "next build && next export",

Thanks for your time.

**Comment by 4nkit777** [comment]
Man, I am having the same issue. Have tried all the fixes, didn't nudge a bit. Can anyone resolve this issue ?

**Comment by darcyclarke** [comment]
@4nkit777 please reference: https://github.com/npm/cli/wiki/%22cb()-never-called%3F--I'm-having-the-same-problem!%22

@Brlaney appreciate the thoroughness here, just want to confirm or not, were your original steps to reproduce consistently reproducible? Or, was this an intermittent issue?

**Comment by scotch83** [comment]
Got this same issue today...no more feedback than just cb() never called, when installing a package (@wdio/jasmine-framework)

**Comment by 4nkit777** [comment]
I have figured it out. If you have too many projects, that means a lot of node_modules on every project. This actually overwhelmes the inodes on Linux. I don't know about windows or mac, but if you clear up all your projects you will be fine. Try that!

**Comment by Brlaney** [comment]
Sorry for the late response @darcyclarke. Yes, I was able to consistently reproduce the error following the initial six steps that I had originally posted. I had deleted my project directory and even started fresh multiple times to make certain. 

In this particular situation, step 6 was incorrect and when deploying a serverless next.js web app you only need to specify @sls-next/serverless-component in your serverless.yml file NOT do what I did and try and npm install the dependency. I am not sure why that error occurred when I would try and npm install it but I do know that I was able to deploy a serverless next.js app to AWS just fine without installing that dependency! Thanks for your time kind sir! @darcyclarke 

Sincerely, Brendan Laney

**Comment by scotch83** [comment]
I could fix this by running `npm cache verify`

**Comment by lukekarrys** [comment]
**Closing:** We suspect this has to do with a combination of resource constraints within the device/program being used and the large amount of transient dependencies being installed by this command.

We've opened https://github.com/npm/statusboard/issues/395 for us to look deeper into this and track the discussion and fixes around it. You can also read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) for more information on why this issue might be happening currently and ways to debug it.
