### ISSUE TITLE
Regression:  7.6.0 throws a `TypeError: Cannot read property '@roundforest/***' of null` error sometimes

### ISSUE THREAD

**Issue by giltayar** [npm/cli#2815]
### Current Behavior:

When I `npm install` in a package, I get the following error `TypeError: Cannot read property '@roundforest/***' of null` (full debug log below)

The same error happens with `npm ci`.

**When using npm v7.5.0, the `npm ci` finishes executing with no problem.**

### Expected Behavior:

It should finish the `npm install/ci`, just like it does with v7.5.0.

### Steps To Reproduce:
Sorry, can't figure out why this _specific_ package fails. Others pass without a problem There's nothing interesting there. Hopefully, the debug log may help you.

### Environment:
- OS: MacOS Big Sur (latest update)
- Node: 15.11.0
- npm: 7.6/0

### Debug log:

[2021-03-04T06_16_20_829Z-debug.log](https://github.com/npm/cli/files/6081279/2021-03-04T06_16_20_829Z-debug.log)

**Comment by wraithgar** [comment]
This is a bug in the meta-vulnerability calculator when dealing with some of the results from the github packages registry (which returns nulls where other repositories return undefined).

It will be fixed in the next npm release.

https://github.com/npm/metavuln-calculator/pull/6
