### ISSUE TITLE
[BUG] Impossible to link more than one local module dependency one at a time.

### ISSUE THREAD

**Issue by tristanls** [npm/cli#2819]
https://github.com/npm/cli/issues/2554 was closed without an explanation and without fixing the bug.

**Comment by joebnb** [comment]
same problem

if link a scoped module @scope/name1 at dir1 it will remove all dir1/node_modules/@scope/*

i just want add a link moudle, not rm -rf @scope/ dir then link this one

**Comment by CodeTroopers** [comment]
Same problem with npm 7.6.3

- from depency @mycompany/B:

`cd dist && npm link`

- from depency @mycompany/C:

`cd dist && npm link`

- from main project @mycompany/A:
`npm link @mycompany/B`
Symlink @mycompany/B exists in node_modules
`npm link @mycompany/C`
Symlink @mycompany/C exists in node_modules
**but Symlink @mycompany/B is deleted in node_modules**

This works well with npm 6.14.11

**Comment by darcyclarke** [comment]
The way you can work around this today is to link these deps at the same time (ex. `npm link @mycompany/B  @mycompany/C`); There are improvements that could be made to `npm link` but those would probably be feature requests/improvements; Definitely feel free to open up an RFC over on [`npm/rfcs`](https://github.com/npm/rfcs) if you have ideas on how this should work differently in the future.

**Comment by tristanls** [comment]
Since this is the second time you're closing this issue as is without changing anything, the only remaining suggestion I have is that perhaps this should be documented per https://github.com/npm/cli/issues/2554#issuecomment-810903688

**Comment by CodeTroopers** [comment]
@darcyclarke you say "those would probably be feature requests/improvements"
But this worked with NPM 6.14.11. so it's rather a regression of npm
