### ISSUE TITLE
[BUG] cb() never called!

### ISSUE THREAD

**Issue by iitsmel** [npm/cli#2820]
### Current Behavior:
Unable to fully install packages.

### Expected Behavior:
Successfully install all packages.

### Steps To Reproduce:
1. Run 'rm -rf node_modules && npm cache clean --force && npm install'
2. See error
I bumped into a situation where I need to remove node_modules in order to clear some mixed up installs. This command was supposed to remove node_modules with cache and reinstall all required packages. However it didn't work as I expected.

### Environment:
- OS: macOS Big Sur 11.2.1
- Node: 14.15.5
- npm: 7.5.2

**Comment by gbeltrao** [comment]
Running 'npm i' is also generating this error. Log file:
[2021-03-05T02_30_06_178Z-debug.log](https://github.com/npm/cli/files/6088107/2021-03-05T02_30_06_178Z-debug.log)

**Comment by sibishan** [comment]
I also ran in to this today 😵. How did you solve it?

**Comment by iitsmel** [comment]
I deleted  the whole file and created a new one. Problem solved but I had no idea why. Still looking forward to a more productive solution. Highly not recommend if your project is a collaborate / huge one.

**Comment by sibishan** [comment]
This problem got solved but I don't how did I solve 😅 and Thank You for helping out 🙏🏾

**Comment by darcyclarke** [comment]
Closing: https://github.com/npm/cli/wiki/%22cb()-never-called%3F--I'm-having-the-same-problem!%22
