### ISSUE TITLE
[BUG] package.json and package-lock.json order is different when used Czech locale

### ISSUE THREAD

**Issue by jakubjosef** [npm/cli#2829]
### Current Behavior:
package-lock and package.json order is different when used non English (Czech) locale

### Expected Behavior:
Sorting should be locale-agnostic to not change package-lock JSON back and forth. 

### Steps To Reproduce:
1) Clone repo created with English locale
2) Run npm install
3) I see different order for packages with `ch` in name (eg. chai)

### Environment:
- OS: macOS 11.2.2
- Node: 14.16.0
- npm: 7.6.1

It looks like similar problem as it's reported here
https://github.com/npm/npm/issues/17048

I think the root cause is different order of letters. In Czech alphabet `CH` letter stands after `H`, but in English alphabet it's just `C`.

**Example in package.json (left is Czech locale, right is English)**

![image](https://user-images.githubusercontent.com/4058213/110140266-345d4a80-7dd4-11eb-851b-b064994ca864.png)

**Workaround**

If someone is facing the same issue in can be fixed by defining alias `alias npm='LANG="en_US.UTF-8" LC_ALL="en_US.UTF-8" npm'` in bash_profile/.zshrc or similar file depends to shell you are using.

**Comment by padinko** [comment]
same in Windows 10 with Slovak language, node v14.16.1, npm v7.11.2
i can't find workaround for windows

**Comment by padinko** [comment]
I make pull requests to fix this

https://github.com/npm/arborist/pull/276 will fix sorting in `package.json`
https://github.com/isaacs/json-stringify-nice/pull/5 will fix sorting in `package-lock.json`

so this 2 packeses will need to be updated to fix this

**Comment by wraithgar** [comment]
Thank you @padinko!

**Comment by jakubjosef** [comment]
I can confirm this is now fixed in NPM. Thank you, closing this issue.
