### ISSUE TITLE
[BUG] `npm version` removes "_moduleAliases" part of package.json

### ISSUE THREAD

**Issue by noneedinmagic** [npm/cli#2830]
### Current Behavior:

After updating my local `npm` to 7.x running `npm version <patch|whatever>` command leads to removal of `"_moduleAliases"` from `package.json` which leads to breaking of the build proccess of my TS-based server app on NodeJS.
"_moduleAliases" is needed for the [module-alias](https://www.npmjs.com/package/module-alias) package.
A few days ago when I was using npm@6 on my local PC everything was okay, but yesterday I just did `npm version patch`, pushed the app to master, it deployed but didn't start on production which was completely unexpected, but in fact I just didn't notice that this part of package.json was missing.
Surely, I could downgrade to npm@6 or return this part everytime by myself, which I do now, but I'm afraid that one time I might forget to add it or my colleagues may update to npm@7, just bump the version before deployment... and break the prod.

### Expected Behavior:
`npm version patch` should just change versions in package.json and package-lock.json and shouldn't touch anything else.

### Steps To Reproduce:
1. Init the package
2. Add "_moduleAliases" field to package.json (value may be even an empty object)
3. Run `npm version patch`
4. ?????????
5. Module aliases are broken, NOT PROFIT!

### Environment:
- OS: Windows 10
- Node: 12.18.0
- npm: 7.6.0

**Comment by wraithgar** [comment]
Looks like `libnpmversion` uses `read-package-json-fast` which is the wrong tool for the job. It should use the normal `read-package-json` as the former is only suitable for reading package-json files from node_modules.

**Comment by wraithgar** [comment]
`read-package-json` does the same thing. Fun https://github.com/npm/read-package-json/blob/latest/read-json.js#L99

**Comment by isaacs** [comment]
Yeah, `version` should just read the file and parse the json, and needs to track the indentation/linebreaks to change as little as possible.  Fixed by npm/libnpmversion#10.

**Comment by wraithgar** [comment]
This is in the `release-next` branch now and will go out w/ the next cli release.
