### ISSUE TITLE
[BUG] Fails install on platform-unsupported optional dependency

### ISSUE THREAD

**Issue by adam-coster** [npm/cli#2832]
### Current Behavior

Installing an npm package that has an optional but platform-incompatible dependency (in this case, `fsevents`) completely fails on Ubuntu 20.04 (while working properly on Windows 10).

### Expected Behavior:

Failure to install optional dependencies should not result in complete failure to install.

### Steps To Reproduce

+ Open a terminal in Ubuntu
+ `npm init -y` (to create a new `package.json`)
+ Run `npm i sass`, which has the *optional* dependency `fsevents`, get:

```terminal
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  undefined
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64
```

**And sass does not appear in the `package.json`.**

### Environment

+ Ubuntu 20.04 running on Windows 10 (v20H2, build 19042.844) via WSL2.
+ `npm@7.6.0` or `npm@7.6.1`
+ `node@14.15.3`

### Additional Notes

+ This failure **does not occur on Windows 10**, when using the same versions of Node, npm, and Sass, despite the `fsevents` dependency being OSX-only.
+ Reverting to `npm@6.14.11` on Ubuntu allows installation to proceed as expected, showing warnings that the optional dependency (`fsevents`) was skipped but still installing `sass`. So this is not an issue with the `sass` npm package improperly indicating that `fsevents` is optional, and is npm version-specific.
+ No version of `sass` within the past year can be installed via `npm@7.6.X`, further indicating that it is not a package issue.
+ Adding `"optionalDependencies": {"fsevents": "*"}` to the `package.json`, with or without the `--no-optional` flag, does not resolve the issue.

**Comment by darcyclarke** [comment]
Have you tried running `install` with either `--legacy-per-deps` and/or `--force` ?

**Comment by adam-coster** [comment]
Weird. I went to test that out by first updating `npm` back to `7.6.1`, then deleting the `node_modules` folder, and then running `npm i`, and this time it installed without error. I guess this is closed? If it happens again I'll try out your suggestions, thanks!
