### ISSUE TITLE
[BUG] rendering unicode emoji in README.md not consistent with Github

### ISSUE THREAD

**Issue by atao60** [npm/cli#2833]
### Current Behavior:
Github replaces native unicode emoji with png image, i.e. something like:
`<g-emoji class="g-emoji" alias="shield" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f6e1.png"><img class="emoji" alt="shield" src="https://github.githubassets.com/images/icons/emoji/unicode/1f6e1.png" width="20" height="20"></g-emoji>`

npmjs.com keeps the native unicode, i.e.:
`<g-emoji class="g-emoji" alias="shield" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f6e1.png">🛡</g-emoji>`

Depending on the case, the look can be slightly different, but at least keeping some colors. In worst case the icon becomes black and white.

### Expected Behavior:
Replace unicode with png image as on Github.

**Comment by darcyclarke** [comment]
Hey @atao60! Thanks for filing this, unfortunately this issue thread is only meant for `npm` CLI bugs; If you have feedback about the website or registry, feel free to create a new discussion over on https://github.com/npm/feedback and/or if you have an issue with the registry or website, feel free to file a suppoet ticket here:  https://www.npmjs.com/support

**Comment by atao60** [comment]
See new discussion https://github.com/npm/feedback/discussions/274
