### ISSUE TITLE
[BUG] unable to publish when using publishConfig option - ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by waitem** [npm/cli#2834]
### Current Behavior:
When running `npm publish` the following error appears:
```
npm ERR! code ERR_INVALID_ARG_TYPE
npm ERR! The "path" argument must be of type string. Received undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xx/.npm/_logs/2021-03-06T09_10_43_193Z-debug.log
```

The debug trace shows:
```
23 verbose stack TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
23 verbose stack     at validateString (internal/validators.js:124:11)
23 verbose stack     at join (path.js:1039:7)
23 verbose stack     at flatten (/home/xx/.nvm/versions/node/v14.16.0/lib/node_modules/npm/lib/utils/flat-options.js:50:10)
23 verbose stack     at Publish.publishConfigToOpts (/home/xx/.nvm/versions/node/v14.16.0/lib/node_modules/npm/lib/publish.js:140:12)
23 verbose stack     at Publish.publish (/home/xx/.nvm/versions/node/v14.16.0/lib/node_modules/npm/lib/publish.js:58:32)
```

### Expected Behavior:
npm publish to continue working as it did in version 6

### Steps To Reproduce:
1. In this environment...
Ubuntu 20.04
 Node 14.16.0
npm 7.6.1
2. With this config...
The package is configured to be published to github as per: [github instrutions](https://docs.github.com/en/packages/guides/configuring-npm-for-use-with-github-packages#publishing-a-package-using-publishconfig-in-the-packagejson-file)

package.json includes:
```
  "publishConfig": {
    "registry": "https://npm.pkg.github.com"
  },
```
3. Run ```npm publish```
4. See error:
```
npm ERR! code ERR_INVALID_ARG_TYPE
npm ERR! The "path" argument must be of type string. Received undefined`
```

### Environment:
Ubuntu 20.04
 Node 14.16.0
npm 7.6.1

### Possible cause
The issue seems to be related to changes made to the ```flatten()``` method in [utils/flat-options.js](https://github.com/npm/cli/blob/08673c34f0f131619ea8eb75dd325e755bf0a323/lib/utils/flat-options.js#L50)
This is being called with the ```publishConfig``` which only contains a ```registry``` property.
However flatten (line 50), tries to use ```join()``` to create a path from the non-existent```'cache``` property, hence the error (I believe).
Looking at the changes, it seems that v6 used to read the npm config for the ```cache``` value.

### Workaround
My temporary workaround for this is to add a **cache** property to the publishConfig section, using the [default cache value](https://docs.npmjs.com/cli/v7/using-npm/config#cache):
```
  "publishConfig": {
    "cache": "~/.npm",
    "registry": "https://npm.pkg.github.com"
  },
```
As others have noted, this workaround has the side-effect of creating a ```~/.npm``` directory in the root of the project. My solution to this was then simply to add ```~/.npm``` to ```.gitgnore```

I guess that you could name this cache directory whatever you like. I used the default value simply to make publish work again. Note that my suggestion is purely a workaround and doesn't resolve the actual issue. Although I could see in the v7 code where the change has been made that is causing this issue, unfortunately I was unable to understand why that change was made.

**Comment by FingalP** [comment]
We had the same issue. The workaround works for now, thanks @waitem

**Comment by Fadoli** [comment]
Having the same issue here,

an other workaround (if you don't want to modify all your publish config) is  to modify line 51 of flat-options.js to 

```
cache: join(obj.cache || '~/.npm', '_cacache'),
```

**Comment by johnthad** [comment]
> We had the same issue. The workaround works for now, thanks @waitem

This workaround does create a local directory `~` with the cache info (macOS 10.15.7).

**Comment by yellowtailfan** [comment]
I just encountered this bug, and the `"cache": "~/.npm",` work around caused a side-effect where the cache was written in the project folder (`<project>/~/.npm`) instead of my home directory. So I've reverted back to NPM 6.x instead. I'm using NPM in WSL2.

**Comment by stheine** [comment]
experienced the same in `npm 7.6.3` and `node v14.16.0`. found a workaround by completely removing the `publishConfig` section from the `package.json`.

**Comment by lorenzogrv** [comment]
Hi everybody. I can confirm this issue too. Proposed workaround (adding `publishConfig.cache`)  helped to step over, same side-effect as @yellowtailfan explains.

In this particular case I can't remove `publishConfig` from `package.json` as it's need to publish against gitlab's package registry, as suggested by @stheine .

Did not downgrade to `6.x` to test.

I'm glad to see the pull request over this comment. Keep up the good work.

```shell
$ uname -srv
Linux 5.4.0-66-generic #74~18.04.2-Ubuntu SMP Fri Feb 5 11:17:31 UTC 2021
$ npm --version
7.6.3
$ node --version
v12.21.0
```

I suggest future readers `"cache": "cache.npm"` or the like so you don't accidentally try to `rm -r ~` within your project, which may have fatal effects within your user's home

**Comment by lorenzogrv** [comment]
Hi again. Just noticed the workaround has another side-effect: **It will publish with `--tag` set to `undefined`**

> Well, it may not be the workaround at all, but side-effect is there

Check `npm show @scope/package-name` to see if side-effect affects you. `npm publish --tag latest` works as expected, after the needed version bump.

**Comment by wraithgar** [comment]
A huge thank you to @kenrick95 for figuring this out and submitting a PR that will resolve it: https://github.com/npm/cli/pull/2865

Will keep this open after we ship that PR (which will hopefully be this week) so those affected can confirm that it fixes their issue.

**Comment by bhargavgohil25** [comment]
The Workaround worked for me too 👍

**Comment by wraithgar** [comment]
This should be fixed in `v7.7.0`. The `publishConfig` is now being consolidated properly

**Comment by hubber-maik** [comment]
> This should be fixed in `v7.7.0`. The `publishConfig` is now being consolidated properly

I can confirm it is indeed working with 7.7.0! Thanks for the effort!

**Comment by lorenzogrv** [comment]
I can confirm too. The `dist-tag` `undefined` issue got away too.

```shell
$ npm -v
7.7.0
$ node -v
v12.21.0
```

Keep up the good work :rocket:

**Comment by Gauhar** [comment]
I can confirm that this issue was happening on my end as well on `npm version 7.6.3` and `node version v15.12.0`. Since we I am publishing a public package then you can get rid of `publishConfig`

**Comment by yairEO** [comment]
I also confirm this issue occurs as of *right now*, using `npm` version `7.9.0`, `node` version `v12.21.0` 

I've removed the `publishConfig` property from the `package.json` file and now I am able to publish.
