### ISSUE TITLE
how to extract roles from access token in Angular-oauth2-oidc 

### ISSUE THREAD

**Issue by sandyrawat** [npm/cli#2837]
I am using angular-oauth2-oidc lib for single sign-on. After successful login, I want to fetch roles from the access token. But as of now, there is no direct method which can parse token and gives its internal attributes.
Is there any way via which can get all the roles or other attributes of the token? Any help would be much appreciated.

**Comment by darcyclarke** [comment]
**Closing:** we do not support/triage third-party libraries or tooling bugs; Please file an issue with the relevant project.
