### ISSUE TITLE
[BUG] global update fails on windows

### ISSUE THREAD

**Issue by ray007** [npm/cli#2838]
### Current Behavior:
As already [noted by someone else](https://github.com/npm/cli/issues/2639#issuecomment-775490191), there seems to be a problem with install/update of global packages:
```
$ npm up -g
npm ERR! code EPERM
npm ERR! syscall mkdir
npm ERR! path C:\Program Files\nodejs\node_modules\.npm-QXjMEw5N
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, mkdir 'C:\Program Files\nodejs\node_modules\.npm-QXjMEw5N'
npm ERR!  [Error: EPERM: operation not permitted, mkdir 'C:\Program Files\nodejs\node_modules\.npm-QXjMEw5N'] {
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: 'C:\\Program Files\\nodejs\\node_modules\\.npm-QXjMEw5N'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rbauer\AppData\Local\npm-cache\_logs\2021-03-08T10_46_40_199Z-debug.log
```
[2021-03-08T10_46_40_199Z-debug.log](https://github.com/npm/cli/files/6100819/2021-03-08T10_46_40_199Z-debug.log)

### Expected Behavior:
Packages get updated.

### Environment:
- OS: Windows 10
- Node: 14.16.0
- npm: 7.5.6

**Comment by Nixinova** [comment]
Same issue in 7.8.0, I can't even revert my version of npm because of this.

**Comment by Nixinova** [comment]
Fixable by running `cmd.exe` as admin; when and why was %appdata% changed to C:/program files?

**Comment by ray007** [comment]
Another box, another error.
Homeworking with a laptop now, I'm getting this error on `npm up -g`:
```
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name ".npm.MODULES": name cannot start with a period
```
[2021-04-08T14_54_04_874Z-debug.log](https://github.com/npm/cli/files/6279576/2021-04-08T14_54_04_874Z-debug.log)
This with npm `7.8.0` and node `v14.16.1` on Windows 10.

Running as admin does not change anything.

**Comment by ray007** [comment]
Update: at least here on the laptop the problem seems to be about argument handling.
Doing `npm up -g <module>` does work, only trying for an update of all fails.

**Comment by ray007** [comment]
Coming back from home office and updating the machine, things seem to be getting worse.
Just checking with `npm list -g` shows that `npm` is looking in the wrong location:
```
$ npm list -g
C:\Program Files\nodejs
`-- npm@6.14.12
```
And it also does not fit with
```
$ where npm
C:\Program Files\nodejs\npm
C:\Program Files\nodejs\npm.cmd
```
and
```
$ npm -v
7.5.6
```
Trying install/uninstall/update `npm` globally all result in the same initial error.

**Comment by darcyclarke** [comment]
@ray007 can you try replicating this problem on the latest version of `npm`? (ie. `npm i -g npm`)

**Comment by Nixinova** [comment]
Both 7.10.0 and 7.12.0 still have this issue (EPERM: operation not permitted). My `npm list -g` also only lists `C:\Program Files\nodejs`.

<details><summary>non-admin `npm i -g npm`</summary>

```
Microsoft Windows [Version 10.0.19041.928]
(c) Microsoft Corporation. All rights reserved.

C:\Users\GGPC\Documents\GitHub>npm -v
7.10.0

C:\Users\GGPC\Documents\GitHub>npm i -g npm
npm ERR! code EPERM
npm ERR! syscall mkdir
npm ERR! path C:\Program Files\nodejs\node_modules\.npm-QXjMEw5N
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, mkdir 'C:\Program Files\nodejs\node_modules\.npm-QXjMEw5N'
npm ERR!  [Error: EPERM: operation not permitted, mkdir 'C:\Program Files\nodejs\node_modules\.npm-QXjMEw5N'] {
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: 'C:\\Program Files\\nodejs\\node_modules\\.npm-QXjMEw5N'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\GGPC\AppData\Local\npm-cache\_logs\2021-05-07T20_43_04_457Z-debug.log

C:\Users\GGPC\Documents\GitHub>
```
</details>
<details><summary>admin `npm i -g npm`</summary>

```
Microsoft Windows [Version 10.0.19041.928]
(c) Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>npm -v
7.10.0

C:\WINDOWS\system32>npm i -g npm

removed 217 packages, changed 3 packages, and audited 37 packages in 12s

found 0 vulnerabilities

C:\WINDOWS\system32>
```
</details>

**Comment by ray007** [comment]
Installing a new `npm` (which only worked through tricks) did not help:
```
$ npm up -g
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name ".bin": name cannot start with a period

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rbauer\AppData\Local\npm-cache\_logs\2021-05-12T09_33_08_823Z-debug.log

$ npm -v
7.12.1
```

**Comment by nesbocaj** [comment]
> Fixable by running `cmd.exe` as admin; when and why was %appdata% changed to C:/program files?

When and why indeed? Having to run NPM with administrator privileges seems like an obvious security risk to me, so surely that cannot be the intended behaviour.

**Comment by ray007** [comment]
While
```
npm up -g
```
still fails with version 7.20.6,
```
npm up -g all
```
does work.

Correction: seemed to work. Now `npm list -g` reports no globally installed modules

**Comment by lukekarrys** [comment]
Closing as a duplicate of #3175.

**Comment by ray007** [comment]
> Closing as a duplicate of #3175.

The linked issue there is closely related and maybe even caused by the same bug, but not the same.
This here is about global update without specifying any module.

**Comment by ray007** [comment]
While this issue started with a different error, now it might be a duplicate of #2835.

**Comment by zloirock** [comment]
Hmm, I have this error on Windows after today updating to the new minor NPM version.

**Comment by ruyadorno** [comment]
@ray007 @zloirock @Nixinova I'd be very interested in learning more on how each of you installed the specific version of **npm** that first got you into that state (with `EPERM` issues). Please feel free to share more details if possible, did you used something like `nvm-windows`? Did you cloned the `npm` repo directly?

The recommended way to install **npm** in Windows is by downloading **nodejs** from https://nodejs.org - the default nodejs installer will make sure to set your `prefix` config option to an user owned folder (at `%APPDATA%\npm`) in which should be enough to avoid any issues when installing/updating/listing global packages.

### Workaround

If anyone else is having `EPERM` issues on windows when trying to operate on global packages, a good workaround is to set a user level config file that manually sets the `prefix` config option to the same value as the **nodejs** installer would, to do so you may run (you'll need at least `npm@7.20.0`) on **powershell**:

```
npm config set prefix=%APPDATA%\npm --location=user
```

Note that this might require a reinstall of all global packages.

### Next steps

I'm going to close this issue since the `EPERM` issue looks to be a configuration problem specific to custom windows installs. That said I'm going to follow up with an issue in our RFC repo to start a conversation on better managing default `prefix` values for both windows and other OSes.

@ray007 for the `EINVALIDPACKAGENAME` issue, it's def better to follow up with #2835 as you noted. Thanks for all the help here!

**Comment by ray007** [comment]
Well, I installed node with [chocolatey](https://chocolatey.org/), and then later `npm i -g npm`, nothing special done.

**Comment by darsain** [comment]
I installed node from the official installer, and later also did `npm i -g npm`. I guess npm installing itself globally is what is (or was) causing this.
