### ISSUE TITLE
[BUG] error publish without cache config in package.json / publishConfig

### ISSUE THREAD

**Issue by neyb** [npm/cli#2842]
### Current Behavior:
running `npm publish` get an error : 

```
18 timing config:load Completed in 8ms
19 verbose npm-session 2c8eccb75d3455d8
20 timing npm:load Completed in 12ms
21 verbose publish [ '.' ]
22 timing command:publish Completed in 13ms
23 verbose stack TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
23 verbose stack     at new NodeError (node:internal/errors:329:5)
23 verbose stack     at validateString (node:internal/validators:129:11)
23 verbose stack     at join (node:path:1081:7)
23 verbose stack     at flatten (/usr/lib/node_modules/npm/lib/utils/flat-options.js:50:10)
23 verbose stack     at Publish.publishConfigToOpts (/usr/lib/node_modules/npm/lib/publish.js:140:12)
23 verbose stack     at Publish.publish (/usr/lib/node_modules/npm/lib/publish.js:58:32)
24 verbose cwd /home/alban/dev/eda-vue-components
25 verbose Linux 4.19.104-microsoft-standard
26 verbose argv "/usr/bin/node" "/usr/sbin/npm" "publish" "."
27 verbose node v15.11.0
28 verbose npm  v7.6.1
29 error code ERR_INVALID_ARG_TYPE
30 error The "path" argument must be of type string. Received undefined
31 verbose exit 1
```

### Expected Behavior:
it should be a success

### Steps To Reproduce:

- remove any "cache" config
- `npm publish` on a working project

### Environment:
wsl archlinux
node v15.11.0
npm  v7.6.1

### workaround
adding "cache":"~/.npm" in package.json solves the problem.

### fix

I guess list[0] [here](https://github.com/npm/cli/blob/latest/lib/publish.js#L140) is supposed to be the default config... but for any reason is not resolved... but I may be wrong here.

I also notice https://github.com/npm/cli/blob/latest/lib/utils/flat-options.js#L50 is the only flatten option that is supposed not to be defined : maybe the problem is there ?

Might be related to [this change](https://github.com/npm/cli/commit/6cd3cd08af56445e13757cac3af87f3e7d54ed27?branch=6cd3cd08af56445e13757cac3af87f3e7d54ed27&diff=split#diff-49d92972c12c110929e2654444cef752a7d1fbf52ad3715ce8667257f68ab464R42) (the code was `  cache: join(npm.config.get('cache'), '_cacache'),
` before, maybe get use default value if any ?

**Comment by neyb** [comment]
note : might also be the cause of #2843 (also seems to miss a default config)

**Comment by malsatin** [comment]
Getting same bug.

Introduced here: https://github.com/npm/cli/commit/4a5dd3a5a200b3f4f7b47168497d8e03dca3a2ca#diff-c8bd325917d181608f40adecdcec3c76acde134cc15a9e4a0d18636698e4fe55

**Comment by like-me4** [comment]
Updated npm and got the same problem. On version 7.5.4 everything worked well.

**Comment by pmclachlan** [comment]
Same bug.

A note for others, at least for me, the workaround line   ("cache": "~/.npm") needed to be added **inside** publishConfig in package.json, not at the top level.

(Actually, getting a bunch of other weird bugs on this latest version too -- will have to roll back.  For example, even after the workaround, after I publish, when I 'npm install mything@latest' it doesn't actually pick up the newly published version.  I rolled back to 7.5.6 and my usual workflow (npm publish; cd ../other; npm install mything@latest ) started working again.

**Comment by wraithgar** [comment]
I believe this PR may fix the issue: https://github.com/npm/cli/pull/2865

If you define a publishConfig, it pushes the defaults out the window, that PR makes sure all publishConfigs (including the defualts) are represented in the final opts that are generated.

**Comment by neyb** [comment]
oO it seems to be a duplicate of #2834

**Comment by neyb** [comment]
duplicate of #2834
