### ISSUE TITLE
[BUG] sh: 1: version: not found

### ISSUE THREAD

**Issue by royalcala** [npm/cli#2848]
### Current Behavior:

I use the next package https://www.npmjs.com/package/@vidalii/backend I try to buil a cli/bin package, 
and when I write all the dependencies that has package copy, it doesnt work anymore, inclusive if I return to the simple file of print only a simple console.log; neither works with npx or npm exec and the error showed is sh: 1: version: not found

regards

**Comment by darcyclarke** [comment]
**Closing:** we do not support/triage third-party libraries or tooling bugs; Please file an issue with the relevant project.
