### ISSUE TITLE
[BUG] npm 7 fails to fetch prebuilds

### ISSUE THREAD

**Issue by knopkem** [npm/cli#2861]
### Current Behavior:
Importing dependencies that use prebuild (c++ build with native api)

### Expected Behavior:
Should install correctly

### Steps To Reproduce:
1. With npm 7 (previous versions work)
2. install dependency that uses prebuild, e.g. ```npm i dicom-dimse-native```

### Environment:
- OS: Windows 10
- Node: 15.11.0
- npm: 7.6.3

**Comment by ruyadorno** [comment]
@knopkem can you try replicating this problem on the latest version of `npm`? (`npm@8.6.0` at the time of writing). If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.
