### ISSUE TITLE
[BUG] Global Installs Show Audit Info But Can't Get Info

### ISSUE THREAD

**Issue by fishcharlie** [npm/cli#2862]
### Current Behavior:

```
charliefish@Charlies-MacBook-Pro ~ % npm i -g updtr ytdl

added 108 packages, and audited 109 packages in 4s

3 packages are looking for funding
  run `npm fund` for details

3 low severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
charliefish@Charlies-MacBook-Pro ~ % npm audit -g
npm ERR! code EAUDITGLOBAL
npm ERR! `npm audit` does not support testing globals

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/charliefish/.npm/_logs/2021-03-14T20_13_46_586Z-debug.log
```

### Expected Behavior:

One of the two options:

1. Shouldn't display audit information when installing globally
2. Allow for `npm audit -g` to work and display audit information

Currently it's **useless** to display audit information on global installs if we can't get details about it.

### Steps To Reproduce:

See above Terminal output

### Environment:

- OS: macOS 11.3 Beta (20E5196f)
- Node: v15.11.0
- npm: 7.6.0

**Comment by darcyclarke** [comment]
`npm audit` unfortunately doesn't support global packages at the moment; We've been considering other improvements to `audit` (ex. [auditing packages that haven't been install yet](https://github.com/npm/rfcs/pull/232)) but this would be a feature improvement; If you feel strongly about this, we'd love for you to make an issue/pr on our [`npm/rfcs` repo](https://github.com/npm/rfcs/)

**Comment by fishcharlie** [comment]
@darcyclarke That's fair. **However** from a user perspective this is very confusing. If npm audit doesn't work for global packages, it shouldn't talk about npm audit when installing global packages.

Totally fine if it's a feature request. But at the very least make the UX better and more understandable so users don't think it's a bug.

**Comment by ljharb** [comment]
It seems like a bug to me that any audit things happen at all when doing a global operation.

**Comment by CodeByZach** [comment]
@darcyclarke I get notified there are "high severity vulnerabilities" when I update my global packages, and yet, I can't run the audit command. This should be revisited.
