### ISSUE TITLE
[BUG] npm@7 does not install proper versions with presence of previous node_modules state

### ISSUE THREAD

**Issue by StreetStrider** [npm/cli#2873]
Our team found an issue of npm inconsistent install while migrating from lerna to npm@7 workspaces. It looks like inability to install proper dependencies if there is previous state of node_modules when checking out between branches. The result differs if previous node_modules is present or not.

### Current Behavior:
The dependencies have incorrect versions after install.

### Expected Behavior:
The dependencies have correct version even after checkout between branches.

### Steps To Reproduce:
Here's git bundle (I've put it to archive because of github limitations).
[npm-7-migration-bug.bundle.zip](https://github.com/npm/cli/files/6142903/npm-7-migration-bug.bundle.zip)
There're two commits in branch `narrow1`. They display broken transition we experience. To test if dependencies are broken or not I check version of axios. It should be 0.20 on first commit and 0.21.1 on second. It version is 0.20.0 on second commit, then we have a bug.

* git checkout narrow1
* git checkout HEAD~
* npm start # here we create initial state for node_modules
* head ./node_modules/axios/package.json # version = 0.20.0, correct
* git checkout -
* npm start # here we trying to actualize state of node_modules
* head ./node_modules/axios/package.json # version = 0.20.0, incorrect, must be = 0.21.1
* rm -rf ./node_modules
* npm start # running from scratch yields correct state, version = 0.21.1

### Environment:
OS is GNU/Linux, but we have devs with the same issue on Windows machines.
In repro I'm using node@12 and npm@7 for broken commit.

**Comment by StreetStrider** [comment]
There's also this anomaly in directory structure:
![anomaly-babel](https://user-images.githubusercontent.com/2124761/111188314-fd521a80-85c5-11eb-96b1-ca1fa03c2e39.png)

**Comment by ljharb** [comment]
You may want `npm ci` for switching branches, so you start fresh?

**Comment by StreetStrider** [comment]
@ljharb that's like our current workaround. We've automated it a little, so this reset scenario occurs only when needed. But that's still a workaround, since `npm i` always been idempotent command and was able to repro consistent `node_modules`.

**Comment by wraithgar** [comment]
`npm i` is not idempotent, it is dependent on (among other things) the current state of `node_modules`.  As @ljharb notes, `npm ci` should be the command to use if you want more consistent builds

**Comment by kanoshin** [comment]
@wraithgar I don't fully understand why this issue was closed. Does it mean that it is normal that `npm i` leaves `node_modules` in the state that is inconsistent with `package-lock.json`? And if it is by design is it due to some technical limitation on npm side? If installation is dependent on the state of `node_modules` why npm can't compare version of that package with lock file for a semver compatibility?

To me it seems like a quite severe issue which needs to have a serious justification to get closed.

**Comment by StreetStrider** [comment]
@wraithgar 
> npm i is not idempotent, it is dependent on (among other things) the current state of node_modules.

I think you mix up statelessness and idempotency. In fact, if it has an ability to set up a proper state from different `node_modules/` states (empty, different deps versions, missing deps etc) that is mean it is idempotent. As far as I know, `npm i` would always able to pick up from any state of `node_modules/` and set it up to actual state that reflects manifest files' current state.

The thing is — for some reason it is not able to do that in _some specific cases_, thus making this issue a bug.

**Comment by ljharb** [comment]
@StreetStrider no, it is not able to do that. The initial state of node_modules alters the final result, by which duplicate package versions are preferred/hoisted.

**Comment by StreetStrider** [comment]
@ljharb I understand you. But on the other hand it still conforms to the ranges in the package.json, making transition from any state to any other state correct. At some conditions it goes to the incorrect state.

**Comment by ljharb** [comment]
the problem is that there isn't one "correct" state.

**Comment by StreetStrider** [comment]
@ljharb I see, I already understood you, that is right correction. I never meant strict idempotency, but being conform to the manifest, thus being idempotently conform to the manifest after any install.

And yet there may be multiple correct states this does not negate the fact that there is some incorrect ones (or they was to the moment I was testing it). The ticket was about this specific bad conditions.
