### ISSUE TITLE
 [DOC] CONTRIBUTING.md needs update to use npm run check-coverage

### ISSUE THREAD

**Issue by chowkapow** [npm/cli#2875]
### Current Behavior:
In the [CONTRIBUTING.md page](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#test-coverage), it still shows `npm run test-coverage`

### Expected Behavior:
The command should be `npm run check-coverage`

**Comment by darcyclarke** [comment]
Fixed, thanks
