### ISSUE TITLE
 cb() never called! Error

### ISSUE THREAD

**Issue by architjee** [npm/cli#2879]
[2021-03-16T10_43_40_211Z-debug.log](https://github.com/npm/cli/files/6148208/2021-03-16T10_43_40_211Z-debug.log)

**Comment by developerweeks** [comment]
12626 silly extract fsevents@1.2.12 extracted to /home/vsts/work/1/s/webroot/themes/custom/ferc/node_modules/.staging/fsevents-1f35d254 (1193ms)
12627 http fetch GET 200 https://registry.npmjs.org/rxjs/-/rxjs-6.5.5.tgz 4438ms
12628 silly extract rxjs@6.5.5 extracted to /home/vsts/work/1/s/webroot/themes/custom/ferc/node_modules/.staging/rxjs-cb5ea271 (4512ms)
12629 timing npm Completed in 410054ms
12630 error cb() never called!
12631 error This is an error with npm itself. Please report this error at:
12632 error <https://npm.community>

##[error]Error: Npm failed with return code: 1
Finishing: npm audit
