### ISSUE TITLE
[BUG] NTLM Auth not works

### ISSUE THREAD

**Issue by whind** [npm/cli#2888]
### Current Behavior:
After I set npm config:
proxy=http://domain%5Cuser:pass@proxy:port/
https-proxy=http://domain%5Cuser:pass@proxy:port/
strict-ssl=false
registry=http://registry.npmjs.org/

I try to get angular:
npm install @angular/cli
And gets error:
npm ERR! code E407
npm ERR! 407 authenticationrequired - GET https://registry.npmjs.org/@angular%2fcli

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Local\npm-cache\_logs\2021-03-17T11_20_41_592Z-debug.log

With wireshark I see that npm try to login with Basic Authentication.
And proxy response with error 407.

In packages I found many libs that support NTLM Auth. So able to implement one of them to npm, for dowloading packages. But my skill in node is too low.

### Expected Behavior:
npm successfully pass authentication on proxy.
packages successfully downloads.

### Steps To Reproduce:
go behind ntlm proxy, that don't support Basic Auth.
set proxy config.
try to get angular.

### Environment:
Windows 10 in domain
NTLM proxy for internet
Node: 15.11.0
npm: 7.6.0

**Comment by wraithgar** [comment]
Adding NTLM auth support to npm would be a totally new feature, which are proposed and discussed over in our RFC repo https://github.com/npm/rfcs
