### ISSUE TITLE
[BUG] npm prune --production deletes local dependencies instead of only deleting the link

### ISSUE THREAD

**Issue by siyb** [npm/cli#2889]
### Current Behavior:

We have a local development dependency defined like this:

```json
  "devDependencies": {
    "our-local-dependency": "../../lib/our-local-dependency"
  }
```
When running `npm prune --production`, npm does not only delete the softlink but also the directory it is pointing to.

### Expected Behavior:

My assumption was that only the softlink would be deleted, but not the actual dependency itself

### Steps To Reproduce:

1. Create a project with a local development dependency
2. run `npm install`
3. run `npm prune --production`

### Environment:

- OS: Debian bullseye/sid
- Node: v12.16.3 (nvm)
- npm: 7.6.3 (I was able to reproduce this issue with 6.x.x as well)

**Comment by ssc-hrep3** [comment]
This occurs also when installing dependencies with `--production`: https://github.com/npm/cli/issues/2863

**Comment by siyb** [comment]
> This occurs also when installing dependencies with `--production`: #2863

I can reproduce this behavior as well!

**Comment by ssc-hrep3** [comment]
Is there any progress on this issue? For those with the same issue: As a workaround, remove all `devDependencies` from the `package.json` file temporarily and then install it productively (or run prune productively).
