### ISSUE TITLE
npm ERR! code ELSPROBLEMS

### ISSUE THREAD

**Issue by fantasyzed** [npm/cli#2897]
# What / Why

>I run the command 'npm ls' and get the the output: npm ERR! code ELSPROBLEMS

## When

* n/a

## Where

* n/a

### Current Behavior

* n/a

### Steps to Reproduce

* n/a

### Expected Behavior

* n/a

## Who

* n/a

## References

* n/a

**Comment by ruyadorno** [comment]
hi @fantasyzed that just means your installed dependencies have something unexpected, usually there are more error messages that describes each of the problems found.

I'm going to go ahead and close this issue but feel free to reopen or open a new one providing more info in case you're still having problems. Thanks!
