### ISSUE TITLE
[BUG] cb() never called!

### ISSUE THREAD

**Issue by zawsq** [npm/cli#2899]
npm install enmap
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2021-03-18T09_28_52_966Z-debug.log
$

**Comment by Rahul0262** [comment]
Try changing your internet connection.

**Comment by wraithgar** [comment]
https://github.com/npm/cli/issues/417
