### ISSUE TITLE
[BUG] On `npm install`, `prepare` script runs in workspaces only if no package-lock.json or node_modules are present

### ISSUE THREAD

**Issue by amatissart** [npm/cli#2900]
### Current Behavior:

`npm install` runs prepare scripts in workspaces on initial install (when no package-lock.json or node_modules exist).
On subsequent `npm install`, prepare scripts are no longer run for workspaces.

### Expected Behavior:

The presence of `package-lock.json` should not have an effect on the lifecycle scripts.

### Steps To Reproduce:

Use this sample repository to reproduce the issue: https://github.com/amatissart/npm-prepare-issue
A single workspace `packages/a` is defined.

Initial tree:
```
.
├── package.json
├── package-lock.json
└── packages
    └── a
        └── package.json
```

1. `npm install`
"prepare" script runs for the root package only.
```
.
├── node_modules
│   └── a -> ../packages/a
├── package.json
├── package-lock.json
├── packages
│   └── a
│       └── package.json
└── root-prepare
```

2. Clean up and remove package-lock.json 
`rm -r node_modules/ package-lock.json root-prepare`

3. `npm install` with no package-lock.json
Without package-lock.json, "prepare" scripts run for both the root package and workspaces.

```
.
├── node_modules
│   └── a -> ../packages/a
├── package.json
├── package-lock.json
├── packages
│   └── a
│       ├── a-prepare
│       └── package.json
└── root-prepare
```

### Environment:

- OS: Ubuntu 18.04
- Node: 14.16.0
- npm: 7.6.3

**Comment by basicdays** [comment]
Yeah just ran into this as well. It's preventing a scenario where a workspace package would have a bin file that needs to be transpiled first. Since the `prepare` script isn't being ran during install, `npm install` is failing because it can't find the transpiled file to link. If I remove the root `package-lock.json` file, then the first install will work.
