### ISSUE TITLE
[BUG] npm version from-git breaks

### ISSUE THREAD

**Issue by y-nk** [npm/cli#2902]
### Current Behavior:
When using `npm version from-git`, the command should not fail.

### Expected Behavior:
The command fails, because it tries to create a git tag (which already exists)

### Steps To Reproduce:

```
npm i -g npm@7
mkdir foo && cd foo
git init .
npm init -y
git add package.json
git commit -m 'initial commit'
git tag -m 1.0.1 v1.0.1
npm version from-git
```

```
npm ERR! code 128
npm ERR! command failed
npm ERR! command /usr/bin/git tag -m 1.0.1 v1.0.1
npm ERR! fatal: tag 'v5.0.0' already exists

npm ERR! A complete log of this run can be found in:
```

### Environment:
- Node: 15.0.1
- npm: 7.6.3

**Comment by dan-barbulescu** [comment]
Normally, this worked for me:

```
npm version from-git --no-git-tag-version
```

With npm@7.10.0 this now fails with:

```
npm ERR! code 128
npm ERR! command failed
npm ERR! command /usr/bin/git describe --tags --abbrev=0 --match='*.*.*'
npm ERR! fatal: No names found, cannot describe anything.
```

It works with npm@7.9.0, though.

**Comment by j-m** [comment]
Partially duplicated by https://github.com/npm/cli/issues/3238

This issue may be fixed by https://github.com/npm/libnpmversion/issues/15

**Comment by wraithgar** [comment]
This was fixed by https://github.com/npm/libnpmversion/pull/16
