### ISSUE TITLE
[BUG] local $PWD .npmrc not used when loading npm config

### ISSUE THREAD

**Issue by zhanwang626** [npm/cli#2904]
Hi npm/cli team, I am a software engineer from LinkedIn. Currently handreds of UI engineers suffered from this problem when running npx command. Can we fix this issue instead of running npx with setting `--userconfig .npmrc` everytime? Thanks! 
 
# What / Why
When running npx commands under some JavaScripts project directory, it will not pick up `.npmrc` from working directory as expected. Instead it will only pulls from `~/.npmrc` and ignores any `.npmrc` in current working directory.

## When
  * Whenever I run npx command

## Where
npx

### Current Behavior
npx only pulls from ~/.npmrc and ignores any .npmrc in current working directory.

### Expected Behavior
npx can picked up working directory's `.npmrc` successfully by default.

## References
https://github.com/npm/npx/issues/13

**Comment by nlf** [comment]
we've never loaded an `.npmrc` file from `$PWD` by default.

per the documentation:

> The four relevant files are:
> 
>        o per-project config file (/path/to/my/project/.npmrc)
> 
>        o per-user config file (~/.npmrc)
> 
>        o global config file ($PREFIX/etc/npmrc)
> 
>        o npm builtin config file (/path/to/npm/npmrc)

the bit left out of here is that the per-project config file is that we determine where your project is based on the location of a `package.json` file, so if you're in a directory that has no `package.json` but does have a `.npmrc` it will be ignored. if you include a `package.json` next to your `.npmrc` it should be detected as a project and loaded appropriately.

if you already have both files, and your config is _still_ not being loaded that's likely a bug. i'd need more information to help figure it out for you though, at minimum what version of npm/npx you're using, the operating system you're working on, and what your directory structure looks like.
