### ISSUE TITLE
[BUG] bundledDependencies not working when files is present, but bundleDependencies works.

### ISSUE THREAD

**Issue by fisherpro** [npm/cli#2907]
### Current Behavior:
When running npm install and pack against the following package.json file, the tgz file does not contain bundledDependencies listed.

```
{
  "name": "test",
  "version": "1.0.0",
  "description": "test",
  "main": "index.js",
  "scripts": {
    "test": "test"
  },
  "dependencies": {
    "graphql": "15.5.0"
  },
  "devDependencies": {
    "@nestjs/testing": "7.6.11"
  },
  "bundledDependencies": [
    "graphql"
  ],
  "files": [
    "lib/**/*"
  ],
  "repository": {
    "type": "git",
    "url": "none"
  },
  "author": "",
  "license": "ISC"
}
```

If 'files' attribute above is removed, bundledDependencies works as expected and packs graphql in with the tgz file. 
If 'files' is there and bundledDependencies is changed to bundleDependencies (without 'd'), then graphql is also found in the tgz file. 

### Expected Behavior:
Documentation seems to indicate bundledDependencies and bundleDependencies should have the same behavior. 
I also don't see a relationship between 'files' and bundledDependencies in the docs.

### Environment:
Was able to reproduce on Mac (10.14.6) and Redhat 7. 
```
npm --version
7.5.6
node --version
v14.5.0
```

**Comment by nlf** [comment]
confirmed, this will be fixed with an updated `npm-packlist` in the next release, the PR is linked above
