### ISSUE TITLE
[DOCUMENTATION?] npm install <pkg> runs pre and post install scripts is undocumented

### ISSUE THREAD

**Issue by CxRes** [npm/cli#2911]
### Current Behavior:
`npm install <pkg>` runs pre and post install scripts specified in `<pkg>`.  

### Expected Behavior:
Either pre and post install scripts must not run or this should be explicitly documented in the npm-install page. Also documentation on npm-scripts page is confusing with it stating that lifecycle scripts are run on `npm install` and `npm install -g <pkg>` (no mention of `npm install <pkg>`)

### Environment:
- OS: Windows 10 x64
- Node: 14.15.4
- npm: 7.6.3

**Comment by wraithgar** [comment]
The lifecycle scripts are documented here https://docs.npmjs.com/cli/v7/using-npm/scripts#npm-install

npm install docs do link to this page https://docs.npmjs.com/cli/v7/commands/npm-install#configuration-options-affecting-build-process and include it in the `See Also` section at the end.

**Comment by CxRes** [comment]
> The lifecycle scripts are documented here https://docs.npmjs.com/cli/v7/using-npm/scripts#npm-install 

The language here is strange. The impression I get is that the lifecycle events run for `npm install` (when run at root of a pkg) and `npm install -g <pkg>` and not `npm install <pkg>` (when run from root in another_pkg)

> npm install docs do link to this page https://docs.npmjs.com/cli/v7/commands/npm-install#configuration-options-affecting-build-process 

I do not understand the significance of these options to the lifecycle events for npm install? What am I failing to understand?

**Comment by wraithgar** [comment]
> The language here is strange. The impression I get is that the lifecycle events run for `npm install` (when run at root of a pkg) and `npm install -g <pkg>` and not `npm install <pkg>` (when run from root in another_pkg)

Yes this is the case.

> I do not understand the significance of these options to the lifecycle events for npm install? What am I failing to understand?

That was just one of the places in there that linked to more info about those scripts and what they do.

**Comment by CxRes** [comment]
> Yes this is the case.

But then it is a bug 😕!!! `preinstall` script runs for me when I run `npm install <pkg>` (when run from root in another_pkg).

**Comment by wraithgar** [comment]
I can not duplicate that behavior.  A script's preinstall script does not run when I install a package into it.

```sh
~/D/n/foo $ cat package.json |json scripts.preinstall
echo foo preinstall script; touch lifecycle/preinstall
~/D/n/foo $ npm install lodash

up to date, audited 5 packages in 482ms

found 0 vulnerabilities
~/D/n/foo $ ls lifecycle/
~/D/n/foo $

**Comment by CxRes** [comment]
I am saying something different. What I am claiming is that if lodash had a preinstall script, that would run when I `npm install lodash`. 

Now, I do not understand if that is intended or not. But documentation is not clear on this!

Also, I do not think the point went across earlier and there is much confusion as a result. eg why the docs would ever talk of a parent's preinstall script running when doing `npm install -g <pkg>` (See my comment/your response above). It must obviously be the `<pkg>`'s preinstall script and at least that's how I interpreted it!
