### ISSUE TITLE
[BUG] npm install <git_repo#commit-hash> fails

### ISSUE THREAD

**Issue by flash-me** [npm/cli#2919]
### Current Behavior:

⚠This works with npm 6⚠

We have an internal bitbucket repository, let say at https://my.bb.intern. 
One dependency is installed via git url, so in the package.json the entry says

```
"@bla/foo": "git+https://my.bb.intern/.....#1384"
```

We tried to install a new commit hash with 
```
npm i -D "git+https://my.bb.intern/.....#2223"
```

which fails with npm 7.6.3, but works with npm 6.x

### Expected Behavior:

Same behaviour like in npm 6. 

### Environment:
OS: Windows 10
Node: 14.15.3
npm 7.6.3
Git for Windows: 2.31.0.1 

### Here is one log
![image](https://user-images.githubusercontent.com/5240450/112108677-d04acc80-8bb0-11eb-9593-473ae9c4bc30.png)

### Weird behaviour

The git repo of the dependency has been cloned into the current working dir
![image](https://user-images.githubusercontent.com/5240450/112109996-924ea800-8bb2-11eb-88e5-edb1325987ab.png)

cheers
flash ⚡

**Comment by Holzhaus** [comment]
For me, installing from git is completely broken:

```
$ npm install -g octokit/rest.js
npm ERR! code 236
npm ERR! git dep preparation failed
npm ERR! command /usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/jan/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code ENOTDIR
npm ERR! npm ERR! syscall rename
npm ERR! npm ERR! path /tmp/lib/node_modules/@octokit/rest
npm ERR! npm ERR! dest /tmp/lib/node_modules/@octokit/.rest-RFojz3cC
npm ERR! npm ERR! errno -20
npm ERR! npm ERR! ENOTDIR: not a directory, rename '/tmp/lib/node_modules/@octokit/rest' -> '/tmp/lib/node_modules/@octokit/.rest-RFojz3cC'
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /home/jan/.npm/_logs/2021-04-19T17_06_12_172Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jan/.npm/_logs/2021-04-19T17_06_12_339Z-debug.log
```

**Comment by darcyclarke** [comment]
@flash-me can you try replicating this problem on the latest version of `npm`? (ie. `npm i -g npm`); @Holzhaus can you create a separate issue? (seems like your problem is different)

**Comment by flash-me** [comment]
@darcyclarke sure, but can't try it before Monday. I'll let you know.

cheers
flash ⚡

**Comment by flash-me** [comment]
hi @darcyclarke,

first of all. Sorry for the delayed answer....

I tried this again with `npm 7.14.0`. **Seems to be working**. 
What I did was `npm i -D "git+https://my.bb.internal/blab/foo#commitId"`

cheers
flash ⚡
