### ISSUE TITLE
[BUG] `npm install --save-exact` doesn't work in 7.7.0

### ISSUE THREAD

**Issue by ghost** [npm/cli#2932]
### Current Behavior:

`npm install --save-exact <package>` adds `save-prefix` to `package.json` in v7.7.0.

I have tracked it down to the removal of [`lib/utils/flat-options.js`](https://github.com/npm/cli/blob/v7.6.3/lib/utils/flat-options.js) ([lines 166-167](https://github.com/npm/cli/blob/v7.6.3/lib/utils/flat-options.js#L166-L167) in particular are important to this issue). I believe this file was removed and is intended to be replaced with the [unified config library](https://github.com/npm/config). This conditional setting of `savePrefix` needs to be handled still.

### Expected Behavior:

npm should save the exact version. No prefix should be added to `package.json`.

### Steps To Reproduce:

1. `npm i -g npm@7.7.0`
2. `npm init -y`
3. `npm install --save-exact typescript@4.2.3`
4. Note in `package.json` that `typescript` is `^4.2.3`

### Environment:

- OS: Manjaro 21.0
- Node: 10.24.0
- npm: 7.7.0

**Comment by ruyadorno** [comment]
fixed in **[npm@7.7.1](https://github.com/npm/cli/releases/tag/v7.7.1)**

**Comment by TomaszG** [comment]
I'm using npm@7.7.4 and neither `--save-exact` nor `-E` doesn't work :(
