### ISSUE TITLE
npm i geckodriver didn't work

### ISSUE THREAD

**Issue by noritxu3** [npm/cli#2933]
### Current Behavior:
When i do a npm install, the donwload of geckodriver in selenium standalone packages is not done correctyl so i have errors when i try to launch my tests

### Expected Behavior:
I should be able to install separately with npm install geckodriver

### Steps To Reproduce:
1.In windows
2. package.json//  "dependencies": {
    "@babel/cli": "^7.13.10",
    "@babel/core": "^7.13.10",
    "@babel/polyfill": "^7.12.1",
    "@babel/preset-env": "^7.13.12",
    "@babel/register": "^7.13.8",
    "@mapbox/node-pre-gyp": "^1.0.1",
    "@types/cucumber": "^7.0.0",
    "@types/node": "^14.14.35",
    "@wdio/allure-reporter": "^7.2.1",
    "@wdio/cli": "^7.2.3",
    "@wdio/dot-reporter": "^7.2.1",
    "@wdio/shared-store-service": "^7.2.3",
    "allure-commandline": "^2.13.8",
    "chai": "^4.3.4",
    "cucumber": "^6.0.5",
    "dotenv": "^8.2.0",
    "eslint": "^7.22.0",
    "eslint-config-airbnb": "^18.2.1",
    "eslint-config-airbnb-base": "^14.2.1",
    "eslint-config-prettier": "^7.2.0",
    "eslint-plugin-import": "^2.22.1",
    "fibers": "^5.0.0",
    "msedgedriver": "^87.0.0",
    "prettier": "^2.2.1",
    "selenium-standalone": "^6.23.0",
    "selenium-webdriver": "^4.0.0-alpha.7",
    "wdio-allure-reporter": "^0.8.3",
    "wdio-timeline-reporter": "^5.1.4",
    "webdriverio": "^7.2.3"
  },
  "devDependencies": {
    "@wdio/cucumber-framework": "^7.0.7",
    "@wdio/local-runner": "^7.2.1",
    "@wdio/mocha-framework": "^7.2.1",
    "@wdio/selenium-standalone-service": "^7.2.1",
    "@wdio/spec-reporter": "^7.2.1",
    "@wdio/sync": "^7.2.1",
    "chromedriver": "^87.0.7",
    "wdio-chromedriver-service": "^7.0.0"
  }
}
3.Npm install or (npm install geckodriver)
4. First error when npm install// **302 https://github.com/mozilla/geckodriver/releases/download/v0.29.0/geckodriver-v0.29.0-win64.zip unable to get local issuer certificate**
5. 
-->Second error when npm install geckodriver//  **npm ERR!       throw er; // Unhandled 'error' event
npm ERR!       ^
npm ERR! ErrorClass [RequestError]: unable to get local issuer certificate
npm ERR!     at ClientRequest.<anonymous> (C:\usr\pme100saas\front100-spa-automation\node_modules\geckodriver\node_modules\got\index.js:69:21)**

### Environment:
- Windows 10
- Node: v12.16.1
- npm: 7.6.3
-->

**Comment by darcyclarke** [comment]
Just tested this & it seems to be working fine for me (potentially this is a problem with your local environment/certs? maybe you're behind a firewall...); For the record, I was testing on Windows 10 (win32) as well & w/ `v.7.6.3`. Let me know if you're able to reproduce this on the latest `npm` (ie. `npm i -g npm` ~ should be >= `v7.7.1`) and if there's potentially any other context you may have about your environment/setup

**Comment by noritxu3** [comment]
Hi, i did what you advice me, i've got the same error when i do the npm i -g npm, the version of npm in my computer is the 7.74 not the 7.7.1. It's possible that is the reason of my error? 
Error in "getDownloadStream". Could not download https://github.com/mozilla/geckodriver/releases/download/v0.29.0/geckodriver-v0.29.0-win64.zip
See more details below:
302 https://github.com/mozilla/geckodriver/releases/download/v0.29.0/geckodriver-v0.29.0-win64.zip
unable to get local issuer certificate

**Comment by ljharb** [comment]
That error is an ssl error unrelated to npm.
