### ISSUE TITLE
[BUG] ERR! cb() never called! while installing @opengsn/gsn

### ISSUE THREAD

**Issue by Ardgevald** [npm/cli#2940]
### Current Behavior:
I'm trying to install https://www.npmjs.com/package/@opengsn/gsn with npm in a new npm project. I ran into issues to get it installed, it never got to the point where @opengsn/gsn is properly installed.
This is the log at installation : [2021-03-24T15_27_18_497Z-debug.log](https://github.com/npm/cli/files/6198638/2021-03-24T15_27_18_497Z-debug.log)

Currently, the project contains a node_modules but all the dependencies are extraneous. Log of `npm list`
[2021-03-24T15_46_52_029Z-debug.log](https://github.com/npm/cli/files/6198628/2021-03-24T15_46_52_029Z-debug.log)

### Expected Behavior:
When installing with `npm install @opengsn/gsn`, the project should contain all the dependencies in the node_modules folder without error. The last attempt was done using a fresh installation of npm.

### Steps To Reproduce:
1. new folder : `mkdir test`
2. go into folder : `cd test`
3. init npm project : `npm init`
4. install @opengsn/gsn : `npm install @opengsn/gsn`

### Environment:
- OS: Ubuntu 20.04
- Node: 14.16.0
- npm: 7.7.1

### Additional information

I had a previous installation of npm the first time I tried to install this, but the error was very different, maybe it can help pinpoint the problem.
[2021-03-24T09_06_12_113Z-debug.log](https://github.com/npm/cli/files/6198648/2021-03-24T09_06_12_113Z-debug.log)
[2021-03-24T09_06_10_920Z-debug.log](https://github.com/npm/cli/files/6198650/2021-03-24T09_06_10_920Z-debug.log)

**Comment by darcyclarke** [comment]
@Ardgevald I just tried this (I'm on osx though - w/ `v7.7.1`) & couldn't replicate the extraneous deps scenario you noted above (see the screenshot below):

![Screen Shot 2021-03-24 at 12 04 29 PM](https://user-images.githubusercontent.com/459713/112343070-285cfe00-8c99-11eb-81d2-f933902a13b7.png)

Potentially there's other issues you're facing. As a rule of thumb `"cb() never called!"` errors are a category of error that could be many things (most likely a race condition though); Check out this issue: https://github.com/npm/cli/issues/417 & this article: https://github.com/npm/cli/wiki/%22cb()-never-called%3F--I'm-having-the-same-problem!%22

Definitely let me know if you're able to consistently throw this error - in which case, we can potentially try troubleshooting what your environment may look like or other variables
