### ISSUE TITLE
[BUG] `npm config` throws/becomes unusable after setting `workspaces` or `workspace` config

### ISSUE THREAD

**Issue by darcyclarke** [npm/cli#2941]
### Current Behavior:
- `npm config` throws errors & becomes unusable when it sees defined `workspaces` or `workspace` config

### Expected Behavior:
- `npm config` should be exempt from this default behavior & not throw errors when it sees defined `workspaces` or `workspace` options (its core function/utility is to get/set that config)

### Steps To Reproduce:
1. `npm config set workspaces=true`
2. `npm config ...` throws

### Environment:
- OS: osx
- Node: 10.24.0
- npm: 7.7.1

**Comment by wraithgar** [comment]
This should be fixed in `v7.7.3`
