### ISSUE TITLE
npm install --unsafe-perm was remove in v6.11.0

### ISSUE THREAD

**Issue by darcyclarke** [npm/cli#295]
Original bug ticket: [https://npm.community/t/10250](https://npm.community/t/10250)
      Originally filed: 2019-09-25T22:01:13.247Z

**Comment by Seb35** [comment]
See also [npm-lifecycle#49](https://github.com/npm/npm-lifecycle/issues/49) for current state around --unsafe-perm. It seems the behaviour changed since this issue was reported (to another related bug).
