### ISSUE TITLE
[BUG] npm cache causes errors when a github dependency's branches change in certain ways.

### ISSUE THREAD

**Issue by trusktr** [npm/cli#2957]
https://github.com/npm/npm/issues/9395

What that solved? No status update was given there and the bot closed it after 30 days.

**Comment by nlf** [comment]
we handle git dependencies quite a bit differently in npm 7.x. without clear step by step instructions on how to reproduce this issue, the best advice i can give is to try it and see what happens.

if it doesn't work, please do feel free to open an issue and fill out our issue template the best you can. specifically step by step how to reproduce the issue would give us the greatest advantage in fixing it.
