### ISSUE TITLE
[BUG] process.env.npm_config_user_agent missing in v7

### ISSUE THREAD

**Issue by alexander-mai** [npm/cli#2960]
### Current Behavior:
```npm i --save-dev husky``` doesn't run the install and postinstall scripts after installing the package so the git hooks are never setup.
The reason is the missing environt variable ```npm_config_user_agent```

### Expected Behavior:
The env var ```npm_config_user_agent``` is set.
The variable is set on npm version 7.6.3.

### Steps To Reproduce:
```npm i --save-dev husky```
See the error message
```
husky > Setting up git hooks
Cannot destructure property `name` of 'undefined' or 'null'.
husky > Failed to install
```

### Environment:
* OS: MacOS 11.2.3
* Node: 10.24.0
* npm: v7.7.2

**Comment by jspivack** [comment]
Also seeing this in 7.7.4 when trying to run a script with `run-script-os`
