### ISSUE TITLE
[BUG] ETIMEDOUT 104.16.20.35:443

### ISSUE THREAD

**Issue by ohardy** [npm/cli#2961]
### Current Behavior:
Everything is working well with 7.3.0 and 7.6.3, it’s really fast too.
When I upgrade npm to any version of 7.7.x, nothing work anymore in my CI. npm become really slow and timeout.

### Expected Behavior:
Install packages

### Steps To Reproduce:
```
export NODE_ENV=development
npm ci
```

### Environment:
- Docker version 20.10.5, build 55c4c88
- Image: node:15.12.0-alpine
```
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code ETIMEDOUT
npm ERR! syscall connect
npm ERR! errno ETIMEDOUT
npm ERR! network request to https://registry.npmjs.org/has-values/-/has-values-0.1.4.tgz failed, reason: connect ETIMEDOUT 104.16.18.35:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly. See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2021-03-25T06_22_18_114Z-debug.log
```

Can send the log if necessary.

**Comment by nlf** [comment]
are you seeing this only in your CI environment, or locally as well? does the issue happen consistently, or only sometimes? do you use a proxy at all?

the log file would definitely be helpful if you can provide that

**Comment by ohardy** [comment]
Only in my CI environment.

At the time of the creation of the issue, it had been more than 10 hours that the version 7.7.x never worked and that the previous versions worked every time.

Everything is working well since this morning, it's really strange.

[2021-03-25T06_22_18_114Z-debug.log](https://github.com/npm/cli/files/6215291/2021-03-25T06_22_18_114Z-debug.log)

**Comment by nlf** [comment]
i'm not seeing anything of interest in the log file, and since you mention that everything is working well now i'm starting to think this may have just been some networking problems our CDN was having and is unrelated to npm.

i'm going to close this, but if it remains a problem please let us know.
