### ISSUE TITLE
error cb() never called!

### ISSUE THREAD

**Issue by dgoyes** [npm/cli#2962]
At the end of apiconnect install package, generates this log:

4551 timing reifyNode:node_modules/apiconnect/node_modules/rxjs Completed in 506530ms
4552 timing npm Completed in 821764ms
4553 error cb() never called!
4554 error This is an error with npm itself. Please report this error at:
4555 error <https://github.com/npm/cli/issues>

**Comment by nlf** [comment]
see this issue https://github.com/npm/cli/issues/417

and please fill out our issue templates fully to the best of your ability.
