### ISSUE TITLE
[BUG] `npm install --save-exact` doesn't work in 7.7.4

### ISSUE THREAD

**Issue by selrond** [npm/cli#2963]
Continuing with https://github.com/npm/cli/issues/2932#issuecomment-806574078

### Current Behavior:
`npm i -E <package>` or `npm i --save-exact <package>` produces `"<package>": "^1.2.3"`

### Expected Behavior:
should produce `"<package>": "1.2.3"`

### Steps To Reproduce:
`npm i -E <package>`

### Environment:

- OS: macOS Catalina 10.15.7
- Node: 15.12.0
- npm: 7.7.4

**Comment by nlf** [comment]
this was fixed in npm@7.7.5 and i've confirmed it can't be reproduced in versions after that.
