### ISSUE TITLE
[DOCS] Typo in npm-scripts section

### ISSUE THREAD

**Issue by darcyclarke** [npm/cli#297]
Original bug ticket: [https://npm.community/t/10847](https://npm.community/t/10847)
      Originally filed: 2019-11-01T14:02:40.831Z

**Comment by ajaymathur** [comment]
Hey @darcyclarke , I think we can close this issue. Unless my PR did not resolved the real issue. 🙂

**Comment by darcyclarke** [comment]
Thanks @ajaymathur!
