### ISSUE TITLE
[BUG] Unable to install npm@7.7.5

### ISSUE THREAD

**Issue by SiddharthShyniben** [npm/cli#2975]
### Current Behavior:
When I am trying to install npm@7.7.5, I get an error saying that `No matching version found for npm@7.7.5.`

### Expected Behavior:
npm should be updated to the latest version (v7.7.5)

### Steps To Reproduce:
Run `npm i npm@7.7.5 -g` 

### Environment:

- OS: macOS Sierra (10.12.6)
- Node: 14.15.1
- npm: 7.6.3

**Comment by ljharb** [comment]
What registry are you using? (npm config get registry)

**Comment by SiddharthShyniben** [comment]
`https://registry.npmjs.org/` is the registry being used.

**Comment by darcyclarke** [comment]
@SiddharthShyniben wasn't able to replicate this, potentially there's something else happening in your network or in your local environment/config... might also be a locale/regional caching error 🤷🏼‍♂️ I'd try switching networks, or VPNing to a different locale & seeing if maybe that helps & just ensuring that you can/do see `7.7.5`'s Packument information (ref. https://registry.npmjs.org/npm/7.7.5 or https://registry.npmjs.org/npm)

`npm i -g npm@7.7.5` should work though (personally just tested on OSX `10.15.7`, Node `14.15.2` & npm `7.6.3`)

**Comment by SiddharthShyniben** [comment]
I see. I'm on macOS 10.13. That might be the problem. I'll try again as soon as I can.

**Comment by nlf** [comment]
closing because this looks to be an issue with a delay in our CDN. please reopen if you're still having problems.

**Comment by SiddharthShyniben** [comment]
It's still broken @nlf. It does not install

**Comment by SiddharthShyniben** [comment]
Ok, got it fixed by reinstalling nodejs
