### ISSUE TITLE
[BUG] ENETUNREACH errors during npm install (DNS, IPv6)

### ISSUE THREAD

**Issue by jansepke** [npm/cli#2983]
### Current Behavior:
After upgrading from NPM v6 to v7 we see ENETUNREACH errors during `npm install` in our CI environment. This does not happen every time but it happens in ca. 50% of all cases and across all our projects. But we could not reproduce this issue locally.  This is an example error output, but the package can be different every time.

```bash
npm ERR! code ENETUNREACH
npm ERR! syscall connect
npm ERR! errno ENETUNREACH
npm ERR! request to https://registry.npmjs.org/punycode/-/punycode-1.3.2.tgz failed, reason: connect ENETUNREACH 2606:4700::6810:1923:443 - Local (:::0)

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-29T09_20_54_406Z-debug.log
```

It only happens when npm resolves `registry.npmjs.org` to any IPv6 address. The error was gone after downgrading back to NPM v6. The ENETUNREACH error happens because the System where npm is running does not support outgoing IPv6 connections, so my question is why does npm try to initiate a IPv6 connection in 50% of the cases?

### Expected Behavior:
`npm install` works without a problem

### Environment:
- OS: Alpine Linux v3.13
- Node: v14.16.0
- npm: 7.6.3 and 7.7.5
- DNS: 8.8.8.8
- CI System: Concourse CI
- Infrastructure: AWS Cloud

**Comment by nlf** [comment]
this is node core behavior, we do not signal whether we want an ipv4 or ipv6 connection at any point.

we could certainly implement a new feature that allows you to tell us to use only one or the other, though. i'd suggest starting a discussion here https://github.com/npm/feedback/discussions

**Comment by jansepke** [comment]
This does only happen after upgrading to NPM v7 without changing the node version. So it seems to be related to a change made between NPM v6 and v7. Could you please reopen this issue.

**Comment by a2nt** [comment]
Having the same issue with the latest NPM

OS: Debian Linux
Node: v18.18.2
npm: 10.1.0

It happens when local network has IPv6, but there's no external IPv6 access.
So NPM tries to get repositories using IPv6, but it's accessible by IPv4 only
