### ISSUE TITLE
Terminal crashes right after running "npm install" command from any of the projects

### ISSUE THREAD

**Issue by Arsasana** [npm/cli#2984]
"npm install" command is not working as expected,
as soon as I run npm install command from any of the terminals (say powershell/command prompt), terminal gets closed abruptly.
This is the cases with different projects. 
Tried degrading and upgrading the versions of nodejs, but was not able to fix the issue
Tried cleaning the cache via npm cache clean --force, still the issue didn't get solved
- OS: Windows 10
- Node: 14.16.0

Can someone help me in fixing this issue?

**Comment by nlf** [comment]
we need more information that would be present in our issue template. at a minimum we'll need to know what version of npm you're using.

you say this happens with different projects, do you have any projects that work correctly?
do you see any error messages or the like before the terminal closes?
do you get a crash report from windows?

if you can reproduce this reliably, the steps to do so would help us diagnose what's going on.

**Comment by Arsasana** [comment]
Hi,

Sorry my terminology might be wrong , by crashing I mean terminal is getting closed while the command is executing.
There aren't any logs/ any windows report as such and no error message even.

Thanks,
Arpitha

**Comment by nlf** [comment]
i still can't reproduce this and need significantly more information in order to try to diagnose. if this is still happening to you, please open a new issue and fill out the issue template in its entirety.
