### ISSUE TITLE
Error al instalar dependencias 

### ISSUE THREAD

**Issue by Barents1** [npm/cli#2986]
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Local\npm-cache\_logs\2021-03-29T17_24_11_612Z-debug.log

**Comment by nlf** [comment]
see https://github.com/npm/cli/issues/417

and please fill out our issue template as completely as you can if you are still experiencing trouble
