### ISSUE TITLE
[BUG] nohoist doesn't work for NPM workspaces

### ISSUE THREAD

**Issue by mesqueeb** [npm/cli#2988]
### Current Behavior:
NPM workspaces work just like yarn workspaces, we have been wanting to switch to NPM for years!

However, we desperately need to use the `nohoist` feature from yarn workspaces for a variety of reasons. Some packages don't work well when hoisted.

### Expected Behavior:
When NPM makes workspaces and they work just like yarn, I'd expect to also have the `nohoist` feature! Therefore I'd love this to be implemented relatively soon!! : )

### Steps To Reproduce:
1. switch out yarn workspaces for npm 7.0 workspaces
2. `nohoist` stops to work

### Environment:
all

**Comment by nlf** [comment]
this isn't a bug, it's a feature request. we do not document that we support `nohoist` or that we're fully compatible with yarn features (we aren't).

if this feature is important to you, i would suggest reviewing the proposals in https://github.com/npm/rfcs to see if one already discusses it and if not, start a new proposal.

**Comment by MaximeBernard** [comment]
For anyone coming here, this is the RFC you're looking for https://github.com/npm/rfcs/issues/287
