### ISSUE TITLE
Npm install exits without installing with ERR subset is not a function 

### ISSUE THREAD

**Issue by vsrini7** [npm/cli#2991]
Using npm 7.7.5, node 12.21.0 on ArchLinux
Since this morning, npm install is not working LOCALLY (works globally) with any package (tried with express, webpack etc).  Was working perfectly till yesterday (and didnt do any upgrades/ system updates etc in the interim). 
It clearly accesses the npm registry fully successfully all through and in the log can see that runs through to the end where it goes through without error  till 
verbose node v12.21.0
verbose npm v7.7.5
error subset not a function 
verbose exit 1

Npm init working locally, but npm install specifically not working and not working for any package. 

Tried npm cache clean --force. Uninstalled npm, node and re-installed from repo, directly and doing a package build as well. Tried lts versions of both npm and node. Also did a archlinux update to be sure.
Nothing worked. Would be very grateful for help.

**Comment by vsrini7** [comment]
Was solved by installing npm again using npm for some reason. Was not getting fixed by uninstalling and reinstalling npm from arch repositories directly. 
Still not understood why. But solved

**Comment by ljharb** [comment]
@vsrini7 npm comes with node, and should only be installed by npm itself, or by npm’s install script (which is only rarely needed). It’s not distributed by itself.

**Comment by vsrini7** [comment]
Thanks so very much Jordan for explaining.
