### ISSUE TITLE
Error with NPM itself

### ISSUE THREAD

**Issue by jozefajogwu** [npm/cli#3003]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'admin-lte@3.0.0-alpha.2',
1 verbose cli   '--save'
1 verbose cli ]
2 info using npm@6.14.9
3 info using node@v14.15.3
4 verbose npm-session 0e9c0538f6d95e8c
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/admin-lte 3730ms (from cache)
8 timing npm Completed in 132713ms
9 error cb() never called!
10 error This is an error with npm itself. Please report this error at:
11 error <https://npm.community>

**Comment by ljharb** [comment]
#417
