### ISSUE TITLE
[BUG] npm publish with error: maintainers error by using npm@7.x

### ISSUE THREAD

**Issue by love477** [npm/cli#3005]
### Current Behavior:
run npm publish to publish private npm package with error:
```
400 Bad Request - PUT http://registry.npm.xxx.com/@xxx%2ftestxxx - maintainers error
```

### Expected Behavior:
publish private npm package successful.

### Steps To Reproduce:
Run npm publish to publish  private npm pakcage will error.

I change my local npm to 6.14.12, it works ok.

### Environment:
- OS: mac os 11.2.3
- Node: 12.16.3
- npm: 7.7.6

**Comment by darcyclarke** [comment]
@love477 can you try replicating this problem on the latest version of `npm`? (ie. `npm i -g npm`) We've changed/fixed quite a bit since you file this

**Comment by love477** [comment]
This error still exists.
When I publish my package to private npm system, failed with this error.
Is problem to private npm system??
npm version : 7.14.0
mac: 11.2.3
node: 12.16.3
