### ISSUE TITLE
y18n vulnerability

### ISSUE THREAD

**Issue by networkandcode** [npm/cli#3006]
Hi, Prisma cloud scan for our docker container which had node 12 and npm 6.14.11, detected a vulnerability for the y18n 4.0.0 package which is installed as part of npm. We have tried upgrading npm with npm i npm@latest -g, I think even that has the same issue. Any solution for this please.

One other thing we tried is, npm i y18n@5.0.5 -g and then npm i npm@latest -g
But then it gave a different compliance issue

Private keys stored in image
Cause: Found: /usr/lib/node_modules/npm/node_modules/node-gyp/test/fixtures/server.key

**Comment by darcyclarke** [comment]
You can get the latest v6 which has the security patch for the `y18n` vuln by running `npm i -g npm@6` (latest v6 should be [`v6.14.12`](https://github.com/npm/cli/releases/tag/v6.14.12)) - Node.js should be shipping versions of `12`/`14` that contain this version of `npm` next week as far as I know. `npm` v7 (latest v6 should be [`v7.7.6`](https://github.com/npm/cli/releases/tag/v7.7.6)) should not have any production dependencies on `y18n` & if you install our dev deps you should get `y18n@4.0.1` (the patched version of the `v4.x` release line) as it's a transitive dep of `tap`

**Comment by networkandcode** [comment]
@darcyclarke Thanks for the response, just curious to know if there would be any impact for the existing packages by this change

**Comment by networkandcode** [comment]
I think the issue still exists.. I tried the following inside the dockerFile:
```
ENV NODE_VERSION=12
ENV NPM_VERSION=6

# Install node
RUN curl -sL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash
RUN apt install -y nodejs

# Upgrade npm
RUN npm install npm@${NPM_VERSION} -g
```

```
Step 11/30 : RUN npm install npm@${NPM_VERSION} -g
 ---> Running in 756fd74fc6c5
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
/usr/bin/npx -> /usr/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.14.12
updated 2 packages in 6.983s
```

**Comment by networkandcode** [comment]
Please ignore, I think it was not properly tagged in the registry first, works !!!
