### ISSUE TITLE
NPX gives "command not found" error when running another npx command

### ISSUE THREAD

**Issue by joebochill** [npm/cli#3007]
### Current Behavior:

I have a CLI tool published to npm which is used to create new projects in various JS frameworks. Behind the scenes it calls, e.g., `npm_config_yes=true npx create-react-app myappname`. 

The expected usage is `npx -p @pxblue/cli@beta pxb new react`.

This works as expected with NPM v6. With npm v7, it throws:
```
Error: Command failed: npx create-react-app myappname
sh: create-react-app: command not found
```
If I copy this 'failed command' into my terminal, it runs fine.
If I install @pxblue/cli globally and then run it, it works as expected, so I suspect there is something going on with npx.

This is not limited to just create-react-app. Any command run via npx will fail (e.g., `npx cowsay helloworld`) with the same message.

### Expected Behavior:

The underlying command should execute successfully when running the CLI via npx.

### Steps To Reproduce:
1. Run `npx @pxblue/cli@beta pxb new react` 
2. Answer the prompts (selections do not matter) - to skip the prompts, you can call `npx -p @pxblue/cli@beta pxb new react --name=sample --language=ts --lint --prettier --template=blank` instead
3. See error...
![image](https://user-images.githubusercontent.com/29152776/113213698-857f2380-9246-11eb-8308-d4409ccf26ee.png)

### Environment:
- OS: MacOS Catalina
- Node: v15.13.0
- npm: v7.7.6

**Comment by stackzzcryp3c** [comment]
Bug fix

**Comment by nlf** [comment]
this was an issue with the package consuming npm, not npm itself, so closing.

**Comment by joebochill** [comment]
@nlf respectfully, I don't believe that's accurate. If you read the full report, the package consuming npm works fine under version 6 and works fine with version 7 when installed globally, but not via npx. 

I merely used the package as an example to illustrate the problem. If it would be helpful, I can make a simpler reproduction example that removes all the extraneous package-related functionality.
