### ISSUE TITLE
[BUG] npm v7 cannot publish to private registry (v6 works)

### ISSUE THREAD

**Issue by dong2590** [npm/cli#3010]
### Current Behavior:
While trying to publish packages to my private repository, I get 128 error when using npm v7
I don't want to publish to github but it will ignore my  registry

Here console print
```bash
npm publish packages/mypackage--tag beta  --registry=http://my/registry/
npm ERR! code 128
npm ERR! command failed
npm ERR! **command git ls-remote ssh://git@github.com/packages/mypackage.git**
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/anymo/.npm/_logs/2021-04-01T06_23_16_755Z-debug.log
```

BUT  IT'S WORKING WITH v6 (6.14.10)
Here console print
```bash
npm publish packages/mypackage--tag beta  --registry=http://my/registry/
npm notice
npm notice 📦  @base/mypackage@1.6.0-beta.0
npm notice === Tarball Contents ===

npm notice 378B  index.js
npm notice 700B  package.json
npm notice 1.8kB CHANGELOG.md
npm notice 135B  README.md
npm notice === Tarball Details ===
npm notice name:          @base/mypackage
npm notice version:       1.6.0-beta.0
npm notice package size:  2.8 kB
npm notice unpacked size: 7.5 kB
npm notice shasum:        820aa6b7e2ad6de97b6e70b88580a5ae248cd0c8
npm notice integrity:     sha512-DsqPPQYpGpBnz[...]KA2DxgNBlls8w==
npm notice total files:   9
npm notice
npm ERR! code EPRIVATE
npm ERR! This package has been marked as private
npm ERR! Remove the 'private' field from the package.json to publish it.
```
### Expected Behavior:
npm  publish  work like v6

### Steps To Reproduce:
Do npm publish with npm v7

### Environment:
- OS: macOS 10.14.6
- Node: v10.23.2
- npm: 7.7.6

**Comment by MrJuliuss** [comment]
Hi, i have the same error.

**Comment by visglz** [comment]
I can confirm the problem also with npm 7.7.6 and 7.11.0.

The problem occurs when you specificy a relative folder, see help for `npm publish`:

```
$ npm publish -h
npm publish

Publish a package

Usage:
npm publish [<folder>]
```

With npm v7 the following fails, because npm assumes a package `parent/folder` and wants to publish it to github:

```
$ npm publish offlinejsbuild/pkg1
npm ERR! code 128
npm ERR! command failed
npm ERR! command git ls-remote ssh://git@github.com/offlinejsbuild/pkg1.git
npm ERR! ERROR: Repository not found.
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/visglz/.npm/_logs/2021-04-23T12_23_27_164Z-debug.log
```

With npmv6 (just tested 6.14.12) the foldername was correctly recognized and upload worked to the correct internal registry.

Funny side note: When you specify an absolute pathname then the upload also works with npm v7, e.g. `npm publish /absolute/path/offlinejsbuild/pkg1`.

**Comment by valex91** [comment]
for me it avoid the issue if I specify --registry <REGISTRY> while doing npm publish

**Comment by darcyclarke** [comment]
In `v7` we expect that you provide `npm publish` a proper file path (ie./ex. `npm publish ./path`) but understand the documentation isn't great here; ~I'll leave this open until we clean up the doc to explicitly note it~

**Comment by visglz** [comment]
Hm. I am not sure, if this is really a documentation issue. Why should `my/path` not be a proper relative file path? I don't know the planned documentation change, but currently `npm publish` takes  either a path to a package file or a path to a folder. So there should be no room for misinterpretation regarding the argument being a package name for github.

Also note that in both cases a registry was set explicitely. @dong259 set it in the command line, mine was set in `package.json`s `publishConfig` (didn't mention that explicitely).

**Comment by darcyclarke** [comment]
`my/path` is unfortunately a shorthand for you github username/repo.
