### ISSUE TITLE
[BUG] Accessing packages not listed in package.json

### ISSUE THREAD

**Issue by basickarl** [npm/cli#3011]
I am unsure if this is to be posted here, or in the node binary issues. If so please do tell and I'll re-create it in the correct place.

### Current Behavior: 
When installing a package that uses package X, package X is accessible in the code without it being defined in package.json dependencies or devDependencies.

### Expected Behavior: 
Should output in the terminal: "MODULE_NOT_FOUND".

### Steps To Reproduce:

package.json
```
{
  "name": "sandbox",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "webpack-dev-server": "3.11.2"
  },
  "devDependencies": {},
  "scripts": {
    "test": "mocha"
  },
  "author": "",
  "license": "ISC"
}
```
index.js
```
const yargs = require('yargs');
console.log('ok');
```

run:
```
npm i
node index.js
```

### Environment:

- macOS 10.15.7
- Node: 13.14.0
- npm: 7.7.6

Is this expected behavior? It seems very weird. Also this could cause security concerns accessing packages not listed.

**Comment by ljharb** [comment]
This is not a bug, it's the way node's algorithm works, combined with npm's (desired) deduping behavior that hoists things to the top level of `node_modules`.

The way to enforce this is with a linter - eslint-plugin-import has a rule for it.

**Comment by basickarl** [comment]
@ljharb An explanation and solution, thank you!
