### ISSUE TITLE
[BUG] npm update removes nested node_modules

### ISSUE THREAD

**Issue by PatrickSpies** [npm/cli#3012]
### Current Behavior:
With npm@7 `npm update` removes nested node_modules from formerly installed package.

### Expected Behavior:
`npm update` keeps or updates nested node_modules to keep the functionality of the package

### Steps To Reproduce:
1. Create new project (`npm init`)

2. Install module with nested node_modules (e.g. `npm install claudia`)
> $ npm install claudia
>
> added 231 packages, and audited 232 packages in 13s
> 
> 6 vulnerabilities (3 low, 1 moderate, 2 high)
> 
> To address all issues, run:
>   npm audit fix
> 
> Run `npm audit` for details.

[package.json_install.txt](https://github.com/npm/cli/files/6243288/package.json_install.txt)
[package-lock.json_install.txt](https://github.com/npm/cli/files/6243289/package-lock.json_install.txt)

=> node_modules/claudia/node_modules/ contains all dependencies of claudia as defined in [npm-shrinkwrap.json](https://github.com/claudiajs/claudia/blob/master/npm-shrinkwrap.json)
> $ ls node_modules/claudia/node_modules/
> @babel               buffer-crc32      decompress-tarbz2        events                      gunzip-maybe             jasmine-core                           minimist          prelude-ls                 shebang-regex        universalify
> acorn                buffer-fill       decompress-targz         exit                        has-flag                 jasmine-spec-reporter                  mkdirp            process-nextick-args       signal-exit          uri-js
> acorn-jsx            buffer-from       decompress-unzip         external-editor             https-proxy-agent        jmespath                               ms                progress                   slice-ansi           url
> agent-base           callsites         deep-is                  fast-deep-equal             iconv-lite               js-tokens                              mute-stream       pump                       sprintf-js           util-deprecate
> ajv                  chalk             doctrine                 fast-json-stable-stringify  ieee754                  js-yaml                                natural-compare   pumpify                    stream-shift         uuid
> ansi-escapes         chardet           dotenv                   fast-levenshtein            ignore                   json-schema-traverse                   nice-try          punycode                   string-width         v8-compile-cache
> ansi-regex           chownr            duplexify                fd-slicer                   import-fresh             json-stable-stringify-without-jsonify  normalize-path    querystring                string_decoder       which
> ansi-styles          cli-cursor        emoji-regex              figures                     imurmurhash              jsonfile                               object-assign     readable-stream            strip-ansi           wordwrap
> archiver             cli-width         end-of-stream            file-entry-cache            inflight                 lazystream                             oh-no-i-insist    regexpp                    strip-dirs           wrappy
> archiver-utils       color-convert     escape-string-regexp     file-type                   inherits                 levn                                   once              remove-trailing-separator  strip-json-comments  write
> argparse             color-name        eslint                   flat-cache                  inquirer                 lodash                                 onetime           resolve-from               supports-color       xml2js
> astral-regex         colors            eslint-config-crockford  flatted                     is-deflate               lodash.assign                          optionator        restore-cursor             table                xmlbuilder
> async                commander         eslint-config-defaults   fs-constants                is-extglob               lodash.defaults                        os-tmpdir         rimraf                     tar-fs               xtend
> aws-sdk              compress-commons  eslint-scope             fs-extra                    is-fullwidth-code-point  lodash.difference                      pako              run-async                  tar-stream           yauzl
> balanced-match       concat-map        eslint-utils             fs.realpath                 is-glob                  lodash.flatten                         parent-module     rxjs                       text-table           zip-stream
> base64-js            core-util-is      eslint-visitor-keys      functional-red-black-tree   is-gzip                  lodash.isplainobject                   path-is-absolute  safe-buffer                through
> bl                   crc               espree                   get-stream                  is-natural-number        lodash.toarray                         path-key          safer-buffer               through2
> brace-expansion      crc32-stream      esprima                  glob                        is-promise               lodash.union                           peek-stream       sax                        tmp
> browserify-zlib      cross-spawn       esquery                  glob-parent                 is-stream                make-dir                               pend              seek-bzip                  to-buffer
> buffer               debug             esrecurse                globals                     isarray                  mimic-fn                               pify              semver                     tslib
> buffer-alloc         decompress        estraverse               graceful-fs                 isexe                    minimal-request-promise                pinkie            sequential-promise-map     type-check
> buffer-alloc-unsafe  decompress-tar    esutils                  graceful-readlink           jasmine                  minimatch                              pinkie-promise    shebang-command            unbzip2-stream

3. Run `npm update`
> $ npm update
> 
> removed 230 packages, and audited 2 packages in 5s
> 
> found 0 vulnerabilities

[package.json_update.txt](https://github.com/npm/cli/files/6243300/package.json_update.txt)
[package-lock.json_update.txt](https://github.com/npm/cli/files/6243301/package-lock.json_update.txt)

=> node_modules/claudia/node_modules/ is empty
> $ ls node_modules/claudia/node_modules/
> @babel

### Environment:

> $ npm version
> {
>   'nested-test': '1.0.0',
>   npm: '7.6.0',
>   node: '14.4.0',
>   v8: '8.1.307.31-node.33',
>   uv: '1.37.0',
>   zlib: '1.2.11',
>   brotli: '1.0.7',
>   ares: '1.16.0',
>   modules: '83',
>   nghttp2: '1.41.0',
>   napi: '6',
>   llhttp: '2.0.4',
>   openssl: '1.1.1g',
>   cldr: '37.0',
>   icu: '67.1',
>   tz: '2019c',
>   unicode: '13.0'
> }

**Comment by nlf** [comment]
this is fixed in 7.11.1
