### ISSUE TITLE
[BUG] npm -v returns 7.7.6 after installing 7.8.0

### ISSUE THREAD

**Issue by ChromaticRanger** [npm/cli#3024]
### Current Behavior:
After installing via `npm install -g npm@7.8.0` `npm -v` returns previous version `7.7.6`

If I run `npm -g list` I do see `npm@7.8.0` listed

### Expected Behavior:
`npm -v` should return `7.8.0`

### Steps To Reproduce:
1. update npm via `npm install -g npm@7.8.0`
2. run command `npm -v`
3. inspect output
4. verify the version number is 7.7.6

### Environment:
OS: Manjaro Linux x86_64
Node: 15.13.0
npm: 7.8.0

**Comment by ljharb** [comment]
What does `which npm` print out?

**Comment by ChromaticRanger** [comment]
@ljharb `which npm` prints `/usr/bin/npm`

**Comment by ChromaticRanger** [comment]
Hmm. I may have to retract this as something weird is going on on my system. I just rebooted and opened a fresh terminal and now `npm -v` shows `7.6.3` !, `npm -g list` still shows `npm@7.8.0`

**Comment by ljharb** [comment]
And which node, and npm root -g?

**Comment by ChromaticRanger** [comment]
`which node` `/usr/bin/node`
`npm root -g` `/home/martin/.npm-global/lib/node_modules`

Happy to be told I somehow have stuff in the wrong place and I should start again. ;-)

**Comment by ChromaticRanger** [comment]
I've drilled into the above node_modules directory and into the npm directory and the README.md in there is for 7.8.0

npm -v still currently shows 7.6.3 not sure where 7.7.6 (that was showing before I rebooted) has gone.

**Comment by ljharb** [comment]
You have a “prefix” set to that npm-global place, so your npm install -g is putting it there, and not overwriting the real global one.

I’d suggest removing that setting (from ~/.npmrc).

**Comment by ChromaticRanger** [comment]
I've removed that setting and reinstalled 7.8.0 globally and npm -v now shows 7.8.0

I do vaguely remember adding that  prefix as I was having problems installing as my user before and would always need to do a sudo. Some random search took me to an article that suggested the prefix would solve that problem, and it did, but obviously created others.

Thanks for your help. I will close this now as resolved now.

**Comment by ChromaticRanger** [comment]
This turned out to be my local environment so closing as resolved.

**Comment by ljharb** [comment]
You're supposed to use sudo when you have a system-wide node. To avoid that, you may want to use a user-level version manager, like nvm or nave.
