### ISSUE TITLE
[BUG] npx create-react-app app-react

### ISSUE THREAD

**Issue by hdpklm** [npm/cli#3031]
$ npx create-react-app app-react

Creating a new React app in C:\Mobile App\app-react.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Local\npm-cache\_logs\2021-04-05T15_04_02_525Z-debug.log

Aborting installation.
  npm install --save --save-exact --loglevel error react react-dom react-scripts cra-template has failed.

Deleting generated file... package.json
Deleting app-react/ from C:\Mobile App
Done.

**Comment by nlf** [comment]
see #417 

please reopen and be sure to fill out our issue template as completely as you can if you're still experiencing problems.
