### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by Rose2161** [npm/cli#3035]
### Environment:

The Google Play version of the Termux app no longer
receives updates. For more information, visit:
https://wiki.termux.com/wiki/Termux_Google_Play

~ $
~ $ npm i -g serverless && serverless init sf_FnsSpZRg
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2021-04-07T05_35_53_307Z-debug.log
~ $
~ $
~ $

**Comment by nlf** [comment]
see #417 and if you continue to see this error be sure to fill out our issue template as fully as you're able.

**Comment by warp9pnt9** [comment]
@Rose2161

> ### Environment:
> The Google Play version of the Termux app no longer
> receives updates. For more information, visit:
> https://wiki.termux.com/wiki/Termux_Google_Play

Also, use [F-Droid](https://f-droid.org/) to pull a more up-to-date Termux.  "no longer receives updates" is a red flag.  Just to rule out the potential of some Termux bug causing the issue.
