### ISSUE TITLE
Angular npm XLSX package add Comments to Cell or Columns

### ISSUE THREAD

**Issue by aydin-faruk** [npm/cli#3037]
Hi there!

I am using Excel 2016. I'm trying to add a comment to the Excel column header. For example: A1.c
I use your package 'xlsx' in Angular for this.
package: [https://www.npmjs.com/package/xlsx](https://www.npmjs.com/package/xlsx)
Comments can be added. But the excel 2016 version shows the comment but is not hidden. I've even added 'hidden = true'. But it still doesn't work. I'm having this problem because I'm using the Excel 2016 version. Can you please help?

`staffWorksheet.A1.c = [];
staffWorksheet.A1.c.hidden = true;
staffWorksheet.A1.c.push({a:"Test Title", t:"Test comment."});
`

Thank you. Best wishes!

**Comment by nlf** [comment]
this repository is for the `npm` utility itself, not for the packages stored in the npm registry.

https://github.com/SheetJS/sheetjs is a link to the repository for the package you're attempting to use, which is linked in the right side of the page you provided.

**Comment by aydin-faruk** [comment]
Yes, but will cell or columns comments not work in excel 2016 version?

**Comment by aydin-faruk** [comment]
> this repository is for the `npm` utility itself, not for the packages stored in the npm registry.
> 
> https://github.com/SheetJS/sheetjs is a link to the repository for the package you're attempting to use, which is linked in the right side of the page you provided.

Yes, but will cell or columns comments not work in excel 2016 version?

**Comment by aydin-faruk** [comment]
Yes, but will cell or columns comments not work in excel 2016 version?
