### ISSUE TITLE
[BUG] prepublish is not executing

### ISSUE THREAD

**Issue by sayem314** [npm/cli#3038]
### Current Behavior:

When publishing a module `prepublish` command are not fired.

### Expected Behavior:

Should fire successfully just like v6

### Environment:

- OS: PopOS 20.04
- Node: 14.16.0
- npm: 7.8.0

**Comment by ljharb** [comment]
Can you provide more info? What are the package.json scripts? What indicates it didn’t fire?

**Comment by sayem314** [comment]
@ljharb here are my scripts.

https://github.com/d-fi/d-fi-core/blob/759ad6220c6d80d4161dbd4dc8a265648e83c53e/package.json#L6-L12

It was supposed to call `eslint . && tsc` but it was totally ignored.

**Comment by ljharb** [comment]
Ignored meaning you didn’t see any output, or ignored meaning it would have failed but didn’t interrupt the publish?

**Comment by sayem314** [comment]
It didn't execute `eslint . && tsc` on `prepublish` but published the packaged anyway so I had to unpublish the version, bump it, manually run `eslint . && tsc` and then publish again. Note that I was on v6 publishing fine few days ago but yesterday updated to v7 and now today this issue occurs.

Edit: There was no output since it was not invoked at all.

**Comment by nlf** [comment]
this is deliberate. the `prepublish` script has been deprecated since it never really did what people expected.

see https://docs.npmjs.com/cli/v7/using-npm/scripts

> prepublish (DEPRECATED)
> 
> Does not run during npm publish, but does run during npm ci and npm install. See below for more info.

more likely, for your use case, `prepare` is the appropriate script

**Comment by ljharb** [comment]
@nlf wait, "deprecated" doesn't mean it shouldn't work at all. When did "prepublish" stop working intentionally in npm 7??

**Comment by nlf** [comment]
afaik we've never run it as part of `npm publish` in any npm 7 release

**Comment by sayem314** [comment]
It’s so sad to deprecate this feature. Doesn’t make any sense really since it literally mean prepublish. Also deprecated doesn’t mean removed. A deprecated feature should still run with a warning that it will be removed in future.

**Comment by ljharb** [comment]
@nlf wow, i did not realize that; all my packages use "prepublish" and i was under the impression that planned disabling was never actually going to happen and did not make the v7.0.0 cut anyways.

**Comment by nlf** [comment]
that's the problem, it never did literally mean prepublish. it ran as part of every install cycle, and it ran at the wrong times. in fact, in npm 6 if you publish a module with a `prepublish` script, it would print a warning informing you that `prepublish` has been deprecated since npm 5.

```
        prepublishWarning([
          'As of npm@5, `prepublish` scripts are deprecated.',
          'Use `prepare` for build steps and `prepublishOnly` for upload-only.',
          'See the deprecation note in `npm help scripts` for more information.'
        ])
```

**Comment by ljharb** [comment]
@nlf additionally, the original plan was to remove `prepublish` _entirely_, so that later, `prepublishOnly` could be migrated back to "prepublish", the proper name for `prepublishOnly`.

**Comment by ljharb** [comment]
(Historically, ftr, it did mean "only before publish"; it was expanded to the definition you're referring to to accommodate coffeescript users)

**Comment by sayem314** [comment]
I understand now. Thanks. I have never noticed that warning because I actually never scrolled up my terminal after publishing. Anyway now I have to keep this in mind when creating  or updating a project.

**Comment by nlf** [comment]
> @nlf additionally, the original plan was to remove `prepublish` _entirely_, so that later, `prepublishOnly` could be migrated back to "prepublish", the proper name for `prepublishOnly`.

that'd be ideal certainly, but us being able to safely migrate prepublishOnly back to prepublish is at least one more major away, along with a great deal of auditing of existing packages. i wouldn't hesitate to switch to `prepublishOnly` or `prepare` today, it's going to be quite a while before `prepublish` does the thing you'd expect.

**Comment by ljharb** [comment]
sadly this means i'll now have to call `npm run prepublishOnly` from inside `prepublish` to ensure that nobody accidentally runs `npm publish` in npm < 4 and thus skips the pre-publishing logic. it's fair that i've had since npm 4 to make this change, but i was pretty certain that it hadn't made the cut for npm 7 :-(

**Comment by nlf** [comment]
i do think it got left out of the blog post that detailed most of the breaking changes, to be completely fair. the scripts documentation i linked above was written based on what actually runs in the code today, rather than referring to the old and potentially incorrect docs. it's a very solid source of truth moving forward.
