### ISSUE TITLE
[BUG] it is possible to delete any existing token from registry.npmjs.org even if I am not the owner of the token

### ISSUE THREAD

**Issue by f4z3k4s** [npm/cli#3039]
### Current Behavior:
I can delete any token with running `npm logout`, even the ones that don't belong to my account. I think this is a serious security issue, but please explain if this is intentional.

### Expected Behavior:
`npm logout` does not delete any token that doesn't belong to my account and it only deletes tokens with `type: 'publish'` and no other types on logout

### Steps To Reproduce:
1. create a token with any npm account (let's say, we create a `read-only` token on npmjs.com)
2. create an `.npmrc` on any computer in any project and add the below content
```
// registry.npmjs.org/:_authToken=PUT_THE_PREVIOUSLY_GENERATED_TOKEN_HERE
```
3. run `npm logout` (you don't have to be logged-in with any account)

The token will be missing from the account that created it, even if it was never logged-in on that computer that initiated the logout request.

### Environment:

- OS: MacOS Big Sur 11.2.3 
- Node: 15.11.0 / 12.18.3
- npm: 7.6.0 / 6.14.6

**Comment by ljharb** [comment]
How would you get the token if it’s not your account?

**Comment by nlf** [comment]
possession of the token is what indicates whether you are logged in or not, so by passing a token you _are_ logged in as the owner of that token and running `npm logout` invalidates the token. there is no further state stored. this is working exactly as intended.
