### ISSUE TITLE
[BUG] `npm install` does not detect changes to `package.json` for private Git repositories

### ISSUE THREAD

**Issue by mmiretsky** [npm/cli#3045]
### Current Behavior:

It seems that in NPM 7.8.0, `npm install` does not detect changes to `package.json` for private Git repositories. In other words, if you change `package.json` to upgrade to a new version of a private NPM package hosted in a Git repo, then run `npm install`, it says "up to date" and does not install the new version.

We host our private repos in Bitbucket. Here is a sample `package.json`:

```
{
    "name": "some-application",
    "description": "Some Application",
    "dependencies": {
        "some-package": "git+ssh://bitbucket.org/some.company/some.package.git#1.0.5"
    }
}
```

### Expected Behavior:

When `package.json` is updated to use a new version of a private package, `npm install` should install the new version. This works correctly in NPM 6.x.

### Steps To Reproduce:

- Install an NPM package from a private Git repo (e.g. version 1.0.5, as in the example above)
- Commit a new version of the package to the package repo (e.g. 1.0.6)
- In the consuming application, update `package.json` to use the new version of the package
- Run `npm install`
- See erroneous "up to date" message, and note that the new version of the package is not installed

### Environment:

- OS: Windows 10
- Node: 14.6.1
- npm: 7.8.0

**Comment by mmiretsky** [comment]
Folks, any idea when someone might be able to take a look at this issue? Thanks!

**Comment by thexeos** [comment]
Removing the installed package from `./node_modules` and from `package-lock.json`, and then trying to install it again, it loads the correct version.

If I only update the entry in `package.json`, then `package-lock.json` has this (which makes no sense):

```
"some-package": {
  "version": "git+ssh://bitbucket.org/some.company/some.package.git#1.0.5",
  "from": "git+ssh://bitbucket.org/some.company/some.package.git#1.0.6"
}
```

Nevertheless, in both cases, npm **does** contact the Git server and it does fetch the list of commits/tags in the private repository.

This most certainly used to work "out-of-the-box" a few npm versions ago.

- OS: Windows 10
- Node: 14.16.0
- npm: 7.7.6

**Comment by thexeos** [comment]
I've had something unexpected happen: even after running the upgrade, as mentioned above, and with filesystem reflecting the changes, TypeScript compiler was throwing an error - it was continuing to use an old version of the dependency, even after the upgrade.

So be wary: it may, or it may not be an `npm` issue, if some third-party tool is not seeing the latest version of your private repository dependency.

**Comment by DanielPower** [comment]
We are also experiencing this on npm 7. It did not occur when we were previously using npm 6.

Known good versions: 6.14.8, 6.14.13
Known bad versions: 7.7.6, 7.11.2

# Prerequisites
1. A private package repo
2. A project that depends on the private package

# Reproduction steps
1. Clone two copies of your project
2. In copy A: install a new version of your private package using `install git+ssh://git@github.com:myorganization/mypackage.git#semver:1.0.1`
3. Note that npm will pull down the new code, and update `package.json` and `package-lock.json`
4. Push the new package and package-lock
5. In copy B: Pull down the new package and package-lock
6. In copy B: Run `npm install`. You'll receive the message `up to date`

Note that when the package was specifically installed in copy A, the new version was actually pulled down. Whereas in copy B, npm returned that the packages were already up to date, and did not install anything. Thus without any indication of failure, copy B is still using the old version of the package.

If needed, I can create a couple dummy repos to ease reproduction.

**Comment by darcyclarke** [comment]
@mmiretsky can you try on the latest version of `npm`? (ie. `npm i -g npm`) Also, is there a reason why you're manually editing your `package.json`? One workaround here, in the interim, would be to ensure you run `npm install git+ssh://bitbucket.org/some.company/some.package.git#1.0.6` which would replace the existing dep/spec & update your `package-lock.json` accordingly

**Comment by DanielPower** [comment]
I will test on the latest npm on Tuesday when I'm back to work.

To clarify, the reason the `package.json` is getting updated is because another user updates the package by running `npm install git+ssh://bitbucket.org/some.company/some.package.git#1.0.6`, and then pushing the new `package.json` and `package-lock.json` to the repository. It is not being updated manually.

Edit: Please see my previous message for another set of reproduction steps. It shows that manually updating `package.json` is not part of the bug.

**Comment by mmiretsky** [comment]
@darcyclarke - the problem still happens with the latest version of `npm` (7.14.0).

With regards to your question - see @DanielPower 's explanation above. It should not matter whether you edit `package.json` manually or pull down somebody else's changes - when you run `npm install`, it should pull down the new version of the package from Bitbucket, but it does not do that.

**Comment by jakubjosef** [comment]
Good news, this seems to be working for me on 7.16.0.

**Comment by mmiretsky** [comment]
Does not work for me either on 7.16.0 or 7.17.0. Still says "up to date" and does not pull down the newer version of the package from Bitbucket.

**Comment by jakubjosef** [comment]
@mmiretsky What format you are using? AFAIK it's important to use semver format when you working with git repos.

This is what we are using in package.json
```
"xxx-common": "gitlab:xxx/xxx-packages/xxx-common#semver:v0.0.2",
```

**Comment by mmiretsky** [comment]
Aha! Now it's working! Started working as soon as I added the `semver` keyword to the URL. It used to work without the `semver` keyword in NPM 6.x, but I guess they changed it in 7.x.

I encourage everyone watching this issue to try this out before we go ahead and close the issue.

**Comment by mmiretsky** [comment]
I am closing this issue since there is a resolution.
