### ISSUE TITLE
[BUG] NPM install private package not generate .bin symlink

### ISSUE THREAD

**Issue by jfreixa** [npm/cli#3047]
### Current Behavior:
When installing a package from a private registry in npm version 7.8.0 does not create a `node_modules/.bin` symlink to my package.
![NPM 7.8.0](https://user-images.githubusercontent.com/12124907/113975052-384f1300-983f-11eb-8ef7-9aded8da7d24.png)

### Expected Behavior:
In versions of NPM before 7.* `npm install` was creating the symlink to my package bin executable.
![NPM 6.14.12](https://user-images.githubusercontent.com/12124907/113975057-3a18d680-983f-11eb-83fc-cbd377ea10bc.png)

### Steps To Reproduce:

1. Environment:
npm: 7.*.*
2. Install a package from a private registry with a bin keyword.
Example installed package:
```
{
  "name": "@domestika/jfreixa",
  "version": "1.7.0",
  "description": "Commit and release manager",
  "main": "index.js",
  "bin": {
    "jfreixa": "bin/jfreixa.js"
  },
  "scripts": {},
  "author": "",
  "license": "MIT"
}
```
Example install package:
```
{
  "name": "testjfreixa",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@domestika/jfreixa": "^1.7.0"
  }
}
```
3. Search for the symlink in the `node_modules/.bin` folder
`ls -la node_modules/.bin`

### Environment:

- OS: macOS Big Sur 11.2.1
- Node: 15.13.0
- npm: 7.8.0

**Comment by ljharb** [comment]
What kind of private registry is it? It's possible that it's not returning the "bin" field in the packument, despite it being in the package.json.

**Comment by jfreixa** [comment]
Hello,
I am using the same private registry (GitLab registry for npm packages) for the 2 tests shown above. In the following image, you can see the package installed inside the node_modules with the folder bin.
![bin folder](https://user-images.githubusercontent.com/12124907/113977308-ad701780-9842-11eb-9738-a0790e1e08b1.png)

Can you explain to me how can I see the packument?

**Comment by nlf** [comment]
I suspect that the minified packuments that the cli requests are missing the bin field, which is necessary for us.

you can try something like

```
curl -H 'Authorization: Bearer $YOUR_AUTH_TOKEN' -H 'Accept: application/vnd.npm.install-v1+json' https://gitlab.domestika.org/api/v4/projects/35/packages/npm/@domestika%2fjfreixa
```

the result should have a `"bin"` field in each version, if it does not try the same command but leaving out the `Accept` header. if that one _does_ have the `"bin"` but it doesn't in the first request then it appears GitLab is returning incorrect data and an issue will have to be filed upstream.

**Comment by jfreixa** [comment]
Hello,

The 2 responses from the registry are not returning the `bin ` field. Also I am installing the same package and same version in different npm versions (6 works and 7 not works).
Had NPM changed the way of creating `.bin` folder between versions and NPM 7 needs the `bin` field in the response?

**With header:**
`curl -H 'Authorization: Bearer yXHT7pAAHoGRACTXtDYA' -H 'Accept: application/vnd.npm.install-v1+json' https://gitlab.domestika.org/api/v4/projects/35/packages/npm/@domestika%2fjfreixa`
```json
{
  "name": "@domestika/jfreixa",
  "versions": {
    "1.7.3": {
      "name": "@domestika/jfreixa",
      "version": "1.7.3",
      "dist": {
        "shasum": "a2f3c020b7c05c3c4d4295aae45c4761dc6432d7",
        "tarball": "https://gitlab.domestika.org/api/v4/projects/35/packages/npm/@domestika/jfreixa/-/@domestika/jfreixa-1.7.3.tgz"
      }
    }
  },
  "dist-tags": {
    "latest": "1.7.3"
  }
}
```

**Without header:**
`curl -H 'Authorization: Bearer yXHT7pAAHoGRACTXtDYA' https://gitlab.domestika.org/api/v4/projects/35/packages/npm/@domestika%2fjfreixa`
```json
{
  "name": "@domestika/jfreixa",
  "versions": {
    "1.7.3": {
      "name": "@domestika/jfreixa",
      "version": "1.7.3",
      "dist": {
        "shasum": "a2f3c020b7c05c3c4d4295aae45c4761dc6432d7",
        "tarball": "https://gitlab.domestika.org/api/v4/projects/35/packages/npm/@domestika/jfreixa/-/@domestika/jfreixa-1.7.3.tgz"
      }
    }
  },
  "dist-tags": {
    "latest": "1.7.3"
  }
}
```

**Comment by ghost** [comment]
Hello,

This problem comes from gitlab. 
See this issue for more information:
https://gitlab.com/gitlab-org/gitlab/-/issues/275992

**Comment by jfreixa** [comment]
I didn't find it before. Thank you so much for your time.
