### ISSUE TITLE
[BUG] `npm install` does not install actual version of dependency from package.json leaving outdated one there

### ISSUE THREAD

**Issue by noneedinmagic** [npm/cli#3057]
### Current Behavior:

I have an exact dependency in my package.json:

```
  "dependencies": {
    // ...
    "validator": "13.5.2",
    // ...
  },
```

But inside node_modules there is a 13.0.0 version beacause previously it was a subdependency of another dependency.
This is a prod environment which is set up via CI/CD, so usually I do not install and update dependencies there manually, they are changed only via `npm install` after fetching new changes from the origin repo.

So even when I run `npm install` manually, the real version of the dependency remains as 13.0.0 which is wrong behavior.
It SHOULD upgrade dependency to 13.5.2.

### Expected Behavior:

Updating installed dependency from 13.0.0 to 13.5.2

### Steps To Reproduce:

1. Make sure you have 13.0.0 installed in your node_modules.
2. Change the version of dependency in package.json to exact one, more recent.
3. Run `npm install`.
4. ???????
5. Get screwed with unexpected errors because of outdated dependencies on prod :(

### Environment:

- OS: CentOS Linux release 8.2.2004 (Core)
- Node: 14.15.0
- npm: 7.7.5 and 7.9.0

**Comment by isaacs** [comment]
I can't seem to reproduce this, either as a direct dep or a transitive dep.  Can you share more about what else is in your package.json before and after editing it manually?

Are you checking in your package-lock.json?  Anything in node_modules checked in?

**Comment by noneedinmagic** [comment]
My package.json:

```json
{
  "name": "%here-goes-the-real-name%",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "build:analysis": "vue-cli-service build --mode analysis",
    "build:dev": "vue-cli-service build --mode development",
    "build:prod": "vue-cli-service build --mode production",
    "format": "prettier --write \"src/**/*.{ts,vue}\"",
    "watch": "vue-cli-service build --watch"
  },
  "dependencies": {
    "@vue/composition-api": "1.0.0-beta.19",
    "axios": "0.21.1",
    "class-transformer": "0.3.1",
    "core-js": "3.6.5",
    "i18n-iso-countries": "6.5.0",
    "moment": "2.29.1",
    "validator": "13.5.2",
    "vue": "2.6.12",
    "vue-router": "3.4.7",
    "vuetify": "2.3.23",
    "vuex": "3.5.1"
  },
  "devDependencies": {
    "@types/validator": "13.1.3",
    "@typescript-eslint/eslint-plugin": "2.34.0",
    "@typescript-eslint/parser": "2.34.0",
    "@vue/cli-plugin-babel": "4.5.8",
    "@vue/cli-plugin-eslint": "4.5.8",
    "@vue/cli-plugin-router": "4.5.8",
    "@vue/cli-plugin-typescript": "4.5.8",
    "@vue/cli-plugin-vuex": "4.5.8",
    "@vue/cli-service": "4.5.8",
    "@vue/eslint-config-prettier": "6.0.0",
    "@vue/eslint-config-typescript": "5.1.0",
    "eslint": "6.8.0",
    "eslint-plugin-prettier": "3.1.4",
    "eslint-plugin-vue": "6.2.2",
    "lint-staged": "9.5.0",
    "moment-locales-webpack-plugin": "1.2.0",
    "prettier": "1.19.1",
    "raw-loader": "4.0.2",
    "sass": "1.27.0",
    "sass-loader": "8.0.2",
    "typescript": "3.9.7",
    "vue-cli-plugin-vuetify": "2.0.7",
    "vue-template-compiler": "2.6.12",
    "vuetify-loader": "1.6.0"
  },
  "gitHooks": {
    "pre-commit": "lint-staged"
  },
  "lint-staged": {
    "*.{js,jsx,vue,ts,tsx}": [
      "vue-cli-service lint",
      "git add"
    ]
  }
}
```

package-lock.json is added to git, so I have it on the server too.

I might try to reproduce it again and share the steps, but later (it is night in my timezone now + I am ill now and have temporarily reduced productivity).

Also it might be worth noting that by now I reinstalled needed packages on the server by removing the whole /node_modules/ directory and installing it from scratch.

**Comment by Heatmanofurioso** [comment]
This issue also seems to happen with angular dependencies a lot.
Updating the dependency version in the package.json and performing npm install doesn't always actually update the dependency inside the node_modules

**Comment by noneedinmagic** [comment]
Just tried to reproduce it with a new test repo on my local Windows machine and everything worked fine.
Clearly, there are some additional conditions, but now it is hard to identify them.

**Comment by Heatmanofurioso** [comment]
It doesn't happen all the time with all dependencies on me too.
I'm going to try and identify and investigate this too, but I've seen a lot of people complaining about this issue since migrating to npm 7

**Comment by vgarba3** [comment]
#3071 I filed this issue as well with an example project to test - does this seem like the same problem you're experiencing ? @noneedinmagic

**Comment by noneedinmagic** [comment]
@vgarba3 actually I am not sure if those are connected, but mine is root dependency, not a nested dependency

but I had the same problem that your issue mentions too, especially annoying when one of the dependencies has vulnerable subdependencies, and `npm audit fix` does not fix the issue, and installing subdependency as root dependency does not fix vulnerable subdependency

Although by this question you made me realize that in my case this problematic dependency was a subdependency before, but after some time redundant dependant was uninstalled from the project and its needed dependency was installed as root dependency of the project, and it had the problem mentioned by this issue later

Will try to check some more examples later when will have some more time

**Comment by ruluva** [comment]
Ran into something similar trying to update a react-scripts in one of our packages. Was trying to fix the immer vulnerability, in one of our packages with react-scripts@3.4.4. Did an update to react-scripts@4.0.3, and ran an install. I was in a weird in between state, where the node_modules seemed to reflect the change (at least partially), but npm and the package-lock did not.

Tried running `npm ls immer` and got:
```
├─┬ @NAMESPACE/SUB_PACKAGE_1@1.0.0 -> /Users/ruluva/development/ROOT_PACKAGE/packages/experiences/SUB_PACKAGE_1
│ └─┬ @reduxjs/toolkit@1.5.1
│   └── immer@8.0.4
├─┬ @storybook/react@6.2.2
│ └─┬ react-dev-utils@11.0.4
│   └── immer@8.0.1
└─┬ SUB_PACKAGE_2@0.4.0 -> /Users/ruluva/development/ROOT_PACKAGE/packages/experiences/SUB_PACKAGE_2
  └─┬ react-scripts@3.4.4 invalid
    └─┬ react-dev-utils@10.2.1
      └── immer@1.10.0
```

Also ran `npm ls react-scripts` and got:

```
root@ /Users/ruluva/development/ROOT_PACKAGE
├─┬ @storybook/preset-create-react-app@2.1.2
│ └── react-scripts@4.0.3
└─┬ SUB_PACKAGE_2@0.4.0 -> /Users/ruluva/development/ROOT_PACKAGE/packages/experiences/SUB_PACKAGE_2
  ├─┬ react-app-rewired@2.1.8
  │ └── react-scripts@4.0.3 deduped
  └── react-scripts@3.4.4 invalid
```

The package-lock also had references to the old package. I had to remove the react-scripts package from the sub package, do an install (in order to reflect a removal), then add it back for it to update correctly.

OS: Mac OS X 11.2.3
Node: 14.15.4
NPM: 7.9.0 and 7.10.0

**Comment by Heatmanofurioso** [comment]
Seems to be a duplicate of https://github.com/npm/cli/issues/3152
Which just got closed

**Comment by darcyclarke** [comment]
@noneedinmagic this should get fixed in the next release (ie. `7.15.1`) - will leave open for now until I can confirm this has gone out
