### ISSUE TITLE
NPM login fails if missing trailing /

### ISSUE THREAD

**Issue by mike247** [npm/cli#3066]
### Current Behavior:
When running npm login for a private artifactory store or another private repo store, if the command is missing a trailing / it fails with a generic and unhelpful warning

```
npm login --registry:https://myregistry.co/npm/repo
```

compared with

```
npm login --registry:https://myregistry.co/npm/repo/
```

In the first instance, the login works successfully but subsequent installs will error out on this message 
```
 Unable to authenticate, need: Basic realm=
```

In the second instance the login works and the install works

### Expected Behavior:
I would expect both paths to work as they are both URLs that point to the same resource
Or in any case I would expect the login to error out if it knows it needs a trailing / to work

### Steps To Reproduce:
1 ) Attempt to login to a private registry without the trailing /
2) run npm install

### Environment:
- OS: MacOS 10.15.4
- Node: 15.3.0
- npm: 7.6.3 and 6.14.13

**Comment by nlf** [comment]
can you share some logs from the failing run? this may be an issue with how your registry itself works, but i need more information

**Comment by darcyclarke** [comment]
@mike247 we believe this should be fixed based on some of the changes we've made to auth/registry matching - please open a new issue if you continue to experience issues post `v7.15.0` (ex. stay up to date & grab latest via `npm i -g npm`)
