### ISSUE TITLE
[npm ERR! cb() never called!] <npx create-react-app >

### ISSUE THREAD

**Issue by mathase** [npm/cli#3073]
### Current Behavior:

I get an error when I create a new react app. console returns an "npm ERR! cb() never called!"
### Expected Behavior:

I expected it to generate a react app template.
### Steps To Reproduce:

C:\Users\murther\New folder>npx create-react-app bts

Creating a new React app in C:\Users\murther\New folder\bts.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\murther\AppData\Local\npm-cache\_logs\2021-04-14T10_54_15_787Z-debug.log

Aborting installation.
  npm install --save --save-exact --loglevel error react react-dom react-scripts cra-template has failed.

Deleting generated file... package.json
Deleting bts/ from C:\Users\murther\New folder
Done.

C:\Users\murther\New folder>node -v
v14.16.1

C:\Users\murther\New folder>npm -v
7.9.0
### Environment:

[2021-04-14T10_54_15_787Z-debug.log](https://github.com/npm/cli/files/6310433/2021-04-14T10_54_15_787Z-debug.log)

OS: Windows 8 pro x64
Node: v14.16.1
npm: 7.9.0

**Comment by snipher-marube** [comment]
me too am experiencing the same problem

**Comment by wendimust** [comment]
Same here

**Comment by Ali-GreenHeart** [comment]
same here ))

**Comment by mathase** [comment]
update node to v15.14.0
npm v7.10.0

cleared the error for me

**Comment by darcyclarke** [comment]
Try updating to latest npm - `npm i -g npm` &/or check out this document:
https://github.com/npm/cli/wiki/%22cb()-never-called%3F--I'm-having-the-same-problem!%22

Closing for now, if you can create a consistent reproduction case, please post back & we'll consider reopening.
