### ISSUE TITLE
[BUG] npm doesn't read config from /etc/npmrc

### ISSUE THREAD

**Issue by duongdominhchau** [npm/cli#3074]
Instead, it reads config from `/usr/etc/npmrc`. This is correct docs-wise, but is unconventional on Linux. The convention is when install prefix is `/usr`, the directory `/etc` is used to store configuration (without the prefix).

### Current Behavior:
`npm` reads system-wide config from `/usr/etc/npmrc`

### Expected Behavior:
`npm` reads system-wide config from `/etc/npmrc`

### Environment:
- OS: Arch
- Node: 15.14.0
- npm: 7.9.0

**Comment by ljharb** [comment]
What is your use case for system-wide configuration at all?

**Comment by duongdominhchau** [comment]
I use that to change the directories to follow XDG for all users (workaround because #654 is still open).

**Comment by darcyclarke** [comment]
This isn't a bug - https://docs.npmjs.com/cli/v7/using-npm/config#globalconfig If you'd like us to consider this, definitely propose it over on our [npm/rfcs](https://github.com/npm/rfcs) repo
