### ISSUE TITLE
[BUG] Package.json Vars $npm_config_{key} $npm_package_ are not in scope of the package.json scripts

### ISSUE THREAD

**Issue by redevill** [npm/cli#3077]
### Current Behavior:

A configuration parameter (can be seen with - npm config list) could be set using a command line parameter to a package.json script
e.g. npm run build -- prod where    "build": "npm config set environ"
now $npm_config_environ should be in scope for ALL package.json scripts:
e.g. "postbuild": "echo $npm_config_environ && npm run NodeSubscript && etc" **NO VALUE FROM ECHO**
and "NodeSubscript": "node ScriptUsingVariable.js $npm_config_environ" **NO VALUE PASSED**

### Expected Behavior:

I am expecting the config parameter to be available, and to be passed to my javascript
Further, I would expect the process.env.npm_config_environ to exist with the given value.

Per the V7 Docs (https://docs.npmjs.com/cli/v7/configuring-npm/package-json) config section:
In the event a package level variable is configured, it should be overridable. 
{
  "name": "myApp",
  "config": {
    "environ": "dev"
  }
}

I would also expect it would be possible to override a default npm_package_config_environ (in this case dev)
to the given value above of prod. Using a command npm config set myApp:environ

### Steps To Reproduce:
As explained above.

### Environment:
Mac OS 10.15.6
NPM V7.9.0
node V12.16.1

**Comment by maxrandolph** [comment]
Upgrading to npm 7 seemed to no longer support all `$npm_package_x` values from env vars. This is a breaking change to some npm scripts which depend on reading values from `package.json` when upgrading to npm 7.

**Comment by JakobJingleheimer** [comment]
Also occurs with:

macOS `11.3.1`
node `16.1.0`
npm `7.11.2` & `7.14.0`

**Comment by darcyclarke** [comment]
This is not a bug (ref. see this RFC https://github.com/npm/rfcs/blob/latest/implemented/0021-reduce-lifecycle-script-environment.md); If you'd like to recommend changes feel free to create a new RFC thread although these vars were intentionally removed

**Comment by JakobJingleheimer** [comment]
@darcyclarke If it's not a bug then the v7 documentation is wrong: it explicitly says this should work as the OP described.

**Comment by redevill** [comment]
Thank you Jakob. 
I have read and understand some of the motivation behind the removal, In the document Darcy references. My suspicion, is that it falls short. With the removal of the script context variables, how then, is state to be shared between preMyScript, MyScript and postMyScript? ... if state is not to be shared - then the "pre" (an implied state by the very word) and post functionality should also go away. 

With my use case: the intent is to have re-usable scripts, where a parameter is passed from the command line in a consistent fashion, to all the invoked children. (pre post inline scripts)

Without the ability of a script to take parameters, it seems we will all have to go back to Gulp et al.

**Comment by JakobJingleheimer** [comment]
@redevill Hmm, I think state should probably not be managed via environment variables—they're more like environment constants: their value should not change during runtime—you can get yourself into quite a bit of trouble if you do.

---

@darcyclarke here is where the documentation explicitly says this should work:

[Using NPM › Scripts › Special package.json config object](https://docs.npmjs.com/cli/v7/using-npm/scripts#special-packagejson-config-object)

> The package.json "config" keys are overwritten in the environment if there is a config param of `<name>[@<version>]:<key>`. For example, if the package.json has this:
>
>```json
> {
>   "name" : "foo",
>   "config" : {
>     "port" : "8080"
>   },
>   "scripts" : {
>     "start" : "node server.js"
>   }
> }
> ```
>
> and the server.js is this:
>
> ```js
> http.createServer(...).listen(process.env.npm_package_config_port)
> ```
>
> then the user could change the behavior by doing:
>
> ```js
> npm config set foo:port 80
> ```

This does not work: The value of `process.env.npm_package_config_port` in `server.js` is `'8080'` instead of `'80'`.

**Comment by redevill** [comment]
@JakobJingleheimer  - Perhaps state was the wrong word. From the point of view that you can set or choose the value of a variable, that is handed to a script... this for me is a "Starting State". I was expecting, that this chosen value (state) would remain in scope for all of the preScript mainScript and postScript portions. However, this chosen value, as you suggest (environment constant) could be immutable for a particular running instance.

Yes - we can set environment constants to provide the run context(better description than "state") described above, but this is no where near as convenient or intuitive as passing the needed value to the script. npm run myBulidScript -- dev

This argument (pun intended) gives me an idea... Will try to set an environment variable in the pre script, to the passed in value.

**Comment by javatask** [comment]
Dear developers can you point me to alternatives of using $npm_config_{key} in the package.json in order parameterized scripts sections.
More details here
https://stackoverflow.com/questions/68511389/paramatrization-of-npm-package-json-scripts

**Comment by redevill** [comment]
**### OPTION 1:** 
Don't use the Npm environment, use it only as a stepping stone to JavaScript. Pass any parameters you need through Npm to your Javascript.

**_e.g._**
_In your package.json scripts section:_
```
 "scripts": {
    "build": "cross-var node env/build.js"
 }
```

build script defined to run javascript under node - optional use of the cross-var package to help it work on windows
(https://www.npmjs.com/package/cross-var)

_To invoke on the command line:_
`npm run build -- <YourFirstArgHere>`

_To access in your javascript:_
`let firstParm = process.argv[2]`

**### OPTION 2:**
Use standard environment variables to capture "Start state" mentioned above (Jun21).

(NOTE: I have not tried this technique, and am not sure if the environment variable value will persist between preScript - Script and postScript npm executions - assuming folks know about this: https://docs.npmjs.com/cli/v7/using-npm/scripts/)

_Details on Setting these environment variables here:_
https://stackoverflow.com/questions/25112510/how-to-set-environment-variables-from-within-package-json

_Of particular interest is comment 14:_

> if you want to use the env var inside the script itself you need to prepend $, for example if you run mode=prod npm run print and you have a script in your package.json called print "print": "echo environment '$mode'" it will print environment 'prod' – Jonathan Morales Vélez

**Comment by javatask** [comment]
@redevill thank you for your ideas. 
I found this that best fits my case
Change
```
"package": "sam package --profile $npm_config_awsProfile --template-file template.yaml --s3-bucket $npm_config_s3BucketName --output-template-file template-out.yaml",
```
to
```
"package": "sam package --profile $(grep awsProfile .npmrc | cut -d '=' -f2) --template-file template.yaml --s3-bucket $(grep s3BucketName .npmrc | cut -d '=' -f2) --output-template-file template-out.yaml",
```

The main draw back is that you need to drop `"` in your values

**Comment by redevill** [comment]
Did not think of "Grepping" in the context of npm script - Cool.

**Comment by loganpowell** [comment]
I had issues using the `$npm_config_<var>` syntax. I believe part of the matter was that I am on Windows.

After some face-slapping, I figured out that you have to use `%npm_config_<var>%` and when using the CLI, you must capitalize `<VAR>`, so, e.g.:

package.json:
```
"demo": "cross-env echo 'Hello %npm_config_msg%!'"
```
CLI:
```
npm run demo --MSG=Dr-Pepper
```
