### ISSUE TITLE
Getting error while installing Angular

### ISSUE THREAD

**Issue by rakeshims36** [npm/cli#3082]
npm ERR! cb() never called!
<img width="743" alt="MMIssue" src="https://user-images.githubusercontent.com/41721796/114861439-e55ef800-9e0a-11eb-9693-1c5ec8545b85.PNG">

**Comment by rakeshims36** [comment]
I have cleared the cache as well but still i am getting installation issue.

**Comment by nlf** [comment]
see #417 regarding cb() never called errors.

if you continue to experience problems, please open a new issue and be sure to fill out our issue template to the best of your ability.
