### ISSUE TITLE
[BUG] Update notice has black background even on white terminals

### ISSUE THREAD

**Issue by fregante** [npm/cli#3091]
Self-explanatory 👇 
<img width="500" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/114978483-71c4f580-9eb3-11eb-8d00-20a2a49a553a.png">

My terminal theme has a white background (macOS default) but npm unnecessarily shows the update notice with a black color.

### Environment:

- OS: macOS 11.2.3
- Node: 15.12.0
- npm: 7.6.3
- Fish Shell 3.2.1

I don't know if this has already been addressed since it will only appear when I'm not running the latest version.

**Comment by nickfryar** [comment]
The background for the update notifier is being set here: https://github.com/npm/cli/blob/a4e7f4e4b40d645fed97622a97c7fa72aa5da82b/lib/utils/update-notifier.js#L112

And per https://github.com/chalk/chalk/issues/102 it appears there's no way to detect background color in the terminal.

**Comment by fregante** [comment]
I think the point is to _not_ use `bgBlack` nor `white` at all. They should just be the default color as defined by the terminal. It makes no sense to set a black background on a black terminal in the first place. Same goes for a white text on a black terminal.

**Comment by nickfryar** [comment]
Does this extend to all cases of `bgBlack`? I found 8 instances of this with various colors in the cli. If it's just a case of removing `bgBlack` / `bgBlack + white`, I can open a PR for this. I'm still new to this repo though, so some direction on this would be appreciated!

**Comment by fregante** [comment]
It appears that in most cases it's trying to highlight a line. I think the correct solution for that is to use the `inverse` function instead, but I'm not familiar with either project to tell you for sure.

**Comment by nickfryar** [comment]
[Chalk](https://www.npmjs.com/package/chalk) supports `inverse`, but [ansicolors](https://www.npmjs.com/package/ansicolors) does not. All but one case of `bgBlack` use chalk, so that one exception can likely just be switched from ansicolors to chalk.

However, [npmlog](https://github.com/npm/npmlog) handles the highlighting differently, so the `npm notice` text in your screenshot above would still appear with a black background. What is the typical process for making changes in dependencies for the cli, such as this?

**Comment by wraithgar** [comment]
this is now half fixed as of `v7.20.0`.

`npmlog` itself having forced black backgrounds for certain levels is going to be a separate fix.

**Comment by lukekarrys** [comment]
This was fixed by 9216d5985fb3e2a2754be5bf0b1d43fc321cf723 and included in `npm@10.7.0`.
