### ISSUE TITLE
Error with npm itself! cb() never called!

### ISSUE THREAD

**Issue by prachitigholap** [npm/cli#3093]
It gives error when tried to run npm install @material-ui/core

![image](https://user-images.githubusercontent.com/61944007/115041046-b8384580-9eef-11eb-932f-cad36119857d.png)

**Comment by ljharb** [comment]
#417

**Comment by nlf** [comment]
see the linked issue above, and if you continue to have difficulties please open a new issue and be sure to fill out our issue template to the best of your ability.
