### ISSUE TITLE
Unable to install: npm ERR! Unexpected end of JSON input while parsing near

### ISSUE THREAD

**Issue by parthsw** [npm/cli#3094]
I am trying to install packages of my angular application using **npm i**, however, it always fails with **npm ERR! Unexpected end of JSON input while parsing near....**

### Environment:
```
node -v
v10.13.0

npm -v
6.4.1
```

### Approaches tried:

1. Tried reinstalling it after deleting the **node_modules** and **package-lock.json**
2. Cleared the cache using `npm cache clean --force`

**Comment by darcyclarke** [comment]
@parthsw need replication steps to be able to triage this properly - if you can provide a reproducible example, I can try to help resolve this; Closing for now.
