### ISSUE TITLE
npm ERR! cb() never called![BUG] 

### ISSUE THREAD

**Issue by keshaviagg** [npm/cli#3097]
### Current Behavior:
on running npx create-react-app or npm I'm seeing this error

### Expected Behavior:
a new app shud be created or dependencies should be installed.

**Comment by ljharb** [comment]
#417

**Comment by keshaviagg** [comment]
> #417

the solution provided is not working.
I tried clearing cache and updating npm version but nothing changed still getting same error

**Comment by ljharb** [comment]
Could you fill out the entire issue template then?

**Comment by keshaviagg** [comment]
> Could you fill out the entire issue template then?

Current Behavior:
on running npx create-react-app or npm I'm seeing this error

Expected Behavior:
a new app shud be created or dependencies should be installed.

Steps To Reproduce:
Environment: run command npx create-react-app my-app or npm i

Environment: npm : v7.7.0
node v14.16.1
OS : ubuntu v18.x

**Comment by zizopixels** [comment]
Same issue is with me ( npm ERR! cb() never called )
Googled everything but nothing is working for me.

**Comment by nlf** [comment]
try updating to the latest release with `npm i -g npm` and see if that helps, i'm not able to reproduce this

**Comment by keshaviagg** [comment]
Still the same issue

**Comment by nlf** [comment]
are you running from an empty directory? can you share the output of `npm config ls`?

**Comment by FarooqueAhmeed** [comment]
In my case, I installed the latest versions of the node and npm

**Comment by darcyclarke** [comment]
Closing: Not enough information to reproduce unfortunately - see: https://github.com/npm/cli/wiki/"cb()-never-called%3F--I'm-having-the-same-problem!"
