### ISSUE TITLE
npm ci does not run prepare script for Git modules (version 6.11.*)

### ISSUE THREAD

**Issue by darcyclarke** [npm/cli#310]
Original bug ticket: [https://npm.community/t/10076](https://npm.community/t/10076)
      Originally filed: 2019-09-16T18:40:45.299Z

**Comment by daneah** [comment]
Confirming this is still an issue in 6.12.0 as well.

**Comment by jjhbw** [comment]
I have the exact same issue when using the `node:12.13.0` Docker container (in CI), which runs 6.12.0. Same issue even after updating its `npm` version to `6.14.3` before running `npm ci`.

However, somehow, `npm ci` in `6.14.3` behaves as intended on my development machine (a mac)

**Comment by funkydev** [comment]
I have the same issue when using the `node:12.13.0` on the docker container (in gitlab-runner CI) on both commands: `npm install` and `npm ci`.

I noticed that npm ignores files from `.gitignore` when there is no `.npmignore` file.
Creating an empty `.npmignore` file helps to solve problems locally (on a macOS system).

The strangest thing is that when I remove the `node_modules` directory and run the following command locally, it works.
```bash
$ docker run --rm --name node-test -v "$PWD":/usr/src/app -w /usr/src/app node:12.13.0 \
             sh -c 'npm cache clean --force && npm ci'
```

I have problems only when trying to run the following command on the CI runner (that uses `node:12.13.0` docker image).
