### ISSUE TITLE
[BUG] npm install failed with node-pre-gyp ERR! stack Error

### ISSUE THREAD

**Issue by santoshp321** [npm/cli#3102]
### Current Behavior:

I was trying to run the Angular application from my Github [repo](https://github.com/santoshpavan/fitness-tracker).

When I ran `npm install` on the repo, I keep coming across errors. I tried uninstalling the angular cli and Node (separately), and tried to run it after reinstallation. It has not worked.

The complete log of the error is attached here.
[2021-04-19T17_34_17_309Z-debug_npm7.log](https://github.com/npm/cli/files/6338072/2021-04-19T17_34_17_309Z-debug_npm7.log)

### Expected Behavior:

The expected behavior is that the `npm install` runs without and installed properly.

### Steps To Reproduce:

The following are the steps-

1. In the environment given below, clone this [repo](https://github.com/santoshpavan/fitness-tracker).
2. Run the `npm install`.

### Environment:

The environment is-

- OS: Windows 10
- Node: 14:16.1
- npm: 7.10.0

*Please note that I have tried this with `npm 6.14.12` as well but it threw an error as well. Here is the attached log.*
[2021-04-19T13_56_45_923Z-debug_npm6.log](https://github.com/npm/cli/files/6338071/2021-04-19T13_56_45_923Z-debug_npm6.log)

**Comment by wraithgar** [comment]
This looks like it is an issue between node-gyp and grpc, possibly related to something like this issue: https://github.com/nodejs/node-gyp/issues/2114

This is not an npm bug.
