### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by hitendra-sahu** [npm/cli#3104]
I am having angular version 11.2.9 but I want to downgrade angular version to 11.2.3. 
For this, I run command npm install -g @angular/cli@11.2.3, but I got below error 
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\UserName\AppData\Local\npm-cache\_logs\2021-04-20T07_39_43_649Z-debug.log

I am attaching log file also.
[log file.txt](https://github.com/npm/cli/files/6341711/log.file.txt)

**Comment by sudhirdhumal289** [comment]
I just wanted to start with Angular tutorial today so freshly installed angular cli which went very well but when tried to create new project I even got the same error.

**last few lines printed on terminal**
⠏ Installing packages (npm)...npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sudhir/.npm/_logs/2021-04-20T12_24_22_860Z-debug.log
✖ Package install failed, see above.


**Environment Details:**
npm -v ------> 7.6.3
node -v -----> v14.15.5
OS -----------> Debian 10 (Buster)
Terminal ----> GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)

Attached LOG File
[2021-04-20T12_24_22_860Z-debug.log](https://github.com/npm/cli/files/6343479/2021-04-20T12_24_22_860Z-debug.log)

**Comment by sudhirdhumal289** [comment]
Update:
Updating npm to 7.10.0 (latest) resolved the issue and now able to create a new angular project successfully.

**Comment by ljharb** [comment]
#417

**Comment by shahzaib-cmyk** [comment]
I have the same issue while installing webpack or parser.I tries almost all the other methods like cleaning the cache and updating npm but nothing seems to work.
