### ISSUE TITLE
Button URL link fails with certain names

### ISSUE THREAD

**Issue by nigelwright7557** [npm/cli#3106]
If i have a button with a url on it some ulr names fail to work.
/checkout will fail and just goes to / url
Yet /checkout43 will work ok
Node js program about 4000 lines.
Didnt see the problem until the program got over 3000 lines
Stack problem ? heap problem ?

**Comment by nigelwright7557** [comment]
[nodejs.zip](https://github.com/npm/cli/files/6343947/nodejs.zip)
Source project in Visual Studio

**Comment by ljharb** [comment]
This doesn't seem like it's a problem with the npm CLI itself.
