### ISSUE TITLE
[BUG] Spawned subshell with npm explore has wrong current working directory

### ISSUE THREAD

**Issue by i-C-o-d-e-r** [npm/cli#3107]
### Current Behavior:
When using `npm explore` to spawn a subshell in the installed directory of a package, the current working directory of the spawned subshell is wrong. It seems to not change (tested on windows only with default shell cmd.exe).

If I run `npm explore ansi-colors` from the command line in the parent directory of `node_modules`, where` package.json` is located, then the spawned subshell has the expected current working directory `node_modules/ansi_colors`.

However, if I run the same command from within a script in `package.json`, then the current working directory is wrong.

### Expected Behavior:
`npm explore ansi-colors -- echo %CD%`

when called from within a script in `package.json` should return

`node_modules/ansi-colors`

### Steps To Reproduce:
Use the example from above.

### Environment:
NodeJS 14.16.1
npm 7.10
Windows 10

**Comment by darcyclarke** [comment]
@hubbergit can you try replicating this problem on the latest version of `npm`? (ie. `npm i -g npm`)

**Comment by i-C-o-d-e-r** [comment]
I am still able to replicate the problem as described above using npm 7.16.0.

However I tried to run a program within `node_modules/ansi-colors` like this

`npm explore ansi-colors -- myexecutable`

from within a script in `package.json` and it works. So the path to `myexecutable` seems to be resolved correctly.

But why is `echo %CD%` showing me the wrong current working directory?

**Comment by i-C-o-d-e-r** [comment]
I am closing this issue, because it seems to be related to the way cmd.exe works and does not seem to be a bug of the npm cli.
