### ISSUE TITLE
[BUG] <title>npm WARN EBADENGINE Unsupported engine

### ISSUE THREAD

**Issue by kul1010** [npm/cli#3114]
npm i
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'react-lottie@1.2.3',
npm WARN EBADENGINE   required: { npm: '^3.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.16.0', npm: '7.6.1' }
npm WARN EBADENGINE }
npm ERR! cb() never called!

npm ERR! This is an error with npm itself.

**Comment by wraithgar** [comment]
Please use the issue template when making issues
