### ISSUE TITLE
enable to install create-react-app

### ISSUE THREAD

**Issue by prabhu1122** [npm/cli#3122]
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\prabh\AppData\Local\npm-cache\_logs\2021-04-22T14_45_04_041Z-debug.log

Aborting installation.
  npm install --save --save-exact --loglevel error react react-dom react-scripts cra-template has failed.

Deleting generated file... node_modules
Deleting generated file... package.json
Deleting my_app/ from C:\Windows\system32
Done.

**Comment by wraithgar** [comment]
Please follow the issue template when creating issues
