### ISSUE TITLE
[BUG] NPM not install jspdf and filesaver successfully

### ISSUE THREAD

**Issue by AmidouSeck** [npm/cli#3124]
+ npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm WARN checkPermissions Missing write access to /opt/atlassian/pipelines/agent/build/node_modules/jspdf/node_modules/file-saver
npm WARN @angular/animations@7.2.15 requires a peer of @angular/core@7.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/compiler-cli@7.2.4 requires a peer of @angular/compiler@7.2.4 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/compiler-cli@7.2.4 requires a peer of typescript@>=3.1.1 <3.3 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/http@2.3.0 requires a peer of rxjs@5.0.0-rc.4 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/http@2.3.0 requires a peer of @angular/core@2.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/http@2.3.0 requires a peer of @angular/platform-browser@2.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/register@7.7.4 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN @nebular/date-fns@7.0.0 requires a peer of date-fns@2 but none is installed. You must install peer dependencies yourself.
npm WARN @nebular/theme@7.0.0 requires a peer of @angular/animations@^11.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nebular/theme@7.0.0 requires a peer of @angular/common@^11.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nebular/theme@7.0.0 requires a peer of @angular/core@^11.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nebular/theme@7.0.0 requires a peer of @angular/router@^11.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nebular/theme@7.0.0 requires a peer of @angular/cdk@^11.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nebular/theme@7.0.0 requires a peer of rxjs@^6.5.4 but none is installed. You must install peer dependencies yourself.
npm WARN @nebular/theme@7.0.0 requires a peer of tslib@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-bootstrap/ng-bootstrap@4.0.1 requires a peer of @angular/common@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-bootstrap/ng-bootstrap@4.0.1 requires a peer of @angular/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-bootstrap/ng-bootstrap@4.0.1 requires a peer of @angular/forms@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.4.1 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN angular-fusioncharts@3.0.3 requires a peer of @angular/core@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-fusioncharts@3.0.3 requires a peer of rxjs@^5.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN angular-progress-http@1.0.0 requires a peer of @angular/core@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-progress-http@1.0.0 requires a peer of @angular/http@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-progress-http@1.0.0 requires a peer of rxjs@^5.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN angular-star-rating@4.0.0-beta.3 requires a peer of @angular/core@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-star-rating@4.0.0-beta.3 requires a peer of @angular/forms@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-star-rating@4.0.0-beta.3 requires a peer of rxjs@^5.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-star-rating@4.0.0-beta.3 requires a peer of css-star-rating@^1.2.4 but none is installed. You must install peer dependencies yourself.
npm WARN igniteui-angular@7.3.21 requires a peer of @angular/common@^7.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN igniteui-angular@7.3.21 requires a peer of @angular/core@^7.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN igniteui-angular@7.3.21 requires a peer of @angular/forms@^7.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN igniteui-angular@7.3.21 requires a peer of web-animations-js@^2.3.1 but none is installed. You must install peer dependencies yourself.
npm WARN ng-image-fullscreen-view@1.0.3 requires a peer of @angular/common@^8.2.14 but none is installed. You must install peer dependencies yourself.
npm WARN ng-image-fullscreen-view@1.0.3 requires a peer of @angular/core@^8.2.14 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/compiler@2.2.4 requires a peer of @angular/core@2.2.4 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/compiler-cli@2.3.0 requires a peer of @angular/compiler@2.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-browser-dynamic@2.3.0 requires a peer of @angular/compiler@2.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/router@3.2.4 requires a peer of @angular/core@2.2.4 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/router@3.2.4 requires a peer of @angular/common@2.2.4 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/router@3.2.4 requires a peer of @angular/platform-browser@2.2.4 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/router@3.2.4 requires a peer of rxjs@5.0.0-beta.12 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-slide-toggle@0.1.1 requires a peer of @angular/core@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-slide-toggle@0.1.1 requires a peer of @angular/common@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-spinner@8.1.0 requires a peer of @angular/common@^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-spinner@8.1.0 requires a peer of @angular/core@^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-toggle-switch@2.0.5 requires a peer of @angular/core@>=5.0.0 <=6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-toggle-switch@2.0.5 requires a peer of @angular/common@>=5.0.0 <=6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-toggle-switch@2.0.5 requires a peer of rxjs@^5.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN The package bootstrap is included as both a dev and production dependency.
npm WARN The package rxjs is included as both a dev and production dependency.
npm WARN The package zone.js is included as both a dev and production dependency.
npm ERR! path /opt/atlassian/pipelines/agent/build/node_modules/jspdf/node_modules/file-saver
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access '/opt/atlassian/pipelines/agent/build/node_modules/jspdf/node_modules/file-saver'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-23T14_35_08_646Z-debug.log
Build teardown

**Comment by ljharb** [comment]
Please fill out the issue template in its entirety, including more than just that one line of log output.

**Comment by AmidouSeck** [comment]
@ljharb issue template updated

**Comment by ljharb** [comment]
The error suggests a permissions issue in `/opt/atlassian/pipelines/agent/build/`. Can you confirm that user has full ownership of that directory?

**Comment by wraithgar** [comment]
Please follow the issue template when creating issues
