### ISSUE TITLE
[Need Help] ReactDataGrid | Inline edit functionality of ReactDataGrid is not working on Tab page

### ISSUE THREAD

**Issue by priyankalxi** [npm/cli#3131]
### Current Behavior:
1. I have created sample page in react js to implement **inline edit** functionality as per given example on "https://adazzle.github.io/react-data-grid/docs/examples/default-editor"   and it is working but same page if I am calling on Tab control then inline edit functionality is not working.
2. I am using **NavPills** Tab control and this page will be a one **tabcontent** in my application.
3. In my sample page I am able to select cell and and edit it but when I do the same in tab page then it is not selecting cell and if I press characters then it is taking only one character for cell edit. Please refer attached **screenshot** over here.

### Expected Behavior:
Inline edit should work on tab control or tab pages also

### Environment:
I am using "react-data-grid": "^6.1.0" 

Working screenshot 
![image](https://user-images.githubusercontent.com/82876278/115866971-1321ed80-a458-11eb-965f-4fc39ed3c40d.png)

Not working on tab page. Only one character is updated in below screenshot and not able to select cell on double click
![image](https://user-images.githubusercontent.com/82876278/115868050-78c2a980-a459-11eb-9f17-1abf9e0f47c6.png)

VS code and node js version
![image](https://user-images.githubusercontent.com/82876278/115868452-1918ce00-a45a-11eb-80cd-9e96e911f67a.png)

**Comment by nlf** [comment]
this repository is for support of `npm`, the cli tool you use to install packages and not for how to use packages. you'll need to file this issue on the repository for the module you are using, which looks to be this one https://github.com/adazzle/react-data-grid

for future reference, you can typically find this by running `npm bugs react-data-grid`

**Comment by priyankalxi** [comment]
Thank you
