### ISSUE TITLE
[BUG] dependency with a `npm-shrinkwrap.json` doesn't install properly when using `npm-ci`

### ISSUE THREAD

**Issue by DetachHead** [npm/cli#3144]
### Current Behavior:
if a package defined in `package.json` has its own `npm-shrinkwrap.json` and you run `npm ci`, none of the package's files get installed, only a nested `node_modules` folder is created.

### Expected Behavior:
all of the files in the package are installed

### Steps To Reproduce:
1. go to a directory with a `package.json` in it
2. install a package that has an `npm-shrinkwrap.json` in it (eg. `npm install @detachhead/ts-helpers@7.0.0-56fddd9273c70b028585f63a2ec0e9f01ff9902b`)
3. check the package in `node_modules`, so far so good:
    
    ![image](https://user-images.githubusercontent.com/57028336/115965398-72712200-a56c-11eb-8a54-07f8a8202009.png)

4. run `npm ci`, then  check the package's `node_modules` directory again:
    
    ![image](https://user-images.githubusercontent.com/57028336/115965302-d7784800-a56b-11eb-9778-eb63dad63073.png)

### Environment:
- OS: windows 10 20H2
- Node: 15.3.0
- npm: 7.0.4

**Comment by nlf** [comment]
we made some fixes to how shrinkwraps are handled recently, and your version of npm (7.0.4) is quite old at this point. can you try updating to 7.11.1 and see if you still have this problem?

**Comment by DetachHead** [comment]
that seems to have fixed it, thanks
