### ISSUE TITLE
Package statistics don't make any sense after publishing update (react @ 33% maintenance)

### ISSUE THREAD

**Issue by darcyclarke** [npm/cli#315]
Original bug ticket: [https://npm.community/t/9755](https://npm.community/t/9755)
      Originally filed: 2019-08-29T07:12:43.850Z

**Comment by patrickjuchli** [comment]
There is still something quite wrong with quality and maintenance scores. 

This has not been addressed for 4 months and yet is a prominent feature on npmjs.com. Have you considered just removing it? Or using whatever npms.io is showing?
