### ISSUE TITLE
[BUG] <PLEASE HELP ME MARKER WAS NOT FOUND>

### ISSUE THREAD

**Issue by milikmu** [npm/cli#3150]
### Environment:

![Screenshot_2021_0426_035022](https://user-images.githubusercontent.com/78453797/116010004-b0427900-a646-11eb-88ed-f3e8fb9a4649.png)

**Comment by devlzcode** [comment]
And how is this an NPM error?

**Comment by milikmu** [comment]
I dont know?

**Comment by nlf** [comment]
this doesn't appear to relate to npm in any way
