### ISSUE TITLE
error This is an error with npm itself.

### ISSUE THREAD

**Issue by FarshadMahmoudi** [npm/cli#3151]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   'electron-edge-js'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v13.14.0
4 verbose npm-session bda7085929f6c093
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/electron-edge-js 1802ms (from cache)
8 timing npm Completed in 11338ms
9 error cb() never called!
10 error This is an error with npm itself. Please report this error at:
11 error <https://npm.community>

**Comment by nlf** [comment]
see #417 and if you still have problems feel free to open a new issue, but please be sure to fill out our issue template as fully as you can.
