### ISSUE TITLE
[BUG] `npm update -g` appears to do nothing.

### ISSUE THREAD

**Issue by coreyog** [npm/cli#3159]
### Current Behavior:
1. Run `npm update -g`
2. Output indicates changes were made
3. Run `npm update -g` again
4. Receive exact same output indicating exact same changes
5. Doubt anything happened at all

### Expected Behavior:
1. Run `npm update -g`
2. Output indicates changes were made
3. Run `npm update -g` again
4. Receive no output because nothing needed to change

### Steps To Reproduce:
Run `npm update -g` multiple times and notice that output always seems to indicate that a change was made.

### Environment:
- OS: macOS 10.15.7
- Node: 15.14.0
- npm: 7.11.1

**Comment by darcyclarke** [comment]
Closing as a duplicate - we're tracking this as work associated with general fixes to `npm update -g`
