### ISSUE TITLE
Error Not Found when I update the package I create

### ISSUE THREAD

**Issue by tachibana-shin** [npm/cli#3161]
Hi,

I get this error when I try to update a package I already own. What happen?

![image](https://user-images.githubusercontent.com/45375496/116386040-9d48c800-a843-11eb-8374-439c52cbb74e.png)

I own this package.

Please help me

**Comment by ljharb** [comment]
You’re using yarn here, which means it might be a yarn bug. What happens with `npm publish`?

**Comment by tachibana-shin** [comment]
It also happened the same error. I try:

``` bash
npm publish
npm logout
nom login
npm publish
```

But it not working

**Comment by ljharb** [comment]
After `npm login`, does `npm whoami` print out the result you expect? what about `npm config get registry`?

**Comment by tachibana-shin** [comment]
```bash npm login``` is successful but when i run ```bash npm whoami``` i get an error:

npm ERR! code E401
npm ERR! 401 Unauthorized - GET https://registry.npmjs.org/-/whoami

``` bash npm config get registry``` result:
https://registry.npmjs.org/

**Comment by ljharb** [comment]
The `npm whoami` suggests that the login isn't successful :-/

**Comment by tachibana-shin** [comment]
How can i fix it. I run ```npm login``` and it notified me that the login was successful

**Comment by darcyclarke** [comment]
I think you're misconfigured when you're trying to publish - you should double check your `publishConfig` in your `package.json` (if `yarn` supports that) &/or you should explicitly pass in the registry you're trying to publish to (ex. `yarn publish --registry=https://npm.pkg.github.com`) as `npm` would default to `registry.npmjs.org` as would `yarn`.
