### ISSUE TITLE
i can´t insttal a package or update npm

### ISSUE THREAD

**Issue by desarrollopetrocasinos** [npm/cli#3164]
### Current Behavior:
I'm trying to install xlsx file-saver but I got this error: 

npm install ngx-bootstrap xlsx file-saver --save
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm ERR! code EINVALIDTYPE
npm ERR! typeerror Error: Argument #5: Expected object but got string
npm ERR! typeerror     at inflatableChild (...\AppData\Roaming\npm\node_modules\npm\lib\install\inflate-shrinkwrap.js:93:3)
npm ERR! typeerror     at ...\AppData\Roaming\npm\node_modules\npm\lib\install\inflate-shrinkwrap.js:55:12
npm ERR! typeerror     at tryCatcher (...\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
npm ERR! typeerror     at Object.gotValue (...\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\reduce.js:155:18)
npm ERR! typeerror     at Object.gotAccum (...\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\reduce.js:144:25)
npm ERR! typeerror     at Object.tryCatcher (...\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
npm ERR! typeerror     at Promise._settlePromiseFromHandler (...\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:517:31)
npm ERR! typeerror     at Promise._settlePromise (...\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:574:18)
npm ERR! typeerror     at Promise._settlePromiseCtx (...\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:611:10)
npm ERR! typeerror     at _drainQueueStep (...\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:142:12)
npm ERR! typeerror     at _drainQueue (...\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:131:9)
npm ERR! typeerror     at Async._drainQueues (...\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:147:5)
npm ERR! typeerror     at Immediate.Async.drainQueues [as _onImmediate] (...\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
npm ERR! typeerror     at processImmediate (internal/timers.js:456:21)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <https://npm.community>

When I try to update: 

npm update
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm ERR! code EINVALIDTYPE
npm ERR! typeerror Error: Argument #5: Expected object but got string
npm ERR! typeerror     at inflatableChild (...\AppData\Roaming\npm\node_modules\npm\lib\install\inflate-shrinkwrap.js:93:3)
npm ERR! typeerror     at ...\AppData\Roaming\npm\node_modules\npm\lib\install\inflate-shrinkwrap.js:55:12
npm ERR! typeerror     at tryCatcher (...\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
npm ERR! typeerror     at Object.gotValue (...\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\reduce.js:155:18)
npm ERR! typeerror     at Object.gotAccum (...\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\reduce.js:144:25)
npm ERR! typeerror     at Object.tryCatcher (...\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
npm ERR! typeerror     at Promise._settlePromiseFromHandler (...\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:517:31)
npm ERR! typeerror     at Promise._settlePromise (...\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:574:18)
npm ERR! typeerror     at Promise._settlePromiseCtx (...\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:611:10)
npm ERR! typeerror     at _drainQueueStep (...\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:142:12)
npm ERR! typeerror     at _drainQueue (...\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:131:9)
npm ERR! typeerror     at Async._drainQueues (...\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:147:5)
npm ERR! typeerror     at Immediate.Async.drainQueues [as _onImmediate] (...\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
npm ERR! typeerror     at processImmediate (internal/timers.js:456:21)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <https://npm.community>

### Expected Behavior:
that npm install that package or update npm

### Steps To Reproduce:
in the command line you can wrote:  install ngx-bootstrap xlsx file-saver --save

### Environment:
OS: win 10
NODE: 12.16.1
npm: 6.14.2
SW: WebStorm

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
