### ISSUE TITLE
[BUG] Installing packages (npm)...npm ERR! cb() never called

### ISSUE THREAD

**Issue by Christoph1972** [npm/cli#3165]
Hello together,

I can’t create new angular projects. Running ng new someDemo fires the following error message:

_REATE someTest/e2e/src/app.po.ts (274 bytes)
    | Installing packages (npm)...npm ERR! cb() never called!
    npm ERR! This is an error with npm itself. Please report this error at:
    npm ERR!     <https://npm.community>
    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\MyUser\AppData\Roaming\npm-cache\_logs\2021-04-29T12_38_54_915Z-debug.log
    × Package install failed, see above.
    The Schematic workflow failed. See above._

This is the content of the log file:

_0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--quiet'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.19.0
4 verbose npm-session 6a2c85ea23618f85
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall sometest@0.0.0
7 info lifecycle sometest@0.0.0~preinstall: sometest@0.0.0
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 timing stage:loadCurrentTree Completed in 14ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 3ms
16 silly install loadAllDepsIntoIdealTree
17 http fetch GET 407 https://registry.npmjs.org/karma 228ms
18 http fetch GET 407 https://registry.npmjs.org/jasmine-core 238ms
19 http fetch GET 407 https://registry.npmjs.org/@angular-devkit%2fbuild-angular 246ms
20 http fetch GET 407 https://registry.npmjs.org/codelyzer 239ms
21 http fetch GET 407 https://registry.npmjs.org/@types%2fjasmine 242ms
22 http fetch GET 407 https://registry.npmjs.org/@angular%2fcompiler-cli 243ms
23 http fetch GET 407 https://registry.npmjs.org/@angular%2fcli 244ms
24 http fetch GET 407 https://registry.npmjs.org/@types%2fnode 241ms
25 http fetch GET 407 https://registry.npmjs.org/karma-chrome-launcher 228ms
26 http fetch GET 407 https://registry.npmjs.org/jasmine-spec-reporter 239ms
27 timing npm Completed in 1521ms
28 error cb() never called!
29 error This is an error with npm itself. Please report this error at:
30 error <https://npm.community>_

I did al steps as mentioned here: https://www.c-sharpcorner.com/article/how-to-solve-the-schematic-workflow-failed-error-in-angular/

What’s on here? What can I do?

**Comment by Suryapardana** [comment]
I also experienced it just now, how to fix it?

**Comment by ljharb** [comment]
Try npm 7. Also, see #417.

**Comment by Suryapardana** [comment]
> Try npm 7. Also, see #417.

Thank you friend

**Comment by Christoph1972** [comment]
I upgraded to nmp 7. It's still the same issue.

**Comment by Christoph1972** [comment]
Installing the newest version of node.js fixed this issue.
