### ISSUE TITLE
[BUG] <cb() never called>

### ISSUE THREAD

**Issue by Manik-Jain** [npm/cli#3167]
Note: Please search to see if an issue already exists for your problem: https://github.com/npm/cli/issues

### Current Behavior:
npm ERR! cb() never called!
npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

### Expected Behavior:
Project dependencies should be downloaded

### Steps To Reproduce:

Run: 
npm install --force
npm WARN using --force Recommended protections disabled.
npm ERR! cb() never called!
npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

### Environment:

- OS: MacOS
- Node: 15.2.0
- npm: 7.0.10

**Comment by Christoph1972** [comment]
Maybe it's related to this: https://github.com/npm/cli/issues/3165

**Comment by ljharb** [comment]
#417

**Comment by nlf** [comment]
as mentioned, see #417, try updating to the latest npm 7 (7.11.2 as of this writing) and if you continue to have problems open a new issue being sure to fill out the issue template entirely. we need to know a lot more information about what you're doing in order to help you with this.
