### ISSUE TITLE
'CALL "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by AjayS21** [npm/cli#3168]
Every time I run an npm command I get this message

'CALL "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or external command, operable program or batch file.

I have uninstalled the node, restarted the computer, and reinstalled the node. This did not make the error go away.

OS
Windows 7 Pro
![image](https://user-images.githubusercontent.com/72499157/116677439-d4df7d80-a9c5-11eb-803b-965accc3df80.png)

**Comment by wraithgar** [comment]
Please use the issue template when creating new issues

**Comment by jaswantisum** [comment]
hii,
how fixed this issue?
