### ISSUE TITLE
[BUG] `npm version prerelease` does not work with numeric `--preid`

### ISSUE THREAD

**Issue by ntkme** [npm/cli#3181]
Currently `--preid` only works correctly with non-numeric value. I have actually root caused it down to a bug in npm/node-semver and submitted a PR to fix it: https://github.com/npm/node-semver/pull/380. I'm opening this issue for tracking purpose and hopefully to get some attention from the npm team.

### Current Behavior:

Case 1:

```
$ cat package.json
{
  "name": "test",
  "version": "1.0.0-2021.0"
}

$ npm version prerelease --preid 2021
npm ERR! Version not changed
```

Case 2:

```
$ cat package.json
{
  "name": "test",
  "version": "1.0.0-2021.1"
}

$ npm version prerelease --preid 2021
v1.0.0-2021.0
```

### Expected Behavior:

Case 1:

```
$ cat package.json
{
  "name": "test",
  "version": "1.0.0-2021.0"
}

$ npm version prerelease --preid 2021
v1.0.0-2021.1
```

Case 2:

```
$ cat package.json
{
  "name": "test",
  "version": "1.0.0-2021.1"
}

$ npm version prerelease --preid 2021
v1.0.0-2021.2
```

### Environment:
```
$ node --version
v16.0.0
$ npm --version
7.10.0
```

**Comment by darcyclarke** [comment]
**Actions:**
- [ ] should support numeric `--preid`s
- [ ] should error out more appropriately

**Comment by ntkme** [comment]
The [semver spec](https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions) says numeric should be supported:

```
<pre-release identifier> ::= <alphanumeric identifier>
                           | <numeric identifier>
```
