### ISSUE TITLE
[BUG] node-gyp@v7 still has dependency on deprecated requests module

### ISSUE THREAD

**Issue by luckman212** [npm/cli#3183]
`node-gyp@8` has removed `requests` dependency: [node-gyp #2220](https://github.com/nodejs/node-gyp/pull/2220). Hopefully npm can roll up to gyp@8 to clean up the warning below:

```
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
``` 

node: 16.1.0
npm: 7.11.2
OS: macOS 11.3.1

**Comment by wraithgar** [comment]
This is on our roadmap.
