### ISSUE TITLE
 This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

### ISSUE THREAD

**Issue by HamzaAdam** [npm/cli#3188]
[2021-05-04T21_18_25_344Z-debug.log](https://github.com/npm/cli/files/6424179/2021-05-04T21_18_25_344Z-debug.log)

**Comment by ljharb** [comment]
That means the lockfile was made with npm 7, but you're using npm 6.

Everyone on your project should be using the same node/npm versions, consistently.
