### ISSUE TITLE
[BUG] sh: tsc: Permission denied when running npm run start

### ISSUE THREAD

**Issue by ZFail** [npm/cli#3189]
### Current Behavior:
"sh: tsc: Permission denied" when running "npm run start"

### Expected Behavior:
"npm run start" must run "tsc -v" command with result "Version 4.2.4"

### Steps To Reproduce:
```sh
# git clone must be run under user
git clone https://github.com/ZFail/npm-reproducer.git
# mounted directory (/root/ws) must not exist in docker
docker run --rm -it -v $(pwd)/npm-reproducer:/root/ws node:16.0.0-alpine3.11 sh
# next commands in opened docker shell
cd /root/ws
npm install
npm run start
> npm-reproducer@1.0.0 start
> tsc -v

sh: tsc: Permission denied
```
### Environment:
- Host OS: Ubuntu 18.04.3 LTS
- Node: v16.0.0
- npm: 7.10.0

**Comment by wraithgar** [comment]
If `tsc` is not a command you have installed on your machine locally, this is going to fail.

If you are trying to run `npm exec tsc` then that needs to be the actual `start` entry in your `scripts` object.

**Comment by ZFail** [comment]
> If `tsc` is not a command you have installed on your machine locally, this is going to fail.

`tsc` is a script for starting the typescript compiler, which is installed under the path `node_modules/.bin/tsc` after running the `npm install` command
PS. node v14 and yarn execute these commands successfully, the problem only appears in node v15 and v16

**Comment by ljharb** [comment]
The `permission denied` error suggests that it's invoking the right binary, but it lacks the `x` permission.

**Comment by ZFail** [comment]
> The `permission denied` error suggests that it's invoking the right binary, but it lacks the `x` permission.

all coomand in docker runs under root
```
~/ws # npm run start

> npm-reproducer@1.0.0 start
> tsc -v

sh: tsc: Permission denied
~/ws # ls -la node_modules/.bin/tsc
lrwxrwxrwx    1 root     root            21 May  6 22:16 node_modules/.bin/tsc -> ../typescript/bin/tsc
~/ws # ls -la node_modules/typescript/bin/tsc
-rwxr-xr-x    1 node     node            45 Oct 26  1985 node_modules/typescript/bin/tsc
```

**Comment by ljharb** [comment]
what does `which tsc` say?

**Comment by ZFail** [comment]
> what does `which tsc` say?

nothing
```
~/ws # which tsc
~/ws #
```

**Comment by ljharb** [comment]
Then it's very strange that `./node_modules/.bin/tsc` would say "permission denied", since you clearly have permission to execute it. My guess is it's something about your docker setup.

**Comment by ZFail** [comment]
> Then it's very strange that `./node_modules/.bin/tsc` would say "permission denied", since you clearly have permission to execute it. My guess is it's something about your docker setup.

I can reproduce this bug on two different machines running under ubuntu 18.04

command `./node_modules/.bin/tsc -v` runs succesfully
```
~/ws # ./node_modules/.bin/tsc -v
Version 4.2.4
```

**Comment by ZFail** [comment]
If I put this command under start script, npm returns
```
~/ws # npm run start

> npm-reproducer@1.0.0 start
> ./node_modules/.bin/tsc -v

node:internal/modules/cjs/loader:943
  throw err;
  ^

Error: Cannot find module '/root/ws/node_modules/.bin/tsc'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.Module._load (node:internal/modules/cjs/loader:773:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by ZFail** [comment]
Look like the npm for some reason runs command under user 'node'

```
~/ws # su node -c "./node_modules/.bin/tsc -v"
node:internal/modules/cjs/loader:943
  throw err;
  ^

Error: Cannot find module '/root/ws/node_modules/.bin/tsc'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.Module._load (node:internal/modules/cjs/loader:773:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by ljharb** [comment]
Ahhhh. Yes, when you're root, i believe npm runs under a no-privilege user, and that might be the issue here.

**Comment by ZFail** [comment]
Confirmed, npm run scripts under user `node`:

```
~/ws # node -e "console.log(require('os').userInfo().username)"
root
~/ws # npm run username

> npm-reproducer@1.0.0 username
> node -e "console.log(require('os').userInfo().username)"

node
```

**Comment by ZFail** [comment]
> Ahhhh. Yes, when you're root, i believe npm runs under a no-privilege user, and that might be the issue here.

Why? It`s documented somethere?

**Comment by ljharb** [comment]
I assume because running as root would be very dangerous - ie, it opens up an attack vector from malicious npm packages.

**Comment by ZFail** [comment]
> Ahhhh. Yes, when you're root, i believe npm runs under a no-privilege user, and that might be the issue here.

This is not true, i create another folder under root, copy the package.json to it, and run commands there:
```
~/ws # mkdir /root/2
~/ws # cp package.json /root/2/
~/ws # cd ../2
~/2 # npm install

added 1 package, and audited 2 packages in 797ms

found 0 vulnerabilities
~/2 # npm run start

> npm-reproducer@1.0.0 start
> ./node_modules/.bin/tsc -v

Version 4.2.4
~/2 # npm run username

> npm-reproducer@1.0.0 username
> node -e "console.log(require('os').userInfo().username, require('os').userInfo().uid, require('os').userInfo().gid)"

root 0 0
```

I think npm runs commands under the owner of the directory in which the package.json is located.
very strange behavior
