### ISSUE TITLE
Sr Technical Architect

### ISSUE THREAD

**Issue by bobmoss14** [npm/cli#3199]
trying to install npm install mat-video for angular app and it gives the following error: 
Build at: 2021-05-06T18:06:01.288Z - Hash: d0051c06976f78f5b7de - Time: 2811ms

Error: node_modules/mat-video/lib/internal/mat-slider-progress-bar/mat-slider-progress-bar.component.d.ts:8:5 - error TS2610: 'value' is defined as an accessor in class 'MatSlider', but is overridden here in 'MatSliderProgressBarComponent' as an instance property.

8     value: number;
      ~~~~~

**Comment by ljharb** [comment]
Seems like a typescript error, not an issue with npm.
