### ISSUE TITLE
Coiner Miner Detected By Windows v6.14.13

### ISSUE THREAD

**Issue by StephenAArredondo** [npm/cli#3202]
Hello,

Just recently received a windows defender alert to a coin miner detected in my node_modules/AUTHOR directory.

My project is currently using:  "npm": "^6.14.13"

Just wanted to bring it to the attention of the community.

Currently, we can't move away from this version and need some guidance on how to assess this.

![image](https://user-images.githubusercontent.com/8017722/117371346-baaa1180-ae95-11eb-986b-fd90ac4d67cf.png)

**Comment by ljharb** [comment]
That file is just a text file listing people's names and email addresses. As such, it can't possibly be a miner; Windows Defender is incorrect here.

The solution is to fix Windows Defender (and/or to ignore this warning).

**Comment by StephenAArredondo** [comment]
Thank you for the quick response!

Just wanted to make sure.
