### ISSUE TITLE
[BUG] Npm Publish assumes an incorrect path to a dir

### ISSUE THREAD

**Issue by omelnik** [npm/cli#3204]
### Current Behavior:
I'm working on a common package for my app and I'd like to publish it to the NPM registry. When I tried to publish a specific dir (in my case, the name of this dir is "dist" and it contains `package.json` inside) for some reason `npm publish` added this dir twice to its path. The publishing  process starts, but it gets aborted halfway through. I assume it's due to the issue with the path.

```fish
> npm publish ./dist --access public

npm ERR! code ENOENT ⠴ : notice
npm ERR! syscall open
npm ERR! path /Users/<myuser>/udemy/app/common/dist/dist/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/<myuser>/udemy/app/common/dist/dist/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/<myuser>/.npm/_logs/2021-05-07T00_20_13_271Z-debug.log
npm ERR! code 254
npm ERR! path /Users/<myuser>/projects/courses/udemy/ticketing/common/dist
npm ERR! command failed
npm ERR! command sh -c npm publish ./dist --access public

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/<myuser>/.npm/_logs/2021-05-07T00_20_13_297Z-debug.log
```

Here's my folder structure:
```
.
├── dist
│   ├── config
│   ├── constants
│   │   └── resources
│   ├── errors
│   ├── events
│   ├── middleware
│   ├── types
│   └── validations
└── src
    ├── config
    ├── constants
    │   └── resources
    ├── errors
    ├── events
    ├── middleware
    ├── types
    └── validations
```

According to [npm-publish docs](https://docs.npmjs.com/cli/v7/commands/npm-publish#description) it's  possible. Not sure what I'm doing wrong here. 

### Expected Behavior:
Should be able to  publish a specific folder successfully.

### Steps To Reproduce:
1. Run `npm publish ./dist --access public`
2. See error describe above

### Environment:
- OS: macOS Catalina 10.15.7
- Node: v15.11.0
- npm: 7.12.0

**Comment by darcyclarke** [comment]
Can you try reproducing on the latest version of `npm` (ie. `npm i -g npm`); We made some changes/improvements to `npm publish` that might have resolve this issue
