### ISSUE TITLE
[BUG] Meshcentral Update error

### ISSUE THREAD

**Issue by VINISHVV** [npm/cli#3213]
### Current Behavior:
When i am trying to update my meshcentral application to new version i am getting below error message.

_______________________________________________________________________0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'meshcentral@0.8.31'
1 verbose cli ]
2 info using npm@6.14.10
3 info using node@v14.15.4
4 verbose npm-session 0aef3a9c6e254065
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/meshcentral 1407ms (from cache)
8 silly pacote version manifest for meshcentral@0.8.31 fetched in 1468ms
9 timing stage:loadCurrentTree Completed in 2641ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 6ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 659ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule meshcentral@0.8.31 checking installable status
17 silly removeObsoleteDep removing meshcentral@0.8.29 from the tree as its been replaced by a newer version or is no longer required
18 silly removeObsoleteDep removing xmldom@0.5.0 from the tree as its been replaced by a newer version or is no longer required
19 http fetch GET 304 https://registry.npmjs.org/xmldom 120ms (from cache)
20 silly pacote range manifest for xmldom@^0.5.0 fetched in 127ms
21 silly resolveWithNewModule xmldom@0.5.0 checking installable status
22 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 619ms
23 timing stage:loadIdealTree Completed in 1489ms
24 silly currentTree M-ACCESS
24 silly currentTree +-- accepts@1.3.7
24 silly currentTree +-- agent-base@6.0.2
24 silly currentTree | +-- debug@4.3.1
24 silly currentTree | `-- ms@2.1.2
24 silly currentTree +-- archiver-utils@2.1.0
24 silly currentTree | `-- readable-stream@2.3.7
24 silly currentTree +-- archiver@4.0.2
24 silly currentTree | `-- async@3.2.0
24 silly currentTree +-- array-flatten@1.1.1
24 silly currentTree +-- asap@2.0.6
24 silly currentTree +-- asn1.js@5.4.1
24 silly currentTree +-- asn1@0.2.4
24 silly currentTree +-- async-limiter@1.0.1
24 silly currentTree +-- async@0.2.10
24 silly currentTree +-- axios@0.21.1
24 silly currentTree +-- balanced-match@1.0.0
24 silly currentTree +-- base64-js@1.5.1
24 silly currentTree +-- bcrypt-pbkdf@1.0.2
24 silly currentTree +-- bignumber.js@9.0.1
24 silly currentTree +-- binary-search-tree@0.2.5
24 silly currentTree +-- bl@4.1.0
24 silly currentTree | `-- inherits@2.0.4
24 silly currentTree +-- bn.js@4.12.0
24 silly currentTree +-- body-parser@1.19.0
24 silly currentTree +-- brace-expansion@1.1.11
24 silly currentTree +-- bson@1.1.5
24 silly currentTree +-- buffer-crc32@0.2.13
24 silly currentTree +-- buffer-equal-constant-time@1.0.1
24 silly currentTree +-- buffer@5.7.1
24 silly currentTree +-- bunyan@1.8.15
24 silly currentTree +-- bytes@3.1.0
24 silly currentTree +-- call-bind@1.0.2
24 silly currentTree +-- cbor@5.2.0
24 silly currentTree +-- compress-commons@3.0.0
24 silly currentTree | `-- readable-stream@2.3.7
24 silly currentTree +-- compressible@2.0.18
24 silly currentTree +-- compression@1.7.4
24 silly currentTree | `-- bytes@3.0.0
24 silly currentTree +-- concat-map@0.0.1
24 silly currentTree +-- connect-redis@3.4.2
24 silly currentTree | +-- debug@4.3.1
24 silly currentTree | `-- ms@2.1.2
24 silly currentTree +-- content-disposition@0.5.3
24 silly currentTree +-- content-type@1.0.4
24 silly currentTree +-- cookie-session@2.0.0-rc.1
24 silly currentTree | +-- debug@3.2.6
24 silly currentTree | +-- ms@2.1.3
24 silly currentTree | `-- safe-buffer@5.2.0
24 silly currentTree +-- cookie-signature@1.0.6
24 silly currentTree +-- cookie@0.4.0
24 silly currentTree +-- cookies@0.8.0
24 silly currentTree | `-- depd@2.0.0
24 silly currentTree +-- core-util-is@1.0.2
24 silly currentTree +-- crc@3.8.0
24 silly currentTree +-- crc32-stream@3.0.1
24 silly currentTree +-- dayjs@1.10.4
24 silly currentTree +-- debug@2.6.9
24 silly currentTree +-- define-properties@1.1.3
24 silly currentTree +-- denque@1.5.0
24 silly currentTree +-- depd@1.1.2
24 silly currentTree +-- destroy@1.0.4
24 silly currentTree +-- double-ended-queue@2.1.0-0
24 silly currentTree +-- dtrace-provider@0.8.8
24 silly currentTree +-- ecdsa-sig-formatter@1.0.11
24 silly currentTree +-- ee-first@1.1.1
24 silly currentTree +-- encodeurl@1.0.2
24 silly currentTree +-- end-of-stream@1.4.4
24 silly currentTree +-- escape-html@1.0.3
24 silly currentTree +-- etag@1.8.1
24 silly currentTree +-- express-handlebars@3.1.0
24 silly currentTree +-- express-ws@4.0.0
24 silly currentTree | `-- ws@5.2.2
24 silly currentTree +-- express@4.17.1
24 silly currentTree +-- fd-slicer@1.1.0
24 silly currentTree +-- finalhandler@1.1.2
24 silly currentTree +-- follow-redirects@1.13.3
24 silly currentTree +-- forwarded@0.1.2
24 silly currentTree +-- fresh@0.5.2
24 silly currentTree +-- fs-constants@1.0.0
24 silly currentTree +-- fs.realpath@1.0.0
24 silly currentTree +-- function-bind@1.1.1
24 silly currentTree +-- get-intrinsic@1.1.1
24 silly currentTree +-- glob@7.1.6
24 silly currentTree +-- graceful-fs@4.2.6
24 silly currentTree +-- handlebars@4.7.7
24 silly currentTree +-- has-symbols@1.0.2
24 silly currentTree +-- has@1.0.3
24 silly currentTree +-- http_ece@1.1.0
24 silly currentTree +-- http-errors@1.7.2
24 silly currentTree +-- https-proxy-agent@5.0.0
24 silly currentTree | +-- debug@4.3.1
24 silly currentTree | `-- ms@2.1.2
24 silly currentTree +-- iconv-lite@0.4.24
24 silly currentTree +-- ieee754@1.2.1
24 silly currentTree +-- image-size@0.9.4
24 silly currentTree +-- immediate@3.0.6
24 silly currentTree +-- inflight@1.0.6
24 silly currentTree +-- inherits@2.0.3
24 silly currentTree +-- ipaddr.js@1.9.1
24 silly currentTree +-- ipcheck@0.1.0
24 silly currentTree +-- isarray@1.0.0
24 silly currentTree +-- jsonwebtoken@8.5.1
24 silly currentTree | `-- ms@2.1.3
24 silly currentTree +-- jwa@1.4.1
24 silly currentTree +-- jws@3.2.2
24 silly currentTree +-- keygrip@1.1.0
24 silly currentTree +-- lazystream@1.0.0
24 silly currentTree | `-- readable-stream@2.3.7
24 silly currentTree +-- lie@3.1.1
24 silly currentTree +-- loadavg-windows@1.1.1
24 silly currentTree +-- localforage@1.9.0
24 silly currentTree +-- lodash.defaults@4.2.0
24 silly currentTree +-- lodash.difference@4.5.0
24 silly currentTree +-- lodash.flatten@4.4.0
24 silly currentTree +-- lodash.includes@4.3.0
24 silly currentTree +-- lodash.isboolean@3.0.3
24 silly currentTree +-- lodash.isinteger@4.0.4
24 silly currentTree +-- lodash.isnumber@3.0.3
24 silly currentTree +-- lodash.isplainobject@4.0.6
24 silly currentTree +-- lodash.isstring@4.0.1
24 silly currentTree +-- lodash.once@4.1.1
24 silly currentTree +-- lodash.union@4.6.0
24 silly currentTree +-- lodash@4.17.21
24 silly currentTree +-- media-typer@0.3.0
24 silly currentTree +-- memory-pager@1.5.0
24 silly currentTree +-- merge-descriptors@1.0.1
24 silly currentTree +-- meshcentral@0.8.29
24 silly currentTree | `-- xmldom@0.5.0
24 silly currentTree +-- methods@1.1.2
24 silly currentTree +-- mime-db@1.46.0
24 silly currentTree +-- mime-types@2.1.29
24 silly currentTree +-- mime@1.6.0
24 silly currentTree +-- minimalistic-assert@1.0.1
24 silly currentTree +-- minimatch@3.0.4
24 silly currentTree +-- minimist@1.2.5
24 silly currentTree +-- mkdirp@0.5.5
24 silly currentTree +-- moment@2.29.1
24 silly currentTree +-- mongodb@3.6.4
24 silly currentTree | +-- bl@2.2.1
24 silly currentTree | `-- readable-stream@2.3.7
24 silly currentTree +-- ms@2.0.0
24 silly currentTree +-- multiparty@4.2.2
24 silly currentTree | +-- http-errors@1.8.0
24 silly currentTree | +-- inherits@2.0.4
24 silly currentTree | +-- safe-buffer@5.2.1
24 silly currentTree | `-- setprototypeof@1.2.0
24 silly currentTree +-- mv@2.1.1
24 silly currentTree +-- nan@2.14.2
24 silly currentTree +-- ncp@2.0.0
24 silly currentTree +-- nedb@1.8.0
24 silly currentTree +-- negotiator@0.6.2
24 silly currentTree +-- neo-async@2.6.2
24 silly currentTree +-- node-forge@0.10.0
24 silly currentTree +-- node-rdpjs-2@0.3.5
24 silly currentTree +-- node-windows@1.0.0-beta.5
24 silly currentTree +-- nodemailer@6.5.0
24 silly currentTree +-- nofilter@1.0.4
24 silly currentTree +-- normalize-path@3.0.0
24 silly currentTree +-- object-keys@1.1.1
24 silly currentTree +-- object.assign@4.1.2
24 silly currentTree +-- on-finished@2.3.0
24 silly currentTree +-- on-headers@1.0.2
24 silly currentTree +-- once@1.4.0
24 silly currentTree +-- optimist@0.6.1
24 silly currentTree | +-- minimist@0.0.10
24 silly currentTree | `-- wordwrap@0.0.3
24 silly currentTree +-- otplib@10.2.3
24 silly currentTree +-- parseurl@1.3.3
24 silly currentTree +-- path-is-absolute@1.0.1
24 silly currentTree +-- path-to-regexp@0.1.7
24 silly currentTree +-- pend@1.2.0
24 silly currentTree +-- pop-iterate@1.0.1
24 silly currentTree +-- process-nextick-args@2.0.1
24 silly currentTree +-- promise@8.1.0
24 silly currentTree +-- proxy-addr@2.0.6
24 silly currentTree +-- q@2.0.3
24 silly currentTree +-- qs@6.7.0
24 silly currentTree +-- querystringify@2.2.0
24 silly currentTree +-- queue@6.0.1
24 silly currentTree +-- random-bytes@1.0.0
24 silly currentTree +-- range-parser@1.2.1
24 silly currentTree +-- raw-body@2.4.0
24 silly currentTree +-- readable-stream@3.6.0
24 silly currentTree +-- redis-commands@1.7.0
24 silly currentTree +-- redis-parser@2.6.0
24 silly currentTree +-- redis@2.8.0
24 silly currentTree +-- require_optional@1.0.1
24 silly currentTree +-- requires-port@1.0.0
24 silly currentTree +-- resolve-from@2.0.0
24 silly currentTree +-- rimraf@2.4.5
24 silly currentTree | `-- glob@6.0.4
24 silly currentTree +-- rootpath@0.1.2
24 silly currentTree +-- safe-buffer@5.1.2
24 silly currentTree +-- safe-json-stringify@1.2.0
24 silly currentTree +-- safer-buffer@2.1.2
24 silly currentTree +-- saslprep@1.0.3
24 silly currentTree +-- scmp@2.1.0
24 silly currentTree +-- semver@5.7.1
24 silly currentTree +-- send@0.17.1
24 silly currentTree | `-- ms@2.1.1
24 silly currentTree +-- serve-static@1.14.1
24 silly currentTree +-- setprototypeof@1.1.1
24 silly currentTree +-- source-map@0.6.1
24 silly currentTree +-- sparse-bitfield@3.0.3
24 silly currentTree +-- ssh2-streams@0.4.10
24 silly currentTree +-- ssh2@0.8.9
24 silly currentTree +-- statuses@1.5.0
24 silly currentTree +-- streamsearch@0.1.2
24 silly currentTree +-- string_decoder@1.1.1
24 silly currentTree +-- tar-stream@2.2.0
24 silly currentTree +-- thirty-two@1.0.2
24 silly currentTree +-- toidentifier@1.0.0
24 silly currentTree +-- tsscmp@1.0.6
24 silly currentTree +-- tweetnacl@0.14.5
24 silly currentTree +-- twilio@3.57.0
24 silly currentTree | `-- qs@6.9.6
24 silly currentTree +-- type-is@1.6.18
24 silly currentTree +-- uglify-js@3.13.0
24 silly currentTree +-- uid-safe@2.1.5
24 silly currentTree +-- underscore@1.4.4
24 silly currentTree +-- unpipe@1.0.0
24 silly currentTree +-- url-parse@1.5.1
24 silly currentTree +-- urlsafe-base64@1.0.0
24 silly currentTree +-- util-deprecate@1.0.2
24 silly currentTree +-- utils-merge@1.0.1
24 silly currentTree +-- vary@1.1.2
24 silly currentTree +-- weak-daemon@1.0.3
24 silly currentTree +-- weak-map@1.0.5
24 silly currentTree +-- web-push@3.4.4
24 silly currentTree | +-- jwa@2.0.0
24 silly currentTree | `-- jws@4.0.0
24 silly currentTree +-- wordwrap@1.0.0
24 silly currentTree +-- wrappy@1.0.2
24 silly currentTree +-- ws@6.2.1
24 silly currentTree +-- xml@0.0.12
24 silly currentTree +-- xmlbuilder@13.0.2
24 silly currentTree +-- xmldom@0.1.31
24 silly currentTree +-- yauzl@2.10.0
24 silly currentTree `-- zip-stream@3.0.1
25 silly idealTree M-ACCESS
25 silly idealTree +-- accepts@1.3.7
25 silly idealTree +-- agent-base@6.0.2
25 silly idealTree | +-- debug@4.3.1
25 silly idealTree | `-- ms@2.1.2
25 silly idealTree +-- archiver-utils@2.1.0
25 silly idealTree | `-- readable-stream@2.3.7
25 silly idealTree +-- archiver@4.0.2
25 silly idealTree | `-- async@3.2.0
25 silly idealTree +-- array-flatten@1.1.1
25 silly idealTree +-- asap@2.0.6
25 silly idealTree +-- asn1.js@5.4.1
25 silly idealTree +-- asn1@0.2.4
25 silly idealTree +-- async-limiter@1.0.1
25 silly idealTree +-- async@0.2.10
25 silly idealTree +-- axios@0.21.1
25 silly idealTree +-- balanced-match@1.0.0
25 silly idealTree +-- base64-js@1.5.1
25 silly idealTree +-- bcrypt-pbkdf@1.0.2
25 silly idealTree +-- bignumber.js@9.0.1
25 silly idealTree +-- binary-search-tree@0.2.5
25 silly idealTree +-- bl@4.1.0
25 silly idealTree | `-- inherits@2.0.4
25 silly idealTree +-- bn.js@4.12.0
25 silly idealTree +-- body-parser@1.19.0
25 silly idealTree +-- brace-expansion@1.1.11
25 silly idealTree +-- bson@1.1.5
25 silly idealTree +-- buffer-crc32@0.2.13
25 silly idealTree +-- buffer-equal-constant-time@1.0.1
25 silly idealTree +-- buffer@5.7.1
25 silly idealTree +-- bunyan@1.8.15
25 silly idealTree +-- bytes@3.1.0
25 silly idealTree +-- call-bind@1.0.2
25 silly idealTree +-- cbor@5.2.0
25 silly idealTree +-- compress-commons@3.0.0
25 silly idealTree | `-- readable-stream@2.3.7
25 silly idealTree +-- compressible@2.0.18
25 silly idealTree +-- compression@1.7.4
25 silly idealTree | `-- bytes@3.0.0
25 silly idealTree +-- concat-map@0.0.1
25 silly idealTree +-- connect-redis@3.4.2
25 silly idealTree | +-- debug@4.3.1
25 silly idealTree | `-- ms@2.1.2
25 silly idealTree +-- content-disposition@0.5.3
25 silly idealTree +-- content-type@1.0.4
25 silly idealTree +-- cookie-session@2.0.0-rc.1
25 silly idealTree | +-- debug@3.2.6
25 silly idealTree | +-- ms@2.1.3
25 silly idealTree | `-- safe-buffer@5.2.0
25 silly idealTree +-- cookie-signature@1.0.6
25 silly idealTree +-- cookie@0.4.0
25 silly idealTree +-- cookies@0.8.0
25 silly idealTree | `-- depd@2.0.0
25 silly idealTree +-- core-util-is@1.0.2
25 silly idealTree +-- crc@3.8.0
25 silly idealTree +-- crc32-stream@3.0.1
25 silly idealTree +-- dayjs@1.10.4
25 silly idealTree +-- debug@2.6.9
25 silly idealTree +-- define-properties@1.1.3
25 silly idealTree +-- denque@1.5.0
25 silly idealTree +-- depd@1.1.2
25 silly idealTree +-- destroy@1.0.4
25 silly idealTree +-- double-ended-queue@2.1.0-0
25 silly idealTree +-- dtrace-provider@0.8.8
25 silly idealTree +-- ecdsa-sig-formatter@1.0.11
25 silly idealTree +-- ee-first@1.1.1
25 silly idealTree +-- encodeurl@1.0.2
25 silly idealTree +-- end-of-stream@1.4.4
25 silly idealTree +-- escape-html@1.0.3
25 silly idealTree +-- etag@1.8.1
25 silly idealTree +-- express-handlebars@3.1.0
25 silly idealTree +-- express-ws@4.0.0
25 silly idealTree | `-- ws@5.2.2
25 silly idealTree +-- express@4.17.1
25 silly idealTree +-- fd-slicer@1.1.0
25 silly idealTree +-- finalhandler@1.1.2
25 silly idealTree +-- follow-redirects@1.13.3
25 silly idealTree +-- forwarded@0.1.2
25 silly idealTree +-- fresh@0.5.2
25 silly idealTree +-- fs-constants@1.0.0
25 silly idealTree +-- fs.realpath@1.0.0
25 silly idealTree +-- function-bind@1.1.1
25 silly idealTree +-- get-intrinsic@1.1.1
25 silly idealTree +-- glob@7.1.6
25 silly idealTree +-- graceful-fs@4.2.6
25 silly idealTree +-- handlebars@4.7.7
25 silly idealTree +-- has-symbols@1.0.2
25 silly idealTree +-- has@1.0.3
25 silly idealTree +-- http_ece@1.1.0
25 silly idealTree +-- http-errors@1.7.2
25 silly idealTree +-- https-proxy-agent@5.0.0
25 silly idealTree | +-- debug@4.3.1
25 silly idealTree | `-- ms@2.1.2
25 silly idealTree +-- iconv-lite@0.4.24
25 silly idealTree +-- ieee754@1.2.1
25 silly idealTree +-- image-size@0.9.4
25 silly idealTree +-- immediate@3.0.6
25 silly idealTree +-- inflight@1.0.6
25 silly idealTree +-- inherits@2.0.3
25 silly idealTree +-- ipaddr.js@1.9.1
25 silly idealTree +-- ipcheck@0.1.0
25 silly idealTree +-- isarray@1.0.0
25 silly idealTree +-- jsonwebtoken@8.5.1
25 silly idealTree | `-- ms@2.1.3
25 silly idealTree +-- jwa@1.4.1
25 silly idealTree +-- jws@3.2.2
25 silly idealTree +-- keygrip@1.1.0
25 silly idealTree +-- lazystream@1.0.0
25 silly idealTree | `-- readable-stream@2.3.7
25 silly idealTree +-- lie@3.1.1
25 silly idealTree +-- loadavg-windows@1.1.1
25 silly idealTree +-- localforage@1.9.0
25 silly idealTree +-- lodash.defaults@4.2.0
25 silly idealTree +-- lodash.difference@4.5.0
25 silly idealTree +-- lodash.flatten@4.4.0
25 silly idealTree +-- lodash.includes@4.3.0
25 silly idealTree +-- lodash.isboolean@3.0.3
25 silly idealTree +-- lodash.isinteger@4.0.4
25 silly idealTree +-- lodash.isnumber@3.0.3
25 silly idealTree +-- lodash.isplainobject@4.0.6
25 silly idealTree +-- lodash.isstring@4.0.1
25 silly idealTree +-- lodash.once@4.1.1
25 silly idealTree +-- lodash.union@4.6.0
25 silly idealTree +-- lodash@4.17.21
25 silly idealTree +-- media-typer@0.3.0
25 silly idealTree +-- memory-pager@1.5.0
25 silly idealTree +-- merge-descriptors@1.0.1
25 silly idealTree +-- meshcentral@0.8.31
25 silly idealTree | `-- xmldom@0.5.0
25 silly idealTree +-- methods@1.1.2
25 silly idealTree +-- mime-db@1.46.0
25 silly idealTree +-- mime-types@2.1.29
25 silly idealTree +-- mime@1.6.0
25 silly idealTree +-- minimalistic-assert@1.0.1
25 silly idealTree +-- minimatch@3.0.4
25 silly idealTree +-- minimist@1.2.5
25 silly idealTree +-- mkdirp@0.5.5
25 silly idealTree +-- moment@2.29.1
25 silly idealTree +-- mongodb@3.6.4
25 silly idealTree | +-- bl@2.2.1
25 silly idealTree | `-- readable-stream@2.3.7
25 silly idealTree +-- ms@2.0.0
25 silly idealTree +-- multiparty@4.2.2
25 silly idealTree | +-- http-errors@1.8.0
25 silly idealTree | +-- inherits@2.0.4
25 silly idealTree | +-- safe-buffer@5.2.1
25 silly idealTree | `-- setprototypeof@1.2.0
25 silly idealTree +-- mv@2.1.1
25 silly idealTree +-- nan@2.14.2
25 silly idealTree +-- ncp@2.0.0
25 silly idealTree +-- nedb@1.8.0
25 silly idealTree +-- negotiator@0.6.2
25 silly idealTree +-- neo-async@2.6.2
25 silly idealTree +-- node-forge@0.10.0
25 silly idealTree +-- node-rdpjs-2@0.3.5
25 silly idealTree +-- node-windows@1.0.0-beta.5
25 silly idealTree +-- nodemailer@6.5.0
25 silly idealTree +-- nofilter@1.0.4
25 silly idealTree +-- normalize-path@3.0.0
25 silly idealTree +-- object-keys@1.1.1
25 silly idealTree +-- object.assign@4.1.2
25 silly idealTree +-- on-finished@2.3.0
25 silly idealTree +-- on-headers@1.0.2
25 silly idealTree +-- once@1.4.0
25 silly idealTree +-- optimist@0.6.1
25 silly idealTree | +-- minimist@0.0.10
25 silly idealTree | `-- wordwrap@0.0.3
25 silly idealTree +-- otplib@10.2.3
25 silly idealTree +-- parseurl@1.3.3
25 silly idealTree +-- path-is-absolute@1.0.1
25 silly idealTree +-- path-to-regexp@0.1.7
25 silly idealTree +-- pend@1.2.0
25 silly idealTree +-- pop-iterate@1.0.1
25 silly idealTree +-- process-nextick-args@2.0.1
25 silly idealTree +-- promise@8.1.0
25 silly idealTree +-- proxy-addr@2.0.6
25 silly idealTree +-- q@2.0.3
25 silly idealTree +-- qs@6.7.0
25 silly idealTree +-- querystringify@2.2.0
25 silly idealTree +-- queue@6.0.1
25 silly idealTree +-- random-bytes@1.0.0
25 silly idealTree +-- range-parser@1.2.1
25 silly idealTree +-- raw-body@2.4.0
25 silly idealTree +-- readable-stream@3.6.0
25 silly idealTree +-- redis-commands@1.7.0
25 silly idealTree +-- redis-parser@2.6.0
25 silly idealTree +-- redis@2.8.0
25 silly idealTree +-- require_optional@1.0.1
25 silly idealTree +-- requires-port@1.0.0
25 silly idealTree +-- resolve-from@2.0.0
25 silly idealTree +-- rimraf@2.4.5
25 silly idealTree | `-- glob@6.0.4
25 silly idealTree +-- rootpath@0.1.2
25 silly idealTree +-- safe-buffer@5.1.2
25 silly idealTree +-- safe-json-stringify@1.2.0
25 silly idealTree +-- safer-buffer@2.1.2
25 silly idealTree +-- saslprep@1.0.3
25 silly idealTree +-- scmp@2.1.0
25 silly idealTree +-- semver@5.7.1
25 silly idealTree +-- send@0.17.1
25 silly idealTree | `-- ms@2.1.1
25 silly idealTree +-- serve-static@1.14.1
25 silly idealTree +-- setprototypeof@1.1.1
25 silly idealTree +-- source-map@0.6.1
25 silly idealTree +-- sparse-bitfield@3.0.3
25 silly idealTree +-- ssh2-streams@0.4.10
25 silly idealTree +-- ssh2@0.8.9
25 silly idealTree +-- statuses@1.5.0
25 silly idealTree +-- streamsearch@0.1.2
25 silly idealTree +-- string_decoder@1.1.1
25 silly idealTree +-- tar-stream@2.2.0
25 silly idealTree +-- thirty-two@1.0.2
25 silly idealTree +-- toidentifier@1.0.0
25 silly idealTree +-- tsscmp@1.0.6
25 silly idealTree +-- tweetnacl@0.14.5
25 silly idealTree +-- twilio@3.57.0
25 silly idealTree | `-- qs@6.9.6
25 silly idealTree +-- type-is@1.6.18
25 silly idealTree +-- uglify-js@3.13.0
25 silly idealTree +-- uid-safe@2.1.5
25 silly idealTree +-- underscore@1.4.4
25 silly idealTree +-- unpipe@1.0.0
25 silly idealTree +-- url-parse@1.5.1
25 silly idealTree +-- urlsafe-base64@1.0.0
25 silly idealTree +-- util-deprecate@1.0.2
25 silly idealTree +-- utils-merge@1.0.1
25 silly idealTree +-- vary@1.1.2
25 silly idealTree +-- weak-daemon@1.0.3
25 silly idealTree +-- weak-map@1.0.5
25 silly idealTree +-- web-push@3.4.4
25 silly idealTree | +-- jwa@2.0.0
25 silly idealTree | `-- jws@4.0.0
25 silly idealTree +-- wordwrap@1.0.0
25 silly idealTree +-- wrappy@1.0.2
25 silly idealTree +-- ws@6.2.1
25 silly idealTree +-- xml@0.0.12
25 silly idealTree +-- xmlbuilder@13.0.2
25 silly idealTree +-- xmldom@0.1.31
25 silly idealTree +-- yauzl@2.10.0
25 silly idealTree `-- zip-stream@3.0.1
26 silly install generateActionsToTake
27 timing stage:generateActionsToTake Completed in 46ms
28 silly diffTrees action count 1
29 silly diffTrees update meshcentral@0.8.31
30 silly decomposeActions action count 10
31 silly decomposeActions unbuild meshcentral@0.8.29
32 silly decomposeActions remove meshcentral@0.8.29
33 silly decomposeActions fetch meshcentral@0.8.31
34 silly decomposeActions extract meshcentral@0.8.31
35 silly decomposeActions preinstall meshcentral@0.8.31
36 silly decomposeActions build meshcentral@0.8.31
37 silly decomposeActions install meshcentral@0.8.31
38 silly decomposeActions postinstall meshcentral@0.8.31
39 silly decomposeActions finalize meshcentral@0.8.31
40 silly decomposeActions refresh-package-json meshcentral@0.8.31
41 silly install executeActions
42 silly doSerial global-install 10
43 verbose correctMkdir C:\Users\Administrator\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
44 verbose makeCacheDir UID & GID are irrelevant on win32
45 verbose lock using C:\Users\Administrator\AppData\Roaming\npm-cache\_locks\staging-2b2563fd7c1c5028.lock for C:\M-ACCESS\node_modules\.staging
46 silly doParallel extract 1
47 silly extract meshcentral@0.8.31
48 silly tarball trying meshcentral@0.8.31 by hash: sha512-0e7k987zOC1HOYInrYFNuA+CikrTQIQHF0LFglPVMYncbnKv1jxnt9UDdVwpPHc72sGuZFNt8qCIG5I/P7uMOQ==
49 timing audit submit Completed in 509ms
50 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 508ms
51 timing audit body Completed in 2ms
52 warn tar EPERM: operation not permitted, open 'C:\M-ACCESS\node_modules\.staging\meshcentral-8795b2ca\agents\MeshService64.exe'
53 timing npm Completed in 6466ms
54 error cb() never called!
55 error This is an error with npm itself. Please report this error at:
56 error <https://npm.community>
______________________________________________________________
### Expected Behavior:

The application must upgrade to latest version

**Comment by ljharb** [comment]
See #417.

Try with npm 7?

**Comment by VINISHVV** [comment]
@ljharb - Thanks.
