### ISSUE TITLE
This is an error with npm itself. Please report this error at:

### ISSUE THREAD

**Issue by NOAHnNAOMI** [npm/cli#3214]
~ $ npm audit fix
npm WARN ancient lockfile
npm WARN ancient lockfile The package-lock.json file was created with an old version of npm,
npm WARN ancient lockfile so supplemental metadata must be fetched from the registry.
npm WARN ancient lockfile
npm WARN ancient lockfile This is a one-time fix-up, please be patient...
npm WARN ancient lockfile
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2021-05-09T13_11_32_579Z-debug.log

**Comment by ljharb** [comment]
#417
