### ISSUE TITLE
[BUG] `--registry` support for custom init modules

### ISSUE THREAD

**Issue by hemanth** [npm/cli#3226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Need support to registry support for `npm init` and `npx`

```sh
npm init --registry=https://registry.npmjs.org/ <module>
```

Say from example:

```sh
$ npm init --registry=https://registry.npmjs.org/ <module>
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to https://npm.example.com/create-slidev failed, reason: getaddrinfo ENOTFOUND npm.example.com npm.example.com:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
Install for <module>@latest failed with code 1
```

### Expected Behavior

Should respect `--registry` like `npm install` does.

### Steps To Reproduce

Any env and any config

### Environment

- OS: Darwin
- Node: v16.0.0
- npm: 7.6.3

**Comment by hemanth** [comment]
Created a [RFC](https://github.com/npm/rfcs/issues/378) hence closing this.

**Comment by isaacs** [comment]
https://github.com/npm/rfcs/issues/378#issuecomment-843379483

Bug: the error message does not clarify that a proxy is set when failing to reach the registry.

In this case, a proxy is set, so even when doing `--registry=https://registry.npmjs.org/`, it'll fail with a message being unable to reach the proxy.

**Comment by hemanth** [comment]
I can work on making the enhancements for this [case](https://github.com/npm/cli/blob/a4e7f4e4b40d645fed97622a97c7fa72aa5da82b/lib/utils/error-message.js#L37) to add proxy info, if that makes sense.

**Comment by isaacs** [comment]
@hemanth That would probably be the best solution here.  Thanks!
