### ISSUE TITLE
not able to create ReactJS Project in Windows 10

### ISSUE THREAD

**Issue by ariticAli** [npm/cli#3232]
I am facing these issues

"
Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SyedHussain\AppData\Local\npm-cache\_logs\2021-05-11T20_09_23_802Z-debug.log

Aborting installation.
  npm install --save --save-exact --loglevel error react react-dom react-scripts cra-template has failed.
"

regards

**Comment by ljharb** [comment]
#417, and please fill out the issue template.

**Comment by ariticAli** [comment]
where to fill?

**Comment by ljharb** [comment]
When you create a new issue, there's initial text in the box for you to fill out if you file a bug with npm 7.

If you selected "file a blank issue", then there wouldn't be one, but this firmly seems like one of the first two options on https://github.com/npm/cli/issues/new/choose

**Comment by ariticAli** [comment]
thanks I got it.
