### ISSUE TITLE
[BUG] Can't install repository "unsupported option "accept-new"."

### ISSUE THREAD

**Issue by riccardomessineo** [npm/cli#3233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm not able to install private npm dependencies that are used inside my package.json.

```
npm ERR! command git --no-replace-objects ls-remote ssh://git@gitserver.com/foo/bar.git
npm ERR! command-line line 0: unsupported option "accept-new".
npm ERR! fatal: Could not read from remote repository.
```

I thought wasn't related to npm cli, but:
1. I can successfully clone the repo on the same machine using ssh
2. yarn install works fine

Openssh version is 7.4p1-21.el7.

Is this a known problem?
Thanks

### Expected Behavior

A successful install

### Environment

- OS: Centos 7
- Node: 14.17.0
- npm: 7.12.1

**Comment by ljharb** [comment]
What version of git are you using?

**Comment by ljharb** [comment]
Also, what kind of git server are you connecting to?

**Comment by riccardomessineo** [comment]
Git version: 2.24.1
Git server: bitbucket.org

**Comment by riccardomessineo** [comment]
I just tested using NPM version 7.8.0 and it worked fine, upgraded to 7.12.1 and that error shows up...

**Comment by wraithgar** [comment]
This flag was added in this PR https://github.com/npm/git/pull/7 and it outlines the requirements for this flag to work (ssh version is also important).

Your openssh of 7.4 is the cause.

The workaround is:

> this default behavior can be overridden by either of
> - configuring core.sshCommand in your ~/.gitconfig
> - exporting your own value for GIT_SSH_COMMAND

**Comment by wraithgar** [comment]
Copying @riccardomessineo's comment from the other repo to aid in future searching from people with older versions of ssh.

> For future reference, I was struggling with the "accept-new" unsupported option due to this PR.
> To fix it, I've tried to use core.sshCommand in .gitconfig but it was ineffective. Instead, setting the env variable worked fine.
> 
> https://git-scm.com/docs/git-config#Documentation/git-config.txt-coresshCommand
> core.sshCommand
> If this variable is set, git fetch and git push will use the specified command instead of ssh when they need to connect to a remote system. The command is in the same form as the GIT_SSH_COMMAND environment variable and is overridden when the environment variable is set.

**Comment by LeonardDrs** [comment]
https://github.com/npm/git/pull/7 feels more like a BC than a patch. Would it be possible to detect the user `ssh -V` before trying to set `GIT_SSH_COMMAND` or we don't care?

**Comment by joshuawinsor** [comment]
This issue should be re-opened (and pr/7 reverted) as it ignores end users' settings in ~/.ssh/config (the fix for the initial bug is for the end user to update their .ssh/config)

**Comment by serbaniuliuscezar** [comment]
https://issues.jenkins.io/browse/JENKINS-69149

Quote from the ticket: 

> [markroland](https://issues.jenkins.io/secure/ViewProfile.jspa?name=markroland) if the log file contains a reference to accept-new, then this is the issue you're seeing. Use "Manage Jenkins" -> "Configure Global Security" -> "Git Host Key Verification Configuration" to change the configuration from "Accept first connection" to "Known hosts file". No need to downgrade the plugin. No need to restart the Jenkins controller.
> 
> If that setting does not resolve it, then you can switch to "Manually provided keys" and provide the ssh host keys for the ssh servers you use.
> 
> If that setting does not resolve it, then you can switch to "No verification" and accept that you've reintroduced the man in the middle attack vector.
> 
> Another shameless plug from me that you'll have better results if you move to a different operating system as your time and your schedules allow. CentOS 7 is supported but the utilities included in CentOS 7 are very old versions, including command line git 1.8.3.
