### ISSUE TITLE
[BUG]  ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by blogcraft** [npm/cli#3236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Generating a new project throws an error:

```
⠸ Installing packages (npm)...npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: curso-de-angular2@0.0.0
npm ERR! Found: jasmine-core@3.6.0
npm ERR! node_modules/jasmine-core
npm ERR!   dev jasmine-core@"~3.6.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer jasmine-core@">=3.7.1" from karma-jasmine-html-reporter@1.6.0
npm ERR! node_modules/karma-jasmine-html-reporter
npm ERR!   dev karma-jasmine-html-reporter@"^1.5.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\blog_\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\blog_\AppData\Local\npm-cache\_logs\2021-05-12T19_12_21_362Z-debug.log
✖ Package install failed, see above.
The Schematic workflow failed. See above.
```

### Expected Behavior

Execute `ng new test-app` and the project will be created and dependencies correctly installed.

### Steps To Reproduce

1. Installed Node 16.1.0
2. Run `npm install -g @angular/cli`
3. Run `ng new test-app`
4. See error `npm ERR! ERESOLVE unable to resolve dependency tree`

### Environment

- OS: Windows 10 Pro 20H2
- Node: 16.1.0
- npm: 7.11.2

**Comment by redevill** [comment]
I have a real problem with the layout and language used in the error message.
"Conflict" happens between 2 entities. The word is used in the error, but it does NOT CLEARLY state between which 2 entities this conflict exists.

If it stated:
The Peer dependency of jasmine-core@">=3.7.1" from karma-jasmine-html-reporter@1.6.0 is in conflict with the jasmine-core@"~3.6.0" from the root project - It would be SO much clearer.

The workaround for the case above is then to "npm install" "jasmine-core@"~3.7.1" into root project

**Comment by redevill** [comment]
Another example:

npm ERR! Could not resolve dependency:
npm ERR! @angular/fire@"^6.1.4" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @angular/platform-browser-dynamic@11.2.13
npm ERR! node_modules/@angular/platform-browser-dynamic
npm ERR!   @angular/platform-browser-dynamic@"^11.2.13" from the root project
npm ERR!   peer @angular/platform-browser-dynamic@"^9.0.0 || ^10.0.0 || ^11.0.0" from @angular/fire@6.1.4
npm ERR!   node_modules/@angular/fire
npm ERR!     @angular/fire@"^6.1.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

In this case - the Error indicates that the peer needs to be either ^9 or ^10 or ^11 with any minor or revision numbers.
Why then is 11.2.13 a conflicting ?!?! dependency?

**Comment by nicolasalarconrapela** [comment]
The same happens to me : 

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: projectTest@1.0.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0 || ^16.0.0" from @shakacode/recompose@0.30.3
npm ERR! node_modules/@shakacode/recompose
npm ERR!   @shakacode/recompose@"^0.30.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.     
npm ERR! 
npm ERR! See C:\Users\<User>\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<User>\AppData\Local\npm-cache\_logs\2021-05-14T06_49_18_630Z-debug.log
```

OS: Windows10 Home
Node: 14.15.0
npm: 7.12.1

**Comment by redevill** [comment]
@nicolasalarconrapela - In your case the peer of @shakacode/recompose@0.30.3 requires a version of react that is less than the 17.0.2 you have in your root.

I would suggest downgrading the react library to a version 16...

Or - Workaround might be to use yarn or the --legacy-peer-deps switch

**Comment by redevill** [comment]
HHHmmmm - my mistake, that tool does not show peerDependencies.
The Library https://www.npmjs.com/package/@shakacode/recompose does not show any peer dependencies either.
I could only find this dependency in the package.json of the installed library :( 
Here is another way peers can be found - 
npm info name-of-module peerDependencies

**Comment by ljharb** [comment]
@blogcraft your issue is that your project pins jasmine to the minor version 3.6, but karma-jasmine-html-reporter requires 3.7.1 or higher. Upgrade jasmine in your own project.

@nicolasalarconrapela your problem is that you’re using a version of shakacode/recompose that does not work with react 17. Downgrade to react 16, upgrade shakacode/recompose, or stop using recompose.

@redevill my guess is that you’re not on the latest npm 7. What version do you have?

**Comment by redevill** [comment]
@ljharb - You are correct, a little behind (including a release 5hours ago) Npm Version 7.11.1
I'll update and check.

**Comment by darcyclarke** [comment]
Closing: seems to be project-specific issues that can be resolved by using either `--force` or `--legacy-peer-deps` if you want to keep conflicts in your peer deps. @ljharb gave some good recommendations; You can also use `npm explain` to understand more about why certain deps are being placed in your project/where.
