### ISSUE TITLE
[BUG] npm version `--force` option is not implemented

### ISSUE THREAD

**Issue by j-m** [npm/cli#3238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The `force` option does nothing.  

I'm trying to version a package using a git tag but, because Azure adds credentials to my `.npmrc`, `npm version` complains that my working directory is not clean.  

*Re searching existing issues, I found https://github.com/npm/npm/issues/17926 

### Expected Behavior

To be able to use `npm version` with the `--force` option so I can change the package version even when the working directory is dirty.   

### Steps To Reproduce

1. With a git repository that has at least 1 commit and tag
2. With any valid package.json
4. With any unstaged changes
3. Run `npm version from-git --no-git-tag-version --force`
4. With npm 5 or 6 see error
```
npm WARN using --force I sure hope you know what you are doing.
npm ERR! Git working directory not clean.
npm ERR! M README.md
``` 
With npm 7 see error
```
npm WARN using --force Recommended protections disabled.
npm ERR! code 128
npm ERR! command failed
npm ERR! command C:\Program Files\Git\cmd\git.EXE --no-replace-objects describe --tags --abbrev=0 --match='*.*.*'
npm ERR! fatal: No names found, cannot describe anything.
```
(running `git --no-replace-objects describe --tags --abbrev=0 --match='*.*.*'` manually returns `2.0.0`)

### Environment

- OS: Windows
- Node: 14.15.1
- npm: 7.12.1
- npm: 6.14.12

<hr/>

- OS: Ubuntu 20.04
- Node: 14.16.1
- npm: 6.14.12

**Comment by j-m** [comment]
I was wrong, with npm 7, `from-git` doesn't work at all

**Comment by ruyadorno** [comment]
It looks like the `from-git` part of this issue was already implemented, now it seems `npm version` is still missing support to the `--force` option.

**Comment by lukekarrys** [comment]
I'm not sure when this was fixed, but can confirm in the latest right now (npm@10.7.0) `npm version --force` works as expected to allow proceeding when git status is not clean.
