### ISSUE TITLE
[BUG] "npx @wordpress/create-block my-block"

### ISSUE THREAD

**Issue by 57webbee** [npm/cli#3245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Creating a new WordPress block in "fswebbee-my-block8" folder.

Creating a "block.json" file.

Creating a "package.json" file.

Installing npm dependencies. It might take a couple of minutes...

Skipping "@wordpress/block-editor" npm dependency. Reason:
Command failed with exit code 1: npm install @wordpress/block-editor
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

Installing `@wordpress/scripts` package. It might take a couple of minutes...
/home/admintajserveur/.npm/_npx/0890e296436e9575/node_modules/execa/lib/error.js:59
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: npm install @wordpress/scripts --save-dev
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: prettier@2.2.1-beta-1
npm WARN node_modules/prettier
npm WARN   prettier@"npm:wp-prettier@2.2.1-beta-1" from @wordpress/scripts@15.0.1
npm WARN   node_modules/@wordpress/scripts
npm WARN     dev @wordpress/scripts@"*" from the root project
npm WARN   1 more (@wordpress/eslint-plugin)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer prettier@">=1.13.0" from eslint-plugin-prettier@3.4.0
npm WARN node_modules/eslint-plugin-prettier
npm WARN   eslint-plugin-prettier@"^3.3.0" from @wordpress/eslint-plugin@9.0.4
npm WARN   node_modules/@wordpress/eslint-plugin
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>
    at makeError (/home/admintajserveur/.npm/_npx/0890e296436e9575/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/admintajserveur/.npm/_npx/0890e296436e9575/node_modules/execa/index.js:114:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/home/admintajserveur/.npm/_npx/0890e296436e9575/node_modules/@wordpress/create-block/lib/init-wp-scripts.js:19:2)
    at async module.exports (/home/admintajserveur/.npm/_npx/0890e296436e9575/node_modules/@wordpress/create-block/lib/scaffold.js:100:3)
    at async Command.<anonymous> (/home/admintajserveur/.npm/_npx/0890e296436e9575/node_modules/@wordpress/create-block/lib/index.js:91:6) {
  shortMessage: 'Command failed with exit code 1: npm install @wordpress/scripts --save-dev',
  command: 'npm install @wordpress/scripts --save-dev',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'npm WARN ERESOLVE overriding peer dependency\n' +
    'npm WARN Found: prettier@2.2.1-beta-1\n' +
    'npm WARN node_modules/prettier\n' +
    'npm WARN   prettier@"npm:wp-prettier@2.2.1-beta-1" from @wordpress/scripts@15.0.1\n' +
    'npm WARN   node_modules/@wordpress/scripts\n' +
    'npm WARN     dev @wordpress/scripts@"*" from the root project\n' +
    'npm WARN   1 more (@wordpress/eslint-plugin)\n' +
    'npm WARN \n' +
    'npm WARN Could not resolve dependency:\n' +
    'npm WARN peer prettier@">=1.13.0" from eslint-plugin-prettier@3.4.0\n' +
    'npm WARN node_modules/eslint-plugin-prettier\n' +
    'npm WARN   eslint-plugin-prettier@"^3.3.0" from @wordpress/eslint-plugin@9.0.4\n' +
    'npm WARN   node_modules/@wordpress/eslint-plugin\n' +
    'npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime\n' +
    'npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime\n' +
    'npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime\n' +
    'npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime\n' +
    'npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime\n' +
    'npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime\n' +
    'npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime\n' +
    'npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime\n' +
    'npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime\n' +
    'npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime\n' +
    'npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime\n' +
    'npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime\n' +
    'npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime\n' +
    'npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime\n' +
    'npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime\n' +
    'npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime\n' +
    'npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime\n' +
    'npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime\n' +
    'npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime\n' +
    'npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime\n' +
    'npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, futime\n' +
    'npm WARN tar TAR_ENTRY_ERROR EPERM: operation no'... 267154 more characters,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

### Expected Behavior

Creating a new WordPress block in "fswebbee-my-block8" folder.

Creating a "block.json" file.

Creating a "package.json" file.

Installing npm dependencies. It might take a couple of minutes...

Installing `@wordpress/scripts` package. It might take a couple of minutes...

Formatting JavaScript files.

Compiling block.

Done: block "Fswebbee My Block 8" bootstrapped in the "fswebbee-my-block8" folder.

Inside that directory, you can run several commands:

  $ npm start
    Starts the build for development.

  $ npm run build
    Builds the code for production.

  $ npm run format
    Formats files.

  $ npm run lint:css
    Lints CSS files.

  $ npm run lint:js
    Lints JavaScript files.

  $ npm run packages-update
    Updates WordPress packages to the latest version.

To enter the folder type:

  $ cd fswebbee-my-block8

You can start development with:

  $ npm start

Code is Poetry

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- OS: ubuntu 20.04.2 LTS (Focal Fossa)
- Node:  v16.1.0
- npm: 7.11.2
- nvm: 0.38.0

**Comment by ruyadorno** [comment]
hi @57webbee I see multiple errors here and I'm not really sure of what I'm looking at, please in the future split bug reports to individual problems and as much info we can get about the problem, the better it is for us to try to find a solution 😊 

**Closing:** in the future please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).
