### ISSUE TITLE
[BUG] "npm install github:..." creates "git+ssh://" in the lockfile, which breaks GitHub Actions.

### ISSUE THREAD

**Issue by WeeJeWel** [npm/cli#3247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Since NPM v7:

When installing a new dependency from a public repository (`github:foo/bar`), this creates a `git+ssh://git@github.com/foo/bar`) in the `package-lock.json`.

This breaks when running `npm ci` in  a GitHub Action because it doesn't have the SSH agent configured. And it shouldn't need to, because the dependency is public.

### Expected Behavior

Don't put `git+ssh` there but `github:`.

### Steps To Reproduce

`npm i github:foo/bar`

### Environment

- OS: macOS Big Sur
- Node 16
- npm v7.12.1

**Comment by joebowbeer** [comment]
Duplicates #2610?

**Comment by wraithgar** [comment]
Yes this is a duplicate of #2610
