### ISSUE TITLE
`cb()` never called

### ISSUE THREAD

**Issue by toothbrush7777777** [npm/cli#3249]
## Details

I downloaded https://github.com/ColorlibHQ/AdminLTE/archive/refs/tags/v3.1.0.zip, extracted it, opened the extracted directory in VS Code and ran `npm install` from the command line.

## Environment

Windows 10 (20H2, build 19042.985)

`npm --version`: 6.14.4
`node --version`: v14.2.0
Default settings.

## Log (anonymised)
[2021-05-14T16_38_45_134Z-debug.log](https://github.com/npm/cli/files/6480216/2021-05-14T16_38_45_134Z-debug.log)

**Comment by ljharb** [comment]
#417

**Comment by darcyclarke** [comment]
**Closing:** this error can arise for a number of reasons; Please read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F--I'm-having-the-same-problem!%22) & refile an issue with as much information as possible if you're able to **consistently reproduce** this error.
