### ISSUE TITLE
[BUG] npm i and npm audit failing

### ISSUE THREAD

**Issue by swapnilsworld** [npm/cli#3255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

npm audit failing

### Expected Behavior

npm audit should work.

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

D:\Swapnil\Project\angular-bootstrap-demo>npm audit fix
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: angular-bootstrap-demo@0.0.0
npm ERR! Found: @angular/compiler-cli@10.1.6
npm ERR! node_modules/@angular/compiler-cli
npm ERR!   dev @angular/compiler-cli@"~10.1.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/compiler-cli@"^11.0.0" from @angular-devkit/build-angular@0.1100.7
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"^0.1100.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\shh914189\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\shh914189\AppData\Local\npm-cache\_logs\2021-05-17T11_21_44_659Z-debug.log

D:\Swapnil\Project\angular-bootstrap-demo>npm audit fix  --legacy-peer-deps
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\shh914189\AppData\Local\npm-cache\_logs\2021-05-17T11_25_19_150Z-debug.log

### Environment

- OS: 
- Node: 
- npm:

**Comment by wraithgar** [comment]
Can't reproduce this with the information given, please provide more info about how to reproduce this bug if this is still a problem.

Please also read this wiki page for more info: https://github.com/npm/cli/wiki/%22cb()-never-called%3F--I'm-having-the-same-problem!%22
