### ISSUE TITLE
Newman testing tool for calls are failing that have Self Signed Certificates

### ISSUE THREAD

**Issue by wilsondgr8** [npm/cli#3259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Newman calls are failing for those postman calls where we have Token as part of request header.
Postman requests like ( Auth, Resetpassword ) with an Token in request response are giving response with warning for Self Signed Certificates in Postman but able to complete test. But in Newman all those scripts are failing.

Tried using the below commands but its still failing

call newman run %CollectionFile% -e %EnvFile% -g %GlobalFile% -r cli,json,htmlextra --folder=Token1 --insecure -k

call newman run %CollectionFile% -e %EnvFile% -g %GlobalFile% -r cli,json,htmlextra --folder=Token1 --insecure

call newman run %CollectionFile% -e %EnvFile% -g %GlobalFile% -r cli,json,htmlextra --folder=Token1 -k

<img width="491" alt="3da0877c-7314-49c7-961c-9e0316448449" src="https://user-images.githubusercontent.com/54820427/118692069-4e9da680-b7cf-11eb-894c-1bcaede5c2f8.png">
<img width="432" alt="b95daef7-b90f-4b5c-959e-9d4811a9866d" src="https://user-images.githubusercontent.com/54820427/118692104-58270e80-b7cf-11eb-9060-f05f3a550742.png">

### Expected Behavior

Newman calls shouldn't fail for any of the accessToken even after using --insecure flag or -k

### Steps To Reproduce

Called the below commands from the command prompt and ran the batch

call newman run %CollectionFile% -e %EnvFile% -g %GlobalFile% -r cli,json,htmlextra --folder=Token1 --insecure -k
call newman run %CollectionFile% -e %EnvFile% -g %GlobalFile% -r cli,json,htmlextra --folder=Token1 --insecure
call newman run %CollectionFile% -e %EnvFile% -g %GlobalFile% -r cli,json,htmlextra --folder=Token1 -k

### Environment

- OS: Windows 10
- Node: 14.16.0
- npm: 6.14.11 and also 7

**Comment by shadowspawn** [comment]
This looks like an issue with `newman` rather than with the `npm` CLI?

**Comment by wraithgar** [comment]
This does not appear to be an npm bug.
