### ISSUE TITLE
[BUG] unsupported engine yet installed

### ISSUE THREAD

**Issue by balane** [npm/cli#3263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/architect@0.1200.0',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     node: '^12.14.1 || ^14.0.0',
npm WARN EBADENGINE     npm: '^6.11.0 || ^7.5.6',
npm WARN EBADENGINE     yarn: '>= 1.13.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v16.1.0', npm: '7.13.0' }
npm WARN EBADENGINE }

### Expected Behavior

Shouldn't get warning messages

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- OS: Windows 10
- Node: 16.1.0
- npm: 7.13.0

**Comment by balane** [comment]
There was an existing issue (#2728) for this but it was closed.

**Comment by wraithgar** [comment]
By default the engines field is only a WARN.

If you want this to result in a failure you need to configure engines-strict flag to true.
