### ISSUE TITLE
[BUG] npm install does not install correct versions when upgrading from npm 6 to 7

### ISSUE THREAD

**Issue by denis-sokolov** [npm/cli#3269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running npm install does not install correct versions of dependencies in place of the existing old versions if the lockfile includes a version change in addition to dependency version upgrades. See reproduction for more details.

Related or possibly a duplicate of: #3057, #3196.

### Expected Behavior

After running npm install, the dependencies in node_modules should match the lockfile contents.

### Steps To Reproduce

1. `git clone git@github.com:denis-sokolov/npm-6-to-7-old-dependency-reproduction.git && cd npm-6-to-7-old-dependency-reproduction`
2. `git checkout base`
3. `npm6 install` (I used 6.14.9)
4. `git checkout master`
5. `npm7 install` (I used 7.11.2)
6. `cat node_modules/\@types/react-select/package.json  | grep 'version":'`

Observed:
>   "version": "3.0.22"

Expected:
>   "version": "4.0.15",

Workaround: `rm -rf node_modules && npm install`.

If reproduction fails, please see the `with-node-modules` branch that has node_modules included in the repository.

### Environment

- OS: macOS 11.3.1
- Node: 14.14.0
- npm: 7.11.2, also reproduced with 7.13.0

**Comment by tobiu** [comment]
I am experiencing something similar:
npm -v => 7.14.0

Published a new version of neo.mjs (e.g. v2.1.4).

Wanted to update the gh-pages repo:
https://github.com/neomjs/pages

changed the dependency to "^2.1.4".
npm install

=> it re-installs 2.1.3 and finishes with exit code 0.

I need to delete the node_modules folder as well as the package-lock.json to make it work. This affects several other repos inside the neomjs namespace as well.

**Comment by ruyadorno** [comment]
It looks like this has already been fixed along with the two other related issues originally linked by @denis-sokolov.

Feel free to open a new issue in case you run into a similar problem again. Thanks for the help!
