### ISSUE TITLE
[BUG] npx is not working.

### ISSUE THREAD

**Issue by shivam-0510-zz** [npm/cli#3270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever I create a react app using npx it shows error.
error cb() never called!
error This is an error with npm itself.

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- OS: Windows
- Node: 16.2.0
- npm: 7.13.0

**Comment by ljharb** [comment]
#417

**Comment by shivam-0510-zz** [comment]
Thanks @ljharb for linking this.

**Comment by nlf** [comment]
**Closing:** this error can arise for a number of reasons; Please read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F--I'm-having-the-same-problem!%22) & refile an issue with as much information as possible if you're able to **consistently reproduce** this error.
