### ISSUE TITLE
[BUG] npm v7 global install doesn't symlink bin path for packages from self-hosted gitlab npm registry

### ISSUE THREAD

**Issue by jwandrews** [npm/cli#3274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to install a global package from a self-hosted GitLab NPM registry, the bin symlink is not created for the `"bin"` option in `package.json` for the installed package.

Given that `@custom-scope` is configured to point to a custom registry at `self-hosted-gitlab.example.com`.

`npm i -g @<custom-scope>/<package-name>`, should result in:
- Package installed at `$(npm config get prefix)/lib` (this part works)
- No symlink found in `$(npm config get prefix)/bin/<package-bin-name>`

**Note:** this only stopped working in npm v7. npm v6 installs this global package correctly.

### Expected Behavior

Expected global package bin to be symlinked properly in `$(npm config get prefix)/bin`

### Steps To Reproduce

1. Have a custom scope point to a self-hosted gitlab npm registry.
2. Have a package hosted there with a `"bin"` config in `package.json`
3. Try to install that scoped package globally.
4. Symlink for global bin not present.

### Environment

- OS: macOS 11.3.1
- Node: 14.17.0
- npm: 7.13.0

**Comment by nlf** [comment]
this is due to a bug in gitlab itself, the issue is filed here https://gitlab.com/gitlab-org/gitlab/-/issues/275992

**Comment by jwandrews** [comment]
@nlf thank you for that info!
