### ISSUE TITLE
Aborting installation.    react-scripts cra-template has failed.

### ISSUE THREAD

**Issue by JavierPons** [npm/cli#3279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Im running create-react-app + app name

start to run and crash. Sometimes works well but now on day each second time I try to create a react app crash. Here is the log:

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

Aborting installation.
  npm install --save --save-exact --loglevel error react react-dom react-scripts cra-template has failed.

Deleting generated file... node_modules
(node:48627) UnhandledPromiseRejectionWarning: Error: ENFILE: file table overflow, scandir '/Users/myroot/path/simplecustomhook/complexcustom/node_modules/.staging/@babel/plugin-syntax-top-level-await-8a096bf0'
    at Object.readdirSync (fs.js:1021:3)
    at rmkidsSync (/usr/local/lib/node_modules/create-react-app/node_modules/fs-extra/lib/remove/rimraf.js:291:11)
    at rmdirSync (/usr/local/lib/node_modules/create-react-app/node_modules/fs-extra/lib/remove/rimraf.js:281:7)
    at rimrafSync (/usr/local/lib/node_modules/create-react-app/node_modules/fs-extra/lib/remove/rimraf.js:252:7)
    at /usr/local/lib/node_modules/create-react-app/node_modules/fs-extra/lib/remove/rimraf.js:291:39
    at Array.forEach (<anonymous>)
    at rmkidsSync (/usr/local/lib/node_modules/create-react-app/node_modules/fs-extra/lib/remove/rimraf.js:291:26)
    at rmdirSync (/usr/local/lib/node_modules/create-react-app/node_modules/fs-extra/lib/remove/rimraf.js:281:7)
    at rimrafSync (/usr/local/lib/node_modules/create-react-app/node_modules/fs-extra/lib/remove/rimraf.js:252:7)
    at /usr/local/lib/node_modules/create-react-app/node_modules/fs-extra/lib/remove/rimraf.js:291:39
(Use `node --trace-warnings ...` to show where the warning was created)
(node:48627) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:48627) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Expected Behavior

Create a basic React App.

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- OS: macOS Catalina v. 10.15.6
- Node: 14.16.1
- npm: 6.14.12

**Comment by itshoax** [comment]
I am getting the same error

**Comment by JavierPons** [comment]
I updated npm to the last version  7.14.0. For me now  it works. That resolve the problem. I created three react app one after another and everything works well.

**Comment by c0derdx** [comment]
Even after updating it..
It shows the following..
Creating a new React app in C:\Users\LUC1F3R\Desktop\book-store\book.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\LUC1F3R\AppData\Local\npm-cache\_logs\2021-05-21T08_57_52_900Z-debug.log

Aborting installation.
  npm install --save --save-exact --loglevel error react react-dom react-scripts cra-template has failed.

Deleting generated file... node_modules
Deleting generated file... package.json
Deleting book/ from C:\Users\LUC1F3R\Desktop\book-store
Done.
