### ISSUE TITLE
[BUG] npm install removes peer dependency

### ISSUE THREAD

**Issue by JoshMcCullough** [npm/cli#3280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`npm i --save ...` removes related peer dependency.

### Expected Behavior

`npm i --save ...` does not remove peer dependencies.

### Steps To Reproduce

Existing package.json:

```json
  "dependencies": {
    "@my-org/my-pkg": "^1.0.0"
  },
  "peerDependencies": {
    "@my-org/my-pkg": "^1.0.0",
    "some-other-pkg": "^2.3.4"
  }
```

Running `npm i --save @my-org/my-pkg@1.0.1` results in the following package.json:

```json
  "dependencies": {
    "@my-org/my-pkg": "^1.0.1"
  },
  "peerDependencies": {
    "some-other-pkg": "^2.3.4"
  }
```

Note that the peer dependency `"@my-org/my-pkg": "^1.0.1"` was removed during install.

### Environment

- OS: Manjaro 21.0.5
- Node: 12.19.1
- npm: 7.14.0

**Comment by ruyadorno** [comment]
This is working as intended, starting with version 7 **npm** tracks peer dependencies as a first class dependency type and as such will avoid duplication when finding multiple entries of the same dep in `package.json`.

**Comment by JoshMcCullough** [comment]
@ruyadorno But shouldn't it leave the dupe in the `peerDependencies` rather than `dependencies`?
