### ISSUE TITLE
[BUG] Failed to run "npm install"

### ISSUE THREAD

**Issue by Im-Fran** [npm/cli#3286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm running `npm i` on my project and I get the following error:
```
npm ERR! Cannot read property 'name' of null

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-22T03_38_31_354Z-debug.log
```

### Expected Behavior

Install the dependencies after I run `npm i`

### Steps To Reproduce

1. Use the attached settings
2. Run `npm i`
3. See the error

### Environment

- OS: Ubuntu 18.04.5 LTS
- Node: 14.0.0 
- npm: 7.14.0

Debug Log: [2021-05-22T03_38_31_354Z-debug.log](https://github.com/npm/cli/files/6525738/2021-05-22T03_38_31_354Z-debug.log)
[Package and Package lock](https://github.com/npm/cli/files/6525744/Archive.zip)

**Comment by ljharb** [comment]
Your package.json is missing a `name` and `version` field.

**Comment by Im-Fran** [comment]
I've never used that, the settings are from a laravel project. If you take a look into [their project](https://github.com/laravel/laravel/blob/8.x/package.json) you'll see that they don't use those variables

**Comment by Im-Fran** [comment]
I'm just going to migrate to the latest version of Laravel. Sorry if someone had the same problem but I couldn't find any other solution than updating to the latest version of the framework.
