### ISSUE TITLE
[BUG] npm ERR! cb() never called!

### ISSUE THREAD

**Issue by cozyloon** [npm/cli#3287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

G:\angular-demos\foodDeliveryAdminPanel>npm i
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DELL\AppData\Roaming\npm-cache\_logs\2021-05-22T04_20_22_670Z-debug.log

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- OS: Windows 10
- Node: v14.17.0
- npm: 6.14.13

**Comment by ljharb** [comment]
#417.

**Comment by nlf** [comment]
**Closing:** this error can arise for a number of reasons; Please read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F--I'm-having-the-same-problem!%22) & refile an issue with as much information as possible if you're able to **consistently reproduce** this error.
