### ISSUE TITLE
angular cli bug 

### ISSUE THREAD

**Issue by Ga8** [npm/cli#3293]
instaling new project : thub.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mypersonnaluser/.npm/_logs/2021-05-23T19_30_08_597Z-debug.log
✖ Package install failed, see above.

**Comment by Ga8** [comment]
logs from .npm : 
tp fetch GET 200 https://registry.npmjs.org/@angular-devkit/build-angular/-/build-angular-12.0.1.tgz 81105ms
9102 timing reifyNode:node_modules/@angular-devkit/build-angular Completed in 86538ms
9103 http fetch GET 200 https://registry.npmjs.org/source-map/-/source-map-0.5.7.tgz 84525ms
9104 timing reifyNode:node_modules/@babel/generator/node_modules/source-map Completed in 89638ms
9105 http fetch GET 200 https://registry.npmjs.org/@angular/forms/-/forms-12.0.1.tgz 86351ms
9106 timing reifyNode:node_modules/@angular/forms Completed in 91741ms
9107 http fetch GET 200 https://registry.npmjs.org/ajv/-/ajv-6.12.6.tgz 86777ms
9108 timing reifyNode:node_modules/webpack-dev-server/node_modules/ajv Completed in 91982ms
9109 http fetch GET 200 https://registry.npmjs.org/karma/-/karma-6.3.2.tgz 86662ms
9110 timing reifyNode:node_modules/karma Completed in 92018ms
9111 http fetch GET 200 https://registry.npmjs.org/webpack/-/webpack-5.36.2.tgz 86844ms
9112 timing reifyNode:node_modules/webpack Completed in 92143ms
9113 http fetch GET 200 https://registry.npmjs.org/@schematics/angular/-/angular-12.0.1.tgz 89884ms
9114 timing reifyNode:node_modules/@schematics/angular Completed in 94337ms
9115 http fetch GET 200 https://registry.npmjs.org/@angular/animations/-/animations-12.0.1.tgz 88929ms
9116 timing reifyNode:node_modules/@angular/animations Completed in 94343ms
9117 http fetch GET 200 https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz 89342ms
9118 timing reifyNode:node_modules/@angular/compiler-cli/node_modules/source-map Completed in 94771ms
9119 http fetch GET 200 https://registry.npmjs.org/webpack-dev-server/-/webpack-dev-server-3.11.2.tgz 90065ms
9120 timing reifyNode:node_modules/webpack-dev-server Completed in 95192ms
9121 http fetch GET 200 https://registry.npmjs.org/zone.js/-/zone.js-0.11.4.tgz 89935ms
9122 timing reifyNode:node_modules/zone.js Completed in 95334ms
9123 http fetch GET 200 https://registry.npmjs.org/rxjs/-/rxjs-6.6.7.tgz 90738ms
9124 timing reifyNode:node_modules/rxjs Completed in 96139ms
9125 http fetch GET 200 https://registry.npmjs.org/@angular/router/-/router-12.0.1.tgz 90865ms
9126 timing reifyNode:node_modules/@angular/router Completed in 96240ms
9127 http fetch GET 200 https://registry.npmjs.org/@angular/compiler-cli/-/compiler-cli-12.0.1.tgz 105438ms
9128 timing reifyNode:node_modules/@angular/compiler-cli Completed in 110866ms
9129 http fetch GET 200 https://registry.npmjs.org/@angular/compiler/-/compiler-12.0.1.tgz 117430ms
9130 timing reifyNode:node_modules/@angular/compiler Completed in 122852ms
9131 http fetch GET 200 https://registry.npmjs.org/@angular/common/-/common-12.0.1.tgz 119226ms
9132 timing reifyNode:node_modules/@angular/common Completed in 124621ms
9133 http fetch GET 200 https://registry.npmjs.org/@angular/core/-/core-12.0.1.tgz 119399ms
9134 timing reifyNode:node_modules/@angular/core Completed in 124811ms
9135 http fetch GET 200 https://registry.npmjs.org/typescript/-/typescript-4.2.4.tgz 132504ms
9136 timing reifyNode:node_modules/typescript Completed in 137924ms
9137 timing npm Completed in 276573ms
9138 error cb() never called!
9139 error This is an error with npm itself. Please report this error at:
9140 error <https://github.com/npm/cli/issues>

**Comment by nlf** [comment]
**Closing:** this error can arise for a number of reasons; Please read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F--I'm-having-the-same-problem!%22) & refile an issue with as much information as possible if you're able to **consistently reproduce** this error.
