### ISSUE TITLE
[BUG] Error in npm installation

### ISSUE THREAD

**Issue by GimmiSingh** [npm/cli#3298]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\HYBRIS\\hybris\\bin\\custom\\ygraphqlcodegen\\.gradle\\nodejs\\node-v6.7.0-win-x64\\node.exe',
1 verbose cli   'C:\\HYBRIS\\hybris\\bin\\custom\\ygraphqlcodegen\\.gradle\\nodejs\\node-v6.7.0-win-x64\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'apollo-codegen@0.19.1',
1 verbose cli   '--save',
1 verbose cli   '--save-exact' ]
2 info using npm@3.10.3
3 info using node@v6.7.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData apollo-codegen@0.19.1
8 silly fetchNamedPackageData apollo-codegen
9 silly mapToRegistry name apollo-codegen
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'apollo-codegen',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'apollo-codegen',
12 silly mapToRegistry   name: 'apollo-codegen',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/apollo-codegen
14 verbose request uri https://registry.npmjs.org/apollo-codegen
15 verbose request no auth needed
16 info attempt registry request try #1 at 6:36:16 PM
17 verbose request id f79c3abbf9e1a74c
18 http request GET https://registry.npmjs.org/apollo-codegen
19 info retry will retry, error on last attempt: Error: write EPROTO 101057795:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:openssl\ssl\s3_clnt.c:2010:
20 info attempt registry request try #2 at 6:36:26 PM
21 http request GET https://registry.npmjs.org/apollo-codegen
22 info retry will retry, error on last attempt: Error: write EPROTO 101057795:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:openssl\ssl\s3_clnt.c:2010:
23 info attempt registry request try #3 at 6:37:26 PM
24 http request GET https://registry.npmjs.org/apollo-codegen
25 silly fetchPackageMetaData Error: write EPROTO 101057795:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:openssl\ssl\s3_clnt.c:2010:
25 silly fetchPackageMetaData
25 silly fetchPackageMetaData     at exports._errnoException (util.js:1036:11)
25 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:794:14)
25 silly fetchPackageMetaData  error for apollo-codegen@0.19.1 { Error: write EPROTO 101057795:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:openssl\ssl\s3_clnt.c:2010:
25 silly fetchPackageMetaData
25 silly fetchPackageMetaData     at exports._errnoException (util.js:1036:11)
25 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:794:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Starting
29 silly runTopLevelLifecycles Finishing
30 silly install printInstalled
31 verbose stack Error: write EPROTO 101057795:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:openssl\ssl\s3_clnt.c:2010:
31 verbose stack
31 verbose stack     at exports._errnoException (util.js:1036:11)
31 verbose stack     at WriteWrap.afterWrite (net.js:794:14)
32 verbose cwd C:\HYBRIS\hybris\bin\custom\ygraphqlcodegen\build\apollo-codegen
33 error Windows_NT 10.0.19042
34 error argv "C:\\HYBRIS\\hybris\\bin\\custom\\ygraphqlcodegen\\.gradle\\nodejs\\node-v6.7.0-win-x64\\node.exe" "C:\\HYBRIS\\hybris\\bin\\custom\\ygraphqlcodegen\\.gradle\\nodejs\\node-v6.7.0-win-x64\\node_modules\\npm\\bin\\npm-cli.js" "install" "apollo-codegen@0.19.1" "--save" "--save-exact"
35 error node v6.7.0
36 error npm  v3.10.3
37 error code EPROTO
38 error errno EPROTO
39 error syscall write
40 error write EPROTO 101057795:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:openssl\ssl\s3_clnt.c:2010:
41 error If you need help, you may report this error at:
41 error     <https://github.com/npm/npm/issues>
42 verbose exit [ 1, true ]

### Expected Behavior

Build is unsuccesful in CMD

### Steps To Reproduce

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\HYBRIS\\hybris\\bin\\custom\\ygraphqlcodegen\\.gradle\\nodejs\\node-v6.7.0-win-x64\\node.exe',
1 verbose cli   'C:\\HYBRIS\\hybris\\bin\\custom\\ygraphqlcodegen\\.gradle\\nodejs\\node-v6.7.0-win-x64\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'apollo-codegen@0.19.1',
1 verbose cli   '--save',
1 verbose cli   '--save-exact' ]
2 info using npm@3.10.3
3 info using node@v6.7.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData apollo-codegen@0.19.1
8 silly fetchNamedPackageData apollo-codegen
9 silly mapToRegistry name apollo-codegen
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'apollo-codegen',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'apollo-codegen',
12 silly mapToRegistry   name: 'apollo-codegen',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/apollo-codegen
14 verbose request uri https://registry.npmjs.org/apollo-codegen
15 verbose request no auth needed
16 info attempt registry request try #1 at 6:36:16 PM
17 verbose request id f79c3abbf9e1a74c
18 http request GET https://registry.npmjs.org/apollo-codegen
19 info retry will retry, error on last attempt: Error: write EPROTO 101057795:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:openssl\ssl\s3_clnt.c:2010:
20 info attempt registry request try #2 at 6:36:26 PM
21 http request GET https://registry.npmjs.org/apollo-codegen
22 info retry will retry, error on last attempt: Error: write EPROTO 101057795:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:openssl\ssl\s3_clnt.c:2010:
23 info attempt registry request try #3 at 6:37:26 PM
24 http request GET https://registry.npmjs.org/apollo-codegen
25 silly fetchPackageMetaData Error: write EPROTO 101057795:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:openssl\ssl\s3_clnt.c:2010:
25 silly fetchPackageMetaData
25 silly fetchPackageMetaData     at exports._errnoException (util.js:1036:11)
25 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:794:14)
25 silly fetchPackageMetaData  error for apollo-codegen@0.19.1 { Error: write EPROTO 101057795:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:openssl\ssl\s3_clnt.c:2010:
25 silly fetchPackageMetaData
25 silly fetchPackageMetaData     at exports._errnoException (util.js:1036:11)
25 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:794:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Starting
29 silly runTopLevelLifecycles Finishing
30 silly install printInstalled
31 verbose stack Error: write EPROTO 101057795:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:openssl\ssl\s3_clnt.c:2010:
31 verbose stack
31 verbose stack     at exports._errnoException (util.js:1036:11)
31 verbose stack     at WriteWrap.afterWrite (net.js:794:14)
32 verbose cwd C:\HYBRIS\hybris\bin\custom\ygraphqlcodegen\build\apollo-codegen
33 error Windows_NT 10.0.19042
34 error argv "C:\\HYBRIS\\hybris\\bin\\custom\\ygraphqlcodegen\\.gradle\\nodejs\\node-v6.7.0-win-x64\\node.exe" "C:\\HYBRIS\\hybris\\bin\\custom\\ygraphqlcodegen\\.gradle\\nodejs\\node-v6.7.0-win-x64\\node_modules\\npm\\bin\\npm-cli.js" "install" "apollo-codegen@0.19.1" "--save" "--save-exact"
35 error node v6.7.0
36 error npm  v3.10.3
37 error code EPROTO
38 error errno EPROTO
39 error syscall write
40 error write EPROTO 101057795:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:openssl\ssl\s3_clnt.c:2010:
41 error If you need help, you may report this error at:
41 error     <https://github.com/npm/npm/issues>
42 verbose exit [ 1, true ]

### Environment

- OS: 
- Node: 10.16
- npm: 6.0

**Comment by ljharb** [comment]
You’re using node 8, which is EOL, and npm 3, which is also EOL (and quite ancient).

On node 8, run `npm install -g npm@6`; otherwise, upgrade node to 10+ and run `npm install -g npm`.

**Comment by nlf** [comment]
node 6.7.0 is what actually looks to be in use, which should play nicely with npm 6 but is still really quite old.

you can try just updating npm as @ljharb mentioned above `npm i -g npm@6` (make sure you get the `@6` at the end or you'll end up with npm 7 which does not work on node versions older than 10)

but i would most definitely advise doing what you can to get yourself up to _at least_ node 12, as even node 10 is EOL now.
