### ISSUE TITLE
[BUG] <npm install -g tondev>

### ISSUE THREAD

**Issue by chaos-ui** [npm/cli#3301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

~ $ npm install -g tondev
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2021-05-25T00_18_47_284Z-debug.log

### Expected Behavior

Run this command in termux

### Steps To Reproduce

1. In this environment...https://github.com/npm/cli/issues
2. With this config...npm install -g tondev
3. Run '...'npm install -g tondev
4. See error...
~ $ npm install -g tondev
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2021-05-25T00_18_47_284Z-debug.log

### Environment

- OS: 
- Node: 
- npm: npm install -g tondev

**Comment by nlf** [comment]
**Closing:** this error can arise for a number of reasons; Please read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F--I'm-having-the-same-problem!%22) & refile an issue with as much information as possible if you're able to **consistently reproduce** this error.
