### ISSUE TITLE
NPM ERROR

### ISSUE THREAD

**Issue by Mavutanii** [npm/cli#3302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

npm WARN deprecated @types/classnames@2.3.1: This is a stub types definition. classnames provides its own type definitions, so you do not need this installed.
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Musa Nkuna\AppData\Roaming\npm-cache\_logs\2021-05-25T08_34_31_996Z-debug.log

### Expected Behavior

It should install all the necessary packages when i run  npm install

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...
![NPM Install Error](https://user-images.githubusercontent.com/84741488/119469573-c62b8280-bd47-11eb-9fc2-c5d00920aa24.PNG)
[2021-05-25T08_34_31_996Z-debug.log](https://github.com/npm/cli/files/6537923/2021-05-25T08_34_31_996Z-debug.log)

### Environment

- OS: Windows 10 
- Node: JS 14
- npm: NPM

**Comment by nlf** [comment]
**Closing:** this error can arise for a number of reasons; Please read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F--I'm-having-the-same-problem!%22) & refile an issue with as much information as possible if you're able to **consistently reproduce** this error.
