### ISSUE TITLE
cb() never called!

### ISSUE THREAD

**Issue by SANDEEP1938** [npm/cli#3303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

HU\Desktop\reactnative>n
ing --force Recommended
() never called!

is is an error with npm
  <https://github.com/np

complete log of this run
  C:\Users\SAHU\AppData\

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- OS: 
- Node: 
- npm:

**Comment by ljharb** [comment]
#417

**Comment by nlf** [comment]
**Closing:** this error can arise for a number of reasons; Please read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F--I'm-having-the-same-problem!%22) & refile an issue with as much information as possible if you're able to **consistently reproduce** this error.
