### ISSUE TITLE
npm ci support to updgrade specific packages to latest version.

### ISSUE THREAD

**Issue by shrikant10** [npm/cli#3310]
Requirement - 
We have some internal libraries in our organization that are installed using GitHub/GitLab URLs for which we always want the latest versions in the microservices.
As npm ci adheres to package-lock.json this isn't possible with npm ci to maintain the libraries in the latest version. 
Is there any solution that can be used in this case. 

PS. We want to avoid running npm install in every service repository for these libraries update package-lock and run it in npm-ci.

**Comment by nlf** [comment]
`npm ci` is meant entirely for installing dependencies matching your `package-lock.json`, using it to update a package would be entirely against the point.

it sounds like what you may want would be to disable the package-lock entirely. if you do this, running `npm install` will install the latest versions of every dependency according to how they're recorded in the package.json. you can do this by creating a file named `.npmrc` in your project directory and putting the line `package-lock=false`

unfortunately, you can't do this for only some dependencies, so it means every package you depend on will also be installed at the newest version matching what's in your package.json and the dependencies.
