### ISSUE TITLE
TERM=dumb and --no-progress is ignored

### ISSUE THREAD

**Issue by tim-janik** [npm/cli#3314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Progressbar is shown when it should not:

```
$ TERM=dumb npm install --progress=false
[         .........] - idealTree: timing idealTree Completed in 388m
```

### Expected Behavior

Progressbar disabling works:

```
$ TERM=dumb npm install --progress=false
up to date, audited 702 packages in 2s
```

### Steps To Reproduce

The 'progress' config value and TERM=dumb checks work correctly in setup-log.js.
But later on, progress is enabled unconditionally, regardless of the config, here:

```
./node_modules/@npmcli/arborist/lib/tracker.js:35:        this.log.enableProgress()
```

Disabling this line fixes the behaviour, so TERM=dumb and --progress=false have an effect again.

Note that there are other places that still disable/enable progress *unconditionally* without regards to the config setting, these might need review as well:

```
$ fgrep enableProgress . -rn
./node_modules/@npmcli/arborist/lib/tracker.js:35:        this.log.enableProgress() // <- unconditional progress bar
./node_modules/libnpmexec/lib/run-script.js:82:      log.enableProgress()
./lib/config.js:132:      this.npm.log.enableProgress()
./lib/explore.js:87:      this.npm.log.enableProgress()
./lib/init.js:164:        this.npm.log.enableProgress()
```

### Environment

- OS: linux
- npm: 7.14.0

**Comment by johnnymajor** [comment]
Since postinstall is treated differently using --foreground-scripts helps however the progress bar is now blocking our prompts for more information on install. Any work around to hide the progress bar would be appreciated Thx

**Comment by trallnag** [comment]
Just to repeat in here as the other issue has been closed, one current workaround is to pipe the output through `tee` like this:

```
npm install --no-progress --prefer-offline 2>&1 | tee
```

https://github.com/npm/cli/issues/2560#issuecomment-775657997
