### ISSUE TITLE
fast-csvv4.3.5 and @fast-csv/parse4.3.3 have security vulnerabilities

### ISSUE THREAD

**Issue by jawahar14** [npm/cli#3315]
We use the exceljs package and when the scan happened for security vulnerabilities using blackduck we got this. 
Fast-csv is an npm package for parsing and formatting CSVs or any other delimited value file in node. In fast-cvs before version 4.3.6 there is a possible ReDoS vulnerability (Regular Expression Denial of Service) when using ignoreEmpty option when parsing. This has been patched in v4.3.6 You will only be affected by this if you use the ignoreEmpty parsing option. If you do use this option it is recommended that you upgrade to the latest version v4.3.6 This vulnerability was found using a CodeQL query which identified EMPTY_ROW_REGEXP regular expression as vulnerable.

**Comment by jawahar14** [comment]
- OS: UNIX
- Node: 14.17
- npm: 6.14.13
1. In the Angular project package json has the dependency on exceljs
2. exceljs 4.2
3. Run blackduck scan
4. Description
Fast-csv is an npm package for parsing and formatting CSVs or any other delimited value file in node. In fast-cvs before version 4.3.6 there is a possible ReDoS vulnerability (Regular Expression Denial of Service) when using ignoreEmpty option when parsing. This has been patched in v4.3.6 You will only be affected by this if you use the ignoreEmpty parsing option. If you do use this option it is recommended that you upgrade to the latest version v4.3.6 This vulnerability was found using a CodeQL query which identified EMPTY_ROW_REGEXP regular expression as vulnerable.

**Comment by nlf** [comment]
this issue is not related to the npm cli as the report is for security findings in other projects. i'm closing this since it is not actionable for our team.
