### ISSUE TITLE
Lodash4.17.15 has vulnerabilities

### ISSUE THREAD

**Issue by jawahar14** [npm/cli#3316]
When we use ng2-charts, which has transitive dependency on Lodash reported , blackduck security scan reported the vulnerability that

Lodash is vulnerable to command injection via the template function. An attacker can take advantage of this vulnerability in order to run arbitrary commands.

**Comment by nlf** [comment]
this issue is related to security advisories in other projects, while this repo is specific to the npm cli and its usage. i'm closing this since it is not actionable by the npm team.
