### ISSUE TITLE
npm ERR! cb() never called!  npm ERR! This is an error with npm itself.

### ISSUE THREAD

**Issue by iamhassam143** [npm/cli#3328]
Creating a new React app in C:\Users\user\Desktop\react js\first-app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Local\npm-cache\_logs\2021-05-27T10_49_42_420Z-debug.log    

Aborting installation.

Deleting generated file... package.json
Deleting first-app/ from C:\Users\user\Desktop\react js
Done.

up to date, audited 1 package in 444ms

found 0 vulnerabilities

**Comment by nlf** [comment]
**Closing:** this error can arise for a number of reasons; Please read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F--I'm-having-the-same-problem!%22) & refile an issue with as much information as possible if you're able to **consistently reproduce** this error.
