### ISSUE TITLE
[BUG] npm run -- <args> not working

### ISSUE THREAD

**Issue by v1d3rm3** [npm/cli#3336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i have a script definition, like `test` in `package.json`, when i try to execute this command with arguments, npm is interpreting as a npm cli argument.

Ex:
```npm run test -- -h```

Gives-me: 

```
npm run-script

Run arbitrary package scripts

Usage:
npm run-script <command> [-- <args>]

Options:
[-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
[-ws|--workspaces] [--if-present] [--ignore-scripts]
[--script-shell <script-shell>]

aliases: run, rum, urn

Run "npm help run-script" for more info
```

### Expected Behavior

I expect that when i run ```npm run test -- -h```, it gives me jest help info.

### Steps To Reproduce

1. NodeJs v16.2, npm v7.15.0
2. A simple package with Jest as dependency and a script definition: ```"test": "jest"```
3. Run ```npm run test -- -h```
4. Not showing jest info

### Environment

- OS: Windows 10
- Node:  16.2.0
- npm: 7.15.0

**Comment by bruxisma** [comment]
I'm also experiencing this same issue, using:

 - Powershell 7.1.3
 - Windows Terminal 1.7.1033
 - Node LTS 14.17.0
 - npm 7.15.0
 - Windows 10

**Comment by gregoryzh** [comment]
reported here too. 
https://github.com/npm/cli/issues/3136
it's only powershell, bash or cmd works

**Comment by v1d3rm3** [comment]
I have used powershell too, so it's the problem.

**Comment by Delagen** [comment]
Don't work in cmd also. Run through cmd terminal with installed MSYS

**Comment by wraithgar** [comment]
Closing in favor of https://github.com/npm/cli/issues/3136
