### ISSUE TITLE
[BUG] Npm script can't find node & npm

### ISSUE THREAD

**Issue by quilicicf** [npm/cli#3355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### :rotating_light::rotating_light::rotating_light: EDIT

I understood the issue and proposed a fix in the next comment. 

TL;DR; when the folder containing the `pakage.json` does not belong to the current user, using `node` or `npm` in npm scripts does not work and the error message is misleading.

### Current Behavior

When running an npm script that uses `node` or `npm`, the script fails with error:

```
sh: node: command not found
```

(or `sh: npm: command not found`, of course)

### Expected Behavior

The script should be run.

### Steps To Reproduce

I have tried to document a minimal setup to help you reproduce and could not reproduce with the said setup. Which means:

* __CASE 1:__ with the setup below, I don't reproduce the bug
* __CASE 2__: with the setup below (same Docker image!) but building _my_ repository (closed source unfortunately, so can't post it here), I reproduce the bug

## Reproduction scenario

Starting from the base CentOS image (`centos:latest`), one can:

```bash
# Install dependencies
yum install -y git
yum install -y jq

# Install asdf
git clone --depth 1 https://github.com/asdf-vm/asdf.git ~/.asdf --branch 'v0.8.0'
printf '\n# Link asdf\n. "%s"\n' ~/.asdf/asdf.sh >> ~/.bashrc
source ~/.asdf/asdf.sh

# Install asdf node plugin
asdf plugin add nodejs
~/.asdf/plugins/nodejs/bin/import-release-team-keyring
  
# Install node
asdf install nodejs 16.2.0
asdf global nodejs 16.2.0

# Create test repo
mkdir repo
cd repo
asdf install nodejs 16.2.0
asdf local nodejs 16.2.0
npm init --yes

# Create npm script
updatedPackage="$(jq 'del(.scripts.test)' < package.json)"
updatedPackage="$(jq '.scripts.fiddle="env && node fiddle.js"' <<< "$updatedPackage")"
printf "$updatedPackage" > package.json
printf 'console.log(process.execPath);\n' > fiddle.js

# Run npm script
npm run fiddle
```

### Case 1

When I run the script, it works:

```
[root@bbb9c153f424 repo]# npm run fiddle

> repo@1.0.0 fiddle
> env && node fiddle.js

...
PATH=/root/repo/node_modules/.bin:/root/node_modules/.bin:/node_modules/.bin:/root/.asdf/installs/nodejs/16.2.0/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/root/.asdf/installs/nodejs/16.2.0/.npm/bin:/root/.asdf/installs/nodejs/16.2.0/bin:/root/.asdf/shims:/root/.asdf/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
...
/root/.asdf/installs/nodejs/16.2.0/bin/node
```

### Case 2

When I run the script, it fails, saying it could not find node:

```
[root@bbb9c153f424 designer-frontend]# npm run fiddle

> talend-api-designer@3.16.0 fiddle
> env && node ./fiddle.js

...
PATH=/root/designer-frontend/node_modules/.bin:/root/node_modules/.bin:/node_modules/.bin:/root/.asdf/installs/nodejs/16.2.0/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/root/.asdf/installs/nodejs/16.2.0/.npm/bin:/root/.asdf/installs/nodejs/16.2.0/bin:/root/.asdf/shims:/root/.asdf/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
...
sh: node: command not found
```

My `PATH` is perfectly nice, as I can run: 

```
[root@bbb9c153f424 designer-frontend]# /root/.asdf/installs/nodejs/16.2.0/bin/node --version
v16.2.0
[root@bbb9c153f424 designer-frontend]# /root/.asdf/installs/nodejs/16.2.0/bin/npm --version
7.13.0
```

Every bit of information I have found on the issue seems to tell that my PATH is somehow screwed but I don't see how. 

Also, node knows where it was run from (running `process.execPath` from REPL gives the right path), so it seems like node/npm could fallback to using this path to find node and npm? :thinking: 

## What I've tried

I have tried to clone npm in the Docker image and call `/root/npm/bin/npm-cli.js` instead of `npm` and updated the source so it showed the path before running (in `node_modules/@npm-cli/run-script/lib/make-spawn-args.js`). I reproduced the same results as with the version of `npm` installed by `asdf`, the logged paths were similar, so it looks like the call to `spawn` is made in the same conditions in both cases.

I'm out of ideas :-( 

### Environment

* OS: CentOS latest
* Node: 16.2.0
* npm: 7.13.0

**Comment by quilicicf** [comment]
Found the issue, the buggy folder did not belong to the root user (it was mounted in the Docker image with `-v /path/on/host:/path/on/image`). 

See: 

```
ls -la 
total 28
drwxrwxr-x 10   1000   1000 4096 Jun  3 07:47 private-repo
drwxr-xr-x  2 root   root   4096 Jun  3 07:48 repo
```

Using `chown "$(whoami):$(whoami)" .` in `private-repo` fixed the issue.

Can something be done about the error message to make it clearer why this does not work? :pray: The error message is a bit misleading currently.

Npm scripts calling other npm scripts is a common pattern, and I had this error trying to run the npm script on Jenkins (in a K8s cluster) which I think can happen to lots of people.

**Comment by ruyadorno** [comment]
Hi @quilicicf thank you for taking the time to reporting and updating this issue. Unfortunately I don't see how we could improve much on the error message since that's a system error that `npm` is just surfacing to the user.

I'm going to close this issue now since it didn't get any more traction and I don't see any action item that can be worked on right now but in the future if you (or anyone else reaching this issue) have ideas on how we could better surface these type of errors to uses, feel free to propose them in our [RFC repo](https://github.com/npm/rfcs). Thanks again!

**Comment by quilicicf** [comment]
No worries, at least the diagnostic is indexed on the web now :man_shrugging:

**Comment by ipontt** [comment]
Thanks for documenting this. It saved a lot of time.
