### ISSUE TITLE
[DOC] please update the doc of npm install <folder>

### ISSUE THREAD

**Issue by jcompagner** [npm/cli#3358]
see my case here: https://github.com/npm/cli/issues/3318

if that is not fixed the doc must be corrected because what it says there is just not right

https://docs.npmjs.com/cli/v7/commands/npm-install

"
npm install :

Install the package in the directory as a symlink in the current project. Its dependencies will be installed before it's linked. If sits inside the root of your project, its dependencies may be hoisted to the top-level node_modules as they would for other types of dependencies.
"

The dependencies are not installed, which is a major problem for us so i rather have that that is fixed
But if that case is just kept close, please update the doc because its just not true that that happens

What happens for us is that we have a main project somewhere on disk
and that project can depend on other library projects also somewhere on disk (can be in a different partition)

the main project has no idea of the dependencies of those other library projects they are fully configured for them selfs

we run (they are angular projects) "ng build -watch" in both projects and then the main has installed the dist folders of the output of those libs.

Those lib projects can't be in a subdir of the main, they all have there own git repo's , the libs don't belong in the git repo of the main.

Now we just have to manually install the dependencies of all the lib projects (there can be multiply) in to the main. (at least for development, and we have to make sure never to commit that package.json)

So how can this be solved better?
why is there a different between:

 npm install subfolder\xxxx  (inside main dir)

and

npm install ..\otherfolder\xxxxx (outside main dir)

We can't make it a tarbal (npm pack) because we really run "ng build -watch" in them and we really are developing the lib project(s)

**Comment by mdkrieg** [comment]
I am also interested in this outcome.
