### ISSUE TITLE
[BUG] On npm@6 tells to install npm 7.15.1 not 7.16.0

### ISSUE THREAD

**Issue by SamuelMarks** [npm/cli#3366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
$ n lts
   installed : v14.17.0 (with npm 6.14.13)
$ npm i -g npm
n/bin/npm -> n/lib/node_modules/npm/bin/npm-cli.js
n/bin/npx -> n/lib/node_modules/npm/bin/npx-cli.js
+ npm@7.16.0
added 62 packages from 25 contributors, removed 242 packages and updated 193 packages in 5.487s


   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │      New major version of npm available! 6.14.13 → 7.15.1      │
   │   Changelog: https://github.com/npm/cli/releases/tag/v7.15.1   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯
```

### Expected Behavior

   │      New major version of npm available! 6.14.13 → 7.16.0      │

### Steps To Reproduce

1. Install https://github.com/tj/n
2. Run `n lts`

### Environment

- OS: macOS 11.4 (20F71)
- Node: v14.17.0
- npm: Upgrade from 6.14.13

**Comment by darcyclarke** [comment]
We cut this release yesterday & you probably got this while we were updating dist-tags/rolling out the release; Upgrading to `v7.16.0` (ie. `npm i -g npm`) should fix this...
