### ISSUE TITLE
CLI commands are opening file explorer and not running

### ISSUE THREAD

**Issue by Morheb-Bek** [npm/cli#3369]
I left react for few months, today i started learning Angular as requested,  and when i was trying to create new app with `ng new myapp` a new apo was not created,  and file explorer opened
I tried `ng version `, also opened file explorer , so does npm bugs command
i am using hyper 
Then i tried npx create-react-app, same thing happened, file explorer opens and terminal goes blank,  and no app is created
I tried removing and reinstalling node and npm,  still not fixed
![image](https://user-images.githubusercontent.com/74189832/120883215-905a8980-c5e4-11eb-97a7-6efe28bb86f8.png)

I used to work with react and it was working fine

**Comment by darcyclarke** [comment]
1. Please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).
2. Can you try replicating this problem on the latest version of `npm`? (ie. `npm i -g npm`) 
3. If it's still happening, can you provide steps to reproduce the problem?

I'm closing this for now but will re-open if you can follow up with the above changes/information.
