### ISSUE TITLE
[cb() never called!] <When try to run npm i its showing cb() never called!>

### ISSUE THREAD

**Issue by rahmanharoon** [npm/cli#3372]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

I need to install new packages on my package.json so I run npm i (npm install) Then it's showing
```
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /UserName/.npm/_logs/2021-06-05T10_36_45_429Z-debug.log
```

Here is the complete log

> 0 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'i' ]
1 info using npm@7.15.1
2 info using node@v14.16.0
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/UserName/Desktop/personal/admin/.npmrc Completed in 0ms
10 timing config:load:project Completed in 0ms
11 timing config:load:file:/UserName/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 6ms
19 timing npm:load:configload Completed in 6ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 2ms
22 timing npm:load:cleanupLog Completed in 1ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 1ms
25 timing npm:load Completed in 12ms
26 timing config:load:flatten Completed in 2ms
27 timing arborist:ctor Completed in 0ms
28 timing arborist:ctor Completed in 0ms
29 timing idealTree:init Completed in 1905ms
30 timing idealTree:userRequests Completed in 0ms
31 silly idealTree buildDeps
32 silly fetch manifest @gorhom/bottom-sheet@^3.6.5
33 http fetch GET 304 https://registry.npmjs.org/@gorhom%2fbottom-sheet 2791ms (from cache)
34 silly fetch manifest react@16.13.1
35 http fetch GET 304 https://registry.npmjs.org/react 1768ms (from cache)
36 silly fetch manifest react-native@https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz
37 timing npm Completed in 416856ms
38 error cb() never called!
39 error This is an error with npm itself. Please report this error at:
40 error <https://github.com/npm/cli/issues>

### Expected Behavior

I need to install the packages

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- OS: `MacOs`
- Node: `v14.16.0`
- npm:  `7.15.1`

**Comment by nlf** [comment]
**Closing:** this error can arise for a number of reasons; Please read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F--I'm-having-the-same-problem!%22) & refile an issue with as much information as possible if you're able to **consistently reproduce** this error.
