### ISSUE TITLE
uuid 3.3 is deprecated with npm 6.14.13 shall we update uuid to latest v8.x?

### ISSUE THREAD

**Issue by emclab** [npm/cli#3379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After installing nodejs 14.17.0, there is an warning message about deprecated uuid 3.3 and claims that uuid 3.3 has security flaw. Shall I update uuid to the latest version of 8.x for npm module or leave as it is?

### Expected Behavior

Deprecated warning message

### Steps To Reproduce

On ubuntu 20.04 after installing nodejs 14.17.0, check package.json of npm under node-modules. The uuid version is 3.3.

### Environment

- OS: Ubuntu 20.04
- Node: 14.17.0
- npm: 6.14.13

**Comment by ljharb** [comment]
@emclab try `npm install -g npm` to install npm 7. npm 6 is basically no longer supported (see #3351)

**Comment by wraithgar** [comment]
Yes, as @ljharb stated, npm 6 is no longer supported.  Critical security updates will be pushed as needed.
