### ISSUE TITLE
NPM Node RFC Installation Issue

### ISSUE THREAD

**Issue by pnvsri** [npm/cli#3387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It's been a year we have installed node-rfc 1.0.3 and working due to application upgradation we need to upgrade the version of rfc, but while trying to verify the status and upgrade/install rfc we are getting the ELOOP: too many symbolic links encountered, access '/opt/node/node_modules/node-fetch' request you to please help us in this regard

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- OS: 
- Node: 
- npm:

**Comment by wraithgar** [comment]
This repo tracks issues with the npm cli itself. If you are having problems installing node-rfc please open an issue in that repo

https://github.com/sap/node-rfc
