### ISSUE TITLE
[BUG] npm i firebase fails with cb() never called! on Termux

### ISSUE THREAD

**Issue by warp9pnt9** [npm/cli#3389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`npm i firebase` gets near the end, but fires a `cb() never called!` error.  No `firebase` dependency in `package.json`. 

`npm i firebase-admin` gets near the end, but fires a `cb() never called!` error.  No `firebase-admin` dependency in `package-lock.json`.

Maybe related?

### Expected Behavior

Expect firebase (and later, firebase-admin) to be installed without error, updating package.json and package-lock.json as needed.

### Steps To Reproduce

1. Android ARMv8 / Aarch64
2. Install F-Droid (Google Play alternative)
3. Install Termux from F-Droid (Google Play version no longer maintained)
4. Start Termux
5. Use pkg, apt, or apt-get to install `nodejs` package
6. e.g. `pkg i nodejs`
7. Upgrade npm e.g. `npm i -g npm@latest`
8. `mkdir app-foo; cd app-foo`
9. `npm init -y`
10. `npm i firebase`
11. Results in almost complete, but `npm ERR! cb() never called!`
12. If followed by `npm i firebase-admin`, error as well.

### Environment

- Samsung SM-N986U1 (not rooted)
- ARCH: aarch64 ARMv8
- OS: Android 11
- OS-extra: OneUI v3.1
- OS-extra: Termux v0.113
- Node: 14.15.4
- npm: 7.16.0

Debug log: 
[2021-06-09T13_45_55_860Z-debug.log](https://github.com/npm/cli/files/6624215/2021-06-09T13_45_55_860Z-debug.log)

**Comment by wraithgar** [comment]
Thank you for including the debug log.  We added some things in `v7.20.0` that should catch more of these errors and properly handle them. Can you try using the newest npm version?

**Comment by warp9pnt9** [comment]
Strange.  This may be s new bug.  No printed errors.  `npm i firebase` appears to succeed, but when I subsequently run `npm i firebase-admin`, I get an error, and `package.json` is unchanged, `package-lock.json` is not created.  There is no debug.log.

```
~/dev $ rm -rf app-foo; mkdir app-foo; cd app-foo
~/dev/app-foo $ npm init -y
~/dev/app-foo $ npm i firebase
~/dev/app-foo $ npm i firebase-admin
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
~/dev/app-foo $ ls -al
total 15
drwx------  3 u0_a296 u0_a296 3488 Jul 16 08:48 .
drwx------  8 u0_a296 u0_a296 3488 Jul 13 06:22 ..
drwx------ 40 u0_a296 u0_a296 3488 Jul 16 08:48 node_modules
-rw-------  1 u0_a296 u0_a296  221 Jul 16 08:47 package.json
~/dev/app-foo $ cat package.json
{
  "name": "app-foo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
~/dev/app-foo $
```

The package.json never has any data written to it after the install.  `package-lock.json` is never created.  Something has gone badly wrong.  There's a whole bunch of packages in node_modules, so some things went right at least.

There was no debug log created.

Ran `npm doctor`.  The only recommendation was to upgrade nodejs from 14.15.4 to 14.17.3.  Not sure if this is related.  However, this is not currently possible in Termux due to [bad register names](https://github.com/termux/termux-packages/pull/6973).

**Comment by lukekarrys** [comment]
**Closing:** We suspect this has to do with a combination of resource constraints within the device/program being used and the large amount of transient dependencies being installed by this command.

We've opened https://github.com/npm/statusboard/issues/395 for us to look deeper into this and track the discussion and fixes around it. You can also read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) for more information on why this issue might be happening currently and ways to debug it.

**Comment by warp9pnt9** [comment]
Thanks for the note.  Currently, firebase is installing ok.  Also, Termux finally updated node to v16.
