### ISSUE TITLE
[BUG] npm i yarn fails with cb() never called! on Termux

### ISSUE THREAD

**Issue by warp9pnt9** [npm/cli#3390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`npm i -g yarn` gets near the end, but fires a `cb() never called!` error.

### Expected Behavior

Expect yarn to be installed globally without error.

### Steps To Reproduce

1. Android ARMv8 / Aarch64
2. Install F-Droid (Google Play alternative)
3. Install Termux from F-Droid (Google Play version no longer maintained)
4. Start Termux
5. Use pkg, apt, or apt-get
6. Update sources with `pkg update` or `apt-get update` and `apt-get upgrade`
7. Install Node.js with `pkg i nodejs` or `apt-get install nodejs`
8. Upgrade npm e.g. `npm i -g npm@latest`
9. `npm i -g yarn`
10. Results in almost complete install, but errors with `npm ERR! cb() never called!`
11. `pkg i yarn`, installs yarn as a Termux package
12. yarn then works ok, but can't be upgraded with `npm i -g yarn@latest`

### Environment

- Samsung SM-N986U1 (not rooted)
- ARCH: aarch64 ARMv8
- OS: Android 11
- OS-extra: OneUI v3.1
- OS-extra: Termux v0.113
- Node: 14.15.4
- npm: 7.16.0

Debug log: 
[2021-06-09T17_13_25_410Z-debug.log](https://github.com/npm/cli/files/6625760/2021-06-09T17_13_25_410Z-debug.log)

**Comment by wraithgar** [comment]
Thank you for including the debug log.  We added some things in `v7.20.0` that should catch more of these errors and properly handle them. Can you try using the newest npm version?

**Comment by warp9pnt9** [comment]
Appears to succeed with no errors, no debug.log.  But package.json is not updated, package-lock.json is never created.

**Comment by wraithgar** [comment]
If you add the `--timing` flag a debug log will be created no matter what.  Can you try that and attach the log?

**Comment by warp9pnt9** [comment]
[2021-07-19T22_58_37_829Z-debug.log](https://github.com/npm/cli/files/6844344/2021-07-19T22_58_37_829Z-debug.log)

**Comment by lukekarrys** [comment]
**Closing:** We suspect this has to do with a combination of resource constraints within the device/program being used and the large amount of transient dependencies being installed by this command.

We've opened https://github.com/npm/statusboard/issues/395 for us to look deeper into this and track the discussion and fixes around it. You can also read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) for more information on why this issue might be happening currently and ways to debug it.

**Comment by warp9pnt9** [comment]
Yarn still fails to install, but now fails instantly (< 2.0s), rather than nearly completes.  The "resource constrained" argument is invalid here.  11 files and 3 folders were created.

node: 16.10.0
npm: 7.24.1

Debug log with `--timing`s.
[2021-09-29T17_12_37_700Z-debug.log](https://github.com/npm/cli/files/7253861/2021-09-29T17_12_37_700Z-debug.log)
