### ISSUE TITLE
[BUG] npm ERR! cb() never called!

### ISSUE THREAD

**Issue by wuluo** [npm/cli#3393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

### Expected Behavior

7714 timing reifyNode:node_modules/gojs Completed in 136686ms
7715 timing npm Completed in 164911ms
7716 error cb() never called!
7717 error This is an error with npm itself. Please report this error at:

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run 'npm i'
4. See error...

### Environment

- OS: mac os big sur 11.3
- Node: '14.5.0',
- npm: '7.16.0',

**Comment by lukekarrys** [comment]
**Closing:** We suspect this has to do with a combination of resource constraints within the device/program being used and the large amount of transient dependencies being installed by this command.

We've opened https://github.com/npm/statusboard/issues/395 for us to look deeper into this and track the discussion and fixes around it. You can also read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) for more information on why this issue might be happening currently and ways to debug it.
