### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by simzoarora** [npm/cli#3395]
npm ERR! cb() never called!

**Comment by Nixinova** [comment]
dupes #417, recent #3393

**Comment by Dirty-Cyrillian-Napkin** [comment]
Dollop i

**Comment by lukekarrys** [comment]
**Closing:** please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).
