### ISSUE TITLE
[security] private keys in node-gyp, npm7

### ISSUE THREAD

**Issue by networkandcode** [npm/cli#3401]
This was found during a container scan:
Private keys stored in image
Cause: Found: /usr/lib/node_modules/npm/node_modules/node-gyp/test/fixtures/server.key

```
/usr/local/lib
└─┬ npm@7.17.0
  ├─┬ @npmcli/run-script@1.8.5
  │ └── node-gyp@7.1.2 deduped
  └── node-gyp@7.1.2
```

**Comment by ljharb** [comment]
It’s a false positive; that’s a test fixture.
