### ISSUE TITLE
[BUG] <title>npm ERR! cb() never called! while creating a new react app.

### ISSUE THREAD

**Issue by kaartik2611** [npm/cli#3407]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

I can the followng commands:
`npm init`
`npm i create-react-app`
`npx create-react-app test`
This gives the following error :
```bash
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\acer\AppData\Roaming\npm-cache\_logs\2021-06-12T12_00_31_951Z-debug.log
```
I also tried:
1)I uninstalled `create-react-app` from global 
2)I tried ` npm cache clean --force` 

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- OS: Windows 10, 64bit
- Node: 14.17.0
- npm: 6.14.13

**Comment by busrakaraa** [comment]
I have the same issue for a week. Could you find a solution?

**Comment by ljharb** [comment]
@kaartik2611 @busrakaraa does this happen on npm 7?

**Comment by kaartik2611** [comment]
> @kaartik2611 @busrakaraa does this happen on npm 7?

yeah.
The same error
```bash
C:\Users\acer\reactjs>npm -v
7.18.1

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\acer\AppData\Local\npm-cache\_logs\2021-06-19T06_12_52_002Z-debug.log
```

**Comment by wraithgar** [comment]
npm `v7.20.0` added some things that should catch more of these network errors. It also added some new debugging messages specifically for this error message. Can you try with that version and also include any debug logs it generates?

**Comment by lukekarrys** [comment]
**Closing:** We suspect this has to do with a combination of resource constraints within the device/program being used and the large amount of transient dependencies being installed by this command.

We've opened https://github.com/npm/statusboard/issues/395 for us to look deeper into this and track the discussion and fixes around it. You can also read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) for more information on why this issue might be happening currently and ways to debug it.
