### ISSUE TITLE
[BUG] "npm update" doesn't work

### ISSUE THREAD

**Issue by arsinclair** [npm/cli#3410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
$ npm outdated
Package      Current   Wanted  Latest  Location
jest          26.6.3   26.6.3  27.0.4  node_modules/jest
$ npm update
$ npm update jest@latest
$ npm update jest@27.0.4
$ npm outdated
Package      Current   Wanted  Latest  Location
jest          26.6.3   26.6.3  27.0.4  node_modules/jest
```
As we can see, jest should be upgraded to 27.0.4, but it is not.

### Expected Behavior

Per https://docs.npmjs.com/updating-packages-downloaded-from-the-registry

> In your project root directory, run the update command:
> $ npm update
> To test the update, run the outdated command. There should not be any output
> $ npm outdated

There should be no output and the package should be upgraded to the latest version.

### Environment

- OS: Windows 10
- Node: v14.17.0
- npm: v7.13.0

**Comment by ljharb** [comment]
Use npm install, instead of npm update, to update a major version.

**Comment by arsinclair** [comment]
Okay, it is thoroughly confusing. But it worked. Should the docs be updated?

**Comment by tobiu** [comment]
I am using v7.16.0 and can confirm that npm update is broken.

The neo.mjs framework was using e.g. `"postcss": "^8.3.2"`, an update did not change it to 8.3.4, which is the latest stable version.

For me the entire npm cli ecosystem is completely messed up for almost 2 months now.

Even npm install does no longer update dependencies.

The only way that still works is:
1. delete the node_modules folder
2. delete the package-lock.json
3. manually update all dependency version numbers inside the package.json
4. run npm install

This is consuming too much time, especially when deploying new framework versions frequently to the online examples.

Please take a look into it!

**Comment by nlf** [comment]
The original issue described is indeed intended behavior, though I agree that this could be noted more clearly in the docs to make it less confusing. Today it just says "respecting semver" but we can add an example of what that means.

@tobiu if you can open a new issue and give us as much information as possible to reproduce what's going on for you, we'll take a look!

**Comment by wraithgar** [comment]
Docs update PR https://github.com/npm/cli/pull/3494

**Comment by wraithgar** [comment]
Docs updated, will go out with the next release and docs site update will automatically follow that.
