### ISSUE TITLE
[BUG] Cannot verifiy email address

### ISSUE THREAD

**Issue by MichaelBaySAP** [npm/cli#3412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to verify the email address, I am getting the following diagnostics ID 65f37bbd1a6edfdb~5a2a
  

### Expected Behavior

It should verify my email 

### Steps To Reproduce

for user d060262

### Environment

Chrome browser

![image](https://user-images.githubusercontent.com/40032066/121891723-1df05480-cd1c-11eb-92a9-0945961f0036.png)

**Comment by wraithgar** [comment]
This looks like a problem w/ the npm registry, not the cli.  Please contact support at https://www.npmjs.com/support
