### ISSUE TITLE
[BUG] npm ERR! cb() never called!

### ISSUE THREAD

**Issue by ADTC** [npm/cli#3421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I encountered this with some scenarios involving Angular. Most recently with `npm i -D @angular-builders/custom-webpack`. I have looked at #417. Please feel free to ask me anything!

### Expected Behavior

It just works!

### Steps To Reproduce

1. Run `npm i -D @angular-builders/custom-webpack`
1. See error

```
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>
```
Log Files:

- [2021-06-16T03_00_14_507Z-debug.log](https://github.com/npm/cli/files/6660673/2021-06-16T03_00_14_507Z-debug.log)
- [2021-06-16T03_17_34_636Z-debug.log](https://github.com/npm/cli/files/6660677/2021-06-16T03_17_34_636Z-debug.log)
- [2021-06-16T04_13_51_474Z-debug.log](https://github.com/npm/cli/files/6660678/2021-06-16T04_13_51_474Z-debug.log)
- [2021-06-16T06_11_23_385Z-debug.log](https://github.com/npm/cli/files/6660679/2021-06-16T06_11_23_385Z-debug.log)
- [2021-06-16T06_21_24_649Z-debug.log](https://github.com/npm/cli/files/6660680/2021-06-16T06_21_24_649Z-debug.log)
- [2021-06-16T06_30_24_129Z-debug.log](https://github.com/npm/cli/files/6660704/2021-06-16T06_30_24_129Z-debug.log)

### Environment

- OS: Windows 10, MINGW64, Git Bash
- Node: 14.17.1
- npm: 7.17.0

**Comment by ljharb** [comment]
#417

**Comment by Lecam-host** [comment]
je rencontre le meme probleme a l'installation d'une application en vue js

**Comment by wraithgar** [comment]
Do these happen if you include `--no-audit`

**Comment by wraithgar** [comment]
npm `v7.20.0` added some things that should catch more of these network errors. It also added some new debugging messages specifically for this error message. Can you try with that version and also include any debug logs it generates in a new issue?
