### ISSUE TITLE
[BUG] Wrong error display for dependency

### ISSUE THREAD

**Issue by ofirrifo** [npm/cli#3422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm using npm version 7.17.0

When I execute the `npm install` command I get: 

```
npm ERR! ERESOLVE unable to resolve dependency tree
```

as you can see the dependency are the same 

```
 While resolving: mgmt-console@2.1.0
npm ERR! Found: @angular/core@11.2.7
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"11.2.7" from the root project
npm ERR!   peer @angular/core@">=11.2.7" from @sentinel-one/singularity-ui@1.0.92
npm ERR!   node_modules/@sentinel-one/singularity-ui
npm ERR!     @sentinel-one/singularity-ui@"^1.0.92" from the root project
```

### Expected Behavior

expected not to show error.
BTW in when I'm use npm V6.14.13 it work as should

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- OS: mac os
- Node: v14.15.5
- npm: 7.17.0

**Comment by nlf** [comment]
We're missing a lot of the error message here. Can you paste the full output? If you can, sharing your package.json and package-lock.json would also be very helpful.

**Comment by wraithgar** [comment]
Not enough info to reproduce. Please re-open with full output (and package/package-lock if possible) or make a new issue with those things included.
