### ISSUE TITLE
[BUG] <title>cb() never called!

### ISSUE THREAD

**Issue by DasarathanSampath** [npm/cli#3428]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

"npm install bable-cli" throws an error "cb() never called!"

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/24868297/122262034-9a3c9080-cef2-11eb-9d3a-47d6e2c51326.png)

### Environment

- OS: Debian GNU/Linux 10 (buster)
- Node: v12.14.1
- npm: 7.16.0

**Comment by ljharb** [comment]
#417

**Comment by DasarathanSampath** [comment]
I tried re-installing the complete project to reproduce the same issue.
I the middle, I found my system, which was running low memory. I deleted few files and got more space.
Everything works well, and no "cb() never called!" error did not appear.
I assume it is a memory issue.
