### ISSUE TITLE
[BUG] <npm ERR! cb() never called!>    v6

### ISSUE THREAD

**Issue by busrakaraa** [npm/cli#3432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,

I had this error first when I create new React app.
I tried every suggested solution for this problem, including upgrading npm but even when I try to update my npm, it gives the same problem again.

NOTE: Please don't redirect me to https://github.com/npm/cli/issues/417, it also didn't work.

### Steps To Reproduce

1. In this environment : VS Code Terminal or node.js command promp
2. With this config...
3. Run :   npm i -g npm@latest,  or upgrade commands
4. See error...

### Environment

- OS: 
- Node:  14.17.0
- npm:  6.14.13

**Comment by macedonga** [comment]
I had the same problem, with the same exact version. I just ran `npm i` again after reinstalling npm and it worked

**Comment by busrakaraa** [comment]
> I had the same problem, with the same exact version. I just ran `npm i` again after reinstalling npm and it worked

Unfortunately, I tried it but got the same problem again. 

![image](https://user-images.githubusercontent.com/39573363/122373445-2a69ec80-cf6a-11eb-8117-85a6513704ea.png)

**Comment by macedonga** [comment]
Weird...
(you forgot to hide your username before `npm i` btw)

**Comment by anoopkumarseth** [comment]
1. Uninstall your node.js, & take backup of NPM folder & delete from C:\Users\<YOUR_NAME>\AppData\Roaming > NPM
2. uninstall windows development kit (IF have) from the control panel
3. clean your computer junks USING Cleaner(free version) https://www.ccleaner.com/ccleaner/download
4. restart your PC.
5. Reinstall Node js & angural CLI
6. then create a new App from the command prompt

Then Your Problem should be fixed (:

![image](https://user-images.githubusercontent.com/30388576/122376932-3b265c80-cf82-11eb-8464-3fdb18492d4b.png)

**Comment by allan-1** [comment]
Mine was a problem with the network connectivity. After I have checked it is now working.

**Comment by darcyclarke** [comment]
@busrakaraa Is this a problem you're able to consistently reproduce? Are you working with any peers that are running into the same problem for the same project? Are you able to provide your project's `package.json` &/or `package-lock.json` & more information about your OS/environment? Unfortunately, we aren't triaging v6 bugs anymore so our current hope is that updating to `npm@7` will help resolve many of these types of issues for folks. If not, & you're able to reproduce this problem on v7, we'd ask you to please file a new issue with some more context. 

We are aware that this error is thrown for a [number of reasons](https://github.com/npm/cli/wiki/%22cb()-never-called%3F--I'm-having-the-same-problem!%22) so it can be hard to trace. If you're having problems upgrading to the latest `npm` (ref. https://github.com/npm/cli#installation), you can also try updating to the [latest Node version, v16.x,](https://nodejs.org/en/download/current/) which ships with `npm@7`
