### ISSUE TITLE
[BUG] WARN old lockfile when running npm update.

### ISSUE THREAD

**Issue by ehoogeveen-medweb** [npm/cli#3438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Starting from npm 7.18.0, when I run `npm update` on my project I get an `old lockfile` warning, even when the lockfile is freshly created. The warning says it's a one-time fix-up, but no changes are actually made and if I run `npm update` again the warning repeats itself.

### Expected Behavior

No warning (or if the warning is legitimate, no warning after it does its fix-up).

### Steps To Reproduce

1. Starting from an empty new directory.
2. Create a fresh node project using `npm init -y`.
3. Run `npm update --dev` (I also get the warning without `--dev` in my non-empty project).
4. npm prints warning `npm WARN old lockfile` every time npm update runs.

### Environment

- OS: Windows 10 21H1 x64
- Node: 14.17.0
- npm: 7.18.1

**Comment by isaacs** [comment]
Fixed by https://github.com/npm/arborist/pull/293

**Comment by ehoogeveen-medweb** [comment]
I no longer see this with 7.19.0 (which includes the commit mentioned above), thanks!

**Comment by dominikseger** [comment]
Still got this Warnings on a fresh project with Node 16.4.0 and NPM 7.19.0
