### ISSUE TITLE
The npm start command is too slow

### ISSUE THREAD

**Issue by tymsai** [npm/cli#3443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The npm start command is too slow it takes almost 5 min to start

### Expected Behavior

It was expected to start within some seconds

### Steps To Reproduce

type npm start and hit enter

### Environment

windows 10 home
node latest version
npm latest

**Comment by ljharb** [comment]
The start command runs a user-provided script, so npm doesn’t have anything to do with it.

**Comment by tymsai** [comment]
I checked in windows power shell also
the npm start command is running slow

**Comment by ljharb** [comment]
Again, it’s not npm, it’s “whatever your project defined start to be”.

**Comment by nlf** [comment]
As @ljharb said, we don't control what your start script runs. If changing your start script to something that you know for sure should run quickly, like `echo hello` and that still takes 5+ minutes, then this is potentially an npm issue. If not, it's out of our control entirely. If a simple command like that is very slow, let us know and we'll reopen this issue.

**Comment by tymsai** [comment]
> As @ljharb said, we don't control what your start script runs. If changing your start script to something that you know for sure should run quickly, like `echo hello` and that still takes 5+ minutes, then this is potentially an npm issue. If not, it's out of our control entirely. If a simple command like that is very slow, let us know and we'll reopen this issue.

`echo hello` is running super fast no problem in this command :-) thanks , but npm start is where issue is starting ( Power Shell Terminal )

**Comment by ljharb** [comment]
@tymsai again, the issue isn't "npm start" - it's "whatever command the start script uses". If you run that command by itself (not `npm start`, but whatever command is inside "scripts.start") in powershell, what happens?

**Comment by tymsai** [comment]
ok if it is not the problem of npm then can you please find out where the trouble is :-(

**Comment by ljharb** [comment]
@tymsai what are the contents of "start" under "scripts" in package.json?

**Comment by tymsai** [comment]
![image](https://user-images.githubusercontent.com/76956612/122865612-4d1e4b80-d344-11eb-8411-16c2c9f17988.png)

**Comment by ljharb** [comment]
@tymsai ok so presumably `npx react-scripts start` would also be slow - which means it's an issue with react-scripts. file it there.

**Comment by tymsai** [comment]
npx react-scripts start is also slow,  " file it there " , can you please give me the link

**Comment by ljharb** [comment]
the package is named "react-scripts", so go to https://npmjs.com/react-scripts, and look for a "repository" link.

**Comment by tymsai** [comment]
ok sir
