### ISSUE TITLE
[BUG] npx outputs successful "Done" message to stderr

### ISSUE THREAD

**Issue by cedricguindon** [npm/cli#3447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a npx command is executed, the results on a valid successful command is sent to stderr

### Expected Behavior

The successful response should be going to stdout and not stderr

### Steps To Reproduce

Command could be anything, here's an example:
1: npx tailwindcss@latest build 2> /tmp/npx_error_log.txt
2: cat /tmp/npx_error_log.txt

The above cat output will be the following:

Done in 2696ms.

A space then the "Done" success message

The command completed successfully but the succeed message waas sent to the 2> (stdErr)

### Environment

- OS: Ubuntu 20.04
- npm: 7.7.6
- node: v15.14.0

**Comment by wraithgar** [comment]
Can't reproduce this with the latest npm (v7.19.0)

```sh
~/D/n/scratch $ npm -v
7.19.0
~/D/n/scratch $ npx @gar/create-test 2 > npx_error_out.txt
~/D/n/scratch $ cat npx_error_out.txt 
Gar's test create script version 1.0.20
~/D/n/scratch $ yes|npx @gar/create-test@1.0.18 2 > npx_error_out.txt 
npm WARN exec The following package was not found and will be installed: @gar/create-test@1.0.18
~/D/n/scratch $ cat npx_error_out.txt
Gar's test create script version 1.0.18
```
