### ISSUE TITLE
[BUG] npm 7 Workspace Dependency Resolution Does Not Work with Docker

### ISSUE THREAD

**Issue by nerdyman** [npm/cli#3448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running npm scripts on workspaces in a Docker container fail to resolve hoisted modules with the error message `Cannot find module`.

Everything works correctly on my Linux desktop machine but does not work in a Docker container (tested on Debian and Alpine).

Also, lodash is correctly resolved by both packages, but package-two, which depends on esbuild cannot find the esbuild dependency even though it is in the parent `node_modules` folder.

### Expected Behavior

Running npm scripts on workspaces in a Docker container correctly resolve hoisted modules from parent directories.

### Steps To Reproduce

1. [Clone this repo](https://github.com/nerdyman/npm-7-workspaces-monorepo-docker) (`git clone git@github.com:nerdyman/npm-7-workspaces-monorepo-docker.git`)
2. Run `docker build --tag npm-workspaces .`
3. See error below

```
> npm-monorepo-workspaces-docker@1.0.0 start-all
> npm run start --workspaces


> @this/package-one@1.0.0 start
> node ./index.js

Package One This Should Be In Start Case

> @this/package-two@1.0.0 start
> npm run build && node ./dist/index.js


> @this/package-two@1.0.0 build
> node ./esbuild.js

node:internal/modules/cjs/loader:944
  throw err;
  ^

Error: Cannot find module '@esbuild-plugins/node-resolve'
Require stack:
- /srv/app/packages/package-two/esbuild.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at Function.Module._load (node:internal/modules/cjs/loader:774:27)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/srv/app/packages/package-two/esbuild.js:3:21)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/srv/app/packages/package-two/esbuild.js' ]
}
npm ERR! Lifecycle script `start` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @this/package-two@1.0.0 
npm ERR!   at location: /srv/app/packages/package-two 
```

The command the container runs is:

```
npm run start --workspaces
```

#### Working (Host)

- OS: Arch Linux
- Node: `16.3.0`
- npm: `7.18.1`

#### Broken (Docker)

- OS: Debian Buster
- Node: `16.3.0`
- npm: `7.18.1`

**Comment by nerdyman** [comment]
After doing a bit more digging on this I've found that it works when `ENV NODE_ENV=production` is removed from the Dockerfile. 

I'm not sure why this breaks the dependency resolution, I thought npm to behave in the same way when running in production mode. It works either way the host machine but does not work with the environment set to production in the container :thinking:

**Comment by ruyadorno** [comment]
hi @nerdyman thank you for taking the time to report this.

Setting a `NODE_ENV=production` env variable is equivalent to running `npm install --prod` which will NOT install any of the development dependencies declared in your `package.json` `devDependencies` object.

With that in mind, it seems to me that the script your docker container is trying to run depends on dependencies that are declared as `devDependencies` which are in turn missing, thus causing your script to fail.

Feel free to open a new issue providing more info, such as `package.json` file or any relevant logfile you can provide in case you still find problems using npm. Thanks again.

**Comment by nerdyman** [comment]
Ah that makes sense, esbuild is in `devDependencies` [in the broken workspace](https://github.com/nerdyman/npm-7-workspaces-monorepo-docker/blob/main/packages/package-two/package.json) thanks @ruyadorno!
