### ISSUE TITLE
[BUG] npx --force warning hides confirmation prompt to install package

### ISSUE THREAD

**Issue by bmwalters** [npm/cli#3461]
### Current Behavior

When using `npx --force`, the warning printed due to using `--force` covers up the prompt asking the user to enter "y" to proceed. At first glance it looks like the command has hung waiting for I/O or something.

```
$ npx --force mkdirp
npm WARN using --force Recommended protections disabled.
Need to install the following packages:
  mkdirp
⸨░░░░░░░░░░░░░░░░░░⸩ ⠙ : WARN using --force Recommended protections disabled.
```

### Expected Behavior

The command output should not hide the line prompting the user to enter "y" to proceed.

### Steps To Reproduce

1. Use a system without any packages installed globally / in the cache.
2. `npx --force mkdirp`.
3. Observe the command output.

### Environment

- OS: macOS 11.3.1
- Node: 16.3.0
- npm: 7.15.1
- shell: fish 3.2.2

**Comment by wraithgar** [comment]
This does not attempt to pause the log, if `log.clearProgress()` is available:

https://github.com/npm/libnpmexec/blob/main/lib/index.js#L168-L171

**Comment by lauta3011** [comment]
This also happens when trying `npm cache clean --force`

**Comment by rayw000** [comment]
I've post PR https://github.com/npm/libnpmexec/pull/8 to fix this issue.

@lauta3011  `npm cache clean --force` works for me as it is supposed, and also `npm cache clean`. Could you provide more details about what happened to you?

**Comment by wraithgar** [comment]
With new libnpmexec:

```sh
~/D/n/cli (release-next↑1|✔) $ node . exec @gar/create-test --force
npm WARN using --force Recommended protections disabled.
Need to install the following packages:
  @gar/create-test
Ok to proceed? (y) 
```

**Comment by wraithgar** [comment]
Thank you @rayw000
