### ISSUE TITLE
[BUG] npm: 7.6.1 causes ERR and WARN - dependencies not resolvable

### ISSUE THREAD

**Issue by Sascha-Block** [npm/cli#3467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`npm install` does not solve it...

`npm install npm@latest -g` - does not take any effect either

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for npm@lastest.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

Before that the Warnings prevent an running npm
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'app@0.1.0',
npm WARN EBADENGINE   required: { node: '>=10.16.0 <=14.x.x', npm: '^6.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.15.1', npm: '7.6.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@casl/ability@4.1.6',
npm WARN EBADENGINE   required: { npm: '^6.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.15.1', npm: '7.6.1' }
npm WARN EBADENGINE }

### Expected Behavior

npm should be that robust, that dependencies are solved and WARNINGS are to be eliminated
Even than, when these warnings result in not running applications.

### Steps To Reproduce

1. In this environment I want to install strapi https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/installation/docker.html#creating-a-strapi-project 
2. With this config

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'app@0.1.0',
npm WARN EBADENGINE   required: { node: '>=10.16.0 <=14.x.x', npm: '^6.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.15.1', npm: '7.6.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@casl/ability@4.1.6',
npm WARN EBADENGINE   required: { npm: '^6.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.15.1', npm: '7.6.1' }
npm WARN EBADENGINE }

3. Run 'docker compise 

npm ERR! code ETARGET
npm ERR! notarget No matching version found for npm@lastest.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hamburg/.npm/_logs/2021-06-25T08_35_41_182Z-debug.log

0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'install',
0 verbose cli   'npm@lastest',
0 verbose cli   '-g'
0 verbose cli ]
1 info using npm@7.6.1
2 info using node@v14.15.1
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/Users/hamburg/WebstormProjects/RTP-Strapi/app/.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:/Users/hamburg/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 7ms
19 verbose npm-session 5c85e487a4d7cb06
20 timing npm:load Completed in 13ms
21 timing arborist:ctor Completed in 1ms
22 timing idealTree:init Completed in 7ms
23 http fetch GET 304 https://registry.npmjs.org/npm 157ms (from cache)
24 timing idealTree Completed in 187ms
25 timing command:install Completed in 195ms
26 verbose type tag
27 verbose stack npm: No matching version found for npm@lastest.
27 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:207:23)
27 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:117:26
27 verbose stack     at async Arborist.[retrieveSpecName] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:463:18)
27 verbose stack     at async Promise.all (index 0)
27 verbose stack     at async Arborist.[applyUserRequests] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:419:7)
27 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:207:7)
27 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:130:5)
27 verbose stack     at async Install.install (/usr/local/lib/node_modules/npm/lib/install.js:122:5)
28 verbose cwd /Users/hamburg/WebstormProjects/RTP-Strapi/app
29 verbose Darwin 19.6.0
30 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "npm@lastest" "-g"
31 verbose node v14.15.1
32 verbose npm  v7.6.1
33 error code ETARGET
34 error notarget No matching version found for npm@lastest.
35 error notarget In most cases you or one of your dependencies are requesting
35 error notarget a package version that doesn't exist.
36 verbose exit 1

This issue seems to be related to https://github.com/npm/cli/issues/2728 

### Environment

- OS: macOS Ver. 10.15.7
- Node: node: 'v14.15.1
- npm: npm: '7.6.1'
[2021-06-25T08_35_41_182Z-debug.log](https://github.com/npm/cli/files/6714854/2021-06-25T08_35_41_182Z-debug.log)

**Comment by wraithgar** [comment]
Looks like there's a typo in the Dockerfile somewhere that's causing it to try to install `lastest` not `latest`.

**Comment by Sascha-Block** [comment]
@wraithgar typo corrected, that does not help and wasn't the error, just here in the ticket

rtp-strapi_postgres_1 is up-to-date
Starting rtp-strapi_strapi_1 ... done
Attaching to rtp-strapi_postgres_1, rtp-strapi_strapi_1
postgres_1  | 
postgres_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1  | 
postgres_1  | 2021-06-25 08:30:57.983 UTC [1] LOG:  starting PostgreSQL 13.3 (Debian 13.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
postgres_1  | 2021-06-25 08:30:57.986 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2021-06-25 08:30:57.987 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2021-06-25 08:30:57.996 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2021-06-25 08:30:58.012 UTC [28] LOG:  database system was interrupted; last known up at 2021-06-22 14:08:14 UTC
postgres_1  | 2021-06-25 08:31:00.326 UTC [28] LOG:  database system was not properly shut down; automatic recovery in progress
postgres_1  | 2021-06-25 08:31:00.367 UTC [28] LOG:  redo starts at 0/1688878
postgres_1  | 2021-06-25 08:31:00.367 UTC [28] LOG:  invalid record length at 0/1688960: wanted 24, got 0
postgres_1  | 2021-06-25 08:31:00.367 UTC [28] LOG:  redo done at 0/1688928
postgres_1  | 2021-06-25 08:31:00.405 UTC [1] LOG:  database system is ready to accept connections
strapi_1    | Starting your app...
strapi_1    | [2021-06-25T17:56:19.142Z] debug ⛔️ Server wasn't able to start properly.
strapi_1    | [2021-06-25T17:56:19.145Z] error Error: 'darwin-x64' binaries cannot be used on the 'linux-x64' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the 'linux-x64' platform.
strapi_1    |     at Object.hasVendoredLibvips (/srv/app/node_modules/sharp/lib/libvips.js:80:13)
strapi_1    |     at Object.<anonymous> (/srv/app/node_modules/sharp/lib/constructor.js:7:22)
strapi_1    |     at Module._compile (internal/modules/cjs/loader.js:999:30)
strapi_1    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
strapi_1    |     at Module.load (internal/modules/cjs/loader.js:863:32)
strapi_1    |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
strapi_1    |     at Module.require (internal/modules/cjs/loader.js:887:19)
strapi_1    |     at require (internal/modules/cjs/helpers.js:74:18)
strapi_1    |     at Object.<anonymous> (/srv/app/node_modules/sharp/lib/index.js:3:15)
strapi_1    |     at Module._compile (internal/modules/cjs/loader.js:999:30)
rtp-strapi_strapi_1 exited with code 1

**Comment by wraithgar** [comment]
That is not an npm error, that is Docker complaining about the type of binary you are trying to run.  This is most likely some sort of error with the docker image bundling built assets in `node_modules` that are not rebuilt for the current system.

**Comment by wraithgar** [comment]
Closing, as this doesn't look like an npm error.
