### ISSUE TITLE
[BUG] Please do not check updates when a user wants to get rid of this update-notifier

### ISSUE THREAD

**Issue by mymedia2** [npm/cli#3470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
mymedia@freesia:~$ rm -rf ~/.npm ~/.npmrc 
mymedia@freesia:~$ npm config set update-notifier false
npm notice 
npm notice New minor version of npm available! 7.15.1 -> 7.19.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.19.0
npm notice Run npm install -g npm@7.19.0 to update!
npm notice 
mymedia@freesia:~$ 
```

### Expected Behavior

In such corner case, npm should silently and instantly set the config key without any network access. Other solution would be to ask a user whether they wish to check an update at first run.

### Steps To Reproduce

Type `npm config set update-notifier false` in terminal given that the ~/.npm directory and the ~/.npmrc file do not exist, and a new npm version is available in a registry.

### Environment

- OS: GNU/Linux Ubuntu 21.04 (Hirsute Hippo)
- Node: v16.3.0
- npm: 7.15.1

**Comment by wraithgar** [comment]
I don't think this is a bug.  The notifier check happens when npm is first ran, before the code that changes that config item has had a chance to take effect.

Having that config in place will suppress the check, as well as setting the config item on the cli, e.g.

```sh
$ npm whoami --no-update-notifier
```

or

```
$ npm config set update-notifier false
$ rm ~/.npm/_update-notifier-last-checked // force a check immediately
$ npm whoami
```
