### ISSUE TITLE
Retrieve removed node module

### ISSUE THREAD

**Issue by DraFfe2** [npm/cli#3473]
Hey, 

So i'm very new to node and js in general.  I am working on a couple of react apps that share a lot of code.  So i was working out how to link from a common app's node_moudle.  I made 2 fatal errors, i didn't back up my code and i didn't update the package.json before running npm install... this has removed the files.  Is there away to retrieve the files?  What does npm do with them on remove?

Could any one shed some light please?
Many thanks
Elliott

**Comment by wraithgar** [comment]
npm asks your operating system to delete the files, and what it does after that is up to your operating system.  Recovering them, if possible, would be something best discussed on a general help forum for your operating system.
