### ISSUE TITLE
[BUG] Overriding package.json config values does not work.

### ISSUE THREAD

**Issue by stocksr** [npm/cli#3475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://docs.npmjs.com/cli/v7/configuring-npm/package-json#config descrbes a way of having a config object in your package.json obect and optinally overriding it from your local config. 
>A "config" object can be used to set configuration parameters used in package scripts that persist across upgrades. For instance, if a package had the following:
``` 
{
  "name": "foo",
  "config": {
      "port": "8080"
  }
}
```
> and then had a "start" command that then referenced the npm_package_config_port environment variable, then the user could override that by doing npm config set foo:port 8001.

The override appears to have stopped working in v7, it would appear from [RFC 21](https://github.com/npm/rfcs/blob/latest/implemented/0021-reduce-lifecycle-script-environment.md) that this is intentional. 
>npm_package_config_* Each key in the config object will be included, but npm will not override values with a <pkgname>:<keyname> config value if one exists.

However 
1.  It is still listed as a feature in the docs.
2. It is very useful and no indication of a suitable alternative has been provided.

### Expected Behavior

I would like this behaviour to be re-introduced or an alternative way of doing the same thing provided. 

### Steps To Reproduce

1. In this environment...
(npm version 7)
2. With this config...
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "node -p process.env.npm_package_config_test"
  },
  "config": {
    "test":"It is NOT working"
  },
  "author": "",
  "license": "ISC"
}

```
3. Run '...'
```
npm config set test:test "It Is Working"
npm run test
```
4. See error...
this is output
```
It is not working
```

### Environment

Tested on 
- OS:  Windows 10
- Node: v14.15.1
- npm: 7.19.0

**Comment by wraithgar** [comment]
The docs do need to be cleaned up to reflect the new behavior.  As far as a suitable alternative, suggesting that would be best done through the [rfc](https://github.com/npm/rfcs) process.

**Comment by wu-lee** [comment]
I agree with the OP: this was useful, and its removal is breaking things. So be it. But there still seems to be no recommendations for "suitable alternatives" to have come out of this process anywhere I can see?
