### ISSUE TITLE
[BUG] wrong folder structure when using prefix to install npm locally

### ISSUE THREAD

**Issue by Maxim-Mazurok** [npm/cli#3489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I run `npm install --cache DAT\npm_cache --prefix DAT\npm npm@%_npm_version% --registry http://proget.company.com/npm/Registry/` I'm getting a different folder structure with npm v6 and v7:

With V6 I'm getting
```text
├── node_modules
│   └── npm
│       ├── LICENSE
│       ├── README.md
│       ├── bin
│       ├── docs
│       ├── lib
│       ├── man
│       ├── node_modules
│       ├── npmrc
│       └── package.json
├── npm
├── npm.cmd
├── npm.ps1
├── npx
├── npx.cmd
└── npx.ps1
```

But with V7 I'm getting
```text
├── node_modules
│   ├── .bin
│   │   ├── npm
│   │   ├── npm.cmd
│   │   ├── npm.ps1
│   │   ├── npx
│   │   ├── npx.cmd
│   │   └── npx.ps1
│   ├── .package-lock.json
│   └── npm
│       ├── LICENSE
│       ├── README.md
│       ├── bin
│       ├── docs
│       ├── lib
│       ├── man
│       ├── node_modules
│       └── package.json
├── package-lock.json
└── package.json
```

### Expected Behavior

I'm not sure if the problem is with V6 or with V7, but I need it to be consistent so that I can later set Path accordingly.

So the expected behavior would be to make both versions put `npm.cmd` in the same place.

The workaround is to use `--global` switch when running `npm install ... npm...`, perhaps this is the correct way to create a local installation of npm?

### Steps To Reproduce

1. In Windows, with npm v6 installed (`nvs use lts`),
2. Run `npm install --cache DAT\npm_cache --prefix DAT\npm npm@7`
3. Run `.\DAT\npm\npm -v`
4. See "7.19.0"
5. Uninstall npm v6, install npm v7 (`nvs use latest`)
6. Delete `DAT\npm` folder
7. Run `npm install --cache DAT\npm_cache --prefix DAT\npm npm@7` again
8. Run `.\DAT\npm\npm -v` again
9. See error:
	  ```
	  .\DAT\npm\npm: The term '.\DAT\npm\npm' is not recognized as a name of a cmdlet, function, script file, or executable program.
	  Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
	  ```

### Environment

- OS: Windows 10
	  ```
	  Edition	Windows 10 Pro N
	  Version	21H1
	  Installed on	‎26/‎07/‎2020
	  OS build	19043.1052
	  Experience	Windows Feature Experience Pack 120.2212.2020.0
	  ```
- Node: v16.4.0 / v14.17.1
- npm: 7.18.1 / 6.14.13 (accordingly)

**Comment by wraithgar** [comment]
Yes the folders that npm puts bins in changes depending on if it is in global mode or not.  See here for more info https://docs.npmjs.com/cli/v7/configuring-npm/folders#executables

Making both versions of npm act the same is likely not going to happen, npm@7 was a breaking change from npm@6 and it is acting the way that it is intended.

If you want `npm` to be available to you to run outside of the context of `npm run` or `npm exec` it needs to be  a global installation, and the prefix needs to be in your path.  If you want it to be available inside the context of another package (i.e. as a dependency) then it needs to be accessed during invocations of `npm run` i.e. in other scripts or referred to by name in the `scripts` entry in that other package's package.json
