### ISSUE TITLE
[BUG] [REGRESSION] npm run with package variable doesn't work

### ISSUE THREAD

**Issue by CodeTroopers** [npm/cli#3490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

First, this worked with NPM 6.14

Our package.json has this script:
```
"name": "my_package_name",
"scripts": {
    "set:app_version": "npm --no-git-tag-version --allow-same-version version $npm_package_config_app_version
}
```
Our Gitlab CI run the command :
`npm run set:app_version --my_package_name:app_version=$TAG`

$TAG is equal to 3.0.0

With NPM 7.19.0 ,the command output with : 
```
{
  'my_package_name': '2.4.0,
  npm: '7.19.0',
  node: '16.3.0',
  v8: '9.0.257.25-node.16',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '93',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '6.0.2',
  openssl: '1.1.1k+quic',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}
```

### Expected Behavior

Package version is set to 3.0.0

### Steps To Reproduce

1. Create a package.json with
```
"name": "my_package_name",
"scripts": {
    "set:app_version": "npm --no-git-tag-version --allow-same-version version $npm_package_config_app_version
}
```
2. Run
export TAG=3.0.0
npm run set:app_version --my_package_name:app_version=$TAG

### Environment

- OS: Ubuntu
- Node: 16.3
- npm: 7.19.0

**Comment by wraithgar** [comment]
This functionality (overriding package config via cli) was removed in npm@7. You can read the RFC here: https://github.com/npm/rfcs/blob/latest/implemented/0021-reduce-lifecycle-script-environment.md

The fact that they were left in the docs was an oversight, and will be removed with today's cli release.
