### ISSUE TITLE
npmjs.com scores (quality, popularity, maintenance) seems to be wrong

### ISSUE THREAD

**Issue by darcyclarke** [npm/cli#350]
Original bug ticket: [https://npm.community/t/10664](https://npm.community/t/10664)
      Originally filed: 2019-10-22T20:16:19.690Z

**Comment by jazz-soft** [comment]
https://npm.community/t/10664
The ticket was closed on April 20.
The bug still remains.

**Comment by jazz-soft** [comment]
I wonder if this should be moved to another branch: it is not about the cli, it's about the npmjs.com
