### ISSUE TITLE
npm install -g @vue/cli@next command fails - 

### ISSUE THREAD

**Issue by danushk** [npm/cli#3502]
```
# npm install -g @vue/cli@next
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-02T09_35_38_653Z-debug.log
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[https://i.imgur.com/hz7P54y.png](https://i.imgur.com/hz7P54y.png)

Above is a screenshot of the problem - vue installation fails 

### Expected Behavior

vue installation should pass

### Steps To Reproduce

1.  docker run -it -p 8080:8080 alpine:latest /bin/sh
2. apk add npm
3. npm i -g @vue/cli@next

### Environment

- OS: Debian version 10 (buster) host running Docker alpine container guest
- Node: 14.17.1
- npm: 7.17

**Comment by ljharb** [comment]
Can you try npm v7.19.1?

**Comment by danushk** [comment]
> Can you try npm v7.19.1?

Thanks for the response - this problem arises when network is slow - it found out after discussion at Discord Channel.

**Comment by wraithgar** [comment]
npm `v7.20.0` added some things that should catch more of these network errors. It also added some new debugging messages specifically for this error message. Can you try with that version and also include any debug logs it generates?

**Comment by lukekarrys** [comment]
**Closing:** We suspect this has to do with a combination of resource constraints within the device/program being used and the large amount of transient dependencies being installed by this command.

We've opened https://github.com/npm/statusboard/issues/395 for us to look deeper into this and track the discussion and fixes around it. You can also read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) for more information on why this issue might be happening currently and ways to debug it.
