### ISSUE TITLE
npm audit fix --force giving error

### ISSUE THREAD

**Issue by np1goal** [npm/cli#3510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

npm WARN using --force Recommended protections disabled.
npm WARN audit Updating react-scripts to 4.0.3,which is a SemVer major change.
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm ERR! cb() never called!

### Expected Behavior

I am trying to fix 44 vulnerabilities (25 low, 8 moderate, 11 high) in a react app.

### Steps To Reproduce

1. In this environment...development
2. With this config...
3. Run npm audit fix --force
4. See error...

### Environment

- OS: Mac Catalina 10.15.6
- Node: 12.22.1
- npm: 7.17.0

**Comment by Shubhamsharma585** [comment]
waiting for answer.

**Comment by nlf** [comment]
see #417

try updating to the latest published npm version (8.5.3 at the time of writing this) and try to reproduce the problem. if you're able to, please give us as much information as possible to help us reproduce the problem. the `package.json` and `package-lock.json` files are often critical.
