### ISSUE TITLE
[BUG] Windows nodejs not removing old installation properly and drive C issues.

### ISSUE THREAD

**Issue by davidmather** [npm/cli#3511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am exclusively using drive C (which is a small fast ssd) for windows and everything else should be installed on drive D.
I uninstalled nodejs from drive C and installed https://nodejs.org/dist/v16.4.1/node-v16.4.1-x64.msi to D:\nodejs . Node appears to still be pointing to C:\Program Files and can't escape the space in the name? 

![image](https://user-images.githubusercontent.com/13389155/124388965-0f72d880-dcdd-11eb-8f00-f48a852da91e.png)

It seems to have been an issue with the prefix not being set on install.

![image](https://user-images.githubusercontent.com/13389155/124389409-d50a3b00-dcde-11eb-8653-a5d6c2effa54.png)

Old environment variables pointing to NPM were also not deleted. 

NPM cache is still pointing to drive C and not the install location for NPM.
![image](https://user-images.githubusercontent.com/13389155/124389658-08999500-dce0-11eb-9d3c-b7e52cae8dfb.png)

### Expected Behavior

NPM should update the prefix to the new location on install. Any environment variables obviously pointing to node or npm should be removed from environment variables on uninstall. 

### Steps To Reproduce

1. Uninstall nodejs from add or remove programs
2. Install nodejs and set the install location to another drive
2. Run npm install

### Environment

- OS:  Windows 10 21H1
- Node:  v16.4.1
- npm: 7.18.1

**Comment by nlf** [comment]
we don't control the nodejs uninstaller, so can't really do much to change that situation. since we also can't automatically change the prefix for you because we have no idea what you want it to be, and guessing is more harmful than leaving it alone, this looks to be entirely issues within that installer. for help with those, you'll have to open an issue at https://github.com/nodejs/node
