### ISSUE TITLE
cb() never called!

### ISSUE THREAD

**Issue by me-masoud** [npm/cli#3512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i was just installing node (npm i ) in laravel project and this error has occurred .

***********************

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

### Expected Behavior

expect to install node module 

### Steps To Reproduce

i got the error on this command : npm install

[
[Uploading 2021-07-04T13_20_12_036Z-debug.log…]()
](url)

### Environment

- OS: windows 10
- Node:  14.16.1
- npm: 7.12.0

**Comment by DavidQuartz** [comment]
Facing the same bug. 
## Environment
- OS: MacOS Big Sur
- Node: v14.17.0
- npm: 7.16.0

**Comment by InfinityAkshay** [comment]
Facing the same bug.

## Environment
OS: Windows 10
Node: v14.17.2
npm: 6.14.13

**Comment by codecooker0105** [comment]
me too.
### **Environment**
OS: win10
Node: v14.15.1
npm: 6.14.8

**Comment by DavidQuartz** [comment]
I solved it by updating my npm

**Comment by rluvaton** [comment]
Try:
1. removing the node modules
2. Remove package-lock.json & option 1
3. Run `npm cache clean -f` & Option 2


That's usually solve it for me

**Comment by lukekarrys** [comment]
**Closing:** We suspect this has to do with a combination of resource constraints within the device/program being used and the large amount of transient dependencies being installed by this command.

We've opened https://github.com/npm/statusboard/issues/395 for us to look deeper into this and track the discussion and fixes around it. You can also read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) for more information on why this issue might be happening currently and ways to debug it.
