### ISSUE TITLE
[BUG] <titlenpm ERR! Error: EPERM: operation not permitted, rename 'C:\Program Files\nodejs\node_modules\npm' -> 'C:\Program Files\nodejs\node_modules\.npm-QXjMEw5N'>

### ISSUE THREAD

**Issue by UltimateCodeWarrior** [npm/cli#3513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

NPM won't update / install.    You need a much better QA Team! 

npm install -g npm@7.19.1

C:\Users\shane>npm install -g npm@7.19.1
npm ERR! code EPERM
npm ERR! syscall rename
npm ERR! path C:\Program Files\nodejs\node_modules\npm
npm ERR! dest C:\Program Files\nodejs\node_modules\.npm-QXjMEw5N
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Program Files\nodejs\node_modules\npm' -> 'C:\Program Files\nodejs\node_modules\.npm-QXjMEw5N'
npm ERR!  [Error: EPERM: operation not permitted, rename 'C:\Program Files\nodejs\node_modules\npm' -> 'C:\Program Files\nodejs\node_modules\.npm-QXjMEw5N'] {
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Program Files\\nodejs\\node_modules\\npm',
npm ERR!   dest: 'C:\\Program Files\\nodejs\\node_modules\\.npm-QXjMEw5N'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\shane\AppData\Local\npm-cache\_logs\2021-07-04T20_52_55_775Z-debug.log

### Expected Behavior

I expected that it would work flawlessly the first time, this is why Developers switched over to package managers, otherwise all it did was create an even bigger mess to straighten out.  

### Steps To Reproduce

Windows 10 latest
64 bit OS
run cmd listed at very top of bug report.  
get real frustrated that NPM can't auto send a bug report back to the team so they can instantaneously see millions of failures from their last release before a holiday weekend.    I mean really, why isn't this baked into this thing?  Should be Feature of the highest priority. 
 

### Environment

- OS: 
- Node: 
- npm:

**Comment by sinclairzx81** [comment]
@UltimateCodeWarrior I'm currently seeing this issue. Did you ever find a resolution to this?

I could be mistaken here, but I'm pretty sure the install path for global packages should be  `C:/Users/<User>/AppData/Roaming/npm/node_modules`? and not `C:/Program Files/nodejs`. 

Currently running `npm@7.24.1` (off a fresh install of Node) and seeing similar errors.

**Comment by nlf** [comment]
this is a known issue. see #4341 for context. the summary is here https://github.com/npm/cli/issues/4341#issuecomment-1040608101

closing this as a duplicate
