### ISSUE TITLE
Do not conflict on meta-peers that will not be replaced

### ISSUE THREAD

**Issue by NickCarducci** [npm/cli#3514]
>@strican It's in @npmcli/arborist 1.0.4, which is included in npm 7.0.4 https://github.com/npm/cli/releases.
>
>This issue has gotten quite a few "me too" comments that are in fact different examples, with different versions of npm in some cases.  Please post new issues for problems that occur with different packages, or using different versions of npm.  The original post here has been root-caused, addressed, and verified fixed.
>
>If you are in fact having *the same* problem, then the solution is to update to the latest release of npm, where this issue is fixed.  If you are having a different issue with the same error code, with different packages, using the latest version of npm, then please post a new issue.  We cannot get to the bottom of your problem any other way.
>
>Thus, I am lovingly and compassionately locking this issue, to force y'all to actually get help from us <3
>
>_Originally posted by @isaacs in >https://github.com/npm/cli/issues/2000#issuecomment-717622366_

B-I-N-G-O; winner-winner, chicken-dinner
````
% npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: react-fuffer@1.0.0
npm ERR! Found: webpack@5.42.0
npm ERR! node_modules/webpack
npm ERR!   peer webpack@"5.42.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"4.x.x" from webpack-cli@3.3.12
npm ERR! node_modules/webpack-cli
npm ERR!   peer webpack-cli@"^3.3.12" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
````
Here I have the same error which `npm: 7.19.1` cannot handle without using `--force` after `npm install `.  Are we meant to just, live like this?  Seems to be just a parsing error.  Thanks team!

**Comment by ljharb** [comment]
This is a legitimate issue with your dep graph. You seem to have two requirements that are incompatible: webpack 3 and 5. Your dep graph isn’t valid until either the 5 things are downgraded, or the 3 things are upgraded.

(altho the messages imply that the root project directly peer depends on both 3 and 5, which is certainly confusing)

**Comment by NickCarducci** [comment]
https://github.com/facebook/react/issues/13018: might be related to other react users, but for npm, a feature suggestion tho you're probably aware:

I can install as an alias (`webpack-legacy@npm:webpack@4.44.1` & `webpack-newest@npm:webpack@latest`), but cannot find a way to point peer dependencies to their respective `alias dependencies`.  I guess the npm team made something abstracted with `--force` for this reason, instead of - for instance - mentioning the `alias dependency` in the `peerDependency` that requires the legacy version (`babel-loader@8.2.2`) appended like `babel-loader@8.2.2_webpack-legacy`.  Using `npm install --force` `npm pack` and `npm install ./<name.tgz> --force` seems to work with this setup fine, testing before publishing:

//after `npm install --force` `npm uninstall @babel/polyfill --save` depreciated for `"core-js": "3.6.5"` & `"regenerator-runtime": "^0.13.7"` without `^` latest so as to not revert
_
package.json
````
{
    "name": "react-fuffer",
    "version": "1.0.0",
    "description": "react-buffer-firestore",
    "main": "src/index.js",
    "keywords": [],
    "repository": {
        "type": "git",
        "url": "https://github.com/nickcarducci/react-fuffer"
    },
    "files": [
        "src",
        "index..js"
    ],
    "sideEffects": false,
    "license": "UNLICENSED",
    "author": "Nick Carducci nick@carducci.sh",
    "bugs": {
        "url": "https://github.com/nickcarducci/react-fuffer"
    },
    "scripts": {
        "build": "webpack"
    },
    "dependencies": {
        "@babel/runtime": "^7.12.0",
        "pouchdb": ">=7.1.1",
        "pouchdb-upsert": ">=2.2.0",
        "react": ">=16.8.0",
        "react-dom": ">=16.8.0"
    },
    "devDependencies": {
        "babel-core": "^6.21.0",
        "babel-loader": "^8.2.2",
        "core-js": "^3.6.5",
        "path": "^0.12.7",
        "regenerator-runtime": "^0.13.7",
        "webpack": "^5.42.0"
    },
    "peerDependencies": {
        "pouchdb": ">=7.1.1",
        "pouchdb-upsert": ">=2.2.0",
        "react": ">=16.8.0",
        "react-dom": ">=16.8.0"
    },
    "resolutions": {
        "react": "^17.0.0",
        "react-dom": "^17.0.0"
    },
    "preconstruct": {
        "entrypoints": [
            "."
        ]
    }
}
````
webpack.config.js
````const path = require('path');
const webpack = require('webpack')
const pkg = require('./package.json')

module.exports = {
    target: 'web',
    devtool: false,
    entry: {
        [pkg.name]: './src/',
        /*resolve: {
            alias: {
                'react': path.resolve(__dirname, './node_modules/react'),
                'react-dom': path.resolve(__dirname, './node_modules/react-dom'),
            }
        },
        externals: {
            // Don't bundle react or react-dom      
            react: {
                commonjs: "react",
                commonjs2: "react",
                amd: "React",
                root: "React"
            },
            "react-dom": {
                commonjs: "react-dom",
                commonjs2: "react-dom",
                amd: "ReactDOM",
                root: "ReactDOM"
            }
        }*/
    },
    externals: {
        react: 'React',
        'react-dom': 'ReactDOM',
    },
    mode: 'production',
    output: {
        path: path.resolve(__dirname, "./src"),
        filename: 'index.js',
        libraryTarget: 'src',
        library: 'localPhoto',
        publicPath: '/',
        pathinfo: true,
        //libraryTarget: 'commonjs2',
    },
    plugins: [
        new webpack.DefinePlugin({
            'process.env.NODE_ENV': JSON.stringify('production'),
        }),
    ],
    module: {
        rules: [
            {
                test: /\.js?$/,
                exclude: /(node_modules)/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: ['@babel/env', '@babel/react', {
                            'plugins': ['@babel/plugin-proposal-class-properties']
                        }],

                        //presets: ['env', 'react']
                    }
                }
            },
        ],
    },
    performance: {
        maxEntrypointSize: 750000,
        maxAssetSize: 750000,
    },
    optimization: {
        minimizer: [
            new TerserPlugin({
                terserOptions: {
                    output: {
                        comments: false,
                    },
                },
            }),
        ],
    },
}
````
Thanks Jordan!

**Comment by ljharb** [comment]
Yes, aliases aren't for that - the feature you want is "overrides" or "resolutions", which npm has not yet added.
