### ISSUE TITLE
CB() never called error during docker build

### ISSUE THREAD

**Issue by sarsampath** [npm/cli#3516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

#11 154.4 npm ERR! cb() never called!
#11 154.4 
#11 154.4 npm ERR! This is an error with npm itself. Please report this error at:
#11 154.4 npm ERR!     <https://npm.community>
#11 154.7
#11 154.8 npm ERR! A complete log of this run can be found in:
#11 154.8 npm ERR!     /root/.npm/_logs/2021-07-05T14_19_27_535Z-debug.log
------

### Expected Behavior

Latest version of Npm and Node should install using docker

### Steps To Reproduce

FROM node:14-alpine3.12 as build-step
WORKDIR /usr/src/app
COPY package.json package-lock.json ./
COPY . .
ENV HTTPS_PROXY="http://on.cypress.io/proxy-configuration"
RUN npm cache verify && npm install 
RUN CMD["npm","start"]
FROM nginx:1.19-alpine
COPY --from=build-step /usr/src/app/dist/AngularApp-Shell/ /usr/share/nginx/html

### Environment

- OS: 
- Node: 
- npm:

**Comment by shirshak55** [comment]
i am also seeing similar errors. Maybe I need to stick to yarn.

**Comment by wraithgar** [comment]
npm `v7.20.0` added some things that should catch more of these network errors. It also added some new debugging messages specifically for this error message. Can you try with that version and also include any debug logs it generates?

**Comment by shirshak55** [comment]
@wraithgar i am very surprised about this instruction. I just went to nodejs.org downloaded the latest node which is supposed to have the latest npm but the version I got was 7.19.1?  I am on windows so I usually use msi images to upgrade which is correct way afaik?

**Comment by ljharb** [comment]
the latest node only has the latest npm at the time it was released; the latest npm was released after every current node version. run `npm install -g npm`.
