### ISSUE TITLE
[BUG] <Issue with registry while installing mailslurp helper>

### ISSUE THREAD

**Issue by mads1814** [npm/cli#3517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to install this helper Mailslurp provided for codecepjs. [Email Testing](https://codecept.io/email/#installation)

`npm i @codeceptjs/mailslurp-helper --save`

However it gives 500 error each time I try to install. Me and my colleagues can install all packages EXCEPT this one.

```
npm ERR! code E500
npm ERR! 500 Internal Server Error - 
```
Note: I did clean cache, removed node module and project and started fresh, still the same error. Also .npmrc file is correctly set with registry set to true. 

### Expected Behavior

Package must install smoothly

### Steps To Reproduce

1. In test automation project of codecepjs
2. I entered `npm i @codeceptjs/mailslurp-helper --save` in terminal and hit enter
3. I see error
```
npm ERR! code E500
npm ERR! 500 Internal Server Error - GET https://baseurl.com/Project/_packaging/Packages/npm/registry/mailslurp-client - InternalServerError

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.npm/_logs/debug.log
```

### Environment

- OS: macOS Big Sur (v 11.4)
- Node: 12.16.3
- npm: 6.14.4

**Comment by ljharb** [comment]
Seems like it's an issue with "baseurl.com", not npm - either way, try with npm 7 latest?

**Comment by mads1814** [comment]
Issue seems to be mailslurp and codeceptjs versions. Reported issue to mailslurp helper. Not an npm issue i guess. Thanks!!
