### ISSUE TITLE
html pages come scattered between pages when i print them with html2pdf library in javascript

### ISSUE THREAD

**Issue by muhamedoufi** [npm/cli#3518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`Any one can solve this`

### Expected Behavior

html2pdf is printing a pdf but the write is choppy between pages how to solve?

this my code javascript if you need to html i can comment it, any one have an idea ? please help me!

```
window.onload = function () {
              document.getElementById("download")
                  .addEventListener("click", () => {
                      const invoice = this.document.getElementById("invoice");
                      console.log(invoice);
                      console.log(window);
                      var opt = {
                          margin: 1,
                          filename: 'myfile.pdf',
                          image: { type: 'png', quality: 0.98 },
                          html2canvas: { scale: 2 },
                          jsPDF: { unit: 'pt', format: 'a4', orientation: 'landscape'}
                          // p\init : pt   unit: 'in', format: 'letter', orientation: 'landscape' 
                      };
                      html2pdf().from(invoice).set(opt).save();
                  })
          }
```
On stackoverflow.com 

_______ https://stackoverflow.com/questions/68218627/html-pages-come-scattered-between-pages-when-i-print-them-with-html2pdf-library
________

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- OS: 
- Node: 
- npm:

**Comment by shadowspawn** [comment]
This repo is for the `npm` command-line tool itself, not for all of the many npm modules.

You could try asking on support forums for the `html2pdf` library you are using.
