### ISSUE TITLE
[BUG] npx/npm exec don't work in child workspace when using --no/--no-install and --package

### ISSUE THREAD

**Issue by rossng** [npm/cli#3520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using NPM workspaces. I am running a command of the format:

```
npm exec --no --workspace=my-workspace --package @graphql-codegen/cli -- graphql-codegen --config codegen.js
```

It fails with a rather terse `npm ERR! canceled`.

This is related to a previous issue #2826. The bug was partially resolved by @ruyadorno in https://github.com/npm/libnpmexec/pull/2. However, looking at the commit, it seems that the fix was only applied inside the `if (needPackageCommandSwap)` block. This only executes if no `--package` option has been specified.

If `--package` is specified, then the code falls through to https://github.com/npm/libnpmexec/blob/a9423e441b914571ec18ad8a4496a3ecf2f500e2/lib/index.js#L153. It will then try to install the package (even though it's already available locally). However, if `--no[-install]` is specified, it will simply throw an exception instead.

### Expected Behavior

The `npm exec` and `npx` commands should work when used in a workspace with the `--package` and `--no[-install]` options.

### Environment

- OS: Windows
- Node: 16.4.0
- npm: 7.19.1

**Comment by nlf** [comment]
we've made a lot of changes to workspaces in the last several months, can you test this in npm 8.5.3 and let us know if it's fixed?

**Comment by rossng** [comment]
I moved my original project to pnpm in the end, so I reproduced this problem by:

- Cloning https://github.com/Quramy/npm-ts-workspaces-example
- `cd packages/x-cli`
- `npm install --save-dev @graphql-codegen/cli`
- `npm exec --no --workspace=@quramy/x-cli --package @graphql-codegen/cli -- graphql-codegen`

I still see the same output:

```
npm ERR! canceled
```

**Comment by wraithgar** [comment]
That repo really helps, thanks.

Logs don't give much info
```
33 timing command:exec Completed in 391ms
34 verbose stack Error: canceled
34 verbose stack     at exec (/Users/wraithgar/.nvm/versions/node/v16.14.0/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:156:17)
34 verbose stack     at async Exec.execWorkspaces (/Users/wraithgar/.nvm/versions/node/v16.14.0/lib/node_modules/npm/lib/commands/exec.js:97:7)
34 verbose stack     at async module.exports (/Users/wraithgar/.nvm/versions/node/v16.14.0/lib/node_modules/npm/lib/cli.js:66:5)
35 verbose cwd /Users/wraithgar/Development/npm/scratch/npm-ts-workspaces-example/packages/x-cli
```

**Comment by rossng** [comment]
Yeah, the log output is no use at all. But I found it easy to step through with the debugger when I first encountered it - looks like [the relevant code](https://github.com/npm/libnpmexec/blob/e1378fc8b8e2243765b068d8eb45aba7d01d45bd/lib/index.js#L154) hasn't changed much since.
