### ISSUE TITLE
[BUG] ERROR

### ISSUE THREAD

**Issue by anshtyagi0** [npm/cli#3532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name " sweetalert ": name cannot contain leading or trailing spaces; name can only contain URL-friendly characters

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-07-10T04_42_03_113Z-debug.log

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- OS: 
- Node: 
- npm:

**Comment by ljharb** [comment]
The error message seems self-explanatory.
