### ISSUE TITLE
[BUG] via field missing despite vulnerable dependency is not direct

### ISSUE THREAD

**Issue by naugtur** [npm/cli#3534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running `npm audit --json` in this branch here https://github.com/mgdodge/rollup-plugin-vue-treeshake-bug-vue3/tree/vue2
I observe lodash, which is not a direct dependency but deduped to the top - doesn't get mentioned in any of the `via` fields and its `effects` is empty.

```js
 "lodash": {
                "name": "lodash",
                "severity": "high",
                "via": [
                    {
                        "source": 1673,
                        "name": "lodash",
                        "dependency": "lodash",
                        "title": "Command Injection",
                        "url": "https://npmjs.com/advisories/1673",
                        "severity": "high",
                        "range": "<4.17.21"
                    }
                ],
                "effects": [],
                "range": "<4.17.21",
                "nodes": [
                    "node_modules/lodash"
                ],
                "fixAvailable": true
            },
```

Other dependencies also affected in a similar way. My hypothesis is it has something to do with dedupe.

### Expected Behavior

Produce correct dependency tree information in `via` fields

### Steps To Reproduce

1. git clone git@github.com:mgdodge/rollup-plugin-vue-treeshake-bug-vue3.git
2. cd rollup-plugin-vue-treeshake-bug-vue3
3. git checkout vue2
4. npm audit --json 
OR
5. npm audit --json | grep -B4 -A4 lodash

exact link to the package-lock.json at the revision used to reproduce https://github.com/mgdodge/rollup-plugin-vue-treeshake-bug-vue3/blob/031b3e104f4030e4a43d9b6454291017c1e8c5ad/package-lock.json

### Environment

- OS: linux
- Node: 16.2.0
- npm: 7.13.0 (latest)

**Comment by nlf** [comment]
the root cause here is #4366 so i'm closing this issue as a duplicate
