### ISSUE TITLE
[BUG] "npm install < dependency >" appears to ignore the package-lock file that belongs to that dependency 

### ISSUE THREAD

**Issue by npomfret** [npm/cli#3538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am installing a dependency via a private GitHub repo: 
`npm install "git+ssh://git@github.com/foo/bar.git#${COMMIT_HASH}" --save`

That dependency has it's own `package.json` and `package-lock.json` file in which we have:

```
  "dependencies": {
   ...
    "ccxt": "^1.52.41",
```
and
```
    ...
    "ccxt": {
      "version": "1.52.41",
      "resolved": "https://registry.npmjs.org/ccxt/-/ccxt-1.52.41.tgz",
    ...
```

I am expecting to see the same version of my dependency's dependency in my package-lock file, but I do not.  Instead I get the latest version of it:

```
    ...
    "ccxt": {
      "version": "1.52.94",
      "resolved": "https://registry.npmjs.org/ccxt/-/ccxt-1.52.94.tgz",
    ...
```

### Expected Behavior

I am expecting my package-lock file to contain the version of ccxt that my dependency needs (in this case v1.52.41). I just want a repeatable build, I thought using lock files was the answer.  Or am I doing something wrong?

### Environment

- OS: osx 11.4
- Node: v14.17.0
- npm: 6.14.13

**Comment by ljharb** [comment]
That is by design - package-lock is dev-only and isn’t even published with the package (and wouldn’t be looked at if it were).

Publishing a lockfile in a package that consumers will respect is possible with npm-shrinkwrap.json, but it is a very bad idea, and user-hostile, since it prevents consumers from deduping packages or automatically updating transitive deps through their semver ranges.

Only the top-level app should be concerned with a repeatable build; not something published.

**Comment by npomfret** [comment]
So the dependencies I get when I call `npm install ... --save` are totally random?  It's just whatever is 'out there' at the time?

**Comment by ljharb** [comment]
That’s not random at all - but yes, it’s only deterministic when you take into account “what’s published at the time”.

This is a feature - it’s a good thing. It’s how bugfixes and security fixes can freely flow to consumers without everyone having to do busy work.

**Comment by npomfret** [comment]
Thanks for the info, I do appreciate it.  I have learned something.

But we can disagree on if or not this is a good thing. It is random as far as I can see.  I have no idea what version I'm going to get because if someone published a new version just before I install, then that's the one I'll get.

The entire reason I found this is because I picked up a very broken sub-dependency when I installed my dependency.  It's definitely not a good thing in my opinion.  I not only need a repeatable build, but also a predicable build. I want to pick up "bug fixes" when I'm ready, and by updating my deps in a timely and intentional way.

You argument, I think, is invalid.  Because once my lock file is place, I will no longer pick up any "bug fixes", right?  I have to manually, and intentionally update my deps from that point on.  For that reason, it makes sense to honour the lock file that in the sub-dependency, because that is the version of the code that has been tested.  The current npm appears to mix approaches - this is not good.

**Comment by ljharb** [comment]
Semver means that a `^` range only includes fixes and additions, not breaking changes. Bugs can happen, sure, but you _want_ to get the newest possible in-range version of every package.

You're correct that the package's dev-only lockfile matches what's been tested. However, the tradeoff is that repeatability/predictability/determinism are in practice *much less important* than being able to get the best/safest/most fixed possible compatible version of each package whenever you install something new.

**Comment by npomfret** [comment]
Again, we disagree, but that's cool.  I understand your point.

Getting the latest/best/fixed version when you install is good, yes.  But this helpfulness stops immediately if you use a lock file - you never get fixes ever again until you manually update your deps.  So it's cool, but kind of pointless.  I would MUCH rather have tested code from known versions, not some random (potentially broken) version that's just been pushed.  

The feature you like just doesn't add nearly as much value as you say it does (if you use a lock file).  There is nothing more important to me than repeatability/predictability/determinism. My app trades over 6B USD per day - I need to know what code I'm running.

**Comment by ljharb** [comment]
Yes, you do - even with a lockfile, when you `npm update foo` or `npm install foo`, you will update your lockfile to include the latest versions of all transitive deps of `foo`.

I work at Coinbase; npm's approach works perfectly fine for much larger transaction volumes than that.

**Comment by npomfret** [comment]
When it's your money at risk you might feel differently.
