### ISSUE TITLE
[BUG] <title> npm install error in project https://github.com/SmartMeshFoundation/VISwap-DApp

### ISSUE THREAD

**Issue by xinminsu** [npm/cli#3544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

npm WARN deprecated ethashjs@0.0.8: New package name format for new versions: @ethereumjs/ethash. Please update.
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sxm/.npm/_logs/2021-07-14T02_01_08_991Z-debug.log

### Expected Behavior

sucess
[Uploading 2021-07-14T02_01_08_991Z-debug.log…]()

### Steps To Reproduce

1. git clone https://github.com/SmartMeshFoundation/VISwap-DApp.git
2. rm -rf package-lock.json
3. npm install
4. See error...

[2021-07-14T02_01_08_991Z-debug.log](https://github.com/npm/cli/files/6813161/2021-07-14T02_01_08_991Z-debug.log)

### Environment

- OS: Ubuntu 20.04
- Node: v14.17.2
- npm: 6.14.13

**Comment by xinminsu** [comment]
could you please to have a look? if still can not find the root cause, close it is ok.

**Comment by ljharb** [comment]
@xinminsu can you try with npm 7 latest?

**Comment by xinminsu** [comment]
after i download node-v16.4.2-linux-x64.tar.xz  which  npm -v  7.18.1,   npm install is ok. this bug is disappeared.
