### ISSUE TITLE
[BUG] <Fix the upstream dependency conflict while creating new angular project>

### ISSUE THREAD

**Issue by sayandeep-volition** [npm/cli#3547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While creating the Angular Project.

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: angular-beginner@0.0.0
npm ERR! Found: jasmine-core@3.7.1
npm ERR! node_modules/jasmine-core
npm ERR!   dev jasmine-core@"~3.7.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer jasmine-core@">=3.8" from karma-jasmine-html-reporter@1.7.0
npm ERR! node_modules/karma-jasmine-html-reporter
npm ERR!   dev karma-jasmine-html-reporter@"^1.5.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.`

### Expected Behavior

Right now I have downgraded the NPM version to 6 and it's running.

### Steps To Reproduce

When I'm going to create the angular project using `ng new <project-name>`

### Environment

- OS:  Windows 10 Home
- Angular CLI: 12.1.1
-Node: 14.17.3
-Package Manager: npm 7.19.1

**Comment by ljharb** [comment]
The error message tells you that your project requires just v3.7.x of jasmine-core, but the version of karma-jasmine-html-reporter requires v3.8 of jasmine-core or higher.

The simplest path is likely for you to upgrade to `^3.7.0` of jasmine-core - the wider semver range would have allowed this to succeed.
