### ISSUE TITLE
[BUG] publishing a tarball does not include readme

### ISSUE THREAD

**Issue by wraithgar** [npm/cli#3548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When publishing from a tarball, the `readme` attribute is not in the manifest.

### Expected Behavior

`fullMetadata: true` in `pacote.manifest` works properly for tarballs.

### Steps To Reproduce

This was technically introduced in [`npm@7.0.8`](https://github.com/npm/cli/pull/2074) but that was because that was when publishing from a tarball was added back in to `v7`.  This has likely never worked in `v7`.

https://github.com/npm/cli/blob/665a7bde900d7fbf46aca609b0b9c92b5508a3ea/lib/publish.js#L193-L197

```javascript
> m = pacote.manifest('.', { fullMetadata: true })
Promise { <pending> }
> m
Promise {
  {
    name: 'npm-readme-repro',
    version: '1.0.0',
    description: 'Example publishing an npm package.',
    main: 'index.js',
    scripts: { test: 'echo "Error: no test specified" && exit 1' },
    repository: {
      type: 'git',
      url: 'git+https://github.com/jcansdale-test/npm-readme-repro.git'
    },
    keywords: [],
    author: 'Gar <gar+npm@danger.computer>',
    license: 'ISC',
    bugs: {
      url: 'https://github.com/jcansdale-test/npm-readme-repro/issues'
    },
    homepage: 'https://github.com/jcansdale-test/npm-readme-repro#readme',
    _id: 'npm-readme-repro@1.0.0',
    _integrity: null,
    _resolved: '/Users/wraithgar/Development/npm/npm-readme-repro',
    _from: 'file:',
    [Symbol(newline)]: '\n',
    [Symbol(indent)]: '  '
  }
}
```

### Environment

See steps to reproduce for relevant environment info.

**Comment by eligao** [comment]
Same here. "readme" gone missing on NPM v7 and v8, but works well on v6

**Comment by fritzy** [comment]
This just got merged for this week's release.
