### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by shirshak55** [npm/cli#3549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

npm WARN tar TAR_ENTRY_ERROR UNKNOWN: unknown error, open 'C:\Users\quantum\Desktop\projects\http-toolkit\httptoolkit-ui\node_modules\openapi-directory\api\azure.com\sql-DatabaseSecurityAlertPolicies.json'
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\quantum\AppData\Local\npm-cache\_logs\2021-07-15T16_55_24_795Z-debug.log

### Expected Behavior

I am not supposed to see such errors.

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

git clone https://github.com/httptoolkit/httptoolkit-ui.git
Run npm install on some projects and see those errors. Yarns works fine.

### Environment

- OS: Windows 
- Node:  16
- npm: 7.10.0

**Comment by wraithgar** [comment]
Please try this using the latest version of npm.  Also please include the log file it generates if possible.

See this wiki entry for more info: https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22
