### ISSUE TITLE
[BUG] <cb() never called>

### ISSUE THREAD

**Issue by deepakraj1110** [npm/cli#3551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

182 silly pacote version manifest for ts-pnp@1.2.0 fetched in 331ms
183 silly resolveWithNewModule ts-pnp@1.2.0 checking installable status
184 http fetch GET 304 https://registry.npmjs.org/url-loader 300ms (from cache)
185 silly pacote version manifest for url-loader@4.1.1 fetched in 320ms
186 silly resolveWithNewModule url-loader@4.1.1 checking installable status
187 http fetch GET 304 https://registry.npmjs.org/webpack 256ms (from cache)
188 silly pacote version manifest for webpack@4.44.2 fetched in 338ms
189 silly resolveWithNewModule webpack@4.44.2 checking installable status
190 http fetch GET 304 https://registry.npmjs.org/webpack-manifest-plugin 225ms (from cache)
191 http fetch GET 200 https://registry.npmjs.org/workbox-webpack-plugin 204ms
192 http fetch GET 304 https://registry.npmjs.org/webpack-dev-server 247ms (from cache)
193 silly pacote version manifest for webpack-manifest-plugin@2.2.0 fetched in 252ms
194 silly resolveWithNewModule webpack-manifest-plugin@2.2.0 checking installable status
195 silly pacote version manifest for workbox-webpack-plugin@5.1.4 fetched in 229ms
196 silly resolveWithNewModule workbox-webpack-plugin@5.1.4 checking installable status
197 silly pacote version manifest for webpack-dev-server@3.11.1 fetched in 274ms
198 silly resolveWithNewModule webpack-dev-server@3.11.1 checking installable status
199 http fetch GET 304 https://registry.npmjs.org/fsevents 221ms (from cache)
200 silly pacote range manifest for fsevents@^2.1.3 fetched in 243ms
201 silly resolveWithNewModule fsevents@2.3.2 checking installable status
202 http fetch GET 304 https://registry.npmjs.org/babel-loader 354712ms attempt #2 (from cache)
203 http fetch GET 304 https://registry.npmjs.org/babel-eslint 354721ms attempt #2 (from cache)
204 silly pacote version manifest for babel-loader@8.1.0 fetched in 354737ms
205 silly resolveWithNewModule babel-loader@8.1.0 checking installable status
206 silly pacote range manifest for babel-eslint@^10.1.0 fetched in 354746ms
207 warn deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
208 silly resolveWithNewModule babel-eslint@10.1.0 checking installable status
209 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2fparser 356967ms attempt #2
210 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint/parser/-/parser-4.28.3.tgz 146ms
211 silly pacote range manifest for @typescript-eslint/parser@^4.5.0 fetched in 357198ms
212 silly resolveWithNewModule @typescript-eslint/parser@4.28.3 checking installable status
213 timing npm Completed in 361783ms
214 error cb() never called!

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- OS: 
- Node: 
- npm:

**Comment by rebelwolfson** [comment]
the same:

```
npm i --save react-scripts


npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     ...........................
```
[2021-07-16T12_59_48_649Z-debug.log](https://github.com/npm/cli/files/6830785/2021-07-16T12_59_48_649Z-debug.log)

**Comment by troyyer** [comment]
got the same error when running npm install for the following project https://github.com/percy/example-percy-webdriverio
Trying to run above code base and after cloning the code onto my local machine, I open the code is VSCode and in the VSCdoe Terminal run `npm install`
I then get the following error 
```
error cb() never called!
error This is an error with npm itself. Please report this error at:
error <https://github.com/npm/cli/issues>
```

[2021-07-19T12_07_38_299Z-debug.log](https://github.com/npm/cli/files/6840808/2021-07-19T12_07_38_299Z-debug.log)

**Comment by pjc2007** [comment]
I also got this, and the output asked me to report (npm version 6.14.13)

```
$ npm i
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>
```
Attached log file...
[2021-07-26T07_53_33_602Z-debug.log](https://github.com/npm/cli/files/6876528/2021-07-26T07_53_33_602Z-debug.log)

**Comment by pjc2007** [comment]
I updated npm to latest and this is now fixed for me

**Comment by wilecoyte78** [comment]
I get this error when upgrading to latest: 7.20.2:

npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

Could be related to https://github.com/npm/cli/issues/3577

After running npm cache clean --force both this error and the error from 7.20.2 went away. Try running npm cache clean --force first and run npm install again and see if the error goes away.

**Comment by ewertonmac** [comment]
I had the same error trying to install angular/cli

**Comment by KarrthikC** [comment]
im updating npm then this issue got solved

**Comment by akhilkineton** [comment]
Strangely for me deleting the package-lock.json and running npm install worked

**Comment by lukekarrys** [comment]
**Closing:** We suspect this has to do with a combination of resource constraints within the device/program being used and the large amount of transient dependencies being installed by this command.

We've opened https://github.com/npm/statusboard/issues/395 for us to look deeper into this and track the discussion and fixes around it. You can also read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) for more information on why this issue might be happening currently and ways to debug it.
