### ISSUE TITLE
[BUG] 7.20.0 - incorrect interaction with workspace postinstall scripts (worked on 7.19.1)

### ISSUE THREAD

**Issue by TomFoyster** [npm/cli#3553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running `npm i` from the project root - the  script referenced as the `postinstall` script in the workspace package json **is called**. This should not be called when installing from the project root. 

### Expected Behavior

As in `7.19.1`, when running `npm i` from the project root - the  script referenced as the `postinstall` script in the workspace package json **is not called**.

### Steps To Reproduce

Please see https://github.com/TomFoyster/npm.7.20.0.bug

### Environment

- OS: Mac OS 11.2.3
- Node: 15.4.0
- npm: 7.20.0

**Comment by TomFoyster** [comment]
Apologies - the attached repo has now been made public.

**Comment by gavinsharp** [comment]
Why don't you expect `postinstall` to be called in this scenario? Per https://github.com/npm/cli/issues/3065 and https://github.com/npm/cli/issues/2900 I think the behaviour change in 7.20.0 was a bug fix for previously broken functionality.

**Comment by nlf** [comment]
> Why don't you expect `postinstall` to be called in this scenario? Per #3065 and #2900 I think the behaviour change in 7.20.0 was a bug fix for previously broken functionality.

this is exactly the case. the `postinstall` script for each workspace is meant to be run in this use case. i'm closing this as the current behavior is the intended one.
