### ISSUE TITLE
[BUG] RxwebValidators: Type 'string' is not assignable to type 'string[] | undefined'.ts(2322) in image validation

### ISSUE THREAD

**Issue by noblemfd** [npm/cli#3557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I got this error on the component:

> Type 'string' is not assignable to type 'string[] | undefined'.ts(2322)
extension-config.d.ts(3, 5): The expected type comes from property 'extensions' which is declared here on type 'ExtensionConfig'
(property) ExtensionConfig.extensions?: string[] | undefined

and this code is highlighted:

> extensions:["jpeg","gif"]

### Expected Behavior

I expected the page to load and validate the image

### Steps To Reproduce

In my Angular-12 project, I am trying to validate image before submitting the form using RxwebValidators

I have this component:

    import {
      Component,
      OnInit
    } from '@angular/core';
    import {
      FormGroup,
      FormBuilder
    } from "@angular/forms"
    import {
      RxwebValidators
    } from '@rxweb/reactive-form-validators';

    @Component({
      selector: 'app-image-add-validator',
      templateUrl: './image-add.component.html'
    })
    export class ImageAddValidatorComponent implements OnInit {
      userInfoFormGroup: FormGroup

      constructor(
        private formBuilder: FormBuilder) {}

      ngOnInit() {
        this.userInfoFormGroup = this.formBuilder.group({
          profilePhoto: ['', [
            RxwebValidators.extension({
              extensions: [jpeg","gif"]
            })
          ]],
        });
      }
    }

I got this error on the component:

> Type 'string' is not assignable to type 'string[] | undefined'.ts(2322)
extension-config.d.ts(3, 5): The expected type comes from property 'extensions' which is declared here on type 'ExtensionConfig'
(property) ExtensionConfig.extensions?: string[] | undefined

and this code is highlighted:

> extensions:["jpeg","gif"]

### Environment

- OS: Windows
- Node: 14.17.1
- npm: 6.14.13

**Comment by ljharb** [comment]
This error comes from typescript, and has nothing to do with npm.
