### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by jukhamil** [npm/cli#3559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to run the app Pencil with requires me to call `npm start` from inside the `pencil` directory.
I received the error that you cannot run the app as root user without `--no-sandbox`.

Someone online suggested adding "no sandbox" to the start script in package.json, but that didn't help.

Why can't electron run as root user without no sandbox? Why would the app designers have designed the app not to work as root user? What is no sandbox? And how do I run npm start with no sandbox?

Thank you.

### Expected Behavior

To call npm start and to launch Penci.

### Steps To Reproduce

 Following the instructions on the Pencil GitHub page

### Environment

- OS: Ubuntu 20
- Node: 
- npm:

**Comment by darcyclarke** [comment]
I think you should reach out to the author of the package/project you're using. It seems like there's some confusion/missing steps in the documentation to help you get things going. Sorry to hear but we unfortunately only can help with `npm` CLI specific issues here.
