### ISSUE TITLE
[BUG]<RESPONSE INFORMATION里没有信息>

### ISSUE THREAD

**Issue by MrPengZ** [npm/cli#3560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/85972403/126287782-e4f90f61-56c7-4969-97a6-4c6528955f8b.png)

### Steps To Reproduce

newman run Api_auto_test.postman_collection.json -e test.postman_environment.json -g My_Workspace.postman_globals.json -r htmlextra --reporter-html-export Report.html

### Environment

- OS: win10
- Node: v16.4.1
- npm: 7.18.1

**Comment by ljharb** [comment]
This doesn’t seem related to npm.

**Comment by MrPengZ** [comment]
The problem is already known, the server is down
