### ISSUE TITLE
[BUG] "audit fix" fails after "audit update" succeeded

### ISSUE THREAD

**Issue by iliubinskii** [npm/cli#3567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Screen](https://user-images.githubusercontent.com/70687432/126516111-3b32cd81-3dfc-49c1-85aa-c74671f0015b.jpg)

I see two strange things:

1. "npm audit-fix" fails right after "npm update" just succeeded. I think this should be impossible. If "npm update" succeeded it means that dependencies tree is resolvable. The commands used:
```
npm update --strict-peer-deps
npm audit --strict-peer-deps fix
```

2. It can be seen from screenshot that conflict is false. Found version 4.46.0 satisfies requirement "^4.1.0".

### Expected Behavior

1. Audit with same option should never fail after update.

2. 4.46.0 should satisfy ^4.1.0 requirement.

### Steps To Reproduce

The issue occurs in private project. I'll try to create public reproduction repsository on request.

### Environment

- OS:  Windows 10
- Node:  14.17.0
- npm: 7.17.0

**Comment by nlf** [comment]
we've made significant changes to audits and peer dependency behaviors, can you try updating to npm@8.5.3 and see if you still have a problem?

**Comment by iliubinskii** [comment]
My npm version is up-to-date.
I did not experience the problem described her recently.
I will close the issue and re-open if it returns.
