### ISSUE TITLE
[BUG] CLI does not throw error when publishing abusive package name 

### ISSUE THREAD

**Issue by y-nk** [npm/cli#3582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

All the npm cli options are one-char package name which can create confusion with the api.

- hyphen: www.npmjs.com/package/-
- `--save-bundle`: www.npmjs.com/package/b
- `--save-dev`: www.npmjs.com/package/d
- `--save-exact`: www.npmjs.com/package/e
- `--save`: www.npmjs.com/package/s
- `--save-optional`: www.npmjs.com/package/o

Misleading:
```
npm i - d react # will NOT save dev
npm i  express - e # will NOT save exact 
```

Confusing:

```
npm i - s -d - e
```

### Expected Behavior

1. npm publish should throw error if package.name.length is < 2
2. npm publish should throw error if package.name.startsWith('-')

### Environment

- OS:  all
- Node:  all
- npm:  all

**Comment by ljharb** [comment]
That would break existing packages.

**Comment by y-nk** [comment]
@ljharb I understand that. but at some point there's confusion which needs to be cleared. It lands into the same (arguable, i agree) area than https://www.npmjs.com/package/install. It sounds "cool" that you can `npm install install` but actually it's more confusing than anything. one-letter packages are similar in that regard.

**Comment by wraithgar** [comment]
This is not something that can be fixed in the cli without breaking existing packages.
