### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by kavi6024** [npm/cli#3583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I don't know what to do, Please help.

Aborting installation.
  npm install --save --save-exact --loglevel error react react-dom react-scripts cra-template has failed.

Deleting generated file... package.json

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- OS: 
- Node: 
- npm:

**Comment by nlf** [comment]
#417 

also, please try updating to the latest npm (7.20.2 as of today) with `npm i -g npm` and see if you still see this issue. if so, please open a new issue and be sure to fill out our template to the best of your ability.
