### ISSUE TITLE
[BUG] Republished package showing on npmjs.com but not available from CLI

### ISSUE THREAD

**Issue by jordanbtucker** [npm/cli#3590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I wanted to publish `ddns-client`, I ran `npm view ddns-client` and it gave me the following message:

```
$ npm view ddns-client
npm ERR! code E404
npm ERR! 404 Unpublished by j.chaniotis on 2014-08-29T06:25:39.794Z
npm ERR! 404
npm ERR! 404  'ddns-client' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

I decided to "use the name" as suggested, and published `ddns-client@0.1.0`. (Unfortunately, I no longer have the log from when I published, but it reported success.)

It's been 11 hours since I published it. It shows up when searching on npmjs.com.

![image](https://user-images.githubusercontent.com/468153/127354723-d7510e01-7a44-4640-9942-d19c334e1a09.png)

But trying to access the [package's page](https://www.npmjs.com/package/ddns-client) gives a 404.

Attempting to install `ddns-client` results in an error saying that no versions are available:

```
$ npm install ddns-client
npm ERR! code ENOVERSIONS
npm ERR! No versions available for ddns-client
```

Attempting to install a specific version gives an even more confusing error:

```
npm install ddns-client@0.1.0
npm ERR! Cannot convert undefined or null to object
```

### Expected Behavior

- I would expect a successfully published package to be available to install and visible on npmjs.com.
- I would expect npmjs.com and the CLI to be consistent.
- I would expect the CLI to block the publish if it wasn't going to be available.
- I would expect some kind of warning if there was a waiting period for republished packages. (I'm just making a guess here.)
- I would expect some way to see which versions have been unpublished since they can never be republished.
- I would expect a better error message than `Cannot convert undefined or null to object`

### Steps To Reproduce

1. Go to npmjs.com
2. Search for `ddns-client`
3. See the `ddns-client` package
4. Click on the entry for `ddns-client`
5. See the 404 page
6. Run `npm install ddns-client`
7. See the error about no versions available
8. Run `npm install ddns-client@0.1.0`
9. See the error `Cannot convert undefined or null to object`

### Environment

- OS: Windows 10
- Node: 14.17.3
- npm: 7.20.2 (However, I published the package with 6.14.14 and have since upgraded.)

**Comment by jordanbtucker** [comment]
Since I've posted this, I've published v0.1.1, v0.2.0, v0.2.1, v0.2.2, and v0.2.3, all of which are available as well as the original v0.1.0 I posted about. I guess it was just a timing thing?

**Comment by MikeChongCan** [comment]
We can repro this issue here: https://github.com/microsoft/ts-gyb/issues/61

**Comment by nlf** [comment]
this was a caching ttl problem, and should be resolved. please open a new issue if you see it happen again!
