### ISSUE TITLE
[BUG] installation fails for Ubuntu 16.04

### ISSUE THREAD

**Issue by ouboub** [npm/cli#3595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running 
npm install mathjax-node-cli
results in Error: Missing required argument #1
log attached

[npm-debug.log](https://github.com/npm/cli/files/6905470/npm-debug.log)

### Expected Behavior

installation should succeed.

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- OS: Ubuntu 16.04
- Node: 4.2.6
- npm: 3.5.2

**Comment by ljharb** [comment]
Both node 4 and npm 3 are incredibly ancient and unsupported. Upgrade to npm 6, or upgrade to node 12+ and npm 7.

**Comment by ouboub** [comment]
ok, I did  (following https://stackoverflow.com/questions/41195952/updating-nodejs-on-ubuntu-16-04)
sudo npm install -g n
sudo n latest
that part worked. Then I run again 
`npm install mathjax-node-cli
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 175 packages, and audited 176 packages in 31s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice
npm notice New minor version of npm available! 7.19.1 -> 7.20.3
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.20.3
npm notice Run npm install -g npm@7.20.3 to update!


I am not sure now: did the installation succeed?`

**Comment by ljharb** [comment]
Yes, seems like it worked fine.

**Comment by ouboub** [comment]
Right, thanks
