### ISSUE TITLE
[BUG] <title> npm ERR! Exit handler never called!

### ISSUE THREAD

**Issue by LancerWang001** [npm/cli#3597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Action: execute the command "npm install parcel -D".

part of the error log:
336 verbose unfinished npm timer command:install 1627740274038
337 verbose unfinished npm timer reify 1627740274039
338 verbose unfinished npm timer reify:loadTrees 1627740274056
339 verbose unfinished npm timer idealTree 1627740274057
340 verbose unfinished npm timer idealTree:buildDeps 1627740274071
341 verbose unfinished npm timer idealTree:node_modules/@parcel/config-default 1627740364968
342 info ok
343 error Exit handler never called!

It happened when I upgraded Node version to 14.17.3.
I have tried to clean the local cache and delete the node_modules folder.
but still threw this error.

What should I do now ..?

### Expected Behavior

Correctly run "npm install".

### Steps To Reproduce

Just run "npm install [package-name] -D".

### Environment

- OS: macOS Big Sur 11.4
- Node: v14.17.3 LTS
- npm: v7.20.2

**Comment by LancerWang001** [comment]
Resolved this issue!

Just install 14.17.4 and it will replace npm 7.2 with npm 6.14.14,
which work fine with me now~

**Comment by ljharb** [comment]
npm 6 is not a solution.
