### ISSUE TITLE
npx uses different environment than invoking command directly

### ISSUE THREAD

**Issue by whoami-defnotme** [npm/cli#3599]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm working with AWS CDK, which I installed via `npm install -g` (as described in the [docs](https://docs.aws.amazon.com/cdk/latest/guide/getting_started.html)). CDK recommends using Python virtual environments for dependencies, which I'm using. I have all my required Python packages installed via `pip install -r requirements.txt`.

If I run a CDK command directly (ex: `cdk synth`), the code runs as expected and I see (via Python debug statements added to the top of my app code) I'm running in the Python virtual environment as expected.

If I run a CDK command using npx (ex: `npx cdk synth`), the Python debug statements show I'm not using the virtual environment as I would expect. Instead, it's apparently using a Python runtime installed using Homebrew (which isn't actually the brew installed version on my PATH).

### Environment

- OS: macOS 11.5.1
- Node: v14.13.1
- npm: 7.12.0

**Comment by nlf** [comment]
it appears this was fixed upstream in the homebrew formula so i'm going to go ahead and close this. if you encounter a similar problem, please feel free to open a new issue
