### ISSUE TITLE
[BUG] `npm dedupe` not working properly since upgrading from 7.20.2 to 7.20.3

### ISSUE THREAD

**Issue by weaintplastic** [npm/cli#3608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We've recently upgraded from `v7.20.2` to `v7.20.3` and experience issues when running `npm dedupe` that we haven't discovered with `v7.20.2`.

#### Unresolved dependencies or problems overriding peer dependencies
When running `npm dedupe` we see new warnings being reported that otherwise did not appear. Such as:

```
npm WARN Conflicting peer dependency: @babel/core@7.14.8
npm WARN node_modules/@babel/core
npm WARN   peer @babel/core@"^7.0.0-0" from @babel/plugin-proposal-object-rest-spread@7.12.1
npm WARN   node_modules/remark-mdx/node_modules/@babel/plugin-proposal-object-rest-spread
npm WARN     @babel/plugin-proposal-object-rest-spread@"7.12.1" from remark-mdx@1.6.22
npm WARN     node_modules/remark-mdx
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @babel/plugin-syntax-jsx@7.12.1
npm WARN Found: @babel/core@7.12.9
npm WARN node_modules/remark-mdx/node_modules/@babel/core
npm WARN   @babel/core@"7.12.9" from remark-mdx@1.6.22
npm WARN   node_modules/remark-mdx
npm WARN     remark-mdx@"1.6.22" from @mdx-js/mdx@1.6.22
npm WARN     node_modules/@mdx-js/mdx
npm WARN   2 more (@babel/plugin-proposal-object-rest-spread, @babel/plugin-syntax-jsx)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer @babel/core@"^7.0.0-0" from @babel/plugin-syntax-jsx@7.12.1
npm WARN node_modules/remark-mdx/node_modules/@babel/plugin-syntax-jsx
npm WARN   @babel/plugin-syntax-jsx@"7.12.1" from remark-mdx@1.6.22
npm WARN   node_modules/remark-mdx
npm WARN 
npm WARN Conflicting peer dependency: @babel/core@7.14.8
npm WARN node_modules/@babel/core
npm WARN   peer @babel/core@"^7.0.0-0" from @babel/plugin-syntax-jsx@7.12.1
npm WARN   node_modules/remark-mdx/node_modules/@babel/plugin-syntax-jsx
npm WARN     @babel/plugin-syntax-jsx@"7.12.1" from remark-mdx@1.6.22
npm WARN     node_modules/remark-mdx
```

#### Auth error for private packages
Ultimately we are getting an auth error for one of our a scoped package hosted in a private artifactory repository. An `.npmrc` file is provided in the project's route. 
It's worth mentioning that the scoped packages is part of the same mono-repo project that we've configured using `workspaces` in the `package.json`. 

```
ERR! code E403
npm ERR! 403 403 Forbidden - GET https://artifactory.xxx.com/artifactory/api/npm/rbds-npm-local/@cosmos%2fbrowserslist-config
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.
```

### Expected Behavior

I'd expect no issues when running `npm dedupe` when upgrading to `v7.20.3`

### Steps To Reproduce

Our monorepo is quite complex, if required I can try to setup a minimal version of it that can be used to reproduce the error. Sorry about that.

### Environment

- OS: macOS 10.15.5
- Node: v16.6.0 or v14.17.4
- npm: v7.20.3

**Comment by gyandeeps** [comment]
I can see similar issues between the 7.20.2 and 7.20.3.
You can see how dedupe is different after running `npm install`. thier is no difference even if i run `npm dedupe`

## 7.20.2

```sh
npm ls @react-aria/focus             
<project>@ /Users/<path>
└─┬ native-base@3.0.7
  ├─┬ @react-native-aria/checkbox@0.2.3
  │ ├─┬ @react-aria/checkbox@3.2.3
  │ │ └─┬ @react-aria/toggle@3.1.4
  │ │   └── @react-aria/focus@3.4.1 deduped
  │ └─┬ @react-native-aria/toggle@0.2.3
  │   └── @react-aria/focus@3.4.1 deduped
  ├─┬ @react-native-aria/combobox@0.2.4-alpha.1
  │ └─┬ @react-aria/combobox@3.0.1
  │   └─┬ @react-aria/textfield@3.3.1
  │     └── @react-aria/focus@3.4.1 deduped
  ├─┬ @react-native-aria/focus@0.2.5
  │ └── @react-aria/focus@3.4.1
  ├─┬ @react-native-aria/listbox@0.2.4-alpha.2
  │ ├─┬ @react-aria/listbox@3.3.1
  │ │ └── @react-aria/focus@3.4.1 deduped
  │ └─┬ @react-aria/selection@3.5.1
  │   └── @react-aria/focus@3.4.1 deduped
  ├─┬ @react-native-aria/radio@0.2.5
  │ └─┬ @react-aria/radio@3.1.5
  │   └── @react-aria/focus@3.4.1 deduped
  └─┬ @react-native-aria/slider@0.2.5-alpha.1
    ├── @react-aria/focus@3.4.1 deduped
    └─┬ @react-aria/slider@3.0.3
      └── @react-aria/focus@3.4.1 deduped

```

## 7.20.3

```sh
npm ls @react-aria/focus             
<projkect>@ /Users/<path>
└─┬ native-base@3.0.7
  ├─┬ @react-native-aria/checkbox@0.2.3
  │ ├─┬ @react-aria/checkbox@3.2.3
  │ │ └─┬ @react-aria/toggle@3.1.4
  │ │   └── @react-aria/focus@3.4.1
  │ └─┬ @react-native-aria/toggle@0.2.3
  │   └── @react-aria/focus@3.4.1
  ├─┬ @react-native-aria/combobox@0.2.4-alpha.1
  │ └─┬ @react-aria/combobox@3.0.1
  │   ├─┬ @react-aria/listbox@3.3.1
  │   │ └── @react-aria/focus@3.4.1
  │   ├─┬ @react-aria/selection@3.5.1
  │   │ └── @react-aria/focus@3.4.1
  │   └─┬ @react-aria/textfield@3.3.1
  │     └── @react-aria/focus@3.4.1
  ├─┬ @react-native-aria/focus@0.2.5
  │ └── @react-aria/focus@3.4.1
  ├─┬ @react-native-aria/listbox@0.2.4-alpha.2
  │ ├─┬ @react-aria/listbox@3.3.1
  │ │ └── @react-aria/focus@3.4.1
  │ └─┬ @react-aria/selection@3.5.1
  │   └── @react-aria/focus@3.4.1
  ├─┬ @react-native-aria/radio@0.2.5
  │ └─┬ @react-aria/radio@3.1.5
  │   └── @react-aria/focus@3.4.1
  ├─┬ @react-native-aria/slider@0.2.5-alpha.1
  │ ├── @react-aria/focus@3.4.1
  │ └─┬ @react-aria/slider@3.0.3
  │   └── @react-aria/focus@3.4.1 deduped
  └─┬ @react-native-aria/tabs@0.2.7
    └─┬ @react-aria/tabs@3.0.0-alpha.2
      └─┬ @react-aria/selection@3.5.1
        └── @react-aria/focus@3.4.1
```

**Comment by kokushkin** [comment]
I think I'm experiencing something similar, when  npm ddp thinks that I've conflicting peers. I've typescript@4.2.4 in the root and a peer >= 2.7 inside of  ts-node and >=4.1 inside of "another package" (our internal package). Obviously shouldn't be the conflict here, right?
I'm on npm 7.24.2 
npm 7.20.1 works fine (I didn't try later versions though)
Also if I delete  this another package it works fine.

Has anybody started to work on this already?

**Comment by nlf** [comment]
can any of you folks give this a shot in npm@8.5.5? we've made quite a few changes to how peer dependencies are handled, as well as auth. i'm hopeful one of those may have addressed this issue for you.

if it hasn't, it would be helpful if someone can post reproduction steps. ideally a minimal step by step reproduction, but if there's a public repository showing this problem that would be just fine too.

**Comment by kokushkin** [comment]
I'm on npm 8.4.0 now. I don't see any problems anymore and my packages'  tree is almost the same as it was.

**Comment by wraithgar** [comment]
@kokushkin thanks for the reply.  If anyone is still having issues with dedupe feel free to open a new issue for it and we'll get it triaged appropriately.
