### ISSUE TITLE
[BUG] npm install - workspaces not installing dependencies as expected

### ISSUE THREAD

**Issue by nathanhall-dev** [npm/cli#3609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have the following configuration
```
  "workspaces": [
    "packages\\sfdx-core-package",
    "packages\\sfdx-bonus-package"
  ],
```

When I run 'npm install' on my local environment - it generates a package-lock with 982 dependencies.

In my CI (using Google Cloudbuild) 

I run
```
  - name: node
    entrypoint: npm
    args: ['install']
```
which runs the 'npm install' command.

But get the following output:
```found 0 vulnerabilities

  run `npm fund` for details
1 package is looking for funding

added 1 package, and audited 2 packages in 574ms
```
I expect that to be much bigger, based off the dependencies in the 2 workspace package.json files.

NPM doesn't seem to be recognising the workspaces, as when I run 'npm run test --ws' as part of the CI build, the following error occurs:

Again this works again locally, but not in the CI.

```
npm ERR!     /builder/home/.npm/_logs/2021-08-04T15_00_23_169Z-debug.log
npm ERR! A complete log of this run can be found in:

npm ERR! No workspaces found!
```

### Expected Behavior

npm install from the package, should create package lock correctly from the workspace directories
'npm run test --ws' should run test on both packages, as it does locally.

### Steps To Reproduce

Below example is an opensource project, that works locally, but does not work on a CI.

1. https://github.com/nhall97/sfdx-monorepo-workspace
2. npm install
3. Expects work correctly

### Environment

CI configuration:
- Node: docker.io/library/node:16.6.1
- npm: 7.20.3

**Comment by wraithgar** [comment]
This is due to the fact that lifecycle scripts in workspaces don't run when they're installed.  You will need to manually run the `prepare` script in each workspace in order for husky to run, and for it to build the things your script is expecting to be there.

See https://github.com/npm/cli/issues/4412 and https://github.com/npm/cli/issues/3598 for more context
