### ISSUE TITLE
[BUG] <Use node child_process to call `npm publish` to prompt `npm adduser`>

### ISSUE THREAD

**Issue by hairyf** [npm/cli#3617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

#### Use node child_process to call npm publish
~~~js
import { execSync } from 'child_process'
execSync('npm publish', { stdio: 'inherit' })
~~~

~~~
npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in.
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mr\AppData\Local\npm-cache\_logs\2021-08-06T14_21_24_909Z-debug.log
~~~

[2021-08-06T14_21_24_909Z-debug.log](https://github.com/npm/cli/files/6946107/2021-08-06T14_21_24_909Z-debug.log)

#### Manual call
`npm publish`
~~~
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/@tuimao%2ftailwind-config-preset - You cannot publish over the previously published versions: 1.2.7-alpha.0.
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.
~~~
It is correct to indicate that the version is incorrect, because I don't want to push a version again because of this problem.

[2021-08-06T14_26_09_693Z-debug.log](https://github.com/npm/cli/files/6946124/2021-08-06T14_26_09_693Z-debug.log)

### Expected Behavior

You can use child_process to publish

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- OS: window
- Node: v16.5.0
- npm: 7.20.5

**Comment by larsivi** [comment]
I see the same. My setup is slightly more complex, as I pass the actual cwd to the child process, but this works fine for commands not requiring auth.

npm 7.19.1

**Comment by larsivi** [comment]
Updated to latest (7.24.1) and with some hackish logging I found out that the wrong repository (yarns) is checked rather than the npmjs one (where we have our private packages). I was able to workaround by explicitly setting correct registry in the child_process using --registry option (or presumably setting it in the package.json).

**Comment by wraithgar** [comment]
Because of the workaround it looks like this was a config issue. There is no reason you can't use child_process to call npm.
