### ISSUE TITLE
[BUG] `npm link` does not respect `--no-save`

### ISSUE THREAD

**Issue by ljharb** [npm/cli#3619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`npm link --no-save $something`

updates package.json with a `file://` link.

### Expected Behavior

`--no-save` means nothing gets saved.

### Steps To Reproduce

See above.

### Environment

- OS: Mac
- Node: 16.6.1
- npm: v7.20.3

**Comment by AttractiveDog** [comment]
Try deleting cache data

**Comment by ljharb** [comment]
@AttractiveDog can you explain why you think that would have any relevance to this?

**Comment by AttractiveDog** [comment]
This thing does not seem to mean anything it is just for the point where it may have stuck.

By the way it seems to be a bug

**Comment by majidkhan12** [comment]
I need it now[.](https://apktiger.com/football-strike-mod-apk/)

**Comment by ljharb** [comment]
This continues to be a problem on npm v8.3.0, and is why v19.0.3 of eslint-config-airbnb was broken last night.

If someone gives me a pointer, I'd be happy to make a PR to fix it.

**Comment by wraithgar** [comment]
Closed by https://github.com/npm/cli/pull/6910
