### ISSUE TITLE
Bugged or hacked

### ISSUE THREAD

**Issue by ghost** [npm/cli#3622]
Remove all my api’s and reset all my accounts and balance to zero. Since, I was bugged and hacked.

Thank you I really appreciate all the hard work and effort.

**Comment by ljharb** [comment]
If you need something done with your npm account, you’ll need to file a support ticket.

**Comment by ghost** [comment]
Thanks for the help and efforts, please remove all api's and reset my accounts and balance to zero (0). Since, I was bugged or hacked.
