### ISSUE TITLE
Remove all my api’s and reset all my accounts and balance to zero. Since, I was bugged and hacked.

### ISSUE THREAD

**Issue by ghost** [npm/cli#3623]
Remove all my api’s and reset all my accounts and balance to zero. Since, I was bugged and hacked.

Thank you I really appreciate all the hard work and effort. 

__Originally posted by @F0o0De in https://github.com/Coinigy/api/pull/45__

**Comment by ljharb** [comment]
Please stop filing duplicate issues.

Duplicate of #3622.
