### ISSUE TITLE
This commit implements a fully-automated development setup using Gitpod.io, an

### ISSUE THREAD

**Issue by ghost** [npm/cli#3624]
This commit implements a fully-automated development setup using Gitpod.io, an
online IDE for GitLab, GitHub, and Bitbucket that enables Dev-Environments-As-Code.
This makes it easy for anyone to get a ready-to-code workspace for any branch,
issue or pull request almost instantly with a single click.

Thanks for the help and efforts, please remove all api's and reset my accounts and balance to zero (0). Since, I was bugged or hacked. 

__Originally posted by @F0o0De in https://github.com/SocketCluster/socketcluster/pull/545__

**Comment by ljharb** [comment]
Please stop filing duplicate issues.

Duplicate of #3622.
