### ISSUE TITLE
[BUG] `npm install` creates symlinks to `file:` dependencies

### ISSUE THREAD

**Issue by LoganDark** [npm/cli#3629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`npm install` creates symlinks for `file:` dependencies. This causes my IDE to fail to index that package, as it doesn't follow symlinks, and it wants me to import using `../../../../<package name>` instead of just `<package name>`, which makes my app refuse to compile because I can only import modules from `node_modules`.

### Expected Behavior

`npm install` should copy files instead, or there should be a setting to make it copy files.

### Steps To Reproduce

1. Specify a dependency as `file:some/path`
2. `npm install`
3. Ta-da, symlink

### Environment

- OS: Ubuntu 20.04
- Node: 16.4.0
- npm: 7.18.1

**Comment by ljharb** [comment]
I think this changed in npm 5. Why does your IDE not follow symlinks?

**Comment by LoganDark** [comment]
> Why does your IDE not follow symlinks?

WSL

Manually using `cp` to replace the symlink in node_modules with the actual contents of the package made everything start working.

**Comment by ljharb** [comment]
I'm not sure how "WSL" is an answer - WSL supports symlinks just fine, since it's POSIX.

**Comment by LoganDark** [comment]
> I'm not sure how "WSL" is an answer - WSL supports symlinks just fine, since it's POSIX.

Yes, but my IDE runs in Windows. Since Windows is a POS, it doesn't properly support symlinks made in WSL (`.lnk` shortcuts are not symlinks) and they show up as regular files. I think NTFS does support symlinks, but Windows does a bad job of recognizing/translating them. So WSL links just show up as files.

![image](https://user-images.githubusercontent.com/4723091/128635544-0771b03c-1bfa-44bc-83e2-54403b35ed89.png)

When npm uses symlinks, my IDE does not see the linked module. It just sees a random file.

Makes me wish I was still using macOS which doesn't have any of these issues.

**Comment by ljharb** [comment]
Ah, gotcha. I'd have expected WSL to translate between POSIX symlinks and Windows symlinks (not `.lnk`, but from `mklnk`). Seems like a WSL bug to me.

**Comment by LoganDark** [comment]
> Ah, gotcha. I'd have expected WSL to translate between POSIX symlinks and Windows symlinks (not `.lnk`, but from `mklnk`). Seems like a WSL bug to me.

Starting to sound like a wontfix, which is alarming. Would you be willing to provide even an *option* to not use symlinks for this purpose?

**Comment by ljharb** [comment]
I'm not an npm CLI maintainer, so none of those decisions are up to me.

**Comment by isaacs** [comment]
I agree that this is confusing and weird, but it was preserved in the v7 update in order to minimize the amount of disruption between v6 and v7.  It's a common enough confusion that I think it ought to be fixed in a future release, but it will definitely be a breaking change.

If you're having problems interoperating between WSL and Windows proper, maybe do your `npm install` commands in windows bash rather than WSL, so that the symlinks are implemented as windows junctions rather than opaque linux symlinks?

**Comment by LoganDark** [comment]
> I agree that this is confusing and weird, but it was preserved in the v7 update in order to minimize the amount of disruption between v6 and v7. It's a common enough confusion that I think it ought to be fixed in a future release, but it will definitely be a breaking change.

You could certainly implement an option for it without it being a breaking change, right?

> If you're having problems interoperating between WSL and Windows proper, maybe do your `npm install` commands in windows bash rather than WSL, so that the symlinks are implemented as windows junctions rather than opaque linux symlinks?

Development isn't a job for Windows, it gets so many things wrong and is generally a very cursed environment to work in - I'd rather not try to make development tools run there, especially not things like Node when nvm doesn't exist for Windows. It's more of a headache than it's worth.
