### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by awstah** [npm/cli#3631]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Awais Tahir\AppData\Roaming\npm-cache\_logs\2021-08-09T07_18_04_801Z-debug.log

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- OS: 
- Node: 
- npm:

**Comment by LilianMessias** [comment]
Ola! estou com esse mesmo problema de npm,vc sabe como me ajudar?
ficarei muitoo grata
