### ISSUE TITLE
[BUG] `npx node -e "console.log('ok nice');"` doesn't respect spaces on Windows

### ISSUE THREAD

**Issue by tamusjroyce** [npm/cli#3633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`npx node -e "console.log('ok nice');"`

C:\Users\Owner\Projects\deno\test_npm_deno\node_modules>`npx --version`
10.2.2

C:\Users\Owner\Projects\deno\test_npm_deno\node_modules>`npx node -e "console.log('ok nice');"`
[eval]:1
console.log('ok
            ^^^
SyntaxError: Invalid or unexpected token

### Expected Behavior

> `npx node -e "console.log('ok nice');"`

ok nice

### Steps To Reproduce

> `npx node -e "console.log('ok nice');"`

### Environment

- OS: Windows 10 Pro
- node v14.17.4
- npm v6.14.14 (why v7 doesn't come with 14.x LTS beats me)
- npx v10.2.2 (upgraded from v6.14.14)

Setup via - https://github.com/coreybutler/nvm-windows (need to quickly switch between 10.x, 12.x, and 14.x LTS to support other projects)

**Comment by tamusjroyce** [comment]
Switching to node v16.6.1 seems to have almost resolved it.

`npx node -e "console.log('ok nice');"`

Need to install the following packages:
  node
Ok to proceed? (y)
ok

after hitting enter, it runs fine ever time after.

But I proceeded to put this in my Azure CI Pipeline and the pipeline is locked.

Does not supporting npm V6 mean you don't support your supported LTS - Long Term Support version of node?
Could both V6 and V7 be fixed, since they both should be supported?

**Comment by ruyadorno** [comment]
Hi @tamusjroyce it would be helpful to understand a little bit more of the context here if you can explain what were you really trying to achieve when running `npx node -e "console.log('ok nice');"` ?

The `npx node` script will try to download the [`node`](https://www.npmjs.com/package/node) package from the registry (which I'm not sure is owned by the nodejs project or automatically updated) which seems to be outdated given that at the moment of writing the latest version of node js is `18.1.0` while the package only has `17.7.2` as latest.

Given that you already have `node` in your system and assuming that you really want to run the command in the subshell spawned by **npx**, you can also run it without requiring the download of that extra package using the `call` (`-c`) option:

```
$ npx -c 'node -p "console.log(\"ok nice\")"'
```

Now back to the original report, you mentioned that npm7+ works as expected:

> Switching to node v16.6.1 seems to have almost resolved it.
>
> npx node -e "console.log('ok nice');"
>
> Need to install the following packages:
> node
> Ok to proceed? (y)
> ok
>
> after hitting enter, it runs fine ever time after.

Given that we're no longer shipping fixes to `npm@6` I'm going to go ahead and close this issue but feel free to post more info in case you still need help handling this workflow.
