### ISSUE TITLE
[BUG] Option "--audit-level" is ignored by "npm audit fix" resulting in unnecessary changes

### ISSUE THREAD

**Issue by metaturso** [npm/cli#3636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`npm audit fix --audit-level critical` fixes all vulnerabilities

### Expected Behavior

`npm audit fix --audit-level critical` only fixes critical vulnerabilities. 

Alternatively, there should be a way to fix individual packages. Yet another alternative would be to replace the following message with an actual fix suggestion:

```bash
fix available via `npm audit fix`
```

### Steps To Reproduce

1. Install multiple packages (jest, tar, websocket-io)
2. Run `npm audit` and check that you have a variety of vulnerable packages
3. Run `npm audit fix --production --audit-level critical` to fix only critical vulnerabilities in non-dev dependencies 

### Environment

- OS: Linux (Ubuntu 20, Centos 7-8, Fedora 34)
- Node: 10-16
- npm: 7.20.5

**Comment by wraithgar** [comment]
Thanks for taking the time to share your idea! While new ideas are always appreciated I would please ask you to open an [issue or discussion in our RFC repo](https://github.com/npm/rfcs) instead since that's the right place in order to get more attention from the rest of the team and the community.

**Comment by ljharb** [comment]
@wraithgar to be fair tho, this seems like a straightforward bug

**Comment by ghassemiN** [comment]
it's ignore also in "npm audit –audit-level=critical"

**Comment by brsolomon-deloitte** [comment]
Why in the world was this closed? It's a dead-simple bug. `--audit-level` is ignored entirely.

**Comment by bindermuehle** [comment]
if `npm audit fix` does not support the flag `--audit-level`, then the help page should not list it as an option. 
should I open a separate bug report for this or can this ticket be used to address this?
```
 ✗ npm audit fix --help
Run a security audit

Usage:
npm audit [fix|signatures]

Options:
[--audit-level <info|low|moderate|high|critical|none>] [--dry-run] [-f|--force]
[--json] [--package-lock-only] [--no-package-lock]
[--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
[--include <prod|dev|optional|peer> [--include <prod|dev|optional|peer> ...]]
[--foreground-scripts] [--ignore-scripts]
[-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
[-ws|--workspaces] [--include-workspace-root] [--install-links]

Run "npm help audit" for more info

```

**Comment by yasirrafiq786** [comment]
this `npm audit fix --force --only=moderate` worked for me. You might want to pass `--force` flag with `--audit-level` as written in help.

**Comment by bindermuehle** [comment]
The command `npm audit fix --force --only=moderate` did not yield the expected outcome in my case. Instead of addressing only the moderate vulnerabilities, it resolved issues across all packages. This behavior contradicts the intended use of the `--only` flag, which, according to the documentation, is designed to manage devDependencies:

```
Skip updating devDependencies:
 $ npm audit fix --only=prod
```

As such, it's important to clarify that the current functionality of npm audit doesn't support fixing vulnerabilities based on their severity levels. While the help text may suggest otherwise, users should be aware that attempting to employ this method won't result in the desired outcome.

I'm sharing this observation to prevent others from mistakenly relying on a solution that doesn't align with npm audit's capabilities at present.

**Comment by JoshElias** [comment]
Why was this closed? `npm audit --audit-level critical` doesn't work. With or without `fix`.

**Comment by PlusMinus0** [comment]
> [audit-level](https://docs.npmjs.com/cli/v10/using-npm/config#audit-level)
>
>    Default: null
>    Type: null, "info", "low", "moderate", "high", "critical", or "none"
>
> The minimum level of vulnerability for npm audit to exit with a non-zero exit code.

Works as documented.
