### ISSUE TITLE
[BUG] npm publish directory/subdirectory ignores global registry, project specific registry AND publishConfig/registry

### ISSUE THREAD

**Issue by tengelmeier** [npm/cli#3638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have a top level package.json containing a script 

"publish:lib":"npm run build:lib && npm publish dist/ourproject" 

and in dist/ourproject/package.json 

"publishConfig": {
    "registry": "https://nexus.example.com/repository/private/"
  },

In the global and the project-local .npmrc a private registry ist defined. 

### Expected Behavior

Publish to the registry specified in publishConfig/registry
Honor as fallbacks the registry defined in project/.npmrc
Honor as fallbacks the registry defined ~/.npmrc

### Steps To Reproduce

1. npm config set registry some.private.registry 
2. npm -g config set registry some.private.registry 
3. setup a top level package.json that has a script phase "publish:lib":"npm publish subfolder"
4. in subfolder/package.json, point publishConfig/registry to a custom registry

### Environment

- OS: macOS 11.4
- Node: v16.2.0
- npm: 7.13.0, 7.20.5

**Comment by tengelmeier** [comment]
Missing in "current behavior": The npm publish tries to publish via ssh+git to GitHub.com. None of the defined private registries are honored.

**Comment by tengelmeier** [comment]
regression test: works with npm 6.14.14

**Comment by nlf** [comment]
what's happening here is that we determine that `dist/ourproject` is actually a shorthand to a github repo and attempt to publish that. `npm publish ./dist/ourproject` will bypass the github shorthand and correctly identify this as a file path and work as you expect.

unfortunately this shorthand is used heavily, so we won't be changing it any time soon.
