### ISSUE TITLE
[BUG] <title>ERR_SOCKET_TIMEOUT

### ISSUE THREAD

**Issue by mohamedmehdigara** [npm/cli#3639]

**Comment by ansf** [comment]
is this the same as #3078?

**Comment by ruyadorno** [comment]
**Closing:** please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).
