### ISSUE TITLE
[BUG] npm login is blind for --scope parameter

### ISSUE THREAD

**Issue by dilame** [npm/cli#3641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My `.npmrc` contains this line 

```.npmrc
@igpapi:registry=https://npm.fury.io/igpapi/
```

But

```bash
 ~ % npm login --scope=@igpapi
npm notice Log in on https://registry.npmjs.org/
Username:
```

First, i thought it's just a wrong notice and tried to enter the credentials for the registry specified in my `.npmrc`, but npm sends the request to the `https://registry.npmjs.org/` and I can't log in.

### Expected Behavior

`npm login --scope=@scope`  should respect the scope registry specified in `.npmrc`

### Steps To Reproduce

1. In this environment
```
~ % npm -v
7.20.5
```
MacOS 11.0.1 (20B29)

2. With this config
```.npmrc
@igpapi:registry=https://npm.fury.io/igpapi/
```

3. Run this
`npm login --scope=@igpapi`

4. See error...
`npm notice Log in on https://registry.npmjs.org/`

### Environment

- OS: MacOS 11.0.1 (20B29)
- Node: v14.16.0
- npm: 7.20.5

**Comment by wraithgar** [comment]
This was fixed in `v8.2.0`. See https://github.com/npm/cli/issues/3515
