### ISSUE TITLE
[BUG] v7.20.5 not installable on MacOS

### ISSUE THREAD

**Issue by BenElferink** [npm/cli#3642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I was notified of an available update on NPM, while installing the an error occurred:

```bash
sudo npm install -g npm@7.20.5
npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module 'agentkeepalive'
npm ERR! Require stack:
npm ERR! - /usr/local/lib/node_modules/npm/node_modules/make-fetch-happen/agent.js
npm ERR! - /usr/local/lib/node_modules/npm/node_modules/make-fetch-happen/index.js
npm ERR! - /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/index.js
npm ERR! - /usr/local/lib/node_modules/npm/node_modules/pacote/lib/remote.js
npm ERR! - /usr/local/lib/node_modules/npm/node_modules/pacote/lib/git.js
npm ERR! - /usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetcher.js
npm ERR! - /usr/local/lib/node_modules/npm/node_modules/pacote/lib/index.js
npm ERR! - /usr/local/lib/node_modules/npm/lib/utils/update-notifier.js
npm ERR! - /usr/local/lib/node_modules/npm/lib/cli.js
npm ERR! - /usr/local/lib/node_modules/npm/bin/npm-cli.js
```

### Expected Behavior

That NPM would update from 7.5.4 -> 7.20.5

### Steps To Reproduce

1. Use MacOS
2. In terminal type `sudo npm i -g npm@7.20.5`
3. Enter password
4. ERROR

### Environment

- OS: MacOS Big Sur 11.5.1
- Node: v14.15.1
- npm: 7.5.4

**Comment by YashKumarVerma** [comment]
@ANISH0309 this could be of  your interest

**Comment by ljharb** [comment]
I believe this is a bug in npm v7.5.4. Try updating to node v14 latest, and then updating npm?

**Comment by ANISH0309** [comment]
<img width="892" alt="Screenshot 2021-08-12 at 8 15 19 PM" src="https://user-images.githubusercontent.com/52633729/129217972-617049e3-5625-4398-94f0-89a0c322e9c8.png">

The NPM is updated to 7.20.5

**Comment by BenElferink** [comment]
Issue seems to have been resolved by itself somehow. I didn't change or update anything, all I did was wait a couple days with a re-boot in-between.

<img width="471" alt="Screen Shot 2021-08-15 at 12 36 28" src="https://user-images.githubusercontent.com/69640911/129474126-29266308-ec5d-4e70-94d2-406f93c42f9d.png">
