### ISSUE TITLE
Incorrect homepage path on website, if repo is not hosted in Github

### ISSUE THREAD

**Issue by CxRes** [npm/cli#3644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

*This is a bug with the npm website, but I could not figure out where else to file this bug!*

If homepage is not specified in package.json and repository is not hosted in Github, the package webpage on npm still displays the homepage as <repo>#readme. 

This is a Github specific solution and does not work with other services.

### Expected Behavior

I see three different possible resolutions when a homepage is not supplied in `package.json` and package is not hosted on Github:
1. Derive the correct homepage path according to the hosting service (ie according to how it links to the readme).
2. Link the homepage to the repository itself.
3. Do not create a homepage link.

### Steps To Reproduce

1. Publish a package that you host on a service other than Github, say Gitlab, without the homepage field in `package.json`.
2. Visit the npm page for the said package and read the homepage field.

### Environment

OS: Irrelevant
node: Irrelevant
npm: 7.20.5

**Comment by wraithgar** [comment]
**Closing:** this looks to be an issue with the registry which is outside the scope of this repo. For registry support please go to [npmjs.com/support](https://www.npmjs.com/support).

**Comment by CxRes** [comment]
I have filed a complaint with npm. However, there is no category to report bugs and given my previous experience with npm, I do not expect an answer. It is also unfortunate that the issue had to be open for six months just to be told that it does not belong here.
