### ISSUE TITLE
[BUG] npm errors after updating to 7.20.6

### ISSUE THREAD

**Issue by owocado** [npm/cli#3646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After updating npm to latest version 7.20.6, trying to use any npm command throws MODULE_NOT_FOUND error. See screenshot for context:

![Screenshot_20210813-174417_JuiceSSH](https://user-images.githubusercontent.com/24418520/129355590-1e53a5fa-0ac6-42ff-8b2d-f3161fd150f7.png)

### Expected Behavior

After updating npm to latest version, I expect npm command/subcommands to function properly and not throw errors. 

### Steps To Reproduce

1. Try to update system/global npm cli module
2. np particular config
3. Run 'npm update -g'
4. See error of MODULE_NOT_FOUND (attached screenshot above for error)

### Environment

- OS: Ubuntu 20.04
- Node: v16.6.2
- npm: 7.20.6

**Comment by darcyclarke** [comment]
@ow0x I just tried replicating this but couldn't from the same `npm` & `node` versions (although I'm on mac); ref.

<img width="671" alt="Screen Shot 2021-08-13 at 10 13 20 PM" src="https://user-images.githubusercontent.com/459713/129431435-242d61c1-1c70-4c09-9443-389dde762eab.png">

Can you try running any other `npm` command just to ensure those work? Another option would be to see if installing `7.20.6` w/ `npm install -g npm` works (even though `npm update -g` should be doing the same thing).

**Comment by owocado** [comment]
hi @darcyclarke

I just tried this on another new Ubuntu 20.04 VM which is on Google Cloud (the first one is also on GCP from where I got original error). I (re)installed nodejs v16.x through apt package manager then tried updating system/global npm package like before but it still gave same error on any npm command after update. Maybe there's a bug with default bundled npm with node v16.x for linux distributions?

![Screenshot_20210814-080616_JuiceSSH](https://user-images.githubusercontent.com/24418520/129431970-246bf374-e138-461f-b3a7-3f671a8368ed.png)

![Screenshot_20210814-081608_JuiceSSH](https://user-images.githubusercontent.com/24418520/129432096-4d9c9511-034b-4517-a72f-e7888d9abba4.png)


I did some troubleshooting on my end. To manually fix this, I had to cd to `/usr/lib/node_modules/npm/node_modules/` and had to manually `git clone https://github.com/isaacs/color-support` which fixed the borked npm and all npm commands started to work again just fine. Could it be that issue lies in default bundled npm package with nodejs v16.x for debian/ubuntu based distributions?

**Comment by isaacs** [comment]
> Could it be that issue lies in default bundled npm package with nodejs v16.x for debian/ubuntu based distributions?

That is certainly possible, but it seems unlikely to me.

Self-upgrading from 7.20.3 to 7.20.6 with `npm update -g` seems to work for me using this minified test script: https://gist.github.com/isaacs/236dc524f9a841c03f738c7fdcaeca7e

Can you run that and see how it behaves?  It should look like this:

```
$ bash test.sh

added 1 package, and audited 260 packages in 2s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
/Users/isaacs/dev/npm/cli/gh-3646/prefix/bin/npm
Package  Current  Wanted  Latest  Location          Depended by
npm       7.20.3  7.20.6  7.20.6  node_modules/npm  global
/Users/isaacs/dev/npm/cli/gh-3646/prefix/lib
└── npm@7.20.3


removed 1 package, changed 21 packages, and audited 259 packages in 2s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
/Users/isaacs/dev/npm/cli/gh-3646/prefix/bin/npm
/Users/isaacs/dev/npm/cli/gh-3646/prefix/lib
└── npm@7.20.6
```

**Comment by owocado** [comment]
@isaacs hi, thanks for the response. I tried your provided test.sh bash script and it worked perfectly fine this time. I really find it weird and puzzling why it threw error the first time on default npm version which came bundled with node 16.x. But anyhow, my issue is solved now so I think I should close this issue. Thanks for the help. 

![Screenshot_20210816-222540_JuiceSSH](https://user-images.githubusercontent.com/24418520/129601271-1f5e8ce2-0d3e-45a7-bd54-4bd5b56058f9.png)

**Comment by isaacs** [comment]
> I really find it weird and puzzling why it threw error the first time on default npm version which came bundled with node 16.x.

Yeah, it's spooky for sure.  We'll keep a lookout for anyone else reporting it.

Just to be clear, you're saying that you got the latest npm installed successfully in the _actual_ global prefix, right?  Not just the `./prefix` place that my bash script dropped it for testing?

**Comment by owocado** [comment]
Yes, doing `which npm` does points to `usr/bin/npm` 👍🏻

**Comment by isaacs** [comment]
> Yes, doing which npm does points to usr/bin/npm 👍🏻

Ok, well... that's good, I guess.  Just adds to the spookiness though.  Maybe the gremlin will come back and we can catch it. 🤷 

Thanks for sharing ;)
