### ISSUE TITLE
npm ERR! cb() never called

### ISSUE THREAD

**Issue by epsi95** [npm/cli#3648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

logs:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/probhakar/.nvm/versions/node/v14.17.0/bin/node',
1 verbose cli   '/home/probhakar/.nvm/versions/node/v14.17.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   'videojs-playlist'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.0
4 verbose npm-session e1050d529ad847ec
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/videojs-playlist 1654ms
8 http fetch GET 200 https://registry.npmjs.org/videojs-playlist/-/videojs-playlist-4.3.1.tgz 91ms
9 silly pacote tag manifest for videojs-playlist@latest fetched in 1781ms
10 timing stage:loadCurrentTree Completed in 1850ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
16 silly install loadAllDepsIntoIdealTree
17 silly resolveWithNewModule videojs-playlist@4.3.1 checking installable status
18 http fetch GET 304 https://registry.npmjs.org/global 86ms (from cache)
19 silly pacote range manifest for global@^4.3.2 fetched in 92ms
20 silly resolveWithNewModule global@4.4.0 checking installable status
21 http fetch GET 304 https://registry.npmjs.org/video.js 159ms (from cache)
22 timing npm Completed in 2684ms
23 error cb() never called!
24 error This is an error with npm itself. Please report this error at:
25 error <https://npm.community>
```

### Expected Behavior

No crash

### Steps To Reproduce

`npm install videojs-playlist`

### Environment

- OS: Ubuntu 20.04.2 LTS
- Node: v14.17.0
- npm: 6.14.13

**Comment by ljharb** [comment]
Try with npm 7?

**Comment by epsi95** [comment]
I Will try, one point to mention that this error occurred only once, will try to reproduce it again on npm 7.

**Comment by lukekarrys** [comment]
**Closing:** We suspect this has to do with a combination of resource constraints within the device/program being used and the large amount of transient dependencies being installed by this command.

We've opened https://github.com/npm/statusboard/issues/395 for us to look deeper into this and track the discussion and fixes around it. You can also read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) for more information on why this issue might be happening currently and ways to debug it.
