### ISSUE TITLE
[BUG] 'npm update' removes all modules that exist, and adds the ones that doesn't

### ISSUE THREAD

**Issue by N247S** [npm/cli#3649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the 'npm update' ('npm install' yields the same result) command is run, it will remove all modules currently installed, and than proceeds to install all modules that are not currently installed. This means that if I add a single module after a previous npm-installation, I have to delete everything (in the node_module directory) in order to make it work properly.

Note that I use a nested workspace with asymlinked `node_modules` directory to share modules across multiple npm-packages / workspaces / projects

### Expected Behavior

I would expect it not throwing modules away which are still in the dependency section of the 'package.json' file

### Steps To Reproduce

**The setup:**

project structure:
```
|- workspace_dir
|    |- node_modules    [symlink to ./../node_modules]
|    |- package.json       [reffered to as nested_package.json]
|- node_modules
|- package.json            [reffered to as root_package.json]
```

`root_package.json`:
```javascript
{
  "workspaces": [
    "workspace_dir"
  ],
  "devDependencies": {
    /* The usual */
  }
}
```

`nested_package.json`:
```javascript
{
  "devDependencies": {
    /* The usual, it doesn't matter if these are identical to the 'root_package' or not.*/
  }
}
```

**Steps to reproduce:**
1. add some dependencies for a basic install situation (it doesn't matter which modules)
2. run `npm install` or `npm update` at the root of the whole setup
3. add another dependecy (doesn't matter which module) > Note, this can be skipped. The 'remove-if-present' behavior is still present without this step
4. run `npm install` or `npm update` and voilá

### Environment

- OS: Windows 10
- Node (tested it with): 16.6.1 & 16.6.2
- npm: 7.20.3

**Comment by nlf** [comment]
the symlinked `node_modules` found in `workspace_dir` is confusing the tree building algorithm. the simple fix here is to remove that symlink. workspaces have seen a lot of improvements over the last several months so your symlink workaround for older workspace support is no longer necessary.

i'm going to close this issue, but if removing the symlink and updating doesn't work for you, please open a new issue. thanks!
