### ISSUE TITLE
[BUG] Can't install node modules

### ISSUE THREAD

**Issue by zakcodez** [npm/cli#3651]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

I've been trying to install nodejs modules but it says 
![github_issue_image](https://user-images.githubusercontent.com/88604164/129436206-2c5cdd36-c64d-4b44-94a1-8e71aba09006.png)

### Expected Behavior

I expected it to go install the module as I told it to

### Steps To Reproduce

1. In command prompt, in the project directory
2. Run 'npm install --save-dev typescript'
3. See error ENOENT rename /node_modules/typescript to /node_modules/.typescript.DELETE

### Environment

- OS: Windows 7
- Node: v12.19.0
- npm: v6.14.8

**Comment by ljharb** [comment]
Try npm 7

**Comment by zakcodez** [comment]
Thanks, I've tested and solved the problem.
