### ISSUE TITLE
[BUG] Conditional responses from registry has incorrect vary header

### ISSUE THREAD

**Issue by DanielThomas** [npm/cli#3656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The 304 response from Cloudflare only includes `Accept-Encoding` in the `Vary` header causing upstream caches of the registry to miss when attempting to refresh the TTL for the object:

```
httpstat https://registry.npmjs.org/append-field -H 'If-None-Match: "ac4f53c3aebf01b17b1fa6f2a93c7714"'
Connected to 104.16.21.35:443 from 192.168.1.16:58835

HTTP/2 304
date: Tue, 17 Aug 2021 04:26:20 GMT
cf-ray: 680024c70a2c377a-MEL
age: 1634
cache-control: public, max-age=300
etag: "ac4f53c3aebf01b17b1fa6f2a93c7714"
last-modified: Sat, 24 Jul 2021 13:35:45 GMT
vary: Accept-Encoding
cf-cache-status: HIT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
x-amz-replication-status: COMPLETED
server: cloudflare
```

### Expected Behavior

A 304 response should contain the same `Vary` headers as a 200 response:
```
❯ httpstat https://registry.npmjs.org/append-field
Connected to 104.16.21.35:443 from 192.168.1.16:58839

HTTP/2 200
date: Tue, 17 Aug 2021 04:26:30 GMT
content-type: application/json
content-length: 7029
cf-ray: 68002502fe74df2c-MEL
accept-ranges: bytes
age: 1644
cache-control: public, max-age=300
etag: "ac4f53c3aebf01b17b1fa6f2a93c7714"
last-modified: Sat, 24 Jul 2021 13:35:45 GMT
vary: accept-encoding, accept
cf-cache-status: HIT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
x-amz-replication-status: COMPLETED
server: cloudflare
```

### Steps To Reproduce

1. Make a registry request for any package and note the `Last-Modified` header
2. Make a conditional request with a `If-Modified-Since` with that value and note that `Vary` does not include the expected headers

### Environment

N/A

**Comment by wraithgar** [comment]
**Closing:** this looks to be an issue with the registry which is outside the scope of this repo. For registry support please go to [npmjs.com/support](https://www.npmjs.com/support). If you believe this is a bug with the cli, please provide further clarifying details.
