### ISSUE TITLE
cb() never called!

### ISSUE THREAD

**Issue by kunal-thakare-ai** [npm/cli#3657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- OS: Windows 10
- Node: v14.17.5.
- npm: 7.20.6

**Comment by adorratm** [comment]
I got same error when I was installing nuxtjs on npm 6.14.14 and node 14.17.5 version.

**Comment by wlinkin** [comment]
Just got the same error on node 14.17.3 and npm 6.14.13.
```sh
574 timing npm Completed in 2093ms
575 error cb() never called!
576 error This is an error with npm itself. Please report this error at:
577 error <https://npm.community>
```

**Comment by shrishail735** [comment]
i got same error

**Comment by shrishail735** [comment]
Is there any solution?

**Comment by yoan-asdrubal** [comment]
i got same error with node V14.17.3 and npm 7.21.0

**Comment by akhilkineton** [comment]
Strangely for me deleting the package-lock.json and running npm install worked

**Comment by lukekarrys** [comment]
**Closing:** We suspect this has to do with a combination of resource constraints within the device/program being used and the large amount of transient dependencies being installed by this command.

We've opened https://github.com/npm/statusboard/issues/395 for us to look deeper into this and track the discussion and fixes around it. You can also read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) for more information on why this issue might be happening currently and ways to debug it.
