### ISSUE TITLE
[BUG] npm audit-level no error exit

### ISSUE THREAD

**Issue by Keepertje** [npm/cli#3659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a project with the dependency that has a vulnerability. When I run
npm audit --audit-level=low it shows there is high vulnerability.

![Inked129749970-f096b31f-d0e8-4c82-842d-0aab46ce7f64_LI](https://user-images.githubusercontent.com/5364290/129750592-31ee35e9-ba7e-4fc9-8159-b6e26c53d11b.jpg)

It does show a verb code of 1 when using --verbose
![image](https://user-images.githubusercontent.com/5364290/129750358-1225f59d-0805-4600-b71d-62859b8d93d3.png)

### Expected Behavior

I expect it to throw an error. Which I do not see in the output terminal. 

### Steps To Reproduce

npm install --save trim-newlines@3.0.0
npm audit --audit-level=low

### Environment

- OS: Windows
- Node:  12.18.4
- npm: 7.20.6

**Comment by ljharb** [comment]
It exits nonzero, which means it failed, and would fail a CI check or a && chain.

**Comment by Keepertje** [comment]
Thank you! Then I will close the issue.
