### ISSUE TITLE
 error cb() never called![BUG] <title>

### ISSUE THREAD

**Issue by imrancrystal** [npm/cli#3663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli'
1 verbose cli ]
2 info using npm@6.14.14
3 info using node@v14.17.5
4 verbose npm-session 8541cc02e724d4f5
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/@angular%2fcli 482ms
8 http fetch GET 200 https://registry.npmjs.org/@angular/cli/-/cli-12.2.2.tgz 113ms
9 silly pacote tag manifest for @angular/cli@latest fetched in 651ms
10 timing stage:loadCurrentTree Completed in 702ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 2ms
16 silly install loadAllDepsIntoIdealTree
17 silly resolveWithNewModule @angular/cli@12.2.2 checking installable status
18 http fetch GET 200 https://registry.npmjs.org/jsonc-parser 129ms
19 http fetch GET 200 https://registry.npmjs.org/@yarnpkg%2flockfile 160ms
20 http fetch GET 200 https://registry.npmjs.org/ini 161ms
21 http fetch GET 200 https://registry.npmjs.org/debug 186ms
22 http fetch GET 200 https://registry.npmjs.org/ini/-/ini-2.0.0.tgz 128ms
23 http fetch GET 200 https://registry.npmjs.org/debug/-/debug-4.3.2.tgz 106ms
24 http fetch GET 200 https://registry.npmjs.org/ansi-colors 302ms
25 http fetch GET 200 https://registry.npmjs.org/jsonc-parser/-/jsonc-parser-3.0.0.tgz 168ms
26 silly pacote version manifest for ini@2.0.0 fetched in 313ms
27 silly resolveWithNewModule ini@2.0.0 checking installable status
28 silly pacote version manifest for debug@4.3.2 fetched in 322ms
29 silly resolveWithNewModule debug@4.3.2 checking installable status
30 silly pacote version manifest for jsonc-parser@3.0.0 fetched in 319ms
31 silly resolveWithNewModule jsonc-parser@3.0.0 checking installable status
32 http fetch GET 200 https://registry.npmjs.org/ansi-colors/-/ansi-colors-4.1.1.tgz 59ms
33 silly pacote version manifest for ansi-colors@4.1.1 fetched in 380ms
34 silly resolveWithNewModule ansi-colors@4.1.1 checking installable status
35 http fetch GET 200 https://registry.npmjs.org/open 80ms
36 http fetch GET 200 https://registry.npmjs.org/npm-pick-manifest 93ms
37 http fetch GET 200 https://registry.npmjs.org/inquirer 420ms
38 http fetch GET 200 https://registry.npmjs.org/npm-package-arg 123ms
39 http fetch GET 200 https://registry.npmjs.org/ora 81ms
40 http fetch GET 200 https://registry.npmjs.org/open/-/open-8.2.1.tgz 54ms
41 silly pacote version manifest for open@8.2.1 fetched in 150ms
42 silly resolveWithNewModule open@8.2.1 checking installable status
43 http fetch GET 200 https://registry.npmjs.org/npm-pick-manifest/-/npm-pick-manifest-6.1.1.tgz 80ms
44 http fetch GET 200 https://registry.npmjs.org/inquirer/-/inquirer-8.1.2.tgz 75ms
45 http fetch GET 200 https://registry.npmjs.org/npm-package-arg/-/npm-package-arg-8.1.5.tgz 69ms
46 silly pacote version manifest for npm-pick-manifest@6.1.1 fetched in 194ms
47 silly resolveWithNewModule npm-pick-manifest@6.1.1 checking installable status
48 silly pacote version manifest for inquirer@8.1.2 fetched in 522ms
49 silly resolveWithNewModule inquirer@8.1.2 checking installable status
50 http fetch GET 200 https://registry.npmjs.org/ora/-/ora-5.4.1.tgz 68ms
51 silly pacote version manifest for npm-package-arg@8.1.5 fetched in 213ms
52 silly resolveWithNewModule npm-package-arg@8.1.5 checking installable status
53 silly pacote version manifest for ora@5.4.1 fetched in 162ms
54 silly resolveWithNewModule ora@5.4.1 checking installable status
55 http fetch GET 200 https://registry.npmjs.org/@yarnpkg/lockfile/-/lockfile-1.1.0.tgz 392ms
56 silly pacote version manifest for @yarnpkg/lockfile@1.1.0 fetched in 563ms
57 silly resolveWithNewModule @yarnpkg/lockfile@1.1.0 checking installable status
58 http fetch GET 200 https://registry.npmjs.org/@schematics%2fangular 659ms
59 http fetch GET 200 https://registry.npmjs.org/uuid 118ms
60 http fetch GET 200 https://registry.npmjs.org/pacote 189ms
61 http fetch GET 200 https://registry.npmjs.org/semver 159ms
62 http fetch GET 200 https://registry.npmjs.org/resolve 174ms
63 http fetch GET 200 https://registry.npmjs.org/@angular-devkit%2farchitect 722ms
64 http fetch GET 200 https://registry.npmjs.org/uuid/-/uuid-8.3.2.tgz 73ms
65 silly pacote version manifest for uuid@8.3.2 fetched in 240ms
66 silly resolveWithNewModule uuid@8.3.2 checking installable status
67 http fetch GET 200 https://registry.npmjs.org/resolve/-/resolve-1.20.0.tgz 93ms
68 http fetch GET 200 https://registry.npmjs.org/pacote/-/pacote-11.3.5.tgz 118ms
69 http fetch GET 200 https://registry.npmjs.org/semver/-/semver-7.3.5.tgz 101ms
70 silly pacote version manifest for resolve@1.20.0 fetched in 296ms
71 silly resolveWithNewModule resolve@1.20.0 checking installable status
72 silly pacote version manifest for pacote@11.3.5 fetched in 342ms
73 silly resolveWithNewModule pacote@11.3.5 checking installable status
74 silly pacote version manifest for semver@7.3.5 fetched in 293ms
75 silly resolveWithNewModule semver@7.3.5 checking installable status
76 http fetch GET 200 https://registry.npmjs.org/@angular-devkit/architect/-/architect-0.1202.2.tgz 103ms
77 silly pacote version manifest for @angular-devkit/architect@0.1202.2 fetched in 859ms
78 silly resolveWithNewModule @angular-devkit/architect@0.1202.2 checking installable status
79 http fetch GET 200 https://registry.npmjs.org/@angular-devkit%2fschematics 869ms
80 http fetch GET 200 https://registry.npmjs.org/@angular-devkit/schematics/-/schematics-12.2.2.tgz 188ms
81 silly pacote version manifest for @angular-devkit/schematics@12.2.2 fetched in 1077ms
82 silly resolveWithNewModule @angular-devkit/schematics@12.2.2 checking installable status
83 http fetch GET 200 https://registry.npmjs.org/@schematics/angular/-/angular-12.2.2.tgz 1141ms
84 http fetch GET 200 https://registry.npmjs.org/symbol-observable 1265ms
85 silly pacote version manifest for @schematics/angular@12.2.2 fetched in 1836ms
86 silly resolveWithNewModule @schematics/angular@12.2.2 checking installable status
87 http fetch GET 200 https://registry.npmjs.org/symbol-observable/-/symbol-observable-4.0.0.tgz 60ms
88 silly pacote version manifest for symbol-observable@4.0.0 fetched in 1336ms
89 silly resolveWithNewModule symbol-observable@4.0.0 checking installable status
90 timing npm Completed in 3408ms
91 error cb() never called!
92 error This is an error with npm itself. Please report this error at:
93 error <https://npm.community>

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- OS: WIndows
- Node:v14.17.5 
- npm: npm install -g @angular/cli

**Comment by primus852** [comment]
+1

## Environment
- OS: In Docker Image `trion/ng-cli-karma:12.2.2`
- Node: v14.17.5
- npm: 6.14.14

## Pipeline Settings
```
.unit-tests:
  stage: test
  image: ${TRION_IMAGE}
  before_script:
    - node -v
    - npm -v
    - npm cache clean --force
    - npm ci --prefer-offline --no-audit --cache .npm
    - git fetch origin
  cache:
    paths:
      - node_modules/
      - .npm
  ...
```

## Logs (truncated to last lines)
```
...
14645 silly tarball trying @protobufjs/aspromise@1.1.2 by hash: sha1-m4sMxmPWaafY9vXQiToU00jzD78=
14646 silly tarball trying @protobufjs/base64@1.1.2 by hash: sha512-AZkcAA5vnN/v4PDqKyMR5lx7hZttPDgClv83E//FMNhR2TMcLUhfRUBHCmSl0oi9zMgDDqRUJkSxO3wm85+XLg==
14647 silly tarball trying @protobufjs/codegen@2.0.4 by hash: sha512-YyFaikqM5sH0ziFZCN3xDC7zeGaB/d0IUb9CATugHWbd1FRFwWwt4ld4OYMPWu5a3Xe01mGAULCdqhMlPl29Jg==
14648 silly tarball trying @protobufjs/eventemitter@1.1.0 by hash: sha1-NVy8mLr61ZePntCV85diHx0Ga3A=
14649 silly tarball trying @protobufjs/fetch@1.1.0 by hash: sha1-upn7WYYUr2VwDBYZ/wbUVLDYTEU=
14650 silly tarball trying @protobufjs/float@1.0.2 by hash: sha1-Xp4avctz/Ap8uLKR33jIy9l7h9E=
14651 silly tarball trying @protobufjs/inquire@1.1.0 by hash: sha1-/yAOPnzyQp4tyvwRQIKOjMY48Ik=
14652 silly tarball trying @protobufjs/path@1.1.2 by hash: sha1-bMKyDFya1q0NzP0hynZz2Nf79o0=
14653 silly tarball trying @protobufjs/pool@1.1.0 by hash: sha1-Cf0V8tbTq/qbZbw2ZQbWrXhG/1Q=
14654 silly tarball trying @protobufjs/utf8@1.1.0 by hash: sha1-p3c2C1s5oaLlEG+OhY8v0tBgxXA=
14655 silly tarball no local data for @protobufjs/aspromise@1.1.2. Extracting by manifest.
14656 silly tarball no local data for @protobufjs/base64@1.1.2. Extracting by manifest.
14657 silly tarball no local data for @protobufjs/codegen@2.0.4. Extracting by manifest.
14658 silly tarball no local data for @protobufjs/eventemitter@1.1.0. Extracting by manifest.
14659 silly tarball no local data for @protobufjs/fetch@1.1.0. Extracting by manifest.
14660 silly tarball no local data for @protobufjs/float@1.0.2. Extracting by manifest.
14661 silly tarball no local data for @protobufjs/inquire@1.1.0. Extracting by manifest.
14662 silly tarball no local data for @protobufjs/path@1.1.2. Extracting by manifest.
14663 silly tarball no local data for @protobufjs/pool@1.1.0. Extracting by manifest.
14664 silly tarball no local data for @protobufjs/utf8@1.1.0. Extracting by manifest.
14665 http fetch GET 200 https://registry.npmjs.org/@protobufjs/inquire/-/inquire-1.1.0.tgz 65ms
14666 http fetch GET 200 https://registry.npmjs.org/@protobufjs/path/-/path-1.1.2.tgz 64ms
14667 silly extract @protobufjs/path@1.1.2 extracted to /builds/epikur/plattform-frontend/node_modules/@protobufjs/path (73ms)
14668 silly extract @protobufjs/inquire@1.1.0 extracted to /builds/epikur/plattform-frontend/node_modules/@protobufjs/inquire (73ms)
14669 http fetch GET 200 https://registry.npmjs.org/@protobufjs/pool/-/pool-1.1.0.tgz 88ms
14670 silly extract @protobufjs/pool@1.1.0 extracted to /builds/epikur/plattform-frontend/node_modules/@protobufjs/pool (98ms)
14671 http fetch GET 200 https://registry.npmjs.org/@protobufjs/codegen/-/codegen-2.0.4.tgz 91ms
14672 silly extract @protobufjs/codegen@2.0.4 extracted to /builds/epikur/plattform-frontend/node_modules/@protobufjs/codegen (100ms)
14673 http fetch GET 200 https://registry.npmjs.org/@protobufjs/eventemitter/-/eventemitter-1.1.0.tgz 104ms
14674 silly extract @protobufjs/eventemitter@1.1.0 extracted to /builds/epikur/plattform-frontend/node_modules/@protobufjs/eventemitter (112ms)
14675 http fetch GET 200 https://registry.npmjs.org/@protobufjs/base64/-/base64-1.1.2.tgz 188ms
14676 silly extract @protobufjs/base64@1.1.2 extracted to /builds/epikur/plattform-frontend/node_modules/@protobufjs/base64 (196ms)
14677 http fetch GET 200 https://registry.npmjs.org/@protobufjs/fetch/-/fetch-1.1.0.tgz 197ms
14678 silly extract @protobufjs/fetch@1.1.0 extracted to /builds/epikur/plattform-frontend/node_modules/@protobufjs/fetch (206ms)
14679 http fetch GET 200 https://registry.npmjs.org/@protobufjs/aspromise/-/aspromise-1.1.2.tgz 218ms
14680 silly extract @protobufjs/aspromise@1.1.2 extracted to /builds/epikur/plattform-frontend/node_modules/@protobufjs/aspromise (224ms)
14681 http fetch GET 200 https://registry.npmjs.org/@protobufjs/utf8/-/utf8-1.1.0.tgz 238ms
14682 silly extract @protobufjs/utf8@1.1.0 extracted to /builds/epikur/plattform-frontend/node_modules/@protobufjs/utf8 (251ms)
14683 http fetch GET 200 https://registry.npmjs.org/@protobufjs/float/-/float-1.0.2.tgz 273ms
14684 silly extract @protobufjs/float@1.0.2 extracted to /builds/epikur/plattform-frontend/node_modules/@protobufjs/float (282ms)
14685 timing npm Completed in 51605ms
14686 error cb() never called!
14687 error This is an error with npm itself. Please report this error at:
14688 error <https://npm.community>
```

**Comment by lukekarrys** [comment]
**Closing:** We suspect this has to do with a combination of resource constraints within the device/program being used and the large amount of transient dependencies being installed by this command.

We've opened https://github.com/npm/statusboard/issues/395 for us to look deeper into this and track the discussion and fixes around it. You can also read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) for more information on why this issue might be happening currently and ways to debug it.
