### ISSUE TITLE
[BUG] Bad error wording consequent to typo

### ISSUE THREAD

**Issue by Aster89** [npm/cli#3670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I entered
```
$ npm isntall --save-dev kss
```
I got
```
npm ERR! The `npm ci` command can only install with an existing package-lock.json or
npm ERR! npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
npm ERR! later to generate a package-lock.json file, then try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/enrico/.npm/_logs/2021-08-20T15_54_49_990Z-debug.log
```
and so I spent quite a lot surfing the web for a solution... except that there's no problem to solve, as I have simply written `isntall` instead of `install`.

### Expected Behavior

A better wording such as this:
```
$ npm isntall --save-dev kss
npm ERR! The `isntall` command does not exist. Do you mean `install`?
```

### Steps To Reproduce

See above

### Environment

- OS: archlinux
- Node:
- npm: 7.21.0

**Comment by ljharb** [comment]
I'd expect `isntall` to be an alias for `install`, not `ci`.
