### ISSUE TITLE
[BUG] <title> npm ERR! 404  '@types/mongoose-findorcreate@latest' is not in the npm registry. </title>

### ISSUE THREAD

**Issue by CodeVisionary** [npm/cli#3674]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

I am currently studying google OAuth 2.0 with which I need the function `mongoose-findorcreate` but when I installed it, there was an error that said `npm ERR! 404  @types/mongoose-findorcreate@latest' is not in the npm registry.` (after I installed it) and then it told me to try `npm i --save-dev @types/mongoose-findorcreate` in cmd(i am using gitbash as my default terminal) which I did but instead it gave me the following error 
```
`npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2fmongoose-findorcreate - Not found
npm ERR! 404
npm ERR! 404  '@types/mongoose-findorcreate@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

```
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\*****\AppData\Roaming\npm-cache\_logs\2021-08-22T07_22_58_212Z-debug.log
And I went to this github issue [#8465](https://github.com/facebook/create-react-app/issues/8465#) to look for an answer, a guy said to install 'error-ex' npm module to fix this and i did but as soon as i did, I got the same error which is
```
 npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2ferror-ex - Not found
npm ERR! 404
npm ERR! 404  '@types/error-ex@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\*****\AppData\Roaming\npm-cache\_logs\2021-08-22T07_29_06_832Z-debug.log`.
```
I don't know what to do when this happens and please reply at the latest.

### Expected Behavior

I just want it to say 
````
npm WARN secrets@1.0.0 No repository field.

+ error-ex@1.3.2
added 2 packages from 1 contributor and audited 23 packages in 1.638s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
````
and

```
npm WARN secrets@1.0.0 No repository field.

+ mongoose-findorcreate@3.0.0
updated 1 package and audited 21 packages in 0.967s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

### Steps To Reproduce

1. Follow a course
2. do what they do
3. download the npm modules they download
4. get the error

### Environment

- OS: Windows 10
- Node: 14.17.5 **LTS**
- npm: 7.21.0

**Comment by lukekarrys** [comment]
Try running `npm i mongoose-findorcreate` and `npm i error-ex`. The error messages you showed are trying to install `@types/mongoose-findorcreate` and `@types/error-ex` which are for the standard location for type definitions, but in this case those packages do not have types published to the npm registry.
