### ISSUE TITLE
[BUG] many of the modules not found

### ISSUE THREAD

**Issue by Sattushivaa** [npm/cli#3675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Module not found

### Expected Behavior

Running successfully

### Steps To Reproduce

1. In cmd or terminal 
2. Run these commands
    a) npm install ws
    b) node
    c) const ws = require("ws")

### Environment

- OS: 
- Node: 
- npm:

**Comment by isaacs** [comment]
Please fill out the template.  What npm version are you using?  Does it work if you upgrade to the latest?  What other packages are installed in your project?  What does `npm ls` report?

**Comment by ruyadorno** [comment]
**Closing:** please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).
