### ISSUE TITLE
[BUG] Backslashes in additional arguments given to npm run scripts are escaped wrongly

### ISSUE THREAD

**Issue by c3er** [npm/cli#3680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Note: This bug is similar to #2638 but not the same.

Given the following `package.json`:

```json
  "scripts": {
    "start": "node index.js"
  }
}
```

And this `index.js`:

```js
console.log(process.argv)
```

Backslashes in additional arguments to `npm start` are escaped wrongly in most cases, i.e. the script gets via `process.argv` *two* backslashes for each given backslash.

Example:

```
$ npm start path\to\file

> start
> node index.js "path\\to\\file"

[
  'C:\\nodejs\\node.exe',
  'C:\\Users\\FlipperX\\Desktop\\tmp\\test\\index.js',
  'path\\\\to\\\\file'
]
```

If the additional argument is only a backslash, it works as expected:

```
$ npm start \

> start
> node index.js "\\"

[
  'C:\\nodejs\\node.exe',
  'C:\\Users\\FlipperX\\Desktop\\tmp\\test\\index.js',
  '\\'
]
```

### Expected Behavior

Given the above example, `process.argv` should look like this:

```
[
  'C:\\nodejs\\node.exe',
  'C:\\Users\\FlipperX\\Desktop\\tmp\\test\\index.js',
  'path\\to\\file'
]
```

### Steps To Reproduce

1. In this environment...

Via CLI

2. With this config...

`package.json`

```json
  "scripts": {
    "start": "node index.js"
  }
}
```

`index.js`

```js
console.log(process.argv)
```

3. Run `npm start path\to\file`

4. See error...

`'path\\\\to\\\\file'` instead of `'path\\to\\file'`

### Environment

- OS: Windows 10 21H1 64 Bit
- Node: 16.7.0 but also 14.17.5
- npm: 7.19.1

**Comment by arapoport** [comment]
I recently stumbled over this problem. npm 8.3.0 is affected too. npm 6.14.15 is not affected.

**Comment by silkfire** [comment]
Having the same problem with `npx`. Can someone look into this?
