### ISSUE TITLE
npm react-discussion-board  : Image url not ending with ( ' )

### ISSUE THREAD

**Issue by KhNikh** [npm/cli#3683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In npm react-discussion-board package the is a image url which is not ending with '
here is the code: 
profileImage:
        'https://www.rd.com/wp-content/uploads/2017/09/01-shutterstock_476340928-Irina-Bg.jpg,
      name: 'Jane Doe',
      content: '<p>Hello everyone!</p><p>How are you all doing?</p><p>-Jane</>',
      date: new Date('01 Jan 2020 01:12:00 GMT')

there should be a ( ' )before coma ( , ) in profileImage

### Expected Behavior

There should be a ( ' )before coma ( , ) in profileImage

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- OS: 
- Node: 
- npm:

**Comment by DanielRuf** [comment]
Please report this at https://github.com/mdeforest/react-discussion-board/issues.
