### ISSUE TITLE
diff from installing from git tag versus registry

### ISSUE THREAD

**Issue by romainPrignon** [npm/cli#3691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to install a package from github using ssh
```
npm i -g github:georgestech/denis-cli
```
I have to following output
```
/usr/local/lib/node_modules/@georgestech/denis-cli $ ls
README.md  bin	node_modules  package-lock.json  package.json  types
```
```
$ denis
CLI to manage developer's common tasks

VERSION
  @georgestech/denis-cli/21.8.24-3379953 linux-x64 node-v14.16.0

USAGE
  $ denis [COMMAND]

COMMANDS
  help  display help for denis
```

### Expected Behavior

When I install the same package from github repository
```
npm config set @georgestech:registry https://npm.pkg.github.com/
npm config set //npm.pkg.github.com/:_authToken ***
npm i -g @georgestech/denis-cli
```
I have to following output
```
/usr/local/lib/node_modules/@georgestech/denis-cli $ ls
README.md  bin	lib  node_modules  package-lock.json  package.json  types
```
```
$ denis
CLI to manage developer's common tasks

VERSION
  @georgestech/denis-cli/21.8.24-3379953 linux-x64 node-v14.16.0

USAGE
  $ denis [COMMAND]

TOPICS
  db  manage your local database

COMMANDS
  help     display help for denis
  install  install project dependencies
  publish  publish current project on our github registry
  release  create a release of the current project using calver version number
  update   update project dependencies
```

### Steps To Reproduce

on each commit, the github ci do:
```
update package.json version field with $version
git add package.json package-lock.json
git commit -m "🔖 Release $version"
git tag -a $version -m "🔖 Release $version"
git tag -f -a $daily_version
git push
git push -f --tags
```

21.8.24-3379953 and 21.8.24 point to the same commit

### Environment

- OS: Ubuntu 20.04, docker node:lts, github action,...
- Node: lts
- npm: 6.14.11 and 7@latest

**Comment by romainPrignon** [comment]
It's like npm install didn't download all the file from github ?
I do have a src/ folder in denis-cli repo on github

**Comment by wraithgar** [comment]
That github package does not exist.

Installing from a git repo is different than installing from the registry. What's uploaded to the registry is a tarball with contents that are often different than repo contents because of lifecycle scripts such as `prepare` and `prepublishOnly`.  Without being able to duplicate we could only speculate as to why that difference is there.  My guess would be that the contents of the git repo changed, and were not published.
