### ISSUE TITLE
[BUG] <title>command failed: npm install --loglevel error --legacy-peer-deps

### ISSUE THREAD

**Issue by Amir-16** [npm/cli#3700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- OS: 
- Node: 
- npm: npm

**Comment by ljharb** [comment]
Please fill out the issue template. What error did it fail with?

**Comment by isaacs** [comment]
Will reopen if more details are provided.  As much as we'd love to help you, there's not much we can do with just "an install failed somewhere, somehow".
