### ISSUE TITLE
[BUG] Many `npm_package_*` and `npm_config_*` fields not exposed in process.env

### ISSUE THREAD

**Issue by valentinoli** [npm/cli#3701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`npm_package_description` is not present in `process.env` and it seems like many other fields are missing too. This works correctly in npm `6.14.5`

### Expected Behavior

`npm_package_description` should be defined in `process.env`

### Steps To Reproduce

1. In package.json put a "descriptions" field
2. Add `index.js` file containing
``` js
console.log(process.env.npm_package_description)
```
3. Add a script to the "scripts" section of package.json:
```json
"scripts": {
  "index": "node index.js"
}
```
4. Run `npm run index`

### Environment

- OS: Windows
- Node: 16.8.0
- npm: 7.21.0

**Comment by ljharb** [comment]
This was intentional in npm 7, at least for the package fields, since you can read package.json yourself.

**Comment by valentinoli** [comment]
@ljharb You are right, thanks for pointing that out. I found the [RFC](https://github.com/npm/rfcs/blob/latest/implemented/0021-reduce-lifecycle-script-environment.md)
