### ISSUE TITLE
[BUG] Windows documentation, "A brief note on the built-in Windows configuration"

### ISSUE THREAD

**Issue by ArfyFR** [npm/cli#3706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Documentation
https://docs.npmjs.com/try-the-latest-stable-version-of-npm#a-brief-note-on-the-built-in-windows-configuration
says for example
`npm config set prefix "${APPDATA}/npm" -g
`

### Expected Behavior

Work in DOS cmd.exe ;)

Right command in a DOC cmd.exe (with Administrator rights !) is
`npm config set prefix "%APPDATA%\npm" -g
`

with 

- %APPDATA% and not ${APPDATA}
- \ and not /

to work well in Windows cmd.exe (note: again, with Administrator rights)

### Steps To Reproduce

1. In Windows 10 Prof
2. Have NodeJs installed
3. Try to install a package with npm and "-g" flaf
4. Error due to "admin rights" and trying to install in C:\Program Files\...
5. Launch a cmd.exe
6. Try to launch yoyr command from your site
7. NPM will try to install in a non existent PATH !

### Environment

- OS: Windows 10 Pro
- Node: 16.8
- npm: 7.19.0

**Comment by ljharb** [comment]
Can you try the latest version of npm 7?

**Comment by fritzy** [comment]
Fixed in https://github.com/npm/documentation/pull/33

**Comment by ArfyFR** [comment]
> Can you try the latest version of npm 7?

Npm update done with
`npm install -g npm@latest verbose`
it stays to 7.19.0

**Comment by wraithgar** [comment]
Closing as per @fritzy's comment
