### ISSUE TITLE
[BUG] Windows, EPERM error trying to access `.npmrc` if it is set to hidden

### ISSUE THREAD

**Issue by nelson2tm** [npm/cli#3709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This issue is the same as the `v6` issue npm/cli#768. Re-filed since it is reproducible in `v7`.

If `.npmrc` is set to hidden in Windows and we attempt to change the npm config by using for example `npm config edit`, an EPERM error is thrown:

```
npm ERR! code EPERM
npm ERR! syscall open
npm ERR! path C:\Users\Username\.npmrc
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, open 'C:\Users\Username\.npmrc'
npm ERR!  [Error: EPERM: operation not permitted, open 'C:\Users\Username\.npmrc'] {
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\\Users\\Username\\.npmrc'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.
```

### Expected Behavior

The npm config should be editable by using the `npm config` command, even while `.npmrc` is set to hidden. For example, using `npm config edit`, a notepad window should open containing the config's contents.

### Steps To Reproduce

1. Go to the user directory in Windows Explorer.
2. Hide `npmrc`: right click `.npmrc`, click "Properties" and enable "Hidden".
2. Open `cmd` and execute `npm config edit`. An EPERM error is printed in the console.

### Environment

- OS: Windows 10 (21H1 build 19043.1165)
- Node: 16.8.0
- npm: 7.21.1

**Comment by wraithgar** [comment]
If we can't write to the file, then this error is what is expected.  When you set a file to hidden, node can not write to that file.

**Comment by rivy** [comment]
@wraithgar , @nelson2tm

This bug should be re-opened. 

`node` *can* write to a WinOS file with the hidden attribute set if the correct file system flags are used (specifically 'r+'). This is noted in the [flags section of the node documentation](https://nodejs.org/api/fs.html#file-system-flags). This documentation was added by https://github.com/nodejs/node/commit/4f1d54829b056d4aefb5a7b57b561898815599b9 in October of 2017.

This is a long term bug that has bitten lots of folks over the years. And it keeps coming up. Yes, in the best case, `node` should have fixed it, but they haven't/won't.

There's a lot of discussion and shrugging over the years...

https://github.com/nodejs/node/issues/14553
https://github.com/nodejs/node/issues/41093
https://github.com/libuv/libuv/pull/3380

But it looks like others have mitigated it...

`bun` mitigated it (see https://github.com/oven-sh/bun/pull/9370/changes#diff-aa425271d32de2d242a358e76bf30fd393e289944992e31468faee588f628993R827-R845) directly by retrying opens with an added hidden attribute for files which fail with EPERM for files opened for writing.

And immich just avoids pure 'w' opens (see https://github.com/immich-app/immich/pull/12812), only creating or overwriting.

Mitigation for this for `npm` would be appreciated. Using 'r+' is documented to work.

But, at least a better error message suggesting that removing the "hidden" attribute could fix the problem would be helpful to users banging into this issue. The current error message suggests a "permissions" problem which points users in the wrong direction.
