### ISSUE TITLE
[Feature] : Test to run on CI (Github Actions)

### ISSUE THREAD

**Issue by mohitmishra786** [npm/cli#3712]
Tests are not running on push or pull request So added on Github Actions

**Comment by isaacs** [comment]
Tests are run on push, but pull request actions have to be allowed by a collaborator for first-time contributors.
<img width="611" alt="Screen Shot 2021-09-02 at 11 01 18 " src="https://user-images.githubusercontent.com/9287/131907954-0665268c-d4e4-4687-96fc-3c3d31071573.png">
