### ISSUE TITLE
[BUG] can not install yarn properly on termux

### ISSUE THREAD

**Issue by RRMovies** [npm/cli#3717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**Exit handler never called!**

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- OS: 
- Node: 
- npm:

**Comment by ljharb** [comment]
I believe termux uses the `PREFIX` environment variable, which npm will use to change where `npm root -g` is, which will mess with global installs.

Use `npx yarn`, or don't use termux, since they're unlikely to stop using `PREFIX`.

**Comment by lukekarrys** [comment]
**Closing:** We suspect this has to do with a combination of resource constraints within the device/program being used and the large amount of transient dependencies being installed by this command.

We've opened https://github.com/npm/statusboard/issues/395 for us to look deeper into this and track the discussion and fixes around it. You can also read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) for more information on why this issue might be happening currently and ways to debug it.
