### ISSUE TITLE
[BUG] '"-S"' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by huan** [npm/cli#3719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I want to put `--no-warnings --loader ts-node/esm --experimental-vm-modules` to node args, so we use `env -S`:

```sh
 #!/usr/bin/env -S node --no-warnings --loader ts-node/esm --experimental-vm-modules 
```

> https://github.com/huan/sidecar/blob/28461a00a1553f6a0008f39b279899971781a767/bin/sidecar-dump.ts#L1

However, this will generate the following `node_modules/.bin` files:

```cmd
IF EXIST "%dp0%\-S.exe" (
  SET "_prog=%dp0%\-S.exe"
) ELSE (
  SET "_prog=-S"
  SET PATHEXT=%PATHEXT:;.JS;=;%
)
```

```ps1
if (Test-Path "$basedir/-S$exe") {
  # Support pipeline input
  if ($MyInvocation.ExpectingInput) {
    $input | & "$basedir/-S$exe" node --no-warnings --loader ts-node/esm --experimental-vm-modules "$basedir/../sidecar/dist/esm/bin/sidecar-dump.js" $args
  } else {
    & "$basedir/-S$exe" node --no-warnings --loader ts-node/esm --experimental-vm-modules "$basedir/../sidecar/dist/esm/bin/sidecar-dump.js" $args
  }
  $ret=$LASTEXITCODE
}
```

### Expected Behavior

The `-S.exe` and `-s$exe` are both not correct, which should be set to `node.exe`

### Steps To Reproduce

Under windows:

1. npm install sidecar@0.15.27
2. run 
```ps1
PS> type .\node_modules\.bin\sidecar-dump.cmd
@ECHO off
GOTO start
:find_dp0
SET dp0=%~dp0
EXIT /b
:start
SETLOCAL
CALL :find_dp0

IF EXIST "%dp0%\-S.exe" (
  SET "_prog=%dp0%\-S.exe"
) ELSE (
  SET "_prog=-S"
  SET PATHEXT=%PATHEXT:;.JS;=;%
)

endLocal & goto #_undefined_# 2>NUL || title %COMSPEC% & "%_prog%" node --no-warnings --loader ts-node/esm --experimental-vm-modules "%dp0%\..\sidecar\dist\esm\bin\sidecar-dump.js" %*
```
4. See error `IF EXIST "%dp0%\-S.exe" (` which is not correct: `-S.exe` should be `node.exe`

### Environment

- OS: Windows
- Node: 16
- npm: 7.15.1

Link to:

- https://github.com/huan/sidecar/issues/19
- https://github.com/npm/cmd-shim/issues/54

**Comment by wraithgar** [comment]
This is the repo for npm issues. It looks like this is a problem with using node itself.  I believe issues for that are to be created at https://github.com/nodejs/node

**Comment by huan** [comment]
No, it's not the node problem but the npm `cmd-shim `

See:

- https://github.com/npm/cmd-shim/issues/54
