### ISSUE TITLE
[BUG] Proxy issues on v7.22.0 but not on v7.21.1

### ISSUE THREAD

**Issue by tarkant** [npm/cli#3728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

npm 7.22.0 fails to fetch a random package with a 403/401 error.

Trying this on previous versions of npm like 6.x.x or 7.21.1 seems to work as expected.

## Notes
* Configuring the proxy in `.npmrc` does not help.
* Of course we've tried cleaning up, another machine and even reinstalling everything.

### Expected Behavior

npm is supposed to fetch and install all packages without errors.

### Steps To Reproduce

1. On Windows 10 on a corporate computer with Zscaler enabled.
2. Run `npm install` with npm@7.22.0
3. npm will fail with a 403 or 401 error on a random package install
4. Downgrade npm@7.21.1
5. Run `npm install`
6. Installation will run as expected

### Environment

- OS: Windows 10
- Node: 16.9.0 and 14.17.6
- npm: 7.22.0

**Comment by wraithgar** [comment]
There is not enough info here to reproduce this locally.  If this is still an issue please provide steps that we can use to reproduce this ourselves and create a new issue.
