### ISSUE TITLE
npm install error on npm-current-user

### ISSUE THREAD

**Issue by deep42Thought** [npm/cli#3734]
nom install requests me to report this error

Copyright (C) 2009 Microsoft Corporation. All rights reserved.

PS C:\Users\martin\Dropbox\NODE - important\$npm wider\utils_upgrader> npm install npm-current-user
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\martin\AppData\Local\npm-cache\_logs\2021-09-10T07_56_17_772Z-debug.log
PS C:\Users\martin\Dropbox\NODE - important\$npm wider\utils_upgrader>

**Comment by ljharb** [comment]
what version of node and npm are you using? please fill out the issue template.

**Comment by lukekarrys** [comment]
@deep42Thought I wasn't able to reproduce this on the latest version of npm `v7.24.0`. Can you try replicating this problem on the latest version of `npm`? (ie. `npm i -g npm`) If you can, please use our [issue template](https://github.com/npm/cli/issues/new/choose) to reopen the issue with more steps to reproduce it.

**Comment by deep42Thought** [comment]
interesting - because I am no longer able to reproduce the problem either

so I guess it is best to close this now

Thanks for the response anyway

Dr. Martin W Baker
York Development and Research Limited

07986 297498
martinwbaker ***@***.******@***.***
