### ISSUE TITLE
[BUG] <Documentation Missing on Local Paths and Peer Dependencies>

### ISSUE THREAD

**Issue by dillonledoux** [npm/cli#3736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If a package is being referenced using a local path designated in the package.json file, any peer dependencies of the referenced package will not be downloaded and installed.  The local package must first be packed for it to download the packages. 

### Expected Behavior

The behavior of a package needing to be packed before peer dependencies are installed should be in the documentation in [this section](https://github.com/npm/cli/blob/latest/docs/content/configuring-npm/package-json.md#local-paths) or npm should be modified to install peer dependencies from packages using local paths. 

### Steps To Reproduce

1. Using npm 7 and an angular package with a peer dependency
2. Run ng build
3. In another app, reference the above package using a local path in the local dist directory
4. Build the app using ng build
5. You should notice the peer dependency can't be resolved

### Environment

- OS: Windows 10, build 1909
- Node: 16.9.0
- npm: 7.19.1

**Comment by wraithgar** [comment]
This is working as intended.  Linked deps do not have their dependencies installed, you have to install them inside that linked dep as a separate step.

Docs update PR explaining that has been created https://github.com/npm/cli/pull/4575
