### ISSUE TITLE
[BUG] Cannot upgrade from v6 to v7 on windows 10

### ISSUE THREAD

**Issue by dead-claudia** [npm/cli#3740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This may sound like a duplicate to https://github.com/npm/cli/issues/1206, but it's not.

```
> npm install --global npm@7 --force
npm WARN using --force I sure hope you know what you are doing.
npm ERR! code EEXIST
npm ERR! path C:\Program Files\nodejs\npm.cmd
npm ERR! Refusing to delete C:\Program Files\nodejs\npm.cmd: is outside C:\Program Files\nodejs\node_modules\npm and not a link
npm ERR! File exists: C:\Program Files\nodejs\npm.cmd
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.
```

The same issue appears with `...\npx.cmd`, `...\npm`, and `...\npx`. Removing these files manually allows it to succeed.

### Expected Behavior

The ability to upgrade my global npm 6 to npm 7 forcibly.

### Steps To Reproduce

1. Run `npm install --global npm --force`
2. Get the above error

### Environment

- OS: Windows 10
- Node: 14.17.6
- npm: 6.14.15

Note: I know you all don't actively support v6, but this is the version of npm shipped with the latest LTS and came from a fresh [`nvm install 14.17.6`](https://github.com/coreybutler/nvm-windows), so it's a pretty big showstopper. The only real workaround is removing the files mentioned above and invoking `node "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js"` directly, and that's...not exactly meant to be publicly supported.

**Comment by ljharb** [comment]
Why would you need `--force`? i'd expect `npm install -g npm@7` to Just Work.

**Comment by dead-claudia** [comment]
@ljharb It failed even without it, but it failing *with* it is suspicious. I've already successfully worked around it, but it should be easily reproducible with a clean installation.

**Comment by siemhesda** [comment]
Hi @dead-claudia, you were right about support for v6 not being active. But it’s now long overdue - We’re currently on v10 at the time of writing this. Not sure how feasible to do a hot fix for v6 to sort out this issue. The best way to upgrade to v7 from v6 would be to download the installer (or use node version managers). Newer versions of node do not have this bug. I think it’s best to close this issue for now

cc @wraithgar

**Comment by dead-claudia** [comment]
This is a 2-year-old issue and Node 14 isn't supported anymore (and I don't use it), so I'm fine with this being closed.
