### ISSUE TITLE
npm bug[BUG] <title>

### ISSUE THREAD

**Issue by AMMUZZACHU** [npm/cli#3742]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

An error when I start a bot.

### Expected Behavior

I don't know what I do

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...
Npm error 
![Screenshot_2021-09-12-23-19-14-783_com termux](https://user-images.githubusercontent.com/87445200/132997599-41df1619-3883-40ec-9cbe-4c12cb6a0a5b.jpg)

### Environment

- OS: 
- Node: 
- npm: 
Error

**Comment by lukekarrys** [comment]
**Closing:** this error can arise for a number of reasons; Please read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) & refile an issue with as much information as possible if you're able to **consistently reproduce** this error.
