### ISSUE TITLE
[BUG] 7.20.0 `npm view versions` Returns Invalid JSON Given `--json` Argument

### ISSUE THREAD

**Issue by hhanesand** [npm/cli#3744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`npm view` returns a singular string when performing an operation on a package with only one version, even when given `--json`.

### Expected Behavior

`npm view` should always return an array regardless of the number of versions.

### Steps To Reproduce

Only reproducible with packages that only have one version. I've picked `our-second-demo-pac` as an example because the one I noticed it on is in a private registry.

> npm i -g npm@7.20.0
> npm view our-second-demo-pac versions --json
```
"1.0.0"
```

Passing the result of this command to `JSON.parse` returns an error message.

It works as expected on 7.19.1 :

> npm i -g npm@7.19.1
> npm view our-second-demo-pac versions --json
```
[
  "1.0.0"
]
```

### Environment

- OS: macOS 11.4 (20F71)
- Node: v14.17.5
- npm: 7.20.0 & above

**Comment by ljharb** [comment]
`JSON.parse('"1.0.0"')` works fine.

**Comment by hhanesand** [comment]
You're right. I had mistakenly pasted a single quoted version of that which errored and I didn't bother looking at the message.

This still causes a crash in applications that expect this to be an array.

**Comment by hhanesand** [comment]
I can go report this to the tool that was crashing.

**Comment by ljharb** [comment]
JSON isn't always an array or an object.
