### ISSUE TITLE
[BUG] npm link removes other links

### ISSUE THREAD

**Issue by Gopikrishna19** [npm/cli#3745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

#### Linking package1

```shell
$ npm link @myscope/package1 

changed 1 package, and audited 603 packages in 10s
found 0 vulnerabilities
```
```shell
$ ll node_modules/@myscope
total 0
lrwxrwxrwx 1 Gopi 123 32 Sep 13 10:35 package1 -> /d/Projects/Websites/package1/
drwxr-xr-x 1 Gopi 123 0 Sep 10 12:09 package2/
drwxr-xr-x 1 Gopi 123 0 Sep 13 10:35 package3/
```

#### Linking package2

```shell
$ npm link @myscope/package2

changed 2 packages, and audited 603 packages in 10s
found 0 vulnerabilities
```
```shell
$ ll node_modules/@myscope
total 0
drwxr-xr-x 1 Gopi 123 32 Sep 13 10:35 package1/
lrwxrwxrwx 1 Gopi 123 0 Sep 10 12:09 package2 -> /d/Projects/Websites/package2/
drwxr-xr-x 1 Gopi 123 0 Sep 13 10:35 package3/
```

#### Linking package1

```shell
$ npm link @myscope/package1 

changed 1 package, and audited 603 packages in 10s
found 0 vulnerabilities
```
```shell
$ ll node_modules/@myscope
total 0
lrwxrwxrwx 1 Gopi 123 32 Sep 13 10:35 package1 -> /d/Projects/Websites/package1/
drwxr-xr-x 1 Gopi 123 0 Sep 10 12:09 package2/
drwxr-xr-x 1 Gopi 123 0 Sep 13 10:35 package3/
```

#### Linking package2

```shell
$ npm link @myscope/package2

changed 1 package, and audited 603 packages in 10s
found 0 vulnerabilities
```
```shell
$ ll node_modules/@myscope
total 0
drwxr-xr-x 1 Gopi 123 32 Sep 13 10:35 package1 -> /d/Projects/Websites/package1/
lrwxrwxrwx 1 Gopi 123 0 Sep 10 12:09 package2 -> /d/Projects/Websites/package2/
drwxr-xr-x 1 Gopi 123 0 Sep 13 10:35 package3/
```

### Steps To Reproduce

1. Start a project with multiple sibling dependencies
2. Link a sibling package
3. LInk another sibling package
4. The first sibling is no longer linked

### Environment

- OS: Windows 10
- Node: v16.3.0
- npm: 7.15.1

**Comment by Gopikrishna19** [comment]
This works:

```shell
$ npm link @myscope/package1 @myscope/package2
$ ll node_modules/@myscope
total 0
lrwxrwxrwx 1 Gopi 123 32 Sep 13 10:35 package1 -> /d/Projects/Websites/package1/
lrwxrwxrwx 1 Gopi 123 0 Sep 10 12:09 package2 -> /d/Projects/Websites/package2/
drwxr-xr-x 1 Gopi 123 0 Sep 13 10:35 package3/
```

Is the new behaviour intentional? I surely remember multiple links working in previous versions of npm. Although I have only attempted it on a posix env.

**Comment by Gopikrishna19** [comment]
Upgraded node to v16.9.1 with npm v7.21.1 and still not working. I see there was a fix https://github.com/npm/cli/commit/40829ec40c33a6d23f18715e60e3395bdcb0467e made which is available from 7.18. But it is not working on Windows.

Tagging #3399 #2554

**Comment by trusktr** [comment]
This has been an issue for forever. I've reported this before (but probably those are lost in archived repos or forums).

**Comment by barisusakli** [comment]
Just ran into this as well after upgrading to npm 7.x. I used to run a script to link 10+ dependencies like
```
npm link <dep1>
npm link <dep2>
npm link <dep3>
npm link <dep4>
```

@Gopikrishna19 thanks for the suggestion `npm link <dep1> <dep2> ... <depn>` works.

**Comment by wraithgar** [comment]
https://github.com/npm/cli/commit/40829ec40c33a6d23f18715e60e3395bdcb0467e should have fixed this.  What does the error state look like now in windows?

**Comment by Gopikrishna19** [comment]
will test it now @wraithgar

**Comment by Gopikrishna19** [comment]
Its still not working in Windows:
```ps
D:\Projects\test> md app1 ; cd app1 ; npm init -y ; npm link ; cd ..
D:\Projects\test> md app2 ; cd app2 ; npm init -y ; npm link ; cd ..
D:\Projects> md app3 ; cd app3 ; npm init -y

D:\Projects\app3> npm link app1 
D:\Projects\app3> npm link app2

D:\Projects\app3> ls node_modules
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----l         3/17/2022   3:20 PM                app2
-a----         3/17/2022   3:20 PM            366 .package-lock.json
```

Again, as mentioned a combined link works.

```ps
D:\Projects\app3> npm link app1 app2
D:\Projects\app3> ls node_modules
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----l         3/17/2022   3:18 PM                app1
d----l         3/17/2022   3:18 PM                app2
-a----         3/17/2022   3:18 PM            387 .package-lock.json
```

However, something did change. If I link both deps and link one again, it is not unlinking others anymore:
```ps
D:\Projects\app3> npm link app1 app2
D:\Projects\app3> npm link app2
D:\Projects\app3> ls node_modules
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----l         3/17/2022   3:18 PM                app1              # Still available
d----l         3/17/2022   3:18 PM                app2
-a----         3/17/2022   3:18 PM            387 .package-lock.json
```

**Comment by Gopikrishna19** [comment]
Works in mac though:
```sh
~/Developer/npm-test                                                                                                                                                                  
❯ mkdir app1 && cd app1 && npm init -y && npm link && cd ..                                                                                                                                       
❯ mkdir app2 && cd app2 && npm init -y && npm link && cd ..                                                                                                                                                            
❯ mkdir app3 && cd app3 && npm init -y                   

~/Developer/npm-test/app3                                                                                                                                                 
❯ npm link app1                                                                                                                                                          
❯ npm link app2

~/Developer/npm-test/app3                                                                                                                                                     
❯ ll node_modules 
total 8
drwxr-xr-x  5 Gopi  123  160 Mar 17 15:26 .
drwxr-xr-x  4 Gopi  123  128 Mar 17 15:26 ..
-rw-r--r--  1 Gopi  123  403 Mar 17 15:26 .package-lock.json
lrwxr-xr-x  1 Gopi  123   10 Mar 17 15:26 app1 -> ../../app1
lrwxr-xr-x  1 Gopi  123   10 Mar 17 15:26 app2 -> ../../app2

**Comment by Gopikrishna19** [comment]
Versions:
```sh
~/Developer/npm-test/app3
❯ npm --version
8.5.5
❯ node --version
v16.14.1
```
```ps
D:\Projects\app3> npm --version
8.5.4
D:\Projects\app3> node --version
v16.14.1
```
I guess I missed the v8.5.5, released 2 hours ago, on Windows. Your comment about the fix was from yesterday, so I guess v8.5.4 is still valid. Please let me know if you want me to test with 8.5.5 on Windows.

**Comment by wraithgar** [comment]
No, there were no changes in 8.5.5 that would be relevant to this bug.

**Comment by Santoshraj2** [comment]
@Gopikrishna19 can you please retest this in windows and confirm if issue is till there.
I tried in windows machine and its seems to be having both the links when tried linking individually, Please recheck and confirm.

**Comment by aldesgroup** [comment]
Hi ! Having this issue right now (WSL2 / Ubuntu). Figured that I had to `npm link moduleA moduleB` to have them since, since linking `moduleA` unlinks `moduleB`. Or is it the expected behaviour?

**Comment by wuleninja** [comment]
Hi ! Having this issue right now (WSL2 / Ubuntu). Figured that I had to npm link moduleA moduleB to have them since, since linking moduleA unlinks moduleB. Or is it the expected behaviour?

**Comment by Mortimer333** [comment]
> Hi ! Having this issue right now (WSL2 / Ubuntu). Figured that I had to npm link moduleA moduleB to have them since, since linking moduleA unlinks moduleB. Or is it the expected behaviour?

bump, encountered same issue Ubuntu 22, node v20.12.1, npm 10.5.0

**Comment by velialiev** [comment]
Same issue here using MacOS 15.2, node v22.12.0, npm 10.9.0

I'm linking libraries one by one to check what impact my changes have on bundle size, but linking package removes previous links

However linking packages using npm link pkg1 pkg2 pk3 works as expected
