### ISSUE TITLE
[BUG] npm stopped during install meteor

### ISSUE THREAD

**Issue by MahdiForoughi** [npm/cli#3749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to install meteor framework , but npm is unable to complete its response and stopped...
I should close the cmd or use ctrl+c to terminate the process

![Capture](https://user-images.githubusercontent.com/46189743/133166115-28065977-26b5-4c6f-83c6-a0c3a10f3a73.PNG)
This is the final response from npm
Thank you for replying!

### Expected Behavior

I expected the package to install after a few seconds or get some error information

### Steps To Reproduce

`npm install -g meteor`

### Environment

- OS: Windows 10
- Node: 14.16.0
- npm: 7.23.0

**Comment by wraithgar** [comment]
There is not enough info here to reproduce this locally.  Meteor does take quite awhile to install.  These happen in the background which can give the appearance of a hung process. If you run with `--foreground-scripts` you will see the message  `Extracting the tarball, this may take some time` and when testing locally this did take some time.
