### ISSUE TITLE
[BUG] Unexpected deduped dependencies

### ISSUE THREAD

**Issue by aleen42** [npm/cli#3751]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have the following specified `package.json`:

```json
{
  "dependencies": {
    "wpsjs-rpc-sdk": "1.0.27"
  },
  "devDependencies": {
    "wpsjs": "1.4.11"
  }
}
```

`wpsjs` has specified its dependencies with `wpsjs-rpc-sdk@latest` which has been pointed to `1.0.28`, but after installation, npm still dedupe it as `1.0.27`

```
npm ls wpsjs-rpc-sdk

+-- wpsjs-rpc-sdk@1.0.27
`-- wpsjs@1.4.11
  `-- wpsjs-rpc-sdk@1.0.27 deduped
```

### Expected Behavior

It is expected that npm should not dedupe the library since `1.0.27` has not been the latest one, and construct a structure like this after installation:

```
npm ls wpsjs-rpc-sdk

+-- wpsjs-rpc-sdk@1.0.27
`-- wpsjs@1.4.11
  `-- wpsjs-rpc-sdk@1.0.28 (latest)
```

### Steps To Reproduce

With the `package.json` mentioned above, we can reproduce the problem

### Environment

- OS: Windows
- Node: 16.9.1
- npm: 7.21.1

**Comment by ljharb** [comment]
Why is that expected? npm tries to maximally dedupe, always.

**Comment by aleen42** [comment]
@ljharb 1.0.27 has not been the `latest` tag required by `wpsjs`, why is it deduped? I have tested under `6.14.4` and it works well

```
npm ls wpsjs-rpc-sdk

+-- wpsjs@1.4.11
| `-- wpsjs-rpc-sdk@1.0.28
`-- wpsjs-rpc-sdk@1.0.27
```

**Comment by ljharb** [comment]
Ah. You depend on the _exact_ version of `wpsjs-rpc-sdk`, and `wpsjs` depends on "latest" (they shouldn't; this is like "*" and is a horrifically bad idea), so this does seem like a bug.

That said, `wpsjs` needs to be fixed and I'd file an issue there.

**Comment by aleen42** [comment]
Because `wpsjs`'s bad practise on using a hard path with the following snippet:

```js
let systemDemoJs = path.resolve(__dirname, '../../node_modules/wpsjs-rpc-sdk', sdkName)
```

I have to use such a feature to make sure that npm has not deduped and installed a duplicated `wpsjs-rpc-sdk` under `wpsjs`'s node_modules

But in my opinion, npm should not take `latest` as `*` and provided another tag like `any` instead.

**Comment by ljharb** [comment]
`latest` should definitely not imply `*`, and should only imply "whatever `latest` points to right now".

and `wpsjs` desperately needs to fix its bugs of "using a latest tag" and "depending on a specific `node_modules` layout", regardless.

**Comment by aleen42** [comment]
Currently, I use a simple shrinkwrap file to keep the behaviour:

```json
{
  "version": "1.0.1",
  "lockfileVersion": 1,
  "dependencies": {
    "wpsjs": {
      "version": "1.4.11",
      "dependencies": {
        "wpsjs-rpc-sdk": {
          "version": "1.0.28"
        }
      }
    },
    "wpsjs-rpc-sdk": {
      "version": "1.0.27"
    }
  }
}
```

**Comment by aleen42** [comment]
Also, @ljharb is there any IM contact way like telegram or other? I have anything else which I want to communicate with you.

**Comment by ljharb** [comment]
Personally? you can find me on most social networks under this username. If it's about a specific project, please feel free to file an issue there.

**Comment by wraithgar** [comment]
This is working as intended, npm dedupes whenever possible.
