### ISSUE TITLE
[BUG] `publishConfig` should be shown in `npm config ls`

### ISSUE THREAD

**Issue by isaacs** [npm/cli#3771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you have a package.json containing

```json
{
  "publishConfig": {
    "registry": "http://example.com/"
  }
}
```

and then try to run `npm publish`, you'll see it attempting to write to `http://example.com/`.

"Ok, that's weird, let's see what's going on", you think.  So you run `npm config ls` and `npm config get registry` and everything looks right.

?!

### Expected Behavior

`npm config ls` should show the `publishConfig` as a config section, with a note that the values will _only_ be effective when running `npm publish`.

### Steps To Reproduce

1. In this environment...  a project containing `publishConfig` in package.json, which are broken and weird.
2. With this config...  normal defaults and reasonable config values.
3. Run '...'  `npm config ls`
4. See error...  not an error, but you don't see the weird broken stuff, which would help you debug why publish isn't working.

### Environment

- OS: all
- Node: all
- npm: all

**Comment by isaacs** [comment]
Example in the wild: https://github.com/rileygowan/eslint-plugin-no-react-component-snapshots/commit/c2b74a352a6d4bb3e0537b2145601f479eb94e1b#r56664865

**Comment by isaacs** [comment]
Also, we should probably `this.npm.log('verbose', 'publishConfig', pkg.publishConfig)` when we have something there, just so it's in the debug info if the publish breaks.

**Comment by wraithgar** [comment]
This got implemented! By @nlf!


```
; "publishConfig" from /Users/wraithgar/Development/npm/scratch/package.json
; This set of config values will be used at publish-time.

registry = "https://npmjs.org"
```
