### ISSUE TITLE
V7.24.0 install Fail

### ISSUE THREAD

**Issue by pricejordan41** [npm/cli#3772]
When running the command: npm install -g npm@7.24.0 - I am getting the following errors. What and how do I obtain/change the permissions in order to update the rpm? 

![image](https://user-images.githubusercontent.com/83792808/133853955-28035686-9064-4c07-81fe-ce6e937a1909.png)

**Comment by ljharb** [comment]
You’ll need to use sudo, since your npm is installed in a root-owned location.

**Comment by pricejordan41** [comment]
> You’ll need to use sudo, since your npm is installed in a root-owned location.

How would I do this?? I'm sorry I'm not all that familiar with this stuff.

**Comment by ljharb** [comment]
`sudo npm install -g npm@7.24.0`
