### ISSUE TITLE
Can't run NPM RUN BUILD

### ISSUE THREAD

**Issue by erikswed** [npm/cli#3774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i do npm run build it always fails with

`(copy plugin) Error: EBUSY: resource busy or locked, copyfile
`
I created a stackoverflow issue for this at:
https://stackoverflow.com/questions/69227446/how-to-run-the-npm-run-build

I even start Windows 10 in safe mode and run the  -, npm run build, but it fails because the files are locked busy something 

Complete reinstall of NODE on windows 10
I tested to build on different locations to rule out that the folder or file was locked. I turn of MacAfee LiveSafe background scanning virus. I don't have any Drive syncing locking folders 

### Expected Behavior

When running npm run build it should build the project

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- OS: win 10
- Node:  v12.8.1
- npm: 7.23.0

**Comment by erikswed** [comment]
Could be some ssd drive issue because now I also get same busy resource message installing  "npm i windows-build-tools". I have reinstalled Node  environment. I will report here on changes in my progress 
![image](https://user-images.githubusercontent.com/3285249/133977937-8477512a-0bac-444b-87a2-c8d65b3f8c12.png)

**Comment by DanielRuf** [comment]
Try to disable the antivirus (realtime protection) and check if this resolves the problem.

**Comment by erikswed** [comment]
> Try to disable the antivirus (realtime protection) and check if this resolves the problem.

I Have MacAfee LiveSafe protection Realtime scanning and I turn that of but no chnages.
Thanks I can run it maybe every 10-20th time it's like some processes is locking the files but I just have to keep trying and it's work, time consuming doaa
I even start Windows 10 in safe mode and run the -, npm run build, but it fails because the files are locked busy something

**Comment by wraithgar** [comment]
This does appear to be a problem w/ windows itself.  If there is some way to reproduce this on another system please open a ticket w/ steps to reproduce so we can fix it.
