### ISSUE TITLE
[BUG] npm uses per-project config file when installing with the --global flag

### ISSUE THREAD

**Issue by julienp** [npm/cli#3779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When installing with `--global` npm loads the per-project config file, from the --verbose output:
```
npm timing config:load:file:/root/.nvm/versions/node/v16.9.1/lib/node_modules/npm/npmrc Completed in 1ms
npm timing config:load:file:/usr/src/app/www/.npmrc Completed in 1ms
npm timing config:load:file:/root/.npmrc Completed in 1ms
npm timing config:load:file:/root/.nvm/versions/node/v16.9.1/etc/npmrc Completed in 0ms
```

`/usr/src/app/www/.npmrc` is the project .npmrc.

### Expected Behavior

In npm 6 it seemingly does not read the per-project config file. I don't see any `config:load:file` output when running with --verbose, but in my setup there is a different token in the per-user file, and it is successfully using that to install the global package. When using npm 7 it uses the per-project file with a token that does not have access to the package I am trying to install, and fails.

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- OS: Debian 10.10
- Node: 14.17.6, 16.91
- npm: 6.14.15, 7.21.1

**Comment by wraithgar** [comment]
This was fixed in [v8.1.3](https://github.com/npm/cli/releases/tag/v8.1.3)
