### ISSUE TITLE
[BUG] Misleading documentation on package.json:bin

### ISSUE THREAD

**Issue by 0x2b3bfa0** [npm/cli#3788]
# What / Why

Documentation states the following:

> _To use this, supply a `bin` field in your package.json which is a map of command name to local file name. When this package is installed globally, that file will be linked where global bins go so it is available to run by name._ [(quote from the documentation)](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#bin)

Unfortunately, this is not true for Windows, where it doesn't use symbolic links, but rather a custom script generated by the [`cmd-shim`](https://github.com/npm/cmd-shim) package.

## When
* running `npm install`

## Where
* on the [`package.json:bin`](documentation)

#### `main.js`
```javascript
const [, file, ...parameters] = process.argv;
console.log(require('path').basename(file));
```

#### `package.json`
```json
{
  "bin": {
    "one": "main.js",
    "two": "main.js"
  }
  ···
}
```

### Current Behavior

Running `one` will print `main.js` on Windows and `one` on every other platform.

### Expected Behavior

Running `one` should print `one` on every platform.

**Comment by Bruce-Hopkins** [comment]
Is this still an issue? Can I pick this up?

**Comment by monikasharma1234** [comment]
@darcyclarke Hey , I want to contribute to this issue , can you share me the preferable resources which can help me.

**Comment by YashasviChaurasia** [comment]
@darcyclarke I would like to work on this issue.
Thank you

**Comment by axelsomerseth** [comment]
I searched about this issue and I found a useful [article](https://2ality.com/2022/08/installing-nodejs-bin-scripts.html) to understand the context.

I am not asking to work on this issue because I am a macOS user.
