### ISSUE TITLE
error This is an error with npm itself. Please   report this error at:

### ISSUE THREAD

**Issue by juanca0423** [npm/cli#3798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

error Exit handler never called!                 9010 error This is an error with npm itself. Please   report this error at:                                 9011 error <https://github.com/npm/cli/issues>

### Expected Behavior

error Exit handler never called!                 9010 error This is an error with npm itself. Please   report this error at:                                 9011 error <https://github.com/npm/cli/issues>

### Steps To Reproduce

Npx  create-react-app

### Environment

- npm:

**Comment by lukekarrys** [comment]
Can you fill out the Environment section of the issue template? I'm curious what OS/device this occurred on?

**Comment by juanca0423** [comment]
He thought that here is all the data if you need anything else let me know

**Comment by lukekarrys** [comment]
@juanca0423 What device and OS are you running this on?

**Comment by juanca0423** [comment]
OS: Android 11
Device: SM-A115M (a11q)
ROM: RP1A.200720.012.A115MUBU2BUH2
Baseband: msm
Kernel: armv8l Linux 4.9.227-21980971
CPU: Qualcomm Technologies, Inc SDM450
 GPU: Qualcomm Technologies, Inc SDM450
RAM: 1505MiB / 1810MiB

**Comment by lukekarrys** [comment]
**Closing:** We suspect this has to do with a combination of resource constraints within the device/program being used and the large amount of transient dependencies being installed by this command.

We've opened https://github.com/npm/statusboard/issues/395 for us to look deeper into this and track the discussion and fixes around it. You can also read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) for more information on why this issue might be happening currently and ways to debug it.
