### ISSUE TITLE
Create react app error in termux

### ISSUE THREAD

**Issue by es6mekawy** [npm/cli#3801]
Every time I create a new app, this happens, and I don't know the solution.
npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2021-09-27T05_25_33_517Z-debug.log

Aborting installation.
  npm install --save --save-exact --loglevel error react react-dom react-scripts cra-template has failed.

Deleting generated file... node_modules
Deleting generated file... package.json
Deleting myapp/ from /data/data/com.termux/files/home
Done.

**Comment by ljharb** [comment]
i believe termux sets a PREFIX env var, which conflicts with npm, which also respects that env var.

**Comment by es6mekawy** [comment]
> i believe termux sets a PREFIX env var, which conflicts with npm, which also respects that env var.

But I've seen people who've already done it with no errors on YouTube

**Comment by lukekarrys** [comment]
**Closing:** We suspect this has to do with a combination of resource constraints within the device/program being used and the large amount of transient dependencies being installed by this command.

We've opened https://github.com/npm/statusboard/issues/395 for us to look deeper into this and track the discussion and fixes around it. You can also read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) for more information on why this issue might be happening currently and ways to debug it.
