### ISSUE TITLE
[BUG] When install a dependency, it's install script not running.

### ISSUE THREAD

**Issue by jiaqidegege** [npm/cli#3807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

dependency is insalled, but it's lifycycle scripts(like install) not called

### Expected Behavior

npm lifecycle scripts get called

### Steps To Reproduce

- `mkdir x && cd x && npm init -y`
- `npm i @n0b0dy/test-lifecycle-scipts`
I set install scripts to `echo install` for `@n0b0dy/test-lifecycle-scipts`.
If successfully installed, string `install` should be printed to the console
It works in npm@6 but not npm@7

### Environment

- OS: MacOS Catalina 10.15.7
- Node:  v14.17.2
- npm: 7.24.1

**Comment by ljharb** [comment]
Postinstall scripts have their output suppressed in npm 7. Try doing something that you can detect without looking at the output; you'll likely find it’s running in npm 7 too.

**Comment by jiaqidegege** [comment]
> Postinstall scripts have their output suppressed in npm 7. Try doing something that you can detect without looking at the output; you'll likely find it’s running in npm 7 too.

Thanks for your reply. I checked again, it does run.

**Comment by jiaqidegege** [comment]
> Postinstall scripts have their output suppressed in npm 7. Try doing something that you can detect without looking at the output; you'll likely find it’s running in npm 7 too.

Is there some way to allow postinstall scripts to output like before
