### ISSUE TITLE
[BUG] <title>termux installation in npm

### ISSUE THREAD

**Issue by Talhary** [npm/cli#3811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

$ npm install
npm WARN ancient lockfile
npm WARN ancient lockfile The package-lock.json file was created with an old version of npm,
npm WARN ancient lockfile so supplemental metadata must be fetched from the registry.
npm WARN ancient lockfile
npm WARN ancient lockfile This is a one-time fix-up, please be patient...
npm WARN ancient lockfile
npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2021-09-29T06_44_18_617Z-debug.log
$

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

-npm

**Comment by ParadoxInfinite** [comment]
@Talhary could you provide more details?
- Which Operating system are you on? Seems like an android device looking at the directory.
- Which node and npm versions are you running?
- Could you give a sample package.json and package-lock.json files?

**Comment by Talhary** [comment]
I don't know
