### ISSUE TITLE
[BUG] User defined install script is not called, the default <node-gyp rebuild> runned instead

### ISSUE THREAD

**Issue by jiaqidegege** [npm/cli#3812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I run `npm i canvas --foreground-scripts  --registry https://registry.npm.taobao.org/`,  the canvas package's custom install script `node-pre-gyp install --fallback-to-build` is not called,  but running the default `node-gyp rebuild`. 
If I run without the `--registry` param, it just work.

### Expected Behavior

It should run `node-pre-gyp install --fallback-to-build` but not `node-gyp rebuild`.

### Steps To Reproduce

1. `mkdir xx && cd xx && npm init -y`.
2. `npm i canvas --foreground-scripts  --registry https://registry.npm.taobao.org/`
3. The log output indicates that `node-gyp rebuild` get called but not `node-pre-gyp install`

### Environment

- OS: MacOS Catalina 10.15.7
- Node: 14.17.2
- npm: 7.24.1

**Comment by wraithgar** [comment]
This appears to have been fixed.  Running `npm i canvas --foreground-scripts --registry https://registry.npm.taobao.org/` does run node-pre-gyp install

```sh
~/D/n/scratch $ npm i canvas --foreground-scripts --registry https://registry.npm.taobao.org/

> canvas@2.9.0 install
> node-pre-gyp install --fallback-to-build
```
