### ISSUE TITLE
[DOCS] option `foreground-scripts` is not documented in `npm install` documentation

### ISSUE THREAD

**Issue by hasezoey** [npm/cli#3820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I had already mentioned this issue in #3347, which i though was fixed by #3360, but documentation at https://docs.npmjs.com/cli/v7/commands/npm-install still does not mention the option `foreground-scripts`

### Expected Behavior

To have Documentation about `foreground-scripts`

### Steps To Reproduce

open https://docs.npmjs.com/cli/v7/commands/npm-install and search for `foreground-scripts`

### Environment

Online Documentation

**Comment by jiaqidegege** [comment]
It's mentioned here: [https://docs.npmjs.com/cli/v7/using-npm/scripts](url)

**Comment by hasezoey** [comment]
> It's mentioned here: https://docs.npmjs.com/cli/v7/using-npm/scripts

yes it is mentioned there, but from what i know it is a option to `npm install` and so should be mentioned as a option there

---

PS: your link links to something else
