### ISSUE TITLE
Missing npm-session header

### ISSUE THREAD

**Issue by kevingilbert100** [npm/cli#3822]
It looks like `npm-session` is no longer being passed in as a header starting in version 7. I can't find any reason to why this was removed. Should this be added back in?

**Comment by kevingilbert100** [comment]
+1

**Comment by wraithgar** [comment]
This was removed in npm@7 because it was no longer used by the npm registry itself.  Adding it again would probably need to go through the rfc process to decide if it is needed for other purposes.
