### ISSUE TITLE
[BUG] npm outdated should ignore private packages installed globally

### ISSUE THREAD

**Issue by zdm** [npm/cli#3825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`npm outdated --global` shows private packages with the invalid data.
```
Package   Current  Wanted  Latest  Location               Depended by
datasets  2.11.16   0.1.0   0.1.0  node_modules/datasets  global
npm        7.20.2  7.24.1  7.24.1  node_modules/npm       global
```
In the example above `datasets` package is private.
It was installed using `npm i -g` command.
It wasn't published, so has no public version.
I think such packages should be ignored.
Currently it confuses user.

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- OS: 
- Node: 
- npm:

**Comment by ljharb** [comment]
How was it installed if it wasn’t published? If it’s a local folder, you can run `npm link` in it and then it won’t appear as if installed from a registry.

**Comment by zdm** [comment]
Yes, it is a local folder.
I run `npm i -g` from this folder to install it globally.
After this, when I exec `npm ou -g` this package appears in the list 
with the incorrect versions.
In the `package.json` this package marked as `private`.

**Comment by ljharb** [comment]
Try running `npm link` from it instead of `npm install -g`.

**Comment by zdm** [comment]
With `link` results are the same.

**Comment by zdm** [comment]
By the way, if project name contains namespace, eg: `@test/datasets` it works correctly and private project is not shown.

**Comment by ljharb** [comment]
Is that because of the scope, or because that isn’t an existing package while the other is?

**Comment by zdm** [comment]
Packages are not exists in npm registry in the both cases.

This is because of scope added. Scoped packages processed correctly, bun 
un-scoped - not.

**Comment by ljharb** [comment]
https://www.npmjs.com/package/datasets definitely exists in the registry.

**Comment by zdm** [comment]
Oh, shit.
This is my mistake, tired for the last days, brains are not working.
Sorry, that disturbing you.

**Comment by ljharb** [comment]
I still think this is a bug - installing a private package globally shouldn’t confuse npm outdated into thinking it’s necessarily the same one as on the public registry. I just wanted to confirm that that’s the issue - when the private package name is also a different public package.

**Comment by zdm** [comment]
Yes, you are right.
I am definitely need to sleep ))

**Comment by zdm** [comment]
Private packages must be ignored in any case.

**Comment by zdm** [comment]
Is this is still actual?
I need to cleanup my stale issues list.
