### ISSUE TITLE
[BUG] Running `npm.cmd` from a folder path that have special characters like "&" cause npm cannot find "npm.html"

### ISSUE THREAD

**Issue by Trung0246** [npm/cli#3826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Reposted from https://github.com/nodejs/node/issues/40262:

![image](https://user-images.githubusercontent.com/11626920/135395906-fd8cdb38-0252-4246-a26d-41447155c1c6.png)
```
PS C:\Users\WDAGUtilityAccount\Desktop\test & testing\node\bin> .\npm.cmd help npm
npm notice
npm notice New patch version of npm available! 7.24.0 -> 7.24.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.24.1
npm notice Run npm install -g npm@7.24.1 to update!
npm notice
npm ERR! code 1
npm ERR! Command failed: cmd.exe /c start "" file://C:\Users\WDAGUtilityAccount\Desktop\test ^& testing\node\bin\node_modules\npm\docs\output\commands\npm.html
npm ERR! The system cannot find the file file://C:\Users\WDAGUtilityAccount\Desktop\test ^& testing\node\bin\node_modules\npm\docs\output\commands\npm.html.
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\WDAGUtilityAccount\AppData\Local\npm-cache\_logs\2021-09-30T05_55_19_316Z-debug.log
PS C:\Users\WDAGUtilityAccount\Desktop\test & testing\node\bin> cd ../../..
PS C:\Users\WDAGUtilityAccount\Desktop> cd '.\test testing\node\bin\'
PS C:\Users\WDAGUtilityAccount\Desktop\test testing\node\bin> .\npm.cmd help npm
PS C:\Users\WDAGUtilityAccount\Desktop\test testing\node\bin>
```
Log: https://pastebin.com/raw/bwvpD3bX

The folder path have special characters like `&` is the main cause. No idea if other special characters will cause problem.

Maybe relevant: while in folder path with `&`, upon running `.\npm.cmd install -g npm@7.24.1` to update and then running `.\npm.cmd`, I was greeted with this (of course renaming folder to something else without `&` will fix it):

```
PS C:\Users\WDAGUtilityAccount\Desktop\test & testing\node\bin> .\npm.cmd
'testing\node\bin\' is not recognized as an internal or external command,
operable program or batch file.
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\WDAGUtilityAccount\Desktop\test \node_modules\npm\bin\npm-cli.js'
←[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:778:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)←[39m
←[90m    at node:internal/main/run_main_module:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}
```

### Expected Behavior

The command will open `node_modules/npm/docs/output/commands/npm.html`.

Note: renaming `test & testing` folder to `test_testing` or `test testing` should "fix" the bug and everything is back to normal.

Also I have no idea if running other subcommands will cause similar problem.

The folder path have special characters like `&` is the main cause. No idea if other special characters will cause problem.

### Steps To Reproduce

1) Download https://nodejs.org/dist/latest/node-v16.10.0-win-x64.zip
2) Extract to folder such as `C:\Users\WDAGUtilityAccount\Desktop\test & testing\node\bin` (see that `&` in folder path?)
3) Run `nodevars.bat` from command line (after changing working dir to above) (this step probably not needed)
4) Run `npm.cmd help npm`

### Environment

- OS: Microsoft Windows NT 10.0.19043.0 x64
- Node: 16.10.0
- npm: 7.24.0

**Comment by wraithgar** [comment]
Windows command escaping has been updated since this issue was created. Is this still an issue for you?

**Comment by Trung0246** [comment]
![image](https://user-images.githubusercontent.com/11626920/158891883-b447a7c3-c2f9-41f3-99c4-e9d8c9e1738d.png)
Nice it works now
