### ISSUE TITLE
[BUG] npm >= 7.20.0 does not honor proxy environment variables

### ISSUE THREAD

**Issue by simon-kolkmann** [npm/cli#3836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We run `npm install` inside our ci pipelines behind a corporate proxy. 
The proxy is configured by setting the `HTTP_PROXY` and `HTTPS_PROXY` environment variables. 
We did not use `npm config set (https-)proxy <url>`, because the [documentation](https://docs.npmjs.com/cli/v7/using-npm/config#https-proxy) states that the environment variables will be honored. This worked nicely until `7.20.0`.

With `7.20.0` upwards, `npm install` fails with an error like this:

```
npm ERR! code ECONNRESET
npm ERR! syscall read
npm ERR! errno ECONNRESET
npm ERR! network Invalid response body while trying to fetch https://registry.npmjs.org/some-package: read ECONNRESET
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
```

I was able to fix the issue by downgrading to `npm@7.19.1` ~~or by explicitly setting the proxy with `npm config set (https-)proxy <url>`~~.

**EDIT**: `npm config set (https-)proxy <url>` does not seem to work consistently (tested with `7.20.0` and `7.24.2`):

```
$ npm --version
7.20.0
$ npm config set proxy http://some.url:8080
$ npm config set https-proxy http://some.url:8080
$ npm install
added 199 packages, and audited 200 packages in 10s
31 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
$ npm cache clean --force
npm WARN using --force Recommended protections disabled.
$ rm -rf node_modules
$ npm install
npm ERR! code ECONNRESET
npm ERR! syscall read
npm ERR! errno ECONNRESET
npm ERR! network Invalid response body while trying to fetch https://registry.npmjs.org/@babel%2fhelper-validator-identifier: read ECONNRESET
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
```

### Environment

- Tested inside docker image `node:16.9.0-alpine` with different versions of `npm`
- Might be relevant: Our proxy is only reachable by http, so our environment variables look like this:
  - `HTTP_PROXY=http://some.url:8080`
  - `HTTPS_PROXY=http://some.url:8080`
- `strict-ssl` is set to `false`

**Comment by simon-kolkmann** [comment]
After some further testing it seems that this might not only be related to `npm`, but also to the used docker image. `node:16.6.2-alpine` works out of the box, `node:16.7.0-alpine` does not, both have `npm@7.20.3` installed by default.

If I install `npm@7.19.1` inside `node:16.7.0-alpine`, it works again. Strange.

**Comment by pbeyeler** [comment]
Hi @simon-lorenz, have you ever found a solution to this problem (except downgrading)? We're facing the exact same issue.

**Comment by simon-kolkmann** [comment]
I haven't, sorry.

Edit: We just used `node:16.6.2-alpine` for our ci pipelines since I've opened this issue. I tried to reproduce the issue right now, but I can't -  everything seems to work again, even with the previously failing `node:16.7.0-alpine` image. Guess I'll update our pipelines and report back if the error still occurs on our end.

**Comment by danielleroux** [comment]
I have also strange proxy problems after updating npm.

Steps to reproduce:

### Working

1. Use node v14.17.1 (npm v6.14.13)
2. Create a folder and execute `npm init -y`
3. Install cypress in the new folder `npm install cypress --save-dev`

==> Works fine!

### Proxy Error

1. Use node v16.13.1 (npm v8.1.2)
2. Create a folder and execute `npm init -y`
3. Install cypress in the new folder `npm install cypress --save-dev`

==> Proxy Error

**Comment by pbeyeler** [comment]
@simon-lorenz Today, I upgraded to NPM 8.2.0 and the problem disappeared. Maybe this solves the problem for you as well.

**Comment by wraithgar** [comment]
Looks like this was resolved in newer versions of npm
