### ISSUE TITLE
[BUG] Audit wrong result

### ISSUE THREAD

**Issue by tony-tran** [npm/cli#3837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a package with a vulnerability (Axios version 0.21.1) see : https://github.com/advisories/GHSA-cph5-m8f7-6c5x

When I try to use `npm audit` I have :

```
➜ npm list axios          
testaxios@1.0.0 /Users/ttran/Projects/tmp/testAxios
└── axios@0.21.1

➜ npm audit
found 0 vulnerabilities
```

Maybe I forget or misunderstood something ? 
I have this issue on NPM 6.x & 7.x

On a real project, I have 0 vulnerabilities with `npm audit` but in real, i have a lot (for example if I enable github dependabot) ...

### Expected Behavior

Found one vulnerabilty in high level with axios 0.21.1

### Steps To Reproduce

```
npm install axios@0.21.1
npm audit
```

### Environment

OS : Mac OS Catalina
npm: 6.14.10 & 7.24.2

**Comment by ljharb** [comment]
What does `npm config get registry` say?

**Comment by tony-tran** [comment]
```
➜ npm config get registry
https://registry.npmjs.org/
```

**Comment by NilSet** [comment]
As of yesterday morning I had a build which detected a vulnerable package `set-value@2.0.1` pointing me at https://www.npmjs.com/advisories/5267 which is now a 404. Today, I no longer get this package flagged as vulnerable, despite finding the advisory at https://github.com/advisories/GHSA-4jqc-8m5r-9rpr

**Comment by awslabspl** [comment]
> As of yesterday morning I had a build which detected a vulnerable package `set-value@2.0.1` pointing me at https://www.npmjs.com/advisories/5267 which is now a 404. Today, I no longer get this package flagged as vulnerable, despite finding the advisory at [GHSA-4jqc-8m5r-9rpr](https://github.com/advisories/GHSA-4jqc-8m5r-9rpr)

Exactly the same situation here.

**Comment by lukekarrys** [comment]
We've been working on a change in the npm registry to better integrate with the GitHub Advisory Database. We noticed a few problems in a recent deployment with the way some clients construct URLs to advisories. We reverted the changes that caused these errors but that means that advisories are not syncing. We should have a fix deployed soon.

**Comment by awslabspl** [comment]
@lukekarrys 

> fix deployed soon.

How soon? Its pretty urgent IMO..........

**Comment by tony-tran** [comment]
Now, the command caught vulnerabilities for me! Thx
