### ISSUE TITLE
[BUG] test/lib/publish.js fails if not ran from a git repo

### ISSUE THREAD

**Issue by wraithgar** [npm/cli#3842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`https://github.com/nodejs/node/pull/40319` cigtm failed cause of a quirk in the way our tests work. Because the snapshots are inside the cli repo itself, when we normally run them there is a `gitHead`. nodejs tests run the code in a state where there is no `.git` folder to find, so that attribute is missing and the tests fail.

These tests should be robust enough to handle either case, either deleting the attribute itself or hard setting it without the if statement.

### Environment

- Node: 16.11.0 release candidate
- npm: 7.24.2

**Comment by targos** [comment]
It's also possible to configure CITGM to use a git checkout for npm (the feature exists already)

**Comment by wraithgar** [comment]
> It's also possible to configure CITGM to use a git checkout for npm (the feature exists already)

That would get your citgm unblocked but this really should be a test that is robust enough to work in this case.  The publish tests aren't the place where we are even checking if the `gitHead` is set properly when reading a package, they should be discarded imo.

npm8 is the only thing going out this week but I'll get a pr ready and this *should* be remediated by next week's npm release.

**Comment by ruyadorno** [comment]
it looks like this was fixed, thanks @wraithgar 😊
