### ISSUE TITLE
[BUG] optionalDependencies are not installed when a local path is used (file:...)

### ISSUE THREAD

**Issue by ricklamers** [npm/cli#3846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you install a package (A) with local `optionalDependencies` (B, C) the `optionalDependencies` (B, C) are not installed to `node_modules/` in the project that contains the dependency (A).

### Expected Behavior

The `optionalDependencies` should install regardless of whether they are `file:...` specified or refer to remote package.

### Steps To Reproduce

1. Have a local package with `optionalDependencies` (`optionalDependencies` should refer to other local packages using `file:...` reference).
2. Have a consumer package (e.g. empty `npm init`)
3. Add local package to consumer package (`package.json --> { ..., dependencies: {"package": "file:..." } }`)
4. Run `npm install`
5. You don't see the `optionalDependencies` in the `node_modules/` folder of the consumer package.

### Environment

- OS: Ubuntu 20.04
- Node: v14.17.4
- npm: 7.20.6

**Comment by yoyo837** [comment]
npm 8.1.2:

Maybe same here.

![image](https://user-images.githubusercontent.com/6134547/152914749-049f2b72-59a9-4a2a-b373-09baa00d3643.png)

**Comment by yoyo837** [comment]
I solved it by adding
```json
  "optionalDependencies": {
    "fsevents": "~2.3.2"
  },
```

 in `@ydmap/web-tools/package.json`

**Comment by wraithgar** [comment]
This is by design. Dependencies that are included via `file:` are linked into the project, they have to bring their own `node_modules` with them, the dependencies in the linked dep are not hoisted.
