### ISSUE TITLE
[BUG] audit reports withdrawn vulnerability 

### ISSUE THREAD

**Issue by apokryfos** [npm/cli#3852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I get the following message from npm audit`

```
# npm audit report

lodash  *
Severity: critical
Arbitrary code execution in lodash - https://github.com/advisories/GHSA-8p5q-j9m2-g8wr
No fix available
node_modules/lodash

1 critical severity vulnerability

Some issues need review, and may require choosing
a different dependency.
```

### Expected Behavior

The advisory at https://github.com/advisories/GHSA-8p5q-j9m2-g8wr is withdrawn and so I don't think it should be reported 

### Steps To Reproduce

Run

```
npm init
npm install --save lodash
npm audit
```

### Environment

- OS:  Ubuntu 20.04
- Node: 12.14.1
- npm:  7.24.2

**Comment by hnguyen72829** [comment]
Will this change to npm-cli also affect npm Audit's API?

**Comment by lukekarrys** [comment]
**Closing:** this looks to be an issue with the registry which is outside the scope of this repo. For registry support please go to [npmjs.com/support](https://www.npmjs.com/support). If you believe this is a bug with the cli, please provide further clarifying details.
