### ISSUE TITLE
[BUG] Unable to install parcel - Unable to find @parcel/reporter-cli@2.0.0-rc.0

### ISSUE THREAD

**Issue by lasyavanga** [npm/cli#3855]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to install parcel using the following command
```
npm install --save-dev parcel
```

I am seeing the following error
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@parcel%2freporter-cli - Not found
npm ERR! 404 
npm ERR! 404  '@parcel/reporter-cli@2.0.0-rc.0' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/<username>/.npm/_logs/2021-10-07T17_09_24_292Z-debug.log

```

I searched for the failing `@parcel/reporter-cli@2.0.0-rc.0` package in NPM Registry and I found
```
URL: https://www.npmjs.com/login?next=%2Fpackage%2F%40parcel%2Freporter-cli
looks like something unexpected occurred!
diagnostics id: 69a8c1b79b8c309b~6c6b
```

### Expected Behavior

It should install parcel without failing.

I see this working earlier without any issues.

### Steps To Reproduce

```
npm install --save-dev parcel
```

### Environment

- OS: Ubuntu 21.04
- Node: v16.6.1
- npm: 7.24.2

**Comment by Tai-Iro** [comment]
Unfortunately, it seems there's an outage on all the npm services right now. https://status.npmjs.org/
https://twitter.com/npmstatus/status/1446155768068120599

**Comment by lukekarrys** [comment]
This incident looks to be mitigated. Installing that package now works for me.
