### ISSUE TITLE
[BUG] `lts` dist-tag has been deleted

### ISSUE THREAD

**Issue by kirbysayshi** [npm/cli#3859]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`npm install -g npm@lts` fails with:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for npm@lts.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /[REDACTED]/.npm/_logs/2021-10-07T20_52_49_379Z-debug.log
```

### Expected Behavior

`npm install -g npm@lts` succeeds. It appears that with the recent release of npm@8 (an hour ago?) the `lts` dist-tag was either removed or all tags were replaced. This broke at least our internal build, which depended on being able to install `npm@lts` in a Docker container. We have mitigated by using a pinned version for now (probably should have to begin with).

### Steps To Reproduce

1. In any environment
2. With any config
3. Run `npm install -g npm@lts`
4. See failure 
5. Try `npm info npm dist-tags`
4. There is no `lts` tag

### Environment

- OS: Mac 11.6
- Node: 14.16.0
- npm: 7.24.2

**Comment by ljharb** [comment]
npm doesn't have an LTS policy; `lts` and `latest` should be the same thing, conceptually.

**Comment by kirbysayshi** [comment]
Alright, makes sense. I saw the `lts` tag a few months ago, and assumed it was part of a larger policy change to provide an LTS version! Especially since npm 6 -> 7 was a big change (not really viable to mix and match 6 & 7 on the same project, for example). Sorry for that.

I wonder if I'm the only person on the entire internet that was affected by this 😂

**Comment by lukekarrys** [comment]
In case other people land on this, here's our LTS policy: https://github.com/npm/cli/wiki/Support-Policy#long-term-support-lts. We meant to remove the `lts` tag in February but it was not removed until earlier today along with the `8.0.0` release. Sorry for the confusion and breakage that caused today!

**Comment by kirbysayshi** [comment]
I missed the official documentation. Thanks for the explanation @lukekarrys !
