### ISSUE TITLE
[BUG] "npm install -g npm@lts" fails

### ISSUE THREAD

**Issue by bartlomiejzuber** [npm/cli#3864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Our CI build failed because `npm install -g npm@lts` doesn't seem to be valid anymore.

### Expected Behavior

`npm install -g npm@lts` should work as previously i.e. it should update npm to LTS version.

### Steps To Reproduce

1. Run this:
```
npm install -g npm@lts
```
4. See error:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for npm@lts.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

### Environment

- OS: Windows 10
- Node: v14.17.1
- npm: 7.24.2

**Comment by t1m0thyj** [comment]
I believe NPM has deliberately chosen to stop offering an LTS-tagged version and has documented this decision here: https://github.com/npm/cli/wiki/Support-Policy#long-term-support-lts
