### ISSUE TITLE
[BUG] <It Dont Install Because Some Code Was Mistypped>

### ISSUE THREAD

**Issue by PokeyManatee4** [npm/cli#3866]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

error typeerror     at /usr/share/npm/lib/install/deps.js:457:7
error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
error typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
error typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
error typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
error typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)

### Expected Behavior

It To Install Firebase Without Errors

### Steps To Reproduce

None

### Environment

- OS: Codeanywhere Container
- Node: Latest
- npm: Latest

**Comment by ruyadorno** [comment]
**Closing:** please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).
