### ISSUE TITLE
[BUG][Regression] ERESOLVE if peerDependencies of dependencies support later major version

### ISSUE THREAD

**Issue by kevinoid** [npm/cli#3868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With `npm@^7.20.3` or `npm@8.0.0`, when one of the peer dependencies of a dependency includes a later major version than the dependency version (in addition to the same major version), `npm install --strict-peer-deps=true` fails with `ERESOLVE`, as described in issue #2055.``

### Expected Behavior

`npm install` should complete successfully with the latest version declared by the dependency (which also satisfies the peer dependency of the other dependency).

### Steps To Reproduce

Using the same steps as #2055:

With `package.json`:

```json
{
  "name": "project-a",
  "dependencies": {
    "webpack": "^4.41",
    "webpack-dev-server": "^3.9"
  }
}
```

Running `npm install --strict-peer-deps=true` produces:

    npm ERR! code ERESOLVE
    npm ERR! ERESOLVE could not resolve
    npm ERR! 
    npm ERR! While resolving: webpack-dev-server@3.11.2
    npm ERR! Found: webpack@4.46.0
    npm ERR! node_modules/webpack
    npm ERR!   webpack@"^4.41" from the root project
    npm ERR!   peer webpack@"^4.0.0 || ^5.0.0" from webpack-dev-server@3.11.2
    npm ERR!   node_modules/webpack-dev-server
    npm ERR!     webpack-dev-server@"^3.9" from the root project
    npm ERR!   1 more (terser-webpack-plugin)
    npm ERR! 
    npm ERR! Could not resolve dependency:
    npm ERR! webpack-dev-middleware@"^3.7.2" from webpack-dev-server@3.11.2
    npm ERR! node_modules/webpack-dev-server
    npm ERR!   webpack-dev-server@"^3.9" from the root project
    npm ERR! 
    npm ERR! Conflicting peer dependency: webpack@5.58.1
    npm ERR! node_modules/webpack
    npm ERR!   peer webpack@"^4.0.0 || ^5.0.0" from webpack-dev-middleware@3.7.3
    npm ERR!   node_modules/webpack-dev-middleware
    npm ERR!     webpack-dev-middleware@"^3.7.2" from webpack-dev-server@3.11.2
    npm ERR!     node_modules/webpack-dev-server
    npm ERR!       webpack-dev-server@"^3.9" from the root project
    npm ERR! 
    npm ERR! Fix the upstream dependency conflict, or retry
    npm ERR! this command with --no-strict-peer-deps, --force, or --legacy-peer-deps
    npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
    npm ERR! 
    npm ERR! See /home/user/.cache/npm/eresolve-report.txt for a full report.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/user/.cache/npm/_logs/2021-10-09T21_37_39_782Z-debug.log

I would expect it to install `webpack@4.46.0`, since it is the latest version which satisfies the `webpack@^4.41` dependency and it also satisfies the `webpack@"^4.0.0 || ^5.0.0"` peer dependency from `webpack-dev-middleware@3.7.3`.

### Environment

- OS: Debian GNU/Linux testing
- Node: v12.22.5
- npm:  `npm@^7.20.3` or `npm@8.0.0`

I believe I've bisected the regression to 97cb5ec31 which upgraded to `@npmcli/arborist@2.8.0` for #3377.

**Comment by kevinoid** [comment]
Another example:

`package.json`:

```json
{
  "name": "project-a",
  "dependencies": {
    "eslint": "^7.0.0",
    "eslint-plugin-node": "^11.0.0"
  }
}
```

<details>
<summary><code>npm install --strict-peer-deps=true</code></summary>

    npm ERR! code ERESOLVE
    npm ERR! ERESOLVE could not resolve
    npm ERR! 
    npm ERR! While resolving: eslint-plugin-node@11.1.0
    npm ERR! Found: eslint@7.32.0
    npm ERR! node_modules/eslint
    npm ERR!   eslint@"^7.0.0" from the root project
    npm ERR!   peer eslint@">=5.16.0" from eslint-plugin-node@11.1.0
    npm ERR!   node_modules/eslint-plugin-node
    npm ERR!     eslint-plugin-node@"^11.0.0" from the root project
    npm ERR! 
    npm ERR! Could not resolve dependency:
    npm ERR! eslint-plugin-es@"^3.0.0" from eslint-plugin-node@11.1.0
    npm ERR! node_modules/eslint-plugin-node
    npm ERR!   eslint-plugin-node@"^11.0.0" from the root project
    npm ERR! 
    npm ERR! Conflicting peer dependency: eslint@8.0.0
    npm ERR! node_modules/eslint
    npm ERR!   peer eslint@">=4.19.1" from eslint-plugin-es@3.0.1
    npm ERR!   node_modules/eslint-plugin-es
    npm ERR!     eslint-plugin-es@"^3.0.0" from eslint-plugin-node@11.1.0
    npm ERR!     node_modules/eslint-plugin-node
    npm ERR!       eslint-plugin-node@"^11.0.0" from the root project
    npm ERR! 
    npm ERR! Fix the upstream dependency conflict, or retry
    npm ERR! this command with --no-strict-peer-deps, --force, or --legacy-peer-deps
    npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
    npm ERR! 
    npm ERR! See /home/user/.cache/npm/eresolve-report.txt for a full report.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/user/.cache/npm/_logs/2021-10-09T21_57_04_502Z-debug.log

</details>

**Comment by lukekarrys** [comment]
Thanks for the thorough report @kevinoid! This is the same issue as #3881, but manifesting in that `ERESOLVE` error when `--strict-peer-deps` is turned on. The good news is that the fix for that works for this as well. I pulled in https://github.com/npm/arborist/pull/337 and was able to run both your examples successfully now. This fix should go out tomorrow!

```
{
  "dependencies": {
    "eslint": "^7.0.0",
    "eslint-plugin-node": "^11.0.0"
  }
}
```

```
❯ npm i --strict-peer-deps=true
❯ npm ls eslint
3868@1.0.0 /Users/lukekarrys/Desktop/npm-sandbox/3868
├─┬ eslint-plugin-node@11.1.0
│ ├─┬ eslint-plugin-es@3.0.1
│ │ └── eslint@7.32.0 deduped
│ └── eslint@7.32.0 deduped
└── eslint@7.32.0
```

```
{
  "dependencies": {
    "webpack": "^4.41",
    "webpack-dev-server": "^3.9"
  }
}
```

```
❯ npm i --strict-peer-deps=true
❯ npm ls webpack
3868@1.0.0 /Users/lukekarrys/Desktop/npm-sandbox/3868
├─┬ webpack-dev-server@3.11.2
│ ├─┬ webpack-dev-middleware@3.7.3
│ │ └── webpack@4.46.0 deduped
│ └── webpack@4.46.0 deduped
└─┬ webpack@4.46.0
  └─┬ terser-webpack-plugin@1.4.5
    └── webpack@4.46.0 deduped
```

**Comment by kevinoid** [comment]
Interesting!  Thanks for investigating an implementing a fix @lukekarrys!  I'll look forward to it in a future release.
