### ISSUE TITLE
[BUG] npm ci doesn't remove hidden files in node_modules

### ISSUE THREAD

**Issue by kirtixs** [npm/cli#3879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running `npm ci` should remove the folder `node_modules` according to the documentation (https://docs.npmjs.com/cli/v6/commands/npm-ci) but it doesn't remove the folder itself and keeps hidden files.

In https://github.com/npm/cli/blob/latest/lib/ci.js#L16 `fs.readdir` is used to find all files and folders in `node_modules` and deletes them using `rimraf`. `fs.readdir` ignores hidden files and folders when it should just ignore `.` and `..` according to https://nodejs.org/docs/latest-v14.x/api/fs.html#fs_fspromises_readdir_path_options.  I'd argue that this could be a bug or missing documentation in node itself but I can't see a reason why `npm ci` shouldn't just do `rimraf(`${path}`).

### Expected Behavior

Either the documentation should be changed to note that hidden files and folders are kept and `node_modules` itself isn't deleted or hidden files and folders should also be deleted by directly removing `node_modules`.

### Steps To Reproduce

1. create a hidden file in `node_modules` "touch node_modules/.hidden"
2. run `npm ci`
3. run `ls node_modules/.hidden`, the file is still there

### Environment

- OS: CentOs/Mac OS
- Node: 6.14.15/v14.17.1
- npm: 6.14.15/6.14.13

**Comment by ljharb** [comment]
What happens in npm 7 or 8?

**Comment by lukekarrys** [comment]
I've confirmed that this is no longer the case in npm 7 and 8. I recommend updating to npm 8 to get this behavior since we only support (except security fixes) the most recent major release line.
