### ISSUE TITLE
[BUG] NPM Logout Removes Wrong Access Token

### ISSUE THREAD

**Issue by Striar-Yunis** [npm/cli#3888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

NPM Logout removes the wrong token leaving the login token available. Reproduced in v6, v7, and v8.0.0.

### Expected Behavior

NPM login adds an access token to `npm config` user section.
NPM logout removes an access token from `npm config` user section.

### Steps To Reproduce

1. In this environment...
* Go to: https://www.npmjs.com/settings/USER_NAME/tokens
* Make a Read-Only token. Keep it's value.
[
![Screenshot from 2021-10-13 12-44-43](https://user-images.githubusercontent.com/22358192/137179577-a4ad2cf2-45f9-4de5-a189-0a810cfa4a54.png)
](url)
* Make a new folder: mkdir test & cd test
* Run: npm init
* Add .npmrc: echo "//registry.npmjs.org/:_authToken=READ_ONLY_TOKEN"  > .npmrc
* Login: npm login (See second access token created)
![Screenshot from 2021-10-13 12-45-22](https://user-images.githubusercontent.com/22358192/137179646-801d3adf-5d5a-4c81-b763-27b300410839.png)
* Logout: npm logout (See wrong token removed. Readonly token was deleted)
![Screenshot from 2021-10-13 12-46-03](https://user-images.githubusercontent.com/22358192/137179708-d67a75dd-a181-492b-a94f-dd19b33e8a73.png)

### Environment

- OS: Ubuntu
- Node: v14.18.0
- npm: Last version tested was 8.0.0, but could recreate in 6 and 7.

**Comment by wraithgar** [comment]
https://github.com/npm/cli/blob/7a858277171813b37d46a032e49db44c8624f78f/lib/commands/logout.js#L39
