### ISSUE TITLE
[BUG] "npm pkg set" append to array and set array value | zsh shell setopt issue

### ISSUE THREAD

**Issue by RunAge** [npm/cli#3891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
$ npx npm@7.24.2 pkg set workspaces[]="repos/shared"
zsh: no matches found: workspaces[]=repos/shared
```
```
$ npx npm@7.24.2 pkg set workspaces=repos/shared 
npm ERR! newWorkspaces.some is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/r/.npm/_logs/2021-10-14T09_22_20_624Z-debug.log
```
LOG:
```
0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/home/r/.npm/_npx/b278dd9933a248ff/node_modules/.bin/npm',
0 verbose cli   'pkg',
0 verbose cli   'set',
0 verbose cli   'workspaces=repos/shared'
0 verbose cli ]
1 info using npm@7.24.2
2 info using node@v16.11.1
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/home/r/.npm/_npx/b278dd9933a248ff/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 0ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/home/r/Documents/Personal/Kamidere-laboratory/teto/.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/home/r/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/home/r/global_node_modules/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 7ms
19 timing npm:load:configload Completed in 7ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 0ms
22 timing config:load:flatten Completed in 2ms
23 timing npm:load:cleanupLog Completed in 1ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 0ms
26 timing npm:load Completed in 11ms
27 timing config:load:flatten Completed in 0ms
28 timing command:pkg Completed in 2ms
29 verbose stack TypeError: newWorkspaces.some is not a function
29 verbose stack     at hasInvalidWorkspaces (/home/r/.npm/_npx/b278dd9933a248ff/node_modules/npm/node_modules/@npmcli/package-json/lib/update-workspaces.js:9:19)
29 verbose stack     at updateWorkspaces (/home/r/.npm/_npx/b278dd9933a248ff/node_modules/npm/node_modules/@npmcli/package-json/lib/update-workspaces.js:10:32)
29 verbose stack     at PackageJson.update (/home/r/.npm/_npx/b278dd9933a248ff/node_modules/npm/node_modules/@npmcli/package-json/lib/index.js:77:25)
29 verbose stack     at Pkg.set (/home/r/.npm/_npx/b278dd9933a248ff/node_modules/npm/lib/pkg.js:124:13)
30 verbose cwd /home/r/Documents/Personal/Kamidere-laboratory/teto
31 verbose Linux 5.13.0-7614-generic
32 verbose argv "/usr/local/bin/node" "/home/r/.npm/_npx/b278dd9933a248ff/node_modules/.bin/npm" "pkg" "set" "workspaces=repos/shared"
33 verbose node v16.11.1
34 verbose npm  v7.24.2
35 error newWorkspaces.some is not a function
36 verbose exit 1
```

Bug occurs also in npm@8.0.0 

### Expected Behavior

Append/Set value to array

### Steps To Reproduce

1. Use this package.json
```
{
  "name": "@kamidere/teto-repo",
  "version": "1.0.0",
  "description": "Monorepo for Teto",
  "repository": {
    "type": "git",
    "url": "git@gitlab.com:kamidere-laboratory/tetodevteam/backend.git"
  },
  "author": {
    "name": "Kamide.re Laboratory",
    "url": "https://gitlab.com/kamidere-laboratory"
  },
  "contributors": [
    {
      "name": "Robert \"RunAge\" Gajda",
      "url": "https://gitlab.com/RunAge"
    }
  ],
  "license": "MIT",
  "workspaces": [
    "repos/user"
  ]
}
```
2. Create subfolder "repos"
3. Create subfolders inside repos "user", "shared"
4. Create package.json for user workspace
```
{
  "name": "@kamidere/teto-user-module",
  "version": "0.0.0",
  "description": "User module for Teto",
  "main": "./build/index.js",
  "scripts": {
    "test": "-"
  },
  "author": {
    "name": "Kamide.re Laboratory",
    "url": "https://gitlab.com/kamidere-laboratory"
  },
  "contributors": [
    {
      "name": "Robert \"RunAge\" Gajda",
      "url": "https://gitlab.com/RunAge"
    }
  ],
  "license": "MIT",
  "devDependencies": {
    "@types/node": "^16.10.3",
    "typescript": "^4.5.0-beta"
  }
}
```
5. Create package.json for shared
```
{
  "name": "@kamidere/teto-shared",
  "version": "0.0.0",
  "description": "Shared library for Teto",
  "type": "module",
  "main": "./build/index.js",
  "scripts": {
    "test": "-",
    "build": "./node_modules/.bin/tsc",
    "start": "node ."
  },
  "author": {
    "name": "Kamide.re Laboratory",
    "url": "https://gitlab.com/kamidere-laboratory"
  },
  "contributors": [
    {
      "name": "Robert \"RunAge\" Gajda",
      "url": "https://gitlab.com/RunAge"
    }
  ],
  "license": "MIT",
  "devDependencies": {
    "@types/node": "^16.10.3",
    "typescript": "^4.5.0-beta"
  }
}
```
6. In main dir run `npm pkg set workspaces[]=repos/shared`
7. See error: `no matches found: workspaces[]=repos/shared`
8. in main dir run `npm pkg set workspaces=repos/shared`
9. See error: 
```
npm ERR! newWorkspaces.some is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/r/.npm/_logs/2021-10-14T09_22_20_624Z-debug.log
```

### Environment

- OS: Pop!_OS 21.04 x86_6
- Node: v16.11.1
- npm: 7.24.2

**Comment by darcyclarke** [comment]
The first error you shared, when using `npx`, looks a bit suspect / almost as if your shell incorrectly parsed the command/args. Can you try running `npm pkg set workspaces[]="repos/shared"` directly vs. using `npx`? 

Running that locally seemed to work fine for me:

<img width="725" alt="Screen Shot 2021-10-14 at 8 43 15 PM" src="https://user-images.githubusercontent.com/459713/137414562-224ec758-1741-4de2-af74-9e957bd117e2.png">

Notably, the `workspaces` key should always be an array & you should only try to append to it using the array syntax; using `workspaces=foo` will result in the second error you got/shared the log of (since we're expecting `workspaces[]` as the key). 

More generally, we don't actually support setting objects/arrays as values today, only strings (ex. `npm pkg set foo=[]` will generate an entry like `"foo":"[]"` in your `package.json`).

**Comment by RunAge** [comment]
```
# r @ r-pc in ~/Documents/Personal/Kamidere-laboratory/teto on git:master x [10:43:25] 
$ npm -v
7.24.2

# r @ r-pc in ~/Documents/Personal/Kamidere-laboratory/teto on git:master x [10:43:27] 
$ npm pkg set workspaces[]="repos/shared"
zsh: no matches found: workspaces[]=repos/shared
```
![image](https://user-images.githubusercontent.com/11584396/137459199-4b7d077e-93e5-46f1-8136-c41f3fc9cdc3.png)

Using bash
![image](https://user-images.githubusercontent.com/11584396/137459386-c1c4d050-d1aa-4866-b38d-7ec3a7580988.png)

So You are correct zsh somehow wrongly pass arguments :(

**Comment by ljharb** [comment]
You can try running setopt and see what options zsh has set - my experience with nvm tells me that almost all of them break something.

**Comment by RunAge** [comment]
Yeah 
![image](https://user-images.githubusercontent.com/11584396/137516310-707727b6-a4cc-4e3b-b385-f35061f73186.png)
so my moving to `fish` was sooner then I expected :D (everything works fine on fish)

I'm not sure what this options do and how to fix it with zsh, so if any good soul can figure it out please post it bellow for others using zsh :D

**Comment by RunAge** [comment]
@darcyclarke Can you remove labels I will rename it to `"npm pkg set" append to array and set array value | zsh shell config issue` because its not an npm issue but maybe someone else will have this problem and maybe someone will figure out what setopt option casue this.

**Comment by ljharb** [comment]
@RunAge you could binary search relatively quickly. My stock zsh's setopt, for reference, is:
```zsh
combiningchars
interactive
monitor
shinstdin
zle
```

**Comment by RunAge** [comment]
Thanks. Are you using oh-my-zsh? Maybe this rewrited my setopt.

**Comment by ljharb** [comment]
i am not; omz sets a lot of options tho, and they can definitely break things.

**Comment by fsgreco** [comment]
It's 2023 and apparently ZSH still has no fixed this issue. 
I had to do `sh -c "npm pkg set workspaces[]='packages/*'"` to make it work 
(from a terminal with`zsh` and `oh-my-zsh`).
