### ISSUE TITLE
[BUG] login failure 

### ISSUE THREAD

**Issue by veritem** [npm/cli#3898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to log in via the CLI, but I'm getting this weird error.

![image](https://user-images.githubusercontent.com/53856673/137438240-f25c2d4c-6c6b-4b47-9daf-0b6136cfac1f.png)

### Steps To Reproduce

1. Run 'npm login'
2. Enter username and password 
3. Error appears

### Environment

- OS: Ubuntu 20.04
- Node: 16.10.0
- npm: 8.0.0

**Comment by wraithgar** [comment]
Not sure if this is still an issue for you but it does look like an npm registry issue, not a cli issue.  If this still doesn't work with the latest npm cli please contact [support](https://www.npmjs.com/support).
