### ISSUE TITLE
[BUG] `bin`s of sub-dependencies overwrite other `bin`s

### ISSUE THREAD

**Issue by neurolag** [npm/cli#3905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My `node_modules/.bin/tsc` and `node_modules/.bin/tsserver` files point to an incorrect module `@tsd/typescript` even though `@tsd/typescript` is not listed in my dependencies.

Thus I can't use the `typescript`-module's `tsc` and `tsserver`.

### Expected Behavior

`tsc` and `tsserver` should point to the `typescript`-dependency.

### Steps To Reproduce

1. Add `typescript` to your dependencies
2. Verify that `./node_modules/.bin/tsc` points to the `typescript`-module as expected
3. Add `tsd` to your dependencies
4. Notice that `./node_modules/.bin/tsc` now points to the `@tsd/typescript`-module which is a dependency of `tsd`

### Environment

- OS: Windows 11
- Node: v16.9.1
- npm: 8.1.0

**Comment by wraithgar** [comment]
This is going to happen when multiple packages in your tree try to define the same `bin`.  `@tsd/typescript` [does this](https://github.com/SamVerschueren/tsd-typescript/blob/master/package.json#L15), which will conflict with typescript's bin.  Which one ends up in `node_modules/.bin` is also nondeterministic.  The only fix is for one of the two modules to rename their bin entry.
