### ISSUE TITLE
NPM issue

### ISSUE THREAD

**Issue by gyurmey** [npm/cli#3909]
![npm issue](https://user-images.githubusercontent.com/15898245/137769073-aa8121ab-656d-4538-8a00-6d5fa2443b50.png)

**Comment by ljharb** [comment]
Please fill out the issue template, including with what you were doing and what versions of things you're running.

**Comment by gyurmey** [comment]
> Please fill out the issue template, including with what you were doing and what versions of things you're running.

i found a similar bug report in 2019 here https://github.com/npm/cli/issues/417 .. anyway my npm version is 7.5.1 and node is v15.8.0 . i was trying to install a library and it give this error when i try with sudo ^^

**Comment by ljharb** [comment]
7.5.1 is pretty old; try 7 latest, or 8.

**Comment by gyurmey** [comment]
> 7.5.1 is pretty old; try 7 latest, or 8.

Thank you.. it seems the problem with the npm is gone now but the other library have the issue.. anyway, thank you once again.
