### ISSUE TITLE
'npm ci' does not run prepack script for git dependencies.

### ISSUE THREAD

**Issue by darcyclarke** [npm/cli#391]
Original bug ticket: [https://npm.community/t/9764](https://npm.community/t/9764)
      Originally filed: 2019-08-29T15:53:31.638Z

**Comment by Akimyou** [comment]
This issue may be fixed in: [v6.12](https://github.com/npm/cli/releases/tag/v6.12.0)
Please have a try.

#321

**Comment by restjohn** [comment]
This does not seem to be working on 6.13.7.  For what it's worth, pnpm 4.10.0 does not appear to run the prepack script for a git dependency either.

**Comment by kalbert312** [comment]
I'm also facing this issue. I had to resort to running my script via `prepare` but this is overkill and causes some other issues. I'm looking to git ignore my dist files, build them on-demand when used as a git dependency via prepack, and build them and package them for a published version.
