### ISSUE TITLE
[BUG] man im tired of this

### ISSUE THREAD

**Issue by ghost** [npm/cli#3911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

```js
~ $ vim image2.js
~ $ npm install node-html-to-image
npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2021-10-19T05_25_39_045Z-debug.log
```
these are the steps to reproduce this issue

### Environment

- OS: android 10
- Node: 16.0.1(maybe)
- npm: 8.0.0

**Comment by ljharb** [comment]
What is `npm root -g` and `echo $PREFIX`? Termux can sometimes conflict with npm.

**Comment by ghost** [comment]
```js
~ $ npm root -g
/data/data/com.termux/files/usr/lib/node_modules
```

**Comment by ghost** [comment]
```js
~ $ echo $PREFIX
/data/data/com.termux/files/usr
```

**Comment by ljharb** [comment]
I think that's the issue - npm and termux both want to use `PREFIX`, and there's a conflict. Can you try without using termux?

**Comment by ghost** [comment]
termux is the only app i know about, do you suggest me any another terminal app?

**Comment by ljharb** [comment]
i don't know much about android apps; anything that provides a terminal should work.

**Comment by ghost** [comment]
```js
~ $ npm install node-html-to-image
npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2021-10-20T14_50_09_724Z-debug.log
```
-_-

**Comment by lukekarrys** [comment]
**Closing:** We suspect this has to do with a combination of resource constraints within the device/program being used and the large amount of transient dependencies being installed by this command.

We've opened https://github.com/npm/statusboard/issues/395 for us to look deeper into this and track the discussion and fixes around it. You can also read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) for more information on why this issue might be happening currently and ways to debug it.
