### ISSUE TITLE
npm preinstall script doesn't respect project .npmrc

### ISSUE THREAD

**Issue by tommyc38** [npm/cli#3915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I run `npm install` it kicks off the preinstall script in package.json (e.g.`preinstall: npx npm-force-resolutions`) which throws a 401 error.  However, when I run `npx npm-force-resolutions` it works just fine.  I currently have an .npmrc file in my project root but I don't have one in my home folder.  The solution was to copy the project's .npmrc to my home folder.  I am confused though based on npm's documentation and the way it resolves configs.  From what I understand, it is suppose to source the project's .npmrc file before looking in the home folder?  Moroever, if I remove the preinstall script it still installs dependencies from my private registry.  For some reason the preinstall only looks in the home folder for .npmrc?

```
(/project/root/.npmrc)

registry=https://${NPM_REGISTRY_URL}
//${NPM_REGISTRY_URL}:_authToken=${MYGET_REPO_PASSWORD}

```

### Expected Behavior

I would expect npm to look at the .npmrc in the project root when running `npm install` (with a preinstall script in package.json) or `npm run preinstall`.

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- OS: Windows 10
- Node: 12.22.6 (tried 14.x.x and same result)
- npm: 6.14.13 (tried different ones and same result)

I

**Comment by ljharb** [comment]
What happens with npm 7 or 8?

**Comment by fritzy** [comment]
@tommyc38  can you try replicating this problem on the latest version of `npm`? (ie. `npm i -g npm`)

**Comment by tommyc38** [comment]
@fritzy and @ljharb  7.5.6 and 8.1.2 work just fine.

**Comment by fritzy** [comment]
@tommyc38 glad to hear it works in the current release!

**Comment by juharris** [comment]
I tried with npm 8.15.0 and got the error when installing microsoft-cognitiveservices-speech-sdk
```
  npm ERR! code 1
  npm ERR! path C:\a\_work\1\s\services\[REDACTED]\node_modules\microsoft-cognitiveservices-speech-sdk
  npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c C:\Users\CLOUDT~1\AppData\Local\Temp\preinstall-c63e922b.cmd
  npm ERR! npm ERR! code E401
  npm ERR! npm ERR! Unable to authenticate, your authentication token seems to be invalid.
  npm ERR! npm ERR! To correct this please trying logging in again with:
  npm ERR! npm ERR!     npm login
  npm ERR! 
  npm ERR! npm ERR! A complete log of this run can be found in:
  npm ERR! npm ERR!     C:\Users\cloudtest\AppData\Local\npm-cache\_logs\2022-08-20T00_08_05_298Z-debug-0.log
```
