### ISSUE TITLE
npm install reaching timeout at Cloudflare

### ISSUE THREAD

**Issue by brianpunzalan** [npm/cli#3916]
### Current Behavior
Trying to install npm dependencies but have been reaching timeout on 104.16.25.35 which I believe is from Cloudflare.
Executing `curl https://registry.npmjs.com/<package-name>` to test the connection but I am having inconsistent results, success response and response timeouts. Already checked with our network team and no blocking from their side.

### Expected Behavior
Installation should go through.

### Steps to Reproduce
1. `npm install`
2. See error...
```
npm ERR: code ETIMEDOUT
npm ERR: errno ETIMEDOUT
npm ERR: network request to https://registry.npmjs.org/glob-parent failed, reason: connect ETIMEDOUT 104.16.18.35:443
```

### Environment
- OS: **Amazon Linux 2**
- Node: **v14.18.1**
- npm: **6.14.15**

**Comment by darcyclarke** [comment]
Unfortunately this is indeed coming back from the registry/cloudflare which we don't control. They might have been experiencing an outage when you filed this issue (ref. https://status.npmjs.com is always the right place to check for updates &/or our Twitter account https://twitter.com/npmstatus/). Amazon also may be getting rate limited by their IP based on the # of requests they make to the registry (with/without caching, ref. https://blog.npmjs.org/post/187698412060/acceptible-use.html). Hopefully this has resolved itself by now for you though & if not, you'll definitely want to reach out to Amazon &/or our support team (https://www.npmjs.com/support).

**Comment by ricardomomm** [comment]
This is happening again, but for registry.npmjs.org, not sure why
