### ISSUE TITLE
Check Permission[BUG] <title>

### ISSUE THREAD

**Issue by LoneStar1845** [npm/cli#3922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

First time commenting so sorry for noob terms
checkPermissions Missing write access to all folders

### Expected Behavior

Update to 8.1.0

### Steps To Reproduce

1. Ran old npm
2. Prompted to update
3. Run 'npm install -g npm'
4. npm WARN checkPermissions Missing write access to /usr/lib/node_modules and other folders

### Environment

- OS: 
- Node: 
- npm:

**Comment by EvanCarroll** [comment]
It's pretty clear the problem. Your `npm  -g` is installing to `/usr/lib/node_modules` which you do not have permissions to write to. So you probably need to run it with sudo.

    sudo npm install -g npm

**Comment by LoneStar1845** [comment]
Thank you for the help. I ran sudo just fine but then I tried running "sudo npm install -g @cdmnky/nexia-api" and found 2 vulnerabilities. I tried "npm audit fix --force" to fix the problems and got this
npm WARN using --force Recommended protections disabled.
npm ERR! code ENOLOCK
npm ERR! audit This command requires an existing lockfile.
npm ERR! audit Try creating one first with: npm i --package-lock-only
npm ERR! audit Original error: loadVirtual requires existing shrinkwrap file

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2021-10-21T19_25_45_204Z-debug.log

**Comment by ljharb** [comment]
you can't audit fix global packages, because there's no lockfile there.

**Comment by ygoe** [comment]
@ljharb Just to clarify, that means that I can safely ignore security vulnerability warnings by npm if I'm only installing global packages, right? As npm is unable to help me with this anyway. I'm just running this on Windows and see the same error message. I have no project, just global tools.

**Comment by ljharb** [comment]
@ygoe in most cases you can safely ignore security vulnerability warnings always; they're almost entirely false positives. For global packages, it's not about "safely", it's that you have no choice but to ignore them.

**Comment by ygoe** [comment]
Thank you for the explanation. I was confused about a package and later found out that it really wasn't updated anymore but replaced by another (scoped) package, so the security warnings might be expected here.
