### ISSUE TITLE
[Feature] npm workspaces --parallel

### ISSUE THREAD

**Issue by Eomm** [npm/cli#3923]
There are some scripts on a monorepo that can run in parallel to speed up the command execution.

It would be useful to integrate the `--parallel` flag as implemented in `lerna`.

example:

```
npm run lint --parallel --workspaces
```

runs the `echo` script for each project workspace.

The result would be:

- successful if all the commands are completed successfully 
- or fail if once returns an error

**Comment by ljharb** [comment]
(This should be discussed in the rfcs repo instead of here)

There’s a lot of complexity around this, including how to interleave and/or prefix output.

**Comment by EvanCarroll** [comment]
Agreed. But that's a good idea to flesh out @Eomm Perhaps we could close this?

**Comment by Eomm** [comment]
Yes,
I found this issue on that repo: https://github.com/npm/rfcs/issues/190 that fits a bit

I will continue the discussion there

Thanks
