### ISSUE TITLE
gitHead missing in registry manifests for scoped packages

### ISSUE THREAD

**Issue by darcyclarke** [npm/cli#393]
Original bug ticket: [https://npm.community/t/9739](https://npm.community/t/9739)
      Originally filed: 2019-08-28T10:58:14.876Z

**Comment by felixfbecker** [comment]
Quoting @isaacs from the forum thread:

> This isn’t based on whether the package is scoped, but rather whether it’s published from the root of a git repo or not.
> 
> @material-ui/core is published from a subfolder in a git repo 3 so it doesn’t get picked up.
> 
> It’d be nice if read-package-json walked up the tree to find the .git folder, but as of today, it does not, which is why this field sometimes doesn’t show up.

This was filed in https://github.com/npm/read-package-json/issues/66. I created a PR for this a long time ago to fix this in https://github.com/npm/read-package-json/pull/80. It would be amazing if it could be merged 🙏🏻

**Comment by felixfbecker** [comment]
@darcyclarke why close this?

**Comment by darcyclarke** [comment]
Hey @felixfbecker! Sorry for any confusion here. That said, we are only expecting to make security updates to `v6` as per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy) now that [`v7`](https://github.blog/changelog/2021-02-02-npm-7-is-now-generally-available/) is GA

**Comment by darcyclarke** [comment]
If you'd like to make a [net-new issue](https://github.com/npm/cli/issues/new/choose) against the project using our new issue template, it may help actually get visibility to the problem if you're still experiencing this in v7
