### ISSUE TITLE
[BUG] peer dependency conflict false positive with beta version of a package

### ISSUE THREAD

**Issue by soullivaneuh** [npm/cli#3932]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After changing the Storybook dependencies from `^6.3` to `^6.4.0-beta.18`, I got this peer dependency conflict error:

```
npm ERR! While resolving: @test@0.0.0-dev
npm ERR! Found: @storybook/react@6.4.0-beta.19
npm ERR! node_modules/@storybook/react
npm ERR!   dev @storybook/react@"^6.4.0-beta.18" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @storybook/react@">=5.2" from @storybook/preset-create-react-app@3.2.0
npm ERR! node_modules/@storybook/preset-create-react-app
npm ERR!   dev @storybook/preset-create-react-app@"^3.2.0" from the root project
```

Here is how I interpret it: The `@storybook/react@6.4.0-beta.19` is not superior or equal to `5.2` as required by `@storybook/preset-create-react-app`.

This makes no sense to me plus, the same package is OK with `@storybook/react@^6.3`.

### Expected Behavior

No dependency conflict error on that case.

### Steps To Reproduce

Use this `package.json` example file:

```json
{
  "name": "test",
  "version": "0.0.0-dev",
  "dependencies": {
  },
  "peerDependencies": {
    "@fortawesome/fontawesome-svg-core": "^1",
    "@fortawesome/pro-duotone-svg-icons": "^5",
    "@fortawesome/pro-light-svg-icons": "^5",
    "@fortawesome/pro-regular-svg-icons": "^5",
    "@fortawesome/pro-solid-svg-icons": "^5",
    "@fortawesome/react-fontawesome": "^0.1",
    "@material-ui/core": "^4.12",
    "react": "^17",
    "react-dom": "^17",
    "typeface-inter": "^3"
  },
  "devDependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.34",
    "@fortawesome/pro-duotone-svg-icons": "^5.15.2",
    "@fortawesome/pro-light-svg-icons": "^5.15.2",
    "@fortawesome/pro-regular-svg-icons": "^5.15.2",
    "@fortawesome/pro-solid-svg-icons": "^5.15.2",
    "@fortawesome/react-fontawesome": "^0.1.14",
    "@material-ui/core": "^4.12",
    "@rollup/plugin-commonjs": "^17.1.0",
    "@rollup/plugin-node-resolve": "^11.2.0",
    "@rollup/plugin-typescript": "^8.2.0",
    "@storybook/addon-a11y": "^6.4.0-beta.18",
    "@storybook/addon-actions": "^6.4.0-beta.18",
    "@storybook/addon-docs": "^6.4.0-beta.18",
    "@storybook/addon-essentials": "^6.4.0-beta.18",
    "@storybook/addon-links": "^6.4.0-beta.18",
    "@storybook/addon-storyshots": "^6.4.0-beta.18",
    "@storybook/addons": "^6.4.0-beta.18",
    "@storybook/node-logger": "^6.4.0-beta.18",
    "@storybook/preset-create-react-app": "^3.2.0",
    "@storybook/react": "^6.4.0-beta.18",
    "@storybook/theming": "^6.4.0-beta.18",
    "@svgr/rollup": "^5.5.0",
    "@testing-library/dom": "^8.1.0",
    "@testing-library/jest-dom": "^5.11.9",
    "@testing-library/react": "^11.2.5",
    "@testing-library/user-event": "^13.2.1",
    "@types/css-mediaquery": "^0.1.0",
    "@types/jest": "^26.0.21",
    "@types/node": "^12.20.6",
    "@types/react": "^17",
    "@types/react-dom": "^17",
    "css-mediaquery": "^0.1.2",
    "fuse.js": "^3.6.1",
    "postcss": "^8.2.8",
    "react": "^17",
    "react-dom": "^17",
    "react-scripts": "4.0.3",
    "rollup": "^2.42.0",
    "rollup-plugin-peer-deps-external": "^2.2.4",
    "rollup-plugin-postcss": "^4.0.0",
    "rollup-plugin-svg": "^2.0.0",
    "rollup-plugin-url": "^3.0.1",
    "storybook-dark-mode": "^1.0.8",
    "typeface-inter": "^3.15.1",
    "typescript": "^4.2.3"
  },
  "scripts": {
    "build": "npm run build:lib && npm run build:storybook",
    "build:lib": "rm -rf lib && rollup -c",
    "build:storybook": "build-storybook -s public",
    "test:storyshots": "jest -u src/storybook.test.ts",
    "test": "react-scripts test --watchAll=false --coverage",
    "test:watch": "react-scripts test --watchAll",
    "storybook": "start-storybook -p ${PORT:-6100} -s public"
  },
  "files": [
    "lib",
    "src/**/*.ts",
    "src/**/*.tsx",
    "!src/**/*.test.*",
    "!src/**/*.stories.*",
    "!src/setupTests.ts",
    "!src/dev",
    "!src/samples"
  ],
  "source": "src/index.ts",
  "main": "lib/src/index.js",
  "types": "lib/src/index.d.ts",
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ],
    "rules": {
      "import/no-anonymous-default-export": "off"
    }
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "jest": {
    "collectCoverageFrom": [
      "src/**/*.{ts,tsx}",
      "!<rootDir>/**/*.stories.tsx",
      "!<rootDir>/node_modules/",
      "!<rootDir>/src/dev/*",
      "!<rootDir>/src/samples/*",
      "!<rootDir>/src/index.ts",
      "!<rootDir>/src/react-app-env.d.ts"
    ]
  }
}
```

### Environment

- OS: Manjaro
- Node: v16.3.0
- npm: 8.1.1

**Comment by ljharb** [comment]
This is correct; prereleases do not get counted for any range that isn't already a prerelease. Meaning, `>= 5.2` can't ever match a prerelease.

**Comment by shadowspawn** [comment]
To see the semver matching rules applied to the actual versions of a package, you can play around in the semver calculator: https://semver.npmjs.com

**Comment by soullivaneuh** [comment]
@shadowspawn Indeed, the tool you kindly shared to me confirms that `>=5.2` will not match any pre-release of `6.4`.

@ljharb I have to say I am really surprised to see this kind of rule that does not seem to follow any [official rule of semver](https://semver.org).

May you share a link where we can find the official reason of this solution?

Also, this is maybe a security reason, that can be understandable.
However, this leads to blocking ridiculous situations like this one where we cannot test a beta release of a package with ease (note: `--force` is not an option as it will override any kind of conflict, even the real ones).

Installing pre-release is our developer responsibility, and yes, `6.4.0` is greater than `5.2`, no matter what suffix we have on it.

May we at least have a `package.json` option to allow this kind of behavior, per package or globally?

Regards

**Comment by ljharb** [comment]
@soullivaneuh the semver spec does not have ranges whatsoever, as such, "what happens with ranges" is defined by "whatever anyone wants to do". In this case, npm's range semantics - including these - are what's likely to [land in the semver spec](https://github.com/semver/semver/pull/584).

The reason, to me, is conceptual. Prereleases are "pre" for a reason - they're unstable and dangerous and nobody should ever use one by accident.

**Comment by soullivaneuh** [comment]
> the semver spec does not have ranges whatsoever, as such, "what happens with ranges" is defined by "whatever anyone wants to do". In this case, npm's range semantics - including these - are what's likely to land in the semver spec.

This looks indeed not clearly indicated on the current version of semver.

About your pull request link:

1. I didn't find any rule matching the current NPM behavior, which part are you referencing?
2. As you said, this PR is still a draft and will trigger many debates. As far as I know, from the different tools I used (yarn, composer, pip), npm is the only tool I know that applies such a behavior.

> Prereleases are "pre" for a reason - they're unstable and dangerous and nobody should ever use one by accident.

Yes. Still, this should be the developer responsibility to put a unstable package or not.

With the current behavior, we are just stuck. This is why I am talking about a finer control less violent than the `--force` option.

**Comment by ljharb** [comment]
npm's behavior with semver ranges is the defacto standard in the npm ecosystem - anything different is automatically wrong. Outside the npm ecosystem, that would be where the spec PR comes in, which references prereleases in a number of places: https://github.com/semver/semver/pull/584/files#diff-ba798153cb400a6256ef418a77ff13dca623f2d69ad523cb1872a5eecc08642dR114

It _is_ the developer's responsibility - a package that wants to depend on a prerelease must explicitly do so, eg, `>= 5.2 || ^6.4.0-0`.

**Comment by soullivaneuh** [comment]
> a package that wants to depend on a prerelease must explicitly do so, eg, `>= 5.2 || ^6.4.0-0`.

Certainly, even if we disagree of the core concept of semver that looks not final according to the related PR itself.

However we should also have the possibility to override the requirement. By the way, we already have this possibility by using the `--force` option. However, this option will silent **any** conflict rule of my project ecosystem, which is not what we want here.

So I will ask an another manner: How can we take the responsibility to force the installation of **one package** despite of the conflict warning?

**Comment by ljharb** [comment]
You can override npm's compatibility warnings with a variety of methods - `npm install $package@^6.4.0-0 --force`, for example.

**Comment by soullivaneuh** [comment]
Thanks. This might work for a package.
However, the storybook case require multiple requirement of the beta version, many conflicting with another.

A package.json definition of the conflict override may be a good idea, at least to have a clear info of what we override on git diff reviews.

I'll play with `--force` or use something else for now.

Regards
