### ISSUE TITLE
OTP can expire during publish

### ISSUE THREAD

**Issue by bakkot** [npm/cli#3934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On a slow connection with a large npm package, `npm publish` requiring an OTP can fail because the OTP times out during upload.

### Expected Behavior

It should verify the OTP because it was good when it submitted.

One way to do this without reducing security would be to have an API to which the CLI could submit just the OTP and the sha of the tarball to be published, and have the server check the OTP and respond with a signature saying the submitting user has permission to publish that tarball (for the next 24 hours, say). This is very little data and would presumably be fast.

Then the actual upload would include that signature, and it could take as long as it liked.

Also, it _really_ shouldn't do the full upload before it prompts for the OTP and then do the whole upload again. Bandwidth isn't free.

### Steps To Reproduce

Enable the "require OTP to publish" setting for your account.

Then, in a large (in my case, 60 megabyte) package, or with a sufficiently slow connection, run `npm publish`. This sits around for a minutes, presumably trying the upload without an OTP, then prompts for an OTP. Give it one. This sits around for _another_ few minutes, then finally fails with

```
npm ERR! code EOTP
npm ERR! This operation requires a one-time password from your authenticator.
npm ERR! You can provide a one-time password by passing --otp=<code> to the command you ran.
npm ERR! If you already provided a one-time password then it is likely that you either typoed
npm ERR! it, or it timed out. Please try again.
```

I assume this happens because the OTP generated when the upload started expires after a minute or two, and the upload job is taking longer than that (~3 minutes).

Passing `--otp=` on the CLI changes nothing about the above behavior, including the prompt for the OTP - presumably it's trying using the provided OTP, failing, and assuming you just provided the wrong one. (That's also weird - if I pass `--otp=`, I really should never be prompted to enter one. Just fail if it's wrong.)

### Environment

- OS: Mac OS
- Node: v15.14.0
- npm: 7.24.2

**Comment by fritzy** [comment]
**Closing:** this looks to be an issue with the registry which is outside the scope of this repo. For registry support please go to [npmjs.com/support](https://www.npmjs.com/support). If you believe this is a bug with the cli, please provide further clarifying details.
