### ISSUE TITLE
[BUG] dependency sort order has changed slightly

### ISSUE THREAD

**Issue by G-Rath** [npm/cli#3935]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Given the following `package.json`:

```
{
  "name": "spj-te",
  "dependencies": {
    "sort-package-json": "^1.52.0"
  },
  "devDependencies": {
    "@types/koa-bodyparser": "^4.3.3",
    "@types/koa__router": "^8.0.8"
  }
}
```

Running:

```
npm install sort-package-json
```

Gives:

```
{
  "name": "spj-te",
  "dependencies": {
    "sort-package-json": "^1.52.0"
  },
  "devDependencies": {
    "@types/koa__router": "^8.0.8",
    "@types/koa-bodyparser": "^4.3.3"
  }
}
```

### Expected Behavior

I'd expect the `package.json` not to have changed.

This expected sort ordering is what appears to currently be used by:
  * npm v6
  * yarn v1 & v2
  * pnpm v6
  * `sort-package-json`

Obviously this is a cosmetic bug and (afaik) there isn't a defined standard on the order that should be used in the ecosystem, but given it looks like just npm v7/8 is the odd duck I figured I'd open an issue to see if folks would be open to a PR, as it makes for noisy diffs to have packages swap back and forward 😅 

I'm happy to help do the work - ~I suspect based on #1766 it could be a matter of adjusting the code added in [this commit](https://github.com/npm/arborist/commit/cc89a97b4807d2e00cab2dfabd3a5bddeb3c96c3)~ having looked a bit more into this, it looks like this commits function has gone away so would appreciate being pointed in the right direction

### Steps To Reproduce

See Current Behaviour

### Environment

- OS: Ubuntu 18.04
- Node: 16.0.0
- npm: v8 (latest, via `npx`), and v7 (latest, via `npx`)

**Comment by G-Rath** [comment]
Having looked a bit further into this, I'm wondering if this should be reported against `npm/arborist` instead as it seems like that is what's responsible for the ordering.

**Comment by G-Rath** [comment]
Nope actually looks like this belongs `npm/package-json` (which is where that commits code has moved to), and that the issue is the use of `localeCompare` :/

**Comment by fritzy** [comment]
This change was intentional to make sorting idempotent.

**Comment by G-Rath** [comment]
@fritzy fwiw it was pointed out to me that `sort` by itself actually already is idempotent, so not sure the use of `localeCompare` actually adds much vs breaking consistency.

**Comment by G-Rath** [comment]
@fritzy would it be possible to re-open this issue for further discussion? While I know it seems very inconsequential, my role has me maintaining a wide range of projects which use different package managers and tools so this little bit of inconsistency adds unnecessary overhead to the mental thinking I have to do by creating nosier diffs.

Ultimately what's on my mind with this is that `.sort()` is _already_ idempotent, and in fact `localeCompare` could have _more_ overhead ([It has already resulted in one extra dependency being pulled in](https://github.com/npm/package-json/pull/1), which'd otherwise not be needed) - so I don't think there's any actual advantage to npm using `localeCompare` like this, since the array contents are strings.

**Comment by ljharb** [comment]
`.sort` is stable _now_, but i'm not sure which node version that landed in, and it might still not be stable in every version npm supports.

**Comment by G-Rath** [comment]
@ljharb [v12 according to MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility)

![image](https://user-images.githubusercontent.com/3151613/139506324-784189ed-10bc-4fd0-9df9-6a8ab961350e.png)

Which is the minimal version supported by npm v8 now

**Comment by ljharb** [comment]
Which v12 precisely tho?

**Comment by ljharb** [comment]
Fair point, it's in v12.0.0 and npm requires even higher than that.

However, the default sort comparator still might not have the desired behavior.

**Comment by G-Rath** [comment]
@ljharb from what I can tell, v12.0.0 itself via updating V8: https://twitter.com/mathias/status/1120700282336423937

**Comment by G-Rath** [comment]
> However, the default sort comparator still might not have the desired behavior.

That's really my question: what other desired behaviour does `localeCompare` provide in this case? I'm aware of there being gotchas when you're sorting arrays that hold things other than strings (e.g. because Objects can implement `toString()`), but that shouldn't be the case for this particular sort.

And so I'd think if there were other behaviours that `localeCompare` is providing that are desired, that could mean that "everyone else" (like the other packages managers) have a bug because they're not using `localeCompare` for this.

Otherwise if there aren't any, why use it when it's requiring an extra dependency in the tree & increasing the divide between tools in the ecosystem.

**Comment by ljharb** [comment]
I don't think there's any inherent value whatsoever from avoiding a dependency, and yes, anything npm does intentionally is the standard, and anyone else that doesn't do it has a bug.

None of that speaks to whether this is the desired behavior, of course.
