### ISSUE TITLE
[BUG] cli calls `node-gyp rebuild` during `npm install`

### ISSUE THREAD

**Issue by RudeySH** [npm/cli#3937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After upgrading from npm 6 to npm 8.1.1, `npm install` started failing. This happens with npm 7.24.2 as well. I used `--loglevel verbose` and found the following:

```
npm timing command:install Completed in 29728ms
npm verb stack Error: git dep preparation failed
npm verb stack     at ChildProcess.<anonymous> (C:\Users\RudeySH\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
npm verb stack     at ChildProcess.emit (events.js:400:28)
npm verb stack     at maybeClose (internal/child_process.js:1058:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
npm verb cwd E:\Sync\Projects\SteamHunters\SteamHunters\src\SteamHunters.Web.Mvc
npm verb Windows_NT 10.0.19042
npm verb argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\RudeySH\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--loglevel" "verbose"
npm verb node v14.18.1
npm verb npm  v8.1.1
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command C:\Program Files (x86)\nodejs\node.exe C:\Users\RudeySH\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js install --force --cache=C:\Users\RudeySH\AppData\Local\npm-cache --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm verb cli [
npm ERR! npm verb cli   'C:\\Program Files (x86)\\nodejs\\node.exe',
npm ERR! npm verb cli   'C:\\Users\\RudeySH\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
npm ERR! npm verb cli   'install',
npm ERR! npm verb cli   '--force',
npm ERR! npm verb cli   '--cache=C:\\Users\\RudeySH\\AppData\\Local\\npm-cache',
npm ERR! npm verb cli   '--prefer-offline=false',
npm ERR! npm verb cli   '--prefer-online=false',
npm ERR! npm verb cli   '--offline=false',
npm ERR! npm verb cli   '--no-progress',
npm ERR! npm verb cli   '--no-save',
npm ERR! npm verb cli   '--no-audit',
npm ERR! npm verb cli   '--include=dev',
npm ERR! npm verb cli   '--include=peer',
npm ERR! npm verb cli   '--include=optional',
npm ERR! npm verb cli   '--no-package-lock-only',
npm ERR! npm verb cli   '--no-dry-run'
npm ERR! npm verb cli ]
```

It get's more interesting a bit further down in the log:

```
npm ERR! npm timing build:link Completed in 126ms
npm ERR! npm info run iltorb@2.4.3 install node_modules/iltorb node ./scripts/install.js || node-gyp rebuild
npm ERR! npm info run iltorb@2.4.3 install { code: 1, signal: null }
npm ERR! npm timing reify:rollback:createSparse Completed in 1809ms
npm ERR! npm timing reify:rollback:retireShallow Completed in 0ms
npm ERR! npm timing command:install Completed in 13304ms
npm ERR! npm verb stack Error: command failed
npm ERR! npm verb stack     at ChildProcess.<anonymous> (C:\Users\RudeySH\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
npm ERR! npm verb stack     at ChildProcess.emit (events.js:400:28)
npm ERR! npm verb stack     at maybeClose (internal/child_process.js:1058:16)
npm ERR! npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
npm ERR! npm verb pkgid iltorb@2.4.3
npm ERR! npm verb cwd C:\Users\RudeySH\AppData\Local\npm-cache\_cacache\tmp\git-cloneO1YrvZ
npm ERR! npm verb Windows_NT 10.0.19042
npm ERR! npm verb argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\RudeySH\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--force" "--cache=C:\\Users\\RudeySH\\AppData\\Local\\npm-cache" "--prefer-offline=false" "--prefer-online=false" "--offline=false" "--no-progress" "--no-save" "--no-audit" "--include=dev" "--include=peer" "--include=optional" "--no-package-lock-only" "--no-dry-run"
npm ERR! npm verb node v14.18.1
npm ERR! npm verb npm  v8.1.1
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path C:\Users\RudeySH\AppData\Local\npm-cache\_cacache\tmp\git-cloneO1YrvZ\node_modules\iltorb
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node ./scripts/install.js || node-gyp rebuild
```

I'm not sure why the cli is using the deprecated `iltorb` package, but it's readme states the following:
> ### Prerequisites for Building
> The following is required to build from source or when a [pre-compiled binary](https://github.com/nstepien/iltorb/releases) does not exist.
> - Python 2.7
> - GCC 4.8+ (Unix) or [windows-build-tools](https://github.com/felixrieseberg/windows-build-tools) (Windows), see [Node Building tools](https://github.com/nodejs/node-gyp#installation).

I'm guessing a pre-compiled binary doesn't exist, and that is why it's calling `node-gyp rebuild`.

I don't have Python nor `windows-build-tools` nor Visual C/C++ Build Tools installed, and I don't want to. I'm not trying to build native addons for for Node.js, after all.

### Expected Behavior

Npm 7 and later versions should not require developers to install Python, nor should it require developers to install C/C++ development tools, if their project does not involve building native addons for Node.js. Just like npm 6 didn't have this requirement.

### Steps To Reproduce

1. Install npm@8.1.1 on a machine that does not have Python or C/C++ development tools
2. In a new empty folder, run `npm init -y`
3. Install a popular npm package, for example `npm i -D microbundle@0.11.0`
4. Run `npm install`
5. See error...

### Environment

- OS: Windows_NT 10.0.19042
- Node: v14.18.1
- npm: v8.1.1

**Comment by shadowspawn** [comment]
This is an issue with `microbundle` directly or indirectly depending on `iltorb`, rather than with `npm` itself. 

I get an error in the same install step using npm 6.14.15 (on macOS):

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iltorb@2.4.5 install: `node ./scripts/install.js || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iltorb@2.4.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

After a successful install using npm 6 (which works for you), you can run `npm ls iltorb` to see the dependency chain.

**Comment by RudeySH** [comment]
Looks like I oversimplified the steps and failed to show the difference between npm versions.

The following works in (up to and including) npm 7.0.8, but not in npm 7.0.9 or later versions:

```
npm install github:lokesh/quantize
```

This is what the [package.json of lokesh/quantize](https://github.com/lokesh/quantize/blob/master/package.json) contains:
```
    "dependencies": {},
    "devDependencies": {
        "microbundle": "^0.11.0"
    }
 ```

I'm not sure what changed in npm 7.0.9, but it looks like it started resolving dev dependencies for `github:` packages.

**Comment by shadowspawn** [comment]
Possibly related: #2784

**Comment by RudeySH** [comment]
Yes, that is related. I'm closing my issue as a duplicate.
