### ISSUE TITLE
[BUG] npm ls does not include root

### ISSUE THREAD

**Issue by Eomm** [npm/cli#3945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running the `npm ls` command within the [`--include-workspace-root`](https://docs.npmjs.com/cli/v7/commands/npm-ls#include-workspace-root) does not change the output.

The outputs:

 Correct
```
npm ls

npm-ls@1.0.0 /Users/mspigolon/workspace/_experiments/npm-workspaces/npm-ls
├── avvio@8.0.0
└─┬ pkg-a@1.0.0 -> ./pkg-a
  └── fastify@3.22.1
```

Correct
```
npm ls -w pkg-a

npm-ls@1.0.0 /Users/mspigolon/workspace/_experiments/npm-workspaces/npm-ls
└─┬ pkg-a@1.0.0 -> ./pkg-a
  └── fastify@3.22.1
```

Incorrect
```
npm ls -w pkg-a --include-workspace-root

npm-ls@1.0.0 /Users/mspigolon/workspace/_experiments/npm-workspaces/npm-ls
└─┬ pkg-a@1.0.0 -> ./pkg-a
  └── fastify@3.22.1
```

### Expected Behavior

`npm ls -w pkg-a --include-workspace-root` should list the root package.json dependancies

### Steps To Reproduce

```
mkdir npm-ls
cd npm-ls
npm init --yes
npm init -w pkg-a --yes
npm install avvio
npm install fastify -w pkg-a
```

### Environment

- OS: mac 11.6
- Node: node 16.11.1
- npm: 8.1.1

**Comment by darcyclarke** [comment]
Can reproduce this on latest, `npm@8.3.0`

**Comment by fritzy** [comment]
This just got merged for this week's release.
