### ISSUE TITLE
[BUG] install yarn2 workspace project

### ISSUE THREAD

**Issue by busyhe** [npm/cli#3946]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

❯ npm install
npm notice 
npm notice New minor version of npm available! 8.0.0 -> 8.1.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.1.1
npm notice Run npm install -g npm@8.1.1 to update!
npm notice 
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:packages/common

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/busyhe/.npm/_logs/2021-10-27T12_40_51_232Z-debug.log
[Uploading 2021-10-27T12_40_51_232Z-debug.log…]()

### Expected Behavior

I don't know if this is a problem or a normal one. But it’s behaving the same <7.0.0version

### Steps To Reproduce

npm i

### Environment

- OS: Macos
- Node: v14.17.2
- npm: 8.0.0

**Comment by fritzy** [comment]
`yarn 2` workspaces are incompatible with `npm`.
