### ISSUE TITLE
[BUG] `npm ci` doesn't exit when dependencies in lockfile do not match the `package.json`

### ISSUE THREAD

**Issue by koenpunt** [npm/cli#3947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the `package.json` was updated with new dependencies, and the lockfile isn't, `npm ci` successfully installs the dependencies.

### Expected Behavior

According to the documentation `npm ci` should exit when there's a discrepancy between the `package.json` and the lockfile.

> If dependencies in the package lock do not match those in package.json, npm ci will exit with an error, instead of updating the package lock.
> https://docs.npmjs.com/cli/v7/commands/npm-ci

### Steps To Reproduce

1. Create an empty directory
2. Initialize npm; `npm init -f && npm install`
2. Add a dependency to the `package.json`, but don't update the `package-lock.json`;
   ```
   npm install --save --no-package-lock leftpad
   ```
3. Run `npm ci`
4. See: There's no error.

### Environment

- OS: macOS
- Node: 14.16.0
- npm: 8.1.1

**Comment by PiDelport** [comment]
The following check can work around this, in the meantime:

```shell
npm install
git diff --exit-status
```

**Comment by legopin** [comment]
This issue already exists in #2701
Not sure why it wasn't fixed yet

Thanks for the work around, might consider it
