### ISSUE TITLE
NPM cannot install firebase cli

### ISSUE THREAD

**Issue by Nathankenap** [npm/cli#3950]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Npm cannot install firebase cli tools this error blocked me like for a month now

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- OS: 
- Node: 
- npm:

**Comment by fritzy** [comment]
@Nathankenap please fill out the steps to reproduce, the error you're getting, and the environment versions.

**Comment by Nathankenap** [comment]
The error :
npm install firebase-tools
Error:
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

**Comment by fritzy** [comment]
You have not provided environment details. Which OS? Which version of node? Which version of npm?

@Nathankenap  can you try replicating this problem on the latest version of `npm`? (ie. `npm i -g npm`)

**Comment by ljharb** [comment]
or, without installing it, `npx npm@latest install`

**Comment by BinToss** [comment]
I'm unable to reproduce this issue.

### Environment
- OS: Windows 10 Pro 21H2 (Build 19044.1387)
- Node: 17.1.0
- npm: 8.1.4


Verbose CLI output log
[npm.tmp - PowerShell 7.2 (19576).txt](https://github.com/npm/cli/files/7623381/npm.tmp.-.PowerShell.7.2.19576.txt)

----

I was wondering if this issue was linked to one I was experiencing. It seems that is *not* the case.
