### ISSUE TITLE
[BUG] <title>npm publish [folder] uses folder name for tgz not name inpackage.json

### ISSUE THREAD

**Issue by AnthonyElcocks** [npm/cli#3952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I created a minimal project https://bitbucket.org/ajenuance/xyzzy/src/master/
package.json has "name":"@xyzzy/my-module"
With Node v15.0.1 (npm 7.0.3) it generates the tarball using the name in package.json
With Node v15.1.0 (npm 7.0.8) it generates the tarball using the folder name

### Expected Behavior

I expect it to generate the tarball (and publish) using the name specified in package.json

### Steps To Reproduce

see https://bitbucket.org/ajenuance/xyzzy/src/master/
> npm run publish.current

### Environment

Microsoft Windows [Version 10.0.19042.1288]
Node >= v15.0.1
npm >= 7.0.3

**Comment by ljharb** [comment]
Can you try npm 7 latest? That's an outdated version of both node 15 and npm 7.

**Comment by AnthonyElcocks** [comment]
I tired the latest, then binary chopped down through the versions until I found the moment it stopped working

**Comment by AnthonyElcocks** [comment]
so tried 17.0.1, 16.13.0, 15.14.0, 15.8.0, 15.3.0, 15.1.0 and 15.0.1 (iirc)

**Comment by AnthonyElcocks** [comment]
I debugged the code.
publish.js in 7.0.8 switched to using npm-package-arg (assigned to npa) to resolve the folder name, which it does not unless specified with a trailing forward slash, previous npm publish pub worked, now it must be npm publish pub/
