### ISSUE TITLE
[BUG] .gitignore subdirectories and files being included in publish when git properly ignores them - due to negative pattern.

### ISSUE THREAD

**Issue by chriseaton** [npm/cli#3954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In a `.gitignore`, a simple name or path such as the following will ignore that path and anything under it, however, `npm publish` or `npm pack` includes files under that directory anyways. The only way to truly exclude them is to use two patterns.This potentially is a huge security issue as people may be publishing things they would expect to be ignored.

### Example
With the following, git will ignore the directory and anything under it. `npm publish` or `npm pack` however will include any files under it under subdirectories (such as coverage/test/file1.txt).
```
coverage/
````

The only way to get npm publish/pack to truly ignore all the files recursively is to use a glob pattern.
```
coverage/
coverage/**/*
```

### Expected Behavior

The expected behavior is that if something is gitignored, that it is also ignored by npm publish and npm pack.

This gitignore
```
coverage/
```
Should result in that folder and ANYTHING under it not being published.

### Steps To Reproduce

1. Create a `coverage/` folder with subfolders.
2. Add test files to the subfolders.
3. Add `coverage/` to your root gitignore.
4. Run `npm pack`, notice that the files are included, despite being gitignored (and git would ignore). 

Sample project attached.
[sample-project.zip](https://github.com/npm/cli/files/7435973/sample-project.zip)

Notice proper ignoring by git:
![image](https://user-images.githubusercontent.com/5247568/139300474-5f6005bd-4b9e-435d-8e4c-a1a4b9aefc54.png)

However, files being included by npm:
![image](https://user-images.githubusercontent.com/5247568/139300537-24f7666b-f25f-4f0c-982d-ceab91ba6bfd.png)

### Environment

- OS: CentOS 8, 4.18.0-305.19.1.el8_4.x86_64
- Node: v16.13.0
- npm: 8.1.0

**Comment by ljharb** [comment]
Do you have an `.npmignore` file present, or "files" defined in package.json? Either will cause `.gitignore` to be ignored.

**Comment by chriseaton** [comment]
Nope -no .npmignore or files. Take a look at the sample project attached above.

**Comment by chriseaton** [comment]
Well this is wacky... it's no longer having the problem... However, it certainly was doing it (as shown in the screenshots)...
WTF

**Comment by chriseaton** [comment]
Ok this is interesting... If I include a negative glob pattern, but for a totally different path, the files get included... but git still properly excludes them, but npm doesn't.

`.gitignore`
```
coverage/
!**/packages/build/
```

**Comment by robations** [comment]
See also #4069 — could be related.

I also count this as a security issue. There's potential to publish sensitive files by mistake.

**Comment by wraithgar** [comment]
This appears to have been fixed

```sh
~/D/n/s/pack $ find coverage/
coverage/
coverage//sub
coverage//sub/subreport.txt
coverage//report.txt
~/D/n/s/pack $ cat .gitignore
coverage/
~/D/n/s/pack $ npm pack --dry-run

> pack@1.0.0 prepack
> echo prepack script

prepack script
npm notice 
npm notice 📦  pack@1.0.0
npm notice === Tarball Contents === 
npm notice 2.6kB pack-1.0.0.tgz
npm notice 285B  package.json  
npm notice === Tarball Details === 
npm notice name:          pack                                    
npm notice version:       1.0.0                                   
npm notice filename:      pack-1.0.0.tgz                          
npm notice package size:  3.0 kB                                  
npm notice unpacked size: 2.9 kB                                  
npm notice shasum:        52b38d1fc0f732a97e631a0d1823752c7d95c788
npm notice integrity:     sha512-6maZ07yxtqEtR[...]x38nZiv18UtYw==
npm notice total files:   2                                       
npm notice 
pack-1.0.0.tgz
```
