### ISSUE TITLE
[BUG] --lockfile-version is not respected when using shrinkwrap and hidden lockfile

### ISSUE THREAD

**Issue by dominykas** [npm/cli#3962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`$ npm shrinkwrap --lockfile-version=2` produces a v3 lockfile.

`v8.1.1` used to print a warning, but https://github.com/npm/cli/pull/3949 changed that.

`v8.1.2` just produces a v3 lockfile without any warnings.

### Expected Behavior

`lockfile-version` param/config should be respected.

### Steps To Reproduce

0. `$ rm -rf npm-shrinkwrap.json` (if the shrinkwrap exists - it seems to work OK)
1. `$ npm shrinkwrap --lockfile-version=2`
2. `$ cat npm-shrinkwrap.json | jq .lockfileVersion`

Actual: 3
Expected: 2

### Environment

- OS: macOS 11.6
- Node: 14.18.1
- npm: 8.1.2

**Comment by dominykas** [comment]
(removed - this didn't actually work as I described it)

**Comment by lukekarrys** [comment]
@dominykas I can't reproduce this. Here's what I'm seeing:

```sh
❯ cat package.json
{
  "name": "3962",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "volta": {
    "node": "14.18.1",
    "npm": "8.1.2"
  }
}

❯ npm --version
node 8.1.2

❯ node --version
v14.18.1

❯ ls -lha
total 4.0K
drwxr-xr-x  3 lukekarrys staff   96 Oct 29 11:16 .
drwxr-xr-x 45 lukekarrys staff 1.5K Oct 29 11:13 ..
-rw-r--r--  1 lukekarrys staff  278 Oct 29 11:13 package.json

❯ npm shrinkwrap --lockfile-version=2
npm notice created a lockfile as npm-shrinkwrap.json

❯ cat npm-shrinkwrap.json| json .lockfileVersion
2

❯ ls -lha
total 8.0K
drwxr-xr-x  4 lukekarrys staff  128 Oct 29 11:14 .
drwxr-xr-x 45 lukekarrys staff 1.5K Oct 29 11:13 ..
-rw-r--r--  1 lukekarrys staff  195 Oct 29 11:14 npm-shrinkwrap.json
-rw-r--r--  1 lukekarrys staff  278 Oct 29 11:13 package.json
```

**Comment by ljharb** [comment]
@lukekarrys off topic, but what is `json`? Typically `jq` is what’s used there; I’ve never seen that one before.

**Comment by lukekarrys** [comment]
> what is json

It's this package from the registry: https://www.npmjs.com/package/json. It does less than `jq` but I tend to use it for simple `npm` examples since it's easier to install.

**Comment by ljharb** [comment]
Gotcha; that seems unwise since most people already have jq available and know what it is :-) (that package is not highly used) maybe if the examples used npx it’d be clearer?

**Comment by lukekarrys** [comment]
> maybe if the examples used npx it’d be clearer?

I agree that it should be made clearer and thanks for the reminder since this already come up in our docs: https://github.com/npm/documentation/issues/45

I'm still leaning towards `npx json` over `jq` since I want to have as few prerequisites as possible. But we can discuss more over there :)

**Comment by dominykas** [comment]
Are you sure you had no lockfile to start with?

**Comment by lukekarrys** [comment]
> Are you sure you had no lockfile to start with?

Yes, that's why I showed the output from the initial `ls -lha` to confirm that. Can you check your .npmrc files? `npm config get lockfile-version` should show if you have that set somewhere.

**Comment by dominykas** [comment]
Oh, yeah, sorry, I missed the `ls`.

I experimented a little more. I was able to see the behavior you're seeing on an empty folder, however when I ran `npm i` before the `npm shrinkwrap`, I got the version 3.

~~I'm not 100% sure I was able to repro that consistently, so I'll try a little more.~~ Upd: able to repro consistently, I think: 

```
✔ ~/devel/experiments/shrinkwrap 
10:27 $ npm --version
8.1.2

✔ ~/devel/experiments/shrinkwrap 
10:27 $ node --version
v14.18.1

✔ ~/devel/experiments/shrinkwrap 
10:27 $ npm config get lockfile-version
null

✔ ~/devel/experiments/shrinkwrap 
10:27 $ ls -al
total 8
drwxr-xr-x   3 dominykas  staff   96 31 Oct 10:27 .
drwxr-xr-x  10 dominykas  staff  320 31 Oct 10:24 ..
-rw-r--r--   1 dominykas  staff  237 31 Oct 10:27 package.json

✔ ~/devel/experiments/shrinkwrap 
10:27 $ cat package.json 
{
  "name": "3962",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "private": true
}

✔ ~/devel/experiments/shrinkwrap 
10:27 $ npm shrinkwrap --lockfile-version=2
npm notice created a lockfile as npm-shrinkwrap.json

✔ ~/devel/experiments/shrinkwrap 
10:27 $ cat npm-shrinkwrap.json | jq .lockfileVersion
2

✔ ~/devel/experiments/shrinkwrap 
10:28 $ rm npm-shrinkwrap.json 

✔ ~/devel/experiments/shrinkwrap 
10:28 $ npm i lodash

added 1 package, and audited 2 packages in 884ms

found 0 vulnerabilities

✔ ~/devel/experiments/shrinkwrap [0] 
10:28 $ npm shrinkwrap --lockfile-version=2
npm notice created a lockfile as npm-shrinkwrap.json

✔ ~/devel/experiments/shrinkwrap [0] 
10:28 $ cat npm-shrinkwrap.json | jq .lockfileVersion
3

✔ ~/devel/experiments/shrinkwrap [0] 
10:28 $ cat node_modules/.package-lock.json | jq .lockfileVersion
2
```

(that last one I find a bit interesting)

**Comment by lukekarrys** [comment]
Do you have `package-lock=false` set anywhere? I can only replicate your results if I do `npm i lodash --package=lock=false`. I think this is still a bug, but I'm trying to nail down the exact scenario. 

Here's my full results (without `package-lock=false`):

```sh
❯ ls -al
total 4
drwxr-xr-x  3 lukekarrys staff   96 Nov  1 13:04 .
drwxr-xr-x 45 lukekarrys staff 1440 Oct 29 11:13 ..
-rw-r--r--  1 lukekarrys staff  218 Nov  1 13:04 package.json

❯ cat package.json
{
  "name": "3962",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}

❯ npm i lodash

added 1 package, and audited 2 packages in 1s

found 0 vulnerabilities

❯ npm shrinkwrap --lockfile-version=2
npm notice package-lock.json has been renamed to npm-shrinkwrap.json

❯ cat npm-shrinkwrap.json | npx json .lockfileVersion
2

❯ cat node_modules/.package-lock.json | npx json .lockfileVersion
2
```

And if I do `--package-lock=false`:

```sh
❯ npm i lodash --package-lock=false

added 1 package, and audited 2 packages in 1s

found 0 vulnerabilities

❯ npm shrinkwrap --lockfile-version=2
npm notice created a lockfile as npm-shrinkwrap.json

❯ cat npm-shrinkwrap.json | npx json .lockfileVersion
3

❯ cat node_modules/.package-lock.json | npx json .lockfileVersion
2
```

**Comment by dominykas** [comment]
Yes, I do have it set globally.

**Comment by lukekarrys** [comment]
Thanks! I updated the issue title to more accurately reflect what's happening and can confirm this is a bug that we should fix.

**Comment by lukekarrys** [comment]
I also found that when update a shrinkwrap file, we sometimes show a message with the incorrect lockfile version, even if the file did get updated correctly.

```sh
❯ ls -lha
total 12K
drwxr-xr-x  5 lukekarrys staff  160 Nov  2 07:47 .
drwxr-xr-x 46 lukekarrys staff 1.5K Nov  2 01:37 ..
-rw-r--r--  1 lukekarrys staff  648 Nov  2 07:47 package-lock.json
-rw-r--r--  1 lukekarrys staff  266 Nov  2 07:45 package.json

❯ cat package-lock.json | npx json .lockfileVersion
2

❯ npm shrinkwrap --lockfile-version=3
npm notice package-lock.json has been renamed to npm-shrinkwrap.json

❯ npm shrinkwrap --lockfile-version=3
npm notice npm-shrinkwrap.json updated to version 2

❯ cat npm-shrinkwrap.json | npx json .lockfileVersion
3
```

**Comment by dominykas** [comment]
🙇
