### ISSUE TITLE
I got this log when I run (npm install -g typewritten) 

### ISSUE THREAD

**Issue by iceking-1912** [npm/cli#3965]
**Log-**

1 info using npm@8.1.0
2 info using node@v17.0.1
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 7ms
5 timing config:load:file:/data/data/com.termux/files/usr/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 7ms
8 timing config:load:env Completed in 2ms
9 timing config:load:project Completed in 6ms
10 timing config:load:file:/data/data/com.termux/files/home/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/data/data/com.termux/files/usr/etc/npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:validate Completed in 1ms
15 timing config:load:credentials Completed in 4ms
16 timing config:load:setEnvs Completed in 4ms
17 timing config:load Completed in 37ms
18 timing npm:load:configload Completed in 37ms
19 timing npm:load:setTitle Completed in 1ms
20 timing npm:load:setupLog Completed in 2ms
21 timing config:load:flatten Completed in 12ms
22 timing npm:load:cleanupLog Completed in 8ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 1ms
25 timing npm:load Completed in 68ms
26 timing arborist:ctor Completed in 4ms
27 timing idealTree:init Completed in 36ms
28 timing idealTree:userRequests Completed in 11ms
29 silly idealTree buildDeps
30 silly fetch manifest typewritten@*
31 http fetch GET 200 https://registry.npmjs.org/typewritten 85ms (cache hit)
32 silly placeDep ROOT typewritten@1.4.4 OK for:  want: *
33 timing idealTree:#root Completed in 127ms
34 timing idealTree:node_modules/typewritten Completed in 0ms
35 timing idealTree:buildDeps Completed in 132ms
36 timing idealTree:fixDepFlags Completed in 2ms
37 timing idealTree Completed in 187ms
38 timing reify:loadTrees Completed in 205ms
39 timing reify:diffTrees Completed in 4ms
40 silly reify mark retired [ '/data/data/com.termux/files/usr/lib/node_modules/typewritten' ]
41 silly reify moves {
41 silly reify   '/data/data/com.termux/files/usr/lib/node_modules/typewritten': '/data/data/com.termux/files/usr/lib/node_modules/.typewritten-utN05GZl'
41 silly reify }
42 timing reify:retireShallow Completed in 9ms
43 timing reify:createSparse Completed in 7ms
44 timing reify:loadBundles Completed in 0ms
45 silly audit bulk request { typewritten: [ '1.4.4' ] }
46 timing reifyNode:node_modules/typewritten Completed in 174ms
47 timing reify:unpack Completed in 175ms
48 timing reify:unretire Completed in 1ms
49 timing build:queue Completed in 4ms
50 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 866ms
51 timing auditReport:getReport Completed in 870ms
52 silly audit report {}
53 timing auditReport:init Completed in 0ms
54 timing reify:audit Completed in 874ms
55 timing npm Completed in 2611ms
56 verbose unfinished npm timer command:install 1635667192936
57 verbose unfinished npm timer reify 1635667192946
58 verbose unfinished npm timer reify:build 1635667193430
59 verbose unfinished npm timer build 1635667193431
60 verbose unfinished npm timer build:deps 1635667193431
61 verbose unfinished npm timer build:run:postinstall 1635667193437
62 info ok
63 error Exit handler never called!
64 error This is an error with npm itself. Please report this error at:
65 error <https://github.com/npm/cli/issues>

**Comment by ljharb** [comment]
Try not using termux, does the same problem occur?

**Comment by iceking-1912** [comment]
Ok 
Thank U
