### ISSUE TITLE
[BUG] root package.json script not utilising workspace argument

### ISSUE THREAD

**Issue by matt-way** [npm/cli#3967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I run `npm run build --workspace=project` the project workspace is built as expected.

If I however put a script in the root package.json: `"buildproject": "npm run build --workspace=project"` and then run `npm run buildproject` it fails (missing script: build).

### Expected Behavior

Running the script inside the package.json should do the same thing as running the script from the command line.

### Steps To Reproduce

1. In the workspace root, create a package.json script that uses the --workspace flag
2. Attempt to run that script

### Environment

- OS: Windows
- Node: 16.13.0
- npm: 8.1.0

**Comment by wraithgar** [comment]
This appears to have been fixed.

```sh
~/D/n/s/ws $ npm pkg set scripts.build='echo "building"' -w workspace-b
{}
~/D/n/s/ws $ npm pkg set scripts.buildproject='npm run build --workspace=workspace-b'
~/D/n/s/ws $ npm run buildproject

> ws@1.0.0 buildproject
> npm run build --workspace=workspace-b


> workspace-b@1.0.0 build
> echo "building"

building
```
