### ISSUE TITLE
Allow empty package.json when installing new packages

### ISSUE THREAD

**Issue by aminnairi** [npm/cli#3968]
When creating a new Node project, if one creates an empty `package.json` file with the following command for instance on UNIX:

```console
$ touch package.json
```

And run the following command:

```console
$ npm install eslint
```

There is an error that is raised by the `npm` CLI with a `EJSONPARSE` error.

In my opinion, there should be a check before that, and if the file is empty, then it can be used as if there was no `package.json` file, meaining it can be overriden without any problem.

**Comment by ljharb** [comment]
Given that `npm init` exists, how likely is an empty package.json file to be intentional?

**Comment by aminnairi** [comment]
Does it has to be intentional for it to be accounted by the NPM CLI?

From my point of view, it seems like this could be a simple file existence and/or emptiness check with a friendly error report instead of the `EJSONPARSE` generic error. Maybe I'm missing something that would make this feature much more complicated to implement into the CLI?

**Comment by ljharb** [comment]
I agree it seems simple - but if it's more likely to mask a bug, versus being a convenience for someone who's done this intentionally, then it seems like it'd be better to keep the current behavior.

**Comment by aminnairi** [comment]
Understandable, thanks for your answer.
