### ISSUE TITLE
[BUG] npm is installing global no matter what. (ALL VERSIONS)

### ISSUE THREAD

**Issue by Ccode-lang** [npm/cli#3969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Npm (no matter what version I use) will not install it's packages locally in the node_modules folder.  It only installs globally.

### Expected Behavior

`npm install prompt-sync@4.2.0` to not install globally.

### Steps To Reproduce

1. Run `npm install prompt-sync@4.2.0` 

### Environment

- OS: Debian
- Node: 14.1.0
- npm: tried like ten different versions

**Comment by ljharb** [comment]
Do you have `global=true` in `~/.npmrc` or another npmrc file, or the `NPM_CONFIG_GLOBAL` env var set?

**Comment by Ccode-lang** [comment]
I never set that but I will check now

**Comment by Ccode-lang** [comment]
where are the other npmrc files? ~/.npmrc does not exist.

**Comment by ljharb** [comment]
In the directory you're running npm in, and there's a few others - what does `npm config get global` say?

**Comment by Ccode-lang** [comment]
false

**Comment by Ccode-lang** [comment]
Oh, I forgot to say I am using nvm.  Would that cause this problem?

**Comment by Ccode-lang** [comment]
found my config it's at `~/.config/nvm/versions/node/v14.1.0/etc/npmrc`

**Comment by Ccode-lang** [comment]
everything is default value

**Comment by Ccode-lang** [comment]
I have also tried reinstalling node and npm.

**Comment by ljharb** [comment]
Using nvm shouldn't affect it; whatever `npm root -g` is, that's where global installs should go.

Do you have a `$HOME/package.json` and `$HOME/node_modules`? if so, remove both of those :-)

**Comment by Ccode-lang** [comment]
that did it.

**Comment by Ccode-lang** [comment]
thanks!
