### ISSUE TITLE
[BUG] Error when `npm i` with `arcon`

### ISSUE THREAD

**Issue by PadowYT2** [npm/cli#3970]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With `arcon` located in `package.json` and running `npm i` or trying install it, gives an error
```root@padow:/var/www/cdn-padow# npm i
npm ERR! code EPERM
npm ERR! syscall symlink
npm ERR! path ../acorn/bin/acorn
npm ERR! dest /var/www/cdn-padow/node_modules/.bin/acorn
npm ERR! errno -1
npm ERR! Error: EPERM: operation not permitted, symlink '../acorn/bin/acorn' -> '/var/www/cdn-padow/node_modules/.bin/acorn'
npm ERR!  [Error: EPERM: operation not permitted, symlink '../acorn/bin/acorn' -> '/var/www/cdn-padow/node_modules/.bin/acorn'] {
npm ERR!   errno: -1,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../acorn/bin/acorn',
npm ERR!   dest: '/var/www/cdn-padow/node_modules/.bin/acorn'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.
```

### Expected Behavior

It should install/build normal

### Steps To Reproduce

1. Make a `package.json`
2. Try installing `arcon`
3. Get error

### Environment

- OS: Ubuntu 20.04
- Node: 16.13.0
- npm: 8.1.0

**Comment by PadowYT2** [comment]
Can it happen because the folder is mounted to an another disk?

**Comment by wraithgar** [comment]
You are correct, you can't create symlinks across disks.  There isn't much npm can do about this.

**Comment by jadeye** [comment]
Had the same issue installing `node_modules` to a USB drive. Using [therocco's answer](https://github.com/MicrosoftDocs/WSL/issues/26#issuecomment-206991754) did the job for me.
