### ISSUE TITLE
[feature request] auto delete expired letsencrypt ssl certificates

### ISSUE THREAD

**Issue by Halfeez92** [npm/cli#3974]
Can you put a feature where the npm can auto delete expired letsencrypt ssl certificates? I need this because I am using task scheduler to copy certificates from npm to other services that using the same domain name.

**Comment by darcyclarke** [comment]
Sorry, this is out of scope for the CLI at the moment. Potentially there's room for a third-party package/tool to exist that handles this for you though (potentially one already exists).
