### ISSUE TITLE
[BUG] Deps are not resolving correctly or as expected

### ISSUE THREAD

**Issue by kumarrishav** [npm/cli#3983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="832" alt="Screen_Shot_2021-11-03_at_11_19_43" src="https://user-images.githubusercontent.com/4078325/140101483-12978d50-b5c5-4864-a4ed-3fc74643f281.png">

- babel-eslint
<img width="325" alt="Screen Shot 2021-11-03 at 11 40 25" src="https://user-images.githubusercontent.com/4078325/140104042-5db3185c-f482-42e8-b381-0d8d07774030.png">

Do we know why babel-eslint v6 wasn't installed along with existing v5? npm ls shows installed version as invalid.

Can someone help understand how did resolution happen and what does ELSPROBLEMS means

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- OS: Macos
- Node: 12.20.0
- npm: 7.24.2

**Comment by ljharb** [comment]
babel-eslint is part of Babel 6; for Babel 7 you want `@babel/eslint-parser`.

**Comment by kumarrishav** [comment]
Thanks for your comment. But how is it related to dependency installation/resolution? 
if babel-eslint mentioned eslint as peerdeps, shouldn't it get installed in npm7/8?

**Comment by ljharb** [comment]
@kumarrishav no, because in this case there's an incompatibility. The output implies some things are depending on eslint 5, and some on eslint 6.

Either way, you absolutely should be explicitly declaring a top-level dev dep on the eslint version you're using. Start with that.

**Comment by kumarrishav** [comment]
so, to peerdeps to be installed, there shouldn't be any incompatibility or conflicting peer deps. is it what you are saying? i.e all peer deps on a package, should be able to resolve to one version. 

My understanding was that in npm 7/8 , if peer dep is not able to resolve to the top one. then it will get installed inside the node_modules (nested) of the package which has peer dep.

and in npm 6, there will be no installation in such case and just the warning. 


Thank you for your patience.

**Comment by kumarrishav** [comment]
one of the feature of npm7 is, 
`PeerDependencies installed automatically` - can you clarify what does that means then? It will be helpful

i think if it's only about compatible version getting installed in peer deps , then npm 6 also had the same behavior

**Comment by ljharb** [comment]
That npm 7+ auto-installs peer deps _when it can_ doesn't change that a peer dep is a hoisted version requirement - your dep graph is invalid if peer deps can't be resolved.

Your current dep graph seems invalid from the error output provided.

**Comment by kumarrishav** [comment]
closing the issue. thanks for clarification
