### ISSUE TITLE
[BUG] npm global install does not create scripts for bin entry in package.json

### ISSUE THREAD

**Issue by Ezekiel-DA** [npm/cli#3984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After upgrading from Node 14 to Node 16 (and therefore from npm 6 to npm 8), I am experiencing the following issue, which is blocking for installation of an internal tool I maintain.

This internal tool is meant to be executed as a script from anywhere, so it is installed globally (npm -g) and its package.json contains a bin entry:
```json
{
  "name": "@tools/my-tool",
  "bin": {
    "my-tool": "./my-tool.js"
  },
```
When installing said tool from an Gitlab internal npm registry, script files are not created in the global npm directory (`%appdata%/npm` in my case, on Windows).

If I downgrade npm to 6.14.15., npm does create the appropriate script files.

Puzzlingly:
- installing from a local folder works (npm i -g C:\my_tool_repo)
- A minimal repro on github.com with their package registry works!
- Essentially the same minimal repro (with minimal config changes for CI/CD) on gitlab.com fails similarly to our internal Gitlab instance

### Expected Behavior

`npm -g` should create script files as appropriate for `bin` entries in `package.json`.

### Steps To Reproduce

Please see this minimal repro I created for this on Gitlab.com: https://gitlab.com/Ezekiel-DA/npm8_bin_issue_repro

Installing the package generated by this project:
```
echo @ezekiel-da:registry=https://gitlab.com/api/v4/projects/31019820/packages/npm/ >> .npmrc
npm install -g @ezekiel-da/npm8_bin_issue_repro
```

Notice that:
- the package is installed as expected, as per `npm list -g`
- script files for it are missing in global npm directory
- the npm8_bin_issue_repro cannot be invoked globally (obivously, since the scripts are missing)

### Environment

- OS: Windows 10
- Node: 16.13.0
- npm: 8.1.0*

*also tested 8.1.2, same results

**Comment by IronGeek** [comment]
This also happens with me with non-global package installation on `npm v8.1.3` and `npm v7.7.6` (`node v15.14.0`)

The `npm 6.14.15` (`node v14.18.1`) however correctly install the package with its binary linked on `node_modules/.bin`. 
Seems to me this is a regression all the way from npm 6 to 7 to 8

FWIW,
I'm also installing a **scoped packages** from **GitLab packages registry**

--- 

**Note**:
On local package installation, deleting the `package-lock.json` and the `node_modules/.package-lock.json` and then running `npm install` again, will correct the issue and add the binary link in `node_modules/.bin`

**Comment by Ezekiel-DA** [comment]
Did some more digging here: this seems to be an issue Gitlab acknowledges, as seen [here](https://gitlab.com/gitlab-org/gitlab/-/issues/330929).

However, it is still a functional regression from npm6 to npm 8. How is npm 6 able to correctly install the bin scripts in this scenario?

**Comment by GVHengy** [comment]
Same issue. If i add dependency in `package.json` from gitlab package repository and use commands like:
`npm i nmp@6`
`npx npm i`
The script in node_modules/.bin is created (and postinstall hook also runs)
However, with npm@7 or npm@8 it does not happen.

On the other hand, if i download .tgz package to filesystem and install it as
`npm i @packed_dependancy_from_gitlab_regestry-0.0.2.tgz --save`
Both postinstall script runs and bin file is created ( like e.g. node_modules/.bin/packed_dependancy_from_gitlab_regestry )

So, it is probably a gitlab issue indeed, however, still not clear why with npm@6 this works fine.

**Comment by wraithgar** [comment]
This appears to be working as of `npm@8.16.0`

```sh
~/D/n/c/w/libnpmexec (gar/libnpmexec-global-scoped-npm-tree|✔) $ npm i -g gist:a5a65137bd390864e294ec80bb91e005

added 1 package, and audited 2 packages in 2s

found 0 vulnerabilities
~/D/n/s/empty $ ls (npm get prefix -g)/bin/npm-exec-gist
/Users/wraithgar/.nvm/versions/node/v18.6.0/bin/npm-exec-gist
```
