### ISSUE TITLE
[BUG] npm ci is trying to load a package.json file when using --prefix

### ISSUE THREAD

**Issue by jcollum** [npm/cli#4001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```
$ npm --version
8.1.3
$ ls mock-servers/oidcMock
package-lock.json
$ npm --prefix mock-servers/oidcMock ci
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/justin.collum/work/reports-landing-page/mock-servers/oidcMock/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/justin.collum/work/reports-landing-page/mock-servers/oidcMock/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/justin.collum/.npm/_logs/2021-11-05T18_02_13_162Z-debug.log
```

Note that this isn't my code so I have no idea why there is a package-lock but no package file. Entirely possible that this is sort of a ridiculous thing to do and we really need that package.json file. But there's nothing in the docs about that and I don't see any good reason that `npm` wouldn't be able to do this.

I did cd in to that folder and run `npm ci` with no issues. 

### Expected Behavior

Since the folder contains a package-lock file I would expect `ci` to read that file and install based on the contents of that file, as usual. But the `--prefix` command seems to be messing things up. Or there's a requirement that the folder have a package.json when using `ci` [that isn't documented](https://docs.npmjs.com/cli/v7/commands/npm-ci). Note that there aren't any 8.x docs on that page but I am using 8.x, so I'm just assuming there's no change. 

The explanation of `--prefix` here [makes me think this should work.](https://docs.npmjs.com/cli/v7/using-npm/config#prefix)

### Steps To Reproduce

1. have a valid package-lock.json file in a subfolder that does not contain a package.json 
2. from the root folder, run `npm --prefix subfolder ci` 

### Environment

```
  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 256.36 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.1/bin/yarn
    npm: 8.1.3 - ~/.nvm/versions/node/v14.18.1/bin/npm
```

- npm config:
```ini
$ npm config ls                                                                                                                                                                254 ↵
; "user" config from /Users/justin.collum/.npmrc

@redacted:registry = "[redacted]"
engine-strict = true
save-prefix = ""

; "project" config from /Users/justin.collum/work/reports-landing-page/.npmrc

registry = "[redacted]"

; node bin location = /Users/justin.collum/.nvm/versions/node/v14.18.1/bin/node
; cwd = /Users/justin.collum/work/reports-landing-page
; HOME = /Users/justin.collum
; Run `npm config ls -l` to show all defaults.
```

**Comment by ljharb** [comment]
Why are you using the prefix at all?

Also note, `prefix` is incompatible with nvm, which nvm will tell you about if you use any other mechanism besides "per-invocation" to set the prefix.

**Comment by jcollum** [comment]
> Why are you using the prefix at all?

Because the alternative is `pushd` & `popd`, which might break a build script if the command fails. 

>prefix is incompatible with nvm

I have no idea why you're bringing up nvm.

**Comment by ljharb** [comment]
@jcollum because of `node bin location` pointing to it in your "npm config" section in the OP.

The alternative is "do the command inside a subshell, with parens", which will then not change the working directory for the overarching context.

**Comment by jcollum** [comment]
I see some nvm issues related to the npm config prefix when the folder is a symlink eg https://github.com/nvm-sh/nvm/issues/2029. But they are all over a year old and none of my nvm versions are symlinks

```
$ ls -alh `npm config get prefix`/..
total 0
drwxr-xr-x  5 justin.collum  NWEA\Domain Users   160B Oct 12 16:38 .
drwxr-xr-x  3 justin.collum  NWEA\Domain Users    96B Oct 12 16:37 ..
drwxr-xr-x  9 justin.collum  NWEA\Domain Users   288B Oct 12 16:37 v12.22.7
drwxr-xr-x  9 justin.collum  NWEA\Domain Users   288B Oct 12 16:37 v14.18.1
drwxr-xr-x  9 justin.collum  NWEA\Domain Users   288B Oct 12 16:38 v16.11.1
```

I have used `--prefix` on an npm command many times in the past while also running Node via nvm. I don't see the route of failure that you're proposing.

**Comment by ljharb** [comment]
I'm nvm's maintainer, and I've built a lot of code into nvm to detect when the npm prefix is non-default, and to error out in that case. I'm glad it's worked for you, but that doesn't change that it's not a supported use case.

That, itself, doesn't change that this seems like a bug with npm - i was just trying to suggest alternatives that may make your issue moot.

**Comment by jcollum** [comment]
Gotcha. Thanks for the assist.

**Comment by wraithgar** [comment]
A package is more than just a lockfile.  `npm ci` does use the lockfile to cut out a lot of calculations it would need to otherwise to do rebuild your tree, but the `package.json` is also still required in order to install.

Looks like the docs are a little misleading there, implying an "either" situation for `package.json` and `node_modules` being valid to do an install, but it's describing how the `prefix` value is derived, not requirements for installation.

If you have a good suggestion for where this fact (a package.json is required) should live in our docs feel free to submit it.
