### ISSUE TITLE
NPM error when trying to install node red on android

### ISSUE THREAD

**Issue by SoumyadeepChatterjee96** [npm/cli#4002]
$ npm i -g --unsafe-perm node-red
npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2021-11-05T09_09_31_968Z-debug.log

I am very new to the env of linux and do not have the knowledge to understand the issue yet so just requesting someone to guide me to understand when i am going wrong and what can be done to eliminate this error and proceed with the installation on my android device on termux through f droid and on lineage os android 11 aosp.

**Comment by VA2XJM** [comment]
I have found that depending on the device you use, the solution might be different. Try in this order:
1. Upgrade NPM: `npm i npm`
2. If it is a lock error, adding this to the command will gets you through: `--no-package-lock`
3. On one tablet I had to revert NPM to V6: `npm i npm@6`

**Comment by darcyclarke** [comment]
**Closing:** this error can arise for a number of reasons; Please read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) & refile an issue with as much information as possible if you're able to **consistently reproduce** this error.
