### ISSUE TITLE
[BUG] React installation fails with npx

### ISSUE THREAD

**Issue by RoyGalaxy** [npm/cli#4007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I have been trying to react with npx v8.1.0 but it fails you can see the error message. Kindly provide me with the solution ASAP.
![Screenshot_20211107-110639_Termux](https://user-images.githubusercontent.com/75137220/140633783-3e08b89f-6186-46f5-a706-d65ebecdc765.png)

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 8.1.0
- Node: 16.13.0
- OS: Android
- platform: 
- npm config: 
; node bin location = /data/data/com.termux/files/usr/bin/node
; cwd = /data/data/com.termux/files/home/reactProjects
; HOME = /data/data/com.termux/files/home
; Run `npm config ls -l` to show all defaults.
```

**Comment by wraithgar** [comment]
This error on termux/android typically has to do with the os running out of resources and prematurely killing processes.  There is not much npm can do for this environment.  We do have plans to try to make npm work better in limited resource environments, but until then you may have to use a system with more memory and/or file handles.
