### ISSUE TITLE
[BUG] <NPM install not downloading any package from NPM registry>

### ISSUE THREAD

**Issue by NoobletBilal** [npm/cli#4011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

NPM install is not pulling any repositry from npm repositories. There SSL routine error for Bad signature. NPM debug logs are as below.
nfo it worked if it ends with ok
erbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
erbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
erbose cli   'install',
erbose cli   '-g',
erbose cli   'gulp' ]
nfo using npm@3.10.9
nfo using node@v6.9.2
illy loadCurrentTree Starting
illy install loadCurrentTree
illy install readGlobalPackageData
illy fetchPackageMetaData gulp
illy fetchNamedPackageData gulp
illy mapToRegistry name gulp
silly mapToRegistry using default registry
silly mapToRegistry registry https://registry.npmjs.org/
silly mapToRegistry data Result {
silly mapToRegistry   raw: 'gulp',
silly mapToRegistry   scope: null,
silly mapToRegistry   escapedName: 'gulp',
silly mapToRegistry   name: 'gulp',
silly mapToRegistry   rawSpec: '',
silly mapToRegistry   spec: 'latest',
silly mapToRegistry   type: 'tag' }
silly mapToRegistry uri https://registry.npmjs.org/gulp
verbose request uri https://registry.npmjs.org/gulp
verbose request no auth needed
info attempt registry request try #1 at 6:43:33 PM
verbose request id 91d9fe34d468ef4f
http request GET https://registry.npmjs.org/gulp
info retry will retry, error on last attempt: Error: write EPROTO 101057795:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:openssl\ssl\s3_clnt.c:2010:
info attempt registry request try #2 at 6:43:47 PM
http request GET https://registry.npmjs.org/gulp
info retry will retry, error on last attempt: Error: write EPROTO 101057795:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:openssl\ssl\s3_clnt.c:2010:
info attempt registry request try #3 at 6:44:48 PM
http request GET https://registry.npmjs.org/gulp
silly fetchPackageMetaData Error: write EPROTO 101057795:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:openssl\ssl\s3_clnt.c:2010:
silly fetchPackageMetaData
silly fetchPackageMetaData     at exports._errnoException (util.js:1022:11)
silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:801:14)
silly fetchPackageMetaData  error for gulp { Error: write EPROTO 101057795:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:openssl\ssl\s3_clnt.c:2010:
silly fetchPackageMetaData
silly fetchPackageMetaData     at exports._errnoException (util.js:1022:11)
silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:801:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }
silly rollbackFailedOptional Starting
silly rollbackFailedOptional Finishing
silly runTopLevelLifecycles Finishing
silly install printInstalled
verbose stack Error: write EPROTO 101057795:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:openssl\ssl\s3_clnt.c:2010:
verbose stack
verbose stack     at exports._errnoException (util.js:1022:11)
verbose stack     at WriteWrap.afterWrite (net.js:801:14)
verbose cwd D:\
error Windows_NT 10.0.19042
error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "gulp"
error node v6.9.2
error npm  v3.10.9
error code EPROTO
error errno EPROTO
error syscall write
error write EPROTO 101057795:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:openssl\ssl\s3_clnt.c:2010:
error If you need help, you may report this error at:
error     <https://github.com/npm/npm/issues>
verbose exit [ 1, true ]

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 3.10.9
- Node: 6.9.2
- OS: Windows 10
- platform: HP Notebook
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by baixiaoyu2997** [comment]
same issue

**Comment by wraithgar** [comment]
npm 3 is unsupported, and is using ssl versions that are not supported by the npm registry anymore.

**Comment by ljharb** [comment]
Only node 0.8 and below use ssl versions that the registry doesn’t; npm 3 and node 0.10, and later, can connect fine. npm 3 is indeed long unsupported, though :-)

**Comment by NoobletBilal** [comment]
I have tested same on HP 10 gen laptop Windows 10 and everything works fine Node installation and npm install for all packages. The issue arised on many HP 11th gen laptop Windows 10 i  tested.

**Comment by Chris55** [comment]
hi

have you tried to use http instead of https ?

npm config set registry http://registry.npmjs.org/

**Comment by pdqsoftware** [comment]
Hi guys,
I am having exactly the same problem as mentioned at the top by Noobletbilal.
I'm using Node v7.10.1 and npm 4.2.0.
I get the error when I try to install any package, either globally or locally.
I have tried setting strict-ssl to false and using the http and https registry URLS.
My machine is a brand new Windows 10 box.

If I go up to using Node 8.0.0, npm works fine.

Please can someone make some suggestions to get me past this?  Unfortunately my app requires this version of Node!
Thanks very much.
Paul

**Comment by ljharb** [comment]
@pdqsoftware both of those are wildly out of date. The oldest node that is supported is node 12 (and in a few weeks, it’ll be 14) and only npm 8 latest is supported.

**Comment by pdqsoftware** [comment]
> @pdqsoftware both of those are wildly out of date. The oldest node that is supported is node 12 (and in a few weeks, it’ll be 14) and only npm 8 latest is supported.

Thanks @ljharb.  Don't I know it!  Sadly it is a company project that was going long before my time.  I've talked about getting a newer version of Node in place, but it will be very time consuming to do.  I'm also not sure how I would even start with such an old application.  If you can please give me any ideas on how to do that I will certainly give it a go...

**Comment by ljharb** [comment]
@pdqsoftware start on node 8, update all your deps to the latest non-breaking versions; test and deploy. update to node 10, update deps, test and deploy. and repeat, going up to 12, and then 14, and ideally then 16.

**Comment by InaFK** [comment]
> > @pdqsoftware both of those are wildly out of date. The oldest node that is supported is node 12 (and in a few weeks, it’ll be 14) and only npm 8 latest is supported.
> 
> Thanks @ljharb. Don't I know it! Sadly it is a company project that was going long before my time. I've talked about getting a newer version of Node in place, but it will be very time consuming to do. I'm also not sure how I would even start with such an old application. If you can please give me any ideas on how to do that I will certainly give it a go...

Hi **@pdqsoftware**! I've similar situation on our legacy projects with the same issue (node v6.10.3 / npm v3.10.10).
Thank you **@ljharb** for describing the way how gradually move on to highest versions.
@pdqsoftware have you tried @ljharb's conception? If yes, how was it? Thanks!

**Comment by pdqsoftware** [comment]
Hi Jordan,
That makes sense.  Let me set up a new system and make a start with Node
8.0.0.
Maybe, if I really get stuck, you wouldn't mind helping me again?
I promise not to bug you every five minutes.
Thanks.
Paul

**Comment by ljharb** [comment]
Sure, but please find me in Twitter or Slack or IRC instead of making noise on this issue :-)

**Comment by pdqsoftware** [comment]
> > > @pdqsoftware both of those are wildly out of date. The oldest node that is supported is node 12 (and in a few weeks, it’ll be 14) and only npm 8 latest is supported.
> > 
> > 
> > Thanks @ljharb. Don't I know it! Sadly it is a company project that was going long before my time. I've talked about getting a newer version of Node in place, but it will be very time consuming to do. I'm also not sure how I would even start with such an old application. If you can please give me any ideas on how to do that I will certainly give it a go...
> 
> Hi **@pdqsoftware**! I've similar situation on our legacy projects with the same issue (node v6.10.3 / npm v3.10.10). Thank you **@ljharb** for describing the way how gradually move on to highest versions. @pdqsoftware have you tried @ljharb's conception? If yes, how was it? Thanks!

Hi @InaFK, it has taken a while but I am now just starting to make progress on this 'project'.  I've moved from v7.10.1 through to v8.5.0.  I've had some fun with stuff that has changed - mostly webpack configurations.  But I'm getting there.  The hardest bit is testing everything to make sure nothing has broken.  I also take regular breaks, for a few days, from it so that I don't get too disheartened!

**Comment by khsbai** [comment]
I had the same issue and installing the Nodejs 32-bit solved it
