### ISSUE TITLE
[BUG] intermittent npm install failure while using github urls - kex_exchange_identification: Connection closed by remote host

### ISSUE THREAD

**Issue by kumarrishav** [npm/cli#4012]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

<img width="1138" alt="Screen_Shot_2021-11-08_at_01_38_53" src="https://user-images.githubusercontent.com/4078325/140702389-84999bba-bfde-498a-b6b3-0d2379eb41a9.png">

### Expected Behavior

Should complete npm install

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 8.1.3
- Node: v12.20.0
- OS: macos
- platform:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by wraithgar** [comment]
This looks like a `git` problem, all npm does is shell out to the `git` executable and that is where the error is happening.
