### ISSUE TITLE
Add a flag which prevents installing any NEWLY published package versions to reduce risk of installing malicious code through compromised packages

### ISSUE THREAD

**Issue by maxpaj** [npm/cli#4013]
Given the recent uaparser-js, coa and rc packages being compromised:

Would it be possible to implement a flag for npm CLI which would prevent installing newly published packages, regardless of where they appear in the dependency tree of a package?

As a developer using npm on a daily basis, installing and updating packages, it would be extremely cumbersome to go through the entire depency tree of each package to check for newly published package versions and expose yourself to the risk of installing some package that may have been compromised recently. 

Something like this:

```
$ npm install react-scripts@latest --skip-newly-published
> ERROR: Found package X (published 3 hours ago) in depedency tree, skipping react-scripts
```

This flag would prevent me from installing malicious software onto my system and gives me the oportunity to review any newly published package myself.

I guess the alternative would be to have a review process for any new package released to the public npm registry... But in my opinion, this implementation would be much easier.

**Comment by ljharb** [comment]
This already exists - use `--before=2021-11-07` or any date of your choosing. I believe you could stick this in `.npmrc` as well.

**Comment by maxpaj** [comment]
> This already exists - use `--before=2021-11-07` or any date of your choosing. I believe you could stick this in `.npmrc` as well.

Very nice. Perhaps the default should be to apply this filtering for packages published within the last couple of hours. An opt-out would allow you to bypass it.

**Comment by wraithgar** [comment]
Changing the default would be a very significant breaking change, and one that would need to go through the [rfc process](https://github.com/npm/rfcs)
