### ISSUE TITLE
[Security Feature Request] ability to `blacklist` typo package

### ISSUE THREAD

**Issue by loynoir** [npm/cli#4014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

typo `npm install typescipt` allowed

### Expected Behavior

typo `npm install typescipt` reject

### Steps To Reproduce

Reproduce something, and add typescript.

### Environment

- npm:
- Node:
- OS:
- platform:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by loynoir** [comment]
https://www.npmjs.com/~jackwenhy

**Comment by wraithgar** [comment]
This is not something that it is feasible for the npm cli itself to do. Typically security things like this are handled on a registry level.
