### ISSUE TITLE
[BUG] postinstall scripts which call `npm run` fail when installing globally

### ISSUE THREAD

**Issue by dominykas** [npm/cli#4015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Didn't have time to build a reduced case, but this works: https://github.com/sindresorhus/pure (not sure what the install script actually does 🙈)

```
14:50 $ npm i -g pure-prompt
npm ERR! code 254
npm ERR! path /Users/dominykas/.nvm/versions/node/v14.18.1/lib/node_modules/pure-prompt
npm ERR! command failed
npm ERR! command sh -c if [ -e /opt/homebrew/bin/zsh ]; then PURE_DEST=/opt/homebrew/share/zsh/site-functions npm run --silent postinstall-link && exit 0; elif [ -e /usr/local/bin/zsh ]; then PURE_DEST=/usr/local/share/zsh/site-functions npm run --silent postinstall-link && exit 0; elif [ -e /bin/zsh ] || [ -e /usr/bin/zsh ]; then for dest in /usr/share/zsh/site-functions /usr/local/share/zsh/site-functions; do if [ -d $dest ]; then PURE_DEST=$dest npm run --silent postinstall-link && exit 0; fi; done; fi; PURE_DEST="$PWD/functions" npm run --silent postinstall-link && npm run --silent postinstall-fail-instructions

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dominykas/.npm/_logs/2021-11-08T12_50_24_800Z-debug.log
```

This works fine in 8.1.2, but fails in 8.1.3.

This works fine when installing locally, but not when installing globally.

I suspect there might some env vars not passed through or smth? I do get complaints about `null/package.json` on some of non-public tools I'm trying this on.

### Expected Behavior

No failure

### Steps To Reproduce

`npm i -g [package with a postinstall script which calls "npm run"]`

### Environment

- npm: 8.1.3
- Node: 14.8.1
- OS: macOS
- platform:
- npm config:
```ini
package-lock = false 
```

**Comment by bohdan-basov** [comment]
Same error when installing aws-lambda-ric globally inside container

**Comment by Prinzhorn** [comment]
Probably broken here https://github.com/npm/cli/commit/a0d35ff20aed6aab8508123eb540bc9c61fb127d

>  fix: dont load project configs in global mode

Why @nlf / @wraithgar ? What exactly does that fix?

**Comment by nlf** [comment]
global mode should work the same whether there's a project config or not, which is why we stopped loading it when operating in global mode. it's also [documented](https://docs.npmjs.com/cli/v8/configuring-npm/npmrc#per-project-config-file) that project configs are ignored in global mode, but that wasn't actually the case, so that change was a bug fix.

the issue here is related, but separate and is fixed by the pull request linked above. it'll be part of the next release, thanks for reporting!
