### ISSUE TITLE
[Question] difference between --legacy-peer-deps and --force

### ISSUE THREAD

**Issue by kumarrishav** [npm/cli#4021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

<img width="928" alt="Screen Shot 2021-11-08 at 23 57 26" src="https://user-images.githubusercontent.com/4078325/140870464-86a1ea25-7114-4920-af23-4d066be76cd5.png">

I got this error message. From the error message, it seems like both flag does same thing and either can be used.

But when I read about these flags, both are a bit different.
- legacy-peer-deps - brings v6 behaviour for peerDeps installation i.e no installation of peerDeps and no install failure
- force - bring npm 7/8  behaviour of peerDeps installation (i.e install peerdeps) but doesn't fail during the installation in case of any issue and proceed with it. The default behaviour of npm 8 is - it fails in case of an issue with peerdeps installation. 

can someone confirm?

### Expected Behavior

clearer error message or hint

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 8.1.3
- Node: 12.20.1
- OS:macOS
- platform:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by wraithgar** [comment]
Yes that is what those mean

https://docs.npmjs.com/cli/v8/using-npm/config#legacy-peer-deps
https://docs.npmjs.com/cli/v8/using-npm/config#force
