### ISSUE TITLE
[Feature Request] Prevent installation of dependency (anywhere in chain)

### ISSUE THREAD

**Issue by zmrmn** [npm/cli#4022]
Since there are multiple incidents because of infected npm-packages, I just asked myself if its somehow possible, to prevent the installation of an package, if it contains a certain dependency or if that dependency is somewhere in the chain.

Something really basic in package.json like

```
{
  "prevent":["rc@1.2.9"]
}
```
... or something in that manner

**Comment by darcyclarke** [comment]
We're currently developing overrides which should meet this need (ref. https://github.com/npm/rfcs/blob/main/accepted/0036-overrides.md) via. swapping any package you don't ever want to be installed (or a specific version of a package) with a patched version, placeholder or maybe a completely different package/fork etc..

Example usage:
```json
{
   "overrides": {
     "rc@1.2.9": "malware-placeholder-pkg"
   }
}
```
