### ISSUE TITLE
[BUG] npm prune --production does not remove hoisted prod dependencies

### ISSUE THREAD

**Issue by everett1992** [npm/cli#4024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`npm prune --production` does not prune `node_modules` installed in workspace package folders. It appears to only modify the workspace root node_modules.

Workspace package's `a` and `b` depend on different versions of typescript so
one or both dependencies must be hoisted above the workspace root. Both are dev
dependencies but only packages in node_modules, not packages/*/node_modules are
removed by `npm prune`.

```console
$ git clean -xfd
$ npm install
```

npm explain shows that `a`'s typescript@3 dep was installed in the workspace
root while `b`'s typescript@4 dep was hoisted to
`node_modules/b/node_modules/typescript`, a symlink to
`packages/b/node_modules/typescript`.

```console
$ npm explain typescript
typescript@3.9.10 dev
node_modules/typescript
  dev typescript@"^3.9.10" from a@1.0.0
  packages/a
    a@1.0.0
    node_modules/a
      workspace packages/a from the root project

typescript@4.4.4 dev
packages/b/node_modules/typescript
  dev typescript@"^4.4.4" from b@1.0.0
  packages/b
    b@1.0.0
    node_modules/b
      workspace packages/b from the root project
```

After running prune to remove all dev dependencies the typescript dev
dependency in packages/b/node_modules/typescript is still present. 

```console
$ npm prune --production
$ npm explain typescript
typescript@4.4.4 dev
packages/b/node_modules/typescript
  dev typescript@"^4.4.4" from b@1.0.0
  packages/b
    b@1.0.0
    node_modules/b
      workspace packages/b from the root project
```

### Expected Behavior

`npm prune --production` should remove all dev dependencies from the workspace.

### Steps To Reproduce

[I created a repository that demonstrates this issue](https://github.com/everett1992/npm-issue-workspace-prune)

### Environment

- npm: 8.1.3
- Node: 16.13.0
- OS: Ubuntu
- platform: N/A
- npm config: N/A

**Comment by jpage-godaddy** [comment]
Is there any workaround for this bug?

**Comment by vincentpham13** [comment]
same issue here, does anyone has solution yet?

**Comment by 0Dmitry** [comment]
Same issue. Looks like none of the three package managers(npm, yarn, pnpm) support this feature. I guess the only possible solution for now is to remove the node_modules after the build/compile step and then re-install only the production dependencies.

**Comment by 0Dmitry** [comment]
Or probably I was wrong about "all package managers", `yarn workspaces focus <packageName> --production` or `yarn workspaces focus --production --all`
 seems to do the job.

**Comment by lavcraft** [comment]
Same issue with npm 9.5.1. Awful bug 1 year old. Looks like many users doesn't respect to resulted docker image size in production :) 

Also this provide security issues, because many dev tools  located in production images.. 

How highlight this problem and increase priority?

**Comment by lavcraft** [comment]
Works fine in 9.7.2

**Comment by eladchen** [comment]
@lavcraft

Nope, does not work. Tested with 9.8.0

**Comment by reggi** [comment]
I test this with 10.7.0 and this works as expected, both are being removed:

```
rm -rf node_modules
rm -rf packages
rm package.json
rm package-lock.json

npm init -y
npm init -y --workspace=packages/a
npm init -y --workspace=packages/b
npm install typescript@3.9.10 --save-dev --workspace=packages/a
npm install typescript@4.4.4 --save-dev --workspace=packages/b

cat ./node_modules/typescript
cat ./packages/b/node_modules/typescript

npm prune --production

cat ./node_modules/typescript
cat ./packages/b/node_modules/typescript

npm -v
```

Results:

```
cat: ./node_modules/typescript: Is a directory
cat: ./packages/b/node_modules/typescript: Is a directory
cat: ./node_modules/typescript: No such file or directory
cat: ./packages/b/node_modules/typescript: No such file or directory
10.7.0
```
