### ISSUE TITLE
Can not use my github username with npm

### ISSUE THREAD

**Issue by sam0hack** [npm/cli#4030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

npm ERR! code E400
npm ERR! 400 Bad Request - PUT https://registry.npmjs.org/-/user/org.couchdb.user:sam0hack - That word is not allowed. Please contact support at https://npmjs.com/support if you believe you received this in error.

[Issue Image](https://imgur.com/a/Dz73Bgk)

### Expected Behavior

Should adduser

### Steps To Reproduce

Step 1. npm adduser
Step 2 . Username: sam0hack
Step 3.  Password: Mypass

### Environment

- npm: 8.1.3
- Node: v12.21.0
- OS: Pop!_OS 21.04 x86_64 
- platform: Dell Inspiron

**Comment by wraithgar** [comment]
The github.com site and the npm registry are two different systems, your login for one is not the same as your login for the other.
