### ISSUE TITLE
Install packages from local paths creates a symlink instead of copying content

### ISSUE THREAD

**Issue by ibilux** [npm/cli#4031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Installing packages from local paths creates a symlink to package instead of copying the local package content.

### Expected Behavior

Installing packages from local paths should copy the local package content instead of creating a symlink to package .

### Steps To Reproduce

Just followed the docs in here:
https://docs.npmjs.com/cli/v7/configuring-npm/package-json#local-paths

### Environment

npm: '8.1.3',
node: '14.18.0',
os: 'Linux';
v8: '8.4.371.23-node.84',
uv: '1.42.0',
zlib: '1.2.11',
brotli: '1.0.9',
ares: '1.17.2',
modules: '83',
nghttp2: '1.42.0',
napi: '8',
llhttp: '2.1.3',
openssl: '1.1.1l',
cldr: '39.0',
icu: '69.1',
tz: '2021a',
unicode: '13.0'

**Comment by KrayzeeKev** [comment]
No, symlinks here are great. If it copies the files and the package refers to a path inside the project, Node may see two packages. eg: if your dependency is "@namespace/lib": "./lib"
Then a require('./lib/foo') will resolve to one file and require('@namespace/lib/foo') will resolve to another. And they'll be different libraries. I love the symlink behaviour. It's allowed us to mix relative paths with "I just want to go back to the root".

I would suggest any change here should be a command line flag or an option in package.json

I face another issue which is that on windows, the symlinks have trailing / which is bad. Lodging separate bug for that.

**Comment by ibilux** [comment]
@KrayzeeKev I'm using sveltekit wich use ES module and the local package I'm importing is using CommonJS, hence, the local package shows errors (that _**require**_ is not support or not found). But, when I copy the local package to "node_modules" folder the project works fine.
Is there any better approach to this ?

**Comment by casperdcl** [comment]
same issue reported in https://github.com/npm/npm/issues/18503 I think

**Comment by saghul** [comment]
The metro bundler, used by default in React Native cannot deal with symlinks, so a way to opt out of creating them when doing `npm install` would be very welcome.

**Comment by nlf** [comment]
`npm install --install-links ../foo` will now install the contents of the directory `../foo` by packing them into a tarball and installing the resulting tarball. we may look into changing the behavior of `file:` based dependencies in the future, but for now this is the way to avoid symlinks

**Comment by saghul** [comment]
This is very helpful, thank you!

What npm version is that available in?
