### ISSUE TITLE
Inform when omitting packages based on environment variables

### ISSUE THREAD

**Issue by MartinMuzatko** [npm/cli#4038]
If I do `npm install --omit=dev` it is easy to see why no `devDependencies` get installed.
However, if there is an environment variable such as `NODE_ENV=production` or `NPM_CONFIG_OMIT=dev`, it is not self-explanatory to the user of the cli.

This becomes especially hard to debug when working with docker multi-stage-builds, where the env is possibly inherited from a previous image. It took me approximately three hours to find out why that was the case.

I only get this information as the result of doing `npm install`, with the env var set somewhere else.
```
up to date, audited 1 package in 156ms

found 0 vulnerabilities
```

Additionally to the text above, I would expect another information, such as `omitted 5 packages`. This would at least inspire to check the relevant documentation for the `--omit` flag, where it is explained very well. https://docs.npmjs.com/cli/v7/using-npm/config#omit.

Thank you for your consideration!

**Comment by darcyclarke** [comment]
Hey @MartinMuzatko! This is great feedback & I apologize for your frustration. We're looking to modify the UI/UX of the CLI in the New Year with an expectation that we'll bubble up more streamlined, accurate, actionable messaging to end-uers for `npm install` & `npm audit`. What I can say is that many people utilize `npm config ls` to get insight into how their environments are set up/configured & will behave today.

I'm going to backlog a note about your recommendation for our team & close this issue as we only track bugs here. In the future, any feature requests or feedback can be submitted to [npm/feedback](https://github.com/npm/feedback) or more formally in the CLI team's [npm/rfcs](https://github.com/npmrfcs) repo.

**Comment by MartinMuzatko** [comment]
Thank you very much for your reply and tracking this further.
