### ISSUE TITLE
[BUG] NPM Run Syntax Error When Using Extglobs

### ISSUE THREAD

**Issue by Errorbot1122** [npm/cli#4051]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

when I run a cmd the has an extglobs (specifically this one: `!(...)` ) with npm run, it seems to not recognize it. But if I run it normally by just typing it out on the cmd line, it works

**NORMAL**
```cmd
$ echo !(node_modules)
docs.hbs dont_doc Globles.js package.json package-lock.json readme.md
```

**NPM RUN**
```cmd
$ npm run test

> roblox-file-handler@1.0.0 test
> echo !(node_modules)

sh: 1: Syntax error: "(" unexpected
```

### Expected Behavior

for it to not tell me `sh: 1: syntax error: "(" unexpected` and work like normel

### Steps To Reproduce

1. Create / Open a folder
2. Create a file named **public.txt**
3. Create a folder called **empty_folder**
4. Run `cd [FOLDER PATH]`
5. Run `npm init` **NO `-y` AT THE END**
6. Spam *Enter* until you get to: **test command**
7. Enter `echo !(empty_folder)` as your command
8. Spam Enter until done
9. Type `yes` at the end
10. Run `echo !(empty_folder)`, you should see this as the output: `package.json public.txt`
11. Run `npm run test`, you should see err: `sh: 1: Syntax error: "(" unexpected`

### Environment

- npm: **8.1.0**
- Node: **16.13.0**
- OS: **Ubuntu 20.04.2 LTS**
- platform: Gitpod

**npm config:**
```ini
; node bin location = /home/gitpod/.nvm/versions/node/v16.13.0/bin/node
; cwd = /workspace/Roblox-File-Handler/test
; HOME = /home/gitpod
; Run `npm config ls -l` to show all defaults.
```

**Comment by ljharb** [comment]
What is an extglob? Is that perhaps something supported by a specific shell, but not the shell npm invokes all its commands in?

**Comment by Errorbot1122** [comment]
@ljharb  look that the [bash page](gnu.org/software/bash/manual/html_node/Pattern-Matching.html) about globs or the [extglob package](https://www.npmjs.com/package/extglob) readme

**Comment by nlf** [comment]
by default we use `sh` as your shell for running scripts. it sounds like on your system this isn't running `bash`, but something else. you'll probably need to change that to bash explicitly with, i.e. `npm config set script-shell bash --location=user`

if that doesn't work, please feel free to reopen this issue and let us know!
