### ISSUE TITLE
Special link for users

### ISSUE THREAD

**Issue by fayasnoushad** [npm/cli#4061]
Please provide special link for users.

Like `https://user.npmjs.com/<username>` redirect to `https://www.npmjs.com/~<username>`

**Comment by ljharb** [comment]
This isn’t a CLI-related topic; it wouldn’t go in rfcs either since it’s a serverside thing. Maybe npm/feedback?

**Comment by fayasnoushad** [comment]
> This isn’t a CLI-related topic; it wouldn’t go in rfcs either since it’s a serverside thing. Maybe npm/feedback?

Ok
