### ISSUE TITLE
[BUG] npm install fails when the package-lock.json file is set to read only

### ISSUE THREAD

**Issue by MichaelGoff** [npm/cli#4068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Our project is using Perforce for version control so any files that are not checked out are put into read-only mode. Starting when we moved to npm 7 when we run `npm install` we get the following error on Windows (we get a very similar error on Mac too). 

```ini
PS E:\JMPdev\Server\webjmp> npm install
npm ERR! code EPERM
npm ERR! syscall open
npm ERR! path E:\JMPdev\Server\webjmp\package-lock.json
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, open 'E:\JMPdev\Server\webjmp\package-lock.json'
npm ERR!  [Error: EPERM: operation not permitted, open 'E:\JMPdev\Server\webjmp\package-lock.json'] {
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'E:\\JMPdev\\Server\\webjmp\\package-lock.json'
npm ERR! }
```

This started occurring when we updated from Node `14.16.1` and npm `6.4.12` to npm 7 and has continued to the latest npm version `8.4.1`

When we put package-lock.json into read only mode and run the install the file is unchanged. 

### Expected Behavior

NPM install executes successfully, like it does when package-lock.json is not in read-only mode.

### Steps To Reproduce

1. `npm init` a new project
2. `npm install --save vue`
3. Set package-lock.json to read only in the operating system
4. run `npm install`
5. see error
```ini
$ npm install
npm ERR! code EPERM
npm ERR! syscall open
npm ERR! path E:\code\package-lock.json
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, open 'E:\code\package-lock.json'
npm ERR!  [Error: EPERM: operation not permitted, open 'E:\code\package-lock.json'] {
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'E:\\code\\package-lock.json'
npm ERR! }
```

### Environment

- npm: 8.1.4
- Node: 16.13.0
- OS: Windows 10 Enterprise version 1909
- platform: Windows Desktop
- npm config:
```ini
$ npm config ls
; node bin location = C:\Program Files\nodejs\node.exe
; cwd = E:\code
; HOME = C:\Users\migoff
; Run `npm config ls -l` to show all defaults.
```

**Comment by ParadoxInfinite** [comment]
Hey @MichaelGoff, `npm install` command is expected to update the package-lock file, for any checksum update, any package changes will be tracked for every `npm install`, so it is working as expected.

What you're looking for is maybe `npm ci` which I believe will work even when package-lock.json is in read-only as it installs using the package-lock itself and not update it, basically a good idea as it'll maintain consistent dependencies.

**Comment by MichaelGoff** [comment]
Thank you for the information. I did not realize that `npm ci` would work in read-only mode and it sounds like exactly what we need.
