### ISSUE TITLE
[BUG] npm v8 installs incorrect dependencies

### ISSUE THREAD

**Issue by zulucoda** [npm/cli#4070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

npm v8 installs packages that have not been included in the package.json file.

### Expected Behavior

In npm v6, npm only installed dependencies specified in the package.json

### Steps To Reproduce

Using my [react-swift-slider repo](https://github.com/zulucoda/react-swift-slider), the root package.json has the following dependencies:
```json
...
"peerDependencies": {
"react": ">=16.8",
"react-dom": ">=16.8"
},
"dependencies": {
"prop-types": "15.7.2",
"styled-components": "5.2.1"
},
"devDependencies": {
"@babel/cli": "7.16.0",
"@babel/core": "7.16.0",
"@babel/plugin-proposal-class-properties": "7.16.0",
"@babel/preset-env": "7.16.0",
"@babel/preset-react": "7.16.0",
"@rollup/plugin-babel": "5.3.0",
"@rollup/plugin-commonjs": "21.0.1",
"@rollup/plugin-node-resolve": "13.0.6",
"@testing-library/jest-dom": "5.15.0",
"@testing-library/react": "12.1.2",
"@testing-library/react-hooks": "7.0.2",
"babel-jest": "27.3.1",
"babel-loader": "8.2.3",
"coveralls": "3.1.0",
"husky": "7.0.4",
"is-ci": "3.0.1",
"jest": "27.3.1",
"lint-staged": "12.0.2",
"prettier": "2.4.1",
"react": "17.0.2",
"react-dom": "17.0.2",
"react-test-renderer": "17.0.2",
"rollup": "2.60.0",
"rollup-plugin-terser": "7.0.2",
"webpack": "5.64.1",
"webpack-cli": "4.9.1"
},
...
```
The example folder has two folders with javascript and typescript examples, and each folder has a package.json file; this is the package.json file for `examaple/javascript`:
```json
...
"dependencies": {},
"devDependencies": {
"@babel/core": "7.12.13",
"@babel/preset-env": "7.12.13",
"@babel/preset-react": "7.12.13",
"babel-loader": "8.2.2",
"react-hot-loader": "4.13.0",
"serve": "11.3.2",
"terser-webpack-plugin": "^5.1.1",
"webpack": "5.21.1",
"webpack-cli": "4.9.0",
"webpack-dev-server": "4.5.0"
}
...
```
**Note:** In the `examaple/javascript/package.json` file there is NO `react`, or `react-dom` packages. These packages are only included in the root/package.json

1. `npm install` in the root
1. cd `example/javascript` and `npm install`

With npm v6, only installs dependencies specified in the `examaple/javascript/package.json`.
```bash
├─┬ example/
  └─┬ javascript
    └─┬ node_modules
      └─ .bin
      └─ ...
      └─ @babel
      └─ babel-loader
      └─ ...
```
With npm v8, `react` and `react-dom` dependencies have been installed in the `example/javascript/node_modules`
```bash
├─┬ example/
  └─┬ javascript
    └─┬ node_modules
      └─ .bin
      └─ ...
      └─ @babel
      └─ babel-loader
      └─ react
      └─ react-dom
      └─ ...
```

This causes the examples not to run with npm v8, whereas npm v6 the examples work fine.

### Environment

npm v8.1.4

### Tested Versions:
It looks like the bug was introduced from v7. I've tested the following versions, and all have the same bug.
- npm 8.1.4
- npm 8.1.0
- npm 7.24.2
- npm 7.0.0

**Comment by nlf** [comment]
npm 6 did not install peerDependencies by default. `react-hot-loader`, which is a dependency in your example `package.json` has peerDependencies on both `react` and `react-dom`.

npm 7 (and 8) changed peerDependencies behavior and now installs them by default. if you do not wish this behavior, you can run `npm install --legacy-peer-deps`.

this change was documented in the [npm 7 announcement](https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major.html)

**Comment by zulucoda** [comment]
@nlf thanks man :+1:
