### ISSUE TITLE
[BUG] Cannot run npx on fresh installation of node

### ISSUE THREAD

**Issue by Stophface** [npm/cli#4071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Upon typing

    $ npx

in the Terminal after a fresh installation of NodeJS, I get the following

```
/usr/local/lib/node_modules/npm/bin/npx-cli.js:27
const { definitions, shorthands } = require('../lib/utils/config/index.js')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
```

### Expected Behavior

I expect a list of available commands for `$ npx`

### Steps To Reproduce

1. Go to nodejs.org and install NodeJS.
2. Add Path to `./bash_profile`

    export PATH=$PATH:/usr/local/bin

3. Restart the Terminal
4. Type `npx `

### Environment

- npm: 3.8.6
- Node: 5.12.0
- OS: 10.15.7
- platform: Macbook Pro
- npm config: ->

```
; cli configs
user-agent = "npm/3.8.6 node/v5.12.0 darwin x64"

; node bin location = /Users/macosx/.nvm/versions/node/v5.12.0/bin/node
; cwd = /Users/macosx
; HOME = /Users/macosx
; "npm config ls -l" to show all defaults.

```

**Comment by ljharb** [comment]
That's because npx ships with npm 5, and both node 5 and npm 3 (and npm 5) are wildly out of date.

The oldest version of node that's not EOL is 12; the newest is 16 or 17.

**Comment by Stophface** [comment]
@ljharb Thanks for your response. When I run

    brew install node

I get no during installation. However, 

    node -v

returns v5.12.0. That is odd.

**Comment by Stophface** [comment]
Apparently I had some odd old version of `node` with `nvm` installed on my machine. I removed the `.nvm` folder in my Home director (`~/`), then did a `brew unlink node && brew link node` and now it works...

**Comment by ljharb** [comment]
The alternative would have been to run `nvm install node`.
