### ISSUE TITLE
[BUG] npm 8.1.4 cli failed when run cache clean

### ISSUE THREAD

**Issue by goldRoshan** [npm/cli#4075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

STEP 32: RUN npm --version
6.4.1
STEP 33: RUN npm install -g npm@latest
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
+ npm@8.1.4
added 83 packages from 25 contributors, removed 248 packages and updated 139 packages in 9.667s
STEP 34: RUN npm cache clean --force
(node:1) ExperimentalWarning: The fs.promises API is experimental
npm WARN npm npm does not support Node.js v10.15.1
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN using --force Recommended protections disabled.
npm ERR! Unexpected token =

npm ERR! A complete log of this run can be found in:

### Expected Behavior

Previous version works as expected:
STEP 30: RUN npm --version
6.4.1
STEP 31: RUN npm install -g npm@8.1.3
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
+ npm@8.1.3
added 80 packages from 25 contributors, removed 249 packages and updated 138 packages in 8.731s
STEP 32: RUN npm cache clean --force
(node:1) ExperimentalWarning: The fs.promises API is experimental
npm WARN npm npm does not support Node.js v10.15.1
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN using --force Recommended protections disabled.
STEP 33: RUN npm install

### Steps To Reproduce

1. Run in container podman
2. Run steps in Dockerfile
RUN npm --version
RUN npm install -g npm@latest
RUN npm cache clean --force
3. See error when run `npm cache clean --force`

### Environment

- npm: 8.1.4
- Node: v10.15.1
- OS: RHEL 7.7
- platform: Linux

**Comment by ljharb** [comment]
npm 8 requires node 12 or later.

**Comment by goldRoshan** [comment]
> * v10.15.1

Thanks @ljharb  wondering why 8.1.3 works with v10.15.1 please?

**Comment by ljharb** [comment]
@goldRoshan by chance. You're not supposed to be using any npm 8 version with node 10, because it's unsupported.
