### ISSUE TITLE
Not able to install Pakages on Termux

### ISSUE THREAD

**Issue by iceking-1912** [npm/cli#4079]
**[ISSUE]** Not able to Install 📦Packages
on _Android Termux_

Commands- 

1. `npm install --global ten-hands-cli`
2. `npm install hello`

[2021-11-22T15_44_47_866Z-debug.log](https://github.com/npm/cli/files/7582581/2021-11-22T15_44_47_866Z-debug.log)

Log is attached 📎

Please Slove This Issue 👍🏻

**Comment by darcyclarke** [comment]
**Closing:** please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).
