### ISSUE TITLE
[BUG]  'ts-node' is not recognized as an internal or external command 

### ISSUE THREAD

**Issue by milon27** [npm/cli#4083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```
#package.json file script

nodemon index.ts
```

 'ts-node' is not recognized as an internal or external command #1951 

### Expected Behavior

it was running on npm 6.*.* properly.

### Steps To Reproduce

 1. in a typescript project. 
 2. just run nodemon index.ts
 3. it will give  'ts-node' is not recognized as an internal or external command but ts-node is already installed as dev-dependency.

### Environment

- npm: 8.*.*
- Node: 16.3.*
- OS: windows
- platform: windows

**Comment by ljharb** [comment]
That seems like an issue with nodemon, not with npm - does `npx ts-node` work?

**Comment by milon27** [comment]
``` npx ts-node ``` yes it working

**Comment by ljharb** [comment]
In that case, please file an issue on nodemon.
