### ISSUE TITLE
[BUG] Cannot install ttfautohint

### ISSUE THREAD

**Issue by cssobral2013** [npm/cli#4088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Install of ttfautohint via npm cannot be made. It displays an error, as shown [here](https://github.com/npm/cli/files/7595786/2021-11-24T12_57_56_104Z-debug.log).

### Expected Behavior

The ttfautohint install should proceed just fine.

### Steps To Reproduce

1. Type in Windows Terminal, without quotes,  'npm install ttfautohint', and wait until it displays that error.

### Environment

- npm: 8.1.0
- Node: 17.0.1
- OS: Windows 11
- platform: Compaq CQ-11
- npm config:
; "builtin" config from C:\Program Files\nodejs\node_modules\npm\npmrc

prefix = "C:\\Users\\cssob\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = D:\CristianoSobral\Documents\GitHub\Cambridge-Font
; HOME = C:\Users\cssob
; Run `npm config ls -l` to show all defaults.

**Comment by shadowspawn** [comment]
From the log file, this looks like a problem with `ttfautohint ` rather than with `npm` itself. You might try opening an issue on [ttfautohint](https://github.com/enteocode/node-ttfautohint), but there have been no issues and no code changes in a few years so may not be active.

```
386 error # [ttfautohint] Compiling binaries
387 error node:child_process:397
387 error       ex = new Error('Command failed: ' + cmd + '\n' + stderr);
387 error            ^
387 error
387 error Error: Command failed: ./configure --disable-shared --enable-static --prefix="C:\Users\cssob\AppData\Local\npm-cache\enteocode\ttfautohint\build" --without-bzip2 --without-harfbuzz --without-png --without-zlib CFLAGS="-fPIC -g -O3 -IC:\Users\cssob\AppData\Local\npm-cache\enteocode\ttfautohint\build/include" CXXFLAGS="-fPIC -g -O3 -IC:\Users\cssob\AppData\Local\npm-cache\enteocode\ttfautohint\build/include" LDFLAGS="-fPIC -LC:\Users\cssob\AppData\Local\npm-cache\enteocode\ttfautohint\build/lib -LC:\Users\cssob\AppData\Local\npm-cache\enteocode\ttfautohint\build/lib64" PKG_CONFIG=" " && make && make install
387 error '.' n�o � reconhecido como um comando interno
387 error ou externo, um programa oper�vel ou um arquivo em lotes.
```

**Comment by ruyadorno** [comment]
thanks @shadowspawn!

**Closing:** we do not support/triage third-party libraries or tooling bugs; Please file an issue with the relevant project.
