### ISSUE TITLE
[BUG] Failed to install heroku-cli through npm. "Exit handler never called!"

### ISSUE THREAD

**Issue by ghost** [npm/cli#4093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I can't install heroku-cli through npm. it just shows the error message "Exit handler never called!".
![Screenshot_20211125-142209753](https://user-images.githubusercontent.com/88977720/143484128-9d87765e-68dc-4e26-ba1f-f51d93bf4f2c.jpg)

LOG: https://pastebin.com/bUuzaezB

### Expected Behavior

Npm should install heroku-cli

### Environment

- npm:  8.1.2
- Node: 17.1.0
- OS: Android
- Environment: Termux
- platform: Xiaomi Pocophone F1
- npm config:
```ini
; node bin location = /data/data/com.termux/files/usr/bin/node
; cwd = /storage/emulated/0/termux/tempbot/a
; HOME = /data/data/com.termux/files/home
; Run `npm config ls -l` to show all defaults.
```

**Comment by solaluset** [comment]
Having same error on Termux, npm 8.1.4, node v16.13.0

**Comment by murga96** [comment]
Same issue over here with npm: 8.1.2, Node: 17.1.0 on termux
Installing heroku with yarn fixes the problem. I hope in the future npm fix this problem

**Comment by ghost** [comment]
> Same issue over here with npm: 8.1.2, Node: 17.1.0 on termux Installing heroku with yarn fixes the problem. I hope in the future npm fix this problem

Excuse-me, could you tell me how did you install it with yarn? i'm still unable to install it, even with yarn or npm

**Comment by murga96** [comment]
Hi, I use yarn add heroku, this give me some errors but it works

**Comment by fritzy** [comment]
Likely this is due to the limit resources of a typical Android environment. Eventually we'll be able to support embedded environments with more limited resources.
