### ISSUE TITLE
[Feature request] allow `:...` suffixes to `start` and `test` commands

### ISSUE THREAD

**Issue by Pomax** [npm/cli#4094]
(Also, it might be useful to have a "feature request" template in the issue type chooser)

Right now `npm start` and `npm test` will run the `start` and `test` scripts, respectively, but only match those two exact words, meaning that things like the following script set requires two different methods of invocation:

```json
{ 
  "scripts": {
    "test": "npm run test:common",
    "test:visual": "run-s test && npx complex-test --very-occasionally-necessary",
    "start": "node server.js",
    "start:electron": "npm run start -- --parallel && npm run electron",
    "electron": "..."
  }
}
```

This uses standard `npm test` and `npm start`, but requires `npm run test:visual` and `npm run start:electron` for the "special case" start and test runs. Not needing `run` here at all would be far less confusing to fingers.

(of course, one can be in the habit of always typing `npm run start` and `npm run test`, but `start` and `test` exist as dedicated commands as quality of life improvement. Allowing suffixes would be in line with that improvement =)

**Comment by ljharb** [comment]
Feature requests go in https://github.com/npm/rfcs, not this repo.

Note that omitting `run` is a proposal that's already been rejected for a number of reasons.

**Comment by Pomax** [comment]
It would be good to have links to those reasons then, because npm _already_ omits `run` for start and test. I would be very impressed if someone has a solid reason not to make those prefix matches into process.argv rather than exclusive matches (because "start up overhead" isn't one).

**Comment by ljharb** [comment]
https://github.com/npm/rfcs/pull/279#issuecomment-823638195

**Comment by Pomax** [comment]
cheers. Although that's wildly different from what this issue was about. There's no addition of new commands _and_ there's no backward compat breaking changes here.

**Comment by ljharb** [comment]
Making `npm test:start` work is adding a new top-level command. doing that just for the entirely non standard colon convention would make no sense, so it’d have to work for every script. Thus, npm could never again add a new top level command without breaking someone.

**Comment by Pomax** [comment]
no, it wouldn't. It would extend the already existing `test` command. As for "colon vs. whatever else" wars: it doesn't matter, go with `\W`, done. The character itself is irrelevant, the only thing that matters is that it matches "what is in package.json". If a project uses `test:jest`, then `npm test:jest` should work. If someone uses `test.whatever` then `npm test.whatever` should work. It would be mighty weird to decline this because "we might want our own `test:...` command in the future" when npm's policy rules that out.

**Comment by ljharb** [comment]
Of course it matters. A ton of people are depending on `test:foo` having NO relationship to `test`, myself included.

Are you only suggesting `test:` and `start:`-prefixed commands be able to omit the `run`? Why just those? What about folks that use `npm run test-foo` or `npm run `test.foo`?

**Comment by Pomax** [comment]
you didn't read what I said apparently? 

> As for "colon vs. whatever else" wars: it doesn't matter, go with \W, done. The character itself is irrelevant, the only thing that matters is that it matches "what is in package.json"

If folks, like you, declare `test-foo` in your package.json then why would anyone even remotely care that you use a hyphen. Or a coloon. Or a dot. Or any "not a letter" as separator. By treating `start` and `test` as prefix commands, none of that matters, all of them work.
