### ISSUE TITLE
[BUG] `npm install` runs `npm run prepublish` in npm 8.1.3

### ISSUE THREAD

**Issue by RomanDavlyatshin** [npm/cli#4097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

As the title states, when running `npm install`, npm calls `prepublish` script.

This behavior is not documented https://docs.npmjs.com/cli/install/ (the search for `pre` and `prepublish` yields nothing related to the subject)

I can see why it is was kept that way for backward-compatibility reasons. Nonetheless, I suggest considering to:

1. Add the appropriate documentation
2. Show WARNING message when running `prepublish` in that way. Something along the lines of `running prepublish automatically, that might not be the desired behavior, read more at <link to the docs>` should do the job.

At that point in time, the only way to understand why `"prepublish": "npm i && npm run build"` + calling `npm i` leads to an infinite loop is to find the obscured thread created back in 2013 for [the exact same issue](https://github.com/npm/npm/issues/3059).

### Expected Behavior

A clear warning message & documentation on the behavior present on https://docs.npmjs.com/cli/install/ page

### Steps To Reproduce

1. Install node v16.x & npm 8.1.3
2. With this package.json config (omitting the unimportant stuff)
```
{
  ...
  "scripts": {
    "build": "echo 'building...'",
    "prepublish": "npm i && npm run build",
    "publish": "npm publish"
  },
  ...
}
```
3. Run 'npm i'
4. Watch the infinite loop happening

### Environment

- npm: 8.1.3
- Node: v16.13.0
- OS: Window 10 
- platform:
- npm config:
```ini
; "builtin" config from C:\Users\pinky\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\pinky\\AppData\\Roaming\\npm"

; "user" config from C:\Users\pinky\.npmrc

//registry.npmjs.org/:_authToken = (protected)
init-license = "Apache-2.0"
init.author.name = "Roman Davlyatshin <davlyatshinra@gmail.com> (https://github.com/RomanDavlyatshin)"
tag-version-prefix = ""

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = D:\projects\sample
; HOME = C:\Users\pinky
; Run `npm config ls -l` to show all defaults.
```

**Comment by wraithgar** [comment]
The scripts docs outline this, and are linked from the `npm install` docs page https://docs.npmjs.com/cli/v8/using-npm/scripts#prepare-and-prepublish

If you would like to suggest an edit to the install docs that calls this out, feel free to submit a PR.

**Comment by adamlui** [comment]
@wraithgar I encountered the same bizarre behavior, find no mention from `npm install` docs page either. Nott sure why you claim it is "linked" unless you suggest TOC which links to everything is suffice

**Comment by RomanDavlyatshin** [comment]
@adamlui CTRL+F "prepublish" does the trick
According to the [updated docs](https://docs.npmjs.com/cli/v8/using-npm/scripts#prepare-and-prepublish):
1. old `prepublish` event that was triggered by `npm install` is deprecated now
2. new event is added called `prepublishOnly` that will work as intuitively expected - only triggered before the `publish` event

That was just a quirk of npm design from old days. It confused a lot of folks - hence, it's changed now.

**Comment by adamlui** [comment]
That's not the doc for `npm install` which OP and I both refer to, it is https://docs.npmjs.com/cli/v10/commands/npm-install. Your link is for a scripts page neither of us claimed to not have deprecation info. Our only claim is `npm install` doc makes no mention (which we obviously both found the intuitive place to go to find out what's wrong, so should be fixed if countless others are like us)

**Comment by adamlui** [comment]
You said "scripts docs outline this, **and are linked from the npm install docs page** " and upon further investigation, you are referring to:

![image](https://github.com/npm/cli/assets/10906554/8f73b945-a739-4b88-9b62-bceb92ee62a2)

... which you are quite strangely using to justify our intuition leading us to look for info for such alarming behavior in main body text should be ignored, simply because one link in a large wall of footer links leads to other docs "outline this behavior"

**Comment by adamlui** [comment]
Actually you're not even the guy that used this awkward claim to close this issue, but you clearly support it with your interjection so my points are still relevant to making you see this is horrible doc design decision to be supporting

**Comment by RomanDavlyatshin** [comment]
> this is horrible doc design decision to be supporting

You can always contribute by creating a pull request to address any issues you see. NPM's documentation is open-source and available on [GitHub](https://github.com/npm/documentation)

>  but you clearly support it

I'm not explicitly supporting or opposing any particular design decisions. My goal is to help anyone encountering this issue by explaining that the way this works has changed.

Overall, it seems like you're experiencing some frustration, which is understandable, yet let's keep the tone constructive. NPM is a free publicly available tool, created by a bunch of people to the best of their ability, with the benign intent.
You wanna improve it - cool, hop onboard and help!

**Comment by adamlui** [comment]
> You can always contribute by creating a pull request to address any issues you see. NPM's documentation is open-source and available on [GitHub](https://github.com/npm/documentation)

Ok I may do that

> I'm not explicitly supporting or opposing any particular design decisions. My goal is to help anyone encountering this issue by explaining that the way this works has changed.

Well both the OP and I clearly understood it changed, our gripe was with the poorly designed docs leading to wasting both ours (and potentially countless others) time

> Overall, it seems like you're experiencing some frustration, which is understandable, yet let's keep the tone constructive.

I am being constructive, my goal was to highlight the closer of this issue was being rash, as OP was not alone in his very valid concern over `npm install` doc is missing a disclaimer by helpfully opening this issue which got swiftly shot down

> NPM is a free publicly available tool, created by a bunch of people to the best of their ability, with the benign intent.

Not sure what your goal in telling me this is, but FYI many projects are gatekept by people who like to be over-controlling (I checked you are barely active on GitHub w/ 475 contributions vs. I have over 27000 in the past year, probably why you didn't know this)

**Comment by adamlui** [comment]
I just realized you are the OP o.O

**Comment by ljharb** [comment]
@adamlui contribution count is utterly meaningless, and can be easily gamed by, eg, making lots of small commits that should really be combined. You may find https://yourlogicalfallacyis.com/ad-hominem and https://yourlogicalfallacyis.com/appeal-to-authority to be helpful reading, as well as https://docs.npmjs.com/policies/conduct.
