### ISSUE TITLE
[BUG] Freshly installed Windows CLI npm: `& was unexpected at this time.`

### ISSUE THREAD

**Issue by MathiasBaumgartinger** [npm/cli#4099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

After downloading nodejs: [LTS Version: 16.13.0 (includes npm 8.1.0)](https://nodejs.org/en/download/ ), whenever I use ``npm`` in my cmd/powershell I get ``& was unexpected at this time.``. By "whenever" i literally mean anytime I use ``npm``:
```ps
PS C:\project> npm
& was unexpected at this time.
PS C:\project> npm -v
& was unexpected at this time.
...
```
I tried alternative installations, the problem seems to persist however.

### Expected Behavior

A working function of npm.

### Steps To Reproduce

To be honest, I dont know how to reproduce. But I am very lost. Tried to reset all Env-Variables, tried purging all of node/npm and freshly installing. Tried different installation options. The problem seems to persist.

### Environment

- npm: 8.1
- Node: 16.13
- OS: Windows 10
- platform: Custom build PC
- npm config: cant really do that with the described problem, my npmrc file looks like this however
```ini
prefix=${APPDATA}\npm
```

**Comment by ljharb** [comment]
Why do you have prefix set? What happens if you remove that line and use the normal npm root -g?

**Comment by MathiasBaumgartinger** [comment]
I do not know why this prefix is set, I can assure that I never did this manually. 

Changing it however, does not seem to make a difference for me.

**Comment by MathiasBaumgartinger** [comment]
Should someone else stumble across this problem in the same context: In fact it is not an npm problem, but a windows registry problem; the ``autorun`` command that is automatically invoked when any cmd (e.g. bat) is used anywhere (which happens to be the case for npm) was faulty. For some reason the entry had an ``&`` sign in it, which i could easily just remove. Everything working fine now.

Further info:
https://stackoverflow.com/questions/59480657/cmd-exe-throws-error-was-unexpected-at-this-time
