### ISSUE TITLE
npm-config should follow XDG directory spec for per-user config filepath

### ISSUE THREAD

**Issue by Xrey274** [npm/cli#4106]
The XDG directory spec outlines a standard, user-configurable set of directories defined as environment variables (with defaults).

npm-config should be using $XDG_CONFIG_HOME/npm/config as its config file instead of ~/.npmrc

[reference spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

Copy of: [#6675](https://github.com/npm/npm/issues/6675)

**Comment by ljharb** [comment]
Feature requests go in the rfcs repo, not here.

Closing this in favor of the existing RFC: https://github.com/npm/rfcs/issues/389
