### ISSUE TITLE
[BUG] Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.

### ISSUE THREAD

**Issue by amiruddinsaifi** [npm/cli#4107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ERR_SOCKET_TIMEOUT: request to https://registry.npmjs.org/mongodb failed, reason: Socket timeout
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node:
- OS:
- platform:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by ljharb** [comment]
Please fill out the issue template, especially the version numbers.

**Comment by wraithgar** [comment]
We would definitely need more info to know what the error is, and how to reproduce it. As jordan said please fill out the issue template.
