### ISSUE TITLE
QUESTION: Is there a way to reference an environment variable in `package.json`?

### ISSUE THREAD

**Issue by sepsol** [npm/cli#4122]
I didn't know where to ask this question, apologies if this is not the right place in advance.

I want to ask everyone in my organization to add an environment variable in their systems pointing to the directory in their computers where the cloned packages from our organization live. Then, I want to point to that directory from our main project's `package.json` under `workspaces`. Is it possible to do that?

For example:

### Package.json
```json
{
  "workspaces": [
    "$COMPANY/packages/*"
  ],
}
```

**Comment by ljharb** [comment]
Then wouldn’t the workspaces live outside the directory that contains the package.json?

Couldn’t you make a package.json inside that folder instead, that uses relative paths?

**Comment by sepsol** [comment]
It would. I'm planning to have some packages shared  between `react` and `react native` frontends but am really hesitant to create a big monorepo to wrap around all that.

**Comment by ljharb** [comment]
Why? If they’re going to be managed together it seems like they should live together, and if they’re not, not.

**Comment by sepsol** [comment]
I've heard that git and some other operations might become slower. Plus I don't want everybody within my org to have access to everything. I want most people to have access to the packages only through regular dependencies and others who are engaged in developing packages have access to the package code itself. Not to mention not anybody who works on a package for `react` would be working on a package for `react native` necessarily. Basically I want a more fluid structure.

**Comment by ljharb** [comment]
So for your question, I do not believe there's any way to do this.

You can file an rfc on github.com/npm/rfcs if you want to propose one.

(To be clear, I think it would be a very bad idea to allow a folder structure where package.json isn't at the root of its project - each architecture choice in your organization has tradeoffs, and while it's nice to want the best of multiple worlds without the downsides, unfortunately it rarely works like that :-/)

**Comment by sepsol** [comment]
@ljharb Thanks for the helpful information. Can you explain why this would not be a bad idea? And whether there are any alternatives I should consider? 

I thought of creating dummy repositories that include my other individual repos as submodules and configure the access for each of them individually. But that would add too much redundancy for the team.

**Comment by ljharb** [comment]
It seems to me like the choices are:

1. put everything in the same repo, it's fine for everyone to have read access to everything, use CODEOWNERS to regulate who can change what, use npm workspaces at the top level of that repo
1. split things up into different repos. each repo can have its own access (but i'd still suggest always giving everyone read access to everything, secrecy for code doesn't add value). then, you *can't* and shouldn't try to manage those repos with the same npm command invocation - meaning, you don't need workspaces across those repos.

**Comment by sepsol** [comment]
Thanks a lot for your help @ljharb! I'm gonna close this issue and think about it a little bit more.
