### ISSUE TITLE
Issue v8

### ISSUE THREAD

**Issue by TehseenTech** [npm/cli#4125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node:
- OS:
- platform:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```
$ npm install electron --verbose
npm verb cli [
npm verb cli   '/data/data/com.termux/files/usr/bin/node',
npm verb cli   '/data/data/com.termux/files/usr/bin/npm',
npm verb cli   'install',
npm verb cli   'electron',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@8.2.0
npm info using node@v16.13.1
npm timing npm:load:whichnode Completed in 1ms
npm timing config:load:defaults Completed in 7ms
npm timing config:load:file:/data/data/com.termux/files/usr/lib/node_modules/npm/npmrc Completed in 3ms
npm timing config:load:builtin Completed in 5ms
npm timing config:load:cli Completed in 8ms
npm timing config:load:env Completed in 2ms
npm timing config:load:file:/data/data/com.termux/files/home/AhMyth-Android-RAT/AhMyth-Server/.npmrc Completed in 1ms
npm timing config:load:project Completed in 4ms
npm timing config:load:file:/data/data/com.termux/files/home/.npmrc Completed in 1ms
npm timing config:load:user Completed in 2ms
npm timing config:load:file:/data/data/com.termux/files/usr/etc/npmrc Completed in 1ms
npm timing config:load:global Completed in 3ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:credentials Completed in 6ms
npm timing config:load:setEnvs Completed in 3ms
npm timing config:load Completed in 44ms
npm timing npm:load:configload Completed in 44ms
npm timing npm:load:setTitle Completed in 2ms
npm timing config:load:flatten Completed in 12ms
npm timing npm:load:display Completed in 33ms
npm verb logfile /data/data/com.termux/files/home/.npm/_logs/2021-12-05T13_22_56_053Z-debug-0.log
npm timing npm:load:logFile Completed in 20ms
npm timing npm:load:timers Completed in 0ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load Completed in 105ms
npm timing arborist:ctor Completed in 4ms
npm timing idealTree:init Completed in 535ms
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm timing npm Completed in 1854ms
npm verb unfinished npm timer command:install 1638710577155
npm verb unfinished npm timer reify 1638710577165
npm verb unfinished npm timer reify:loadTrees 1638710577237
npm verb unfinished npm timer idealTree 1638710577239
npm verb unfinished npm timer idealTree:inflate 1638710577777
npm info ok
npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2021-12-05T13_22_56_053Z-debug-0.log
~/AhMyth-Android-RAT/AhMyth-Server $ npm install
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2021-12-05T13_23_57_331Z-debug-0.log
~/AhMyth-Android-RAT/AhMyth-Server $

**Comment by darcyclarke** [comment]
**Closing:** this error can arise for a number of reasons; Please read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) & refile an issue with as much information as possible if you're able to **consistently reproduce** this error.
