### ISSUE TITLE
[BUG] config color "always" don't show color on command outdated 

### ISSUE THREAD

**Issue by Gurran** [npm/cli#4129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`npm outdated --color="always" | less -S`  shows colors in less

`npm config get color` shows `true`
This is the default value so all good. 

`npm config set color always`  should make `npm outdated` show colors.

`npm outdated | less -S` don't show colors(!) Even though --color="always" was working. 

### Expected Behavior

npm config setting color = always should always show colors on npm command `outdated`. 

### Steps To Reproduce

1. `npm config set color true`
2. `npm outdated | less -S` - should not show color
3. `npm config set color always`
4. `npm outdated | less -S` - should show color but don't

### Environment

- npm: 8.2.0
- Node: v17.2.0
- OS: Windows 10
- platform: Intel 
- npm config:
```ini
; "user" config from /home/user/.npmrc
color = "always" 
email = "npm requires email to be set but doesn't use the value" 

; "project" config from /home/user

always-auth = true 
registry = "REDACTED" 

; node bin location = /home/user/.nvm/versions/node/v17.2.0/bin/node
; cwd = /home/user/Code/
; HOME = /home/user
; Run `npm config ls -l` to show all defaults.
```

**Comment by lukekarrys** [comment]
Confirmed that this is fixed in at least `npm@10.7.0`, although probably much earlier than that.
