### ISSUE TITLE
[BUG] Reset Password Fails

### ISSUE THREAD

**Issue by dmidz** [npm/cli#4133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Hello,
I am sorry, this might not be the right place to ask, but I cannot login neither reset my npm password, and  [get support](https://www.npmjs.com/support) needs to signup so...
Behaviour : asking for reset, I receive the reset link by email, it opens a page where a temp generated password should be used on the signup, I try with my email and this temp passwords, it just fails ( tried 3 times until reset is blocked ).
Thank you for any help or direction to ask. 

### Expected Behavior

Able to reset account password.

### Steps To Reproduce

1. Go to https://www.npmjs.com/forgot and type your email
2. Click on the reset link from your inbox
3. Copy the generated temp password on the page
4. Try to signup with your email and the generated password

### Environment

N/A

**Comment by leegee** [comment]
Not sure why this was closed because there is no comment or reason given.

**Comment by bernardoadc** [comment]
same here, simply cannot reset password. Tryed also in cli, which correctly asks for new password, but does not work as well:

```
$ npm profile set password
Current password: 
New password: 
Again: 
npm ERR! code E401
npm ERR! 401 Unauthorized - GET https://registry.npmjs.org/-/npm/v1/user

```

**Comment by herom** [comment]
same here! I get to the point where I get an OTP via e-mail, enter it and boom..... 404
![image](https://user-images.githubusercontent.com/2472487/201750475-813b975c-2c7f-4467-b50c-80c2fb4a2395.png)

I mailed the npmjs support about this issue, but it seems that it doesn't bother them that much to send me a reply... :(
