### ISSUE TITLE
[BUG] npm ping docs are old

### ISSUE THREAD

**Issue by MansurAliKoroglu** [npm/cli#4136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`npm ping` does not return what is described in the docs.

### Expected Behavior

Docs should be updated

### Steps To Reproduce

1. Go check [npm docs](https://docs.npmjs.com/cli/v8/commands/npm-ping)
2. terminal
3. npm ping

### Environment

- npm: 8.2.0
- OS: Kubuntu linux 20.04
- npm config: default

**Comment by wraithgar** [comment]
https://github.com/npm/cli/pull/4423
