### ISSUE TITLE
[BUG] npm install creates symlinks incorrectly under Windows

### ISSUE THREAD

**Issue by KrayzeeKev** [npm/cli#4138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Our package.json includes (amongst others):
```
"dependencies": {
    "@root/api": "./api",
    "@root/app": "./app.js",
```
In Linux, this creates the following under ./node_modules/@root:
```
lrwxrwxrwx 1 userid groupid  9 Dec  7 13:27 api -> ../../api/
lrwxrwxrwx 1 userid groupid 12 Dec  7 13:27 app -> ../../app.js*
```

Which is great. require('@root/api') works, require('@root/api/github') works, require('@root/app') works

Under windows (using git bash) we get this:
```
lrwxrwxrwx 1 userid groupid 29 Dec 8 10:39 api -> /c/Users/userid/project/api//
lrwxrwxrwx 1 userid groupid 45 Dec 8 10:39 app.js -> /c/Users/userid/project/app.js/
```
Note the appended /

As a result, require('@root/api') and require('@root/api/github') both work fine as node_modules/@root/api//github.js resolves fine (even with two /'s)

BUT require('@root/app') does NOT work because the trailing slash makes that look like a symlink to a non-existent directory and so it's looking for node_modules/@root/app.js/index.js (or similar) which fails.

### Expected Behavior

In Linux, this creates the following under ./node_modules/@root:
```
lrwxrwxrwx 1 userid groupid  9 Dec  7 13:27 api -> ../../api/
lrwxrwxrwx 1 userid groupid 12 Dec  7 13:27 app -> ../../app.js*
```

Which is great. require('@root/api') works, require('@root/api/github') works, require('@root/app') works

### Steps To Reproduce

1. Under Windows
2. Include local package links in package.json
3. Run 'npm install'
4. See error... under node_modules as above

### Environment

- npm: 8.1.2
- Node: 16.13.1
- OS: Windows 10
- platform: Windows 10 / git-bash
- npm config: 
```ini
> npm config ls ; "builtin" config from C:\Program Files\nodejs\node_modules\npm\npmrc
prefix = "C:\\Users\\userid\\AppData\\Roaming\\npm"
; "user" config from C:\Users\userid\.npmrc
strict-ssl = true
; "project" config from C:\Users\userid\nguc-dm\.npmrc
registry = "http://hostname.company.com:32550/repository/ABC-NPM/"
; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\userid\nguc-dm
; HOME = C:\Users\userid
; Run `npm config ls -l` to show all defaults.
```

**Comment by nlf** [comment]
the strange thing here is that `./app.js` works as a dependency for you anywhere, that's not a supported means of declaring a package.. in windows, we create junctions rather than symlinks because symlinks require admin privileges. the trade off here is that junctions can only be absolute paths, and can only point to directories.

the fact you're able to use this means of aliasing `./app.js` to `@root/app` anywhere is actually a bug, and one we should fix..

**Comment by KrayzeeKev** [comment]
It makes sense to me that it works. At least under unix. If require opens the file and then parses it, it should work. Don't know if import would do the same. I also understand why you classify it as an accident.

Our use-case here is we originally had a hack that created "global.rootRequire = name => require(__dirname + '/' + name);"
The reason is that we could not publish our code as modules (various corporate / firewall issues) so use git submodules. So I have ./models, ./lib, ./api, etc in the root of the project. If something in models needs something in lib it does 'rootRequire('lib/utils'), for instance. That way I don't end up with "require('../../.../../lib/utils')" and moving files around in models is possible without going nuts. 
And then app.js exports the express router so there is, unfortunately, a lot of "const app = rootRequire('app')" so people can get to app.locals, for instance. 
Now I'm trying to remove rootRequire as the first of many small steps towards ESM and the @root thing in package.json worked magnificently. In linux (and apparently incorrectly, you say). If app can map to app.js then @root/app mapping to app.js seems consistent (in some sense). 

My issue is - what is the alternative? Refactor everything to never need the app. Or inject it everywhere. Or use globals.app. All ugly. Or move app.js to app/index.js and move config.js to config/index.js which is starting to be hack on top of hack on top of hack. And having a config.js in the root of the project just makes sense. Compared to config/index.js.

We've previously used module_alias but I dislike things that modify builtins. 

I'd just like a clean way of getting require and/or import to load things relative to the root of the project.

require('~/app') might be nice :-) 

I understand why npm uses junctions. We're struggling with our IT department on adjusting user permissions. I was planning on writing a script to remove the npm generated junctions and creating symlinks if we can get that permission. But it's all so messy.

**Comment by nlf** [comment]
> If require opens the file and then parses it, it should work.

not quite, a dependency is more than a single file that can be required. it's a directory with at least a `package.json` in it, the metadata contained in the `package.json` is critical to us building a proper dependency tree. it's very much a bug that we allow you to say a single javascript file is a package.

one alternative here i think may interest you is workspaces. here's a link to the docs: https://docs.npmjs.com/cli/v8/using-npm/workspaces

what you would do is define each of your `./models` `./lib`, etc as workspaces from a single root. they _must_ be directories with a `package.json` in each one, giving the package a name. generally it's best to make that name not be the same as something that exists in the actual registry. when you do this, we create symlinks for each package name to their corresponding workspace directory, which allows you to get the effect of `require('my-app')` instead of having to figure out the correct relative path.

if that's not acceptable for you, then you'll have to get creative. especially if you're moving to ESM. 

notably, https://nodejs.org/api/policy.html#dependency-redirection and https://nodejs.org/api/policy.html#example-import-maps-emulation are likely of interest to you (though they both require an experimental flag passed to `node` to work)

**Comment by KrayzeeKev** [comment]
@nlf  Thanks for that. Workspaces seem interesting as long as I can give them names that clearly indicate they are our stuff. And we're still faking them looking like modules. Which they will eventually be and then this problem mostly evaporates.

And it doesn't solve the very simple question: How do I require a file from the root of my project. Like "config.js" - Every file that needs that config has to otherwise have it injected. So it's a parameter to hundreds of functions. And it's VERY specific to this app so it's not a submodule.

It'd be nice if the standard / npm could simply do require('~/config.js") meaning the root of the project. Or the "cwd" in an ecosystem file. We already have require("from-node-modules"), require("/from/root/filesystem") (which should NEVER be a thing), require('./relative/directory') - having an alias for the root of the project just seems like a missed opportunity. Perhaps leading / could have been interpreted differently but that ship has sailed. Seriously, we allow a module to **require('/etc/passwd')** (yes I know it can read that file using fs but still, it's a little scary).

In the end, I think I'm leaning towards:
imports: {
  '#root/*': "."
}

Which appears to do EVERYTHING I want it to do as it's simple string replacement and refers to the root of the project. Pity that the '#root/*': "./*.js" can't do multiple, optional suffixes or I could mimick require behaviour in import later :-) But I'm going to have to have several /index.js imports in the future which is inevitable but ugly. Or massive refactoring.

But imports above seems to do the right thing.

**Comment by ljharb** [comment]
Implicit requires of things go pretty strongly against ecosystem patterns; if every file needs the config, the typical recommendation would be that every file needs a `require` (or an argument).

**Comment by KrayzeeKev** [comment]
@ljharb Exactly. But there is no mechanism to do the require other than every file knowing exactly how many ../'s they are from the root. node_modules doesn't need that. You can require("axios") from anywhere. But I can't require("%PROJECT_ROOT%/config.js"). Which ends up meaning every function we write, other than some little utilities have to have a config parameter. 
It's different to building modules which provide a standalone block-box interface. This is the guts of application software. I can use global.config but dislike that. I can use JSON.parse(process.env.CONFIG) but if I do, somebody better take me out the back and beat me with a stick.  require(`${process.env.CWD}/config.js`) is ugly and verbose and not good. 
If "~/...." means user's home directory (which makes sense but feels dangerous - but can't be argued to change) then maybe ~~/... could mean project home. Or some other construct.
Hence my various fiddlings with @root, #root and other trickery.

**Comment by ljharb** [comment]
@KrayzeeKev yes, that's what node has solved by using the "exports" field, and self-reference. In other words, if your root has `{ "name": "root", "exports": "./config.js" }`, then everything in the sub-projects should be able to do `require('root')`.

**Comment by KrayzeeKev** [comment]
@ljharb Is there a reference anywhere on how that works. The npm documentation says almost nothing. And every article on the web is about trying to export different things from modules in different environments. What is the syntax of exports? How does it work? I want to do this:
In routes/customer/site/user.js   I want to get to models/user.js, models/address.js, models/50otherthings.js
What do I put in exports and what syntax do I use to indicate I want models from the root? 

Actually, how does your syntax work? Where does "name" go? 
The exports syntax implies it should be: "exports": { "root": "./config.js" } which doesn't work.

**Comment by ljharb** [comment]
It’s a node feature, so it’s in node’s documentation for the “exports” field.

**Comment by KrayzeeKev** [comment]
@ljharb OK, I've worked out why this isn't making sense. It's not going to do anything even remotely what I want. I'm not exporting stuff from a module. This is not a name of a module. This is a program. Let's pretend there's no modules at all. Just one mono-repo filesystem.
I have (making this up but the idea is exactly what we do actually have, for better or worse):
./api/clients/system1API.js
./api/clients/system2API.js
./plugins/devices/device1.js
./models/users/address.js
./models/users/roles.js
./routes/customers/admins/users/roles.js

OK, so in that last file, there's a PATCH route for change the user's role. 
const userRoles = require('../../../../models/users/roles');
router.patch( '/role', (req, res, done) => { userRoles.setRole(req.body.role); done(); } );

That is horrible and I want it gone :-) This file needs to know it's 4 levels down the hierarchy so that it can escape to get to the roles. I want some way of indicating "THE ROOT OF THE PROJECT" or, if that's not possible then "THE MODELS DIRECTORY" (it's NOT a module, it's just a directory but I'm happy to put a package.json in there if it helps.

So I'm after:
require('ROOT/models/users/roles') OR
require('@root/models/users/roles') OR
require('#root/models/users/roles') OR
require('#models/users/roles') OR
require('~~/models/users/roles')

any way that is sensible, works in Unix & Windows (without admin privs - symlinks are out), does not depend on bugs in npm and does not require me to have a line in a package.json for EVERY file that require needs to find. I can live with an entry in package.json for every directory - one for models, one for api, one for plugins, etc

I'd also want it to handle: require('#root/app.js') or require('#root/config.js') - ie individual files as well as directories (this is where local packages in dependencies breaks down. Works in npm on unix because of a bug. 

So far, I'm leaning towards 'imports': { '#root/*': './*' } or similar.

I'm not sure how this exports feature helps with that. It appears to only have one "name" field for the entire project. Or, if the name is for the models "submodule" directory, how does require find it?

**Comment by ljharb** [comment]
again, using the name of the root package - which has to also define "exports" - should do exactly what you want.

This repo isn't the place to discuss it tho; find me on Slack or IRC or Gitter and I'll be happy to walk you through it.

**Comment by KrayzeeKev** [comment]
@ljharb I'm pretty much about to give up. I've spent an age battling slack to try break out of the team I'm in and I think I've created a personal workspace. Because you have to be part of my team. But I have no way of contacting you.
I'm convinced exports can't work unless every piece of software we produce is called the same thing and every one of 500+ files we have is listed in exports. VERY happy to be proved wrong. If you can find a way to chat outside here.

**Comment by ljharb** [comment]
@KrayzeeKev https://www.nodeslackers.com
