### ISSUE TITLE
[BUG] workspace scripts should be run in topological order by default

### ISSUE THREAD

**Issue by justinfagnani** [npm/cli#4139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

when running a script across workspaces like `npm run build --workspaces` you'll most likely end up with errors if your workspaces depend on each other as npm doesn't execute the script in topological order. Other monorepo tools like Lerna do this automatically.

The only workaround is to not use `"workspaces": ["packages/*"]` in package.json, but manually enter and maintain the list of packages by hand.

### Expected Behavior

Scripts should run in topological order.

### Steps To Reproduce

1. In any environment...
2. With a config that has multiple workspaces and wildcard workspaces setting like `"workspaces": ["packages/*"]`, and one package that depends on another, and say both use TypeScript...
3. Run `npm run build --workspaces`
4. See error from the compiler

### Environment

- npm: 8.2.0
- Node: 16.9.1
- OS: macOS 12.0.1
- platform: macOS
- npm config:
```ini
legacy-peer-deps = true 
```

**Comment by lukekarrys** [comment]
Just leaving a comment to link this to #3413 which is a related issue I think.

**Comment by ruyadorno** [comment]
Hi @justinfagnani thanks for taking the time to bring this up to our attention.

Given that this would be an entire new feature for **npm workspaces** to support I would recommend you to propose this as either a issue or discussion over at our [RFC repo](https://github.com/npm/rfcs) where it can pick up the attention from the community and the rest of the **npm cli** team.

**Comment by justinfagnani** [comment]
Sorry, I don't really have time to do that. This is how other monorepo tools work though, so if you want to just copy, say Lerna, that would probably be great for your users.

**Comment by ruyadorno** [comment]
Sounds good, no worries at all @justinfagnani 😊 eventually someone in the team (maybe even myself) will take the time to open an RFC for discussion and we'll move on from there.

I appreciate your help and keep an eye for updates! Thanks 😄

**Comment by zackerydev** [comment]
I went ahead and opened an RFC issue here
https://github.com/npm/rfcs/issues/548

We are hoping for this feature to land in `npm` as well

**Comment by faroceann** [comment]
A workaround here is to order your packages in the `workspaces` property of the top level package.json in the desired order of script execution. 

Example
```
...
"workspaces": [ 
	"/packages/a-package-depended-on",
	"/packages/b-package-depended-on",
	"/packages/package-dependent-on-a-b"
]
```

**Comment by stephematician** [comment]
> A workaround here is to order your packages in the `workspaces` property of the top level package.json in the desired order of script execution.
> 
> Example
> 
> ```
> ...
> "workspaces": [ 
> 	"/packages/a-package-depended-on",
> 	"/packages/b-package-depended-on",
> 	"/packages/package-dependent-on-a-b"
> ]
> ```

Is this still true? Using 10.8.1 I'm finding that "npm install" (locally) runs the "prepare" script for each workspace first, meaning that if you require one workspace package for the "prepare" script of another workspace (e.g. if you want to run `npx` or `ncc`) then it fails.

**Comment by Shadowstep33** [comment]
Any resolution/updates on this?
