### ISSUE TITLE
npm error : exit handler never called

### ISSUE THREAD

**Issue by M3hdi-Rostami** [npm/cli#4154]
### how to fix this error?

m3hdi@ubuntu:~/Desktop$ npx create-react-app my-app

Creating a new React app in /home/m3hdi/Desktop/my-app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...

npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/m3hdi/.npm/_logs/2021-12-10T06_47_49_060Z-debug-0.log

Aborting installation.
  npm install --save --save-exact --loglevel error react react-dom react-scripts cra-template has failed.

Deleting generated file... package.json
Deleting my-app/ from /home/m3hdi/Desktop
Done.

### Environment

- npm: 8.2.0
- Node: 14.17.6
- OS: ubuntu 20.04

**Comment by nlf** [comment]
see #417
