### ISSUE TITLE
[BUG] Please respect the calling runtime and PATH.

### ISSUE THREAD

**Issue by Dmole** [npm/cli#4164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Currently npm can not be used if there is more than one node version installed,
because npm will ignore the calling node runtime,
and npm will ignore the node runtime on the PATH,
and npm will refuse to run from node directly,
instead npm will use an arbitrary runtime.

### Expected Behavior

npm should use the current runtime, and respect $PATH.

### Steps To Reproduce

```
sudo which -a node
/usr/local/bin/node
/usr/bin/node
/bin/node
```

```
sudo which node
/usr/local/bin/node
```

```
sudo /usr/local/bin/node --version
v17.1.0
```

```
sudo /usr/local/bin/node /usr/local/bin/npm install -g node@latest
...
npm ERR! npm WARN npm npm does not support Node.js v10.19.0
...
```

```
node
Welcome to Node.js v17.1.0.
Type ".help" for more information.
> npm install -g node@latest
npm should be run outside of the Node.js REPL, in your normal shell.
(Press Ctrl+D to exit.)
>
```

### Environment

- npm:8.1.4
- Node:v17.1.0
- OS:Ubuntu 20.04.3 LTS
- platform:Dell XPS 13 9310
- npm config:
```ini
; node bin location = /home/user/node_modules/node/bin/node
; cwd = /home/user/Documents/eclipse-workspace/Noodle
; HOME = /home/user
```

**Comment by EduApps-CDG** [comment]
Yeah, don't blame him!

**Comment by nlf** [comment]
`sudo /usr/local/bin/node /usr/local/bin/npm install -g node@latest`

this won't work to run npm using a different version of node. you'll find that the file at `/usr/local/bin/npm` has what's known as a shebang that looks like `#!/usr/bin/env node` this tells your shell to run the script using the binary found by running `/usr/bin/env node`. We don't control what binary that resolves to, your system does it on your behalf.

you can see if this is different by running `/usr/bin/env node --version` and `sudo /usr/bin/env node --version`

i would also note that depending on your `sudo` config, there's no guarantee that your environment variables won't be dropped. we generally do not recommend using `sudo` with npm, though we are aware that when using system packages in distributions like ubuntu you don't have much choice. an alternative would be to `sudo apt remove nodejs` and use something like [`nvm`](https://github.com/nvm-sh/nvm) to install node, and npm, which will be stored in your user directory and would no longer require `sudo`.

if you really want to run npm with a specific version of node you can try something like:

`/usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js` which skips the shebang behavior

**Comment by Dmole** [comment]
@nlf
> shebang

is only checked when not specifying a runtime, and as you can see with this example:

```
sudo /usr/bin/env node --version
v17.1.0
```

env finds the correct node but npm ignores it somehow. Furthermore npm-cli exhibits the same behavior;

```
sudo /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install -g node@latest
...
npm ERR! npm does not support Node.js v10.19.0
...
```

**Comment by nlf** [comment]
it's not up to us what node we get. we don't alter your PATH, we don't ignore your `node`, and we don't have any choice how it's handled. your shell runs the `npm` cli with the `node` it chooses to and that's what we run under.

i'll give it to you there's definitely something strange going on with your system, but i can also tell you that it's not because of anything we're doing. what happens if you run `sudo /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js --version`? if that works, i suspect it's something about the package that you're installing that's causing the issue

**Comment by Dmole** [comment]
@nlf
```
sudo /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js --version
8.3.0
```

Is it possible npm is spawning a sub processes with the wrong node? or is it somehow not checking what node is in use correctly?

**Comment by Dmole** [comment]
> npm ERR! command sh -c node installArchSpecificPackage

looks like a sub processes issue to me

```
sudo /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install -g node@latest
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/node
npm ERR! command failed
npm ERR! command sh -c node installArchSpecificPackage
npm ERR! npm does not support Node.js v10.19.0
npm ERR! You should probably upgrade to a newer version of node as we
npm ERR! can't make any promises that npm will work with this version.
npm ERR! You can find the latest version at https://nodejs.org/
npm ERR! /usr/local/lib/node_modules/npm/lib/npm.js:32
npm ERR!   #unloaded = false
npm ERR!   ^
npm ERR! 
npm ERR! SyntaxError: Invalid or unexpected token
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:723:23)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:653:32)
npm ERR!     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:692:17)
npm ERR!     at require (internal/modules/cjs/helpers.js:25:18)
npm ERR!     at module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:22:15)
npm ERR!     at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:2:25)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:778:30)
npm ERR! internal/modules/cjs/loader.js:638
npm ERR!     throw err;
npm ERR!     ^
npm ERR! 
npm ERR! Error: Cannot find module 'node-linux-x64/package.json'
npm ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
npm ERR!     at Function.resolve (internal/modules/cjs/helpers.js:33:19)
npm ERR!     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/node/node_modules/node-bin-setup/index.js:18:27)
npm ERR!     at ChildProcess.emit (events.js:198:13)
npm ERR!     at maybeClose (internal/child_process.js:982:16)
npm ERR!     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-16T23_35_25_780Z-debug-0.log
```

**Comment by Dmole** [comment]
@nlf 
so it looks like npm is breaking what binary node resolves to by using sh instead of the current shell (bash) and not copying the current environment.

**Comment by nlf** [comment]
ok so there's a lot of things going on here..

first, `npm i node@latest` installs a package containing a script named `installArchSpecificPackage.js`, that script runs as part of the `preinstall` phase. `npm` does spawn a child process to run this script, and that child process _does_ inherit the current shell's environment (you can look [here](https://github.com/npm/run-script) to see how that works).

it runs the `installArchSpecificPackage.js` module, which in turn spawns _another_ child process that installs a different package [here](https://github.com/aredridel/node-bin-setup/blob/master/index.js#L12-L15).

this second child process is what's failing. _why_ it's failing is harder to determine, but i can say that doing an `npm install` from a lifecycle script like these packages do is known to be unreliable at best.. i'm frankly kind of surprised these packages work at all. i'll do a little digging to see if i can track exactly where the `PATH` is getting lost, but you've got a lot of pieces to this puzzle..
