### ISSUE TITLE
[BUG] <Error: Spawn failed>

### ISSUE THREAD

**Issue by sunmiao0301** [npm/cli#4169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When  I ran `hexo d` to deploy my GitHub Pages, It jumped out:
fatal: unable to access 'https://github.com/sunmiao0301/sunmiao0301.github.io.git/': Failed to connect to github.com port 443 after 21089 ms: Timed out
FATAL {
  err: Error: Spawn failed
      at ChildProcess.<anonymous> (D:\repo\sunmiao0301.github.io\node_modules\hexo-util\lib\spawn.js:51:21)
      at ChildProcess.emit (node:events:390:28)
      at ChildProcess.cp.emit (D:\repo\sunmiao0301.github.io\node_modules\cross-spawn\lib\enoent.js:34:29)
      at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
    code: 128
  }
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html

### Expected Behavior

What I excepted is:
INFO  Deploy done: git

### Steps To Reproduce

1. In this environment
2. With this config
3. Run 'hexo d'
4. See error: as what I write above

### Environment

- npm:8.1.2
- Node:16.13.1
- OS:windows 11
- platform:
- npm config:
```ini
; copy and paste output from `npm config ls` here
; "builtin" config from D:\nodejs\node_modules\npm\npmrc

prefix = "C:\\Users\\hfut_\\AppData\\Roaming\\npm"

; node bin location = D:\nodejs\node.exe
; cwd = D:\repo\sunmiao0301.github.io
; HOME = C:\Users\hfut_
; Run `npm config ls -l` to show all defaults.

```

**Comment by sunmiao0301** [comment]
sorry, I found the solution...
just using this command :
     $ git config --global http.proxy XXX.XXX.XXX.XXX:ZZ
XXX.XXX.XXX.XXX is the proxy server address
ZZ is the port number of the proxy server.

**Comment by dadaocao** [comment]
git config --global http.proxy XXX.XXX.XXX.XXX:ZZ  : How to find the  proxy server address
and the port number of the proxy server😭
