### ISSUE TITLE
NPM Service Unavailable

### ISSUE THREAD

**Issue by pushpender-singh-ap** [npm/cli#4172]
https://www.npmjs.com/

Location:- Uttar Pradesh, India

<img width="1440" alt="Screenshot 2021-12-15 at 9 12 30 PM" src="https://user-images.githubusercontent.com/73298854/146217614-70afac1b-7bbf-4f67-9134-e9fa937424d7.png">

**Comment by Giuzzilla** [comment]
Major outage reported in their status page: https://status.npmjs.org/

**Comment by pushpender-singh-ap** [comment]
Now Working TYSM
