### ISSUE TITLE
Unable to upgrade to latest version of npm

### ISSUE THREAD

**Issue by ty-mcfarland** [npm/cli#4173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When running the command sudo npm i -g npm@latest the following error is generated:
[2021-12-15T16_00_48_413Z-debug.log](https://github.com/npm/cli/files/7720925/2021-12-15T16_00_48_413Z-debug.log)

### Expected Behavior

The command should successfully install the latest version

### Steps To Reproduce

Run sudo npm i -g npm@latest

### Environment

npm: 7.6.0
Node: 14.15.5
OS: Mac OS 11.6.2
platform: MacBook Pro
- npm config:
```ini
; "user" config from /Users/Ty.McFarland/.npmrc

unsafe-perm = false 

; "cli" config from command line options

omit = [] 
user-agent = "npm/7.6.0 node/v14.15.5 darwin x64" 

; node bin location = /usr/local/bin/node
; cwd = /Users/Ty.McFarland
; HOME = /Users/Ty.McFarland
; Run `npm config ls -l` to show all defaults.
```

**Comment by nlf** [comment]
this was an unfortunate bug present in npm@7.6.0 (which you're currently using), there's a few ways to fix it:

## Clone this repo and use it to install a new npm

```shell
git clone https://github.com/npm/cli
cd cli
node . install -g npm@latest
```

## Use the install script

```shell
curl https://www.npmjs.com/install.sh | sh
```

**Comment by ty-mcfarland** [comment]
@nlf Thank you, the issue resolved itself after restarting my laptop and using the same command.  I apologize that I had to click the "I am using the latest npm" checkbox, the submit button is disabled unless it's checked, and my issue dealt with getting the latest npm, so I clicked it just to submit the ticket after searching.  Thanks for checking in on this!

**Comment by nlf** [comment]
no worries! that's some good feedback, i'll see if we can update our issue template to not make that mandatory. i'm glad you got this fixed!
