### ISSUE TITLE
[BUG] Exit handler never called!

### ISSUE THREAD

**Issue by Cenanmehmet** [npm/cli#4182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

![Screenshot_20211219-232329](https://user-images.githubusercontent.com/90787334/146689866-05c8cbc7-e327-44ea-a48d-a5bd676bf4ca.jpg)

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:npm install @kava-labs/javascript-sdk
- Node:
- OS:android 9.0
- platform:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```
npm install @kava-labs/javascript-sdk

**Comment by nlf** [comment]
see #417

unfortunately this type of error happens in limited resource environments, like android, fairly often. there's not much we can do with today's npm architecture to fix it.
