### ISSUE TITLE
[BUG] npm outdated doesn't produce any results

### ISSUE THREAD

**Issue by bluelephant825** [npm/cli#4183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I have a project folder containing a package.json file with dependencies, but when I type 'npm outdated' in the terminal from within the project folder, nothing happens! However, 'npm outdated --all' does produce some results, but it doesn't list the dependencies in my package.json file.

<img width="1775" alt="Screenshot 2021-12-20 at 14 18 23" src="https://user-images.githubusercontent.com/4818315/146774111-d43ef895-e1ec-4293-b469-6146a0757b64.png">

### Expected Behavior

I was expecting to see the 3 dependencies that are listed in my package.json file in my project folder.

### Steps To Reproduce

1. In this environment...
npm: 8.3.0
node: 17.3.0
OS: macOS Monterey 12.1
platform: iMac18,3
2. With this config...
```
; node bin location = /Users/odebroqueville/.nvm/versions/node/v17.3.0/bin/node
; cwd = /Users/odebroqueville/Developer/contextSearch
; HOME = /Users/odebroqueville
```
3. Run '...'
npm outdated
4. See error...
No errors and no results!

### Environment

- npm: 8.3.0
- Node: 17.3.0
- OS: macOS Monterey 12.1
- platform: iMac18,3
- npm config:
```ini
; node bin location = /Users/odebroqueville/.nvm/versions/node/v17.3.0/bin/node
; cwd = /Users/odebroqueville/Developer/contextSearch
; HOME = /Users/odebroqueville
```

**Comment by shadowspawn** [comment]
`npm outdated` lists only the direct dependencies that are outdated. If your direct dependencies are all up to date, nothing is shown, and the exit status of the command is zero. 

For example, in an up-to-date project:

```
% npm outdated
% echo $?
0
```

**Comment by bluelephant825** [comment]
Thank you for the clarifications.
