### ISSUE TITLE
[BUG] <title>npm ERR! git dep preparation failednpm ERR! command /data/data/com.termux/files/usr/bin/node /data/data/com.termux/files/usr/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/data/data/com.termux/files/home/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-runnpm ERR! npm WARN using --force Recommended protections disabled.npm ERR! npm ERR! Exit handler never called!npm ERR!npm ERR! npm ERR! This is an error with npm itself. Please report this error at:npm ERR! npm ERR!     <https://github.com/npm/cli/issues>npm ERR!npm ERR! npm ERR! A complete log of this run can be found in:npm ERR! npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2021-12-21T10_20_59_172Z-debug-0.lognpm ERR! A complete log of this run can be found in:npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2021-12-21T10_20_37_451Z-debug-0.log

### ISSUE THREAD

**Issue by Xorizn** [npm/cli#4187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

npm ERR! git dep preparation failed
npm ERR! command /data/data/com.termux/files/usr/bin/node /data/data/com.termux/files/usr/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/data/data/com.termux/files/home/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! Exit handler never called!
npm ERR!
npm ERR! npm ERR! This is an error with npm itself. Please report this error at:
npm ERR! npm ERR!     <https://github.com/npm/cli/issues>
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2021-12-21T10_20_59_172Z-debug-0.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2021-12-21T10_20_37_451Z-debug-0.log

### Expected Behavior

npm ERR! git dep preparation failed
npm ERR! command /data/data/com.termux/files/usr/bin/node /data/data/com.termux/files/usr/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/data/data/com.termux/files/home/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! Exit handler never called!
npm ERR!
npm ERR! npm ERR! This is an error with npm itself. Please report this error at:
npm ERR! npm ERR!     <https://github.com/npm/cli/issues>
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2021-12-21T10_20_59_172Z-debug-0.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2021-12-21T10_20_37_451Z-debug-0.log

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node:
- OS:
- platform:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by matkoniecz** [comment]
Note

> ; copy and paste output from `npm config ls` here
