### ISSUE TITLE
[BUG] error executing npm --version

### ISSUE THREAD

**Issue by EduApps-CDG** [npm/cli#4192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

For some reason when I execute npm with any arguments it shows the same thing in this pic:
![IMG-20211227-WA0000](https://user-images.githubusercontent.com/32627482/147444074-62116aca-aff8-441a-b196-324069fc1ce1.jpeg)

### Expected Behavior

Not throw errors

### Steps To Reproduce
1. Run `npm i -g npm`
1. Run `npm`

### Environment

- npm: latest (updated exactly now)
- Node: 17.2.0
- OS: Ubuntu 20.04
- platform: Intel Notebook
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by verbose117** [comment]
This may occur if you installed Nodejs or npm incorrectly.
Try installing `node.js` after cleaning all the node.js cache files on your machine.

**Comment by EduApps-CDG** [comment]
> This may occur if you installed Nodejs or npm incorrectly. Try installing `node.js` after cleaning all the node.js cache files on your machine.

Yeah, but I just did `npm install -g npm`. Yet, doing this solved my problem.
