### ISSUE TITLE
Exit Handler

### ISSUE THREAD

**Issue by rahulroy0322** [npm/cli#4194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

~/next $ npx create-next-app chat
Creating a new Next.js app in ~

Using npm.

Installing dependencies:
- react
- react-dom
- next

added 290 packages, and audited 291 packages in 18s

51 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Installing devDependencies:
- eslint
- eslint-config-next

npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2021-12-27T10_31_28_619Z-debug.log

Aborting installation.
  npm install --save-exact --save-dev eslint eslint-config-next has failed.

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node:
- OS:
- platform:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by ljharb** [comment]
Please fill out the issue template, including node/npm versions.

**Comment by ruyadorno** [comment]
**Closing:** please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).
