### ISSUE TITLE
Cannot find module 'F:\web\app.js[BUG] 

### ISSUE THREAD

**Issue by vinodonweb** [npm/cli#4195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

when I write in VS code terminal `npm start` it shows an error `MODULE_NOT_FOUND'` (I also attached a screenshot) I am trying many things to solve this issue but have not found any solution. please help me it has been appreciated
![error](https://user-images.githubusercontent.com/84795184/147495713-70d1b405-81cf-4dea-b9da-e7e56911f5bf.PNG)
 

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node:
- OS:
- platform:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by ljharb** [comment]
`npm start` runs the "start" script in your own package.json. If it's failing, it's an issue with your own code.

**Comment by vinodonweb** [comment]
I know that to run `npm`. But it not working. And my code is default first react  i try to `npm start`

**Comment by ljharb** [comment]
@vinod786-op what is the "start" script in your package.json? the error message implies it's referencing `app.js`, but that file doesn't exist.
