### ISSUE TITLE
`npm hook ls` duplicates hook name prefixes

### ISSUE THREAD

**Issue by Dionysusnu** [npm/cli#4201]
Hooks for scopes get a double prefix, ie `@@scope`, when shown with the `npm hook ls` command. This is due to the response from the web request already including the prefix in the `name` field, and the [following lines](https://github.com/npm/cli/blob/d8aac8448e983692cacb427e03f4688cd1b62e30/lib/commands/hook.js#L123-L132) of code then locally adding the prefix again, duplicating it.

**Comment by ashutoshdhande** [comment]
@Dionysusnu can i work on this issue? if yes any extra guidance you would like to provide

**Comment by Dionysusnu** [comment]
It appears that the hooks feature has been disabled on the server side anyways, so I wouldn't waste time on a low priority thing like this.

**Comment by Bruce-Hopkins** [comment]
If this has been disabled on the server-side, can't we close the issue?

**Comment by ljharb** [comment]
@Bruce-Hopkins it could still be used by private registries.

**Comment by Dionysusnu** [comment]
> If this has been disabled on the server-side, can't we close the issue?

To clarify, the hooks can still get created, modified, and all that around it, so the bug still exists.

However, in my testing, the actual hook configured URL was never accessed when the hook should have triggered. That's what I meant by "seemingly disabled on the server side".

**Comment by 552020** [comment]
Since this issue is tagged as 'good first issue' and since people looking for 'good first issues' are looking for good first issues that can be assigned now, maybe it would be appropriate to remove the tag.

**Comment by ljharb** [comment]
@552020 it still is one. The above comments are just folks who don’t think it’s worth the effort, but nobody from npm has agreed with that.
