### ISSUE TITLE
[BUG] npm ERR! Exit handler never called!npm ERR! This is an error with npm itself

### ISSUE THREAD

**Issue by getsettalk** [npm/cli#4203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node:
- OS:
- platform:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by nlf** [comment]
see #417 and please fill out the full issue template if you continue having problems
