### ISSUE TITLE
[BUG] npm install picks the wrong registry when installing a scoped package

### ISSUE THREAD

**Issue by thobas-dnvgl** [npm/cli#4208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I have a project depending on the 3 following packages (besides usual public packages like `react`):
* `@dnv/ui-utils` located on custom registry on Azure 
* `@veracity/js-internal` and `@veracity/vui`, private packages on npmjs.org's own registry.

This is the .npmrc file for this project:
```
@veracity:registry=https://registry.npmjs.org/
registry=https://pkgs.dev.azure.com/XXX/npm/registry/
always-auth=true
```

According to this file, all `@veracity/***` packages should be downloaded from npm's registry while ALL the other packages should be downloaded from our custom registry (which will proxy most requests to http://registry.npmjs.org anyway).
 
`npm install` fails with the following error:
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://pkgs.dev.azure.com/XXX/npm/registry/@veracity/vui/-/vui-0.3.1.tgz - NotFound
npm ERR! 404
npm ERR! 404  '@veracity/vui@https://pkgs.dev.azure.com/XXX/npm/registry/@veracity/vui/-/vui-0.3.1.tgz' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\THOBAS\AppData\Local\npm-cache\_logs\2022-01-05T14_45_42_390Z-debug.log
```

The error makes it look like it's trying to get `@veracity/vui` from our custom registry…

Even weirder if I look at the log file I see:
```
...
40 silly fetch manifest react-dom@^17.0.2
41 http fetch GET 200 https://pkgs.dev.azure.com/XXX/npm/registry/react-dom 625ms (cache updated)
42 silly fetch manifest @veracity/vui@^0.3.1
43 http fetch GET 200 https://registry.npmjs.org/@veracity%2fvui 1565ms (cache updated)
44 silly fetch manifest react-focus-lock@^2.7.1
45 http fetch GET 200 https://pkgs.dev.azure.com/XXX/npm/registry/react-focus-lock 162ms (cache updated)
...
```

My `.npmrc` file in my home directory has the right tokens for both registries. Running `npm info @veracity/ui` gives the right information, not a 404, it's just the installation that fails. WTH?

I am using Windows 10, Node.JS v16.13.1 and npm 8.1.2.

### Expected Behavior

It should be able to fetch `@veracity/vui` from npm's own registry. I just tried running `yarn` with `v1.22.17` and it worked.

### Steps To Reproduce

Well, you would need a repository with packages from a private registry and packages that are private on npm's own/default registry to reproduce this error.

### Environment

- npm: 8.1.2
- Node.js: v16.13.1
- OS Name: Windows 10
- System Model Name: 
- npm config:
```ini
; "builtin" config from C:\Program Files\nodejs\node_modules\npm\npmrc

prefix = "C:\\Users\\THOBAS\\AppData\\Roaming\\npm" 

; "user" config from C:\Users\THOBAS\.npmrc

//pkgs.dev.azure.com/XXX/npm/registry/:_password = (protected) 
//pkgs.dev.azure.com/XXX/npm/registry/:email = "not-used@example.com"
//pkgs.dev.azure.com/XXX/npm/registry/:username = "VssSessionToken"     
//registry.npmjs.org/:_authToken = (protected) 
email = "not-used@example.com" 
init-author-email = "Thomas.Bassetto@dnv.com" 
init-author-name = "Thomas Bassetto" 

; "project" config from C:\Users\THOBAS\Code\CAS-Account-Web\src\veracity.account.web.frontend\.npmrc

@veracity:registry = "https://registry.npmjs.org/"
always-auth = true
registry = "https://pkgs.dev.azure.com/XXX/npm/registry/"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\THOBAS\Code\CAS-Account-Web\src\veracity.account.web.frontend
; HOME = C:\Users\THOBAS
; Run `npm config ls -l` to show all defaults.
```

**Comment by webketje** [comment]
Related and also encountered on `npm 7.21.0`: https://gitlab.com/gitterHQ/webapp/-/issues/2818

**Comment by hexxone** [comment]
So after a lot of struggle with the same problem, I finally figured out a working `.nmprc` config and put it in a bash script.
`Node v17.4.0 & npm 8.4.0`

```
#!/bin/bash
CI_SERVER_HOST=gitlab.mydomain.com
CI_PROJECT_ID=<num>
CI_JOB_TOKEN=<read_token>

echo "registry=https://registry.npmjs.org/" > .npmrc
echo "@mycompany:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" >> .npmrc
echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
echo "always-auth=true" >> .npmrc

npm install --save @mycompany/core-package
```

or for windows powershell:
```
$env:CI_SERVER_HOST="gitlab.mydomain.com"
$env:CI_PROJECT_ID="<num>"
$env:CI_JOB_TOKEN="<read_token>"

echo "registry=https://registry.npmjs.org/" > .npmrc
echo "@mycomp:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" >> .npmrc
echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
echo "always-auth=true" >> .npmrc

npm install --save @mycomp/core-package
```

P.S. check for other interferring `.npmrc` files in the appdata npm `debug.log`..
they will look like
```
5 timing config:load:file:C:\Users\Redacted\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 2ms
...
9 timing config:load:file:D:\Proj\test-npm\.npmrc Completed in 0ms
...
13 timing config:load:file:C:\Users\Redacted\AppData\Roaming\npm\etc\npmrc Completed in 0ms
```

... and finally the long awaited message:
`added 1 package in 960ms`

hope this helps someone. Cheers

**Comment by elranu** [comment]
If you fix this, it will also be awesome, if you don't find a scoped private package on a private registry, don't throw an error. Try to find it in the public npm registry. There is no way to handle when a scope @company, has public and private packages.

**Comment by ljharb** [comment]
@elranu a company never should, as that leaves them open to a supply chain attack if the public scope is ever compromised. It’s far better to keep private and public packages on a different scope.

**Comment by wraithgar** [comment]
This appears to have been fixed.

```sh
~/D/n/s/registry $ cat package.json 
{
  "name": "registry",
  "version": "1.0.0",
  "dependencies": {
    "@gar/promisify": "^1.1.3",
    "@wraithgar/gh-registry-test": "^1.0.3"
  }
}
~/D/n/s/registry $ npm i

added 2 packages in 954ms
~/D/n/s/registry $ npm config list
; "user" config from /Users/wraithgar/.npmrc

@gar:registry = "https://registry.npmjs.org" 
//npm.pkg.github.com/:_authToken = (protected) 
//registry.npmjs.org/:_authToken = (protected) 
registry = "https://npm.pkg.github.com/" 
```

**Comment by antoineNRB** [comment]
Looks like the issue reappeared with node 16.18.0 (npm v8.19.2)

**Comment by antoineNRB** [comment]
my bad, it was because of my .npmrc `@OWNER:registry=https://npm.pkg.github.com` I wasn't specifying the `@OWNER` everythings is fine now

**Comment by EricBuist** [comment]
Then what's the solution? Seems to work one day and the next day, my bad something wrong with .npmrc? I have a private-scoped package, hosted at <private_npm_repository>. That package has a public dependency to google-protobuf, and NPM, instead of searching the public registry, tries to find the public package in <private_npm_repository> and fails. Arguing that this is not doable because of poor supply chain analogies makes no sense to me and won't help going forward. That works with Node 18.16.0 but fails with Node 16.20.0, both running NPM 9.6.5. Any attempt to update Node version causes failures in my private package so it will takes a lot of time to iron these out.

**Comment by Owez** [comment]
It might be a caching issue if packages where previously installed with a different registry, my first delete of `node_modules` and the lockfile didn't work, but the second time did
