### ISSUE TITLE
[BUG] Pressing Ctrl+C exits running scripts anyways, Terminate batch job (Y/N)? prompt does not skip it on 'N' response.

### ISSUE THREAD

**Issue by Git-Harshit** [npm/cli#4209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [ ] I am using the latest npm

### Current Behavior

I am using the latest npm LTS (Long Term Support) version v7.20.3 at the time of reporting this issue.

Normally, when we press _Ctrl + C_ keyboard shortcut to terminate our running program, it prompts us with "Terminate batch job (Y/N)?", before actually stopping it. However, even when the response entered is a no (tried with entering 'n', 'no', 'N', 'No', 'NO' to this prompt), it still exits the running script. This is an undesired response for the case of denial to this prompt, as a non-termination should mean that the user has changed their mind on being prompted, and would like to keep the script running.  

This behavior has been observed on Windows 10 Powershell. A snapshot of this has been attached:
![Non-Termination Error Highlighted](https://user-images.githubusercontent.com/57865187/148351978-2dcb4cf1-7def-414f-8490-de759679c458.PNG)

### Expected Behavior

On pressing _Ctrl + C_ keyboard shortcut, when "Terminate Batch Job (Y/N)?" prompt appears, it should ideally terminate the script only upon a positive confirmation (with case-insensitive responses like: 'y', 'yes'), and on a negation with responses like 'n'/'no', the termination of program must not be done, since it has prompted for the termination and the choice must still remain over to user.

i.e., 
`Terminate batch job (Y/N)?` should not terminate the script and continue running it in case of 'no' as a response.

### Steps To Reproduce

1. Run your npm project (with `npm start`)
2. As the script gets successfully running, try to exit the running script with _Ctrl + C_ keyboard shortcut.
3. As a prompt appears, "Terminate batch job (Y/N)?", respond with typing 'n' or 'no' in terminal.
Notice that the script still terminates, which is undesired and is exactly why this issue has been raised.

### Environment

- npm: 7.20.3
- Node.js: 16.13.1
- OS Name: Windows 10 Home (20H2 Edition)
- System Model Name: HP Pavilion Notebook
- npm config:
```ini
; "builtin" config from C:\Users\Devil's Lair\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\Devil's Lair\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\Devil's Lair\Desktop\Temp\Swiggy IPP Backend Round 2 Case Study\food-app
; HOME = C:\Users\Devil's Lair
; Run `npm config ls -l` to show all defaults.
```

**Comment by ljharb** [comment]
npm start just runs your own script. Does *that* support control-c?

**Comment by ljharb** [comment]
Also, npm has no LTS and v7 is EOL. Try v8.

**Comment by verbose117** [comment]
I have also came across with that issue sometimes, but I didn't bother because I thought it was a typo 👀

**Comment by Git-Harshit** [comment]
> npm start just runs your own script. Does _that_ support control-c?

No, that Control+C isn't handled within the running script, but I guess npm does handle it since it captures the _Control+C_ keyboard combination and prompts for "Terminate batch job (Y/N)?" following it, which gets exit on any input either beginning with a 'y' (which is desired) or 'n' (which isn't desired) or even a repeated _Control+C_ key combination.

**Comment by fritzy** [comment]
"Terminate batch job" is a prompt that the windows command prompt gives. SIGINT is not something that npm handles when running scripts.

**Comment by SlugFiller** [comment]
The prompt is actually triggered in `npm.cmd` after `npm` itself has already exited. It can be completely suppressed by making the following change to the last line in `npm.cmd`:
```cmd
endLocal & goto #_undefined_# 2>NUL || title %COMSPEC% & "%NODE_EXE%" "%NPM_CLI_JS%" %*
```
(Note: There are other ways to achieve this, but this is the method used by NPM's own [cmd-shim](https://github.com/npm/cmd-shim/blob/7b2f56ff7f8400d7322dbab92eead8ff0a69cd70/lib/index.js#L115))
