### ISSUE TITLE
[BUG] Require wrong version of peer dependency in monorepo

### ISSUE THREAD

**Issue by maksimr** [npm/cli#4210]
STR:

- Create a monorepo `foo` | `mkdir foo && cd foo && npm init -y .`
- Add workspace `a` | `npm init -y -w ./packages/a`
- Add workspace `b` | `npm init -y -w ./packages/b`
- Add workspace `c` | `npm init -y -w ./packages/c`
- Add `c` as dependency `a` and `b` using `file` version
- Install react@17.x as dependency of `a` |  `npm install react@17 -w a`
- Install react@16.x as dependency of `b` |  `npm install react@16 -w b`
- Set react as `peerDependency` of `c` | `"peerDependencies": { "react": "16.x.x || 17.x.x" },`
- Add index.js to `c` | `echo "console.log(require('react').version);" > ./packages/c/index.js`
- Add index.js to `a` | `echo "require('c');" > ./packages/a/index.js`
- Add index.js to `b` | `echo "require('c');" > ./packages/b/index.js`
- Add `test` script to `a` and `b` | `"scripts": { "test": "node ./index.js" },`
- Run `npm test` for all workspaces `npm test --ws`

ER: 
```
> a@1.0.0 test
> node ./index.js

17.x.x

> b@1.0.0 test
> node ./index.js

16.x.x ✅
```

AR:
```
> a@1.0.0 test
> node ./index.js

17.x.x

> b@1.0.0 test
> node ./index.js

17.x.x ❌
```

Test repository - https://github.com/maksimr/npm-4210
```
.
├── package-lock.json
├── package.json
└── packages
    ├── a
    │   ├── index.js
    │   └── package.json
    ├── b
    │   ├── index.js
    │   └── package.json
    └── c
        ├── index.js
        └── package.json

```

node@v16.13.1
npm@8.1.2

**Comment by cyberalien** [comment]
You have a typo (should be `react@16`):

> * Install [react@16.x](mailto:react@16.x) as dependency of `b` |  `npm install react@17 -w b`

Though bug is valid, it is just a typo in instructions. I'm getting exactly the same issue when trying to use both Vue 2 and Vue 3 in the same monorepo. Looks like `require()` is broken if used in a package installed outside of current workspace (in root `node_modules` or another package in same monorepo as in this example): it checks root `node_modules` first instead of current workspace.

**Comment by maksimr** [comment]
@cyberalien thanks, fixed

**Comment by fritzy** [comment]
@maksimr Please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).

I don't know what STR, AR, and ER are. Please re-open this issue with the template.
