### ISSUE TITLE
npm publish error message is still confusing when not logged in

### ISSUE THREAD

**Issue by GrosSacASac** [npm/cli#4212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

npm publish
npm notice 
npm notice 📦  x@a.b.c
npm notice === Tarball Contents ===
npm notice....
npm notice === Tarball Details ===
npm notice ...
npm notice total files:   39
npm notice 
npm notice Publishing to https://registry.npmjs.org/
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/dom99 - Not found
npm ERR! 404
npm ERR! 404  ' x@a.b.c' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     azerersr.log

### Expected Behavior

please login

### Steps To Reproduce

1. In this environment... win10
2. With this config... (not logged in)
3. Run '...' npm publish
4. See error... (confusing message see above)

### Environment

- npm: 8.3.0
- Node.js: 17.3

**Comment by broofa** [comment]
Landed here after getting the same "[package] is not in this registry." error when trying to do `npm publish`.    It was not at all obvious from the error that I needed to do`npm login` to fix the issue.   (I actually thought I was authenticated.)

This is on latest MacOS, Node 16, NPM 8.10.0.

**Comment by lukekarrys** [comment]
`npm` now gives a nicer error message when not authed:

```
npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in to https://registry.npmjs.org/
npm ERR! need auth You need to authorize this machine using `npm adduser`
```
