### ISSUE TITLE
[BUG] <the package-lock.json in workspaces module dosen't work>

### ISSUE THREAD

**Issue by lgh757079506** [npm/cli#4217]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

package.json
package-lock.json
|----workspaces
       |----module-a
              |----package.json
              |----package-lock.json
A dependency x(1.0.0) in the root package-lock.json, at the same time, the dependency x(1.1.0) in the module-a's package-lock.json, when i execute the `npm install`, module-a's package-lock.json dosen't work, it will install the version in root package-lock.json. I don't know is this normal or a bug

### Expected Behavior

the dependencies in workspaces'module should be installed by it's self package-lock.json

### Steps To Reproduce

1. new a project x, write `lodash: ^4.0.0` to root package.json
2. new another project y, write `lodash: ^3.0.0` to root package.json,then execute `npm install`,now there is a package-lock.json in this project(Let us suppose lodash version: 3.1.1), then delete the node_modules
3. copy the project y to the root project(x)'s workspaces, and declare workspaces
4. execute `npm install`, y's package-lock.json dosen't work, and then there is package-lock.json in project x, and it includes the dependency lodash with two version(4.x.x and 3.7.1) , but not the version(3.1.1) in y's package-lock.json

### Environment

- npm: 6.14.13
- Node.js: 14.17.0
- OS Name: windows10
- System Model Name: windows pc
- npm config: 
```ini
; cli configs                                                      
metrics-registry = "xxxxxxxxxxxxxxxxxx"
scope = ""                                                         
user-agent = "npm/6.14.13 node/v14.17.0 win32 x64"                 
                                                                   
; userconfig C:\Users\xxxx\.npmrc                                
@xxx:registry = "xxxxxxxxxxxxx"
registry = "xxx"        
                                                                   
; builtin config undefined                                         
prefix = "C:\\Users\\xxxxx\\AppData\\Roaming\\npm"                
                                                                                      
```

**Comment by ruyadorno** [comment]
Hi @lgh757079506 workspaces support is not available on npm version 6. It was first release as part of npm version 7. Please refer to the docs if you need more help: https://docs.npmjs.com/cli/v7/using-npm/workspaces
