### ISSUE TITLE
[BUG] `npm init / exec` options forwarding not working

### ISSUE THREAD

**Issue by ambrauer** [npm/cli#4220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

According do docs for v8, options forwarding should be working:
https://docs.npmjs.com/cli/v8/commands/npm-init#forwarding-additional-options

However, this doesn't seem to be the case. For example, the following commands don't properly create a React app with typescript:
```
npm init react-app -y -- my-app --template typescript
npm exec -y -- create-react-app my-app --template typescript
```

while npx does:
```
npx create-react-app my-app --template typescript
```

This is not an issue with npm v6.

### Expected Behavior

I expect options forwarding to work for `npm init` and `npm exec` the same way it works for `npx` and worked previously in v6.

### Steps To Reproduce

1. Install npm 8.3.0 on Windows
2. Run `npm init react-app -y -- my-app --template typescript`
3. The resulting React app is not typescript. In the console output, you should see for example "We detected TypeScript in your project".

### Environment

- npm: 8.3.0
- Node.js: 16.13.1
- OS Name: Windows 10 (Version 1909)
- System Model Name: HP ZBook
- npm config:
```ini
; "user" config from C:\Users\adab\.npmrc

//registry.npmjs.org/:_authToken = (protected)
strict-ssl = true

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\WIP\_TEMP
; HOME = C:\Users\adab
; Run `npm config ls -l` to show all defaults.
```

**Comment by wraithgar** [comment]
This appears to be working in `npm@8.16.0`

```sh
npm init react-app -y -- my-app --template typescript
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.

Creating a new React app in /Users/wraithgar/Development/npm/scratch/init/my-app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template-typescript...


added 1396 packages in 35s

Initialized a git repository.

Installing template dependencies using npm...
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated

added 39 packages, and changed 1 package in 4s

We detected TypeScript in your project (src/App.test.tsx) and created a tsconfig.json file for you.
```

**Comment by vobu** [comment]
observing similar behavior: forwarding additional options works _until_ `v18.6.0` - all versions after that seem to have a different (or broken?) forwarding behavior.
This can be tested with `create-wdi5` package (that I maintain):
✅ npm `v18.6.0`: `$> npm init wdi5 -- --ts` → triggers the desired process via the `ts` flag
❗ npm `v18.7.0`: `$> npm init wdi5 -- --ts` → triggers a different, namely the standard process; but it should trigger the `ts` flagged process
❗npm `v18.8.0`: `$> npm init wdi5 -- --ts` → triggers a different, namely the standard process; but it should trigger the `ts` flagged process
❗npm `v18.9.2`: `$> npm init wdi5 -- --ts` → triggers a different, namely the standard process; but it should trigger the `ts` flagged process

all of the above with node `v18.10.0` on macOS with `zsh`.
funny enough, for all of the above npm versions, the target command `npm exec -- --create-wdi5 --ts` works as desired!

can this issue please be reopened?
