### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by aboongm** [npm/cli#4224]
When I wrote  "npx create-react-app dojo-blog" terminal, it's not able to create the react packages and is returning 

_npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hp\AppData\Local\npm-cache\_logs\2022-01-08T14_25_30_526Z-debug.log

Aborting installation.
  npm install --no-audit --save --save-exact --loglevel error react react-dom react-scripts cra-template has failed.

Deleting generated file... package.json
Deleting dojo-blog/ from C:\Users\hp\OneDrive\Desktop\Essential Skills\ReactJs\tuts
Done._

Prior to this I have :
"npx clear-npx-cache" and 
"npm cache clean --force" also.

This is the debug log generated:
_0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\hp\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'install',
0 verbose cli   '--no-audit',
0 verbose cli   '--save',
0 verbose cli   '--save-exact',
0 verbose cli   '--loglevel',
0 verbose cli   'error',
0 verbose cli   'react',
0 verbose cli   'react-dom',
0 verbose cli   'react-scripts',
0 verbose cli   'cra-template'
0 verbose cli ]
1 info using npm@7.8.0
2 info using node@v14.16.0
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:C:\Users\hp\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 7ms
6 timing config:load:builtin Completed in 8ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:C:\Users\hp\OneDrive\Desktop\Essential Skills\ReactJs\tuts\dojo-blog\.npmrc Completed in 1ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:C:\Users\hp\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\hp\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setEnvs Completed in 0ms
17 timing config:load Completed in 15ms
18 timing npm:load:configload Completed in 15ms
19 timing npm:load:setTitle Completed in 0ms
20 timing npm:load:setupLog Completed in 2ms
21 timing npm:load:cleanupLog Completed in 2ms
22 timing npm:load:configScope Completed in 0ms
23 timing npm:load:projectScope Completed in 1ms
24 timing npm:load Completed in 22ms
25 timing config:load:flatten Completed in 2ms
26 timing arborist:ctor Completed in 1ms
27 timing arborist:ctor Completed in 0ms
28 timing idealTree:init Completed in 15ms
29 timing idealTree:userRequests Completed in 3ms
30 silly idealTree buildDeps
31 silly fetch manifest react@*
32 http fetch GET 304 https://registry.npmjs.org/react 2115ms (from cache)
33 silly fetch manifest react-dom@*
34 http fetch GET 304 https://registry.npmjs.org/react-dom 399ms (from cache)
35 silly fetch manifest react-scripts@*
36 http fetch GET 304 https://registry.npmjs.org/react-scripts 425ms (from cache)
37 silly fetch manifest typescript@^3.2.1 || ^4
38 http fetch GET 304 https://registry.npmjs.org/typescript 274ms (from cache)
39 silly fetch manifest cra-template@*
40 http fetch GET 304 https://registry.npmjs.org/cra-template 591ms (from cache)
41 silly placeDep ROOT cra-template@1.1.3 OK for: dojo-blog@0.1.0 want: *
42 silly placeDep ROOT react@17.0.2 OK for: dojo-blog@0.1.0 want: *
43 silly placeDep ROOT react-dom@17.0.2 OK for: dojo-blog@0.1.0 want: *
44 silly placeDep ROOT react-scripts@5.0.0 OK for: dojo-blog@0.1.0 want: *
45 silly fetch manifest loose-envify@^1.1.0
46 silly fetch manifest object-assign@^4.1.1
47 silly fetch manifest scheduler@^0.20.2
48 silly fetch manifest fsevents@^2.3.2
49 silly fetch manifest @babel/core@^7.16.0
50 silly fetch manifest @pmmmwh/react-refresh-webpack-plugin@^0.5.3
51 silly fetch manifest @svgr/webpack@^5.5.0
52 silly fetch manifest babel-jest@^27.4.2
53 silly fetch manifest babel-loader@^8.2.3
54 silly fetch manifest babel-plugin-named-asset-import@^0.3.8
55 silly fetch manifest babel-preset-react-app@^10.0.1
56 silly fetch manifest bfj@^7.0.2
57 silly fetch manifest browserslist@^4.18.1
58 silly fetch manifest camelcase@^6.2.1
59 silly fetch manifest case-sensitive-paths-webpack-plugin@^2.4.0
60 silly fetch manifest css-loader@^6.5.1
61 silly fetch manifest css-minimizer-webpack-plugin@^3.2.0
62 silly fetch manifest dotenv@^10.0.0
63 silly fetch manifest dotenv-expand@^5.1.0
64 silly fetch manifest eslint@^8.3.0
65 silly fetch manifest eslint-config-react-app@^7.0.0
66 silly fetch manifest eslint-webpack-plugin@^3.1.1
67 silly fetch manifest file-loader@^6.2.0
68 silly fetch manifest fs-extra@^10.0.0
69 silly fetch manifest html-webpack-plugin@^5.5.0
70 silly fetch manifest identity-obj-proxy@^3.0.0
71 silly fetch manifest jest@^27.4.3
72 silly fetch manifest jest-resolve@^27.4.2
73 silly fetch manifest jest-watch-typeahead@^1.0.0
74 silly fetch manifest mini-css-extract-plugin@^2.4.5
75 silly fetch manifest postcss@^8.4.4
76 silly fetch manifest postcss-flexbugs-fixes@^5.0.2
77 silly fetch manifest postcss-loader@^6.2.1
78 silly fetch manifest postcss-normalize@^10.0.1
79 silly fetch manifest postcss-preset-env@^7.0.1
80 silly fetch manifest prompts@^2.4.2
81 silly fetch manifest react-app-polyfill@^3.0.0
82 silly fetch manifest react-dev-utils@^12.0.0
83 silly fetch manifest react-refresh@^0.11.0
84 silly fetch manifest resolve@^1.20.0
85 silly fetch manifest resolve-url-loader@^4.0.0
86 silly fetch manifest sass-loader@^12.3.0
87 silly fetch manifest semver@^7.3.5
88 silly fetch manifest source-map-loader@^3.0.0
89 silly fetch manifest style-loader@^3.3.1
90 silly fetch manifest tailwindcss@^3.0.2
91 silly fetch manifest terser-webpack-plugin@^5.2.5
92 silly fetch manifest webpack@^5.64.4
93 silly fetch manifest webpack-dev-server@^4.6.0
94 silly fetch manifest webpack-manifest-plugin@^4.0.2
95 silly fetch manifest workbox-webpack-plugin@^6.4.1
96 http fetch GET 200 https://registry.npmjs.org/bfj 47214ms
97 http fetch GET 200 https://registry.npmjs.org/jest-resolve 50056ms
98 http fetch GET 200 https://registry.npmjs.org/scheduler 52991ms
99 http fetch GET 200 https://registry.npmjs.org/mini-css-extract-plugin 56486ms
100 http fetch GET 200 https://registry.npmjs.org/postcss-flexbugs-fixes 60946ms
101 http fetch GET 200 https://registry.npmjs.org/@pmmmwh%2freact-refresh-webpack-plugin 64684ms
102 http fetch GET 200 https://registry.npmjs.org/file-loader 66814ms
103 http fetch GET 200 https://registry.npmjs.org/postcss-loader 68663ms
104 http fetch GET 200 https://registry.npmjs.org/postcss-normalize 70020ms
105 http fetch GET 200 https://registry.npmjs.org/prompts 72413ms
106 http fetch GET 200 https://registry.npmjs.org/postcss 73456ms
107 http fetch GET 200 https://registry.npmjs.org/eslint 74865ms
108 http fetch GET 200 https://registry.npmjs.org/resolve-url-loader 76251ms
109 http fetch GET 200 https://registry.npmjs.org/react-app-polyfill 76389ms
110 http fetch GET 200 https://registry.npmjs.org/postcss-preset-env 76397ms
111 http fetch GET 200 https://registry.npmjs.org/resolve 76847ms
112 http fetch GET 200 https://registry.npmjs.org/source-map-loader 79039ms
113 http fetch GET 200 https://registry.npmjs.org/style-loader 79588ms
114 http fetch GET 200 https://registry.npmjs.org/browserslist 84403ms
115 http fetch GET 200 https://registry.npmjs.org/babel-preset-react-app 111516ms
116 http fetch GET 304 https://registry.npmjs.org/css-minimizer-webpack-plugin 112654ms (from cache)
117 http fetch GET 304 https://registry.npmjs.org/fs-extra 115290ms (from cache)
118 http fetch GET 304 https://registry.npmjs.org/dotenv 116465ms (from cache)
119 http fetch GET 304 https://registry.npmjs.org/loose-envify 116535ms (from cache)
120 http fetch GET 304 https://registry.npmjs.org/eslint-webpack-plugin 117466ms (from cache)
121 http fetch GET 304 https://registry.npmjs.org/dotenv-expand 117475ms (from cache)
122 http fetch GET 304 https://registry.npmjs.org/camelcase 119377ms (from cache)
123 http fetch GET 304 https://registry.npmjs.org/case-sensitive-paths-webpack-plugin 124626ms (from cache)
124 http fetch GET 304 https://registry.npmjs.org/identity-obj-proxy 127078ms (from cache)
125 http fetch GET 304 https://registry.npmjs.org/fsevents 128178ms (from cache)
126 http fetch GET 200 https://registry.npmjs.org/webpack-dev-server 128787ms
127 http fetch GET 200 https://registry.npmjs.org/workbox-webpack-plugin 128887ms attempt #2
128 http fetch GET 304 https://registry.npmjs.org/object-assign 134248ms (from cache)
129 warn registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ERR_SOCKET_TIMEOUT: request to https://registry.npmjs.org/babel-loader failed, reason: Socket timeout
130 warn registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
131 http fetch GET 200 https://registry.npmjs.org/@svgr%2fwebpack 135396ms (from cache)
132 http fetch GET 200 https://registry.npmjs.org/babel-loader 135405ms (from cache)
133 http fetch GET 200 https://registry.npmjs.org/jest 141680ms
134 http fetch GET 200 https://registry.npmjs.org/html-webpack-plugin 153938ms
135 http fetch GET 200 https://registry.npmjs.org/eslint-config-react-app 194577ms
136 http fetch GET 200 https://registry.npmjs.org/react-refresh 219520ms
137 http fetch GET 200 https://registry.npmjs.org/webpack 268231ms
138 http fetch GET 200 https://registry.npmjs.org/@babel%2fcore 280088ms
139 http fetch GET 200 https://registry.npmjs.org/babel-jest 320390ms
140 http fetch GET 200 https://registry.npmjs.org/babel-plugin-named-asset-import 335197ms
141 http fetch GET 200 https://registry.npmjs.org/css-loader 411280ms
142 timing npm Completed in 416291ms
143 error cb() never called!
144 error This is an error with npm itself. Please report this error at:
145 error <https://github.com/npm/cli/issues>_

**Comment by darcyclarke** [comment]
**Closing:** this error can arise for a number of reasons; Please read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) & refile an issue with as much information as possible if you're able to **consistently reproduce** this error.

**Comment by aboongm** [comment]
> **Closing:** this error can arise for a number of reasons; Please read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) & refile an issue with as much information as possible if you're able to **consistently reproduce** this error.

I found a solution and it's working. What I did is, to uninstall the node.js 14.17.6 installation and install the latest node.js 16.13.2. Also, I manually remove the npm-cache from AppData as, during the uninstallation, this folder was not deleted.
