### ISSUE TITLE
Getting an error cb() never called

### ISSUE THREAD

**Issue by darcyclarke** [npm/cli#423]
Original bug ticket: [https://npm.community/t/9499](https://npm.community/t/9499)
      Originally filed: 2019-08-15T18:59:34.080Z

---

From original issue: https://npm.community/t/9499
Debug log: n/a
Action triggered: `npm install`

Platform Info:
```
$ npm --versions
{
  npm: '6.10.2',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  llhttp: '1.1.4',
  modules: '72',
  napi: '4',
  nghttp2: '1.39.1',
  node: '12.8.0',
  openssl: '1.1.1c',
  tz: '2019a',
  unicode: '12.1',
  uv: '1.30.1',
  v8: '7.5.288.22-node.16',
  zlib: '1.2.11'
}
$ node -p process.platform
win32
```

Additional information:
Seems related, but signs of integrity error are present (which could be root cause)

**Comment by mikemimik** [comment]
Duplicate issue; aggregating into https://github.com/npm/cli/issues/417.

**Comment by ezechiaskumbu77** [comment]
I am facing the same problem when installing node js in my angular project

**Comment by ezechiaskumbu77** [comment]
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Local\npm-cache\_logs\2021-06-22T11_54_05_253Z-debug.log
