### ISSUE TITLE
[BUG] saat saya menginstall node modul tidak bisa

### ISSUE THREAD

**Issue by Fahrilahmad** [npm/cli#4235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

saat saya menginstall node modul 

### Expected Behavior

Agar bisa seterah di tanggani

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...
5. NPM ERR

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by ruyadorno** [comment]
**Closing:** please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).
