### ISSUE TITLE
[QUESTION] Are npm hooks working?

### ISSUE THREAD

**Issue by smashah** [npm/cli#4247]
# What / Why

I have been trying to set npm hook all day but unfortunately none of them ever get triggered! I have been publishing many patches for smaller libs to get these to trigger - but nothing. It would be useful if there is some updated documentation or something regarding npm hook. Will this only work if I have a paid npm account? If so shouldn't that be mentioned when setting it via the CLI?

![CleanShot 2021-09-24 at 20 29 13@2x](https://user-images.githubusercontent.com/5903821/134730013-a7b461e8-56f1-4294-ac88-18b8a7315b52.png)

## Where

* n/a

## Who

* n/a

## References

* n/a

**Comment by Beace** [comment]
I have the same problem. I used https://webhook.site/ to test npm hook, but nothing happened.

**Comment by smashah** [comment]
@BeAce I felt like i was being gaslit by the docs when I was trying to implement this. It's so hard to even look this up on google because it just returns results to other libs :D I've given up now.

**Comment by Beace** [comment]
@smashah Are you a paying user? I read NPM's blog. It says if you have a paid individual or organizational NPM account, you can start using hooks right now.  See  https://blog.npmjs.org/post/145260155635/introducing-hooks-get-notifications-of-npm.html. I want to try to pay and see if it works.

**Comment by smashah** [comment]
My original post explores this possiblity. If that was the case then it should've been mentioned as an error message when setting the hook. In the blog it implies that it will be available to everyone later on and that blog was posted in 2016. 

If it was a problem of paying for it then the least someone at npm could do would be to reply to us confirming that.

So I'm not going to try it, if you do please let me know if it starts working for you.

**Comment by MylesBorins** [comment]
These should be fixed now, PTAL

**Comment by smashah** [comment]
Exciting! Can't wait to try it out
