### ISSUE TITLE
[QUESTION](libnpmpublish) Migration from v3 to v4

### ISSUE THREAD

**Issue by wesleytodd** [npm/cli#4248]
# What / Why

Looks like the `CHANGELOG.md` was not updated when 4.x was released, and from reading the new source it looks like the signature changed and now expects the tarball pack do be done outside of this lib.  Are there docs on a migration for folks using the v3 version? Additionally is there any way to leverage npm lib's to replicate the old behavior where starting from a directory and a `package.json` we can get the proper tarball (by proper I mean exactly like npm creates it) outside of the cli? Maybe `libnpmpack`?

## Where

* n/a

## Who

* @nlf 
* @wraithgar 
* @ruyadorno 

## References

* n/a

**Comment by wraithgar** [comment]
There aren't docs per se but you can see how the `pack` and `publish` commands do things.  Specifically `pack` is calling directly out to `libnpmpack`  That's all you should need to generate the tarball that `libnpmpublish` is expecting, s your assumption there was correct.

Both modules expect the same options so migrating shouldn't be anything breaking from the view of changing which one you call to generate the tarball.

For reference this is the PR that had the cli update to v4: https://github.com/npm/cli/pull/2074
And this is the PR for libnpmpublish that changed the function signature: https://github.com/npm/libnpmpublish/pull/16
