### ISSUE TITLE
issue when installing plotly, got: "npm ERR! cb() never called!"

### ISSUE THREAD

**Issue by darcyclarke** [npm/cli#425]
Original bug ticket: [https://npm.community/t/9422](https://npm.community/t/9422)
      Originally filed: 2019-08-11T05:48:47.639Z

---

From original issue: https://npm.community/t/9422
Debug log: n/a
Action triggered: `npm install --save plotly.js`

Platform info:
```
$ npm --versions
npm --versions
{ npm: '6.9.0',
  ares: '1.14.0',
  cldr: '32.0.1',
  http_parser: '2.8.1',
  icu: '60.2',
  modules: '57',
  napi: '3',
  nghttp2: '1.32.1',
  node: '8.11.4',
  openssl: '1.0.2n',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.22.0',
  v8: '6.2.414.54',
  zlib: '1.2.11' }

$ node -p process.platform
linux
```

Additional information:
> Unhandled rejection Error: EACCES: permission denied, mkdir '/home/ravn/.npm/_cacache/content-v2/sha1/e0/b1'

Was present in the output

**Comment by mikemimik** [comment]
Duplicate issue; aggregating into https://github.com/npm/cli/issues/417.
