### ISSUE TITLE
[BUG] npm install produces output even with `--no-progress --silent`

### ISSUE THREAD

**Issue by jfirebaugh** [npm/cli#4259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`npm install` produces output even with `--no-progress --silent`. For example, with the repro steps below, intermediate output includes states like:

⸨#########⠂⠂⠂⠂⠂⠂⠂⠂⠂⸩ ⠏ reify:@types/yargs: timing reify:loadBundles Completed in 0ms

and:

⸨##################⸩ ⠋ reify:typescript: timing reifyNode:node_modules/puppeteer Completed 

This appears to be a regression from a previous version (last tested with 6.14.15).

### Expected Behavior

npm is completely silent when given `--no-progress --silent`.

### Steps To Reproduce

Use the following package.json:

```
{
  "name": "npm-silent",
  "dependencies": {
    "@types/yargs": "^17.0.7",
    "p-defer": "^3.0.0",
    "puppeteer": "^12.0.1",
    "ts-node": "^10.4.0",
    "typescript": "^4.5.2",
    "yargs": "^17.3.0"
  }
}
```

Run `npm install --no-save --no-progress --no-audit --quiet --silent`.

### Environment

- npm: 8.3.0
- Node.js: v16.13.1
- OS Name: macOS
- System Model Name:
- npm config:
```ini
; node bin location = /usr/local/bin/node
; cwd = /Users/john/figma/npm-silent
; HOME = /Users/john
; Run `npm config ls -l` to show all defaults.
```

**Comment by wraithgar** [comment]
@lukekarrys [fixed this](https://github.com/npm/cli/pull/4644)!
