### ISSUE TITLE
[BUG](arborist) should not remove global node_modules

### ISSUE THREAD

**Issue by mingc00** [npm/cli#4274]
# What / Why

For switching different Node.js version, we use symlink for global node_modules.

```bash
$ ls -ld /usr/local/lib/node_modules
/usr/local/lib/node_modules -> /var/packages/Node.js_v16/var/node_modules
```

The global module directory and npm itself is removed after installing global module.

```bash
$ npm install -g pino-pretty
npm WARN reify Removing non-directory /usr/local/lib/node_modules
```

The behavior have been changed from https://github.com/npm/arborist/commit/f2b0ceebfe94123f162c3652af46f9c4c473cc36.

### Current Behavior

```bash
$ npm install -g pino-pretty
npm WARN reify Removing non-directory /usr/local/lib/node_modules
```

### Steps to Reproduce

1. Make global node_modules be symlink.
2. Run `npm install -g <any module>`
3. The global node_modules is removed.

### Expected Behavior

Allow global node_modules be symlink.

**Comment by tophf** [comment]
How do we move a local per-project `node_modules` from the project's folder to another drive/folder now?

**Comment by ljharb** [comment]
@tophf a hard link? generally you don't; a local project, including its node_modules folder, should be kept all on the same drive and in the same location.

**Comment by tophf** [comment]
How do we make a hardlink for a directory in Windows, which can only make junctions or symlinks?

**Comment by wraithgar** [comment]
Closing as duplicate of https://github.com/npm/cli/issues/4358
