### ISSUE TITLE
[BUG](arborist) installing older semver tagged git dep doesn't downgrade if newer git dep is present

### ISSUE THREAD

**Issue by isaacs** [npm/cli#4278]
Reproduction: https://gist.github.com/isaacs/edebb26f6d5aa6f0fa6121a8b9cc8084
Original issue: https://github.com/npm/cli/issues/3427

Suspect that the decision to use `KEEP` instead of `REPLACE` when a newer semver version is present is being overly loose in comparing git deps for resolution of dependencies.  If a git dep is on a specific git ref, and the resolution of the ref is known, then only a git ref to the same sha should satisfy the edge.

**Comment by wraithgar** [comment]
This appears to be fixed now, see comments https://github.com/npm/cli/issues/3427#issuecomment-1048195424
