### ISSUE TITLE
[FEATURE](arborist) Have minor and patch versions changelog

### ISSUE THREAD

**Issue by felipeplets** [npm/cli#4279]
# What / Why

> Currently there are no changelog notes for minor or patch versions of Arborist as much as there are no details on the releases. The feature requested is to have a changelog.  

## When

* Whenever a new major, minor or patch version of the library is generated.

## Where

* Here in the git repo feeding the [CHANGELOG.md](https://github.com/npm/arborist/blob/main/CHANGELOG.md) available in the root folder.

### Current Behavior

* There are only major version change logs.

### Expected Behavior

* Change logs for each version. Which we can discuss how to automatically generate based on the commit messages, or manually depending on the lifecycle and the contributors for the project

## Who

* The Arborist team? 

## References

* Use the CLI as a reference [https://github.com/npm/cli/blob/latest/CHANGELOG.md]

**Comment by ruyadorno** [comment]
hi @felipeplets thanks for bringing this to our attention. We are currently looking at ways to standardize changelogs for all the workspaces within the **npm cli** including arborist.

Keep an eye for changes in the future. Thanks again!
