### ISSUE TITLE
[QUESTION](arborist) What happened to global lifecycle hooks?

### ISSUE THREAD

**Issue by augustobmoura** [npm/cli#4282]
# What / Why
Before npm@7 we had global lifecylcle hooks, `postinstall` and `postuninstall` script files in the directory `/node_modules/.hooks` were run for every package being installed or removed, but since npm@7 this scripts don't run at all. This worked for both local `node_modules` and global `$NPM_PREFIX/.npm/lib/node_modules`

Is that a bug? Or global hooks were removed once and for all? This was a feature heavily used in https://github.com/asdf-vm/asdf-nodejs and we were actually thinking about a new hook suggestion that would be more useful for our use case

**Comment by ruyadorno** [comment]
There's discussion being tracked in our [RFC repo](https://github.com/npm/rfcs) that is related to this PR: https://github.com/npm/cli/pull/4260, you can see the minutes for some of the meetings here:
- https://github.com/npm/rfcs/blob/main/meetings/2022-01-26.md
- https://github.com/npm/rfcs/blob/main/meetings/2022-02-02.md
- https://github.com/npm/rfcs/blob/main/meetings/2022-02-16.md
