### ISSUE TITLE
[BUG](arborist) npm install crashes if package version is not specified

### ISSUE THREAD

**Issue by 4javier** [npm/cli#4283]
When I try to install a new package without explicitly ask for a version, `npm install` fail with an error on arborist

**node v15.13.0
npm  v7.8.0**

```
npm install ngrx-store-localstorage
npm ERR! subset is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/javier/.npm/_logs/2021-04-05T10_59_12_150Z-debug.log
```

> 76 verbose stack TypeError: subset is not a function
76 verbose stack     at Arborist.[saveIdealTree] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:956:37)
76 verbose stack     at /usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:138:39
76 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:134:5)
76 verbose stack     at async Install.install (/usr/lib/node_modules/npm/lib/install.js:137:5)

https://github.com/npm/arborist/blob/5a185fbea691a86668e873ed47fb8897192312ff/lib/arborist/reify.js#L956

No problem passing @version

```
npm install ngrx-store-localstorage@11.0.0

changed 2 packages, and audited 1816 packages in 7s
```

**Comment by ruyadorno** [comment]
**Closing:** please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).
