### ISSUE TITLE
bug(arborist) If package.json is missing scripts block an exception will be thrown killing npm installs

### ISSUE THREAD

**Issue by theunforgiven** [npm/cli#4284]
Hello,
I had an issue with npm i tracked down to the following line:
https://github.com/npm/arborist/blob/9e324976ea5211dc24430a83928ca41b69e46b33/lib/arborist/rebuild.js#L266

If a package,json file is missing a scripts block that line can cause an exception to be thrown killing installs. I think this pkg.script lookup should probably be made null safe.

Thanks!

**Comment by ruyadorno** [comment]
I can't reproduce this one, if anyone is still able to reproduce this issue please open a new issue following our new [issue template](https://github.com/npm/cli/issues/new/choose)  and make sure to provide a minimal reproduction scenario along with it.
