### ISSUE TITLE
[FEATURE](arborist) support specifying the lockfileVersion as an option

### ISSUE THREAD

**Issue by isaacs** [npm/cli#4286]
Set `options.lockfileVersion` to a number between 1 and 3, to tell arborist how to save the lockfile/shrinkwrap.

1. Do not include `packages` section, only `dependencies`, a la npm v6.
2. What we do by default, both `packages` and `dependencies`.
3. Do not save `dependencies` and do not include the root node in the lockfile (what we do for hidden lockfiles today).

**Comment by ruyadorno** [comment]
I believe this has been completed a long while ago since npm@8 supports a `lockfile-version` config option
