### ISSUE TITLE
[QUESTION](arborist) Can i use Arborist with data from pacote.manifest ?

### ISSUE THREAD

**Issue by fraxken** [npm/cli#4288]
# What / Why
Hello on the project [nsecure](https://github.com/ES-Community/nsecure) we are working on an implementation of npm audit. Because i'm already using Arborist for the local analysis [here](https://github.com/ES-Community/nsecure/blob/master/src/depWalker.js#L202) we can easily use the .audit() method to implement warnings to the analysis.

But when we are working with a remote package we only fetch the manifest with pacote and my question was: **is there is a way to initialize Arborist with this manifest** ?

**Comment by ruyadorno** [comment]
From my knowledge there's no programmatic API to initialize pacote or arborist with a manifest. That said, there is an in-memory cache layer for packuments (which is where the manifests come from iirc) named `packumentCache` that you can initialize and provide as an arborist option, see:

https://github.com/npm/cli/blob/2db3eff44d7bb86b956207cc63d279806fd14ed0/workspaces/arborist/lib/arborist/index.js#L75

Maybe that's what you're looking for but if not I hope it helps at least in giving some direction on what to explore. You can dig more on how the `packumentCache` works by peaking at the code over the **pacote** repo: https://github.com/npm/pacote/blob/17d45f03ff5152e97fe931e47fb0572f9fbafb8a/lib/registry.js#L79
