### ISSUE TITLE
[BUG](arborist) `node-gyp` doesn't work from within Electron

### ISSUE THREAD

**Issue by hrueger** [npm/cli#4291]
# What / Why
Hi,
I have an Electron app in which I am using arborist to install npm packages into a folder at runtime. Those packages are then required and used. When I install a package which requires native addon modules to be rebuilt using node-gyp, I encounter the following error:
```Unhandled Rejection at: Promise Promise {
  <rejected> Error: command failed
      at ChildProcess.<anonymous> (C:\Users\Hannes\AppData\Local\Programs\glue\resources\app.asar\node_modules\@npmcli\promise-spawn\index.js:64:27)
      at ChildProcess.emit (events.js:315:20)
      at maybeClose (internal/child_process.js:1021:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
    cmd: 'C:\\WINDOWS\\system32\\cmd.exe',
    args: [
      '/d',
      '/s',
      '/c',
      'prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild'
    ],
    code: 1,
    signal: null,
    stdout: '',
    stderr: 'Der Befehl "node-gyp" ist entweder falsch geschrieben oder\r\n' +
      'konnte nicht gefunden werden.\r\n',
    event: 'install',
    script: 'prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild',
    pkgid: '@serialport/bindings@8.0.8',
    path: 'C:\\Users\\Hannes\\AppData\\Roaming\\glue\\data\\features\\node_modules\\@serialport\\bindings'
  }
} reason: Error: command failed
    at ChildProcess.<anonymous> (C:\Users\Hannes\AppData\Local\Programs\glue\resources\app.asar\node_modules\@npmcli\promise-spawn\index.js:64:27)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  cmd: 'C:\\WINDOWS\\system32\\cmd.exe',
  args: [
    '/d',
    '/s',
    '/c',
    'prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild'
  ],
  code: 1,
  signal: null,
  stdout: '',
  stderr: 'Der Befehl "node-gyp" ist entweder falsch geschrieben oder\r\n' +
    'konnte nicht gefunden werden.\r\n',
  event: 'install',
  script: 'prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild',
  pkgid: '@serialport/bindings@8.0.8',
  path: 'C:\\Users\\Hannes\\AppData\\Roaming\\glue\\data\\features\\node_modules\\@serialport\\bindings'
}
```
The german (sorry for that, but my windows is set to German) translates to The command "node-gyp" is either misspelled or could not be found. 
All of this happens in the Electron Main process. The end-user will not have NodeJS nor node-gyp installed.
So I ship it with my electron app. But how can I tell arborist to use node-gyp from that path?

## When
I install a npm package requiring node-gyp rebuilds.

## Where
In an Electron main process
* n/a

## How
?

### Current Behavior
See above

### Steps to Reproduce

* n/a

### Expected Behavior
It should rebuild the dependencies.

## Who

* n/a

## References
* Original issue: npm/cli/issues/2469

**Comment by ruyadorno** [comment]
Hi @hrueger thanks for sharing that, it's definitely a super interesting usage of **arborist** and one I'd love to try to hack with a bit more myself 😄 

With that in mind, one possible way I could see to try and work around this issue would be to maybe just a setup step in your app in which you reify `node-gyp` (and possibly any similar potential system dependency) either in that path as a dev dependency (might be not ideal since it's going to modify `package.json`, lock file, etc) or in the global folder (equivalent of `npm i -g node-gyp`) so that you can ensure it's installed and available by the time you try to reify something else.

**Comment by mmomtchev** [comment]
Because of two `require.resolve` statements - including the `node-gyp` one and an additional one coming from `@sigstore/tuf` for `seeds.json`, `arborist` currently cannot be (easily) bundled for server-less environments.
