### ISSUE TITLE
[FEATURE](arborist) add engines.node and engines.npm as easily queryable fields on inventory

### ISSUE THREAD

**Issue by isaacs** [npm/cli#4293]
A little bit differently shaped than name and license, since it's not a single string, but it would be nice to be able to have a top-level inventory map that we could query to find all the modules that have an engines restriction in their manifest.

Maybe we just save it as a boolean, or list the keys?  So, for example:

```js
for (const node of tree.inventory.query('engines', 'node')) {
  // node has an engines.node restriction
}
```

cc: @ljharb

**Comment by wraithgar** [comment]
`npm query` solved this problem:

`npm query '* :attr(engines, [node])'`
`npm query '* :attr(engines, [node]):not(:semver(10.2.0, :attr(engines, [node]), satisfies))'`

**Comment by ljharb** [comment]
Does npm query work without a reified node_modules? If not, then it doesn’t meet this need.

**Comment by wraithgar** [comment]
```
~/D/n/s/query $ rm -rf node_modules/
~/D/n/s/query $ npm query '* :attr(engines, [node]):not(:semver(10.2.0, :attr(engines, [node]), satisfies))' --package-lock-only|json -a name engines.node
abbrev ^14.17.0 || ^16.13.0 || >=18.0.0
```

**Comment by ljharb** [comment]
Awesome, thanks for confirming :-)

**Comment by ljharb** [comment]
@wraithgar actually after more thought, the thing I actually need is a JS way to do this without calling out to the shell. Does arborist expose a query function that takes a selector?

**Comment by wraithgar** [comment]
Yes this is all arborist https://github.com/npm/cli/blob/0f7008851f1c250405e8dc326f15d535e8fc1eae/lib/commands/query.js#L81
