### ISSUE TITLE
[FEATURE](arborist) A way to use new Arborist() by providing the package.json / lock file directly

### ISSUE THREAD

**Issue by dominykas** [npm/cli#4295]
# What / Why

I'm building some tooling which needs to build some ideal trees. It doesn't care about installing those trees - it just needs to get the list of (deep) dependencies.

I have the `package.json` and lock file data loaded directly from Github. It would be nice to be able to construct the ideal tree for those without first creating a temp folder and writing these files out to disk.

### Current Behavior

It already does that under the hood.

### Expected Behavior

Would be nice to have an API exposed to achieve that.

**Comment by ryandutton** [comment]
This would be extremely useful, particularly when trying to get a valid payload which can be used with OWASP Dependency Check were the Node Audit Analyser is currently broken. [#3717](https://github.com/jeremylong/DependencyCheck/issues/3717)

**Comment by wraithgar** [comment]
This isn't something the npm team is planning on implementing.  A pr that implements this would be ok to submit if someone wants to write it.
