### ISSUE TITLE
not able to create a project

### ISSUE THREAD

**Issue by raviteja213** [npm/cli#4299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

PS C:\Users\HP\OneDrive\Desktop\lcorn> npx react-native init mypro
Need to install the following packages:
  react-native
Ok to proceed? (y) y
npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! network Socket timeout
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Local\npm-cache\_logs\2022-01-20T12_02_03_778Z-debug-0.log

### Expected Behavior

it need to create a folder with name mypro

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node.js:
- OS Name: windows
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by ruyadorno** [comment]
**Closing:** please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).
