### ISSUE TITLE
[BUG] 2 high severity vulnerabilities

### ISSUE THREAD

**Issue by Creo2005** [npm/cli#4304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 8.3.2
- Node.js: v14.18.3
- OS Name: Ubuntu 20
- System Model Name: mini PC
- npm config:
```ini
; "user" config from /home/creo/.npmrc

registry = "https://registry.npmjs.org/" 

; "project" config from /opt/zigbee2mqtt/.npmrc

tag-version-prefix = "" 

; node bin location = /usr/bin/node
; cwd = /opt/zigbee2mqtt
; HOME = /home/creo
; Run `npm config ls -l` to show all defaults.
```

**Comment by ruyadorno** [comment]
**Closing:** please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).
