### ISSUE TITLE
primordials was not defined plus many missing dependency errors all of a sudden

### ISSUE THREAD

**Issue by TheChickenKnight** [npm/cli#4314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [ ] I am using the latest npm

### Current Behavior

I'm not able to install anything using npm, with always around the same error message about "primordials". I've snooped through a lot of files and such, but I can't see any connection to "primordials" I'll attach the debug file below. It started with heroku continuously failing it's build from GitHub, because "a module may have been missing from dependencies". So then I looked through and apparently "node-bin-setup" was extraneous according to node or npm, so I uninstalled it, and also uninstalled something else called "prisma". Since then I've been getting these errors even when reinstalling node or installing older versions like node v11. All I can find online is about some "gulp" library and nothing when removing "gulp" as a keyword. Any help would be appreciated.

(It's on my ToastBot repo by the way)
[npm-debug.log](https://github.com/npm/cli/files/7921726/npm-debug.log)

### Expected Behavior

no error messages in npm install, so being able to install any npm normally.

### Steps To Reproduce

Don't think you really can but perhaps what I mentioned in current behavior

### Environment

- npm: v3.5.4
- Node.js: v16.13.2
- OS Name: Windows 10
- System Model Name: System Version
- npm config:
```ini
; cli configs
user-agent = "npm/3.5.4 node/v16.13.2 win32 x64"

; builtin config undefined
prefix = "C:\\Users\\chckn\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = E:\GitHub repos\ToastBot
; HOME = C:\Users\chckn
; "npm config ls -l" to show all defaults.
```

**Comment by ljharb** [comment]
npm 3 is very very ancient. node 16 ships with npm 6, so it shouldn't even be possible to have npm 3 with it.

How did you install node in the first place?

**Comment by TheChickenKnight** [comment]
Huh, I don't really see how that could happen either. I really just installed from the node website with the recommended release. I didn't even realize I didn't have the latest npm version, so I really just assumed I had the latest one. Thanks, I'll close it in the next comment once I definitely fix the problem. I'm not really sure If I can update npm though, but this is a node problem not one with npm. Also, I can't update npm through the usual means because it just gives me the error message I mentioned above. Is there another way of updating npm?

**Comment by ljharb** [comment]
You may want to try removing every copy of node and npm from your system, and then install fresh from the node website (or use a popular version manager, like nvm, nave, or n).

**Comment by TheChickenKnight** [comment]
So I've tried nvm for windows and I still have npm version 3.5.4 with node 16.13.2. Next, I tried downloading node 17.4.0 through nvm, and somehow that one decided to come with npm 8.3.1, so i deleted all of my libraries and redownloaded them and it seems we are so good. Thank you for taking your time to help me, I really wouldn't have figured this out without you.
