### ISSUE TITLE
[BUG] `sudo npm install plotta.js` deletes npm installation

### ISSUE THREAD

**Issue by kupietools** [npm/cli#4315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I installed a single package, and it told me to try again as administrator. So I ran it with Sudo, and somehow this deleted npm entirely from my computer. Log:
```
MacBook:node_modules mycomputer$ npm install plotta.js
npm notice 
npm notice New patch version of npm available! 8.3.0 -> 8.3.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.3.2
npm notice Run npm install -g npm@8.3.2 to update!
npm notice 
npm ERR! code EACCES
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/corepack
npm ERR! dest /usr/local/lib/node_modules/.corepack-xqcTrkeV
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/corepack' -> '/usr/local/lib/node_modules/.corepack-xqcTrkeV'
npm ERR!  [Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/corepack' -> '/usr/local/lib/node_modules/.corepack-xqcTrkeV'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rename',
npm ERR!   path: '/usr/local/lib/node_modules/corepack',
npm ERR!   dest: '/usr/local/lib/node_modules/.corepack-xqcTrkeV'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mycomputer/.npm/_logs/2022-01-24T00_20_18_344Z-debug-0.log
MacBook:node_modules mycomputer$ sudo npm install plotta.js
Password:

added 1 package, removed 3662 packages, and audited 2 packages in 39s

found 0 vulnerabilities
npm notice 
npm notice New patch version of npm available! 8.3.0 -> 8.3.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.3.2
npm notice Run npm install -g npm@8.3.2 to update!
npm notice 
MacBook:node_modules mycomputer$ npm list
-bash: /usr/local/bin/npm: No such file or directory
MacBook:node_modules mycomputer$ npm list -g
-bash: /usr/local/bin/npm: No such file or directory
MacBook:node_modules mycomputer$ npm list -g
-bash: /usr/local/bin/npm: No such file or directory
MacBook:node_modules mycomputer$ cd ~
MacBook:~ mycomputer$ npm list -g
-bash: /usr/local/bin/npm: No such file or directory
MacBook:~ mycomputer$ npm install -g npm@8.3.2
-bash: /usr/local/bin/npm: No such file or directory
MacBook:~ mycomputer$ which npm
MacBook:~ mycomputer$ 
```

### Expected Behavior

I expected the plotta.js package to be installed, and nothing important to be deleted. 

### Steps To Reproduce

1. In this environment...

MacOS 10.14.6

2. With this config...

Sorry, I don't know what a config is. 

3. Run '...'

`npm install plotta.js`. When you get the error, try `sudo npm install plotta.js`. When that is done, do `npm list`.

4. See error...
response to `npm list` is now:
`-bash: /usr/local/bin/npm: No such file or directory`

### Environment

- npm: was NPM 8.3.0

- Node.js: v16.13.0
- OS Name: MacOS Mojave 10.14.6
- System Model Name: MacBook Pro
- npm config:
Doesn't work because npm is totally gone:
```ini
MacBook:~ mycomputer$ npm config ls
-bash: /usr/local/bin/npm: No such file or directory
```

**Comment by ljharb** [comment]
Why are you using sudo for a local installation?

**Comment by bnb** [comment]
@ljharb 

> I installed a single package, and it told me to try again as administrator.

because the command output told them to 😅

**Comment by ljharb** [comment]
ha, oops. The corepack path might suggest it's to blame?

**Comment by nlf** [comment]
> ha, oops. The corepack path might suggest it's to blame?

indeed. this looks like a bug in corepack. there's nothing about this package that could cause the removal of npm, and i'm unable to reproduce it. you can open an issue for corepack here: https://github.com/nodejs/corepack
