### ISSUE TITLE
[BUG] Don't suggest npm audit when it won't work (global installs)

### ISSUE THREAD

**Issue by varungandhi-src** [npm/cli#4318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Using `npm install --global <pack>` can suggest using `npm audit`. However, the latter fails and recommends creating a lock file. Creating a lock file is the wrong fix because the audit will be run for the local package, not for the global config.

### Expected Behavior

Either the `npm audit` recommendation should be removed if the lock file is not present, or there should be some other flag to `npm audit` which should be recommended instead to audit the global configuration.

### Steps To Reproduce

Environment:  (npm v8.1.4)

```
$ npm install --global verdaccio
# other output...
To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
$ npm audit
npm ERR! code ENOLOCK
npm ERR! audit This command requires an existing lockfile.
npm ERR! audit Try creating one first with: npm i --package-lock-only
```

### Environment

- npm: npm 8.1.2
- Node.js: node v17.2.0
- npm config:
```ini
; node bin location = /Users/varun/.nvm/versions/node/v17.2.0/bin/node
; cwd = /Users/varun/Code/npm-testing
; HOME = /Users/varun
; Run `npm config ls -l` to show all defaults.
```

**Comment by ljharb** [comment]
Indeed, npm shouldn’t suggest an audit at all when the install is global.

**Comment by costispavlou** [comment]
I'm actually having the same issue trying to update npm to 8.3.2

```
sudo npm install -g npm@8.3.2
changed 14 packages, and audited 215 packages in 26s
11 packages are looking for funding
  run `npm fund` for details
3 moderate severity vulnerabilities
To address all issues, run:
  npm audit fix
Run `npm audit` for details.
```
```
sudo npm audit fix
up to date, audited 250 packages in 32s
28 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
```
```
sudo npm fund
pi
├─┬ https://github.com/chalk/chalk?sponsor=1
│ │ └── chalk@4.1.2
│ └── https://github.com/chalk/ansi-styles?sponsor=1
│     └── ansi-styles@4.3.0
├── https://github.com/sponsors/sindresorhus
│   └── find-up@5.0.0, locate-path@6.0.0, p-locate@5.0.0, p-limit@3.1.0, yocto-queue@0.1.0, get-stdin@8.0.0, globby@11.1.0, p-map@4.0.0, boxen@5.1.2, camelcase@6.3.0, cli-boxes@2.2.1, type-fest@0.20.2, is-installed-globally@0.4.0, global-dirs@3.0.0, is-npm@5.0.0, make-dir@3.1.0, get-stream@5.2.0, p-limit@2.3.0
├── https://github.com/sponsors/isaacs
│   └── rimraf@3.0.2, glob@7.2.0
└── https://github.com/yeoman/update-notifier?sponsor=1
    └── update-notifier@5.1.0
```

**Comment by ljharb** [comment]
(Just because it tells you about audit warnings doesn’t mean you have to fix them)

**Comment by costispavlou** [comment]
well I'm trying to update npm and it wont update, that's the reason I'm asking.

**Comment by ljharb** [comment]
@costispavlou the audit warnings don’t mean it didn’t update, run npm -v

**Comment by costispavlou** [comment]
indeed npm has updated but homebridge states that the version is still 8.1.2
any ideas why ? I restarted homebridge as well.

**Comment by ljharb** [comment]
No, i have no idea what homebridge is. You may want to file a different issue tho, since it’s off topic for this one.

**Comment by elandorr** [comment]
How are you supposed to 'audit' global npm packages in the first place? (Rarely use anything JS, excuse)

I see about one googol worth of `deprecated` `ERR!` `high severity vulnerability` and really don't know what the proper procedure is.

**Comment by ljharb** [comment]
You’re not. You’re not really supposed to have any global packages in the first place.

**Comment by elandorr** [comment]
@ljharb How do you use globally used tools then? Do you seriously install a minifier in every project? Besides development related packages I have quite a few other tools that just happen to be written in node as well.

I guess I could make a separate folder for them and create a fake package.json, but that is exactly like having them global, no? (apart from easy access, of course)

**Comment by ljharb** [comment]
@elandorr what is globally used? Yes, i install all the tools a project uses in each project that uses them; that way versions are tracked and other developers can use the same ones. That means, eg, i probably have a thousand copies of eslint on my machine, and my life is infinitely better for it.
