### ISSUE TITLE
unable create a new react instance(create-react-app)

### ISSUE THREAD

**Issue by krisphinna** [npm/cli#4324]
I am trying to create a new project, during the installation build up, it abbot and throw the message below.

npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\KRIS\AppData\Local\npm-cache\_logs\2022-01-25T13_11_39_762Z-debug-0.log

Aborting installation.
  npm install --no-audit --save --save-exact --loglevel error react react-dom react-scripts cra-template has failed.

Deleting generated file... package.json
Deleting react-expense-device/ from C:\Users\KRIS
Done.

kindly need help.

**Comment by krisphinna** [comment]
Sorry, i did not give information relating to the tools i am using.

Node version 14.16.0
npm version 8.3.2
windows 10
code editor VS code

**Comment by nlf** [comment]
see #417

if you continue to encounter issues and can reproduce them, please open a new issue and be sure to fill out our template as completely as you can. without a reproduction we can't do much here.
