### ISSUE TITLE
dependencies, devDependencies, and peerDependencies Order

### ISSUE THREAD

**Issue by jasonnicholson** [npm/cli#4325]
We have some tools that run in the postinstall script for moving stuff out of node_modules because we adopted npm as our package manager. We don't use Javascript for development. It turns out we think we accidentally ended up depending on the order by which npm installs dependencies, devDependencies, and peerDependencies. However, we cannot find any documentation on the order by which dependencies, devDependencies, and peerDependencies are installed. 

* Is there a spec that documents the order of dependencies, devDependencies, and peerDependencies running the lifecycle scripts (preinstall, install, postinstall)? 
* Or is it undocumented on purpose so you can change it at will because you don't want people relying on this order?

**Comment by ljharb** [comment]
The order shouldn't matter - postinstall should run (i think) after everything is installed.

**Comment by jasonnicholson** [comment]
In our case, with `npm ci`, postinstall runs before a peer dependency is installed causing the failure. There is definitely is a failure. 

What I really need from you is, "No there is no documentation of what order dependencies are installed" or point me to the documentation/specification.

Below is sanitized stack trace. We are using npm 6.14.15 and node 14.18.2. We can't upgrade currently (same old pattern we can't upgrade because of xyz thing). When we can finally upgrade, the change in how peer dependencies are handled does help us I think.

```text
297 silly lifecycle package-A@1.0.0~postinstall: Args: [ '/d /s /c', 'do-stuff' ]
298 silly lifecycle package-A@1.0.0~postinstall: Returned: code: 1  signal: null
299 info lifecycle package-A@1.0.0~postinstall: Failed to exec postinstall script
300 verbose teardown shutting down workers.
301 info teardown Done in 0s
302 verbose stack Error: package-A@1.0.0 postinstall: `do-stuff`
302 verbose stack Exit status 1
302 verbose stack     at EventEmitter.<anonymous> (c:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
302 verbose stack     at EventEmitter.emit (events.js:400:28)
302 verbose stack     at ChildProcess.<anonymous> (c:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
302 verbose stack     at ChildProcess.emit (events.js:400:28)
302 verbose stack     at maybeClose (internal/child_process.js:1058:16)
302 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
303 verbose pkgid package-A@1.0.0
304 verbose cwd C:\GIT\npm-hgl-test
305 verbose Windows_NT 10.0.19042
306 verbose argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ci"
307 verbose node v14.18.2
308 verbose npm  v6.14.15
309 error code ELIFECYCLE
310 error errno 1
311 error package-A@1.0.0 postinstall: `do-stuff`
311 error Exit status 1
312 error Failed at the package-A@1.0.0 postinstall script.
312 error This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by ljharb** [comment]
Note; i'm not an official npm contributor, I'm just trying to help.

The dependency type helps build the dep graph, and i don't personally think the type has ANY impact whatsoever on the order of installation.

Note that npm 7+ does have different behavior with peer dependencies - notably, if your dependency graph is invalid because you've failed to explicitly depend on your deps' peerDeps, it will try to install a valid peer dep for you, and if it can't, it will fail the overarching installation.

**Comment by jasonnicholson** [comment]
Okay, thank you. I think you have given me enough.

>The dependency type helps build the dep graph, and i don't personally think the type has ANY impact whatsoever on the order of installation.

I can tell you that type does have an effect that causes us problems. Without a spec or documentation of how the dependencies are resolved, **this order is not something we can depend on**. We have to get away from accidentally depending on the order things are installed.

npm 7 is an improvement and does fix the issues we are seeing. I can tell you I don't see errors with npm 7. I found the blogs about the invention of Arborist. Super interesting! However, without a specification/documentation of how dependencies are ordered, this is still something we should not rely on. 

# Solution
Do not rely on the order in which dependencies are installed. Do the secondary operation after installing. i.e.

```
npm ci
npx doStuff
```
