### ISSUE TITLE
[BUG] URLSearchParams API instead of querystring API

### ISSUE THREAD

**Issue by thuongtruong1009** [npm/cli#4328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I use the NPM package manager in my project. When I deploy to Vercel.com, I get an error like that: 
```
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
```
What I can do in this situation? 
I looking forward to your help!
Thank you very much!

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 8.3.2
- Node.js: 16.13.1
- OS Name: Window10 x64
- System Model Name: Lenovo Thinkpad
- npm config:
```
npm install && npm run build
```

**Comment by ljharb** [comment]
This has nothing to do with npm; it just means that package added a deprecation notice.

In this particular case, you can ignore it, switch to URLSearchParams, or switch to the qs package.
