### ISSUE TITLE
`npm update --save` in npm@8.3.2 does not respect exact versions

### ISSUE THREAD

**Issue by matthewmayer** [npm/cli#4329]
`npm update --save` in npm@8.3.2 works differently to `npm update` in npm@6 when specifying an exact version

For example if you run `npm install --save-exact cron@1.8.0`

Then your package.json will look like this:

` "cron": "1.8.0"`

if you then run on npm@6
`npm update`

nothing is changed

but if you then run on npm@8.3.2

`npm update --save`

package.json is updated to 

` "cron": "^1.8.0"`

and then if you run `npm update --save` again package.json is updated to 

` "cron": "^1.8.2"`

This is doubly confusing as my pinned version is lost AND I get a different behavior if I run npm update twice

_Originally posted by @matthewmayer in https://github.com/npm/cli/issues/2704#issuecomment-1018400947_

**Comment by ruyadorno** [comment]
thanks for the report @matthewmayer that's def unintended behavior!

I can easily reproduce it with a minimal example:

```
$ npm i --save-exact abbrev@1.0.9
$ cat package.json
{
  "name": "test-save-exact",
  "version": "1.0.0",
  "dependencies": {
    "abbrev": "1.0.9"
  }
}

$ npm up --save
$ cat package.json
{
  "name": "test-save-exact",
  "version": "1.0.0",
  "dependencies": {
    "abbrev": "^1.0.9"
  }
}

$ npm up --save
$ cat package.json
{
  "name": "test-save-exact",
  "version": "1.0.0",
  "dependencies": {
    "abbrev": "^1.1.1"
  }
}
```
