### ISSUE TITLE
[BUG] npm_config_ ignore camelCase variables

### ISSUE THREAD

**Issue by yarikpavlin** [npm/cli#4330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Hello there!

Let's assume that we have the following script:
```
"scripts": {
        "demo": "echo \"Hello $npm_config_firstname $npm_config_lastName\"",
}

```
In this case when we execute the demo script with some values, we have such string:
```
> npm run demo --firstname=Foo --lastWord=Bar
> Hello Foo 
```
Second argument was ignored due to variable name has camelCase style. I've tested it in different combinations of vartiable names but the result is always the same.

### Expected Behavior

I expect that $npm_config_{variable} shoud work with any variable name style.

### Steps To Reproduce

1. Add script provieded above
2. Run following command: npm run demo --firstname=Foo --lastWord=Bar
3. Check results

### Environment

- npm: 8.1.2
- Node.js:  v16.13.2
- OS Name: Mac OS Monterey
- System Model Name: Mac Mini (2018)
- npm config:
```
; node bin location = /usr/local/bin/node
; cwd = /Users/ypavlyn/PetProjects/npm_bug
; HOME = /Users/ypavlyn
; Run `npm config ls -l` to show all defaults.
```

**Comment by nlf** [comment]
we actually don't intentionally support exporting any environment variables other than ones we've defined ourselves, and the fact that even `lastname` is working is a bug. this is a pretty clever trick, but unfortunately it's one you'll have to deal with by making your script understand command line flags directly and run it like `npm run demo -- --lastname=Foo`

as an FYI, we intend to fix this bug and stop exporting environment variables for flags that we don't define in npm@9

**Comment by opncow** [comment]
> as an FYI, we intend to fix this bug and stop exporting environment variables for flags that we don't define in npm@9

Is there some issue to track for progress regarding this "bug fix"?
