### ISSUE TITLE
npm overlapping with extertnal package manager

### ISSUE THREAD

**Issue by whyvn** [npm/cli#4337]
There is an existing issue for this in another repo but it only mentioned fixes for the end user. (i don't have my own proof since i already fixed this issue myself) And sorry for the bad issue template.

When `npm` prompts you to update itself `npm install -g npm.*` while its installed from an external package manager (i.e. [pacman](https://wiki.archlinux.org/title/Pacman)), the files will overlap causing an error message and a halt in the update sequence of `npm` and the package manager. You can fix this by executing `npm r -g npm` and syncing it with your package manager. It would help if npm prompted you to update it from where you got `npm` from to avoid causing this issue.

**Comment by ljharb** [comment]
npm isn’t supposed to _be_ installed by another package manager; it comes with node.

**Comment by ruyadorno** [comment]
Hi @FabianPaci thanks for taking the time to report this issue. As @ljharb noted above, in case you're having problems it's better to stick with our [documented installation alternatives](https://github.com/npm/cli#installation).
