### ISSUE TITLE
Unexpected token "."

### ISSUE THREAD

**Issue by syedbilal07** [npm/cli#4340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When i run command "npm outdated -g --depth=0". It throws the following error. https://imgur.com/a/2l1ijmL. The issue was also present in v8.3.1 and v8.3.2.
It is still present in v8.4.0. I don't want to switch to LTS release. Here is the complete log  https://files.fm/u/gzravnp2s.

### Expected Behavior

It should show the outdated packages.

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```
npm -v: npm 8.40
node -v:  Node.js: 17.4.0
OS Name: Windows 11 (Enterprise Edition)
System: Dell Optiplex 990,
npm config ls: ; "user" config from C:\Users\Bilal\.npmrc

registry = "http://registry.npmjs.org/"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\Bilal
; HOME = C:\Users\Bilal
; Run `npm config ls -l` to show all defaults.

**Comment by fumiichan** [comment]
Can confirm this happening on `npm 8.3.1`.

Here's the log file for additional info:
```
0 verbose cli [
0 verbose cli   'C:\\Irene\\nvm\\nodejs\\node.exe',
0 verbose cli   'C:\\Irene\\nvm\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'install',
0 verbose cli   '-g',
0 verbose cli   'eslint',
0 verbose cli   'http-server',
0 verbose cli   'yarn'
0 verbose cli ]
1 info using npm@8.3.1
2 info using node@v17.4.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Irene\nvm\v17.4.0\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 4ms
8 timing config:load:env Completed in 1ms
9 timing config:load:project Completed in 4ms
10 timing config:load:file:C:\Users\nekocat\.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:C:\Irene\nvm\nodejs\etc\npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:validate Completed in 0ms
15 timing config:load:credentials Completed in 1ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 15ms
18 timing npm:load:configload Completed in 16ms
19 timing npm:load:setTitle Completed in 1ms
20 timing config:load:flatten Completed in 4ms
21 timing npm:load:display Completed in 5ms
22 verbose logfile C:\Users\nekocat\AppData\Local\npm-cache\_logs\2022-01-29T20_10_44_844Z-debug-0.log
23 timing npm:load:logFile Completed in 8ms
24 timing npm:load:timers Completed in 0ms
25 timing npm:load:configScope Completed in 0ms
26 timing npm:load Completed in 31ms
27 verbose stack C:\Irene\nvm\v17.4.0\node_modules\npm\node_modules\libnpmfund:1
27 verbose stack ../workspaces/libnpmfund
27 verbose stack ^
27 verbose stack
27 verbose stack SyntaxError: Unexpected token '.'
27 verbose stack     at Object.compileFunction (node:vm:352:18)
27 verbose stack     at wrapSafe (node:internal/modules/cjs/loader:1026:15)
27 verbose stack     at Module._compile (node:internal/modules/cjs/loader:1061:27)
27 verbose stack     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
27 verbose stack     at Module.load (node:internal/modules/cjs/loader:975:32)
27 verbose stack     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
27 verbose stack     at Module.require (node:internal/modules/cjs/loader:999:19)
27 verbose stack     at require (node:internal/modules/cjs/helpers:102:18)
27 verbose stack     at Object.<anonymous> (C:\Irene\nvm\v17.4.0\node_modules\npm\lib\utils\reify-output.js:16:38)
27 verbose stack     at Module._compile (node:internal/modules/cjs/loader:1097:14)
28 verbose cwd C:\Users\nekocat
29 verbose Windows_NT 10.0.19044
30 verbose argv "C:\\Irene\\nvm\\nodejs\\node.exe" "C:\\Irene\\nvm\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "eslint" "http-server" "yarn"
31 verbose node v17.4.0
32 verbose npm  v8.3.1
33 error Unexpected token '.'
34 verbose exit 1
35 timing npm Completed in 391ms
36 verbose code 1
37 error A complete log of this run can be found in:
37 error     C:\Users\nekocat\AppData\Local\npm-cache\_logs\2022-01-29T20_10_44_844Z-debug-0.log
```

OS: Windows 10 21H2 (Build 19044.1415)
Node: 17.4.0
NPM: 8.3.1

**Comment by syedbilal07** [comment]
Yes, it was happening on npm v8.3.1. I managed to solve the command npm outdated -g --depth=0 by myself. But npm install didn't work.

**Comment by fumiichan** [comment]
I found the something that seems that these files are (maybe?) supposed to be symlinks against the folders in `../workspaces`.
![image](https://user-images.githubusercontent.com/35658068/151813160-3c7d1e34-0071-4451-a162-1e718d2a4158.png)

I replaced those with symlinks from `../workspaces` folders and it finally worked.

`@npmcli/arborist` is symlinked to `workspaces/arborist`
![image](https://user-images.githubusercontent.com/35658068/151814574-05695c75-31f3-4a45-be01-7be2e75ccacd.png)

And the same for others
![image](https://user-images.githubusercontent.com/35658068/151814793-bd4d38c7-7b70-4b94-8aee-64f9466c458f.png)

I don't really know if I should do this and whether the issue is on `nvm-windows` itself.

Anyways, after that I updated to npm 8.4.0 and it seems to be working fine now.

**Comment by syedbilal07** [comment]
Are you able to run "npm outdated -g --depth=0" and "npm install". If  yes, please share this npm version by uploading it to files.fm

**Comment by nlf** [comment]
how did you folks install these npm versions? just a standard `npm i -g npm`? it definitely looks like for some reason you ended up with folders that are supposed to be symlinks being symlink placeholders, which is a thing that git does by default in windows unless you configure it not to. if you installed from the npm registry, though, i don't think that should be what you end up with so i'm a bit confused. i'll investigate this further

**Comment by fumiichan** [comment]
This happens after I install `17.4.0` version using `nvm-windows`. It installs `npm 8.3.1`. It downloads `npm` as a `zip` from this repository and didn't symlinked those folders after the unpack.

I was certain this is a `nvm-windows` issue for me at least.

**Comment by ljharb** [comment]
real nvm has actual windows support now in many shells; you may want to try that to see if it works better.

**Comment by syedbilal07** [comment]
> 

I never used npm i -g npm for installation. I always used this repository for npm install.!

**Comment by MadLittleMods** [comment]
> This happens after I install `17.4.0` version using `nvm-windows`. It installs `npm 8.3.1`. It downloads `npm` as a `zip` from this repository and didn't symlinked those folders after the unpack.
> 
> I was certain this is a `nvm-windows` issue for me at least.

I also ran into this with `nvm-windows@1.1.6`. After updating to `nvm-windows@1.1.9` and re-installing Node.js `17.4.0`, it seems to work 🎉

**Comment by nlf** [comment]
the issue is in downloading a zip of this repository. since we've migrated some of our internal libraries to workspaces, those workspaces are in `node_modules` as symlinks, which windows seems to treat as plain files with the path they're meant to link to as the contents.

this isn't something we're going to change, it's very much up to your tooling to take care of it. sounds like `nvm-windows` has a new version that fixes this problem, and for anyone else seeing it [this comment](https://github.com/npm/cli/issues/4340#issuecomment-1025833090) describes how to manually correct the problem.

**Comment by syedbilal07** [comment]
Ok thank you.

**Comment by yanceyk** [comment]
Thanks @aikoofujimotoo. This solved my issue.

**Comment by casp4** [comment]
> real nvm has actual windows support now in many shells; you may want to try that to see if it works better.

I ran into this with real nvm as well. Didn't even realise there was an nvm specifically for windows. Haven't had it long though. node 16.12.0 does not throw error while node 18* does.

I can't be using node 17* on client production code so not even going to try it.

**Comment by ljharb** [comment]
@casp4 if you're seeing an issue with actual nvm, please file an issue on the repo https://github.com/nvm-sh/nvm
