### ISSUE TITLE
[BUG](arborist) install failed even though peer dependency is satisfied

### ISSUE THREAD

**Issue by Badisi** [npm/cli#4343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

Seems related to #4104 and #4267 

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Consider the following:

- **@angular/core@12.2.16** is installed as a direct dependency
- **@sentry/angular@6.17.2** requires **@angular/core@"10.x || 11.x || 12.x || 13.x"** as a peer dependency

Though, trying to install the latter will results in the following:

```shell
test % npm i @sentry/angular@6.17.2
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: test@1.0.0
npm ERR! Found: @angular/core@12.2.16
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"^12.2.16" from the root project
npm ERR!   peer @angular/core@"10.x || 11.x || 12.x || 13.x" from @sentry/angular@6.17.2
npm ERR!   node_modules/@sentry/angular
npm ERR!     @sentry/angular@"6.17.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"13.2.0" from @angular/common@13.2.0
npm ERR! node_modules/@angular/common
npm ERR!   peer @angular/common@"10.x || 11.x || 12.x || 13.x" from @sentry/angular@6.17.2
npm ERR!   node_modules/@sentry/angular
npm ERR!     @sentry/angular@"6.17.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### Expected Behavior

**@sentry/angular** should install fine as its peer dependency requirements is satisfied :

-> `@angular/core@12.2.16` satisfies `"10.x || 11.x || 12.x || 13.x"`

### Steps To Reproduce

Simply run the following:

```shell
npm init --yes
npm i @angular/core@12
npm i @sentry/angular@6.17.2
```

### Environment

- npm: **8.4.0**
- Node.js: **v14.17.5**
- OS Name: **macOS Catalina (v10.15.7)**
- System Model Name: **MacBook Pro (16-inch, 2019)**

**Comment by ljharb** [comment]
`@angular/common@13.2.0` requires precisely `@angular/core@"13.2.0"`, but your root project has `@angular/core@"^12.2.16"`.

In other words, the peer dependency is not satisfied. It may be satisfiable, if the right version of `@angular/common` is selected - but a workaround might be to explicitly depend on `@angular/common@12` yourself.

**Comment by Badisi** [comment]
Makes so much sense now that you said it... 😅
Thanks a lot @ljharb !
