### ISSUE TITLE
chore: Remove docs/package-lock.json

### ISSUE THREAD

**Issue by thernstig** [npm/cli#4344]
I learned that a workspace-aware project should only retain a package-lock.json file at the root of the repository, see comment at https://github.com/npm/cli/issues/1984#issuecomment-1022378808

The `docs/` directory in this repository is a workspace:
https://github.com/npm/cli/blob/f5a7360b95cbe77a5a76f8905340ac78ac83f229/package.json#L5-L8

Should https://github.com/npm/cli/blob/latest/docs/package-lock.json thus be removed?

**Comment by ruyadorno** [comment]
good catch! thanks @thernstig
