### ISSUE TITLE
[DOCS] `npm ci` not significantly faster when `node_modules` is missing

### ISSUE THREAD

**Issue by thernstig** [npm/cli#4349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Problem, not another kind of Docs Problem.

- [X] This is a CLI Docs Problem.

### Description of Problem

From https://github.com/npm/cli/blob/f5a7360b95cbe77a5a76f8905340ac78ac83f229/docs/content/commands/npm-ci.md?plain=1#L20-L23:

> `npm ci` will be significantly faster when:
>
>- There is a `package-lock.json` or `npm-shrinkwrap.json` file.
>- The `node_modules` folder is missing or empty.

Using npm 8.1.2 with 3 workspaces and in total about 400 packages, I get these benchmarking results with the command:

```fish
hyperfine --runs 10 --export-markdown results.md --prepare 'rm -rf node_modules/ workspace-a/node_modules/ workspace-b/node_modules/ workspace-c/node_modules/' 'npm install' 'npm ci'
```

| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `npm install` | 31.872 ± 0.433 | 31.370 | 32.657 | 1.01 ± 0.02 |
| `npm ci` | 31.542 ± 0.434 | 30.884 | 32.375 | 1.00 |

Has this old truth changed since the introduction of npm version 7, and the docs should thus be updated?

### Potential Solution

Remove the text or re-phrase it.

### Affected URL

https://docs.npmjs.com/cli/v8/commands/npm-ci#description

**Comment by bnb** [comment]
@thernstig did you have a package-lock.json? I believe that's the situation where it's technically supposed to be faster.

**Comment by nlf** [comment]
> [@thernstig](https://github.com/thernstig) did you have a package-lock.json? I believe that's the situation where it's technically supposed to be faster.

`npm ci` doesn't work if you don't have a `package-lock.json` so certainly there is one.

as for whether or not these docs are "wrong" the answer, unfortunately, is "it depends". there's a lot of factors that determine if `npm ci` will be faster or not. the correction to the docs would probably be to replace `will be significantly faster` with `may be faster`. the current wording speaks with certainty that we cannot possibly have.

**Comment by thernstig** [comment]
@nlf is there any point in mentioning _may_ be faster at all then, if that is not a feature anymore? You could say that about many commands and variations then. I do not see the value of `may be faster` as that is not the primary intention of `npm ci`. I think it just throws people off. Especially since it _may_ (pun intended) not be true 😄

**Comment by nlf** [comment]
that's totally fair. it's not meant to guarantee a performance increase, it's meant to guarantee a consistent `node_modules` structure so the statement could be removed entirely.

**Comment by thernstig** [comment]
Especially since the text says:

> `npm ci` will be significantly faster when:
>
>- There is a `package-lock.json` or `npm-shrinkwrap.json` file

Then goes on to say it _must_  have one. So I think the entire quoted text in my original post should be removed. I think that text might have held true once, but not anymore.

**Comment by thernstig** [comment]
@nlf this is fixed in the latest 8.X and 9.X docs it seems: https://docs.npmjs.com/cli/v9/commands/npm-ci?v=true

Closing.
