### ISSUE TITLE
[DOCS] npm workspaces and retaining version pinning from previous lockfiles

### ISSUE THREAD

**Issue by thernstig** [npm/cli#4350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Enhancement, not another kind of Docs Enhancement.

- [X] This is a CLI Docs Enhancement.

### Description of Problem

We are moving from a non-workspace repository to using the workspaces feature. Previously we had two workspaces like `workspace-a/package-lock.json` and `workspace-b/package-lock.json`. When we add these as:
```json
{
  "name": "my-workspaces-powered-project",
  "workspaces": [
    "workspace-a",
    "workspace-b"
  ]
}
```

we get a `package-lock.json` in the root, which is the only one that should be kept (removing the ones in the workspace folders).

The problem we have is that this does not pin the exact versions we have in our previous `package-lock.json` files. For example

```json
    "node_modules/engine.io-parser": {
      "version": "4.0.2",
```
gets changed to
```json
    "node_modules/engine.io-parser": {
      "version": "4.0.3",
```

This is not wanted, due to that we require the exact version pinning due to how our internal systems has a process to update these, something that we cannot do as part of this upgrade. It would be far too extensive.

Is there a way to document on how to retain the versions from the old `package-lock.json` files, or is this not possible at all?
If it is not possible, is it a missing feature?

### Potential Solution

Document how to achieve this if it is possible. If not there should be some way to support this when moving to the workspace feature for the first time.

### Docs URL

https://docs.npmjs.com/cli/v8/using-npm/workspaces

**Comment by nlf** [comment]
as of today we don't have a mechanism for combining workspace package-locks into a central package-lock when adopting workspaces. this will need to be moved to a feature request, you can do so by opening an RRFC issue here https://github.com/npm/rfcs/issues

**Comment by thernstig** [comment]
@nif with your experience, do you think this feature request would be worth it as an RFC? I'm surprised this has not come up before. I know users often complain when package-lock.json files (pre-workspace-era) got updated for versions they did not intend to update. There is a lot of historic bugs/issues about this. So that users have not wanted this when moving to workspaces seems strange.

I am just not sure if it is worth me writing one if it will never be done, so to say.

**Comment by jfirebaugh** [comment]
Cross-referencing the RFC: https://github.com/npm/rfcs/issues/521
