### ISSUE TITLE
[BUG] Unable to resolve dependencies when trying to install npm packages

### ISSUE THREAD

**Issue by jtuchel** [npm/cli#4357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I'm facing the same problems as described here

https://github.com/vuejs/pinia/issues/853

I'm using the latest Node and npm version. This bug is related to multiple packages. When trying to setup TailwindCSS for my Vue app I'm facing the same problems.

### Expected Behavior

It should be possible to install npm packages

### Steps To Reproduce

1. Create a Vue 3 app
2. Try to setup Pinia by running `npm install pinia` or try to setup TailwindCSS by running `npm install -D tailwindcss postcss autoprefixer`

### Environment

- npm: 8.4
- Node.js: 17.4
- OS Name: Windows 11
- System Model Name: Thinkbook
- npm config:
```ini
; "builtin" config from C:\Users\me\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\me\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\me
; HOME = C:\Users\me
; Run `npm config ls -l` to show all defaults.
```

**Comment by ljharb** [comment]
The error message in the linked issue explicitly explains that your dep graph is invalid - one thing requires vue < 3, and another thing requires vue 3 - which means those things can’t be used together.

**Comment by nlf** [comment]
> The error message in the linked issue explicitly explains that your dep graph is invalid - one thing requires vue < 3, and another thing requires vue 3 - which means those things can’t be used together.

this is exactly correct.

your options are
a) update all of your dependencies to require compatible versions of vue
b) use an override in your `package.json` like `{ "overrides": { "vue": "3" } }` to force the deps you have to install together anyway

note that with option `b` you _may_ break things, it's up to you to determine if the override is safe or not.
