### ISSUE TITLE
[BUG] Installing dependency with node-gyp-build fails unless foreground-scripts is specified on Raspberry Pi

### ISSUE THREAD

**Issue by theimpostor** [npm/cli#4374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

On Ubuntu focal on raspberry pi, installing `bufferutil` which has a node-gyp build step fails unless the [foreground-scripts](https://docs.npmjs.com/cli/v8/using-npm/config#foreground-scripts) option is used.

### Expected Behavior

`npm install bufferutil` should not require [foreground-scripts](https://docs.npmjs.com/cli/v8/using-npm/config#foreground-scripts) to work.

### Steps To Reproduce

1. In this environment...
```
$ npm -v
8.4.1
$ node -v
v16.13.2
$ uname -a
Linux pi4u1 5.4.0-1050-raspi #56-Ubuntu SMP PREEMPT Thu Jan 13 13:09:35 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```
Using [node 16/stable](https://snapcraft.io/node) via snapcraft.

2. With this config...
`prefix = /home/shoda/.npm-global`

3. Run '...'
```
cd $(mktemp -d)
npm init -y
npm install bufferutil@latest
```
4. See error...
```
npm ERR! code 1
npm ERR! path /tmp/tmp.4dq5qL1pxo/bufferutil-test/node_modules/bufferutil
npm ERR! command failed
npm ERR! command sh -c node-gyp-build
```

If however run with foreground-scripts it succeeds, see output here: https://github.com/websockets/bufferutil/issues/144#issuecomment-1029372868

### Environment

- npm: 8.4.1
- Node.js: 16.13.2
- OS Name: Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-1050-raspi aarch64)
- System Model Name: Raspberry Pi 4
- npm config:
```ini
; "user" config from /home/shoda/.npmrc

prefix = "/home/shoda/.npm-global" 

; node bin location = /snap/node/5776/bin/node
; cwd = /tmp/tmp.IxT03BDBLm
; HOME = /home/shoda
; Run `npm config ls -l` to show all defaults.
```

**Comment by fritzy** [comment]
I wonder if this is a memory issue. Currently, npm is fairly unbounded when it comes to memory and network usage. You could be running out of RAM. Can you monitor your memory usage and report back?

**Comment by theimpostor** [comment]
I now believe this is an issue with the node snap package. Using the ubuntu nodesource install of node v16.14.0, `npm install bufferutil@latest` works just fine without the foreground-scripts option. This is possibly another manifestation of https://github.com/nodejs/snap/issues/13.
