### ISSUE TITLE
Question: multiple `npm install` processes in the same folder

### ISSUE THREAD

**Issue by bd82** [npm/cli#4383]
Hello.

I have a very strange scenario in which due to an automatic system that executes "npm install" auto-magically
for certain users, multiple "npm install" processes could be invoked at **the same time** under the **same folder**.
e.g: if the end user runs "npm install" while the automated system does it as well..

How bad is this? could it cause strange race conditions in which some of these npm commands would fail
or the resulting node_modules directory become invalid?

I've only found some references to issues with the cache issues for `npm install` commands running concurrently for different folders.
- https://github.com/npm/cli/issues/1484

I guess nobody had an edge case as strange as mine 😄

**Comment by ljharb** [comment]
That seems very bad, yes. Why would you want `npm install` to be run automatically (in an environment where it's also run manually)? Running that is something developers have to learn anyways, and should know for the ability to reinstall things as well.

**Comment by nlf** [comment]
yeah.. this isn't great. it means two processes will be fighting over things like rearranging the `node_modules` directory structure, and since we do atomic writes of the `package-lock.json` you're also guaranteeing that one of the processes changes to that file will be lost (whichever writes last will "win"). i would strongly advise not doing this.

**Comment by bd82** [comment]
I did not define the scenario... 😿 

However, the general case is of "low code" developers who don't want or know how to deal with `npm install` and/or the `package.json` file.

Except that in my opinion running `npm i` auto-magically is a bit of "leaky abstraction":
- What happens if the `npm i` fails?
- What happens if for some reason the user needs to `rm -rf node_modules`?
- What would the "low code" user do when faced with a modified `package-lock` file?

Possible causes of concurrent `npm i` processes:
- users running `npm i` manually
- yeoman generators running `npm i` post generation.

**Comment by ljharb** [comment]
@bd82 imo the reality is that it's not practical to service these kind of users while *also* servicing developers. The best approach is to teach these users the skills they need.

**Comment by bd82** [comment]
Thanks for the feedback everyone
