### ISSUE TITLE
[BUG] npm install uses system-wide node installation instead of local one

### ISSUE THREAD

**Issue by Osiris-Team** [npm/cli#4390]
I was told to move this here. Previous issue: https://github.com/nodejs/help/issues/3731
### Version

17.4.0

### Platform

Windows x64

### What steps will reproduce the bug?

1. Download node installation from here: https://nodejs.org/download/release/latest-v17.x/
2. Unpack the zip/tar somewhere
3. Create a new empty folder and open a terminal in that folder
4. Enter the following command in that terminal: `<npm-path> install puppeteer` (can be any module, puppeteer just a random example, also the npm-path must be pointing to the npm file from the unpacked node installation from before)
5. Voila.

### How often does it reproduce? Is there a required condition?

NodeJS must NOT be installed system-wide.

### What is the expected behavior?

It should check for an existing `node.exe` in its installation directory first, and only use the global `node` variable if there is no `node.exe` in its installation directory.

### What do you see instead?

```txt
...
npm ERR! path C:\WORK\node_modules\puppeteer
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node install.js
...
```
As you can see npm tries to execute the command `node install.js`, the problem is, that node was not installed system-wide and thus there is no global `node` variable available.

**Comment by fritzy** [comment]
@Osiris-Team  Thanks for filing this! Since this is working as intended, can you please open an [RFC issue](https://github.com/npm/rfcs) with some details on how you could/would like to see this changed?

**Comment by Osiris-Team** [comment]
Sure thing even though is think this is more a bug than a new feature request.
