### ISSUE TITLE
[BUG] Prepack isn't run when installing from git

### ISSUE THREAD

**Issue by mvolfik** [npm/cli#4391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

After steps to reproduce:

```sh
$ ls -a node_modules/svelte-photoswipe/
.  ..  LICENSE	package.json  patchPhotoswipe.cjs  README.md  src  usage.svelte
```

This means `.npmignore` is applied and I can also check that the `postinstall` script ran, but the `prepack` didn't run.

### Expected Behavior

After installing my library [svelte-photoswipe](https://github.com/mvolfik/svelte-photoswipe) from a git repository, as per [docs](https://docs.npmjs.com/cli/v8/using-npm/scripts#life-cycle-scripts), `devDependencies` should be installed and the `prepack` script run, and therefore the directory `node_modules/svelte-photoswipe/dist` should exist.

### Steps To Reproduce

1. Create a new project
2. `npm install --save-dev github:mvolfik/svelte-photoswipe#f7429c4094926169080b97675725ee7c5f024cfa`
3. `ls node_modules/svelte-photoswipe`

### Environment

- npm: 8.3.0
- Node.js: v14.18.3
- OS Name: Ubuntu 20.04 LTS
- System Model Name: Lenovo B590
- npm config:
```ini
; "user" config from /home/volfmatej/.npmrc

//registry.npmjs.org/:_authToken = (protected) 
prefix = "/home/volfmatej/.local" 

; node bin location = /usr/bin/node
; cwd = /tmp/foo/bar
; HOME = /home/volfmatej
; Run `npm config ls -l` to show all defaults.
```

**Comment by willwill96** [comment]
Is this supposed to be fixed? I tried with `v8.19.2` & `v9.0.0`, but neither are executing `prepack` when installing from git repositories.

Edit: Nevermind, I was being dumb. My package.json was missing some metadata, like the git repo url.
