### ISSUE TITLE
[BUG] `npm adduser` fails in workspace.

### ISSUE THREAD

**Issue by louis-bompart** [npm/cli#4404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Since 8.5.0, running `npm adduser` from a workspace fails with `ENOWORKSPACES`.

### Expected Behavior

Running `npm adduser` from a workspace should be as-if it was run from the top-level directory.

### Steps To Reproduce

1. Scaffold npm workspace project:
```
mdkir testproject
cd testproject
npm init -y
npm init -y -w ./packages/a
```
2. cd into the workspace: `cd packages/a`
3. Run `npm adduser`
4. See error:
```
npm ERR! code ENOWORKSPACES
npm ERR! This command does not support workspaces.
```

### Environment

- npm: npm 8.5.0
- Node.js: 16.14.0
- OS Name: Windows 10
- System Model Name: N.A.
- npm config: N.A.

**Comment by fritzy** [comment]
I wonder if this related to the new workspace detection. It's essentially running adduser with the `--workspace` config item.

**Comment by dbouwman** [comment]
I'm running into a similar issue with `npm whoami` failing with `ENOWORKSPACES` where as another repo that's using `8.1.2` works just fine.

**Comment by fritzy** [comment]
@dbouwman yeah, I have a fix in the works that will cover the appropriate commands

**Comment by fritzy** [comment]
This just got merged for this week's release.

**Comment by dbouwman** [comment]
@fritzy Thanks! Much appreciated!
