### ISSUE TITLE
Need npx or npm wrapper bootstrap for not global npm like gradle wrapper

### ISSUE THREAD

**Issue by deanhiller** [npm/cli#4406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

jump to expected behavior where I write the desired behavior

### Expected Behavior

npm, npx, node, tsc, various tools are amazing when you never install them 'globally'.  gradle has a bootstrap system that simply checks the version in gradle.properties and installs that version. As I switch projects in gradle, the version of gradle seamlessly changes.  I have 3 versions of gradle from 3 projects and I never run "gradle use {version}" which is very very nice.  node use {version} is very frustrating as you do not necessarily know/care about the version of each project's tools

pick one tool to run them all and do local installs on-demand would be amazing to fix the version compatibility issue.  

npx npm run build should automatically check 

- do I have this npm version that this project uses
- if yes, use it
- if no, download
- continue on to the run build phase of the project

In this way, developers on my team never have to worry about installing stuff to their global cache.

NOT ONLY that but we found repository history if you **go back 1 year and versions have changed STILL WORKS and builds while doing it the current way does not**.  new tooling versions often do not work with the old files.

### Steps To Reproduce

it is a feature request

### Environment

latest

**Comment by fritzy** [comment]
We'd love to hear more about this feature. Please bring it up in https://github.com/npm/feedback discussions, or create an RFC in https://github.com/npm/rfcs. We only deal with bugs in the cli/issues.
