### ISSUE TITLE
[BUG] Published package autoinstalls optional peer dependency

### ISSUE THREAD

**Issue by JannickeN** [npm/cli#4408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I have a package with react-redux as an optional peer dependency. When I run npm pack and install the package in another project, react-redux is not automatically installed. But when I install the published version of the package, react-redux _is_ automatically installed.

Using the tgz-file, the package-lock in the consumer project is updated and shows that react-redux is optional.
Using the published package, the package-lock in the consumer project does not include the peerDependenciesMeta section, and this is the output from npm explain:
```
$ npm explain react-redux
react-redux@7.2.6 peer
node_modules/react-redux
  peer react-redux@"^7.2.6" from [package name]@11.1.1
  node_modules/[package name]
    peer [package name]@"^11.1.1" from the root project
```

### Expected Behavior

I expect the optional dependency not to be installed automatically, and the package-lock file in the consumer project to behave the same way with the package produced with npm pack as the published package.

### Steps To Reproduce

1. Add a peer dependency to a project, and set it as optional
   ```
   "peerDependencies": {
     "react-redux": "^7.2.6"
    },
    "peerDependenciesMeta": {
      "react-redux": {
        "optional": true
      }
    },
   ```
2. Publish the package.
3. Install the package in another project.
4. Run `npm ls react-redux` to see that react-redux is installed.
5. Run `npm explain react-redux` to see that it is listed as a peer dependency, and not an optional peer dependency.

### Environment

- npm: 8.5.0
- Node.js: 16.14.0
- OS Name: Windows 10

**Comment by fritzy** [comment]
This looks like a likely dupe to #2744. We'll refer to this ticket as well when we handle that issue.

**Comment by JannickeN** [comment]
Okay, in my case the tgz works as expected, though, and there is no error. And the published package creates the wrong tree, missing the peerDependenciesMeta section. But maybe it's related.

**Comment by evelynhathaway** [comment]
I ran into optional peer dependencies being automatically installed as well, and I wanted to leave a breadcrumb here in case it helps others diagnose or report a similar issue.

If you are using a registry proxy like Artifactory, switch back to the [public npmjs.org registry](https://docs.npmjs.com/cli/v8/using-npm/registry) and install again on a fresh reproductionn project. Your company's registry may not be providing the `peerDependenciesMeta` property in the metadata. This is currently an [issue with Artifactory npm registries](https://www.jfrog.com/jira/browse/RTFACT-27265) right now. Even though the `peerDependenciesMeta` property shows up in `node_modules`, it's not being sent to npm before installation.

**Comment by WtfJoke** [comment]
> If you are using a registry proxy like Artifactory, switch back to the [public npmjs.org registry](https://docs.npmjs.com/cli/v8/using-npm/registry) and install again on a fresh reproductionn project. Your company's registry may not be providing the `peerDependenciesMeta` property in the metadata. This is currently an [issue with Artifactory npm registries](https://www.jfrog.com/jira/browse/RTFACT-27265) right now. Even though the `peerDependenciesMeta` property shows up in `node_modules`, it's not being sent to npm before installation.

@evelynhathaway thank you for the breadcrumb <3

The GitHub Package Registry is affected from this as well, see https://github.com/orgs/community/discussions/51104
