### ISSUE TITLE
cb() never called! Can't update NPM or install new

### ISSUE THREAD

**Issue by darcyclarke** [npm/cli#442]
Original bug ticket: [https://npm.community/t/9164](https://npm.community/t/9164)
      Originally filed: 2019-07-29T19:05:16.541Z

---

From original issue: https://npm.community/t/9164
Debug log: n/a
Action triggered: `sudo npm install -g npm`

Platform info: (incomplete)
```
$ npm --versions
6.9.0
$ node -p process.platform
darwin
```

Additional information:
- reference to a blog post which indicates solving the problem with an update of `npm` and clearing the cache.

**Comment by mikemimik** [comment]
Duplicate issue; aggregating into https://github.com/npm/cli/issues/417.
