### ISSUE TITLE
[BUG] Why does the "npm publish" command manifest not contain the "unpackedSize" and "fileCount" fields in the npm client？

### ISSUE THREAD

**Issue by Beace** [npm/cli#4420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

The npm registry  API  `PUT /xxx` body is 

```json
{
  "versions": {
    "1.0.4": {
      "name": "my-package-name",
      "version": "1.0.4",
      "description": "",
      "main": "dist/index.js",
      "_nodeVersion": "16.0.0",
      "_npmVersion": "8.4.1",
      "dist": {
        "integrity": "xxx",
        "shasum": "xxx"
        "tarball": "xxx"
      }
    }
  },
}
```

But the  `GET /:xxx` API  return this

```json
"dist": {
        "integrity": "sha512-s8+wktIuDSLffCywiwSxQOMqtPxML11a/dtHE17tMn4B1MSWw/C22EKf7M2KGUBcDaVFEGT+S8N02geDXeuNKg==",
        "shasum": "f4a3d302976aaf042356ba1ade3b1a2c62d9d794",
        "tarball": "https://registry.npmjs.org/colors/-/colors-1.2.1.tgz",
        "fileCount": 21,
        "unpackedSize": 37634
}
```

### Expected Behavior

Sometimes I need to get the file size for some filtering and limiting behavior. I guess npm server calculates the unpacked file size on the server. I'm curious about why it's not transmitted to the server directly after the client-side calculation.

### Steps To Reproduce

just run npm publish 

### Environment

- npm: 8.4.1
- Node.js: 16.0.0
- OS Name: OSX

**Comment by fritzy** [comment]
**Closing:** this looks to be an issue with the registry which is outside the scope of this repo. For registry support please go to [npmjs.com/support](https://www.npmjs.com/support). If you believe this is a bug with the cli, please provide further clarifying details.

As for why the CLI doesn't calculate this, you can technically publish tarballs and other sources directly.
