### ISSUE TITLE
2FA setup only offers a QR code, not the secret key—so I can't set it up

### ISSUE THREAD

**Issue by darcyclarke** [npm/cli#444]
Original bug ticket: [https://npm.community/t/9120](https://npm.community/t/9120)
      Originally filed: 2019-07-26T15:56:49.512Z

**Comment by markrian** [comment]
Why was this closed? This is _still_ true, and still a problem. My phone's camera is broken, so I am unable to set up 2FA.

**Comment by toxinu** [comment]
Same issue. Can't set up 2fa because there is only a QR code.
