### ISSUE TITLE
[BUG] All npm commands are being sent to background after switching to node v16.x

### ISSUE THREAD

**Issue by jvlch** [npm/cli#4440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Only on node versions 16.x (not a problem with 14.x and lower)
Tested on fnm and nvm installations of node v16.14.0 (odd behavior) vs v14.16.1 (working as expected)

All npm commands are being sent to some background process with the only stdout being something like "[1]+  Stopped npm xxx"
Upon next prompt load, the command often comes back with the previous command's return, e.g. "[1] Done npm xxxx".

### Expected Behavior

npm commands to run in the foreground by default, and not leak stdout into the next shell command's stdout.

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/43323655/154729409-5441e591-cd30-4ed5-81cf-d564ac9c79f5.png)

![image](https://user-images.githubusercontent.com/43323655/154730833-466aaed3-1805-4077-8a15-9a409222fe04.png)

### Environment

- npm: 8.3.1
- Node.js: v16.14.0
- OS Name: MacOS Big Sur 11.6.1
- System Model Name: Macbook Pro Intel Core i9
- npm config:
```ini
save-exact = false
save-prefix = "^"
```

**Comment by fritzy** [comment]
This is changed behavior with > npm@7. You'll need to use the flag or config `--foreground-scripts` for the old behavior.
https://docs.npmjs.com/cli/v8/using-npm/scripts

**Comment by jvlch** [comment]
Even with that set, still seeing the odd behavior
![image](https://user-images.githubusercontent.com/43323655/155622422-646e077c-8e64-49ba-a3ac-86a0581605f2.png)
