### ISSUE TITLE
[BUG] Hoists dependant without peer dependency: conflicting binaries

### ISSUE THREAD

**Issue by jablko** [npm/cli#4441]
I've got two problems installing npm package `xo` with npm < 8. The first is with npm 6, the second is with the deployed workaround and npm 7. Both appear to be fixed in npm 8, so I'm not sure which, if either, to report?

The first problem is that npm 6 hoists a dependant without a peer dependency. It's [described here](https://github.com/xojs/xo/issues/555#issuecomment-935062115) and can be reproduced with the following command:
```sh
npm install @tsd/typescript xo@0.45
```
npm 6 hoists `@typescript/parser` from `xo` but not `typescript`, because it and `@tsd/typescript` both have a `tsc` binary:
```sh
$ ls --directory node_modules/@typescript-eslint/parser
node_modules/@typescript-eslint/parser
$ ls --directory node_modules/typescript
ls: cannot access 'node_modules/typescript': No such file or directory
```
Here's the conflicting binaries check: https://github.com/npm/cli/blob/6996ecaddcb36ca330293f1c4acc371471e94a9a/lib/install/deps.js#L813-L820

npm >= 7 hoists both `@typescript/parser` and `typescript`, maybe because it [automatically installs peer dependencies](https://github.blog/2021-02-02-npm-7-is-now-generally-available/)?

The second problem is that I'm getting the following, installing `xo` with npm 7, in some cases:
```sh
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/runner/work/remark-lint/remark-lint/node_modules/xo/node_modules/typescript/bin/tsc'
```
You can reproduce this with npm 7:
```sh
$ git clone https://github.com/remarkjs/remark-lint.git
$ cd remark-lint
remark-lint (main)$ npm install
```

`remark-lint` dev-depends on `xo`. `node_modules/xo/node_modules/typescript/bin/tsc` [should exist](https://unpkg.com/browse/typescript@4.5.5/bin/tsc).

To work around the first problem (with npm 6), `xo` declared [`bundledDependencies` on `@typescript-eslint/parser`](https://github.com/xojs/xo/pull/624/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R56). I haven't confirmed that this caused the second problem, but it smells like it.

Possibly worth noting:
- If you install `xo`, `typescript@4.5.5` -> `node_modules/typescript` and succeeds.
- If you install `remark-lint`, `typescript@4.4.4` -> `node_modules/typescript`, presumably `typescript@4.5.5` -> `node_modules/xo/node_modules/typescript`? and fails.

**Comment by nlf** [comment]
npm versions 6 and 7 are both unsupported, except for security fixes. if this is working correctly in npm 8, unfortunately we won't be taking the time to backport a fix to older versions so i'll have to suggest that you continue using npm 8 to the extent possible.

> npm >= 7 hoists both @typescript/parser and typescript, maybe because it [automatically installs peer dependencies](https://github.blog/2021-02-02-npm-7-is-now-generally-available/)?

correct, we install peer dependencies by default now which is what causes the additional packages to be installed and hoisted. you can skip that behavior with `--legacy-peer-deps` if you like.

**Comment by jablko** [comment]
@nlf Understood, thanks for the response!
