### ISSUE TITLE
[BUG] npm unpublish shows invalid or wrong error messages

### ISSUE THREAD

**Issue by simllll** [npm/cli#4444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I'm trying to unpublish old versions of private packages (old, temporary version of it that we only used for CI), and experienced some weird things regarding npm unpublish:
1.) if I'm not authenticated, it just shows a success message..even though the package is still there, and nothing has chagned (e.g. no npmrc file with the auth key in it):
outputs, but it's not true:
`- @hokify/b2bonboarding@0.0.2-next-app-api.22c714125675cafacf1797d9907dad65eef53ccc.906.0`
success code is 0.

2.) when unpublishing more versions, it often shows errors about **publishing** over a previosuly published version.. I'm unpublish? Why it's states that I'm trying to publish something? 
**Cannot publish over previously published version "1.0.7-next-website-api.682391fe9e6532baac3460f90f031512a0ffce32.860.0".**
```
- @hokify/b2bonboarding@1.0.7-next-website-api.682391fe9e6532baac3460f90f031512a0ffce32.861.0
npm ERR! code E400
npm ERR! 400 Bad Request - PUT https://registry.npmjs.org/@hokify%2fb2bonboarding/-rev/4510-5af58010561bb36f7e19195d7c08bf21 - Cannot publish over previously published version "1.0.7-next-website-api.682391fe9e6532baac3460f90f031512a0ffce32.860.0".

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2022-02-19T17_32_47_774Z-debug.log
- @hokify/b2bonboarding@1.0.7-next-website-api.f9742addc663cf05fc0b1102dcf185adf6d6a156.863.0
- @hokify/b2bonboarding@1.0.7-next-worker.682391fe9e6532baac3460f

```
3.) It seems that it does something else too, I first ran these commands within our monorepo, and it seems it ran a "npm install" afterwards all the time (or something else at least), now I switched to a different directory with a plain simple package.json, the command runs now at least 10x faster than before (well, don't get too excited, it's still quite slow!).

### Expected Behavior

should print correct messages if authentaicted or not, or if the request was sucessful or not and execute the expected behaviour.

### Steps To Reproduce

1. run npm unpublish with specific package versions. try to unpublish 5-10 versions each after the other, but without any breaks between.

### Environment

- npm: 8.5.1 (also tried 8.4.1)
- Node.js: v16.11.1
- OS Name: linux
- System Model Name: linux

**Comment by fritzy** [comment]
**Closing:** this looks to be an issue with the registry which is outside the scope of this repo. For registry support please go to [npmjs.com/support](https://www.npmjs.com/support). If you believe this is a bug with the cli, please provide further clarifying details.
