### ISSUE TITLE
[BUG] npm update --save not update the `package.json`

### ISSUE THREAD

**Issue by HomyeeKing** [npm/cli#4449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

npm update foo --save

the foo semver in `package` is not updated

### Expected Behavior

update semver to the latest version

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 8.3.1
- Node.js: 17.4
- OS Name: mac M1 12.1
- System Model Name: 
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by ljharb** [comment]
Can you try npm v8.5.1?

**Comment by HomyeeKing** [comment]
BTW, I'm on node v17.4.0, can't upgrade to the latest npm via `nvm`, is 17.4.0 not support latest npm or is a bug?

**Comment by ljharb** [comment]
@HomyeeKing you should be able to. `npm install -g npm`, or `nvm install-latest-npm`, should do it.

**Comment by HomyeeKing** [comment]
![image](https://user-images.githubusercontent.com/49113249/155056770-00caf878-7e3e-4df7-b591-a6b7e3baaa22.png)


neither works

**Comment by ljharb** [comment]
@HomyeeKing that might be a different issue. If you're using a registry that's not the public one, it may not have any version later than v8.3.1. What does `npm show npm` print out about the version number?

**Comment by HomyeeKing** [comment]
- the `nvm` install latest npm issue is because I have a prefix settings
-  `npm update` still not working in npm@latest, also npm update always sucks in my mind

**Comment by HomyeeKing** [comment]
@ljharb  it seems works now, how about  making `update latest  dep semver to package.json` as default ?

**Comment by fritzy** [comment]
Sounds like this is handled. As far as discussions on changes to to behavior (defaults), please join us with the RFC process. https://github.com/npm/rfcs/
