### ISSUE TITLE
[BUG] npm ci changes node_modules in an unexpected way

### ISSUE THREAD

**Issue by PLsap** [npm/cli#4453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [x] I am using the latest npm

### Current Behavior

The node_modules is unexpectedly changed when performing following steps:

```
npm init
npm install @sap/hdi-deploy@4.2.3
npm ci
npm install
```

The second cmd creates a new package-lock.json with 26 packages:
+ @sap/hdi-deploy@4.2.3
added 26 packages from 70 contributors and audited 26 packages in 5.993s

The third cmd outputs as well to add 26 packages
added 26 packages in 2.578s

The forth cmd is installing an additional unexpected package:
added 1 package from 1 contributor and audited 27 packages in 0.654s

The package-lock after the last command has changed by one dependency:
```
49a50,56
>           },
>           "dependencies": {
>             "async": {
>               "version": "3.1.0",
>               "resolved": "https://registry.npmjs.org/async/-/async-3.1.0.tgz",
>               "integrity": "sha512-4vx/aaY6j/j3Lw3fbCHNWP0pPaTCew3F6F3hYyl/tHs/ndmV1q7NW9T5yuJ2XAGwdQrP+6Wu20x06U4APo/iQQ=="
>             }
```

The dependency resolution is adding this package once again in a subfolder despite being part of the first level dependency:
```
t9@1.0.0 
└─┬ @sap/hdi-deploy@4.2.3
  ├─┬ @sap/hana-client@2.9.28
  │ └─┬ debug@3.1.0
  │   └── ms@2.0.0
  ├─┬ @sap/hdi@4.1.0
  │ └── async@3.1.0
  ├─┬ @sap/xsenv@3.1.0
  │ ├─┬ debug@3.1.0
  │ │ └── ms@2.0.0
  │ └─┬ verror@1.10.0
  │   ├── assert-plus@1.0.0
  │   ├── core-util-is@1.0.2
  │   └── extsprintf@1.4.0
  ├── async@3.1.0
  ├── dotenv@10.0.0
  ├─┬ handlebars@4.7.7
  │ ├── minimist@1.2.5
  │ ├── neo-async@2.6.2
  │ ├── source-map@0.6.1
  │ ├── uglify-js@3.14.3
  │ └── wordwrap@1.0.0
  └─┬ micromatch@4.0.4
    ├─┬ braces@3.0.2
    │ └─┬ fill-range@7.0.1
    │   └─┬ to-regex-range@5.0.1
    │     └── is-number@7.0.0
    └── picomatch@2.3.0
```

### Expected Behavior

Either the initial package-lock.json or the final package-lock.json should be consistent

### Steps To Reproduce

Start with a new project using npm 6 (latest of 6) and node 14:

```
npm init
npm install @sap/hdi-deploy@4.2.3
npm ci
npm install
```

npm 8 is not affected.

Unfortunately we must stay using npm 6 / node 14 for a while. Therefore a proper analysis and fix is needed. I have no clue what might cause the issue and hoping for help here.

Thanks!

### Environment

- npm: 6.14.16
- Node.js: 14.19.0
- OS Name: Ubuntu (under WSL)
- System Model Name: Windows
- npm config:
```ini
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.14.16 node/v14.19.0 linux x64"
; builtin config undefined
prefix = "/home/linuxbrew/.linuxbrew"
; node bin location = /home/linuxbrew/.linuxbrew/Cellar/node@14/14.19.0/bin/node
```

**Comment by ljharb** [comment]
npm 6 isn’t receiving bugfixes any more afaik.

**Comment by fritzy** [comment]
@PLsap as @ljharb mentioned, we do not backport fixes to v6 or v7 as a rule.

If there's something keeping you from using the latest version, please let us know.
