### ISSUE TITLE
[BUG] npm audit can cause ENOTEMPTY error

### ISSUE THREAD

**Issue by scottschreckengaust** [npm/cli#4455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

During `npm audit fix`, affected `./node_modules/PACKAGENAME/*` directories are not emptied, and returns with:
```
$ npm audit fix
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /Users/username/directory/node_modules/PACKAGENAME
npm ERR! dest /Users/username/directory/node_modules/.PACKAGERNAME-HASHCODE
npm ERR! errno -66
npm ERR! ENOTEMPTY: directory not empty, rename '/Users/username/directory/node_modules/PACKAGENAME' -> '/Users/username/directory/node_modules/.PACKAGENAME-HASHCODE'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/username/.npm/_logs/2022-02-22T15_50_06_093Z-debug-0.log
```

Each time this is due to items left in the PACKAGENAME folder (I have not seen files only directories thus far):
```
$ ls -al  /Users/username/directory/node_modules/PACKAGENAME
bin
dist
lib
test
```

### Expected Behavior

Files should be cleared out and able to proceed without manually moving/removing them.

### Steps To Reproduce

1. In this environment macOS
```
      System Version: macOS 11.6.3 (20G415)
      Kernel Version: Darwin 20.6.0
```

2. With this config `npm version`
```
8.3.1
```
3. Run `npm audit fix`
4. See error...

### Environment

- npm: 8.3.1
- Node.js: v16.14.0
- OS Name: macOS 11.6.3 (20G415)
- System Model Name: MacBook Pro
- npm config:
```ini
; copy and paste output from `npm config ls` here
; node bin location = /Users/username/.local/share/virtualenvs/directory-HASHCODE/bin/node
; cwd = /Users/username/directory
; HOME = /Users/username
; Run `npm config ls -l` to show all defaults.
```

**Comment by fritzy** [comment]
@scottschreckengaust Please supply full steps to reproduce. Is there a particular set of packages that I could add to a freshly init'd project that would cause this problem?

**Comment by scottschreckengaust** [comment]
Use something like `npm install -g @aws-amplify/cli` with a `npm fix audit` message.

**Comment by fritzy** [comment]
You can't audit fix a global. We should remove that suggestion for globals. Maybe npm is detecting a different project root with corrupted packages.

I am unable to reproduce this error. Feel free to re-open if you have more specific reproduction instructions.
