### ISSUE TITLE
How to change lockfileVersion properly ?

### ISSUE THREAD

**Issue by kokushkin** [npm/cli#4456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Problem, not another kind of Docs Problem.

- [X] This is a CLI Docs Problem.

### Description of Problem

Moving form lockfileVersion 2 to 3. Couldn't find any explanation of how to do it properly. Of course it can be changed in package-lock.json  + npm i  and it seems like it's working. But is it a right way of doing so? It might be that npm uses this record itself, basically to find out what  the version of a package-lock is. Then, changing it manually would mean fooling npm.

So how to change lockfileVersion properly ?

### Potential Solution

add a command to npm

**Comment by fritzy** [comment]
@kokushkin to answer your question, the intention is that users do not touch package-lock.json. We do a have a config option for `--lockfile-version` that you can also set in your .npmrc. I'll make sure to update the documents for package-lock to reference this option.

**Comment by kokushkin** [comment]
yeah, thanks a lot! I see it now here [lockfileVersion](https://docs.npmjs.com/cli/v8/using-npm/config#lockfile-version) . Couldn't find it before, probably because of the different naming conventions; "lockfile-version" in .npmrc  vs "lockfileVersion" in package-lock , but it seems ok to me now)
