### ISSUE TITLE
Disabling deduping to a single dependency

### ISSUE THREAD

**Issue by K-Schaeffer-LOG** [npm/cli#4461]
Hi,       

I'm having trouble with two dependencies in my project in which I have:

- Dependency A
  - Dependency A dependencies
- Dependency B
  - Dependency B dependencies (dependency A included as a dependency here)
- My project that uses both dependencies A and B

The issue is when I have the same version of dependency A both in dependency B and in my project. Since the deduping will remove dependency A from the dependency B node_modules, It will throw some errors, because dependency B uses some functions from dependency A, and has no access through the upper scope in which dependency A is in the project.

I know that there's the [legacy-building](https://docs.npmjs.com/cli/v8/commands/npm-install#legacy-bundling), but I was wondering if a non-legacy solution is possible.
We could perhaps have a --disable-deduping flag to not use this mechanism in the dependency installed with it, or something like this.

I'm looking forward to hear what you guys think of it.

**Comment by ljharb** [comment]
What do you mean “has no access”? B will be able to require a hoisted A, assuming both are in the same project, unless you’re using a pnpm-style layout, or unless B is npm linked.

**Comment by K-Schaeffer-LOG** [comment]
> What do you mean “has no access”?

B imports A utils from node_modules, so when A is in the upper scope node_modules the import can't find it

**Comment by ljharb** [comment]
Yes it can - node looks in parent directories for node_modules all the way up to the root.

**Comment by K-Schaeffer-LOG** [comment]
Perhaps I'm missing something then :thinking: 

I'll give you my practical example:

1. I have a NPM package called Design
2. I have another NPM package called Shared-Components that always uses the latest stable version of Design
3. Shared-Components imports some variables from Design (@import '../../../node_modules/@logcomex/design/src/assets/scss/export.module.scss ), so It can use those and export them again merging with it's own variables
4. My project depends on both packages, and uses the import from the previous step (Design and Shared merged variables). When the project and Shared are using the same version of Design, I get an error in my project because that @import can't get resolved.

So, this is what I mean by has no access. 
I'm wondering if the issue is the relative path import, or If I missing something else.

**Comment by ljharb** [comment]
ah, you're hardcoding node_modules. Instead, try importing from `@logcomex/design/src/assets/scss/export.module.scss`, and then it should resolve properly.

**Comment by K-Schaeffer-LOG** [comment]
This didn't work when I previously tried, but I found out why.

It works like this: @logcomex/design/src/assets/scss/_export.module.scss

I need to add the underscore before the name of the file, even though sass don't require It when using @import. 
In this case It can't resolve If the name of the file isn't exactly the same when importing.

So that's It, I hope this issue helps If someone struggles in something similar in the future.

Thank you very much for your assistance @ljharb
