### ISSUE TITLE
[BUG] NPM_CONFIG_PREFIX is ignored during install

### ISSUE THREAD

**Issue by chr15m** [npm/cli#4467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Trying to set the `prefix` config option using environment variables as documented here:

https://docs.npmjs.com/cli/v8/using-npm/config#environment-variables

The current behaviour is that the output from these two commands is different.

```
NPM_CONFIG_PREFIX=dingle npm config ls -l | grep prefix
```

```
npm --prefix dingle config ls -l | grep prefix
```

In addition, currently this command:

```
NPM_CONFIG_PREFIX=dingle npm install doodle.css
```

does not install into the folder `dingle` whereas this command does:

```
npm install --prefix dingle doodle.css
```

### Expected Behavior

Expected behaviour setting the `prefix` via either `NPM_CONFIG_PREFIX` or `--prefix` has the same results and installs into the specified folder.

### Steps To Reproduce

1. `$ npm --version` -> `8.1.2`
2. Run `NPM_CONFIG_PREFIX=dingle npm config ls -l | grep prefix` and `npm --prefix dingle config ls -l | grep prefix`
3. Observe the output is different

### Environment

- npm: 8.1.2
- Node.js: v16.13.1
- OS Name: Ubuntu Linux
- System Model Name: Dell XPS 13
- npm config:
```ini
; "user" config from /home/chrism/.npmrc

//registry.npmjs.org/:_authToken = (protected) 
unsafe-perm = true 

; node bin location = /home/chrism/.nvm/versions/node/v16.13.1/bin/node
; cwd = /home/chrism/dev/npm-prefix-test
; HOME = /home/chrism
; Run `npm config ls -l` to show all defaults.
```

**Comment by ljharb** [comment]
Do you mean NPM_CONFIG_PREFIX? NODE_CONFIG isn’t a thing.

**Comment by fritzy** [comment]
It looks like `npm_config_prefix` isn't working as expected. This may be due to a recent change with implicit workspace detection (or may be unrelated).

**Comment by fritzy** [comment]
To clarify, I was able to reproduce the issue with the correct environment variable.

**Comment by chr15m** [comment]
Yes, thanks for picking that up. I used the wrong variable name in the bug description, but the bug is there with `NPM_CONFIG_PREFIX`.

**Comment by chr15m** [comment]
I've updated the text of the ticket for clarity: `NODE_CONFIG_PREFIX` -> `NPM_CONFIG_PREFIX`.

**Comment by Santoshraj2** [comment]
<img width="1415" alt="4467_latestVersion" src="https://github.com/npm/cli/assets/143222321/69ddcf99-00b2-4a0d-bdbf-667ec76ff479">
<img width="1452" alt="4467_version_8 1 2" src="https://github.com/npm/cli/assets/143222321/925c611e-5719-440a-a4c3-e5a8e1eef62c">

I see this is giving same result in both the latest as well as mentioned version(8.1.2), @chr15m let me know if you are still facing this.

**Comment by MarcellPerger1** [comment]
I can still reproduce this (or at least a very very similar bug). 

The problem is here:

https://github.com/npm/cli/blob/5b858c6b2c275f0e670e09c52de5b931936d6e07/workspaces/config/lib/index.js#L685-L690

This function never checks the environment variables for `prefix`, it only checks the CLI. So commands that use the `package.json` in the `localPrefix` directory will fail in these cases, as `localPrefix` isn't set correctly using the environment variables.

Fix:
```diff
   async loadLocalPrefix () {
-    const cliPrefix = this.#get('prefix', 'cli')
+    const cliPrefix = this.#get('prefix', 'cli') || this.#get('prefix', 'env')
     if (cliPrefix) {
       this.localPrefix = cliPrefix
       return
     }
```

Could someone reopen this? I don't have the permission to do so.

P.S. I can create a PR in the next few days.

**Comment by MarcellPerger1** [comment]
> let me know if you are still facing this

@Santoshraj2 It is only fixed for commands that don't require there to be a `package.json` in the `Config.localPrefix` directory. For other commands, the issue still occurs
