### ISSUE TITLE
[BUG] Install (and other commands) should fail clearly on invalid package names

### ISSUE THREAD

**Issue by OmgImAlexis** [npm/cli#4473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```
❯ npm i -D @database

changed 1 package, and audited 401 packages in 2s

26 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

uptime-zaba on  main [!?] is 📦 v0.0.1 via  v17.5.0 took 2s
❯ npm rm @database
npm ERR! Must provide a package name to remove

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xo\AppData\Local\npm-cache\_logs\2022-02-25T23_33_04_415Z-debug-0.log
```

### Expected Behavior

The package installation process to throw an error while trying to install as `@database` isn't a valid package name.

### Steps To Reproduce

Steps shown in "Current Behavior".

### Environment

- npm: 8.4.1
- Node.js: v17.5.0
- OS Name: Windows 11 (Dev Channel)
- System Model Name: Custom PC
- npm config:
```ini
; "user" config from C:\Users\xo\.npmrc

msvs_version = "2017"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\xo\code\OmgImAlexis\uptime-zaba
; HOME = C:\Users\xo
; Run `npm config ls -l` to show all defaults.
```

**Comment by ljharb** [comment]
`@database` is not a valid package name. Package names must either be unscoped (not starting with `@`), or scoped (starting with `@`, and containing exactly one slash).

**Comment by OmgImAlexis** [comment]
I know this yet the command didn't error hence the issue being opened.

The following shouldn't have worked, correct?
```
npm i -D @database
```

**Comment by ljharb** [comment]
Yes, I agree that command should have errored - that seems like a bug to me.

**Comment by nlf** [comment]
i'm unable to reproduce this one, `npm i -D @database` in an empty project throws an error:

```
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "@database" of package "@database": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nlf/.npm/_logs/2022-03-01T19_59_55_915Z-debug-0.log
```

can you provide more details about you're reproducing this?

**Comment by OmgImAlexis** [comment]
What other details do you need? This is on Windows 11 with node `v17.5.0`. 

```
❯ mkdir x

    Directory: C:\Users\xo

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           2/03/2022  6:49 AM                x


~
❯ cd x

~\x
❯ npm init -y
Wrote to C:\Users\xo\x\package.json:

{
  "name": "x",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}



~\x is 📦 v1.0.0 via  v17.5.0
❯ npm i -D @database

up to date, audited 1 package in 286ms

found 0 vulnerabilities
```

**Comment by nlf** [comment]
i'm still not able to reproduce this one for installs. i tested in osx, linux and windows using your exact steps listed above. i used `npm@8.4.1` as you specified in your original issue, and node@17.5.0. in every version i tested i got the same `EINVALIDTAGNAME` error mentioned above when running `npm i -D @database`

`npm rm @database` is another story, however, as that command runs successfully in all cases and simply does nothing.

since the error message we _do_ print is frankly garbage here, i'm going to keep this open and put it into our backlog as something we should explicitly validate and error with something way more readable. i'm hopeful that despite the fact i can't reproduce the behavior you're seeing with `npm install` that the explicit validation will fix the issue for you anyway.

**Comment by OmgImAlexis** [comment]
This is interesting..

1. Are you testing this on windows or windows subsystem for linux?
2. Which version of windows?

Tried it again, I've rebooted and all that since.

```
~\code\_
❯ mkdir x

    Directory: C:\Users\xo\code\_

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           8/03/2022  7:39 AM                x


~\code\_
❯ cd x

code\_\x
❯ npm init -y
Wrote to C:\Users\xo\code\_\x\package.json:

{
  "name": "x",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}



code\_\x is 📦 v1.0.0 via  v17.5.0 took 6s
❯ npm i -D @database

up to date, audited 1 package in 435ms

found 0 vulnerabilities

code\_\x is 📦 v1.0.0 via  v17.5.0
```

**Comment by nlf** [comment]
> 1. Are you testing this on windows or windows subsystem for linux?

windows directly, no subsystem for linux involved.

> 2. Which version of windows?

windows 11, all updates installed as of this morning (march 7th 2022)

**Comment by OmgImAlexis** [comment]
Exactly the same as my setup. Just trying to work out how it's reproducable here but not for you. 🤔 

Is this in powershell, terminal, cmd?

**Comment by nlf** [comment]
> Exactly the same as my setup. Just trying to work out how it's reproducable here but not for you. 🤔
> 
> Is this in powershell, terminal, cmd?

i tried in cmd as well as the bash provided by git-bash

**Comment by OmgImAlexis** [comment]
That's the difference. Try in powershell or powershell 7.

Just tried in cmd and it doesn't work.

```
C:\Users\xo\code\_\x>npm i -D @database
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "@database": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xo\AppData\Local\npm-cache\_logs\2022-03-07T22_07_22_453Z-debug-0.log
```

**Comment by nlf** [comment]
ahhh! there's nothing we can do about that, unfortunately, `@` is an operator for powershell so it's being evaluated before we ever even see it. if you run the command like:

```
npm i -D `@database
```

that escapes the `@` and you'll see the same error we do in other shells

**Comment by OmgImAlexis** [comment]
Oh that's really interesting. Didn't even think of that.

```
❯ npm i --loglevel verbose -D @database
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'i',
npm verb cli   '--loglevel',
npm verb cli   'verbose',
npm verb cli   '-D'
npm verb cli ]
```
