### ISSUE TITLE
[BUG] npm installs packages wrongly

### ISSUE THREAD

**Issue by its-dibo** [npm/cli#4474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I created a node project that includes a workspace, the project structure looks like:

/package.json
```
{
 "name": "root",
  "workspaces": ["./child"]
}
```

/child/package.json
```
{
  "name": "child",
  "dependencies": {
    "@angular/compiler": "^13.1.2",
    "@angular/router": "^13.1.2"
  }
}
```
 
when running `npm install` it installs `@angular/compiler` in the root node_modules dir which is the expected behavior.
but it installs `@angular/router` in child/node_modules, it should be installed in the root node_modules

also, the dependencies of it such as `rxjs` are installed in the child dir even no other versions of the same packages 

the project is created in a clean and empty folder, and I cleared the npm cache

[minimal reproduction](https://github.com/eng-dibo/issue-npm-install)

### Expected Behavior

all packages to be installed in the root dir

### Steps To Reproduce

use the [minimal reproduction](https://github.com/eng-dibo/issue-npm-install) and run `npm install` from the root dir

### Environment

- npm: 8.3.1
- Node.js: v16.14.0
- OS Name: debian
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here

 node bin location = /usr/local/nvm/versions/node/v16.14.0/bin/node
; cwd = /home/sh_eldeeb_2010/@eng-dibo/dibo
; HOME = /home/sh_eldeeb_2010
; Run `npm config ls -l` to show all defaults.
```

**Comment by nlf** [comment]
this is happening because your `package-lock.json` lists the modules under the `project` directory. removing your `package-lock.json` and running `npm i` gives you the desired behavior, as does running `npm update`.

unfortunately there's nothing to fix here. we put the files where the `package-lock.json` told us to put them, which is definitely not a bug.
