### ISSUE TITLE
npm error message when updating manjaro-arm

### ISSUE THREAD

**Issue by RobotsAreCrazy** [npm/cli#4478]
Hi,  

getting this error message when trying to update my system any idea what i can do to fix it?

![Screenshot_20220227_134539](https://user-images.githubusercontent.com/9435484/155890444-1bf818be-b4cd-4bb2-8861-f28f24721f31.jpg)

Thanks

**Comment by nlf** [comment]
:grimacing: this one looks like an issue in how npm (and likely node) are packaged, which we have nothing to do with. i would open an issue with manjaro.
