### ISSUE TITLE
npmjs package page, custom install command

### ISSUE THREAD

**Issue by ZimaTechOli** [npm/cli#4483]
I've been asked by the npm support to open an issue here for my... well, issue.

In the top right corner of packages, there's this convenient box that contains the install command (convenient because clicking it copies the command to clipboard):

![npmjs-install](https://user-images.githubusercontent.com/67362793/155989556-e4be882c-5450-499f-8328-d16490ec088e.png)

However, this particular package is only required in development. That's why we suggest to install it with the `-D` flag, like `npm i -D @zimatech/zdoccer`

My question/issue: How, if possible, do I customise that command? I suspect via package.json, but I couldn't figure out how (and as said before, support sent me here)

**Comment by ljharb** [comment]
You don’t.

Whether a package is used for dev, or production, is not something an author can know. What if someone is making a package that wraps this one, and is in turn used as a dev dep? Your package would be a production dep of that package, and -D would be wrong.

In other words, there’s not a reliable way (even from the author) to know what the consumer’s intention is, so the safest choice is to default to being a production dep.

**Comment by ZimaTechOli** [comment]
Thank you for your answer. Makes sense.

However, if I may: I think a consumer with an intention should know when to use --save-dev. My initial guess would be, that this quick command-copy function is for those with "less intention". But then again, they probably won't be publishing packages anyways and they wouldn't be bothered by some wrongly placed dependencies.

**Comment by ljharb** [comment]
I think you nailed it, yes.

**Comment by nlf** [comment]
i think this was answered, so i'm going to close it. as an aside, however, if you want to open a feature request for the website to allow a custom install command, or possibly just some means of communicating that a package is meant to be installed as a dev dependency, you can do so by starting a discussion here: https://github.com/npm/feedback/discussions

**Comment by Dominic-Mayers** [comment]
I disagree that the argument provided justifies the current generic instruction.  The argument is "Whether a package is used for dev, or production, is not something an author can know".  But that argument actually goes against the generic instruction that chooses one the two options. Moreover, in some cases, the typical user is likely to need the other option.
