### ISSUE TITLE
cb() never called!

### ISSUE THREAD

**Issue by kafriyiegyamfi** [npm/cli#451]
i tried installing the react expo cli using "npm install -g expo-cli"
and i recieved  this error in my log file
21640 error cb() never called!
21641 error This is an error with npm itself. Please report this error at:
21642 error <https://npm.community>

**Comment by JacopoBonta** [comment]
I have got the same error using `npx create-react-app my-app`

**Comment by JacopoBonta** [comment]
> I have got the same error using `npx create-react-app my-app`

I'm not aware of what was causing the problem but I found [this](https://www.alex-arriaga.com/issue-when-running-npm-install-npm-err-cb-never-called-solved/) and solved. Hope it can help.
In short:
```sh
sudo npm cache clean -f
npm install -g n
sudo n stable
npx create-react-app my-app
```

**Comment by prahaladbelavadi** [comment]
Node helper n doesn't work on windows.
Force clearing the cache helped solve my problem.
Thanks @JacopoBonta

**Comment by kafriyiegyamfi** [comment]
trying it out

**Comment by kafriyiegyamfi** [comment]
thanks but it still didnt work for me

**Comment by kafriyiegyamfi** [comment]
found the fix here : https://stackoverflow.com/questions/58268958/i-am-getting-invalid-regular-expression-error-while-running-npm-start

**Comment by mikemimik** [comment]
Duplicate issue; aggregating into https://github.com/npm/cli/issues/417.
