### ISSUE TITLE
NPM update: File already exist. Use --force

### ISSUE THREAD

**Issue by ghost** [npm/cli#4514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Description

Just a minor issue:

![cli](https://user-images.githubusercontent.com/53160891/156901587-f365f32b-acdb-4bf9-9458-c9a8ba610a1f.png)

Should the `--force` arg be in the notice? Avoid trial n error. 

```
npm install -g --force npm@8.5.3
```

**Comment by ljharb** [comment]
You may need to `sudo npm install -g npm`.

**Comment by nlf** [comment]
`--force` is not typically needed to update npm itself. this can happen if, for example, a user were to use `corepack` to manager their `npm` installation, which overwrites the original `npm`/`npx` binaries with the `corepack` provided shims.

if you run the command with `--force` do you get a successfully updated `npm`? if so, i don't think this is a bug in npm itself so much as some external process replacing the binary shim with its own file.
