### ISSUE TITLE
[BUG] Prompt does not reappear after using any npm command.

### ISSUE THREAD

**Issue by Tarang74** [npm/cli#4516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Whenever I use any npm command, the prompt does not reset to the default cmd prompt:

My prompt is `CMD > `
```bash
CMD > npm -v
8.5.3
echo test
test
```

As you can see, the command is working normally and returning to cmd, but the prompt itself does not show up. 
This is also 

### Expected Behavior

I should see the prompt again after using an `npm` command.

### Steps To Reproduce

1. Windows 10
2. My prompt is `CMD > `
3. Run the following in administrator mode:
```bash
CMD > npm -v
8.5.3
echo test
test
```

### Environment

- npm: 8.5.3
- Node.js: 17.5.0
- OS Name: Windows 10
- npm config:
```ini
; "builtin" config from C:\Users\tarang\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\tarang\\AppData\\Roaming\\npm"

; node bin location = C:\Users\tarang\AppData\Roaming\npm\node_modules\node\bin\node.exe
; cwd = C:\Users\tarang
; HOME = C:\Users\tarang
; Run `npm config ls -l` to show all defaults.
```

**Comment by nlf** [comment]
i'm not able to reproduce this one. do you have anything else special about your shell? i'm assuming you're using `cmd.exe` as your shell, is that right?

**Comment by Tarang74** [comment]
Yes that's correct

**Comment by Tarang74** [comment]
I can't think of a reason why this happened (must have modified something by accident), but I have created a new user profile and the problem is fixed :)
I'll close the issue for now.
