### ISSUE TITLE
Modifying where Packages are Resolved in Package-lock. Package keep referencing internal provider even when registry is set to default external provider

### ISSUE THREAD

**Issue by hlahlou-pp-dev** [npm/cli#4523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

For an external facing SDK, we want the packages to be resolved from an external default provider. Example below:

```
"node_modules/foreach": {
"version": "2.0.5",
"resolved": "[https://registry.npmjs.org/foreach/-/foreach-2.0.5.tgz]",
"integrity": "sha1-C+4AUBiusmDQo6865ljdATbsG5k=",
"dev": true
},
```

But currently some packages are resolved through an internal artifactory which we do not want. Example:

```
"node_modules/foreground-child": {
"version": "2.0.0",
"resolved": "[https://artifactory.g.devqa.gcp.dev.paypalinc.com/artifactory/api/npm/npm-all/foreground-child/-/foreground-child-2.0.0.tgz]",
"integrity": "sha1-cbMoAMnxWqjy+D9Ka9m/812GGlM=",
"dev": true,
"dependencies": {
"cross-spawn": "^7.0.0",
"signal-exit": "^3.0.2"
},
"engines": {
"node": ">=8.0.0"
}
},
```

I have tried updating my node and npm to v12.22.4 and v8.5.3 and have set my registry to "[https://registry.npmjs.org/]" instead of our internal npm endpoint. I have also followed the below steps when reinstalling the packages

$ rm -rf node_modules/
$ npm cache clean --force
$ npm i

Below will be my local npm configs:
hlahlou@LM-SJN-40024033 node-sdk % npm config list
; "global" config from /usr/local/etc/npmrc

; registry = "https://npm.paypal.com/" ; overridden by project
; scope = "@paypalcorp" ; overridden by user

; "user" config from /Users/hlahlou/.npmrc

@paypalcorp:registry = "[https://registry.npmjs.org/]" 
//npm.paypal.com/:_authToken = (protected) 
cafile = "/usr/local/etc/openssl/certs/combined_cacerts.pem" 
; registry = "[https://registry.npmjs.org/]" ; overridden by project
scope = "@paypalcorp"

; "project" config from /Users/hlahlou/hwSDK/node-sdk/.npmrc

registry = "[https://registry.npmjs.org/]

; node bin location = /usr/local/bin/node
; cwd = /Users/hlahlou/hwSDK/node-sdk
; HOME = /Users/hlahlou

### Expected Behavior

The expected behavior is that within the package-lock.json, packages should be resolved from

`"resolved": "[https://registry.npmjs.org/...]",
`

and not from our internal server

`"resolved": "[https://artifactory.g.devqa.gcp.dev.paypalinc.com/artifactory/api/...]",
`

### Steps To Reproduce

This happens in this project when installing the packages just by running

npm i

### Environment

- npm: 8.5.3
- Node.js: 12.22.4
- OS Name: macOS Big Sur v 11.6.4
- System Model Name: MacBook Pro (16-inch 2019)
- npm config:
```ini
; "global" config from /usr/local/etc/npmrc

; registry = "https://npm.paypal.com/" ; overridden by project
; scope = "@paypalcorp" ; overridden by user

; "user" config from /Users/hlahlou/.npmrc

@paypalcorp:registry = "https://registry.npmjs.org/" 
//npm.paypal.com/:_authToken = (protected) 
cafile = "/usr/local/etc/openssl/certs/combined_cacerts.pem" 
; registry = "https://registry.npmjs.org/" ; overridden by project
scope = "@paypalcorp" 

; "project" config from /Users/hlahlou/hwSDK/node-sdk/.npmrc

registry = "https://registry.npmjs.org/" 

; node bin location = /usr/local/bin/node
; cwd = /Users/hlahlou/hwSDK/node-sdk
; HOME = /Users/hlahlou
; Run `npm config ls -l` to show all defaults.```

**Comment by fritzy** [comment]
If you change the config after a lock file is made, you'll need to rebuild the lock file. The current behavior is to only override existing URLs with the configured registry host if it is set to registry.npmjs.com. It sounds like you've changed your configuration after generating a lock file for these entries.

FYI, we're working on short and long term features and changes to behavior around registry host replacement, but we don't currently have plans to address the behavior that you've described. Feel free to join our RFC process if you'd like to see behavior changes. https://github.com/npm/rfcs
