### ISSUE TITLE
[BUG] run-script changing from root-user to non-root user

### ISSUE THREAD

**Issue by ArcoMul** [npm/cli#4525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When running `npm run start` as root user npm starts a process as non-root user, it runs the script as the user who 'owns' the current working directory.

### Expected Behavior

When running `npm run start` as root user I expect the started process to be also start as root user

### Steps To Reproduce

1. Setup new npm/node project
2. Include index.js file:
```
const { exec } = require('child_process');

const ls = exec('id', function (error, stdout, stderr) {
  if (error) {
    console.log(error.stack);
    console.log('Error code: ' + error.code);
    console.log('Signal received: ' + error.signal);
  }
  console.log('Child Process STDOUT: ' + stdout);
  console.log('Child Process STDERR: ' + stderr);
});
```
3. Add script as npm script: `"start": "node index.js"`
3. Run `node index.js` note that current user id is printed
4. Run `npm run start` note that current user id is printed
5. Run `sudo node index.js` note that root user id is printed
6. Run `sudo npm run start` note that regular user id is printed instead of root user id (probably because the current working directory of where the script is run is owned by this regular user)

---

- I ended up understanding this behaviour from this SO post: https://stackoverflow.com/questions/70738567/why-does-running-npm-run-script-as-root-switch-user
- I noted that the latest [promise-spawn](https://github.com/npm/promise-spawn) package fixes the behaviour (2.0.1)
- But that the current version of promise-spawn in the cli lockfile is still 1.3.2: https://github.com/npm/cli/blob/latest/package-lock.json#L11505

### Environment

- npm:8.3.1
- Node.js:16.14.0
- OS Name:Window Linux Subsystem 2
- System Model Name:Windows 10, WSL Ubuntu
- npm config:
```ini
not relevant? let me know if needed
```

**Comment by wraithgar** [comment]
The reason the newest promise-spawn doesn't do that anymore is because that functionality was moved to a new module https://github.com/npm/exec.  That hasn't been implemented in the cli yet but it is on the roadmap.  The behavior is intended, and there are no plans to change it.
