### ISSUE TITLE
[QUESTION] npm ERR! cb() never called!

### ISSUE THREAD

**Issue by gnusiva** [npm/cli#455]
npm http fetch GET 200 https://registry.npmjs.org/qs/-/qs-6.9.1.tgz 9519ms
npm timing npm Completed in 3754889ms
**npm ERR! cb() never called!**

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Siva\AppData\Roaming\npm-cache\_logs\2019-11-08T14_43_49_232Z-debug.log

node -v
v13.1.0

npm -v
6.12.1

This is happening for **v12.13.0** also.

**Comment by mikemimik** [comment]
Duplicate issue; aggregating into https://github.com/npm/cli/issues/417.
