### ISSUE TITLE
[BUG] peer warnings no longer printed out when running npm install

### ISSUE THREAD

**Issue by Roaders** [npm/cli#4554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

because of the way that peer validation works in npm 8 it seems to me that there is no way of updating a project that has a lot of interrelated peer dependencies (like angular) without having to do `npm install @angular/core@latest --force`. When you do this you get a whole load of warnings preinted about mis-matched peers that will be fixed with subsequent npm installs. There doesn't seem to be any way of ensuring that all the issues have been fixed though. Previously running `npm install` would print out warnings for any incompatible peer dependencies that are installed but that is no longer the case.

How can I ensure that all peer dependencies have been correctly resolved and that my project is in a good state?

### Expected Behavior

when running npm install warnings for incorrectly aligned peer versions should be printed out.

### Steps To Reproduce

```
npx @angular/cli@13.1 new testAngular131
cd testAngular131
npm install @angular/core@latest --force
npm install
```

### Environment

- npm: 8.5.4
- Node.js: 16.3.2
- OS Name: Windows

**Comment by ljharb** [comment]
npm v8.1.2 is not the latest npm, in contrast to the box you checked saying you were using it. Can you try with v8.5.4?

**Comment by Roaders** [comment]
sorry, I thought it was. It's certainly the latest that I can currently install at my place of work so no, at the moment I can't try with a later version I am afraid.

**Comment by ljharb** [comment]
even if you can't do `npm install -g npm` for some reason, you can certainly do `npx npm@latest` and try it out.

(Separately, it is highly advisable for your place of work to not be on an old, and thus very broken, version of npm)

**Comment by Roaders** [comment]
No it's not that. The latest version has not been onboarded into our local repository yet.

**Comment by ljharb** [comment]
`NPM_CONFIG_REGISTRY=https://registry.npmjs.org npx npm@latest` should work, then.

**Comment by Roaders** [comment]
No, external access is blocked.

I'll see if I can replicate at home over the weekend.

**Comment by Roaders** [comment]
updated initial post with reporoduction steps. Tried it on npm `8.5.4`

**Comment by wraithgar** [comment]
`npm ls -a` will show you that there are version conflicts, and will exist w/ a statuscode if you want to make that part of another scripting process.


```
├─┬ @angular/animations@13.1.3
│ ├── @angular/core@13.2.6 deduped invalid: "13.1.3" from node_modules/@angular/animations
```

```
npm ERR! code ELSPROBLEMS
npm ERR! invalid: @angular/core@13.2.6 /Users/wraithgar/Development/npm/scratch/testAngular131/node_modules/@angular/core
```
