### ISSUE TITLE
[BUG] I have uploaded the new version of my package but still not updated on site

### ISSUE THREAD

**Issue by anshtyagi0** [npm/cli#4556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I have uploaded a new version of my package and its around 30 min its is still not updated on site.
https://www.npmjs.com/package/bhbotlist.js it is showing 1.0.2 version

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by wraithgar** [comment]
This is an issue with the npm registry itself, not the cli.  Please open a support ticket at https://www.npmjs.com/support
