### ISSUE TITLE
Cannot find module 'is-typedarray'

### ISSUE THREAD

**Issue by flojo007** [npm/cli#4559]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When I try to install any npm package with `npm i` I always get the error:
![grafik](https://user-images.githubusercontent.com/83416975/158077111-d82ef445-89b4-426f-85b5-d9836b9be749.png)

### Expected Behavior

Normally it should install the package

### Steps To Reproduce

1. I installed the newest version of nodejs & npm
2. I tried to install a module with `npm i`

### Environment

- npm: 8.5.4
- Node.js: 16.14.0
- OS Name: Ubuntu 18.04
- npm config:
```ini
(node:6482) [LRU_CACHE_OPTION_maxAge] DeprecationWarning: The maxAge option is deprecated. Please use options.ttl instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
; "builtin" config from /usr/local/lib/node_modules/npm/npmrc

globalignorefile = "/etc/npmignore"
prefix = "/usr/local"

; node bin location = /usr/local/bin/node
; cwd = /root
; HOME = /root
; Run `npm config ls -l` to show all defaults.
```

**Comment by ljharb** [comment]
Are you using the public registry? https://www.npmjs.com/package/is-typedarray does exist.

**Comment by flojo007** [comment]
> Are you using the public registry? https://www.npmjs.com/package/is-typedarray does exist.

I cant even install that package

All I did was installing nodejs & npm

**Comment by wraithgar** [comment]
The latest version of npm doesn't require that dependency anymore, it was removed in `v8.5.3`.  I'm not sure how you got into a situation where you have a `write-file-atomic` that is out of date but are on the newest npm.  This should not be possible because npm bundles its dependencies.

How are you installing Node.js and npm?

**Comment by flojo007** [comment]
> The latest version of npm doesn't require that dependency anymore, it was removed in `v8.5.3`.  I'm not sure how you got into a situation where you have a `write-file-atomic` that is out of date but are on the newest npm.  This should not be possible because npm bundles its dependencies.
> 
> How are you installing Node.js and npm?

I installed it using these commands:
`apt-get update` & `apt-get install nodejs`

**Comment by wraithgar** [comment]
It would appear that the ubuntu nodejs installs npm in a way that is broken.  You may need to open up an issue w/ the maintainer of that apt package.

How are you installing npm? I would be very surprised if the apt image for nodejs already had the version of npm that was just published 4 days ago.

**Comment by flojo007** [comment]
> It would appear that the ubuntu nodejs installs npm in a way that is broken.  You may need to open up an issue w/ the maintainer of that apt package.

I will create an issue later when I'm home (if I don't forget it)


> How are you installing npm? I would be very surprised if the apt image for nodejs already had the version of npm that was just published 4 days ago.

Well it did actually haven't changed anything there
I tried `npm install npm -g` gives me the same error.

**Comment by wraithgar** [comment]
It sounds like the apt image for nodejs is broken if the npm that it ships with doesn't work.

**Comment by ljharb** [comment]
Definitely don't install node from apt, and npm should generally only come with node and not be installed separately :-)

**Comment by flojo007** [comment]
> npm should generally only come with node and not be installed separately :-)

If you read the comments, you will see that I never said that I installed it sperately
