### ISSUE TITLE
[DOCS] "npm-cli-docs" package is listed as malicious at www.npmjs.com/package/npm-cli-docs

### ISSUE THREAD

**Issue by joeliedtke** [npm/cli#4560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Problem, not another kind of Docs Problem.

- [X] This is a CLI Docs Problem.

### Description of Problem

Sorry if this is the wrong place to ask about this, I've tried contacting NPM support and searching for this answer but I haven't found anything.

On npmjs.com, the [`npm-cli-docs` package](https://www.npmjs.com/package/npm-cli-docs) is listed as containing malicious code. Is this the same `npm-cli-docs` package that was part of NPM prior to the CLI docs package being renamed `docs`? Or, is that referring to a different package that was introduced with the same name?

If this is the same package that was included as a part of NPM, is there a security warning that I could review to understand which releases are affected? (The link on the `npm-cli-docs` package goes to a page that does not appear to include any documentation about this vulnerability.)

**Comment by wraithgar** [comment]
Yeah, this isn't really the place that will have an answer for that, this is the repo for the npm cli itself.  None of the code here affects what shows up on npmjs.com.

npm support should be the place to find that info out, if it exists.

**Comment by joeliedtke** [comment]
Can you confirm that the `npm-cli-docs` package included with NPM (that was managed in this repo until late last year when the docs package was replaced with the `docs` package) does not have any known malicious code issues?

**Comment by wraithgar** [comment]
There are no advisories for it, that's the extent of my knowledge.
