### ISSUE TITLE
[Moderate/BUG] Package.json: npm start to start itself

### ISSUE THREAD

**Issue by Mafee6** [npm/cli#4564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

If you set scripts to
```json
  "scripts": {
    "start": "npm start"
  },
```

> Infinite Loop
> Suggestion: Add filter for npm scripts

### Expected Behavior

> Filter npm scripts from the package.json scripts property

### Steps To Reproduce

1. Init the npm Project
2. go to `package.json`
3. edit under scripts to `"start": "npm start"`
4. Looping

### Environment

- npm:
- Node.js:
- OS Name: Linux
```ini
; node bin location = /nix/store/w1cy324vnr8an1lzp316agcnfb0jbb88-nodejs-16.13.2/bin/node
; cwd = /home/runner/InfiniteNpmStart
; HOME = /home/runner
; Run `npm config ls -l` to show all defaults.
```

**Comment by ljharb** [comment]
If you explicitly asked for an infinite loop, it sounds like npm’s doing exactly what you asked

**Comment by wraithgar** [comment]
This is working as intended, filtering it out would likely introduce more bugs than the extreme edge case it's trying to solve.

**Comment by Mafee6** [comment]
Yes
