### ISSUE TITLE
[BUG] <The package-lock.json file was created with an old version of npm >

### ISSUE THREAD

**Issue by CoryResilient** [npm/cli#4596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

~/pi-explorer $ npm i && npm start
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

### Expected Behavior

~/pi-explorer $ npm i && npm start
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...
~/pi-explorer $ npm i && npm start
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by nlf** [comment]
we need a lot more information to stand a chance at helping you with this one. please open a new issue and carefully fill out the entire template to the best of your ability. at the very least, we need to know what version of node and npm you're using, what operating system you're on, and how to reproduce the problem.

**Comment by mehraj6303** [comment]
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
