### ISSUE TITLE
[BUG] Install fails if "bin" script doesn't exist

### ISSUE THREAD

**Issue by remcohaszing** [npm/cli#4597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

This is a duplicate of https://github.com/npm/cli/issues/2632. This has been closed, but I still encounter it using the latest version of npm.

When running `npm install` in a project that references a `bin` script that doesn’t exist, the command fails with the error:

```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /home/remco/Projects/appsemble/node_modules/@appsemble/server/dist/index.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/remco/Projects/appsemble/node_modules/@appsemble/server/dist/index.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

### Expected Behavior

`npm install` is succesful

### Steps To Reproduce

```sh
git clone git@gitlab.com:appsemble/appsemble.git
cd appsemble
rm yarn.lock
npm install
```

### Environment

- npm: 8.5.5
- Node.js: 16.14.2
- OS Name: Pop!_OS
- System Model Name:
- npm config:
```ini
; "global" config from /home/remco/.local/etc/npmrc

fund = false 

; node bin location = /usr/bin/node
; cwd = /home/remco/Projects/appsemble
; HOME = /home/remco
; Run `npm config ls -l` to show all defaults
```

**Comment by fritzy** [comment]
#2632 possible regression

**Comment by remcohaszing** [comment]
The issue still exists today in npm 9.

The issue occurs when two packages install the same executable name, but it doesn’t exist in the second package that is supposed to install that executable.

It’s simplest to reproduce with npm workspaces, but it applies to other dependencies as well.

Let’s say we have the following files:

`package.json`

```json
{
  "workspaces": [
    "workspaces/*"
  ]
}
```

`workspaces/a/package.json`

```json
{ 
  "name": "a",
  "bin": {
    "cli": "./cli.js"
  }
}
```

`workspaces/b/package.json`

```json
{ 
  "name": "b",
  "bin": {
    "cli": "./cli.js"
  }
}
```

Running `npm install` from this project will reproduce the issue.

If we create an empty file `workspaces/a/cli.js`, the issue still exists. However, if we create an empty file `workspaces/b/cli.js` instead, the issue goes away.

**Comment by remcohaszing** [comment]
The problem is in https://github.com/npm/bin-links/blob/v4.0.1/lib/link-gently.js#L30-L33. This naively returns true if a link target was seen before. This indicates the file was linked succesfully. Then https://github.com/npm/bin-links/blob/main/lib/link-bin.js#L7 will try to make the non-existent file executable, which makes npm fail.
