### ISSUE TITLE
[BUG] Unexpected, recursive workspace script calls

### ISSUE THREAD

**Issue by nickhudkins** [npm/cli#4603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

In `npm 8.4.x`, the following command with the following set of scripts, did not result in recursive calls. As of 8.5.x it ends up with recursive calls to `{{ other_script }}` as though the command line args are being passed down to `workspace-a`'s {{ other_script}} `npm run ...` call.

`npm run {{ workspace_script }} --workspaces --if-present --include-workspace-root`

workspace-root (package.json... truncated)
```
  "{{ other_script }}": "npm run {{ other_script }} --workspaces --if-present"
```

workspace-a (package.json... truncated)
```
"{{ workspace_script }}": "npm run {{ other_script }}",
"{{ other_script }}: "echo 'Hello World'"
```

A simple test case can be found here: https://github.com/nickhudkins/npm-workspaces-uh-oh-spaghettio

### Expected Behavior

I expected the `--workspaces`, `--if-present`, and `--include-workspace-root` flags, and that `npm run` calls from child workspaces, NOT to include the caller's flags, as I would EXPECT recursion to occur if I had passed the workspace flags in both the caller and callee's scripts.

### Steps To Reproduce

See README.md of: https://github.com/nickhudkins/npm-workspaces-uh-oh-spaghettio

# npm 8.4.1

Run:
`npm run release --workspaces --if-present --include-workspace-root`

Output:

```
○ npm run release --workspaces --if-present --include-workspace-root

[RELEASE]: Package B
[BUILD]: Package B
```

# npm 8.5.0

Output
```
○ npm run release --workspaces --if-present --include-workspace-root
[RELEASE]: Package B

... Infinitely ...
Highly Unexpected for this to log...
Highly Unexpected for this to log...
Highly Unexpected for this to log...

```

### Environment

- npm: **8.5.5**
- Node.js: **16.14.2**
- OS Name: **OS X**
- System Model Name: **MacBook Pro (16-inch, 2019)**
- npm config:
```ini
; "user" config from /Users/nhudkins/.npmrc

//registry.npmjs.org/:_authToken = (protected)

; node bin location = /Users/nhudkins/.nvm/versions/node/v16.14.2/bin/node
; cwd = /Users/nhudkins
; HOME = /Users/nhudkins
; Run `npm config ls -l` to show all defaults.
```

**Comment by nickhudkins** [comment]
@nlf would you expect flags to be passed along to `npm run {{ script }}` commands when `npm run {{ script }}` is invoked by another workspace, or does this seem like defective behavior?

Trying to understand if I need to make wide-sweeping fixes due to the changed behavior, or if the changed behavior is intended to stay, and the previous workspace behavior was incomplete or defective.

There seem to be a lot of changes around `workspaces`, would love to help out, either with documentation, or implementation, as I would love to be able to lean on `npm` for workspace support. Are there any RFCs for how workspaces are intended to work? Totally understandable if not, just trying to understand if this is information that maintainers have in their head and the code that exists, or if there's any design document I could refer to to help out.

**Comment by fritzy** [comment]
I'm not seeing this behavior

```sh
npm-workspaces-uh-oh-spaghettio on  main [?] is 📦 v1.0.0 via ⬢ v16.14.2 
❯ npm -v
8.5.5

npm-workspaces-uh-oh-spaghettio on  main [?] is 📦 v1.0.0 via ⬢ v16.14.2 
❯ node -v
v16.14.2

npm-workspaces-uh-oh-spaghettio on  main [?] is 📦 v1.0.0 via ⬢ v16.14.2 
❯ npm run release --workspaces --if-present --include-workspace-root

> b@1.0.0 release
> echo "[RELEASE]: Package B" && npm run build

[RELEASE]: Package B

> b@1.0.0 build
> echo "[BUILD]: Package B"

[BUILD]: Package B
```

I'm not saying that it's not possible you've seen this with some version combo (you mention both 8.5.0 and 8.5.5), as we've been working to define and solidify this behavior in recent releases. This could be related to https://github.com/npm/cli/issues/4618.

I've used your repo and followed your instructions, but I was not able to reproduce the behavior.

**Comment by nickhudkins** [comment]
Hey @fritzy! I'm sorry you couldn't reproduce.

Fortunately GithubActions can, for both 8.5.0 and 8.5.5.

https://github.com/nickhudkins/npm-workspaces-uh-oh-spaghettio/actions/runs/2080669489

**Comment by lemiesz** [comment]
Im seeing the same issue in my workspace.

**Comment by nickhudkins** [comment]
Just so that I'm clear, I'm not actually looking for a fix, I'm hoping to understand if the behavior in 8.5.x is expected or not. I'd be happy to dig in if it is indeed incorrect behavior, but hoping for an npm maintainer to weigh in on what the desired behavior is.

**Comment by nickhudkins** [comment]
@fritzy could I get confirmation that the change in behavior, as seen in the reproduction in CI (GitHub Actions) here: https://github.com/nickhudkins/npm-workspaces-uh-oh-spaghettio/actions/runs/2080669489 is expected? Again, not looking for a fix, just trying to understand the npm maintainers intent for behavior.
