### ISSUE TITLE
[BUG] Running NPM command within a docker container calls to outside network (npm artifactory)

### ISSUE THREAD

**Issue by Yaron01** [npm/cli#4612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When setting up a docker I can see that the pod send packets to the outside network and trying to reach the artifcatory.
This network traffic appears every time we are pushing container and use the npm commands: 
- 'npm config set..'
- 'npm run..'

### Expected Behavior

After creating a docker file and getting all NPM packages I would expect that set the container up will not contact with outside network when running NPM commands such as 'npm config set..' and 'npm run..' .

### Steps To Reproduce

1. In this environment - Docker container
2. on terminal- run 'tcpdump -n -i ens160 not dst net 192.168.0.0/16 and not dst net 10.0.0.0/8 and not dst net 172.16.0.0/12'
3. See many internet traffic to the artifactory addresses.

### Environment

- npm:6.14.8
- Node.js: v14.15.0
- OS Name:darwin
- System Model Name:Macbook Pro
- npm config:
```ini
user-agent = "npm/6.14.8 node/v14.15.0 darwin x64"
```

**Comment by wraithgar** [comment]
npm 6 is not the latest npm. Does this happen in npm 8?

One thing that hits the network every time is the update notifier, letting you know if there is a new npm version available.  Set `update-notifier` to false in your config or via cli options if you want to disable this.

**Comment by Yaron01** [comment]
@wraithgar - thank you , it solved the issue.

**Comment by Yaron01** [comment]
It's somehow not working again, any other suggestions ?

**Comment by fritzy** [comment]
@Yaron01 which versions are you using now? What does your configuration look like now?

**Comment by Yaron01** [comment]
npm 5.6.0
node v9.3.0

I've added 'RUN npm config set update-notifier false' in dockerFile and it didn't work.

**Comment by lukekarrys** [comment]
Can you try updating to npm 8? npm 5 and 6 are both unsupported. If you're able to reproduce on npm 8 please reopen this issue and we can investigate further.
