### ISSUE TITLE
[BUG] <title>Get an error with npm itself when using "npm install"

### ISSUE THREAD

**Issue by guoqiangqi** [npm/cli#4640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

npm ERR! typeerror This is an error with npm itself. Please report this error at:

### Expected Behavior

npm install should success.

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by ljharb** [comment]
The issue template isn't filled out.
