### ISSUE TITLE
[BUG] npm stopped working after upgrading to latest version, now can not downgrade or uninstall

### ISSUE THREAD

**Issue by SSaquif** [npm/cli#4646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I upgraded my npm from version `6.9.0` to `8.5.5` as per the CLI message, using the command
`npm install -g npm`
After which I tired running 
`npm -v` and `npm --version` and ended up with the error below

As you can see in the message, I am using v12.0.0 of node and upgrading is `not` an option at the moment (It's for work)

I next tried downgrading to my old version using `npm install -g npm@6.9.0` and then uninstalling npm `sudo npm uninstall npm -g`

They all failed, with the  same error message

**The Error message**
 ```
 npm does not support Node.js v12.0.0
You should probably upgrade to a newer version of node as we
can't make any promises that npm will work with this version.
You can find the latest version at https://nodejs.org/
/Users/ssaquif/.nvm/versions/node/v12.0.0/lib/node_modules/npm/lib/utils/log-file.js:48
    maxLogsPerFile = 50_000,
                     ^^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:703:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/ssaquif/.nvm/versions/node/v12.0.0/lib/node_modules/npm/lib/npm.js:15:17)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
 ```

### Expected Behavior

Be able to run npm commands after update
 
### Steps To Reproduce

1. See environment below.
2. upgrade from npm version `6.9.0` to `8.5.5` while using node version `12.0.0`

### Environment

- npm: can not run any npm commands but I expect its 8.5.5 (as the upgrade did not throw any errors)
- Node.js: 12.0.0
- OS Name: macOS Monterey version 12.3
- System Model Name: Macbook Pro
- npm config: can not run any npm commands
```ini
; copy and paste output from `npm config ls` here
```

**Comment by SSaquif** [comment]
**Update:**
Solved it by updating node to latest stable version `16.14.2`, then downgraded npm back to `6.9.9` and switching back to node version `12.0.0`

**P.S.:** Yes I feel dumb for raising the issue

**Update 2:**
So the issue was the update corrupted my installation of node `12.0.0` completely removed it from the folder and reinstalled everything now runs with version `12.0.0`

**Comment by welew204** [comment]
Don't feel dumb @SSaquif ! I did the same thing, and your comment solved it for me! Had to completely remove the older corrupted version inside ./.nvm/node/ then nvm install the version I needed, and it bundled correct npm with it.
