### ISSUE TITLE
npm profile set command exits with non zero exit code

### ISSUE THREAD

**Issue by vikas-t** [npm/cli#4651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Running the command `npm profile set fullname <name>`  throws the following error and the exit code is `1` but the command actually sets the fullname

```
npm ERR! Cannot read property 'fullname' of undefined
```

Here is the output from the terminal
```
vikas-t@Vikass-MBP node_modules % npm profile set fullname npmqa
npm ERR! Cannot read property 'fullname' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vikas-t/.npm/_logs/2022-03-31T10_58_22_980Z-debug-0.log
vikas-t@Vikass-MBP node_modules % npm profile get fullname
npmqa
vikas-t@Vikass-MBP node_modules % npm -v
8.5.5
vikas-t@Vikass-MBP node_modules % node -v
v14.16.0
vikas-t@Vikass-MBP node_modules %
```

### Expected Behavior

The command should not throw and error message and the exit code should be 0/

### Steps To Reproduce

1. Install npm 8.5.5
2. Run `npm profile set fullname <name>`

### Environment

- npm: 8.5.5
- Node.js: v14.16.0
- OS Name: macOs BigSur v 11.6.3
- System Model Name: Macbook Pro M1 (2020)
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by vikas-t** [comment]
Possibly links to https://github.com/npm/cli/issues/4313

**Comment by lukekarrys** [comment]
Yes, this is the same issue. I'm going to close this one and I believe updating to v8.6.0 should fix both of these. Please let me know if that's not the case.
