### ISSUE TITLE
Inconsistent behaviour in installation of dependent packages in the node modules

### ISSUE THREAD

**Issue by JijiyaT** [npm/cli#4653]
Hi Team,

I have a project "project1" which has a dependency on library package "local library".Local library project has a dependency on primeng and luxon .When i am installing node modules for project1,primeng is not installed in root nodemodules folder where in luxon has been installed in node modules of project1.

`
project 1 package.json

dependencies:
{
local library:1
}

local library package.json
{
luxon
primeng
}`

This is happening:

project 1 nodemodules:

```
-luxon
-local library
      - node modules
              -primeng
```

But I below is expected.

```
-luxon
 -primeng
-local library
```

Could you please tell us why this inconsistent behavior across dependencies installation in node modules folders.
   
using
node:16.14.2
npm:8.5

Thanks.

**Comment by ljharb** [comment]
When you say "local library", do you mean "it's not installed by npm, it's linked from somewhere else"? If so, i think that's the answer - npm doesn't install it, so npm can't merge the two dep trees.

**Comment by JijiyaT** [comment]
Hi,

"local library" package itself is installed by npm in project 1 as it is mentioned as one of the dependency for project1 .
 some of the dependencies from local library are installed properly and some are not properly installed in nodemodules of project1.

local library has two dependencies luxon and primeng.

Where in luxon is properly installed and primeng is not.

project 1 package.json
```

dependencies:
{
local library:1
}
```

```
local library package.json
{
luxon
primeng
}`
```
This is happening:

project 1 nodemodules:

```
-luxon
-local library
      - node modules
              -primeng
```
But below is expected.

```
-luxon
 -primeng
-local library
```

**Comment by nlf** [comment]
we would need a lot more information to help you figure out what's going on here. please open a new issue and be sure to fill out our issue template as thoroughly as you can. specifically we really must have step by step instructions to recreate the problem that you're seeing. without having the full picture, there's not really anything we can do for you.
