### ISSUE TITLE
[BUG] package.json fields can not be referenced in scripts with npm v8.5.0 

### ISSUE THREAD

**Issue by EnricoPicci** [npm/cli#4673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

With npm v6.14.16 I was able to use an attribute defined in package.json in the scripts (also defined in package.json).

So, for intance, given this package.json
```
{
    ...
    "scripts": {
        "tsc": "tsc --outDir ${npm_package_my_app_outdir}",
        ...
    }
    "my_app": {
        "outdir": "my-outdir"
    }
}
```

I was able to run `npm run tsc` and the compiled code was put in the folder "my-outdir".

Now, with npm v8.5.0, if I run `npm run tsc` I get the following error

_tsc --outDir ${npm_package_outdir}
error TS6044: Compiler option 'outDir' expects an argument._

### Expected Behavior

I would like to have, with npm v8.5.0 the same behavior as with npm v6.14.16

**Comment by ljharb** [comment]
This was an intentional breaking change in npm v7. You can read it from package.json yourself with node, for example, as a workaround.

**Comment by EnricoPicci** [comment]
So, if I understand right, it is not possible any more to reference a package.json attribute within a script, right?

**Comment by ljharb** [comment]
Specific scripts might inject specific ones, but for arbitrary package.json attributes, that's right - that was intentionally removed.

**Comment by nlf** [comment]
as mentioned, this was a deliberate and documented breaking change in npm v7. we have no plans to restore the old behavior, so i'm closing this issue.
