### ISSUE TITLE
[Question] A hook for an NPM package

### ISSUE THREAD

**Issue by talentedandrew** [npm/cli#4683]
Is there a hook for the below scenario?
 
Let's suppose there is an npm package called `x`. I'm using the package `x` in my node backend project. I install that package using the command:
```
npm install x
```
I need a hook in package `x`, that would be triggered after its installed in my project. I didn't find anything related to it on the web or docs, so finally came here to ask.

**Motive is to run the build command as soon as the package `x` is installed in any node project.**

Thanks in Advance

**Comment by ljharb** [comment]
a “build” or “postinstall” script?

What’s the actual use case?

**Comment by talentedandrew** [comment]
@ljharb 

> a “build” or “postinstall” script?
> 
> What’s the actual use case?

I have a package let's say `x` which is a wrapper across another package, let's say `y`. So whenever I install package `x` I want it to have the latest version of package `y` in it. I want to eliminate the manual intervention of updating `x` whenever there is a new version of `y` available.  I hope this explains my use case.

**Comment by ljharb** [comment]
You don't need a hook for that, that's what semver ranges are for. Have `x` depend on `y` with a `^` range, and as long as `y` doesn't have a semver-major update, `x` will never have to change.

**Comment by talentedandrew** [comment]
@ljharb But the package `x` in npm repository consist of the build files. So I have to build and publish package `x` everytime there is a new minor or patch version of `y`.

**Comment by ljharb** [comment]
@talentedandrew no you don't, because the built files in `y` should not contain any part of `x` - they should be requiring it dynamically.

**Comment by talentedandrew** [comment]
@ljharb I think I'm not able to explain my issue properly. I'll try one last time.

Let's say I have a node application named `my-app`.

There is an npm package named `YYY` (frontend library).

I create a package named `XXX`, which is a wrapper around `YYY` and depends on version `^1.x.x` of `YYY`. Now I build this `XXX` package using `rollup` and publish it to the npm repository.

Now, after I have published `XXX` to the npm repository, I use it as a dependency in my node application `my-app`. All good till here.

Now let's suppose a new minor version of npm package `YYY` is released. But my package `XXX` which is used in `my-app` was build using previous version of `YYY`.  In this case, I have to rebuild my package `XXX` and publish it to the npm repository, so that when I install packages in `my-app`, I get package `XXX` with the latest version of `YYY`.

**Comment by ljharb** [comment]
No, you don't, because you wouldn't rollup the YYY code - rollup would only produce a bundle containing XXX's code, and YYY would continue to be dynamically required.

**Comment by talentedandrew** [comment]
@ljharb Got it. I was under the assumption that `rollup` would bundle `YYY` in my `XXX` package. Thank you for the clarification.

**Comment by darcyclarke** [comment]
> "I need a hook in package x, that would be triggered after its installed in my project."

A `postinstall` script defined in the package being consumed is what you're looking for as far as I can tell (ref. https://docs.npmjs.com/cli/v8/using-npm/scripts#npm-install)
