### ISSUE TITLE
Npm i gulp-rename@1.4.0 -D -E updates whole package lock

### ISSUE THREAD

**Issue by Drag13** [npm/cli#469]
# What / Why
Hi! The issue is simple (and I think common), but I didn't find any answer. I have package.json with strict dependencies. I have package-lock.json file synced. I want to add gulp-rename as an additional dependency. Everything is fine except my package-lock.json completely changes.

Example
Was: 

```json
 "@babel/highlight": {
            "version": "7.0.0",
            "resolved": "https://registry.npmjs.org/@babel/highlight/-/highlight-7.0.0.tgz",
            "integrity": "sha512-UFMC4ZeFC48Tpvj7C8UgLvtkaUuovQX+5xNWrsIoMG8o2z+XFKjKaN9iVmS84dPwVN00W4wPmqvYoZF3EGAsfw==",
            "dev": true,
            "requires": {
                "chalk": "2.4.2",
                "esutils": "2.0.2",
                "js-tokens": "4.0.0"
            },
```

Became: 

```json
 "@babel/highlight": {
            "version": "7.0.0",
            "resolved": "https://registry.npmjs.org/@babel/highlight/-/highlight-7.0.0.tgz",
            "integrity": "sha512-UFMC4ZeFC48Tpvj7C8UgLvtkaUuovQX+5xNWrsIoMG8o2z+XFKjKaN9iVmS84dPwVN00W4wPmqvYoZF3EGAsfw==",
            "dev": true,
            "requires": {
                "chalk": "^2.0.0",
                "esutils": "^2.0.2",
                "js-tokens": "^4.0.0"
            }
```

I found this question on the StackOverflow but no answer or guess is present.

What I missed? How to add npm module without changing old dependencies in package-lock.json?

**Comment by DanielRuf** [comment]
Hi @Drag13,

Please provide some details about your npm version.

**Comment by ljharb** [comment]
Also, which npm version was the lockfile generated with?

**Comment by Drag13** [comment]
Hi, sorry for the long time answer.

My current npm version is 6.4.1
And if I am not mistaken it was generated also with this version (it was far ago, but I don't remember any updated)

**Comment by Drag13** [comment]
Hi guys!

Don't want to be annoying, but is there any chance for the answer? 
Or, if it is by design, I may close the issue,.
