### ISSUE TITLE
cb() never called, easily reproducible with v6.14.16

### ISSUE THREAD

**Issue by MarkKharitonov** [npm/cli#4712]
Our setup is the following:

1. Build server in Azure
2. Azure DevOps server **on prem** with Azure Artifacts (AA for short) repository serving node packages.

We have many njsproj projects, but there is one where it is relatively easy to reproduce the problem. Most of the packages are from npmjs.org, but there are some internal. In either case we specify AA as our repository, because npmjs.org is defined as an upstream repo and AA caches all the upstream packages.

Our methodology is simple:

1. npm cache clean --force
2. git clean -qdfx
3. npm ci

These 3 commands when ran in a loop produce a reproduction within the 10 iterations with 100% probability. Often it happens within the first 3 iterations. Sometimes right away.

We were unable to understand the root cause. The same methodology does not work when a dev workstation is used - no reproduction. 

I tried with npm 8.3, but it runs 2.5 slower than npm 6.14.16 and there is no reproduction there as well. There is also no reproduction with Fiddler running. Which makes me think there is something about the intensity of the network requests that step on some problem in our network setup between the build server and AA. npm@8 is very slow and produces requests less frequently, similarly to when Fiddler is running.

I was able to capture traffic with WireShark. First 2 runs were successful, the 3rd one failed. The difference is that the 3rd run misses three last http requests for 3 packages, but there are no errors and I am no network specialist to be able to determine if there are other problems. The 3 HTTP requests are just missing there.

How can I troubleshoot this? The npm log was not very useful, but I can attach it.

**Comment by ckirbybigdog** [comment]
OK I can see that this is like homework go to study for I’ll do my best

**Comment by MarkKharitonov** [comment]
@ckirbybigdog - I can save you time if you are in a position to zoom.

**Comment by ljharb** [comment]
npm 6cis basically EOL, so trying with npm 8 latest (8.3 is pretty old too) is probably your best bet.

**Comment by MarkKharitonov** [comment]
@ljharb - npm8.3 is very slow. The workload that takes about 110s with npm 6.14.16 takes 5m with npm 8.3. And it is a known thing - https://github.com/npm/cli/issues/2011 The workaround of creating an empty node_modules does not help. We cannot upgrade to npm@8 given the current state of affairs. The `cb() never called` problem is annoying, but we can mitigate it through retries. We have no mitigation for performance degradation.

We cannot use versions higher than 8.3 due to https://stackoverflow.com/questions/70958371/unexpected-token-when-trying-to-run-npm-install. This is because we are not ready yet to upgrade our node version.

**Comment by ljharb** [comment]
Have you tried the latest version, v8.6?

I was just trying to set your expectations; problems with "not npm 8 latest" are pretty unlikely to be fixed.

**Comment by MarkKharitonov** [comment]
As I have explained, we cannot use versions above 8.3 because apparently they depend on newer node version. We tried, but got the error described in https://stackoverflow.com/questions/70958371/unexpected-token-when-trying-to-run-npm-install

**Comment by ljharb** [comment]
What node version are you using? npm 8 works on every node version that's not EOL, and if you're using an EOL node you've got security vulnerabilities and should be dropping everything in order to work on updating that :-)

**Comment by MarkKharitonov** [comment]
We currently use node 14.19.1

**Comment by MarkKharitonov** [comment]
However, judging by the fact that https://github.com/npm/cli/issues/2011 is still open it seems that npm 8.6 has the same performance degradation issue as 8.3.

**Comment by ljharb** [comment]
Maybe so, but npm 8 still works fine on node 14, and if your choice is "fast and wrong" or "slow and correct", i'd hope you choose the latter ¯\\\_(ツ)\_/¯

**Comment by MarkKharitonov** [comment]
So our experience is in line with what is described in https://stackoverflow.com/questions/70958371/unexpected-token-when-trying-to-run-npm-install - npm above 8.3 **does not** work on node 14. We have exactly the same error.

It is not fast and wrong. When it fails, it has to be restarted. It does not produce wrong results. It is annoying and requires extra code from us to deal with the error. However, we do not normally clean the npm cache and so when the dependencies do not change we have no problems. The problems may arise if using a new build server or new dependencies for the first time and I hope to be able to workaround with automated retries. The performance degradation on the other hand is permanent and very much noticeable. And there is no workaround for it. At least for now.

I do not know if the **cb() never called** error we see is a bug in npm. But it could be. Right now it seems to be sensitive to the requests intensity and is masked by poor performance of npm@8. But it could be there nonetheless. If there is a methodology to troubleshoot this kind of errors I am really interested to learn it.

**Comment by ljharb** [comment]
The [reported issue](https://github.com/npm/cli/issues/4234) there is a problem with nvm-windows. Is that what you're using?

**Comment by MarkKharitonov** [comment]
Not at all. I do not even know what nvm-windows is. Maybe my methodology was wrong:

1. Cloned npm cli repo
2. Switched to v8.6
3. Edited bin\npm.cmd to use the npm-cli.js found in the same directory.
4. npm cache clean --force
5. git clean -qdfx
6. npm ci

I did that this way because I have already had the repo cloned since I have tried to debug npm in order to figure out the issue (in vain)

Anyway, `npm ci` fails:
```
npm ERR! Unexpected token '.'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\g5tfsbuild\AppData\Local\npm-cache\_logs\2022-04-08T16_53_58_423Z-debug-0.log
```
The log contains this:
```
33 verbose stack D:\work\npm-cli\node_modules\@npmcli\arborist:1
33 verbose stack ../../workspaces/arborist
33 verbose stack ^
33 verbose stack
33 verbose stack SyntaxError: Unexpected token '.'
33 verbose stack     at wrapSafe (internal/modules/cjs/loader.js:1001:16)
33 verbose stack     at Module._compile (internal/modules/cjs/loader.js:1049:27)
33 verbose stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
33 verbose stack     at Module.load (internal/modules/cjs/loader.js:950:32)
33 verbose stack     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
33 verbose stack     at Module.require (internal/modules/cjs/loader.js:974:19)
33 verbose stack     at require (internal/modules/cjs/helpers.js:101:18)
33 verbose stack     at Object.<anonymous> (D:\work\npm-cli\lib\commands\ci.js:2:18)
33 verbose stack     at Module._compile (internal/modules/cjs/loader.js:1085:14)
33 verbose stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
```
Indeed the file D:\work\npm-cli\node_modules\@npmcli\arborist contains just one line:
```
../../workspaces/arborist
```
No idea what it is, but it does not work on node 14.

**Comment by ljharb** [comment]
Steps 1-3 are not typical. To use a newer npm, you `npm install -g npm`.

**Comment by MarkKharitonov** [comment]
Yeah, I suspected it could be a problem. You are right, upgrading properly does not produce an issue.
But the performance degradation is still there. Twice slower.

**Comment by 54keesh** [comment]
This issue of cb never called occured for me too on npm 7.4.0 as well

**Comment by lukekarrys** [comment]
We no longer support bug fixes in the v6 release line. If you (or anyone else) is having the `cb never called` issue on v8 please open a new issue so we can triage there.

As for the performance of npm v8 there are some [`open issues related to performance`](https://github.com/npm/cli/issues?q=is%3Aopen+is%3Aissue+label%3Aperf) that we are tracking. If you feel like this is a performance issue not covered in any of those issues please open a new issue with the output from your npm 8 install debug logs so we can triage further.

**Comment by 54keesh** [comment]
> We no longer support bug fixes in the v6 release line. If you (or anyone else) is having the `cb never called` issue on v8 please open a new issue so we can triage there.
> 
> As for the performance of npm v8 there are some [`open issues related to performance`](https://github.com/npm/cli/issues?q=is%3Aopen+is%3Aissue+label%3Aperf) that we are tracking. If you feel like this is a performance issue not covered in any of those issues please open a new issue with the output from your npm 8 install debug logs so we can triage further.

I didn't encounter it in v6 rather in v7

**Comment by lukekarrys** [comment]
We also don't support bug fixes in the v7 release line. v8 is currently our only supported release line (outside of urgent security patches).
