### ISSUE TITLE
It says there's an issue with the npm itself. It's not installing and when i installed the module 1 by 1 again the file does not open due to some error

### ISSUE THREAD

**Issue by ingsha09** [npm/cli#4717]
[2022-04-09T09_42_38_157Z-debug-0.log](https://github.com/npm/cli/files/8456649/2022-04-09T09_42_38_157Z-debug-0.log)

**Comment by lukekarrys** [comment]
**Closing:** please use our [issue template](https://github.com/npm/cli/issues/new/choose) & review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).
