### ISSUE TITLE
NPM BUG

### ISSUE THREAD

**Issue by RHYTHMHACKER** [npm/cli#4719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I tried npm install
To install a File but
It is showing

npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:

### Expected Behavior

Expecting to install the corresponding file i Want it to install__

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by lukekarrys** [comment]
Can you share the package.json you are installing? And if you fill out the environment section of the issue template it will help us try and reproduce your issue more easily.

**Comment by RHYTHMHACKER** [comment]
This is the package that I am trying to use

**Comment by lukekarrys** [comment]
@RHYTHMHACKER there was nothing linked in your previous comment? can you paste the `package.json` and/or upload the `debug.log` linked at the bottom of the error output?

**Comment by RHYTHMHACKER** [comment]
LINK FOR MY package.json

https://drive.google.com/file/d/1BKMMT6hg2e3m-jwDkzCzdsA-6RpAkdT0/view?usp=drivesdk
