### ISSUE TITLE
show more relevant error message for 403s during publish

### ISSUE THREAD

**Issue by Nikkolast88** [npm/cli#4736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/@pole%2ficons-vue - Forbidden
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.

### Expected Behavior

success!

### Steps To Reproduce

1. npm publish --access public
2.npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/@pole%2ficons-vue - Forbidden
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.

### Environment

- npm:8.3.1
- Node.js:16.14.0
- OS Name:window 11
- System Model Name: xiaomi
- npm config:
```ini
; "user" config from C:\Users\123\.npmrc

//registry.npmjs.org/:_authToken = (protected)
registry = "https://registry.npmjs.org/"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\123\Desktop\pole-icons\packages\vue
; HOME = C:\Users\123
; Run `npm config ls -l` to show all defaults.
```

**Comment by ljharb** [comment]
https://www.npmjs.com/package/@pole/icons-vue is a private package; you can’t convert it to public one from a publish like that. I believe you have to change it on the site, or perhaps there’s a different command for it.

**Comment by lukekarrys** [comment]
You can use the `access` command to turn a private package into a public one:

```
npm access public <package-name>
```

It can also be accomplished on the site: https://docs.npmjs.com/changing-package-visibility#making-a-private-package-public

The error message in this case is a generic one we use for all 403s, but it really only makes sense for install. We should detect the command and output a more helpful message in this case.

### Action Items
- [ ] Display more relevant error message for 403s during publish

**Comment by Nikkolast88** [comment]
I found out that it was because the organization @pole had the same name, I changed it to @pole-platform to upload
