### ISSUE TITLE
[BUG] `npm ls --omit=dev` does not omit dev dependencies

### ISSUE THREAD

**Issue by denik1981** [npm/cli#4739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`npm ls --help` does not show `--prod` between the list of options available this command accepts.
It forces me google for it to remember it and `--omit dev` still lists both **prod** and **dev** dependencies together so this might be the source of a different issue         

### Expected Behavior

Should list `--prod` among the list of options

### Steps To Reproduce

1. `npm ls --help`
2. See `--prod` is missing

### Environment

- npm: 8.5.5
- Node.js: v14.19.0
- OS Name: ubuntu  20.04.1

**Comment by ljharb** [comment]
hmm, i'd expect `--only=prod` to be the preferred alias, but that one's not listed either, only `omit` is.

**Comment by lukekarrys** [comment]
`only` is deprecated, which I think is why its not listed for `ls` (or any other commands). https://docs.npmjs.com/cli/v8/using-npm/config#only

> It forces me google for it to remember it and --omit dev still lists both prod and dev dependencies together so this might be the source of a different issue

This definitely seems like a bug. The docs explicitly call out: `When set to prod or production, this is an alias for --omit=dev.` Here's the output that from the cli itself, which directly contradicts that:

```
❯ npm ls --only prod | grep tap-snapshots/

❯ npm ls --omit dev | grep tap-snapshots/
│ ├── tap@16.0.1 deduped
│ ├── tap@16.0.1 deduped
│ └── tap@16.0.1 deduped
│ ├── tap@16.0.1 deduped
│ ├── tap@16.0.1 deduped
│ └── tap@16.0.1 deduped
│ └── tap@16.0.1 deduped
│ └── tap@16.0.1 deduped
│ └── tap@16.0.1 deduped
│ └── tap@16.0.1 deduped
│ └── tap@16.0.1 deduped
│ └── tap@16.0.1 deduped
│ └── tap@16.0.1 deduped
├── tap@16.0.1
```

**Comment by denik1981** [comment]
Yes, well I suppose the correct usage is with `--omit dev` as you say if it happens that `--prod` is deprecated.
Thanks for addressing this issue.

**Comment by denik1981** [comment]
Thanks!
