### ISSUE TITLE
cb() never called! During installation of new Angular project

### ISSUE THREAD

**Issue by jager** [npm/cli#474]
During installation of new Angular project I get following error (from logs):

20917 error cb() never called!
20918 error This is an error with npm itself. Please report this error at:
20919 error <https://npm.community>

**Comment by DanielRuf** [comment]
Hi @jager,

Please provide more info about your npm and node versions.

**Comment by RidingRoad** [comment]
> Hi @jager,
> 
> Please provide more info about your npm and node versions.

i met this error too, the node version is v13.1.0.

**Comment by DanielRuf** [comment]
And your npm version?

**Comment by ghost** [comment]
Getting this on a Gatsby project. Node v 13.1 and npm 6.12.1, macOS Cataline, 10.15.0

**Comment by DanielRuf** [comment]
See https://github.com/npm/cli/issues/417

Let's discuss this there.

**Comment by RichGlz** [comment]
Hi there, I got the same problem creating a new Angular Project:

#### Information about versions:

###### __Node:__ v13.1.0   |   __npm:__ 6.12.1

1) #### During installation I got this message:

```PowerShell
npm WARN deprecated fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 
1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size
```

2) #### After finish, I got this error:

```PowerShell
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!   <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!   C:\Users\Username\AppData\Roaming\npm-cache\_logs\2019-11-14T00_11_16_075Z-debug.log
Package install failed, see above.
```
---
### Extra

##### When I try to upgrade *fsevents* to v2 (as the message 1. says) by:
``` npm install -g fsevents```

#### I got this message:

```PowerShell
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Username\AppData\Roaming\npm-cache\_logs\2019-11-14T00_46_00_606Z-debug.log
```
### Computer Info:

###### SO: Microsoft Windows 10 Pro  |  SO version: 10.0.18362  |  System: x64-based PC

 Thanks for your active help!

**Comment by mikemimik** [comment]
Duplicate issue; aggregating into https://github.com/npm/cli/issues/417.

**Comment by HemangSidapara** [comment]
**When called ng new my-app then get error:**

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\heman\AppData\Roaming\npm-cache\_logs\2020-04-09T06_59_03_102Z-debug.log

**If anyone have solution then share it**

**Comment by Joesac** [comment]
I got this issue when creating a new angular project

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Joesac\AppData\Roaming\npm-cache\_logs\2020-11-28T22_54_00_145Z-debug.log

my node version is 14.15.1
npm version 6.14.5

**Comment by ghost** [comment]
I got this issue when creating a new angular project
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wasim\AppData\Local\npm-cache\_logs\2021-03-18T08_49_12_555Z-debug.log

my node version is 14.16.0
npm version 7.6.3
