### ISSUE TITLE
[BUG] postinstall script does not run

### ISSUE THREAD

**Issue by Roaders** [npm/cli#4750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

a post install script should run after a package is installed. In npm 8 it does not.

### Expected Behavior

the postinstall script should run

### Steps To Reproduce

create a new package with a `postinstall` script:

```json
{
    "scripts": {
        "postinstall": "echo \"hello world from postinstall\""
    }
}
```

run `npm pack`
install the generated tgz from another package.
no message is logged when running npm 8

### Environment

- npm: 8.6.0
- Node.js: v16.13.0
- OS Name: Windows
- System Model Name:
- npm config:
```ini
_auth = (protected)
access = null
all = false
allow-same-version = false
also = null
audit = true
audit-level = null
auth-type = "legacy"
before = null
bin-links = true
browser = null
ca = null
cache = "C:\\Users\\Giles\\AppData\\Local\\npm-cache"
cache-max = null
cache-min = 0
cafile = null
call = ""
cert = null
ci-name = null
cidr = null
color = true
commit-hooks = true
depth = null
description = true
dev = false
diff = []
diff-dst-prefix = "b/"
diff-ignore-all-space = false
diff-name-only = false
diff-no-prefix = false
diff-src-prefix = "a/"
diff-text = false
diff-unified = 3
dry-run = false
editor = "notepad.exe"
engine-strict = false
fetch-retries = 2
fetch-retry-factor = 10
fetch-retry-maxtimeout = 60000
fetch-retry-mintimeout = 10000
fetch-timeout = 300000
force = false
foreground-scripts = false
format-package-lock = true
fund = true
git = "git"
git-tag-version = true
global = false
global-style = false
globalconfig = "C:\\Users\\Giles\\AppData\\Roaming\\npm\\etc\\npmrc"
heading = "npm"
https-proxy = null
if-present = false
ignore-scripts = false
include = []
include-staged = false
include-workspace-root = false
init-author-email = ""
init-author-name = ""
init-author-url = ""
init-license = "ISC"
init-module = "C:\\Users\\Giles\\.npm-init.js"
init-version = "1.0.0"
init.author.email = ""
init.author.name = ""
init.author.url = ""
init.license = "ISC"
init.module = "C:\\Users\\Giles\\.npm-init.js"
init.version = "1.0.0"
json = false
key = null
legacy-bundling = false
legacy-peer-deps = false
link = false
local-address = null
location = "user"
lockfile-version = null
loglevel = "notice"
logs-dir = null
logs-max = 10
; long = false ; overridden by cli
maxsockets = 15
message = "%s"
metrics-registry = "https://registry.npmjs.org/"
node-options = null
node-version = "v16.13.0"
noproxy = [""]
npm-version = "8.6.0"
offline = false
omit = []
only = null
optional = null
otp = null
pack-destination = "."
package = []
package-lock = true
package-lock-only = false
parseable = false
prefer-offline = false
prefer-online = false
; prefix = "C:\\Program Files\\nodejs" ; overridden by builtin
preid = ""
production = null
progress = true
proxy = null
read-only = false
rebuild-bundle = true
registry = "https://registry.npmjs.org/"
save = true
save-bundle = false
save-dev = false
save-exact = false
save-optional = false
save-peer = false
save-prefix = "^"
save-prod = false
scope = ""
script-shell = null
searchexclude = ""
searchlimit = 20
searchopts = ""
searchstaleness = 900
shell = "C:\\WINDOWS\\system32\\cmd.exe"
shrinkwrap = true
sign-git-commit = false
sign-git-tag = false
sso-poll-frequency = 500
sso-type = "oauth"
strict-peer-deps = false
strict-ssl = true
tag = "latest"
tag-version-prefix = "v"
timing = false
tmp = "C:\\Users\\Giles\\AppData\\Local\\Temp"
umask = 0
unicode = false
update-notifier = true
usage = false
user-agent = "npm/{npm-version} node/{node-version} {platform} {arch} workspaces/{workspaces} {ci}"
userconfig = "C:\\Users\\Giles\\.npmrc"
version = false
versions = false
viewer = "browser"
which = null
workspace = []
workspaces = null
workspaces-update = true
yes = null
```

**Comment by lukekarrys** [comment]
Can you try running install with `--foreground-scripts`. npm 8 hides the output of postinstall scripts by default, but it can be shown with that flag

**Comment by Roaders** [comment]
OK, I'll try with that. Thanks.
Where is this documented? I haven't found any breaking changes information that would say that this is no longer printed out. `--foreground-scripts` is also not mentioned when doing `npm install -h`.

**Comment by ljharb** [comment]
It should be in the npm v7.0 changelog.

**Comment by Cactusbone** [comment]
@Roaders did `--foreground-scripts` fix your issue ? (I'm having a similar issue and wanted to know if I should open a new issue :) )

**Comment by Roaders** [comment]
yes, `--foreground-scripts` does re-enable the removed feature of showing errors when things don't work (even though it's not listed in the help).

**Comment by zWingz** [comment]
still not run in npm@8.19.4, but work in npm@6.x

npm@8.x
<img width="559" alt="image" src="https://github.com/npm/cli/assets/13031838/40c6ff35-fcfb-4e66-818d-95373d8af081">

npm@6
<img width="747" alt="image" src="https://github.com/npm/cli/assets/13031838/3c1e829e-1e7d-4666-8190-bbe49d7dd947">

**Comment by Cactusbone** [comment]
@zWingz Are you on a custom registry ? Is so You're probably having [[BUG] Regression: custom scripts not executed on dependencies from custom registry · Issue #4821 · npm/cli · GitHub](https://github.com/npm/cli/issues/4821)

**Comment by zWingz** [comment]
@Cactusbone I found the reason. It is because I use the package [pinst](https://www.npmjs.com/package/pinst) to change my scripts `_postinstall` to `postinstall` on `beforePublishOnly`.
When I use yarn to publish the package. It will update the package's manifest with `_postinstall`([yarn](https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/publish.js#L45)) before the `pinst` to change the script to `postinstall`. so the scripts `postinstall` was ignored in manifest.

When I use npm to publish the package. It work correctly
