### ISSUE TITLE
[BUG] ping github private registry states package [ping] was not found

### ISSUE THREAD

**Issue by eddiecorrigall** [npm/cli#4751]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When using the npm ping command to test a GitHub private registry, the command responses with "package [ping] was not found". Used many times before without issue, just not today.

### Expected Behavior

Expected command to return non-zero since the GitHub Personal Access Token is valid and works to install packages.

Did not expect GitHub to response to a "ping" command with: "package [ping] was not found".

### Steps To Reproduce

1. In this environment...
    - Latest npm installed
    - GitHub personal access token is setup in `~/.npmrc`
    - Can install packages from private registry
    - NPM ping command for private registry worked this week - today it does not
1. With this `~/.npmrc` config...
    ```
    @myorganization:registry=https://npm.pkg.github.com
    //npm.pkg.github.com/:_authToken=mygithubpersonalaccessotken
    ```
1. Run `npm ping --quiet --registry https://npm.pkg.github.com`
1. See error...

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://npm.pkg.github.com/-/ping?write=true - Package [ping] was not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2022-04-14T12_36_19_012Z-debug.log
```

---

Alternatively.

1. In this environment... same as above.
1. With this `~/.npmrc` config... same as above.
1. Navigate to URL... https://npm.pkg.github.com/-/ping?write=true
    - Enter GitHub username, and
    - GitHub Personal Access token as password.
1. See error...

<img width="401" alt="Screen Shot 2022-04-14 at 8 39 15 AM" src="https://user-images.githubusercontent.com/4554187/163392248-ea58b8df-263a-4cb4-b7f9-6734720e08df.png">

### Environment

- npm: `8.6.0`
- Node.js: `v16.14.2`
- OS Name: macOS Big Sur 11.6.4
- System Model Name: Macbook Pro
- npm config:
```ini
; "user" config from /Users/eddie/.npmrc

@myorganization:registry = "https://npm.pkg.github.com"
//npm.pkg.github.com/:_authToken = (protected)

; node bin location = /Users/eddie/.nvm/versions/node/v16.14.2/bin/node
; cwd = /Users/eddie
; HOME = /Users/eddie
; Run `npm config ls -l` to show all defaults.
```

**Comment by eddiecorrigall** [comment]
Started a discussion with GitHub:
https://github.com/github/feedback/discussions/14943

**Comment by eddiecorrigall** [comment]
Now it works again. Perhaps GitHub fixed this API?

**Comment by fritzy** [comment]
**Closing:** this looks to be an issue with the registry which is outside the scope of this repo.
