### ISSUE TITLE
[BUG] .npmrc has no effect on indirect dependencies

### ISSUE THREAD

**Issue by fltenwall** [npm/cli#4762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

.npmrc has invalid dependencies on dependencies, as shown below

```shell
registry=https://registry.npm.taobao.org/
A:registry=A'
C:registry=C'
```

Private position C 'that indirectly depends on C Settings is invalid

The background of this problem is that I have A project whose direct dependency on A is A ', and another direct dependency on B that depends on C is C '. After I set the corresponding cache to A and C in the.npmrc file, the indirect dependency on C will not take effect and its address will be the global address

### Expected Behavior

I hope you can solve this problem, this scenario may not be very common, but if this problem is encountered it cannot be solved by NPM at present

### Steps To Reproduce

1. In this environment

I tried two environments：

node  v14.18.3
npm 6.14.8

and 

node  v16.14.2
npm  8.7.0

2. With this config

.npmrc
```shell
registry=https://registry.npm.taobao.org/
A:registry=A'
C:registry=C'
```

Where A is the direct dependence of the project, A 'is the private warehouse of A; B is the indirect dependency of the project, and C 'is its secret compartment

3. Run 

Then `npm install` 

And then you'll see that C's address is wrong

### Environment

- npm: 6.14.8  or 8.7.0
- Node.js: v14.18.3 or v16.14.2
- OS Name: Mac OS 11.6.2
- System Model Name: Mac mini (2018)

**Comment by ljharb** [comment]
A dep installed from a specific registry must have its entire subgraph on that registry. Is that the issue here?

**Comment by fritzy** [comment]
This seems like an assumed behavior and may be a request for new behavior. Dependency resolution is much more subtle than sub-dependencies, and often has multiple solutions based on the timeline of adding dependencies. This new behavior would need to be well defined.

Can you create [an RRFC](https://github.com/npm/rfcs/issues/new?assignees=&labels=&template=rrfc.md&title=%5BRRFC%5D+%3Ctitle%3E) in that repo?
