### ISSUE TITLE
[BUG] <Npm install and upgrade causes Monorepo package dependancy to display" Couldn't find package "@MonoreporName/PackageName@" required by "@MonoreporName/PackageName@" on the "npm" registry">

### ISSUE THREAD

**Issue by someGuySeekingAnswers** [npm/cli#4764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

In the current version 8.7.  In a workspace like 
-- packages
   -- package1
    --package2

Running npm install or upgrade will throw and error 
`error Couldn't find package "@reponame/common@^1.0.307" required by "@reponame/browser@1.0.307" on the "npm" registry.   
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Couldn't find package "@twtr/common@^1.0.307" required by "@twtr/server@1.0.307" on the "npm" registry.   
    at MessageError.ExtendableBuiltin (C:\Program Files (x86)\Yarn\lib\cli.js:721:66)
    at new MessageError (C:\Program Files (x86)\Yarn\lib\cli.js:750:123)
    at PackageRequest.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (C:\Program Files (x86)\Yarn\lib\cli.js:304:30)
    at C:\Program Files (x86)\Yarn\lib\cli.js:317:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
`

### Expected Behavior

To install dependencies without error-free and update package.json properly.

### Steps To Reproduce

Create a monorepo such as
repo
  --package.json
  -- packages
    -- package1
        --package.json
     --package2
        --package.json
and run npm install or npm upgrade

### Environment

- npm: v8.7
- Node.js: v 16,4
- OS Name: Windows 10

**Comment by fritzy** [comment]
These appear to be errors generated by yarn, not npm.
