### ISSUE TITLE
[BUG] `npm audit fix` moving subdependencies from root to parent dependency

### ISSUE THREAD

**Issue by backflip** [npm/cli#4790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

After running `npm audit fix` in a Next.js / Storybook project, Storybook stopped working. Turns out `npm audit fix` was moving a subdependency from the root to its parent dependency and I was incorrectly relying on this subdependency.

Specifically, `@storybook/addon-docs` was moved from `node_modules/` to `node_modules/@storybook/addon-essentials/node_modules/`.

### Expected Behavior

This is more of a question: Should `npm audit fix` move subdependencies around? 

The proper solution is obviously to add `@storybook/addon-docs` to `devDependencies` when planning on importing it anywhere, but I was still surprised by this behavior.

### Steps To Reproduce

See https://github.com/backflip/npm-testcase:
- The first commit sets up the project with Storybook, React and an ESLint plugin (I started with my original project and removed all dependencies I did not need to reproduce the problem).
- Running `npm run build-storybook` works fine.
- Running `npm audit fix` will change the lock file as documented in the second commit. The specific issue is `node_modules/@storybook/addon-docs` being changed to `node_modules/@storybook/addon-essentials/node_modules/@storybook/addon-docs`: https://github.com/backflip/npm-testcase/commit/fac8b4eafbc30a46a3aa5eea052bd224883dd5f7#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519R3246
- Running `npm run build-storybook` fails with `Module not found: Error: Can't resolve '@storybook/addon-docs'`

### Environment

- npm: 8.0.0 (but reproduced on another machine with latest v8)
- Node.js: 16.11.1  (but reproduced on another machine with latest v16)
- OS Name: macOS
- System Model Name: 12.3
- npm config:
```ini
; "user" config from /Users/USER/.npmrc
; node bin location = /Users/USER/.nvm/versions/node/v16.11.1/bin/node
; cwd = /Users/USER/npm-testcase
; HOME = /Users/USER
; Run `npm config ls -l` to show all defaults.
```

**Comment by ljharb** [comment]
Yes, you have no guarantees about the layout of node_modules except that you can require things you directly depend on.

**Comment by wraithgar** [comment]
Yes this is expected, as @ljharb noted.  Many factors go into this including bundling and hoisting.  Typically what happens in cases like this is that whatever is requiring `@storybook/addon-docs` did not declare it as a dependency itself, and was relying it on it being hoisted, which is not guaranteed.  You were correct when you said:

> The proper solution is obviously to add @storybook/addon-docs to devDependencies when planning on importing it anywhere, but I was still surprised by this behavior.

Never rely on hoisting, if you need to require a dependency in a package, declare that dependency in the package.json

**Comment by backflip** [comment]
@ljharb, @wraithgar, thanks for the clarification!
