### ISSUE TITLE
i am getting an error in my npm when trying to install expo-cli globally, can anyone help me on how to fix this issues

### ISSUE THREAD

**Issue by Emmybritt** [npm/cli#4792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Problem, not another kind of Docs Problem.

- [X] This is a CLI Docs Problem.

### Description of Problem

when i try to install npm globally, using the command npm install -g expo-cli i am getting an error that says

npm install -g expo-cli npm ERR! code ERR_OSSL_UNSUPPORTED npm ERR! error:1E08010C:DECODER routines::unsupported

npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\user\AppData\Local\npm-cache_logs\2022-04-20T21_10_42_635Z-debug-0.log

although i just updated my node version to version 17.9.0 and my npm version is 8.5.5

please any suggestion of what i can do to solve this problem

**Comment by wraithgar** [comment]
A quick search of `ERR_OSSL_UNSUPPORTED` seems to indicate this may be a [node17 / openssl issue](https://www.code4copy.com/post/err_ossl_evp_unsupported-on-nodejs-17/).  Please use the full issue template when opening issues.

This does not appear to be an npm cli issue.

**Comment by olasamuel486** [comment]
Am  also facing the same problem  trying to  Install Express.js 
npm ERR! error:1E08010C:DECODER routines::unsupported

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\samstrings\AppData\Local\npm-cache\_logs\2022-08-04T19_06_26_062Z-debug-0.log

**Comment by Jaleyvazli** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### This is a CLI Docs Problem, not another kind of Docs Problem.
> * [x]  This is a CLI Docs Problem.
> 
> ### Description of Problem
> when i try to install npm globally, using the command npm install -g expo-cli i am getting an error that says
> 
> npm install -g expo-cli npm ERR! code ERR_OSSL_UNSUPPORTED npm ERR! error:1E08010C:DECODER routines::unsupported
> 
> npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\user\AppData\Local\npm-cache_logs\2022-04-20T21_10_42_635Z-debug-0.log
> 
> although i just updated my node version to version 17.9.0 and my npm version is 8.5.5
> 
> please any suggestion of what i can do to solve this problem
> 
> ### Potential Solution
> _No response_
> 
> ### Affected URL
> _No response_

Hi, how did you solve this problem?

**Comment by chiedozie013** [comment]
please has anyone resolved this err_OSSL_UNSUPPORTED error? it's killing me. i cant run react on my PC

**Comment by olasamuel486** [comment]
Remove the old expo-cli that was install globally By using this command line  for example npm uninstall -g @angular/cli. Npm uninstall -g  cli-poSent from Mail for Windows From: James Chiedozie JamesSent: Thursday, January 26, 2023 8:12 PMTo: npm/cliCc: olasamuel486; CommentSubject: Re: [npm/cli] i am getting an error in my npm when trying to install expo-cli globally, can anyone help me on how to fix this issues (Issue #4792) please has anyone resolved this err_OSSL_UNSUPPORTED error? it's killing me. i cant run react on my PC—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by lilseniorj** [comment]
I've been looking for a solution to this create-react-app problem for about 4 months and I haven't been able to find a solution. Anyone who knows how to solve it please share the solution so I don't kill myself every time I want to find the solution.

npm ERR! code ERR_OSSL_UNSUPPORTED
npm ERR! error:1E08010C:DECODER routines::unsupported

**Comment by Imohh** [comment]
i have been dealing with this issue for a few hours now. i have tried everything, nothing works. somebody help!

**Comment by sami7568** [comment]
I've just solve this issue, steps to do 
you have to open a file and remove key from this file.
* open ~/.npmrc
* remove key=value
and this will work.
