### ISSUE TITLE
[BUG] 413 Payload Too Large

### ISSUE THREAD

**Issue by victorrica** [npm/cli#4794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

The following error was displayed during the publishing process.
```
npm notice === Tarball Details ===
npm notice name:          pretendard
npm notice version:       1.3.0
npm notice filename:      pretendard-1.3.0.tgz
npm notice package size:  229.9 MB
npm notice unpacked size: 297.7 MB
npm notice shasum:        2864736d7b895c59a13c128bfcba83fbb12bb891
npm notice integrity:     sha512-WddoMy1XB6V5U[...]pFpNxaVn2XyEw==
npm notice total files:   4110
npm notice
npm ERR! code E413
npm ERR! 413 Payload Too Large - PUT https://registry.npmjs.org/pretendard - Payload Too Large

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/phoary/.npm/_logs/2022-04-22T06_19_17_772Z-debug.log
```

There is no file size limit in the npm document, so how much is the size limit of the package? Or is there any option to upload more than 300MB size package?

repo url
https://github.com/orioncactus/pretendard

### Environment

- npm: 8.1.4
- Node.js: 16.13.1
- OS Name: MacOS Montery
- npm config:
```ini
; "builtin" config from /opt/homebrew/lib/node_modules/npm/npmrc

prefix = "/opt/homebrew"

; "user" config from /Users/phoary/.npmrc

//registry.npmjs.org/:_authToken = (protected)

; node bin location = /usr/local/bin/node
; cwd = /Users/phoary/Documents/pretendard
; HOME = /Users/phoary
; Run `npm config ls -l` to show all defaults.
```

**Comment by wraithgar** [comment]
The cli itself does not limit payload sizes, it works with many different registries. Each one can set their own upload size limit and the 413 response is how they indicate that an upload is too large.  This is not something the npm cli can do anything about.

You can contact the npm registry for support at https://www.npmjs.com/support
