### ISSUE TITLE
npm ERR! Exit handler never called!

### ISSUE THREAD

**Issue by shehzad75** [npm/cli#4798]
└─$ npm install
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kali/.npm/_logs/2022-04-24T11_44_15_288Z-debug-0.log
┌──(kali㉿localhost)-[~/botnet/lemon]
└─$ ls
app  assets  clientData  includes  index.js  package-lock.json  package.json
┌──(kali㉿localhost)-[~/botnet/lemon]
└─$ npm install
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kali/.npm/_logs/2022-04-24T11_47_06_467Z-debug-0.log

**Comment by darcyclarke** [comment]
Closing: There is not enough information in this issue to help debug your problem. Please use our issue template (here: https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+8.x&template=bug_8.yml&title=%5BBUG%5D+%3Ctitle%3E) & refile).
