### ISSUE TITLE
Pacstall

### ISSUE THREAD

**Issue by trymeouteh** [npm/cli#4802]
Please add this app into the pacstall repository. Pacstall is the AUR for Ubuntu which will allow Ubuntu users to easily install the app and receive updates very shortly after an update is released.

https://pacstall.dev/

**Comment by ljharb** [comment]
npm ships with node, and node doesn't officially distribute in AUR, so i'm not sure that'd make much sense. For node, Ubuntu users have the same official option as everyone else: to install from nodejs.org manually, or use a version manager that automates that.

**Comment by darcyclarke** [comment]
Closing: consider opening an issue on our [`npm/rfcs`](https://github.com/npm/repos) repo (where we discuss feature requests/ideas/proposals etc.)
