### ISSUE TITLE
[BUG] --install-links creates symlinks

### ISSUE THREAD

**Issue by oshi97** [npm/cli#4803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Installing a local npm package with `--install-links` creates a symlink.

### Expected Behavior

When set file: protocol dependencies that exist outside of the project root will be packed and installed as regular dependencies instead of creating a symlink.

### Steps To Reproduce

1. `git clone https://github.com/oshi97/install-links.git`
2. `cd parent`
3. `npm i ../child --install-links`
4. `ls -l`
5. see a symlink, `lrwxr-xr-x  1 oshi  staff  11 Apr 25 16:25 child -> ../../child`

### Environment

- npm: 8.7.0
- Node.js: 16.14.2
- OS Name: macOS Monterey
- System Model Name: 2013 Mac Pro
- npm config:
```ini
; "user" config from /Users/oshi/.npmrc

//registry.npmjs.org/:_authToken = (protected) 

; node bin location = /Users/oshi/.nvm/versions/node/v16.14.2/bin/node
; node version = v16.14.2
; npm local prefix = /Users/oshi/techops/install-links-test/parent
; npm version = 8.7.0
; cwd = /Users/oshi/techops/install-links-test/parent
; HOME = /Users/oshi
; Run `npm config ls -l` to show all defaults.
```

**Comment by nlf** [comment]
the `--install-links` flag was added in npm@8.8.0, you'll need to update to at least that version to use it
