### ISSUE TITLE
[BUG] <npm publish command is delayed>

### ISSUE THREAD

**Issue by McStip9** [npm/cli#4812]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Hey guys, I published a new version for my package "quickfunc", 1.2.3, but on npmjs.com it only shows 1.2.0 when I published it. Does anyone know about this issue? It seems to me that it is delaying the updates.

### Expected Behavior

What I expected is that it would quickly update on npmjs.com, so that people could install the new update quickly.

### Steps To Reproduce

1. Update your package, as usual.
2. `npm version ...` to update the version
3. `npm publish` to publish the new update
4. npmjs.com shows 2 versions before the new update.

### Environment

- npm: 8.7.0
- Node.js: v17.9.0
- OS Name: Windows 11 Home Single
- System Model Name: Lenovo IdeaPad 3 15IT05
- npm config:
```ini
; "user" config from /home/realguystuff/.npmrc

//registry.npmjs.org/:_authToken = (protected)

; node bin location = /home/realguystuff/.nvm/versions/node/v17.9.0/bin/node
; node version = v17.9.0
; npm local prefix = /mnt/c/Users/Family/OneDrive/Desktop/projects/quickfunctions
; npm version = 8.7.0
; cwd = /mnt/c/Users/Family/OneDrive/Desktop/projects/quickfunctions
; HOME = /home/realguystuff
; Run `npm config ls -l` to show all defaults.
```

**Comment by jrpool** [comment]
Same for me. Search shows the latest version, but the package page and the version list do not.

**Comment by lukekarrys** [comment]
**Closing:** this looks to be an issue with the registry which is outside the scope of this repo. For registry support please go to [npmjs.com/support](https://www.npmjs.com/support).
