### ISSUE TITLE
cannot input password when "npm login" or "npm adduser" at command line

### ISSUE THREAD

**Issue by bim2016** [npm/cli#4817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

C:\Users\bim2016>npm whoami
npm WARN config [init.author.name](http://init.author.name/) Use `--init-author-name` instead.
npm WARN config init.license Use `--init-license` instead.
npm WARN config init.author.email Use `--init-author-email` instead.
bim2016

Password: [enter your password, it will be encrypted]
i tried both npm adduser and npm login at command line but Password is disabled, means i cannot type in (simply not allowed), not because encrypted.

### Expected Behavior

Password: [enter your password, it will be encrypted]
can input password at command line

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run npm login or npm adduser
4. See error...

### Environment

- npm: 8.8.0
- Node.js: v16.15.0
- OS Name: Windows 10 Home, Version 21H1, OS Build 19043.1645
- System Model Name: LAPTOP-EQDRA12L
- npm config:
```ini
npm WARN config init.author.name Use `--init-author-name` instead.
npm WARN config init.license Use `--init-license` instead.
npm WARN config init.author.email Use `--init-author-email` instead.
; "builtin" config from C:\Users\bim2016\AppData\Roaming\npm\node_modules\npm\npmrc
prefix = "C:\\Users\\bim2016\\AppData\\Roaming\\npm"
; "user" config from C:\Users\bim2016\.npmrc
//registry.npmjs.org/:_authToken = (protected)
init-license = "MIT"
init.author.email = "bim2016@gmail.com"
init.author.name = "Joe"
init.license = "MIT"
init.main = "app.js"
iniy-author-name = "joe"
registry = "http://registry.npmjs.org/"
```

**Comment by ljharb** [comment]
Are you sure it's not just hiding your input? Password input prompts on shells always show nothing as you type, to avoid onlookers being able to see your password.

**Comment by bim2016** [comment]
thanks Jordan, see below messages along w/ attached log file FYI:

C:\Users\bim2016>npm login
npm WARN config init.author.name Use `--init-author-name` instead.
npm WARN config init.license Use `--init-license` instead.
npm WARN config init.author.email Use `--init-author-email` instead.
npm notice Log in on http://registry.npmjs.org/
npm notice Beginning October 4, 2021, all connections to the npm registry -
including for package installation - must use TLS 1.2 or higher. You are
currently using plaintext http to connect. Please visit the GitHub blog for
more information:
https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
Username: bim2016
Password:
Email: (this IS public) ***@***.***
npm notice Beginning October 4, 2021, all connections to the npm registry -
including for package installation - must use TLS 1.2 or higher. You are
currently using plaintext http to connect. Please visit the GitHub blog for
more information:
https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
npm notice Beginning October 4, 2021, all connections to the npm registry -
including for package installation - must use TLS 1.2 or higher. You are
currently using plaintext http to connect. Please visit the GitHub blog for
more information:
https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
npm ERR! code E426
npm ERR! 426 Upgrade Required - PUT
http://registry.npmjs.org/-/user/org.couchdb.user:bim2016
npm ERR! A complete log of this run can be found in:
npm ERR!
C:\Users\bim2016\AppData\Local\npm-cache\_logs\2022-04-27T21_03_00_443Z-debug-0.log

Cheers, Joe

**Comment by ljharb** [comment]
The error messages imply you're connecting to the registry via HTTP. Is that in your config? I'd expect only an HTTPS connection.

**Comment by bim2016** [comment]
hi Jordan, any progress? thanks. Joe

**Comment by nlf** [comment]
@bim2016 try changing your `registry` line in your `.npmrc` file to `registry=https://registry.npmjs.org`. you could also remove the line entirely since that's the default

**Comment by bim2016** [comment]
thanks Jordan, that seems working even though i got below error when npm
login due to annoying OTP code (one-time password) requirement, is it
possible to disable it or at least make valid time limit longer? again,
very appreciated for your help! Joe
npm notice ERROR: Auth rate limited
npm ERR! code E429
npm ERR! 429 Too Many Requests - PUT
https://registry.npmjs.org/-/user/org.couchdb.user:bim2016

**Comment by wraithgar** [comment]
Looks like you got the original issue solved.

The 429 rate limiting is something the npm registry itself sends, the cli doesn't have any control over that. You either have to wait that out or contact [support](https://www.npmjs.com/support) if it is happening when it shouldn't.

**Comment by bim2016** [comment]
Ok, thanks.
