### ISSUE TITLE
[DOCS] <npm unpublish name --force i do this Wrong operation>

### ISSUE THREAD

**Issue by ShuangDa1018** [npm/cli#4820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Problem, not another kind of Docs Problem.

- [X] This is a CLI Docs Problem.

### Description of Problem

I accidentally ran the command ，My important items were deleted。how should i do ?

### Potential Solution

i   need Restore my project

### Affected URL

https://www.npmjs.com/

**Comment by ljharb** [comment]
You need to file an npm support ticket for this; this repo is for the CLI itself.

**Comment by ShuangDa1018** [comment]
> 您需要为此提交 npm 支持票；这个 repo 是针对 CLI 本身的。
Do you have a solution ，my handsome programmer

**Comment by ljharb** [comment]
The solution is to file a support ticket. I’ll close this.

**Comment by ShuangDa1018** [comment]
> The solution is to file a support ticket. I’ll close this.

ok,i love u my baby

**Comment by ljharb** [comment]
Those kind of comments aren’t appropriate, thanks.

**Comment by ShuangDa1018** [comment]
> Those kind of comments aren’t appropriate, thanks.

have a good day, begin When u meet me
