### ISSUE TITLE
WTF!? Log in is complety broken!?

### ISSUE THREAD

**Issue by blaasvaer** [npm/cli#4822]
I've spent an hour now trying to first log in to my account, and then trying to patch and publish a package.

Now, I've hit the: 429 Too Many Requests situation due to a whirlwind of OTPs and failed logins ... now does anyone have any advice on how to actually be able to log into ones npm account from the Terminal and publish a package ... used to work, now it's completely impossible to do any of that.

I've both enabled and disabled 2FA as it only seemed to make it all even worse ... but neither situation will let me log in to my account.

**Comment by darcyclarke** [comment]
@blaasvaer sorry to hear you're having issues; that said, this backlog is actually mean for `npm` CLI-specific bugs. If you reach out to our support team, they should be able to help you with any website/registry/account/login related issues (ref. https://www.npmjs.com/support)
