### ISSUE TITLE
[BUG] Incorrect peerDeps conflict identification

### ISSUE THREAD

**Issue by Mr0cket** [npm/cli#4823]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```
code ERESOLVE
ERESOLVE unable to resolve dependency tree

While resolving: <package_name>
Found: graphql@15.8.0
node_modules/graphql
  graphql@"^15" from the root project

Could not resolve dependency:
peer graphql@"0.13.0 | 14.x | 15.x" from aws-appsync@4.1.5
node_modules/aws-appsync
  aws-appsync@"^4.0.5" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
```

### Expected Behavior

`aws-appsync` package peer dependency range is: "`0.13.0` | `14.x` | `15.x`"
Installed version of `graphql` is: `15.8.0`.

`15.8.0` is inside of the dependency range (`15.x`). 

npm should not error for this peer dependency.

### Steps To Reproduce

In empty directory:
1. `npm init -y`
2. `npm i graphql@^15`
3. `npm i aws-appsync`

### Environment

- npm: 8.8.0
- Node.js: v14.9.0
- OS Name: macOS
- System Model Name: m1 Macbook pro
- npm config:
```ini
audit-level = "low"
package-lock = false
strict-peer-deps = false

; node bin location = /Users/<username>/.nvm/versions/node/v14.19.0/bin/node
; node version = v14.19.0
; npm version = 8.8.0
; HOME = <user home>
```

**Comment by ljharb** [comment]
I think semver uses ||, not | - it may be that aws-appsync has declared an invalid peer dep?

You can verify this on https://semver.npmjs.com/

**Comment by Mr0cket** [comment]
@ljharb Thanks, I believe you're correct... issue can be considered as resolved

**Comment by ljharb** [comment]
I’d suggest filing a bug on that package :-)

**Comment by Mr0cket** [comment]
Already on it ;)
