### ISSUE TITLE
[DOCS] npm pkg delete complex key

### ISSUE THREAD

**Issue by atomiks** [npm/cli#4829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Enhancement, not another kind of Docs Enhancement.

- [X] This is a CLI Docs Enhancement.

### Description of Problem

The docs don't mention how to delete a complex key.

I have an `exports` key that I need to delete before publish, but I'm not sure how (or if it's possible). I want to delete `"./src/index.ts"` before publish because it's only used as an entry point in the monorepo for development:

```json
  "exports": {
    ".": {
      "import": {
        "development": "./dist/floating-ui.dom.esm.development.js",
        "production": "./dist/floating-ui.dom.esm.min.js",
        "default": "./dist/floating-ui.dom.esm.js"
      },
      "require": "./dist/floating-ui.dom.cjs"
    },
    "./package.json": "./package.json",
    "./src/index.ts": "./src/index.ts"
  },
```

`npm pkg delete exports../src/index.ts` does not work. Tried escape characters/quotes too

### Docs URL

https://docs.npmjs.com/cli/v8/commands/npm-pkg

**Comment by ljharb** [comment]
Why can’t the exports path remain, and you just npmignore the file?

**Comment by atomiks** [comment]
Skypack CDN errors when building as it can't find the module: https://github.com/floating-ui/floating-ui/issues/1661

**Comment by ljharb** [comment]
Seems like a bug in skypack, since an unimported path shouldn’t even be checked.

**Comment by wraithgar** [comment]
```sh
~/D/n/s/foo $ npm pkg set "foo[.].bar"=bin
~/D/n/s/foo $ npm pkg get foo
{
  ".": {
    "bar": "bin"
  }
}
```

[Docs will be updated](https://github.com/npm/cli/pull/4847)
