### ISSUE TITLE
Npm ci --workspace=<name> drops items in /.bin folder

### ISSUE THREAD

**Issue by klimashkin** [npm/cli#4830]
Hello,

If a workspace has a dependency that requires having its own node_modules, and we run `npm ci -w=<name>` in the parent to the workspace's folder, then it wipes out everything from the parent's node_modules/.bin, and puts there only scripts that belong to that workspace.

Found it out by missing `gulp` which is usually installed on the parent level, it disappears in that case.

Not sure if it's a bug or `ci` is not meant to work with workspaces at all

Version: 8.5.5

**Comment by wraithgar** [comment]
`ci` does work in the context of workspaces but it doesn't work like, say `run-script` or `bugs`.  For commands that install packages, the workspace flags limit the context to those of the workspaces listed.  However installations are still always done from the scope of the root project.  So npm is working as intended here.

The only hole in all of this is that currently the `node_modules` of all your workspaces aren't properly being removed prior to this process, which is not part of this issue but we did realize it why triaging it. https://github.com/npm/cli/issues/4846

Workspaces should never rely on having their own content in node_modules. That directory will only exist if they have non-hoistable dependencies.

**Comment by klimashkin** [comment]
Hi @wraithgar, thanks for the response!

I understand your reasoning, but let me tell you about a couple of cases we've been trying to solve in our organization, and maybe you can help with guiding me in the right direction.

1.  We have multiple workspaces in the repo, which can come and go depending on the branch you are on. We've built a pretty sophisticated sh hook to determine the root package-lock changes between what a developer has locally versus what they are checking out from the git repo. If there are differences, we force running `npm ci --prefer-offline` before the desired script (gulp, npm run, etc) will be executed. We've chosen `ci` to make sure everyone has a snapshot of deps exactly how it's described in package-lock, and it's consistent.
And if a developer for some reason doesn't have a `node_modules` folder in a workspace-a, but the root package-lock contains `workspace-a/node_modules/<package>`, and there are no other differences, then we wanted the sh script to run `npm ci -w=worspace-a`, for faster installation of deps only for that workspace. In other words, we would expect the workspace `ci` to be _additive_ to whatever is already installed in root and other workspaces.

2. In the actual ci (in our case it's Jenkins), we would expect to run `npm ci -w=worspace-a` to install the dependencies of that workspace, plus the root dependencies, because the root dependencies contain some common deps, like Babel, Webpack, Gulp etc. We don't want to list them in each workspace.
For example, we have a workspace that contains Cypress tests and all the related tools in deps, and we have a separate job on Jenkins to run it. We don't want to install other workspace deps with just `npm ci`, but we want the root dependencies and that specific workspace dependencies to be installed in one go before we run cypress. As far as I understand, there is no such capability right now, is that correct?

I would appreciate any tip from you if there are workarounds, plans to support that in the future, or maybe we use 'npm ci' incorrectly for this case.

**Comment by wraithgar** [comment]
`ci` removes node_modules (and is supposed to remove workspace node_modules, which is an open bug right now).  It is not additive, its entire point is to "clean" before install.

[--include-workspace-root](https://docs.npmjs.com/cli/v8/using-npm/config#include-workspace-root) is the flag you want to incude the root project dependencies when reifying.

**Comment by klimashkin** [comment]
@wraithgar Thanks, we totally missed the [--include-workspace-root](https://docs.npmjs.com/cli/v8/using-npm/config#include-workspace-root) flag!

What about the first case, do you think there is a better way to additively install workspace deps in a dev environment, than `npm ci`
