### ISSUE TITLE
[BUG] Error when package.json exists in volume root on Windows

### ISSUE THREAD

**Issue by 2A5F** [npm/cli#4831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When using `npm i` in an empty directory and a `package.json` exists in volume root
`Error: EPERM: operation not permitted, mkdir 'D:\'` occurred

### Expected Behavior

```
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path D:\Foo/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'D:\Foo\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

Or maybe a more explicit error message

### Steps To Reproduce

```
PS D:\> ls

...

-a----                     0 package.json
```

`D:\Foo` is a empty dir

```
PS D:\Foo> npm i

npm ERR! code EPERM
npm ERR! syscall mkdir
npm ERR! path D:\
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, mkdir 'D:\'
npm ERR!  [Error: EPERM: operation not permitted, mkdir 'D:\'] {
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: 'D:\\'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.
```

### Environment

- npm: 8.5.5
- Node.js: 17.9.0
- OS Name: Windows 11 21H2

**Comment by wraithgar** [comment]
This is by design.  When you run `npm install` it tries to find out what the package root is by walking up directories till it finds a package.json file.  An empty directory is not a package.  Add a package.json file to the directory to make npm treat it like a package.

**Comment by 2A5F** [comment]
Even then it shouldn't appear `Error: EPERM: operation not permitted, mkdir 'D:\'`

**Comment by sohang3112** [comment]
@wraithgar I had the same issue as the original poster - `npm install` raises error (for all packages) when run in a volume root `D:\`, but it works in a subdirectory `D:\Work`. 

As you suggested to @2A5F, I tried adding `package.json` in `D:\` using `npm init`. But `npm install` and `npm install --save` still raise the same `EPERM` error (when run in `D:\`). `npm install -g` *doesn't* raise error - but it doesn't actually install either (trying to `require` the package `node` shows error `MODULE_NOT_FOUND`.

**Note:** I am using Windows 11 - don't know if this is relevant.

**Comment by aayu-11** [comment]
I'm using ubuntu same issue is there can anyone pls help

**Comment by sohang3112** [comment]
@aayu-11 The problem occurs when current directory is top level (no folder above it). I solved problem on Windows by first doing `cd D:/some_folder` and then `npm install`. On Linux, you can try to `cd` to any folder except `/` (root folder). 
Example:
```console
$ cd /home/some.user
$ npm install some_package
```
