### ISSUE TITLE
npm install timeout on work VPN

### ISSUE THREAD

**Issue by aka5050** [npm/cli#4832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When on work VPN (Cisco AnyConnect), running `npm install` or any command which invokes npm to download causes the process to hang until timeout. Running off VPN everything works fine. Running M1 Macbook. Have checked network and firewall with IT several times and they say it all checks out.

**Here is the result after timeout of `npm i`:**
npm ERR! code ETIMEDOUT
npm ERR! syscall connect
npm ERR! errno ETIMEDOUT
npm ERR! network request to http://registry.npmjs.org/aws-cdk failed, reason: connect ETIMEDOUT 2606:4700::6810:1b23:80
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly. See: 'npm help config'

I have run `npm doctor` off VPN and resolved any suggestions it made. When running on VPN `npm doctor` hangs until the following output is produced:

Check                               Value   Recommendation/Notes
npm ping                            ok
npm -v                              ok      current: v8.8.0, latest: v8.8.0
**node -v                             not ok  FetchError: request to https://nodejs.org/dist/index.json failed, reason: connect ETIMEDOUT 2606:4700:10::6814:162e:443**
npm config get registry             ok      using default registry (https://registry.npmjs.org/)
which git                           ok      /usr/bin/git
Perms check on cached files         ok
Perms check on local node_modules   ok
Perms check on global node_modules  ok
Perms check on local bin folder     ok
Perms check on global bin folder    ok
Verify cache contents               ok      verified 9062 tarballs
npm ERR! Some problems found. See above for recommendations.

### Expected Behavior

runs commands without timeout and gets dependencies

### Steps To Reproduce

1. In this environment... Cisco AnyConnect Secure Mobility Client VPN
2. With this config...?
3. Run '...' `npm i` in a npm project, or `npm doctor` or `npx create-react-app <app-name>`
4. See error...

### Environment

- npm: 8.8.0
- Node.js: 18.0.0 and 17.3.0
- OS Name: Monterey 12.3.1
- System Model Name: Macbook Pro M1
- npm config:
```ini
; "user" config from ~/.npmrc

registry = "https://registry.npmjs.org/" 
strict-ssl = false 

; node bin location = ~/.nvm/versions/node/v18.0.0/bin/node
; node version = v18.0.0
; npm local prefix = ~/Development/React/testing-app
; npm version = 8.8.0
; cwd = ~/Development/React/testing-app
; HOME = ~
```

**Comment by wraithgar** [comment]
Are you sure that normal requests to `registry.npmjs.org` work in node when the vpn is connected?  This does not appear to be a problem with npm, it is simply using the networking it is given by the operating system.

**Comment by aka5050** [comment]
I'm not sure of anything related to this issue since it's something I am unfamiliar with. After time spent with IT on this they said that they suspected an issue with NPM so I went ahead and made this ticket. In my opinion an issue with NPM does not make sense in this case since everything works correctly off the VPN and I have not heard of anyone else that I work with having this same problem.
I would appreciate any help in finding the source of the issue since at this point I've exhausted everything I have the ability and knowhow to perform.

**Comment by wraithgar** [comment]
I agree that this does not look like an npm issue.  Feel free to show them this ticket if it helps you get further along with them.

**Comment by aka5050** [comment]
Ok, thank you.
Can you suggest anything I can check on my end, maybe something with configuration of npm for network/vpn?

**Comment by wraithgar** [comment]
The only config would be if you need to use a [proxy](https://docs.npmjs.com/cli/v8/using-npm/config#proxy)
