### ISSUE TITLE
[BUG] init.author.name deprecation warning does not stop

### ISSUE THREAD

**Issue by sourabhv** [npm/cli#4840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```
$ cat ~/.npmrc
init-author-name=<name>
init-author-email=<email>
init-author-url=<url>

$ npm i 
npm WARN config init.author.name Use `--init-author-name` instead.
```

The `init.author.name` warning is still there

### Expected Behavior

Warning `init.author.name` should stop like other 2.

### Steps To Reproduce

1. In this environment...
   Mac OS Monterey on Macbook Pro 16 2021
   Node v18.0.0 installed via brew
   NPM v8.8.0

1. With this config...

   init-author-name="Foo bar"
   init-author-email=foo.bad@gmail.com
   init-author-url=https://github.com/foobar

1. Run
   `npm i`
1. See error:
   `npm WARN config init.author.name Use `--init-author-name` instead.`

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by wraithgar** [comment]
Please fill out this issue completely. Of particular importance is the output from `npm config ls` as it may give us clues as to what is happening here.

**Comment by sourabhv** [comment]
This might sound weird, but I removed the brew version and installed from nvm and it works fine now. Closing, not sure why it was happening.

**Comment by calocaleta** [comment]
Hi, I use VSCode and edit the lines as the warning say:

`code /home/MYUSER/.npmrc`

I replace line 14:
`init-author-email=<email>`
or
`init.author.email=<email>`

instead:
`--init-author-email=<email>`

and works fine.

**Comment by SamuuX** [comment]
> Hola, uso VSCode y edito las líneas como dice la advertencia:
> 
> `code /home/MYUSER/.npmrc`
> 
> Reemplazo la línea 14: `init-author-email=<email>` o `init.author.email=<email>`
> 
> en cambio: `--init-author-email=<email>`
> 
> y funciona bien

A mí también me funciono / it worked for me too
