### ISSUE TITLE
[BUG] Package.json `files` paths with leading periods don't get published

### ISSUE THREAD

**Issue by dzearing** [npm/cli#4850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When using leading periods in paths within the `files` section, the path is not included in publishing. This feels very inconsistent from paths in `exports` maps and other places.

### Expected Behavior

All relative paths defined in `package.json` content should consistently allow leading periods.

### Steps To Reproduce

1. Create a project to publish with files in a `lib` folder.
2. Create a `package.json` which includes the `lib` folder in the `files` section:

```js
{
  "files": [
    "./lib"
  ]
}
```

3. Run `npm publish --dry` to see what gets published.
4. Remove the leading period in the `./lib` path and re-run the publish dryrun. Notice more files.

### Environment

- npm: 8.8.0
- Node.js: 14.17.6
- OS Name: MacOS
- System Model Name: Macbook Pro M1
- npm config:
```ini
; node bin location = /usr/local/bin/node
; node version = v14.17.6
; npm local prefix = /Users/dzearing/git/ori
; npm version = 8.8.0
; cwd = /Users/dzearing/git/ori/js/packages/api
; HOME = /Users/dzearing
```

**Comment by dzearing** [comment]
Semi-related: https://github.com/npm/cli/issues/1435

I think glob matches seem to have issues with leading periods, which throws some confusion into expectations with the files array.

Documentation reference:
https://docs.npmjs.com/cli/v8/configuring-npm/package-json#files

Still a bit unclear after reading the docs which one is right:

* `./lib`
* `/lib`
* `lib`
* `lib/**/*`
* `lib/`

**Comment by dzearing** [comment]
I have a sinking feeling this could be by design. Which feels bad only because of the inconsistencies when using paths in different parts of `package.json`. I can understand tho.

Fixed the title to be more searchable for future hits.

**Comment by wraithgar** [comment]
Nah this is a bug.  [We already strip the leading `/` from the array](https://github.com/npm/npm-packlist/blob/ce176f794f2cce932fecc4446fe0c822403181dc/lib/index.js#L245-L246) there's no reason we can't strip leading `./`. Especially as you pointed out how `exports` works, and it's prudent to assume folks would want `files` to work the same way.
