### ISSUE TITLE
npm install (Ubuntu)

### ISSUE THREAD

**Issue by OriginalHKwolf** [npm/cli#4858]
Hello, I am receiving this error when using "npm install"
Please advise on how to fix?

44807 error Linux 5.4.0-84-generic
44808 error argv "/usr/bin/node" "/usr/bin/npm" "install"
44809 error node v8.10.0
44810 error npm  v3.5.2
44811 error code EMISSINGARG
44812 error typeerror Error: Missing required argument #1
44812 error typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
44812 error typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
44812 error typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
44812 error typeerror     at /usr/share/npm/lib/install/deps.js:457:7
44812 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
44812 error typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
44812 error typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
44812 error typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
44812 error typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
44812 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
44813 error typeerror This is an error with npm itself. Please report this error at:
44813 error typeerror     <http://github.com/npm/npm/issues>
44814 verbose exit [ 1, true ]

[Pastebin](https://pastebin.com/wfiC6af0)

**Comment by ljharb** [comment]
node 8 and npm 3 are both very obsolete. Can you upgrade?

**Comment by wraithgar** [comment]
Please use the new issue form when opening issues.

**Comment by OriginalHKwolf** [comment]
> Please use the new issue form when opening issues.

Hi! Where can I find the new issue form
