### ISSUE TITLE
[BUG] npm repo <pkg> assumes a `master` branch

### ISSUE THREAD

**Issue by billyjanitsch** [npm/cli#4867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Given the following package:

```json
{
  "name": "b",
  "repository": {
    "type": "git",
    "url": "https://github.com/a/b.git",
    "directory": "c"
  }
}
```

`npm repo b` points to `https://github.com/a/b/tree/master/c`. In other words, it assumes that a `master` branch exists, which increasingly isn't always the case with many repos moving to other default branch names like `main`.

(Note: this only happens when the `repository` spec specifies a `directory`, because otherwise the command points to the repo base, e.g., `https://github.com/a/b`.)

There are a few possible failure states. GitHub redirects to the default branch if `master` doesn't exist, but it can't always handle this gracefully (and I'm not sure how other hosts behave). One unfortunate example is when a repo switched from `master` to `main` but kept the former as an archive, meaning that `npm repo` opens to an outdated view of the repo, e.g., `npm repo @babel/cli@7.17.10`.

The underlying issue is [here](https://github.com/npm/hosted-git-info/blob/a3f4836ba0a75b355c004e1991e8dd1e6321a983/lib/git-host-info.js#L10), or in one of the other places that this library hardcodes the string `'master'`.

### Expected Behavior

`npm repo <pkg>` should open to the default branch of the repository. Perhaps `HEAD` could be used instead of `master`?

### Steps To Reproduce

1. Run `npm repo @babel/cli@7.17.10`. (Including the version for posterity, but it's not currently necessary.)
2. Note that you've landed on https://github.com/babel/babel/tree/master/packages/babel-cli, which is not the default branch of the repo.

### Environment

- npm: 8.9.0
- Node.js: 16.15.0
- OS Name: macOS
- System Model Name: MacBook Pro
- npm config: n/a

**Comment by ljharb** [comment]
oof, this should definitely use `HEAD` and not `master`.

**Comment by darcyclarke** [comment]
@billyjanitsch thanks for bringing this to our attention. The change required to make this possible is actually in an upstream dep ([`hosted-git-info`]()). It is a breaking change as this will more holistically change the default across the board for `npm` (but that's a good thing). We've got it queued up to land for `v9` which we'll hopefully have prereleases/RCs for in a month or so. 

- https://github.com/npm/statusboard/issues/503
- https://github.com/npm/hosted-git-info/pull/142
