### ISSUE TITLE
[FEATURE] GitHub avatar instead of Gravatar on npmjs.org

### ISSUE THREAD

**Issue by zlatanvasovic** [npm/cli#487]
I am sorry if this is not the right place to report an issue related to npmjs.org. I've been trying to find a repository for the site itself, but to no avail.

# What / Why

Gravatar is a service unrelated to the (GitHub) developer environment and as such, it should not be required on npmjs website. GitHub, on the other side, is completely related to it, and as such it is very suitable for obtaining developer information like a profile picture.

Hence, my idea is to use GitHub's API instead of Gravatar's for obtaining avatars.

**Comment by ljharb** [comment]
Gravatar is a universal avatar for the web, and GitHub isn't required for using or publishing to npm.

**Comment by zlatanvasovic** [comment]
@ljharb It requires creating an account outside GitHub / npm, which shouldn't be necessary to have a profile picture on npm. Most npm packages are linked to GitHub repos and most npm users are linked to GitHub profiles already. It's not a must to remove Gravatar, but to add an option to use GitHub avatar instead.
