### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by dpomerantz-jci** [npm/cli#4886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I am on npm on WIndows.  Executing "npm run ci" runs "npm run prepare" script after ci.  This does not appear to be documented anywhere.

I'm not on the latest version, but this is clearly not in the documentation.  Even if it's not desired behavior and has already been fixed, it needs to be documented somewhere that it was once the behavior.

### Expected Behavior

One of two actions is expected.  Preferably, just don't run "npm run prepare" after "npm ci".  Npm ci is documented as installing pacakges from your pacakge-lock.json.  It should not need to "prepare" anything.  The second action would be to CLEARLY document on the pages for both npm-ci and the special purpose prepare script that prepare will be executed as part of npm-ci.  I could not easily find such documentation.

### Steps To Reproduce

On windows, create a instance of pacakge.json with npm init.  

Once it is created, add a script "prepare" which does something that causes an error (or echos to std out).

Execute npm install in order to generate a package-lock.json.

Execute "npm ci".  Note that the error or comment from the second step is now visible.

### Environment

- npm: 6.14.13
- Node.js:  14.17.1
- OS Name: Windows 10
- System Model Name: Dell something
- npm config:
```ini
; copy and paste output from `npm config ls` here
``; cli configs
metrics-registry = "***Internal Artifactory***"
scope = ""
user-agent = "npm/6.14.13 node/v14.17.1 win32 x64"

; userconfig C:\Users\****\.npmrc
registry = "***Internal Artifactory***"
strict-ssl = false

; builtin config undefined
prefix = "C:\\Users\\****\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\****
; HOME = C:\Users\****
; "npm config ls -l" to show all defaults.`

**Comment by wraithgar** [comment]
npm 6 is not the latest npm, npm 8 is.

The prepare lifecycle script is documented here: https://docs.npmjs.com/cli/v7/using-npm/scripts#life-cycle-scripts

It does mention that it runs on local install, which includes `ci` since `ci` is `clean install`.

If you feel this needs to be documented in other places feel free to submit a PR adding it there so it can be reviewed.
