### ISSUE TITLE
npm_config_userconfig vs NPM_CONFIG_USERCONFIG when referred as environment variable

### ISSUE THREAD

**Issue by ryenus** [npm/cli#4887]
This is about the ambiguity regarding the case of the environment variables. 

If we take `NPM_CONFIG_USERCONFIG` as the example.
[Here in the docs][1], it's referred as `NPM_CONFIG_USERCONFIG`, in **uppercase**:
> per-user configuration file (defaults to `$HOME/.npmrc`; configurable via CLI
  option `--userconfig` or environment variable `$NPM_CONFIG_USERCONFIG`)

However [later in the same docs][2], and [in the source][3], it's referred as `npm_config_userconfig`, in **lowercase**:
> This may be overridden by the `npm_config_userconfig` environment variable
or the `--userconfig` command line option

I understand that both uppercase `NPM_CONFIG_USERCONFIG` and lowercase `npm_config_userconfig` work, because internally [the environment variable names are converted to lowercase][4].

[1]: https://github.com/npm/documentation/blob/f69adf90e62edfb1a43c805787546e121591506c/content/cli/v8/using-npm/config.md?plain=1#L54
[2]: https://github.com/npm/documentation/blob/f69adf90e62edfb1a43c805787546e121591506c/content/cli/v8/using-npm/config.md?plain=1#L1759
[3]: https://github.com/npm/cli/blob/48d2db6037487fd782f67bbcd2cf12e009ece17b/lib/utils/config/definitions.js#L2188
[4]: https://github.com/npm/cli/blob/8a49e3ab6499c6196c5d7a0f6dad3b345944b992/node_modules/%40npmcli/config/lib/index.js#L369-L371

But what happens if both `NPM_CONFIG_USERCONFIG` and `npm_config_userconfig` are set? Or even if there's also`NPM_CONFIG_userconfig`? I haven't done a thorough testing but I bet the result would be _interesting_ and/or _surprising_.

Can we follow the convention and always refer to environment variable names in uppercase? That is already the de-facto standard. Thank you!

**Comment by wraithgar** [comment]
This is a [cli docs problem](https://github.com/npm/cli/issues/new?assignees=&labels=Documentation%2CNeeds+Triage&template=docs-problem.yml&title=%5BDOCS%5D+%3Ctitle%3E), please use the appropriate templates when creating new issues. We get a lot of issues coming in, and they really do need to be properly tagged so they can be seen and triaged by the responsible parties.

**Comment by ryenus** [comment]
Done, opened the doc issue https://github.com/npm/cli/issues/4891

**Comment by ryenus** [comment]
According to https://github.com/npm/npm/issues/14528 the lowercase `npm_config_userconfig` should be preferred.
