### ISSUE TITLE
[BUG] sudo npm install not work

### ISSUE THREAD

**Issue by copyNdpaste** [npm/cli#4904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`sudo npm install`

![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/b45609fb-e5d5-4c9f-b723-ee7b4968906a/Untitled.png)

### Expected Behavior

install packages

### Steps To Reproduce

https://docs.ipfs.io/how-to/exchange-files-between-nodes/#set-up

1. In this environment...
aws ubuntu 18 ec2
npm 3.5.2
node v8.10.0

2. With this config...

3. Run '...'
`git clone https://github.com/ipfs/js-ipfs.git`
`cd js-ipfs`
`npm install`

7. See error...
npm ERR! Unsupported URL Type: npm:@achingbrain/node-fetch@^2.6.4

### Environment

- npm:3.5.2
- Node.js:8.10.0
- OS Name: ubuntu 18
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```
; cli configs
user-agent = "npm/3.5.2 node/v8.10.0 linux x64"

; builtin config undefined
globalconfig = "/etc/npmrc"
globalignorefile = "/etc/npmignore"
prefix = "/usr/local"

; node bin location = /usr/bin/node
; cwd = /home/ubuntu/js-ipfs
; HOME = /home/ubuntu
; "npm config ls -l" to show all defaults.

**Comment by ljharb** [comment]
node 8 and npm 3 are both very EOL. Can you please try node 14 or later, and npm 8?
