### ISSUE TITLE
[BUG] `npm publish --dry-run` does not fail when package version is already published

### ISSUE THREAD

**Issue by broofa** [npm/cli#4927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I'm developing a new release workflow for the `uuid` module.  Obviously as part of this I need to verify that the `npm publish` command will work.  However, because of the large audience of users `uuid` has, I want to avoid publishing new versions until actually necessary.  `npm publish --dry-run` to the rescue, right?!?

To that end, I did a quick test of `npm publish --dry-run` to verify it performed all of authentication and validation checks that are required, by attempting to republish the current version of `uuid@8.3.2`, _fully expecting that this would fail_.

**Much to my surprise, it didn't!**

I.e. `npm publish` and `npm publish --dry-run` exhibit different behavior.  Specifically, when I `npm publish` (no dry run) It asks me to authenticate and then fails as expected:
```
$ npm publish
...
npm notice Open https://www.npmjs.com/login/7562620b-a308-48eb-8cda-7550673e2d5b to use your security key for authentication or enter OTP from your authenticator app
This operation requires a one-time password.
Enter OTP: ####################
...
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/uuid - You cannot publish over the previously published versions: 8.3.2.
```

However, when I do `npm publish --dry-run`, it does neither of those things.  It just... works, with no indication of the issues that I should expect to run into when actually publishing:
```
$ npm publish --dry-run
...
npm notice Publishing to https://registry.npmjs.org/ (dry-run)
+ uuid@8.3.2
```

Unfortunately this means that `--dry-run` can't be used to verify release processes.  😢 

### Expected Behavior

`npm publish --dry-run` should behave the same as `npm publish` - it should run through all of the same authentication and validation checks - except for the last step where the package is actually inserted into the repository.

### Steps To Reproduce

Pretty much as described above...

* `npm publish` a [package]@[version] that's already on npm.
* `npm publish --dry-run` the same package.
* *notice the difference in behavior*

### Environment

- npm: 8.10.0
- Node.js: 16.14.2
- OS Name: macOS 12.0.1
- System Model Name: (8) x64 Apple M1
- npm config:
```ini
; "user" config from /Users/kieffer/.npmrc

//registry.npmjs.org/:_authToken = (protected)
email = "robert@broofa.com"
save-prefix = ""
strict-ssl = false
tag-version-prefix = "v"

; node bin location = /Users/kieffer/.nvm/versions/node/v16.14.2/bin/node
; node version = v16.14.2
; npm local prefix = /Users/kieffer/projects/huevos
; npm version = 8.10.0
; cwd = /Users/kieffer/projects/huevos
; HOME = /Users/kieffer
; Run `npm config ls -l` to show all defaults.```

**Comment by darcyclarke** [comment]
What you're suggesting requires the configured registry to support a "dry-run" capability on their end (not the CLI itself). The CLI does it's best to mimic a publish up until the point where we'd pass the payload off to the configured registry. To my knowledge, the best way to check for the existence of a package today -- as a client -- is to use `npm view` (ex. `npm view <pkg>@<version>`).

You could then add that check in a `prepare` script which could gate/throw on a `npm publish --dry-run` OR `npm pack` of a pre-existing package. Example:

```json
{ 
  "scripts": {
    "prepare": "[ \"$(npm view .@${npm_package_version})\" == \"\" ] && exit 0 || echo \"Error: package exists\" && exit 1"
}
```

To my knowledge, `npm publish --dry-run` is working as expected. If you have thoughts/suggestions for how to improve that command, feel free to open an [RFC](https://github.com/npm/rfcs) issue/PR.

**Comment by timkinnane** [comment]
Above can also be achieved with `npm diff | grep version -q`
The command will diff the published package.json and search the diff for a line containing "version".
The -q flag will fail when not found (i.e. there's no diff between local and published version).

**Comment by paul4156** [comment]
> You could then add that check in a `prepare` script which could gate/throw on a `npm publish --dry-run` OR `npm pack` of a pre-existing package. Example:
> 
> ```json
> { 
>   "scripts": {
>     "prepare": "[ \"$(npm view .@${npm_package_version})\" == \"\" ] && exit 0 || echo \"Error: package exists\" && exit 1"
> }
> ```
> 

How can I check if the version is later than `latest`? Thanks.
