### ISSUE TITLE
[BUG] `files` field in package.json doesn't work

### ISSUE THREAD

**Issue by amustaque97** [npm/cli#4928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I have created a project. Project has 3 files: 
- index.js
- other.js
- package.json

Here is the directory structure.
```console
.
├── index.js
├── other.js
└── package.json

0 directories, 3 files
```

As per the [documentation](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#files), in my package.json file I have added `files` field to include only `other.js` file as a part of the package. Unfortunately it is not happening. Package is  considering all the files. Here is my content of `package.json` file:
```json
{
  "name": "project1",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "files": [
    "other.js"
  ],
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```

### How I verified this behviour?
I ran a command `npm publish --dry` and here is the output.
```console
❯ npm publish --dry
npm notice
npm notice 📦  project1@1.0.0
npm notice === Tarball Contents ===
npm notice 87B  index.js
npm notice 85B  other.js
npm notice 255B package.json
npm notice === Tarball Details ===
npm notice name:          project1
npm notice version:       1.0.0
npm notice filename:      project1-1.0.0.tgz
npm notice package size:  364 B
npm notice unpacked size: 427 B
npm notice shasum:        6b829b0563b5d7e24f2efea7ca829365e796d216
npm notice integrity:     sha512-xYSDIngar20KT[...]UWtmyD0dDcu6Q==
npm notice total files:   3
npm notice
npm WARN This command requires you to be logged in to https://registry.npmjs.org/ (dry-run)
npm notice Publishing to https://registry.npmjs.org/ (dry-run)
+ project1@1.0.0
```

### Expected Behavior

I would expect when I run `npm publish` it should only consider two files from the above package.
- other.js
- package.json

### Steps To Reproduce

1. create an empty project.
2. create two files `index.js` and `other.js`
3. Inside `package.json` file, add block
```json
 "files": [
    "other.js"
  ],
```
4. Run the following command:
```console
npm publish --dry
```
5. Observe it will consider all the project files.

This is the minimal steps to reproduce.

### Environment

- npm: 8.10.0
- Node.js: v16.13.2
- OS Name: MacOS
- System Model Name: 
- npm config:
```ini
; "user" config from /Users/<username>/.npmrc

; node bin location = /Users/<username>/.nvm/versions/node/v16.13.2/bin/node
; node version = v16.13.2
; npm local prefix = /private/tmp/project1
; npm version = 8.10.0
; cwd = /private/tmp/project1
; HOME = /Users/<username>
; Run `npm config ls -l` to show all defaults.
```

**Comment by ljharb** [comment]
Your "main" points to index.js, so it's automatically included. Why would you want to publish a package that's broken? (ie, that points explicitly to a file that's excluded from the tarball)

**Comment by amustaque97** [comment]
Thank you so much @ljharb for correcting me. My actual use case is different and not sure what would be the proper/decent way to achieve. I would try to explain it here. I would love to hear your thoughts 🙂 

There is an already existing microservice built in `nestjs` and it has implemented mongoose schema let's assume `xyz.schema.ts`. I have another independent script let's call it `consumer.ts` in a different repo that requires only the `xyz.schema.ts` file to use (rest of the service code is waste for the script). My initial thought was to use `files` field. But it adds `main` field file as well. 

I'm not clear what would be the better solution that I can directly use `xyz.schema.ts` from microservice.

Thanks once again for the reply.

**Comment by amustaque97** [comment]
We can close this issue.
