### ISSUE TITLE
[BUG] npmjs.com profile image change

### ISSUE THREAD

**Issue by RusticBombastic** [npm/cli#4937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Wanna change profile image instead of randomly generated one:
![Screen Shot 2022-05-24 at 3 17 58 PM](https://user-images.githubusercontent.com/39921649/170142582-88f73dd4-5bde-44ff-8c9c-381c3fe8b9be.png)

1) Registered on a **npmjs.com** with 
**Google Chrome browser**:
**Version 101.0.4951.64 (Official Build) (x86_64)**

2) Registered on a Gravatar.com:
Changed my email associated image on Gravatar.com, profile image on npmjs.com has not changed.

### Expected Behavior

npmjs.com profile image should change

### Steps To Reproduce

1. Register a new npmjs.com account
2. Go to your profile and click "Edit Profile"
3. Click on "Change your gravatar image"
4. Login with your WordPress gravatar account
5. Pick your new image
6. Nothing happens

**Comment by RusticBombastic** [comment]
Wrong topic

**Comment by marialuisacp** [comment]
The same here. How did you resolve?
