### ISSUE TITLE
[BUG] Exclude more redundant files from the tarball

### ISSUE THREAD

**Issue by XhmikosR** [npm/cli#495]
I mentioned this in #461 too

>it seems there are many seemingly unneeded files like .eslintrc, .travis.yml etc.

Now, I know the aforementioned files are not big, but IMO the tarball should be as slim as possible.

**Comment by ljharb** [comment]
They are not necessarily redundant. All of my packages explicitly include these files, so that `npm explore foo && npm install && npm test` always works. npm implicitly excluding these files will break that use case.

**Comment by XhmikosR** [comment]
I just mentioned 2 files as an example. I'm not familiar with what is needed, so this issue is mostly for npm maintainers to have another look at the shipped files.

**Comment by ljharb** [comment]
That's up to them; npm itself shouldn't have an opinion here.

**Comment by XhmikosR** [comment]
If the npm maintainers don't know which files are needed, who does?

**Comment by ljharb** [comment]
Only the author of the package knows what files are needed, and the current status is that the author decides - via `files` or `.npmignore`.

**Comment by XhmikosR** [comment]
I don't see why we keep discussing this TBH. This is mostly a callout for npm developers to have a further look if there are more files that should be excluded from npm's own package like #461...

If everything that's currently included is needed, then the issue can be closed.

**Comment by ljharb** [comment]
Sorry, that wasn’t clear to me from the issue title and OP.
