### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by theanubhavk** [npm/cli#4955]
npm WARN config production Use `--omit=dev` instead.                   npm WARN config optional Use `--omit=optional` to exclude optional dependencies, or                                                           npm WARN config `--include=optional` to include them.                  npm WARN config                                                        npm WARN config     Default value does install optional deps unless otherwise omitted.
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @strapi/design-system@1.1.1
npm WARN Found: @strapi/icons@1.1.1
npm WARN node_modules/@strapi/admin/node_modules/@strapi/icons
npm WARN   @strapi/icons@"1.1.1" from @strapi/admin@4.1.12
npm WARN   node_modules/@strapi/admin
npm WARN     @strapi/admin@"4.1.12" from @strapi/strapi@4.1.12
npm WARN     node_modules/@strapi/strapi
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @strapi/icons@"^0.0.1-alpha.73" from @strapi/design-system@1.1.1
npm WARN node_modules/@strapi/admin/node_modules/@strapi/design-system
npm WARN   @strapi/design-system@"1.1.1" from @strapi/admin@4.1.12
npm WARN   node_modules/@strapi/admin
npm WARN
npm WARN Conflicting peer dependency: @strapi/icons@0.0.1-alpha.79
npm WARN node_modules/@strapi/icons
npm WARN   peer @strapi/icons@"^0.0.1-alpha.73" from @strapi/design-system@1.1.1
npm WARN   node_modules/@strapi/admin/node_modules/@strapi/design-system
npm WARN     @strapi/design-system@"1.1.1" from @strapi/admin@4.1.12
npm WARN     node_modules/@strapi/admin
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated mailcomposer@3.12.0: This project is unmaintained
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated buildmail@3.10.0: This project is unmaintained
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated sequelize@5.22.5: Please update to v6 or higher! A migration guide can be found here: https://sequelize.org/v6/manual/upgrade-to-v6.html
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kali/.npm/_logs/2022-05-29T08_25_20_496Z-debug-0.log

**Comment by nlf** [comment]
**Closing:** please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).

**Comment by ashish784** [comment]
npm WARN config     Default value does install optional deps unless otherwise omitted.
