### ISSUE TITLE
[Feature] A way to enable/disable/review specific lifecycle scripts of (transitive) dependencies

### ISSUE THREAD

**Issue by xsrvmy** [npm/cli#4956]
Recently, there have been some problematic or useless lifecycle scripts (specifically, ones that prints out messages to the console unrelated to the package, such as political protests). It would be nice if there is a way to enable/disable them.

It would be even nicer if the lifecycle scripts of dependencies can be reviewed before they are run at all, similar to how you can review PKGBUILDs of Archlinux AUR packages before building them with AUR helpers. The developer can then enable/disable these scripts before they can run. If this is implemented, it would also be nice to warn the user that one of your dependencies disabled the lifecycle script of another upstream dependency (i.e., if A dependencies on B, and A disables B's postinstall script, I want to know that A did this when I install A). This would make it easier for regular users to see potential malware present in a script (looking at you, node-ipc).

Alternatively, there could be a policy on the registry against useless lifecycle scripts. I posted that in discussions.

**Comment by ljharb** [comment]
linking to https://github.com/npm/feedback/discussions/696

**Comment by xsrvmy** [comment]
I now realize that overrides are supported now, and pointing to a fork of the repo without the postinstall would work. However, it would be easier to simply remove the script directly in the override. For example:
```json
"overrides": {
  "es5-ext": {
    ".postinstall": false
  }
}
```
or
```json
"overrides": {
  "es5-ext": [{}, {
    "postinstall": false
  }]
}
```
(for the second one, the first object is the versions, and the second object disables postinstall.

**Comment by fritzy** [comment]
Can you create [an RRFC](https://github.com/npm/rfcs/issues/new?assignees=&labels=&template=rrfc.md&title=%5BRRFC%5D+%3Ctitle%3E) in that repo?
