### ISSUE TITLE
[BUG] <Enhacement> Use central local repositories that contain versioned libraries and refer those in project -- Maven like

### ISSUE THREAD

**Issue by jaydeepmehta15** [npm/cli#4959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I see npm is using project specific repositories containing the libraries used in the particular project. The issue is this creates duplicate library files for the ones used in multiple projects as Angular/react framework libraries. This effectively creates disk space issue in case you are working on multiple projects common for most enterprise developers. Also, long download time.

In sense there is already mature maven ecosystem that already solves this problem by using local central repository containing **versioned** libraries and than each project can refer to the library version that it needs. This saves lot of disc space.

In sense version conflicts should not be the reason, you can maintain versioned dependencies. I guess the problem is solved by yarn. I am new to npm ecosystem request help here.

### Expected Behavior

Use central local repositories that contain versioned libraries and refer those in project -- Maven like

### Steps To Reproduce

npx create-react-app my-app

creates local node modules folder with all app dependencies.

### Environment

- npm:
- Node.js:
- OS Name: Windows
- System Model Name:
- npm config:
```ini

; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.14.6 node/v12.18.3 win32 x64"

; builtin config undefined
prefix = "C:\\Users\\ABC\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\ABC
; HOME = C:\Users\ABC
; "npm config ls -l" to show all defaults.

**Comment by ljharb** [comment]
You’re not describing a _problem_, you’re describing why npm is superior to package managers that have a flat pool of deps, like maven.

**Comment by jaydeepmehta15** [comment]
> You’re not describing a _problem_, you’re describing why npm is superior to package managers that have a flat pool of deps, like maven.

The problem is duplicate and filling up disk space if you are working on multiple projects. Also, setup of new project takes time as it needs to download all again for every new project.

I am not too sure but yarn simplifies this storing lib in local shared folder and projects referring to them rather than having copy.

**Comment by ljharb** [comment]
Disk space is effectively infinite and free (certainly compared to correctness, or to processing time, which are much more expensive), and new projects use the primed npm cache, so there should only be downloads if there’s new versions available *to* download.

**Comment by nlf** [comment]
what you're describing is like a global form of [isolated mode](https://github.com/npm/rfcs/blob/main/accepted/0042-isolated-mode.md)

work on isolated mode is under way, but it does not deduplicate your dependencies across multiple projects. that's not something that we plan to implement for a lot of reasons. if this is something that's really important to you, feel free to open an RRFC issue at https://github.com/npm/rfcs and join us during our open rfc calls (details in the README at that link)

**Comment by DesignByOnyx** [comment]
@nlf - can you give any feedback on the status of isolated mode? Preferably here (I've been searching for hours and your previous comment is the closest I've come to anything meaningful... thanks!): https://stackoverflow.com/questions/75666566/what-is-the-status-of-npm-isolated-mode-for-monorepos
