### ISSUE TITLE
[BUG] <title>.npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated npm ERR! Exit handler never called!

### ISSUE THREAD

**Issue by rholli1** [npm/cli#4965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I am running 'ng new my-app' and I get this error:

| Installing packages (npm)...npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Local\npm-cache\_logs\2022-06-01T00_44_32_520Z-debug-0.log
× Package install failed, see above.
The Schematic workflow failed. See above.

Full Output:

ng new my-app
? Would you like to add Angular routing? No
? Which stylesheet format would you like to use? CSS
CREATE my-app/angular.json (3039 bytes)
CREATE my-app/package.json (1069 bytes)
CREATE my-app/README.md (1059 bytes)
CREATE my-app/tsconfig.json (863 bytes)
CREATE my-app/.editorconfig (274 bytes)
CREATE my-app/.gitignore (548 bytes)
CREATE my-app/.browserslistrc (600 bytes)
CREATE my-app/karma.conf.js (1423 bytes)
CREATE my-app/tsconfig.app.json (287 bytes)
CREATE my-app/tsconfig.spec.json (333 bytes)
CREATE my-app/.vscode/extensions.json (130 bytes)
CREATE my-app/.vscode/launch.json (474 bytes)
CREATE my-app/.vscode/tasks.json (938 bytes)
CREATE my-app/src/favicon.ico (948 bytes)
CREATE my-app/src/index.html (291 bytes)
CREATE my-app/src/main.ts (372 bytes)
CREATE my-app/src/polyfills.ts (2338 bytes)
CREATE my-app/src/styles.css (80 bytes)
CREATE my-app/src/test.ts (745 bytes)
CREATE my-app/src/assets/.gitkeep (0 bytes)
CREATE my-app/src/environments/environment.prod.ts (51 bytes)
CREATE my-app/src/environments/environment.ts (658 bytes)
CREATE my-app/src/app/app.module.ts (314 bytes)
CREATE my-app/src/app/app.component.html (23332 bytes)
CREATE my-app/src/app/app.component.spec.ts (956 bytes)
CREATE my-app/src/app/app.component.ts (210 bytes)
CREATE my-app/src/app/app.component.css (0 bytes)
| Installing packages (npm)...npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rholl\AppData\Local\npm-cache\_logs\2022-06-01T00_44_32_520Z-debug-0.log
× Package install failed, see above.
The Schematic workflow failed. See above.

### Expected Behavior

The 'ng new my-app' should complete.

### Steps To Reproduce

1. In this environment... Windows CLI
3. With this config...
None.
5. Run '...'
ng new my-myapp
7. See error...

### Environment

- npm: 8.5.5
- Node.js: v16.15.0
- OS Name: Microsoft Windows [Version 10.0.19044.1706]
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```
npm config ls
; "builtin" config from C:\Users\user\AppData\Roaming\nvm\v11.0.0\node_modules\npm\npmrc

prefix = "C:\\Users\\user\\AppData\\Roaming\\npm"

; "user" config from C:\Users\rholl\.npmrc

msvs_version = "2017"
python = "C:\\Users\\user\\AppData\\Local\\Microsoft\\WindowsApps\\python.exe"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\user\Desktop\Computation\WebPages\newapps
; HOME = C:\Users\user
; Run `npm config ls -l` to show all defaults.

**Comment by rholli1** [comment]
This was fixed by upgrading NPM to the latest version:

npm install npm@latest -g

**Comment by davide1995** [comment]
Still happens with npm@8.19.1
