### ISSUE TITLE
[DOCS] Stable Version Doc references deprecated syntax

### ISSUE THREAD

**Issue by miWatch10** [npm/cli#4979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Enhancement, not another kind of Docs Enhancement.

- [X] This is a CLI Docs Enhancement.

### Description of Problem

https://docs.npmjs.com/try-the-latest-stable-version-of-npm#upgrading-on-nix-osx-linux-etc mentions to run `npm install -g npm@latest` 

But that is a deprecated syntax and causes a warning in 8.11.0+:

```sh
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
```

Note: there might be same issue on other places, I haven't checked, I just noticed this one.

### Potential Solution

Update doc to mention syntax to use in 8.11.0+

Ideally there's one syntax that covers both older and newer.

### Docs URL

https://docs.npmjs.com/try-the-latest-stable-version-of-npm#upgrading-on-nix-osx-linux-etc

**Comment by nlf** [comment]
we've reverted this deprecation in v8.12.1 so i'm closing this issue. thanks for the report!
