### ISSUE TITLE
Using stale data from https://registry.npmjs.org/ due to a request error during revalidation. npm ERR! cb() never called!

### ISSUE THREAD

**Issue by Boanerges1996** [npm/cli#499]
# What / Why
Please I have been trying to install mongoose but I get the error above
> n/a

## When
It started just today. I installed mongoose for another project I was working on yesterday. But i have tried installing it today and am getting the same error.

## This is from the log
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-IlqAUOOUNMA0jkNmixEqaK5nj7D1fMuso+hakd7lN1CAnlP60oTb467DHSoQPr1ZB3jntua6dj6Dh9pFWZLwfg== integrity checksum failed when using sha512: wanted sha512-IlqAUOOUNMA0jkNmixEqaK5nj7D1fMuso+hakd7lN1CAnlP60oTb467DHSoQPr1ZB3jntua6dj6Dh9pFWZLwfg== but got sha512-n3e0s+FdPlMXKxIIatiVv7THOR7xwVF23x4HUbn0Dgqld8ef/dEBN4gOzAys0v7Dq2iZ5NiYmpCtN/eSPID1Pg==. (245089 bytes)
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! cb() never called!

**Comment by simonron** [comment]
I have a similar problem after attempting to update Appcelerator studio on Catalina.

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'appcelerator',
1 verbose cli   '-g~' ]
2 info using npm@6.9.0
3 info using node@v10.16.1
4 verbose config Skipping project config: /Users/Cyberman/.npmrc. (matches userconfig)
5 verbose npm-session 83deb95553973077
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 http fetch GET 304 https://registry.npmjs.org/appcelerator 161ms (from cache)
9 silly pacote tag manifest for appcelerator@latest fetched in 181ms
10 timing stage:loadCurrentTree Completed in 1104ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 5ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 287ms
16 silly install loadAllDepsIntoIdealTree
17 silly resolveWithNewModule appcelerator@4.2.15 checking installable status
18 http fetch GET 200 https://registry.npmjs.org/npm-install-checks 22ms (from cache)
19 silly pacote range manifest for npm-install-checks@^3.0.0 fetched in 48ms
20 silly resolveWithNewModule npm-install-checks@3.0.2 checking installable status
21 http fetch GET 200 https://registry.npmjs.org/chalk 50ms (from cache)
22 silly pacote version manifest for chalk@0.5.1 fetched in 53ms
23 silly resolveWithNewModule chalk@0.5.1 checking installable status
24 http fetch GET 304 https://registry.npmjs.org/pac-proxy-agent 56ms (from cache)
25 silly pacote range manifest for pac-proxy-agent@^3.0.0 fetched in 57ms
26 silly resolveWithNewModule pac-proxy-agent@3.0.1 checking installable status
27 http fetch GET 304 https://registry.npmjs.org/tar 108ms (from cache)
28 http fetch GET 304 https://registry.npmjs.org/progress 111ms (from cache)
29 silly pacote range manifest for tar@^4.4.4 fetched in 112ms
30 silly resolveWithNewModule tar@4.4.13 checking installable status
31 silly pacote version manifest for progress@1.1.8 fetched in 113ms
32 silly resolveWithNewModule progress@1.1.8 checking installable status
33 http fetch GET 304 https://registry.npmjs.org/which 143ms (from cache)
34 http fetch GET 304 https://registry.npmjs.org/async 151ms (from cache)
35 silly pacote version manifest for which@1.0.8 fetched in 148ms
36 silly resolveWithNewModule which@1.0.8 checking installable status
37 silly pacote range manifest for async@^1.5.0 fetched in 155ms
38 silly resolveWithNewModule async@1.5.2 checking installable status
39 http fetch GET 304 https://registry.npmjs.org/debug 154ms (from cache)
40 http fetch GET 304 https://registry.npmjs.org/semver 151ms (from cache)
41 silly pacote range manifest for debug@^2.1.1 fetched in 157ms
42 silly resolveWithNewModule debug@2.6.9 checking installable status
43 silly pacote range manifest for semver@^6.0.0 fetched in 153ms
44 silly resolveWithNewModule semver@6.3.0 checking installable status
45 http fetch GET 304 https://registry.npmjs.org/request 155ms (from cache)
46 silly pacote range manifest for request@^2.87.0 fetched in 157ms
47 silly resolveWithNewModule request@2.88.0 checking installable status
48 http fetch GET 304 https://registry.npmjs.org/has-ansi 38ms (from cache)
49 silly pacote range manifest for has-ansi@^0.1.0 fetched in 43ms
50 silly resolveWithNewModule has-ansi@0.1.0 checking installable status
51 http fetch GET 304 https://registry.npmjs.org/ansi-styles 55ms (from cache)
52 http fetch GET 304 https://registry.npmjs.org/strip-ansi 55ms (from cache)
53 silly pacote range manifest for ansi-styles@^1.1.0 fetched in 57ms
54 silly resolveWithNewModule ansi-styles@1.1.0 checking installable status
55 silly pacote range manifest for strip-ansi@^0.3.0 fetched in 57ms
56 silly resolveWithNewModule strip-ansi@0.3.0 checking installable status
57 http fetch GET 304 https://registry.npmjs.org/supports-color 58ms (from cache)
58 silly pacote range manifest for supports-color@^0.2.0 fetched in 59ms
59 silly resolveWithNewModule supports-color@0.2.0 checking installable status
60 http fetch GET 304 https://registry.npmjs.org/ansi-regex 31ms (from cache)
61 silly pacote range manifest for ansi-regex@^0.2.0 fetched in 32ms
62 silly resolveWithNewModule ansi-regex@0.2.1 checking installable status
63 http fetch GET 304 https://registry.npmjs.org/ms 42ms (from cache)
64 silly pacote version manifest for ms@2.0.0 fetched in 43ms
65 silly resolveWithNewModule ms@2.0.0 checking installable status
66 silly pacote range manifest for semver@^2.3.0 || 3.x || 4 || 5 fetched in 2ms
67 silly resolveWithNewModule semver@5.7.1 checking installable status
68 silly pacote range manifest for debug@^4.1.1 fetched in 7ms
69 silly resolveWithNewModule debug@4.1.1 checking installable status
70 http fetch GET 200 https://registry.npmjs.org/socks-proxy-agent 20ms (from cache)
71 silly pacote range manifest for socks-proxy-agent@^4.0.1 fetched in 22ms
72 silly resolveWithNewModule socks-proxy-agent@4.0.2 checking installable status
73 http fetch GET 304 https://registry.npmjs.org/pac-resolver 53ms (from cache)
74 silly pacote range manifest for pac-resolver@^3.0.0 fetched in 57ms
75 silly resolveWithNewModule pac-resolver@3.0.0 checking installable status
76 http fetch GET 304 https://registry.npmjs.org/https-proxy-agent 60ms (from cache)
77 silly pacote range manifest for https-proxy-agent@^3.0.0 fetched in 62ms
78 silly resolveWithNewModule https-proxy-agent@3.0.1 checking installable status
79 http fetch GET 304 https://registry.npmjs.org/http-proxy-agent 67ms (from cache)
80 http fetch GET 304 https://registry.npmjs.org/get-uri 68ms (from cache)
81 http fetch GET 304 https://registry.npmjs.org/raw-body 68ms (from cache)
82 silly pacote range manifest for http-proxy-agent@^2.1.0 fetched in 69ms
83 silly resolveWithNewModule http-proxy-agent@2.1.0 checking installable status
84 silly pacote range manifest for get-uri@^2.0.0 fetched in 70ms
85 silly resolveWithNewModule get-uri@2.0.4 checking installable status
86 silly pacote range manifest for raw-body@^2.2.0 fetched in 70ms
87 silly resolveWithNewModule raw-body@2.4.1 checking installable status
88 http fetch GET 304 https://registry.npmjs.org/agent-base 73ms (from cache)
89 silly pacote range manifest for agent-base@^4.2.0 fetched in 73ms
90 silly resolveWithNewModule agent-base@4.3.0 checking installable status
91 http fetch GET 304 https://registry.npmjs.org/es6-promisify 32ms (from cache)
92 silly pacote range manifest for es6-promisify@^5.0.0 fetched in 33ms
93 silly resolveWithNewModule es6-promisify@5.0.0 checking installable status
94 http fetch GET 304 https://registry.npmjs.org/es6-promise 62ms (from cache)
95 silly pacote range manifest for es6-promise@^4.0.3 fetched in 64ms
96 silly resolveWithNewModule es6-promise@4.2.8 checking installable status
97 silly pacote range manifest for ms@^2.1.1 fetched in 1ms
98 silly resolveWithNewModule ms@2.1.2 checking installable status
99 http fetch GET 304 https://registry.npmjs.org/data-uri-to-buffer 32ms (from cache)
100 silly pacote range manifest for data-uri-to-buffer@1 fetched in 34ms
101 silly resolveWithNewModule data-uri-to-buffer@1.2.0 checking installable status
102 http fetch GET 304 https://registry.npmjs.org/ftp 40ms (from cache)
103 silly pacote range manifest for ftp@~0.3.10 fetched in 45ms
104 silly resolveWithNewModule ftp@0.3.10 checking installable status
105 http fetch GET 304 https://registry.npmjs.org/file-uri-to-path 50ms (from cache)
106 silly pacote range manifest for file-uri-to-path@1 fetched in 53ms
107 silly resolveWithNewModule file-uri-to-path@1.0.0 checking installable status
108 http fetch GET 304 https://registry.npmjs.org/extend 54ms (from cache)
109 silly pacote range manifest for extend@~3.0.2 fetched in 55ms
110 silly resolveWithNewModule extend@3.0.2 checking installable status
111 http fetch GET 304 https://registry.npmjs.org/readable-stream 56ms (from cache)
112 silly pacote range manifest for readable-stream@2 fetched in 58ms
113 silly resolveWithNewModule readable-stream@2.3.6 checking installable status
114 silly pacote range manifest for readable-stream@1.1.x fetched in 1ms
115 silly resolveWithNewModule readable-stream@1.1.14 checking installable status
116 http fetch GET 200 https://registry.npmjs.org/xregexp 3ms (from cache)
117 silly pacote version manifest for xregexp@2.0.0 fetched in 4ms
118 silly resolveWithNewModule xregexp@2.0.0 checking installable status
119 http fetch GET 304 https://registry.npmjs.org/isarray 36ms (from cache)
120 silly pacote version manifest for isarray@0.0.1 fetched in 37ms
121 silly resolveWithNewModule isarray@0.0.1 checking installable status
122 http fetch GET 304 https://registry.npmjs.org/inherits 43ms (from cache)
123 silly pacote range manifest for inherits@~2.0.1 fetched in 44ms
124 silly resolveWithNewModule inherits@2.0.4 checking installable status
125 http fetch GET 304 https://registry.npmjs.org/string_decoder 78ms (from cache)
126 silly pacote range manifest for string_decoder@~0.10.x fetched in 79ms
127 silly resolveWithNewModule string_decoder@0.10.31 checking installable status
128 silly pacote range manifest for inherits@~2.0.3 fetched in 3ms
129 silly resolveWithNewModule inherits@2.0.4 checking installable status
130 silly pacote range manifest for isarray@~1.0.0 fetched in 3ms
131 silly resolveWithNewModule isarray@1.0.0 checking installable status
132 silly pacote range manifest for string_decoder@~1.1.1 fetched in 3ms
133 silly resolveWithNewModule string_decoder@1.1.1 checking installable status
134 http fetch GET 304 https://registry.npmjs.org/process-nextick-args 41ms (from cache)
135 silly pacote range manifest for process-nextick-args@~2.0.0 fetched in 45ms
136 silly resolveWithNewModule process-nextick-args@2.0.1 checking installable status
137 http fetch GET 304 https://registry.npmjs.org/util-deprecate 46ms (from cache)
138 silly pacote range manifest for util-deprecate@~1.0.1 fetched in 48ms
139 silly resolveWithNewModule util-deprecate@1.0.2 checking installable status
140 http fetch GET 304 https://registry.npmjs.org/safe-buffer 49ms (from cache)
141 silly pacote range manifest for safe-buffer@~5.1.1 fetched in 51ms
142 silly resolveWithNewModule safe-buffer@5.1.2 checking installable status
143 silly pacote version manifest for debug@3.1.0 fetched in 1ms
144 silly resolveWithNewModule debug@3.1.0 checking installable status
145 silly pacote range manifest for debug@^3.1.0 fetched in 1ms
146 silly resolveWithNewModule debug@3.2.6 checking installable status
147 silly pacote range manifest for ms@^2.1.1 fetched in 1ms
148 silly resolveWithNewModule ms@2.1.2 checking installable status
149 http fetch GET 304 https://registry.npmjs.org/degenerator 55ms (from cache)
150 http fetch GET 304 https://registry.npmjs.org/thunkify 56ms (from cache)
151 silly pacote range manifest for degenerator@^1.0.4 fetched in 59ms
152 silly resolveWithNewModule degenerator@1.0.4 checking installable status
153 http fetch GET 304 https://registry.npmjs.org/co 60ms (from cache)
154 http fetch GET 304 https://registry.npmjs.org/ip 59ms (from cache)
155 http fetch GET 304 https://registry.npmjs.org/netmask 59ms (from cache)
156 silly pacote range manifest for ip@^1.1.5 fetched in 61ms
157 silly resolveWithNewModule ip@1.1.5 checking installable status
158 silly pacote range manifest for co@^4.6.0 fetched in 62ms
159 silly resolveWithNewModule co@4.6.0 checking installable status
160 silly pacote range manifest for thunkify@^2.1.2 fetched in 59ms
161 silly resolveWithNewModule thunkify@2.1.2 checking installable status
162 silly pacote range manifest for netmask@^1.0.6 fetched in 61ms
163 silly resolveWithNewModule netmask@1.0.6 checking installable status
164 http fetch GET 304 https://registry.npmjs.org/escodegen 35ms (from cache)
165 silly pacote range manifest for escodegen@1.x.x fetched in 37ms
166 silly resolveWithNewModule escodegen@1.12.0 checking installable status
167 http fetch GET 304 https://registry.npmjs.org/ast-types 39ms (from cache)
168 silly pacote range manifest for ast-types@0.x.x fetched in 41ms
169 silly resolveWithNewModule ast-types@0.13.2 checking installable status
170 http fetch GET 304 https://registry.npmjs.org/esprima 179ms (from cache)
171 silly pacote range manifest for esprima@3.x.x fetched in 183ms
172 silly resolveWithNewModule esprima@3.1.3 checking installable status
173 http fetch GET 304 https://registry.npmjs.org/esutils 44ms (from cache)
174 silly pacote range manifest for esutils@^2.0.2 fetched in 45ms
175 silly resolveWithNewModule esutils@2.0.3 checking installable status
176 http fetch GET 304 https://registry.npmjs.org/estraverse 47ms (from cache)
177 silly pacote range manifest for estraverse@^4.2.0 fetched in 48ms
178 silly resolveWithNewModule estraverse@4.3.0 checking installable status
179 http fetch GET 304 https://registry.npmjs.org/source-map 83ms (from cache)
180 silly pacote range manifest for source-map@~0.6.1 fetched in 84ms
181 silly resolveWithNewModule source-map@0.6.1 checking installable status
182 http fetch GET 304 https://registry.npmjs.org/optionator 166ms (from cache)
183 silly pacote range manifest for optionator@^0.8.1 fetched in 167ms
184 silly resolveWithNewModule optionator@0.8.3 checking installable status
185 http fetch GET 200 https://registry.npmjs.org/levn 14ms (from cache)
186 silly pacote range manifest for levn@~0.3.0 fetched in 15ms
187 silly resolveWithNewModule levn@0.3.0 checking installable status
188 http fetch GET 304 https://registry.npmjs.org/type-check 55ms (from cache)
189 silly pacote range manifest for type-check@~0.3.2 fetched in 56ms
190 silly resolveWithNewModule type-check@0.3.2 checking installable status
191 http fetch GET 304 https://registry.npmjs.org/prelude-ls 65ms (from cache)
192 http fetch GET 304 https://registry.npmjs.org/deep-is 66ms (from cache)
193 silly pacote range manifest for prelude-ls@~1.1.2 fetched in 67ms
194 silly resolveWithNewModule prelude-ls@1.1.2 checking installable status
195 silly pacote range manifest for deep-is@~0.1.3 fetched in 67ms
196 silly resolveWithNewModule deep-is@0.1.3 checking installable status
197 http fetch GET 304 https://registry.npmjs.org/fast-levenshtein 70ms (from cache)
198 silly pacote range manifest for fast-levenshtein@~2.0.6 fetched in 71ms
199 silly resolveWithNewModule fast-levenshtein@2.0.6 checking installable status
200 timing npm Completed in 2933ms
201 error cb() never called!
202 error This is an error with npm itself. Please report this error at:
203 error <https://npm.community>

**Comment by mikemimik** [comment]
Duplicate issue; aggregating into https://github.com/npm/cli/issues/417.
