### ISSUE TITLE
[BUG][since 7.18.0] A wrong symlink is produced when installing a local `file:` package.

### ISSUE THREAD

**Issue by issuefiler** [npm/cli#4994]
# The environments

## The directory tree
- `T:/a/b/c/`
  - `PackageA/`
    - `package.json`
  - `PackageB/`

## `T:/a/b/c/PackageA/package.json`
```JSON
"dependencies": {
	"package-b": "file:../PackageB/"
}
```

## The command
The working directory: `B:/a/b/c/PackageA/`.
```
npm install
```
on **Windows 10**’s _command prompt_.

-----

# The results

The following symlink is created.

## NPM version 7.17.0 ✔
`./node_modules/package-b` ⟶[symlink]⟶ `T:/a/b/c/PackageB/`

## NPM version 7.18.0 or newer ❌<sup>bug</sup>
`./node_modules/package-b` ⟶[symlink]⟶ `T:/a/PackageB/`

-----

Tested with freshly installed NPM.

```
npm install -g npm@7.17.0
npm install
```
```
npm install -g npm@7.18.0
npm install
```

**Comment by ljharb** [comment]
@issuefiler npm 7 is long EOL, can you try with npm 8 latest?

**Comment by issuefiler** [comment]
@ljharb:
> @issuefiler npm 7 is long EOL, can you try with npm 8 latest?


I’ve also tried with `npm@8.12.1`. This bug still exists.
