### ISSUE TITLE
[BUG] `/etc/hosts` as plain text in any file causes `npm publish` to fail with 403: Forbidden

### ISSUE THREAD

**Issue by HexaField** [npm/cli#4995]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Including the string `/etc/hosts` as plain text in any file that `npm publish` tries to push to the npm registry will fail. All information can be found in the following screenshots.

![Screenshot from 2022-06-08 10-35-18](https://user-images.githubusercontent.com/10372036/172507009-91986428-f7a3-4f9a-a1ca-e4028ffd2e82.png)
![Screenshot from 2022-06-08 10-34-50](https://user-images.githubusercontent.com/10372036/172507013-5384feb1-c3d5-46cf-9e0b-c0989b791df1.png)

### Expected Behavior

To publish successfully, or at least progress to the OTP stage.

### Steps To Reproduce

1. create a package.json and set it's description to `/etc/hosts` or add any plain text formatted file and include the string `/etc/hosts`
2. try to `npm publish`
3. it will fail before getting to the OTP stage with 403: Forbidden

### Environment

- npm: 8.12.1
- Node.js: 16.14.2
- OS Name: Ubuntu 18.04.6 LTS
- System Model Name: 
- npm config: 
```ini
; "user" config from /home/josh/.npmrc

//registry.npmjs.org/:_authToken = (protected) 

; node bin location = /home/josh/.nvm/versions/node/v16.14.2/bin/node
; cwd = /home/josh
; HOME = /home/josh
; Run `npm config ls -l` to show all defaults.
```

**Comment by fritzy** [comment]
**Closing:** this looks to be an issue with the registry which is outside the scope of this repo. For registry support please go to [npmjs.com/support](https://www.npmjs.com/support). If you believe this is a bug with the cli, please provide further clarifying details.
