### ISSUE TITLE
[BUG] Redirect Installation of package x when a request for package y installation is made using config in package.json

### ISSUE THREAD

**Issue by ganeshkbhat** [npm/cli#5009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I have two packages `ajs` and `bjs`. Due to some reason I intend to merge both. Right now, I am installing `ajs` with `npm install ajs` and `bjs` with `npm install bjs`. But after the merge I wish to install `bjs` when `ajs` (`npm i ajs`) is installed.

I am aware of manual installation of `npm i <alias>@npm:<package>`. It does not solve my purpose. I did try searching a couple of times around this but did not find any documentation related to this. I doubt this is even directly possible. I wish not to copy one repo to another to maintain the sanity of the deprecated repository upgraded to another. The only option I see is update the github url in the repository. But I doubt it solves the purpose. Any help is welcome.

https://stackoverflow.com/questions/72554667/install-package-x-when-a-request-for-package-y-installation-is-made

### Expected Behavior

Add documentation to redirect installation of one package(`ajs`) when installing another(`bjs`) package. Alternatively allow for the same as a feature.

### Steps To Reproduce

NA. Feature 

### Environment

- npm: 8.5.5
- Node.js: 16.15.0
- OS Name: Windows/Linux
- System Model Name: Dell Vostro OEM 3590 - i5 x64 Arch
- npm config: 
```ini
; copy and paste output from `npm config ls` here
; node bin location = C:\Users\ganes\OneDrive\Documents\binaries\node\node.exe
; cwd = C:\Users\ganes\OneDrive\Documents\projects\github\cgi-js
; HOME = C:\Users\ganes
; Run `npm config ls -l` to show all defaults.

C:\Users\ganes\OneDrive\Documents\projects\github\cgi-js>npm config ls -l
; "default" config from default values

_auth = (protected) 
access = null 
all = false
allow-same-version = false
also = null
audit = true
audit-level = null
auth-type = "legacy"
before = null
bin-links = true
browser = null
ca = null
cache = "C:\\Users\\ganes\\AppData\\Local\\npm-cache"
cache-max = null
cache-min = 0
cafile = null
call = ""
cert = null
ci-name = null
cidr = null
color = true
commit-hooks = true
depth = null
description = true
dev = false
diff = []
diff-dst-prefix = "b/"
diff-ignore-all-space = false
diff-name-only = false
diff-no-prefix = false
diff-src-prefix = "a/"
diff-text = false
diff-unified = 3
dry-run = false
editor = "notepad.exe"
engine-strict = false
fetch-retries = 2
fetch-retry-factor = 10
fetch-retry-maxtimeout = 60000
fetch-retry-mintimeout = 10000
fetch-timeout = 300000
force = false
foreground-scripts = false
format-package-lock = true
fund = true
git = "git"
git-tag-version = true
global = false
global-style = false
globalconfig = "C:\\Users\\ganes\\OneDrive\\Documents\\binaries\\node\\etc\\npmrc"
heading = "npm"
https-proxy = null
if-present = false
ignore-scripts = false
include = []
include-staged = false
include-workspace-root = false
init-author-email = ""
init-author-name = ""
init-author-url = ""
init-license = "ISC"
init-module = "C:\\Users\\ganes\\.npm-init.js"
init-version = "1.0.0"
init.author.email = ""
init.author.name = ""
init.author.url = ""
init.license = "ISC"
init.module = "C:\\Users\\ganes\\.npm-init.js"
init.version = "1.0.0"
json = false
key = null
legacy-bundling = false
legacy-peer-deps = false
link = false
local-address = null
location = "user"
lockfile-version = null
loglevel = "notice"
logs-max = 10
; long = false ; overridden by cli
maxsockets = 15
message = "%s"
metrics-registry = "https://registry.npmjs.org/"
node-options = null
node-version = "v16.15.0"
noproxy = [""]
npm-version = "8.5.5"
offline = false
omit = []
only = null
optional = null
otp = null
pack-destination = "."
package = []
package-lock = true
package-lock-only = false
parseable = false
prefer-offline = false
prefer-online = false
prefix = "C:\\Users\\ganes\\OneDrive\\Documents\\binaries\\node"
preid = ""
production = null
progress = true
proxy = null
read-only = false
rebuild-bundle = true
registry = "https://registry.npmjs.org/"
save = true
save-bundle = false
save-dev = false
save-exact = false
save-optional = false
save-peer = false
save-prefix = "^"
save-prod = false
scope = ""
script-shell = null
searchexclude = ""
searchlimit = 20
searchopts = ""
searchstaleness = 900
shell = "C:\\Windows\\system32\\cmd.exe"
shrinkwrap = true
sign-git-commit = false
sign-git-tag = false
sso-poll-frequency = 500
sso-type = "oauth"
strict-peer-deps = false
strict-ssl = true
tag = "latest"
tag-version-prefix = "v"
timing = false
tmp = "C:\\Users\\ganes\\AppData\\Local\\Temp"
umask = 0
unicode = true
update-notifier = true
usage = false
user-agent = "npm/{npm-version} node/{node-version} {platform} {arch} workspaces/{workspaces} {ci}"
userconfig = "C:\\Users\\ganes\\.npmrc"
version = false
versions = false
viewer = "browser"
which = null
workspace = []
workspaces = null
yes = null

; "cli" config from command line options

long = true
```

**Comment by huajie2020** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### This issue exists in the latest npm version
> 
> - [X] I am using the latest npm
> 
> ### Current Behavior
> 
> I have two packages `ajs` and `bjs`. Due to some reason I intend to merge both. Right now, I am installing `ajs` with `npm install ajs` and `bjs` with `npm install bjs`. But after the merge I wish to install `bjs` when `ajs` (`npm i ajs`) is installed.
> 
> I am aware of manual installation of `npm i <alias>@npm:<package>`. It does not solve my purpose. I did try searching a couple of times around this but did not find any documentation related to this. I doubt this is even directly possible. I wish not to copy one repo to another to maintain the sanity of the deprecated repository upgraded to another. The only option I see is update the github url in the repository. But I doubt it solves the purpose. Any help is welcome.
> 
> https://stackoverflow.com/questions/72554667/install-package-x-when-a-request-for-package-y-installation-is-made
> 
> 
> 
> ### Expected Behavior
> 
> Add documentation to redirect installation of one package(`ajs`) when installing another(`bjs`) package. Alternatively allow for the same as a feature.
> 
> ### Steps To Reproduce
> 
> NA. Feature 
> 
> ### Environment
> 
> - npm: 8.5.5
> - Node.js: 16.15.0
> - OS Name: Windows/Linux
> - System Model Name: Dell Vostro OEM 3590 - i5 x64 Arch
> - npm config: 
> ```ini
> ; copy and paste output from `npm config ls` here
> ; node bin location = C:\Users\ganes\OneDrive\Documents\binaries\node\node.exe
> ; cwd = C:\Users\ganes\OneDrive\Documents\projects\github\cgi-js
> ; HOME = C:\Users\ganes
> ; Run `npm config ls -l` to show all defaults.
> 
> C:\Users\ganes\OneDrive\Documents\projects\github\cgi-js>npm config ls -l
> ; "default" config from default values
> 
> _auth = (protected) 
> access = null 
> all = false
> allow-same-version = false
> also = null
> audit = true
> audit-level = null
> auth-type = "legacy"
> before = null
> bin-links = true
> browser = null
> ca = null
> cache = "C:\\Users\\ganes\\AppData\\Local\\npm-cache"
> cache-max = null
> cache-min = 0
> cafile = null
> call = ""
> cert = null
> ci-name = null
> cidr = null
> color = true
> commit-hooks = true
> depth = null
> description = true
> dev = false
> diff = []
> diff-dst-prefix = "b/"
> diff-ignore-all-space = false
> diff-name-only = false
> diff-no-prefix = false
> diff-src-prefix = "a/"
> diff-text = false
> diff-unified = 3
> dry-run = false
> editor = "notepad.exe"
> engine-strict = false
> fetch-retries = 2
> fetch-retry-factor = 10
> fetch-retry-maxtimeout = 60000
> fetch-retry-mintimeout = 10000
> fetch-timeout = 300000
> force = false
> foreground-scripts = false
> format-package-lock = true
> fund = true
> git = "git"
> git-tag-version = true
> global = false
> global-style = false
> globalconfig = "C:\\Users\\ganes\\OneDrive\\Documents\\binaries\\node\\etc\\npmrc"
> heading = "npm"
> https-proxy = null
> if-present = false
> ignore-scripts = false
> include = []
> include-staged = false
> include-workspace-root = false
> init-author-email = ""
> init-author-name = ""
> init-author-url = ""
> init-license = "ISC"
> init-module = "C:\\Users\\ganes\\.npm-init.js"
> init-version = "1.0.0"
> init.author.email = ""
> init.author.name = ""
> init.author.url = ""
> init.license = "ISC"
> init.module = "C:\\Users\\ganes\\.npm-init.js"
> init.version = "1.0.0"
> json = false
> key = null
> legacy-bundling = false
> legacy-peer-deps = false
> link = false
> local-address = null
> location = "user"
> lockfile-version = null
> loglevel = "notice"
> logs-max = 10
> ; long = false ; overridden by cli
> maxsockets = 15
> message = "%s"
> metrics-registry = "https://registry.npmjs.org/"
> node-options = null
> node-version = "v16.15.0"
> noproxy = [""]
> npm-version = "8.5.5"
> offline = false
> omit = []
> only = null
> optional = null
> otp = null
> pack-destination = "."
> package = []
> package-lock = true
> package-lock-only = false
> parseable = false
> prefer-offline = false
> prefer-online = false
> prefix = "C:\\Users\\ganes\\OneDrive\\Documents\\binaries\\node"
> preid = ""
> production = null
> progress = true
> proxy = null
> read-only = false
> rebuild-bundle = true
> registry = "https://registry.npmjs.org/"
> save = true
> save-bundle = false
> save-dev = false
> save-exact = false
> save-optional = false
> save-peer = false
> save-prefix = "^"
> save-prod = false
> scope = ""
> script-shell = null
> searchexclude = ""
> searchlimit = 20
> searchopts = ""
> searchstaleness = 900
> shell = "C:\\Windows\\system32\\cmd.exe"
> shrinkwrap = true
> sign-git-commit = false
> sign-git-tag = false
> sso-poll-frequency = 500
> sso-type = "oauth"
> strict-peer-deps = false
> strict-ssl = true
> tag = "latest"
> tag-version-prefix = "v"
> timing = false
> tmp = "C:\\Users\\ganes\\AppData\\Local\\Temp"
> umask = 0
> unicode = true
> update-notifier = true
> usage = false
> user-agent = "npm/{npm-version} node/{node-version} {platform} {arch} workspaces/{workspaces} {ci}"
> userconfig = "C:\\Users\\ganes\\.npmrc"
> version = false
> versions = false
> viewer = "browser"
> which = null
> workspace = []
> workspaces = null
> yes = null
> 
> ; "cli" config from command line options
> 
> long = true
> ```
>

**Comment by fritzy** [comment]
@ganeshkbhat Thanks for taking the time to share your idea! New ideas are always appreciated and are better suited for [our RFC repo](https://github.com/npm/rfcs) instead since that's the right place in order to get more attention from the rest of the team and the community.

Can you create [an RRFC](https://github.com/npm/rfcs/issues/new?assignees=&labels=&template=rrfc.md&title=%5BRRFC%5D+%3Ctitle%3E) in that repo?

Alternatively, this could be a feature of a registry rather than the CLI. For registry support please go to [npmjs.com/support](https://www.npmjs.com/support).

**Comment by ganeshkbhat** [comment]
Merging Issues. Seems this feature is being worked on already. I was not aware nor communicated. I though that was not nice at all.

https://github.com/npm/cli/issues/5009
https://github.com/npm/config/issues/76
https://github.com/npm/package-json/issues/9

**Comment by ganeshkbhat** [comment]
Citing npm package being pushed in as spam based on these articles I wish to push this as a reason to avoid false positives for a few percent of npm packages which were published as new packages:

- https://blog.sandworm.dev/one-in-two-new-npm-packages-is-seo-spam-right-now , and 
- https://developers.slashdot.org/story/23/03/30/184239/one-in-two-new-npm-packages-is-seo-spam-right-now 

While there may be a lot of spam packages, if you have duplicate package - renamed or republished due to some reason allowing redirect of a npm package to a different package name is definitely going to be a critical feature. You may want to do two this as per my view here:

1) `npm package one` -> redirect -> `npm package two` using keyword in `package.json` (the feature will install `npm package two` instead of `npm package one`).
2) `npm package one` -> redirect -> `npm package two` when opening the npm website 
     - Redirect the npmjs website desciption page for `npm package one` to `npm package two` since the package.json specifies config of redirect from `npm package one` to `npm package two`
     - Alternatively put a note in npmjs website in package description page that the `npm package one` is deprecated in favour of `npm package two` and that installation of `npm package one` will lead to installation of `npm package two`). This will help you to take a look at legacy `npm package one` package, its `description`, and its `legacy code`. This is expected and preferable.

I am now updating the expected behaviour in the issues from: 

`I should be able to redirect a npmjs A package to npmjs B package from package.json config.` to `I should be able to redirect installation of a npmjs A package to npmjs B package from package.json config.`

https://github.com/npm/package-json/issues/9#issuecomment-1491209278
