### ISSUE TITLE
[BUG] Got this error, whenever i tired to npm install (ubuntu 18.04)

### ISSUE THREAD

**Issue by Sanj4real** [npm/cli#5010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

npm ERR! Linux 5.4.0-117-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /media/sanjay/Data 1/nextproject/npm-debug.log

### Expected Behavior

1. have to install node module 

### Environment

- npm: 3.5.2
- Node.js: v8.10.0
- OS Name: ubuntu 18.04

**Comment by BalaM314** [comment]
> npm ERR! Please include the following file with any support request:
> npm ERR! /media/sanjay/Data 1/nextproject/npm-debug.log

**Comment by wraithgar** [comment]
The version of node and npm you are running are very old and not supported anymore.  Please try updating both to at least node@14 (which is in maintenance support) or newer, and npm@8

**Comment by AndnixSH** [comment]
I encounted the same issue. Turns out apt is out of date, i don't know why. I ended up installing nvm https://heynode.com/tutorial/install-nodejs-locally-nvm/ and ran npm script `curl -qL https://www.npmjs.com/install.sh | sh`
