### ISSUE TITLE
[BUG] run "npm init @scope@latest" error

### ISSUE THREAD

**Issue by jackyking-cn** [npm/cli#5022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

$ npm init @scope@latest
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "@scope" of package "@scope@0.0.6/create": name can only contain URL-friendly characters.

### Expected Behavior

fetches and runs the latest @scope/create from the registry

### Environment

- npm: 8.x

**Comment by fritzy** [comment]
You might mean `@scope/create@0.0.6`
If you had a package named `@scope/create-jackyking-app@0.0.6` you would do `npm init @scope/jackyking-app@0.0.6` and it would prefix `create-` for you.
