### ISSUE TITLE
[BUG] engine strict is not working with npm version 8.11.0

### ISSUE THREAD

**Issue by arusubramanian** [npm/cli#5037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

"engines": {
    "npm": "~8.5",
    "node": "~16"
  },

Engine strict is not working in the latest npm version 8.11.0. It is working in 8.5.1 version. 

If I run npm install or npm ci, it is not complaining about the engine's version (npm) but checking for peer dependency conflicts.

### Expected Behavior

npm install should fail if the engine's version in package.json is not met.

### Steps To Reproduce

Please add below configuration in package.json
"engines": {
    "npm": "~8.5",
    "node": "~16"
  },
Keep the environment as node v16.15.1 and npm 8.11.0
Run npm install

### Environment

.npmrc
engine-strict = true

; node version = v16.15.1
; npm version = 8.11.0

**Comment by ljharb** [comment]
The engines field is advisory, it is not supposed to fail.

You can add enginesStrict: true to package.json, but i don’t recommend it.

**Comment by fritzy** [comment]
Unable to reproduce
```sh
❯ cat package.json 
{
  "dependencies": {
    "ape-ecs": "^1"
  },
  "engines": {
  "npm": "~8.5",
  "node": "~16"
  }
}

projects/scratchpad/test6 via ⬢ v16.15.0 
❯ npm i --engine-strict
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: undefined
npm ERR! notsup Not compatible with your version of node/npm: undefined
npm ERR! notsup Required: {"npm":"~8.5","node":"~16"}
npm ERR! notsup Actual:   {"npm":"8.13.1","node":"v16.15.0"}

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fritzy/.npm/_logs/2022-06-29T19_11_54_488Z-debug-0.log
```

**Comment by flyhard** [comment]
I believe this issue only shows up when there are dependencies that won't resolve with npm 8 but will resolve with a previous version. I have a project myself that uses internal dependencies that won't resolve correctly using npm 8, but work fine using npm 6. 

If I remove those internal dependencies, the warnings come up, but not if I have them. 

I guess the "engines" section is processed after the dependencies have been resolved.

**Comment by zyf0330** [comment]
> I believe this issue only shows up when there are dependencies that won't resolve with npm 8 but will resolve with a previous version. I have a project myself that uses internal dependencies that won't resolve correctly using npm 8, but work fine using npm 6.
> 
> If I remove those internal dependencies, the warnings come up, but not if I have them.
> 
> I guess the "engines" section is processed after the dependencies have been resolved.

I think you are right.
This is my package.json.
```
{
  "name": "name",
  "version": "4.27.0",
  "scripts": {
    "e": "echo e"
  },
  "dependencies": {
    "@swc/helpers": "^0.4.11"
  },
  "devDependencies": {
    "@commitlint/cli": "^7.5.2",
    "@commitlint/config-conventional": "^7.5.0",
    "@nrwl/cli": "14.6.4",
    "@nrwl/eslint-plugin-nx": "14.6.4",
    "@nrwl/jest": "^14.7.17",
    "@nrwl/js": "14.6.4",
    "@nrwl/linter": "14.6.4",
    "@nrwl/node": "14.6.4",
    "@nrwl/workspace": "14.6.4",
    "@swc/core": "^1.3.10",
    "@swc/jest": "^0.2.22",
    "@types/jest": "^29.0.3",
    "@types/node": "18.7.1",
    "@typescript-eslint/eslint-plugin": "5.33.1",
    "@typescript-eslint/parser": "5.33.1",
    "conventional-changelog-cli": "^2.0.12",
    "cpx": "^1.5.0",
    "dotenv": "10.0.0",
    "eslint": "8.15.0",
    "eslint-config-prettier": "8.1.0",
    "husky": "^2.2.0",
    "jest": "^29.1.1",
    "jest_workaround": "^0.1.12",
    "nx": "14.6.4",
    "prettier": "2.6.2",
    "pretty-quick": "^3.1.0",
    "rimraf": "^2.6.3",
    "swc-loader": "^0.2.3",
    "ts-node": "10.9.1",
    "typescript": "4.6.4",
    "weak-napi": "^2.0.2"
  },
  "engines": {
    "yarn": ">=3.2.0",
    "node": "<=14.18.1",
    "npm": "use yarn"
  },
  "husky": {
    "hooks": {
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS",
      "pre-commit": "pretty-quick --staged"
    }
  },
  "packageManager": "yarn@3.2.0"
}

```
And after run `npm i`, npm resolves all dependencies like normal installation before show `EBADENGINE` error info
```
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: pc-typhon-nx@4.27.0
npm ERR! notsup Not compatible with your version of node/npm: pc-typhon-nx@4.27.0
npm ERR! notsup Required: {"yarn":">=3.2.0","node":"<=14.18.1","npm":"use yarn"}
npm ERR! notsup Actual:   {"npm":"8.19.2","node":"v16.17.0"}
```.
