### ISSUE TITLE
[DOCS] npmjs.com styling issue

### ISSUE THREAD

**Issue by LookRain** [npm/cli#5041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Problem, not another kind of Docs Problem.

- [X] This is a CLI Docs Problem.

### Description of Problem

Hi I could not find a place to report bugs for the npmjs.com website so here's that.

- Text are not properly wrapped on https://www.npmjs.com/package/sm2
![image](https://user-images.githubusercontent.com/11829847/174491050-b40e6c31-3d92-4aa9-8a43-15882af05f02.png)

### Potential Solution

![image](https://user-images.githubusercontent.com/11829847/174491141-c477df1c-7bca-46a5-94ca-cd4e9dd15727.png)
adding a css property seems to fix it, but not sure if that's the best solution to it

### Affected URL

https://www.npmjs.com/package/sm2

**Comment by fritzy** [comment]
**Closing:** this looks to be an issue with the registry which is outside the scope of this repo. For registry support please go to [npmjs.com/support](https://www.npmjs.com/support). If you believe this is a bug with the cli, please provide further clarifying details.
