### ISSUE TITLE
[BUG] npm audit fix fails to update packages, but stops reporting vulnerabilities anyway

### ISSUE THREAD

**Issue by cyrusae** [npm/cli#5053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

This appears to be somewhere in the neighborhood of #3472 + #4318, but there are enough complicating factors that I felt commenting would be derailing. As such I have included the entire series of cascading bugs and apologize if I should've started later in the series of events.

## Context and update issues
I am trying to make an Azure Data Studio theme for personal use. Based on guides such as [this one](https://github.com/dzsquared/AzureDataStudio_ExtensionDevelopment/blob/master/0-Prereqs.md), I installed Yo and the azuredatastudio generator as global installs. When I tried to do this, npm gave me multiple security alerts (I'm sorry, this beginning part I closed the relevant terminal and don't have transcripts, so I know updating npm was an issue in itself but I don't have a clear narrative of why) regarding the need to update npm itself. 

I (thought) I updated npm via the prompt npm itself suggested; the fact that this didn't work is relevant but I don't have the terminal output so I'm not comfortable reporting it as its own bug, I'm sorry. Running the attempt to install Yo again produced the same error. I looked it up and found advice to reinstall npm from `npm@latest`. I'm no longer sure how (sorry, as above) but I got it to version 8.12.2 eventually. 

Once I could install yo/the generator, npm returned 
```
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.

added 466 packages, and audited 467 packages in 7s

26 packages are looking for funding
  run `npm fund` for details

10 vulnerabilities (3 moderate, 3 high, 4 critical)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```
## First problem:

`npm audit` returned (I assume this is the global installs issue linked above) this: 
```
npm ERR! code ENOLOCK
npm ERR! audit This command requires an existing lockfile.
npm ERR! audit Try creating one first with: npm i --package-lock-only
npm ERR! audit Original error: loadVirtual requires existing shrinkwrap file
```
## Second problem:
Running `npm i --package-lock-only` produced an `ENOENT` error. I looked up this kind of error and the consensus seemed to be that `npx npm-global-audit` would be necessary to get around it. I installed npm-global-audit and ran `npx npm-global-audit --auditor npm`, with [this output](https://gist.github.com/cyrusae/5142d5f59cabf7864091e6ef0033d307) (stuck in a gist because it's massive). The comparison will be relevant shortly.
## Third problem:
I ran `npm audit fix` and then `npm audit fix --force`, as suggested. Both gave 
```
up to date, audited 1 package in 44ms

found 0 vulnerabilities
```
Rerunning npm-global-audit produced the same output in the above gist, *but* `npm audit` itself now returns just 
```
Found 0 vulnerabilities
```
Based on comments in one of the existing bugs here, I tried (re)installing each of the listed packages by hand. This worked successfully but did not change the audit output (either content or the conflicting part). 

## Fourth problem:
I tried troubleshooting Yo (`yo doctor` returned no issues, reinstalling `yo@latest` changed nothing), uninstalled the problem generator `azuredatastudio` itself (no change), and finally uninstalled Yo outright. 

After uninstalling Yo in its entirety, npm-global-audit and `npm audit` return matching `Found 0 vulnerabilities`. 

## Reason to believe npm is a/the problem
Yo itself does appear to have [catastrophic ongoing dependency issues](https://github.com/yeoman/yo/issues/716), i.e. the original audit was accurate. However, I'm reporting this as an npm bug for the following reasons based on my best understanding of what's at fault:
1. Mismatched audit results for global packages, showing the original (accurate) audit as having been "fixed"
2. Failure to update installed packages regardless of attempted method, including citing a "breaking change" update for Yo within an hour of installing it
3. False sense of security (literally) from `npm audit` due to the combination of 1 and 2 

### Expected Behavior

- My understanding is that `npm audit fix --force` is supposed to install things (e.g., despite things like the "will install Yo 1.4.5" alert for running `npm audit`, none of the announced behavior happened). 
- npm should have been capable of returning the same vulnerability alerts `npm-global-install` did a second time--especially since I'm using npm itself when doing so instead of the default yarn--instead of giving a false all clear.

### Steps To Reproduce

1. Attempt `npm install -g yo` in Terminal on macOS.
2. Attempt `npm install -g generator-azuredatastudio`.
3. Run `npm audit`, `npm audit fix`, and `npm audit fix --force` when prompted.
4. Run `npx npm-global-audit --auditor npm`.
5. Run `npm i -g [name]` for each package mentioned in the result of (4). 
6. Run `npm audit` and `npx npm-global-audit --auditor npm` again.
7. Uninstall Yo with `npm uninstall -g yo`.
8. Repeat step 6.

### Environment

- npm: 8.12.2
- Node.js: 17.3.1
- OS Name: macOS 12.3.1
- System Model Name: MacBook Air (2020)
- npm config:
```ini
; "builtin" config from /opt/homebrew/lib/node_modules/npm/npmrc

prefix = "/opt/homebrew" 

; node bin location = /opt/homebrew/Cellar/node/17.3.1/bin/node
; node version = v17.3.1
; npm local prefix = /Users/watcher
; npm version = 8.12.2
; cwd = /Users/watcher
; HOME = /Users/watcher
; Run `npm config ls -l` to show all defaults.```

**Comment by fritzy** [comment]
We don't support `audit fix` for global installs at this time.

**Comment by dobraslawa** [comment]
I have the same issue on Ubuntu 22,04. Anyone knows how to fix this issue? I've been thru same steps as op, nothing works.

**Comment by officalAbdulMalik** [comment]
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module 'mongoose'
Require stack:
- D:\node\app_beckend\app.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\node\app_beckend\app.js:2:18)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'D:\\node\\app_beckend\\app.js' ]
}


 npm install mongoose 

up to date, audited 22 packages in 3s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Getting the error after installing mongoose

**Comment by Jhonmacc** [comment]
Aqui está o que você pode fazer para atualizar o react-scripts:

Atualizar o react-scripts para a versão mais recente: Execute o comando abaixo para atualizar o pacote:


npm install react-scripts@latest
Isso vai atualizar o react-scripts para a versão 5.0.1 (ou a versão mais recente).

Verificar novamente: Após a atualização, você pode executar o comando npm outdated novamente para garantir que a atualização foi bem-sucedida.

Verificar se há outras dependências desatualizadas: Se houver mais pacotes desatualizados, você pode seguir o mesmo procedimento para atualizá-los. Use o comando:


npm update
Isso atualizará todas as dependências para a versão mais recente compatível, conforme definido no seu package.json.

Testar o projeto: Após atualizar o react-scripts, execute o seu projeto para verificar se tudo continua funcionando corretamente:


npm start
Esse procedimento deve corrigir as vulnerabilidades associadas à versão desatualizada do react-scripts.
