### ISSUE TITLE
[BUG] There is no way to get users email in my organization

### ISSUE THREAD

**Issue by BlueSeph28** [npm/cli#5057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When I use 
```
npm team ls organization:team

@organization:team has # users

user1
user2
user3
....
```

I only get a users list, for managing users in my organization is not useful only the username.

### Expected Behavior

Email must be provided if I'm the manager of the organization or the team.

we only admit enterprise's email so it's very easy to manage users by their email.

```
npm team ls organization:team

@organization:team has # users

user1 - user1@organization.com
user2  - user2@organization.com
user3  - user3@organization.com
....
```

### Steps To Reproduce

1. Run npm team ls organization:team

### Environment

- npm: 8.12.2
- Node.js: 15.0.1
- OS Name: Mac OS Big Sur
- System Model Name: Macbook Pro

**Comment by fritzy** [comment]
Can you create [an RRFC](https://github.com/npm/rfcs/issues/new?assignees=&labels=&template=rrfc.md&title=%5BRRFC%5D+%3Ctitle%3E) in that rep with some details on how you would like to see this changed?
