### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by motaharmalik** [npm/cli#507]
Hello! 

New to this, attached is the screenshot of the code I sent, I downloaded nodejs and put the code it told me to put ( npm install expo-cli --global) but I keep getting errors, I don't know why, 

Please help!
![Screenshot 2019-11-20 at 17 06 19](https://user-images.githubusercontent.com/58002725/69260784-55d2fc80-0bb8-11ea-8fb7-6047221fd7bf.png)
![Screenshot 2019-11-20 at 17 06 32](https://user-images.githubusercontent.com/58002725/69260791-58cded00-0bb8-11ea-9396-9548003652c0.png)

**Comment by motaharmalik** [comment]
Would like to comment that I have a macbook Air, if that helps.

**Comment by ljharb** [comment]
This seems to be an issue with libxmljs; you'll want to file it there.
