### ISSUE TITLE
npm v8.13.1 文件名、目录名或卷标语法不正确。

### ISSUE THREAD

**Issue by shunyue1320** [npm/cli#5075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

C:\Users\admin\working\F2E-harbour-web>npm run server:local
> truckharbour@1.0.0 server:local
> rimraf dist && npm run fix-memory-limit && webpack-dev-server --config webpack.local.js --progress --profile --watch --content-base ./dist --inline

文件名、目录名或卷标语法不正确。

### Steps To Reproduce

1. npm run ...
2. 文件名、目录名或卷标语法不正确。

### Environment

- npm: v8.13.1
- Node.js: v16.12.0
- OS Name: windows 11
- System Model Name: windows 
- npm config: npm run ...
```ini
; copy and paste output from `npm config ls` here
```

**Comment by JonasSchubert** [comment]
Related to https://github.com/npm/cli/issues/5066

**Comment by fritzy** [comment]
This is a dupe and a fix is in place for the next release.
