### ISSUE TITLE
[BUG] [Windows] Npm update fails from 8.4.0 to 8.11.0

### ISSUE THREAD

**Issue by munchkindev** [npm/cli#5083]
I have checked the existing issues and tried to use the newest npm version.

I newly installed the newest LTS release of Node.js (v16.15.1) which is supposed to contain npm version of 8.11.0.

I've installed the Windows package and executed all of the chocolatey scripts as recommended.

But when I run `npm -v` I get the following output:
```
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
8.4.0
```

Any idea how to fix this?

I already tried running `choco upgrade all`.

The older version causes issues for me, I also tried restarting the machine.

**Comment by fritzy** [comment]
This is a deprecation warning, and fixed with newer versions of npm.

**Closing:** please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).
