### ISSUE TITLE
[BUG] npm-install does not replace file dependency with npm dependency

### ISSUE THREAD

**Issue by iliubinskii** [npm/cli#5084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```json
{
  peerDependencies: {
   "my-package": "file:../local/my-package-1.0.0.tgz",
  }
}  
```

```bat
npm install my-package
```

It writes that everyting is up-to-date

### Expected Behavior

Npm should replace file dependency with npm dependency (even if they have the same versions)

### Steps To Reproduce

Add file dependency and try to install npm dependency over it.

### Environment

- npm: 8.5.5
- Node.js: 17.9.0
- OS Name: Windows
- System Model Name: 10

**Comment by fritzy** [comment]
If you don't specify the version as part of the <spec>, `npm install` will use what is already available in the package.json for the spec.

`npm install my-package@latest` using an existing tag or version spec will properly replace this value.
