### ISSUE TITLE
[BUG] npm publish with automation token in npmrc returns 404 "not in this registry" error

### ISSUE THREAD

**Issue by Dottenpixel** [npm/cli#5089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I'm testing a publishing workflow locally with an Automation access token so that I can then implement for CI. 

Note: I don't get this error if I'm logged in manually, via the username, password, email OTP prompts, but am trying to set things up so that publishing can be done autonomously in CI.

My .npmrc looks like this:
```
_auth=npm_fooBAR
//registry.npmjs.org/:_authToken=$TOKEN
```
The token in my `.npmrc` is an Automation token so I don't get 2FA'd. I'm publishing a new version to my already existing package.

On `npm publish ./.dist` I receive
```
npm notice Publishing to https://registry.npmjs.org/
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/@my-package%2fmy-package - Not found
npm ERR! 404
npm ERR! 404  '@my-org/my-package@1.1.0-alpha.1' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

### Expected Behavior

The package is published successfully without me being prompted for auth

### Steps To Reproduce

1. `npm config set _auth "npm_fooBAR" --location project`
2. `npm set //registry.npmjs.org/:_authToken $TOKEN`
3. Run 'npm publish ./.dist'
4. See error...
```
npm notice === Tarball Details ===
...
npm notice Publishing to https://registry.npmjs.org/
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/@my-package%2fmy-package - Not found
npm ERR! 404
npm ERR! 404  '@my-org/my-package@1.1.0-alpha.1' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```
Am I missing something in my .npmrc? 
Also, if I'm publishing, why would the error be telling me about install options?

### Environment

- npm: 8.13.1
- Node.js: 16.15.0
- OS Name: MacOS 11.6.7
- System Model Name: iMac (Retina 5K, 27-inch, 2020)
- npm config:
```ini
npm config ls
; "user" config from /Users/dmolidor/.npmrc

; //registry.npmjs.org/:_authToken = (protected) ; overridden by project

; "project" config from /Users/dmolidor/_Code/design-system/.npmrc

_auth = (protected)
//registry.npmjs.org/:_authToken = (protected)

; node bin location = /Users/dmolidor/.nvm/versions/node/v16.15.0/bin/node
; node version = v16.15.0
; npm local prefix = /Users/dmolidor/_Code/design-system
; npm version = 8.13.1
; cwd = /Users/dmolidor/_Code/design-system
; HOME = /Users/dmolidor
```

**Comment by fritzy** [comment]
I'm not sure how you're sourcing your automation token. Please see the documentation for CI tokens. https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow

**Comment by Dottenpixel** [comment]
Thanks for responding @fritzy, but that link doesn't address my issue. My package, although scoped, is public. Can you please re-open my issue?

I'm sourcing my automation token from the UI flow: https://www.npmjs.com/settings/{{my-org}}/tokens/new

Any idea why would I get such a cryptic error as the one I'm getting? Our package has been in the public registry for years.

**Comment by Dottenpixel** [comment]
> Can you please re-open my issue?

nm @fritzy I made a new token via the UI and the publish process worked! Can't find what was wrong with the original token. The error message definitely threw me off, though.

Thanks again!

**Comment by HobaiRiku** [comment]
![image](https://github.com/user-attachments/assets/81b95fdb-dabe-4ec2-ba4f-f045d5f32038)
![image](https://github.com/user-attachments/assets/b7e1c433-517d-479c-96a2-7aa1659fd8a1)
same here， I use the same token from npm -> account -< accessToken and put it into the GitLab variable, some packages work, but some show 404.
![image](https://github.com/user-attachments/assets/0293cf13-29da-4972-9858-604a7be90529)
