### ISSUE TITLE
[BUG] Check failed: reservation_.SetPermissions

### ISSUE THREAD

**Issue by RealityGamin** [npm/cli#5090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

This unexplainable error is showing up when trying to install any NPM package anywhere on my OS

![image](https://user-images.githubusercontent.com/100086757/176094190-f4f11fa5-cd1d-4300-b961-590bd07f5f19.png)

```

#
# Fatal error in , line 0
# Check failed: reservation_.SetPermissions( unprotect_start, unprotect_size, MemoryChunk::GetCodeModificationPermission()).
#
#
#
#FailureMessage Object: 0x7ffde2f90250
 1: 0xbd40d1  [npm install laravel-mix@latest]
 2: 0x1dfdab4 V8_Fatal(char const*, ...) [npm install laravel-mix@latest]
 3: 0xf98f6e  [npm install laravel-mix@latest]
 4: 0xf40e11 v8::internal::Heap::UnprotectAndRegisterMemoryChunk(v8::internal::HeapObject, v8::internal::UnprotectMemoryOrigin) [npm install laravel-mix@latest]
 5: 0xf1feb4 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [npm install laravel-mix@latest]
 6: 0xf01045 v8::internal::Factory::CodeBuilder::AllocateCode(bool) [npm install laravel-mix@latest]
 7: 0xf14f2c v8::internal::Factory::CodeBuilder::BuildInternal(bool) [npm install laravel-mix@latest]
 8: 0x1e1f31e v8::internal::compiler::CodeGenerator::FinalizeCode() [npm install laravel-mix@latest]
 9: 0x1e9ed82 v8::internal::compiler::PipelineImpl::FinalizeCode(bool) [npm install laravel-mix@latest]
10: 0x1e9fdfb v8::internal::compiler::PipelineCompilationJob::FinalizeJobImpl(v8::internal::Isolate*) [npm install laravel-mix@latest]
11: 0xdfae50 v8::internal::OptimizedCompilationJob::FinalizeJob(v8::internal::Isolate*) [npm install laravel-mix@latest]
12: 0xdfef0b v8::internal::Compiler::FinalizeTurbofanCompilationJob(v8::internal::TurbofanCompilationJob*, v8::internal::Isolate*) [npm install laravel-mix@latest]
13: 0xe259cf v8::internal::OptimizingCompileDispatcher::InstallOptimizedFunctions() [npm install laravel-mix@latest]
14: 0xec6377 v8::internal::StackGuard::HandleInterrupts() [npm install laravel-mix@latest]
15: 0x12c4f0f v8::internal::Runtime_StackGuardWithGap(int, unsigned long*, v8::internal::Isolate*) [npm install laravel-mix@latest]
16: 0x16f6939  [npm install laravel-mix@latest]

Trace/breakpoint trap (core dumped)

```

### Steps To Reproduce

1) Created a new folder
2) ran the command `npm install laravel-mix@latest`

Please note that its happening regardless of the package im trying to install

### Environment

- npm: 8.12.1
- Node.js: v18.4.0
- OS Name: Alma Linux 8
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```
; "default" config from default values

_auth = (protected)
access = null
all = false
allow-same-version = false
also = null
audit = true
audit-level = null
auth-type = "legacy"
before = null
bin-links = true
browser = null
ca = null
cache = "/home/haward/.npm"
cache-max = null
cache-min = 0
cafile = null
call = ""
cert = null
ci-name = null
cidr = null
color = true
commit-hooks = true
depth = null
description = true
dev = false
diff = []
diff-dst-prefix = "b/"
diff-ignore-all-space = false
diff-name-only = false
diff-no-prefix = false
diff-src-prefix = "a/"
diff-text = false
diff-unified = 3
dry-run = false
editor = "vi"
engine-strict = false
fetch-retries = 2
fetch-retry-factor = 10
fetch-retry-maxtimeout = 60000
fetch-retry-mintimeout = 10000
fetch-timeout = 300000
force = false
foreground-scripts = false
format-package-lock = true
fund = true
git = "git"
git-tag-version = true
global = false
global-style = false
globalconfig = "/usr/etc/npmrc"
heading = "npm"
https-proxy = null
if-present = false
ignore-scripts = false
include = []
include-staged = false
include-workspace-root = false
init-author-email = ""
init-author-name = ""
init-author-url = ""
init-license = "ISC"
init-module = "/home/haward/.npm-init.js"
init-version = "1.0.0"
init.author.email = ""
init.author.name = ""
init.author.url = ""
init.license = "ISC"
init.module = "/home/haward/.npm-init.js"
init.version = "1.0.0"
install-links = false
json = false
key = null
legacy-bundling = false
legacy-peer-deps = false
link = false
local-address = null
location = "user"
lockfile-version = null
loglevel = "notice"
logs-dir = null
logs-max = 10
; long = false ; overridden by cli
maxsockets = 15
message = "%s"
metrics-registry = "https://registry.npmjs.org/"
node-options = null
node-version = "v18.4.0"
noproxy = [""]
npm-version = "8.12.1"
offline = false
omit = []
omit-lockfile-registry-resolved = false
only = null
optional = null
otp = null
pack-destination = "."
package = []
package-lock = true
package-lock-only = false
parseable = false
prefer-offline = false
prefer-online = false
prefix = "/usr"
preid = ""
production = null
; progress = true ; overridden by user
proxy = null
read-only = false
rebuild-bundle = true
registry = "https://registry.npmjs.org/"
save = true
save-bundle = false
save-dev = false
save-exact = false
save-optional = false
save-peer = false
save-prefix = "^"
save-prod = false
scope = ""
script-shell = null
searchexclude = ""
searchlimit = 20
searchopts = ""
searchstaleness = 900
shell = "/bin/bash"
shrinkwrap = true
sign-git-commit = false
sign-git-tag = false
sso-poll-frequency = 500
sso-type = "oauth"
strict-peer-deps = false
strict-ssl = true
tag = "latest"
tag-version-prefix = "v"
timing = false
tmp = "/tmp"
umask = 0
unicode = true
update-notifier = true
usage = false
user-agent = "npm/{npm-version} node/{node-version} {platform} {arch} workspaces/{workspaces} {ci}"
userconfig = "/home/haward/.npmrc"
version = false
versions = false
viewer = "man"
which = null
workspace = []
workspaces = null
workspaces-update = true
yes = null

; "user" config from /home/haward/.npmrc

progress = false

; "cli" config from command line options

long = true

**Comment by RealityGamin** [comment]
**Update:**

Okay, it seems like I can run the command in root, but on my local user, I get this error, any idea how to resolve permission issues with NPM?

**Comment by RealityGamin** [comment]
***Update:***

Running the command on root works, but when trying to do it on my user created directories, it gives the above error, could it be a permission issue with using NPM?

**Comment by fritzy** [comment]
This looks like it's an issue with script protection on your OS. Some quick searches reveal that this may be related to PaX and permission for node/npm/npx scripts.
