### ISSUE TITLE
[BUG] npm 8.13.1 error when using --ssl: The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by pawan-gwebs** [npm/cli#5092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I'm stuck with this error 
I used command: "npm start", which is using " run-script-os" to serve ng application

> appx@0.0.0 start
> run-script-os

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> appx@0.0.0 start:windows
> ng serve --ssl --ssl-cert %APPDATA%\ASP.NET\https\%npm_package_name%.pem --ssl-key %APPDATA%\ASP.NET\https\%npm_package_name%.key

The filename, directory name, or volume label syntax is incorrect.

### Expected Behavior

App should be run/compile successfully.

### Environment

- npm: v8.13.1
- Node.js:  v16.15.1
- OS Name: Windows 10
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by fritzy** [comment]
There's a known issue with colons in scriptnames on windows for 8.13.1 that should be fixed in tomorrow's release. https://github.com/npm/cli/issues/5066

It's confusing that you're getting the `--global` warning with 8.13.1 as that's been removed.
