### ISSUE TITLE
[BUG] Package name capitalization is handled inconsistently

### ISSUE THREAD

**Issue by McSneaky** [npm/cli#5096]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Sometimes `jQuery` and `jquery` are same package. Sometimes they are different ones

Seems like when doing initial installation of project, they are considered different ones

When doing fresh installation:
```sh
└─$ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: frontend-vue@0.1.0
npm ERR! Found: jquery@3.5.1
npm ERR! node_modules/jquery
npm ERR!   jquery@"3.5.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer jQuery@"3.5.1" from jquery-expression-builder@0.1.2
npm ERR! node_modules/jquery-expression-builder
npm ERR!   jquery-expression-builder@"^0.1.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/mcsneaky/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mcsneaky/.npm/_logs/2022-06-28T23_06_36_648Z-debug-0.log
```

Notice how `jquery-expression-builder` requires `jQuery`, but at root of project there is `jquery` (no capital `Q`)

Now when doing `npm install https://github.com/McSneaky/JQuery-expression-builder` to install my fork where I changed `peerDependency` from `jQuery` to `jquery` installation is all good

After installing with my fork I can switch it back from
`"jquery-expression-builder": "https://github.com/McSneaky/JQuery-expression-builder",`
to
`"jquery-expression-builder": "^0.1.2",`
and after that `npm i` passes all good. It's only initial installation where capitalization seems to matter

### Expected Behavior

NPM to resolve `jquery` and `jQuery` to same dependency consistantly

Or resolves them to be different ones consistantly. Currently sometimes they are considered same, sometimes they are considered different

### Steps To Reproduce

Create fresh project (folder)
Run:
- `npm i jquery@3.5.1`
- `npm i jquery-expression-builder`
Error appears:
```sh
└─$ npm i jquery-expression-builder
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: jquery@3.5.1
npm ERR! node_modules/jquery
npm ERR!   jquery@"^3.5.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer jQuery@"3.5.1" from jquery-expression-builder@0.1.2
npm ERR! node_modules/jquery-expression-builder
npm ERR!   jquery-expression-builder@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/mcsneaky/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mcsneaky/.npm/_logs/2022-06-28T23_27_07_176Z-debug-0.log
```

Install fork:
- `npm i https://github.com/McSneaky/JQuery-expression-builder`
No error, everything works

Replace fork with original again by replacing `github:McSneaky/JQuery-expression-builder` with `0.1.2` in `package.json` so it looks like this:
```json
{
  "dependencies": {
    "jquery": "^3.5.1",
    "jquery-expression-builder": "0.1.2"
  }
}
```

Run install again:
- `npm i`
Everything works this time with original versioning. When you delete `package-lock.json` and `node_modules` folders it starts to break again

### Environment

- npm: 8.13.1
- Node.js: v16.6.0
- OS Name: Ubuntu
- System Model Name: VERSION="20.04.3 LTS (Focal Fossa)"
- npm config:
```ini
; "user" config from /home/mcsneaky/.npmrc

//registry.npmjs.org/:_authToken = (protected) 

; node bin location = /home/mcsneaky/.nvm/versions/node/v16.6.0/bin/node
; node version = v16.6.0
; npm local prefix = /home/mcsneaky/Projects/temp
; npm version = 8.13.1
; cwd = /home/mcsneaky/Projects/temp
; HOME = /home/mcsneaky
; Run `npm config ls -l` to show all defaults.
```

**Comment by wraithgar** [comment]
This is a legacy of how the npm registry used to work.  Originally it was a couchdb, and the package names were case sensitive.  The npm registry no longer allows upper case letters in package names, but the support for those old packages still exists.  This means that the cli has to treat package names as case sensitive still.

`jquery` and `jQuery` are two different packages in the registry.  npm is doing exactly what was asked of it. https://github.com/magicops/JQuery-expression-builder/pull/13 is the correct fix.

**Comment by McSneaky** [comment]
Thank you for explaining reasoning behind there! 🙂👍 

There are still packages with both naming conventions so cant just migrate everything to be lowercase in registry? So such migration would cause name collisions?
