### ISSUE TITLE
[DOCS] <https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004>

### ISSUE THREAD

**Issue by HomyeeKing** [npm/cli#5099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Problem, not another kind of Docs Problem.

- [X] This is a CLI Docs Problem.

### Description of Problem

in caret part, there's an example:
> ^1.2.3-beta.2 := >=1.2.3-beta.2 <2.0.0 Note that prereleases in the 1.2.3 version will be allowed, if they are greater than or equal to beta.2. So, 1.2.3-beta.4 would be allowed, but 1.2.4-beta.2 would not, because it is a prerelease of a different [major, minor, patch] tuple

if I didn't get wrong, it says 1.2.4-beta.2  not satisfied ^1.2.3-beta.2, but it does

![image](https://user-images.githubusercontent.com/49113249/176396544-e215c36c-eae7-4cf4-9690-cb0c09fe6d2d.png)

### Affected URL

https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004

**Comment by fritzy** [comment]
@HomyeeKing You can use our calculator, https://semver.npmjs.com/. Our semver spec is slightly extended.
