### ISSUE TITLE
Getting peer dependencies issue for npm@8.5.5

### ISSUE THREAD

**Issue by SRUJANA-PENUGONDA13** [npm/cli#5100]
I am facing peer dependencies issues for below versions 

npm -  8.5.5
node - 14.19.0

Which was working fine before with below versions with same codebase

npm - 8.12.2
node - 14.19.1

Can someone please help me why this is happening

**Comment by ljharb** [comment]
npm 8.5.5 is older than 8.12.2, so it’s missing a bunch of bugfixes. Try npm 8 latest.

**Comment by fritzy** [comment]
There were some fixes regarding lock files being inconsistent with package.json dependencies in 8.6.0. We only accept bug reports on the latest version of npm, please upgrade with something like `npm i npm@latest -g`
