### ISSUE TITLE
npmjs site

### ISSUE THREAD

**Issue by kamalkech** [npm/cli#511]
Today i buy a private package successufly
but the site npmjs not work correctly and same time pages broken and i can t check my account npm
i can t understand that, the site on maintenance / construction ???

because like that i can t finish my work, 

![npmjs](https://user-images.githubusercontent.com/1313428/69425507-5049f380-0d2b-11ea-8c00-b87c4e7f8238.png)

**Comment by DanielRuf** [comment]
There was an outage which should be resolved now.
Consider using caches and verdaccio as offline fallback.

**Comment by ruyadorno** [comment]
thanks for the report @kamalkech 👍 

for reference, in the future you might want to reach out to support directly at support@npmjs.com or https://twitter.com/npm_support for help 😊
