### ISSUE TITLE
[BUG] Some Github dependencies no longer install

### ISSUE THREAD

**Issue by jdesrosiers** [npm/cli#5116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Some of my dependencies from Github repos such as `"json-schema-test-suite": "github:json-schema-org/JSON-Schema-Test-Suite",` are no longer successfully installing the way they used to. I get an error related to not being able to find a file. Some github dependencies work fine, but others give this error.

### Expected Behavior

Dependencies from Github repos should work like they used to, or there should be a useful error message informing the user how to correct the problem.

### Steps To Reproduce

The following reproduces the error.

```
docker run node npm install -g github:json-schema-org/json-schema-test-suite
```

```
npm notice 
npm notice New minor version of npm available! 8.12.1 -> 8.13.2
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.13.2>
npm notice Run `npm install -g npm@8.13.2` to update!
npm notice 
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /root/.npm/_cacache/tmp/git-clone7IMxQh/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/root/.npm/_cacache/tmp/git-clone7IMxQh/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-07-01T17_12_31_470Z-debug-0.log
```

Other repos, such as the following still work fine.

```
docker run node npm install -g github:hyperjump-io/json-pointer#v0.9.1
```

```

added 2 packages, and audited 3 packages in 3s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice 
npm notice New minor version of npm available! 8.12.1 -> 8.13.2
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.13.2>
npm notice Run `npm install -g npm@8.13.2` to update!
npm notice 
```

### Environment

- npm: 8.12.1
- Node.js: 18.4.0
- OS Name: Debian GNU/Linux 11 (bullseye)
- System Model Name: Docker
- npm config:
```ini
; node bin location = /usr/local/bin/node
; node version = v18.4.0
; npm local prefix = /
; npm version = 8.12.1
; cwd = /
; HOME = /root
; Run `npm config ls -l` to show all defaults.

```

**Comment by jdesrosiers** [comment]
I found the problem. It's not an npm bug.

**Comment by chm-diederichs** [comment]
@jdesrosiers what was the issue in the end? Have been repeatedly running into this error in another repo.

**Comment by jdesrosiers** [comment]
@chm-diederichs It turned out that a dependency I was using had deleted their package.json file. Any package that used that dependency or depended on something that used that dependency gave this error.
