### ISSUE TITLE
Provide a means for other programs to import config definitions for @npmcli/config as a replacement to libnpmconfig

### ISSUE THREAD

**Issue by Kytech** [npm/cli#5119]
Since [libnpmconfig](https://www.npmjs.com/package/libnpmconfig) and the programmatic APIs have been deprecated, there is no library or API provided by NPM that can be consumed by other packages to read NPM's configuration. libnpmconfig has been replaced with `@npmcli/config`, which cannot read the npm configuration on its own.

In order to allow other programs to read the npm config file using NPM's config resolution algorithm, the definitions in this repository (https://github.com/npm/cli/tree/latest/lib/utils/config) need to be made available.

There are a large number of projects that read the npm config files, but they all have to resort to writing a large amount of the resolution code themselves. Yarn and PNPM provide packages that allow their respective config files to be read by other programs, but since the deprecation of libnpmconfig and the programmatic API, NPM does not have a usable config package (as far as other applications are concerned), which has caused pain points for a number of projects, especially since the recent security issue with `rc`, which many packages used to roll their own solution, and are now looking to replace as a dependency.

**Comment by ljharb** [comment]
Typically they shell out to npm config get. Is there a reason that won’t work for your use case?

**Comment by Kytech** [comment]
The use case I have dealt with is for packages such as [registry-auth-token](https://www.npmjs.com/package/registry-auth-token), which has to rely on someone else's reimplementation of the NPM config resolution algorithm (previously used rc, but now is using PNPM's implementation). Registry tokens are not retrievable using npm config get due to the `option is protected, and cannot be retrieved in this way` error, so the project always has to resort to using re-implementations of the config resolution logic. I can understand why that setting is protected, and I do think that making it inaccessible via the CLI is good practice, but there are some legitimate use cases where accessing the token outside of npm is needed.

As to what the use case is for even trying to read the npm auth token, for more context, I've had to resort to using registry-auth-token instead of shelling out (which is sufficient for other settings for my use case) since I've needed to be able to retrieve an NPM auth token from configuration for use in some scripting that we use as part of our workflow automation. Part of it involves running npm on both a host and inside containers as well as between multiple machines where just copying user-level .npmrc files results in additional settings being overwritten. Ideally, we want to be able to just pass around the npm token on its own when the script runs without having to worry about modifying the .npmrc files. I believe that the most common use case for registry-auth-token is in automation scripts. Storing the auth token as a system or user-level environment variable for the sake of these automation scripts isn't something we'd want to do either since we would have less access control over an environment variable than by managing file permissions/SELinux (where used), even though a .npmrc file can pull the token from the system environment.

Other use cases that would benefit would be package managers like PNPM, who currently have to resort to writing their own reimplementation of the NPM config resolution algorithm since it is designed to reuse the existing npm config options and files. I am not a contributor to the PNPM project, so I can't say why shelling out isn't sufficient for their project, but I would guess that it might have to do with the performance overhead or code complexity of having to shell out many times for each setting they need to read.

Additionally, projects such as [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) also read a number of NPM config values. Since many of these are also node packages, it gives a much cleaner interface if there's a JavaScript API to call instead of shelling out. There seems to be a fair number of projects out there that read NPM config values, a few of which I have mentioned. Many of the projects of this type look to have used `libnpmconfig` when it was actively maintained, so it seems like the the status quo shift of having a library to read configs to no longer having such a library has created a lot of additional friction for these types of projects.

**Comment by ljharb** [comment]
Thanks, "getting the auth token" makes the use case quite clear.

I think every other config value would be gettable on the CLI, so shelling out is relatively straightforward, but "protected" values make it tricky.

**Comment by fritzy** [comment]
I started an RRFC to discuss this feature.
https://github.com/npm/statusboard/issues/525

**Comment by AlexanderLeonov** [comment]
Any updates on this?
