### ISSUE TITLE
Publish operations slow

### ISSUE THREAD

**Issue by lol768** [npm/cli#512]
No idea where to raise this sort of issue by the way, there are numerous repos pointing me at https://npm.community and telling me not to raise GitHub issues but it appears to be dead:

> This site is in read only mode. Please continue to browse, but replying, likes, and other actions are disabled for now.

Publish operations are incredibly slow as of late but there's nothing on the status page:

```
[..................] / : http fetch PUT 401 https://registry.npmjs.org/@universityofwarwick%2fid7 24065ms
```

![image](https://user-images.githubusercontent.com/2552726/69426692-b764a980-0d25-11ea-950c-4756becfebde.png)

**Comment by lol768** [comment]
#511 looks like it's probably related

**Comment by nikolaik** [comment]
I also see see requests to npmjs.com timing out:
![image](https://user-images.githubusercontent.com/104154/69429784-a4a5a100-0d34-11ea-93bd-eb57a30234ed.png)

![image](https://user-images.githubusercontent.com/104154/69429797-b129f980-0d34-11ea-8173-53c06992fb97.png)

**Comment by michael-riess** [comment]
This may be related:
I just tried to publish a private package and after hanging for a while I finally got this.
<img width="801" alt="Screen Shot 2019-11-22 at 22 33 58" src="https://user-images.githubusercontent.com/35740174/69430058-4a2e3400-0d78-11ea-8055-93f01e080167.png">
Hoping that it was just a fluke, I rebuilt and tried to publish again. Again it hung for a while, but this time I got the warning telling me that I cannot publish over an already existing version. I went to npmjs.com and sure enough it had actually been published.

**Comment by thomasmichaelwallace** [comment]
Just another datapoint: we've been having sporadic 503's all day (Service Unavailable / No Backends Available) both when downloading and publishing.

[edit] now seems to be reflected on the status page: https://status.npmjs.org/incidents/gtjlhzsjqsyr?u=z8clpczywxcb

**Comment by ruyadorno** [comment]
> No idea where to raise this sort of issue by the way, there are numerous repos pointing me at https://npm.community and telling me not to raise GitHub issues but it appears to be dead

GitHub issues are open now 😊 although this repo is a better place to follow up on specific **cli** issues.

The incident in discussion here seems over now but for reference, in the future you might want to reach out to support directly at support@npmjs.com or https://twitter.com/npm_support for help 😊
