### ISSUE TITLE
[BUG] git dependency installed with npm ci triggers error with npm prune --production

### ISSUE THREAD

**Issue by Cherry** [npm/cli#514]
When installing some git dependencies using the Docker image node:10-alpine via `npm ci`, attempts to `npm prune --production` result in an error like:
```
npm ERR! code 128
npm ERR! Command failed: git clone --mirror -q https://github.com/nodecraft/ampify.git /root/.npm/_cacache/tmp/git-clone-6573274f/.git
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-6573274f/.git'
```

To help replicate the issue, I have a directory that contains a `package.json` and `package-lock.json`. I then have a `Dockerfile` which when building, illustrates the issue.

I've created a repository at https://github.com/Cherry/npm-prune-ci-bug detailing this, including commands to run to replicate the issue.

Last known working version: `6.10.3`. This issue does not occur if I use npm version `6.10.3` or earlier.
Tested versions that throw the above error:
```
6.11.0
6.11.1
6.11.2
6.11.3
6.12.1
6.13.1
```
It appears this regression was introduced in `6.11.0`, and exists through to the latest version.

If I can provide any further information, please let me know.

**Comment by sdanieru** [comment]
This was a breaking change for our builds when we bumped node:10.16 to node:10.17 (since that bumps npm 6.9.0 to 6.11.3)
Thanks @Cherry for writing this up!

**Comment by Cherry** [comment]
Is there any update or resolution to this issue? With the recent [security advisory to update to 6.13.4](https://blog.npmjs.org/post/189618601100/binary-planting-with-the-npm-cli), this issue is preventing us from ensuring our team and their systems are safe.

**Comment by isaacs** [comment]
Looks like a duplicate of #624.

**Comment by Cherry** [comment]
Seems like it, yes. This was created before #624 but that issue has more discussion. I'll go ahead and close this issue and leave the discussion there.
