### ISSUE TITLE
[BUG] npm exit without error doing nothing

### ISSUE THREAD

**Issue by ksuedile** [npm/cli#5142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

see that ticket : https://github.com/nodejs/node/issues/43348

### Expected Behavior

see that ticket : https://github.com/nodejs/node/issues/43348

### Steps To Reproduce

see that ticket : https://github.com/nodejs/node/issues/43348

### Environment

see that ticket : https://github.com/nodejs/node/issues/43348

**Comment by wraithgar** [comment]
Duplicate of https://github.com/npm/cli/issues/4838
