### ISSUE TITLE
Feature request: Support --cpu and --os flag to specify platform specific install

### ISSUE THREAD

**Issue by archfz** [npm/cli#5152]
## Use case

Given the `os` and `cpu` package.json attributes, and the rise on usage of `optionalDependencies` for native modules, and also given cross platform building of certain applications like `electron`, it would be nice to be able to install npm packages for a given platform, disregarding current platform.

My case is having a thrid party native module using `optionalDependencies` to install platform specific node bindings. Now this module is bundled together with an `electron` app, and the build pipeline uses `wine` to build it for windows as well from debian. The issue is that the thrid party native module will always be installed with `linux` native bindings.

## Proposal

The proposal is to have two extra possible arguments for `npm install`. `--os` would specify for what operating system to install packages, `--cpu` for what cpu. The defaults for these options would be from current platform.

Example: `npm i --os win32 --cpu x64`

**Comment by ljharb** [comment]
feature requests go in https://github.com/npm/rfcs

**Comment by alex-kinokon** [comment]
RFC Link: https://github.com/npm/rfcs/issues/612
