### ISSUE TITLE
[BUG] Error: Cannot create a string longer than 0x1fffffe8 characters

### ISSUE THREAD

**Issue by LanYunDev** [npm/cli#5174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When I do this:npm publish --access public
I got : 
Error: Cannot create a string longer than 0x1fffffe8 characters

<img width="730" alt="image" src="https://user-images.githubusercontent.com/95263282/179199866-4f26a1ad-2777-422f-b453-c06fcab2555d.png">

This is my log file:
[2022-07-15T09_38_03_593Z-debug-0.log](https://github.com/npm/cli/files/9119798/2022-07-15T09_38_03_593Z-debug-0.log)

I can hardly analyze what is wrong.

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by ljharb** [comment]
I wonder if the file path containing chinese characters is the issue - could you try relocating the package temporarily, and publishing from there?

**Comment by wraithgar** [comment]
This appears to be an issue w/ the registry itself, as it parses the tarball contents.  You likely need to open up a ticket w/ the npm registry at https://www.npmjs.com/support

**Comment by wraithgar** [comment]
This isn't hitting the npm registry which means it is node itself that's bailing out.

Digging into the logfile again I now see that it's erroring when trying to create the tarball. It is over 500mb in memory.  That is larger an node can put into a string to upload to the server, let alone anything the registry is prepared to accept.

Your published package can not be that large.  You can try shrinking it by omitting some of the built assets using a `.npmignore` file or by specifying only the files to include in the published package using a `files` array in the package.json.

**Comment by qiancheng6** [comment]
I have similar issue when syncing a video file to S3. The video is just 200+ Mb, and its encrypted file less than 400 Mb. Local notebook works fine but when syncing to AWS S3, it shows "Last error: Error: Error: Cannot create a string longer than 0x1fffffe8 characters."

I am using the Mac version Joplin 2.13.15
