### ISSUE TITLE
[BUG] version specifier doesn't work with scoped packages in `npm init`

### ISSUE THREAD

**Issue by alan-agius4** [npm/cli#5175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When using `npm init` the version specifier doesn't work when the package is scoped.

### Expected Behavior

The version specifier is used and the command doesn't error.

### Steps To Reproduce

```
$ npm create @angular@next
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "@angular" of package "@angular@next/create": name can only contain URL-friendly characters.
```

### Environment

- npm: 8.11.0
- Node.js: 16.15.1
- OS Name: Linux 5.17 Debian GNU/Linux rodete 12 (rodete)
- System Model Name: cloud

**Comment by ljharb** [comment]
When it's scoped, you have to use the full package name - `@angular/create`

**Comment by alan-agius4** [comment]
That doesn't works either

```
npm init @angular/create@next
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@angular%2fcreate-create - Not found
npm ERR! 404 
npm ERR! 404  '@angular/create-create@next' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

```

**Comment by marssaljr** [comment]
@alan-agius4 Have you tried this?
> npm install -g @angular/cli
> ng new [PROJECT NAME]

**Comment by alan-agius4** [comment]
Hi @marssaljr, I am well aware of that command, as I am from the Angular team. The bug I am reporting is caused by NPM init command is incorrectly handling version specifiers when using scoped packages.

**Comment by wraithgar** [comment]
Sorry about that @alan-agius4.  Should be fixed by https://github.com/npm/cli/pull/5206

**Comment by alan-agius4** [comment]
Thanks @wraithgar

**Comment by wraithgar** [comment]
@alan-agius4 this is in `npm@8.15.1`

**Comment by alan-agius4** [comment]
Great thanks.
