### ISSUE TITLE
Hello! Facing the same issue with npm and yarn in windows too

### ISSUE THREAD

**Issue by Tobi-davies** [npm/cli#5179]
Hello! Facing the same issue in windows too...

**npm version** - 8.5.2
**OS** - Windows 10
**Node** - v16.14.0

Getting the error -
 **npm ERR! code UNKNOWN
npm ERR! syscall mkdir
npm ERR! path C:\Users\HP\AppData\Local\npm-cache\_cacache\index-v5\ab\02
npm ERR! errno UNKNOWN
npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/@babel%2fplugin-transform-react-jsx: UNKNOWN: unknown error, mkdir 'C:\Users\HP\AppData\Local\npm-cache\_cacache\index-v5\ab\02'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Local\npm-cache\_logs\2022-07-16T09_58_49_000Z-debug-0.log`**

Could you prioritize, please...Unable to install node modules for any of the new projects

If there is any other way to get rid of that error, please help (Have tried npm cache clean/clear --force, Couldn't delete the npm-cache files manually, even tried deleting individually)

Thank you

_Originally posted by @k-sai-kiranmayee in https://github.com/npm/cli/issues/1785#issuecomment-836289907_

**Comment by wraithgar** [comment]
If you can't delete the files manually from your OS then this is likely not a problem npm can do anything about.

Please also use the new issue template when creating issues.
