### ISSUE TITLE
Error installing express using npm

### ISSUE THREAD

**Issue by ZorRro** [npm/cli#518]
I created a new node project with npm new. Initialized with default values.

While installing 'express' package using command below :
npm install express --save

npm exits with error 
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:

Earlier I was getting 503 Error. Serivce Unavailable for which I followed the steps from
 https://github.com/npm/npm/issues/6841

**Comment by mikemimik** [comment]
Duplicate issue; aggregating into https://github.com/npm/cli/issues/417.
