### ISSUE TITLE
[BUG] `npm outdated -g` not work

### ISSUE THREAD

**Issue by Tarrowren** [npm/cli#5182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`npm outdated -g` no output

```js
// commands/outdated.js
  getEdgesOut (node) {
    // TODO: normalize usage of edges and avoid looping through nodes here
    if (this.npm.global) {
      for (const child of node.children.values()) {
        this.trackEdge(child)
      }
    } 
...
```
`node` is an instance of the `Link` class

```js
// arborist/link.js
class Link extends Node {
...
  // links can't have children, only their targets can
  // fix it to an empty list so that we can still call
  // things that iterate over them, just as a no-op
  get children () {
    return new Map()
  }

  set children (c) {}
}
```
`children` is always empty

### Expected Behavior

output expired packages

### Steps To Reproduce

1. npm i -g typescript@3
2. npm outdated -g

### Environment

- npm: 8.14.0
- Node.js: 16.16.0
- OS Name: win10
- System Model Name:
- npm config:

**Comment by ljharb** [comment]
It’s not supposed to work imo, since there’s no global package.json.

**Comment by wraithgar** [comment]
Global outdated assumes a situation in which you have a `package.json` that is wanting the latest at all times.  It does work for me, I can not reproduce.

```sh
$ nvm use v16.16.0
$ npm i -g npm@8.14.0
$ npm i -g webpack@3
$ npm outdated -g
Package   Current  Wanted  Latest  Location               Depended by
webpack    3.12.0  5.73.0  5.73.0  node_modules/webpack   global
```

**Comment by Tarrowren** [comment]
I found that it was caused by my use of nvs, which creates a symbolic directory link to the node.js directory, causing arb.loadActual() to return ArboristLink instead of ArboristNode.

**Comment by Tarrowren** [comment]
The problem is not solved.
Is it better to disable similar node.js version managers from using symbolic directory links, or is it compatible with them?

**Comment by wraithgar** [comment]
npm treats linked dependencies very differently from real ones, yes.  It is not designed to have global installs be links.
