### ISSUE TITLE
[DOCS] Clear Explanation of `npm build` for versions `6.x` of the CLI

### ISSUE THREAD

**Issue by ColmBhandal** [npm/cli#5185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Problem, not another kind of Docs Problem.

- [X] This is a CLI Docs Problem.

### Observation

The [`6.x` docs for `npm-build`](https://docs.npmjs.com/cli/v6/commands/npm-build) state:

>This is the plumbing command called by npm link and npm install. It should generally be called during installation, but if you need to run it directly, run:
>`npm run-script build`

However, `npm build` and `npm run-script build` have different results. I tested in both `npm@5.6.0` and `npm@6.9.0` and in each case, `npm build` silently succeeded, while `npm run-script build` failed, because it apparently couldn't find the user-defined script `"build"` in `package.json`.

### Expectation

I would not expect advice to run `npm run-script build` in the section on the `npm build`, since it seems to me that `npm run-script build` is simply trying to run a user-defined script called `"build"`.

### References

I have written an answer about this [here](https://stackoverflow.com/a/73025713/5134722). I would be grateful to hear if there is anything incorrect in that answer.

### Potential Solution

Modify the [`6.x` docs for `npm-build`](https://docs.npmjs.com/cli/v6/commands/npm-build) e.g.

1. Describe exactly what `npm build` does in the version 6 CLI instead of vaguely describing it as a "plumbing command". The command is exposed to users of the CLI, so users should know what the command actually does.
1. Describe how `npm build` differs from `npm run-script build`.
1. Give an example usage of `npm build`, or else explain to readers that this probably shouldn't be used directly by them if that's the case.

### Affected URL

https://docs.npmjs.com/cli/v6/commands/npm-build

**Comment by wraithgar** [comment]
In `v6` `npm build` is the code that runs after `npm install` has run. It is a plumbing command and really shouldn't need to be ran on its own.

There is a [docs](https://github.com/npm/cli/tree/v6-docs) branch where you can suggest a change if you want.  `npm build` would be the correct command to run if you somehow needed it (which you shouldn't, as `npm install` and `npm link` do this already).

`v6` is no longer in active maintenance, and only gets security updates as needed.  We highly recommend updating and using the latest npm.

**Comment by ColmBhandal** [comment]
@wraithgar, here is the key question. Why does the documentation conflate `npm run-script build` with `npm run-build`, in the following paragraph?

> It should generally be called during installation, but if you need to run it
> directly, run:
> ```bash
>     npm run-script build
> ```

From what I understand, and based on testing I've done, `npm run-script build` tries to run the _user-defined_ script `build`, even in v6 - so why is this being suggested on the `npm build` CLI command page?

I would happily make an edit to the docs on the branch you suggested, but I am hesitant to make an edit without clarification of this key issue by an npm maintainer who is familiar with the `npm build` command.

---

Agree with the advice to use the latest Node version - and I do - this is just a documentation issue that's confusing people who get mixed up with `npm build` and `npm run-script build`. Unfortunately, many people will be unaware that they have landed on the old v6 docs when they Google search for `npm build` - and may think they're reading the latest `npm` docs - and so confusion ensues - as is clear from SO questions like [this](https://stackoverflow.com/q/49606019/5134722).

**Comment by wraithgar** [comment]
>I would happily make an edit to the docs on the branch you suggested, but I am hesitant to make an edit without clarification of this key issue by an npm maintainer who is familiar with the npm build command.

Yes the suggestion to `run-script` is in error. It should just be `npm build` to rerun the `build` command.
