### ISSUE TITLE
devDependcies are installed when they are peer dependency to one of production dependency

### ISSUE THREAD

**Issue by SergeS** [npm/cli#5203]
Scenario, we have a project, that is using knex package to generate SQL, then we have sqlite3 db for development purposes and oracle database for production.

in package.json there are 

```
    "dependencies": {
        "knex": "^0.21.19",
        "oracledb": "^4.2.0"
    },
    "devDependencies": {
        "sqlite3": "^5.0.2"
    }
```

Both oracledb and sqlite3 are peer dependencies of knex, marked as optional. When i do `npm i` it installs all as expected, problem is with `npm i --omit=dev`

### Expected

`npm i --omit=dev` installs only oracledb package

### Current behavior

`npm i --omit=dev` installs both sqlite3 and oracledb package

```
PS C:\Users\sbrjucha\Git\lde\server> npm --version
8.15.0
```

**Comment by wraithgar** [comment]
`npm` will attempt to install optional dependencies unless specifically told not to. You need to also `--omit=optional` if you don't want optional dependencies installed.

```sh
~/D/n/s/optional $ cat package.json
{
    "dependencies": {
        "knex": "^0.21.19",
        "oracledb": "^4.2.0"
    },
    "devDependencies": {
        "sqlite3": "^5.0.2"
    }
}
~/D/n/s/optional $ npm i --omit=dev --omit=optional
[...]
~/D/n/s/optional $ npm ls sqlite3
optional@ /Users/wraithgar/Development/npm/scratch/optional
└── (empty)

~/D/n/s/optional
```
