### ISSUE TITLE
[FEAT] New --ci option for npm outdated

### ISSUE THREAD

**Issue by khalyomede** [npm/cli#5208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Currently, I am manually checking if my NPM packages are up to date. I run `npm outdated` on my console often. The issue is sometimes I might skip this command, and let in production a version of my app that is not up to date.

I have a CI that runs everytime I push a code on the main branch. Due to the fact that the `npm outdated` command does not a non-zero code if there is outdated package found, it is currently unusable to ensure package are up to date.

### Expected Behavior

A new `--ci` (or `-c`) option, which when enabled will return a non zero code if some outdated packages have been found.

### Steps To Reproduce

1. On a linux-compatible environment
2. Open a terminal on a project with outdated dependencies
3. Run `npm outdated`
4. Run `echo $?`
5. The result is `0`, instead of a non-zero code

### Environment

- npm: 8.13.2
- Node.js: 18.6.0
- OS Name: Ubuntu 22.04
- System Model Name: Custom config
- npm config:
```ini
; node bin location = /usr/bin/node
; node version = v18.6.0
; npm local prefix = /home/node
; npm version = 8.13.2
; cwd = /home/node
; HOME = /root
```

**Comment by fritzy** [comment]
Can you create [an RRFC](https://github.com/npm/rfcs/issues/new?assignees=&labels=&template=rrfc.md&title=%5BRRFC%5D+%3Ctitle%3E) in that repo?
