### ISSUE TITLE
[BUG] npm publish --dry-run For script prepare void

### ISSUE THREAD

**Issue by shinelp100** [npm/cli#5210]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### This is a CLI Docs Problem, not another kind of Docs Problem.

- [X] This is a CLI Docs Problem.

### Description of Problem

npm publish --dry-run For script prepare void

prepare will not run during [--dry-run](https://docs.npmjs.com/cli/v8/using-npm/scripts#npm-publish)

`
"scripts": {
    "jest": "jest",
    "prepare": "npx husky install"
  },
`

node: 16.15.0
npm: 8.5.5

![image](https://user-images.githubusercontent.com/19980132/180353192-d1922c16-7ab7-44f5-b56f-39b085efcbdc.png)

**Comment by fritzy** [comment]
The documentation says that `--dry-run` should not run prepare, but it currently does.

**Comment by jpg619** [comment]
What are the steps to reproduce the issue?

**Comment by wraithgar** [comment]
@jpg619 this is a documentation issue, the docs need to reflect how npm 7 and up do things.
