### ISSUE TITLE
[BUG] install commands without "" could cause problems

### ISSUE THREAD

**Issue by moritztim** [npm/cli#5214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When installing a package like this  `npm i @username/example` certain usernames can cause issues in PowerShell in certain cases. If the username starts with a number and contains a `.` PowerShell will see it as a variable and complain.
Here is an example (sorry it's german, I didn't wanna change my language just for this)
```
In Zeile:1 Zeichen:7
+ npm i @9fv.io/notimplemented-error
Der Splat-Operator "@" kann nicht dazu verwendet werden, auf Variablen in einem Ausdruck zu verweisen. "@9fv" kann nur als Argument für einen Befehl verwendet werden. Wenn Sie auf     
Variablen in einem Ausdruck verweisen möchten, verwenden Sie "$9fv".
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : SplattingNotPermitted
```

### Expected Behavior

On the package page the install field should check for that and use "" to prevent this if the username matches `^[0-9][^\.]*(?:\.).*`, which appears to be the pattern.

### Steps To Reproduce

1. In PowerShell
2. Run `npm i @9fv.io/notimplemented-error` or any package by a user matching `^[0-9][^\.]*(?:\.).*`

### Environment

- npm: `8.15.0`
- Node.js: `v16.11.0`
- PowerShell:
```
  Name                           Value
  ----                           -----
  PSVersion                      5.1.19041.1682
  PSEdition                      Desktop
  PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
  BuildVersion                   10.0.19041.1682
  CLRVersion                     4.0.30319.42000
  WSManStackVersion              3.0
  PSRemotingProtocolVersion      2.3
  SerializationVersion           1.1.0.1
```
- OS Name: Windows 10

**Comment by fritzy** [comment]
Generally, escaping and quoting in the command line is an exercise left for the user, but I see your point about the registry page itself.

**Closing:** this looks to be an issue with the registry which is outside the scope of this repo. For registry support please go to [npmjs.com/support](https://www.npmjs.com/support). If you believe this is a bug with the cli, please provide further clarifying details.

**Comment by moritztim** [comment]
> Generally, escaping and quoting in the command line is an exercise left for the user, but I see your point about the registry page itself.
> 
> **Closing:** this looks to be an issue with the registry which is outside the scope of this repo. For registry support please go to [npmjs.com/support](https://www.npmjs.com/support). If you believe this is a bug with the cli, please provide further clarifying details.

I have been to the support page and found that none of the categories fit:
> -Account or billing issues
-Copyright or trademark data removal
-Dispute a package, org, or username -Report a security issue or abuse
