### ISSUE TITLE
[BUG] cb() never called!

### ISSUE THREAD

**Issue by CCCanna** [npm/cli#522]
# What / Why

> npm install leveldown pouchdb-adapter-leveldb

## When
* Tue 26 Nov 2019 07:08:46 PM CST

## Where

* npm public registry

### Current Behavior

* terminal output like this:
> error cb() never called!
> error This is an error with npm itself. Please report this error at:
> error <https://npm.community>

### Steps to Reproduce

* npm install leveldown pouchdb-adapter-leveldb(has express express-graphql graphql rxdb rxjs preinstalled)

### Expected Behavior

* install successfully.

## Who

* n/a

## References

* n/a

**Comment by CCCanna** [comment]
when install pouchdb-adapter-node-websql the same question raised again.

**Comment by DanielRuf** [comment]
Please provide more details like the npm version.

**Comment by CCCanna** [comment]
[2019-11-26T11_04_28_608Z-debug.log](https://github.com/npm/cli/files/3924678/2019-11-26T11_04_28_608Z-debug.log)
This is the debug log when the problem occurred.
and ```npm version``` outputs:
{
  npm: '6.13.1',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  icu: '64.2',
  llhttp: '1.1.4',
  modules: '79',
  napi: '5',
  nghttp2: '1.39.2',
  node: '13.1.0',
  openssl: '1.1.1d',
  tz: '2019a',
  unicode: '12.1',
  uv: '1.33.1',
  v8: '7.8.279.17-node.19',
  zlib: '1.2.11'
}

**Comment by mikemimik** [comment]
Duplicate issue; aggregating into https://github.com/npm/cli/issues/417.
