### ISSUE TITLE
[BUG] Default value for workspace in config is unclear

### ISSUE THREAD

**Issue by chrisprobably** [npm/cli#5220]
# What / Why
On the config page for 8.x, the default for workspace is completely blank See: https://docs.npmjs.com/cli/v8/using-npm/config#workspace

It looks like this:

> Default:
> Type: String (can be set multiple times)

Other config items are using `null` / `""`. If this is type String, I assume the default should be displayed as  `null` / `""`.

## Where
[https://docs.npmjs.com/cli/v8/using-npm/config#workspace](https://docs.npmjs.com/cli/v8/using-npm/config#workspace)

**Comment by MylesBorins** [comment]
I'm transferring this issue to the CLI repository where these docs are maintained

**Comment by fritzy** [comment]
Just like `diff` `include` and `package`, the internal default is an empty array, but that doesn't make sense from a command line or config file perspective. It's either set to one or more values, or it isn't set at all. What is the actual problem you're trying to solve?

**Comment by chrisprobably** [comment]
I see, thanks for explaining, I can see why it's blank now as `[]` wouldn't really make sense. I thought it was an oversight at first. Since, I think,  `diff` has been like this for ages, it seems likely most people are able to understand the meaning of the empty default.

As a bit of background, I was troubleshooting another tool that wraps npm. This tool, for some unbeknownst (and bizarre) reason, attempts to pass in any config that you don't set with the default values. As I was using a project with no workspaces, it was attempting to pass in `--workspace=[] --workspaces=[]`, which makes no sense. This is why I was interested in confirming the default value.
