### ISSUE TITLE
[BUG] npm update doesn't actually fetch the latest versions of dependencies

### ISSUE THREAD

**Issue by ahmadnassri** [npm/cli#5229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

running `npm update` doesn't update to the `latest` tag.

![image](https://user-images.githubusercontent.com/183195/181420485-198f6065-6442-42d7-9fd7-cf1babaec05e.png)

### Expected Behavior

npm update should update packages to the `latest` tag

### Steps To Reproduce

1. `package.json`
```json
  "devDependencies": {
    "tap": "^15.0.2"
  }
```

2. `npm update`
3. should be updating to `16.3.0`, instead remains at `15.0.2`

### Environment

- npm: 8.3.1
- Node.js: v16.14.0
- OS Name: Ubuntu 20.04
- System Model Name: VM
- npm config:
```ini
; "user" config from /home/ahmad/.npmrc

@[redacted]:registry = "https://npm.pkg.github.com" 
@[redacted]:registry = "https://npm.pkg.github.com" 
//npm.pkg.github.com/:_authToken = (protected) 
//registry.npmjs.org/:_authToken = (protected) 
email = "[redacted]" 
loglevel = "error" 
registry = "https://registry.npmjs.org/" 
```

**Comment by ljharb** [comment]
That’s incorrect; it updates to the latest in-range dependency, and should not update to the latest. To update to the latest, you should explicitly install it as such.

**Comment by ahmadnassri** [comment]
if semver ranges are to be respected by default, then what's the mechanism for getting updates outside of the defined ranges? (without having to `npm install` each one)

also, the docs are not clear on the ranges being a determinate factor, though the examples later in the page do indicate that.

**Comment by ljharb** [comment]
I’d hope there isn’t such a dangerous command as “implicitly install breaking updates” built into npm. You can use something like `npx salita -f && npm install` to do this, as well as other userland modules.

**Comment by wraithgar** [comment]
npm update only updates within the semver constraints of your package and its dependencies, as the docs state.

There is no mechanism to install all of the existing packages in your package.json at a range outside their current spec without redefining that spec (i.e. `npm install a@foo b@bar`).  There are tools like https://github.com/raineorshine/npm-check-updates which attempt to do this for you, but npm does not have such a mechanism.

There is an ongoing discussion in rfcs about how to improve this. https://github.com/npm/rfcs/issues/571

**Comment by darcyclarke** [comment]
As @wraithgar notes, definitely something that's been asked for before & something we could help folks do easily. Here's a one-liner to update direct deps specifically to work around the limitation for now:

```bash
# depends on jq, xargs & printf
npm pkg get dependencies | jq 'keys | join(" ")' | xargs printf "%s@latest " | npm install
```

Updating transitive deps to `@latest` would likely require using another tool afaict & **very likely** break things (again, we can look into adding support for that, although it may be best left to, or mean the dynamic creation of, `overrides` given that you're explicitly asking to break out of the specified dependency ranges & that decision should live somewhere other then just the lockfile &/or `node_modules`)
