### ISSUE TITLE
[BUG] npm 6.13.1 package in requires is not match in this package`s package.lock.json

### ISSUE THREAD

**Issue by crecreek** [npm/cli#523]
Eg: my programme dependent package X
"dependencies": {
   "X": {
        "requires": {
           "A": "^1.0.0"
          }
    },
    "A": "1.0.1"
}
package A is locked 1.0.1 in X's package.lock.json, then I `npm i X@latest` , I saw

"dependencies": {
   "X": {
        "requires": {
           "A": "^1.0.0"
          }
    },
    "A": "1.1.1"
}

but  it did not match the package X's lock.json

**Comment by ljharb** [comment]
package-lock is never published; it's a dev-only lockfile.

You'd need `npm-shrinkwrap.json` to have consumers pick it up, but that can be user-hostile since it prevents deduping.

**Comment by PatrickQuintal** [comment]
I think there is some misunderstanding of what `npm i`does.

It _will touch_ your package.json and package-lock.

Depending on your use case, `npm ci` might be what you want.
