### ISSUE TITLE
[DOCS] Missing flags of npm install and npm ci

### ISSUE THREAD

**Issue by PatrikTrefil** [npm/cli#5232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Problem, not another kind of Docs Problem.

- [X] This is a CLI Docs Problem.

### Description of Problem

Documentation for `npm install` and `npm ci` does not include the `--include`, `--only`, `--no-optional` flags in version 8.x.

- [npm-install](https://docs.npmjs.com/cli/v8/commands/npm-install)
- [npm-ci](https://docs.npmjs.com/cli/v8/commands/npm-ci)

### Potential Solution

Include  `--include`, `--only`, `--no-optional` flags in the documentation.

**Comment by wraithgar** [comment]
`only` and `optional` are deprecated flags and should not be included. `include` is the inverse of `omit` and probably should be included.

**Comment by s100** [comment]
Since it might take a little while to show up in the official documentation, could someone in this issue give an informal explanation of how `--include` works?

**Comment by AKayy2020** [comment]
Historical jeans

**Comment by siemhesda** [comment]
> Since it might take a little while to show up in the official documentation, could someone in this issue give an informal explanation of how `--include` works?

The `--include` option allows for defining which types of dependancies to install.

It is the inverse of `--omit=<type>`.

Dependency types specified i `--include` won't be omitted, regardless of the order in which omit/include are specified.
