### ISSUE TITLE
Issue with deploying app on heroku

### ISSUE THREAD

**Issue by noopur0210** [npm/cli#5235]
### Current Behavior

I'm trying to deploy my phoenix app on heroku. But the following error is showing

-----> Building dependencies
       Installing node modules
npm ERR! Linux 4.4.0-1104-aws
npm ERR! argv "/tmp/build_004bec59/.heroku/node/bin/node" "/tmp/build_004bec59/.heroku/node/bin/npm" "prune"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! path /tmp/build_004bec59/assets/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/tmp/build_004bec59/assets/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/tmp/build_004bec59/assets/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/build_004bec59/assets/npm-debug.log
 !     Push rejected, failed to compile Phoenix app.
 !     Push failed

Not sure what am I doing wrong...

### Expected Behavior

I expect the app to deploy on heroku. This is the [github repo](https://github.com/noopur0210/counter), if anyone wants to see.

### Environment

- `npm -v`: 8.15.1
- `node -v`: 16.14.2
- OS Name: Windows 11

**Comment by ljharb** [comment]
The log says node 6 and npm 3. You may need to update things on heroku’s side.

**Comment by noopur0210** [comment]
> The log says node 6 and npm 3. You may need to update things on heroku’s side.

Yes, I noticed it node 6 and npm 3 by default. How do I make it download the latest versions?
This is supposed to be a phoenix application. So I'm confused, where do I need to put the package.json file, in the root directory or the assets folder?

**Comment by ljharb** [comment]
I’m not sure, but none of this has to do with npm. Perhaps ask heroku support, or whatever phoenix is?

**Comment by wraithgar** [comment]
Closing as this appears to be a heroku issue.
