### ISSUE TITLE
npm audit fix not properly moving directories

### ISSUE THREAD

**Issue by tkiral** [npm/cli#5236]
`npm audit fix` is consistently not correctly moving directories and their associated files and subdirectories. This has meant the only way to proceed is to manually recursively copy then delete from whatever source and target directories that are necessary for the fix. The examples I've come across are for the `acorn-walk`, `acorn-globals` and `babel-loader` projects, but I'm assuming I will come across more as I continue.

**Comment by tkiral** [comment]
Here is a relevant screenshot of the logs that come up when `npm audit fix` is run:

<img width="1290" alt="Screen Shot 2022-07-30 at 07 12 08" src="https://user-images.githubusercontent.com/20247751/181908345-f1aefcc0-bd39-4ff5-846c-dd7c43bd51a7.png">

**Comment by wraithgar** [comment]
Please use the issue template when opening issues.

**Comment by tkiral** [comment]
Noted. Resolved but bug continues when using `--force`. FYI - https://github.com/npm/cli/issues/5254
