### ISSUE TITLE
[BUG] npm view fails with read-only HOME

### ISSUE THREAD

**Issue by adelphes** [npm/cli#524]
Executing a node application using `npm` as an imported library and running the `view` command results in the following error:

> Unhandled rejection Error: EACCES: permission denied, mkdir '/read-only-home-dir/.npm

This happens when the `HOME` environment variable points to a folder which is read-only.

Attempting to run `npm view` results in different errors for the same reason:

> $ HOME=/tmp/rohome npm view react
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /tmp/rohome/.npm
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/tmp/rohome/.npm"

> $ HOME=/tmp/rohome npm view elf-tools
npm ERR! cb() never called!
npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

This is a problem because managed services (AWS lambda, Google Cloud Functions, Azure Functions) typically run node applications in a read-only environment, making the `npm` module difficult to use in these scenarios.

### Reproduction
- Create a new node application, `require('npm')` as a module and call `npm.commands.view()`. If the HOME directory is read-only, the application exits with the unhandled rejection.

Since the view command does not (should not?) alter anything on the local machine, I would expect the command to succeed without needing to write anything to disk.

An obvious workaround in some managed environments is to explicitly set the HOME environment variable to a writable folder (e.g `HOME=/tmp`)

**Comment by mikemimik** [comment]
This is loosely related to https://github.com/npm/cli/issues/417. Though the solution for this should be to update to the most recent version of `npm`.

I'm going to close this issue, but if there are other points, please feel free to comment here, or in #417 :)
