### ISSUE TITLE
[DOCS] How to specify a <package-spec> for the `prepare` script to match `publish`.

### ISSUE THREAD

**Issue by nspaeth** [npm/cli#5265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Enhancement, not another kind of Docs Enhancement.

- [X] This is a CLI Docs Enhancement.

### Description of Problem

The `npm publish` command allows for a `<package-spec>` parameter so that you could, for example `npm publish ./dist`.

This works fine for directly publishing to npm: `npm install <pkg>` installs the `dist` folder as the package into your `node_modules`. 

On the other hand, if you use `npm install github:me/repo`, it isn't clear how to let npm know that the `./dist` folder is what should be installed after the `prepare` script is run.

### Potential Solution

I don't know. The only thing I can think of is maybe using `workspace`, but it isn't clear how that would interact when the `./dist` package has the same name as the root source package.

### Docs URL

docs/content/commands/npm-install.md

**Comment by wraithgar** [comment]
Installing complex git repos that have build scripts AND have their package in a separate folder is not currently supported.  We do plan on eventually supporting git repos that have their package in a subdirectory, but not the combination of the two (i.e. running build from one directory and having the installed package be in a separate one).
