### ISSUE TITLE
[BUG] npm v8 does not publish the version specified in package.json

### ISSUE THREAD

**Issue by geyuqiu** [npm/cli#5266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Currently after angular update (12->14 and 14->18 for nodejs ), there seems to be a bug in the latest version of npm, which causes that an already existing (in our case always the "Latest") version of an angular application is uploaded on nexus, although in the package.json another higher version is entered. Due to the security setting that already existing artifactory versions must not be overwritten on nexus, the upload is NOT executed in the end.

Therefore, we fixed that temporarily by reseting from NPM8 (18.X.X) back to NPM6 (14.X.X). (At the same time, we have to change the angular/cli version from 14.0.5 to 12.2.15 because of the deprecated --prod flag and non ivy mode publish). 

### Expected Behavior

the version in package.json should be published

### Steps To Reproduce

```
# update angular from 12 to 14 and nodejs from 14 to 18
npx ng build
npm publish --registry registry-url project-name
```

### Environment

- npm: 8.x.x
- Node.js: 18.5.0
- OS Name: windows
- System Model Name: windows vm
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by alasdairhurst** [comment]
By passing `project-name` to `npm publish` you're essentially ignoring the project in the current directory and telling it to publish `project-name`(@latest) from the registry. https://docs.npmjs.com/cli/v8/commands/npm-publish

It should work if you leave off the name of the package - `npm publish --registry registry-url` or, if you're in a different directory to the project, provide an explicit path to the directory that contains the package.json for the project you want to publish, - `npm publish --registry registry-url ./project-name`

**Comment by wraithgar** [comment]
As @alasdairhurst said, giving `npm publish` a name will tell npm to interpret that as a package spec to download and install.  Omit that if the current directory contains what you want to publish, or use a path  (i.e. prefix with `./` or `/`).
