### ISSUE TITLE
[BUG] npm config does not allow `path` types to use ${ENVIRONMENT_VARIABLE} syntax.

### ISSUE THREAD

**Issue by alasdairhurst** [npm/cli#5267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I'm trying to configure a project using the command line by setting a custom registry and CA file. The project will be built in a docker container, so all configuration should be configured relative to the project, and nothing from the host should be referenced.

Since npm automatically turns the relative paths into absolute paths when setting cafile, let's try an use an environment variable as documented here: https://docs.npmjs.com/cli/v7/configuring-npm/npmrc
```
npm config set cafile='\${PWD}/cafile.crt' --location=project
```
This results in the bug:
```.npmrc
cafile=/absolute/path/to/project/${PWD}/cafile.crt
```

**This is also an issue without setting `location`**

### Expected Behavior

I expect
```
npm config set cafile='\${PWD}/cafile.crt'
```
To write:

```.npmrc
cafile=${PWD}/cafile.crt
```

### Steps To Reproduce

1. run `npm config set cafile='\${PWD}/cafile.crt'`
2. see that unexpected data is written to .npmrc

### Environment

- npm: 8.16.0
- Node.js: 16.14.2
- OS Name: MacOS Big Sur
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by KAZI-SAMIR** [comment]
I have used this command `npm config set cache ~/.npm/_cacache/tmp/ --global` 
and faceing this  
[Problem ](https://stackoverflow.com/questions/73176664/npm-cli-showing-nothing) 
:(

**Comment by wraithgar** [comment]
This affects all config items with a `path` type

```sh
~/D/n/cli (gar/exec-directory|✔) $ node . config set cache "\${PWD}/.cache"
~/D/n/cli (gar/exec-directory|✔) $ grep cache ~/.npmrc
cache=/Users/wraithgar/Development/npm/cli/${PWD}/.cache
```

**Comment by wraithgar** [comment]
Fixed by https://github.com/npm/cli/pull/6328

```sh
~ $ npm config set cache "\${PWD}/.cache"
~ $ grep cache ~/.npmrc
cache=${PWD}/.cache
```
