### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by 4i8** [npm/cli#5270]
The first suggestion is to add a command to update readme without the need to change the version like:
```sh-session
npm update readme 
```
The second suggestion, which is the most important, is publishing. The question should be asked: Do you want to publish the package or not? It is necessary because sometimes you may write the order by mistake and make your project public.

**Comment by ljharb** [comment]
That first one would require massive registry changes, and should go in npm/feedback.

The second one is solved by adding private:true to your package.json.

**Comment by 4i8** [comment]
Solution for the first suggestion:
Allow to modify the README via the site or in the case of the README it only performs a fake update and does not require modifying the version number or adding a new property in package.json 
```json
"readme ":"<Repository Link >"
``` 
The file is get from repositories from GITHUB and if updated in github, it will be updated automatically in npm

**Comment by wraithgar** [comment]
Changes to the cli need to go through the [rfc process](https://github.com/npm/rfcs)
