### ISSUE TITLE
[BUG] `npm install package.with.dots another.with.dots` incorrectly errors

### ISSUE THREAD

**Issue by ljharb** [npm/cli#5271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```sh
npx npm@latest install --save array.prototype.group array,prototype.grouptomap
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "array,prototype.grouptomap" of package "array,prototype.grouptomap": Tags may not have any characters that encodeURIComponent encodes.
```

### Expected Behavior

The two packages are installed.

### Steps To Reproduce

node 18.7, mac, standard config, run the npx command above.

### Environment

- npm: 18.16
- Node.js: 18.7
- OS Name: Mac
- System Model Name: N/A
- npm config: N/A
```ini
; "user" config from $HOME/.npmrc

//registry.npmjs.org/:_authToken = (protected) 
init-author-email = (redacted)
init-author-name = "Jordan Harband" 
init-license = "MIT" 
init-version = "0.0.0" 

; "project" config from $PWD/.npmrc

package-lock = false 

; node bin location = $NVM_DIR/versions/node/v18.7.0/bin/node
; node version = v18.7.0
; npm local prefix = $PWD
; npm version = 8.15.0
; cwd = $PWD
; HOME = /Users/ljharb
; Run `npm config ls -l` to show all defaults.

; "publishConfig" from $PWD/package.json
; This set of config values will be used at publish-time.

ignore = ["!browser.js",".github/workflows"]
```

**Comment by shadowspawn** [comment]
NB: there is a comma rather than a dot in the second package name: `array,prototype.grouptomap`

Changing that to a dot leads to a successful install when I tried reproducing.

**Comment by ljharb** [comment]
oh lol, thanks, pebcak
