### ISSUE TITLE
[BUG] dependences not install before prepare 

### ISSUE THREAD

**Issue by liudonghua123** [npm/cli#5277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I want to install a github package via npm, I use `npm i  --production=false --verbose -g liudonghua123/javascript-deobfuscator#test`, and the package.json contains a `prepare: tsc` script, but the installation seems failed with `Cannot find module 'shift-ast' or its corresponding type declarations. ...`

### Expected Behavior

The prepare script run after the dependences installed.

### Steps To Reproduce

1. Run `npm i  --production=false --verbose -g liudonghua123/javascript-deobfuscator#test`
2. See error...

### Environment

- npm: 8.16.0
- Node.js: 18.1.0
- OS Name: Microsoft Windows [Version 10.0.22000.832]
- System Model Name:
- npm config:
```ini
; "user" config from C:\Users\Liu.D.H\.npmrc

//registry.npmjs.org/:_authToken = (protected)
ELECTRON_MIRROR = "https://cdn.npm.taobao.org/dist/electron/"
msvs_version = "2022"
node_gyp = "C:\\Users\\Liu.D.H\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js"
prefix = "C:\\Users\\Liu.D.H\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v18.1.0
; npm local prefix = C:\Users\LIUD~1.H\AppData\Local\Temp
; npm version = 8.16.0
; cwd = C:\Users\LIUD~1.H\AppData\Local\Temp
; HOME = C:\Users\Liu.D.H
; Run `npm config ls -l` to show all defaults.
```

**Comment by wraithgar** [comment]
https://github.com/npm/cli/issues/4148
