### ISSUE TITLE
[BUG] Regression in 8.13.0 on Windows: `echo 5%` prints just `5` instead of `5%`

### ISSUE THREAD

**Issue by lydell** [npm/cli#5285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```
$ npm test

> test
> echo 5%

5
```

This happens since 8.13.0.

### Expected Behavior

```
$ npm test

> test
> echo 5%

5%
```

8.12.2 prints `5%` as expected.

### Steps To Reproduce

1. Use Windows
2. With this package.json:

   ```json
   {
     "private": true,
     "scripts": {
       "test": "echo 5%"
     }
   }
   ```

3. Run `npm test`
4. Notice how the percentage sign is gone.

### Environment

- npm: 8.16.0
- Node.js: 18.7.0
- OS Name: Windows 10
- System Model Name: PC

**Comment by simplesmiler** [comment]
Can confirm, stumbled upon it with different scenario:

```
# npx echo-cli Привіт

╨Я╤А╨╕╨▓╤Ц╤В
```

OS: Windows 10 with English locale.

**Comment by nlf** [comment]
this should work correctly as of npm@8.17.0, but please do reopen the issue if you can still reproduce it

**Comment by lydell** [comment]
Amazing!

For the curious following along, this was the fix I think: https://github.com/npm/run-script/pull/98
