### ISSUE TITLE
[BUG] npm ERR! Windows_NT 10.0.22000 | npm -v3.10.8 | node -v6.9.1

### ISSUE THREAD

**Issue by Beckdotan** [npm/cli#5287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Enhancement, not another kind of Docs Enhancement.

- [X] This is a CLI Docs Enhancement.

### Description of Problem

0

I got to work on an old program. I installed node 6.9.1 (with npm v3.10.8) using nvm because it was probably the last node version that i know this code was working with (and it solved me like a 10000 different errors while trying to run it).

I'm working on windows 11 system.

while try to run the code using:
 npm install -g node-gyp
(with python 310 or 27 - doesnt make difference)

in the repo clone folder I got this message:

npm ERR! Windows_NT 10.0.22000
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "node-gyp"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code EPROTO
npm ERR! errno EPROTO
npm ERR! syscall write

npm ERR! write EPROTO 101057795:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:openssl\ssl\s3_clnt.c:2010:
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\dotan\Desktop\ECO-OS\ecoos\npm-debug.log
Expand snippet

I looked at the internet and found few solutions, non of them worked so far. I ran:

npm i node-gyp 
and got the same error I ran:

 npm install -g npm
and got the same error

I ran:

npm cache clean --force
and didn't got error but got the same message when it tried to do npm install again. (so it didnt help)

I would love to know if you have a different solution for it.

### Potential Solution

IDK

**Comment by wraithgar** [comment]
Older versions of node/npm use ssl versions that are no longer supported by the npm registry. You will not be able to use them to access the npm registry.  Your only solution is to update node and npm.

Additionally, node 6 was EOL in 2019 and neither it nor npm@3 are supported anymore.

**Comment by Kcud** [comment]
> Older versions of node/npm use ssl versions that are no longer supported by the npm registry. You will not be able to use them to access the npm registry. Your only solution is to update node and npm.
> 
> Additionally, node 6 was EOL in 2019 and neither it nor npm@3 are supported anymore.

My npm version 3.10.10 node version 14.17.3 operating system is windows11 (version Windows 11 Home Chinese version
Version 21 h2 Operating system version 22000.978)
The following error occurred when downloading using npm

npm ERR! Windows_NT 10.0.22000
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_global\\node_modules\\npm\\bin\\npm-cli.js" "install" "webpack" "-g"
npm ERR! node v14.17.3
npm ERR! npm  v3.10.10

npm ERR! cb.apply is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by Kcud** [comment]
> Older versions of node/npm use ssl versions that are no longer supported by the npm registry. You will not be able to use them to access the npm registry. Your only solution is to update node and npm.
> 
> Additionally, node 6 was EOL in 2019 and neither it nor npm@3 are supported anymore.

I'm gonna run npm config set prefix "folder path"
npm config set cache "folder path" reset the path of the two folders
