### ISSUE TITLE
[DOCS] How to pull packages from registry instead symlink in workspace

### ISSUE THREAD

**Issue by fjodor-rybakov** [npm/cli#5290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Problem, not another kind of Docs Problem.

- [X] This is a CLI Docs Problem.

### Description of Problem

For example there is following workspaces:

```
apps
  pkg1
  pkg2
package-lock.json
```

pkg1 depends of pkg2, pkg2 is in npm registry. When i run `npm i` npm create symlink for pkg2. 

We need option for pull all local packages from registry instead symlink in workspace. 

### Potential Solution

Yarn berry has `enableTransparentWorkspaces` option for solve this problem

**Comment by wraithgar** [comment]
This would be a net new feature and would need to go through the rfc process https://github.com/npm/rfcs
