### ISSUE TITLE
[BUG] npm@6.13.1: TypeError: mkdirp is not a function

### ISSUE THREAD

**Issue by charbelsako** [npm/cli#530]
# What / Why

> n/a

## When

* Every time I run npm to do anything. This bug occurs

## Where

* with npm itself

### Current Behavior

* Throws an error **TypeError: mkdirp is not a function**

### Steps to Reproduce

* I updated to 6.13.1 and now it happens. This might be only happening to me.

Here is an image of what is happening. This happened with someone else on stackoverflow but he was running on windows. I have a kde neon.

![2019-11-27-193352_1366x768_scrot](https://user-images.githubusercontent.com/26299987/69746421-e6778280-114c-11ea-8cfb-129331f57111.png)

**Comment by ljharb** [comment]
What version of node? fs.mkdirp was added in a more recent version.

**Comment by charbelsako** [comment]
Was using node@10.x
switched to version 12
Silly me.

**Comment by ljharb** [comment]
This may need to be reopened; that implies that npm 6.13.1 is incompatible with node 10, which is still under LTS.

cc @ruyadorno @darcyclarke

**Comment by ruyadorno** [comment]
tracing that line of code from the screenshot, it's from a consumed library (`gentle-fs`) so I don't think it has to do with `fs.mkdirp`, I just give the cli a spin in `node@10` and everything works as expected (also, on that note the CI tests runs in all supported versions of node so such an error would be unlikely to occur) but still, the fact that it happened to more than one person could indicate something went wrong somewhere.

@charbelsako you mentioned you had just updated to `npm@6.13.1`, how did you updated?

**Comment by charbelsako** [comment]
Sorry, I forgot to post my solution. 
I had accidentally changed my version of node using the `n` package.

Changing it back fixed it.
@ruyadorno

**Comment by charbelsako** [comment]
@ruyadorno `sudo npm i -g npm` running on kde plasma
