### ISSUE TITLE
code E403 forbidden - angular cli

### ISSUE THREAD

**Issue by Simkiw** [npm/cli#5312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I have installed node + npm via nvm-windows

**node -v : 16.17.0**  
**npm -v : 8.15.0**

And when I try to install angular cli via npm like :  **npm install -g @angular/cli**

_npm ERR! code E403
npm ERR! 403 403 Forbidden - GET https://registry.npmjs.org/@angular%2fcli
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to._

The same happens if I try to install a different version of npm  

_npm install -g npm
npm ERR! code E403
npm ERR! 403 403 Forbidden - GET https://registry.npmjs.org/npm
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to._

**What I tried**
To use different version of node. I've also tried one of the proposed solution found on the internet (setting the config registry to http). As a matter of fact, I could access _https://registry.npmjs.org/@angular%2fcli_. I find it weird npm cannot access it.

### Expected Behavior

Install the angular cli and start running angular commands such as **ng --version**

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 8.15.0
- Node.js: 16.17.0
- OS Name: Windows 10 Pro
- System Model Name:
- npm config:
```ini
; "user" config from C:\Users\<usrX>\.npmrc

@corporate:registry = "<corporate registry>"
//<corporate registry>/repository/app-services-npm/:_authToken = (protected)
https-proxy = "<corporate proxy>"
proxy = "<corporate proxy>"
registry = "https://registry.npmjs.org/"

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v16.17.0
; npm local prefix = C:\Users\<usrX>\WhateverRepo
; npm version = 8.15.0
; cwd = C:\Users\<usrX>\WhateverRepo
; HOME = C:\Users\<usrX>
```

**Comment by Simkiw** [comment]
https://github.com/npm/cli/issues/805#issuecomment-586962141 
Removing the proxy lines solved the issue. But i don't know if there is a better way to make things work by keeping the proxy in the config?

**Comment by wraithgar** [comment]
That is an error that your private registry is giving, it is unrelated to the npm cli itself.  You have to either bypass it (remove the `proxy` config) or get whoever manages your private registry to allow it.
