### ISSUE TITLE
[BUG] npx does not get latest version

### ISSUE THREAD

**Issue by jurgensweere** [npm/cli#5313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When using npx `<test-package>` it does not get the latest version, if that is available.

### Expected Behavior

running npx `<test-package>` always takes the latest version available

### Steps To Reproduce

1. `npx <test-package>`
2. publish a new version of `<test-package>`
3. `npx <test-package>`

The same issue was marked resolved here: https://github.com/npm/cli/issues/2329

The steps there to mark it as fixed do work:
```
~/D/npm $ npx tap@15.0.8 -v
Need to install the following packages:
  tap@15.0.8
Ok to proceed? (y) 
15.0.8
~/D/npm $ npx tap -v
Need to install the following packages:
  tap
Ok to proceed? (y) 
15.0.9
```

However, if you would publish a newer version of tap (in this case) it would still use 15.0.9 instead of 15.0.10 or newer

### Environment

- npm: 8.17.0
- Node.js: 16.16.0
- OS Name: MacOS
- System Model Name: Macbook Pro M1
- npm config:
```ini
//localhost:4873/:_authToken = (protected) 
registry = "http://localhost:4873/" 

; node bin location = /Users/jurgensweere/.nvm/versions/node/v16.16.0/bin/node
; node version = v16.16.0
; npm local prefix = /Users/jurgensweere/tmp/test
; npm version = 8.17.0
; cwd = /Users/jurgensweere/tmp/test
; HOME = /Users/jurgensweere
; Run `npm config ls -l` to show all defaults.
```
- Using Verdaccio registry to do test publishing

**Comment by wraithgar** [comment]
This is how npx/npm exec works.  If you do not give a spec (i.e. a tag like `latest` or a semver version/range) npx will use any version of a given package that it already finds.  If you want to always ensure that it checks for the latest version you need to specify `npx tap@latest`
