### ISSUE TITLE
[BUG] Able to remove all optional transitive peerDependencies?

### ISSUE THREAD

**Issue by broksonic21** [npm/cli#5326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

npm install --omit=optional won't remove transitive optional peerDependencies (i.e. dependencies who have peerDependenciesMeta field, paired with { "optional": true } for other dependencies) that happen to be in your package-lock.json for legacy reasons.

Is there a way to get npm install to remove all such packages without deleting package-lock.json/node-modules and starting over (and thus updating various packages you might not want to)

### Expected Behavior

Some documented way to do this.

### Environment

- npm: 8.15
- Node.js: 16.16.0
- OS Name: Mac

**Comment by ljharb** [comment]
Perhaps `npm prune --only=optional`?

**Comment by broksonic21** [comment]
Checking back in here - is there a newer way to do this? that CLI, which I can't remember if it worked for this use case, doesn't work now at all, but I have a need for cleaning up optional dependencies again, so circling back on this

```
> npm prune --only=optional
npm warn invalid config only="optional" set in command line options
npm warn invalid config Must be one of: null, prod, production
```
