### ISSUE TITLE
[BUG] `npm pkg delete` can't delete keys containing a dot `.`

### ISSUE THREAD

**Issue by tschersach** [npm/cli#5333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Running something like `npm pkg delete dependencies.'ngraph.graph'` doesn't delete the key.

### Expected Behavior

I can delete keys containing dots with `npm pkg delete`

### Steps To Reproduce

In a package.json where `ngraph.graph` is installed
```
"ngraph.graph": "20.0.0",
"ngraph.path": "1.4.0",
```
 running `npm pkg delete dependencies.'ngraph.graph'` results 
```

"ngraph": {},
"ngraph.graph": "20.0.0",
"ngraph.path": "1.4.0",
```

I tried escaping the dot with some `\` but nothing did it.

### Environment

- npm: 8.15.0
- Node.js: v18.7.0
- OS Name: macOs Monterey 12.3
- System Model Name: MacBookPro M1
- npm config:
```ini
; "user" config from /Users/tirke/.npmrc

init-author-name = "Thomas"
init-author-url = "https://github.com/Tirke"
init-license = "MIT"
init-version = "0.0.0"

; "project" config

auto-install-peers = true
strict-peer-dependencies = false

; node bin location = /Users/tirke/Library/Application Support/fnm/node-versions/v18.7.0/installation/bin/node
; node version = v18.7.0
; npm local prefix = /Users/tirke/isolated/monorepo
; npm version = 8.15.0
; cwd = /Users/tirke/isolated/monorepo
; HOME = /Users/tirke
; Run `npm config ls -l` to show all defaults.
```

**Comment by wraithgar** [comment]
Please note that the `dependencies` entry is not meant to be edited with `npm pkg`.  Editing your dependencies by hand is not suggested, instead use `npm uninstall`.

If you do want to interact with other entries in your package.json with dot notation you will have to use `[]` notation:

```sh
~/D/n/s/a $ npm pkg get scripts
{}
~/D/n/s/a $ npm pkg set scripts\[foo.bar\]=baz
~/D/n/s/a $ npm pkg get scripts
{
  "foo.bar": "baz"
}
~/D/n/s/a $ npm pkg delete scripts\[foo.bar\]
~/D/n/s/a $ npm pkg get scripts
{}
```

This does also work on dependencies but again it is not advised

```sh
~/D/n/s/a $ npm pkg get dependencies
{
  "foo.bar": "*"
}
~/D/n/s/a $ npm pkg delete dependencies\[foo.bar\]
~/D/n/s/a $ npm pkg get dependencies
{}
```

**Comment by tschersach** [comment]
Thanks wraithgar :)
