### ISSUE TITLE
[BUG]When I introduce "npm" in js by means of commonJs or ESM, it results in the following error

### ISSUE THREAD

**Issue by wangrongding** [npm/cli#5427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When I introduce "npm" in js by means of commonJs or ESM, it results in the following error
```js
import npm from "npm";
// or
const npm = require("npm");
```
Are there any alternatives? Is it only possible to downgrade to 7.x.x ?
Hope to get your reply, thanks! 💖
<img width="752" alt="image" src="https://user-images.githubusercontent.com/42437658/186873742-8d561e3e-25f1-4bbc-af3a-5efd44fe5571.png">

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 8.11.0
- Node.js: v16.16.0
- OS Name: MacOS
- System Model Name: Macbook Pro
- npm config:
```ini
; "user" config from /Users/wangrongding/.npmrc

//registry.npmjs.org/:_authToken = (protected) 
; registry = "https://registry.npm.taobao.org/" ; overridden by project

; "project" config from /Users/wangrongding/Coding/prm-cli/.npmrc

registry = "https://registry.npm.taobao.org/" 

; node bin location = /usr/local/bin/node
; node version = v16.16.0
; npm local prefix = /Users/wangrongding/Coding/prm-cli
; npm version = 8.11.0
; cwd = /Users/wangrongding/Coding/prm-cli
; HOME = /Users/wangrongding
; Run `npm config ls -l` to show all defaults.
```

**Comment by ljharb** [comment]
The message tells you what’s going on - there’s no programmatic API, so there’s nothing to require or import.

The proper way to use npm from code is to shell out to it - the API hasn’t been supported since npm 3.
