### ISSUE TITLE
Markdown duplicate reference links are not working

### ISSUE THREAD

**Issue by alfawal** [npm/cli#5432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Problem, not another kind of Docs Problem.

- [X] This is a CLI Docs Problem.

### Description of Problem

Visiting [this page](https://docs.npmjs.com/cli/v8/configuring-npm/package-json), there are 2 "description" sections, using the reference #description with a link will point to the first description section [link](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#description).

You cannot copy a link to the "description" package.json file field.
The right side indexing panel shows it as "#description-1" ([link](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#description-1)) but it wont redirect the user to that section since its labeled as "description" for some reason.

### Potential Solution

GitHub supports the *-1 indexing method, it should be implemented similarly, or just tweak with the markdown file.

### Affected URL

https://docs.npmjs.com/cli/v8/configuring-npm/package-json#description-1

**Comment by ahtee** [comment]
`description` here is working fine and as intended as the second "description" is all lowercase and referring to the available object key named `description` where the lowercase term there is used in describing packages automatically in the https://www.npmjs.com repositories.
 
example: https://github.com/jquery/jquery/blob/main/package.json and check the "description" key in the json object.

**Comment by wraithgar** [comment]
This is a bug w/ the documentation site itself, not w/ the npm cli https://github.com/npm/documentation/issues/34
