### ISSUE TITLE
I have a question about NPM dependency management

### ISSUE THREAD

**Issue by tonycody** [npm/cli#5440]
NPM essentially does component dependency management, which is a similar tool to Java Maven, Gralde, and GO.

But why is the package version of the NPM project installed for each project in the node_modules folder local to the current project?

Why can't you centrally manage a local folder like Maven and Gradle? Unrelated to the project?

For example: the version of Axios 0.27.2, which may be used in Project A, is also used in project B, and is currently located at:
A/node_modules/axios - 0.27.2
B/node_modules/axios - 0.27.2

Why not?

~/.npm/node_modules/axios

**Comment by ljharb** [comment]
You’re describing the approach used by pnpm and yarn PnP, but npm doesn’t do this by default or historically because you’re supposed to be able to make local edits to one project’s dependencies for debugging, without affecting other projects’ dependencies.

**Comment by tonycody** [comment]
> You’re describing the approach used by pnpm and yarn PnP, but npm doesn’t do this by default or historically because you’re supposed to be able to make local edits to one project’s dependencies for debugging, without affecting other projects’ dependencies.

The java / go project also has the ability to debug the current project locally, but it doesn't affect it. 
You can learn from the relevant dependency package management design.

**Comment by ljharb** [comment]
Not just to move through it with a debugger - to *edit it on disk* so that multiple runs of the program use your edits.

**Comment by frank-dspeed** [comment]
I guess this can be closed what my frind @ljharb trys to explain is the following the other mentioned languages are pre compiled once like java and go when you add a package to a project you will mostly not change them. The @isaacs how ever for any reason was thinking hey. ECMAScript is text so lets edit and publish node_modules directly.

when you would only import and extend modules like you should do the yarn pnpm method is the correct one. 

if you plan to do npm install cd node_modules do all kind of edits and then publish that edits some where npm is the right thing to do.

## Workaround with npm

```
npm i -g my-package # global install to npm prefix something like ~/......
cd project 
npm link my-package # linking from global npm prefix
```

**Comment by fritzy** [comment]
@tonycody Thanks for filing this! This is currently working as intended, and any suggested changes would be best suited as [an RRFC](https://github.com/npm/rfcs/issues/new?assignees=&labels=&template=rrfc.md&title=%5BRRFC%5D+%3Ctitle%3E)
