### ISSUE TITLE
[BUG] npm view --json command returns not only JSON if failed

### ISSUE THREAD

**Issue by ThePlenkov** [npm/cli#5444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

**Use case**

I have a monorepo with workspaces. Each workspace gets published to a separate package. In CI pipeline I want to check whether is module needs to be published or no. So to make a central decision which packages I need to publish I would love to know what are the most recent published versions. So what I do I run such a command `npm view -ws --json` to have a common list of published packages. In case if I add one more package which is not yet published - I get an error `npm ERR! 404 Not Found`

### Expected Behavior

For a single request it makes sense - for a bulk mode - I would prefer to have this error as a part of json payload. 

It's ok to have an additional flag to indicate that behavior.

Do you think is possible?

Thank you! 

### Steps To Reproduce

1. Create a new monorepo with couple workspaces
2. Publish them
3. Add a new workspace
4. Run `npm view -ws --json`

### Environment

- npm: 8.12.1
- Node.js: v18.4.0

**Comment by ljharb** [comment]
Can you try with npm v8.18?

**Comment by ThePlenkov** [comment]
of course . Result is same.  Actually I thought - it looks like the issue is in `view --json` command itself. It would be nice if on the error in json mode it would react with json payload, not log

**Comment by lukekarrys** [comment]
@ThePlenkov Thanks for the report. I'm tracking a few issues with `json` output (ref: https://github.com/npm/cli/issues/4724) and will add this to the list.

Is it ok to recharacterize this issue as only to do with the json payload? I would expect `npm -ws` to fail as you said if any of the workspaces are missing.

**Comment by ThePlenkov** [comment]
@lukekarrys  I totally agree. If `npm view --json -ws` will fail with json containing responses for all workspaces - that would be just perfect! Exit code is correct
