### ISSUE TITLE
[BUG] error Couldn't find any versions for "libnpmversion" that matches "^3.0.7" 

### ISSUE THREAD

**Issue by San-Shui** [npm/cli#5453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

error Couldn't find any versions for "libnpmversion" that matches "^3.0.7" 
<img width="530" alt="image" src="https://user-images.githubusercontent.com/20311239/187831530-f91ca877-c4b2-48d2-80a6-1f20cb768bcc.png">
<img width="823" alt="image" src="https://user-images.githubusercontent.com/20311239/187831552-0aae0008-9b05-4bd3-bd07-2def07f49c43.png">

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by dcroote** [comment]
We're seeing this cause Docker build failure in CI: https://github.com/api3dao/airnode/runs/8127741866?check_suite_focus=true#step:4:94

**Comment by seanjb** [comment]
Looks like this commit, bumped the version number for libnpmversion ^3.0.1 to ^3.0.7 https://github.com/npm/cli/commit/44bfedc22ee11de461eeffa030d30bea921bb0ca#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519
3.0.7 does not exist on the public NPM registry. This is causing a lot of downstream build failures for our projects.

**Comment by nadimdiazramzi** [comment]
Same here, massive impact, can we get an update please? All our pipelines are dead for the past 6 hrs.

**Comment by Esonhugh** [comment]
Also Get my CICD down

**Comment by zcoding** [comment]
+1

**Comment by AsidStorm** [comment]
Reproduced for us with semantic-release today.

Dockerfile for reproduce

```
FROM node:16.13.0 as build
CMD yarn global add semantic-release
```

Will try to downgrade semantic-release to 8.0.3 (which have lower npm version dependency) in few hours, if not be fixed.

**Comment by existe-deja** [comment]
If you use yarn, adding this to your `package.json` does the trick.

```
"resolutions": {
    "libnpmversion": "3.0.6"
}
```

**Comment by Esonhugh** [comment]
Change your Npm version at
```
"npm": "8.18.0"
```
also fix
and waiting for new the upgrade.

**Comment by joundy** [comment]
+1

**Comment by camfou** [comment]
+1

**Comment by lukekarrys** [comment]
Thanks for the report. This was the case of a mis-run command by me while documenting a new release process for us yesterday. I've manually published this missing version and updated our release process to ensure it doesn't happen again.

```sh
❯ npm view libnpmversion

libnpmversion@3.0.7 | ISC | deps: 5 | versions: 27
library to do the things that 'npm version' does
https://github.com/npm/cli#readme

...

dist-tags:
latest: 3.0.7

published just now by lukekarrys
```
