### ISSUE TITLE
[BUG] package install with npm8 fails with .npmrc containing org registry

### ISSUE THREAD

**Issue by pierreroth64** [npm/cli#5460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

## Description

I made a public repo to reproduce the issue: https://github.com/pierreroth64/registry-test
The README files contain the steps to reproduce the installation issue with npm@8 with an .npmrc file for our organization.

## Reproduction Steps

This works (`npm6` branch):

```
git checkout npm6
nvm use
npm --version // <- should return npm 6 such as 6.14.15
rm -rf node_modules && npm install <- works :)
```

This does **NOT** work (`npm8` branch):

```
git checkout npm8
nvm use
npm --version // <- should return npm 8 such as 8.11.0
rm -rf node_modules && npm install // <- does not work :(
```

The console output:

```
npm ERR! code E405
npm ERR! 405 Method Not Allowed - GET https://npm.pkg.github.com/eove/@types/react/-/react-17.0.49.tgz
```

There's a strange "eove" in the url... ?!
The only difference between the two branches `npm6` and `npm8` is the content of `.nvmrc` to be able to select between v8 or v6 easily.

### Environment

- npm: v8.11.0
- Node.js: v16.15.1
- OS Name: MacOS Monterey
- System Model Name:
- npm config:
```ini
; "user" config from /Users/peio/.npmrc

//npm.pkg.github.com/:_authToken = (protected)
//registry.npmjs.org/:_authToken = (protected)

; "project" config from /Users/peio/Work/eove/registry-test/.npmrc

registry = "https://npm.pkg.github.com/eove"

; node bin location = /Users/peio/.nvm/versions/node/v16.15.1/bin/node
; node version = v16.15.1
; npm local prefix = /Users/peio/Work/eove/registry-test
; npm version = 8.11.0
; cwd = /Users/peio/Work/eove/registry-test
; HOME = /Users/peio
; Run `npm config ls -l` to show all defaults.
```

**Comment by pierreroth64** [comment]
Here's another error from another repo (also containing a `.npmrc` to point to our organization):

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://npm.pkg.github.com/eove/electron-to-chromium/-/electron-to-chromium-1.4.240.tgz
npm ERR! 404
npm ERR! 404  'electron-to-chromium@https://npm.pkg.github.com/eove/electron-to-chromium/-/electron-to-chromium-1.4.240.tgz' is not in this registry.
```

Again, `electron-to-chromium` is a public one and has nothing todo with our `eove` org namespace...

**Comment by wraithgar** [comment]
`registry = "https://npm.pkg.github.com/eove"` That tells npm to download everything from your private registry, which doesn't have public packages in it.

I assume what you're wanting is to only download packages of a given scope from there, in which case you'll want to tell npm this w/ a scoped registry config

`@OWNER:registry=https://npm.pkg.github.com`

where `@OWNER` is your scope.

More info can be found at https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry
