### ISSUE TITLE
[BUG] Lack a way to specify files as source for client key and client cert

### ISSUE THREAD

**Issue by krzyk** [npm/cli#5464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

There is no way to specify the files that contain client key and client certificate (just strings containing those).

### Expected Behavior

`kafile` and `certfile` (similar to current `cafile`) that point to client key and client certificate.

It is quite common to have those as files and copy pasting them into `.npmrc` is cumbersome and requires repeating it with each refresh of certificates.

### Steps To Reproduce

There are no steps here, this is missing config keys.

### Environment

- npm: 8.1.2
- Node.js: v16.13.2
- OS Name: Linux
- System Model Name: not relevant
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by wraithgar** [comment]
The registry scoped `keyfile` and `certfile` configs are what you want to use here.

```
//other-registry.tld/:keyfile=/path/to/key.pem
//other-registry.tld/:certfile=/path/to/cert.crt
```

See the [auth related section of configuring npmrc](https://docs.npmjs.com/cli/v9/configuring-npm/npmrc#auth-related-configuration)
