### ISSUE TITLE
Service unavailable when visting https://www.npmjs.com/settings/<username>/tokens

### ISSUE THREAD

**Issue by piyushpathakqa** [npm/cli#5472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Getting

`{"error":"Service Unavailable"}`

### Steps To Reproduce

1. Loging to npm account
2. Visit tokens page

### Environment

npm website

**Comment by wraithgar** [comment]
This repo is for tracking issues with the npm cli itself.  Registry and website issues need to go through npm support at https://www.npmjs.com/support
