### ISSUE TITLE
[BUG] `npm outdated` reports exit status 1 when there are major changes

### ISSUE THREAD

**Issue by lorenzogrv** [npm/cli#5473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

In the past, it would report exit status 0 when there are only "major upgrades".

Is this new behavior expected?

### Expected Behavior

Exit status zero when there are no upgrades within semver compatible range

### Steps To Reproduce

```bash
mkdir example && cd example
npm init --yes
npm install react@17
npm outdated
echo "Exit status is $?" # 1
```

### Environment

- npm: 8.19.1
- Node.js: v16.16.0
- OS Name: Manjaro i3
- System Model Name: x86_64 based PC
- npm config:
```ini
; no user config present on this system
```

**Comment by sun0day** [comment]
I am afraid so.

https://github.com/npm/cli/blob/eb1998a1664decc4aa064a4eb66966f64ae92d39/lib/commands/outdated.js#L76-L85

**Comment by wraithgar** [comment]
Yes this is the new intended behavior.

**Comment by lorenzogrv** [comment]
> 

Thx for clarification.
