### ISSUE TITLE
[Step is not defined] <Mocha-Steps  "step is not defined">

### ISSUE THREAD

**Issue by muneebrana23** [npm/cli#551]
# What / Why

> n/a
in mocha-steps docs it's mentioned "Simply run --require mocha-steps" what is it mean?
## When

* n/a

## Where

* n/a

### Current Behavior

* n/a

### Steps to Reproduce

* n/a

### Expected Behavior

* n/a

## Who

* n/a

## References

* n/a

**Comment by DanielRuf** [comment]
This is not a bug with npm and can be closed.
