### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by emanuelefavero** [npm/cli#5517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I'm trying to publish a package called "cra-template-essential" to npm with npm publish.
The package is a custom template for create react app (https://create-react-app.dev/docs/custom-templates/)
I've enabled two factor authentication and still get this error

error code E403
error 403 403 Forbidden - PUT https://registry.npmjs.org/cra-template-essential - You do not have permission to publish "cra-template-essential". Are you logged in as the correct user? In most cases, you or one of your dependencies are requesting a package version that is forbidden by your security policy, or error 403 on a server you do not have access to.

### Environment

- npm: 8.15.0
- Node.js: v18.7.0
- OS Name: Mac OS Monterey 12.5.1
- System Model Name: Macbook Pro 14
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by fritzy** [comment]
**Closing:** this looks to be an issue with the registry which is outside the scope of this repo. For registry support please go to [npmjs.com/support](https://www.npmjs.com/support). If you believe this is a bug with the cli, please provide further clarifying details.

If you look at https://www.npmjs.com/package/cra-template-essential, it's an exiting package. If you're not a publisher for that package, you won't be able to publish. If this isn't the problem, please reach out to the registry support.
