### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by zeki0775** [npm/cli#553]
hi, when I say install npm install package, it gives error. not loaded.

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR! https://npm.community

npm ERR! A complete log of this run can be found in:

what should I do?

**Comment by fwip** [comment]
I have also seen this error, just this morning.

What I did:

```bash
npx create-elm-app elmess
cd elmess
npx create-elm-app eject
```

`npx --version` -> `6.12.1`
`node --version` -> `v13.1.0`
`uname -a` -> `Darwin nelsonjs-mac 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64`

The log is available here: https://gist.github.com/fwip/f6594c5967d29592993b37ccfc158172


Edit:

From this state, I then executed `npm install create-elm-app && npx elm-app eject`, which worked as expected (npm did not throw an error).

**Comment by zeki0775** [comment]
The answer did not work.

**Comment by mikemimik** [comment]
Duplicate issue; aggregating into https://github.com/npm/cli/issues/417.
