### ISSUE TITLE
[BUG] NPM 7 and higher do not seem to support relative metadata sources 

### ISSUE THREAD

**Issue by pashakondratyev** [npm/cli#5534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Hi! We have a custom registry set up where we return the relative path for the targz, example: 
```
{"name":"decamelize","dist":{"tarball":"decamelize/-/decamelize-1.2.0.tgz","shasum":"f6534d15148269b20352e7bee26f501f9a191290"}}
```

This worked fine for npm versions < 7.0.0 but it seems that after upgrading this is no longer supported, and it searches in the current repo instead of downloading from the provided registry.  
```
 tarball no local data for decamelize@file:/Volumes/git/myRepo/decamelize/-/decamelize-1.2.0.tgz.
```
Unfortunately in certain cases we can't pass the full path so we really needed the relative path information.

### Expected Behavior

Would expect npm to be able to install from the repositories

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:8.15.0
- Node.js:16.17.0
- OS Name: MacOS
- System Model Name: Macbook Pro 
- npm config:
```
; "project" config from /Volumes/git/repo/.npmrc

///company.com/{companySpecificPath}/contents/release/npm/:_authToken = (protected) 
cafile = "/Volumes/git/repo/build/cert.pem" 
registry = "https://company.com/{companySpecificPath}/contents/release/npm/" 

; node bin location = /Users/{myName}/.local/share/nvm/v16.17.0/bin/node
; node version = v16.17.0
; npm local prefix = /Volumes/git/repo
; npm version = 8.15.0
; cwd = /Volumes/git/repo
; HOME = /Users/{myName}

```

**Comment by wraithgar** [comment]
This is unfortunately not something that npm is going to be able to support.  Due to the security fixes implemented since npm 6, the tarball path needs to be a full url.
