### ISSUE TITLE
NPM

### ISSUE THREAD

**Issue by sobusob** [npm/cli#5546]
npm install sqlite
npm WARN ancient lockfile
npm WARN ancient lockfile The package-lock.json file was created with an old version of npm,
npm WARN ancient lockfile so supplemental metadata must be fetched from the registry.
npm WARN ancient lockfile                                                        npm WARN ancient lockfile This is a one-time fix-up, please be patient...
npm WARN ancient lockfile                                                        npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2022-09-20T20_01_20_006Z-debug-0.log

![Screenshot_2022-09-21-01-35-33-250_com.termux.jpg](https://user-images.githubusercontent.com/70920951/191354289-2a946908-a7d4-4342-9e51-7312b38f43a4.jpg)

**Comment by fritzy** [comment]
**Closing:** please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).
