### ISSUE TITLE
trying to install aws-amplify/cli and error was thrown as cb() was never called 

### ISSUE THREAD

**Issue by suraj9657** [npm/cli#556]
22127 silly extract @graphql-codegen/plugin-helpers@1.8.3 extracted to C:\Users\chauh\AppData\Roaming\npm\node_modules\.staging\@graphql-codegen\plugin-helpers-eccd06ff (271114ms)
22128 timing npm Completed in 480230ms
22129 error cb() never called!
22130 error This is an error with npm itself. Please report this error at:
22131 error <https://npm.community>

**Comment by mikemimik** [comment]
Duplicate issue; aggregating into https://github.com/npm/cli/issues/417.

**Comment by theJsTsGuy** [comment]
I have same issue: I even tried clearing cache but that doesn't work.
```
(base) ubuntu@ubuntu-OptiPlex-9010:/media/ubuntu/Data/Bootcamp/project_14a-new/frontend$ npm cache clean --force && npm i -g @aws-amplify/cli
npm WARN using --force I sure hope you know what you are doing.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-09-20T09_07_10_378Z-debug.log
```

Node version: ```v14.17.6```
NPM version: ```6.14.15```
Node Version Manager version ```0.38.0```
