### ISSUE TITLE
Feature Request: Stateless Registry Support 

### ISSUE THREAD

**Issue by hsjobeki** [npm/cli#5585]
Generally many developers (including me) dont like using a registry. Because it accumulates state and doesnt provide real reproducability. It relies on the maintainers to do the messy work of synchronizing semantic versionings and commit hashes. 
There are many countless examples from the past where the maintainer messed up and unpublished, mixed up, etc. on her/his packages.

Therefore I request that npm should support a feature where the packages get only build on demand. This requires the package to be 100% reproducible (which can be achieved using a tool called nix) 

If there is any need to push npm in that direction I (and my company) are willing to support.

**Comment by ljharb** [comment]
In what way does it not provide real reproducibility?

JavaScript packages - due to the nature of the language itself - simply aren’t reliably or consistently reproducible, so building on demand simply wouldn’t provide the property you’re looking for. In other words, that level of reproducibility is not possible in JavaScript without adding a bunch of tooling and constraints.

**Comment by hsjobeki** [comment]
In fact youre right. Javascript is not reproducible without some constraints. Me and my colleges are willing to accept those constraints. Actually with nix we have a Toolchain, that is capable of producing bitidentical builds. ([numbers here](https://r13y.com/)). But we cannot use npm as it is to install dependencies that are build with that toolchain because we dont push them to a registry. We only know that running the "build" step will produce every time the same output no matter where and when and how you run it. 

Are you familiar with the "nix" tool world ? Maybe it is possible to move in the same direction with npm. 
Draft idea: "An option to download not the package from a registry but the build output from its respository".  The registry should indeed just be a cache to prevent the different users from building stuff over again.

**Comment by ljharb** [comment]
npm needs to support the JS ecosystem - which means everyone, not just nix or bazel.

**Comment by hsjobeki** [comment]
I do not doubt that. In fact i consider myself as a JavaScript developer. So i know the JS ecosystem. 
I just please you to think about this:

> The ecosystem of JavaScript frameworks is almost unbelievably unstable. Yes, even now in the year 2021. (https://dev.to/jaredcwhite/the-shocking-immaturity-of-javascript-c70)

How can we improve that ?

Maybe the first step would be to add support for reproducible builds. However they are achieved should not be of interest.

My draft vision / feature could be:

1. Imagine a World where some packages can be built reproducible
2. If the user wants to install a reproducible package; deliver the source where it can be built from (e.g. a commit hash)
3. let the user or the registry do the "build" and cache the result. (e.g. scripts -> build; from the package.json)
4. use the result as a normal dependency and copy/link it to the  correct node_modules folder

Or maybe you have another idea ?

**Comment by ljharb** [comment]
Just because it’s reproducible doesn’t mean you have to actually *reproduce* it.
