### ISSUE TITLE
[BUG] npm prune --production removes dependencies that are defined in both devDependencies and dependencies

### ISSUE THREAD

**Issue by chrisdoc** [npm/cli#5590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When a dependency is defined in both `devDependencies` and `dependencies` and `npm prune --production` is executed, then this dependency is removed from `node_modules`

### Expected Behavior

When a dependency is defined in both `devDependencies` and `dependencies` and `npm prune --production` is executed, then this dependency should still be included in `node_modules` and dependencies defined in `dependencies` should have precedence over `devDependencies`

### Steps To Reproduce

I created a minimal [repo](https://github.com/chrisdoc/npm-prune-issue) with a [GitHub action ](https://github.com/chrisdoc/npm-prune-issue/actions/runs/3133249399/jobs/5086424973) that shows that after running `npm prune --production` the resulting node_modules does not have the dependencies that are defined in both `devDependencies` and `dependencies`

### Environment

- npm: 8.19.1
- Node.js: v18.9.1
- OS Name: Ubuntu 20.04 LTS // GitHub Action Runner
- System Model Name:
- npm config:
```ini
; node bin location = /opt/hostedtoolcache/node/18.9.1/x64/bin/node
; node version = v18.9.1
; npm local prefix = /home/runner/work/npm-prune-issue/npm-prune-issue
; npm version = 8.19.1
; cwd = /home/runner/work/npm-prune-issue/npm-prune-issue
; HOME = /home/runner
; Run `npm config ls -l` to show all defaults.
```

**Comment by wraithgar** [comment]
This is by design.  If a dependency is in devDependencies it is a dev dependency.  npm does not have a concept of having a dependency be both.  Having them in both places in the package.json is not supported, and npm itself would never put them in both places, you'd have to hand-edit your package.json to get it in that state.
