### ISSUE TITLE
[BUG] while calling npm install command :Exit handler never called!  

### ISSUE THREAD

**Issue by Macbeth47** [npm/cli#5593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

getting error while trying to install npm into my project.
ERROR:
Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

### Expected Behavior

npm should be installed successfully. 

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 8.19.2
- Node.js: v14.17.6
- OS Name: windox
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by wraithgar** [comment]
This is not enough info to go off of
