### ISSUE TITLE
[BUG] Failed parsing JSON config key userconfig

### ISSUE THREAD

**Issue by bernardoadc** [npm/cli#560]
# What / Why
I'm working in virtual machines that are created each time I loggon. I mapped a network drive to local drive, and want npm to use a user config .npmrc file of that folder, so every npm command in that loggon session uses those configs.

## Where
Windows command prompt
NPM version: 6.11.3

## How
```
> set HOME=E:\AppData
> npm --userconfig "E:\AppData\.npmrc" config set registry "http://example.com"
> set NPM_CONFIG_USERCONFIG="E:\AppData\.npmrc"
```

### Current Behavior
```
> npm config get registry
THROWS failed parsing JSON config key userconfig: "E:\AppData\.npmrc"
  ...
THROWS npm.load() required
  ...
```

The same happens even if there isn't a file, or if it is an empty one

### Expected Behavior
```
> npm config get registry
http://example.com
```

**Comment by ljharb** [comment]
You may need to escape the backslashes.

**Comment by bernardoadc** [comment]
Omg @ljharb you're right... changing to `set NPM_CONFIG_USERCONFIG="E:/AppData/.npmrc"` solved it all
