### ISSUE TITLE
[BUG] update-notifier.js suggests with deprecated -g parameter instead of --location=global

### ISSUE THREAD

**Issue by besimgurbuz** [npm/cli#5607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [x] I am using the latest npm

### Current Behavior

When `cli` suggest to update the `npm` it recommends updating with deprecated `-g` parameter.

![image](https://user-images.githubusercontent.com/33575384/193126192-7ee8b9f5-d3c8-45be-80cb-e6143ed188c1.png)

### Expected Behavior

It should suggest updating with `--location=global` parameter.

### Steps To Reproduce

1. Run any `cli` command on outdated `npm` environment (I was using version `8.11.0`)
2. `update-notifier.js` will suggest with deprecated parameter.

### Environment

- npm: 8.11.0
- Node.js: 16.15.1
- OS Name: Ubuntu 20.04
- System Model Name: AMD Ryzen 7 3700X 8-Core Processor
- npm config:
```ini
; node bin location = /home/besim/.nvm/versions/node/v16.15.1/bin/node
; node version = v16.15.1
; npm local prefix = /home/besim
; npm version = 8.19.2
; cwd = /home/besim/develop
; HOME = /home/besim
; Run `npm config ls -l` to show all defaults.
```

**Comment by besimgurbuz** [comment]
I would like to create a PR for this issue, if it's okay.

**Comment by ljharb** [comment]
`-g` is not actually deprecated whatsoever.

**Comment by besimgurbuz** [comment]
After trying to use it with version `8.19.2 (latest)` warning is gone. I think it might be about previous version `8.11.0`.  Thanks for informing and sorry about wasting your time.

(The warning I got was ```npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.```)
