### ISSUE TITLE
[DOCS] bin filed has multi script

### ISSUE THREAD

**Issue by wangcongyi** [npm/cli#5608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Problem, not another kind of Docs Problem.

- [X] This is a CLI Docs Problem.

### Description of Problem

if my pacjage.json "bin" filed has multi-script, Which script will execute? 
According to my test results, the priority is reversed by the string,
but I did not find the relevant documentation.
Can the bin field have multiple scripts? 
![image](https://user-images.githubusercontent.com/13843979/193205248-c8760f27-98f5-4840-8eae-5933e7b906cf.png)

**Comment by ljharb** [comment]
There’s no priority - the LHS is the name of the binary.
