### ISSUE TITLE
[QUESTION] Can `libnpmversion` upgrade the root `package.json`?

### ISSUE THREAD

**Issue by raphaelokon** [npm/cli#5623]
Hi there.
We are planning to use the `libnpmversion` package to programmatically bump versions in our monorepo (NPM workspaces) packages individually (we cannot use the CLI directly). Is there a programmatic way to update the root package.json and its package-lock.json via `libnpmversion` once the workspace packages where bumped via `libnpmversion`? I couldn’t find anything related to `update-workspaces` for it.
Any help greatly appreciated. Cheers.

**Comment by ljharb** [comment]
You'd use arborist most likely, not one of the "libnpm" packages - but why can't you use the CLI directly?

**Comment by raphaelokon** [comment]
Hi @ljharb – thanks for your reply.

> but why can't you use the CLI directly?

I was assuming that the CLI cannot be used programmatically (as in imported as a module and the used via its API). 

Can `arborist` handle the update of the root package? Or is arborist capable of ~to~ individually bumping the workspace packages and then updating the root package.json and its package-lock.json?

Thanks for taking the time to answer this. Cheers

**Comment by ljharb** [comment]
It can’t, but the best practice is to shell out with child_process.exec to the npm CLI.

**Comment by raphaelokon** [comment]
Cheers. Sub shelling is not an option for us unfortunately. We just tried `arborist` to reify in the workspaces root and that did the trick. Thanks again ❤️

**Comment by ljharb** [comment]
I’d love to understand why that best practice is not an option, but I’m glad arborist works for you.

**Comment by raphaelokon** [comment]
Hi @ljharb 
I think it is just a mix of preference that we prefer to use  modules via its API directly and that we already had the versioning done via `libnpmversion`. But I’ll take with me that shelling out is the actual preferred method and maybe refactor it later on. Thanks again for your answer. 
Cheers

**Comment by raphaelokon** [comment]
Hi there @ljharb 
Sorry to reopen this, but we are discovering issues when using `reify` to update the root lock when utilizing `npm workspaces` with our private registry with scoped packages.

What would the best practice command be if we would rather shell out than to use `reify()`?
Also: We observed that `arborist.reify` is calling/fetching informations from the default registry for our private packages and 404s. Is that normal behavior?

Cheers and thanks again.

**Comment by ljharb** [comment]
For the second question, if your private packages are scoped and the scope is configured to use your private registry, that shouldn't happen I think.

reify is usually `npm install`.

**Comment by raphaelokon** [comment]
Cheers for your answers @ljharb 

Yes, the private packages are scoped and we utilize the scope ~is~ using our private artifactory.
I just thought that we may be able to update the root `package-lock.json` by shelling out with `npm i --package-lock-only` rather than using `reify`. Not sure if this is the best practice you referred to.

**Comment by ljharb** [comment]
"private" imo refers to `private: true` which can't be published. What you're calling private i'm calling internal :-)

Yes, you should be able to do that.

**Comment by raphaelokon** [comment]
Ha! Yeah, we both mean the same thing :D

I’ll report regarding updating the root lock file via `npm i --package-lock-only` and hopefully close this issue once and for all :-)

**Comment by raphaelokon** [comment]
I am still wondering why calling the `reify()` tries to fetch the _scoped internal_ package from the public registry rather than from our artifactory. It seems like it is not respecting the root `.npmrc` in the mono repo where it is executed.

**Comment by raphaelokon** [comment]
We worked around it by not using arborist but the `npm` cli directly.
