### ISSUE TITLE
[BUG] npm help install doesnt find a matching help page

### ISSUE THREAD

**Issue by icrayix** [npm/cli#5625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [x] I am using the latest npm

### Current Behavior

`npm help install` doesn't find a matching help page although it's mentioned in `npm install --help`.

### Expected Behavior

`npm help install` should output a help page.

### Steps To Reproduce

run `npm help install`

### Environment

- npm: 8.3.1
- Node.js: v16.14.0
- OS Name: GNU/Linux Fedora 36

**Comment by lukekarrys** [comment]
Can you try updating to the latest version of npm@8? If that doesn't work, can you paste the output of `npm help install` and `npm config ls`?

I get the full output of `man/man1/npm-install.1` when I run `npm help install`.

**Comment by wraithgar** [comment]
Closing due to age.
