### ISSUE TITLE
ENEEDAUTH on upgrade to node 16 and accessing private repo of my company

### ISSUE THREAD

**Issue by dixitbafnar** [npm/cli#5657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I have upgraded to `Node 16` and updated my `npmrc` file to access the private artifactroy of my firm.
In old version i.e node 14 when I have same changes in `npmrc` and I do `npm whoami i` get my username my `.npmrc` file looks like this
`%scope%:registry=%artifactoryurl%`
`%artifactoryurl%:_auth=%auth_token%`
`%artifactoryurl%:always-auth=true`
But when I update to node 16 nad run `npm whoami I` get error as
npm ERR! code ENEEDAUTH npm ERR! need auth This command requires you to be logged in. npm ERR! need auth You need to authorize this machine using npm adduser

### Expected Behavior

Should see my username

### Steps To Reproduce

Env: Windows
.npmrc
`%scope%:registry=%artifactoryurl%`
`%artifactoryurl%:_auth=%auth_token%`
`%artifactoryurl%:always-auth=true`
> npm whomai

### Environment

- npm: 8.15.0
- Node.js: 16.17.1
- OS Name: windows
- System Model Name:
- npm config:
```ini
`%scope%:registry=%artifactoryurl%`
`%artifactoryurl%:_auth=%auth_token%`
`%artifactoryurl%:always-auth=true`
```

**Comment by wraithgar** [comment]
`whoami` needs the `registry` itself to be specified if you want it to use the artifactory auth token.  There is no package or scope involved so the scope-dependent configuration is not going to be applied.  If you want to test your artifactory token you can specify `--registry` when you run `whoami`
