### ISSUE TITLE
[BUG] Packages won't install on Windows

### ISSUE THREAD

**Issue by ChariseWalraven** [npm/cli#5662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [x] I am using the latest npm

### Current Behavior

```
command:  npm i -g corepack (or some other package)
npm ERR! Unexpected token '.'
```

Packages won't install. I've tried with corepack

Here are some logs wwhere this happens:

[2022-10-10T11_30_37_725Z-debug-0.log](https://github.com/npm/cli/files/9745587/2022-10-10T11_30_37_725Z-debug-0.log)
[2022-10-10T11_52_41_649Z-debug-0.log](https://github.com/npm/cli/files/9745687/2022-10-10T11_52_41_649Z-debug-0.log)
[2022-10-10T11_47_34_790Z-debug-0.log](https://github.com/npm/cli/files/9745689/2022-10-10T11_47_34_790Z-debug-0.log)

### Expected Behavior

Corepack installs

### Steps To Reproduce

1. Run `npm i -g corepack`
2. See error...
`npm ERR! Unexpected token '.'`

### Environment

- Windows Specifications:
Edition	Windows 10 Pro
Version	21H1
Installed on	‎20/‎10/‎2020
OS build	19043.1526
- npm: 8.15.0
- Node.js: v16.17.1
- npm config:
```ini
; node bin location = C:\Program Files\nodejs\node.exe
; node version = v16.17.1
; npm local prefix = C:\Users\Charise
; npm version = 8.15.0
; cwd = C:\Users\Charise\AppData\Local\npm-cache\_logs
; HOME = C:\Users\Charise
; Run `npm config ls -l` to show all defaults.
```

**Comment by ChariseWalraven** [comment]
Looks like this happens with other packages too. 😞

**Comment by ChariseWalraven** [comment]
This seems to be the issue: `verbose stack ../workspaces/libnpmfund`

**Comment by fritzy** [comment]
Does this happen with latest npm?
@ChariseWalraven can you try replicating this problem on the latest version of `npm`? (ie. `npm i -g npm`)

**Comment by jj22511-dev** [comment]
[ChariseWalraven](https://github.com/ChariseWalraven) check it out https://github.com/coreybutler/nvm-windows/issues/814 maybe it will solve your problem.

**Comment by yassine-klilich** [comment]
I'm facing the same issue, when I run command `npm init -y`

npm: 8.19.0
Node.js: v18.12.0

[2022-10-28T14_23_36_260Z-debug-0.log](https://github.com/npm/cli/files/9889192/2022-10-28T14_23_36_260Z-debug-0.log)

This seems to be the issue: ../workspaces/libnpmexec

**Comment by yassine-klilich** [comment]
I'm facing the same issue, when I run command `npm init -y`

NPM: 8.19.2
Node.js: v18.12.0
NVM: 1.1.9

[2022-10-28T14_23_36_260Z-debug-0.log](https://github.com/npm/cli/files/9889232/2022-10-28T14_23_36_260Z-debug-0.log)

This seems to be the issue: ../workspaces/libnpmexec

**Comment by yassine-klilich** [comment]
@ChariseWalraven if you are working with NVM just re-install it. I did that and it worked for me.

**Comment by nlf** [comment]
as was identified in comments, this problem is present in old versions of nvm-windows that downloaded a zip archive from this repository rather than installing from the tarball published to the npm registry. this repository contains symlinks to our workspaces, but since by default git in windows does not support symlinks they are instead represented by a text file whose contents refer to where the package actually exists.

this bug was fixed in nvm-windows. you should be able to update nvm-windows and then use it to reinstall node and get back to a working system.
