### ISSUE TITLE
Error: Cannot find module '/usr/local/lib/node_modules/npm/scripts/bundle-and-gitignore-deps.js'

### ISSUE THREAD

**Issue by andrei-kiparuk** [npm/cli#5694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

can't install anything via npm
getting error message:
Error: Cannot find module '/usr/local/lib/node_modules/npm/scripts/bundle-and-gitignore-deps.js'

### Expected Behavior

should be able to install

### Steps To Reproduce

use  ubuntu 20.04 docker container

the way I'm installing it

ARG NODE_VERSION=14.20.1
ARG NPM_VERSION=8.19.2
ARG SKIP_NPM_UPGRADE="no"
RUN curl -SL "[https://nodejs.org/download/release/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.xz](https://nodejs.org/download/release/v$%7BNODE_VERSION%7D/node-v$%7BNODE_VERSION%7D-linux-x64.tar.xz)" -o /tmp/node-v${NODE_VERSION}-linux-x64.tar.xz \
    && tar -xJf /tmp/node-v${NODE_VERSION}-linux-x64.tar.xz -C /usr/local --strip-components=1 \
    && rm "/tmp/node-v${NODE_VERSION}-linux-x64.tar.xz" \
    && if [ "$SKIP_NPM_UPGRADE" = "yes" ]; then \
        echo "NPM upgrade skipped (SKIP_NPM_UPGRADE=${SKIP_NPM_UPGRADE})" ; \
    else \
        echo "Upgrading NPM (SKIP_NPM_UPGRADE=${SKIP_NPM_UPGRADE})..." \
        && curl -qL https://www.npmjs.com/install.sh | sh ; \
    fi

any other command after that will show mentioned error. for example:
    
RUN cd /usr/local/lib/node_modules/npm/ \
    && npm update opener \
    && npm install 'y18n' \
    && node --version \
    && npm --version
    
 will result - Error: Cannot find module '/usr/local/lib/node_modules/npm/scripts/bundle-and-gitignore-deps.js'   

### Environment

- npm: 8.19.2
- Node.js: 14.20.1
- OS Name: ubuntu 20.04
- System Model Name: docker
- npm config:
```ini
; ; node bin location = /usr/local/bin/node
; node version = v14.20.1
; npm local prefix = /usr/local/lib/node_modules/npm
; npm version = 8.19.2
; cwd = /usr/local/lib/node_modules/npm
; HOME = /root
; Run `npm config ls -l` to show all defaults.
```

**Comment by fritzy** [comment]
Your example is running npm within it's own install, changing its own dependencies. I can't imagine a use case for this, nor will it work since the published package doesn't contain its own development scripts.

You can't run `npm` commands within the published `npm` install as if it were a full project.

If you're trying to globally install `opener` do `npm install -g opener`.
