### ISSUE TITLE
[BUG] vueify install error using npm@6.9.0 node@v10.16.3 

### ISSUE THREAD

**Issue by Tsmorro** [npm/cli#570]
# What / Why
installed latest global browserify package and latest vue release as a dev dependency, but when I tried to install vueify as a dev-dependency it returned with this error log: 

0 info it worked if it ends with ok
1 verbose cli [ '/Users/tmorrow/.nvm/versions/node/v10.16.3/bin/node',
1 verbose cli   '/Users/tmorrow/.nvm/versions/node/v10.16.3/bin/npm',
1 verbose cli   'install',
1 verbose cli   'vueify' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose npm-session 77f02e58cfbcc967
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/vueify 15ms (from cache)
8 silly pacote tag manifest for vueify@latest fetched in 24ms
9 timing stage:loadCurrentTree Completed in 62ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 3ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule vueify@9.4.1 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/object-assign 136ms (from cache)
18 http fetch GET 304 https://registry.npmjs.org/lru-cache 139ms (from cache)
19 http fetch GET 304 https://registry.npmjs.org/hash-sum 144ms (from cache)
20 silly pacote range manifest for object-assign@^4.0.1 fetched in 143ms
21 silly resolveWithNewModule object-assign@4.1.1 checking installable status
22 silly pacote range manifest for lru-cache@^4.0.0 fetched in 149ms
23 silly resolveWithNewModule lru-cache@4.1.5 checking installable status
24 http fetch GET 304 https://registry.npmjs.org/source-map 148ms (from cache)
25 silly pacote range manifest for hash-sum@^1.0.2 fetched in 155ms
26 silly resolveWithNewModule hash-sum@1.0.2 checking installable status
27 http fetch GET 304 https://registry.npmjs.org/convert-source-map 158ms (from cache)
28 http fetch GET 304 https://registry.npmjs.org/through 152ms (from cache)
29 silly pacote range manifest for source-map@^0.5.6 fetched in 162ms
30 silly resolveWithNewModule source-map@0.5.7 checking installable status
31 http fetch GET 304 https://registry.npmjs.org/postcss-selector-parser 164ms (from cache)
32 silly pacote range manifest for convert-source-map@^1.2.0 fetched in 173ms
33 silly resolveWithNewModule convert-source-map@1.7.0 checking installable status
34 silly pacote range manifest for through@^2.3.6 fetched in 167ms
35 silly resolveWithNewModule through@2.3.8 checking installable status
36 http fetch GET 304 https://registry.npmjs.org/chalk 174ms (from cache)
37 silly pacote range manifest for postcss-selector-parser@^2.0.0 fetched in 172ms
38 silly resolveWithNewModule postcss-selector-parser@2.2.3 checking installable status
39 http fetch GET 304 https://registry.npmjs.org/postcss 174ms (from cache)
40 silly pacote range manifest for chalk@^1.1.1 fetched in 181ms
41 silly resolveWithNewModule chalk@1.1.3 checking installable status
42 http fetch GET 304 https://registry.npmjs.org/cssnano 182ms (from cache)
43 silly pacote range manifest for postcss@^5.0.10 fetched in 182ms
44 silly resolveWithNewModule postcss@5.2.18 checking installable status
45 silly pacote range manifest for cssnano@^3.3.2 fetched in 189ms
46 silly resolveWithNewModule cssnano@3.10.0 checking installable status
47 http fetch GET 304 https://registry.npmjs.org/json5 47ms (from cache)
48 http fetch GET 304 https://registry.npmjs.org/vue-hot-reload-api 46ms (from cache)
49 silly pacote range manifest for json5@^0.5.1 fetched in 49ms
50 silly resolveWithNewModule json5@0.5.1 checking installable status
51 silly pacote range manifest for vue-hot-reload-api@^2.0.1 fetched in 48ms
52 silly resolveWithNewModule vue-hot-reload-api@2.3.4 checking installable status
53 http fetch GET 304 https://registry.npmjs.org/vue-template-es2015-compiler 31ms (from cache)
54 silly pacote range manifest for vue-template-es2015-compiler@^1.2.2 fetched in 32ms
55 silly resolveWithNewModule vue-template-es2015-compiler@1.9.1 checking installable status
56 http fetch GET 304 https://registry.npmjs.org/vue-template-compiler 59ms (from cache)
57 silly pacote range manifest for vue-template-compiler@^2.0.0-alpha.8 fetched in 60ms
58 silly resolveWithNewModule vue-template-compiler@2.6.10 checking installable status
59 http fetch GET 304 https://registry.npmjs.org/has-ansi 25ms (from cache)
60 http fetch GET 304 https://registry.npmjs.org/ansi-styles 28ms (from cache)
61 silly pacote range manifest for has-ansi@^2.0.0 fetched in 29ms
62 silly resolveWithNewModule has-ansi@2.0.0 checking installable status
63 silly pacote range manifest for ansi-styles@^2.2.1 fetched in 33ms
64 silly resolveWithNewModule ansi-styles@2.2.1 checking installable status
65 http fetch GET 304 https://registry.npmjs.org/supports-color 35ms (from cache)
66 http fetch GET 304 https://registry.npmjs.org/strip-ansi 37ms (from cache)
67 silly pacote range manifest for supports-color@^2.0.0 fetched in 38ms
68 silly resolveWithNewModule supports-color@2.0.0 checking installable status
69 silly pacote range manifest for strip-ansi@^3.0.0 fetched in 40ms
70 silly resolveWithNewModule strip-ansi@3.0.1 checking installable status
71 http fetch GET 304 https://registry.npmjs.org/escape-string-regexp 40ms (from cache)
72 silly pacote range manifest for escape-string-regexp@^1.0.2 fetched in 41ms
73 silly resolveWithNewModule escape-string-regexp@1.0.5 checking installable status
74 http fetch GET 304 https://registry.npmjs.org/ansi-regex 25ms (from cache)
75 silly pacote range manifest for ansi-regex@^2.0.0 fetched in 26ms
76 silly resolveWithNewModule ansi-regex@2.1.1 checking installable status
77 http fetch GET 304 https://registry.npmjs.org/safe-buffer 25ms (from cache)
78 silly pacote range manifest for safe-buffer@~5.1.1 fetched in 26ms
79 silly resolveWithNewModule safe-buffer@5.1.2 checking installable status
80 http fetch GET 304 https://registry.npmjs.org/defined 22ms (from cache)
81 silly pacote range manifest for defined@^1.0.0 fetched in 22ms
82 silly resolveWithNewModule defined@1.0.0 checking installable status
83 http fetch GET 304 https://registry.npmjs.org/postcss-convert-values 47ms (from cache)
84 http fetch GET 304 https://registry.npmjs.org/postcss-colormin 48ms (from cache)
85 http fetch GET 304 https://registry.npmjs.org/decamelize 51ms (from cache)
86 http fetch GET 304 https://registry.npmjs.org/postcss-discard-duplicates 49ms (from cache)
87 http fetch GET 304 https://registry.npmjs.org/postcss-calc 52ms (from cache)
88 silly pacote range manifest for postcss-convert-values@^2.3.4 fetched in 51ms
89 silly resolveWithNewModule postcss-convert-values@2.6.1 checking installable status
90 http fetch GET 304 https://registry.npmjs.org/has 54ms (from cache)
91 silly pacote range manifest for postcss-colormin@^2.1.8 fetched in 55ms
92 silly resolveWithNewModule postcss-colormin@2.2.2 checking installable status
93 http fetch GET 304 https://registry.npmjs.org/postcss-discard-empty 54ms (from cache)
94 silly pacote range manifest for decamelize@^1.1.2 fetched in 56ms
95 silly resolveWithNewModule decamelize@1.2.0 checking installable status
96 silly pacote range manifest for postcss-discard-duplicates@^2.0.1 fetched in 57ms
97 silly resolveWithNewModule postcss-discard-duplicates@2.1.0 checking installable status
98 silly pacote range manifest for postcss-calc@^5.2.0 fetched in 59ms
99 silly resolveWithNewModule postcss-calc@5.3.1 checking installable status
100 http fetch GET 304 https://registry.npmjs.org/postcss-discard-comments 58ms (from cache)
101 silly pacote range manifest for has@^1.0.1 fetched in 63ms
102 silly resolveWithNewModule has@1.0.3 checking installable status
103 silly pacote range manifest for postcss-discard-empty@^2.0.1 fetched in 65ms
104 silly resolveWithNewModule postcss-discard-empty@2.1.0 checking installable status
105 silly pacote range manifest for postcss-discard-comments@^2.0.4 fetched in 71ms
106 silly resolveWithNewModule postcss-discard-comments@2.0.4 checking installable status
107 http fetch GET 304 https://registry.npmjs.org/autoprefixer 93ms (from cache)
108 silly pacote range manifest for autoprefixer@^6.3.1 fetched in 100ms
109 silly resolveWithNewModule autoprefixer@6.7.7 checking installable status
110 http fetch GET 304 https://registry.npmjs.org/postcss-discard-overridden 88ms (from cache)
111 http fetch GET 304 https://registry.npmjs.org/postcss-discard-unused 61ms (from cache)
112 silly pacote range manifest for postcss-discard-overridden@^0.1.1 fetched in 92ms
113 silly resolveWithNewModule postcss-discard-overridden@0.1.1 checking installable status
114 http fetch GET 304 https://registry.npmjs.org/postcss-filter-plugins 61ms (from cache)
115 silly pacote range manifest for postcss-discard-unused@^2.2.1 fetched in 64ms
116 silly resolveWithNewModule postcss-discard-unused@2.2.3 checking installable status
117 http fetch GET 304 https://registry.npmjs.org/postcss-merge-idents 62ms (from cache)
118 silly pacote range manifest for postcss-filter-plugins@^2.0.0 fetched in 65ms
119 silly resolveWithNewModule postcss-filter-plugins@2.0.3 checking installable status
120 http fetch GET 304 https://registry.npmjs.org/postcss-merge-longhand 64ms (from cache)
121 http fetch GET 304 https://registry.npmjs.org/postcss-minify-font-values 58ms (from cache)
122 silly pacote range manifest for postcss-merge-idents@^2.1.5 fetched in 68ms
123 silly resolveWithNewModule postcss-merge-idents@2.1.7 checking installable status
124 http fetch GET 304 https://registry.npmjs.org/postcss-merge-rules 63ms (from cache)
125 http fetch GET 304 https://registry.npmjs.org/postcss-minify-gradients 56ms (from cache)
126 silly pacote range manifest for postcss-minify-font-values@^1.0.2 fetched in 63ms
127 silly resolveWithNewModule postcss-minify-font-values@1.0.5 checking installable status
128 silly pacote range manifest for postcss-merge-longhand@^2.0.1 fetched in 71ms
129 silly resolveWithNewModule postcss-merge-longhand@2.0.2 checking installable status
130 silly pacote range manifest for postcss-merge-rules@^2.0.3 fetched in 70ms
131 silly resolveWithNewModule postcss-merge-rules@2.1.2 checking installable status
132 silly pacote range manifest for postcss-minify-gradients@^1.0.1 fetched in 65ms
133 silly resolveWithNewModule postcss-minify-gradients@1.0.5 checking installable status
134 http fetch GET 304 https://registry.npmjs.org/postcss-minify-params 63ms (from cache)
135 silly pacote range manifest for postcss-minify-params@^1.0.4 fetched in 72ms
136 silly resolveWithNewModule postcss-minify-params@1.2.2 checking installable status
137 http fetch GET 304 https://registry.npmjs.org/postcss-minify-selectors 56ms (from cache)
138 silly pacote range manifest for postcss-minify-selectors@^2.0.4 fetched in 60ms
139 silly resolveWithNewModule postcss-minify-selectors@2.1.1 checking installable status
140 http fetch GET 304 https://registry.npmjs.org/postcss-normalize-charset 49ms (from cache)
141 silly pacote range manifest for postcss-normalize-charset@^1.1.0 fetched in 53ms
142 silly resolveWithNewModule postcss-normalize-charset@1.1.1 checking installable status
143 http fetch GET 304 https://registry.npmjs.org/postcss-ordered-values 47ms (from cache)
144 http fetch GET 304 https://registry.npmjs.org/postcss-reduce-transforms 41ms (from cache)
145 http fetch GET 304 https://registry.npmjs.org/postcss-reduce-idents 47ms (from cache)
146 silly pacote range manifest for postcss-ordered-values@^2.1.0 fetched in 51ms
147 silly resolveWithNewModule postcss-ordered-values@2.2.3 checking installable status
148 silly pacote range manifest for postcss-reduce-transforms@^1.0.3 fetched in 44ms
149 silly resolveWithNewModule postcss-reduce-transforms@1.0.4 checking installable status
150 silly pacote range manifest for postcss-reduce-idents@^2.2.2 fetched in 51ms
151 silly resolveWithNewModule postcss-reduce-idents@2.4.0 checking installable status
152 http fetch GET 304 https://registry.npmjs.org/postcss-reduce-initial 45ms (from cache)
153 silly pacote range manifest for postcss-reduce-initial@^1.0.0 fetched in 46ms
154 silly resolveWithNewModule postcss-reduce-initial@1.0.1 checking installable status
155 http fetch GET 304 https://registry.npmjs.org/postcss-unique-selectors 39ms (from cache)
156 silly pacote range manifest for postcss-unique-selectors@^2.0.2 fetched in 41ms
157 silly resolveWithNewModule postcss-unique-selectors@2.0.2 checking installable status
158 http fetch GET 304 https://registry.npmjs.org/postcss-value-parser 32ms (from cache)
159 silly pacote range manifest for postcss-value-parser@^3.2.3 fetched in 35ms
160 silly resolveWithNewModule postcss-value-parser@3.3.1 checking installable status
161 http fetch GET 304 https://registry.npmjs.org/postcss-svgo 59ms (from cache)
162 silly pacote range manifest for postcss-svgo@^2.1.1 fetched in 60ms
163 silly resolveWithNewModule postcss-svgo@2.1.6 checking installable status
164 http fetch GET 304 https://registry.npmjs.org/postcss-zindex 32ms (from cache)
165 silly pacote range manifest for postcss-zindex@^2.0.1 fetched in 33ms
166 silly resolveWithNewModule postcss-zindex@2.2.0 checking installable status
167 timing npm Completed in 889ms
168 error cb() never called!
169 error This is an error with npm itself. Please report this error at:
170 error <https://npm.community>

## When
 when running npm install vueify -save-dev

## Where

* n/a

### Steps to Reproduce
[newportfolio.zip](https://github.com/npm/cli/files/3935230/newportfolio.zip)

(Mac OS)

sudo npm install -g browserify 
npm init

npm install vue --save-dev
npm install vueify --save-dev

### Expected Behavior

* n/a

## Who

* n/a

## References

* n/a

**Comment by mikemimik** [comment]
Duplicate issue; aggregating into https://github.com/npm/cli/issues/417.
