### ISSUE TITLE
[BUG] EOWNERMUTATE 404 Not Found - Team not found

### ISSUE THREAD

**Issue by kvz** [npm/cli#5700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I'm trying to remove a collaborator from a module like so:

```bash
npm owner rm goto-bus-stop @uppy/utils
```

and am getting the following output:

```bash
This operation requires a one-time password.
Enter OTP: ******
npm ERR! code EOWNERMUTATE
npm ERR! Failed to update package: "404 Not Found - PUT https://registry.npmjs.org/@uppy%2futils/-rev/70-c1e129da13b8f231d4174d4e1f195aca - Team not found"
```

Google has zero hits on EOWNERMUTATE. Nor this GitHub issue tracker. This should be a simple operation that many people perform all the time, so I wonder what am I doing wrong? 🤔 

### Expected Behavior

The user is removed from the module.

### Steps To Reproduce

```bash
npm owner rm goto-bus-stop @uppy/utils
```

### Environment

latest macOS with:

```
; node bin location = /usr/local/Cellar/node/18.9.0/bin/node
; node version = v18.9.0
; npm local prefix = /Users/kvz/code/accounting
; npm version = 8.19.1
; cwd = /Users/kvz/code/accounting
; HOME = /Users/kvz
; Run `npm config ls -l` to show all defaults.
```

**Comment by fritzy** [comment]
**Closing:** this looks to be an issue with the registry which is outside the scope of this repo. For registry support please go to [npmjs.com/support](https://www.npmjs.com/support). If you believe this is a bug with the cli, please provide further clarifying details.
