### ISSUE TITLE
[BUG] <NPM looks at wrong folder for react-scripts>

### ISSUE THREAD

**Issue by GreenJ84** [npm/cli#5708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When running the `npm run start` for a newly created React App I get an error saying react-scripts cannot be found.

<img width="790" alt="Screen Shot 2022-10-17 at 6 15 43 PM" src="https://user-images.githubusercontent.com/102741688/196312497-0393eeb6-45f6-4ae3-8318-a6061e1d63e5.png">

However, if I run  `node node_modules/react-scripts/scripts/start.js` the React App will spin up.
<img width="757" alt="Screen Shot 2022-10-17 at 6 17 37 PM" src="https://user-images.githubusercontent.com/102741688/196312656-508198bb-bf14-4004-9fc2-3e9a73b7a2bf.png">

This tells me it isn't that I don't have  react-scripts it just wont let itself be directly called via module name as it looks at the wrong place

### Expected Behavior

I expect the `npm run start` to spin up the front end environment

### Steps To Reproduce

1. `npx create-reacte-app --template typescript`
2. `npm run start`
3. try manually uninstalling and re-installing (multiple different ways) react-scripts, node_modules, package-lock.json and re-run `npm run start`

### Environment

- npm: 8.15.0
- Node.js: v16.17.0
- OS Name: macOS Monterey 12.6
- System Model Name: Macbook Pro
- npm config:
```
; node bin location = /usr/local/bin/node
; node version = v16.17.0
; npm local prefix = /Users/jessegreenough/Documents/Personal_Coding_2022:2023/ReactExchange/client
; npm version = 8.15.0
; cwd = /Users/jessegreenough/Documents/Personal_Coding_2022:2023/ReactExchange/client
; HOME = /Users/jessegreenough
; Run `npm config ls -l` to show all defaults.

```

**Comment by fritzy** [comment]
I'm unable to reproduce with `npm@8.19.2`
@GreenJ84 can you try replicating this problem on the latest version of `npm`? (ie. `npm i -g npm`)
