### ISSUE TITLE
[BUG?] cb() never called!

### ISSUE THREAD

**Issue by supertsy5** [npm/cli#571]
# What / Why

I tried to install electron using `npm install --save-dev electron`, and npm gave me this(and something like `rollbackFailedOptional` for a moment before).  Cleaning cache doesn't fix the problem.

Versions: Ubuntu 19.10,  node v12.13.1(from `sudo n stable` after updated npm),  npm 6.12.1(from `sudo npm install npm@latest -g` with npm 5.8.0 and node v10.15.2 from apt)

## When

* Whenever I install something using npm, but `sudo npm install npm@latest -g` works normally.

## Where

* npm public registry?

### Current Behavior

* Here:
>x7f178735@x7f178735-desktop:~/electron-test$ npm install --save-dev electron  
npm ERR! cb() never called!  
npm ERR! This is an error with npm itself. Please report this error at:  
npm ERR!     <https://npm.community>  
npm ERR! A complete log of this run can be found in:  
npm ERR!     /home/x7f178735/.npm/_logs/2019-12-08T10_33_15_026Z-debug.log  
* 2019-12-08T10_43_02_816Z-debug.log is here:
> 0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save-dev',
1 verbose cli   'electron'
1 verbose cli ]
2 info using npm@6.12.1
3 info using node@v12.13.1
4 verbose npm-session d4ceea4abcc76540
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 timing npm Completed in 16597ms
8 error cb() never called!
9 error This is an error with npm itself. Please report this error at:
10 error <https://npm.community>

### Steps to Reproduce

* Just simply type `npm install --save-dev electron` and press ENTER in Terminal.

### Expected Behavior

* I can't describe the normal behavior exactly(install successfully?), but I know it shouldn't be like this.

## Who

* n/a

## References

* Really a lot of similar issues here.

PS: Please forgive my terribly poor English. I am an amateur programming enthusiast(just googled for this word) in China and a High School student with a not high English mark.

PS2: Reporting a bug(?) is sometime even troublesome than programming. I've spent about 1 hour writing this issue.

**Comment by mikemimik** [comment]
Duplicate issue; aggregating into https://github.com/npm/cli/issues/417.
