### ISSUE TITLE
npm outdated should exit with 0 when only "warnings" are found

### ISSUE THREAD

**Issue by radekmikeska** [npm/cli#5720]
**Description**
When `npm outdated` is run in bash and it finds warnings (all packages are at their wanted version but some are not at the latest version registered in npm registry) it should exit with status code `0` instead of `1`.

**Why**
It is not always desired to use the latest version of the package, and it is fine if `npm outdated` prints this warning, but it should exit with `0` so that it might be used CI/CD pipelines without failing.

**Comment by wraithgar** [comment]
This has been suggested in the past, and discussed in rfc meetings.  This is not something we are going to be changing.  In the future `npm query` is going to be how this kind of thing can be programmatically determined.
