### ISSUE TITLE
Allow omitting runtime dependencies when auditing

### ISSUE THREAD

**Issue by ericcornelissen** [npm/cli#5726]
## Request

I want to request an option to omit runtime dependencies when auditing dependencies using `npm audit`. I would expect it to work identically to `--omit dev`, `--omit optional`, and `--omit peer` but instead for dependencies required through the `"dependencies"` field of `package.json`.

## Reasoning

This may sound like a surprising request, but my reasoning is as follows:

As a "library" - i.e. a package of code that is never run on it's own but only as part of a larger application, ex. [lodash](https://www.npmjs.com/package/lodash) - maintainer I don't necessarily need to worry about vulnerabilities in runtime dependencies. In particular, say my library depends on some dependency and supports `^2.0.0` of that dependency. For most classes of vulnerabilities[^1], if there's a vulnerability in `2.1.0` of this dependency that is not relevant to me as a library maintainer. The library itself will never run the vulnerable code in an interesting setting and users of my library can safely upgrade to `2.1.1` of this dependency whenever they want.

Now, as a library maintainer I could have `^2.0.0` in my manifest and depend on `2.1.1` in my lockfile. However, as a library maintainer I'd (personally) want to depend on exactly the minimum version that is support (`2.0.0` in this case) during development to ensure my library stays compatible with that version of the dependency. Additionally, I (personally) consider bumping the version of a runtime dependency, even within the `^2.0.0` range, a breaking change; **EDIT**: [this statement is incorrect](https://github.com/npm/cli/issues/5726#issuecomment-1284458338). 

Considering all that, I think it should be possible to omit runtime dependencies from the `npm audit` results - because for library maintainers they may not be directly relevant.

If there's anything incorrect about my assessment, please do point it out :slightly_smiling_face: 

[^1]: Using a broad definition of "vulnerabilities" here, in line with what `npm audit` might report on. Things like malware in a dependency would constitute a problem even in the scenario I'm describing.

**Comment by ljharb** [comment]
Have you tried `--omit=prod`?

Separately, it's *in no way* a breaking change to raise the minimum requirement for a non-peer runtime dependency, doing that is the *entire point* of semver ranges.

**Comment by ericcornelissen** [comment]
> Have you tried `--omit=prod`?

I have:

```sh
$ npm audit --omit prod
npm WARN invalid config omit="prod" set in command line options
npm WARN invalid config Must be one or more of: dev, optional, peer
found 0 vulnerabilities

$ npm audit --omit=prod 
npm WARN invalid config omit="prod" set in command line options
npm WARN invalid config Must be one or more of: dev, optional, peer
found 0 vulnerabilities

$ npm version
{
  npm: '8.15.0',
  node: '18.7.0',
  v8: '10.2.154.13-node.9',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '108',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.7',
  openssl: '3.0.5+quic',
  cldr: '41.0',
  icu: '71.1',
  tz: '2022a',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}
```


> Separately, it's _in no way_ a breaking change to raise the minimum requirement for a non-peer runtime dependency, doing that is the _entire point_ of semver ranges.

Interesting, admittedly I wasn't sure about this.

For me to get some more clarity on this, consider this scenario:

1. A project depends on `dependency-a@1.0.0` and `dependency-b@1.0.0`. `dependency-a` depends on (the range) `dependency-c@^2.0.0` and `dependency-b` depends on (exactly) `dependency-c@2.0.1`.
2. `dependency-a` releases v1.0.1 and now depends on `dependency-c@^2.1.0`.
3. The projects upgrades to `dependency-a@1.0.1`.

Does this work? If so, is that because `dependency-a`'s and `dependency-b`'s dependency on `dependency-c` are mutually exclusive?

Additionally, if "doing that is the entire point of semver ranges", what about if `dependency-a` releases v1.0.2 and now depends on `dependency-c@^3.0.0` (as `^3.0.0` isn't within the `^2.0.0` range)?

**Comment by ljharb** [comment]
In npm, because it's a working package manager, dependencies can be duplicated.

As such, it's perfectly fine and expected to have both dependency-c v2.0.1 and v2.1.0 in the same project. There is no conflict as long as the observable API of a package (which includes supported node versions) remains nonbreaking, even if its non-peer runtime dependencies upgrade major versions.

**Comment by ericcornelissen** [comment]
I see, thanks for clarifying @ljharb!

In that case I no longer have a direct need for (something like) `--omit prod` on `npm audit`. I'll leave the decision to close this issue to you(/the npm team) as you might still decide to add support for it.

**Comment by wraithgar** [comment]
omitting production has been discussed in the past and so far there hasn't been a compelling reason to implement it. There aren't any cases where production deps won't be installed after reification, and `npm query` is going to be what filters things in the future.
