### ISSUE TITLE
[BUG] <npm ERR! cb() never called!>

### ISSUE THREAD

**Issue by Ferry72morang** [npm/cli#573]
![image](https://user-images.githubusercontent.com/55728640/70403143-8c3dc200-1a68-11ea-8184-f2c0a19d4335.png)

# What / Why

> n/a

## When

* n/a

## Where

* n/a

### Current Behavior

* n/a

### Steps to Reproduce

* n/a

### Expected Behavior

* n/a

## Who

* n/a

## References

* n/a

**Comment by mikemimik** [comment]
Duplicate issue; aggregating into https://github.com/npm/cli/issues/417.
