### ISSUE TITLE
[BUG] Npm Current version and LTS version 16.18 package install extremely slow.

### ISSUE THREAD

**Issue by mhy-beta** [npm/cli#5738]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

First of all, I tried the same process with the LTS version.
On a newly formatted windows 10 x64 system, git,chocolatey,vs code and node current version are installed.

Moreover, I encountered the same long times, not only for the global installation, but also for the creation of a normal project.
When I try it with NuxtJS and ReactJS, it still takes a very long time to load.

I wanted to install FeathersJS but it takes minutes. I repeated the command again with verbose.
command: npm install --verbose @feathersjs/cli -g

and it takes 7 minutes to do this. Not --verbose 4-5 min.

### Expected Behavior

I think there is a problem with the npm install command. Because what should take seconds takes minutes.

### Steps To Reproduce

1. Remove nodejs windows add/remove programs
2. Download nodejs v19 setup file and execute, complate setup.
3. npm cache clean --force
4. Create new folder and test again, but no --verbose command
5. Run 'npm install @feathersjs/cli -g'
6. ...
npm WARN deprecated tough-cookie@0.9.15: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to 
use Promises in 1.x.)
npm WARN deprecated github@0.1.16: 'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)

added 1431 packages, and audited 1868 packages in 4m

...

### Environment

- npm: 8.19.2
- Node.js: v19.0.0
- OS Name: Microsoft Windows 10
- System Model Name: Not
- npm config:
```ini
; "builtin" config from C:\Program Files\nodejs\node_modules\npm\npmrc

prefix = "C:\\Users\\mhy\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v19.0.0
; npm local prefix = C:\Users\mhy\ReactNative Projects\realtime-todo\server
; npm version = 8.19.2
; cwd = C:\Users\mhy\ReactNative Projects\realtime-todo\server
; HOME = C:\Users\mhy
; Run `npm config ls -l` to show all defaults.
```

**Comment by mhy-beta** [comment]
Format my pc, and install clean windows 10 again, I tested other one (almost 3 minutes):

command: npm install --verbose @feathersjs/cli -g

+ @feathersjs/cli@4.8.0
added 1394 packages from 1233 contributors in 171.423s

node: v14.17.0
npm: 6.14.13

**Comment by Konglomneshued** [comment]
I have the same issue, mine is taking 12+ minutes to run npm install.

Node 18.13.0 LTS
npm 8.19.3

**Comment by nlf** [comment]
you're both running relatively old versions of npm, updating to npm@9.5.0 should help with this to some degree.

other things that you could try include disabling any anti-malware or anti-virus software from scanning the contents of your `node_modules` directories, as well as disabling search indexing in those directories. unfortunately we are aware that npm is noticeably slower in windows, however it shouldn't be to the degree that you're seeing.

another thing that can cause slow installations is the inclusion of git based dependencies. they require cloning, installing and packing before they are installed into your project which can take quite a bit of time. if you have git based dependencies it would help performance rather a lot to publish them to a registry and install from there instead.

give those suggestions a shot and let us know if you're still seeing significant slowdowns.

**Comment by milaninfy** [comment]
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.
