### ISSUE TITLE
[BUG] <title>npm ERR! cb() never called!  npm ERR! This is an error with npm itself. Please report this error at: npm ERR!     <https://npm.community>

### ISSUE THREAD

**Issue by FelixsJeff** [npm/cli#574]
#
> n/a

the contents of the associated log file are

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'info',
1 verbose cli   'cordova'
1 verbose cli ]
2 info using npm@6.13.1
3 info using node@v13.3.0
4 verbose npm-session 8885ffcd267498aa
5 timing npm Completed in 3432ms
6 error cb() never called!
7 error This is an error with npm itself. Please report this error at:
8 error <https://npm.community>

**Comment by mikemimik** [comment]
Duplicate issue; aggregating into https://github.com/npm/cli/issues/417.
