### ISSUE TITLE
[BUG] npm deprecate does not work with scoped packages

### ISSUE THREAD

**Issue by sopranopillow** [npm/cli#5740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When running `npm deprecate @scope/package-name@9.0.x "Message"` in version `8.19.2`, I get the error:
`npm ERR! 404 Not Found - PUT https://registry.npmjs.org/@<scope>%2<package name> - Not found`

It seems it replaces the `/` character for a `%2`.

### Expected Behavior

`npm deprecate` shouldn't replace the `/` character with `%2` from a scoped package.

### Steps To Reproduce

Run `npm deprecate @scope/package-name@9.0.x "Message"`

### Environment

- npm: 8.19.2
- Node.js: v14.20.0
- OS Name: Windows + wsl 2

**Comment by wraithgar** [comment]
The `%2F` is the `/` url encoded. This is intentional.  If you are getting a 404 during deprecation it either means the package does not exist or you do not have access to publish to it.

```sh
~/D/n/cli (main|✔) $ npm deprecate @gar/deprecate-example "This should fail it does not exist"
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@gar%2fdeprecate-example?write=true - Not found
```
