### ISSUE TITLE
[BUG] npm v9.0.0: src/, dist/ was not packed

### ISSUE THREAD

**Issue by aladdin-add** [npm/cli#5741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```json
  "files": [
    "./src/",
    "./dist/"
  ],
```
```bash
➜  dn git:(main) npm pack
npm notice 
npm notice 📦  @dian/dn@0.5.19
npm notice === Tarball Contents === 
npm notice 2.6kB README.md   
npm notice 2.6kB package.json
npm notice === Tarball Details === 
npm notice name:          @dian/dn                                
npm notice version:       0.5.19                                  
npm notice filename:      @dian/dn-0.5.19.tgz                     
npm notice package size:  2.4 kB                                  
npm notice unpacked size: 5.2 kB                                  
npm notice shasum:        7da9625b31463f5fe420732e6e0d428a885a1ae2
npm notice integrity:     sha512-/FDJumc6JZIIl[...]I+P00TGf9VRPw==
npm notice total files:   2                                       
npm notice 
dian-dn-0.5.19.tgz
```

### Expected Behavior

the files in `"src/"` and `"dist/"` should be packed.
I've confirmed it's working fine with npm v8.

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 9.0.0
- Node.js: v19.0.0
- OS Name: macos
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by wraithgar** [comment]
The `files` array does not support the leading `./`, if you remove them it should work.

The entries in `files` are not paths, they are glob patterns. https://docs.npmjs.com/cli/configuring-npm/package-json#files

**Comment by wraithgar** [comment]
```sh
~/D/n/s/pack $ cat package.json
{
  "name": "pack",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "files": [
    "src/",
    "dist/"
  ],
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "Gar <gar+npm@danger.computer>",
  "license": "ISC"
}
~/D/n/s/pack $ npm pack --dry-run
npm notice 
npm notice 📦  pack@1.0.0
npm notice === Tarball Contents === 
npm notice 0B   dist/foo    
npm notice 289B package.json
npm notice 0B   src/bar     
```

**Comment by aladdin-add** [comment]
sounds a regression: https://github.com/npm/cli/issues/4850#issuecomment-1117540803

I didn't see it was mentioned in the release note, if you want it to be a breaking change.

**Comment by wraithgar** [comment]
It was introduced in npm@9 w/ the packlist refactor.  cc @nlf
