### ISSUE TITLE
[BUG] @ scoped packages are excluded from pack, regression from v7

### ISSUE THREAD

**Issue by atkinchris** [npm/cli#5744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Given a wildcard `.npmignore` and `bundleDependencies: true`, when running `npm pack` to produce a bundle of a package, dependencies prefixed with `@` are not included in the bundle.

With `npm@7`, all dependencies were included in the bundle. With `npm@8`, only dependencies which do not start with `@` are included.

### Expected Behavior

With a wildcard `.npmignore` (i.e. `echo "*" > .npmignore`) and `bundleDependencies` set to either `true` (or an array of packages), it is expected that all dependencies are included in the `npm pack` bundle.

## Setup

Create the following files:

`package.json`
```json
{
  "name": "my-package",
  "version": "1.0.0",
  "bundleDependencies": true,
  "dependencies": {
    "@colors/colors": "^1.5.0",
    "uuid": "^9.0.0"
  }
}
```

`.npmignore`
```
*
```

## With version 7

1. Install `npm@7` (`npm install -g npm@7`)
2. Run `npm pack --dry-run`
3. Observe that both dependencies are bundled. ✅
```sh
npm notice === Bundled Dependencies ===
npm notice @colors/colors
npm notice uuid
npm notice === Tarball Details ===
```

## With version 8

1. Install `npm@8` (`npm install -g npm@8`)
2. Run `npm pack --dry-run`
3. Observe that only the non-scoped dependency is bundled. ❌
```sh
npm notice === Bundled Dependencies ===
npm notice uuid
npm notice === Tarball Details ===
```

### Environment

- npm: `8.19.2`
- Node.js: `v16.17.0`
- OS Name: Mac OS
- System Model Name: MacBook Pro
- npm config:
```ini
; node bin location = /Users/[redacted]/.nvm/versions/node/v16.17.0/bin/node
; node version = v16.17.0
; npm local prefix = /Users/[redacted]
; npm version = 8.19.2
; cwd = /Users/[redacted]
; HOME = /Users/[redacted]
; Run `npm config ls -l` to show all defaults.
```

**Comment by atkinchris** [comment]
Digging further, I believe this is a bug in `npm-packlist@5` - which has subsequently been resolved in later versions. 

However, `npm` uses `npm-packlist@5.1.3` - which has this (potential) bug.

```sh
$ npm ls -g npm-packlist

└─┬ npm@8.19.2
  └─┬ pacote@13.6.2
    └── npm-packlist@5.1.3
 ```

**Comment by wraithgar** [comment]
Yes this was a bug we fixed but can't put in npm 8 because the new packlist rules are a breaking change. This should be fixed in npm 9
