### ISSUE TITLE
[BUG] [QUESTION] npm ddp command is not considering prereleases tags

### ISSUE THREAD

**Issue by iwollmann** [npm/cli#5759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I don't know if this should be the default behavior for the `dedupe` command but it's not considering the prerelease tags

![image](https://user-images.githubusercontent.com/997343/198153226-f9e45ae5-c5e4-4e2a-a76f-ac64b4419e80.png)

The first one is how the `dedupe` is currently calling the `semver.satisfies` and the second one is how to include the prerelease tags. So my question is, is this the current expected behavior? If yes, shouldn't we add an option on the `dedupe` command to consider this case?

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: v8.19.2
- Node.js: v14.19.0

**Comment by ljharb** [comment]
I think it's expected; prereleases are explicitly not included in semver ranges that don't explicitly include them.

**Comment by wraithgar** [comment]
@ljharb is correct this is by design.  We do not want to add a flag for npm to ignore what is in a package's manifest.  This is why it is a "pre" release. It's not released and packages shouldn't get it unless they are specifically asking for it.

**Comment by iwollmann** [comment]
@wraithgar but how can I test my prerelease versions in this case? Is there another way to force my sub-dependencies to use my prerelease versions?

**Comment by ljharb** [comment]
@iwollmann with overrides, or with `npm link`.
