### ISSUE TITLE
Update the docs for package-lock.json

### ISSUE THREAD

**Issue by skvlakov** [npm/cli#5772]
https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json
---
In the doc you are describing how perfectly package-lock.json guards the versions in the package.json. You are just ignorant to beginner users and don't describe the most important aspect which is "how the package-lock.json" is doing it.
Please, mention in the doc:
npm init - it will use the package-lock.json to install the exact versions of packages recorded in the package-lock.json
npm ci - clean install - it will use the package-lock.json to install exact versions of packages.
Thank you.

**Comment by wraithgar** [comment]
The docs are in this repo and if you want to suggest changes a PR is welcome.
