### ISSUE TITLE
[BUG] npm prune doesn't remove the extraneous packages from node_modules

### ISSUE THREAD

**Issue by ericmorand** [npm/cli#5803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When removing a dependency manually in `package.json`, and then executing `npm prune`, the package is still present in node_module alongside (of course) its own dependencies.

### Expected Behavior

When removing a dependency manually in `package.json`, and then executing `npm prune`, the package removed from node_module as well as (of course) its own dependencies.

### Steps To Reproduce

* Create a new npm project using `npm init -y`
* add an `.npmrc` file that contains `package-lock=false`
* install a dependency
* remove this dependency from package.json
* run `npm prune`
* look at the content of node_module

### Environment

- npm: 8.15.0
- Node.js: 16.17.0
- OS Name: Linux XUbuntu 20.04
- System Model Name: Dell Something
- npm config:
```ini
; "global" config from /home/emorand/.nvm/versions/node/v16.17.0/etc/npmrc

; "user" config from /home/emorand/.npmrc

; node bin location = /home/emorand/.nvm/versions/node/v16.17.0/bin/node
; node version = v16.17.0
; npm local prefix = /home/emorand/Projects/npm-prune
; npm version = 8.15.0
; cwd = /home/emorand/Projects/npm-prune
; HOME = /home/emorand
; Run `npm config ls -l` to show all defaults.

```

**Comment by milaninfy** [comment]
Not able to reproduce with the steps. Issue might have been fixed if it existed before. Please update the npm version and check. 

with npm@8
```bash
~/workarea/rep $ npm ls
rep@1.0.0 /Users/test/workarea/rep
└── lodash@4.17.21

~/workarea/rep $ vi package.json

~/workarea/rep $ npm ls
rep@1.0.0 /Users/test/workarea/rep
└── lodash@4.17.21 extraneous

~/workarea/rep $ npm prune

removed 1 package, and audited 1 package in 267ms

found 0 vulnerabilities
~/workarea/rep $ npm -v
8.19.4
~/workarea/rep $ ls node_modules 
```

with npm@9
```
~/workarea/rep $ npm ls
rep@1.0.0 /Users/test/workarea/rep
└── lodash@4.17.21

~/workarea/rep $ vi package.json
~/workarea/rep $ npm ls
rep@1.0.0 /Users/test/workarea/rep
└── lodash@4.17.21 extraneous

~/workarea/rep $ npm prune

removed 1 package, and audited 1 package in 275ms

found 0 vulnerabilities
~/workarea/rep $ npm ls
rep@1.0.0 /Users/test/workarea/rep
└── (empty)

~/workarea/rep $ npm -v
9.9.3
```
