### ISSUE TITLE
[BUG] `npm view <pkg>@<spec>` prints info for every matching version

### ISSUE THREAD

**Issue by billyjanitsch** [npm/cli#5804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`npm view <pkg>@<spec>` prints the package information for every matching version of that package.

### Expected Behavior

I expect it to print the package information for only a single version (the resolution of the spec, as with `npm install <pkg>@<spec>`). This was the behavior in npm@8. I don't see this mentioned as an intentional change in the changelog, so it seems like a regression.

### Steps To Reproduce

1. Install `npm@9`.
2. Run `npm view react@18`.
3. Notice that there are multiple outputs (at time of writing, for `react@18.0.0`, `react@18.1.0`, and `react@18.2.0`).
4. Install `npm@8`.
5. Run `npm view react@18`.
6. Notice that there is only one output (for `react@18.2.0`).

### Environment

- npm: 9.0.1
- Node.js: 18.12.0
- OS Name: macOS
- System Model Name: MacBook Pro
- npm config:
```ini
; n/a
```

**Comment by darcyclarke** [comment]
Hey @billyjanitsch! We can't seem to reproduce your issue. Notably, `npm view` will return multiple results for version ranges (ex. `>=1` or `*`). `npm` v6/v7/v8/v9 all return multiple versions when you pass `view` an unqualified package spec (ie. `foo@1` will get expanded to `foo@1.*` - a range - vs. `foo@1.0.0` which is a specific version, so only one result is returned)

Here's the output we're seeing:

```bash
❯ npm --version
8.19.2

❯ npm view react@18 | grep react@
react@18.0.0 | MIT | deps: 1 | versions: 1120
react@18.1.0 | MIT | deps: 1 | versions: 1120
react@18.2.0 | MIT | deps: 1 | versions: 1120

# using jq to check the # of versions returned
❯ npm view react@18 --json | jq 'length'
3
```

**Comment by wraithgar** [comment]
This was the behavior in npm 6 as well.

```sh
$ npx npm@6 view react@18|grep "react"|grep @
react@18.0.0 | MIT | deps: 1 | versions: 1128
react@18.1.0 | MIT | deps: 1 | versions: 1128
react@18.2.0 | MIT | deps: 1 | versions: 1128
```

and npm 7

```sh
$ npx npm@7 view react@18|grep "react"|grep @
react@18.0.0 | MIT | deps: 1 | versions: 1128
react@18.1.0 | MIT | deps: 1 | versions: 1128
react@18.2.0 | MIT | deps: 1 | versions: 1128
```
