### ISSUE TITLE
Getting TypeError: Net.connect is not a function when I try to run createConnection in mysql2 with Next.js

### ISSUE THREAD

**Issue by tdobrian** [npm/cli#5806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I'm trying to query a MySQL DB using mysql2 for Next.js. The results of the query are displaying correctly in the console, but instead of the results showing in the browser I get an error. VS code tells me that the error is at the period between mysql and createConnection in the line const connection = mysql.createConnection({. 
I am calling const mysql = require('mysql') before that. The error I get is "TypeError: Net.connect is not a function". 
I've done many Google searches on this and have tried reinstalling every related program and library about 4 or 5 times. I've also tried older versions of each program and library. Before this problem, I got errors from Next.js not being able to find the fs and tls modules, but I installed them with npm i fs and npm i tls and those errors went away. I know the query is going through because it the results are showing up in the console.

### Expected Behavior

I expect the code to put the query results on the browser page, without displaying an error.

### Steps To Reproduce

1. In this environment...
The program is being run in Next.js

2. With this config...

I'm using the following dependencies:

"dependencies": {
    "@fortawesome/fontawesome-svg-core": "^6.2.0",
    "@fortawesome/free-solid-svg-icons": "^6.2.0",
    "@fortawesome/react-fontawesome": "^0.2.0",
    "bluebird": "^3.7.2",
    "cardinal": "^2.1.1",
    "fs": "^0.0.1-security",
    "mysql2": "^2.3.3",
    "net": "^1.0.2",
    "next": "^12.3.1",
    "next-connect": "^0.13.0",
    "path": "npm:path-browserify@^1.0.1",
    "react": "^18.2.0",
    "react-devtools": "^4.26.1",
    "react-dom": "^18.2.0",
    "tls": "^0.0.1",
    "webpack": "^5.74.0"
  },
  "devDependencies": {
    "eslint": "8.24.0",
    "eslint-config-next": "12.3.1"
  },
  
3. Run '...'

const GetData = () => {
  // get the client
  
  const mysql = require('mysql2');
  // create the connection to database
  const connection = mysql.createConnection({
    host: 'localhost',
    user: 'root',
    password: 'password',
    database: 'genicsApp',
  });

  // simple query
  connection.query(
    'SELECT firstName,lastName,lastLogin ' + 
    'FROM genicsAppUser;', 
    function(err, results, fields) {
      console.log(results); // results contains rows returned by server
      // console.log(fields); // fields contains extra meta data about results, if available
      return (
        <div>
          <h1>Get Data</h1>
          <h1>{results}
          </h1>
          </div>)  
    },
  );
}

export default GetData

4. See error...

TypeError: Net.connect is not a function

It says the error is at the period between mysql and createConnection.

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by wraithgar** [comment]
This doesn't appear to be an npm issue

**Comment by big-dudu-mosty** [comment]
我也遇到了这个问题，请问你解决了吗？这是模块冲突吗？
