### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by 2tab** [npm/cli#581]
[2019-12-10T15_54_18_149Z-debug.log](https://github.com/npm/cli/files/3945844/2019-12-10T15_54_18_149Z-debug.log)

### Installed node using brew on Mojave OsX
>>> tried to install vue using node: npm install -g @vue/cli
but turned out cb() was never called and i was encouraged to drop a line.
Thank you

**Comment by mikemimik** [comment]
Duplicate issue; aggregating into https://github.com/npm/cli/issues/417.
