### ISSUE TITLE
[BUG] --omit=dev doesn't work when installing from github

### ISSUE THREAD

**Issue by gabrielgrant** [npm/cli#5826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

using ``omit=dev` flag doesn't seem to work when installing from a github repo -- the install tries to install the dev deps and fails with errors related to those dev deps. it appears to not be passing along the flag, and instead be running the following command to actually install the package after fetching:

```
 /home/gabriel/.nvm/versions/node/v16.15.1/bin/node /home/gabriel/.nvm/versions/node/v16.15.1/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/gabriel/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
```

### Expected Behavior

running install with `omit=dev` should not try to install dev deps

### Steps To Reproduce

```
$ npm install https://github.com/gabrielgrant/iframe-resizer#fix-jquery-checks --save-prod  --omit=dev
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /home/gabriel/.nvm/versions/node/v16.15.1/bin/node /home/gabriel/.nvm/versions/node/v16.15.1/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/gabriel/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
...
```

Note the command executed (it includes `--include=dev`), and a bunch of warnings and/or errors from dev dependencies that shouldn't be getting installed

### Environment

- npm: 8.19.3
- Node.js: v16.15.1
- OS Name: Ubuntu
- System Model Name: Ubuntu 18.04.2 LTS
- npm config:
```ini
; "project" config from /home/gabriel/repos/alton-mill-astro/.npmrc

shamefully-hoist = true

; node bin location = /home/gabriel/.nvm/versions/node/v16.15.1/bin/node
; node version = v16.15.1
; npm local prefix = /home/gabriel/repos/alton-mill-astro
; npm version = 8.19.3
; cwd = /home/gabriel/repos/alton-mill-astro
; HOME = /home/gabriel
; Run `npm config ls -l` to show all defaults.
```

**Comment by wraithgar** [comment]
git dependencies always install dev dependencies by design, this is because many of them have `build` scripts that npm will run in order to make them work.

**Comment by gabrielgrant** [comment]
so there's really supposed to be no way at all to install from a git repo without installing dev deps? that seems like a reasonable default, but seems a bit surprising that explicitly disabling dev deps would just be silently ignored

**Comment by wraithgar** [comment]
This is ignored because "installing dev deps" is a signal to npm only insofar as what is in the package.json of your package, not the dependencies its installing.  That flag doesn't ever affect anything else.

When a dependency is installed by npm, its dev dependencies are never installed even though the config setting is telling npm to install dev dependencies.  Conversely, git dependencies always have THEIR dev dependencies installed for reasons described above.

It's a subtle difference to be sure, especially because optional and peer dependency settings DO change what subdependencies get installed.  The dev flag however never changes what is in node_modules.
