### ISSUE TITLE
[BUG] `npm view` does not correctly resolve local-only packages

### ISSUE THREAD

**Issue by legodude17** [npm/cli#5834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I have a local package that I have not published yet: `noclis`. I wanted to see want info npm would get from it before I publish, so I ran `npm view .`. This, however, produced an error:
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/noclis - Not found
npm ERR! 404
npm ERR! 404  'noclis@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```
This error message was confusing for two reasons:
1. It says "install" even though I'm not installing anything
2. It says I can use a folder, but that's what I did and it didn't work.

### Expected Behavior

Either:
1. Correctly fetch and infer data for my local package.
2. Output an error that explains that you can only `npm view` something in the registry.

### Steps To Reproduce

1. `mkdir npm-test-view-local` Any name that doesn't exist in the registry works.
2. `cd npm-test-view-local`
3. `npm init -y`
4. `npm view .`
5. See error:
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/npm-test-view-local - Not found
npm ERR! 404
npm ERR! 404  'npm-test-view-local@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

### Environment

- npm: 9.1.0
- Node.js: v19.0.0
- OS Name: macOS Monterey Version 12.6
- System Model Name: MacBook Prop
- npm config:
```ini
; "user" config from /Users/[REDACTED]/.npmrc

//registry.npmjs.org/:_authToken = (protected)
python = "python3"

; "cli" config from command line options

location = "project"

; node bin location = /Users/[REDACTED]/.nvm/versions/node/v19.0.0/bin/node
; node version = v19.0.0
; npm local prefix = /Users/[REDACTED]/code/node/npm-test-view-local
; npm version = 9.1.0
; cwd = /Users/[REDACTED]/code/node/npm-test-view-local
; HOME = /Users/[REDACTED]
; Run `npm config ls -l` to show all defaults.
```

**Comment by wraithgar** [comment]
`npm view` only works in the context of fetching package data from the registry.  The only thing it will look for if given a directory is the package name, which it uses to ask the registry for information on that package including things like when it was last published, the tarball location, dist-tags, maintainers, etc.

**Comment by legodude17** [comment]
In that case, could you make the error message clearer? Since it says "Note that you can also install from a tarball, folder, http url, or git url" in the error I would expect that to be the case.

**Comment by akhenry** [comment]
> In that case, could you make the error message clearer? Since it says "Note that you can also install from a tarball, folder, http url, or git url" in the error I would expect that to be the case.

I guess they couldn't 😄  Hitting the same issue in 2026 with the same misleading error message.
