### ISSUE TITLE
[BUG] Issue updating globally to `latest`

### ISSUE THREAD

**Issue by ghost** [npm/cli#5839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Enhancement, not another kind of Docs Enhancement.

- [X] This is a CLI Docs Enhancement.

### Description of Problem

Hi, I've been have an issue with npm@latest, It's run until v7.2.24 the previous latest version but now it doesn't works

![Issue with NPM latest version installation](https://user-images.githubusercontent.com/22520811/201056986-f0b3b8cd-7f15-46d1-a3c7-7bb1b21f4308.png)

### Potential Solution

I've not any one to fix this issue right now.

### Docs URL

https://nodejs.org

**Comment by peterjaap** [comment]
We are also running into issues in our pipelines where we use the latest version.

This worked in 9.1.0;

```
$ npm --unsafe-perm --prefix $REACT_CHECKOUT_PATH ci --omit=optional
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
> client-react-checkout@1.0.3 preinstall
> node scripts/configurePaymentMethods
Payment methods successfully added
added 1547 packages, and audited 1549 packages in 37s
228 packages are looking for funding
  run `npm fund` for details
9 vulnerabilities (8 high, 1 critical)
To address issues that do not require attention, run:
  npm audit fix
To address all issues (including breaking changes), run:
  npm audit fix --force
Run `npm audit` for details.
```

But breaks in 9.1.1;

```
$ npm --unsafe-perm --prefix $REACT_CHECKOUT_PATH ci --omit=optional
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /builds/client/magento2/vendor/hyva-themes/magento2-react-checkout/src/reactapp/src/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/builds/client/magento2/vendor/hyva-themes/magento2-react-checkout/src/reactapp/src/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-11-10T10_09_04_013Z-debug-0.log
```

**Comment by ghost** [comment]
But how i fix my issue, it's different than the above issue?

**Comment by peterjaap** [comment]
No idea, I just found an issue that referred to issues with the latest version, so I added my experience.

**Comment by wraithgar** [comment]
@senseijurado this does not appear to be a docs issue.  It's important to use the correct issue template so we can properly get the steps to reproduce from you.

@peterjaap please do not add unrelated comments to issues. It almost guarantees that your particular issue is not going to be resolved, and complicates the existing one.

**Comment by ghost** [comment]
Where i should appear about you? I don't handle this GitHub's Section
