### ISSUE TITLE
When I run npm install with 13.2.0 version ,  prompt cb() never called!

### ISSUE THREAD

**Issue by zhaohx** [npm/cli#584]
npm WARN deprecated fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size
npm WARN deprecated core-js@1.2.7: core-js@<3.0 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
[            ......] | extract:rxjs: sill extract rxjs@^6.5.2 extracted to /mnt/d/work/luoshu/node_modules/.staging/rxj
[            ......] | extract:rxjs: sill extract rxjs@^6.5.2 extracted to /mnt/d/work/luoshu/node_modules/.staging/rxj
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zhaohx/.npm/_logs/2019-12-11T10_27_58_941Z-debug.log

**Comment by mikemimik** [comment]
Duplicate issue; aggregating into https://github.com/npm/cli/issues/417.
