### ISSUE TITLE
[BUG] <Problem installing npm install -g node-gyp>

### ISSUE THREAD

**Issue by DevAshleyD** [npm/cli#585]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'node-gyp'
1 verbose cli ]
2 info using npm@6.13.1
3 info using node@v13.0.1
4 verbose npm-session 48b186e574a11571
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/node-gyp 398ms (from cache)
8 silly pacote tag manifest for node-gyp@latest fetched in 437ms
9 timing stage:loadCurrentTree Completed in 502ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 2ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule node-gyp@6.0.1 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/env-paths 461ms (from cache)
18 silly pacote range manifest for env-paths@^2.2.0 fetched in 467ms
19 silly resolveWithNewModule env-paths@2.2.0 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/which 381ms (from cache)
21 silly pacote range manifest for which@^1.3.1 fetched in 390ms
22 silly resolveWithNewModule which@1.3.1 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/semver 847ms (from cache)
24 http fetch GET 304 https://registry.npmjs.org/graceful-fs 865ms (from cache)
25 http fetch GET 304 https://registry.npmjs.org/rimraf 857ms (from cache)
26 http fetch GET 304 https://registry.npmjs.org/request 859ms (from cache)
27 http fetch GET 304 https://registry.npmjs.org/mkdirp 872ms (from cache)
28 silly pacote range manifest for semver@^5.7.1 fetched in 866ms
29 silly resolveWithNewModule semver@5.7.1 checking installable status
30 http fetch GET 304 https://registry.npmjs.org/glob 880ms (from cache)
31 http fetch GET 304 https://registry.npmjs.org/tar 868ms (from cache)
32 http fetch GET 304 https://registry.npmjs.org/npmlog 874ms (from cache)
33 silly pacote range manifest for graceful-fs@^4.2.2 fetched in 886ms
34 silly resolveWithNewModule graceful-fs@4.2.3 checking installable status
35 http fetch GET 304 https://registry.npmjs.org/nopt 881ms (from cache)
36 silly pacote range manifest for request@^2.88.0 fetched in 880ms
37 silly resolveWithNewModule request@2.88.0 checking installable status
38 silly pacote range manifest for rimraf@^2.6.3 fetched in 879ms
39 silly resolveWithNewModule rimraf@2.7.1 checking installable status
40 silly pacote range manifest for mkdirp@^0.5.1 fetched in 890ms
41 silly resolveWithNewModule mkdirp@0.5.1 checking installable status
42 silly pacote range manifest for tar@^4.4.12 fetched in 879ms
43 silly resolveWithNewModule tar@4.4.13 checking installable status
44 silly pacote range manifest for glob@^7.1.4 fetched in 895ms
45 silly resolveWithNewModule glob@7.1.6 checking installable status
46 silly pacote range manifest for npmlog@^4.1.2 fetched in 887ms
47 silly resolveWithNewModule npmlog@4.1.2 checking installable status
48 silly pacote range manifest for nopt@^4.0.1 fetched in 889ms
49 silly resolveWithNewModule nopt@4.0.1 checking installable status
50 http fetch GET 304 https://registry.npmjs.org/inflight 210ms (from cache)
51 silly pacote range manifest for inflight@^1.0.4 fetched in 212ms
52 silly resolveWithNewModule inflight@1.0.6 checking installable status
53 http fetch GET 304 https://registry.npmjs.org/fs.realpath 241ms (from cache)
54 silly pacote range manifest for fs.realpath@^1.0.0 fetched in 243ms
55 silly resolveWithNewModule fs.realpath@1.0.0 checking installable status
56 http fetch GET 304 https://registry.npmjs.org/path-is-absolute 347ms (from cache)
57 http fetch GET 304 https://registry.npmjs.org/once 350ms (from cache)
58 http fetch GET 304 https://registry.npmjs.org/inherits 353ms (from cache)
59 silly pacote range manifest for path-is-absolute@^1.0.0 fetched in 353ms
60 silly resolveWithNewModule path-is-absolute@1.0.1 checking installable status
61 silly pacote range manifest for once@^1.3.0 fetched in 356ms
62 silly resolveWithNewModule once@1.4.0 checking installable status
63 http fetch GET 304 https://registry.npmjs.org/minimatch 359ms (from cache)
64 silly pacote range manifest for inherits@2 fetched in 361ms
65 silly resolveWithNewModule inherits@2.0.4 checking installable status
66 silly pacote range manifest for minimatch@^3.0.4 fetched in 362ms
67 silly resolveWithNewModule minimatch@3.0.4 checking installable status
68 http fetch GET 304 https://registry.npmjs.org/wrappy 131ms (from cache)
69 silly pacote range manifest for wrappy@1 fetched in 134ms
70 silly resolveWithNewModule wrappy@1.0.2 checking installable status
71 http fetch GET 304 https://registry.npmjs.org/brace-expansion 95ms (from cache)
72 silly pacote range manifest for brace-expansion@^1.1.7 fetched in 97ms
73 silly resolveWithNewModule brace-expansion@1.1.11 checking installable status
74 http fetch GET 304 https://registry.npmjs.org/balanced-match 147ms (from cache)
75 http fetch GET 304 https://registry.npmjs.org/concat-map 147ms (from cache)
76 silly pacote range manifest for balanced-match@^1.0.0 fetched in 150ms
77 silly resolveWithNewModule balanced-match@1.0.0 checking installable status
78 silly pacote version manifest for concat-map@0.0.1 fetched in 152ms
79 silly resolveWithNewModule concat-map@0.0.1 checking installable status
80 http fetch GET 304 https://registry.npmjs.org/minimist 123ms (from cache)
81 silly pacote version manifest for minimist@0.0.8 fetched in 125ms
82 silly resolveWithNewModule minimist@0.0.8 checking installable status
83 http fetch GET 304 https://registry.npmjs.org/abbrev 115ms (from cache)
84 http fetch GET 304 https://registry.npmjs.org/osenv 117ms (from cache)
85 silly pacote range manifest for abbrev@1 fetched in 118ms
86 silly resolveWithNewModule abbrev@1.1.1 checking installable status
87 silly pacote range manifest for osenv@^0.1.4 fetched in 120ms
88 silly resolveWithNewModule osenv@0.1.5 checking installable status
89 http fetch GET 304 https://registry.npmjs.org/os-tmpdir 85ms (from cache)
90 silly pacote range manifest for os-tmpdir@^1.0.0 fetched in 89ms
91 silly resolveWithNewModule os-tmpdir@1.0.2 checking installable status
92 http fetch GET 304 https://registry.npmjs.org/os-homedir 127ms (from cache)
93 silly pacote range manifest for os-homedir@^1.0.0 fetched in 129ms
94 silly resolveWithNewModule os-homedir@1.0.2 checking installable status
95 http fetch GET 304 https://registry.npmjs.org/console-control-strings 113ms (from cache)
96 silly pacote range manifest for console-control-strings@~1.1.0 fetched in 147ms
97 silly resolveWithNewModule console-control-strings@1.1.0 checking installable status
98 http fetch GET 304 https://registry.npmjs.org/are-we-there-yet 177ms (from cache)
99 http fetch GET 304 https://registry.npmjs.org/gauge 178ms (from cache)
100 silly pacote range manifest for are-we-there-yet@~1.1.2 fetched in 181ms
101 silly resolveWithNewModule are-we-there-yet@1.1.5 checking installable status
102 http fetch GET 304 https://registry.npmjs.org/set-blocking 182ms (from cache)
103 silly pacote range manifest for gauge@~2.7.3 fetched in 184ms
104 silly resolveWithNewModule gauge@2.7.4 checking installable status
105 silly pacote range manifest for set-blocking@~2.0.0 fetched in 185ms
106 silly resolveWithNewModule set-blocking@2.0.0 checking installable status
107 http fetch GET 304 https://registry.npmjs.org/delegates 149ms (from cache)
108 silly pacote range manifest for delegates@^1.0.0 fetched in 151ms
109 silly resolveWithNewModule delegates@1.0.0 checking installable status
110 http fetch GET 304 https://registry.npmjs.org/readable-stream 155ms (from cache)
111 silly pacote range manifest for readable-stream@^2.0.6 fetched in 165ms
112 silly resolveWithNewModule readable-stream@2.3.6 checking installable status
113 http fetch GET 304 https://registry.npmjs.org/core-util-is 334ms (from cache)
114 http fetch GET 304 https://registry.npmjs.org/safe-buffer 334ms (from cache)
115 http fetch GET 304 https://registry.npmjs.org/process-nextick-args 337ms (from cache)
116 http fetch GET 304 https://registry.npmjs.org/string_decoder 338ms (from cache)
117 silly pacote range manifest for core-util-is@~1.0.0 fetched in 341ms
118 silly resolveWithNewModule core-util-is@1.0.2 checking installable status
119 silly pacote range manifest for safe-buffer@~5.1.1 fetched in 342ms
120 silly resolveWithNewModule safe-buffer@5.1.2 checking installable status
121 silly pacote range manifest for process-nextick-args@~2.0.0 fetched in 344ms
122 silly resolveWithNewModule process-nextick-args@2.0.1 checking installable status
123 http fetch GET 304 https://registry.npmjs.org/isarray 345ms (from cache)
124 silly pacote range manifest for string_decoder@~1.1.1 fetched in 345ms
125 silly resolveWithNewModule string_decoder@1.1.1 checking installable status
126 http fetch GET 304 https://registry.npmjs.org/util-deprecate 346ms (from cache)
127 silly pacote range manifest for isarray@~1.0.0 fetched in 348ms
128 silly resolveWithNewModule isarray@1.0.0 checking installable status
129 silly pacote range manifest for util-deprecate@~1.0.1 fetched in 348ms
130 silly resolveWithNewModule util-deprecate@1.0.2 checking installable status
131 http fetch GET 304 https://registry.npmjs.org/aproba 197ms (from cache)
132 silly pacote range manifest for aproba@^1.0.3 fetched in 200ms
133 silly resolveWithNewModule aproba@1.2.0 checking installable status
134 http fetch GET 304 https://registry.npmjs.org/has-unicode 353ms (from cache)
135 http fetch GET 304 https://registry.npmjs.org/signal-exit 354ms (from cache)
136 http fetch GET 304 https://registry.npmjs.org/wide-align 354ms (from cache)
137 http fetch GET 304 https://registry.npmjs.org/object-assign 359ms (from cache)
138 silly pacote range manifest for has-unicode@^2.0.0 fetched in 360ms
139 silly resolveWithNewModule has-unicode@2.0.1 checking installable status
140 http fetch GET 304 https://registry.npmjs.org/string-width 360ms (from cache)
141 silly pacote range manifest for wide-align@^1.1.0 fetched in 363ms
142 silly resolveWithNewModule wide-align@1.1.3 checking installable status
143 silly pacote range manifest for signal-exit@^3.0.0 fetched in 366ms
144 silly resolveWithNewModule signal-exit@3.0.2 checking installable status
145 silly pacote range manifest for object-assign@^4.1.0 fetched in 369ms
146 silly resolveWithNewModule object-assign@4.1.1 checking installable status
147 silly pacote range manifest for string-width@^1.0.1 fetched in 369ms
148 silly resolveWithNewModule string-width@1.0.2 checking installable status
149 http fetch GET 304 https://registry.npmjs.org/strip-ansi 369ms (from cache)
150 silly pacote range manifest for strip-ansi@^3.0.1 fetched in 374ms
151 silly resolveWithNewModule strip-ansi@3.0.1 checking installable status
152 http fetch GET 304 https://registry.npmjs.org/code-point-at 105ms (from cache)
153 silly pacote range manifest for code-point-at@^1.0.0 fetched in 108ms
154 silly resolveWithNewModule code-point-at@1.1.0 checking installable status
155 http fetch GET 304 https://registry.npmjs.org/is-fullwidth-code-point 145ms (from cache)
156 silly pacote range manifest for is-fullwidth-code-point@^1.0.0 fetched in 152ms
157 silly resolveWithNewModule is-fullwidth-code-point@1.0.0 checking installable status
158 http fetch GET 304 https://registry.npmjs.org/number-is-nan 89ms (from cache)
159 silly pacote range manifest for number-is-nan@^1.0.0 fetched in 91ms
160 silly resolveWithNewModule number-is-nan@1.0.1 checking installable status
161 timing npm Completed in 4740ms
162 error cb() never called!
163 error This is an error with npm itself. Please report this error at:
164 error <https://npm.community>

**Comment by mikemimik** [comment]
Duplicate issue; aggregating into https://github.com/npm/cli/issues/417.
