### ISSUE TITLE
[BUG] NPM v9 lose directory structure and pack/publish  empty package

### ISSUE THREAD

**Issue by adenisovgit** [npm/cli#5853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

when using npm >9 pack or publish produced empty package, just few headers

➜  pss-components git:(feature/PSS-390/componentsUpgrades) ✗ npm -v      
9.1.1
➜  pss-components git:(feature/PSS-390/componentsUpgrades) ✗ npm pack    
<img width="957" alt="image" src="https://user-images.githubusercontent.com/9318214/201718629-0e46577f-66f9-4f89-b2c7-ce3e59865d25.png">

### Expected Behavior

➜  pss-components git:(feature/PSS-390/componentsUpgrades) ✗ npm -v
8.19.3
➜  pss-components git:(feature/PSS-390/componentsUpgrades) ✗ npm pack
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/9318214/201717950-46071742-2998-4e69-b8e2-ac46a314b330.png">

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 9.1.1
- Node.js: 16.15
- OS Name: macOs 12.6
- System Model Name: 
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by wraithgar** [comment]
There is not enough here to reproduce the issue.  Notably the `Steps To Reproduce` entry has not been filled in.

**Comment by wraithgar** [comment]
npm 9 changed how it parses its include/ignore lists.  Please be sure to give a reproduction case that includes the contents of the package.json files, and any gitignore/npmignore files.

**Comment by nexdrew** [comment]
Note that I had a package using this glob pattern in package.json:

```
  "files": [
    "lib/*"
  ]
```

Using npm 8, doing `npm pack .` would include any directories (and the modules within those directories) under `lib`.

Using npm 9, `npm pack .` would no longer include the directories (or their submodules) under `lib`.

Changing the glob pattern to this fixed the problem:

```
  "files": [
    "lib/**"
  ]
```

If helpful, I can create a repository to reproduce this.

**Comment by nexdrew** [comment]
I suppose using this declaration would have been better in my case:

```
  "files": [
    "lib"
  ]
```

**Comment by wraithgar** [comment]
```
~/D/n/s/glob $ npm pkg get files
"dir/*"
```



```
~/D/n/s/glob $ npx npm@8 publish --dry-run
npm notice 
npm notice 📦  files-example@1.0.0
npm notice === Tarball Contents === 
npm notice 0B   dir/sub/deepsub/file4.txt
npm notice 0B   dir/sub/file1.txt        
npm notice 0B   dir/sub2/file2.txt       
npm notice 286B package.json            
```

```
~/D/n/s/glob $ npx npm@9 publish --dry-run
npm notice
npm notice :package: files-example@1.0.0
npm notice === Tarball Contents ===
npm notice 286B package.json
```

**Comment by adenisovgit** [comment]
> I suppose using this declaration would have been better in my case:
> 
> ```
>   "files": [
>     "lib"
>   ]
> ```

That helps, thank you.
