### ISSUE TITLE
[BUG] Cannot install npm latest on Windows Node.js 14

### ISSUE THREAD

**Issue by peterjuras** [npm/cli#5856]
Hi,

When running Node.js 14 on Windows, updating npm to the latest version (now 9) fails. Could you please investigate and fix the cause of this?

Issue that surfaced this: https://github.com/actions/setup-node/issues/623

**Comment by darcyclarke** [comment]
@peterjuras could you please use [our issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+9.x&template=bug_9.yml&title=%5BBUG%5D+%3Ctitle%3E). We need certain information to be able to properly debug/reproduce (ex. current version of `npm` / `node` environment/config information etc.) - there may be something unique about your situation which we aren't aware of.

**Comment by wraithgar** [comment]
This is an npm 6 bug.  You are going to have to leapfrog from a version of npm that npm 6 can install (i.e. npm 8) and from there install 9.  We will be updating https://github.com/npm/cli/issues/5862 so folks can more easily know about this.
