### ISSUE TITLE
Getting Error while executing cmd

### ISSUE THREAD

**Issue by vedxp** [npm/cli#5857]
Here's the error: 
```rb
Your cache folder contains root-owned files,
due to a bug in previous versions of npm which has since been addressed.
To permanently fix this problem, please run:
sudo chown -R 10405:10405 "/data/data/com.termux/files/home/.npm"
```

---

### Here's the screenshot:
>  ![Screenshot_20221115-192757](https://user-images.githubusercontent.com/87353286/201940079-9ebc0c11-359e-4432-bb00-689d95d3fe83.png)

---

Info:
- I've tried clearing app data of Termux, which I'm using.
- I've no root access.
-

**Comment by wraithgar** [comment]
Did you run `sudo npm` at any point?

**Comment by wraithgar** [comment]
@VedxP can you please fill out the issue template fully?  We don't even know what version of npm you're running, or what steps to take to reproduce this.
