### ISSUE TITLE
Upgrading from `v6.x` FAQ (WIP)

### ISSUE THREAD

**Issue by darcyclarke** [npm/cli#5862]

**Comment by NSG-LLC** [comment]
NSG-LLC/cli,

**Comment by NSG-LLC** [comment]
NSG-LLC/cli,

**Comment by DeeDeeG** [comment]
Hi folks.

Sorry to bother, but I think it'd be good to mention https://github.com/npm/cli/issues/5856 here. (Or maybe pin that one, if there is no upgrade FAQ?)

(Although the title of https://github.com/npm/cli/issues/5856 doesn't clarify that the NodeJS version doesn't _technically_ matter for the issue -- according to https://github.com/npm/cli/issues/5856#issuecomment-1317755924 it's an npm v6.x bug. I can confirm from some quick testing that it happens on any currently supported NodeJS version. When using npm v6.x to install v9.x over itself on Windows with `npm install -g npm`, it gives an error.)

(As folks may know, NodeJS 14.x comes with npm v6.x, and [NodeJS 14.x is LTS and supported until 2023 April 30th](https://github.com/nodejs/release#release-schedule). So, I reckon some people will be looking for this info, particularly between now and next May.)

Best regards.
