### ISSUE TITLE
[BUG] Specifying dependencies using local paths broken between 8.19.3 and 9.1.1

### ISSUE THREAD

**Issue by mind-bending-forks** [npm/cli#5864]
At version 8.19.3 and prior, referencing a dependency via a local path in `package.json` as follows, and running `npm install`, worked:

```json
{
  "dependencies": {
    "@myorg/mylib": "file:./myorg/mylib"
  }
}
```

From 9.1.1, `npm install` fails with

> npm WARN tarball tarball data for mylib@file:/path/from/root/node_modules/@myorg/mylib (null) seems to be corrupted. Trying again.
> npm WARN tarball tarball data for mylib@file:/path/from/root/node_modules/@myorg/mylib (null) seems to be corrupted. Trying again.
> npm ERR! code ENOENT
> npm ERR! syscall open
> npm ERR! path /path/from/root/node_modules/@myorg/mylib/package.json
> npm ERR! errno -2
> npm ERR! enoent ENOENT: no such file or directory, open '/path/from/root/node_modules/@myorg/mylib/package.json'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent 

However, nothing external has changed. The file is where the `file:...` local path says it is. There is nothing that we can find in the change logs or docs that would suggest functionality relating to local paths has changed.

Therefore, this appears to be a regression.

**Comment by wraithgar** [comment]
Please use the issue template when making new issues. This does not have enough info to reproduce

```sh
~/D/n/s/file $ cat package.json 
{
  "name": "example",
  "version": "1.0.0",
  "dependencies": {
    "@test/directory": "file:./test/directory"
  }
}
~/D/n/s/file $ cat test/directory/package.json 
{
  "name": "@test/directory",
  "version": "1.0.0"
}
~/D/n/s/file $ npm i

added 1 package, and audited 2 packages in 326ms

found 0 vulnerabilities
~/D/n/s/file $ find node_modules/
node_modules/
node_modules//.package-lock.json
node_modules//@test
node_modules//@test/directory
node_modules//@test/directory/index.js
node_modules//@test/directory/package.json
~/D/n/s/file $ npm -v
9.1.2
```
