### ISSUE TITLE
[BUG] npm whoami allow empty username

### ISSUE THREAD

**Issue by sosoba** [npm/cli#5867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```sh
npm whoami

undefined
```

https://github.com/npm/cli/blob/dc8e6bdd1d9e3416846c4f0624705cb42a7fb067/lib/utils/get-identity.js#L12-L21

### Expected Behavior

```sh
npm whoami

npm ERR! This command requires you to be logged in.
```

It seems to me, that there should be condition on return at line 15
```js
if (registryData?.username) {
  return registryData.username;
}
```

### Steps To Reproduce

1. Config registry=https://verdaccio.example.com
2. Run 'npm whoami'
3. See result

### Environment

- npm: 8.19.2
- Node.js: 18.12.1
- OS Name: Windows 11
- System Model Name: Other
- npm config:
```ini
registry=https://verdaccio.example.com
```

**Comment by wraithgar** [comment]
Is verdaccio returning a 2xx response when you are not logged in?  npm assumes that whoami will return an http error if you are not logged in.  This seems like a verdaccio bug if it is not properly telling clients the situation.

**Comment by sosoba** [comment]
> Is verdaccio returning a 2xx response when you are not logged in? npm assumes that whoami will return an http error if you are not logged in. This seems like a verdaccio bug if it is not properly telling clients the situation.

Yes. You are right, This third-party registy has different behaviour that registry.npmjs.org. But in general the client should not assume that the server always returns valid values. It should validate them.

**Comment by juanpicado** [comment]
I think is a mix both, I will also include some improvements in verdaccio. Thanks @sosoba .
