### ISSUE TITLE
Feat: Support glob for `-w **/*` monorepo workspaces

### ISSUE THREAD

**Issue by 1aron** [npm/cli#5869]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`package.json`

```json
{
    "workspaces": [
        "packages/*",
        "examples/*"
    ]
}
```
```bash
npm version -w packages/a -w packages/b -w packages/c ...
npm publish -w packages/a -w packages/b -w packages/c ...
```

### Expected Behavior

`package.json`

```bash
npm version -w packages/*
npm publish -w packages/*
```
even filter some workspaces:
```bash
npm version --filter-workspace examples/*
npm publish --filter-workspace examples/*
```

**Comment by ljharb** [comment]
Try quoting the string that contains asterisks - otherwise the shell expands it before npm sees it.

**Comment by 1aron** [comment]
Now it works with commands like this `npm version 2.0.0-beta.100 --workspace packages`.
