### ISSUE TITLE
[BUG]  npx no longer respects local workspace between 8.11.0 and 8.18.0

### ISSUE THREAD

**Issue by kenlyon** [npm/cli#5871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

In my case it's similar to a monorepo.

* The root package.json has a devDependency of typescript 4.5.5.
* A child project has its own package.json with a devDependency of typescript 4.3.5.

It's essential that this child project is compiled with the older version for compatibility reasons.

Previously, executing npx tsc in the child folder would correctly use TypeScript 4.3.5.

Now it uses TypeScript 4.5.5.

### Expected Behavior

I expect it to respect the version of typescript specified by the package.json in the folder where npx was executed.

### Steps To Reproduce

* Create a new folder with a package.json file with the following details
  * A devDependency of typescript 4.5.5.
  * A workspaces section containing an entry for a new subdirectory.
  * A packageManager entry specifying `"yarn@3.2.1"`. (Not sure if this is relevant, but I'm using yarn.)
* Create a sub-directory with a name that matches the workspace.
* In the sub-directory, add a package.json file that contains a devDependency of typescript 4.3.5.
* In the root folder, execute the `yarn` command to install all the dependencies, including those of the workspace.
* Execute `npx tsc -v` in the root folder. It will return `Version 4.5.5`. This is expected.
* Execute `npx tsc -v` in the workspace folder. It will incorrectly return `Version 4.5.5` when using npm 8.18.0, but correctly return `Version 4.3.5` when using npm 8.11.0.

### Environment

- npm: 8.18.0
- Node.js: v16.17.0
- OS Name: Windows 10 Pro
- System Model Name: Dell Latitude 7420
- npm config:
```
; node bin location = C:\Program Files\nodejs\node.exe
; node version = v16.17.0
; npm local prefix = C:\Windows\system32
; npm version = 8.18.0
; cwd = C:\Windows\system32
; HOME = C:\Users\myUserName
```

**Comment by fritzy** [comment]
We now do root workspace detection. If you want to override that, you can use `--prefix=.`. If you think this behavior for `npm exec`/`npx` specifically should change, please contribute [an RRFC](https://github.com/npm/rfcs/issues/new?assignees=&labels=&template=rrfc.md&title=%5BRRFC%5D+%3Ctitle%3E).

**Comment by kenlyon** [comment]
Thanks for the explanation. The `--prefix=.` parameter gives me what I need.
