### ISSUE TITLE
NPM network issue. 

### ISSUE THREAD

**Issue by constobidullah** [npm/cli#5873]
When my create a react app using npx create-react-app then show under the error. how to handle this error ??
![image](https://user-images.githubusercontent.com/108364455/202841516-0a92a336-979f-4f64-96e4-94b53708660d.png)

**Comment by fritzy** [comment]
**Closing:** please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).
