### ISSUE TITLE
wrong execution file

### ISSUE THREAD

**Issue by itaybitax** [npm/cli#5874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I have created a cli library using `"bin"` in my `package.json` file, after running `npm link` the created shell file that created is not executing the scripts using `node`

this is the file that created: 
```
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*) basedir=`cygpath -w "$basedir"`;;
esac

exec "$basedir/node_modules/bittax-scripts/src/bin/cli.js"   "$@"
```

### Expected Behavior

the shell script should execute the `cli.js` using `node`

### Steps To Reproduce

1. create cli.js file
2. set the bin to "./cli.js"
3. Run npm link
4. go to "C:\Users\USER_NAME\AppData\Roaming\npm"
5. the created file should not have `exec node ...`.

### Environment

- npm: 8.15.0
- Node.js: v16.17.0
- OS Name: windows
- System Model Name:
- npm config:
```ini
; "builtin" config from C:\Users\ItayOded\AppData\Roaming\nvm\v16.17.0\node_modules\npm\npmrc

prefix = "C:\\Users\\ItayOded\\AppData\\Roaming\\npm"

; "user" config from C:\Users\ItayOded\.npmrc
; node bin location = C:\Program Files\nodejs\node.exe
; node version = v16.17.0
; npm local prefix = C:\Users\ItayOded\projects\bittax
; npm version = 8.15.0
; cwd = C:\Users\ItayOded\projects\bittax
; HOME = C:\Users\ItayOded
; Run `npm config ls -l` to show all defaults.
```

**Comment by ljharb** [comment]
cli.js needs a shebang that points to node, generally.

**Comment by wraithgar** [comment]
In windows this shim is required because symlinks do not work in windows.  In posix systems a symlink is made to the file instead, and it is assumed that the file is executable by the operating system without the need to be parsed by node.

https://github.com/npm/cmd-shim
