### ISSUE TITLE
Support npm view --local

### ISSUE THREAD

**Issue by fabiospampinato** [npm/cli#5877]
It'd be extremely convenient to have an `npm view` command that works off the locally installed packages, so that you can basically ask NPM to get the `package.json` for a package with a particular name and with a particular version that is already installed.

This would simplify logic by a lot, and improve correctness, in tools that provide you with some kind of metadata about your installed packages, like those that fetch the license information.

**Comment by wraithgar** [comment]
`npm query` returns the data from what is installed in `node_modules`

```sh
$ npm query '#pacote'|json -a _id location keywords repository
pacote@13.6.2 node_modules/licensee/node_modules/pacote [
  "packages",
  "npm",
  "git"
] {
  "type": "git",
  "url": "https://github.com/npm/pacote.git"
}
pacote@15.0.6 node_modules/pacote [
  "packages",
  "npm",
  "git"
] {
  "type": "git",
  "url": "https://github.com/npm/pacote.git"
}
```

**Comment by fabiospampinato** [comment]
Awesome!
