### ISSUE TITLE
[BUG] npm install causes code 1 or code 134 errors

### ISSUE THREAD

**Issue by sspahic2** [npm/cli#5880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When running npm install on my cPanel from my provider, I get a different range of errors. They usually are EAGIN, with either code 1 or code 134.

I've tried running node --max-old-space-size=750 `which npm` install to limit how much memory it can use, thinking that might be at fault, but it isn't.
The systems ram limit is 2gb.

This is one variation of the messages.
![image](https://user-images.githubusercontent.com/12472045/203144801-9a52ff01-33f8-45c6-89d3-122b933d821e.png)
![image](https://user-images.githubusercontent.com/12472045/203144882-a4581f05-d6fe-4867-9623-9ad9853046c2.png)

The other variation is this.
![image](https://user-images.githubusercontent.com/12472045/203145646-4503d04b-0d1e-42b0-8e12-35818ff5d213.png)
![image](https://user-images.githubusercontent.com/12472045/203145700-cd6e0d3a-7cb4-4ff1-89a8-734f8e2fcbd3.png)

I'm no wiz or anything, but usually issues that I come across, someone already solved and posted. This is maybe the third day of googling different key words, checking if maybe the different packages are at fault and so on.

### Expected Behavior

When running npm install I get a message that it's successful.

### Steps To Reproduce

1. Run npm install
2. See different errors happening with different messages

### Environment

- npm: 8.15.0 (It says that I need the latest release, but I'm not sure if I can run node 16.17.1 on the latest, because that is what I need)
- Node.js: 16.17.1
- OS Name: linux 4.18.0-372.16.1.lve.el8.x86_64
- System Model Name: cPanel 
- npm config:
; "user" config from /home/.../.npmrc

scripts-prepend-node-path = true

; node bin location = /home/.../node/bin/node
; node version = v16.17.1
; npm local prefix = /home/.../public_html
; npm version = 8.15.0
; cwd = /home/.../public_html
; HOME = /home/...
; Run `npm config ls -l` to show all defaults.

**Note:** About the OS version. I tried using 
cat /etc/os-release
cat /etc/*-release
lsb_release -a
hostnamectl

But I can't get what distro cPanel is running on.

**Comment by fritzy** [comment]
**Closing:** We suspect this has to do with a combination of resource constraints within the device/program being used and the large amount of transient dependencies being installed by this command.

We've opened https://github.com/npm/statusboard/issues/395 for us to look deeper into this and track the discussion and fixes around it. You can also read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) for more information on why this issue might be happening currently and ways to debug it.
