### ISSUE TITLE
I don't want to create the .npm directry at ~ ,How can I do that?

### ISSUE THREAD

**Issue by maozhitao12450** [npm/cli#5883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Enhancement, not another kind of Docs Enhancement.

- [X] This is a CLI Docs Enhancement.

### Description of Problem

npm WARN install Usage of the `--dev` option is deprecated. Use `--also=dev` instead.
npm ERR! code EROFS
npm ERR! syscall mkdir
npm ERR! path /root/.npm
npm ERR! errno -30
npm ERR! rofs EROFS: read-only file system, mkdir '/root/.npm'
npm ERR! rofs Often virtualized file systems, or other file systems
npm ERR! rofs that don't support symlinks, give this error.

**Comment by matthiaz** [comment]
What version of node/npm is this? 
This seems awfully similar to https://github.com/npm/cli/issues/5183

**Comment by fritzy** [comment]
Please use the issue template, and the latest version. We've improved the behavior in v9.

**Comment by matthiaz** [comment]
Try setting the `npm_config_cache` to `/tmp`

That should work
```
$ > npm_config_cache=/tmp/ npm --version ; echo $?
8.11.0
0
```
