### ISSUE TITLE
[EXIT HANDLER NEVER CALLED] While installing dependencies using NPM v8.19.2 on ARMv8

### ISSUE THREAD

**Issue by Sc00bz77** [npm/cli#5886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Running `npx create-next-app@latest` creates the below Error while installing dependencies. 

```
npm ERR! Exit handler never called!
                                                npm ERR! This is an error with npm itself. Please report this error at:                         npm ERR!     <https://github.com/npm/cli/issues>                                                npm ERR! A complete log of this run can be found in:                                            npm ERR!     /home/kali/.npm/_logs/2022-11-22T16_44_39_402Z-debug-0.log
                                                Aborting installation.                            npm install --save-exact --save react react-dom next typescript @types/react @types/node @types/react-dom eslint eslint-config-next has failed.
```

The result in the directory is:
- node_modules
- package.json

### Expected Behavior

Expected to initialise NextJs App project tree with project directories etc.

### Steps To Reproduce

1. In this environment... Kirin 980, Arm64 Linux Kali 
2. 
3. With this config... Vanilla, npm v8.19.2 using nextjs13 (latest) 
4. Run 'npx create-next-app@latest'
5. See error... "Exit Handler never called" 

### Environment

- npm: 8.19.2
- Node.js: 18.12.1
- OS Name: Kali Linux Nethunter (Android ARM64) 
- System Model Name: Huawei Nova 5T
- npm config:
```ini
; copy and paste output from `npm config ls` here
```
- node bin location = /usr/local/lib/nodejs/node-v18.12.1-linux-arm64/bin/node                  
- node version = v18.12.1                       
- npm local prefix = /home/kali/test-site/test-3
- npm version = 8.19.2                          
- cwd = /home/kali/test-site/test-3             
- HOME = /home/kali

**Comment by fritzy** [comment]
npm isn't currently supported in resource constrained environments due to unbounded parallelization. We're looking to improve this soon.

**Comment by Sc00bz77** [comment]
![Screenshot_20221123_214447_com duckduckgo mobile android](https://user-images.githubusercontent.com/118838072/203651925-ee755bd9-3be6-4a04-93ee-c5609b2ad1eb.jpg)
Thanks for the quick response. I was able to install Yarn using a script I found bouncing around github[Link](https://gist.githubusercontent.com/lackdaz/15f929aeb0fee44369af1d96635769b8/raw/a23a0c604f1236cb1ae709da9930dc0922b6cdb0/install-node-yarn-arm.sh) then after installing n with yarn using
`chmod +x install-node-yarn-arm.sh`
`sudo ./install-node-yarn-arm.sh`
Then
`yarn add n`
`yarn n install latest`

I could successfully create next app using

`yarn create next-app`

Thanks 👍
