### ISSUE TITLE
Support npm ls --omit prod

### ISSUE THREAD

**Issue by fabiospampinato** [npm/cli#5887]
I don't see a way to list dependencies that are not production dependencies, I guess one way to do that should probably be added.

**Comment by maxbilbow** [comment]
I think npm query might be an effective way of achieving this https://docs.npmjs.com/cli/v8/using-npm/dependency-selectors

**Comment by fabiospampinato** [comment]
I can combine the two potentially to get what I want, but using only `query` I don't think would allow me to filter the output of what `ls` provides, which ultimately is what I need, a detailed tree of dependencies.

**Comment by maxbilbow** [comment]
Looking at the docs, isn't the behaviour of **ls** likely to change or be deprecated?

**Comment by fritzy** [comment]
Yes, we're looking to support different outputs with query, or support query syntax with `ls`. We typically explore new features through RFCs.

Can you create [an RRFC](https://github.com/npm/rfcs/issues/new?assignees=&labels=&template=rrfc.md&title=%5BRRFC%5D+%3Ctitle%3E) in that repo?

Also, in the future, please use our issue template.

**Comment by fabiospampinato** [comment]
@fritzy can you tell me which issue template I should have picked?

<img width="1180" alt="Screen Shot 2022-11-22 at 22 21 14" src="https://user-images.githubusercontent.com/1812093/203433217-db3bc0cd-d42b-49a8-a571-2250e57850f7.png">

This isn't a bug, it isn't about docs, and it's not a security issue.

**Comment by ljharb** [comment]
isn’t this already `npm ls --only=prod`?

**Comment by fabiospampinato** [comment]
@ljharb I want to exclude production dependencies, not everything else, so something like `npm ls --only=dev`, which doesn't seem to work for that.
