### ISSUE TITLE
[BUG] permissions uid problem in docker

### ISSUE THREAD

**Issue by lubomirblazekcz** [npm/cli#5889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```dockerfile
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND noninteractive
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install apt-utils -y
RUN apt-get install curl -y

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
RUN apt-get install -y nodejs

RUN npm i npm -g && npm i lighthouse -g

```

When installing lighthouse in docker (perhaps also generally on linux), same files and folders have problematic uid. 
Eg. `lighthouse/node_modules/cssstyle` has `829141562` and this cause us that docker wasn't able to pull the docker image on our remote server. 

```dockerfile
WARNING: Failed to pull image with policy "always": failed to register layer: Error processing tar file(exit status 1): Container ID 829141562 cannot be mapped to a host ID (manager.go:240:36s)
```

Which led me to https://circleci.com/docs/high-uid-error/, but changing the uid via chown in docker didn't solve the issue.

After some digging I've found out that it was caused by npm@9, the issue was not happening in npm@8, perhaps because of changes in https://github.com/npm/cli/pull/5703

### Expected Behavior

I've resolved this by installing lighthouse with npm@8 for now.

The changes in https://github.com/npm/cli/pull/5703 seems like a good aproach, and this is just an edge case issue, so maybe close it. Just wanted to raise awareness about this to anyone experiencing similar problems.

### Environment

- npm: 9.1.2
- Node.js: 18.12.1
- OS Name: Ubuntu 22.04
- System Model Name:
- npm config:
```ini
; node bin location = /usr/bin/node
; node version = v18.12.1
; npm local prefix = /
; npm version = 9.1.2
; cwd = /
; HOME = /root
```

**Comment by papb** [comment]
> Which led me to https://circleci.com/docs/high-uid-error/, but changing the uid via chown in docker didn't solve the issue.

Are you sure chown didn't work? Maybe you used chown incorrectly?

What is the uid/gid you get when installing with npm 8?

**Comment by lubomirblazekcz** [comment]
I used following in the Dockerfile, after that I could find the uid anymore in the image, but docker pull still failed 

```
RUN chown --from=829141562:root -R root:root /usr/lib/node_modules/lighthouse/node_modules/cssstyle
```

**Comment by nlf** [comment]
this should be resolved in npm@9 as we no longer attempt to modify file ownership automatically. please feel free to reopen this issue if you're still experiencing this problem with the latest npm@9 build, ideally with reproduction steps.
