### ISSUE TITLE
[FEATURE] initialize package.json with default module type of commonjs as part of npm init

### ISSUE THREAD

**Issue by thescientist13** [npm/cli#590]
# What / Why

> Set a default [module `type`](https://nodejs.org/api/esm.html#esm_code_package_json_code_code_type_code_field) when generating a _package.json_, of **commonjs**.  I think there is a case to be made that a prompt could be made to select a module type. (as another FEATURE issue)

This would be helpful for the tooling / loader / JS ecosystem in terms of better understanding package contents by making sure this setting is always available (and not needing to know the assumed default workings of npm / nodejs / etc)

## When

When a user runs `npm init`

## Where

NPM CLI

### Current Behavior

By default, `npm init` (and accepting all defaults) creates a minimal _package.json_ like this
```bash
$ npm init
$ cat package.json
{
  "name": "scratch",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

### Expected Behavior

After running `npm init` the module type should be defined, with a default of **commonjs**
```bash
$ npm init
$ cat package.json
{
  "name": "scratch",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "type": "commonjs",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

## Who

@darcyclarke 

## References

Discussed during [Node+JS Interactive 2019 Collab Summit](https://github.com/openjs-foundation/summit/blob/master/2019-12-Montreal/agenda.md) during the [ESM modules session](https://github.com/openjs-foundation/summit/issues/207).

**Comment by ljharb** [comment]
This seems like a good thing to post as an RFC https://github.com/npm/rfcs

**Comment by thescientist13** [comment]
Ah, good call!  That could also allow / accommodate a selection option too as well as part of the `init` process.

**Comment by thescientist13** [comment]
thanks for the suggestions @ljharb , opened the same issue + added the prompt suggestion as well
https://github.com/npm/rfcs/issues/75
