### ISSUE TITLE
[BUG] Unable to publish using automation token

### ISSUE THREAD

**Issue by alshdavid** [npm/cli#5909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When trying to publish an npm package to the npm registry using Node 18 and Npm 8 or 9, I am unable to use the "Automation" token from the `NPM_TOKEN` `NPMJS_TOKEN` or using an `.npmrc` file configured with the token.

I believe I followed the [documentation in on the npm website](https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow) correctly.

<a href="https://i.imgur.com/jy4Fecb.mp4" target="_blank">
  <img width="960" alt="image" src="https://user-images.githubusercontent.com/12656294/204704925-79d3cedc-297d-4886-98a1-2cda7d2c9ce5.png">
</a>

```bash
export NPM_TOKEN=npm_xxxx

npm whoami # fails
npm publish --access public #fails
```

I am not sure if `npm whoami` should work with an automation token but I have the exact same issue when trying to publish a package to npm

```bash
mkdir my-unique-fake-project
cd my-unique-fake-project
npm init -y
npm publish --access public
```

I initially noticed this when trying to publish a package in a GitHub action without success. Since then I have tried on several environments I have lying around to the same effect.

### Expected Behavior

It should be authorized to publish

### Steps To Reproduce

1) Create Automation token
2) set `NPM_TOKEN` variable to it in an environment that hasn't previously logged into npm
3)
```bash
mkdir my-unique-fake-project
cd my-unique-fake-project
npm init -y
npm publish --access public
```

### Environment

- npm: 9.1.2
- Node.js: 18.12.1
- OS Name: 
  - MacOS 
  - Ubuntu (Github Actions, `actions/setup-node@v3` `node-version: 18`
  - Windows PowerShell (PS Core 7)
  - Windows WSL1 (debian)

**Comment by fritzy** [comment]
If your config includes the correct config, then this looks to be a registry support issue.
`//registry.npmjs.org/:_authToken=${NPM_TOKEN}`

**Closing:** this looks to be an issue with the registry which is outside the scope of this repo. For registry support please go to [npmjs.com/support](https://www.npmjs.com/support). If you believe this is a bug with the cli, please provide further clarifying details.
