### ISSUE TITLE
[version] Don't tag per default. 

### ISSUE THREAD

**Issue by infacto** [npm/cli#5911]
Suggestion: Don't create Git tags by default. Invert the logic of `--no-git-tag-version`. The dev should add option like `--git-tag` to automatically create a tag. In my opinion we (e.g. CI) should have full controll when and how to commit and tag. It's more error-prone to tag by default.

https://docs.npmjs.com/cli/commands/npm-version

**Comment by lukekarrys** [comment]
@infacto Thanks for filing this! This would be best suited as [an RRFC](https://github.com/npm/rfcs/issues/new?assignees=&labels=&template=rrfc.md&title=%5BRRFC%5D+%3Ctitle%3E). Please open an issue in that repo for further discussion about this change.
