### ISSUE TITLE
Error: ENOENT when installing anything, failing to find a nonexistent ~/package.json

### ISSUE THREAD

**Issue by Ulrik54** [npm/cli#5917]
Typing `npm install`, or any other install command, gives the following message:
```
npm WARN saveError ENOENT: no such file or directory, open '/Users/(USER)/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/(USER)/package.json'
npm WARN (USER) No description
npm WARN (USER) No repository field.
npm WARN (USER) No README data
npm WARN (USER) No license field.
```
How can I solve this? What file is it looking for? Searching for solutions have been fruitless so far, only producing more error messages.

npm v6.14.4
Node v13.14.0
macOS 10.11.15

**Comment by ljharb** [comment]
Run `npm init` in your project directory (NOT in your home directory) first.

**Comment by Ulrik54** [comment]
I don't have a project directory. I'm just trying to install a package.

**Comment by ljharb** [comment]
Then you'd want to `npm install -g` it (although generally you always want a project directory; global (project-less) installs are for command line tools that aren't project-specific, which aren't many.

**Comment by Ulrik54** [comment]
Entering `npm install -g` yields the following message:
```
npm ERR! code ENOLOCAL
npm ERR! Could not install from "" as it does not contain a package.json file.
[2022-12-05T15_56_10_877Z-debug.log](https://github.com/npm/cli/files/10155736/2022-12-05T15_56_10_877Z-debug.log)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/(USER)/.npm/_logs/2022-12-05T15_56_10_877Z-debug.log
```
[2022-12-05T15_56_10_877Z-debug.log](https://github.com/npm/cli/files/10155739/2022-12-05T15_56_10_877Z-debug.log)

**Comment by ljharb** [comment]
`npm install -g whatever`, where “whatever” is the package name you want to install.

**Comment by lukekarrys** [comment]
**Closing:** this looks to be a general support question which is outside the scope of the repo. For support please post your question to [github.community](https://github.community).
