### ISSUE TITLE
[BUG] Missing "latest-8" Tag

### ISSUE THREAD

**Issue by CodeMan99** [npm/cli#5921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Trying to install v8.x via "latest" tag fails.

```
npm install -g npm@latest-8
```

### Expected Behavior

Installing npm with the `latest-8` tag to resolve to a version matching `^8.19.3`.

### Steps To Reproduce

1. Get a list of the _dist-tags_ for npm.

```
npm info --json npm dist-tags | python3 -m json.tool --sort-keys
```

In the response there are `latest-*` for versions 1.x through 7.x, but not one for 8.x.

### Environment

- npm: 8.19.3
- Node.js: 16.18.0
- OS Name: Ubuntu 22.04.1 LTS
- System Model Name: Lenovo ThinkPad P15
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by lukekarrys** [comment]
What's your use case for using the `latest-8` tag?

We've moved away from creating new `latest-MAJOR` tags, but we keep the old ones around for legacy reasons. Running `npm install -g npm@8` should be functionally equivalent to us maintaining a `latest-8` tag that points to the latest version of npm 8.

**Comment by CodeMan99** [comment]
> Running `npm install -g npm@8` should be functionally equivalent

Oh, I was unaware of that. Thank you.

#### Use Case

Slowly upgrading custom docker images. My employment has a strong preference for using tags whenever possible. I suppose that makes them feel good and/or safe.

**Comment by ljharb** [comment]
Tags are a lot more mutable than version ranges, so they may want to adjust their preference :-)
