### ISSUE TITLE
[BUG] Unable to use adduser/login

### ISSUE THREAD

**Issue by recleun** [npm/cli#5922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I have been trying to publish a package to npmjs for a while now but I couldn't because I am not able to authenticate on the cli using adduser or login commands. Once I use them, an error occurs.

```
> npm login
npm notice Log in on https://registry.npmjs.org/
npm ERR! code ERR_SYSTEM_ERROR
npm ERR! syscall uv_os_gethostname
npm ERR! errno -4054
npm ERR! A system error occurred: uv_os_gethostname returned ENOSYS (function not implemented)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USER\AppData\Local\npm-cache\_logs\2022-12-06T23_34_51_900Z-debug-0.log
```

I have upgraded npm and also upgraded node from 16 to 18. Still same error.
Additional notes (that might be the cause but I'm not 100% sure): I use node v18 on windows 7, yes I know it's not fully supported by node but it worked fine for me since I installed it but this is the first time I had a problem with node.

### Expected Behavior

Once I use `adduser` it should ask me for a username and a password so I login to registry.npm.org.

### Steps To Reproduce

1. Open an instance of the command prompt.
2. Change directory to a package I want to publish.
3. Use the command `npm publish`.
4. Error occurs.

### Environment

- npm: 9.3.1
- Node.js: 18.12.1
- OS Name: Microsoft Windows
- System Model Name: Windows 7
- npm config:
```ini
; copy and paste output from `npm config ls` here
; "cli" config from command line options

location = "project"

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v18.12.1
; npm local prefix = D:\Development\Projects\wikisearch\wikisearch
; npm version = 9.1.3
; cwd = D:\Development\Projects\wikisearch\wikisearch
; HOME = C:\Users\Trashie
; Run `npm config ls -l` to show all defaults.
```

**Comment by fritzy** [comment]
This appears to be an issue with your access to do DNS queries in Windows.

Can you try running `nslookup registry.npmjs.org` and seeing if you similar error? If so, you can use this to debug your environment.

**Comment by wraithgar** [comment]
`node -e "dns.resolve('registry.npmjs.org', 'A', console.log)"` can also show you if node is allowed to make dns requests.

**Comment by recleun** [comment]
> Can you try running `nslookup registry.npmjs.org` and seeing if you similar error? If so, you can use this to debug your environment.

Unfortunately I can't do that now as I upgraded my laptop to windows 10 to resolve the issue, I did more research and I found out that `uv_os_gethostname` is a function that is implemented only in windows 8 and higher. (I may be wrong but that is what I understood)
