### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by theaxelchoco** [npm/cli#594]
I was downloading expo-cli and after it was doing the job it showed that.

![Capture](https://user-images.githubusercontent.com/55996711/70867838-5dd05300-1f50-11ea-9d84-9b22e38604a6.PNG)

**Comment by damian-pastorini** [comment]
FYI: you could probably sum up on https://github.com/npm/cli/issues/417 ? I've read about this issue many times.

**Comment by theaxelchoco** [comment]
Thanks

**Comment by mikemimik** [comment]
Duplicate issue; aggregating into https://github.com/npm/cli/issues/417.
