### ISSUE TITLE
[BUG] npm ECONNRESET connection error

### ISSUE THREAD

**Issue by LeonardoYoel** [npm/cli#5944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I'm trying to use `npm create-react-app` and I'm getting an ECONNRESET error and sometimes ETIMEDOUT

I understand that these errors are associated with the connection but nevertheless I can access [https://registry.npmjs.org/create-react-app](https://registry.npmjs.org/create-react-app) from the browser

I do not use proxy and I have already tried several of the solutions found on the net and in the problems raised here

I have changed the configuration setting the registry from _HTTPS_ to _HTTP_

I have cleared the cache with `npm cache clear --force`

I have reverted to previous versions of NodeJS

and when running npm doctor the response is the following:

```
npm ping                   not ok  request to https://registry.npmjs.org/-/ping?write=true failed, reason: connect ETIMEDOUT 104.16.22.35:443
npm -v                     not ok  FetchError: request to https://registry.npmjs.org/npm failed, reason: connect ETIMEDOUT 104.16.22.35:443
node -v                    not ok  FetchError: request to https://nodejs.org/dist/index.json failed, reason: connect ETIMEDOUT 104.20.22.46:443
npm config get registry    ok      using default registry (https://registry.npmjs.org/)
git executable in PATH     ok      C:\Program Files\Git\cmd\git.EXE
global bin folder in PATH  ok      C:\Users\Usuario\AppData\Roaming\npm
npm ERR! Some problems found. See above for recommendations.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Usuario\AppData\Local\npm-cache\_logs\2022-12-09T16_31_32_978Z-debug-0.log
```

### Expected Behavior

I'm just trying to create an app in react with `npm create-react-app my-app --template typescript`

### Steps To Reproduce

1. I am using the windows 11 console (cmd).
2. I am not using any proxy in the npm configuration or the windows itself, I have disabled the firewall and the ESET Nod32 antivirus
3. Run `npm create-react-app my-app --template typescript`
4. I am currently seeing the following error:

```
npm ERR! code ETIMEDOUT
npm ERR! syscall connect
npm ERR! errno ETIMEDOUT
npm ERR! network request to https://registry.npmjs.org/create-react-app failed, reason: connect ETIMEDOUT 104.16.23.35:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! networks
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly. See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\User\AppData\Local\npm-cache\_logs\2022-12-09T16_10_28_894Z-debug-0.log
```

### Environment

- npm: 9.2.0
- Node.js: 19.2.0
- OS Name: windows 11
- System Model Name: Lenovo Thinkpad
- npm config:
```ini
; "builtin" config from C:\Users\Usuario\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\Usuario\\AppData\\Roaming\\npm"

; "user" config from C:\Users\Usuario\.npmrc

registry = "https://registry.npmjs.org/"

; "cli" config from command line options

location = "project"

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v19.2.0
; npm local prefix = C:\Users\Usuario
; npm version = 9.2.0
; cwd = C:\Users\Usuario
; HOME = C:\Users\Usuario
; Run `npm config ls -l` to show all defaults.
```

**Comment by hindicator** [comment]
I've encounter a specific bug twice now.

Sometimes the router fail to connect you through IPv4 and automatically fallback the connection to IPv6,
which caused this issue.

Restart the router should solve this issue.

Hope this would help you..

**Comment by LeonardoYoel** [comment]
> I've encounter a specific bug twice now.
> 
> Sometimes the router fail to connect you through IPv4 and automatically fallback the connection to IPv6,
> which caused this issue.
> 
> Restart the router should solve this issue.
> 
> Hope this would help you..

thanks for your answer but it didn't work 🥺

**Comment by LeonardoYoel** [comment]
After looking for a lot of information, I found the solution to install a VPN.
For some reason the telephone company in Cuba blocks access to npm records.

**Comment by sebasQuesada** [comment]
Buenas amigo yo estoy reprenentando el mismo problema, como es eso que al instalar una vpn se soluciono? bloquea los registro de npm? podria darme mas detalle, estoy reprentando algo parecido con un proyecto que lo empezaron en cuba

**Comment by LeonardoYoel** [comment]
Hola, sí realmente la solución está en instalar los paquetes detras de una VPN, te aconsejo eliminar las caché antes de hacerlo. El VPN q uso es Tunnelbear.
