### ISSUE TITLE
[BUG] "1 package is looking for funding" can't be disabled

### ISSUE THREAD

**Issue by LoganDark** [npm/cli#595]
Every time I install a package I get "1 package is looking for funding". I looked through your source code and it looks like it can't be disabled. I don't want to be nagged every time I use npm that some project wants my money. I would greatly appreciate adding a config option to disable this

npm 6.13.1, node 13.3.0

**Comment by ljharb** [comment]
You can run `npm install --no-fund`, or `NPM_CONFIG_FUND=false npm install`, or you can add `fund=false` to `~/.npmrc`, for example.

This is mentioned in the original `npm fund` announcement https://blog.npmjs.org/post/188841555980/updates-to-community-docs-more. The docs on docs.npmjs.com seem to not be updated yet (cc @ruyadorno) but I believe that once they are, they will contain a "funding" section.

**Comment by LoganDark** [comment]
Really, you can do all three of those things? Wow, I looked through the source code and couldn't find ANYTHING.

Thanks

**Comment by ruyadorno** [comment]
thank you so much @ljharb 🙏 for now it's only documented in the preview of the new docs: https://preview-docs.npmjs.com/cli-commands/npm-install but we should be replacing the current docs with that new version sometime soon 😊 

@LoganDark you can do all these variations with most config values that I know of, it's all abstracted away by the `npm.config` so it's hard to get it from reading the source code but basically this is the LOC in which it retrieves whether or not to show the fund msg:

https://github.com/npm/cli/blob/797a59797a2e226631f068c912f351ba340581fe/lib/install.js#L248

**Comment by mvasilkov** [comment]
Yeah, this should be right up there with the terminal spam. "1 package is looking for funding, to disable this message please install AdBlock for your terminal because these are the developer tools we all deserve."

**Comment by LoganDark** [comment]
@mvasilkov Unnecessary. There is a way to disable this, you don't need to revive a months-old thread just to say you don't like an issue that has already been addressed.

**Comment by casbloem** [comment]
To disable run:
`npm config set fund false --global`

**Comment by bubinek** [comment]
@LoganDark It's necessary. It's commercial spam in open source environment ergo It's disgusting. There should be text added "To disable this message do ...".

**Comment by LoganDark** [comment]
@bubinek Yes I understand that, but this issue has been solved twice already and there is no need to continue trying to drive home just how unnecessary/unacceptable the feature is. If you'd like the wording to be changed, perhaps that should be a separate issue

**Comment by LoganDark** [comment]
@ruyadorno please consider locking this issue to prevent people from coming along months or years in the future just to echo their disappointment. This issue has been completely solved (it is about the inability to disable the message, and the message is able to be disabled; there are even clear instructions in 2 comments), and any further discussion about some other characteristic of the message should warrant a new issue imho.

**Comment by ruyadorno** [comment]
agreed, thanks @LoganDark 👍
