### ISSUE TITLE
Not receiving error recovery email

### ISSUE THREAD

**Issue by Arooba-git** [npm/cli#5950]
Hi 👋 
I actually don't recall creating an account with npm. Nevertheless, my email is registered (it might be slipped out of my memory). Regardless, when I request "forgot password" and enter the username/email. I get this message but do not receive any email. :(

<img width="626" alt="Screen Shot 2022-12-11 at 1 26 44 PM" src="https://user-images.githubusercontent.com/56495631/206886615-706c00b3-431a-4b8c-99e3-993055c321f7.png">

My email: arooba.shahoor@gmail.com

**Comment by ljharb** [comment]
@Arooba-git please file a support ticket with npm/github for that; this repo is for issues with the CLI itself.

**Comment by Arooba-git** [comment]
Thank you for getting back to me. Could you guide me on how to create a
support ticket at npm?

**Comment by ljharb** [comment]
https://www.npmjs.com/support

**Comment by Arooba-git** [comment]
thank you!
