### ISSUE TITLE
[BUG] Input Prompt (e.g. private key password request for a git-based dependency) is hidden by fancy console output

### ISSUE THREAD

**Issue by mattpr** [npm/cli#5954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```
$ npm --version
8.11.0
```

(I also tried `npm@9.2.0`...same issue).

When I have a package.json that includes a **private** repo via git url... e.g.

```
"dep-name": "gitlab:group-name/dep-name#main",
```

...and do an `npm install` or `npm ci` things progress and then at some point npm hangs with last line of output something like (for example)...

```
(##################) ⠇ reify:next: timing reifyNode:node_modules/typescript Completed in 10491ms
```

If I hit `CTRL-C` I get a hint as the output updates to something like:

```
Enter passphrase for key '/Users/user/.ssh/id_rsa': Enter passphrase for key '/Users/user/.ssh/id_rsa': (##################) ⠇ reify:next: timing reifyNode:node_modules/typescript Completed in (##################) ⠇ reify:next: timing reifyNode:node_modules/typescript Completed in 10491ms
```

This has been around forever.  I run into it periodically and waste some time wondering what npm is doing that is taking so long.    Eventually I figure out that actually something is waiting for user input and npm is just hiding the prompt so I don't know what is needed.

I've searched the issues and can't find any open or closed reference to this.  Am I the only one or is this something special about my environment?  (macos Mojave, node 16.latest, node via nvm).

I can do `npm --progress false install` and then I see the prompt but it looks like npm isn't handling the prompt properly as it is shown multiple times before I have a chance to enter a password (multiple on same line).  When I enter my password it doesn't work, so my input to npm is not being passed to the underlying process that generated the prompt I guess.

```
$ npm --progress false install
Enter passphrase for key '/Users/username/.ssh/id_rsa': Enter passphrase for key '/Users/username/.ssh/id_rsa': Enter passphrase for key '/Users/username/.ssh/id_rsa': Enter passphrase for key '/Users/username/.ssh/id_rsa': Enter passphrase for key '/Users/username/.ssh/id_rsa': Enter passphrase for key '/Users/username/.ssh/id_rsa':
Enter passphrase for key '/Users/username/.ssh/id_rsa':
Enter passphrase for key '/Users/username/.ssh/id_rsa':
Enter passphrase for key '/Users/username/.ssh/id_rsa':
Enter passphrase for key '/Users/username/.ssh/id_rsa':
```

Yes I could use ssh-agent to work around this but that isn't really the point.  

It would be nice if when user input is required, npm surfaces that and plumbs the user input into the underlying process.  The "no output" hang scenario is really terrible user experience.  Getting the prompt and not having my password work is also confusing.

### Expected Behavior

When user input is required during npm install or npm ci (and the install stops/hangs), I expect to see the prompt text, be able to provide input and have that input be provided to the underlying process that requested it.

### Steps To Reproduce

Do `npm install` or `npm ci` on a project that includes a private git repo as a dependency where your ssh key has not been added to ssh agent.

Do this on macos in default bash shell.

Note that the install process hangs due to underlying password prompt to unlock your private key.

Even if you type your password, it won't work as your password input is not properly passed to the underlying process the generated the prompt.

### Environment

- npm:
8.11.0 and/or 9.2.0
- Node.js:
16.16
- OS Name:
macos Mojave (10.14)
- System Model Name:
macbook pro
- npm config:
```ini
; "cli" config from command line options

location = "project"

; node bin location = /Users/username/.nvm/versions/node/v16.16.0/bin/node
; node version = v16.16.0
; npm local prefix = /tmp
; npm version = 9.2.0
; cwd = /tmp
; HOME = /Users/username
; Run `npm config ls -l` to show all defaults.
```

# update

I found an unresolved bug from 2018 in the old/frozen repo for the same issue.  Doesn't look like it was migrated.
https://github.com/npm/npm/issues/18108

It used to be I could enter my key password to the invisible prompt if I figured out what was going on and things would proceed... but that doesn't work anymore (correct key password doesn't work).

**Comment by lukekarrys** [comment]
The terminal output has been largely rewritten since this issue, with a new foundation of making sure that all output is paused during inputs. One reason this was done is to fix issues like this 😄  So I'm going to close this since it's old and all the cases I've been able to test work correctly now.
