### ISSUE TITLE
[BUG] Failure installing/running git-hosted package via `npx`

### ISSUE THREAD

**Issue by bdehamer** [npm/cli#5957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When trying to install/run the latest version of the npm CLI via the `npx` command I get a no output and an exit code of 1.

```bash
$ npx npm@npm/cli#latest version    
Need to install the following packages:
  github:npm/cli#latest
Ok to proceed? (y) y
$ echo $?
1
```

Worth noting that the above command **will** work as expected if the referenced package has already been installed/cached (say, by running `npm exec npm@npm/cli#latest` first). So it seems like the issue may be related to downloading/installing.

### Expected Behavior

I expect the package to be downloaded and executed similar to the way it works w/ the `npm exec` command:

```bash
$ npm exec npm@npm/cli#latest -- version
Need to install the following packages:
  github:npm/cli#latest
Ok to proceed? (y) y
{
  delme: '1.0.0',
  npm: '9.2.0',
  node: '14.20.0',
  v8: '8.4.371.23-node.87',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '83',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '2.1.5',
  openssl: '1.1.1q',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0'
}
```

### Steps To Reproduce

1. Start w/ an empty "~/.npm/_npx" directory to ensure you don't already have the package installed.
2. Execute `npx npm@npm/cli#latest version`
3. Answer "y" when prompted about proceeding w/ the package installation
4. Note that no output is displayed the the process exit code is non-zero

### Environment

- npm: 9.1.1
- Node.js: v14.20.0
- OS Name: macOS 13.0.1
- System Model Name: Macbook Pro M1 Max
- npm config:
```ini
; "user" config from /Users/bdehamer/.npmrc

@github:registry = "https://npm.pkg.github.com/" 
//npm.pkg.github.com/:_authToken = (protected) 
//registry.npmjs.org/:_authToken = (protected) 

; "cli" config from command line options

location = "project" 

; node bin location = /Users/bdehamer/.asdf/installs/nodejs/14.20.0/bin/node
; node version = v14.20.0
; npm local prefix = /private/tmp/delme
; npm version = 9.1.1
; cwd = /private/tmp/delme
; HOME = /Users/bdehamer
; Run `npm config ls -l` to show all defaults.
```

**Comment by mgabeler-lee-6rs** [comment]
Observed this as well with 8.19.4. Running under strace, I see that, after unpacking the package to be run, it spawns `node ${install-path}/lib/node_modules/npm/bin/npx-cli.js install --force --cache=... ...`

I.e. `npx foo` is itself than running `npx install`, i.e. it's trying to find a command to run from this package: https://www.npmjs.com/package/install ... which fails.

**Comment by satyaki1** [comment]
Any update on this ticket? We are facing an issue with node v18, while installing a dependency having git+ssh through `npm install`

**Comment by milaninfy** [comment]
Executing the steps mentioned in the repro steps it worked as expected in the issue on `npm@10.8.2` Please update and check. 

Cleared cache as suggested in the issue... 
```sh
~ $ cd $(npm config get cache)
~/.npm $ ls
_cacache			_npx
_logs				_update-notifier-last-checked
~/.npm $ rm -rf *  
zsh: sure you want to delete all 4 files in /Users/mi/.npm [yn]? y
```

```sh
~/.npm $ 
~/.npm $ pwd 
/Users/mi/.npm
~/.npm $ npx npm@npm/cli#latest version
Need to install the following packages:
github:npm/cli#latest
Ok to proceed? (y) y

{
  npm: '10.8.2',
  node: '22.5.1',
  acorn: '8.11.3',
  ada: '2.9.0',
  ares: '1.32.1',
  brotli: '1.1.0',
  cjs_module_lexer: '1.2.2',
  cldr: '45.0',
  icu: '75.1',
  llhttp: '9.2.1',
  modules: '127',
  napi: '9',
  nbytes: '0.1.0',
  nghttp2: '1.62.1',
  nghttp3: '0.7.0',
  ngtcp2: '1.3.0',
  openssl: '3.0.13+quic',
  simdjson: '3.9.4',
  simdutf: '5.3.0',
  sqlite: '3.46.0',
  tz: '2024a',
  undici: '6.19.2',
  unicode: '15.1',
  uv: '1.48.0',
  uvwasi: '0.0.21',
  v8: '12.4.254.21-node.16',
  zlib: '1.3.0.1-motley-209717d'
}
```
