### ISSUE TITLE
[BUG] cb() never called! for `install -g eslint`

### ISSUE THREAD

**Issue by versat** [npm/cli#596]
# What / Why
`npm ERR! cb() never called!` every time I try to `install -g eslint`

## When
Everytime I try to install `eslint` via:
`sudo npm install -g eslint`

## Where
```
$ npm -v
6.13.4
$ uname -a
Linux debian10 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
```

### Current Behavior

Installing `eslint`always crashes with an error like this:
```
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-16T12_34_57_744Z-debug.log
```
I have tried `npm cache clean --force` but that did not help.

### Steps to Reproduce
Update `npm` to latest and install `eslint`:
```
ms@debian10:~$ sudo npm install -g npm@latest
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.13.4
updated 1 package in 6.632s
ms@debian10:~$ sudo npm install -g eslint
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-16T12_34_57_744Z-debug.log
```

### Expected Behavior
The package should be installed successfully

## Who
* n/a

## References
Collection of similar issues in ticket #417

**Comment by versat** [comment]
Example log file of failure:
[npm_cb_never_called_log.txt](https://github.com/npm/cli/files/3968057/npm_cb_never_called_log.txt)

**Comment by versat** [comment]
I have the same issue under Windows 7 with npm 6.12.1 (that came with node.js installation) and 6.13.4 (updated npm).
Clearing the cache does not help and `npm cache verify` says there is no problem.

**Comment by versat** [comment]
It works better with npm 6.7.0. At least under Linux I was able to install `eslint` :tada:
Under Windows the cb() issue does not happen but it simply hangs forever at some point during installation :(

**Comment by mikemimik** [comment]
Duplicate issue; aggregating into https://github.com/npm/cli/issues/417.
