### ISSUE TITLE
[BUG] `npm update -g` should not downgrade prerelease packages

### ISSUE THREAD

**Issue by hyrious** [npm/cli#5963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`npm update -g` updates a global package from `0.2.0-alpha.1` (alpha) to `0.1.5` (latest).

### Expected Behavior

It should not downgrade an alpha (prerelease) package.

### Steps To Reproduce

I have a package `@hyrious/telegraph` which has these versions:

- latest: 0.1.5
- alpha: 0.2.0-alpha.2

1. Install the alpha one with `npm i -g @hyrious/telegraph@alpha`,
   verify that: `npm ls -g | grep telegraph` &rArr;
   ```
   ├── @hyrious/telegraph@0.2.0-alpha.2
   ```
3. Run `npm update -g`, check again:
   ```
   ├── @hyrious/telegraph@0.1.5
   ```

### Environment

- npm: 9.2.0
- Node.js: v19.2.0
- OS Name: macOS Ventura 13.0.1
- System Model Name: Macbook Pro
- npm config:
```ini
; "builtin" config from /usr/local/lib/node_modules/npm/npmrc

prefix = "/usr/local"

; "user" config from /Users/hyrious/.npmrc

//registry.npmjs.org/:_authToken = (protected)
cmake_LLVM_DIR = "/usr/local/Cellar/llvm/11.0.0_1/lib/cmake/llvm"
email = "hyrious@outlook.com"
init.license = "MIT"
loglevel = "error"
package-lock = true
viewer = "browser"

; "cli" config from command line options

location = "project"

; node bin location = /usr/local/Cellar/node/19.2.0/bin/node
; node version = v19.2.0
; npm local prefix = /private/tmp/test-npm
; npm version = 9.2.0
; cwd = /private/tmp/test-npm
; HOME = /Users/hyrious
; Run `npm config ls -l` to show all defaults.
```

**Comment by shadowspawn** [comment]
Somewhat to my surprise, this is documented behaviour for the global update.

https://docs.npmjs.com/cli/v9/commands/npm-update#updating-globally-installed-packages

> Note: Globally installed packages are treated as if they are installed with a caret semver range specified. So if you require to update to `latest` you may need to run `npm install -g [<pkg>...]`
>
> NOTE: If a package has been upgraded to a version newer than `latest`, it will be _downgraded_.

**Comment by hyrious** [comment]
Wow, I see. So this issue can be closed since it works as expected.
