### ISSUE TITLE
[BUG] 404 if package published under trailing slash

### ISSUE THREAD

**Issue by polRk** [npm/cli#5975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

404 for package https://internal/repo/npm/secure-json-parse
200 for package https://internal/repo/npm/secure-json-parse/

Problem with internal proxy nexus, i can't configure npm to use trailing slash for packages search/dowload

### Expected Behavior

Return 200 for paths with and without trailing slash.

npm cli should have option for turn on/off trailing slash

### Steps To Reproduce

You can not reproduce, because it is internal registry with proxy to registry.npmjs.org

### Environment

- npm: 9.0.1
- Node.js: v19.0.0
- OS Name: Mac OS
- System Model Name: Macbook Pro M1
- npm config:
```ini
; "user" config from (protected)/.npmrc

//(protected)/repo/npm/:_authToken = (protected) 
; always-auth = true ; overridden by project
; audit = false ; overridden by project
; strict-ssl = false ; overridden by project

; "project" config from (protected)/.npmrc

always-auth = true 
audit = false 
registry = "(protected)/repo/npm" 
strict-ssl = false 

; node bin location = (protected)/.nvm/versions/node/v19.0.0/bin/node
; node version = v19.0.0
; npm local prefix = (protected)
; npm version = 9.0.1
; cwd = (protected)
; HOME = (protected)
; Run `npm config ls -l` to show all defaults.
```

**Comment by polRk** [comment]
I think the problem may be related to how the package author publishes his package. With or without trailing slash

**Comment by fritzy** [comment]
Can you create [an RRFC](https://github.com/npm/rfcs/issues/new?assignees=&labels=&template=rrfc.md&title=%5BRRFC%5D+%3Ctitle%3E) in that repo for the feature you have in mind? Unfortunately, we can't support your internal proxied registry directly.
