### ISSUE TITLE
delete this issue pls

### ISSUE THREAD

**Issue by Aeplet** [npm/cli#5977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

im getting an npm [error][
![image_2022-12-18_095210433](https://user-images.githubusercontent.com/86505664/208305052-d62a9309-3d5d-4820-bd70-f52f0b4bed86.png)
](url)

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by ljharb** [comment]
node 8 and npm 3 are both many years obsolete. Can you try node 14, 16, 18, or 19, and npm 6 or 9?

**Comment by Aeplexi** [comment]
i might try it idk

**Comment by Aeplet** [comment]
how do i update?

**Comment by ljharb** [comment]
That depends on how you installed node in the first place. The official sources are nodejs.org, or a version manager that automates that, like nvm, nave, n, etc.

**Comment by Aeplet** [comment]
i updated ubuntu, works now
