### ISSUE TITLE
[BUG] `.npmrc` overload

### ISSUE THREAD

**Issue by y-nk** [npm/cli#5982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

(i think it's not really a bug since it's there from many versions afaik)

When creating multiple levels of `.npmrc` ([like this in the docs](https://docs.npmjs.com/cli/v7/configuring-npm/npmrc#files)) config of more "local" `.npmrc` are overriding more global `.npmrc` even when the cli prompts for incorrect value (see steps to reproduce)

### Expected Behavior

If the cli finds that there's a misconfiguration at local level, it should try to fallback to valid configuration at global level, if present.

### Steps To Reproduce

1. create a `~.npmrc` with a custom github registry and a PAT such as (for example):

```
@my-registry=https://npm.pkg.github.com/
//npm.pkg.github.com/:_authToken=ghp_A_VALID_TOKEN_VALUE
```

2. create a repo with a local `.npmrc` containing a slightly different configuration:

```
@my-registry=https://npm.pkg.github.com/
//npm.pkg.github.com/:_authToken=${GH_PAT}
```

3. when running `npm` commands in the repo, the cli will complain that it cannot read the value of `GH_PAT` (since it's not exported in env) but will not fallback to the value defined in 1.

### Environment

- npm: tested in 7, 8 and 9
- Node.js: not relevant
- OS Name: not relevant
- System Model Name: Macbook Pro

**Comment by ljharb** [comment]
This seems like correct behavior. If there's a misconfiguration - especially with auth - you don't want a silent fallback, you want everything to die, loudly, so you can correct the configuration.

**Comment by y-nk** [comment]
@ljharb i somehow understand the behavior, but since GH_PAT are user oriented it makes sense to have them in a centralized place (`~/.npmrc` or env var). i would think using `~/.npmrc` is better than env, since a file may not be accessible but the env _feels_ a bit more public.

what i mean by that is that the correct behavior somehow encourages a practice which i think is less secure than if the behavior was corrected in favor of what i was proposing.

(closing since not a bug, but happy to continue the discussion nonetheless)
