### ISSUE TITLE
[BUG] npm hooks firing over a week late

### ISSUE THREAD

**Issue by hardillb** [npm/cli#5983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

re: https://github.com/npm/cli/issues/4247

https://docs.npmjs.com/cli/v9/commands/npm-hook?v=true

I have created a couple of hooks early in 2022 and had problems with them not firing at all, this was fixed back in March, but in the last 2 months the hooks have fired later and later, they are now taking well over a week to fire.

### Expected Behavior

Hooks to fire with in a couple of hours at worst not multiple days

### Steps To Reproduce

1. create an internet facing web hook at https://foo.example.com
2. create a npm hook for a package that points to the web hook `npm hook add foo https://foo.example.com secret`
3. update the package targeted by the hook
4. wait for the hook to be called by npmjs.org (currently this is a LONG time)
 

### Environment

- npm: 8.19.2 (but this is server side not a client issue)
- Node.js: 16.18.1
- OS Name: Linux
- System Model Name: na
- npm config:
```ini
npm config ls
; "user" config from /home/hardillb/.npmrc

@ben:registry = "http://localhost:4873/" 
@flowforge:registry = "https://npm.hardill.me.uk/" 
//localhost:4873/:_authToken = (protected) 
//npm.hardill.me.uk/:_authToken = (protected) 
//registry.kube.ptsdevstaging.com/:_authToken = (protected) 
//registry.npmjs.org/:_authToken = (protected) 
//registry.ubuntu.local/:_authToken = (protected) 

; node bin location = /usr/bin/node
; node version = v16.18.1
; npm local prefix = /home/hardillb
; npm version = 8.19.2
; cwd = /home/hardillb
; HOME = /home/hardillb
; Run `npm config ls -l` to show all defaults.

```

**Comment by fritzy** [comment]
This is an issue with the registry you're using. These issues are just for the CLI.

**Closing:** this looks to be an issue with the registry which is outside the scope of this repo. For registry support please go to [npmjs.com/support](https://www.npmjs.com/support). If you believe this is a bug with the cli, please provide further clarifying details.

**Comment by hardillb** [comment]
@fritzy Fine, but where do I raise issues against the npmjs.org repo?

p.s. this is where I was directed by Myles Borins to raise issues with the repo in the past...
