### ISSUE TITLE
[BUG] npm pkg delete fails to delete if there's dot in the key name

### ISSUE THREAD

**Issue by avihay2019** [npm/cli#5984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I have this section in the package.json:
"dependencies": {
    "uWebSockets.js": "uNetworking/uWebSockets.js#v20.3.0",
    "undici": "^5.0.0"
  }

I'm running the command: npm pkg delete dependencies.uWebSockets.js

The result after it is:
"dependencies": {
    "undici": "^5.0.0",
    "uWebSockets": {},
    "uWebSockets.js": "uNetworking/uWebSockets.js#v20.3.0"
  }

### Expected Behavior

I'd expect the following result:
"dependencies": {
    "undici": "^5.0.0",
  }

### Steps To Reproduce

Can be reproduced in the mentioned above steps

I saw a similar issue [here](https://github.com/npm/cli/issues/4829), but trying to work with [.] didn't help.

### Environment

- npm:9.2.0 (also happen on 8.19)
- Node.js:18.8.0
- OS Name:macOS Ventura

**Comment by ljharb** [comment]
For managing dependency lists, I'd expect users to use `npm install` and `npm uninstall` rather than `npm pkg`.

**Comment by shadowspawn** [comment]
As noted by @ljharb , there are better commands for managing dependencies in general, but you can work with field names which include dots.

This works for your example:

```
npm pkg delete 'dependencies[uWebSockets.js]'
```

-----

https://docs.npmjs.com/cli/v9/commands/npm-pkg
> For complex fields you can also name a property in square brackets to specifically select a child field.

**Comment by nlf** [comment]
i believe the original question was well answered so i'm going to close this issue. please do reopen it if the suggestions here do not solve your problem.
