### ISSUE TITLE
[FEAT] Option to run npm audit only on package.json direct dependencies

### ISSUE THREAD

**Issue by khalyomede** [npm/cli#6004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Currently `npm audit` will scan all dependencies and sub dependencies. This leads to situations where I use the latest version possible of my direct dependencies, but these dependencies do not use the latest version of their own dependencies. E.g. sub dependencies are outdated, but direct dependences are up to date.

I personnally prefer to let the package maintainers to handle restricting their own dependencies to fix the security concern, rather than having to do it myself, in order to ensure the maintainer will test his/her package still works fine after restricting and fixing the security issue on the said compromised package. Also in most case these security issues are of a little concern for me since I use only NPM dependencies to build my JS assets for front-end (and do not use Node.js to run a back-end script in production).

Note I got inspired by `composer outdated --direct`, which does the same behavior for PHP packages ([official documentation about composer outdated command](https://getcomposer.org/doc/03-cli.md#outdated)).

### Expected Behavior

I propose to introduce a new flag called `--direct`, which would only scan for direct dependencies security issues (and not diving into the sub dependencies of these direct dependencies).

```bash
khalyomede@ubuntu:~/Documents/programming/my-project$ npm audit --direct
# npm audit report

ansi-regex  5.0.0
Severity: high
Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
fix available via `npm audit fix --direct`
node_modules/ansi-regex

1 vulnerability (1 high, 0 critical)

To address all issues, run:
  npm audit fix --direct
```

Note that `npm audit fix` should also be supplemented with this new `--direct` flag to keep consistencies.

### Environment

- npm: 8.13.2
- Node.js: 18.6.0
- OS Name: Ubuntu 22.04 (over Docker)
- System Model Name: VivoBook_ASUSLaptop X532FLC_S532FL
- npm config:
```ini
; node bin location = /usr/bin/node
; node version = v18.6.0
; npm local prefix = /home/node
; npm version = 8.13.2
; cwd = /home/node
; HOME = /root
```

**Comment by khalyomede** [comment]
I just found there seems to be a package that aimed to add this feature (and goes beyond by providing the ability to ignore dependencies for various reasons using a configuration file).

https://www.npmjs.com/package/audit-ci

**Comment by fritzy** [comment]
This is an interesting idea. We've got Audit Policies on the roadmap, so feel free to open a discussion on the RFC repo [or create an RRFC](https://github.com/npm/rfcs/issues/new?assignees=&labels=&template=rrfc.md&title=%5BRRFC%5D+%3Ctitle%3E).
