### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by mkpandey100** [npm/cli#6016]
Project was running fine when I run npm install I get following error.

[npm_issue.txt](https://github.com/npm/cli/files/10332558/npm_issue.txt)

**Comment by lukekarrys** [comment]
**Closing:** please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).
