### ISSUE TITLE
[BUG] Exit handler never called during one-time lock update

### ISSUE THREAD

**Issue by 5ide4ustle5ales** [npm/cli#6017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Npm old lockfile and told to report bug here, to be fair I'm going off YouTube videos of how to install live server in termux 
Here the link for the YouTube
https://youtu.be/_zrTZphAaAk
Here's the guy's github 
https://github.com/ProjectsByJackHe/airshare
Termux cloned site gh termux 
Apt install nodejs -y
Cd in airshare npm install 
These are the logs from the error

29 timing npm:load:logFile Completed in 12ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 74ms
33 timing arborist:ctor Completed in 2ms
34 silly logfile done cleaning log files
35 timing idealTree:init Completed in 310ms
36 warn old lockfile
36 warn old lockfile The package-lock.json file was cr
eated with an old version of npm,
36 warn old lockfile so supplemental metadata must be
fetched from the registry.
36 warn old lockfile
36 warn old lockfile This is a one-time fix-up, please
 be patient...
36 warn old lockfile
37 timing npm Completed in 925ms
38 verbose unfinished npm timer command:install 167268
3037758
39 verbose unfinished npm timer reify 1672683037765
40 verbose unfinished npm timer reify:loadTrees 167268
3037784
41 verbose unfinished npm timer idealTree 167268303778
6
42 verbose unfinished npm timer idealTree:inflate 1672
683038098
43 info ok
44 error Exit handler never called!
45 error This is an error with npm itself. Please repo
rt this error at:
46 error     <https://github.com/npm/cli/issues>
47 error A complete log of this run can be found in:
47 error     /data/data/com.termux/files/home/.npm/_lo
gs/2023-01-02T18_10_37_328Z-debug-0.log

### Expected Behavior

The video said npm install then npmstart would launch the live server

### Steps To Reproduce

1. In this environment...termux
2. With this config...
3. Run '...'
4. See error...
// /* see current behavior*/ //

### Environment

- npm:
- Node.js:
- OS Name: termux
- System Model Name: Samsung a136u
- npm config: newly installed
```ini
; "user" config from /data/data/com.termux/files/home/.npmrc

foreground-scripts = true

; node bin location = /data/data/com.termux/files/usr/bin/node
; node version = v18.12.1
; npm local prefix = /data/data/com.termux/files/home/airshare
; npm version = 8.19.2
; cwd = /data/data/com.termux/files/home/airshare
; HOME = /data/data/com.termux/files/home
; Run `npm config ls -l` to show all defaults.
```

**Comment by 5ide4ustle5ales** [comment]
I've actually found the issue from reading around, 
Npm has problem installing to anything without the global tag so npm install -global ran fine with no error outputs

**Comment by ljharb** [comment]
@5ide4ustle5ales that is definitely not a good workaround; almost everything should be installed locally, not globally.

Do note that termux's `PREFIX` env var conflicts with npm.

**Comment by 5ide4ustle5ales** [comment]
Ya it's still not quite working correctly

**Comment by fritzy** [comment]
Please update to the latest version of npm `npm i -g npm@latest` and re-open if still an issue.
