### ISSUE TITLE
[BUG] npm audit does not take workspaces/nested dependencies in account when using a custom repository

### ISSUE THREAD

**Issue by timewasternl** [npm/cli#6021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When attempting to run an `npm audit` after moving to NPM workspaces, it reported 0 vulnerabilities for the workspaces even when being sure those were present. Running it with `npm audit --registry=<npmjs registry url>` fixed this. When moving the vulnerable dependencies to the root `package.json` file, the audit was able to find the vulnerabilities.

### Expected Behavior

Running `npm audit` resulting in the same audit for workspace dependencies as it does for the root package and reporting the same amount of vulnerabilities. 
If this depends on the enterprise repository, I would not expect the behaviour to differ between root package and workspace package audits.

### Steps To Reproduce

1. Create an npm package with a workspace
2. Install a package that certainly has a vulnerability (I have usen json5@2.2.1 for this)
3. Run `npm audit`
4. It reports 0 vulnerabilities
5. Remove the vulnerable dependency from the workspace package and install it to the root `package.json`
6. Run `npm audit` again
7. It reports 1 high vulnerability

### Environment

- npm:
- Node.js: 9.2.0
- OS Name: x86_64 GNU/Linux
- System Model Name: AWS EC2 instance
- npm config:
```ini
fund = false 
registry = "https://<enterprise-url>/artifactory/api/npm/npm" 
```

**Comment by cedricmillet** [comment]
Problem does not seem new: https://stackoverflow.com/questions/62469080/npm-audit-on-private-package-in-artifactory

**Comment by rveerd** [comment]
I have the same issue with npm 8.19.2 and Verdaccio 5.1.3 registry.

I noticed that this version of the Verdaccio registry does not yet support the "Bulk Advisory Endpoint". npm than falls back to the older "Quick Audit Endpoint".

```
npm sill audit bulk request {
...
npm sill audit }
npm http fetch POST 404 https://***/-/npm/v1/security/advisories/bulk 82ms
npm sill audit bulk request failed <!DOCTYPE html>
...
npm sill audit 
npm http fetch POST 200 https://*/-/npm/v1/security/audits/quick 258ms
npm timing auditReport:getReport Completed in 368ms
```

Perhaps the "Quick Audit Endpoint" does not support auditing workspaces?

**Comment by rveerd** [comment]
Just updated Verdaccio to 5.20.1. This version does support the "Bulk Advisory Endpoint". Now npm audit also works in a workspace.

**Comment by timewasternl** [comment]
Great catch! Our enterprise repository neither seems to have support for Bulk Advisory Endpoint either, so that must be it then!
