### ISSUE TITLE
[BUG] Packages created using npm v9 break `npm ci`  on npm v6.

### ISSUE THREAD

**Issue by jeswr** [npm/cli#6023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

If I run `nvm use 19 && npm init -y && npm i is-even && nvm use 14 && npm ci` then the final command errors with:

```bash
npm ERR! Cannot read property 'is-even' of undefined
```

### Expected Behavior

The final `npm ci` to run succesfully 

### Steps To Reproduce

1. Install node version manager
2. Run `nvm use 19 && npm init -y && npm i is-even && nvm use 14 && npm ci` (where `is-even` can be replaced by any other package)

The full output from running these commands is
```bash
Now using node v19.3.0 (npm v9.2.0)
Wrote to /home/jesse/Documents/github/test/package.json:

{
  "name": "test",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "description": ""
}



added 5 packages, and audited 6 packages in 9s

found 0 vulnerabilities
Now using node v14.20.0 (npm v6.14.17)
npm WARN prepare removing existing node_modules/ before installation
npm ERR! Cannot read property 'is-even' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jesse/.npm/_logs/2023-01-04T02_25_27_783Z-debug.log
```

and the debug log is

```bash
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/jesse/.nvm/versions/node/v14.20.0/bin/node',
1 verbose cli   '/home/jesse/.nvm/versions/node/v14.20.0/bin/npm',
1 verbose cli   'ci'
1 verbose cli ]
2 info using npm@6.14.17
3 info using node@v14.20.0
4 verbose npm-session 10c48f0dd3d2f090
5 info prepare initializing installer
6 verbose prepare starting workers
7 verbose prepare installation prefix: /home/jesse/Documents/github/test
8 verbose prepare using package-lock.json
9 warn prepare removing existing node_modules/ before installation
10 verbose checkLock verifying package-lock data
11 verbose teardown shutting down workers.
12 info teardown Done in 0s
13 verbose stack TypeError: Cannot read property 'is-even' of undefined
13 verbose stack     at /home/jesse/.nvm/versions/node/v14.20.0/lib/node_modules/npm/node_modules/lock-verify/index.js:27:40
13 verbose stack     at Array.forEach (<anonymous>)
13 verbose stack     at /home/jesse/.nvm/versions/node/v14.20.0/lib/node_modules/npm/node_modules/lock-verify/index.js:25:25
14 verbose cwd /home/jesse/Documents/github/test
15 verbose Linux 5.19.0-26-generic
16 verbose argv "/home/jesse/.nvm/versions/node/v14.20.0/bin/node" "/home/jesse/.nvm/versions/node/v14.20.0/bin/npm" "ci"
17 verbose node v14.20.0
18 verbose npm  v6.14.17
19 error Cannot read property 'is-even' of undefined
20 verbose exit [ 1, true ]
```

### Environment

- OS Name: Linux Ubuntu 22.10 (Kinetic Kudu)
- System Model Name: Dell XPS 9520

Node 19
- npm: 9.2.0
- Node.js: 19.3.0
- npm config:
```ini
; "user" config from /home/jesse/.npmrc

//registry.npmjs.org/:_authToken = (protected) 

; "cli" config from command line options

location = "project" 

; node bin location = /home/jesse/.nvm/versions/node/v19.3.0/bin/node
; node version = v19.3.0
; npm local prefix = /home/jesse/Documents/github/test
; npm version = 9.2.0
; cwd = /home/jesse/Documents/github/test
; HOME = /home/jesse
; Run `npm config ls -l` to show all defaults.
```

Node 14
- npm: 6.14.17
- Node.js: 14.2.0
- npm config:
```ini
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.14.17 node/v14.20.0 linux x64"

; node bin location = /home/jesse/.nvm/versions/node/v14.20.0/bin/node
; cwd = /home/jesse/Documents/github/test
; HOME = /home/jesse
; "npm config ls -l" to show all defaults.
```

**Comment by ljharb** [comment]
Is it expected that a lockfile built in a newer version of npm will work in an older one? Typically a project using a lockfile has to ensure all developers use a similarly versioned CLI.

**Comment by jeswr** [comment]
There are 2 reasons I was expecting it should work:
1. npm@6 is shipped with Node 14 which is doesn't have an end-of-life until April. I would expect backwards compatibility until the EOL of Node 14, as without this compatibility I cannot run NodeJS CI checks on all active versions of Node.
2. This set of commands work if I have no dependencies in the lockfile - I would expect at least some kind of patch to npm@6 giving warning saying that there is no support for the version of lockfile provided.

```bash
$ nvm use 19 && npm init -y && npm i && nvm use 14 && npm ci
Now using node v19.3.0 (npm v9.2.0)
Wrote to /home/jesse/tmp/n/package.json:

{
  "name": "n",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "description": ""
}



up to date, audited 1 package in 41ms

found 0 vulnerabilities
Now using node v14.20.0 (npm v6.14.17)
added 0 packages in 0.011s
```

**Comment by lukekarrys** [comment]
This was an intentional breaking change in npm 9. The `lockfile-version` now defaults to `3` which is not compatible with `npm@6`. Note that this only applies to new projects, and `npm@9` will not attempt to change the version of any existing lockfiles.

To revert to the previous behavior you can set `lockfile-version=2` for your project with:

```
npm config set lockfile-version=2 --location project
```

There are no plans to update npm 6 to handle lockfiles later than version 2, as it is only receiving security updates.

**Comment by jeswr** [comment]
Node 14 LTS ends on April 30. It no longer think it is worth pursuing this fix.
