### ISSUE TITLE
[BUG] Installing a package changes the version of a project dependency

### ISSUE THREAD

**Issue by ejh1** [npm/cli#6027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Installing one package (ts-import-plugin) changes the version of a pre-existing project dependency, even after uninstalling the new package.

### Expected Behavior

The version of the existing project dependency should remain unchanged.

### Steps To Reproduce

1. npm init -y
2. npm i typescript@4.1.5 
3. cat package-lock.json 
{
  "name": "tstest",
  "version": "1.0.0",
  "lockfileVersion": 2,
  "requires": true,
  "packages": {
    "": {
      "name": "tstest",
      "version": "1.0.0",
      "license": "ISC",
      "dependencies": {
        "typescript": "^4.1.5"
      }
    },
    "node_modules/typescript": {
      "version": "4.1.5",
      "resolved": "https://registry.npmjs.org/typescript/-/typescript-4.1.5.tgz",
      "integrity": "sha512-6OSu9PTIzmn9TCDiovULTnET6BgXtDYL4Gg4szY+cGsc3JP1dQL8qvE8kShTRx1NIw4Q9IBHlwODjkjWEtMUyA==",
      "bin": {
        "tsc": "bin/tsc",
        "tsserver": "bin/tsserver"
      },
      "engines": {
        "node": ">=4.2.0"
      }
    }
  },
  "dependencies": {
    "typescript": {
      "version": "4.1.5",
      "resolved": "https://registry.npmjs.org/typescript/-/typescript-4.1.5.tgz",
      "integrity": "sha512-6OSu9PTIzmn9TCDiovULTnET6BgXtDYL4Gg4szY+cGsc3JP1dQL8qvE8kShTRx1NIw4Q9IBHlwODjkjWEtMUyA=="
    }
  }
}

4. Install and uninstall another package
npm install ts-import-plugin@2.0.0 
npm uninstall ts-import-plugin 

5. Now, the installed typescript version has changed to 4.9.4, changing the behavior of the project:

cat package-lock.json
{
  "name": "tstest",
  "version": "1.0.0",
  "lockfileVersion": 2,
  "requires": true,
  "packages": {
    "": {
      "name": "tstest",
      "version": "1.0.0",
      "license": "ISC",
      "dependencies": {
        "typescript": "^4.1.5"
      }
    },
    "node_modules/typescript": {
      "version": "4.9.4",
      "resolved": "https://registry.npmjs.org/typescript/-/typescript-4.9.4.tgz",
      "integrity": "sha512-Uz+dTXYzxXXbsFpM86Wh3dKCxrQqUcVMxwU54orwlJjOpO3ao8L7j5lH+dWfTwgCwIuM9GQ2kvVotzYJMXTBZg==",
      "bin": {
        "tsc": "bin/tsc",
        "tsserver": "bin/tsserver"
      },
      "engines": {
        "node": ">=4.2.0"
      }
    }
  },
  "dependencies": {
    "typescript": {
      "version": "4.9.4",
      "resolved": "https://registry.npmjs.org/typescript/-/typescript-4.9.4.tgz",
      "integrity": "sha512-Uz+dTXYzxXXbsFpM86Wh3dKCxrQqUcVMxwU54orwlJjOpO3ao8L7j5lH+dWfTwgCwIuM9GQ2kvVotzYJMXTBZg=="
    }
  }
}

### Environment

- npm: 8.19.3
- Node.js:v16.19.0
- OS Name: MacOS Big Sur 11.4
- System Model Name:MacBook Air (M1, 2020)
- npm config:
```ini
; node bin location = /Users/me/.nvm/versions/node/v16.19.0/bin/node
; node version = v16.19.0
; npm local prefix = /Users/me/Downloads/tsTest
; npm version = 8.19.3
; cwd = /Users/me/Downloads/tsTest
; HOME = /Users/me
```

**Comment by ParadoxInfinite** [comment]
@ejh1 This is due to cyclic dependency. You require `typescript@4.1.5`, however, `ts-import-plugin@2.0.0` requires `typescript >=4.2`. And since you didn't use the `-E` or `--save-exact` flag, it will auto-update the dependency accordingly.

P.S: If you use the `--save-exact` flag, your second dependency will not install citing failure to match required dependency.

**Comment by milaninfy** [comment]
Installation of any dependencies if you want to retain exact version then use --save-exact with npm install command https://docs.npmjs.com/cli/v10/commands/npm-install#save-exact
