### ISSUE TITLE
[DOCS] Documentation for package-lock.json is missing `from` field

### ISSUE THREAD

**Issue by alkorlos** [npm/cli#6030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Enhancement, not another kind of Docs Enhancement.

- [X] This is a CLI Docs Enhancement.

### Description of Problem

In a `package-lock.json` file may be field `from` which is not in the official documentation. https://docs.npmjs.com/cli/v9/configuring-npm/package-lock-json#dependencies

If in `package.json`
```json
 "example": "git+https://example.com/foo/bar#115311855adb0789a0466714ed48a1499ffea97e"
```
In `package-lock.json` will be
```json
"example": {
    "version": "git+https://example.com/foo/bar#115311855adb0789a0466714ed48a1499ffea97e",
    "from": "git+https://example.com/foo/bar#115311855adb0789a0466714ed48a1499ffea97e"
},
```

### Potential Solution

Adding a field `from` with it is description in the official documentation.

### Docs URL

https://docs.npmjs.com/cli/v9/configuring-npm/package-lock-json#dependencies

**Comment by fritzy** [comment]
"from" was used in npm@6 lockfiles, but was fairly nondeterministic. So it looks like it's unnecessary and vestigial at this point. In general, with v9 you should be migrating to v3 lockfiles.

**Comment by alkorlos** [comment]
Yes, thank you. In `node 18.12.1` and `npm 8.19.2`, `from` was still there, but not in node `node 18.15.0` and `npm 9.5.0`.
