### ISSUE TITLE
[BUG] npm install from github doesn't run prepare script

### ISSUE THREAD

**Issue by BrentBaccala** [npm/cli#6031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm (from the deb.nodesource.com/node_16.x repo)

### Current Behavior

I have a github-based node package that I'm trying to include as a dependency in another project.

### Expected Behavior

According to https://docs.npmjs.com/cli/v8/using-npm/scripts:

**prepare** (since `npm@4.0.0`)

- NOTE: If a package being installed through git contains a prepare script, its dependencies and devDependencies will be installed, and the prepare script will be run, before the package is packaged and installed.

The package's `package.json` contains, among other things:

```
  "scripts": {
...
    "prepare": "neutrino build",
...
   ],
...
  "devDependencies": {
    "gh-pages": "^2.1.1",
    "neutrino": "^8.1.2",
    "neutrino-preset-mozilla-frontend-infra": "^4.1.0",
    "react": "^16.14.0",
    "react-dom": "^16.14.0"
  },

```

I expect neutrino to be installed and a `neutrino build` to be run when I install the package.

### Steps To Reproduce

1. On Ubuntu 20.04, install `npm` from `https://deb.nodesource.com/node_16.x`
2. In an empty directory, run `npm init`
3. Run `npm install BrentBaccala/react-vnc-display`
4. Run `ls node_modules`
5. `neutrino` isn't there, and `neutrino build` wasn't run

### Environment

- npm: `8.19.3`
- Node.js: `v16.19.0`
- OS Name: Ubuntu 20.04.5 LTS
- System Model Name: Samsung 550XTA
- npm config:
```ini
; node bin location = /usr/bin/node
; node version = v16.19.0
; npm local prefix = /home/baccala/src/bigbluebutton-remote-desktop-2.4/bigbluebutton-html5
; npm version = 8.19.3
; cwd = /home/baccala/src/bigbluebutton-remote-desktop-2.4/bigbluebutton-html5
; HOME = /home/baccala
; Run `npm config ls -l` to show all defaults.

```

**Comment by HyperOC12** [comment]
retry it if fix it

**Comment by fritzy** [comment]
To be clear, the `prepare` script is run before it's installed in node_modules, so your dev dependencies won't be included. It's just to make sure that the package is in the same shape it'd be if it were `pack`ed or `publish`ed before installing it.
