### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by ima-antonio** [npm/cli#6032]
`npm ERR! cb() never called!`
`npm ERR! This is an error with npm itself. Please report this error at:`
`npm ERR!     <https://github.com/npm/cli/issues>`

`npm ERR! A complete log of this run can be found in:`
`C:\Users\******\AppData\Local\npm-cache\_logs\2023-01-07T22_22_59_109Z-debug.log`

Greetings, I got this error using the command: `npm install @capacitor/cli@latest-3 @capacitor/core@latest-3 --legacy-peer-deps`

In an ionic project that I intend to update, I believe that the error was caused by NVM, however I also pass the log for further clarification.

___A complete log of this run is here___
[2023-01-07T22_22_59_109Z-debug.log](https://github.com/npm/cli/files/10367302/2023-01-07T22_22_59_109Z-debug.log)

**Comment by fritzy** [comment]
Please upgrade to the current version of `npm`.
`npm i -g npm@latest`

**Closing:** please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).
