### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by cam1024** [npm/cli#6039]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

npm WARN npm npm does not support Node.js v18.13.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! cb.apply is not a function

### Expected Behavior

npm i

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 5.6.0
- Node.js: v18.13.0
- OS Name: windows
- System Model Name: hp envy
- npm config:
```ini
; copy and paste output from `npm config ls` here
```
npm WARN npm npm does not support Node.js v18.13.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! Usage:
npm ERR! npm config set <key> <value>
npm ERR! npm config get [<key>]
npm ERR! npm config delete <key>
npm ERR! npm config list [--json]
npm ERR! npm config edit
npm ERR! npm set <key> <value>
npm ERR! npm get [<key>]
npm ERR!
npm ERR! alias: c

**Comment by ljharb** [comment]
npm 5 is very obsolete, and node 18 ships with a much newer version of node.

Make sure you're not installing npm separately (it only comes with node, typical), and that you're installing node from an official installation source.

**Comment by fritzy** [comment]
Like @ljharb said, this is an unsupported configuration, and it'd be interesting to know how such an old version of npm got installed on Node.js v18.
