### ISSUE TITLE
[BUG] No way to determine if process is in bin anymore

### ISSUE THREAD

**Issue by k2snowman69** [npm/cli#6060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

As described in the [9.0.0](https://github.com/npm/cli/releases/tag/v9.0.0) release docs, `npm bin` has been removed in favor of npx which makes sense. However currently through npx, there is no way to determine if a process exists or not and only run it if it does exist.

Consider a shared script containing the following executions where some projects will have tslint (before upgrade) and some will have eslint (after upgrade) but from a shared script standpoint, we want to check which is installed (if any) and run what is available:
```shell
# For backwards compatibility
tslint
# Linting
eslint --fix
```

Originally we could use `npm bin` to determine if the folder to look for a process, determine if the process existed, and either run or skip it.

Further `npx --no does-not-exist` returns a exit code of `1` when it fails due to a package not being installed or existing. Currently it's impossible to distinguish as a caller for npx, if the exit code of `1` came from npx, or the underlying process npx is executing.

In summary currently with npx, there is now way to ignore a command if it's not installed.

### Expected Behavior

Somehow be able to check if a command is installed first and then run it if it's available. A few proposals all being new arguments:

 - `npx --no --ignore-missing prettier`
 - `npx --no --skip-if-missing prettier`
 - `npx --no --if-exists prettier`
 - `npx --no --if-present prettier`

### Steps To Reproduce

1. In npm@9.3.0
1. Run `npx --no does-not-exist`
1. Run `$?`, $LastExistCode, or however you get the last exist code for your environment
   1. Expect exit code to be 1
1. Run `npx --no prettier`
1. Get the last exit code again
   1. Expect exit code to be 1

Expect: No way to differentiate between the two failing exit codes

### Environment

- npm: 9.3.0
- Node.js: 18.12.1
- OS Name: Microsoft Windows 10 Pro
- System Model Name: AX370-Gaming K5
- npm config:
```ini
; "builtin" config from C:\Users\RickyPatel\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\RickyPatel\\AppData\\Roaming\\npm"

; "user" config from C:\Users\RickyPatel\.npmrc

//registry.npmjs.org/:_authToken = (protected)
//snowcoders.pkgs.visualstudio.com/_packaging/snowcoders/npm/registry/:_password = (protected)
//snowcoders.pkgs.visualstudio.com/_packaging/snowcoders/npm/registry/:email = "not-used@example.com"
//snowcoders.pkgs.visualstudio.com/_packaging/snowcoders/npm/registry/:username = "VssSessionToken"
registry = "https://registry.npmjs.org/"

; "cli" config from command line options

location = "project"

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v18.12.1
; npm local prefix = D:\Projects\exec-if-exists
; npm version = 9.3.0
; cwd = D:\Projects\exec-if-exists
; HOME = C:\Users\RickyPatel
; Run `npm config ls -l` to show all defaults.
```

**Comment by ljharb** [comment]
`npx -c 'which foo'`?

**Comment by k2snowman69** [comment]
Should be sufficient, wasn't expecting to use a separate library but makes sense. I can also grep off `npm ERR! code E404` on npx failure to determine the package isn't available.

Thanks!

**Comment by ljharb** [comment]
`which` isn't a library, it's a shell builtin.

**Comment by k2snowman69** [comment]
To support windows users I'd have to use the npm supported library; which doesn't exist on windows

**Comment by ljharb** [comment]
i suppose you could pivot on the OS and shell out to `which` or `where` as appropriate?
