### ISSUE TITLE
[BUG] Getting ENEEDAUTH in NPM 8 after adjusting .npmrc _auth setting as scoped

### ISSUE THREAD

**Issue by rvillane** [npm/cli#6062]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

As part of my CI/CD system, I use a private NPM registry with .npmrc and _auth setting as described in [1] to connect and it has worked just fine when using NPM 7 and 8, however, when execute pipelines to build NodeJS apps using NPM 9, I've got the following error that _auth setting must be scoped
 
npm ERR! code ERR_INVALID_AUTH
npm ERR! Invalid auth configuration found: '_auth' must be renamed to '//artifacts.mycompany.com/repository/npm/:_auth' in project config
npm ERR! Please run 'npm config fix' to repair your configuration.
 
 After implementing the .npmrc changes suggested about for the _auth setting, builds are working fine for Node apps using NPM 9, however, we are getting the following error when use the same .npmrc settings (updated per NPM 9 requirement above) in NPM 8 apps when trying to run npm publish command:
 
npm notice
npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in to https://artifacts.mycompany.com/repository/npm/
npm ERR! need auth You need to authorize this machine using `npm adduser`

[1] https://help.sonatype.com/repomanager3/nexus-repository-administration/formats/npm-registry/npm-security

### Expected Behavior

Considering that in NPM 8, there is a warning about the need to scope _auth to a registry, I would expect that when this change is made as is now required by NPM 9, that same .npmrc would be backward compatible in NPM 8.

`npm WARN config `_auth`, `_authToken`, `username` and `_password` must be scoped to a registry. see `npm help npmrc` for more information.
`

### Steps To Reproduce

1. In this environment...a folder with an .npmrc file having _auth scoped to a registry
2. With this config...
3. Run npm publish
4. See error npm ERR! code ENEEDAUTH

### Environment

- npm: 8.19.3
- Node.js: v16.19.0
- OS Name: Linux alpine

**Comment by rvillane** [comment]
I guess the bottom line question here is how to configure the `_auth` setting to be scoped to a registry and be compatible with NPM 8 and NPM 9

**Comment by ljharb** [comment]
`npm login --registry=whatever`?

**Comment by rvillane** [comment]
yup, I tested running that command and it works, but before the scoped _auth change, I didn't need to run `npm login --registry=whatever` command with NPM 8

**Comment by fritzy** [comment]
This seems to work in the latest npm@8 `npm@8.19.4`. Are you still seeing this there? Please re-open if not.
