### ISSUE TITLE
Security Enhancement: hide/mask OTP passwords while being entered

### ISSUE THREAD

**Issue by getify** [npm/cli#6065]
I have done some research and there seems to be a divide between whether UIs that accept entry of a OTP for 2FA should mask the input or show the digits.

The main argument I've seen for NOT showing the digits while typing them in is, a "shoulder surfer" attacker might be able to view the code you're typing *AND* be able to block (or even just delay) your network connection slightly so they can submit the code before you.

It feels to me like the display of digits in the CLI is at least as susceptible to such snooping as a web page UI.

The main counter-argument is that users like seeing what they type to make sure it's accurate. But they surely also would like to see their typed-in passwords for the same reasons, and yet most UI forms mask your passwords (definitely best-practice) and give you an option to unmask (temporarily) the password. So I don't think that's a strong argument to keep the CLI as it currently sits, where it shows the digits as typed.

So it feels like it would be slightly more secure if the NPM CLI tool masked (with `*`) the OTP entry. Optionally, some sort of hot-key keystroke could temporarily unmask/reveal the OTP for those who want to double-check just before entry.

Thoughts?

**Comment by ljharb** [comment]
(note that this would be more appropriate on npm/rfcs than here)

I don't think there's any value in masking - anywhere, not just here - nor do I think there's actual practical attacks carried out by "shoulder surfing".

Masking is the most common practice, but not the best one:
 - https://www.zdnet.com/article/we-need-to-stop-masking-passwords/
 - https://uxmovement.com/forms/why-password-masking-can-hurt-your-sign-up-form/
 - https://www.techrepublic.com/article/masking-passwords-why-its-not-a-good-idea/

In the case of an OTP, if someone already has your credentials somehow, why would they need to "shoulder surf"? They can just disable 2FA, or add their own device as an acceptable 2FA key. If they don't have your credentials, who cares if they see it?

**Comment by getify** [comment]
> ...why would they need to "shoulder surf"? They can just disable 2FA, or add their own device as an acceptable 2FA key

As far as I'm aware, proper 2fa services best practices mean you need to enter a 2fa code to be able to make changes (remove 2fa, add another 2fa device, etc). Indeed, that's how npm's own website works. I think that's kind of the point of 2fa, that knowing my credentials isn't enough. Which means if they can also snoop/phish a 2fa code, ***then*** they can compromise my account. Making that even a little more difficult seems like the appropriate conservative stance to take.

I don't agree with your position, nor those links, and I could paste several links making the argument in the other direction. As I said in the OP, it's a divided subject.

I think masking still serves a useful security role. I appreciate that many of the services I use do still mask passwords and OTPs. I wish npm was one of them.
