### ISSUE TITLE
[BUG] Prefix in .npmrc ignored

### ISSUE THREAD

**Issue by berarma** [npm/cli#6081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I'm trying to change the prefix for the current project using a .npmrc file.

The prefix in the .npmrc file is ignored. Tested with `npm install` and `npm prefix`.

The output of `node prefix` is the current directory instead of the configured directory.

### Expected Behavior

I expected `npm` to use the prefix in the .npmrc file.

### Steps To Reproduce

1. Create file `.npmrc` with contents `prefix=./vendor`.
2. Run `npm prefix` or `npm install`.
3. The first command shows the current directory and install creates `./node_modules` in the current directory.

### Environment

- npm: 9.3.1
- Node.js: v14.21.2
- OS Name: Debian GNU/Linux 11.5
- System Model Name: PC
- npm config:
```ini
; "project" config from /home/xxxx/yyyy/.npmrc

prefix = "/home/xxxx/yyyy/vendor" 

; node bin location = /usr/bin/node
; node version = v14.21.2
; npm local prefix = /home/xxxx/yyyy
; npm version = 9.3.1
; cwd = /home/xxxx/yyyy
; HOME = /home/xxxx
; Run `npm config ls -l` to show all defaults.
```

**Comment by wraithgar** [comment]
`prefix` can not be changed from the project level, npm has already parsed that level of config by the time it is parsing the `.npmrc` file.

npm should probably log an error if it sees you trying to do that.

**Comment by berarma** [comment]
Any other way to change the location of the `node_modules` directory inside the project that doesn't require environment variables or command options? I would like it to be as automatic as possible based on the current directory.

**Comment by ljharb** [comment]
No, and lots of tooling depends on it being in that exact location, so it shouldn’t be moved.

**Comment by rahulio96** [comment]
Hello, I'm an intern at CodeDay Labs and I've been working on resolving this issue alongside my teammate, Aaron.
