### ISSUE TITLE
Use .npmrc from nearest parent directory

### ISSUE THREAD

**Issue by edbrannin** [npm/cli#6087]
Issue (labelled patch-welcome) in previous repo: https://github.com/npm/npm/issues/11437

For people who work at a company that uses a private npm registry, it would be very helpful if we could override the npm registry in a parent folder.

This is mostly a minor annoyance

## Workaround: 

1. Copy the following `.npmrc` into each personal project folder before running `npm install` (or similar)
    ```
    registry=https://registry.npmjs.org/
    ```
2. If something already ran `npm install` before step 1, delete `package-lock.json` & `node_modules/` and run `npm install` again
    - Examples of things that would do this:
    - create-react-app
    - create-next-app (also commits the incorrect `package-lock.json` to git)
    - Yourself running `npm init -y && npm install foo` without remembering to start with step 1

## Steps to reproduce:
1. Work at a company that uses a private npm registry.
2. Set up that private npm registry in `$HOME/.npmrc`
4. Do work development in `$HOME/dev/work`
5. Have some personal side-projects under `$HOME/dev/personal`
6. Add `registry=https://registry.npmjs.org/` to `$HOME/dev/personal/.npmrc`

## Expected result:
- `npm install` uses the company registry in `$HOME/dev/work/company-app`
- `npm install` uses the public registry in `$HOME/dev/personal/awesome-bananaphone`

## Observed result:
- `npm install` uses the company registry in both `$HOME/dev/work/company-app` and `$HOME/dev/personal/awesome-bananaphone` until you remember to do the above workaround

**Comment by fritzy** [comment]
Can you create [an RRFC](https://github.com/npm/rfcs/issues/new?assignees=&labels=&template=rrfc.md&title=%5BRRFC%5D+%3Ctitle%3E) in that repo?

**Comment by TWiStErRob** [comment]
Does this feature exist in any form? (Considering it's closed as completed.)
