### ISSUE TITLE
Automatinmg policies with nodejs using citgm

### ISSUE THREAD

**Issue by saquibkhan** [npm/cli#6088]
- https://github.com/npm/cli/pull/6049
- https://github.com/npm/cli/pull/6084

**Comment by nlf** [comment]
this is just waiting for today's release to go out so i can verify the workflows run as intended. once i've confirmed that, i'll close this issue.

**Comment by nlf** [comment]
the workflow ran correctly! we have a few things that are popping up as failures that should be marked as known failures, i'll make those tweaks today and then call this finished for the time being.
