### ISSUE TITLE
[BUG] If npm registry fails with "503 (service is unavailable)" during publish - it does not allow to re-publish the same version

### ISSUE THREAD

**Issue by KonstantinEpam23** [npm/cli#6103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

During publishing a package - a 503 (service unavailable error occurred)

Log:
```
npm publish --tag beta
...
npm notice Publishing to https://registry.npmjs.org/

npm ERR! code E503
npm ERR! 503 Service Unavailable - PUT https://registry.npmjs.org/ketcher-standalone - Service Unavailable

npm ERR! A complete log of this run can be found in: ...
```

After retrying a EPUBLISHCONFLICT error appears:
```
npm publish --tag beta
...
npm ERR! code EPUBLISHCONFLICT
npm ERR! publish fail Cannot publish over existing version.
npm ERR! publish fail Update the 'version' field in package.json and try again.
npm ERR! publish fail 
npm ERR! publish fail To automatically increment version numbers, see:
npm ERR! publish fail     npm help version

npm ERR! A complete log of this run can be found in: ...
```

The email of successful publish was not received.

The package in question is: https://www.npmjs.com/package/ketcher-standalone?activeTab=versions
The version that was not published correctly is 2.8.0-rc.1 (beta channel)

### Expected Behavior

If a 503 service unavailable error occurs during publish - republishing should be available and should not cause a EPUBLISHCONFLICT error.

### Steps To Reproduce

n/a

### Environment

- npm: 8.15.0
- Node.js: 16.17.0
- OS Name: MacOS 13.0.1 (22A400)
- System Model Name: Macbook Pro
- npm config:
```ini
; "user" config from /Users/username/.npmrc

//registry.npmjs.org/:_authToken = (protected) 

; node bin location = /usr/local/bin/node
; node version = v16.17.0
; npm local prefix = /Users/...
; npm version = 8.15.0
; cwd = /Users/...
; HOME = /Users/...
; Run `npm config ls -l` to show all defaults.
```

**Comment by wraithgar** [comment]
This is a registry issue.  The 503 happened after the registry accepted the new version, so subsequent publishes collide w/ that.  There isn't anything the npm cli can do about this.
