### ISSUE TITLE
[BUG] npm hangs when trying to install package with same name as workspace

### ISSUE THREAD

**Issue by jabrks** [npm/cli#6104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

If I try to install a package in one workspace that has the same name as another workspace, and the versions don't match, then npm will hang at
```
(#########⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠧ idealTree:workspaces-repro: timing idealTree:#root Completed in 0ms
```

### Expected Behavior

npm should attempt to install the specified version of the package from a registry and throw an error if it doesn't exist

### Steps To Reproduce

```bash
mkdir workspaces-repro
cd workspaces-repro

npm init -y
npm init -y -w packages/package
npm init -y -w packages/react

npm install react@18.2.0 -w package
```

### Environment

- npm: 9.4.0
- Node.js: 18.13.0
- OS Name: macOS Ventura 13.2
- System Model Name: MacBook Pro
- npm config:
```ini
; node bin location = /Users/james.brooks/.nvm/versions/node/v18.13.0/bin/node
; node version = v18.13.0
; npm local prefix = /Users/james.brooks/Desktop/workspaces-repro
; npm version = 9.4.0
; cwd = /Users/james.brooks/Desktop/workspaces-repro
; HOME = /Users/james.brooks
; Run `npm config ls -l` to show all defaults.
```

**Comment by fritzy** [comment]
This may is yet another indicator that we should prioritize working on a "workspace:" protocol for declaring dependencies. 

@jabrks  However, I'm not able to reproduce in npm@9.6.0. Can you confirm?

```
❯ npm ls -a
workspaces-repro@1.0.0 /Users/fritzy/projects/scratchpad/workspaces-repro
├─┬ package@1.0.0 -> ./packages/package
│ └─┬ react@18.2.0
│   └─┬ loose-envify@1.4.0
│     └── js-tokens@4.0.0
└── react@1.0.0 -> ./packages/react
```

**Comment by jabrks** [comment]
Hi @fritzy, I can confirm this is no longer a problem for me on the latest version of npm. 

I would welcome the introduction of a "workspace:" protocol. We don't want to use the local workspace version of a dependency in some cases, so to have the option to easily switch between that and the latest version of the dependency from the registry would be beneficial
