### ISSUE TITLE
Add new abilities to specify package's permission

### ISSUE THREAD

**Issue by chiro-hiro** [npm/cli#6105]
# Problem

I've a concern if the installed package going to send the confidential information over the internet or steal my private key and send it to hacker. Are there any solution to specify permission of given package.

E.g:
We add a new section in `package.json` describe permission that required of the given package.
```json
"permissions": {
    "ACCESS_FILE": false,
    "ACCESS_NETWORK": false
}
```

I think, It is necessary to enforce package's permission. Honesty, I don't think all packages in the wild were well audited.

**Comment by ljharb** [comment]
That'd be part of node, not npm - look into node's experimental "policies" feature.

(If it were to be applicable to npm, then it'd need to be filed as an RRFC)
