### ISSUE TITLE
How can I lock the NPM version used in a github repository?

### ISSUE THREAD

**Issue by lfender6445** [npm/cli#6107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Problem, not another kind of Docs Problem.

- [X] This is a CLI Docs Problem.

### Description of Problem

I would like to lock the NPM version my team is using for a specific repository. We are using asdf to manage nodejs versions, but lack the ability to lock in a specific version of npm.  

I could use npm engine to suggest the use of a specifc NPM version but the reality is that my team is bouncing around different repositories that use different versions of NPM:

```
  "engines": {
    "npm": ">= 9.*.*",
    "node": ">= 16.*.*"
  },
```

A global install of npm `npm install -g npm` gives me npm@9.4 for all repositories, which is not what I want. 

I would much prefer the correct version of NPM is auto loaded when I cd into a repository, similar to yarn policies https://classic.yarnpkg.com/en/docs/cli/policies/ (but for NPM) where the binary is checked in - is this possible? 

I have seen recommendations for engine-strict, but this would still require a developer to `npm install -g npm@my_repo_version` every time they change projects, which I do not want. It is not clear from the documentation if this is possible

### Potential Solution

Is there a recommended way to commit the NPM binary with version control so that all team members are using the same version? 

### Affected URL

https://docs.npmjs.com/cli/v9/configuring-npm/package-json#engines

**Comment by ljharb** [comment]
`engines.npm` (which should only be used in an app, never a package) is the only way.

There is not anything i'm aware of short of something like volta that can automatically manage both node and npm versions. Either way, such a tool wouldn't be part of npm itself, since it would be managing npm.

**Comment by wraithgar** [comment]
As @ljharb states, this is not something npm itself can manage.
