### ISSUE TITLE
[DOCS] Remove outdated packages

### ISSUE THREAD

**Issue by NuroC** [npm/cli#6109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Enhancement, not another kind of Docs Enhancement.

- [X] This is a CLI Docs Enhancement.

### Description of Problem

I am currently working on an API, and there's a different npm package which basically takes up the name that I would like to use. The npm package is not functional anymore and hasnt been maintained or touced in 3 years. (https://www.npmjs.com/package/moomoo).

### Potential Solution

Removing the owner or sending an email to the owner saying the package would expire could be a possible solution. Or do I have to solve this issue directly with the owner?

**Comment by wraithgar** [comment]
This repo is for tracking issues w/ the npm cli. The request you have made here is one that can only be handled through the npm registry. Support link is https://www.npmjs.com/support

However it is unlikely you will be able to get this package given only the reasons listed.  The [dispute policy](https://docs.npmjs.com/policies/disputes#when-not-to-use-this-process) explicitly calls out lack of activity as NOT one of the reasons for claiming a package name.
