### ISSUE TITLE
Issues with installing a config for a beginner javascript course

### ISSUE THREAD

**Issue by AmyCox** [npm/cli#612]
![Screenshot 2019-12-18 at 10 24 39](https://user-images.githubusercontent.com/22813619/71078630-b0448600-2181-11ea-8415-ba342187ef83.png)

**Comment by anantbahuguna** [comment]
You can try to reinstall npm with a nvm [Install npm](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm).
If still not working try the steps mentioned here [npm docs](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally)

**Comment by DanielRuf** [comment]
This is a known issue with the file permissions.
