### ISSUE TITLE
[BUG] Local dependencies not updating

### ISSUE THREAD

**Issue by dalisoft** [npm/cli#6124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Locally linked/set dependencies not updating after installation.

Tried different options such as:
- `npm i --install-strategy=linked`
- `npm i --install-strategy=shallow`
- `npm i --install-strategy=nested`

And neither of them help

### Expected Behavior

Same behavior as **npm v8**

### Steps To Reproduce

1. Clone repo via `git clone git@github.com:dalisoft/pnpm-esbuild.git`
2. Go-to folder via `cd pnpm-esbuild`
3. Go-to `frontend` folder via `cd frontend`
4. Run `npm install`
5. Change file `ui-shared/components/Button/Button.jsx` and check updates from `frontend/node_modules/@shared/ui/components/Button/Button.jsx`

### Environment

- npm: v9.3.1
- Node.js: v19.5.0
- OS Name: macOS Monterey 12.6.3
- System Model Name: Macbook Pro M1 2020
- npm config:
```ini
; "builtin" config from /opt/homebrew/lib/node_modules/npm/npmrc

; prefix = "/opt/homebrew" ; overridden by env

; "user" config from /Users/dalisoft/.npmrc

; auto-install-peers = true ; overridden by project
strict-peer-dependencies = true 
use-lockfile-v6 = true 

; "project" config from /Users/dalisoft/Desktop/bug/pnpm-esbuild/frontend/.npmrc

auto-install-peers = true 

; "env" config from environment

prefix = "/Users/dalisoft/.npm-global" 

; node bin location = /opt/homebrew/Cellar/node/19.5.0/bin/node
; node version = v19.5.0
; npm local prefix = /Users/dalisoft/Desktop/bug/pnpm-esbuild/frontend
; npm version = 9.3.1
; cwd = /Users/dalisoft/Desktop/bug/pnpm-esbuild/frontend
; HOME = /Users/dalisoft
; Run `npm config ls -l` to show all defaults.

```

**Comment by dvester** [comment]
I can also confirm this issue. I am on NPM version `9.3.1` and have a mono-repo setup where we reference our shared packages from multiple folders. Our dependency looks like this.

```
"dependencies": {
    "@company/model": "file:../model"
}
```

NPM Version <= 8 would create a symbolic link to the shared package folder directly, and any changes would be visible immediately in our other projects. But the new version of NPM copies the entire contents of our shared package folder into the `node_modules` folder of the parent project.

**UPDATE** Also tried it with NPM version `9.4.0` and `--install-strategy=linked` did restore the symbolic link for the file reference, however, it also created symbolic links for almost all the other normal packages. So from what I can tell, there is not currently a way to restore the previous behavior of just creating a symbolic link for local file references.

**Comment by dalisoft** [comment]
@dvester I am tried the `--install-strategy=linked` too and it not worked for me, references same old files (or last installed files). Please can you re-check behavior for me?

**Comment by fritzy** [comment]
The option you're looking for is `--install-links=false`, which had it's default changed to `true` in `9.0.0`, but was reverted to `false` in `9.4.2` due to confusion like this. Update to the latest version, and it works.
