### ISSUE TITLE
[BUG] dependencies not present when install scripts are invoked with install-strategy=linked

### ISSUE THREAD

**Issue by gavinsharp** [npm/cli#6135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I have been experimenting with `--install-strategy=linked` using npm 9.4.1 in a large-ish monorepo.

The first issue I ran into seems like a fairly basic one, where one of our dependencies (`bufferutil`) has an [`install` script](https://github.com/websockets/bufferutil/blob/4020ad44a7612040facf86bc91dc2aaf0ef38433/package.json#L10) that [relies on a dependency](https://github.com/websockets/bufferutil/blob/4020ad44a7612040facf86bc91dc2aaf0ef38433/package.json#L29) (`node-gyp-build`).

Installing this dependency fails when using `--install-strategy=linked` (see below).

### Expected Behavior

Package with an `install` script that relies on invoking a dependency's scripts succeeds.

### Steps To Reproduce

1. With `npm` v9.4.1 on a Mac 
2. Run:
```
mkdir tmp-npm-bug && cd tmp-npm-bug && npm init -y
npm install --install-strategy=linked bufferutil@4.0.7
```
3. See error:
```
npm WARN reify The "linked" install strategy is EXPERIMENTAL and may contain bugs.
npm ERR! code 127
npm ERR! path /Users/gavin/dev/tmp-npm-install-linked/node_modules/.store/bufferutil@4.0.7-YpxTsim8olsHVs9iNz9edQ/node_modules/bufferutil
npm ERR! command failed
npm ERR! command sh -c node-gyp-build
npm ERR! sh: node-gyp-build: command not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gavin/.npm/_logs/2023-02-06T20_10_54_221Z-debug-0.log
```

### Environment

- npm: 9.4.1
- Node.js: v16.13.2
- OS Name: macOS 13.0.1 (Ventura)
- System Model Name: MacBook Pro (M1 Max)
- npm config:
```ini
; node bin location = /Users/gavin/.nvm/versions/node/v16.13.2/bin/node
; node version = v16.13.2
; npm local prefix = /Users/gavin/dev/tmp-npm-install-linked
; npm version = 9.4.1
; cwd = /Users/gavin/dev/tmp-npm-install-linked
; HOME = /Users/gavin
; Run `npm config ls -l` to show all defaults.
```

**Comment by fritzy** [comment]
Fixed in `npm@9.5.1`.
