### ISSUE TITLE
[BUG] Binaries defined by the current package are not recognized as available binaries inside itself by npm run

### ISSUE THREAD

**Issue by fabiospampinato** [npm/cli#6141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I have something like this:

```json
{
  "name": "tsex",
  "bin": "./dist/bin.js",
  "scripts": {
     "compile": "tsex compile"
  }
}
```

And running `npm run compile` leads to the following error:

```
zsh:1: command not found: tsex
```

### Expected Behavior

I think this error shouldn't exist because "npm run" (and npx I guess) should be able to recognize that the "tsex" binary mentioned in the script is actually provided by the package itself.

### Steps To Reproduce

Do something like the above.

### Environment

- npm: 8.19.2
- Node.js: 18.12.0
- OS Name: macOS
- System Model Name: What's a system?
- npm config:
```ini
; "user" config from /Users/fabio/.npmrc

//registry.npmjs.org/:_authToken = (protected) 
package-lock = false 
script-shell = "zsh" 

; node bin location = /Users/fabio/.nvm/versions/node/v18.12.0/bin/node
; node version = v18.12.0
; npm local prefix = /Users/fabio/Code/fabiospampinato/tsex
; npm version = 8.19.2
; cwd = /Users/fabio/Code/fabiospampinato/tsex
; HOME = /Users/fabio
; Run `npm config ls -l` to show all defaults.
```

**Comment by ljharb** [comment]
Scripts are not accessible to things that install the package. That’s what “bin” is for.

**Comment by ljharb** [comment]
npm has always worked this way; in the same package you need to copy the path to the bin, afaik.

**Comment by fabiospampinato** [comment]
Yeah I don't think it ever worked in any version of NPM that I used, I think it should work though.

**Comment by ljharb** [comment]
In that case it sounds like you want to file an RRFC on github.com/npm/rfcs ?

**Comment by fabiospampinato** [comment]
Do you want me to do that? I consider this a bug, but I'd be happy to move the issue elsewhere if needed.

**Comment by ljharb** [comment]
It’s intentional behavior since the dawn of npm; it can’t be a bug :-) it’s a feature request to me.

**Comment by fabiospampinato** [comment]
If "npm run script_name" worked for any script name other than "asdasd" it would probably be intentional also, but it still wouldn't make sense.

Anyway I'll move the issue 👍
