### ISSUE TITLE
[BUG] Conflicting bin executable links from transitive dependencies

### ISSUE THREAD

**Issue by TWiStErRob** [npm/cli#6152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```
bin-conflict$ npm exec webdriver-manager version
[13:48:25] I/version - webdriver-manager 12.1.9
```

Which means `node_modules/.bin/webdriver-manager` points to `node_modules/protractor/bin/webdriver-manager` which points to `node_modules/protractor/node_modules/webdriver-manager/bin/webdriver-manager`.

### Expected Behavior

```
bin-conflict$ npm exec webdriver-manager version
[13:48:25] I/version - webdriver-manager 13.0.1
```

Which means `node_modules/.bin/webdriver-manager` points to `node_modules/webdriver-manager/bin/webdriver-manager`.

### Steps To Reproduce

1. Clone https://github.com/TWiStErRob/repros/tree/master/npm/bin-conflict
2. `npm install`
3. Run `npm exec webdriver-manager version` to see which version is installed.

Note: `dependencies` vs `devDependencies` doesn't matter. Same if moved together, but this is more realistic to my original setup.

I've found https://github.com/npm/cli/issues/3905, but in that case two different packages were defining the same binary, in this case the binary is coming from different versions of the same package.

Before I updated the webdriver-manager from 12.1.9 to 13.0.1, it worked perfectly fine, the version was matching (because the transitive dependency was compatible), AND the bin pointed to the right folder.

### Environment

- npm: 8.19.3
- Node.js: 16.14.2
- OS Name: Windows 10
- System Model Name: ?
- npm config:
```ini
; "env" config from environment

cache = "P:\\caches\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v16.14.2
; npm local prefix = p:\projects\bugs\npm\bin-conflict
; npm version = 8.19.3
; cwd = p:\projects\bugs\npm\bin-conflict
; HOME = C:\Users\TWiStEr
; Run `npm config ls -l` to show all defaults.
```

**Comment by wraithgar** [comment]
This is fundamentally the same as #3905, two of your dependencies are trying to define a `webdriver-manager` bin. Only one can win and it is not something that can be controlled outside of rebuilding the one you want to win

```sh
~/D/n/s/bindupe $ ls -al node_modules/.bin/webdriver-manager
lrwxr-xr-x  1 wraithgar  staff  35 Apr 20 16:58 node_modules/.bin/webdriver-manager@ -> ../protractor/bin/webdriver-manager
~/D/n/s/bindupe $ npm rebuild webdriver-manager
rebuilt dependencies successfully
~/D/n/s/bindupe $ ls -al node_modules/.bin/webdriver-manager
lrwxr-xr-x  1 wraithgar  staff  42 Apr 20 16:58 node_modules/.bin/webdriver-manager@ -> ../webdriver-manager/bin/webdriver-manager
```

**Comment by TWiStErRob** [comment]
@wraithgar isn't there a fundamental issue that I (as a user) declare a dependency that I want to use, and some random library overwrites my preference? Shouldn't the ordering be "explicit wins", which would mean installing the transitive deps first and then the root dependencies. Since it's non-deterministic now, you (as the author of the tool that resolves things) could fix the ordering to be consistent and meaningful.
