### ISSUE TITLE
[BUG] Dependencies in cli

### ISSUE THREAD

**Issue by 4i8** [npm/cli#6159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I am the owner of this package and The package does not have dependencies, and when you download it, it downloads other packages
![image](https://user-images.githubusercontent.com/76555623/218240274-fa67df93-ea3d-4304-9123-b6204da10925.png)
![Screenshot from 2023-02-11 07-39-32](https://user-images.githubusercontent.com/76555623/218240304-f43d08bc-c451-427b-b64b-82e100a3e1f1.png)

### Expected Behavior

Hidden packages can be combined in the same way and cause the user to be hacked without knowing

### Steps To Reproduce

The problem is as follows: If you publish the package the first time, and this package has Dependencies, and you delete it and publish it again without Dependencies, when you install the package, you will find that it installs old Dependencies that are not included in this version

### Environment

; "user" config from /home/arth/.npmrc

//registry.npmjs.org/:_authToken = (protected) 

; node bin location = /usr/bin/node
; node version = v18.14.0
; npm local prefix = /home/arth/Desktop/iipc_Test
; npm version = 9.4.2
; cwd = /home/arth/Desktop/iipc_Test
; HOME = /home/arth
; Run `npm config ls -l` to show all defaults.

**Comment by wraithgar** [comment]
This appears to be an issue with the npm registry website, not with the cli.

**Comment by 4i8** [comment]
In cli, before you close, Understand what the problem is 😆

**Comment by ljharb** [comment]
@4i8 which version are you referring to? https://unpkg.com/browse/iipc@0.0.1-b/package.json has no deps, and that's the only version currently published. If you unpublish it, it can't ever be republished - so perhaps if you had 0.0.1-a in your cahce with deps (and had unpublished it), that would cause the behavior you're seeing - but since semver ranges don't include prereleases by default, it's highly likely that your local package.json was pointing to the a version and thus never attempting to install the b version.

**Comment by 4i8** [comment]
> @4i8 which version are you referring to? https://unpkg.com/browse/iipc@0.0.1-b/package.json has no deps, and that's the only version currently published. If you unpublish it, it can't ever be republished - so perhaps if you had 0.0.1-a in your cahce with deps (and had unpublished it), that would cause the behavior you're seeing - but since semver ranges don't include prereleases by default, it's highly likely that your local package.json was pointing to the a version and thus never attempting to install the b version.

@ljharb ljharb I have re-published it on a different version and there is no deps, and if you install the new version of the package does not have deps, it will install deps of the first version that you unpublished

**Comment by ljharb** [comment]
@4i8 not on my machine; it installs the b version with no deps.
