### ISSUE TITLE
Get several instances of `@material-ui/styles` initialised in this application warning.

### ISSUE THREAD

**Issue by ankitpatelinitio** [npm/cli#617]
I developed my own progress bar npm and publish it. I am using @material-ui/core npm to apply CSS styles on the progress bar.

      After successfully publish my npm and install this npm package into my existing application. But @material-ui/core npm is already installed in my existing application and progress bar npm also. So When I install progress bar npm in my existing application and run it at that time it gives me a below warning and my progress bar npm not working.
    
      It looks like there are several instances of @material-ui/styles initialized in this application. This may cause theme propagation issues, broken class names, specificity issues, and makes your application bigger without a good reason.

      I refer https://material-ui.com/getting-started/faq/#i-have-several-instances-of-styles-on-the-page document also but not get any solution

      Anyone, please suggest me a solution.

**Comment by mikemimik** [comment]
Hello @ankitpatelinitio is it possible for you to link the repository you're speaking about? I am a little confused on some details. Thanks in advance!

**Comment by ankitpatelinitio** [comment]
Hello, @mikemimik Here is npm link that I am created. https://www.npmjs.com/package/my-test-react-component
