### ISSUE TITLE
[DOCS] install-links default value is listed as false

### ISSUE THREAD

**Issue by manuartero** [npm/cli#6177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Problem, not another kind of Docs Problem.

- [X] This is a CLI Docs Problem.

### Description of Problem

According to [npm v9 config documentation](https://docs.npmjs.com/cli/v9/using-npm/config?v=true#install-links), `install-links` default value is `false`

![Captura de Pantalla 2023-02-16 a las 15 54 40](https://user-images.githubusercontent.com/2211052/219399160-c003bbd5-b03b-48a2-a905-f6dd461e1985.png)

While I do think the default value (`npm@9`) for this is config flag is `true`;

```bash
 $» npm config ls -l
; "default" config from default values

...
init.version = "1.0.0"
install-links = true
install-strategy = "hoisted"
...

; "user" config from /Users/cx01885/.npmrc

//registry.npmjs.org/:_authToken = (protected)

; "cli" config from command line options

long = true

```

```bash
$» npm config get install-links
true
```

As you can see I have not override the default value;

***

```bash
 $» npm --version
9.3.1
```

```bash
 $» node --version
v18.14.0
```

### Potential Solution

Change the doc page: 

```diff
### `install-links`

- Default: false
+ Default: true
```

### Affected URL

https://docs.npmjs.com/cli/v9/using-npm/config

**Comment by ljharb** [comment]
The default value of install-links was changed from true (new in 9.0.0) to false in a later version of npm (the latest is 9.5.0).

**Comment by nlf** [comment]
https://github.com/npm/cli/blob/latest/CHANGELOG.md#942-2023-02-07

the default got set back to `false` in 9.4.2, the current docs are correct.

**Comment by manuartero** [comment]
This seems almost to a breaking change to me 🤷
