### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by Rameez-Rahil** [npm/cli#618]
C:\Users\ramee\iSplendidtask\iSplendidApp>npm install --save react-navigation
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ramee\AppData\Roaming\npm-cache\_logs\2019-12-19T14_14_22_526Z-debug.log

**Comment by rishi-singh26** [comment]
I had the same problem, don't know what to do

**Comment by mikemimik** [comment]
Duplicate issue; aggregating into https://github.com/npm/cli/issues/417.
