### ISSUE TITLE
[BUG] npm unlink not work.

### ISSUE THREAD

**Issue by wuweikd** [npm/cli#6191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

one day,I used `npm link pb-2-js` to test the bin,  now i need remove it,but  'npm unlink pb-2-js' not work.

### Steps To Reproduce

<img width="510" alt="image" src="https://user-images.githubusercontent.com/34428646/220551547-7f37d107-5556-426c-a9fc-87dc627cb9f0.png">

### Environment

- npm: 8.3.1
- Node.js:16.14.0
- OS Name: mac os M1
- System Model Name: Macbook Pro
- npm config:
```ini
; "user" config from /Users/wuwei/.npmrc

@yy:registry = "https://npm-registry.duowan.com/" 
//npm-registry.duowan.com/:_authToken = (protected) 
//registry.npmjs.org/:_authToken = (protected) 
email = "wuwei3@joyy.com" 
home = "https://www.npmjs.org" 
registry = "https://registry.npmjs.org/" 

; node bin location = /Users/wuwei/.nvm/versions/node/v16.14.0/bin/node
; cwd = /Users/wuwei
; HOME = /Users/wuwei
; Run `npm config ls -l` to show all defaults.
```

**Comment by fritzy** [comment]
@wuweikd  can you try replicating this problem on the latest version of `npm`? (ie. `npm i -g npm`).

Please reopen if this is still an issue.

**Comment by hanalice** [comment]
node 18.13.0 can't work also.
