### ISSUE TITLE
[DOCS] Archived `npm/npm` repo still points to `npm.community`; redirect has bad cert

### ISSUE THREAD

**Issue by thw0rted** [npm/cli#6194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Problem, not another kind of Docs Problem.

- [X] This is a CLI Docs Problem.

### Description of Problem

The [archived npm repo](https://github.com/npm/npm) prominently links to http://npm.community/ in several places.  This domain now redirects to `npmjs.com` -- reasonable people can disagree over how helpful this is, I guess, but that's not my point here.  The problem is that the redirect involves going through a connection to `npm.community` which is signed with a wildcard cert that is only good for `*.github.com`.

### Potential Solution

If you're going to leave a redirect page there, it should be signed with a cert that is valid for the domain that the user is visiting.

(It would be great if the redirect went somewhere more useful for getting actual NPM support, like this repository, or a direct link to the `npm/feedback` repo, rather than the package repository homepage, but that's neither here nor there.)

### Affected URL

http://npm.community/

**Comment by thw0rted** [comment]
I also found #698, #977, and #1280, but I'm not sure they're relevant.  I also tried to report this on `npmjs.com` but without a login my only option was to treat it as a "security issue" (which it is, sort of), but there were no applicable sub-issue types for "bad cert on a redirect to your site", so here we are.

**Comment by fritzy** [comment]
The certificate appears to be in good shape.

**Comment by jpluscplusm** [comment]
> The certificate appears to be in good shape.

It isn't.

```
$ curl -v https://npm.community
* Host npm.community:443 was resolved.                                     
* IPv6: (none)                                                              
* IPv4: 140.82.112.18                                                                                                                                   
*   Trying 140.82.112.18:443...
* Connected to npm.community (140.82.112.18) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256 / X25519 / RSASSA-PSS
* ALPN: server accepted h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=*.github.com
*  start date: Jun  9 00:00:00 2024 GMT
*  expire date: Jun 11 23:59:59 2025 GMT
*  subjectAltName does not match npm.community
* SSL: no alternative certificate subject name matches target host name 'npm.community'
* Closing connection
* TLSv1.3 (OUT), TLS alert, close notify (256):
curl: (60) SSL: no alternative certificate subject name matches target host name 'npm.community'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
