### ISSUE TITLE
[BUG] EPERM on mkdir C:\

### ISSUE THREAD

**Issue by uzair-learner** [npm/cli#6195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I could not resolve this issue please advise.

C:\Datting>npm --v
9.5.0

C:\Datting>npm install @angular/cli@12.2.13
npm ERR! code EPERM
npm ERR! syscall mkdir
npm ERR! path C:\
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, mkdir 'C:\'
npm ERR!  [Error: EPERM: operation not permitted, mkdir 'C:\'] {
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: 'C:\\'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\amir\AppData\Local\npm-cache\_logs\2023-02-24T05_30_09_633Z-debug-0.log

C:\Datting>

![Untitled](https://user-images.githubusercontent.com/123616687/221100558-c9695aa0-2341-4baf-85db-f30c28fb7f09.jpg)

### Expected Behavior

Cannot run an npm command see another example.

C:\Datting>**npm install latest-version**
npm ERR! code EPERM
npm ERR! syscall mkdir
npm ERR! path C:\
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, mkdir 'C:\'
npm ERR!  [Error: EPERM: operation not permitted, mkdir 'C:\'] {
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: 'C:\\'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\amir\AppData\Local\npm-cache\_logs\2023-02-24T05_39_48_409Z-debug-0.log

C:\Datting>

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by fritzy** [comment]
Most likely, you have a `package.json` in C:\, which is causing `npm` to assume that your current directory is a workspace rather than a project. Generally, you'll want to have your project in your user directory rather than C:\.

**Comment by surfmuggle** [comment]
With `npm -v  10.7.0` and `node -v v20.11.1` i did have a `package.json` under `C:`. I renamed both files to have a prefix `wrong_` like this

```bash
C:\>dir *package*
 Directory C:\

09.02.2023  10:57             1.372 wrong_package-lock.json
09.02.2023  10:57               328 wrong_package.json           
```

But trying `npm install jasmine` as admin under Windows 10 still does not work:

```
C:\dev\jasmine>npm install jasmine
npm error code EPERM
npm error syscall mkdir
npm error path C:\
npm error errno -4048
npm error [Error: EPERM: operation not permitted, mkdir 'C:\'] {
npm error   errno: -4048,
npm error   code: 'EPERM',
npm error   syscall: 'mkdir',
npm error   path: 'C:\\'
npm error }
npm error
npm error The operation was rejected by your operating system.
npm error It's possible that the file was already in use (by a text editor or antivirus),
npm error or that you lack permissions to access it.
npm error
npm error If you believe this might be a permissions issue, please double-check the
npm error permissions of the file and its containing directories, or try running
npm error the command again as root/Administrator.

npm error A complete log of this run can be found 
in: %userprofile%\AppData\Local\npm-cache\_logs\2024-05-05T08_56_18_014Z-debug-0.log
```

[This stackoverflow question](https://stackoverflow.com/q/58078937/819887) has the same error and some possible fixes like
 - `npm cache clean --force`
 - or `npm uninstall npm -g`
 - or `npm install npm -g`
 - or `npm set prefix "%USERPROFILE%\\AppData\\Roaming\\npm"`

I tried all and none of them solved the issue. 

Does anyone have additional ideas?

**Comment by GrimReaper6651** [comment]
If the project is new and you do not have the "package.json" file, npm goes through the folders until it finds it, that is why it reaches c:// without finding it (or it found it there), what you should do is create a file " package.json" inside your folder or run npm init

**Comment by surfmuggle** [comment]
@GrimReaper6651 Thanks for that hint. It seems i am one step further. 

I created a `package.json` file at `C:\dev\jasmine>` using [npm init](https://docs.npmjs.com/creating-a-package-json-file) the result looks like this

```json
{
  "name": "testjasmine", "version": "0.0.1",
  "description": "Get started using jasmine - a hello world",
  "main": "index.js",
  "scripts": { "test": "test" },
  "keywords": [ "jasmine", "hello-world" ],
  "author": "me", "license": "ISC",
  "dependencies": { "jasmine": "^5.1.0" }
}
```

After that running `npm install jasmine` worked without a problem: `added 43 packages, and audited 44 packages in 5s`.
