### ISSUE TITLE
npm ERR! Exit handler never called!

### ISSUE THREAD

**Issue by Dutiful783** [npm/cli#6196]
I'm trying to install firebase dependency to my react app and this is the error
message I got. 

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

**Comment by lukekarrys** [comment]
**Closing:** please use our [issue template](https://github.com/npm/cli/issues/new/choose) to open a new issue fully describing the behavior you are seeing.
