### ISSUE TITLE
[BUG] npm install from tarball recursively looks for package.json and uses it

### ISSUE THREAD

**Issue by cvakiitho** [npm/cli#6197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

when using npm install to install physical `.tar.gz` packed packges, npm checks root directories for `package.json`, and also installs packages from that file.

Happens only since v8.

### Expected Behavior

I would expect npm install to not do that.

### Steps To Reproduce

1. Create package.json with non existing package name in it
2. Create a folder 
3. Download any package packed to .tar.gz, for example here, into that folder: 
https://github.com/jonschlinkert/is-number/releases/tag/7.0.0 
4. run `npm i <tarname>

I prepared following gh action repo to showcase the error, you can see it works for v6, fails for v8+:
https://github.com/cvakiitho/npm-i-tar/actions/runs/4264335835/jobs/7422275938 

https://github.com/cvakiitho/npm-i-tar

### Environment

- npm: v8+
- Node.js: 16+
- OS Name: tested on linux and macos
- System Model Name: MBP/azure devops
- npm config:
```ini
doesn't matter imo
```

**Comment by fritzy** [comment]
`npm` is doing workspace detection, looking for the root of the project. If your parent folders have `package.json` in them, it'll assume that this is a workspace.

You can work around this by manually setting the `--prefix`
