### ISSUE TITLE
[SUGGESTION] Suggestion for `npm init`

### ISSUE THREAD

**Issue by ghost** [npm/cli#6200]
When running `npm init`, make the CLI detect the `LICENSE` file and autofill the `license` field in `package.json`. For example, I'm using MIT License and when running `npm init`, I would expect the CLI suggest `MIT` instead of the default `ISC`.

**Comment by wraithgar** [comment]
This is not something currently on our roadmap to implement.

**Comment by zkk123123** [comment]
您好，您的邮件我已收到，谢谢
——张可可
