### ISSUE TITLE
[SUGGESTION] Replace deprecated `set-output` command with environment file

### ISSUE THREAD

**Issue by jongwooo** [npm/cli#6201]
## Description

In `.github/workflows/release.yml`, `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

**Comment by lukekarrys** [comment]
This has been completed in #6229. Thanks for the report!
