### ISSUE TITLE
[BUG] when npm publish, relative url of local files in README are not transformed to absolute url of GitLab repository

### ISSUE THREAD

**Issue by ewmb7701** [npm/cli#6206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When using `npm publish` with a package.json with a repository field of a GitLab url, relative links in README are not transformed to absolute url. This is the case when https, ssh, and shortcut syntax, 

### Expected Behavior

I expect relative urls of local files in the README to be transformed to absolute url of GitLab repositories (for all syntaxes).

### Steps To Reproduce

1. create an npm package with a package.json repository field set to a GitLab url
2. create a README.md with an img HTML tag with a src url as a local file  
3. publish the package to npm 

### Environment

- npm: 8.19.2
- Node.js: 19.4.0
- OS Name: Manjaro Linux 22.0.1
- System Model Name: N/A (custom)
- npm config:
```ini
; "user" config from /home/walter/.npmrc

; node bin location = /usr/bin/node
; node version = v19.4.0
; npm local prefix = /run/media/walter/Development/vveisard.debug
; npm version = 8.19.2
; cwd = /run/media/walter/Development/vveisard.debug
; HOME = /home/walter
; Run `npm config ls -l` to show all defaults.
```

**Comment by ewmb7701** [comment]
I see this discussion https://github.com/npm/feedback/discussions/210 and it's implying transforming urls is part of the website and not the cli, and that the README will be parsed eventually?

**Comment by wraithgar** [comment]
readme rendering is done by the website and not the cli itself.  If a place where the readme is being rendered isn't generating correct links that should be brought up through the support channel of the site itself.
