### ISSUE TITLE
npm ERR! typeerror Error: Missing required argument

### ISSUE THREAD

**Issue by ashijay** [npm/cli#621]
Error in installing with npm install. It was working till last week and with no change from today it started to fail.

### Steps to Reproduce
13:07:35  npm ERR! Linux 3.10.0-1062.9.1.el7.x86_64
13:07:35  npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
13:07:35  npm ERR! node v6.7.0
13:07:35  npm ERR! npm  v3.10.3
13:07:35  npm ERR! code EMISSINGARG
13:07:35  
13:07:35  npm ERR! typeerror Error: Missing required argument #1
13:07:35  npm ERR! typeerror     at andLogAndFinish (/usr/lib/node_modules/npm/lib/fetch-package-metadata.js:31:3)
13:07:35  npm ERR! typeerror     at fetchPackageMetadata (/usr/lib/node_modules/npm/lib/fetch-package-metadata.js:51:22)
13:07:35  npm ERR! typeerror     at resolveWithNewModule (/usr/lib/node_modules/npm/lib/install/deps.js:515:12)
13:07:35  npm ERR! typeerror     at /usr/lib/node_modules/npm/lib/install/deps.js:516:7
13:07:35  npm ERR! typeerror     at /usr/lib/node_modules/npm/node_modules/iferr/index.js:13:50
13:07:35  npm ERR! typeerror     at /usr/lib/node_modules/npm/lib/fetch-package-metadata.js:37:12
13:07:35  npm ERR! typeerror     at addRequestedAndFinish (/usr/lib/node_modules/npm/lib/fetch-package-metadata.js:67:5)
13:07:35  npm ERR! typeerror     at returnAndAddMetadata (/usr/lib/node_modules/npm/lib/fetch-package-metadata.js:121:7)
13:07:35  npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/lib/node_modules/npm/lib/fetch-package-metadata.js:138:20)
13:07:35  npm ERR! typeerror     at /usr/lib/node_modules/npm/node_modules/iferr/index.js:13:50
13:07:35  npm ERR! typeerror This is an error with npm itself. Please report this error at:
13:07:35  npm ERR! typeerror     <http://github.com/npm/npm/issues>

I tried upgrading npm version which didn't worked. We also are not using type: module in package.json file as discussed in other issues.

**Comment by ljharb** [comment]
A stack trace from npm 6 (not 3) would probably help.

**Comment by ashijay** [comment]
So I am using a docker image file currently where I am not able to update npm version. I am trying a new docker itself.

Though I wanted to check what could have happened on a weekend that may result in this error. Nothing changed on the code or dependencies side.

I will keep you posted on the new docker image testing

**Comment by ashijay** [comment]
New docker image from npm6 worked fine. Still old working npm3 was working fine till now and suddenly stopped working is still a question.

Since using a different docker image resolved issue for me, will close the case
