### ISSUE TITLE
[BUG] npx 'canceled' error reason lacks clarity

### ISSUE THREAD

**Issue by lancegliser** [npm/cli#6215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Using npm version 9.5.0 running the command:

```bash
npx --no-install esbuild --bundle "~/typescript-graphql-service/service/src/lambda.ts" --target=node18 --platform=node --outfile="~/typescript-graphql-service/AWS/cdk.out/bundling-temp-d2395ea5f5b16624b9255daf70671b29ee231644c99ea4f7718828f55c1a0f13/index.js" --external="@aws-sdk/*" --loader:.graphql=file
```

I get 

```bash
npm ERR! canceled

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lancegliser/.npm/_logs/2023-03-01T18_11_17_043Z-debug-0.log
```

### Expected Behavior

A more useful explanation of why it was cancelled. It was unclear what module was throwing an error or canceling at first.

```bash
npm ERR! npx canceled due to missing packages and no YES option: ["esbuild@0.17.10"]

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lancegliser/.npm/_logs/2023-03-01T18_11_17_043Z-debug-0.log
```

### Steps To Reproduce

1. In a general termal
2. Without `esbuild` in path
3. Run `npx --no-install esbuild --bundle`
4. See error...

### Environment

- npm: 9.5.1
- Node.js: 18.13.0
- OS Name: MacOS 12.6.3
- System Model Name: Mackbook Pro
- npm config: 
```ini
; "user" config from /Users/lancegliser/.npmrc

init-author-name = "Lance Gliser" 

; node bin location = /usr/local/bin/node
; node version = v18.13.0
; npm local prefix = /Users/lancegliser
; npm version = 9.5.1
; cwd = /Users/lancegliser
; HOME = /Users/lancegliser
; Run `npm config ls -l` to show all defaults.```

**Comment by ShubhamPatilsd** [comment]
I would like to reserve this issue for our students over at [CodeDay Labs](https://labs.codeday.org) during our summer session.

A bit about CodeDay Labs:
> CodeDay Labs provides “micro-internships” for college students. This means working on real issues on real-world projects. The best part about this is that we’re helping the open source community at the same time by providing opportunities for these students to work on *******open-source******* projects.

**Comment by rahulio96** [comment]
Hello, I'm an intern at CodeDay Labs and am working on this issue alongside my teammate, Aaron.
