### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by Sapnajha19** [npm/cli#6223]
I was trying to clone an open-source project in my local system. I had node version 18 pre-installed in my system but that project was to be set up in node version 14, so I updated it accordingly. After doing all the prerequisites when I did the npm install,  I got this error. So then I tried to resolve this by asking the community members. They suggest deleting node modules and package-lock.json files after that,npm cache clean --force, and then npm install. I did exactly the same but still got the same error.
![Welcome - Webiu - Visual Studio Code 28-02-2023 22_19_12](https://user-images.githubusercontent.com/99778524/222767003-231beb52-44c9-478b-9d99-03281ff6d4f4.png)

**Comment by lukekarrys** [comment]
**Closing:** please use our [issue template](https://github.com/npm/cli/issues/new/choose) to open a new issue fully describing the behavior you are seeing.
