### ISSUE TITLE
[BUG] <delete npm account. but cannot re-register>

### ISSUE THREAD

**Issue by 1739616529** [npm/cli#6233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I deleted my npm account. re-create   

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 9.4.0
- Node.js: v19.6.0
- OS Name: Windows 10 企业版 LTSC 21H2
- System Model Name: 19044.2604
- npm config: 
```ini
; "global" config from D:\.dev\.nodejs\npm\prefix\etc\npmrc

; registry = "https://registry.npmjs.org/" ; overridden by user

; "user" config from C:\Users\ail\.npmrc

//registry.npmjs.org/:_authToken = (protected)
cache = "D:\\.dev\\.nodejs\\npm\\cache"
prefix = "D:\\.dev\\.nodejs\\npm\\prefix"
registry = "https://registry.npmmirror.com/"

; node bin location = D:\.dev\nodejs\node.exe
; node version = v19.6.0
; npm local prefix = C:\Users\ail\Desktop
; npm version = 9.4.0
; cwd = C:\Users\ail\Desktop
; HOME = C:\Users\ail
; Run `npm config ls -l` to show all defaults.
```

**Comment by 1739616529** [comment]
that username is already in use

**Comment by ljharb** [comment]
You'll need to contact npm support for that; this repo is for the cli.

**Comment by 1739616529** [comment]
excuse me;


1739616529
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "npm/cli"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月9日(星期四) 中午1:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [npm/cli] [BUG] <delete npm account. but cannot re-register&gt; (Issue #6233)





 
Closed #6233 as not planned.

**Comment by 1739616529** [comment]
excuse me; I don't know how to contact&nbsp;npm support


1739616529
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "npm/cli"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月9日(星期四) 中午1:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [npm/cli] [BUG] <delete npm account. but cannot re-register&gt; (Issue #6233)





 
Closed #6233 as not planned.

**Comment by azu** [comment]
contact form: https://www.npmjs.com/support

**Comment by 1739616529** [comment]
very&nbsp;thank&nbsp;you


1739616529
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "npm/cli"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月9日(星期四) 中午1:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [npm/cli] [BUG] <delete npm account. but cannot re-register&gt; (Issue #6233)





 
contact form: https://www.npmjs.com/support
