### ISSUE TITLE
[BUG] Expect `audit-registry` can taken effect

### ISSUE THREAD

**Issue by beiifeng** [npm/cli#6257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When `.npmrc` config was
```
registry=https://registry.npmmirror.com
```

It can not work when I use `npm audit --audit-registry=https://registry.npmjs.org` .

### Expected Behavior

`npm audit --audit-registry=https://registry.npmjs.org` will be find host correct as the code
```
        const res = await fetch('/-/npm/v1/security/advisories/bulk', {
          ...this.options,
          registry: this.options.auditRegistry || this.options.registry,
          method: 'POST',
          gzip: true,
          body,
        })
```

Can we add define of `audit-registry` as `registry` on `lib/utils/config/definitions.js` file, and update docs? ^_^

### Steps To Reproduce

1. Any one nodejs project, clean `node_modules` folder, and add `.npmrc` as
```
registry=https://registry.npmmirror.com
```
2. Run `npm install`
3. Run 'npm audit --audit-registry=https://registry.npmjs.org'

### Environment

- npm: 8.19.3
- Node.js: 16.19.0
- OS Name: Window 10
- System Model Name: ThindPad X13
- npm config:
```ini
; "builtin" config from C:\Users\Yifei\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\Yifei\\AppData\\Roaming\\npm"

; "user" config from C:\Users\Yifei\.npmrc

//registry.npmjs.org/:_authToken = (protected)
ELECTRON_MIRROR = "https://npm.taobao.org/mirrors/electron/"
registry = "https://registry.npmmirror.com/"

; node bin location = D:\Program Files\nodejs\node.exe
; node version = v16.19.0
; npm local prefix = D:\Rep\yifei\nestjs
; npm version = 8.19.4
; cwd = D:\Rep\yifei\nestjs
; HOME = C:\Users\Yifei
; Run `npm config ls -l` to show all defaults.
```

**Comment by fritzy** [comment]
The audit command doesn't currently pass through `audit-registry` `auditRegistry` to arborist.

**Comment by fritzy** [comment]
You can invoke this directly with the Arborist CLI, but we don't support this in the npm CLI simply because we only associate audit reports with the public registry. If it's another registry or proxy, we can't guarantee that the packages are related just because they have the same name and version.
