### ISSUE TITLE
Third party dependency breaks npm cli

### ISSUE THREAD

**Issue by yadirhb** [npm/cli#6258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

https://github.com/npm/metavuln-calculator/issues/80

### Expected Behavior

https://github.com/npm/metavuln-calculator/issues/80

### Steps To Reproduce

https://github.com/npm/metavuln-calculator/issues/80

### Environment

- npm: Several (7.10.0, 8.19.2 and more)
- Node.js: (16.0.0, 16.17.0, 16.19.1, 18.11.0)
- OS Name: Ubuntu 16, Mac OS
- System Model Name: Unix, Jenkins, CI
- npm config:
```ini
; "user" config from /Users/yadirbatista/.npmrc

progress = true 
strict-ssl = false 

; node bin location = /Users/yadirbatista/.nvm/versions/node/v18.11.0/bin/node
; node version = v18.11.0
; npm local prefix = /Users/yadirbatista/workspace/microservice-cx
; npm version = 8.19.2
; cwd = /Users/yadirbatista/workspace/microservice-cx
; HOME = /Users/yadirbatista
; Run `npm config ls -l` to show all defaults.
```

**Comment by alexanderkirsanov** [comment]
We're facing similar issue, while doing `npm i`

**Comment by yadirhb** [comment]
Any news on this? This is still ongoing and a solution has been provided...

**Comment by wraithgar** [comment]
This is just a duplicate issue for https://github.com/npm/metavuln-calculator/issues/80

**Comment by rainabba** [comment]
A fix has been merged, but not yet released: https://github.com/npm/metavuln-calculator/pull/85
