### ISSUE TITLE
Tracking issue for SLSA v1.0 provenance

### ISSUE THREAD

**Issue by kommendorkapten** [npm/cli#6268]
Main issue in SLSA org: https://github.com/slsa-framework/slsa/issues/574

The CLI can generate SLSA provenance v0.2 [today](https://github.com/npm/cli/blob/latest/workspaces/libnpmpublish/lib/provenance.js#L5), this ticket is to track tooling that supports SLSA provenance generation, and get better understanding of future support for v1.0 format.

cc: @steiza @feelepxyz

**Comment by wraithgar** [comment]
I don't think this repo is where we want to track this.  These issues are mostly for bug reports.

**Comment by wraithgar** [comment]
@mlieberman85 sorry I misclicked and removed your comment.  Usually work like this is tracked on https://github.com/npm/statusboard.
