### ISSUE TITLE
npm ci --omit=dev install dev dependency

### ISSUE THREAD

**Issue by maksimr** [npm/cli#6282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`npm ci --omit=dev` install dev dependency(ts-node) because it's [declared as optional `peerDependency`](https://github.com/typeorm/typeorm/blob/master/package.json#L210-L212) for prod dependency(typeorm)

### Expected Behavior

Doesn't install dependency marked as dev

### Steps To Reproduce

1. Setup project
```bash
mkdir /tmp/foo \
  && pushd /tmp/foo \
  && npm init -y \
  && npm install --save-dev ts-node \
  && npm install --save-prod typeorm
```
2. Install production dependencies
```
npm ci --omit=dev
```

3. Try to find ts-node in node_modules 
```
ls node_modules | grep ts-node
```

### Environment

- npm: 8.19.2
- Node.js: v18.12.0
- OS Name: darwin21.0 (MacOS Monterey 12.6.2)
- System Model Name: Macbook Air
- npm config:
```ini
; node bin location = /Users/maksimrv/.nvm/versions/node/v18.12.0/bin/node
; node version = v18.12.0
; npm local prefix = /private/tmp/foo
; npm version = 8.19.2
; cwd = /private/tmp/foo
; HOME = /Users/maksimrv
; Run `npm config ls -l` to show all defaults.
```

**Comment by ljharb** [comment]
If it's an optional peer of a prod dep, then it's not a dev dep.

**Comment by maksimr** [comment]
> If it's an optional peer of a prod dep, then it's not a dev dep.

🤔 `ts-node` in the example above, a dev dependency. In `typeorm` it's an optional peer dependency. Why this is a prod dep? Even in package-lock.json it marked as `devOptional: true`

**Comment by ljharb** [comment]
> for prod dependency(typeorm)

if typeorm is a dev dep of yours, then certainly its optional peers should also be dev deps.

what does `npm explain ts-node` print out?

**Comment by maksimr** [comment]
> npm explain ts-node

```
npm explain ts-node
ts-node@10.9.1
node_modules/ts-node
  dev ts-node@"^10.9.1" from the root project
  peerOptional ts-node@"^10.7.0" from typeorm@0.3.12
  node_modules/typeorm
    typeorm@"^0.3.12" from the root project
```

**Comment by ljharb** [comment]
and is typeorm a prod dep of yours, or a dev dep? If prod, ts-node is a prod dep too.

**Comment by maksimr** [comment]
@ljharb in my case `typeorm` is a prod dependency, but `ts-node` is a dev dependency

```
{
  "name": "foo",
  "version": "1.0.0",
  "devDependencies": {
    "ts-node": "^10.9.1"
  },
  "dependencies": {
    "typeorm": "^0.3.12"
  }
}
```

**Comment by maksimr** [comment]
> and is typeorm a prod dep of yours, or a dev dep? If prod, ts-node is a prod dep too.

That is a counterintuitive (at least for me). If I remove `ts-node` from `devDependency` it would not be installed via `npm ci --omit=dev`.

**Comment by ljharb** [comment]
Right - but ts-node is a *prod* dep of typeorm, so it's irrelevant that it's a dev dep of yours, because it's a prod dep of typeorm.

**Comment by ljharb** [comment]
Given that behavior difference, I definitely see why it's unexpected - I'll let the npm team weigh in here on whether that's by design or a bug.

**Comment by wraithgar** [comment]
Why would this be unexpected?  `omit=dev` disregards the entries in `devDependencies` but that doesn't mean it would refuse to install something that also happened to be in there if a production dependency required it.

**Comment by wraithgar** [comment]
This is working as expected and I think was just a misunderstanding of what the flag does.

**Comment by maksimr** [comment]
> Why would this be unexpected? `omit=dev` disregards the entries in `devDependencies` but that doesn't mean it would refuse to install something that also happened to be in there if a production dependency required it.

Because production dependency doesn't require it. `typorm` is a production dependency and has **optional** peer dependency on `ts-node`

**Comment by wraithgar** [comment]
optional dependencies are always installed if they can be.  npm just won't error out if they can't.

**Comment by maksimr** [comment]
> optional dependencies are always installed if they

If I get documentation right, they would be installed if I declared them in my project. In my case, I declared `ts-node` as dev dependency. So in this case there are no workarounds to remove dev dependencies from production code just because they were declared as optional for some prod deps.

**Comment by wraithgar** [comment]
If you want to stop installing optional dependencies use `--omit=optional`  You can use both i.e. `--omit=dev --omit-optional`

```sh
~/D/n/s/optional $ rm -rf node_modules/;npm i --omit=dev --omit=optional

added 62 packages, and audited 63 packages in 12s

found 0 vulnerabilities
~/D/n/s/optional $ npm ls ts-node
optional@1.0.0 /Users/wraithgar/Development/npm/scratch/optional
└── (empty)

~/D/n/s/optional $ npm pkg get dependencies
{
  "typeorm": "^0.3.12"
}
~/D/n/s/optional $ npm pkg get devDependencies
{
  "ts-node": "^10.9.1"
}
```

**Comment by maksimr** [comment]
Nice! That is what I need. Thanks a lot! ❤️
