### ISSUE TITLE
[BUG] npm install --install-strategy=linked is very slow if package-lock.json deleted but node_modules exist

### ISSUE THREAD

**Issue by asdfjkalsdfla** [npm/cli#6288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

npm install --install-strategy=linked is very slow if package-lock.json deleted but node_modules exist. This can take minutes and minutes to run/complete.

### Expected Behavior

The performance is at least as good as a clean install.

### Steps To Reproduce

1. `npm install --install-strategy=linked`
2. `rm package-lock.json`
3. `npm install --install-strategy=linked `

Wait for a long, long while. This can be reproduced with https://github.com/asdfjkalsdfla/pnpm.github.io/tree/npm_linked/benchmarks/fixtures/medium-size-app

### Environment

- npm: npm 9.5.1
- Node.js: 19.8.1
- OS Name: Ubuntu

**Comment by kchindam-infy** [comment]
@asdfjkalsdfla 'very slow' performance is subjective and does not fall under the scope of issues we actively track. Performance improvements can vary greatly depending on individual use cases and are not a priority for this specific context. As such this ticket will be closed. Thank you
