### ISSUE TITLE
Hoisting dependencies with peerDependencies while ignoring them in npm@8

### ISSUE THREAD

**Issue by Priti-Khattar** [npm/cli#6295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I have prepared a repo at https://github.com/developer-73/ajv-peerdep-issue. 
Running `npm install --legacy-peer-deps` in this repository will give incorrect dependency tree structure.

This shows a problem with how ignoring peer dependencies (--legacy-peer-deps) during npm install (npm@8.19.4) hoists incorrect dependencies 

	 I am using following devDependencies ::
	
	"babel-loader": "9.1.2",
    "eslint": "8.36.0"
	
    - eslint@8.36.0 depends on avj@^6.12.4
    - babel-loader@^9.1.2 depends on schema-utils@^4.0.0 which further depends on :
	  ajv@^8.8.0 and ajv-keywords@^5.0.0, where ajv-keywords has a peer dependency on ajv@^8.8.0 
	
	While installing I am ignoring peer dependencies (--legacy-peer-deps), ajv-keywords@5.1.0 
	still gets hoisted on the root level of node_modules and is using incorrect version of ajv@6.12.6. 
	This gives following error on build: 
	
	Error: Cannot find module 'ajv/dist/compile/codegen'
	
	This is a problem because the hoisted ajv-keywords@^5.0.0 will not have its peer dependency on ajv@^8.8.0 met.
	
	Note: This works correctly on npm < 7 
	

### Expected Behavior

Incorrect dependencies should not be hoisted

### Steps To Reproduce
```

git clone https://github.com/developer-73/ajv-peerdep-issue.git

npm install --legacy-peer-deps

```
 	Verify node_modules, tree structure should be like:

	|__@eslint
        |__avj@6.12.6       <<<<<---- |
        |__ajv-keywords@5.1.0    >>---|  Incompatible with ajv@6.12.6
        |__schema-utils@4.0.0
               |___ajv@8.12.0

**Note:** This issue is only reproducible when __ignoring peer dependencies__ i.e. (npm install --legacy-peer-deps) and not with (npm install). With npm install it gives correct tree structure

	|__@eslint
	      |__avj@6.12.6
        |__ajv@8.12.0            <<<<<---- |
	|__ajv-keywords@5.1.0    >>---|  Compatible with ajv@8.12.0
	|__schema-utils@4.0.0

### Environment

- npm: 8.19.4
- Node.js: 18.15.0
- OS Name: Mac OS

**Comment by wraithgar** [comment]
`--legacy-peer-deps` is a mode that allows folks to (hopefully temporarily) install otherwise incompatible trees.  By its very nature it doesn't install 100% correct trees, it is a legacy mode to support old broken behavior.  The "ignoring" of peer dependencies talked about in the docs is not that they are omitted, but that compatibility and semver is ignored. The docs discourage using it, and if your tree works without it you should not use it.
