### ISSUE TITLE
Feature Request: `--esm` or similar flag for `npm init`

### ISSUE THREAD

**Issue by trevor-scheer** [npm/cli#6298]
Hello, I'd like to suggest a flag for `npm init` which creates a project using `"type": "module"`. `--esm`, `--module`, or similar. Would this change be welcome? Assuming it's trivial in the way I imagine I'd consider opening the PR for it. Thanks in advance!

**Comment by ljharb** [comment]
Duplicate of https://github.com/npm/feedback/discussions/480.
