### ISSUE TITLE
what is the solution

### ISSUE THREAD

**Issue by mertbehic** [npm/cli#630]
![123](https://user-images.githubusercontent.com/53021413/71420997-346aa200-2689-11ea-838e-81ae22bf54ea.JPG)
I would appreciate if you make a comeback here.

**Comment by DanielRuf** [comment]
Hi @mertbehic,

please try the following steps:
* `npm cache clean --force`
* `npm i -g npm`

Please also provide the exact steps that you have taken or provide the logfile. And please provide the result of `npm --versions`.

**Comment by mikemimik** [comment]
Duplicate issue; aggregating into https://github.com/npm/cli/issues/417.
