### ISSUE TITLE
[BUG] Parsing of flags with boolean & string values is incorrect.

### ISSUE THREAD

**Issue by ianlewis** [npm/cli#6313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

The `npm fund` command has a `--browser` flag which can be `null` (not provided), a boolean value, or a string.

However there are a number of things wrong with it.

1. `npm fund --browser=open` should attempt to use the "open" command to open a browser. However the argument resolves to the value `true` and the system default is used.
2. `npm fund --browser --help` should parse the `--help` flag but doesn't because it's treated as an argument to the `--browser` flag.

The end result is only boolean values can actually be input as all string values resolve to the boolean value `true`.

### Expected Behavior

1. `npm fund --browser=open` should attempt to use the appropriate method to open the browser.
2. `npm fund --browser --help` should parse any flags after the `--browser` flag as a flag rather than an argument to the `--browser` flag.

### Steps To Reproduce

1. Run `npm fund --browser=open` on a Linux system.
2. The system default `xdg-open` is used to open the browser.

### Environment

- npm: npm HEAD (60460ed942eb78d419913cc8622d84d611437f74)
- Node.js: v16.17.0
- OS Name: Debian Linux
- npm config: None
```ini
; "user" config from /usr/local/google/home/ianlewis/.npmrc

//registry.npmjs.org/:_authToken = (protected) 

; "project" config from /usr/local/google/home/ianlewis/opt/node-v16.17.0-linux-x64/bin/node_modules/npm/.npmrc

package-lock = true 

; node bin location = /usr/local/google/home/ianlewis/opt/node-v16.17.0-linux-x64/bin/node
; node version = v16.17.0
; npm local prefix = /usr/local/google/home/ianlewis/opt/node-v16.17.0-linux-x64/bin/node_modules/npm
; npm version = 8.15.0
; cwd = /usr/local/google/home/ianlewis/opt/node-v16.17.0-linux-x64/bin/node_modules/npm
; HOME = /usr/local/google/home/ianlewis
; Run `npm config ls -l` to show all defaults.
```

**Comment by wraithgar** [comment]
This has nothing to do w/ the `fund` command per se. It is an underlying bug w/ our opts parsing that does not work having an overloaded boolean or string flag.

**Comment by ianlewis** [comment]
> This has nothing to do w/ the `fund` command per se. It is an underlying bug w/ our opts parsing that does not work having an overloaded boolean or string flag.

Right. The reason I mentioned it is that this is how it might affect users currently and how to reproduce the issue without necessarily biasing towards any specific solution to the problem.

**Comment by bdehamer** [comment]
Instead of trying to get boolean-and-string flags working, I think we're gonna add support for sets of mutually exclusive flags instead and then have things like `--browser` and `--browser-path` as separate, mutually exclusive flags.

https://github.com/npm/statusboard/issues/677

**Comment by ianlewis** [comment]
Ok, Thanks that's much easier. I had a PR that proposed that very thing but was rejected.
https://github.com/npm/cli/pull/6300

**Comment by wraithgar** [comment]
@ianlewis yeah I had that in mind too when I was thinking about this. The thing that PR is missing is the mechanism to couple the two configs together so they're mutually exclusive by way of a simple attribute on the config definition.  You had it as an explicit check in one of the commands but this would need to be baked into the config definition.


You were ultimately right in that the overloading was wrong, and since `browser` never worked right we can fix it w/o a semver major.

**Comment by ianlewis** [comment]
> @ianlewis yeah I had that in mind too when I was thinking about this. The thing that PR is missing is the mechanism to couple the two configs together so they're mutually exclusive by way of a simple attribute on the config definition. You had it as an explicit check in one of the commands but this would need to be baked into the config definition.
> 
> You were ultimately right in that the overloading was wrong, and since `browser` never worked right we can fix it w/o a semver major.

SG, thanks so much for following up on this.
