### ISSUE TITLE
[BUG] `npm ci` lists `npm install` flags that don't work for `npm ci`

### ISSUE THREAD

**Issue by richardebeling** [npm/cli#6319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```bash
$ npm ci --global
npm ERR! code ECIGLOBAL
npm ERR! `npm ci` does not work for global packages
```

### Expected Behavior

[The documentation](https://docs.npmjs.com/cli/v9/commands/npm-ci#global) says that the global flag is allowed:
> Operates in "global" mode, so that packages are installed into the prefix folder instead of the current working directory. See [folders](https://docs.npmjs.com/cli/v9/configuring-npm/folders) for more on the differences in behavior.
> 
> * packages are installed into the `{prefix}/lib/node_modules` folder, instead of the current working directory.
> * bin files are linked to `{prefix}/bin`
> * man pages are linked to `{prefix}/share/man`

### Steps To Reproduce

1. execute `npm ci -g`.

### Environment

The code raising the error is here:
https://github.com/npm/cli/blob/1c3612cc2fe9974166b5aab92477b289a768c1e7/lib/commands/ci.js#L18-L22

and there are tests for this:
https://github.com/npm/cli/blob/1c3612cc2fe9974166b5aab92477b289a768c1e7/test/lib/commands/ci.js#L184-L189

so I guess my environment doesn't matter here.

**Comment by ljharb** [comment]
`npm ci` only makes sense with a lockfile, and there isn't a global lockfile, so it shouldn't work.

**Comment by richardebeling** [comment]
From the documentation, I would have expected it to use the lockfile in the current working directory.

**Comment by ljharb** [comment]
That would be `npm ci`, then, since `-g` explicitly means "global, not the current working directory".
