### ISSUE TITLE
[BUG] [security] npm will install wrong version when using specific npm mirror and specifc package

### ISSUE THREAD

**Issue by loynoir** [npm/cli#6331]
### Background

In real world [issue](https://github.com/stacktracejs/error-stack-parser/issues/89), `error-stack-parser` published a version [3.0.0](https://www.npmjs.com/package/error-stack-parser/v/3.0.0) under default tag with wrong type which cause runtime error.

And `error-stack-parser` deprecate it.

So, the version under default tag should be `2.1.4` instead of `3.0.0`.

When using or not using npm mirror, for most cases, npm install error-stack-parser with version `2.1.4`.

But, when using specific npm mirror, npm install error-stack-parser with version `3.0.0`.

### Thought

Version is a big thing.

When maintainer deprecate a version, 
- it might be out of date, 
- it might be small bug, 
- it might be **high security vulnerabilities bug**.

So, I think 
- this is a **npm mirror** security related bug
- this is also a **npm cli design** security related bug

### Reproduce

- Any specific npm mirror
- Any npm package with newest version deprecated under default tag

<details>
<summary>Warning and code</summary>

**WARNGING**

This code will

- delete `~/.npm`

- modify npmrc, which may cause your comment lost

```bash
#!/bin/bash
set -euo pipefail

echo "node:$(node --version) npm:$(npm --version)" >> /tmp/reproduce.log

# https://github.com/Pana/nrm/blob/master/registries.json
registries=(
    https://registry.npmjs.org/
    https://registry.yarnpkg.com/
    https://mirrors.cloud.tencent.com/npm/
    https://r.cnpmjs.org/
    https://registry.npmmirror.com/
    # https://skimdb.npmjs.com/registry/

    # "verdaccio": "^5.23.2"
    http://localhost:4873

    # "verdaccio": "^6.0.0-6-next.67"
    http://localhost:4874
)

for registry in "${registries[@]}"; do
    rm -rf ~/.npm || :

    d="$(mktemp -d)"
    cd "${d:?}"
    npm init -y

    npm config set registry "${registry:?}"
    npm add error-stack-parser

    echo "${registry:?} $(grep error-stack-parser package.json)" | tee -a /tmp/reproduce.log
done

cat /tmp/reproduce.log
```

</details>

### Actual

Tencent npm mirror under all test cases, npm install `error-stack-parser` with **deprecated** version 3.0.0.

Tested matrix
```txt
node:v18.15.0 npm:8.19.2
node:v18.15.0 npm:9.6.4
node:v19.8.1 npm:8.19.2
node:v19.8.1 npm:9.6.4
```

<details>
<summary>Full output</summary>

```txt
node:v18.15.0 npm:8.19.2
https://registry.npmjs.org/     "error-stack-parser": "^2.1.4"
https://registry.yarnpkg.com/     "error-stack-parser": "^2.1.4"
https://mirrors.cloud.tencent.com/npm/     "error-stack-parser": "^3.0.0"
https://r.cnpmjs.org/     "error-stack-parser": "^2.1.4"
https://registry.npmmirror.com/     "error-stack-parser": "^2.1.4"
http://localhost:4873     "error-stack-parser": "^2.1.4"
http://localhost:4874     "error-stack-parser": "^2.1.4"
node:v18.15.0 npm:9.6.4
https://registry.npmjs.org/     "error-stack-parser": "^2.1.4"
https://registry.yarnpkg.com/     "error-stack-parser": "^2.1.4"
https://mirrors.cloud.tencent.com/npm/     "error-stack-parser": "^3.0.0"
https://r.cnpmjs.org/     "error-stack-parser": "^2.1.4"
https://registry.npmmirror.com/     "error-stack-parser": "^2.1.4"
http://localhost:4873     "error-stack-parser": "^2.1.4"
http://localhost:4874     "error-stack-parser": "^2.1.4"
node:v19.8.1 npm:8.19.2
https://registry.npmjs.org/     "error-stack-parser": "^2.1.4"
https://registry.yarnpkg.com/     "error-stack-parser": "^2.1.4"
https://mirrors.cloud.tencent.com/npm/     "error-stack-parser": "^3.0.0"
https://r.cnpmjs.org/     "error-stack-parser": "^2.1.4"
https://registry.npmmirror.com/     "error-stack-parser": "^2.1.4"
http://localhost:4873     "error-stack-parser": "^2.1.4"
http://localhost:4874     "error-stack-parser": "^2.1.4"
node:v19.8.1 npm:9.6.4
https://registry.npmjs.org/     "error-stack-parser": "^2.1.4"
https://registry.yarnpkg.com/     "error-stack-parser": "^2.1.4"
https://mirrors.cloud.tencent.com/npm/     "error-stack-parser": "^3.0.0"
https://r.cnpmjs.org/     "error-stack-parser": "^2.1.4"
https://registry.npmmirror.com/     "error-stack-parser": "^2.1.4"
http://localhost:4873     "error-stack-parser": "^2.1.4"
http://localhost:4874     "error-stack-parser": "^2.1.4"
```

</details>

### Expected

Tencent npm mirror under all test cases, npm install `error-stack-parser` with version 2.1.4.

If `error-stack-parser` had published version > 3.0.0, **including deprecated version**, **MUST** find another package to reproduce.

### Suggestion

1. `npm` should not depends on `registry mirror deprecation implement`, because a wrong version might means high security vulnerabilities, and hard to debug.

2. `npmrc` should have options for it.

3. By default, that options should not trust `registry mirror deprecation implement`.

4. Or `npmrc` just add option `metajson-and-assets-registry`

### Additional

- It will be nice if somebody publish a npm package with newest version deprecated under default tag. So, after `error-stack-parser` get a new version, this bug can still be reproduced.

- It will be nice if somebody can contact tencent npm mirror team members.

**Comment by wraithgar** [comment]
This looks like a problem with the mirrors themselves and issues should be opened up with their support teams.  As far as your suggestions go, they are not very feasible as npm has no way to know that they *are* mirrors. You have simply pointed npm at a registry and it has to use what you told it.
