### ISSUE TITLE
[BUG] Globally installing modules installs them in a $HOME folder in the local directory

### ISSUE THREAD

**Issue by alifeee** [npm/cli#6333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When installing a package globally, they are placed into a `$HOME` directory in the current directory of the terminal.

### Expected Behavior

Globally installed packages should be installed into node install location (i.e., `C:\Program Files\nodejs`)

### Steps To Reproduce

1. In Windows
2. Install Node + npm using <https://nodejs.org/en/download>
3. Run `cd c:/`
4. Run `npm install -g tldr` (or any other package)
5. Run `tldr tar` (error as it installed in the wrong place)
6. Run `npx tldr tar` (this is how it must be run)

Observe the directory `C:\`. There is a new `$HOME` directory
```bash
C:.
└───$HOME
    │   tldr
    │   tldr.cmd
    │   tldr.ps1
    │
    └───node_modules
        └───tldr
```

### Environment

- npm: 9.5.0
- Node.js: 18.5.0
- OS Name: Windows 10 v22H2
- System Model Name: PC
- npm config:
```ini
; "builtin" config from C:\Program Files\nodejs\node_modules\npm\npmrc

; prefix = "C:\\Users\\alifeee\\AppData\\Roaming\\npm" ; overridden by user

; "user" config from C:\Users\alifeee\.npmrc

prefix = "C:\\Users\\alifeee\\$HOME"

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v18.15.0
; npm local prefix = C:\Users\alifeee
; npm version = 9.5.0
; cwd = C:\Users\alifeee
; HOME = C:\Users\alifeee
; Run `npm config ls -l` to show all defaults.
```

**Comment by wraithgar** [comment]
```
; "user" config from C:\Users\alifeee\.npmrc

prefix = "C:\\Users\\alifeee\\$HOME"
```

It would appear that you explicitly told npm to put things in this directory in your `.npmrc` file.
