### ISSUE TITLE
[BUG] Residual global package installed at `C:\Users\xiongmao86\AppData\Roaming\npm\pnpm-global\5\node_modules`.

### ISSUE THREAD

**Issue by xiongmao86** [npm/cli#6336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I have a residual package `vite` installed at `C:\Users\xiongmao86\AppData\Roaming\npm\pnpm-global\5\node_modules`. 

When I run `vite` in powershell, I ran this `vite` package installed at the above location. And `npm list -g` don't show `vite`, and I can't `npm uninstall -g vite` as well, how do I remove this package?

### Expected Behavior

There should be a way to remove this residual global `vite` package.

### Steps To Reproduce

I don't know why this happen, and how it could be reproduced, it might related to my historical operations that I have no idea what operation have lead to this situation.

### Environment

- npm: 9.6.4
- Node.js: 6.15.0
- OS Name: windows 11
- System Model Name: Dell G15
- npm config:
```ini
; "builtin" config from C:\Users\xiongmao86\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\xiongmao86\\AppData\\Roaming\\npm"

; "user" config from C:\Users\xiongmao86\.npmrc

registry = "https://registry.yarnpkg.com"

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v16.15.0
; npm local prefix = C:\Users\xiongmao86
; npm version = 9.6.4
; cwd = C:\Users\xiongmao86
; HOME = C:\Users\xiongmao86
; Run `npm config ls -l` to show all defaults.
```

**Comment by ljharb** [comment]
It’s inside a pnpm folder, so it seems like you may have used pnpm at some point - you’d need to use that (or file an issue with them)

**Comment by xiongmao86** [comment]
Thanks, @ljharb. I'll ask on pnpm project.
