### ISSUE TITLE
[BUG] npm version [major/minor/patch] -m "commit message" does not commit or tag in subfolder.

### ISSUE THREAD

**Issue by clickonben** [npm/cli#6337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

If your NPM app is in a folder at any depth other than the root of your git repo, e.g. if you have a directory structure like below: 

```
my-repo/
    ├─ my-npm-app/ 
    └─ .git
```
When you run `npm version [patch | minor | major | whatever] -m "commit message"` in the root of your npm app, it does not commit the changes to git or create a tag. This happens irrespective of the value of npm config setting `git-tag-version`. 

### Expected Behavior

When you run `npm version [patch | minor | major | whatever] -m "commit message"` in the same directory that contains your `package.json` and `package-lock.json`, if the git config value of git-tag-version is set to true, it should commit `package.json` and `package-lock.json` with the commit message specified and create a tag with the version number. It should do this irrespective of where in the folder structure of the repository your npm app folder is.

### Steps To Reproduce

First, ensure that git-tag-version is set to true:

```
npm config set git-tag-version true
npm config get git-tag-version 
```

now create a repo with an npm app in a subfolder.

```
mkdir my-repo
cd my-repo
mkdir my-node-app
git init
cd my-node-app
npm init  (accept defaults)
git add .
git commit -m "initial commit"
npm version patch -m "Bump version to %s"
git status
```

You will get the erroneous behaviour and It will say:

```
On branch main
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   package.json

no changes added to commit (use "git add" and/or "git commit -a") 
```
git log will show one commit and no tags.

However, if you do the following:

```
mkdir my-repo
cd my-repo
git init
npm init  
git add .
git commit -m "initial commit"
npm version patch -m "Bump version to %s"
git status
```

You will get the expected behaviour and it will output 

```
On branch main
nothing to commit, working tree clean
```

git log will show something like 

```
commit e6eef678effc3c7f510aa61c6b427278892c5cca (HEAD -> main, tag: v1.0.1)
Author: Fred Blogs <someone@example.com>
Date:   Sat Apr 8 15:07:17 2023 +0100

    Bump version to 1.0.1

commit c2de4169bb314b90316f78fb0c718af99eca7b6c
Author: Fred Blogs <someone@example.com>
Date:   Sat Apr 8 15:07:15 2023 +0100

    initial commit
```

### Environment

`npm -v`: npm: 9.6.4
`node -v`: Node.js: 18.15.0
OS Names: Windows 11, Ubuntu 22.04, Docker image - node:latest

- npm config:
```
; "builtin" config from C:\Users\Ben Robinson\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\Ben Robinson\\AppData\\Roaming\\npm"

; "user" config from C:\Users\Ben Robinson\.npmrc

@ben:registry = "https://build.click-on.co.uk/api/v4/packages/npm/"
//build.click-on.co.uk/:_authToken = (protected)
git-tag-version = true

; node bin location = C:\Program Files (x86)\nodejs\node.exe
; node version = v18.15.0
; npm local prefix = C:\Users\Ben Robinson\source\repos\my-repo
; npm version = 9.6.4
; cwd = C:\Users\Ben Robinson\source\repos\my-repo
; HOME = C:\Users\Ben Robinson
; Run `npm config ls -l` to show all defaults.
```

**Comment by wraithgar** [comment]
This is not a bug, this is by design. npm will not go outside the package directory when making decisions about a package, such as when to make a commit.
