### ISSUE TITLE
issue in existing app

### ISSUE THREAD

**Issue by avaneeshkshukla** [npm/cli#634]
I am using a link from 
https://github.com/ionicthemes/ionic-facebook-login
and use this theme in app building first I have clone it then we use ionic serve and got error
> ng.cmd run app:serve --host=localhost --port=8100
[ng] An unhandled exception occurred: Could not find module "@angular-devkit/build-angular" from "C:\\Users\\Avaneesh Shukla\\Desktop\\Avaneesh\\facebook\\ionic-facebook-login".
[ng] See "C:\Users\AVANEE~1\AppData\Local\Temp\ng-Dp5pqX\angular-errors.log" for further details.
[ERROR] ng has unexpectedly closed (exit code 127).
        The Ionic CLI will exit. Please check any output above for error details.
then use npm install and got error
C:\Users\Avaneesh Shukla\Desktop\Avaneesh\facebook\ionic-facebook-login>npm install
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Avaneesh Shukla\AppData\Roaming\npm-cache\_logs\2019-12-25T18_14_36_368Z-debug.log
this is happen after anguler new version came

**Comment by DanielRuf** [comment]
Did you already try to install `@angular-devkit/build-angular`?

**Comment by mikemimik** [comment]
Duplicate issue; aggregating into https://github.com/npm/cli/issues/417.
