### ISSUE TITLE
[BUG] README.md/LICENSE files etc are included recursively and cannot be excluded

### ISSUE THREAD

**Issue by XhmikosR** [npm/cli#6341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Up until some time ago, only the root README.md, LICENSE etc were included.

Now these files are included **recursively** and there doesn't seem to exist a way to exclude them.

I tried adding `"!lib/**/README.md"` in the `files` section in package.json but the issue persists.

### Expected Behavior

The user should be able to exclude any files from subfolders like before. 

### Steps To Reproduce

1. `git clone https://github.com/stylelint/stylelint.git && cd stylelint && npm ci`
2. default config
3. `npm pack --dry`
4. See number of files is `588` and includes all README.md files from subfolders.

### Environment

- npm: 9.6.4
- Node.js: 18.15.0
- OS Name: Windows/Ubuntu via WSL
- System Model Name: N/A
- npm config:
```ini
; "builtin" config from C:\Program Files\nodejs\node_modules\npm\npmrc

prefix = "C:\\Users\\xmr\\AppData\\Roaming\\npm"

; "user" config from C:\Users\xmr\.npmrc

update-notifier = false

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v18.15.0
; npm local prefix = C:\Users\xmr\Desktop
; npm version = 9.5.0
; cwd = C:\Users\xmr\Desktop
; HOME = C:\Users\xmr
; Run `npm config ls -l` to show all defaults.
```

If this change was intended, please at least allow people to exclude the non-ROOT files. Including hundreds of files increases the tarball size, time to extract, download time, disk health, etc.

It should be up to the package publishers to decide if they want to exclude these files, like it was up until some time ago. v8.19.4 that I tried has the previous behavior and doesn't include these files recursively. v9.0.0 and newer has the new behavior.

**Comment by XhmikosR** [comment]
Is there any news about this issue? I understand that it's not the highest priority, but it's a regression nonetheless.

**Comment by AaronHamilton965** [comment]
Hello, I'm an intern at CodeDay Labs, and my teammate, Rahul, and we have been working on this issue. Hoping to put out a pull request soon.

**Comment by XhmikosR** [comment]
This is supposed to be fixed in npm v10.
