### ISSUE TITLE
[BUG] <title>How to upload mac link files through `npm publish`

### ISSUE THREAD

**Issue by anjisZhou** [npm/cli#6342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Using `publish` will not upload link files

### Expected Behavior

Use `publish` to upload link files

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by ljharb** [comment]
Why would you want to? node supports mac, linux, and windows, and Mac shortcuts won't work on 2 of those 3 platforms.

**Comment by anjisZhou** [comment]
I am using node-addon to make native modules, but rely on some third-party frameworks, which contain shortcuts files, so I want to know whether it can support uploading such files, or how to manage the framework in native modules

**Comment by wraithgar** [comment]
[node-tar](https://github.com/isaacs/node-tar) Only supports symlinks and hard links.
