### ISSUE TITLE
[BUG] is there an alternative to --scripts-prepend-node-path in v9

### ISSUE THREAD

**Issue by etnav** [npm/cli#6343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

We updated to the lastest NPM version from v6 and are wondering if there is an alternative to `--scripts-prepend-node-path` since it was removed in v7.

**Comment by wraithgar** [comment]
There is no alternative for this setting.  Folks who want a consistent node executable to run will need to solve that using traditional `PATH` declarations or other operating-system-level approaches.
