### ISSUE TITLE
README.md file not showing on npmjs.com

### ISSUE THREAD

**Issue by AmeyKhoje** [npm/cli#6345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [ ] I am using the latest npm

### Current Behavior

README.md file is present in repository but not showing on package display page

### Expected Behavior

README.md content should show on page

### Steps To Reproduce

Goto: https://www.npmjs.com/package/react-base-utility

Also added homepage property to package.json

Package.json:
`
{
  "name": "react-base-utility",
  "version": "1.0.1",
  "description": "Utilities for building react applications more faster",
  "main": "dist/cjs/index.js",
  "module": "dist/esm/index.js",
  "type": "module",
  "homepage": "https://github.com/AmeyKhoje/react-base-utility#readme",
  "scripts": {
    "start": "webpack serve -- --env mode=development",
    "build": "webpack -- --env mode=production",
    "lint": "eslint --ext .js,.ts,.jsx,.tsx src",
    "format": "npm run lint --fix & npm prettier --write 'src/**/*.{js,jsx,ts,tsx}'",
    "rollup": "rollup -c",
    "tsbuild": "tsc"
  },
  "files": [
    "dist"
  ],
  "types": "dist/index.d.ts",
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@types/react-icons": "^3.0.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-icons": "^4.8.0",
    "sass": "^1.55.0",
    "style-object-to-css-string": "^1.0.1",
    "web-utility-helpers": "0.0.3-beta"
  },
  "devDependencies": {
    "@babel/core": "^7.19.3",
    "@babel/preset-env": "^7.19.4",
    "@babel/preset-react": "^7.18.6",
    "@babel/preset-typescript": "^7.18.6",
    "@rollup/plugin-alias": "^5.0.0",
    "@rollup/plugin-babel": "^6.0.3",
    "@rollup/plugin-commonjs": "^24.0.1",
    "@rollup/plugin-image": "^3.0.2",
    "@rollup/plugin-json": "^6.0.0",
    "@rollup/plugin-node-resolve": "^15.0.2",
    "@rollup/plugin-typescript": "8.3.3",
    "@types/react": "^18.0.21",
    "@types/react-dom": "^18.0.6",
    "@typescript-eslint/eslint-plugin": "^5.40.1",
    "babel-loader": "^8.2.5",
    "core-js": "^3.25.5",
    "css-loader": "^6.7.1",
    "eslint": "^8.25.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-config-react-app": "^7.0.1",
    "eslint-config-standard-with-typescript": "^23.0.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-n": "^15.3.0",
    "eslint-plugin-promise": "^6.1.0",
    "eslint-plugin-react": "^7.31.10",
    "file-loader": "^6.2.0",
    "html-webpack-plugin": "^5.5.0",
    "prettier": "^2.7.1",
    "regenerator-runtime": "^0.13.10",
    "rollup": "^3.20.2",
    "rollup-plugin-cleanup": "^3.2.1",
    "rollup-plugin-copy": "^3.4.0",
    "rollup-plugin-dts": "^5.3.0",
    "rollup-plugin-exclude-dependencies-from-bundle": "^1.1.23",
    "rollup-plugin-livereload": "^2.0.5",
    "rollup-plugin-multi-input": "^1.4.1",
    "rollup-plugin-node-builtins": "^2.1.2",
    "rollup-plugin-node-globals": "^1.4.0",
    "rollup-plugin-peer-deps-external": "^2.2.4",
    "rollup-plugin-postcss": "^4.0.2",
    "rollup-plugin-scss": "^4.0.0",
    "rollup-plugin-serve": "^2.0.2",
    "rollup-plugin-terser": "^7.0.2",
    "rollup-plugin-typescript2": "^0.34.1",
    "sass-loader": "^13.1.0",
    "style-loader": "^3.3.1",
    "terser-webpack-plugin": "^5.3.6",
    "typescript": "^4.8.4",
    "webpack": "^5.78.0",
    "webpack-cli": "^4.10.0",
    "webpack-dev-server": "^4.13.2"
  }
}

`

### Environment

- npm: 6.14.15
- Node.js: 14.18.0
- OS Name: Windows 10
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by ljharb** [comment]
I see a readme on the page?

**Comment by wraithgar** [comment]
The readme does appear on the page
