### ISSUE TITLE
[BUG] Readme not shown on package

### ISSUE THREAD

**Issue by alphonse92** [npm/cli#6346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

After running npm version $VERSION and the npm publish the package is uploaded, however it does not display the README.md

### Expected Behavior

Readme will show in the repo

### Steps To Reproduce

1. go to https://www.npmjs.com/package/simple-lambda-api-router
2. Go to code, open README.md you can see the same readme than the github repo specified there
3.  The package wont show the README.md even there is inside

### Environment

- npm:9.6.4
- Node.js: v16.15.0
- OS Name: Macos monterrey
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here

; "user" config from /Users/elmo/.npmrc

//registry.npmjs.org/:_authToken = (protected) 

; node bin location = /Users/elmo/.nvm/versions/node/v16.15.0/bin/node
; node version = v16.15.0
; npm local prefix = /Users/elmo/Documents/github/-mv-simple-lambda-api-router
; npm version = 9.6.4
; cwd = /Users/elmo/Documents/github/-mv-simple-lambda-api-router
; HOME = /Users/elmo
; Run `npm config ls -l` to show all defaults.

```

**Comment by alphonse92** [comment]
News, after many minutes I can see it. It's taking to much time. I'll keep it open. Feel free to close it but seems weird. It make your repo without readme for a while

**Comment by ljharb** [comment]
This isn't a cli issue so npm/feedback would be the place to post it, but also it's fine that it takes time.

**Comment by isumix** [comment]
I should be more obvious, if it is being validated or something... Please put a message saying so. People waisting their time trying to find out what is going on. Still waiting for my readme to show up.

**Comment by ljharb** [comment]
I see your readme just fine, so that implies to me it's replication lag - network congestion.

**Comment by isumix** [comment]
They probably have some sort of front-end caching, as a was able to see my published version immediately, but not the readme file. Now it is showing though.
