### ISSUE TITLE
[BUG] invalid config for proxy even when proxy is NULL

### ISSUE THREAD

**Issue by Kenya-West** [npm/cli#635]
# What / Why

> I confused commands that setup git and npm proxies.
I typed this:
```npm config --global set proxy http.proxy http://proxyhost:proxyport```
Since then, npm displays an error:
```npm WARN invalid config proxy="http.proxy"```
I tried `npm config delete proxy`, but it does not solve the problem as the message keeps displaying.
`npm config get proxy` returns NULL

```
> npm -v
> 6.13.4
```

![npm wrongly setup proxy](https://user-images.githubusercontent.com/12271104/71466767-f219a000-2803-11ea-8923-c93004c358aa.png)

## When

* Today

## Where

* npm on local machine

### Current Behavior

* n/a

### Steps to Reproduce

- `npm config --global set proxy http.proxy http://proxyhost:proxyport`
- Expect an error
- Try to `npm config delete proxy`
- Problem still persists and the message `npm WARN invalid config proxy="http.proxy"` appears

### Expected Behavior

* `npm config delete proxy` removes error

## Who

* @KenyaWest

## References

* n/a

**Comment by ljharb** [comment]
If you set it with --global, I’d expect you to need to delete it with --global. Does that work?

**Comment by Kenya-West** [comment]
Well, that actually solves the problem, thanks for help!
