### ISSUE TITLE
Question about staleness timeout

### ISSUE THREAD

**Issue by original001** [npm/cli#6355]
I'm experiencing unexpected behavior in my workspace:

1) I published a new version of my package, which is a peer dependency of another package.
1) I updated the versions in package.json and the lock file and pushed the changes.
1) I received an update in some other repository.
1) I ran npm install with the new version.
1) I received an error stating that the version was not found on the registry.
1) I waited for some time, maybe a few hours.
1) I tried to run npm install again and it finished successfully.

It seems like npm doesn't immediately look up updates from the registry after the last update from the server. Am I correct in my conclusion? If so, what is the time span that npm doesn't look up updates for? Should npm force an update when the required version is not found in the cache?

Here's some additional information about my environment:

npm 9.2
Node.js 16.13.1
Private registry behind Nexus
Monorepo with workspaces, where dependencies are set as peer or direct dependencies.

**Comment by wraithgar** [comment]
Please use the issue template when making new issues. This does not seem like a bug report and more of a general question.

**Comment by original001** [comment]
I haven't found any template for general question. That's why I used a blank template. Where is template for general questions?

**Comment by wraithgar** [comment]
https://github.com/npm/feedback
