### ISSUE TITLE
[BUG] npm audit fix loop / installs subdepedency version that does not match package-lock

### ISSUE THREAD

**Issue by wmurphyrd** [npm/cli#6356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

npm audit reports that an issue is fixable with `npm audit fix`. After running `npm audit fix`, the same audit message appears.
The audit issue is:

```
vm2  <=3.9.15
Severity: critical
vm2 vulnerable to sandbox escape - https://github.com/advisories/GHSA-7jxr-cg7f-gpgv
vm2 Sandbox Escape vulnerability - https://github.com/advisories/GHSA-xj72-wvfv-8985
fix available via `npm audit fix`
node_modules/firebase-tools/node_modules/vm2
```

After `npm audit fix`, our tree looks like this:

```
$ npm ls vm2

├─┬ cloudinary@1.28.1
│ └─┬ proxy-agent@5.0.0
│   └─┬ pac-proxy-agent@5.0.0
│     └─┬ pac-resolver@5.0.0
│       └─┬ degenerator@3.0.1
│         └── vm2@3.9.16
└─┬ firebase-tools@11.26.0
  └─┬ proxy-agent@5.0.0
    └─┬ pac-proxy-agent@5.0.0
      └─┬ pac-resolver@5.0.0
        └─┬ degenerator@3.0.1
          └── vm2@3.9.11
```

### Expected Behavior

install vm2@3.9.16 under firebase-tools

### Steps To Reproduce

Here is the package lock that produces this issue: [package-lock.json.txt](https://github.com/npm/cli/files/11222945/package-lock.json.txt)

I have also tried the following workarounds to attempt to install the updated `vm2` inside `firebase-tools`. None of them were successful.

**Overides**

`"overrides": { "vm2": "3.9.16" }`

```
├─┬ cloudinary@1.28.1
│ └─┬ proxy-agent@5.0.0
│   └─┬ pac-proxy-agent@5.0.0
│     └─┬ pac-resolver@5.0.0
│       └─┬ degenerator@3.0.1
│         └── vm2@3.9.16 overridden
└─┬ firebase-tools@11.26.0
  └─┬ proxy-agent@5.0.0
    └─┬ pac-proxy-agent@5.0.0
      └─┬ pac-resolver@5.0.0
        └─┬ degenerator@3.0.1
          └── vm2@3.9.11 overridden
```

**Top level install**

`npm install vm2@3.9.16 && npm dedupe`

```
├─┬ cloudinary@1.28.1
│ └─┬ proxy-agent@5.0.0
│   └─┬ pac-proxy-agent@5.0.0
│     └─┬ pac-resolver@5.0.1
│       └─┬ degenerator@3.0.3
│         └── vm2@3.9.16 deduped
├─┬ firebase-tools@11.26.0
│ └─┬ proxy-agent@5.0.0
│   └─┬ pac-proxy-agent@5.0.0
│     └─┬ pac-resolver@5.0.0
│       └─┬ degenerator@3.0.1
│         └── vm2@3.9.11
└── vm2@3.9.16
```

**Manual edit of package-lock**

Update references to vm2 (`version`, `resolved`, and `integrity`) within the package lock to match the 3.9.16 version installed under cloudinary and then ran `npm ci`

```
├─┬ cloudinary@1.28.1
│ └─┬ proxy-agent@5.0.0
│   └─┬ pac-proxy-agent@5.0.0
│     └─┬ pac-resolver@5.0.0
│       └─┬ degenerator@3.0.1
│         └── vm2@3.9.16
└─┬ firebase-tools@11.26.0
  └─┬ proxy-agent@5.0.0
    └─┬ pac-proxy-agent@5.0.0
      └─┬ pac-resolver@5.0.0
        └─┬ degenerator@3.0.1
          └── vm2@3.9.11
```

(this one blew my mind - how could it install 3.9.11 without any reference to it in the package lock?)

### Environment

- npm: 9.6.4 (and 9.5.0)
- Node.js: v18.15.0
- OS Name: Ubuntu WSL and Windows native
- System Model Name: multiple
- npm config: 
```ini
; "user" config from /home/will/.npmrc

//registry.npmjs.org/:_authToken = (protected) 

; node bin location = /home/[redacted]/node/v18.15.0/bin/node
; node version = v18.15.0
; npm local prefix = /home/[redacted]/functions
; npm version = 9.6.4
; cwd = /home/[redacted]/functions
; HOME = /home/[redacted]
```

**Comment by wraithgar** [comment]
`firebase-tools` ships with an `npm-shrinkwrap.json` file so its dependencies are unchangeable.  We have other issues tracking when `npm audit` says it can fix things when it can't.
