### ISSUE TITLE
[DOCS] CLI command list page is missing `npm create`

### ISSUE THREAD

**Issue by leonardoraele** [npm/cli#6359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Problem, not another kind of Docs Problem.

- [X] This is a CLI Docs Problem.

### Description of Problem

CLI command list page is missing `npm create`

### Affected URL

https://docs.npmjs.com/cli/v9/commands

**Comment by wraithgar** [comment]
This is an alias for `npm init`

```sh
$ npm create -h
Create a package.json file

Usage:
npm init <package-spec> (same as `npx <package-spec>`)
```
