### ISSUE TITLE
[DOCS] Fix mistakes

### ISSUE THREAD

**Issue by ghost** [npm/cli#6368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Problem, not another kind of Docs Problem.

- [X] This is a CLI Docs Problem.

### Description of Problem

I corrected some mistakes such as `it also possible` (instead of `it is also possible`), but the PR did not pass all the tests. Maybe someone else wants to make a clean PR with the corrections, see here: [comparison](https://github.com/npm/cli/compare/latest...ivan-pan:cli:patch-1#files_bucket).

**Comment by wraithgar** [comment]
A lot of these changes aren't mistakes but are stylistic choices. If folks fix typos and make PRs we will do what we can to help them land. We don't have a running "fix the docs" issue open though.
