### ISSUE TITLE
[BUG] npm registry server-side hooks delayed several days

### ISSUE THREAD

**Issue by gmaclennan** [npm/cli#6369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I add an npm server-side hook via:

```
npm hook add $PACKAGE_NAME $WEBHOOK_URL $SECRET
```

When an update to $PACKAGE_NAME is published, I receive an email about the new version being published, but the hook is not triggered. Calling `npm hook ls` shows the hook as active, but "never triggered":

```
┌──────────┬───────────────────────────┬─────────────────────────────────────────┐
│ id │ target │ endpoint │
├──────────┼───────────────────────────┼─────────────────────────────────────────┤
│ ognjczrz │ $PACKAGE_NAME │ $WEBHOOK_URL │
│ ├───────────────────────────┴─────────────────────────────────────────┤
│ │ never triggered │
└──────────┴─────────────────────────────────────────────────────────────────────┘
```

The webhook does trigger eventually, but after several days. The quickest I have observed is 3 days, and the longest is 18 days.

### Expected Behavior

I expect the registry webhooks to trigger immediately, at least within a few hours.

### Steps To Reproduce

1. In this environment...
See below
3. With this config...
4. Run '...'

```
npm hook add $PACKAGE_NAME $WEBHOOK_URL $SECRET
```

Then publish a new version of $PACKAGE_NAME

6. See error...

Hook does not trigger for several days.

### Environment

- npm: v8.19.2
- Node.js: 16.18.0
- OS Name: MacOS
- System Model Name: Macbook Pro
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by wraithgar** [comment]
For registry issues please use https://www.npmjs.com/support
