### ISSUE TITLE
npm ci ignores --no-optional flag

### ISSUE THREAD

**Issue by dmytro-gokun** [npm/cli#637]
It should obey that flag. I know that i can do "npm i --no-optional", but that defeats the whole purpose of having lock files.

**Comment by ManfredLange** [comment]
Whether ```npm ci --no-optional``` works appears to depend on one ore more additional factors. It appears to work in my environment which is:

- Windows 10
- Nodejs 12.13.1
- npm 6.13.4

**Comment by c-z-chen** [comment]
Why is this closed? What about linux users?
