### ISSUE TITLE
[BUG] the path resolution of npx is wrong when ancestor directory name include sign “&”

### ISSUE THREAD

**Issue by zihahahaha** [npm/cli#6376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

on windows，if ancestor directory name include sign “&”，the path resolution will wrong when npx

### Expected Behavior

it's easy to repair just replace `SET dp0=%~dp0` width `SET "dp0=%~dp0"` in the batch script that npm generated
 

### Environment

- npm: 9.3.1
- Node.js: 18.14.1
- OS Name: windows
```

**Comment by Voltra** [comment]
Same here:

* Node: 14.21.3
* NPM: 9.6.5
* OS: Windows 10 Pro (64 bits)

**Comment by milaninfy** [comment]
**Closing:** this looks to be similar if not a duplicate of an existing issue,https://github.com/npm/cli/issues/7761. If you believe your instance is unique, please provide further clarifying details.
