### ISSUE TITLE
[QUESTION] can some one point out how the deprecate api works

### ISSUE THREAD

**Issue by frank-dspeed** [npm/cli#638]
# What / Why
i was looking at the installer code and found no point for the deprecation msg so i think the registry it self does something with the package maybe wrapps it? i would be interrested in the details what it is doing so i can handle deprecated packages more well.

i simply want to know how i can manual fake a deprecated package i want to know the code part that shows the configured deprecation msg.

## Where

* n/a

## Who

* n/a

## References

* n/a

**Comment by frank-dspeed** [comment]
ok i got it already it adds a "deprecated": "gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5", fild thanks!

**Comment by ljharb** [comment]
Deprecation is a status in the registry; you can’t “fake” it unless you control the registry it’s being installed from or the client doing the installing.

**Comment by frank-dspeed** [comment]
@liharb i understand it and its not really true. When i add deprecated to a package,json i get the msg on install so i can fake it or lets say emulate it i found  the feature that does the stuff in the registry manfifest wich the registry returns 

its for a registry proxy not a registry  we wanted to be able to deprecate packages on that proxy, Thanks for your attention i got all information thats needed.

**Comment by ljharb** [comment]
Sure, if you control the registry via a proxy you can fake it as well. Whether it's a good idea to do this is a separate discussion.

**Comment by frank-dspeed** [comment]
@ljharb its a really good idea it enforces to code on edge in our team :) we deprecate in our organisation all old versions so if any one is depending on a old version he gets informed to upgrade it.

sure its a edge case but for that its usefull we could also simply enforce update and so on but i like the warnings and it helps to keep all sub depdencys always up to date in all projects.
