### ISSUE TITLE
what do the npm audit errors mean? ??

### ISSUE THREAD

**Issue by winservkc** [npm/cli#6387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Problem, not another kind of Docs Problem.

- [X] This is a CLI Docs Problem.

### Description of Problem

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

C:\Windows\System32>npm audit fix --force
npm WARN using --force Recommended protections disabled.
npm WARN audit Updating go to 3.0.1, which is a SemVer major change.
npm WARN audit No fix available for go-loader-gist@*
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated

added 225 packages, removed 76 packages, changed 3 packages, and audited 281 packages in 7s

5 packages are looking for funding
  run `npm fund` for details

# npm audit report

ejs  <3.1.7
Severity: critical
ejs template injection vulnerability - https://github.com/advisories/GHSA-phwq-j96m-2c2q
fix available via `npm audit fix`
node_modules/ejs
  go-plugin-templates  >=0.0.1
  Depends on vulnerable versions of ejs
  Depends on vulnerable versions of globby
  node_modules/go-plugin-templates

glob-parent  <5.1.2
Severity: high
glob-parent before 5.1.2 vulnerable to Regular Expression Denial of Service in enclosure regex - https://github.com/advisories/GHSA-ww39-953v-wcq6
fix available via `npm audit fix`
node_modules/glob-parent
  fast-glob  <=2.2.7
  Depends on vulnerable versions of glob-parent
  node_modules/fast-glob
    globby  8.0.0 - 9.2.0
    Depends on vulnerable versions of fast-glob
    node_modules/globby

minimist  1.0.0 - 1.2.5
Severity: critical
Prototype Pollution in minimist - https://github.com/advisories/GHSA-vh95-rmgr-6w4m
Prototype Pollution in minimist - https://github.com/advisories/GHSA-xvch-5gv4-984h
fix available via `npm audit fix --force`
Will install go@2.0.2, which is a breaking change
node_modules/minimist
  go-cli  >=1.0.0-rc.0
  Depends on vulnerable versions of go-loader-gist
  Depends on vulnerable versions of go-loader-git
  Depends on vulnerable versions of go-loader-github
  Depends on vulnerable versions of minimist
  node_modules/go/node_modules/go-cli
    go  >=3.0.0-rc.0
    Depends on vulnerable versions of go-cli
    Depends on vulnerable versions of go-plugin-cli
    Depends on vulnerable versions of go-plugin-templates
    node_modules/go
  go-loader-gist  *
  Depends on vulnerable versions of minimist
  node_modules/go-loader-gist
  go-loader-git  >=3.0.0
  Depends on vulnerable versions of minimist
  node_modules/go-loader-github/node_modules/go-loader-git
  node_modules/go/node_modules/go-loader-git
  go-loader-github  >=0.0.1
  Depends on vulnerable versions of go-loader-git
  Depends on vulnerable versions of minimist
  node_modules/go-loader-github
  go-plugin-cli  >=2.0.0
  Depends on vulnerable versions of minimist
  node_modules/go-plugin-cli

12 vulnerabilities (3 high, 9 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

### Potential Solution

if the npm is advising you to fix everything with npm audit fix --force --- then why do all of these errors just persist forever?  i've never had it not indicate all of that critical errors.  for example if i want to updatae minimist why cant it just update itself when im doing the update  & fix the issue?!?  how does anyone ever GET AHEAD Of these ? it's so stupid.  should i just ignore them?

**Comment by wraithgar** [comment]
https://github.com/npm/cli/issues/2798
