### ISSUE TITLE
[BUG] `cache add` subcommand interprets file path as github URL

### ISSUE THREAD

**Issue by thw0rted** [npm/cli#6398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`npm pack some-package` downloads a TGZ archive of the specified package.  `npm cache add some-package-x.y.z.tgz` adds this package to the local cache.  But `npm cache add somedir/some-package-x.y.z.tgz` tries to add a package from `ssh://git@github.com/somedir/some-package-x.y.z.tgz.git`.

### Expected Behavior

Providing a relative path to a local file should add that file to the cache.

### Steps To Reproduce

1. Run `npm pack qs`
2. Create a subdirectory `subdir` and move `qs-a.b.c.tgz` into it
3. Run `npm pack subdir/qs-a.b.c.tgz`

### Environment

- npm: 9.6.5
- Node.js: 18.16.0
- OS Name: Windows 11

**Comment by wraithgar** [comment]
The package spec requires you to prepent paths with `./` for this very reason `foo/bar` is a shorthand for a github url.
