### ISSUE TITLE
[BUG] npm isntall is also working as npm install

### ISSUE THREAD

**Issue by dzheng113** [npm/cli#6403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`npm isntall` has a typo in **isntall** which should prevent running `npm install` command but its working just like `npm install`
same goes with `npm instal`

### Expected Behavior

errors out when running `npm isntall`

### Steps To Reproduce

1. Have any package.json file ready
2. Run `npm isntall` or `npm instal`
3. Package is installed correctly under typo command

### Environment

- npm: 8.5.5
- Node.js: 16.15.0
- OS Name: Ubuntu 20.04
- System Model Name: Windows WSL V2
- npm config:
```ini
; "user" config from /home/xxx/.npmrc

unsafe-perm = true
user = "0"

; node bin location = /home/xxx/.nvm/versions/node/v16.15.0/bin/node
; cwd = /home/xxx/TEST/playground/
; HOME = /home/xxx
; Run `npm config ls -l` to show all defaults.
```

**Comment by ljharb** [comment]
This isn't a bug, it's an intentional alias. There's a lot of them.
