### ISSUE TITLE
[BUG] Using npm_config__auth environtment variable in v8 to authorize private repository

### ISSUE THREAD

**Issue by rittneje** [npm/cli#6406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Reopening #3985. The "solution" to go manually create an npmrc file is completely unacceptable.

### Expected Behavior

The npm_config__auth env var specifies the credentials to use for the _default_ registry, as specified by npm_config_registry env var. It is NOT for npm specifically.

**Comment by ljharb** [comment]
I'm confused; why is an env var starting with "npm_" not for npm specifically?

**Comment by rittneje** [comment]
https://docs.npmjs.com/cli/v9/using-npm/config#environment-variables

> Any environment variables that start with npm_config_ will be interpreted as a configuration parameter. 

They are configurations for npm the command line tool, which is distinct from npm the registry.

**Comment by ljharb** [comment]
sure, this is about the npm client, which talks to the registry. The config isn't for the registry - it's for the CLI, so it applies to *every* registry the CLI talks to.

**Comment by rittneje** [comment]
@ljharb I'm not sure what you are trying to say. Previously the `npm_config__auth` env var could be used to specify the credentials to use for interacting with the registry specified in the `npm_config_registry` env var. Then a breaking change was introduced such that `npm_config__auth` is only used for interacting with npmjs.org specifically. (That is, if `npm_config_registry` is configured to something other than npmjs.org, now it incorrectly sends unauthenticated requests to it instead of using `npm_config__auth` like it should.) I am asking for this change to be reverted.

**Comment by ljharb** [comment]
ah, i believe this was intentional for security reasons, and that the best practice is to use scope-based registry settings (and auth), but I'll let the npm team weigh in.

**Comment by wraithgar** [comment]
`_auth` will only ever be used to authenticate to the npm registry. This was a security concern.  Your best option is to configure your auth to specify the registry it should go to.  The linked issue has examples for how to do this.
