### ISSUE TITLE
media capture issue with cordova CLI 9

### ISSUE THREAD

**Issue by anoop18111982** [npm/cli#641]
Hi team, I am using media capture plugin in my ionic project. The plug in is working fine in local android build apk as well as emulator. But when I commit the code and build the same ionic cloud(web) build, the build is successful but the plug in doesn't work and is giving error plugin_not_installed. I suspect the issue could be with compatibility of media-capture  plugin with Cordova CLI 9. Is there any work around for this? I have already spend too much in analysing and finding solution for this. Raised a request in IONIC community forum also. But didnt get any response till now. Expecting a response from some expert here.Thanks in advance

**Comment by DanielRuf** [comment]
Hi @anoop18111982,

This is probably not an issue with the npm cli. Please provide steps to reproduce this.
