### ISSUE TITLE
[BUG] "npm install" differs from "semver.maxSatisfying()" when using "||" with pre-release versions

### ISSUE THREAD

**Issue by mikeharder** [npm/cli#6420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`npm install` differs from `semver.maxSatisfying()` when using `||` with pre-release versions:

```
 > semver.maxSatisfying(['0.43.0', '0.44.0-dev.1'], '>=0.43.0 || >=0.44.0-dev')
'0.44.0-dev.1'
```

```
$ npm install @typespec/compiler@">=0.43.0 || >=0.44.0-dev"

$ npm ls
└── @typespec/compiler@0.43.0
```

### Expected Behavior

I would expect `npm install @typespec/compiler@">=0.44.0-dev || >=0.43.0"` to install a version like `0.44.0-dev.15`, since this is higher than `0.43.0` according to `semver.maxSatisfying()`.

### Steps To Reproduce

```
npm install @typespec/compiler@">=0.44.0-dev || >=0.43.0"
```

### Environment

- npm: 9.6.5
- Node.js: 18.16.0
- OS Name: Ubuntu 22.04
- System Model Name:
- npm config:
```ini
; node bin location = /home/username/.nvm/versions/node/v18.16.0/bin/node
; node version = v18.16.0
; npm local prefix = /home/username/tmp/install-test
; npm version = 9.6.5
; cwd = /home/username/tmp/install-test
; HOME = /home/username
; Run `npm config ls -l` to show all defaults.
```

**Comment by wraithgar** [comment]
If the `latest` tag is in the range given npm will always pick that.

**Comment by abatishchev** [comment]
That's it, that's the discussion and the resolution?
