### ISSUE TITLE
[BUG] npm ERR! request to https://registry.npmjs.org/create-next-app failed, reason: Socket connection timeout

### ISSUE THREAD

**Issue by EAAARL** [npm/cli#6433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I run **npx create-next-app@latest --typescript --tailwind**
```
npm ERR! code ERR_SOCKET_CONNECTION_TIMEOUT
npm ERR! errno ERR_SOCKET_CONNECTION_TIMEOUT
npm ERR! request to https://registry.npmjs.org/create-next-app failed, reason: Socket connection timeout

npm ERR! A complete log of this run can be found in: C:\Users\Earl A. Villapaz\AppData\Local\npm-cache\_logs\2023-05-08T13_56_45_064Z-debug-0.log
``` 
I looked into different solutions set the timeouts, check my internet connection and seems it's good (600+mbps dl & 97 ups) but I am still having this issue. I also tried to restart my pc, reset my internet connection, clear cache.

### Expected Behavior

**It should create a new Next JS 13 packages**

### Steps To Reproduce

1. `npx create-next-app@latest --typescript --tailwind`

![image](https://user-images.githubusercontent.com/91045673/236846891-769c4b39-907c-4b89-98d7-b665834ca845.png)

### Environment

- npm: 9.6.4
- Node.js: v20.1.0
- OS Name: Windows 10 Pro x64
- System Model Name: PC Desktop
- npm config:
```ini
; "global" config from C:\Program Files\nodejs\etc\npmrc

; fetch-retry-mintimeout = 20000 ; overridden by user   

; "user" config from C:\Users\Earl A. Villapaz\.npmrc   

fetch-retry-maxtimeout = 120000
fetch-retry-mintimeout = 20000

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v20.1.0
; npm local prefix = D:\Workspace\Stack\...
; npm version = 9.6.4
; cwd = D:\Workspace\Stack\...
; HOME = C:\Users\Earl A. Villapaz
; Run `npm config ls -l` to show all defaults.
```

**Comment by abraraltaf** [comment]
I also get this error can you please tell me the solution?

**Comment by EAAARL** [comment]
> I also get this error can you please tell me the solution?

I don't think that this should also be your solution but I just turn off my WIFI for 3-5mins then run the code again and it works on me.

ps: I have a decent internet connection but just in case I turn of my WIFI
