### ISSUE TITLE
npm -v command throws access denied at random instances.

### ISSUE THREAD

**Issue by suryafrizzera** [npm/cli#6442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When running "npm -v" command, normally the command executes successfully and returns the version of NPM installed on my machine but 4 out of 10 times this command prints a failure "Access denied" in first line after executing then prints the version of NPM correctly, so to check what's happening in the failure cases, I enabled the log level verbose to view the detailed logs in the cmd itself, upon checking I found that when npm -v command is executed node application was called two times with two different arguments the first time it it is called with --prefix global in the argument list and the second time the argument "--version" was passed and the version got printed, my issue here is why does the access denied error gets printed randomly when the first node call with argument --prefix global gets executed but the same call gets executed successfully in another attempt in the same machine, can you elaborate what's happening internally when npm -v command is executed.

### Expected Behavior

npm -v command running successfully at all instances.

### Steps To Reproduce

This issue doesn't get reproduced in any other machines of mine and I guess this is an environmental issue.

### Environment

- npm: 9.5.1
- Node.js:
- OS Name: windows 10 
- System Model Name: 
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by wraithgar** [comment]
There's not much we can do w/ some way to reproduce this.  In windows npm runs itself twice. the `npm.cmd` runs npm to parse all the config and find what global prefix it should be using. It's the first one that appears to be failing so you should start there.
