### ISSUE TITLE
write EPROTO 14488:error:1408F10B:SSL

### ISSUE THREAD

**Issue by Narendhar666** [npm/cli#645]
# What / Why
npm WARN registry Unexpected warning for http://registry.npmjs.org/: Miscellaneous Warning EPROTO: request to http://registry.npmjs.org/react failed, reason: write EPROTO 14488:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\\ws\\deps\\openssl\\openssl\\ssl\\record\\ssl3_record.c:332:\n
npm WARN registry Using stale data from http://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! code ELOOP
npm ERR! syscall stat
npm ERR! path \\ctxnas2.app.syfbank.com\citrixdata2\
npm ERR! errno -62
npm ERR! ELOOP: too many symbolic links encountered, stat '\\ctxnas2.app.syfbank.com\citrixdata2\'

## When
npm install -g react

## Where
in windows 10

### Current Behavior

* n/a

### Steps to Reproduce

* n/a

### Expected Behavior

* n/a

## Who

* n/a

## References

* n/a

**Comment by DanielRuf** [comment]
It seems this is an issue with your outdated openssl version and your citrix setup. Not directly related to npm cli itself I guess.

**Comment by DanielRuf** [comment]
It seems you use the http endpoint. Please check your npmrc / registry settings.

`http://registry.npmjs.org/react`

What happens if you go to http://registry.npmjs.org/react in your browser?

**Comment by gautrohit** [comment]
Thanks, It's works
