### ISSUE TITLE
[BUG] `npx` downloads the same version of the same package multiple times if described differently

### ISSUE THREAD

**Issue by benblank** [npm/cli#6450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

*Note that I'm not actually **certain** this is unintended behavior; it could also simply be something I found surprising and couldn't find documentation for.*

When `npx` is used to run a package multiple times, with different version specifiers *that all resolve to the same version*, that version is downloaded even if it is already present locally.

In other words, running the following three commands in sequence result in three download prompts (and three cached copies), even though `latest` is the default tag and resolves (at time of writing) to 5.0.4:

``` sh
npx --package typescript -- tsc --version
npx --package typescript@latest -- tsc --version
npx --package typescript@5.0.4 -- tsc --version
```

### Expected Behavior

I expected `npx` to recognize that the resolved version was already present and use that.

### Steps To Reproduce

1. Ensure you are **not** currently in a directory which is part of a package. (In the example below, I used `~/.local/tmp`, which was empty.)
2. Delete or rename your npm cache directory, e.g. `mv ~/.npm ~/Documents/somewhere-safe/`.
3. Run `npx --package typescript -- tsc --version`.
4. Run `npx --package typescript@latest -- tsc --version`.
5. Run `npx --package typescript@5.0.4 -- tsc --version` (or whatever the "latest" tag resolves to when you're trying this).
6. Observe that there three download prompts, all for the same version, and that there are three cached copies of the "typescript" package, which are identical aside from the "name" in "node_modules/.package-lock.json" and "package-lock.json", which reflect the name of the containing directory.

<details><summary>A transcript of the above steps, on my laptop.</summary>

``` text
~/.local/tmp $ npx --package typescript -- tsc --version
Need to install the following packages:
  typescript@5.0.4
Ok to proceed? (y) 
Version 5.0.4

~/.local/tmp $ npx --package typescript@latest -- tsc --version
Need to install the following packages:
  typescript@5.0.4
Ok to proceed? (y) 
Version 5.0.4

~/.local/tmp $ npx --package typescript@5.0.4 -- tsc --version
Need to install the following packages:
  typescript@5.0.4
Ok to proceed? (y) 
Version 5.0.4

~/.local/tmp $ grep version ~/.npm/_npx/*/node_modules/typescript/package.json
/home/five35/.npm/_npx/11d9e06b573ee33f/node_modules/typescript/package.json:    "version": "5.0.4",
/home/five35/.npm/_npx/98f625b637dfc4f6/node_modules/typescript/package.json:    "version": "5.0.4",
/home/five35/.npm/_npx/9ca470fa61f45e06/node_modules/typescript/package.json:    "version": "5.0.4",

~/.local/tmp $ diff -uNr ~/.npm/_npx/{11d9e06b573ee33f,98f625b637dfc4f6}/
diff -uNr /home/five35/.npm/_npx/11d9e06b573ee33f/node_modules/.package-lock.json /home/five35/.npm/_npx/98f625b637dfc4f6/node_modules/.package-lock.json
--- /home/five35/.npm/_npx/11d9e06b573ee33f/node_modules/.package-lock.json	2023-05-14 09:30:17.485461377 -0700
+++ /home/five35/.npm/_npx/98f625b637dfc4f6/node_modules/.package-lock.json	2023-05-14 09:30:43.944755489 -0700
@@ -1,5 +1,5 @@
 {
-  "name": "11d9e06b573ee33f",
+  "name": "98f625b637dfc4f6",
   "lockfileVersion": 3,
   "requires": true,
   "packages": {
diff -uNr /home/five35/.npm/_npx/11d9e06b573ee33f/package-lock.json /home/five35/.npm/_npx/98f625b637dfc4f6/package-lock.json
--- /home/five35/.npm/_npx/11d9e06b573ee33f/package-lock.json	2023-05-14 09:30:17.481461481 -0700
+++ /home/five35/.npm/_npx/98f625b637dfc4f6/package-lock.json	2023-05-14 09:30:43.940755598 -0700
@@ -1,5 +1,5 @@
 {
-  "name": "11d9e06b573ee33f",
+  "name": "98f625b637dfc4f6",
   "lockfileVersion": 3,
   "requires": true,
   "packages": {
```

</details>

### Environment

- npm: 9.6.6
- Node.js: v18.16.0
- OS Name: Ubuntu 22.10
- System Model Name: Lenovo ThinkPad T450s
- npm config:
  ```ini
  ; "user" config from /home/five35/.npmrc

  init-author-email = "ben.blank@gmail.com" 
  init-author-name = "Ben \"535\" Blank" 
  init-author-url = "https://five35.com/" 
  init-license = "BSD-3-Clause" 
  init-version = "0.1.0" 
  save = true 
  sign-git-commit = true 
  sign-git-tag = true 

  ; node bin location = /home/five35/.config/nvm/versions/node/v18.16.0/bin/node
  ; node version = v18.16.0
  ; npm local prefix = /home/five35/.local/tmp
  ; npm version = 9.6.6
  ; cwd = /home/five35/.local/tmp
  ; HOME = /home/five35
  ; Run `npm config ls -l` to show all defaults.
  ```

**Comment by wraithgar** [comment]
This is how npx is designed to work.  `typescript` `typescript@latest` and `typescript@5.0.4` are all distinct package specs that can resolve to different versions.  npx caches based on the spec it is given, not the results of parsing that spec.

**Comment by benblank** [comment]
I wondered whether that might be the case, but couldn't find the behavior specified in the documentation anywhere. It would be nice to have a note to that effect added to the pages for `npx` and `npm exec`, as the behavior differs (or at least *appears* to differ) from the behavior of, say, `npm install`, where installing all three specs would result in only a single copy of version 5.0.4 being installed.
