### ISSUE TITLE
Exit handler never called!

### ISSUE THREAD

**Issue by aminsoraya** [npm/cli#6471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When i attempt to install  a package in my existing project . cli thrown error:

npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in: C:\Users\amin\AppData\Local\npm-cache\_logs\2023-05-18T15_40_15_479Z-debug-0.log

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by ljharb** [comment]
Please fill out the issue template.
