### ISSUE TITLE
[DOCS] `npm help dedupe` mentions an option for `npm install` that is not documented in `npm help install`

### ISSUE THREAD

**Issue by m4rch3n1ng** [npm/cli#6473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Problem, not another kind of Docs Problem.

- [X] This is a CLI Docs Problem.

### Description of Problem

running `npm help dedupe` shows you the option `--prefer-dedupe` in an example for `npm install` ([ref `npm install --prefer-dedupe`](https://github.com/npm/cli/blob/37cc797341100cd0a8371e80b25b938f166c9d71/docs/lib/content/commands/npm-dedupe.md?plain=1#L60-L61)), which is not documented in either `npm help install` or `npm install --help`.  
running the command also seems to not do anything differently than without the option, and `"prefer-dedupe"` is also not defined in [`lib/utils/config/definitions.js`](https://github.com/npm/cli/blob/37cc797341100cd0a8371e80b25b938f166c9d71/lib/utils/config/definitions.js), nor does it seem to be read from the command-line args at any point in the code, but i am not too confident about this since i don't really know the structure of this code-base.

**Comment by wraithgar** [comment]
Looks like this was a flag that got added to arborist, and back before the config was cleaned up to not add random values to the flatOptions was working by accident.

This is a valid flag that arborist understands so a new definition in the cli is in order, with the default flattener.
