### ISSUE TITLE
[BUG] <title>npm i -D nodemon

### ISSUE THREAD

**Issue by tychicus04** [npm/cli#6493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

node.js

### Expected Behavior

Tychicusnguyen@MacBook-Pro-ca-Tychicus ~ % npm i -D nodemon
npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in: /Users/Tychicusnguyen/.npm/_logs/2023-05-23T05_06_36_301Z-debug-0.log

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by ljharb** [comment]
Please fill out the issue template.
