### ISSUE TITLE
[BUG] <title>npm ERR! EXIT Handler never called 

### ISSUE THREAD

**Issue by Saba807** [npm/cli#6495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

the log of the error is 
C:\Users\marhaba\AppData\Local\npm-cache\_logs\2023-05-23T14_48_18_792Z-debug-0.log

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by johnthagen** [comment]
Related to

- #6409

**Comment by ShogunPanda** [comment]
This is a duplicate of #6409.

**Comment by milaninfy** [comment]
**Closing:** this error can arise for a number of reasons; Please read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) & refile an issue with as much information as possible if you're able to **consistently reproduce** this error.
