### ISSUE TITLE
[DOCS] npm-ci

### ISSUE THREAD

**Issue by hirehamir** [npm/cli#6499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Enhancement, not another kind of Docs Enhancement.

- [X] This is a CLI Docs Enhancement.

### Description of Problem

It might help users remember what `npm ci` does if the docs mentioned what the `ci` in `npm ci` stands for.

### Potential Solution

I thought the `ci` in `npm ci` stands for **C**ontinuous **I**ntegration, but according to https://stackoverflow.com/questions/52499617/what-is-the-difference-between-npm-install-and-npm-ci/53325242#53325242, it stands for **C**lean **I**nstall.

> npm ci (also known as Clean Install) is meant to be used in automated environments — such as test platforms, continuous integration, and deployment — or, any situation where you want to make sure you're doing a clean install of your dependencies.

### Docs URL

https://docs.npmjs.com/cli/v6/commands/npm-ci

**Comment by wraithgar** [comment]
The [docs](https://docs.npmjs.com/cli/v9/commands/npm-ci) already start with "clean install a project" and the description already says "any situation where you want to make sure you're doing a clean install of your dependencies"

The cli output also states it

```sh
$ npm ci -h
Clean install a project
...
```

I don't think we need it a third time on the same doc page.
