### ISSUE TITLE
Exit handler never called! error

### ISSUE THREAD

**Issue by AbdelkaderYahiaouii** [npm/cli#6512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in: C:\Users\pc\AppData\Local\npm-cache\_logs\2023-05-30T00_05_13_543Z-debug-0.log

### Expected Behavior

npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in: C:\Users\pc\AppData\Local\npm-cache\_logs\2023-05-30T00_05_13_543Z-debug-0.log

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by EAAARL** [comment]
Same issue here, I was trying to install a next package

**Comment by SaeedAchiever** [comment]
Same issue here too, creating a react project 
ERROR MESSAGE

npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error a

npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in: C:\Users\saeed\AppData\Local\npm-cache\_logs\2023-05-31T02_52_06_367Z-debug-0.log

**Comment by wangge04** [comment]
I also encountered this problem, how can I solve it

**Comment by milaninfy** [comment]
**Closing:** this error can arise for a number of reasons; Please read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) & refile an issue with as much information as possible if you're able to **consistently reproduce** this error.
