### ISSUE TITLE
[BUG] multiple "omit" options in the .npmrc file are not accepted

### ISSUE THREAD

**Issue by dominikj111** [npm/cli#6516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`npm i --omit dev --omit peer` works as expected, but when I have `.npmrc` like this
```
save = true
omit = dev
omit = peer
```
`devDependencies` are installed and `peerDependencies` are not.

### Expected Behavior

According to documentation where is said
> "dev", "optional", or "peer" (can be set multiple times)

the `npm` will accept omits from `.npmrc` file correctly.

### Steps To Reproduce

1. make new folder and enter it 
2. with this `package.json`:
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "sass": "^1.62.1"
  },
  "peerDependencies": {
    "url-loader": "^4.1.1"
  },
  "optionalDependencies": {
    "sass-loader": "^13.2.2"
  }
}
```
3. with this `.npmrc`:
```
save=true
omit=peer
omit=optional
```
4. `npm i` will install `sass` what is expected and `url-loader` what is not expected

### Environment

> - npm: 9.5.1
> - Node.js: 18.16.0
> - OS Name: MacOS Ventura 13.4
> - System Model Name: Macbook Pro 2019

> - npm: 9.6.7
> - Node.js: 20.2.0
> - OS Name: Debian GNU/Linux 11 (bullseye)

> - `npm config ls`: default except the `.npmrc` config above

**Comment by cco3** [comment]
The `ini` configuration format requires using `[]` in order to set a field multiple times.  [Docs](https://www.npmjs.com/package/ini)

I.e.,

```
omit[]=peer
omit[]=optional
```

This works as expected.  (Tested on provided reproduction steps)

**Comment by dominikj111** [comment]
Yeah, every day is a chance to learn something :)
Thank you
