### ISSUE TITLE
[BUG] NPM passes the --ignore-scripts option to all dependencies.

### ISSUE THREAD

**Issue by frbuceta** [npm/cli#6519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I install a package of my own that contains sqlite3 which itself contains an install script. When I run `npm ci --ignore-scripts` in my project, the sqlite3 does not execute the install script.

### Expected Behavior

Running `npm ci --ignore-scripts` should only ignore the scripts in my packages.

### Steps To Reproduce

https://github.com/loopbackio/loopback-next/pull/9562 See tests

### Environment

- npm: 9.6.7
- Node.js: 18.15.0
- OS Name: GitHub Actions (ubuntu, macos, windows)
- System Model Name: CI
- npm config:
```ini
; "user" config from /home/fran/.npmrc

//registry.npmjs.org/:_authToken = (protected) 

; "project" config from /home/fran/Projects/loopback-next/.npmrc

package-lock = true 
scripts-prepend-node-path = true 

; node bin location = /usr/bin/node
; node version = v18.15.0
; npm local prefix = /home/fran/Projects/loopback-next
; npm version = 9.6.7
; cwd = /home/fran/Projects/loopback-next
; HOME = /home/fran
; Run `npm config ls -l` to show all defaults.
```

**Comment by ljharb** [comment]
The primary purpose of the flag is to ignore scripts in installed deps imo.

**Comment by wraithgar** [comment]
This is not a bug this is by design and as stated is the original purpose behind the flag.
