### ISSUE TITLE
[QUESTION] Reporting a dead project

### ISSUE THREAD

**Issue by ekkis** [npm/cli#652]
How do I report a dead project?

This: https://www.npmjs.com/package/@cryptobridge/bitcoin-address-generator leads to a non-existent Github repo and should be removed from npm

**Comment by ljharb** [comment]
Many projects are dead; but a GitHub repo is not a requirement for anything to be on npm, and removing anything that’s not actively malicious might break people.

**Comment by ljharb** [comment]
Either way this is something you should email npm support about; this is the repo for the CLI.

**Comment by ekkis** [comment]
hei ljharb.  it wasn't clear how to reach out to npm.  I clicked on Community / Bug Tracker as the other choices: "Documentation, Events, Feature Request, Archived Forum and Support (Are you experiencing problems with npm itself?)" didn't applicable

you're right that pulling it might break people using it but no one can be using it as the Github repo isn't even there

**Comment by ljharb** [comment]
Of course they can; a GitHub repo is entirely unused for *any* package - it’s optional and no package need have a working one, or any at all.

**Comment by ekkis** [comment]
hmm... ok.  I'll close the issue.  thanks mate
