### ISSUE TITLE
[BUG] Undocumented change in behaviour in npm v7 around npm install from package-lock

### ISSUE THREAD

**Issue by Thrillpool** [npm/cli#6528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

If one does like so

```
npm init --yes
npm install lodash

modify package-lock so https://registry.npmjs.org/ ... becomes like
https://registryyyyyyyyyyy.npmjs.org/

npm ci --force --cache ./somecache
```

Then the effect in npm v7 is that you get a resolution error, can't resolve the name registryyyyyyyyyyy.npmjs.org

Happens in all versions of npm that I've checked since, including latest.

### Expected Behavior

If you compare the behaviour with npm 6, there it happily just works out to not worry about the registry. I think this is probably the intended behaviour based on https://twitter.com/zkat__/status/862834964932435969.  And to me it makes a lot more sense, this new behaviour is unhappy for me, because for instance my cicd refers to the same repo as is used by developers locally, but by a different host name, and in fact cicd can't resolve the name the developers use.

I am thinking this is a bug because it wasn't detailed in https://github.com/npm/cli/releases/tag/v7.0.0

### Steps To Reproduce

Already detailed

### Environment

- npm: 7.0.0
- Node.js: 15.0.0

**Comment by wraithgar** [comment]
This was an intentional part of the update to [lockfile v2](https://github.blog/2021-02-02-npm-7-is-now-generally-available/#breaking-changes).  Ignoring the fqdn in the lockfile is a security concern.
