### ISSUE TITLE
[BUG] `npm run`: '--' prefixed flags invalid

### ISSUE THREAD

**Issue by JerryWn12** [npm/cli#6541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

The arguments start with '--' won't pass to program when using `npm run --`
main.js
`console.log(process.argv)`
commands:
`npm run start -- --test=text`
output:
(won't show `--test=text` argument)
screenshot:
![screenshot](https://github.com/npm/cli/assets/78143571/cf27fc6d-2c01-4bc3-9677-fd1161ea3fb3)

### Expected Behavior

the argument start with '--' should output normally
```
[
  'C:\\Users\\user\\AppData\\Local\\Programs\\node-v18.16.0-win-x64\\node.exe',
  'C:\\Users\\user\\WorkSpace\\test\\src\\main.js',
  '--test=text'
]
```

### Steps To Reproduce

1. latest vscode, nodejs lts v18.16.0, npm v9.7.1
2. create file structure in screenshot above
3. open terminal, run `npm run start -- --arg=value`
4. won't see value in output

### Environment

- npm: v9.7.1
- Node.js: v18.16.0 lts
- OS Name: Windows 11	22H2 22621.1778
- System Model Name: Lenovo
- npm config:
```ini
; "user" config from C:\Users\user\.npmrc

//registry.npmjs.org/:_authToken = (protected)

; node bin location = C:\Users\user\AppData\Local\Programs\node-v18.16.0-win-x64\node.exe
; node version = v18.16.0
; npm local prefix = C:\Users\user
; npm version = 9.7.1
; cwd = C:\Users\user
; HOME = C:\Users\user
; Run `npm config ls -l` to show all defaults.
```

**Comment by JerryWn12** [comment]
<del>update npm to 9.7.1 fixes it </del>
it still happen
```
npm run start -- --test=text

> test@1.0.0 start
> node main.js

[
  'C:\\Users\\user\\AppData\\Local\\Programs\\node-v18.16.0-win-x64\\node.exe',
  'C:\\Users\\user\\WorkSpace\\test\\main.js'
]
npm -v
9.7.1
```

**Comment by JerryWn12** [comment]
behave normally when argument don't start with '--'
```
npm run start -- test=text  

> test@1.0.0 start
> node main.js test=text

[
  'C:\\Users\\user\\AppData\\Local\\Programs\\node-v18.16.0-win-x64\\node.exe',
  'C:\\Users\\user\\WorkSpace\\test\\main.js',
  'test=text'
]
```

**Comment by shadowspawn** [comment]
Are you running the command from PowerShell?

Possibly related: #3136

**Comment by JerryWn12** [comment]
> Are you running the command from PowerShell?
> 
> Possibly related: #3136

yes, it's powershell
thank you for help, i'll use solution in that thread

**Comment by AlexandreNS** [comment]
I'm having to use `--` twice, like this:

`npm run start -- -- --some-parameter`

Any solution implemented without use this trick in powershell?
