### ISSUE TITLE
[BUG] npm >= 9.6.7 does not pass signals to the running script

### ISSUE THREAD

**Issue by zdm** [npm/cli#6547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I have docker sontainer with nodejs application.
Application started  using `npm run prod` command. 
It starts script `main.js`.
This script waiting for `SIGTERM` and exits.

With npm <= 9.6.6 - when I send TERM signal, to the container it works as expected.
With npm >= 9.6.7 - main script just not receive signal.

Tested with all nom versions from 9.6.5 - 9.7.1.
Bug was introduced in v9.6.7.

### Expected Behavior

Please, see above.

### Steps To Reproduce

Please, see above.

### Environment

- npm:
- Node.js:
- OS Name: ubuntu
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by zdm** [comment]
This is major issue, that may lead to the data loss.

**Comment by zdm** [comment]
I created repo to reproduce this bug.

https://github.com/zdm/npm-issue-547

Please, see README..

Could you please fix it? This is very important for  us.

**Comment by zdm** [comment]
Guys,
`nom` doesn't handle signals anymore.
This means that instead of correct exit on `SIGTERM` process will be killed after timeout.
This will lead to data loss on many applications.
Could you, please, restore correct functionality, as it was implemented in `v9.6.6.`.

**Comment by tetsuharuohzeki** [comment]
I guess this is caused by:

- https://github.com/npm/cli/commit/35e2e9a4ce91325462d75b1774298485127762fc
- https://github.com/npm/run-script/pull/142

**Comment by zdm** [comment]
Yes.
I am unable to contact person, who created this bug. He don't answer.

**Comment by zdm** [comment]
Is it possible to fix this?
Who ever decided to disable signals processing?

I am personally currently loaded on 200% and absolutely have no time to study and dig npm sources.

**Comment by zdm** [comment]
Does this project has development team?
How bugs are fixed?
Seems that U am understand now, why `npm` is so ugly.

**Comment by zdm** [comment]
@wraithgar 
Does this project has development team?
How bugs are fixed

**Comment by zdm** [comment]
This is complete shit.

**Comment by ngbrown** [comment]
I just encountered this in npm v9.6.7 after upgrading my docker container to `node:18-bookworm-slim`. Any call to `npm run ...` no longer passes `SIGTERM` through to the final script.

This was working in npm v8.19.4 that was shipped with `node:16-bullseye-slim` .

**Comment by ryanrasti** [comment]
I've run into the same issue in #6684 -- and it's more than signals are not passed to the final script: npm itself doesn't terminate when it receives a SIGTERM.

**Comment by ryanrasti** [comment]
@zdm I noticed you closed this bug -- is it fixed?

**Comment by dmaizel** [comment]
Why was this closed?

**Comment by bencripps** [comment]
Could we reopen this issue, and merge https://github.com/npm/run-script/pull/188
