### ISSUE TITLE
NPM advisories data dump

### ISSUE THREAD

**Issue by Anshu2405** [npm/cli#657]
Hi Team,

I am looking to get complete dump of all advisories and their information (like which component is affected due to this etc.)
So is there any API from where I can get it?

Is there any solution that this which has been out there from npm?

Any help is much appreciated!

**Comment by DanielRuf** [comment]
Yes, it is possible with the `X-Spiferack: 1` header

https://npm.community/t/can-i-query-npm-for-all-advisory-information/2096/7

https://reqbin.com/afmhg3pn
