### ISSUE TITLE
[BUG] npm update --save does not update dev packages in packages.json

### ISSUE THREAD

**Issue by pboguslawski** [npm/cli#6571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

<del>When `packages.json` contains package with `^7.0.0-beta.0`, updating with `npm update --save` does not update it to latest available `7.0.0-beta.8` version.</del>

 `npm update --save` should update devDependencies in package.json not only update packages in local project dir.

### Expected Behavior

<del>Package should be updated to latest compatible (`7.0.0-beta.8`) version.</del>

 `npm update --save` should update devDependencies in package.json not only update packages in local project dir.

### Steps To Reproduce

```
$ npm --version
8.19.4

$ grep '@smui/button' package.json 
                "@smui/button": "^7.0.0-beta.0",

$ npm update --save

$ grep '@smui/button' package.json 
                "@smui/button": "^7.0.0-beta.0",

$ npm i -D @smui/button@latest

$ grep '@smui/button' package.json 
                "@smui/button": "^7.0.0-beta.8",

$ sudo npm install -g npm@latest

$ npm --version
9.7.1

$ grep '@smui/dialog' package.json
                "@smui/dialog": "^7.0.0-beta.0",

$ npm update --save

$ grep '@smui/dialog' package.json
                "@smui/dialog": "^7.0.0-beta.0",

$ npm i -D @smui/dialog@latest

$ grep '@smui/dialog' package.json
                "@smui/dialog": "^7.0.0-beta.8",
```

### Environment

- npm: checked in 8.19.4 and 9.7.1 as above
- Node.js: v16.20.0
- OS Name: linux debian 10
- System Model Name:
- npm config:
```
engine-strict = true 
audit = false 
```

**Comment by major-mayer** [comment]
I noticed that when you execute `npm update --save` it actually updates the beta packages with the caret specifier, but doesn't change the version in the `package.json` file.
I checked the version using `npm ls` and it shows: `@smui/button@7.0.0-beta.14` after the update instead of `@smui/button@7.0.0-beta.0`

So I think this bug is only about the save to package.json process, not the actual update.

**Comment by major-mayer** [comment]
You can reproduce this by executing this commands:
```
npm install --save  @smui/button@7.0.0-beta.0
npm update --save
npm ls
cat package.json
```

The package.json should still show the beta.0 version while `npm ls` reports beta.14 (or a newer version).

**Comment by pboguslawski** [comment]
> So I think this bug is only about the save to package.json process, not the actual update.

I can confirm that. Problem is not related to package name/version but not saving updated version in packages.json.
Issue's subject and description updated.

**Comment by erikerikson** [comment]
Perhaps related: I ran `npm update -S -D` and it collected both the dev and normal dependencies but wrote both back to `devDependencies`, leaving `dependencies` unchanged with the previous versions.

Following major-mayer's lead, running the following (only added `-D`):

```
npm install --save  @smui/button@7.0.0-beta.0
npm update --save -D
npm ls
cat package.json
```

on a freshly `init`ed `package.json` gave me:

```
npm ERR! Cannot set properties of undefined (setting '@smui/button')
```

Adding an empty `devDependencies` to package.json resolved that issue while exhibiting the transfer behavior:

```
> npm update --save -D
npm ls
cat package.json

changed 24 packages, and audited 47 packages in 1s

found 0 vulnerabilities
tmp5@1.0.0 /.../tmp5
└── @smui/button@7.0.0-beta.15

{
  "name": "tmp5",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@smui/button": "^7.0.0-beta.0"
  },
  "dependencies": {
    "@smui/button": "^7.0.0-beta.0"
  }
}
```

**Comment by kchindam-infy** [comment]
npm update --save command is able to update the package to the latest stable version and save it to the dev dependencies as expected. Try updating to the latest npm version. 
<img width="347" alt="Screenshot 2024-07-09 at 5 50 10 AM" src="https://github.com/npm/cli/assets/172311602/64f61b82-a2e5-4c2a-a0b5-c921612fee0f">
<img width="263" alt="Screenshot 2024-07-09 at 5 51 09 AM" src="https://github.com/npm/cli/assets/172311602/1ce98bdd-370b-448c-a28b-afbb8c903b90">

**Comment by milaninfy** [comment]
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce. If this is still an issue feel free to reopen or create new one.
