### ISSUE TITLE
[BUG] npm profile not work when use web-auth

### ISSUE THREAD

**Issue by elrrrrrrr** [npm/cli#6592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

$ npm whoami
--------
elrrrrrrr

$ npm profile get fullname
--------
npm ERR! code E403
npm ERR! 403 403 Forbidden - GET https://registry.npmjs.org/-/npm/v1/user
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.

### Expected Behavior

$ npm profile get fullname
-------
elrrrrrrr

### Steps To Reproduce

1. npm login
2. login by the web-auth
3. npm profile get fullname

### Environment

- npm: 9.6.7
- Node.js: 16.20.0
- OS Name: osx 13.3.1
- System Model Name: Ventura
- npm config:
```ini
; copy and paste output from `npm config ls` here
; "user" config from /Users/elr/.npmrc
//registry.npmjs.org/:_authToken = (protected)
registry = "https://registry.npmjs.org/"
strict-ssl = false

; node bin location = /Users/elr/.nvm/versions/node/v16.20.0/bin/node
; node version = v16.20.0
; npm local prefix = /Users/elr/code/hituweb
; npm version = 9.6.7
; cwd = /Users/elr/code/hituweb
; HOME = /Users/elr
; Run `npm config ls -l` to show all defaults.
```

**Comment by elrrrrrrr** [comment]
I recently logged into npm using the default webauth authentication method. However, after doing so, when I try to access the User API endpoint at `https://registry.npmjs.org/-/npm/v1/user`, I am receiving a **403** error.
![image](https://github.com/npm/cli/assets/5574625/00b4f5af-1238-49b1-8f2b-71e05e33201d)


Interestingly, when I execute other commands such as npm whoami, everything works as expected, which makes me even more puzzled about the 403 error when accessing the User API endpoint.
![image](https://github.com/npm/cli/assets/5574625/c12033e9-0837-44f9-8131-f8e5d488beaa)

I am uncertain whether the issue is directly related to using the webauth authentication method, or if it's something else.

I've looked through the official NPM documentation at https://github.com/npm/registry/blob/master/docs/user/profile.md and https://docs.npmjs.com/cli/v9/commands/npm-profile and I couldn't find any information that might suggest why this issue is happening.

Can you please help me understand why this is happening and how to resolve it? Any help or insights on this matter would be greatly appreciated. 😘

**Comment by wraithgar** [comment]
I'm logged in via web auth and this command works fine. Cannot reproduce.  This is likely an issue w/ your auth token and the npm registry, you may want to contact support at https://www.npmjs.com/support
