### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by icemn** [npm/cli#660]
npm install -g exp

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\delger\AppData\Roaming\npm-cache\_logs\2020-01-07T02_45_34_493Z-debug.log

**Comment by irismm** [comment]
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\ruanjian\nodejs\node_cache\_logs\2020-01-07T04_23_55_282Z-debug.log

**Comment by ljharb** [comment]
Maybe provide the debug logs?

**Comment by irismm** [comment]
[2020-01-07T04_23_55_282Z-debug.log](https://github.com/npm/cli/files/4029558/2020-01-07T04_23_55_282Z-debug.log)

**Comment by irismm** [comment]
> npm install -g exp
> 
> npm ERR! cb() never called!
> 
> npm ERR! This is an error with npm itself. Please report this error at:
> npm ERR! https://npm.community
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\delger\AppData\Roaming\npm-cache_logs\2020-01-07T02_45_34_493Z-debug.log

hi, have you resolve it ?

**Comment by mikemimik** [comment]
Duplicate issue; aggregating into https://github.com/npm/cli/issues/417.
