### ISSUE TITLE
 Exit handler never called! This is an error with npm itself. Please report this error ...

### ISSUE THREAD

**Issue by JoeCodeswell** [npm/cli#6603]
```powershell
PowerShell 7.3.4
PS C:\Windows\System32> # install prerequisites for a Word task pane add-in (https://learn.microsoft.com/en-us/office/dev/add-ins/tutorials/word-tutorial)
PS C:\Windows\System32> # running as admin
PS C:\Windows\System32> ts
23_06_23___13_35_36___Fri
PS C:\Windows\System32> node -v
v20.2.0
PS C:\Windows\System32> npm -v
9.6.6
PS C:\Windows\System32> # follow https://learn.microsoft.com/en-us/office/dev/add-ins/tutorials/word-tutorial#prerequisites
PS C:\Windows\System32> # install latest version of Yeoman and the Yeoman generator for Office Add-ins.
PS C:\Windows\System32> # install above GLOBALLY
PS C:\Windows\System32> npm install -g yo generator-office
npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in: ...npm-cache\_logs\2023-06-23T20_38_01_947Z-debug-0.log
PS C:\Windows\System32>

```

**Comment by AmaLevi1** [comment]
> ```powershell
> PowerShell 7.3.4
> PS C:\Windows\System32> # install prerequisites for a Word task pane add-in (https://learn.microsoft.com/en-us/office/dev/add-ins/tutorials/word-tutorial)
> PS C:\Windows\System32> # running as admin
> PS C:\Windows\System32> ts
> 23_06_23___13_35_36___Fri
> PS C:\Windows\System32> node -v
> v20.2.0
> PS C:\Windows\System32> npm -v
> 9.6.6
> PS C:\Windows\System32> # follow https://learn.microsoft.com/en-us/office/dev/add-ins/tutorials/word-tutorial#prerequisites
> PS C:\Windows\System32> # install latest version of Yeoman and the Yeoman generator for Office Add-ins.
> PS C:\Windows\System32> # install above GLOBALLY
> PS C:\Windows\System32> npm install -g yo generator-office
> npm ERR! Exit handler never called!
> 
> npm ERR! This is an error with npm itself. Please report this error at:
> npm ERR!     <https://github.com/npm/cli/issues>
> 
> npm ERR! A complete log of this run can be found in: ...npm-cache\_logs\2023-06-23T20_38_01_947Z-debug-0.log
> PS C:\Windows\System32>
> ```

How do I resolve this

**Comment by AmaLevi1** [comment]
How do I resolve this

**Comment by JoeCodeswell** [comment]
Hi AmaLevi1,

If you don't know, I CERTAINLY don't know. :)

I was following [install prerequisites for a Word task pane add-in](https://learn.microsoft.com/en-us/office/dev/add-ins/tutorials/word-tutorial)

After  I issued the command `npm install -g yo generator-office`, the "npm ERR!" messages came up saying:
 **"... Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues> ..."**

So I OBEYED the messages. That's all I know.

Thanks for the help.

Love and peace,
Joe

**Comment by milaninfy** [comment]
update npm to latest (10.8.3) and try. 

**Closing:** this error can arise for a number of reasons; Please read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) & refile an issue with as much information as possible if you're able to **consistently reproduce** this error.
