### ISSUE TITLE
[QUESTION] Issues with running scripts on Windows 7

### ISSUE THREAD

**Issue by thisiskylierose** [npm/cli#661]
# What / Why
I'm not sure if this is the right place to ask for help but I have exhausted a few options (such as reinstalling node.js twice and adding/reverting npm config properties. 

The basic issue is that scripts such as postinstall, start and build have stopped working. I'm not sure why this occurred but it is (obviously) blocking my work. 

## Where
I can't provide an example of the project configuration or dependencies. But we use the recharts and react-scripts packages and this is where the issue occurs when installing. 

I am using node v10.16.1 and npm v6.13.4
The OS is Windows 7

An excerpt from the log is below:

```
200 verbose stack Error: core-js@2.6.11 postinstall: `node -e "try{require('./postinstall')}catch(e){}"`
200 verbose stack spawn = ENOENT
200 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
200 verbose stack     at onErrorNT (internal/child_process.js:415:16)
200 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
201 verbose pkgid core-js@2.6.11
202 verbose cwd C:\WebDev\panda-live-v2
203 verbose Windows_NT 6.1.7601
204 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "recharts"
205 verbose node v10.16.1
206 verbose npm  v6.13.4
207 error code ELIFECYCLE
208 error syscall spawn =
209 error file =
210 error path =
211 error errno ENOENT
212 error core-js@2.6.11 postinstall: `node -e "try{require('./postinstall')}catch(e){}"`
212 error spawn = ENOENT
213 error Failed at the core-js@2.6.11 postinstall script.
213 error This is probably not a problem with npm. There is likely additional logging output above.
214 verbose exit [ 1, true ]
```

**Comment by ljharb** [comment]
It looks like core-js's postinstall script is failing; you should file a new issue (https://github.com/zloirock/core-js/issues/729 is similar but was closed)

**Comment by thisiskylierose** [comment]
> It looks like core-js's postinstall script is failing; you should file a new issue ([zloirock/core-js#729](https://github.com/zloirock/core-js/issues/729) is similar but was closed)

Thanks @ljharb
