### ISSUE TITLE
Port and instanceName not working in mssql 

### ISSUE THREAD

**Issue by vachansuthar** [npm/cli#662]
If I pass port and instanceName both in connectionString then it is not working due to this code
`const port = parsed.port ? `,${parsed.port}` : (instance ? `\\${instance}` : '')` in connectionstring.js
It should be like below
`const port = parsed.port && instance ? `,${parsed.port}\\${instance}` : (parsed.port ? `,${parsed.port}` : (instance ? `\\${instance}` : ''))`
The connection string I am passing is like this:
mssql://UserName:Password@hostName:58000/instanceName/DataBaseName?applicationintent=readonly
![Capture](https://user-images.githubusercontent.com/22950586/71877912-5d426b00-3150-11ea-897f-7c67eecc86ce.PNG)

**Comment by ljharb** [comment]
This is a repo for npm itself; you'll need to file a bug on the mssql package instead.
