### ISSUE TITLE
Wrong install command for scoped/private packages (Windows 10+)

### ISSUE THREAD

**Issue by igorskyflyer** [npm/cli#6621]
On Windows 10+ machines that use PowerShell as the command processor (which is quite common in dev-world), the asperand (@) symbol has a special meaning - it's an operator, thus `npm install` command provided on any npm page for a scoped/private package will fail.

<div align="center">
	<img src="https://github.com/npm/cli/assets/20957750/3e9eaba2-aaab-42de-a049-5893cf3aab98" alt="npm page for @igor.dvlpr/normalized-string">
</div>

Package names that contain an asperand symbol (@) should be quoted, like seen at the bottom of the screenshot I provided and written about in the README of my project.

Here's the actual error being shown:

<div align="center">
	<img src="https://github.com/npm/cli/assets/20957750/87d4edff-49d1-4e23-844d-0ec4ef9d3644" alt="Screenshot of the Terminal error">
</div>

**Comment by ljharb** [comment]
huh, never heard the term "asperand" before, usually people just call it "the at sign".

**Comment by igorskyflyer** [comment]
> huh, never heard the term "asperand" before, usually people just call it "the at sign".

Guess we learn something new every day. 🤓

**Comment by milaninfy** [comment]
**Closing:** this looks to be an issue with the registry which is outside the scope of this repo. For registry support please go to [npmjs.com/support](https://www.npmjs.com/support). If you believe this is a bug with the cli, please provide further clarifying details.
