### ISSUE TITLE
[BUG] Could not find 'xxx/**/*test.ts'

### ISSUE THREAD

**Issue by Adibla** [npm/cli#6629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Hello, I'm having trouble running my script test using npm. When I use "npm run test", I get the following error:

`Could not locate '/workspaces/xxx/test/routes/**/*test.ts'` due to '**'.

Using the same procedure from my terminal, nothing goes wrong. 

`node --test --require node register ts-node./test/routes/**/*test.ts`

The issue was fixed with the subsequent command.
`npm config set script-shell bash`

Alternatives to changing the user's npm setup are there? Thanks

### Expected Behavior

I assume the same results from the terminal and `npm run test`.

### Environment

- npm: 9.6.3
- Node.js: v19.9.0
- npm config:
```ini
; node bin location = /usr/local/share/nvm/versions/node/v19.9.0/bin/node
; node version = v19.9.0
; npm local prefix = /workspaces/project-sample
; npm version = 9.6.3
; cwd = /workspaces/project-sample
; HOME = /home/codespace
```

**Comment by wraithgar** [comment]
This does not appear to be a bug w/ npm but with the package itself.  No steps to reproduce so can't triage further.
