### ISSUE TITLE
[DOCS] `description` field section anchor in invalid

### ISSUE THREAD

**Issue by victorpolko** [npm/cli#6632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Problem, not another kind of Docs Problem.

- [X] This is a CLI Docs Problem.

### Description of Problem

The table of contents (ToC) on [this page](https://docs.npmjs.com/cli/v9/configuring-npm/package-json) contains a link to the `description` field, and its url links to the anchor `#description-1`, but for some reason there's no such anchor on the page itself.

### Investigation

1. There's a heading `Description` for the page contents description
1. There's a heading `description` for the corresponding `package.json` field
1. Markdown implies that the auto-generated section links for sections with identical names (`Description` and `description`) become `<name>-1`, `<name>-2` etc.
1. ToC seems to be auto-generated based upon the contents of this `md` file
1. ToC contains correct section links: `#description` redirects to the page contents description, `#description-1` – to the `description` field
1. The `Description` heading is rendered correctly: `h3#description`, anchor with `id="description"`
1. The `description` heading is rendered _incorrectly_: `h3#description`, anchor with `id="description"`, which is the root of the issue

### Potential Solution

I tried to fix it changing [this file](https://github.com/npm/cli/blob/latest/docs/lib/content/configuring-npm/package-json.md), but even GitHub's preview rendered the original code correctly (with `#description-1` as the anchor for the `description` section), and thus I'm unable to reproduce the issue, so, I can't fix it.

#### Possible solutions
1. ? Add a `&nbsp;` after the `### description` or after the `### Description`
1. ? Change the level of either `Description` or `description` section
1. ? Rename the `Description` section (not recommended, as other pages each have a section with that name)

I'm not sure if any of these would work, because, again, I can't reproduce the issue in any MD editor.

### Affected URL

https://docs.npmjs.com/cli/v9/configuring-npm/package-json#description-1

**Comment by wraithgar** [comment]
https://github.com/npm/documentation/issues/34
