### ISSUE TITLE
[BUG] Cannot find module '@npmcli/config'

### ISSUE THREAD

**Issue by natesire** [npm/cli#6635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

It looks like the require of that config package isn't loading. This is a clean install.

Node v20.3.1

I cannot run any npm cli commands either. This happened around the same time debugging workspaces and Windows path problems.

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node.js:
- OS Name: Windows 11
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```
Cannot run npm commands.

**Comment by TimB87** [comment]
still happening with facda25daab7cdd5f6aaad2260379aedeef33caa

**Comment by polyzen** [comment]
You have to first run `node scripts/resetdeps.js`.

**Comment by TimB87** [comment]
@polyzen thank you!
Using the tarball it throws another error for not having a git repository:

```
+ node scripts/resetdeps.js
INFO spawn git checkout node_modules/
fatal: not a git repository (or any of the parent directories): .git
ERRO GitUnknownError: An unknown git error occurred
ERRO     at makeError (/home/pkgmk/work/npm/src/cli-9.8.1/node_modules/@npmcli/git/lib/make-error.js:28:13)
ERRO     at /home/pkgmk/work/npm/src/cli-9.8.1/node_modules/@npmcli/git/lib/spawn.js:37:26
ERRO     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
ERRO     at async spawn (/home/pkgmk/work/npm/src/cli-9.8.1/scripts/util.js:72:11)
ERRO     at async cleanup (/home/pkgmk/work/npm/src/cli-9.8.1/scripts/resetdeps.js:6:3)
ERRO     at async main (/home/pkgmk/work/npm/src/cli-9.8.1/scripts/resetdeps.js:22:3)
ERRO     at async run (/home/pkgmk/work/npm/src/cli-9.8.1/scripts/util.js:166:17)
ERRO cmd: /usr/bin/git
ERRO args: --no-replace-objects checkout node_modules/
ERRO code: 128
```

Preferably, git wasn't a requirement. Is there a way around that?

**Comment by TimB87** [comment]
What worked for me is moving the missing directories from workspaces to node_modules:
```
  cp -r workspaces/config node_modules/@npmcli/
  cp -r workspaces/libnpmfund node_modules/libnpmfund
  cp -r workspaces/arborist node_modules/@npmcli/arborist
```

that way I was able to execute `node bin/npm-cli.js`

**Comment by natesire** [comment]
It seems that Node 18 fixed the issue but then the issue regressed in Node 20. I am looking at it again :) Thanks for all the awesome comments. So helpful.

**Comment by Raidoxe** [comment]
The only thing that worked for me was deleting my nodejs folder located in programfiles/nodejs and then my nvm folder located in user/AppData/Roaming/nvm. Then doing a complete re install of node js.

**Comment by NaomiN** [comment]
I am getting this error all of the sudden and cannot run any npm commands. What should I do?

Error: Cannot find module '@npmcli/arborist'
Require stack:
- C:\Program Files (x86)\Nodist\npmv\9.3.1\lib\npm.js
- C:\Program Files (x86)\Nodist\npmv\9.3.1\lib\cli.js
- C:\Program Files (x86)\Nodist\npmv\9.3.1\bin\npm-cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)

**Comment by pungggi** [comment]
https://stackoverflow.com/questions/77128188/error-cannot-find-module-npmcli-config

**Comment by FrongKT98** [comment]
> ### Is there an existing issue for this?
> 
> 
> 
> - [X] I have searched the existing issues
> 
> 
> 
> ### This issue exists in the latest npm version
> 
> 
> 
> - [X] I am using the latest npm
> 
> 
> 
> ### Current Behavior
> 
> 
> 
> It looks like the require of that config package isn't loading. This is a clean install.
> 
> 
> 
> Node v20.3.1
> 
> 
> 
> I cannot run any npm cli commands either. This happened around the same time debugging workspaces and Windows path problems.
> 
> 
> 
> ### Expected Behavior
> 
> 
> 
> _No response_
> 
> 
> 
> ### Steps To Reproduce
> 
> 
> 
> 1. In this environment...
> 
> 2. With this config...
> 
> 3. Run '...'
> 
> 4. See error...
> 
> 
> 
> 
> 
> ### Environment
> 
> 
> 
> - npm:
> 
> - Node.js:
> 
> - OS Name: Windows 11
> 
> - System Model Name:
> 
> - npm config:
> 
> ```ini
> 
> ; copy and paste output from `npm config ls` here
> 
> ```
> 
> Cannot run npm commands.
