### ISSUE TITLE
cannot install carthage from npm 6.9.0 version

### ISSUE THREAD

**Issue by KajalJena** [npm/cli#664]
Getting npm error when tried to install carthage.

npm - 6.9.0
Command- npm install carthage 

Here is the error log 
 0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'carthage' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose config Skipping project config: /Users/usrName/.npmrc. (matches userconfig)
5 verbose npm-session 7bb22338421ff355
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 timing npm Completed in 2026ms
9 error cb() never called!
10 error This is an error with npm itself. Please report this error at:
11 error <https://npm.community>

**Comment by ljharb** [comment]
Why about with the latest version of npm?

**Comment by KajalJena** [comment]
I'd updated homebrew and npm package again and got latest versions. Now it is working and I can install packages without any error or issue.
Thanks

**Comment by DanielRuf** [comment]
Ok then please close the issue.

**Comment by mikemimik** [comment]
Duplicate issue; aggregating into https://github.com/npm/cli/issues/417.
