### ISSUE TITLE
[BUG] npm i failing for random packages on retry saying package not found

### ISSUE THREAD

**Issue by manojbavikati** [npm/cli#6644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

npm ERR! 404 Not Found - GET https://registry.npmjs.org/@antv%2fl7-component - Not found

### Expected Behavior

install should complete without errors.

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:9.6.7
- Node.js:v18.16.1
- OS Name: Windows 11
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by jfirebaugh** [comment]
Also seeing this. Looks like consistency issues with the CDN or something like that.

**Comment by jfirebaugh** [comment]
Repeat of https://github.com/npm/cli/issues/1626?

**Comment by codybswaney** [comment]
Also seeing this, inconsistency with pulling various packages over the last 45+ minutes or so. 

The full error from the first package we saw it on: 

```
#10 79.31 npm ERR! code E404
#10 79.31 npm ERR! 404 Not Found - GET https://registry.npmjs.org/@vercel%2fncc - Not found
#10 79.31 npm ERR! 404 
#10 79.31 npm ERR! 404  '@vercel/ncc@0.34.0' is not in this registry.
#10 79.31 npm ERR! 404 
#10 79.31 npm ERR! 404 Note that you can also install from a
#10 79.31 npm ERR! 404 tarball, folder, http url, or git url.
#10 79.32 
#10 79.32 npm ERR! A complete log of this run can be found in:
#10 79.32 npm ERR!     /root/.npm/_logs/2023-07-14T19_49_53_940Z-debug-0.log
#10 ERROR: process "/bin/sh -c npm ci" did not complete successfully: exit code: 1
```

For clarity, [@vercel/ncc@0.34.0](https://www.npmjs.com/package/@vercel/ncc/v/0.34.0) does exist.

**Comment by iagormoraes** [comment]
> Also seeing this, inconsistency with pulling various packages over the last 45+ minutes or so.
> 
> The full error from the first package we saw it on:
> 
> ```
> #10 79.31 npm ERR! code E404
> #10 79.31 npm ERR! 404 Not Found - GET https://registry.npmjs.org/@vercel%2fncc - Not found
> #10 79.31 npm ERR! 404 
> #10 79.31 npm ERR! 404  '@vercel/ncc@0.34.0' is not in this registry.
> #10 79.31 npm ERR! 404 
> #10 79.31 npm ERR! 404 Note that you can also install from a
> #10 79.31 npm ERR! 404 tarball, folder, http url, or git url.
> #10 79.32 
> #10 79.32 npm ERR! A complete log of this run can be found in:
> #10 79.32 npm ERR!     /root/.npm/_logs/2023-07-14T19_49_53_940Z-debug-0.log
> #10 ERROR: process "/bin/sh -c npm ci" did not complete successfully: exit code: 1
> ```
> 
> For clarity, [@vercel/ncc@0.34.0](https://www.npmjs.com/package/@vercel/ncc/v/0.34.0) does exist.

Is not only this package, various others is happening the same.

**Comment by JavaScriptBach** [comment]
Most likely the NPM registry is busted. Still no incident declared in https://status.npmjs.org/ sadly

**Comment by codybswaney** [comment]
Yes, thanks @iagormoraes I should have clarified better: we are seeing it happening on various packages and it's very inconsistent. E.g. my last build failed on another package:

```
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@graphql-tools%2fdelegate - Not found
npm ERR! 404 
npm ERR! 404  '@graphql-tools/delegate@9.0.21' is not in this registry.
```

**Comment by melMass** [comment]
Same here, it worked on the node-setup github action by [explicitely telling it the registry url](https://github.com/teia-community/teia-ui/commit/5cf932bd6fd960ee2b527b2e1f8feb288de50b58), but our [docker build](https://github.com/teia-community/teia-ui/actions/runs/5558251589/jobs/10153121550) now trigger the same

![image](https://github.com/npm/cli/assets/7041726/d2e14ea5-3238-4eb7-a56e-88d5945de908)

**Comment by manojbavikati** [comment]
Looks like the npm registry issue is resolved for me after multiple retry. Looks like it was failing for random packages

**Comment by manojbavikati** [comment]
Looks like the npm registry issue is resolved for me after multiple retry. Looks like it was failing for random packages

**Comment by konard** [comment]
We had a problem for https://registry.npmjs.org/@tand_ferret%2fuseful_hooks too for a short period of time after publish. So this issue continue to reproduce.

https://github.com/deep-foundation/npm-packager/issues/97 - our issue on that problem.
