### ISSUE TITLE
[BUG] semver vulnerability - Is there a public version to move onto that doesn't have it?

### ISSUE THREAD

**Issue by toddtarsi** [npm/cli#6655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I'm on 9.8.0, and when I look at the semver version via `npm ls`, I see 7.5.2. When I look at the semver version in github, it's at 7.5.4. What gives?

### Expected Behavior

I'd expect there'd be a version incremented up to 7.5.4. I understand that this vulnerability is pedantic, but thats a pretty apt description for compliance folks.

### Steps To Reproduce

1. npm i -g npm
2. npm ls semver -g

### Environment

- npm: 9.8.0
- Node.js: 16.14.2
- OS Name: Mac
- System Model Name: idk
- npm config: none
```ini
; "user" config from /Users/toddtarsi/.npmrc

//registry.npmjs.org/:_authToken = (protected) 

; node bin location = /Users/toddtarsi/.nvm/versions/node/v16.14.2/bin/node
; node version = v16.14.2
; npm local prefix = /Users/toddtarsi/Code/vo-ts-monorepo
; npm version = 9.8.0
; cwd = /Users/toddtarsi/Code/vo-ts-monorepo
; HOME = /Users/toddtarsi
; Run `npm config ls -l` to show all defaults.
```

**Comment by ljharb** [comment]
Yes, v5, v6, and v7 latest are all not vulnerable to this, however, vulnerability warnings may not have been updated yet to note that v5 and v6 are fixed.

It takes time for npm to be released, so if you're seeing github more updated than the released code on any project, the only thing you can really do is wait for a release.

**Comment by toddtarsi** [comment]
@ljharb - That is perfectly acceptable. Thanks for explaining the deal! I'll keep an eye out for a patch to npm!
