### ISSUE TITLE
[BUG] Why does when i enter npm install, it said ERR and state that the error is npm itself? 

### ISSUE THREAD

**Issue by LEVUKHANHNGAN** [npm/cli#6657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

$ npm install
npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in: /data/data/com.termux/files/home/.npm/_logs/2023-07-19T07_36_06_226Z-debug-0.log

### Expected Behavior

I expect it to install npm and then start the program

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 9.6.6
- Node.js: 20.2.0
- OS Name:
- System Model Name: Android Samsung S20 FE
- npm config:
```ini
; copy and paste output from `npm config ls` ; "user" config from /data/data/com.termux/files/home/.npmrc

foreground-scripts = true

; node bin location = /data/data/com.termux/files/usr/bin/node
; node version = v20.2.0
; npm local prefix = /data/data/com.termux/files/home/SillyTavern
; npm version = 9.6.6
; cwd = /data/data/com.termux/files/home/SillyTavern
; HOME = /data/data/com.termux/files/home
; Run `npm config ls -l` to show all defaults.
```

**Comment by wraithgar** [comment]
termux on a phone is an extremely resource-limited environment and this typically means the operating system killed something npm was not expecting. There's not a lot npm can do about this currently.
