### ISSUE TITLE
npm ERR! 401 Unauthorized- - You must be logged in to publish packages

### ISSUE THREAD

**Issue by pavansahu06** [npm/cli#668]
While pushing the package in registry not able to publish, its shows "npm ERR! 401 Unauthorized"

please find the  snipped on below-

![image](https://user-images.githubusercontent.com/27881250/71955190-a5739300-320d-11ea-82fd-a204f0ab79ae.png)

I tried to logout the npm and then again logged-in. and then tried to push the package but still getting the same error. please share the solution?

@npm-deploy-user @npm-sre-write @mcollina

**Comment by shinryak** [comment]
Make sure your package name is unique. I think you should search the name you want on npmjs.com before generating new project

**Comment by pavansahu06** [comment]
I tried with unique name but still getting the same error-
Please refer the below snipped-
![image](https://user-images.githubusercontent.com/27881250/72199772-79068380-3466-11ea-8399-907e4691d6ae.png)
@shinryak please suggest.

**Comment by ljharb** [comment]
What does `npm whoami` print out?

**Comment by pavansahu06** [comment]
@ljharb Its printing my account name. please refer the below snipped-

![image](https://user-images.githubusercontent.com/27881250/72200221-cede2a00-346c-11ea-8637-8a53852f99b4.png)

**Comment by shinryak** [comment]
@pavansahu06 
Let's try 
`npm init --scope=@pavansahu06`
and
`npm publish --access public`
Full [docs](https://docs.npmjs.com/creating-and-publishing-scoped-public-packages)
If you already do that, please show npm log and package.json files.
