### ISSUE TITLE
[BUG] some NPM modules are outdated.

### ISSUE THREAD

**Issue by stein2nd** [npm/cli#6692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

After cloning to a local drive, I ran "ncu" and it indicated that some NPM modules were outdated:

> Checking [User home directory]/Documents/GitHub/cli/package.json
> [===================-] 81/84 96%
>  @tufjs/repo-mock     ^1.3.1  →   ^1.4.0
>  glob                ^10.2.7  →  ^10.3.3
>  is-cidr              ^4.0.2  →   ^5.0.3
>  make-fetch-happen   ^11.1.1  →  ^12.0.0
>  minipass             ^5.0.0  →   ^7.0.2
>  ms                   ^2.1.2  →   ^2.1.3
>  nock                ^13.3.0  →  ^13.3.2
>  npm-pick-manifest    ^8.0.1  →   ^8.0.2
>  npm-registry-fetch  ^14.0.5  →  ^15.0.0
>  p-map                ^4.0.0  →   ^6.0.0
>  remark              ^14.0.2  →  ^14.0.3
>  sigstore             ^1.7.0  →   ^1.8.0
>  spawk                ^1.7.1  →   ^1.8.1
>  tap                 ^16.3.4  →  ^16.3.8
> 
>  @npmcli/docs                    404 Not Found - GET https://registry.npmjs.org/@npmcli%2fdocs. Either your internet connection is down or unstable and all 3 retry attempts failed, or the registry is not accessible, or the package does not exist. 
>  @npmcli/mock-globals    404 Not Found - GET https://registry.npmjs.org/@npmcli%2fmock-globals. Either your internet connection is down or unstable and all 3 retry attempts failed, or the registry is not accessible, or the package does not exist. 
>  @npmcli/mock-registry  404 Not Found - GET https://registry.npmjs.org/@npmcli%2fmock-registry. Either your internet connection is down or unstable and all 3 retry attempts failed, or the registry is not accessible, or the package does not exist. 

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:

## System:
 - OS: macOS 13.5
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 285.12 MB / 32.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 20.5.0 - ~/.nodebrew/current/bin/node
 - Yarn: 1.22.19 - /usr/local/bin/yarn
 - npm: 9.8.0 - ~/.nodebrew/current/bin/npm

**Comment by milaninfy** [comment]
Not enough to reproduce the issue. Please fill all the details of the issue template like steps to reproduction, environment details, config etc.

**Comment by lukekarrys** [comment]
We keep our dependencies updated manually in our root package-lock.json file. We don't usually bump the ranges in the individual package.json files, which is what ncu is outputting in the example. But even if there were outdated dependencies, we manage those manually and don't always have everything to the latest version due to incompatibilities, etc.
