### ISSUE TITLE
[BUG] npm publish performs retry after "503 Service Unavailable" which results in "403 Forbidden" as package was actually published on first try

### ISSUE THREAD

**Issue by reey** [npm/cli#6693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When the `PUT` request of `npm publish` returns with an error e.g. 503 this is not properly handled within the cli.
Even though we had the 503 response, the package was actually published successfully.

The retry mechanism of [make-fetch-happen](https://www.npmjs.com/package/make-fetch-happen) is used under the hood by the npm cli and makes a second `PUT` request, but this second request results in a `403 Forbidden` status code as the package was actually published already with the previous request.

This results in that our pipeline fails while publishing the lib, even though the package was actually published.

### Expected Behavior

The retry mechanism of [make-fetch-happen](https://www.npmjs.com/package/make-fetch-happen) should not be used when publishing a package. 
Instead there should be a retry mechanism as part of the `libnpmpublish` package, that after every try checks if the package in the provided version might have been published although the request failed. Some checksum comparisons might be required as well to double check this.
In case it was successfully published `npm publish` should exit gracefully despite the bad status code of the `PUT` request

### Steps To Reproduce

When publishing our package using:
```
npm publish ./.tmp/c8y-ngx-components-1018.403.0.tgz --tag next
```
This fails from time to time (within the last few days more often than before) with status `403 Forbidden` and the following message: `You cannot publish over the previously published versions: 1018.403.0.`:
```
42 notice Publishing to https://registry.npmjs.org/
43 http fetch PUT 403 https://registry.npmjs.org/@c8y%2fngx-components 85574ms attempt #2
44 timing command:publish Completed in 91456ms
45 verbose stack HttpErrorGeneral: 403 Forbidden - PUT https://registry.npmjs.org/@c8y%2fngx-components - You cannot publish over the previously published versions: 1018.403.0.
45 verbose stack     at /opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:95:15
45 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
45 verbose stack     at async publish (/opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/npm/node_modules/libnpmpublish/lib/publish.js:43:12)
45 verbose stack     at async otplease (/opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/npm/lib/utils/otplease.js:4:12)
45 verbose stack     at async Publish.exec (/opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/npm/lib/commands/publish.js:120:7)
45 verbose stack     at async module.exports (/opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/npm/lib/cli.js:78:5)
46 verbose statusCode 403
47 verbose pkgid @c8y/ngx-components@1018.403.0
48 verbose cwd /runner/_work/cumulocity-ui/cumulocity-ui
49 verbose Linux 5.15.0-1040-azure
50 verbose node v16.20.1
51 verbose npm  v8.19.4
52 error code E403
53 error 403 403 Forbidden - PUT https://registry.npmjs.org/@c8y%2fngx-components - You cannot publish over the previously published versions: 1018.403.0.
54 error 403 In most cases, you or one of your dependencies are requesting
54 error 403 a package version that is forbidden by your security policy, or
54 error 403 on a server you do not have access to.
55 verbose exit 1
56 timing npm Completed in 91519ms
57 verbose code 1
58 error A complete log of this run can be found in:
58 error     /home/runner/.npm/_logs/2023-08-01T13_26_17_632Z-debug-0.log
```

The debug log contained the following line:
```
43 http fetch PUT 403 https://registry.npmjs.org/@c8y%2fngx-components 85574ms attempt #2
```
The `attempt #2` was especially irritating.

After some investigations we found out that package that is used for interacting with the API under the hood is: [make-fetch-happen](https://www.npmjs.com/package/make-fetch-happen). This fetch client implementation has some retry mechanism that also applies to the `PUT` request performed when executing the `npm publish` depending on the status code.

The retry mechanism can be disabled by executing `npm config set fetch-retries=0`.

In the meantime we also switched to npm v10.0.0-pre.0 and nodejs v20.5.0 to have the changes from here as well: https://github.com/npm/cli/pull/6641/files#diff-0a79cf1ec4898b2343e3462152578839e57bb9497e81680bd5d7a10d83c883f9

With that config set and the next `npm publish` with another version, this failed with:
```
40 notice Publishing to https://registry.npmjs.org/ with tag next and default access
41 http fetch PUT 503 https://registry.npmjs.org/@c8y%2fngx-components 63384ms
42 timing command:publish Completed in 69900ms
43 verbose stack HttpErrorGeneral: 503 Service Unavailable - PUT https://registry.npmjs.org/@c8y%2fngx-components - Service Unavailable
43 verbose stack     at /opt/hostedtoolcache/node/20.5.0/x64/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:95:15
43 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
43 verbose stack     at async publish (/opt/hostedtoolcache/node/20.5.0/x64/lib/node_modules/npm/node_modules/libnpmpublish/lib/publish.js:53:15)
43 verbose stack     at async otplease (/opt/hostedtoolcache/node/20.5.0/x64/lib/node_modules/npm/lib/utils/otplease.js:4:12)
43 verbose stack     at async Publish.exec (/opt/hostedtoolcache/node/20.5.0/x64/lib/node_modules/npm/lib/commands/publish.js:123:7)
43 verbose stack     at async module.exports (/opt/hostedtoolcache/node/20.5.0/x64/lib/node_modules/npm/lib/cli-entry.js:61:5)
44 verbose statusCode 503
45 verbose pkgid @c8y/ngx-components@1018.420.0
46 verbose cwd /runner/_work/cumulocity-ui/cumulocity-ui
47 verbose Linux 5.15.0-1041-azure
48 verbose node v20.5.0
49 verbose npm  v10.0.0-pre.0
50 error code E503
51 error 503 Service Unavailable - PUT https://registry.npmjs.org/@c8y%2fngx-components - Service Unavailable
52 verbose exit 1
53 timing npm Completed in 70099ms
54 verbose code 1
55 error A complete log of this run can be found in: /home/runner/.npm/_logs/2023-08-04T12_03_29_500Z-debug-0.log
```

Even though we received the 503 and/or 403 errors, the package was still actually published to npm in our cases.

### Environment

- npm: 8.19.4 / 10.0.0-pre.0
- Node.js: 16.20.1 / 20.5.0
- OS Name: Ubuntu 20.04
- System Model Name: GitHub actions runner on GHES using summerwind/actions-runner-dind:ubuntu-20.04 image
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by wraithgar** [comment]
Retry has long since been the established response to a 503. There is even a `Retry-After` header baked into the spec to help clients know how long to wait.

If npm didn't retry the end result would be the same: your package would be published but you'd have gotten an error.  The 503 from the registry when the publish is successful is the real issue here.  npm registry support is at https://www.npmjs.com/support
