### ISSUE TITLE
Request: Remove the Warning about --production

### ISSUE THREAD

**Issue by bdkjones** [npm/cli#6698]
This is a simple feature request (hence the lack of issue template). See this screenshot:

<img width="375" alt="Screenshot 2023-08-07 at 22 20 06" src="https://github.com/npm/cli/assets/926566/be3b37b6-6eb2-417b-b769-e67f4d3a895a">

## The Problem:

`--production` is dead-simple for humans to remember. `--omit=dev`, by contrast, is awful for humans. Every time I have to type the command I think, "What's that gobbledegook they changed '--production' to again? Eh, whatever, the old way works fine."

## The Fix:

Just get rid of the CLI warning and let `--production` be an official alias for `--omit=dev`. The canonical build environments since the dawn of computers have been `production` and `development`, so it makes sense to recognize these as official aliases. For other, more nuanced environments, the `--omit=` parameter provides fine-grained control.

**Comment by kchindam-infy** [comment]
Thank you for the suggestion, According to github guidelines, new feature and suggestions are discussed in the npm feedback forum. Recommended to open a discussion in the npm feedback forum. You can visit here https://github.com/npm/feedback/discussions
