### ISSUE TITLE
[override] how to override dependency with another dependency

### ISSUE THREAD

**Issue by HomyeeKing** [npm/cli#6699]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I tried to override, but got error : conflicts with direct dependency

### Expected Behavior

like pnpm, can override `foo` with nother dependency `bar`

```json
 "overrides": {
    "foo":"bar"
  },
```

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 9.8.1
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by ljharb** [comment]
Have you tried exactly that in npm?

**Comment by HomyeeKing** [comment]
works right now, sorry about this, maybe something wrong at that time
![image](https://github.com/npm/cli/assets/49113249/f664402d-bae2-4965-aa20-7c9fb36bead0)
