### ISSUE TITLE
npm error Unexpected token "."

### ISSUE THREAD

**Issue by shaikh007** [npm/cli#6701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

npx create-react-app youtubeClone
npm ERR! Unexpected token '.
npm ERR! A complete log of this run can be found in:

### Expected Behavior

need to install react app

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 8.6.0
- Node.js: v18.0.0
- OS Name: windows 11
- System Model Name: hp
- npm config: 
```ini
; copy and paste output from `npm config ls` here
```

**Comment by milaninfy** [comment]
@shaikh007 I was unable to reproduce this issue. If this is still an issue, Please provide steps to reproduce and full log of the error.

**Comment by milaninfy** [comment]
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.
