### ISSUE TITLE
[BUG] Error npm new 

### ISSUE THREAD

**Issue by FuriosoJack** [npm/cli#671]
21172 http fetch GET 200 https://registry.npmjs.org/@schematics/angular/-/angular-8.3.22.tgz 7570ms
21173 silly extract adm-zip@^0.4.9 extracted to /home/juan/Descargas/angulartest2/node_modules/.staging/adm-zip-27448250 (242ms)
21174 silly extract ajv-keywords@^3.1.0 extracted to /home/juan/Descargas/angulartest2/node_modules/.staging/ajv-keywords-1b14627e (289ms)
21175 silly extract source-map@^0.5.7 extracted to /home/juan/Descargas/angulartest2/node_modules/.staging/source-map-d4228d6a (549ms)
21176 silly extract bluebird@^3.5.5 extracted to /home/juan/Descargas/angulartest2/node_modules/.staging/bluebird-9a21dd6a (752ms)
21177 silly extract aria-query@^3.0.0 extracted to /home/juan/Descargas/angulartest2/node_modules/.staging/aria-query-5a6e8dea (1298ms)
21178 silly extract clean-css@4.2.1 extracted to /home/juan/Descargas/angulartest2/node_modules/.staging/clean-css-d7477071 (1198ms)
21179 http fetch GET 200 https://registry.npmjs.org/acorn/-/acorn-6.4.0.tgz 431ms
21180 silly extract acorn@^6.2.1 extracted to /home/juan/Descargas/angulartest2/node_modules/.staging/acorn-42021e1e (480ms)
21181 silly extract axobject-query@2.0.2 extracted to /home/juan/Descargas/angulartest2/node_modules/.staging/axobject-query-12f817a2 (765ms)
21182 silly extract @schematics/angular@8.3.22 extracted to /home/juan/Descargas/angulartest2/node_modules/.staging/@schematics/angular-5f0daa7c (7923ms)
21183 silly extract es-abstract@^1.17.0-next.1 extracted to /home/juan/Descargas/angulartest2/node_modules/.staging/es-abstract-f935f34a (6410ms)
21184 silly extract fsevents@^1.2.7 extracted to /home/juan/Descargas/angulartest2/node_modules/.staging/fsevents-2248f495 (8928ms)
21185 silly extract fsevents@^1.2.7 extracted to /home/juan/Descargas/angulartest2/node_modules/.staging/fsevents-c856f956 (8734ms)
21186 silly extract babel-runtime@^6.26.0 extracted to /home/juan/Descargas/angulartest2/node_modules/.staging/babel-runtime-8f0077d1 (958ms)
21187 silly extract less@3.9.0 extracted to /home/juan/Descargas/angulartest2/node_modules/.staging/less-0543a831 (9308ms)
21188 silly extract fsevents@^1.2.7 extracted to /home/juan/Descargas/angulartest2/node_modules/.staging/fsevents-a9521bad (4600ms)
21189 silly extract fsevents@^1.2.7 extracted to /home/juan/Descargas/angulartest2/node_modules/.staging/fsevents-fcaf301e (4603ms)
21190 http fetch GET 200 https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30001019.tgz 2151ms
21191 silly extract lodash@^4.17.13 extracted to /home/juan/Descargas/angulartest2/node_modules/.staging/lodash-66d8d44f (4175ms)
21192 silly extract caniuse-lite@1.0.30001019 extracted to /home/juan/Descargas/angulartest2/node_modules/.staging/caniuse-lite-c0e00ea5 (2349ms)
21193 http fetch GET 200 https://registry.npmjs.org/core-js/-/core-js-2.6.11.tgz 4592ms
21194 silly extract core-js@^2.2.0 extracted to /home/juan/Descargas/angulartest2/node_modules/.staging/core-js-38b89d7e (4646ms)
21195 silly extract core-js@3.2.1 extracted to /home/juan/Descargas/angulartest2/node_modules/.staging/core-js-08a44d9f (3301ms)
21196 silly extract core-js@^2.4.0 extracted to /home/juan/Descargas/angulartest2/node_modules/.staging/core-js-78476a57 (2514ms)
21197 http fetch GET 200 https://registry.npmjs.org/@angular/core/-/core-8.2.14.tgz 11670ms
21198 silly extract @angular/core@~8.2.14 extracted to /home/juan/Descargas/angulartest2/node_modules/.staging/@angular/core-d482d40e (11835ms)
21199 silly extract typescript@~3.5.3 extracted to /home/juan/Descargas/angulartest2/node_modules/.staging/typescript-4c869f1c (9284ms)
21200 http fetch GET 200 https://registry.npmjs.org/@angular/common/-/common-8.2.14.tgz 11861ms
21201 silly extract @angular/common@~8.2.14 extracted to /home/juan/Descargas/angulartest2/node_modules/.staging/@angular/common-cf2f1af3 (12025ms)
21202 silly extract rxjs@~6.4.0 extracted to /home/juan/Descargas/angulartest2/node_modules/.staging/rxjs-d103409f (9327ms)
21203 http fetch GET 200 https://registry.npmjs.org/@angular/compiler/-/compiler-8.2.14.tgz 32482ms
21204 silly extract @angular/compiler@~8.2.14 extracted to /home/juan/Descargas/angulartest2/node_modules/.staging/@angular/compiler-5b7f64bf (32613ms)
21205 error cb() never called!
21206 error This is an error with npm itself. Please report this error at:
21207 error <https://github.com/npm/npm/issues>

**Comment by mikemimik** [comment]
Duplicate issue; aggregating into https://github.com/npm/cli/issues/417.
