### ISSUE TITLE
[BUG] npm commands don't work on PowerShell (but work on Command Prompt)

### ISSUE THREAD

**Issue by andradei** [npm/cli#6710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I tried installing `node` and `npm` (shipped with node) with each of these tools (one at a time)
- Scoop
- Winget
- Direct download from official site

And I have the same issue with all of them where:
- Node runs fine on both `Command Prompt` and `PowerShell`
- `npm` works only on `Command Prompt` but **not** on `PowerShell`

![image](https://github.com/nodejs/node/assets/2653546/f97f344e-3613-4270-be56-c2f60848d315)

How do I make `npm` work on PowerShell?

### Expected Behavior

`npm` commands work in PowerShell like they do in Command Prompt.

### Steps To Reproduce

1. Install `node` (comes with `npm`) from the official site (for Windows 10)
2. Run `npm -version` on PowerShell

### Environment

- npm: 9.6.7
- Node.js: v18.17.1
- OS Name: Windows 11 (tried on 10 as well)
- System Model Name: 22H2
- npm config:
```ini
; "builtin" config from C:\Program Files\nodejs\node_modules\npm\npmrc

cache = "C:\\Program Files\\nodejs\\cache"
prefix = "C:\\Program Files\\nodejs\\bin"

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v18.17.1
; npm local prefix = C:\Users\me
; npm version = 9.6.7
; cwd = C:\Users\me
; HOME = C:\Users\me
; Run `npm config ls -l` to show all defaults.
```

**Comment by ParamThakkar123** [comment]
In my case, It's actually working in powershell as well
![Capture](https://github.com/npm/cli/assets/128291516/730e2a5b-eedf-4dca-aeae-1223da924602)

**Comment by ParamThakkar123** [comment]
try to upgrade your reinstall node and see if it's working

**Comment by ParamThakkar123** [comment]
![Capture1](https://github.com/npm/cli/assets/128291516/b9cc5deb-99e2-46d0-afee-ae6483aed7dd)

**Comment by andradei** [comment]
No dice. I'm avoiding developing on Windows. Linux or WSL are offering a better developer experience.
