### ISSUE TITLE
[BUG] VSCode does not provide suggestions/auto-complete for package installed as a dependency of another

### ISSUE THREAD

**Issue by paul-uz** [npm/cli#6713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I have my own "SDK" package which has a dependency of a popular ORM package.

I can installed my SDK package in a project, and I can import the ORM package and use it, however, autocomplete, and suggestions when i write a method belonging to the ORM hasn't yet been imported, simply do not work, unless I add the ORM package explicitly to my projects package.json, which seems a bit redundant?

Is there anything I can add to my project package.json file to get it working?

### Expected Behavior

Auto complete/suggestions for the ORM package methods works

### Environment

- npm: 9.5.1
- Node.js: 18.16.1
- OS Name: Mac OS

**Comment by ljharb** [comment]
Autocomplete is a function of your editor; npm doesn’t have anything to do with it.

**Comment by paul-uz** [comment]
> Autocomplete is a function of your editor; npm doesn’t have anything to do with it.

It clearly has some impact, as when the ORM package is added to the main package.json, autocomplete works.

**Comment by ljharb** [comment]
What's clear to me is that your editor's autocomplete is broken and is only looking at the top level of node_modules or is only looking at explicit deps.

You can test this by adding it to package.json and NOT running `npm install`, and restart your editor, and see if it picks up the autocompletions or not.

**Comment by milaninfy** [comment]
**Closing:** this looks to be a general support question which is outside the scope of the repo. For support please post your question to [github.community](https://github.community).
