### ISSUE TITLE
[DOCS] npx reports "high severity vulnerabilities" with an issue suggestion that is broken

### ISSUE THREAD

**Issue by gitcnd** [npm/cli#6718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Problem, not another kind of Docs Problem.

- [X] This is a CLI Docs Problem.

### Description of Problem

I ran "npx create-react-app myfirstreactapp" which installed "create-react-app@5.0.1" which says "6 high severity vulnerabilities" and that I need to do this:-

` To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
`

but both of those commands are broken for multiple reasons

`
[leo@v64 ~]$ npm audit 
npm ERR! code ENOLOCK
npm ERR! audit This command requires an existing lockfile.
npm ERR! audit Try creating one first with: npm i --package-lock-only
npm ERR! audit Original error: loadVirtual requires existing shrinkwrap file

npm ERR! A complete log of this run can be found in: /home/leo/.npm/_logs/2023-08-18T04_46_49_729Z-debug-0.log

[leo@v64 ~]$ npm i --package-lock-only
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/leo/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/leo/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in: /home/leo/.npm/_logs/2023-08-18T04_47_26_340Z-debug-0.log

[leo@v64 ~]$ npm audit
found 0 vulnerabilities

`

### Potential Solution

Probably someone knows what the reason is, and how to fix it - that knowledge should be ported into the doc

**Comment by gitcnd** [comment]
FYI - the "npx" github repo said this CLI repo is the one to post bugs into.  I'm not an expert at node

**Comment by ljharb** [comment]
CRA is deprecated and has tons of issues; this isn't an npm problem, but is definitely a reason to avoid CRA.
