### ISSUE TITLE
[BUG] Issue with Newly Published NPM Packages (invalid date)

### ISSUE THREAD

**Issue by Archer-Lotos** [npm/cli#6725]
Hello Team,

I am writing to report an issue we've noticed with newly published packages in the NPM registry. 

Whenever trying to locate these newly published packages using NPM's search functionality, they seem to be undetectable or they do not show up at all in the search results. This seems to happen irrespective of the relevance or specificity of the package names, or the filters applied.

This issue has been pervasive, and it is affecting all the new packages, impeding the discoverability of the new tools and libraries we contribute to the NPM ecosystem.

Here are the problems being faced:

1) Consistency: The issue presents consistently across all searches for newly released packages.

2) Delays: Even after the meaningful delay post-publication, new packages remain undiscoverable through search.

Having correct, timely, and reliable search functionality is critical for developers publishing their packages, making this a significant concern for the community.

We appreciate your attention to this matter and hope to see improvements in future iterations.

Thank you.

![image](https://github.com/npm/cli/assets/14317425/630035c5-9c7c-4a5f-9288-8a8a8e8979ca)

```[tasklist]
### Tasks
```

**Comment by milaninfy** [comment]
**Closing:** This appears to be fixed. If this issue persists feel free to raise it on registry support. 
For registry support please go to [npmjs.com/support](https://www.npmjs.com/support). If you believe this is a bug with the cli, please provide further clarifying details.
