### ISSUE TITLE
[BUG] (libnpmpublish) Publishing to private registry fails with EPUBLISHCONFLICT and @undefined version but it STILL ends up there with the right version

### ISSUE THREAD

**Issue by ep1kt3t0s** [npm/cli#6727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`npm publish` fails with `Error: Cannot publish @user/libs@undefined over existing version.` in the verbose logs.
The right version is in the package.json which does not exist in the upstream.

But the package ends up **published up there fine** with the right version when I go to the repo! I can install and use the package with its version fine.

I tried to update the version with npm version patch as well as manually. I've tried having a matching git tag with e.g. v1.2.2. I've put the correct version in package-lock.json as well as package.json.

I've deleted all the packages from the Github repo, let it have no packages and it is still the same.

Tried `npm cache clean --force`

I am on Node 18 but initially I tried with Node 20 with its latest NPM npm and result is the exact same.

### Expected Behavior

`npm publish` should succeed as the result of running the command succeeds.

### Steps To Reproduce

Create an empty private repo on Github.
Set up its credentials and `.npmrc` and try to `npm publish` there

Package.json I am using:

```
{
	"name": "@user/lib",
	"version": "1.2.2",
	"description": "",
	"main": "dist/index.js",
	"module": "esm/index.js",
	"types": "dist/types/index.d.ts",
	"scripts": {
		"build:cjs": "tsc --module CommonJS --outDir dist && cp -R src/styles dist/",
		"build:esm": "tsc --target ES2018 --outDir esm && cp -R src/styles esm/",
		"build": "rm -rf dist esm && npm run build:esm && npm run build:cjs",
		"prepublish": "npm run build",
		"publish": "npm publish",
	},
	"files": [
		"dist",
		"esm",
		"src"
	],
	"repository": "https://github.com/user/lib",
	"publishConfig": {
		"registry": "https://npm.pkg.github.com"
	},
```

### Environment

- npm: 9.8.1
- Node.js: 18.17.1
- OS Name: Darwin 22.6.0
- System Model Name: MacBook Air M2
- npm config:
```ini
; "user" config from /Users/user/.npmrc

@user:registry = "https://npm.pkg.github.com"
//npm.pkg.github.com/:_authToken = (protected)
fetch-retry-maxtimeout = 180000
fetch-retry-mintimeout = 30000

; "project" config from /Users/user/projects/lib/.npmrc

@NAMESPACE:registry = "https://npm.pkg.github.com"

; node bin location = /Users/user/.nvm/versions/node/v18.17.1/bin/node
; node version = v18.17.1
; npm local prefix = /Users/user/projects/lib
; npm version = 9.8.1
; cwd = /Users/user/projects/lib
; HOME = /Users/user
; Run `npm config ls -l` to show all defaults.

; "publishConfig" from /Users/user/projects/lib/package.json
; This set of config values will be used at publish-time.

registry = "https://npm.pkg.github.com"
```

**Comment by ep1kt3t0s** [comment]
Found it. This is caused because I had `"scripts": { "publish": "npm publish" } ` and running `npm publish` was causing it to be run twice... Just naming it to `publish2` made it succeed.

Could there be another bug here, if a script name matches a default npm command, it gets run twice, maybe even stuck in a loop?

**Comment by ep1kt3t0s** [comment]
There is also another bug about the `version` variable being undefined at the below lines but that is only in v9.8.1 and those codes seem removed from the `latest` branch already.
https://github.com/npm/cli/blob/facda25daab7cdd5f6aaad2260379aedeef33caa/workspaces/libnpmpublish/lib/publish.js#L208-L215

**Comment by milaninfy** [comment]
Closing. Based on this documentation the publish script is suppose to run. https://docs.npmjs.com/cli/v10/using-npm/scripts#npm-publish.
