### ISSUE TITLE
[BUG] run-script across workspaces doesn't fail when scripts are missing

### ISSUE THREAD

**Issue by Nokel81** [npm/cli#6733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Running `npm --workspaces run <script-name>` executes the script across all the workspaces and pipes the output to STDOUT and then exits with code 0.

It still exits with code 0 if one of the scripts is missing

### Expected Behavior

A non-zero exit code if one of the scripts is missing

### Environment

- npm: 9.8.0
- Node.js: v18.16.1
- OS Name: macOS
- npm config:
```ini
@ogre-tools:registry = "https://registry.npmjs.org/"
//cafile = "/Users/myname"
//npm.pkg.github.com/:_authToken = (protected)
description = true
registry = "https://registry.npmjs.org"
save-prefix = "^"
scope = "@nokel81"

disturl "https://electronjs.org/headers" = true
engine-strict = true
runtime "electron" = true
target "25.3.0" = true
```

**Comment by wraithgar** [comment]
The implicit "if-present" logic was removed in [npm@10](https://github.com/npm/cli/releases/tag/v10.0.0)

> npm no longer treats missing scripts as a special case in workspace mode. Use if-present to ignore missing scripts.


ref: https://github.com/npm/cli/commit/0318f442fe6c18275607a5d574c383f085484e6e

**Comment by Nokel81** [comment]
Cool thanks
