### ISSUE TITLE
[BUG] yarn.lock not included by `npm pack`

### ISSUE THREAD

**Issue by mdonnalley** [npm/cli#6738]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`npm pack` on a package that includes `yarn.lock` in `files` section of package.json does **not** include `yarn.lock` in the packaged tarball

```
npm notice
npm notice 📦  no-yarn-lock@1.0.0
npm notice === Tarball Contents ===
npm notice 0B   README.md
npm notice 0B   index.js
npm notice 336B package.json
npm notice === Tarball Details ===
npm notice name:          no-yarn-lock
npm notice version:       1.0.0
npm notice filename:      no-yarn-lock-1.0.0.tgz
npm notice package size:  345 B
npm notice unpacked size: 336 B
npm notice shasum:        c6509508fea1bdea7eefab41a0a45c464f35ae01
npm notice integrity:     sha512-oVxQ1UBiz8W2X[...]lFq+8bqqGZBcA==
npm notice total files:   3
npm notice
no-yarn-lock-1.0.0.tgz
```

### Expected Behavior

v8 allowed you to package the `yarn.lock` so I would expect the same in v9 - especially since I can't find anything in the announcement or docs that mention this breaking change. However, I could have missed it.

If yarn.lock is ignored by default now, it would be useful to have an option to include it. 

Our use case is that we have a plugin-based CLI framework ([oclif](https://github.com/oclif)) that allows users to install plugins from the npm registry. If the plugin ships with the `yarn.lock` we're able to use the locked dependencies during install which prevents various issues with dependencies suddenly breaking.

Our current workaround is to rename the `yarn.lock` during the release and then rename it before the plugin is installed. 

```
npm notice
npm notice 📦  no-yarn-lock@1.0.0
npm notice === Tarball Contents ===
npm notice 737B README.md
npm notice 0B   index.js
npm notice 336B package.json
npm notice 86B  yarn.lock
npm notice === Tarball Details ===
npm notice name:          no-yarn-lock
npm notice version:       1.0.0
npm notice filename:      no-yarn-lock-1.0.0.tgz
npm notice package size:  751 B
npm notice unpacked size: 1.2 kB
npm notice shasum:        6b2f5d255307e7b58779438ed4bc8336cd99b0ac
npm notice integrity:     sha512-BpBchI9L4COJ0[...]luEShMcFyglSw==
npm notice total files:   4
npm notice
no-yarn-lock-1.0.0.tgz
```

### Steps To Reproduce

Repro: https://github.com/mdonnalley/no-yarn-lock

`git clone https://github.com/mdonnalley/no-yarn-lock.git`

`cd no-yarn-lock && yarn`

`npm pack --dry-run`

on `npm v9.8.1` **yarn.lock not included**
```
npm notice
npm notice 📦  no-yarn-lock@1.0.0
npm notice === Tarball Contents ===
npm notice 0B   README.md
npm notice 0B   index.js
npm notice 336B package.json
npm notice === Tarball Details ===
npm notice name:          no-yarn-lock
npm notice version:       1.0.0
npm notice filename:      no-yarn-lock-1.0.0.tgz
npm notice package size:  345 B
npm notice unpacked size: 336 B
npm notice shasum:        c6509508fea1bdea7eefab41a0a45c464f35ae01
npm notice integrity:     sha512-oVxQ1UBiz8W2X[...]lFq+8bqqGZBcA==
npm notice total files:   3
npm notice
no-yarn-lock-1.0.0.tgz
```

on `npm v8.19.4` **yarn.lock included**

```
npm notice
npm notice 📦  no-yarn-lock@1.0.0
npm notice === Tarball Contents ===
npm notice 737B README.md
npm notice 0B   index.js
npm notice 336B package.json
npm notice 86B  yarn.lock
npm notice === Tarball Details ===
npm notice name:          no-yarn-lock
npm notice version:       1.0.0
npm notice filename:      no-yarn-lock-1.0.0.tgz
npm notice package size:  751 B
npm notice unpacked size: 1.2 kB
npm notice shasum:        6b2f5d255307e7b58779438ed4bc8336cd99b0ac
npm notice integrity:     sha512-BpBchI9L4COJ0[...]luEShMcFyglSw==
npm notice total files:   4
npm notice
no-yarn-lock-1.0.0.tgz
```

### Environment

- npm: 9.8.1
- Node.js: 18.15.0
- OS Name: macOs Ventura 13.5
- System Model Name: Macbook Pro
- npm config:
```ini
; "user" config from /Users/mdonnalley/.npmrc

//localhost:4873/:_authToken = (protected)
//registry.npmjs.org/:_authToken = (protected)
unsafe-perm = true

; node bin location = /Users/mdonnalley/.nvm/versions/node/v18.15.0/bin/node
; node version = v18.15.0
; npm local prefix = /Users/mdonnalley/repos/mdonnalley/no-yarn-lock
; npm version = 9.8.1
; cwd = /Users/mdonnalley/repos/mdonnalley/no-yarn-lock
; HOME = /Users/mdonnalley
; Run `npm config ls -l` to show all defaults.
```

**Comment by ljharb** [comment]
yarn.lock is a dev-only lockfile, just like package-lock.json - it’s not supposed to ever be used by a consumer, whether it’s published or not.

**Comment by mdonnalley** [comment]
@ljharb I understand that but I'm not aware of another way to handle our use case than to use lockfiles. 

Our CLI framework allows users to install plugins from the npm registry. If we don't respect a lock file during install then there's no way to ensure that the dependencies that get installed were the dependencies used during that plugin's test and release pipelines. For instance a plugin might have passed all it's tests and released using `foo-bar@1.0.0` but then foo-bar accidentally introduces a regression in `1.0.1` - without a lockfile users would get that broken version instead of the version used during testing.

Would love to hear an alternative approach if you have one

**Comment by ljharb** [comment]
Of course there is - npm-shrinkwrap.json. That’s the lockfile consumers obey.

of course, it’s insanely hostile to users to publish that, because users depend on behind able to get transitive updates freely flowing - iow, the thing you want is not your concern as the package publisher, that’s the concern of the end user only.

**Comment by mdonnalley** [comment]
>of course, it’s insanely hostile to users to publish that, because users depend on behind able to get transitive updates freely flowing - iow, the thing you want is not your concern as the package publisher, that’s the concern of the end user only.

I don't think I've done a good job explaining our use case. I'll give an example, the [Salesforce CLI](https://github.com/salesforcecli/cli) is built on top of our framework, oclif. That cli is executed millions of times a day an companies depend on it for their CI/CD processes and as such we must be able to ensure that the dependencies are stable. It's simply no acceptable for a transitive dependency to potentially break the CLI.

>Of course there is - npm-shrinkwrap.json. That’s the lockfile consumers obey.

Yes, this is a possibility. We're dealing with a situation where we use `npm` for packing but then we're using `yarn` for the plugin install in production. So we'd have to do some work to align those. 

At any rate, I want to hear from the npm team on this. Version 8 allowed you to pack `yarn.lock` but version 9 doesn't. I'd like to know if that was an intentional breaking change or if they're open to fixing it

**Comment by ljharb** [comment]
I believe yarn reads from npm-shrinkwrap; if not then it’s a major yarn bug.

I beliege it was an intentional change, but obv they can weigh in.

**Comment by strager** [comment]
A `yarn.lock` file is omitted from `npm pack`'s output even if I explicitly unignore it using `!/yarn.lock` in my `.npmignore` file. Is this intentional?

broken: 9.8.1
broken: 9.6.4
working: 8.1.2
working: 7.6.3

**Comment by ljharb** [comment]
Yes, because no yarn client will ever read it.

**Comment by wraithgar** [comment]
`yarn.lock` is treated like `package-lock.json` and is never included in a published package.  Those files are only used at the top level of a package.


https://classic.yarnpkg.com/blog/2016/11/24/lockfiles-for-all/

> When you publish a package that contains a yarn.lock, any user of that library will not be affected by it. When you install dependencies in your application or library, only your own yarn.lock file is respected. Lockfiles within your dependencies will be ignored.

**Comment by derHodrig** [comment]
But why do I get a `No lockfile found from [path to package in node-modules]` ? 
There is a new Nuxt 3 Feature, [Nuxt Layers](https://nuxt.com/docs/getting-started/layers)

Basically you create a webapp and publish as a npm package, which you install in your current App which extends from that app. But the issue is, while installing yarn recognize "[the package] must be built because it never has been before or the last one failed"
> So if build means I can do a prod build, the package can be build.
That phase will fail, because we cant publish yarn.lock anymore.

I use yarn 3.6.4 and i think it worked with 3.5.x
The node-linker is set to node-modules.
