### ISSUE TITLE
[BUG] Why is the package version in package.json file not updated when I use the command npm up

### ISSUE THREAD

**Issue by dong-lufei** [npm/cli#6739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I used the npm outdated command to check if there are any packages that need to be updated, and there are 7, so I ran it, and the npm up command was successful, but the package dependency version in package.json file doesn't seem to have changed

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:9.6.7
- Node.js:v18.17.1
- OS Name:win11
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by shadowspawn** [comment]
The `npm update` command will only update to the latest version compatible with what is in the `package.json`. 

For example, I have a project with this in the `package.json`:
```
  "dependencies": {
    "chalk": "^4.1.2",
```

`npm outdated` will show you newer versions that are available, including ones which won't be installed by `npm update`. The `wanted` column shows you what `npm update` will use, the `latest` column shows you even later versions.

```
% npm outdated
Package                            Current    Wanted  Latest  Location                                       Depended by
chalk                                4.1.2     4.1.2   5.3.0  node_modules/chalk                             forest-arborist
```

```
```

**Comment by wraithgar** [comment]
As @shadowspawn said, `npm update` does not change the package.json file.

https://docs.npmjs.com/cli/v9/commands/npm-update#description

> Note that by default npm update will not update the semver values of direct dependencies in your project package.json, if you want to also update values in package.json you can run: npm update --save (or add the save=true option to a [configuration file](https://docs.npmjs.com/cli/v9/configuring-npm/npmrc) to make that the default behavior).
