### ISSUE TITLE
[BUG] `npm stars` doesn't show any packages

### ISSUE THREAD

**Issue by ysh83737** [npm/cli#6740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

- using the official repository
- and i am logged in
- run `npm star vue` and this command has succeeded
- run `npm stars`, it doesn't show any packages. Tips are as follows: `npm WARN stars user has not starred any packages`

<img width="379" alt="image" src="https://github.com/npm/feedback/assets/32612643/255baddd-bfb0-4662-be3e-5d49f8350dc3">

### Expected Behavior

list my stared packages after I run the `npm stars` command.

### Steps To Reproduce

- using the official repository
- and i am logged in
- run `npm star vue`
- run `npm stars`

<img width="379" alt="image" src="https://github.com/npm/feedback/assets/32612643/255baddd-bfb0-4662-be3e-5d49f8350dc3">

### Environment

- npm: 9.8.0
- Node.js: 20.5.1
- OS Name: macOS Ventura 13.4.1
- System Model Name: Macbook Pro M1 chip
- npm config:
```ini
; "user" config from /Users/xxx/.npmrc

//registry.npmjs.org/:_authToken = (protected) 
registry = "https://registry.npmjs.org/" 

; node bin location = /Users/xxx/Library/pnpm/nodejs/20.5.1/bin/node
; node version = v20.5.1
; npm local prefix = /Users/xxx
; npm version = 9.8.0
; cwd = /Users/xxx
; HOME = /Users/xxx
; Run `npm config ls -l` to show all defaults.
```

**Comment by ysh83737** [comment]
This problem also occurs in v8.x/v6.x

**Comment by wraithgar** [comment]
This is in all likelihood a caching issue w/ the npm registry itself.  `npm stars` works in the npm cli

```sh
$ npm stars
lodash
~ $ npm --version
10.0.0
```
