### ISSUE TITLE
[DOCS] No docs published for v10

### ISSUE THREAD

**Issue by andrewrlee** [npm/cli#6754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Problem, not another kind of Docs Problem.

- [X] This is a CLI Docs Problem.

### Description of Problem

Hi,

It looks like v10 of the CLI has been released but I don't think a [changelog](https://docs.npmjs.com/cli/v9/using-npm/changelog?v=true) or other docs have been published? 

Thanks

### Affected URL

https://docs.npmjs.com/cli/v9/using-npm/changelog?v=true

**Comment by lukekarrys** [comment]
Docs for npm 10 (https://docs.npmjs.com/cli/v10) are now published after this commit: https://github.com/npm/documentation/commit/a0c1dc34ef9453ffa9dac2107c46f0b245a47b75
