### ISSUE TITLE
[BUG] Wrong tag mentioned in publish log when publishing a prerelease

### ISSUE THREAD

**Issue by jussirantala** [npm/cli#6774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

If you publish a prelease version, the tag is not "latest" by default like you can see here: https://github.com/npm/cli/blob/latest/scripts/publish.js

But for the log output [you get default tag from npm config](https://github.com/npm/cli/blob/d0b7899e6ea6e2b699adfc3f39b572f1f1f04c5b/lib/commands/publish.js) and it's "latest". 

So it's saying that the prerelease was published with "latest" tag even though it was not.

### Expected Behavior

Correct tag is mentioned in log output and [documentation](https://docs.npmjs.com/cli/v8/commands/npm-publish#tag) is updated about this.

**Comment by wraithgar** [comment]
That is the script that npm uses to publish itself, it's not used during `npm publish` when folks type it normally.  npm uses the `distTag` config when publishing unless told to otherwise.

**Comment by jussirantala** [comment]
Okay, well I thought that's the reason why `latest` tag was not used for my prereleases. I don't know why it's happening then 🤔 The log output says "latest" tag was used but nope.
