### ISSUE TITLE
[BUG] npm v6 does not install on nodejs v6

### ISSUE THREAD

**Issue by legobeat** [npm/cli#6788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```
~ $ npm i -g npm@6
/home/node/npm/lib
`-- (empty)

npm ERR! Linux 6.x.x
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-g" "npm@6"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! path /home/node/npm/lib/node_modules/.staging/@iarna/cli-f250681c
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/home/node/npm/lib/node_modules/.staging/@iarna/cli-f250681c' -> '/home/node/npm/lib/node_modules/npm/node_modules/@iarna/cli'
npm ERR! enoent ENOENT: no such file or directory, rename '/home/node/npm/lib/node_modules/.staging/@iarna/cli-f250681c' -> '/home/node/npm/lib/node_modules/npm/node_modules/@iarna/cli'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /home/node/npm-debug.log
npm ERR! code 1
``` 

File `/home/node/npm-debug.log` does not exist after command exit.

`npm i -g npm@6.14.17` does install as expected so this was introduced in latest release `6.14.18`.

### Expected Behavior

`npm i -g npm@6` installs latest release of NPM v6.x without errors when executed on Node.js v6.

### Steps To Reproduce

1. Tried from nvm on Fedora 37, `node:6-alpine` and `node:6-jessie` Docker images
2. `echo 'prefix=/home/node/npm' >> /home/node/.npmrc`
3. `npm i -g npm@6`

### Environment

- npm: 3.10.10 / 6.14.18
- Node.js: 6.17.1
- OS Name: Linux
- npm config:
```ini
; cli configs
user-agent = "npm/3.10.10 node/v6.17.1 linux x64"
prefix = "/home/node/npm"

; node bin location = /usr/local/bin/node
; cwd = /home/node
; HOME = /home/node
```

**Comment by legobeat** [comment]
Seems relevant: `@iarna/cli` was updated from `^1.2.0` to `^2.1.0` through the `lock-verify@2.2.2` bump in d3e7eed13a1109d7760e62bca639ed3ef64a0bd3.

**Comment by ljharb** [comment]
This is because npm 3 can’t handle scoped bundled packages. It’s definitely a bug.

With nvm, you can run `nvm install-latest-npm` and it will handle the proper hops, and stop at the latest version that works.

**Comment by wraithgar** [comment]
This is not something that is going to be fixed, npm 3 is not being updated.

We have an install self-bootstrapping install script that can be used to install npm globally without needing npm.  You can set the `npm_install` environment variable to tell it what version to install (it defaults to latest).  It requires `curl` and `tar`.


```sh
npm_install=6.14.16 curl -s https://www.npmjs.com/install.sh|sh
```

**Comment by legobeat** [comment]
Appreciate the pointers, thank you! If there is at any point a future release of npm v6, maybe a line or two in the readme/chengelog/release notes could be nice to point people in the right direction? I imagine a large portion of npm v6 installs are for older legacy node releases.

**Comment by ljharb** [comment]
@wraithgar yes but npm 6 could stop bundling a scoped module, if any future backports are coming.
