### ISSUE TITLE
[BUG] npm should use PowerShell by default on Windows

### ISSUE THREAD

**Issue by Stanzilla** [npm/cli#6789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

The problem here is that cmd does not work with a few things that are now part of a Windows developer's daily workflow, like using WSL and it's network shared file system. cmd does not understand UNC file paths and therefore npm is broken by default when you first try to use it. Yes the default shell and default script shell can be changed but there is no reason why the default should still be cmd in the first place, imo.

There were recent changes in that [PR](https://github.com/npm/cli/pull/6548) that made npm work with PowerShell so I once again want to ask if it can now be made default. npm is a Microsoft product, cmd is the past, PowerShell is the future in the Windows ecosystem, you guys need to properly support and embrace it.

Answer: npm on Windows uses the old cmd instead of PowerShell

### Expected Behavior

npm should use PowerShell by default

### Steps To Reproduce

- run npm install on a UNC share

### Environment

- npm: 10.1.0
- Node.js: 20.6.1
- OS Name: Windows 11 22631.2271
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by lukekarrys** [comment]
npm now ships powershell scripts that will be installed by the default nodejs windows installer https://github.com/nodejs/node/pull/52009

I don't believe there is anything else that npm can do to make this the default. the npm/npx powershell scripts will be in place for future installs of nodejs which is all npm and node can do.

i'm not an expert in windows development so feel free to reopen if i am incorrect about any of the above details.
