### ISSUE TITLE
[BUG] Bad Request error on upgrade of npm

### ISSUE THREAD

**Issue by humpy125** [npm/cli#6797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Current configuration is node 20.5.0 and npm 9.8.1
I upgraded npm when a message in the cli indicated v10.0.0 of npm was available.

After upgrading npm from 9.8.1 to 10.0.0 npm would fail with  400 bad request error
I am behind a firewall and set the proxy and https-proxy configuration.
Running the command:
       npm install -g npm 
fails with this error.

I have tried installing node 18.17.0 with the same result.

I removed the c:\npm installation and reinstalled the node 20.5.0 package and npm is now at 9.8.1 and working again

### Expected Behavior

npm v10.0.0 should download packages from the registry

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run 'npm install -g npm '
4. See error 400 Bad Request

### Environment

- npm: 10.0.0
- Node.js: 20.5.0
- OS Name: Windows Server 2016 Standard
- System Model Name:
- npm config:
; "builtin" config from C:\Program Files\nodejs\node_modules\npm\npmrc
; prefix = "C:\\Users\\sastw\\AppData\\Roaming\\npm" ; overridden by user
; "user" config from C:\Users\sastw\.npmrc
https-proxy = "http://<myproxy>:8080"
prefix = "c:\\npm"
proxy = "http://<myproxy>:8080"
registry = "https://registry.npmjs.org/"

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v20.6.1
; npm local prefix = D:\applications\node_apps
; npm version = 9.8.1
; cwd = D:\applications\node_apps
; HOME = C:\Users\sastw
; Run `npm config ls -l` to show all defaults.
```

**Comment by lukekarrys** [comment]
This issue should be fixed in v10.1.0. Can you try updating to that and see if the issue persists?

**Comment by humpy125** [comment]
The new version has fixed this issue. Thanks for the quick response
