### ISSUE TITLE
[BUG] `npm start` updates cache from custom registry

### ISSUE THREAD

**Issue by gmichalec-pandora** [npm/cli#6799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

It seems that, when you have a custom registry defined, running `npm start` causes npm to make requests to that registry to update its cache.
Here's a very simple docker container showing the behavior:
```
FROM node:20
RUN echo "{}" > package.json
RUN echo "setTimeout(() => { process.exit(0); }, 60000);" > server.js
RUN echo registry = https://sonatype3.savagebeast.com/repository/npm-all/ > /usr/local/etc/npmrc

CMD ["npm", "start",  "--loglevel",  "verbose"]
```
I build and run it like so:
`docker build -t test -f ./Dockerfile.test . && docker run -ti test`

running `docker stats` I see this:
```
CONTAINER ID   NAME             CPU %     MEM USAGE / LIMIT     MEM %     NET I/O          BLOCK I/O         PIDS
41aba3e6b052   serene_noether   0.00%     268.3MiB / 15.37GiB   1.70%     44.7MB / 860kB   16.4kB / 26.3MB   26
```
and the logs report 
```
npm http fetch GET 200 https://sonatype3.savagebeast.com/repository/npm-all/npm 16954ms (cache miss)
npm http fetch GET 200 https://sonatype3.savagebeast.com/repository/npm-all/npm 17329ms (cache miss)
```

If I comment out the `echo registry` line in the dockerfile, then `docker stats` reports this:
```
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O        PIDS
2c1c2f6b3800   boring_wiles   0.00%     41.45MiB / 15.37GiB   0.26%     4.37MB / 17.9kB   508kB / 2.17MB   26
```
and the logs show 
```
npm http fetch GET 200 https://registry.npmjs.org/npm 483ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/npm 520ms (cache miss)
```

If I change the CMD to `CMD ["node", "server.js",  "--loglevel",  "verbose"]` (skipping npm entirely), then `docker stats` shows
```
CONTAINER ID   NAME                CPU %     MEM USAGE / LIMIT     MEM %     NET I/O      BLOCK I/O    PIDS
6ef158d99f4e   quizzical_lamport   0.00%     7.297MiB / 15.37GiB   0.05%     5.4kB / 0B   131kB / 0B   10
```

The primary issue for me is that the cache update process causes the application's memory to balloon. If I leave the app running, the memory is GC'd, but this is an issue in a containerized environment where one has to provision this extra memory to avoid an OOM kill. It's also causing unnecessary CPU and bandwidth usage, which could be a problem at scale.

### Expected Behavior

Running scripts such as `npm start` or `npm run x` that do not inherently interact with package dependencies should not attempt to do any cache updating. I can't think of a reason why this would be useful or necessary.

If this behavior is intentional, it should at least be documented - I could find no mention in the documentation of when/why npm would be pulling these caches.

### Steps To Reproduce

see docker example above

### Environment

- npm: 9.8.1
- Node.js: v20.6.1
- OS Name: Debian 12 (bookworm)
- System Model Name: Docker container
- npm config:
```ini
; node bin location = /usr/local/bin/node
; node version = v20.6.1
; npm local prefix = /
; npm version = 9.8.1
; cwd = /
; HOME = /root
; Run `npm config ls -l` to show all defaults.```

**Comment by milaninfy** [comment]
npm is checking version update notification, whether newer version of npm is available. that's why it's showing those two log lines. if you don't want to have those update check use `--update-notifier` flag [update-notifier](https://docs.npmjs.com/cli/v10/using-npm/config#update-notifier). 
This is does not seem a bug with npm.
