### ISSUE TITLE
[BUG] npx doesn't pull updates for the major version (even with --prefer-online)

### ISSUE THREAD

**Issue by vvscode** [npm/cli#6804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

For experiments, I created a package `@vvscode/fake-cli`

I'm aiming to run the latest version of the binary from the concrete major version. For that I do use

```
npx "@vvscode/fake-cli@0.*"
```
on initial run it used version `0.0.4`

After that I do release version `0.0.5` and I do expect to get this version. But I don't. As clearing the cache is not an option for me (I'm trying to create a command to provide to the end-user) I tried

```
npx "@vvscode/fake-cli@0.*" --prefer-online
```

but it also doesn't fetch the version

```
npx "@vvscode/fake-cli@0.*" --prefer-online 
# 0.0.4

# release 0.0.5

npx "@vvscode/fake-cli@0.*" --prefer-online
# gives 0.0.4
```

### Expected Behavior

I do expect to have a way to run the latest version of package from the major release.

I do expect `--prefer-online` flag forces checking a new version. So in the case it should be

```
npx "@vvscode/fake-cli@0.*" --prefer-online 
# 0.0.4

# release 0.0.5

npx "@vvscode/fake-cli@0.*" --prefer-online
# expect 0.0.5
```

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 10.1.0 (same on 9.8.0)
- Node.js: 20.5.1
- OS Name: MacOS Ventura 13.3
- System Model Name: Macbook Air
- npm config:
```ini
; copy and paste output from `npm config ls` here
; "builtin" config from /opt/homebrew/lib/node_modules/npm/npmrc

prefix = "/opt/homebrew"

; node bin location = /opt/homebrew/Cellar/node/20.5.1/bin/node
; node version = v20.5.1
; npm local prefix = /Users/vvscode/repo
; npm version = 10.1.0
; cwd = /Users/vvscode/repo
; HOME = /Users/vvscode
; Run `npm config ls -l` to show all defaults.
```

**Comment by vvscode** [comment]
I tried 

```
npx @vvscode/fake-cli@~0.0.4 --prefer-online
```

and 

```
npx @vvscode/fake-cli@^0.0.4 --prefer-online
```

and

```
npx @vvscode/fake-cli@0 --prefer-online
```

as well

**Comment by vvscode** [comment]
Just to add - looks like using `@latest` fetches the latest version any way. But why this solution does not satisfy me - it allows major updates (this is what I'm trying to avoid)

in code workaround might look like 

```bash
#!/bin/bash

# Store all arguments in the 'args' variable
args=("$@")

# Package name
package_name="@xxx/yyy"

# Major version of the package (default is 14)
major_version=14

# Check if there is an argument for the major version and set it
if [ ! -z "$1" ]; then
  major_version="$1"
  shift
fi

# Get the latest minor version of the package
latest_minor_version=$(npm show "$package_name@$major_version" version --json | awk -F. '{print $1"."$2}' | sort -V | tail -n 1)

# Formulate the command to execute
command_to_execute="npx $package_name@$latest_minor_version ${args[@]}"

# Display the command before executing it
echo "Executing command: $command_to_execute"

# Execute the command
eval "$command_to_execute"

```

**Comment by milaninfy** [comment]
@vvscode I tried using 10.8.2. I got these results. 
Can you try replicating this problem on the latest version of `npm`? (ie. `npm i -g npm`)  

```bash
~ $ npx @vvscode/fake-cli@~0.0.4 --prefer-online
Need to install the following packages:
@vvscode/fake-cli@0.0.10
Ok to proceed? (y) y

Hello from @vvscode/fake-cli@0.0.10!
~ $ npx @vvscode/fake-cli@0.0.4 --prefer-online 
Need to install the following packages:
@vvscode/fake-cli@0.0.4
Ok to proceed? (y) y

Hello from @vvscode/fake-cli@0.0.4!
~ $ npx @vvscode/fake-cli@0 --prefer-online 
Need to install the following packages:
@vvscode/fake-cli@0.0.10
Ok to proceed? (y) y

Hello from @vvscode/fake-cli@0.0.10!
~ $ npx "@vvscode/fake-cli@0.*" --prefer-online 

Need to install the following packages:
@vvscode/fake-cli@0.0.10
Ok to proceed? (y) y

```

**Comment by vvscode** [comment]
Hey, @milaninfy 
thanks, not it looks like a valid behavior 

Thanks
