### ISSUE TITLE
error when installing npm on a ccu3

### ISSUE THREAD

**Issue by averlon** [npm/cli#6810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`curl -qL https://www.npmjs.com/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3755  100  3755    0     0  18406      0 --:--:-- --:--:-- --:--:-- 18497
fetching: https://registry.npmjs.org/npm/-/npm-10.1.0.tgz
removing existing npm
/tmp/npm.5571/package/lib/es6/validate-engines.js:31
    throw err
    ^

Error: Cannot find module 'timers/promises'
`

### Steps To Reproduce

1. In this environment... running on a CCU§
3. With this config... curl -qL https://www.npmjs.com/install.sh | sh
4. Run '...'
5. See error...

### Environment

- npm: is not working anymore!
- Node.js: v8.11.4
- OS Name: Linux f42240c3 4.14.34 #1 SMP PREEMPT Wed Jul 19 18:21:15 CEST 2023 armv7l GNU/Linux
- System Model Name:
- npm config: O.K. - after reboot of the device I can get some output:
```
npm config ls
npm WARN npm npm does not support Node.js v14.16.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/5.6.0 node/v14.16.0 linux arm"

; globalconfig /usr/local/addons/redmatic/etc/npmrc
cache = "/usr/local/addons/redmatic/var/npm-cache"
prefix = "/usr/local/addons/redmatic"

; node bin location = /usr/local/addons/redmatic/bin/node
; cwd = /usr/local/addons/redmatic
; HOME = /usr/local/addons/redmatic/home
; "npm config ls -l" to show all defaults.
```
```ini
; copy and paste output from `npm config ls` here
```

**Comment by ljharb** [comment]
That implies you have too old a version of node.

Also what’s a ccu?

**Comment by averlon** [comment]
CCU3 = Homematic IP Controller. I assume based on Raspberry but with some very specific setup!

Any Idea how I could deinstall the current version?

**Comment by ljharb** [comment]
Please fill out the “environment” section in the template.

**Comment by averlon** [comment]
most of that is unknown to me - but I will try! and npm config ls will not work anymore!

**Comment by ljharb** [comment]
node 8 is the problem; the oldest version of node that’s still supported is 18, and node 8 has been EOL for many years.

**Comment by averlon** [comment]
any idea how I could update?

**Comment by averlon** [comment]
since npm is back working again - to some extend - I will stay with this. I only use npm to install or upgrade node red. All other updates are done via propriatary procedures of Homematic IP.
Thanks for help!
