### ISSUE TITLE
[BUG] Support dollar notation also for peerDependencies

### ISSUE THREAD

**Issue by orgads** [npm/cli#6818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`overrides` supports dollar notation that translates to "same version as I depend upon". For example:
```json
{
  "dependencies": {
    "mongodb": "5.9.0"
  },
  "overrides": {
    "mongodb": "$mongodb"
  }
}
```

This is very useful. When I updated the dependency, I don't need to update the override as well.

What i miss is a similar feature for `peerDependencies`. In my project, I have a dependency, which I require my dependents to have a matching version, but I have to update it in both places on version upgrades.

```json
  "dependencies": {
    "@nestjs/common": "^10.2.1"
  },
  "peerDependencies": {
    "@nestjs/common": "^10.2.1" // <-- Would be nice to support $@nestjs/common here
  }
}
```

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 9.8.0
- Node.js: 18.17.1
- OS Name: Windows

**Comment by wraithgar** [comment]
This would break a lot of clients out there that don't understand this notation, including every version of npm that's currently in use.

New features like this are best discussed at https://github.com/npm/rfcs
