### ISSUE TITLE
npm v6 uninstalling the older version globally when newer version installation fails

### ISSUE THREAD

**Issue by Tej81r** [npm/cli#6822]
**Current Behavior**:

I installed the most recent version of my Node JS project on top of the older one without uninstalling it.
In the latest release, I added a preinstall script that verifies the local Node version and aborts the installation if it does not match.
Note: Installing my Node JS project globally every time

I see the process happening here is

loadIdealTree
Uninstalling the previous version of my project
```
npm timing action: extract Completed in 712ms
npm info lifecycle olevel@2.2.1~preuninstall: olevel@2.2.1
npm info lifecycle oleveli@2.2.1~uninstall: olevel@2.2.1
npm verb unbuild rmStuff olevel@2.2.1 from /Users/user1/.nvm/versions/node/v12.22.1/lib/node_modules
```
It starts installing the new version after uninstalling the older one globally.
The latest version requires Node 18; however, because I did not update the Node version to 18, my local installation will fail.

Now, the installation of a newer version on my local machine has failed, and the earlier version was removed before installing the newer version, therefore I do not have the version on my machine.

There is no rollback mechanism here. Could you please tell me what steps I'm missing or if this is expected behaviour?

preinstall script:

```
  try {
   nodeversionCheck();
  } catch (err) {
    throw new Error(err);
  }
```

**Expected Behavior:**

When the installation of the newer version fails due to the preinstall script, the previous version should not be deleted globally in the system.

node version - 12.22.1
npm version  -  6.14.2

**Comment by Tej81r** [comment]
This behaviour is not present from npm v7. Why it is removing the older version in npm v6. 
Is there any specific reason why it is removing the older version in npm v6 and not in a version more than v7?

**Comment by wraithgar** [comment]
This looks like an issue w/ npm 6 which is not supported.
