### ISSUE TITLE
[BUG] installation fails without a message 

### ISSUE THREAD

**Issue by rejetto** [npm/cli#6827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

tried version 9.8.1, 9.6.7 and some others.
`npx -y hfs@latest` (or 0.48.2 in place of latest)
will act like installing, but then exit without printing any message before running the program, and leaving an empty folder in its cache. Empty folder = the download didn't terminate correctly.

Apparently the problem is solely related to the download phase, as if npm9 finds the package in the cache, it will just run correctly.

Updating to npm 10 solves the issue, but i'd like to know what it is, so that i can try to work around the problem and be compatible with node 18 LTS without requiring my users to update manually npm.

https://github.com/npm/cli/assets/1367199/7c6af8f1-43bb-4379-af42-3b5638578d0d

### Expected Behavior

package "hfs" should be downloaded and executed

### Steps To Reproduce

1. be sure you don't have "hfs@0.48.2" in your cache
2. npx -y hfs@0.48.2

### Environment

- npm: 9.8.1
- Node.js: 18.17.1
- OS Name: macos 13 and Windows 11

**Comment by rejetto** [comment]
i've found that the problem is triggered by this dependency
>    "nat-upnp": "github:kaden-sharpin/node-nat-upnp",

I'm going to see if I can find a simple work around, and as last attempt I will publish that package (not mine) on npm registry myself.

**Comment by ljharb** [comment]
That’s a package on github, not a registry.

**Comment by rejetto** [comment]
yeah, i know, and it's not currently on npmjs.com, that's why i'm including from github.
but this is causing the problem with npm 9 (not with 10).
publishing it on npmjs.com will hopefully work around the problem without having to require npm 10.

**Comment by ljharb** [comment]
ah, i see, because it’s a fork. Then yes, you should publish it - probably under a scope.

**Comment by rejetto** [comment]
i've found that the same package is already available on npmjs under the name "nat-upnp-ts".
Using it, as expected, is working around the problem.
It's good enough for me, so I guess I won't investigate anymore.
I just took a note to not use this feature with version 9 🙃

**Comment by milaninfy** [comment]
Woking as expected on 10.8.1. Please update npm to latest. 
```sh
~ $ npx -y hfs@0.48.2
npm warn deprecated @koa/router@10.1.1: **IMPORTANT 10x+ PERFORMANCE UPGRADE**: Please upgrade to v12.0.1+ as we have fixed an issue with debuglog causing 10x slower router benchmark performance, see https://github.com/koajs/router/pull/173
HFS ~ HTTP File Server - Copyright 2021-2023, Massimo Melina <a@rejetto.com>
License https://www.gnu.org/licenses/gpl-3.0.txt
started 2024-07-12, 4:09:52 p.m. 
version 0.48.2
build 2023-09-20T22:00:36.550Z
pid 72746
cwd /Users/milaninfy/.hfs
node v22.2.0
config config.yaml
No config file, using defaults
HINT: type "help" for help
http serving on any network : 80
loading plugin antibrute
serving on http://10.189.161.10
serving on http://[fe80::bcd0:74ff:fe30:c8b6]

```
