### ISSUE TITLE
Audit API lockfileVersion 3

### ISSUE THREAD

**Issue by 0x8B41L3Y** [npm/cli#6840]
Hello!

I'm using the npm audit API to check for security issues in my project, and I'm not using the npm command-line tool for this. Instead, I have code that sends a POST request to the npm audit endpoint(https://registry.npmjs.org/-/npm/v1/security/audits).

To get results, I used to create a "requires" object with package names and versions, add it to my package-lock.json file, and then send this file to the endpoint. But things changed when I upgraded my project from Node.js version 14 to version 18, which also meant switching from lockfileVersion 1 to lockfileVersion 3. Unfortunately, my old method with the "requires" object no longer works because of changes in the package-lock.json structure.

I came across the documentation mentioning a new Bulk Advisory Endpoint for the latest npm versions. However, I couldn't find clear instructions on how to send data to this endpoint. When I use the npm command-line tool, the JSON payload is automatically generated for me. But in my case, I have to create it manually since I'm making the POST request on my own.

Could you please help me understand how to adjust the JSON payload I send to the npm audit endpoint to work with lockfileVersion 3 and get information about vulnerabilities?

Thank you!

BR
Bernhard

**Comment by wraithgar** [comment]
Unfortunately we don't have this documented.  The best "docs" are the tests right now.

https://github.com/npm/cli/blob/0f7008851f1c250405e8dc326f15d535e8fc1eae/test/lib/commands/audit.js#L82-L86

As you can see here, it's a JSON object indexed by package names, with the attributes being arrays containing every version of that package found in the tree.

The response is a JSON object indexed by package name, with the attributes being an array of advisories.
