### ISSUE TITLE
[BUG] `engines` in `package.json` doesn't work

### ISSUE THREAD

**Issue by babakfp** [npm/cli#6845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

![Screenshot 2023-09-28 102512](https://github.com/npm/cli/assets/44144724/e15a7dbc-0545-43d4-a30f-bf8719cac7f8)

### Expected Behavior

To throw error emiditly after runing any npm commands. This this what is expected only if `engine-strict=true` is used inside of `.npmrc` file.

### Steps To Reproduce

1. Add the `engines` object to `package.json`
2. Add the config the `.npmrc`
3. Run `npm i`
4. See that it continues to install instead of failing!

```
"engines": {
  "node": ">= 20.6.1",
  "pnpm": ">= 8.6.12",
  "npm": "please-use-pnpm",
  "yarn": "please-use-pnpm"
},
```

### Environment

- npm: 10.1.0
- Node.js: 20.6.1
- OS Name: Windows
- System Model Name: Asus VivoBook
- npm config:
```ini
; "user" config from C:\Users\babak\.npmrc

//registry.npmjs.org/:_authToken = (protected) 
fetch-retry-mintimeout = 20000 
save-exact = true 
save-prefix = "" 

; "project" config from C:\Users\babak\OneDrive\Desktop\resume-builder\.npmrc

engine-strict = true

; node bin location = C:\Users\babak\AppData\Local\Volta\tools\image\node\20.6.1\node.exe
; node version = v20.6.1
; npm local prefix = C:\Users\babak\OneDrive\Desktop\resume-builder
; npm version = 10.1.0
; cwd = C:\Users\babak\OneDrive\Desktop\resume-builder
; HOME = C:\Users\babak
; Run `npm config ls -l` to show all defaults.
```

**Comment by ljharb** [comment]
I don’t think this is how engines are expected to work. It’d be a warning, at best.

**Comment by babakfp** [comment]
> I don’t think this is how engines are expected to work. It’d be a warning, at best.

I updated it to:

> To throw error emiditly after runing any npm commands. This this what is expected only if `engine-strict=true` is used inside of `.npmrc` file.

**Comment by lukekarrys** [comment]
@babakfp Thanks for filing this! This is currently working as intended, and would be best suited as [an RRFC](https://github.com/npm/rfcs/issues/new?assignees=&labels=&template=rrfc.md&title=%5BRRFC%5D+%3Ctitle%3E)

Can you create [an RRFC](https://github.com/npm/rfcs/issues/new?assignees=&labels=&template=rrfc.md&title=%5BRRFC%5D+%3Ctitle%3E) in that rep with some details on how you would like to see this changed?
