### ISSUE TITLE
Node.js module changes

### ISSUE THREAD

**Issue by benjamingr** [npm/cli#6855]
Hey,

Node.js is debating some changes with regards to modules and we'd like your help.

The changes are outlined here: https://github.com/nodejs/TSC/issues/1445#issue-1920522548
The migration path for package authors is outlined here: https://github.com/nodejs/TSC/issues/1445#issuecomment-1742116718

What we'd hopefully like is:
 - For `npm publish` to warn if the published `package.json` file does not have a `"type"` field.
 - For `npm init` to set `"type": "module"` in "new" Node.js by default.

This is still all in discussion in Node.js, the above list is just some ideas and this issue is mostly so we can discuss things.

**Comment by wraithgar** [comment]
This is best discussed in https://github.com/npm/rfcs

**Comment by GeoffreyBooth** [comment]
@wraithgar This landed in Node and was released in 21.1.0:

- https://github.com/nodejs/node/pull/50096

[We hope to make this enabled by default, without requiring a flag, in a future version of Node](https://nodejs.org/en/blog/release/v21.1.0#:~:text=We%20hope%20to%20make%20detection%20enabled%20by%20default%20in%20a%20future%20version%20of%20Node.js.%20Detection%20increases%20startup%20time%2C%20so%20we%20encourage%20everyone%20%E2%80%94%20especially%20package%20authors%20%E2%80%94%20to%20add%20a%20type%20field%20to%20package.json%2C%20even%20for%20the%20default%20%22type%22%3A%20%22commonjs%22.) (potentially as soon as Node 22 in April 2024). This will mean that any Node app and dependency without a `package.json` `type` field will have a slower startup time. Therefore we would appreciate any help that `npm` can provide in ensuring that both application developers and library authors add a `type` field to every `package.json` file, even if it’s just making explicit the default `"type": "commonjs"`. I agree with @benjamingr’s suggested improvements [above](https://github.com/npm/cli/issues/6855#issue-1920829876).

> This is best discussed in [npm/rfcs](https://github.com/npm/rfcs)

https://github.com/npm/rfcs/issues/620 is already open, which suggests one of these changes. Perhaps now that this performance penalty to `type`-less packages is potentially coming to Node, it might be timely to act on that proposal?

**Comment by wraithgar** [comment]
We can get this into the `init-package-json` roadmap but there is no way to edit any already published package so the vast majority of packages in the ecosystem just got slower load times.

**Comment by GeoffreyBooth** [comment]
More specifically, packages that don't currently include a `type` field or use `.mjs`/`.cjs` get slightly lower load times. Which is many of them, for sure; but all they need to do is add `"type": "commonjs"` and the penalty disappears. Yes this doesn't help unmaintained packages or transitive dependencies of old packages, etc, but that's the trade-off we've chosen.

**Comment by ljharb** [comment]
… which is the vast majority of packages, for the foreseeable future.

**Comment by GeoffreyBooth** [comment]
@wraithgar FYI this has been backported and released in Node 20.10.0: https://nodejs.org/en/blog/release/v20.10.0
