### ISSUE TITLE
[BUG] authentication failure when using git dependency, project .npmrc and private npm registry

### ISSUE THREAD

**Issue by TheJefe** [npm/cli#6857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

E401 error when trying to install npm dependencies from git, with a project specific .npmrc  private registry definition.
To reproduce, you must have a `~/.npmrc` with a private registry configured. If you move that configuration to the root of a project, and then try to install a git dependency, you'll get a E401 authentication error for npmjs. Copying or moving this exact .nprc file to the user home directory (`~/.npmrc`) will make this issue go away.  Detailed reproduction steps are below with changes to the .npmrc file commented out to protect a user from copying and pasting this unknowingly.

### Expected Behavior

The expectation is that git dependencies should be installable with a project specific .npmrc file definition

### Steps To Reproduce

prerequisite, you have a private registry configured in an `.npmrc` file
should look similar to this..
```
//<redacted>.jfrog.io/<redacted>/api/npm/npm/:_auth=<redacted>
always-auth=true
email=<redacted>
registry=https://<redacted>.jfrog.io/<redacted>/api/npm/npm/
```

```sh
$ mkdir test
$ cd test

# next step commented out because it will break your local configuration until you reverse it
# mv ~/.nprmrc  .

$ npm install v8-profiler-next@git+ssh://git@github.com:hyj1991/v8-profiler-next.git
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /Users/jeff/.asdf/installs/nodejs/18.17.1/bin/node /Users/jeff/.asdf/installs/nodejs/18.17.1/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/Users/jeff/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code E401
npm ERR! npm ERR! Incorrect or missing password.
npm ERR! npm ERR! If you were trying to login, change your password, create an
npm ERR! npm ERR! authentication token or enable two-factor authentication then
npm ERR! npm ERR! that means you likely typed your password in incorrectly.
npm ERR! npm ERR! Please try again, or recover your password at:
npm ERR! npm ERR!     https://www.npmjs.com/forgot
npm ERR! npm ERR!
npm ERR! npm ERR! If you were doing some other operation then your saved credentials are
npm ERR! npm ERR! probably out of date. To correct this please try logging in again with:
npm ERR! npm ERR!     npm login

# next line commented out because it can break your local configuration if you aren't careful 
# mv .npmrc ~/.npmrc

$ npm install v8-profiler-next@git+ssh://git@github.com:hyj1991/v8-profiler-next.git
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs

added 109 packages, and audited 110 packages in 11s

found 0 vulnerabilities

```

### Environment

- npm: 9.6.7
- Node.js: v18.17.1
- OS Name: MacOS 14
- System Model Name:
- npm config:
```ini
; "project" config from /Users/jeff/test/.npmrc

//<redacted>.jfrog.io/<redacted>/api/npm/npm/:_auth = (protected)
always-auth = true
email = <redactec>
registry = "https://<redacted>.jfrog.io/<redacted>/api/npm/npm/"

; node bin location = /Users/jeff/.asdf/installs/nodejs/18.17.1/bin/node
; node version = v18.17.1
; npm local prefix = /Users/jeff/test
; npm version = 9.6.7
; cwd = /Users/jeff/test
; HOME = /Users/jeff
; Run `npm config ls -l` to show all defaults.

```

**Comment by kchindam-infy** [comment]
Hi @TheJefe  Could you confirm the following 
that private registry url is accessible without any network restrictions?
Do you have any npm related environment variables set like NM_CONFIG_REGISTRY or NPM_TOKEN?
Could you run the command with --verbose and share the npm logs?

**Comment by milaninfy** [comment]
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.
