### ISSUE TITLE
`npm query` exit status

### ISSUE THREAD

**Issue by wojpawlik** [npm/cli#6872]
When nothing matches, `npm query` should exit with code 1 (like `grep`), to simplify scripting:

```sh
! npm query '#ts-morph:outdated(major)' >/dev/null
# instead of
npm outdated ts-morph --json | jq --exit-status '."ts-morph" | .latest == .wanted' >/dev/null
```

**Comment by wraithgar** [comment]
There is already a tracking issue for this, we do plan on implementing it along with another flag to tell npm if you should expect results or not, and amend the exit code accordingly.


https://github.com/npm/statusboard/issues/609
