### ISSUE TITLE
[BUG] dedupe doesn't find duplicate

### ISSUE THREAD

**Issue by 1EDExg0ffyXfTEqdIUAYNZGnCeajIxMWd2vaQeP** [npm/cli#6889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

There are multiple installations of the same version of a package installed in my dependency tree, verified by `npm ls`

### Expected Behavior

`npm dedupe` should find the duplicate and remove it (Better would be if `npm install` would detect it).

### Steps To Reproduce

1. In an empty folder, run `npm install @testing-library/react@14.0.0 vitest@0.28.5`.
2. Observe with `npm ls pretty-format` that `pretty-format` is deduped:
```
codespaces-blank@ /workspaces/codespaces-blank
├─┬ @testing-library/react@14.0.0
│ └─┬ @testing-library/dom@9.3.3
│   └── pretty-format@27.5.1
└─┬ vitest@0.28.5
  └─┬ @vitest/utils@0.28.5
    └── pretty-format@27.5.1 deduped
```
3. Then, run `npm install vitest@0.34.6` to update vitest
4. run `npm ls pretty-format` agai.: Notice pretty-format@29.7.0 is listed twice, without DEDUPED. Annoying, but acceptable.
```
codespaces-blank@ /workspaces/codespaces-blank
├─┬ @testing-library/react@14.0.0
│ └─┬ @testing-library/dom@9.3.3
│   └── pretty-format@27.5.1
└─┬ vitest@0.34.6
  ├─┬ @vitest/snapshot@0.34.6
  │ └── pretty-format@29.7.0
  └─┬ @vitest/utils@0.34.6
    └── pretty-format@29.7.0
```

5. Run `npm dedupe`:
```
up to date, audited 150 packages in 948ms

55 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
6. Run `npm ls pretty-format` again. **The duplication still exists**
```
codespaces-blank@ /workspaces/codespaces-blank
├─┬ @testing-library/react@14.0.0
│ └─┬ @testing-library/dom@9.3.3
│   └── pretty-format@27.5.1
└─┬ vitest@0.34.6
  ├─┬ @vitest/snapshot@0.34.6
  │ └── pretty-format@29.7.0
  └─┬ @vitest/utils@0.34.6
    └── pretty-format@29.7.0
```

### Environment

- npm: 10.1.0
- Node.js: 20.8.0
- OS Name: Ubuntu 20.04, also on 23.04.
- System Model Name: Github codespaces, also on WSL
- npm config:
```ini
; node bin location = /usr/local/share/nvm/versions/node/v20.8.0/bin/node
; node version = v20.8.0
; npm local prefix = /workspaces/codespaces-blank
; npm version = 10.1.0
; cwd = /workspaces/codespaces-blank
; HOME = /home/codespace
; Run `npm config ls -l` to show all defaults.
```

**Comment by wraithgar** [comment]
There is a subtle difference between deduping and hoisting.  npm can't "dedupe" `pretty-format@29.7.0` because `pretty-format@27.5.1` is already hoisted to the root.  npm does not currently have a mechanism to "prefer" what version to hoist.

A solution folks have used for this is to install the exact version they want in their package, then uninstall it.  Direct dependencies *have* to be hoisted, so when you install it will be hoisted.  Then when you uninstall that hoisted dep will remain as long as it's valid in the tree.
