### ISSUE TITLE
[BUG] _auth is valid only for registry url with 1 slash

### ISSUE THREAD

**Issue by dmwcz** [npm/cli#6890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When npmrc file is set this way, authentication works
.npmrc
`//<domain>/repository/:_auth=<auth>`

When it is set like, authentication is ignored
.npmrc
`//<domain>/repository/repository_specifier/:_auth=<auth>`

The issue is during `npm publish --registry https://<domain>/repository/repository_specifier/` getting ENEEDAUTH while it works fine with the first version. 

### Expected Behavior

Ability to set _auth for repository based on full uri
.npmrc
```
registry=https://<domain>/repository/another-specifier/
//<domain>/repository/repository-specifier/:_auth=<auth1>
//<domain>/repository/another-specifier/:_auth=<auth2>
```

### Steps To Reproduce

1. have 2 different registries on same server address (domain)
2. have both registries behind authentication
3. set different authentication for each registry
4. set _auth per registry (full uri) in .npmrc file
5. publish into registry

### Environment

- npm: 10.2
- Node.js: 18.18.0
- OS Name: Win 11
- System Model Name: -
- npm config:
```ini
; "builtin" config from C:\Users\user\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\user\\AppData\\Roaming\\npm"

; "global" config from C:\Users\user\AppData\Roaming\npm\etc\npmrc

python = "C:\\Users\\user\\.windows-build-tools\\python27\\python.exe"

; "user" config from C:\Users\user\.npmrc

; registry = "https://_domain_/repository/npm/" ; overridden by project

; "project" config from F:\_project_\.npmrc

//_domain_/repository/<proxy>-javascript/:_auth = (protected)
registry = "https://<domain>/repository/<proxy>-javascript/"

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v18.18.0
; npm local prefix = F:\<project>
; npm version = 10.2.0
; cwd = F:\<project>
; HOME = C:\Users\user
; Run `npm config ls -l` to show all defaults.

; "publishConfig" from F:\<project>\package.json
; This set of config values will be used at publish-time.

registry = "https://<domain>/repository/<project>-dev-repo"


```

**Comment by wraithgar** [comment]
Based on the config here it looks like `publishConfig` is setting the registry, but there is no corresponding auth token for it.  The only auth is for `<proxy>-javascript`.

Where is the auth for `<project>-dev-repo` defined?

**Comment by LaughDonor** [comment]
Does it work when using `npm 10.1.0`, @dmwcz?
