### ISSUE TITLE
[BUG] npm install fails if lockfile resolved url not accessible (not sure if bug?)

### ISSUE THREAD

**Issue by aliu-vmware** [npm/cli#6896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Installing packages using a registry proxy on a vpn causes `npm install` from a ci machine outside the vpn to fail, due to inability to access the proxy from the public internet.  

For various reasons, granting vpn access to the ci machine is not an option, and not using the proxy on the vpn side is also not an option.

### Expected Behavior

npm should fall back to the npmrc defined registry if the resolved url is not available.

If that's not possible, I want an option to tell npm that the registry in question is to be treated as a proxy of registry.npmjs.org, so that the lockfile writes `registry.npmjs.org` into `resolved` in the lockfile, since that "is a magic value meaning 'the currently configured registry'." according to https://docs.npmjs.com/cli/v10/configuring-npm/package-lock-json

### Steps To Reproduce

dev machine (on vpn):
`npm install zenscroll`
.npmrc contains:
```ini
registry=http://build-artifactory.eng.[redacted]/artifactory/api/npm/npm
```
package-lock contains:
```json
 "node_modules/zenscroll": {
      "version": "4.0.2",
      "resolved": "http://build-artifactory.eng.[redacted]/artifactory/api/npm/npm/zenscroll/-/zenscroll-4.0.2.tgz",
      "integrity": "sha512-jEA1znR7b4C/NnaycInCU6h/d15ZzCd1jmsruqOKnZP6WXQSMH3W2GL+OXbkruslU4h+Tzuos0HdswzRUk/Vgg=="
    }
```
ci machine (not on vpn):
.npmrc contains:
```ini
registry=https://registry.npmjs.org
```

`npm install`
```
11:32:49 npm ERR! network request to http://build-artifactory.eng.[redacted]/artifactory/api/npm/npm/zenscroll/-/zenscroll-4.0.2.tgz failed, reason: getaddrinfo ENOTFOUND build-artifactory.eng.[redacted]
```

### Environment

- npm: 10.2.0
- Node.js: 20.6.0
- OS Name: MacOS Ventura 13.5.2 (22G91)
- System Model Name: Macbook Pro M2
- npm config (vpn):
```ini
registry=http://build-artifactory.eng.[redacted]/artifactory/api/npm/npm
```
- npm config (non-vpn):
```ini
registry=https://registry.npmjs.org
```

**Comment by wraithgar** [comment]
You'll want to use [replace-registry-host](https://docs.npmjs.com/cli/v10/using-npm/config#replace-registry-host)
