### ISSUE TITLE
[BUG] npx foo inside project: `sh: foo: command not found`

### ISSUE THREAD

**Issue by trusktr** [npm/cli#6904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Inside my project (which has a package.json, but not necessarily all dependencies in `node_modules`):

```
❯ npx --yes rimraf --help
sh: rimraf: command not found
```

If I go outside the project:

```
❯ cd ..
                                                                                                                                          
❯ npx --yes rimraf --help
rimraf version 5.0.5

Usage: rimraf <path> [<path> ...]

.... etc ...
```

### Expected Behavior

Expect it to work the same either way, regardless if it is installed or not (especially because `--yes` should install it without asking)

I'm using Lerna, I wonder if that has anything to do with it.

### Steps To Reproduce

Ok, I made a tiny reproduction of the error state here:

https://github.com/trusktr/npm-cli-issue-6904

This shows the error state, but I don't know how I got into that state, or maybe `node-gyp` just needs to exist.

Steps to see the error:

```
$ git clone git@github.com:trusktr/npm-cli-issue-6904.git
$ cd npm-cli-issue-6904
$ npx --yes rimraf --help
sh: rimraf: command not found
```

The repository is minimal, the only thing in `node_modules` is `node-gyp`.

### Environment

- npm: 10.2.0
- Node.js: v20.6.1
- OS Name: macOS 14
- System Model Name: MacBook Air M2
- npm config:
```ini
; "builtin" config from /Users/trusktr/.npm-packages/lib/node_modules/npm/npmrc

; prefix = "/opt/homebrew" ; overridden by user

; "user" config from /Users/trusktr/.npmrc

//registry.npmjs.org/:_authToken = (protected) 
prefix = "/Users/trusktr/.npm-packages" 

; "project" config from /Users/trusktr/src/lume+lume+develop/.npmrc

engine-strict = true 
legacy-peer-deps = true 
package-lock = false 

; node bin location = /Users/trusktr/.n-node-versions/bin/node
; node version = v20.6.1
; npm local prefix = /Users/trusktr/src/lume+lume+develop
; npm version = 10.2.0
; cwd = /Users/trusktr/src/lume+lume+develop
; HOME = /Users/trusktr
; Run `npm config ls -l` to show all defaults.
```

**Comment by trusktr** [comment]
Ok, I made a tiny reproduction of the error state here:

https://github.com/trusktr/npm-cli-issue-6904

This shows the error state, but I don't know how I got into that state, or maybe `node-gyp` just needs to exist.

Steps to see the error:

```
$ git clone git@github.com:trusktr/npm-cli-issue-6904.git
$ cd npm-cli-issue-6904
$ npx --yes rimraf --help
sh: rimraf: command not found
```

The repository is minimal, the only thing in `node_modules` is `node-gyp`.

**Comment by trusktr** [comment]
In my project, I have varying versions of `node-gyp` in nested `node_modules`, and I verified that if I delete ***all*** of them (I had about 10 of them throughout), then `npx --yes rimraf --help` starts working.

**Comment by trusktr** [comment]
I'm not exactly sure what causes this yet. But, the reduced error state is one of many possible errors states. For example, if I start by first deleting all `node-gyp` folders anywhere inside `node_modules`, I will still have the error, so if I continue to reduce from there, I'll end up with a different `node_modules` than in the reproduction but with the same error state.

**Comment by wraithgar** [comment]
What has happened here is you have a `node_modules` that is present but not properly installed.

```sh
$ npm ls rimraf
npm-cli-issue-6904@ /Users/wraithgar/Development/npm/scratch/npm-cli-issue-6904
└─┬ node-gyp@ extraneous
  └── rimraf@2.7.1 extraneous
```

rimraf is in the tree, and it defines a bin of `rimraf`

```sh
~/D/n/s/npm-cli-issue-6904 (main|✔) $ npm query '#rimraf'|json -a _id bin
rimraf@2.7.1 {
  "rimraf": "bin.js"
}
```

npm assumes that `node_modules` got there by a real `npm install` and tries to find `rimraf` where it should be, which is in `node_modules/.bin`.  Because it's not there npm errors out.

```sh
$ ls node_modules/.bin
ls: node_modules/.bin: No such file or directory
```

The TLDR here is that your `node_modules` is invalid and npm cannot recover from that.  If you absolutely must alter `node_modules` (which is not advised) you should ensure that the `.bin` directory is intact.

```sh
~/D/n/s/npm-cli-issue-6904 (main|✚165) $ npm i node-gyp@9
~/D/n/s/npm-cli-issue-6904 (main|✚140) $ ls node_modules/.bin
color-support@ mkdirp@        node-gyp@      node-which@    nopt@          rimraf@        semver@
```

**Comment by almahdi404** [comment]
So you can't do `npx --yes [command]` inside the [command] package repo.

**Comment by prmichaelsen** [comment]
> So you can't do `npx --yes [command]` inside the [command] package repo.

Wow
