### ISSUE TITLE
When we use keyboard keys unable to expand dropdown.

### ISSUE THREAD

**Issue by msftedad** [npm/cli#6917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Dropdown is not expanded with keyboard keys, but dropdown is expanded with mouse.

### Expected Behavior

Dropdown should expand with keyboard ENTER key or SPACE key.

### Steps To Reproduce

1. Open URL: [custom-theme - CodeSandbox](https://codesandbox.io/s/custom-theme-p1556)
2. TAB to “multi select” dropdown and Press ENTER key.
3. Observe that Dropdown is not expanded.

### Environment

npm: 6.14.15

Node.js:14.18.0

OS Name: Windows 11

System Model Name: Lenovo.

npm config:
; cli configs

long = true

metrics-registry = "project configuration"

scope = ""

user-agent = "npm/6.14.15 node/v14.18.0 win32 x64"

; project config C:\WorkSpace\project name\.npmrc

@fxp:registry = "related to project"

@m365-admin:registry = "[https://uifabric.pkgs.visualstudio.com/\_packaging/iss/npm/registry/](https://uifabric.pkgs.visualstudio.com/%5C_packaging/iss/npm/registry/) "

always-auth = true

registry = "related to project"

; userconfig .npmrc config related to project

; builtin config undefined

prefix = "C:\\Users\\logged in user account name\\AppData\\Roaming\\npm"

; default values

access = null

allow-same-version = false

also = null

; always-auth = false (overridden)

audit = true

audit-level = "low"

auth-type = "legacy"

before = null

bin-links = true

browser = null

ca = null

cache = "C:\\Users\\account name\\AppData\\Roaming\\npm-cache"

cache-lock-retries = 10

cache-lock-stale = 60000

cache-lock-wait = 10000

cache-max = null

cache-min = 10

cafile = undefined

cert = null

cidr = null

color = true

commit-hooks = true

depth = null

description = true

dev = false

dry-run = false

editor = "notepad.exe"

engine-strict = false

fetch-retries = 2

fetch-retry-factor = 10

fetch-retry-maxtimeout = 60000

fetch-retry-mintimeout = 10000

force = false

format-package-lock = true

fund = true

git = "git"

git-tag-version = true

global = false

global-style = false

globalconfig = "C:\\Users\\account name\\AppData\\Roaming\\npm\\etc\\npmrc"

globalignorefile = "C:\\Users\\account name\\AppData\\Roaming\\npm\\etc\\npmignore"

group = 0

ham-it-up = false

heading = "npm"

https-proxy = null

if-present = false

ignore-prepublish = false

ignore-scripts = false

init-author-email = ""

init-author-name = ""

init-author-url = ""

init-license = "ISC"

init-module = "C:\\Users\\account name\\.npm-init.js"

init-version = "1.0.0"

json = false

key = null

legacy-bundling = false

link = false

local-address = undefined

loglevel = "notice"

logs-max = 10

; long = false (overridden)

maxsockets = 50

message = "%s"

; metrics-registry = null (overridden)

node-options = null

node-version = "14.18.0"

noproxy = null

offline = false

onload-script = null

only = null

optional = true

otp = null

package-lock = true

package-lock-only = false

parseable = false

prefer-offline = false

prefer-online = false

; prefix = "C:\\Program Files\\nodejs" (overridden)

preid = ""

production = false

progress = true

proxy = null

read-only = false

rebuild-bundle = true

; registry = "https://registry.npmjs.org/ " (overridden)

rollback = true

save = true

save-bundle = false

save-dev = false

save-exact = false

save-optional = false

save-prefix = "^"

save-prod = false

scope = ""

script-shell = null

scripts-prepend-node-path = "warn-only"

searchexclude = null

searchlimit = 20

searchopts = ""

searchstaleness = 900

send-metrics = false

shell = "C:\\WINDOWS\\system32\\cmd.exe"

shrinkwrap = true

sign-git-commit = false

sign-git-tag = false

sso-poll-frequency = 500

sso-type = "oauth"

strict-ssl = true

tag = "latest"

tag-version-prefix = "v"

timing = false

tmp = "C:\\Users\\account name\\AppData\\Local\\Temp"

umask = 0

unicode = false

unsafe-perm = true

update-notifier = true

usage = false

user = 0

; user-agent = "npm/{npm-version} node/{node-version} {platform} {arch} {ci}" (overridden)

userconfig = "C:\\Users\\account name\\.npmrc"

version = false

versions = false

viewer = "browser"

Attachment:

https://github.com/npm/cli/assets/93735775/d308033c-8e25-4a63-b535-4c5db481af40

**Comment by ljharb** [comment]
This seems like you're having an issue with a specific npm package, one that isn't even on the public registry.

You'll need to file this with whoever makes the package you're using.

**Comment by msftedad** [comment]
Hi @ljharb, We get the below input from primary team.

This is open-source library only and we saved in Azure artifacts from there we using,
This Comments are not helpful to resolve this bug.
The owner of the package should fix this issue and need to release the new version then only we can go further.

**Comment by ljharb** [comment]
right - so file the issue with the open source package owner, not with npm.
