### ISSUE TITLE
[BUG] Unwxpwcted warning "Removed invalid scripts" on publish

### ISSUE THREAD

**Issue by zdm** [npm/cli#6918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Npm shows unexpected warning every time, when I am publishong any of my packahes.

```
npm publish --dry-run
```

Result:
```
npm WARN publish npm auto-corrected some errors in your package.json when publishing.  Please run "npm pkg fix" to address these errors.
npm WARN publish errors corrected:
npm WARN publish Removed invalid "scripts"

...
```

`pachage.json`:
```
{
    "name": "@softvisio/api",
    "version": "2.9.8",
    "description": "API",
    "keywords": [
        "softvisio",
        "api"
    ],
    "homepage": "https://softvisio-node.github.io/api/",
    "bugs": {
        "url": "https://github.com/softvisio-node/api/issues",
        "email": "zdm <zdm@softvisio.net>"
    },
    "repository": {
        "type": "git",
        "url": "git+https://github.com/softvisio-node/api.git"
    },
    "license": "ISC",
    "author": "zdm <zdm@softvisio.net>",
    "type": "module",
    "imports": {
        "#core/*": "@softvisio/core/*",
        "#lib/*": "./lib/*.js"
    },
    "exports": {
        "./*": "./lib/*.js"
    },
    "files": [
        "/bin",
        "/lib",
        "/resources",
        "/src"
    ],
    "dependencies": {
        "linkedom": "^0.15.0",
        "random-location": "^1.1.3"
    },
    "peerDependencies": {
        "@softvisio/core": "^7.0.0"
    }
}

```

### Expected Behavior

No warnings should be desplayed, because `package.json` has no `scripts` ptoperty at all.

### Steps To Reproduce

See above.

### Environment

- npm: 10.1.0
- Node.js: v20.8.1
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by ljharb** [comment]
If you add an empty one, does it avoid the warning?

**Comment by zdm** [comment]
With empty scripts - no warning.

**Comment by ljharb** [comment]
so how come your package has no scripts? you're not running any tests?

**Comment by zdm** [comment]
I tested it completely before created  this issue.
If package.json has no `sccrips` - it show warning on pusblish.
You can check it yourself.

**Comment by ljharb** [comment]
Right, i mean, why don’t you have any scripts?

**Comment by zdm** [comment]
Hnn, strange question.
Because most of packages don;t need scripts.

**Comment by ljharb** [comment]
Every package needs tests, and the "test" script thus needs to be defined. In other words, virtually zero packages don't need scripts.

**Comment by zdm** [comment]
This is other question.
Believe me, 90& of packaged u the world do not use scripts.
In an case scripts are not mandatory., so according to this issure - I thisnk it should be fixed.

**Comment by ljharb** [comment]
I don't believe you; I'd guess that 99% of packages in the world do use scripts.

I agree that they're not mandatory and the issue should be fixed, but I also think the reason nobody found this before is because everybody has scripts :-)

**Comment by zdm** [comment]
Please, download 100 random packaces from the nom.org and check  - do they have scripts.

Listen, this is not related to this issur at all, let's not not wast time.

Scripts are not ,mandatory, so what the sense of this warning, annoy people?
This is not `nom` business to watch for how user use package.

If you are member of npm dev team and you are decided that this is not a issue - please, close it, bit let's stop crazy discussion.

**Comment by zdm** [comment]
lasr words:

If user need scripts - he will use them, if not - not. Without reminders from `npm`.

`npm` trying to force user to add scripts, which are not required.

We need to add some fake scripts to make is happy?

The single goal of this warning is to annoy and confuse people.

**Comment by wraithgar** [comment]
This is a side effect of how npm has been publishing packuments this whole time. 

If you inspect the packages in the registry, you'll see they all have an empty `scripts` object even if the `package.json` source does not.

The new logging is a byproduct of our attempts to make sure these two entries are in sync.  The decision was made to NOT allow a change change to what's in the registry to minimize potential breaking changes for those who consume these packages.

**Comment by victorhenrion** [comment]
> This is a side effect of how npm has been publishing packuments this whole time.
> 
> If you inspect the packages in the registry, you'll see they all have an empty `scripts` object even if the `package.json` source does not.
> 
> The new logging is a byproduct of our attempts to make sure these two entries are in sync. The decision was made to NOT allow a change change to what's in the registry to minimize potential breaking changes for those who consume these packages.

Makes sense to me! However, the warning `Removed invalid "scripts"` when there was no scripts in the first place is pretty unclear.

**Comment by SorinGFS** [comment]
> > This is a side effect of how npm has been publishing packuments this whole time.
> > If you inspect the packages in the registry, you'll see they all have an empty `scripts` object even if the `package.json` source does not.
> > The new logging is a byproduct of our attempts to make sure these two entries are in sync. The decision was made to NOT allow a change change to what's in the registry to minimize potential breaking changes for those who consume these packages.
> 
> Makes sense to me! However, the warning `Removed invalid "scripts"` when there was no scripts in the first place is pretty unclear.

Is not just "unclear", is **wrong**! This is because actually **does not remove anything!**

**Comment by ljharb** [comment]
It doesn’t from package.json, but it does from the packument in the published package.

**Comment by mcqj** [comment]
Explaining the background to the bug is useful for context. However, the end user will not expect a warning message when they have a perfectly valid package.json. Furthermore, a warning message that suggests running `npm pkg fix` to address the errors, when in fact running that command will not address them creates even more confusion.
The warning message should be removed.

**Comment by romainmenke** [comment]
> I don't believe you; I'd guess that 99% of packages in the world do use scripts.

We definitely use scripts but we don't see why we should be bloating the npm registry, user `node_modules` folders and everything in between with several hundred bytes of data that is useless on that end.

We prefer to strip this before publishing.

Some quick maths : we save the interwebs ±120 gigabytes of transfer each week by stripping all scripts from `package.json` before publishing.

I don't see the point of this warning ...

**Comment by l3ender** [comment]
Still seeing this problem with Node v20.15.1 (NPM 10.7.0). Not quite sure why this issue was closed when the incorrect behavior still exists (summarized well by @mcqj in https://github.com/npm/cli/issues/6918#issuecomment-1978707029).
