### ISSUE TITLE
[BUG] Exit handler never called

### ISSUE THREAD

**Issue by amysteriousdude** [npm/cli#6920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

when i wanted to install firebase-tools in termux, it doesnt work!

### Expected Behavior

i expected to crash but it was very late.

### Steps To Reproduce

idk

### Environment

- npm: 9.6.6
- Node.js: v20.2.0
- OS Name: Android
- System Model Name: Samsung A127F
- Terminal: Termux Latest Version FDroid
- Logs: https://drive.google.com/file/d/1DwpaJph7rtCRKE_97oZBjdUPJWlfoCPp/view?usp=sharing

**Comment by milaninfy** [comment]
**Closing:** this error can arise for a number of reasons; Please read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) & refile an issue with as much information as possible if you're able to **consistently reproduce** this rror.    

If this is still an issue, update npm to latest (10.8.3) and try.
