### ISSUE TITLE
[BUG] npm doesn't reconcile peer and dev dependencies

### ISSUE THREAD

**Issue by sethsamuel** [npm/cli#6922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

NPM is installing multiple versions of a dependency that could be met by a single version. We have a fixed dependency on `@types/react` in our shared library, and a broadly ranged peer dependency from another module.

```
❯ npm explain @types/react
@types/react@18.2.31 peer
node_modules/@types/react
  peer @types/react@">=18" from react-markdown@9.0.0
  node_modules/react-markdown
    react-markdown@"9.0.0" from the root project

@types/react@18.2.30 dev
src/overtime-lib/node_modules/@types/react
  dev @types/react@"18.2.30" from overtime-lib@1.0.0
  src/overtime-lib
    overtime-lib@1.0.0
    node_modules/overtime-lib
      overtime-lib@"file:./src/overtime-lib" from the root project
```

### Expected Behavior

NPM should recognize that the peer dependency is already fulfilled and not install a second version.

### Steps To Reproduce

1. Install a package with a fixed version of `@types/react`
2. Install a second package with a peer dependency that includes that version in its range

### Environment

- npm: 10.2.1
- Node.js: 18.18.0
- OS Name: OS X
- System Model Name: Macbook Pro
- npm config:
```ini
; node bin location = /Users/seth/.nvm/versions/node/v18.18.0/bin/node
; node version = v18.18.0
; npm local prefix = /Users/seth/Documents/overtime/overtime-ot7-www
; npm version = 10.2.1
; cwd = /Users/seth/Documents/overtime/overtime-ot7-www
; HOME = /Users/seth
; Run `npm config ls -l` to show all defaults.```

**Comment by ljharb** [comment]
I think what's happening here is that the first one selects the latest, and the second one is pinned and thus is incompatible with it.

If the second package used a `^` or `~` (which I'd argue would be the only correct thing to do), then I would expect only one to be installed.

**Comment by sethsamuel** [comment]
How are "first" and "second" determined by npm?

**Comment by ljharb** [comment]
That's a good question. I'd bet that it's not deterministic.

Either way, your own project should always be explicitly depending on your graph's peer deps, which in this case would mean you'd explicitly depend on `18.2.30`, and then everything should work itself out.

**Comment by sethsamuel** [comment]
The whole point of our shared lib is to centralize dependencies, especially for core modules like types since Typescript is extremely sensitive to having duplicate definitions. I would expect npm to at the very least be deterministic in calculating dependencies, and ideally it should recognize that there is an existing fulfillment of the peer dependency.

**Comment by ljharb** [comment]
That's all fine, but you'd still want every package.json to have explicit dependencies for any peer deps in its graph.

**Comment by sethsamuel** [comment]
Why is that? I don't see anything in the docs on peer dependencies suggesting that the root package must or even should install them, just that they they will be installed, which doesn't seem to leave them any different than other dependencies.

**Comment by ljharb** [comment]
Because it's explicit, and explicit > implicit. It also avoids having to delegate the decisionmaking to npm.

**Comment by sethsamuel** [comment]
Maybe this is a feature request rather than a bug then, because my expectation would be that npm resolves the dependency tree to minimize the number of versions of modules it installs.

**Comment by ljharb** [comment]
It does do that - it's already a best-effort thing. The actual task is objectively impossible for a computer to solve (it's one of those P=NP hard things), which is why the best approach includes humans making those decisions explicit in as many places as possible.

**Comment by sethsamuel** [comment]
Appreciate that in the general case, but in this specific case wouldn't evaluating peer dependencies after all other dependencies both solve this particular issue and hew more closely to the intent of a peer?

**Comment by ljharb** [comment]
That would just cause a different set of similar problems. This one only occurs because one of the packages improperly pins to a single version, which is far less common than the affected scenarios if your suggestion was implemented.

**Comment by TarSzator** [comment]
I have the following issue and asking myself it is related.
I can run `npm i` with `npm v10.2.1` and it works and creates a `package-lock.json`
But when I then run `npm ci` I get an error that my `package-lock.json` is not up2date connected with a ton of 
`Invalid: Lock file's` and `Missing:` errors

**Comment by TarSzator** [comment]
Just tested it with a project where there is no `react` involved and there it works

**Comment by wraithgar** [comment]
This is because your shared library is from a local directory.  
`overtime-lib@"file:./src/overtime-lib" from the root project`

That directory (`./src/overtime-lib`) has its own dependencies installed, independent of its context in the main package.

Even if I make the versions match exactly, as long as the secondary library has its own node_modules, this will happen.

```sh
~/D/n/s/a/main $ npm explain @types/react
@types/react@18.2.37 peer
node_modules/@types/react
  peer @types/react@">=18" from react-markdown@9.0.1
  node_modules/react-markdown
    react-markdown@"^9.0.0" from the root project

@types/react@18.2.37
../second/node_modules/@types/react
  @types/react@"18.2.37" from second@1.0.0
  ../second
    second@1.0.0
    node_modules/second
      second@"file:../second" from the root project
```

The only way to fix this is for your shared library NOT to have its own node_modules installed

```sh
/D/n/s/a/main $ cd ../second
~/D/n/s/a/second $ rm -rf node_modules/ package-lock.json 
~/D/n/s/a/second $ cd ../main
~/D/n/s/a/main $ npm i

up to date, audited 70 packages in 602ms

found 0 vulnerabilities
~/D/n/s/a/main $ npm explain @types/react
@types/react@18.2.37 peer
node_modules/@types/react
  peer @types/react@">=18" from react-markdown@9.0.1
  node_modules/react-markdown
    react-markdown@"^9.0.0" from the root project

```
