### ISSUE TITLE
[BUG] bundled dependencies are not bundled when not specified in dependencies

### ISSUE THREAD

**Issue by 0c3d7r4** [npm/cli#6931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [ ] I am using the latest npm

### Current Behavior

even if one adds a package into "bundledDependencies" array (or field) it will not be packaged unless it's explicitly included in "dependencies" which completely defeats the purpose.

9.5.1

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by ljharb** [comment]
Why does that defeat the purpose? Putting it in both means it's a requirement, and it's also bundled.

**Comment by 0c3d7r4** [comment]
i don't think we're on the same page. unless i put it in "dependencies" it won't be bundled at all. and i don't want it in dependencies because then it makes people download it which is pointless since it bundled.

eg I have a private package @my/package that is not publically available to people but i'd like to put it in another package of mine which is public. so i bundle it. this is the _real_ purpose of bundled dependencies. 

also fyi the behavoiur was correct previously on whatever npm was with node 12

**Comment by ljharb** [comment]
I’m pretty sure it won’t make people download it if it’s in both.

**Comment by 0c3d7r4** [comment]
@ljharb yeah it will that's the problem it didn't used to but it does now

**Comment by 0c3d7r4** [comment]
@ljharb with `yarn` it will be added to the yarn.lock and also if the package is private it will fail to download and the whole process will fail. i'm pretty sure more than 1 person uses yarn.

**Comment by ljharb** [comment]
Ok, but what does npm, the standard node package manager, do? If npm handles it right, then it’s a yarn bug.

**Comment by 0c3d7r4** [comment]
let the arguing commence. 

Who says that it handles it right? essentially we're not talking about npm client but npm "protocol" where if a dependency is (was) in the bundled dependencies but not prod deps, it will be packaged fine. this used to be the case for years. then, you broke the protocol by saying that a dependency must be specified in prod deps if it needs to be bundled. without any discussion with anyone or hearing anyone's arguments. just all of the sudden, **logical** things that used to work don't work anymore. it is logical because when i bundle a dependency, i don't need to have it installed as a prod dependency: as i've already mentioned, i have a use case where i install a private dep as dev dep and then bundle it which have worked for years. what is the logic of a dependency having to be in prod deps if it's bundled? there's no logic to it at all. what is the reasoning of a person who decided on this? by knowing open source maintenance operates, i can pretty confidently bet it was exactly you who introduced it because of the way you're defending this completely unreasonable flow by trying to convince me that the _protocol_ is that a dependency must be a prod dependency in order to be bundled, and the NPM client is doing the right thing right now by simply not downloading it. well as i said there are other clients and you have a responsibility to them to maintain the contract. what is happening, is that you're making a decision, on your own, without any pro-con argumentation, breaking the previously established protocol and saying that it is now right. very well done mate very high standard, super professional, exactly what i expected from a js-community "collaborator". 👀

**Comment by ljharb** [comment]
You say "you", but I'm not on the npm team, I'm just helping to triage.

It very well may be that there's a bug here on the publishing side! I'm asking about the installing side. *if* a dep is mentioned in bundled deps, I would assume that npm, and all other clients, would refuse to download it, since that's the semantic bundledDeps has.

**Comment by 0c3d7r4** [comment]
i say you because i my experience people just love to deny an obvious bug and call it a feature when they are responsible. since it wasn't you then forgive me. it goes either way:

if a dep is mentioned in bundled deps, I would assume that npm, and all other clients, would _still bundle it_, since that's the semantic bundledDeps has.

**Comment by ljharb** [comment]
I would agree. I’d expect the same on install, which is what i was asking - if it’s in both, and it’s bundled, will the bundling be respected by npm on install?

**Comment by wraithgar** [comment]
> let the arguing commence

Can we not do this, please.

This is not something npm is going to support.  Bundled dependencies are tied to the `dependencies` of the project, not whatever happens to be hoisted inside `node_modules`.  That's its "purpose".

**Comment by 0c3d7r4** [comment]
@wraithgar oh because you said so you feel like you can close the issue? who says they are tied to dependencies, and not dev dependencies? you? In addition, npm already supported  this in past if you ever read the thread.
