### ISSUE TITLE
Add npm init option to generate a .gitignore file containing node_modules

### ISSUE THREAD

**Issue by sdavids** [npm/cli#6940]
Add an npm init option to generate a _.gitignore_ file containing `node_modules`.

Either via a CLI option or an npm config flag.

Something along the lines of `npm init --generate-gitignore`

The generated (or updated) _.gitignore_ file would have an entry:

```
/node_modules/
```

This could even be the default going forward.

**Comment by ruchikamuddinagiri** [comment]
Hey, I'd like to add this, can I go ahead?

**Comment by ljharb** [comment]
This would need to be an RFC, not a CLI issue. Post it on https://github.com/npm/rfcs

**Comment by sdavids** [comment]
I have opened https://github.com/npm/rfcs/discussions/742
