### ISSUE TITLE
[BUG] concurrent npx calls break module installation

### ISSUE THREAD

**Issue by sakulstra** [npm/cli#6955]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

We maintain a suite of scripts that utilize npx to run certain npm modules.
Occasionally when it happends that multiple `npx module` commands are executed concurrently it happens that execution fails due to missing modules.

When afterwards running the scripts again they will now always fail as the global npx node_modules cache now houses the partially installed module.

The only solution i found is removing the module manually and trying again.
The issue happens on macos and windows.

### Expected Behavior

npx commands should somehow be collision resistant and not permanently break the npx setup.

### Steps To Reproduce

I didn't not manage to create a reliable, minimal reproduction.

I think in theory a `npx --yes eslint README.md & npx --yes eslint package.json` could work, but if I'm facing issues or not relies on how heavy the package is / how fast my connection is. If the package was already installed before there will not be a problem.

### Environment

- npm: 9.8.1
- Node.js: v20.6.1
- OS Name: MacOs
- System Model Name: Macbook Pro
- npm config:
```ini
; "user" config from /Users/sakulstra/.npmrc

//registry.npmjs.org/:_authToken = (protected) 

; node bin location = /Users/sakulstra/.nvm/versions/node/v20.6.1/bin/node
; node version = v20.6.1
; npm local prefix = /Users/sakulstra
; npm version = 9.8.1
; cwd = /Users/sakulstra
; HOME = /Users/sakulstra
; Run `npm config ls -l` to show all defaults.
(base
```

**Comment by wraithgar** [comment]
This is unfortunately just a reality of npm.  It does not write to a cache that's exclusive to each running instance.  It's not even a proper "cache" in that it doesn't obtain locks and doesn't expire. It's a folder that it saves the installation to.

You'd potentially see this problem running npm concurrently in any context, even install, since the installed package cache works in a similar way.

npx and npm are not currently concurrency-safe.
