### ISSUE TITLE
using npm install found a error: npm verb stack Error: No workspaces found: npm verb stack   --workspace=[]

### ISSUE THREAD

**Issue by jiakangning** [npm/cli#6956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

This phenomenon occurs in container environments， 
node： v16.14.0
npm：  v8.3.1
when usening npm and exec `npm install --verbose`
then occur this issue

guess node > 16 (npm >= 8) has a `workspace `attribute， whether or not？

### Expected Behavior

`npm install` can right work

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:8.3.1
- Node.js:16.14.0
- OS Name: linux （docker）
- System Model Name:
- npm config: set a registry

**Comment by wraithgar** [comment]
not enough info here to reproduce
