### ISSUE TITLE
[New: Memory Leaked] Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by iampawanpoudel** [npm/cli#6961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

While installing any package via npm or using NPX  I am getting memory leaked error.
```bash
(node:10460) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
```

### Expected Behavior

I have tried updating both Nodejs and NPM but none of them worked for me.

### Steps To Reproduce

1. Install any NPM package

### Environment

- npm:10.2.3
- Node.js:v20.9.0
- OS Name: window
- System Model Name:SLIC-MPC

**Comment by wraithgar** [comment]
This was a node.js bug, fixed in the latest version https://github.com/nodejs/node/pull/50136
