### ISSUE TITLE
Sudden odd behaviour with npm install and lock file

### ISSUE THREAD

**Issue by paul-uz** [npm/cli#6962]
We have a lock file generated with node 18 and npm 9.

When it's building on our Jenkins box, which also uses node 18 and npm 9, the lock file is modified from lockfileversion 3 to 1 and not all of thr packages in the package.jsomn file are installed.

I removed the carets, so exact versions are installed, but that didn't seem to help.

This never used to happen and has only started to do so with this latest code we have written.

**Comment by wraithgar** [comment]
please use the issue template so we can see your config and a way to reproduce locally.

**Comment by paul-uz** [comment]
So I figured it out, but it makes no sense as it's been fine for years.

The root node modules folder had an npm folder in it, which must have been affecting the install commands in the sub folders.

Removing it solved the issue, but as I said, this has never been an issue before. Oh well.
