### ISSUE TITLE
[BUG] random 404s when installing private package.

### ISSUE THREAD

**Issue by paul-uz** [npm/cli#6975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Our Jenkins CI/CD setup uses EC2 instances to build our project.

The NPM_TOKEN is added as an env variable, and we are seeing random 404s for a private package we use in various parts of the project (multiple folders, with self contained package files)

After doing several builds, there is no consistency, just that npm is unable to install a private package version, which does exist, saying 

> 404  '@company-name/package-name@https://registry.npmjs.org/@company-name/package-name/-/package-name-1.3.2.tgz' is not in this registry.

It has happened for different versions, all of which are still available in the private registry

### Expected Behavior

Private package should be installed, as it exists and the token is correct.

### Environment

- npm: 9.6.7
- Node.js: 18.17.1
- OS Name: Amazon Linux
- npm config
```
node bin location = /jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_18_Latest/bin/node
node version = v18.17.1
npm local prefix = /jenkins/workspace/Dev/Me/Project
npm version = 9.6.7
cwd = /jenkins/workspace/Dev/Me/Project
HOME = /home/ec2-user
```

**Comment by paul-uz** [comment]
I seem to have fixed it by explicitly adding `npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"` to my build steps. However, other jobs don't require this in order to successfully install the private package, so something fishy is going on 🤔

**Comment by wraithgar** [comment]
This does not appear to be a bug with npm but with the config of your build environments. If npm has the authToken for the registry it will use it.

Please reopen if you have a consistent way to reproduce this.
