### ISSUE TITLE
[BUG] `npm update --save` after `npm update` doesn't update `package.json`

### ISSUE THREAD

**Issue by arnabanimesh** [npm/cli#6980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`package.json` not getting updated with the latest versions

### Expected Behavior

`package.json` should get updated with the latest versions

### Steps To Reproduce

1. Run `npm outdated` to check the packages which require update and monitor those package versions in the `package.json` file (Optional)
2. Run `npm update` to update the depdendencies in `package-lock.json`
3. Run `npm update --save` and note the versions in the `package.json` file

### Environment

- npm: 10.2.1
- Node.js: 20.9.0
- OS Name: Windows 11 Pro 23H2 x64
- System Model Name: Dell Precision 3571
- npm config:
```ini
; "builtin" config from C:\Users\Arnab\scoop\persist\nodejs-lts\bin\node_modules\npm\npmrc

cache = "C:\\Users\\Arnab\\scoop\\persist\\nodejs-lts\\cache"
prefix = "C:\\Users\\Arnab\\scoop\\persist\\nodejs-lts\\bin"

; node bin location = C:\Users\Arnab\scoop\apps\nodejs-lts\current\node.exe
; node version = v20.9.0
; npm local prefix = D:\coding\nextjs\qwix_ui
; npm version = 10.2.1
; cwd = D:\coding\nextjs\qwix_ui
; HOME = C:\Users\Arnab
; Run `npm config ls -l` to show all defaults.
```

**Comment by wraithgar** [comment]
I can't reproduce this with the steps given

```sh
~/D/n/s/a $ rm -rf *
~/D/n/s/a $ npm i abbrev@1.1.0

added 1 package in 446ms
~/D/n/s/a $ npm pkg get dependencies.abbrev
"^1.1.0"
~/D/n/s/a $ npm update

changed 1 package, and audited 2 packages in 571ms
~/D/n/s/a $ npm ls abbrev
a@ /Users/wraithgar/Development/npm/scratch/a
└── abbrev@1.1.1

~/D/n/s/a $ npm update --save

up to date in 440ms
~/D/n/s/a $ npm pkg get dependencies.abbrev
"^1.1.1"
```
