### ISSUE TITLE
[BUG] Unable to download some packages 

### ISSUE THREAD

**Issue by pixelguy106** [npm/cli#6982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Doesn't working properly

### Expected Behavior

Download it without any issues 

### Steps To Reproduce

1. Android termux
2. Ex npm install -g ejs
3. Run '
4. error: npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in: /data/data/com.termux/files/home/.npm/_logs/2023-11-12T01_23_10_778Z-debug-0.log

### Environment

- npm:9.6.6
- Node.js:v20.2.0
- OS Name: Android 11 armv7l
- System Model Name: Infinix Infinix X6512
- npm config: 
; "user" config from /data/data/com.termux/files/home/.npmrc

foreground-scripts = true

; node bin location = /data/data/com.termux/files/usr/bin/node
; node version = v20.2.0
; npm local prefix = /data/data/com.termux/files/home/.npm/_logs
; npm version = 9.6.6
; cwd = /data/data/com.termux/files/home/.npm/_logs
; HOME = /data/data/com.termux/files/home
; Run `npm config ls -l` to show all defaults.

**Comment by wraithgar** [comment]
This is a known issue with termux and other extremely resource-limited environments.  npm often runs out of memory and the OS kills processes in an unrecoverable way.

You can see our original [tracking issue](https://github.com/npm/cli/issues/417) for more examples/comments.
