### ISSUE TITLE
Ignore a particular package from appearing in `package-lock.json`

### ISSUE THREAD

**Issue by jjant** [npm/cli#7016]
I have two packages, `Library`, `App`. I want `App` to depend on `Library@^1.0.0`, and always pick the latest version satisfying that constraint. I also want to use lock files for these projects for "best practices" reasons.

For this, I need to be able to "ignore" `Library` from appearing in `App`'s lockfile. Is this possible?

**Comment by ljharb** [comment]
Not that I’m aware of.

**Comment by wraithgar** [comment]
If you want a different version of a package to be installed you don't want a lockfile. The ideas are mutually exclusive
