### ISSUE TITLE
8 vulnerabilities (2 moderate, 6 high)[BUG] <title>

### ISSUE THREAD

**Issue by ghost** [npm/cli#7023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by ghost** [comment]
Please help me to resolve this issue

**Comment by David-51** [comment]
i think its the same as https://github.com/facebook/create-react-app/issues/11174
