### ISSUE TITLE
npm ERR! Exit handler never called!

### ISSUE THREAD

**Issue by arunklu** [npm/cli#7031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Run npm login --registry=${NPM_REGISTRY} --scope=${NPM_REGISTRY} --always-auth --username=${NPM_USER} --***
npm notice Log in on ***/
npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in: /home/runner/.npm/_logs/2023-[11](https://github.com/arunklu/verdaccio-cicd-test/actions/runs/7015267105/job/19084308755#step:6:12)-28T07_00_34_033Z-debug-0.log
Username: 
Error: Process completed with exit code 1.

### Expected Behavior

success

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by VutukuriBharatTR** [comment]
Hi,
Is there any solution for that. I'm also facing the same issue.
