### ISSUE TITLE
[BUG] `npx` doesn't handle package aliases nicely

### ISSUE THREAD

**Issue by HoldYourWaffle** [npm/cli#7041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`npx` doesn't handle package aliases resulting in two versions of a package/binary nicely.
It seems to always pick the binary of the first package in alphabetical order, with no way to override this default.

### Expected Behavior

I would expect `npx` to pick the most recent version of the package by default. The current behavior can lead to unexpected results when a package alias is merely renamed.

Either way, a flag (`-p`?) to explicitly set the package would be nice.

### Steps To Reproduce

1. With a `package.json` like this:
```json
"devDependencies": {
    "legacy-ts": "npm:typescript@3.8",
    "typescript": "^5.3.2"
}
```

2. Run: `npx tsc --version`
3. See "Version 3.8.3"
4. Run: `npx -p typescript tsc --version`
5. See "Version 3.8.3"
6. Run: `npx -p legacy-ts tsc --version`
7. See "Not Found - GET https://registry.npmjs.org/legacy-ts - Not found"

### Environment

- npm: 10.2.4
- Node.js: 20.8.1
- OS Name: Windows 10
- npm config: 
```ini
; node bin location = HOME\AppData\Roaming\nvm\v20.8.1\node.exe
; node version = v20.8.1
; npm local prefix = PROJECTFOLDER
; npm version = 10.2.4
; cwd = PROJECTFOLDER
; HOME = C:\Users\USERNAME
```

**Comment by wraithgar** [comment]
This is not just limited to `npx` this is how npm works.  Every package that gets installed can define a `bin` that ends up being installed by name. If two packages have the same name there is no way for npm to know which one to use, and it is not a setup we can support.

```sh
~/D/n/i/b/main (main|✔) $ npm view typescript@5.3.2 bin
{ tsc: 'bin/tsc', tsserver: 'bin/tsserver' }
~/D/n/i/b/main (main|✔) $ npm view typescript@3.8.3 bin
{ tsc: 'bin/tsc', tsserver: 'bin/tsserver' }
```

You would have this problem even if the package itself was named `legacy-ts`.  If it had that `bin` entry you'd be in the same situation.

There is no way for npm to support this tree and satisfy both `bin` entries.  `bin` entries are not affected by aliasing, they are intended for overriding dependencies.
