### ISSUE TITLE
[BUG] < Cannot find module @rollup/rollup-win32-x64-msvc. npm has a bug related to optional dependencies>

### ISSUE THREAD

**Issue by ananthumaheswaran** [npm/cli#7045]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

![image](https://github.com/npm/cli/assets/138190517/a6d38745-eac7-475e-99d4-1e8fc4f6b059)

### Expected Behavior

I expected that running the npm run dev command would start a local development server for my Vite-based React application, allowing me to access and hot-reload my app locally in my web browser.

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: version - 10.2.4
- Node.js: v20.10.0 - lts
- OS Name: Microsoft Windows 11 Home Single Language
- System Model Name:  VivoBook_ASUSLaptop X513EAN_K513EA
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by taikinyemi** [comment]
I experienced the same thing for days. This is what worked for me. I downloaded the most recent Visual C++ Redistributable. 
You can download it here: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
