### ISSUE TITLE
[BUG] <Error: CERT_UNTRUSTED>

### ISSUE THREAD

**Issue by LiKaizi** [npm/cli#706]
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/bin/npm', 'install', 'bittorrent-tracker' ]
2 info using npm@1.3.6
3 info using node@v0.10.48
4 verbose cache add [ 'bittorrent-tracker', null ]
5 verbose cache add name=undefined spec="bittorrent-tracker" args=["bittorrent-tracker",null]
6 verbose parsed url { protocol: null,
6 verbose parsed url   slashes: null,
6 verbose parsed url   auth: null,
6 verbose parsed url   host: null,
6 verbose parsed url   port: null,
6 verbose parsed url   hostname: null,
6 verbose parsed url   hash: null,
6 verbose parsed url   search: null,
6 verbose parsed url   query: null,
6 verbose parsed url   pathname: 'bittorrent-tracker',
6 verbose parsed url   path: 'bittorrent-tracker',
6 verbose parsed url   href: 'bittorrent-tracker' }
7 silly lockFile bf8cf609-bittorrent-tracker bittorrent-tracker
8 verbose lock bittorrent-tracker /root/.npm/bf8cf609-bittorrent-tracker.lock
9 silly lockFile bf8cf609-bittorrent-tracker bittorrent-tracker
10 silly lockFile bf8cf609-bittorrent-tracker bittorrent-tracker
11 verbose addNamed [ 'bittorrent-tracker', '' ]
12 verbose addNamed [ null, '*' ]
13 silly lockFile b804a38e-bittorrent-tracker bittorrent-tracker@
14 verbose lock bittorrent-tracker@ /root/.npm/b804a38e-bittorrent-tracker.lock
15 silly addNameRange { name: 'bittorrent-tracker', range: '*', hasData: false }
16 verbose url raw bittorrent-tracker
17 verbose url resolving [ 'https://registry.npmjs.org/', './bittorrent-tracker' ]
18 verbose url resolved https://registry.npmjs.org/bittorrent-tracker
19 info trying registry request attempt 1 at 20:28:19
20 http GET https://registry.npmjs.org/bittorrent-tracker
21 info retry will retry, error on last attempt: Error: CERT_UNTRUSTED
22 info trying registry request attempt 2 at 20:28:29
23 http GET https://registry.npmjs.org/bittorrent-tracker
24 info retry will retry, error on last attempt: Error: CERT_UNTRUSTED
25 info trying registry request attempt 3 at 20:29:29
26 http GET https://registry.npmjs.org/bittorrent-tracker
27 silly lockFile b804a38e-bittorrent-tracker bittorrent-tracker@
28 silly lockFile b804a38e-bittorrent-tracker bittorrent-tracker@
29 error Error: CERT_UNTRUSTED
29 error     at SecurePair.<anonymous> (tls.js:1430:32)
29 error     at SecurePair.emit (events.js:92:17)
29 error     at SecurePair.maybeInitFinished (tls.js:1029:10)
29 error     at CleartextStream.read [as _read] (tls.js:521:13)
29 error     at CleartextStream.Readable.read (_stream_readable.js:341:10)
29 error     at EncryptedStream.write [as _write] (tls.js:418:25)
29 error     at doWrite (_stream_writable.js:226:10)
29 error     at writeOrBuffer (_stream_writable.js:216:5)
29 error     at EncryptedStream.Writable.write (_stream_writable.js:183:11)
29 error     at write (_stream_readable.js:602:24)
30 error If you need help, you may report this log at:
30 error     <http://github.com/isaacs/npm/issues>
30 error or email it to:
30 error     <npm-@googlegroups.com>
31 error System Linux 2.6.32-504.3.3.el6.x86_64
32 error command "node" "/usr/bin/npm" "install" "bittorrent-tracker"
33 error cwd /root
34 error node -v v0.10.48
35 error npm -v 1.3.6
36 verbose exit [ 1, true ]

**Comment by DanielRuf** [comment]
Please try `curl https://registry.npmjs.org/` and also try https://registry.npmjs.org/ in your browser.

It looks like something (proxy, vpn) replaces the certificate.

**Comment by ljharb** [comment]
Closing pending repro info.

Also, npm v1 is long obsolete and unsupported, as is node v0.10, so you'll want to upgrade both anyways.
