### ISSUE TITLE
[FEATURE] Make the `npm update` command take effect immediately

### ISSUE THREAD

**Issue by Beace** [npm/cli#7074]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I understand that the npm registry has a cache of 5 minutes, and the npm CLI will always reuse the local cache until the cache expires. 

This phenomenon causes the client to not make a new request to the registry when using the `npm update <package>` command, resulting in untimely updates. 

```sh
$ npm update beace-tests --registry https://registry.npmjs.org --cache=mycache
0 verbose cli /Users/my/.nvm/versions/node/v20.9.0/bin/node /Users/my/.nvm/versions/node/v20.9.0/bin/npm
1 info using npm@10.1.0
2 info using node@v20.9.0
21 verbose title npm update beace-tests
22 verbose argv "update" "beace-tests" "--registry" "https://registry.npmjs.org" "--cache" "mycache"
38 http fetch GET 200 https://registry.npmjs.org/beace-tests 18ms (cache hit)
39 silly placeDep ROOT beace-tests@1.0.5 KEEP for: npm-test@1.0.0 want: ^1.0.5
```

I had to uninstall and reinstall it or choose a specific version to install.

### Expected Behavior

Can we change the behavior of the `npm update` command to send a request verification to the registry server, even if the local cache has not expired within 5 minutes ?

### Environment

- npm: 10.1.0
- Node.js: v20.9.0
- OS Name: MacOS Intel

**Comment by milaninfy** [comment]
@Beace  Try adding this flag `npm update --prefer-online` see if that works for your use case.  
https://docs.npmjs.com/cli/v10/using-npm/config#prefer-online

**Comment by milaninfy** [comment]
This is more of a feature request. A good place to start this discussion is at https://github.com/npm/feedback
