### ISSUE TITLE
[BUG] npm 10.2.5 changes the behavior of package.json files globs like "foo/**/*"

### ISSUE THREAD

**Issue by danpere** [npm/cli#7081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

If the `files` section of `package.json` has lines like `"foo/**/*"` they do not match anything.

### Expected Behavior

`npm pack` should have picked up all files from the `foo/` directory. If I downgrade to 10.2.4, they do.

I have reported this at https://github.com/npm/npm-packlist/issues/212 as this change appears to be due to a change in npm-packlist between v8.0.0 and v8.0.1 which npm picked up in 10.2.5. Reporting here as well because I expected the behavior change to be documented in npm's documentation or changelog.

### Steps To Reproduce

1. Write a `package.json` file with a `files` section like
```json
"files": [
    "foo/**/*"
]
```
where the directory `foo` is non-empty.
2. Run `npm pack`.
3. Observe that no files from the `foo/` directory were included.

### Environment

- npm: 10.2.5
- Node.js: 20.10.0
- OS Name: Windows 11 Enterprise Version 10.0.22631 Build 22631
- System Model Name: Surface Book 2
- npm config:
```ini
; "builtin" config from C:\Users\danpere\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\danpere\\AppData\\Roaming\\npm"

; "user" config from C:\Users\danpere\.npmrc

; "project" config from C:\prose\.npmrc

always-auth = true
registry = "[omitted URL]"

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v20.10.0
; npm local prefix = C:\prose
; npm version = 10.2.5
; cwd = C:\prose
; HOME = C:\Users\danpere
; Run `npm config ls -l` to show all defaults.
```

**Comment by milaninfy** [comment]
@danpere can you try replicating this problem on the latest version of `npm`? (ie. `npm i -g npm`) . 
This appears to be fixed as on this PR https://github.com/npm/npm-packlist/pull/214
