### ISSUE TITLE
[BUG] run "npm publish" then "ERR! code ETIMEDOUT"

### ISSUE THREAD

**Issue by wd3322** [npm/cli#7082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### run "npm publish" or "npm login"

![image](https://github.com/npm/cli/assets/23045774/a1dac168-6928-4cab-9690-371d57bfbb78)
![image](https://github.com/npm/cli/assets/23045774/7434214e-3ab0-405b-beb4-394f3fd6f787)
![image](https://github.com/npm/cli/assets/23045774/e6f1eb83-cd1e-478d-8730-71ef7284d1ad)

npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! network request to https://registry.npmjs.org/el-table-model failed, reason: connect ETIMEDOUT 104.16.29.34:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\asus\AppData\Roaming\npm-cache\_logs\2023-12-14T01_27_18_524Z-debug.log

### Environment

- npm: 6.14.18
- Node.js: 14.21.3
- OS Name: Windows
- System Model Name:
- npm config:

**Comment by Thecodefirst** [comment]
me too.

**Comment by linzhe141** [comment]
me too.

**Comment by haixin-fang** [comment]
me too.

**Comment by liluanhui** [comment]
me too.

**Comment by Thecodefirst** [comment]
Yes, please set npm config set proxy

**Comment by wd3322** [comment]
> Yes, please set npm config set proxy

兄弟是中国人吗， 这类设置我已经处理过了， 仍然没有效果

**Comment by liluanhui** [comment]
> > Yes, please set npm config set proxy
> 
> 兄弟是中国人吗， 这类设置我已经处理过了， 仍然没有效果

兄弟可以发布了，什么也没处理，我刚试了重新 publish 没问题。

**Comment by wd3322** [comment]
> > > Yes, please set npm config set proxy
> > 
> > 
> > 兄弟是中国人吗， 这类设置我已经处理过了， 仍然没有效果
> 
> 兄弟可以发布了，什么也没处理，我刚试了重新 publish 没问题。

我还是不行，难受

**Comment by tangbzai** [comment]
我这里不仅 `publish` 命令不行，就连 `npm install -g npm` 和 `npm login` 都会出现相同的错误，而且如果切换`registry`为`http://registry.npmjs.org/`的话`login`的时候可以输入用户名和密码（只是因为非 `https` 会报 `TSL` 错误，依旧登录失败）。
所以可能问题和`https`有关

---
I am not only `publish` here, but even the` npm install -g npm` and `npm login` will have the same errors, and If I change `registry` to `http://registry.npmjs.org/`, i can enter the username and password (just because the non -`https` will report the `TSL` error, it still fails). 
So i think the problem may be related to `https`

**Comment by wd3322** [comment]
> 我这里不仅 `publish` 命令不行，就连 `npm install -g npm` 和 `npm login` 都会出现相同的错误，而且如果切换`registry`为`http://registry.npmjs.org/`的话`login`的时候可以输入用户名和密码（只是因为非 `https` 会报 `TSL` 错误，依旧登录失败）。 所以可能问题和`https`有关
> 
> I am not only `publish` here, but even the` npm install -g npm` and `npm login` will have the same errors, and If I change `registry` to `http://registry.npmjs.org/`, i can enter the username and password (just because the non -`https` will report the `TSL` error, it still fails). So i think the problem may be related to `https`

确实如此，一开始我怀疑是自己的问题，现在想想应该不是，各种办法我都尝试了，切换过node14/16/18/20，npm6/8/10等版本，翻墙、连接手机热点(ipv6)、设置proxy，结果全都是超时

**Comment by Pursuemc** [comment]
设置代理之后成功了。

**Comment by huqiliang** [comment]
> 设置代理之后成功了。

咋弄的？我和楼上一样 各种方法都试了 还是不行

**Comment by it-chenliang** [comment]
我也遇到这个问题了，现在无论是npm login还是npm install或是npm adduser都是这个ETIMEDOUT错误，然后我刚刚看到有人说他也遇到这个问题了，就切换到手机热点可以使用，我抱着尝试的心态试了下，结果还真的可以了，回头来看好像错误提示里有说是`This is a problem related to network connectivity.`网络问题。
![image](https://github.com/npm/cli/assets/34783722/7fea1d6e-76cd-41a4-b8eb-e77717c3249e)

**Comment by it-chenliang** [comment]
> > 设置代理之后成功了。
> 
> 咋弄的？我和楼上一样 各种方法都试了 还是不行

试试连手机热点，我反正用手机热点是可以了

**Comment by linzhe141** [comment]
今天能够pnpm install 下载了，npm install还是不行，昨天这两个都不行，都说网络问题
不过pnpm i 显示downloaded显示0，不知道是不是没有走网络下载
![image](https://github.com/npm/cli/assets/40790268/93265b48-3138-46cc-bd75-9483e3f948c5)

> 我这里不仅 `publish` 命令不行，就连 `npm install -g npm` 和 `npm login` 都会出现相同的错误，而且如果切换`registry`为`http://registry.npmjs.org/`的话`login`的时候可以输入用户名和密码（只是因为非 `https` 会报 `TSL` 错误，依旧登录失败）。 所以可能问题和`https`有关
> 
> I am not only `publish` here, but even the` npm install -g npm` and `npm login` will have the same errors, and If I change `registry` to `http://registry.npmjs.org/`, i can enter the username and password (just because the non -`https` will report the `TSL` error, it still fails). So i think the problem may be related to `https`

**Comment by huqiliang** [comment]
> > > 设置代理之后成功了。
> > 
> > 
> > 咋弄的？我和楼上一样 各种方法都试了 还是不行
> 
> 试试连手机热点，我反正用手机热点是可以了

可以了 多谢 手机热点我之前试过不行。

其他类似问题朋友 建议手机热点 多试几次

**Comment by linzhe141** [comment]
> 设置代理之后成功了。

怎么设置代理？

**Comment by xiaoshuoyiyi** [comment]
我试了，手机热点也不行

**Comment by Lucas0819** [comment]
如果现象为可以通过浏览器打开 https://registry.npmjs.org ，但是执行命令`npm ping`失败，有可能是npm命令没有被成功的代理。
设置npm的proxy为本地VPN工具的代理端口：
```
npm config set proxy http://127.0.0.1:7890
```
亲测有效。

**Comment by xiaoshuoyiyi** [comment]
> 如果现象为可以通过浏览器打开https://registry.npmjs.org ，但是执行命令`npm ping`失败，有可能是npm命令没有被成功的代理。 设置npm的代理为本地VPN工具的代理端口：
> 
> ```
> npm config set proxy http://127.0.0.1:7890
> ```
> 
> 亲测有效。

你也用的Clash Verge？

**Comment by Lucas0819** [comment]
> > 如果现象为可以通过浏览器打开https://registry.npmjs.org ，但是执行命令`npm ping`失败，有可能是npm命令没有被成功的代理。 设置npm的代理为本地VPN工具的代理端口：
> > ```
> > npm config set proxy http://127.0.0.1:7890
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 亲测有效。
> 
> 你也用的Clash Verge？

ClashXR

**Comment by Lucas0819** [comment]
> > 如果现象为可以通过浏览器打开https://registry.npmjs.org ，但是执行命令`npm ping`失败，有可能是npm命令没有被成功的代理。 设置npm的代理为本地VPN工具的代理端口：
> > ```
> > npm config set proxy http://127.0.0.1:7890
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 亲测有效。
> 
> 你也用的Clash Verge？

也可以尝试在VPN工具的规则匹配内，手动新增npmjs.org规则。猜测可能是近期被墙，VPN规则配置未同步。

**Comment by wd3322** [comment]
> 如果现象为可以通过浏览器打开 https://registry.npmjs.org ，但是执行命令`npm ping`失败，有可能是npm命令没有被成功的代理。 设置npm的proxy为本地VPN工具的代理端口：
> 
> ```
> npm config set proxy http://127.0.0.1:7890
> ```
> 
> 亲测有效。

成功了， 这条操作是目前最有效的， 不知道为何工信部要去墙npm

**Comment by chengliang666** [comment]
通过浏览器打开 https://registry.npmjs.org/， 获取IP地址，在本地hosts配置代理就可以了。
![IMG_20231215_235837](https://github.com/npm/cli/assets/35751327/c7910b35-040f-4a91-8cac-33c6db515fd4)
![IMG_20231215_235921](https://github.com/npm/cli/assets/35751327/c4b4e41d-c365-41fe-97f6-b6bb3b0c0641)

**Comment by chengliang666** [comment]
通过浏览器打开https://registry.npmjs.org/ ，获取IP地址，然后在本地hosts配置代理就可以了，亲测有效。
`104.16.28.34  registry.npmjs.org`

**Comment by milaninfy** [comment]
**Closing:** this looks to be an issue with the registry which is outside the scope of this repo. For registry support please go to [npmjs.com/support](https://www.npmjs.com/support). If you believe this is a bug with the cli, please provide further clarifying details.

**Comment by MuYi086** [comment]
我是使用以下俩个操作，然后可以正常npm login 和publish了
1. 使用ping.cn拿到了延迟比较低的ip，然后粘贴到hosts;
2. 更换dns，使用1.1.1.1或者8.8.8.8,这俩个对国外网站比较友好
之后可以尝试访问https://registry.npmjs.org，能正常返回200基本就通了
