### ISSUE TITLE
[BUG] npm addUser redirects to login instead of sign up

### ISSUE THREAD

**Issue by Lysoun** [npm/cli#7104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When I run `npm adduser` without specifying any more options, I am told to create an account and then, redirected to the login page:

```bash
➜  /tmp npm adduser
npm notice Log in on https://registry.npmjs.org/
Create your account at:
https://www.npmjs.com/login?next=/login/cli/caead4c5-9b9b-41a7-a384-315e02bfafb0
Press ENTER to open in the browser...
```

The same happens if I specify the `auth-type` option with `web`.

I am provided with the same kind of link when I run `npm login`:

```bash
➜  /tmp npm login
npm notice Log in on https://registry.npmjs.org/
Login at:
https://www.npmjs.com/login?next=/login/cli/4ee429dd-4efc-4f5b-b3ef-e186e3af4e52
Press ENTER to open in the browser...
```

### Expected Behavior

Following the [documentation](https://docs.npmjs.com/cli/v9/commands/npm-adduser), `npm adduser` should help users to create accounts so I'm expecting to be redirected to the [sign up](https://www.npmjs.com/signup) page instead of the [login](https://www.npmjs.com/login/) one. Furthermore, the commands `adduser` and `login` should be completely different commands so I find it odd that they redirect users to the same link.

### Steps To Reproduce

1. Run `npm adduser`
2. You are given a link to the login page

### Environment

- npm: 9.6.7
- Node.js: v18.17.0
- OS Name: macOS Monterey version 12.6.1
- System Model Name: Macbook Pro
- npm config:
```ini
; node bin location = /Users/myUser/.nvm/versions/node/v18.17.0/bin/node
; node version = v18.17.0
; npm local prefix = /private/tmp
; npm version = 9.6.7
; cwd = /private/tmp
; HOME = /Users/myUser
```

**Comment by wraithgar** [comment]
This was fixed in subsequent versions of npm:

```
$ npm adduser
npm notice Log in on https://registry.npmjs.org/
Create your account at:
https://www.npmjs.com/login?next=/login/cli
```

**Comment by Lysoun** [comment]
> This was fixed in subsequent versions of npm:
> 
> ```
> $ npm adduser
> npm notice Log in on https://registry.npmjs.org/
> Create your account at:
> https://www.npmjs.com/login?next=/login/cli
> ```

The example you are giving is exactly the behaviour I noticed in my message and it is misleasing because adduser should redirect to https://www.npmjs.com/signup and it is redirecting to https://www.npmjs.com/login/. It is the issue.

**Comment by wraithgar** [comment]
Ah right this looks like it was due to a change in the way login works on the npmjs website.  The switch to web auth is the reason it does things this way is so that the `--auth-type legacy` still works.

Creating new accounts through the cli itself is not recommended, this is mostly a legacy command.  There is a 'create account' link on the login page you are sent to that should still work if you truly are creating a new account for the first time.  Given that the recommended way to create accounts is through the website, this is not likely something that we are going to spend time to tweak.
