### ISSUE TITLE
[FEATURE] Make it so the command in the "npm available update" message can be changed.

### ISSUE THREAD

**Issue by fgclue** [npm/cli#7108]
Hello. I'd like to request a feature where you can change the command on the npm update available message, I installed npm with pacman, but it tells me to upgrade with `npm i -g npm@latest`. I'd like to be able to change that to `pacman -u npm`. I'd also like to change it so the command message does not show up, so I know that I should update but don't have the command, because I update it with my other packages when I run `pacman -Syu`

This is the "update available message":
![image](https://github.com/npm/cli/assets/87581499/37637141-7fc0-481d-aa00-07fbad3a9d94)

The reason I want this feature is because today I tried updating my system and had to re-install npm, because I failed to fix it. Thanks!

NPM version: 10.2.5
Node version: v21.4.0
Kernel: Linux 6.6.1-arch1-1
Distro: Arch Linux
```[tasklist]
### Tasks
- [ ] Add setting for changing the command
- [ ] Add setting for removing the "Run <command> to update!" message
```

**Comment by ljharb** [comment]
Why are you using pacman to manage npm? It’s not officially distributed there. npm should only come with node, or be installed with npm or with npm’s install script.

**Comment by wraithgar** [comment]
You can disable the update check with `--no-update-notifier` or `--update-notifier=false` but we don't plan on adding any functionality to customize that message.
