### ISSUE TITLE
[DOCS] when will aurgmentless `npm install` update lock file? 

### ISSUE THREAD

**Issue by skyboyer** [npm/cli#7117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Problem, not another kind of Docs Problem.

- [X] This is a CLI Docs Problem.

### Description of Problem

Up to my understanding(am I accurate?) argumentless `npm install` should update lock file if and only if current state of lock file data is not compatible with semver ranges defined in `package.json`

For example, package.json lists `"abc": ">15"` but package-lock.json has it as `"abc": { "version": "0.5.0"`

Maybe there are more nuances(e.g. how "overrides" section works in modern NPM) but I don't see anything mentioned neither in [npm-install](https://docs.npmjs.com/cli/v10/commands/npm-install) article nor for [package-lock.json](https://docs.npmjs.com/cli/v10/configuring-npm/package-lock-json)

### Affected URL

https://docs.npmjs.com/cli/v10/commands/npm-install

**Comment by skyboyer** [comment]
I tried to find existing github issue ticket with discussion on this, but obviously searching for "npm install lock update" gives _too many_ results and I have no idea how to narrow.

Also I tried to dig into https://github.com/npm/arborist/ which I believe is responsible for checking if lock file matches package.json, but I've lost to its complexity and my lack of the knowledge.

**Comment by wraithgar** [comment]
https://github.com/npm/feedback/discussions/990
