### ISSUE TITLE
[BUG] <Failure installing packages>

### ISSUE THREAD

**Issue by dwalbeck** [npm/cli#712]
# What / Why

> n/a

## When

* n/a

## Where

* n/a

### Current Behavior

* n/a

### Steps to Reproduce

* n/a

### Expected Behavior

* n/a

## Who

* n/a

## References

[npm-debug.log](https://github.com/npm/cli/files/4088737/npm-debug.log)
* n/a

**Comment by DanielRuf** [comment]
The file is currently too big to check. But I see that you use npm 3 which is very old. Please upgrade npm to the latest version.
