### ISSUE TITLE
[BUG] Can't do an unattended unpublish, silent failure when using an automate token

### ISSUE THREAD

**Issue by unilynx** [npm/cli#7120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I'm setting up a workflow to publish/unpublish 'alpha' versions of multiple packages. I can automate a batch of npm publish, but not npm unpublish:

With a 'Publish' token:

```
$ npm unpublish --//registry.npmjs.org/:_authToken=<PUBLISHTOKEN> @webhare/std@0.504.0-alpha-20240105-105618
Authenticate your account at:
https://www.npmjs.com/auth/cli/d6ae9f8f-5229-4abf-b325-6ef12980ab12
Press ENTER to open in the browser...

```
here it works but I have to do a manual OTP authentication, which would be cumbersome with a dozen packages

with an 'Automate' token

```
$ npm unpublish --//registry.npmjs.org/:_authToken=<AUTOMATE TOKEN> @webhare/std@0.504.0-alpha-20240105-114324
- @webhare/std@0.504.0-alpha-20240105-114324
```

No error is reported, but the package is not actually unpublished. `--verbose` does show a 404 which is apparently ignored

```
npm http fetch GET 200 https://registry.npmjs.org/@webhare%2fstd?write=true 455ms (cache updated)
npm http fetch GET 200 https://registry.npmjs.org/@webhare%2fstd?write=true 209ms (cache updated)
npm http fetch PUT 404 https://registry.npmjs.org/@webhare%2fstd/-rev/10-a47c9bec14a459ca2aa7770e0cd428e4 168ms
- @webhare/std@0.504.0-alpha-20240105-114324
npm verb exit 0
npm info ok 
```

### Expected Behavior

Automate tokens working with npm unpublish too. If this is intentional and will never be available, I'd expect an error message from NPM

### Environment

- npm: 10.2.4
- Node.js: v21.5.0
- OS Name: 14.1.1 (23B2082)
- System Model Name: Mac
- npm config:
```ini
; "builtin" config from /opt/homebrew/lib/node_modules/npm/npmrc

prefix = "/opt/homebrew" 

; node bin location = /opt/homebrew/Cellar/node/21.5.0/bin/node
; node version = v21.5.0
; npm local prefix = /Users/arnold/projects/webhare-cue
; npm version = 10.2.4
; cwd = /Users/arnold/projects/webhare-cue
; HOME = /Users/arnold
; Run `npm config ls -l` to show all defaults.
```

**Comment by luyangliuable** [comment]
There is a issue going on with npm packages can't be unpublished anymore once they are published. I am not sure if this is resolved. It was due to a package that listed every npm package as its dependency

**Comment by wraithgar** [comment]
This appears to be an issue w/ the [npm registry itself](https://www.npmjs.com/support) and how you have auth set up, specifically OTP and automation tokens.  This is not an npm cli bug.

**Comment by unilynx** [comment]
@wraithgar but I still wouldn't expect a success status/exit code 0 after a 404 error for the PUT ?

**Comment by wraithgar** [comment]
This is a tricky situation because npm does not know the difference between a 404 and an invalid token (sending different response codes from the registry would be an information leak about the existence of a private package).  Currently if you try to unpublish a version that does not exist, npm exits cleanly because that version doesn't exist, which is what the end result of unpublish is asking for.  Changing this will change that behavior for npm, and would be considered a breaking change.
