### ISSUE TITLE
[BUG] npm install -g npm@latest Does not Install Latest Version of NPM

### ISSUE THREAD

**Issue by sophisticatedOscillator** [npm/cli#713]
# What / Why
When I attempt to update npm to the latest version I am advised the package has updated but when I go to check it returns the same version before the update. There are no errors to advise there was an error during the update.

What I can tell you is I'm not very confident with the inner workings of NPM itself. I know enough to run it if npm itself is configured completely.

About two years ago I started running my code in a different directory, same user (single user device) because I kept running into access issues and having to sudo every time I wanted to install any dependency. I don't recall remapping anything in any $PATH or any npm configurations.

What I have tried

hash -r to clear terminal cache
Restarting terminal/restarting device
> n/a

## When
```
ianbuss @ Ians-MacBook-Air in ~ [10:23:44]
$ npm -v
6.10.0

# ianbuss @ Ians-MacBook-Air in ~ [10:23:49]
$ sudo npm install -g npm@latest
Password:
/Users/ianbuss/.npm-global/bin/npm -> /Users/ianbuss/.npm-global/lib/node_modules/npm/bin/npm-cli.js
/Users/ianbuss/.npm-global/bin/npx -> /Users/ianbuss/.npm-global/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.13.6
updated 1 package in 11.955s

# ianbuss @ Ians-MacBook-Air in ~ [10:29:29]
$ npm -v
6.10.0
```

**Comment by DanielRuf** [comment]
sudo should be avoided. Please check the content of `$PATH`.

**Comment by delagen** [comment]
Also has same issue on Windows 10
```
C:\Users\delag>npm i npm -g
D:\projects\node-global\npm -> D:\projects\node-global\node_modules\npm\bin\npm-cli.js
D:\projects\node-global\npx -> D:\projects\node-global\node_modules\npm\bin\npx-cli.js
+ npm@6.14.1
updated 2 packages in 20.955s

C:\Users\delag>npm -v
6.14.0
```

**Comment by DanielRuf** [comment]
@Delagen please retry it, this might have been a cache issue with the reigstry, the version was released 10 hours ago.

https://github.com/npm/cli/releases/tag/v6.14.1

**Comment by DanielRuf** [comment]
@Delagen please retry it, this might have been a cache issue with the registry, the version was released 10 hours ago.

https://github.com/npm/cli/releases/tag/v6.14.1

**Comment by delagen** [comment]
@DanielRuf No, this error occurs with previous version also. I resolved it with manually replace with contents of tar archive

**Comment by sophisticatedOscillator** [comment]
@DanielRuf I have completely uninstalled npm & node then reinstalled NodeJS from the MacOS installer at the current version 13.10.1. `npm -v`  now returns `6.13.7`
When I run `npm i -g npm` restart my computer after a success message, reload the terminal and run `npm -v` it does not provide the version # that was installed prior to the restart.
You had stated to check my $PATH variables.  
`/Users/ianbuss/bin:/usr/local/bin:/Users/ianbuss/.composer/vendor/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin` is what I currently get when I run `echo $PATH`
I have no idea whether that is a good or bad PATH assignment.

**Comment by DanielRuf** [comment]
6.14.2 is the latest version. https://www.npmjs.com/package/npm?activeTab=versions

What happens when you do `npm i -g npm@latest`?

Please provide the output that you see in your terminal.

**Comment by delagen** [comment]
@DanielRuf Found that fucking `yarn` was overwrite paths in npm link files, so it's started from yarn cache. Removed that fucking manager totally, now it predictive and fine)

**Comment by DanielRuf** [comment]
> @DanielRuf Found that fucking `yarn` was overwrite paths in npm link files, so it's started from yarn cache. Removed that fucking manager totally, now it predictive and fine)

Hey, calm down =) The first entry in PATH pointing to a binary always wins. So you should make sure that you use the right package manager and decide for one (yarn or npm for global packages) ;-)

**Comment by DanielRuf** [comment]
But I guess we can close this issue as the original reporter did not provide any feedback. Your issues are different (always check your PATH variable).

**Comment by sophisticatedOscillator** [comment]
@DanielRuf  Tried that as well w/ no dice (pending restart and I'll edit once I confirm restart)
```
# ianbuss @ Ians-MacBook-Air in ~ [13:46:15]
$ npm i -g npm@latest
/Users/ianbuss/.npm-global/bin/npx -> /Users/ianbuss/.npm-global/lib/node_modules/npm/bin/npx-cli.js
/Users/ianbuss/.npm-global/bin/npm -> /Users/ianbuss/.npm-global/lib/node_modules/npm/bin/npm-cli.js
+ npm@6.14.2
updated 1 package in 11.566s

# ianbuss @ Ians-MacBook-Air in ~ [22:55:36]
$ npm -v
6.13.7
```

// Edit: I restarted and it still spits back 6.13.7 :(

**Comment by DanielRuf** [comment]
@ianpatrickbuss please check your `$PATH`.

**Comment by ianpatrickbuss** [comment]
Hey @DanielRuf  I didn't get a notification for your response and then totally forgot I opened up this issue.  
`/Users/ianbuss/bin:/usr/local/bin:/Users/ianbuss/.composer/vendor/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin`
That is what `echo $PATH` returns in my console.

**Comment by sophisticatedOscillator** [comment]
Sorry ya'll, BASH is not my specialty.  It was definitely my $PATH variable.  I guess somewhere I changed a config file.  I found this article really useful to resolve my issue in case anyone else ever comes across it. Specifically, STEP 3: https://medium.com/@jagatjyoti.1si13cs040/npm-g-install-npm-package-not-working-as-desired-why-why-why-19795abf0b59
