### ISSUE TITLE
[BUG] `npm audit` erroneously reports issue when workspace named the same as an npm package

### ISSUE THREAD

**Issue by dmeehan1968** [npm/cli#7131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When a workspace name conflicts with an installed npm package, `npm audit` will produce an erroneous vulnerability if one exists for said package.

```
npm WARN ignoring workspace config at /Users/[REDACTED]/Projects/Todo-Experiments/packages/svelte/.npmrc 
# npm audit report

svelte  <3.49.0
Severity: moderate
Svelte vulnerable to XSS when using objects during server-side rendering - https://github.com/advisories/GHSA-wv8q-r932-8hc7
fix available via `npm audit fix`
packages/svelte

1 moderate severity vulnerability

To address all issues, run:
  npm audit fix
```

### Expected Behavior

npm audit should not show errors when there is a name clash with workspaces.

### Steps To Reproduce

1. mkdir [rootname]
2. cd [rootname]
3. `npm init`
4. `npm init -w packages/svelte`
5. `cd packages/svelte`
6. `npm i svelte@latest`
7. `npm audit`

### Environment

- npm: 10.3.0
- Node.js: 18.18.1
- OS Name: macOS 14.1.2
- System Model Name: macbook Pro M1
- npm config:
```ini
; node bin location = /Users/[REDACTED]/.nvm/versions/node/v18.18.1/bin/node
; node version = v18.18.1
; npm local prefix = /Users/[REDACTED]/Desktop/test
; npm version = 10.3.0
; cwd = /Users/[REDACTED]/Desktop/test
; HOME = /Users/[REDACTED]
; Run `npm config ls -l` to show all defaults.
```

**Comment by wraithgar** [comment]
This is on purpose. npm has no way of knowing that workspace isn't the real `svelte` package.  The audit ecosystem is keyed by name, that's how it works.  If I installed lodash from its git repo I'd still expect the same warnings as if I'd installed from the npm registry.

Scopes (aka `@namespace/package`) are the solution to name collisions like this, it's highly recommended you utilize them.

**Comment by dmeehan1968** [comment]
@wraithgar Please can I suggest that you review and expand the documentation for [workspaces](https://docs.npmjs.com/cli/v10/using-npm/workspaces) because it makes no mention of this behaviour - indeed, the examples show this exact usage without mentioning the potential for conflict.

Also your mention of 'namespaces' is unhelpful because this doesn't appear to be terminology used by npm - it uses 'scopes'.  I actually can't reconcile what you've said with the scopes documentation and how that impacts how I would use workspaces.

What I was trying to do here was segment a project where I'm evaluating different dev frameworks - I've not intention of publishing.  Perhaps workspaces is the wrong way to go about this and I'm misusing npm.
