### ISSUE TITLE
npm WARN EBADENGINE Unsupported engine

### ISSUE THREAD

**Issue by mdodge-ecgrow** [npm/cli#7134]
I can't tell if this is a bug or something I am doing wrong or what.

I am simply running `sudo npm i` in my node server to install all the required packages.  I keep getting this warning: 'npm WARN EBADENGINE Unsupported engine' for multiple packages.  And the in the warning, the "current" version of Node is wrong.  I have followed every tutorial I can find to uninstall all old versions of Node.  Also I am using nvm to allow multiple node versions.  I am using v20.11.0 with nvm.

My full warning/error message looks like this:
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'express-rate-limit@7.1.5',
npm WARN EBADENGINE   required: { node: '>= 16' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'jwks-rsa@3.1.0',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'lru-cache@8.0.5',
npm WARN EBADENGINE   required: { node: '>=16.14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'tsx@4.7.0',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'typescript@5.3.3',
npm WARN EBADENGINE   required: { node: '>=14.17' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
```
![image](https://github.com/npm/cli/assets/57459547/14ddca1e-881d-4228-a746-73b02295c73a)

Also, if it matters, this is what `nvm list` shows:
![image](https://github.com/npm/cli/assets/57459547/95a3ea55-055f-41cc-bd5a-78ab47becdc1)

**Comment by ljharb** [comment]
You should never use `sudo` with nvm (or at all). Just `npm install`.

**Comment by wraithgar** [comment]
This does not appear to be an npm problem, but an issue between your os setup and running the correct node version.  It's possible `sudo` is the problem, as it likely bypasses your local user nvm setup.

**Comment by mdodge-ecgrow** [comment]
Yep, you guys were right.  If anyone comes with the same problem, here was my resolution.
I was using `sudo npm i` because it was failing to make the node_modules directory with a permissions error.  So I though 'sudo' would fix that.  Instead, I made my user account the owner of the folder and subfolders.  Then ran `npm i` again and everything worked as expected.
