### ISSUE TITLE
Error: Warning: Ignoring extra certs

### ISSUE THREAD

**Issue by kossa** [npm/cli#7135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When I run: npm --version I got this error:

Warning: Ignoring extra certs from `/Users/mac/.config/valet/CA/LaravelValetCASelfSigned.pem`, load failed: error:80000002:system library::No such file or directory
10.2.4

<img width="1437" alt="image" src="https://github.com/npm/cli/assets/1175584/a0a7d559-9fcb-48c2-aaec-9b0b04917409">

### Expected Behavior

Just the version

### Steps To Reproduce

Dont know what's the steps exactly

### Environment

- npm: 10.2.4
- Node.js: v21.5.0
- OS Name: MacOs 
- System Model Name: Sonoma 14.2.1
- npm config:
```ini
Warning: Ignoring extra certs from `/Users/mac/.config/valet/CA/LaravelValetCASelfSigned.pem`, load failed: error:80000002:system library::No such file or directory
; "builtin" config from /opt/homebrew/lib/node_modules/npm/npmrc

prefix = "/opt/homebrew"

; "user" config from /Users/mac/.npmrc

audit = false

; node bin location = /opt/homebrew/Cellar/node/21.5.0/bin/node
; node version = v21.5.0
; npm local prefix = /Users/mac
; npm version = 10.2.4
; cwd = /Users/mac
; HOME = /Users/mac
; Run `npm config ls -l` to show all defaults.
```

**Comment by SurgeKalva-AIML** [comment]
Hey @kossa, I am getting the same issue and I believe it is what is preventing to run my hugo server. Any updates or solutions for this problem?

**Comment by kossa** [comment]
@a186929 I fixed my issue recently, I found in my .zshrc this line then I commented it :)

<img width="940" alt="image" src="https://github.com/npm/cli/assets/1175584/fb1ee624-db69-4374-a3e9-6162f0eeb998">

Otherwise add: `export NODE_EXTRA_CA_CERTS=""` it should fix it too
