### ISSUE TITLE
Error when tried to download artillery

### ISSUE THREAD

**Issue by MellyFinnese** [npm/cli#7136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Id Just try different cmds and args with the artillery repo 

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:3.5.2
- Node.js:4.2.6
- OS Name:Tsurugi
- System Model Name:Dell Optiplex
1161 error Linux 5.4.2-050402-tsurugi
1162 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "artillery@latest"
1163 error node v4.2.6
1164 error npm  v3.5.2
1165 error code EMISSINGARG
1166 error typeerror Error: Missing required argument #1
1166 error typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
1166 error typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
1166 error typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
1166 error typeerror     at /usr/share/npm/lib/install/deps.js:457:7
1166 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
1166 error typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
1166 error typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
1166 error typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
1166 error typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
1166 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
1167 error typeerror This is an error with npm itself. Please report this error at:
1167 error typeerror     <http://github.com/npm/npm/issues>
1168 verbose exit [ 1, true ]

**Comment by ljharb** [comment]
Both node 4 and npm 3 are many, many, many years out of date. You should be on node 18, 20, or 21; and npm 10.
