### ISSUE TITLE
[BUG] Issues with node-gyp < 5.0.5

### ISSUE THREAD

**Issue by jnardone** [npm/cli#714]
# What / Why
On MacOS at least, there are issues with Python version detection that break builds.  Leads to this scenario: https://github.com/nodejs/node-gyp/issues/1917

## When
For example: use the 0.25.1 argon2 build, on MacOS, when your default interpreter is Python 3.6 and not 2.7.

## Where
latest NPM 6.13.6

## Who
@npm/cli

Can we make sure the next patch bump of the NPM CLI has node-gyp 5.0.6 or higher?

**Comment by ljharb** [comment]
Pretty sure it wouldn’t be a patch bump unless npm is already on a lower version of node-gyp 5.

**Comment by jnardone** [comment]
@ljharb it's 5.0.5:

https://github.com/npm/cli/blob/latest/package.json#L96

**Comment by rvagg** [comment]
5.1.0 is out, has some nicer noproxy support

FYI the only difference with 6.1.0 is that v6 picks Python 3 where both are available where v5 picks Python 2. They both support 2 and 3, it's just order of preference. Otherwise the diff is extremely minimal.

v7 will be out soon with a big change to GYP internals and there'll be a bit more risk in that so probably won't be ready for npm at least initially.

**Comment by DanielRuf** [comment]
I fail to see how this is an npm issue.

**Comment by ljharb** [comment]
I believe npm bundles node-gyp, and that's what it uses for `npm rebuild`?

**Comment by DanielRuf** [comment]
So if I understand it correctly it is about bumping the node-gyp version bundled with npm?

**Comment by jnardone** [comment]
Yes.

**Comment by DeeDeeG** [comment]
Hello, all.

I believe this issue can be closed.

`node-gyp` 5.1.0 shipped in `npm` 6.14.2. See the changelog:
- https://github.com/npm/cli/blob/latest/CHANGELOG.md#6142-2020-03-03

**Comment by DeeDeeG** [comment]
Actually, this is asking for a patch-level bump for the 6.13.x series, but the version I mentioned with the fix is in the 6.14.x series.

Sorry about that.

**Comment by DanielRuf** [comment]
Only the current / last version is supported afaik. You should be able to upgrade / update npm to 6.14.x.

**Comment by DeeDeeG** [comment]
Well this was done in the 6.13 series, too (`npm` 6.13.7 bumped `node-gyp` to 5.0.7).

https://github.com/npm/cli/blob/latest/CHANGELOG.md#6137-2020-01-28

So this can definitely be closed!

**Comment by ljharb** [comment]
Additionally, npm 7 will use node-gyp v7 (see https://github.com/npm/cli/issues/287#issuecomment-706015622).
