### ISSUE TITLE
[BUG] Unable to configure hook

### ISSUE THREAD

**Issue by Goralt** [npm/cli#7145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When I'm trying to configure a new npm hook using `npm hook add <package> <hook-url> <secret>` I'm getting a 401 error when I login into my npm account my user is connected to paid org so It should work for me.
I also tried to use the yarn registry and got the same error.

### Expected Behavior

I expected that the hook will be configure.

### Steps To Reproduce

login to your npm account using `npm login`
run `npm hook add <package> <hook-url> <secret>`

### Environment

- npm: 10.3.0
- Node.js: 18.17.1
- OS Name: Ubuntu 20.04
- System Model Name: Macbook Pro
- npm config:
```ini
; "user" config from /Users/goral/.npmrc

//registry.npmjs.org/:_authToken = (protected) 
//registry.yarnpkg.com/:_authToken = (protected) 

; node bin location = /Users/goral/.nvm/versions/node/v18.17.1/bin/node
; node version = v18.17.1
; npm local prefix = /Users/goral/Development/npm-webhook-test/goral-personal-test
; npm version = 10.3.0
; cwd = /Users/goral/Development/npm-webhook-test/goral-personal-test
; HOME = /Users/goral
; Run `npm config ls -l` to show all defaults.
```

**Comment by wraithgar** [comment]
This does not appear to be an issue w/ the npm cli itself.  This repo is for tracking bugs w/ the cli, not the registry.  Registry issues should go through https://www.npmjs.com/support
