### ISSUE TITLE
[BUG] NPX command sometime it can't find packages

### ISSUE THREAD

**Issue by 64BitAsura** [npm/cli#7155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Sometime npx command fails to find some packages alone
![Screenshot 2024-01-18 at 16 52 39](https://github.com/npm/cli/assets/6957824/60970fe2-aca6-472e-a8ab-f6735677d70b)

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by wraithgar** [comment]
There are no steps to reproduce this, so we can't triage this.  Anecdotally this can happen in a package that defines a binary but you have not installed `node_modules` properly yet.
