### ISSUE TITLE
Package-lock.json file affecting npm install

### ISSUE THREAD

**Issue by tdammon** [npm/cli#716]
I'm working off of two branches, `master` and `improvement`. I noticed that the package-lock files were not the same between the two branches even though the package.json files are the same.  

In my `master` branch I deleted my package-lock.json and node-modules and ran `npm install`.  My app works fine in this branch.  Now if I switch to the `improvement` branch and pull from master, delete the package-lock.json and node-modules and run `npm install` the two package-lock.json files are still different (despite identical package.json files) and the improvement branch gets the following error when running:
```
There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "webpack": "4.41.2"

Don't try to install it manually: your package manager does it automatically.
However, a different version of webpack was detected higher up in the tree:
```

I am able to resolve the issue by copying the package-lock.json from `master` and pasting it into `improvement` and then running `npm install`.

However, I am not sure why the package-lock.json file would be effecting the `npm install` and I am not sure why `npm install` would create different package-lock.json files when package.json is the same.

**Comment by ljharb** [comment]
Installs at different times can create different lockfiles, so that’s not an abnormal occurrence, but that doesn’t sound like your issue.

What’s the `diff --name-only` between the branches?

**Comment by tdammon** [comment]
I believe the only relevant difference between the two is the package-lock.json 

README.md
package-lock.json
src/components/modals/DocshareModal.js
src/components/modals/DocshareModal.test.js
src/components/modals/SendPmSuccessModal.js
src/components/modals/SendPmSuccessModal.module.css
src/components/modals/SendPmSuccessModal.test.js
src/components/modals/__snapshots__/DocshareModal.test.js.snap
src/components/modals/__snapshots__/SendPmSuccessModal.test.js.snap
src/components/sendProjectManagerEmail/SendProjectManagerEmail.test.js
src/containers/adminCreateOrg/AdminCreateOrg.js
src/containers/editOrganization/EditOrganization.js
src/context/AdminContext.js

**Comment by ljharb** [comment]
yeah that's very strange :-/ it might help if you provided both `packages-lock.json` contents in `<details>` tags, for npm folks to debug?

**Comment by tdammon** [comment]
I'm trying to find a way to display the relevent information.  The `pack-lock.json` files are both around 20,000 lines which exeeds the maximum number of charecters.  Any ideas how I can extract the pertinent info?

**Comment by ljharb** [comment]
ah, true. maybe you could add them to a gist?

**Comment by tdammon** [comment]
Yes that is a great idea.  The top link is for the `master` branch and the second link is for the `improvement` branch.  Both `package-lock.json` files before running `npm install`

[master](https://gist.github.com/tdammon/b43b7ea4780652a4bcf0a7d75144451c)

[improvement](https://gist.github.com/tdammon/03ded8b6f9f4fe2d25e0c38c9d029189)
