### ISSUE TITLE
[DOCS] The latest version of python (3.12) doesn't support node-gyp

### ISSUE THREAD

**Issue by harshajk** [npm/cli#7161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Problem, not another kind of Docs Problem.

- [X] This is a CLI Docs Problem.

### Description of Problem

I am trying the below 

npm install

However, I see the below error

npm ERR! ModuleNotFoundError: No module named 'distutils

Reason: The latest version of python (3.12) doesn't support node-gyp. 

### Potential Solution

node-gyp is currenlty supported only up to python version 3.11

### Affected URL

https://www.npmjs.com/package/node-gyp#on-windows

**Comment by wraithgar** [comment]
That package is not maintained by npm.  Its source repo is at https://github.com/nodejs/node-gyp

**Comment by harshajk** [comment]
Sure, will raise it there. Thanks
