### ISSUE TITLE
24 packages are looking for funding and npm WARN cli npm v10.3.0 does not support Node.js v18.16.1.

### ISSUE THREAD

**Issue by b9Joker108** [npm/cli#7164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Here is a pastebin of my shell inputs and outputs:
https://pastebin.com/djsC71Fv

### Expected Behavior

Well, I didn't expect to get the warning and error output. I think I need a version manager,mso I can run multiple versions in Termux on my Android system.

### Steps To Reproduce

Please refer Pastebin linkage.

### Environment

- npm: npm -v                                                                           ✔  at 14:56:06  
npm WARN cli npm v10.3.0 does not support Node.js v20.2.0. This version of npm supports the following node versions: `^18.17.0 || >=20.5.0`. You can find the latest version at https://nodejs.org/.
10.3.0
- Node.js: v20.2.0
- OS Name: OneUI 5.1.1 (Android 13)
- System Model Name: Samsung Galaxy Tab S9 Ultra 
- npm config: npm WARN cli npm v10.3.0 does not support Node.js v20.2.0. This version of npm supports the following node versions: `^18.17.0 || >=20.5.0`. You can find the latest version at https://nodejs.org/.
; "user" config from /data/data/com.termux/files/home/.npmrc

foreground-scripts = true

; node bin location = /data/data/com.termux/files/usr/bin/node
; node version = v20.2.0
; npm local prefix = /data/data/com.termux/files/home
; npm version = 10.3.0
; cwd = /data/data/com.termux/files/home
; HOME = /data/data/com.termux/files/home
; Run `npm config ls -l` to show all defaults.
```ini
; copy and paste output from `npm config ls` here
```

**Comment by b9Joker108** [comment]
npm config ls -l                                                                 ✔  at 15:10:15  
npm WARN cli npm v10.3.0 does not support Node.js v20.2.0. This version of npm supports the following node versions: `^18.17.0 || >=20.5.0`. You can find the latest version at https://nodejs.org/.
; "default" config from default values

_auth = (protected)
access = null
all = false
allow-same-version = false
also = null
audit = true
audit-level = null
auth-type = "web"
before = null
bin-links = true
browser = null
ca = null
cache = "/data/data/com.termux/files/home/.npm"
cache-max = null
cache-min = 0
cafile = null
call = ""
cert = null
cidr = null
color = true
commit-hooks = true
cpu = null
depth = null
description = true
dev = false
diff = []
diff-dst-prefix = "b/"
diff-ignore-all-space = false
diff-name-only = false
diff-no-prefix = false
diff-src-prefix = "a/"
diff-text = false
diff-unified = 3
dry-run = false
editor = "vi"
engine-strict = false
fetch-retries = 2
fetch-retry-factor = 10
fetch-retry-maxtimeout = 60000
fetch-retry-mintimeout = 10000
fetch-timeout = 300000
force = false
; foreground-scripts = false ; overridden by user
format-package-lock = true
fund = true
git = "git"
git-tag-version = true
global = false
global-style = false
globalconfig = "/data/data/com.termux/files/usr/etc/npmrc"
heading = "npm"
https-proxy = null
if-present = false
ignore-scripts = false
include = []
include-staged = false
include-workspace-root = false
init-author-email = ""
init-author-name = ""
init-author-url = ""
init-license = "ISC"
init-module = "/data/data/com.termux/files/home/.npm-init.js"
init-version = "1.0.0"
init.author.email = ""
init.author.name = ""
init.author.url = ""
init.license = "ISC"
init.module = "/data/data/com.termux/files/home/.npm-init.js"
init.version = "1.0.0"
install-links = false
install-strategy = "hoisted"
json = false
key = null
legacy-bundling = false
legacy-peer-deps = false
libc = null
link = false
local-address = null
location = "user"
lockfile-version = null
loglevel = "notice"
logs-dir = null
logs-max = 10
; long = false ; overridden by cli
maxsockets = 15
message = "%s"
node-options = null
noproxy = [""]
npm-version = "10.3.0"
offline = false
omit = []
omit-lockfile-registry-resolved = false
only = null
optional = null
os = null
otp = null
pack-destination = "."
package = []
package-lock = true
package-lock-only = false
parseable = false
prefer-dedupe = false
prefer-offline = false
prefer-online = false
prefix = "/data/data/com.termux/files/usr"
preid = ""
production = null
progress = true
provenance = false
provenance-file = null
proxy = null
read-only = false
rebuild-bundle = true
registry = "https://registry.npmjs.org/"
replace-registry-host = "npmjs"
save = true
save-bundle = false
save-dev = false
save-exact = false
save-optional = false
save-peer = false
save-prefix = "^"
save-prod = false
sbom-format = null
sbom-type = "library"
scope = ""
script-shell = null
searchexclude = ""
searchlimit = 20
searchopts = ""
searchstaleness = 900
shell = "/data/data/com.termux/files/usr/bin/fish"
shrinkwrap = true
sign-git-commit = false
sign-git-tag = false
strict-peer-deps = false
strict-ssl = true
tag = "latest"
tag-version-prefix = "v"
timing = false
umask = 0
unicode = true
update-notifier = true
usage = false
user-agent = "npm/{npm-version} node/{node-version} {platform} {arch} workspaces/{workspaces} {ci}"
userconfig = "/data/data/com.termux/files/home/.npmrc"
version = false
versions = false
viewer = "man"
which = null
workspace = []
workspaces = null
workspaces-update = true
yes = null

; "user" config from /data/data/com.termux/files/home/.npmrc

foreground-scripts = true

; "cli" config from command line options

long = true

**Comment by wraithgar** [comment]
This is not an npm bug. The engines field is working as intended to let you know that npm 10 is likely to include features that don't work in your version of node.  Either use the version of npm that came with the version of node you are using, or update your node version.
