### ISSUE TITLE
[DEPS] Update dependencies for release v6.13.7

### ISSUE THREAD

**Issue by mikemimik** [npm/cli#717]
### List of Dependencies
- [`bin-links@1.1.7`](https://github.com/npm/bin-links/compare/v1.1.6...v1.1.7)
```
> npm ls bin-links
npm@6.13.6 
├── bin-links@1.1.6
├─┬ libcipm@4.0.7
│ └── bin-links@1.1.6  deduped
└─┬ libnpm@3.0.1
  └── bin-links@1.1.6  deduped
```

- [`libnpx@10.2.2`](https://github.com/npm/npx/compare/v10.2.0...v10.2.2) https://github.com/npm/cli/issues/717#issuecomment-579009527
```
> npm ls libnpx
npm@6.13.6 
└── libnpx@10.2.0
```

- [`node-gyp@5.0.7`](https://github.com/nodejs/node-gyp/compare/v5.0.5...v5.0.7)
```
> npm ls node-gyp
npm@6.13.6 
├── node-gyp@5.0.5
└─┬ npm-lifecycle@3.1.4
  └── node-gyp@5.0.5  deduped
```

### List of devDependencies
- n/a

**Comment by jnardone** [comment]
please make sure to pick up node-gyp 5.0.6 or higher! https://github.com/npm/cli/issues/714

**Comment by mikemimik** [comment]
@ruyadorno and I discovered that we bumped `libnpx` incorrectly and pulling in `10.2.1` would actually be a breaking changes as that version of the package doesn't support `node@6` anymore.

**Comment by mikemimik** [comment]
A new version of `libnpx` was publish `10.2.2` with fixes for https://github.com/npm/cli/issues/717#issuecomment-579009527. 👍
