### ISSUE TITLE
[GitHub Settings feature request] Put "Steps To Reproduce" above "Current/Expected Behavior" in GH bug template

### ISSUE THREAD

**Issue by DanKaplanSES** [npm/cli#7170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

It prints "Version 1."

### Expected Behavior

It prints "Version 2."

### Steps To Reproduce

1. `node -p 'console.log("Version 1")' // oops. I had a typo. I meant "Version 2"` 

---

Most bug templates have the Steps To Reproduce before describing the Actual/Expected behavior. Without that, you see context-less output (e.g., `It prints "Version 1."` and `It prints "Version 2."`) before knowing how to interpret what you're reading. There may be some advantage of the current order I'm not understanding.

Thoughts on putting "Steps To Reproduce" above "Current/Expected Behavior?" I would have submitted a PR, but [it's a github setting I don't have access to](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository). 

### Environment

- npm: 10.3.0
- Node.js: 20.10.0
- OS Name: Windows
- System Model Name: 10
- npm config:
```ini
; "builtin" config from C:\Users\myuser\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\myuser\\AppData\\Roaming\\npm"

; "user" config from C:\cygwin64\home\myuser\.npmrc

//registry.npmjs.org/:_authToken = (protected)
registry = "https://registry.npmjs.org/"
script-shell = "C:\\cygwin64\\bin\\bash.exe"

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v20.10.0
; npm local prefix = C:\my-projects\jsdom-sandbox
; npm version = 10.3.0
; cwd = C:\my-projects\jsdom-sandbox
; HOME = C:\cygwin64\home\myuser
; Run `npm config ls -l` to show all defaults.
```

**Comment by wraithgar** [comment]
It's not a github setting, it's a template file https://raw.githubusercontent.com/npm/cli/latest/.github/ISSUE_TEMPLATE/bug_10.yml

However as one of the people who does a lot of the triage work on these issues, it's nice to have the bug itself defined first.  Steps to reproduce comes after we've determined if it even is a bug.  A lot of reports are people who have assumptions about how npm *should* work, and report it as a bug when it is working as intended.

Gonna say no on this one, but we really do appreciate the thought you're putting into docs lately.  Don't let this discourage you.

**Comment by DanKaplanSES** [comment]
> It's not a github setting, it's a template file https://raw.githubusercontent.com/npm/cli/latest/.github/ISSUE_TEMPLATE/bug_10.yml

Ah. I have a feeling if I kept reading I could've learned that on my own. Thanks!

> However as one of the people who does a lot of the triage work on these issues, it's nice to have the bug itself defined first. 
> Steps to reproduce comes after we've determined if it even is a bug. 

I see the value in that. 

May I ask a follow-up question: Between "Current Behavior," "Expected Behavior," and "Steps To Reproduce," why is "Current Behavior" the most appropriate place for the bug definition? 

> Gonna say no on this one, but we really do appreciate the thought you're putting into docs lately. Don't let this discourage you.

NP! I appreciate the kind words.

**Comment by wraithgar** [comment]
"Current behavior" describes what it is doing now.  In practice, I and others who triage issues can usually see the problem in that part alone.  It really does help.
