### ISSUE TITLE
Package manifest file so large that it breaks Nexus RM proxy

### ISSUE THREAD

**Issue by benmarch** [npm/cli#7177]
I'm not sure if there is anything that can be done about this, but the manifest file for the `npm` package is so large now that we are unable to install dependencies because it causes our Nexus RM registry to 500. https://registry.npmjs.org/npm

```
npm info npm
npm WARN Ignoring workspaces for specified package(s) 
npm ERR! code E500
npm ERR! 500 Server Error - GET http://<internal nexus domain>/content/groups/npm-all/npm

npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2024-01-24T15_29_06_995Z-debug-0.log
```

Here's a screenshot of what that Nexus URL above displays:
<img width="906" alt="image" src="https://github.com/npm/cli/assets/1646126/224b343b-5733-40dc-b5a8-7da4dae9ac43">

For what it's worth, if I try to access https://registry.npmjs.org/npm in Chrome it causes the tab to crash.

**Comment by ljharb** [comment]
Seems like nexus should look into a streaming json parser so it can more efficiently handle large json strings - the npm registry isn’t gonna get any smaller.

**Comment by benmarch** [comment]
Thanks for the quick response @ljharb. I agree, we're also using a very old version of Nexus and can't upgrade for some reason. I'll close this out and work with our infrastructure team. Thanks!
