### ISSUE TITLE
[BUG] Can't authenticate to publish

### ISSUE THREAD

**Issue by edemaine** [npm/cli#7179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`npm publish` gives me a link of the form `https://www.npmjs.com/auth/cli/...`. I click the link, and I get this page:

![image](https://github.com/npm/cli/assets/2218736/fc4887d2-8445-478b-abac-c2fb8d9f6fba)

### Expected Behavior

Expected to do 2-factor authorization as usual.

### Steps To Reproduce

1. `npm publish`
2. Follow link

### Environment

- npm: 9.9.2
- Node.js: 18.16.0
- OS Name: Windows 11
- System Model Name: 
- npm config:
```ini
; "builtin" config from C:\Users\edemaine\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\edemaine\\AppData\\Roaming\\npm"

; "user" config from C:\Users\edemaine\.npmrc

//registry.npmjs.org/:_authToken = (protected)

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v18.16.0
; npm local prefix = C:\Users\edemaine\Projects\Civet
; npm version = 9.9.2
; cwd = C:\Users\edemaine\Projects\Civet
; HOME = C:\Users\edemaine
; Run `npm config ls -l` to show all defaults.
```

**Comment by wraithgar** [comment]
This appears to be a problem with the npm registry/website.  Support for those is at https://www.npmjs.com/support
