### ISSUE TITLE
[BUG] Module not found: Error: Can't resolve `'../node_modules/open'`

### ISSUE THREAD

**Issue by priyankarpal** [npm/cli#7183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

when I build the site it's failing & producing this error. 
`Module not found: Error: Can't resolve '../node_modules/open'`

### Steps To Reproduce

1. installed all dependencies using `npm i --legacy-peer-deps`
2. run using the `npm run dev` site is running successfully
3. but not building when I use `npm run build` 

### Environment

- npm: 9.2.0
- Node.js: v18.19.0
- OS Name: Kali Linux
- System Model Name: HP Victus
- npm config:
```ini
; "builtin" config from /usr/share/nodejs/npm/npmrc

globalignorefile = "/etc/npmignore" 
prefix = "/usr/local" 

; "cli" config from command line options

location = "project" 

; node bin location = /usr/bin/node
; node version = v18.19.0
; npm local prefix = /home/pewpew/Desktop/react-play
; npm version = 9.2.0
; cwd = /home/pewpew/Desktop/react-play
; HOME = /home/pewpew
; Run `npm config ls -l` to show all defaults.
                                                       
```

**Comment by ljharb** [comment]
npm 9 is eol, try npm 10?

**Comment by clevercoderjoy** [comment]
> npm 9 is eol, try npm 10?

Tried that as well
But it did not help and the build fails

**Comment by clevercoderjoy** [comment]
we've tried everything we could but nothing has helped us so far

**Comment by ljharb** [comment]
Sounds like it's a problem with your build script, not with npm.

**Comment by wraithgar** [comment]
Not enough here to reproduce
