### ISSUE TITLE
[BUG] <title> Offline update to npm 9.8.1

### ISSUE THREAD

**Issue by hassan-xy** [npm/cli#7185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Hi guys,
In my yocto image I get npm 6.x with node 14.18.1. But I need to update to npm 9.8.1. The issue is I need to do it offline and need your support in doing so. Please share some documentation or some steps with which I can update to the npm 9.8.1 version
Thanks

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:6.14.15
- Node.js: 14.18.1
- OS Name: Poky (Yocto Project Reference Distro) 3.1.11 (dunfell)
- System Model Name: architecture: arm64
- npm config:
```ini
; copy and paste output from `npm config ls` here
```
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.14.15 node/v14.18.1 linux arm"

; node bin location = /usr/bin/node
; cwd = /root
; HOME = /root
; "npm config ls -l" to show all defaults.

**Comment by shadowspawn** [comment]
From a context with internet access, you can download the tarball using:
```
npm pack npm@9.8.1
```

**Comment by hassan-xy** [comment]
Hi @shadowspawn, I am able to manually run a custom script and was able to update it offline by referring the install.sh script.

Thanks
