### ISSUE TITLE
[DOCS] npm help outputs content using hyphen character "‐" insteadof dash "-"

### ISSUE THREAD

**Issue by zyf0330** [npm/cli#7192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Problem, not another kind of Docs Problem.

- [X] This is a CLI Docs Problem.

### Description of Problem

You can see differences between these two chars when read this https://jkorpela.fi/dashes.html.
The dash is "-	U+002D	&#45;	hyphen-minus".
The hyphen is "‐	U+2010	&#8208;	hyphen".

This problem causes that user cannot search info about options in the output of `npm help`.
User types `/-D` and find nothing, but this option is there actually.

### Potential Solution

Use U+002D instead of U+2020 to represent dash or hyphen.

**Comment by wraithgar** [comment]
Where are you seeing that character? I am able to search (for example npm help install` for `-omit`
<img width="665" alt="Screenshot 2024-04-13 at 10 08 09 PM" src="https://github.com/npm/cli/assets/36607/ab50e9dd-1244-4ef1-9467-4e5949064e6b">

And `-P`
<img width="514" alt="Screenshot 2024-04-13 at 10 09 27 PM" src="https://github.com/npm/cli/assets/36607/0dd3baeb-2a6e-4850-b0b1-879633379326">

So both `-` and `--` appear to be working just fine.

Searching the website also works for me

<img width="497" alt="Screenshot 2024-04-13 at 10 10 34 PM" src="https://github.com/npm/cli/assets/36607/ec7367b7-36a9-4b3c-be0c-803b399aa7d9">
