### ISSUE TITLE
'.' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by sangeesafi** [npm/cli#720]
While installing npm in windows its showing error like this please guide me how to proceed further

> emulsify@1.0.0 postinstall D:\xampp\htdocs\drupal-8.8.1\themes\custom\emulsify
> ./scripts/pattern_lab.sh && ./scripts/twig_functions.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! emulsify@1.0.0 postinstall: `./scripts/pattern_lab.sh && ./scripts/twig_functions.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the emulsify@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-01-22T10_59_16_551Z-debug.log

**Comment by ljharb** [comment]
These seem like postinstall scripts in your own package.json, not npm.

**Comment by DanielRuf** [comment]
This might work on powershell but `./` does not work in many cases, you might want to remove this.

**Comment by DanielRuf** [comment]
For reference, it comes from https://github.com/fourkitchens/emulsify/blob/develop/package.json#L11
