### ISSUE TITLE
No copy buttons for the command for any npm package

### ISSUE THREAD

**Issue by MohammadHarish521** [npm/cli#7215]
![Screenshot 2024-02-12 000108](https://github.com/npm/cli/assets/109061798/6e6d35ad-678a-4f8f-9b40-4d61ec1e7cf7)

It would have been better if their was a copy button to copy the commands in one go instead of selecting the whole command and ctr+C

**Comment by ljharb** [comment]
This is the readme of a specific package, so you'll have to file it on that repo. npm isn't involved with the contents of any package's readme.
