### ISSUE TITLE
[BUG] Support for package.js to avoid json problems (comments, dangling commas etc)

### ISSUE THREAD

**Issue by Eccenux** [npm/cli#7219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I'm sure many people have stumbled upon this: I have a script named 'build-js', I want to try out a new build module, I want to comment it out, add a new script with the same name, try out `npm run build` pipeline. Comments are not allowed in JSON.

### Expected Behavior

Would be nice if, much like eslint, npm would support `package.js` in the absence of `package.json`. Obviously it would take a "bit" of time for other tools to adapt, but long term having JS config would work better in some cases (removing items is also easier in JS and diffs are nicer, because you can have dangling commas).

### Steps To Reproduce

N/A

### Environment

N/A

**Comment by ljharb** [comment]
There’s a ton of reasons this isn’t viable imo; config needs to be static.

Either way, it’d need to be an RFC and not an issue here, so, closing.

**Comment by gmullerb** [comment]
I’ve had some of these issues and needs for a while! A way to share build scripts across my projects, reuse dependencies, add comments, and implement more complex build logic (e.g. custom JS code). 

The easiest solution would have been migrating `package.json` to a JS file, similar to how ESLint does it, Unfortunately, that’s not supported [npm issue #7219](https://github.com/npm/cli/issues/7219). 
Another partial solution would be allowing a parent `package.json`, but that’s been explicitly rejected as well [npm issue #8112](https://github.com/npm/npm/issues/8112).

So, in pursuit of these capabilities, I decided to build a tool (useful at least until we eventually get a native `package.js`). I called it **jko**: [jko npm package](https://www.npmjs.com/package/jko), [jko documentation](https://jko-doc.github.io). I hope it proves useful to others!
