### ISSUE TITLE
[Error] cb() never called! on Windows 10

### ISSUE THREAD

**Issue by yuvipatel** [npm/cli#722]
While executing '**npm install**' of my project got below error -

"npm ERR! cb() never called!"

My node and npm version details are--
node  -- **v13.6.0**
npm -- **6.13.4**

System Information --
Operating System: Win64
Chrome Browser Version: 79.0.3945.130
Chrome OS Version: NA
Memory: 1.01GB available out of 8.45GBCPU: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz ( x86_64architecture - 8 processors )

**Comment by ljharb** [comment]
#417

**Comment by SimonMaghiar** [comment]
Jeez can't believe that no one found the solution to this problem.

**Comment by Tomato6966** [comment]
First use this:     `npm cache clean --force`

Then it should work!

**Comment by rvinothkumarer** [comment]
Hi @Tomato6966 - Im using the configurations as below and tried all the ways suggested but still facing the same. Im running behind the corporate proxy. If i remove the npm proxy from config, it throws error related to proxy. If i add the proxy then it throws the cb() never called error. Any help would be much appreciated.

npm cache clean --force -->doesnt work

npm cache verify --> doesnt work

node -v
v14.15.3

npm -v
6.14.9

npm install -g @angular/cli
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vinothra\AppData\Roaming\npm-cache\_logs\2020-12-18T17_25_28_220Z-debug.log

**Comment by karthikganesanTR** [comment]
Any updates on issue. I am also facing the issue for the past one week

**Comment by rvinothkumarer** [comment]
Hi @karthikganesanTR,

For me, I faced the issue when I was setting the http_proxy/https_proxy but actually that is not required. But instead, I will have to update my .npmrc file to have my correct artifactory. Additionally, I have also set, strict-ssl=false. Please see below,

strict-ssl=false 
registry=https://ARTIFACTORY/api/npm/npm/
