### ISSUE TITLE
when npm unpublish package, show 422 Unprocessable Entity

### ISSUE THREAD

**Issue by tclxjiaxing-huang** [npm/cli#7229]
How to handle this error
<img width="600" alt="image" src="https://github.com/npm/cli/assets/26563716/4c350d15-66f9-4a57-8922-5aeddb413dc7">

**Comment by ljharb** [comment]
Don’t use force with unpublish; if it doesn’t work without that, then it’s not unpublishable.

**Comment by tclxjiaxing-huang** [comment]
> Don’t use force with unpublish; if it doesn’t work without that, then it’s not unpublishable.

if it’s not unpublishableso,  how can I unpublish, I am sure the package need to unpublish.

**Comment by ljharb** [comment]
You can’t. Packages are not permitted to be unpublished after 72 hours, or, if it has a certain number of dependents/installs.

**Comment by wraithgar** [comment]
Please use the template when filling out a bug report.

This is the npm registry telling you that you can not unpublish. It is not a cli bug.

**Comment by Iswaryasl** [comment]
But i m trying to unpublish the package which s published just an hr ago
