### ISSUE TITLE
[BUG] <pnpm did it - why not npm as well? >

### ISSUE THREAD

**Issue by onexbash** [npm/cli#7234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

- 35.6s for 115 packages(clean install)
- 12.3s for 115 packages(with lock file)

### Expected Behavior

- 9s for the same 115 packages (clean install)
- 5.4s for the same 115 packages (with lock file)

### Steps To Reproduce

1. Delete node_modules & package-lock 
2. Run **npm** install + stopwatch
3. Delete node_modules & package-lock again 
4. Run **pnpm** install + stopwatch

=> You'll recognize that pnpm is ~4x faster. 
=> Without deleting node_modules & package-lock, npm & pnpm offer similar performance, but as we are in 2024 and everything uses pods & containers, it's more important than ever to deploy fast.  

### Environment

- pnpm:
- Node.js: 20.11
- OS Name: OSX Sonoma
- System Model Name: Mac M2 Pro
```ini
package-manager=pnpm
registry=https://registry.npmjs.org/
user-agent=pnpm/8.15.3 npm/? node/v21.6.2 darwin arm64

```

**Comment by ljharb** [comment]
Regardless of your CLI tool, you shouldn't be installing deps at deploy time - you should be deploying a fully installed application.

**Comment by onexbash** [comment]
@ljharb Definitely! But you cherrypicked one false expression "important to deploy fast" to dodge the key question. Why can the most used & default nodejs package manager that is developed since 2010 not compete with a small community that started developing js package managers in 2016? If there were promising plans, to improve npm, I wouldnt say one word, but it feels like nothing happens and criticism is not taken serious.

**Comment by ljharb** [comment]
I'm not sure what you mean by "not compete".

Speed is one metric, but correctness is a much more important one - and npm has improved a lot over every year in the past 10, so again, I'm not sure what you're referring to.

**Comment by paulius-valiunas** [comment]
> Regardless of your CLI tool, you shouldn't be installing deps at deploy time - you should be deploying a fully installed application.

I think I should point out that in a CI/CD pipeline, "deploy time" and "build time" are essentially the same. Either way, the install (node_modules) should definitely NOT come from a developer machine, it should come from a build agent, and more often than not these days, build agents are containers. So just replace "deploy fast" with "build fast" if you like, but what OP said makes perfect sense either way.

One detail I might nitpick on is that performance should always be compared with the lock file in tact - I just don't see a legitimate use case where you would need a fast build without one. Node_modules, on the other hand, should be deleted.

**Comment by wraithgar** [comment]
This does not appear to be an actual bug report, but more of a general complaint.  If you have an actionable way to speed npm up please let us know.
