### ISSUE TITLE
npm doesnt create node_modules or package-lock.json in workspaces

### ISSUE THREAD

**Issue by habsfanongit** [npm/cli#7248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Using the below workspace, installing any package in any of the below workspace ie, services/service1 or package/package1, npm install the packages to the workspace root directory and leaves workspaces without a package-lock.json or node_modules even though package.json is present in the directory and the package is added correctly to the dependencies.

Running npm install within the workspaces (services/service1) has the same effect 
```json
{
  "name": "npm-monorepo",
  "version": "1.0.0",
  "description": "npm-monorepo",
  
  "scripts": {
   //removed for privity
  },
  "workspaces": [
    "./packages/*",
    "./services/*",
    "./tools/*",
    "./apps/*"
  ],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@compodoc/live-server": "^1.2.3",

  }
}
```

### Expected Behavior

npm to install packages within the impacted workspace, not only in the root directory

### Steps To Reproduce

1. using the example json file
2.  create services/service1 either by navigating to serviceone directory after running `npm init` 
3.  install any package
4. observer no node_modules or package-lock.json are created

### Environment

- npm:10.2.3
- Node.js: v20.10.0
- OS Name: MacOS Sonoma 14.3.1
- System Model Name: M2
- npm config:default configs

**Comment by wraithgar** [comment]
This is by design.  Workspaces will only get dependencies in their local node_modules that can not be hoisted to the project root.
