### ISSUE TITLE
[FEATURE] add cicdDependencies to package.json

### ISSUE THREAD

**Issue by joelnet** [npm/cli#725]
# What / Why

I have a few projects that require specific dependencies exclusively on the ci/cd server. These are untracked in the project.json and exist in the cicd config files.

It would be nice to have these managed by npm as we could take advantage of features like `npm outdated` and `npm update`, etc.

* Fewer (unnecessary) dependencies installed on local dev boxes.
* Packages can be managed by npm cli.
* Single location to manage packages (in the package.json).

## When
  * when `--cicd` or `NPM_CICD=true`
  * during `npm install` and also  `npm ci`

## Where
  * only on the ci/cd server

### Current Behavior

ci/cd dependencies are currently installed in either the docker container, the cicd config, or in the `devDependencies` in the package.json.

example `.gitlab-ci.yml`:
```yaml
  script:
    - npm install --no-save @semantic-release/exec
    - npx semantic-release
```

### Expected Behavior

package.json:
```javascript
{
  "dependencies": { },
  "devDependencies": { },
  "cicdDependencies": {
    "@semantic-release/exec": "^4.0.0",
    "semantic-release": "^16.0.3",
    "sonar-scanner": "^3.0.1",
  },
}
```

```bash
# also installs cicdDependencies
npm install --cicd

# also installs cicdDependencies
npm ci --cicd
```

* only on the ci/cd server would `cicdDependencies` be installed.
* `cicdDependencies` could be installed with a cli switch or environment variable.

## Who
* n/a

## References
* n/a

**Comment by ljharb** [comment]
What problems occur with having these things as dev deps? (besides slightly longer install times)

**Comment by joelnet** [comment]
> What problems occur with having these things as dev deps? (besides slightly longer install times)

- Longer install times on dev
- Unnecessary packages on dev machines
- node_modules larger on dev

I guess the same question could be posed regarding `devDependencies` being installed on production.

**Comment by ljharb** [comment]
That's a very different consideration; there's security issues with installing more than you need in production.

Disk space isn't usually at a premium on dev machines, but i'd be interested to see an actual install times comparison when those packages are added as dev deps.

**Comment by joelnet** [comment]
> i'd be interested to see an actual install times

These times would vary based on the packages required. As an example, one project I am looking at right now would add 17s to npm install times and 68M of files.

```bash
$ time npm install @semantic-release/exec semantic-release sonar-scanner
real    0m17.250s
user    0m14.817s
sys     0m10.564s

$ du -sh .
 68M    .
```

> Disk space isn't usually at a premium on dev machines

I would agree with this, but node_modules is by far the largest consumer of disk space because it is multiplied across every project. That being said, even saving 68M x 50 projects won't put a large dent in the node_modules issue.

**Comment by joelnet** [comment]
a better comparison using `npm ci`:

```bash
# without cicd dependencies
$ npm ci
added 1335 packages in 14.482s

# with cicd dependencies
$ added 1566 packages in 18.88s
```

It looks like there is 4-5 seconds (+30%) added to install time, 231 additional packages (+17%)

**Comment by ljharb** [comment]
The comparison i'd want is "your whole tree with those deps" and "your whole tree without those deps", to maximally eliminate the npm overhead.

**Comment by joelnet** [comment]
> The comparison i'd want is "your whole tree with those deps" and "your whole tree without those deps", to maximally eliminate the npm overhead.

Okay, I think this is what you are looking for:
 
```shell
# without cicd dependencies
$ npm ci
added 1335 packages in 14.482s
 
# with cicd dependencies
$ added 1566 packages in 18.88s
```
 
It looks like there is 4-5 seconds (+30%) added to install time, 231 additional packages (+17%)
