### ISSUE TITLE
[BUG] `npx` doesn’t consider globally installed namespaced packages

### ISSUE THREAD

**Issue by rauschma** [npm/cli#7257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Related issues

* https://github.com/npm/cli/issues/1746
* https://github.com/npm/cli/issues/2894

### This issue exists in the latest npm version

- [X] I am using the latest npm

## Installation

I installed a package via `sudo npm link` (without publishing it to the registry):

```
% cd ~/tmp/hello/
% sudo npm link
```

Result:

```
% npm ls -g
/usr/local/lib
├── @rauschma/hello@1.0.0 -> ./../../../Users/rauschma/tmp/hello
├── corepack@0.24.0
├── npm@10.2.4
└── typescript@5.3.3
```

## Interaction

I’m unable to use `npx @rauschma/hello`:

```
% cd $HOME

% hello
Hello!

% npx hello
Hello!

% npx @rauschma/hello
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@rauschma%2fhello - Not found
npm ERR! 404 
npm ERR! 404  '@rauschma/hello@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

% npx --package @rauschma/hello hello   
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@rauschma%2fhello - Not found
npm ERR! 404 
npm ERR! 404  '@rauschma/hello@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

### Expected Behavior

I expected `npx @rauschma/hello` to work.

### Steps To Reproduce

* Clone the following GitHub repo: https://github.com/rauschma/hello
* Use as described in its readme (and above).

### Environment

- npm: 10.2.4
- Node.js: v21.6.2
- OS Name: macOS Sonoma 14.3.1
- System Model Name: MacBook Pro 14-inch with an M1 Pro
- npm config:
```ini
; "user" config from /Users/rauschma/.npmrc

//registry.npmjs.org/:_authToken = (protected) 
loglevel = "error" 

; node bin location = /usr/local/bin/node
; node version = v21.6.2
; npm local prefix = /Users/rauschma/tmp/hello
; npm version = 10.2.4
; cwd = /Users/rauschma/tmp/hello
; HOME = /Users/rauschma
; Run `npm config ls -l` to show all defaults.
```

**Comment by rauschma** [comment]
Loosely related: https://github.com/npm/cli/issues/1746

**Comment by ljharb** [comment]
If you’re linking it globally you don’t need npx to use it, tho.

**Comment by rauschma** [comment]
I know! The idea is to invoke a bin script via npx then users can choose between:
* Installing locally
* Installing globally
* Letting npx install it

**Comment by ljharb** [comment]
yeah that makes sense - i would definitely expect npx to check local first, then global, then the registry. Is this perhaps a duplicate of #5596?

**Comment by rauschma** [comment]
> i would definitely expect npx to check local first, then global, then the registry.

Right. That’s how it works with non-namespaced packages.

**Comment by what1s1ove** [comment]
Hey @ljharb !

I have the same problem, and it seems it started with the 20.11 Node release (and its other components).

Node.js - 20.10.0
npm/npx - 10.2.3
build command - pass
<img width="511" alt="image" src="https://github.com/npm/cli/assets/42296182/c235bf1c-0462-4af1-99da-434760b6deb0">

Node.js - 20.11.0
npm/npx - 10.2.4
build command - fail (due to the suggestion to install the package. What I really don’t want, but I want to use the version from node_modules (behavior of  Node 20.10)
<img width="499" alt="image" src="https://github.com/npm/cli/assets/42296182/5584a0e7-42fa-4141-913d-844950507a15">

I do not have a lot of time to investigate more now, but hope it will help a bit 🙏

**Comment by milaninfy** [comment]
not able to reproduce the issue with the steps provided. Likely that this issue might be fixed. Please try with latest npm. 
```bash
~/workarea/rep $ sudo npm link

added 1 package, and audited 3 packages in 453ms

found 0 vulnerabilities
~/workarea/rep $ hello
Hello dfsdf!
~/workarea/rep $ npx hello
Hello dfsdf!
~/workarea/rep $ npx @rauschma/hello
Hello dfsdf!
~/workarea/rep $ npm -v
10.2.4
```

**Comment by rauschma** [comment]
Thanks! It indeed looks like the issue is fixed now.
