### ISSUE TITLE
[BUG] login with otp will get 404

### ISSUE THREAD

**Issue by abigoroth** [npm/cli#7261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I am a newly registered user,
as I am about to login as a first time user,
I submit my username & password on the login page https://www.npmjs.com/login
then I got the 'OTP has been sent to your email message' :

![image](https://github.com/npm/cli/assets/520990/598c802f-e847-49e3-b091-ffcce781c084)

then I copy the code from my email and paste+submit it.

then I got this.

![image](https://github.com/npm/cli/assets/520990/159737e7-ef4b-4c4c-86f5-7f86db924dde)

### Expected Behavior

able to login 

### Steps To Reproduce

1. click login from top right
2. submit login form
3. copy OTP from email and submit

**Comment by milaninfy** [comment]
**Closing:** this looks to be an issue with the registry which is outside the scope of this repo. For registry support please go to [npmjs.com/support](https://www.npmjs.com/support). If you believe this is a bug with the cli, please provide further clarifying details.
