### ISSUE TITLE
Getting an error while running or making a new React app I have also connected with NPM support, but their solution has not worked for me. My ticket ID is 2492208. 

### ISSUE THREAD

**Issue by Akash-Gupta03** [npm/cli#7264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Problem, not another kind of Docs Problem.

- [X] This is a CLI Docs Problem.

### Description of Problem

while making new react app.

**Command --> npx create-react-app hello**

npm ERR! code ERR_SSL_CIPHER_OPERATION_FAILED
npm ERR! errno ERR_SSL_CIPHER_OPERATION_FAILED
npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/electron-to-chromium: 00270000:error:1C800066:Provider routines:ossl_gcm_stream_update:cipher operation failed:c:\\ws\\deps\\openssl\\openssl\\providers\\implementations\\ciphers\\ciphercommon_gcm.c:320:
npm ERR!

**while running npm i -->**

npm ERR! code ERR_SSL_CIPHER_OPERATION_FAILED
npm ERR! D8160000:error:1C800066:Provider routines:ossl_gcm_stream_update:cipher operation failed:c:\ws\deps\openssl\openssl\providers\implementations\ciphers\ciphercommon_gcm.c:320:
npm ERR!

### Potential Solution

We recommend uninstalling and installing npm and node.
 
https://docs.npmjs.com/misc/removing-npm.html
https://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x
 
You may refer to the link below when you are ready to install npm and node again:
https://docs.npmjs.com/downloading-and-installing-node-js-and-npm
https://www.npmjs.com/get-npm

**Comment by milaninfy** [comment]
**Closing:** please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).

**Comment by Akash-Gupta03** [comment]
Okay thanks for the support.
