### ISSUE TITLE
[BUG] audit signatures Internal Server Error "Buffer is not defined"

### ISSUE THREAD

**Issue by maxRN** [npm/cli#7266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When verifying the signatures of my project with `npm audit signatures` I run into an internal server error during verification of the Axios package @1.6.7. Error message:

```shell
npm ERR! code E500
npm ERR! 500 Internal Server Error - GET https://registry.npmjs.org/-/npm/v1/attestations/axios@1.6.7 - Buffer is not defined

npm ERR! A complete log of this run can be found in: /Users/maxrn/.npm/_logs/2024-03-05T15_53_35_458Z-debug-0.log
```

### Expected Behavior

The `npm audit signatures` command either finishes sucessfully or tells me that one of my packages couldn't be verified.

### Steps To Reproduce

0. Reproduction repository: https://github.com/maxRN/npm-audit-signatures-repro
1. New project with `npm init`. All default values.
2. Run `npm i axios`. (This currently install `axios@1.6.7`)
3. Run `npm audit signatures`
4. After a short delay the error message is printed.

### Environment

- npm: 10.5.0
- Node.js: 21.6.2
- OS Name: macOS Sonoma 14.3.1
- System Model Name: Macbook Pro M1 Pro
- npm config:
```ini
; node bin location = /Users/maxrn/Library/Application Support/fnm/node-versions/v21.6.2/installation/bin/node
; node version = v21.6.2
; npm local prefix = /Users/maxrn/work/test-axios
; npm version = 10.5.0
; cwd = /Users/maxrn/work/test-axios
; HOME = /Users/maxrn
; Run `npm config ls -l` to show all defaults.
```

**Comment by maxRN** [comment]
Maybe related: https://github.com/microsoft/playwright/issues/29798

**Comment by milaninfy** [comment]
@maxRN I tried to reproduce this issue using the same steps and repo link mentioned in issue, it worked for me as expected.
```
npm-audit-signatures-repro % npm audit signatures
audited 9 packages in 1s

9 packages have verified registry signatures

1 package has a verified attestation
```

**Comment by maxRN** [comment]
I just tried again after running `npm cache verify` and now it works. It was also failing in our CI pipeline, but is also working again, without any changes made.

**Comment by chadwickellis** [comment]
It appears this issue is still occurring. The URL in the error trace (https://registry.npmjs.org/-/npm/v1/attestations/axios@1.6.7), among others, is broken or invalid, returning `{"error":"Buffer is not defined"}`.

**Comment by Tzinov15** [comment]
We are also running into this, another example error trace

https://registry.npmjs.org/-/npm/v1/attestations/tailwind-merge@2.2.1

**Comment by jean-motorway** [comment]
Same deal here, for all packages that pull signature checks from `registry.npmjs.org/-/npm/v1/attestations/`.
