### ISSUE TITLE
[BUG] Inconsistent `npm install` behaviour with prerelease versions of dependencies

### ISSUE THREAD

**Issue by DawidKopys** [npm/cli#7268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`npm install` installs different version of dependency (defined with prerelease semver range) before and after publishing new, non-prerelase version.

Let's say we have:
- a library `foo` with versions `0.0.1-alpha.1`, `0.0.1-alpha.2`, `0.0.1-nobatching.2` and `0.0.1-alpha.3`
- a project using `foo` as a dependency - its `package.json`:
```
{
  "dependencies": {
    "foo": "^0.0.1-alpha.1",
  }
}
```
When we run `npm install` in this project, npm will install `0.0.1-alpha.3` version of the `foo` library.

**The problem**
Let's imagine that `foo` library authors publish a new version of their package - `0.1.0`.
If we run `npm install` in the project now, npm will install `0.0.1-nobatching.2` instead of `0.0.1-alpha.3`!

Nothing changed in the project in the meantime. The only thing that happened was `foo` had a new version published, that's it. This new version doesn't even satisfy semver range defined in the project. But still, it results in different version of `foo` being installed.

### Expected Behavior

`npm install` installs the same `foo` version (either `0.0.1-alpha.3` or `0.0.1-nobatching.2`, I am not sure about this one) both before and after the library authors publish new version `0.1.0`.

### Steps To Reproduce

1. clone repository https://github.com/DawidKopys/prerelease-versions-reproduction
2. go into the directory and install dependencies `cd prerelease-versions-reproduction && npm i`
3. list installed packages `npm ls --depth 0`

Result:
```ini
prerelease-versions-reproduction@1.0.0 /Users/dawidkopys/Workspace/playground/prerelease-versions-reproduction
├── @dkopys/prerelase-test@0.0.1-nobatching.2
└── @dkopys/prerelease-test-2@0.0.1-alpha.3
```

Expected result: both dependencies have the same version installed.

This bug is submitted to npm 10 but the same happens in npm 8 for sure, haven't verified npm 9.

### Environment

- npm: 10.2.4
- Node.js: v21.6.2
- OS Name: macOS Sonoma 14.2.1
- System Model Name: Macbook Pro 16-inch 2019
- npm config:
```ini
; "user" config from /Users/dawidkopys/.npmrc

; node bin location = /Users/dawidkopys/.nvm/versions/node/v21.6.2/bin/node
; node version = v21.6.2
; npm local prefix = /Users/dawidkopys/Workspace/playground/prerelease-versions-reproduction
; npm version = 10.2.4
; cwd = /Users/dawidkopys/Workspace/playground/prerelease-versions-reproduction
; HOME = /Users/dawidkopys
; Run `npm config ls -l` to show all defaults.
```

**Comment by ljharb** [comment]
I’m confused; why would it change given the release of 0.1.0?

Certainly depending on prerelease ranges doesn’t cover very many versions; this is good because any prerelease may have breaking changes. You’re not supposed to ship packages that depend on prereleases :-)

**Comment by DawidKopys** [comment]
I am not sure what you are confused about, could you try to explain?
The point of this issue is that **it should not** change after release of 0.1.0 but - for some reason - it does change in current implementation.

> You’re not supposed to ship packages that depend on prereleases :-)

As far as I understand you are saying that depending on prerelease versions in not a good practice. While I might agree with that, I don't think it means that it is okay for npm to not work with prerelease versions as expected. Don't you think?

**Comment by ljharb** [comment]
What i mean is, the range sorting of the prerelease ranges listed doesn’t change based on the presence of 0.1.0. If it did, that would indeed be a serious bug in the semver package.

**Comment by DawidKopys** [comment]
Take a look at the minimal reproduction repo I have provided.
Here is a project that depends on 2 packages:
- `@dkopys/prerelase-test`
- `@dkopys/prerelease-test-2`

These packages have versions:
`@dkopys/prerelease-test-2`: 0.0.1-alpha.1, 0.0.1-alpha.2, 0.0.1-nobatching.2, 0.0.1-alpha.3 
`@dkopys/prerelase-test`: 0.0.1-alpha.1, 0.0.1-alpha.2, 0.0.1-nobatching.2, 0.0.1-alpha.3 **and 0.1.0**
... as you can see, the only difference between these two is, that the `@dkopys/prerelase-test` package has one more version published - 0.1.0.

The project in miminal repro has both these dependencies installed **with the same semver range** - `^0.0.1-alpha.1`.

**The problem is:**
When you run `npm install` in this project (which can be proved with `npm ls --depth 0`):
- npm installs version 0.0.1-alpha.3 of `@dkopys/prerelease-test-2` package
- npm installs version 0.0.1-nobatching.2 of `@dkopys/prerelase-test` package

I completely agree with what you are saying:

> What i mean is, the range sorting of the prerelease ranges listed doesn’t change based on the presence of 0.1.0.

... but it seems that it does change, and that's why I submitted this issue in the first place.

**Comment by ljharb** [comment]
when i check semver.npmjs.com for version range `^0.0.1-0`, I get this (i get the same results for `^0.0.1-alpha.1`):
<img width="841" alt="Screenshot 2024-03-06 at 9 20 04 AM" src="https://github.com/npm/cli/assets/45469/fa02d00b-c404-4852-897f-de052b231527">
<img width="885" alt="Screenshot 2024-03-06 at 9 19 54 AM" src="https://github.com/npm/cli/assets/45469/1202ef46-6319-49b5-9276-ad6bad85197e">

This shows the latest version (the last one) as v0.0.1-alpha.3 in both cases, as I'd expect.

However, when I check out your repo, and run `npm install` and `npm ls`, i definitely see what you're describing.

When I run `npm explain @dkopys/prerelase-test@0.0.1-nobatching.2`, i get this:
```sh
@dkopys/prerelase-test@0.0.1-nobatching.2
node_modules/@dkopys/prerelase-test
  @dkopys/prerelase-test@"^0.0.1-alpha.1" from the root project
```

and when i run `npm show @dkopys/prerelase-test@"^0.0.1-alpha.1" version` i see the expected version list, with '0.0.1-alpha.3' correctly shown last.

So, I think this is indeed an npm install bug, not a semver bug. Thanks for being persistent with me :-)

**Comment by wraithgar** [comment]
```
~/D/n/s/pre $ npm dist-tag ls @dkopys/prerelease-test-2
latest: 0.0.1-alpha.3
```

This is working as intended.  If you tag a release as `latest` that's what you get, as long as it's in range of what your package.json is asking for.


```
~/D/n/s/pre $ npm dist-tag ls @dkopys/prerelase-test
latest: 0.1.0
```

Latest here is out of range of `"^0.0.1-alpha.1"` so npm falls back on picking the highest possible version.

**Comment by ljharb** [comment]
ahhh, and the "n" is "later" than the "a", got it

**Comment by DawidKopys** [comment]
Ahhh, got it.
- `npm publish` uses the `latest` tag  by default
- `npm install` installs the version with `latest` tag, as long as it satisfies the semver range in `package.json`
- when `0.1.0` was published it became the new `latest`. As a result, `latest` no longer satisfies `"^0.0.1-alpha.1"` range so npm picks highest possible version, which is `0.0.1-nobatching.2` (because "n" is "later" than the "a").

Thanks a lot for your patience and explaining it to me!
