### ISSUE TITLE
THROW ERR: npm config set @something:registry http://something.com

### ISSUE THREAD

**Issue by Tichss** [npm/cli#7270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Steps To Reproduce

1. run eg: `npm config set @dataedge:registry http://verdaccio.dataedge`
2. error on console:  `npm ERR! `//verdaccio.dataedge` is not a valid npm option`

worked on version8.

### Environment

- npm: 10.2.4
- Node.js: v20.11.1
- OS Name: Win10
- System Model Name: 
- npm config:
; "user" config from C:\Users\User\.npmrc

@dataedge:registry = "http://verdaccio.dataedge/"
//verdaccio.dataedge/:_authToken = (protected)
http://verdaccio.dataedge = ""
registry = "https://registry.npmjs.org/"

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v20.11.1
; npm local prefix = C:\Users\User
; npm version = 10.2.4
; cwd = C:\Users\User
; HOME = C:\Users\User
; Run `npm config ls -l` to show all defaults.

**Comment by ljharb** [comment]
Try quoting it (also, try using https)

**Comment by Tichss** [comment]
> Try quoting it (also, try using https)
Dont worked this way.

But work this way: delete global `.npmrc` from `C:\Users\User\.npmrc` and re install node with fresh .npmrc. And this way work with the latest `npm` && `node`
