### ISSUE TITLE
EPERM: operation not permitted, unlink[BUG]

### ISSUE THREAD

**Issue by khadeejabasharat** [npm/cli#7273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When I try to run npm i or npm i --force, its throws following error:
`5446 verbose stack Error: EPERM: operation not permitted, unlink 

'C:\Users\m.sohail\AppData\Local\npm-cache\_cacache\tmp\2af0631f'
5447 verbose cwd D:\Clone Project\angular-tour-of-heroes
5448 verbose Windows_NT 10.0.19045
5449 verbose node v20.11.1
5450 verbose npm  v10.2.4
5451 error code EPERM
5452 error syscall unlink
5453 error path C:\Users\m.sohail\AppData\Local\npm-cache\_cacache\tmp\2af0631f
5454 error errno -4048
5455 error [Error: EPERM: operation not permitted, unlink 'C:\Users\m.sohail\AppData\Local\npm-cache\_cacache\tmp\2af0631f'] {
5455 error   errno: -4048,
5455 error   code: 'EPERM',
5455 error   syscall: 'unlink',
5455 error   path: 'C:\\Users\\m.sohail\\AppData\\Local\\npm-cache\\_cacache\\tmp\\2af0631f'
5455 error }
5456 error
5456 error The operation was rejected by your operating system.
5456 error It's possible that the file was already in use (by a text editor or antivirus),
5456 error or that you lack permissions to access it.
5456 error
5456 error If you believe this might be a permissions issue, please double-check the
5456 error permissions of the file and its containing directories, or try running
5456 error the command again as root/Administrator.
5457 verbose exit -4048`

I have tried all the solutions mentioned on different threads. The solution I have tried are as follows:

1. npm cache clean --force
2. Delete folders of npm and npm cache in APPDATA
3. Reboot system
4. Reinstall node
5. Upgrade node to latest
6. Delete node_modules and package-lock.json
7. Give all permissions to the project folder.
8. No node process in Task manager to kill.
9. Tried cmd with administrator rights.
10. Also, run VS Code with Administrator permissions.
11. Tried running commands on git bash using administrator permissions.
12. Turn off the window firewall. All the steps performed above were done with the firewall disabled.

Please provide some guidance to the issue. One more thing, I am also unable to create new angular project. I am getting this same issue.

### Expected Behavior

npm i should successfully install the packages.

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 10.2.4 
- Node.js: 20.11.1 
- OS Name: Windows 10
- System Model Name:
- npm config:
; "builtin" config from C:\Program Files\nodejs\node_modules\npm\npmrc

prefix = "C:\\Users\\m.sohail\\AppData\\Roaming\\npm"

; "user" config from C:\Users\m.sohail\.npmrc

@infragistics:registry = "https://packages.infragistics.com/npm/js-licensed/"
//packages.infragistics.com/npm/js-licensed/:_auth = (protected)
//packages.infragistics.com/npm/js-licensed/:username = "fyousaf!!ssidecisions.com"
email = "fyousaf@ssidecisions.com"

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v20.11.1
; npm local prefix = C:\Windows\system32
; npm version = 10.2.4
; cwd = C:\Windows\system32
; HOME = C:\Users\m.sohail
; Run `npm config ls -l` to show all defaults.

**Comment by wraithgar** [comment]
There is not enough info here to reproduce.
