### ISSUE TITLE
[BUG] NPM not properly installed using hombrew

### ISSUE THREAD

**Issue by lewiswolf** [npm/cli#7278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I have installed NPM and Node with homebrew, and for whatever reason my version of NPM is stuck a 10.3.0. When I run `sudo npm i -g npm@latest`, it installs the new version `/usr/local/lib/node_modules/lib/node_modules/npm`, but remains linked to `/usr/local/lib/node_modules/npm`. Any ideas?

I have reinstalled Node already using `brew reinstall node`. 

### Steps To Reproduce

```bash
brew install node
sudo npm i -g npm@latest
npm -v 
```

### Environment

- npm: 10.3.0
- Node.js: 21.7.1
- OS Name: MacOS 14.4
- System Model Name: Macbook Pro 2020 (Intel)
- npm config:
```ini
; "builtin" config from /usr/local/lib/node_modules/npm/npmrc

; prefix = "/usr/local" ; overridden by user

; "user" config from /Users/lewiswolstanholme/.npmrc

//registry.npmjs.org/:_authToken = (protected) 
prefix = "/usr/local/lib/node_modules" 

; node bin location = /usr/local/Cellar/node/21.7.1/bin/node
; node version = v21.7.1
; npm local prefix = /Users/lewiswolstanholme
; npm version = 10.3.0
; cwd = /Users/lewiswolstanholme
; HOME = /Users/lewiswolstanholme
; Run `npm config ls -l` to show all defaults.
```

**Comment by ljharb** [comment]
node isn’t officially distributed through homebrew, and npm comes with node and generally isn’t installed separately. Have you tried another way to install node?

**Comment by chenrui333** [comment]
> I have installed NPM and Node with homebrew, and for whatever reason my version of NPM is stuck a 10.3.0. When I run `sudo npm i -g npm@latest`, it installs the new version `/usr/local/lib/node_modules/lib/node_modules/npm`, but remains linked to `/usr/local/lib/node_modules/npm`. Any ideas?

👋 homebrew maintainer in here, I believe this is more of a `PATH` issue, which you can finding out with `which node`.

```
$ brew install -s node
Warning: node 21.7.1 is already installed and up-to-date.
To reinstall 21.7.1, run:
  brew reinstall node
  
$ export PATH="/opt/homebrew/Cellar/node/21.7.1/bin/:$PATH"
$

$ npm -v
npm verb cli /opt/homebrew/Cellar/node/21.7.1/bin/node /opt/homebrew/Cellar/node/21.7.1/bin/npm
npm info using npm@10.5.0
npm info using node@v21.7.1
npm verb title npm
npm verb argv "--version"
npm verb logfile logs-max:10 dir:/Users/rui/.npm/_logs/2024-03-18T20_43_18_699Z-
npm verb logfile /Users/rui/.npm/_logs/2024-03-18T20_43_18_699Z-debug-0.log
10.5.0
npm verb exit 0
npm info ok
```

**Comment by chenrui333** [comment]
Also feel free to submit an issue in the homebrew-core, https://github.com/Homebrew/homebrew-core/issues

**Comment by milaninfy** [comment]
**Closing** as this does not look like npm issue.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.
