### ISSUE TITLE
[BUG] No way to override on single level i.e, only direct-dependencies

### ISSUE THREAD

**Issue by Anutrix** [npm/cli#7284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Currently, if dependency A has dependencies on B(also depends on C) and C:
And just want to override direct dependency C of A, not those under B.

**Practical case:**
`highchart-export-server` & `prompt` & `async`.
```
  "overrides": {
    "highcharts-export-server": {
      "async": "2.6.4"
    }
  }
```

`npm ls async` without override:
```
abc@1.2.3 <project-full-path>
└─┬ highcharts-export-server@2.1.0
  ├── async@2.1.4
  └─┬ prompt@1.3.0
    ├── async@3.2.3
    └─┬ winston@2.4.7
      └── async@2.6.4
```
`npm ls async` with override:
```
abc@1.2.3 <project-full-path>
└─┬ highcharts-export-server@2.1.0 overridden
  ├── async@2.6.4 overridden
  └─┬ prompt@1.3.0
    ├── async@2.6.4 deduped
    └─┬ winston@2.4.7
      └── async@2.6.4 deduped
```
As you can see, direct dependency `async` went from `2.1.4` to `2.6.4` which is great
BUT indirect/grand-child/'dependency of a dependency' `async` under `prompt` went from `3.2.3` to `2.6.4`.
A major version downgrade happened. I couldn't find it a way to just override direct dependencies.

### Expected Behavior

There should be a way to only override direct dependencies.

### Steps To Reproduce

1. On empty folder, create a package.json with:
```
{
  "name": "abc",
  "version": "1.2.3",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo 'Hi' && exit 1"
  },
  "author": "",
  "license": "MIT",
  "dependencies": {
    "highcharts-export-server": "^2.1.0"
  },
  "overrides": {
    "highcharts-export-server": {
      "async": "2.6.4"
    }
  }
}
```
3. Now run `npm install`.
4. Run `npm ls async`
5. See async versions versions under grand-dependencies getting overridden:
```
abc@1.2.3 <project-full-path>
└─┬ highcharts-export-server@2.1.0 overridden
  ├── async@2.6.4 overridden
  └─┬ prompt@1.3.0
    ├── async@2.6.4 deduped
    └─┬ winston@2.4.7
      └── async@2.6.4 deduped
```

### Environment

- npm: 10.1.0 & 10.5.0(latest)
- Node.js: 20.8.1 & 21.7.1(latest)
- OS Name: macOS 14 & even Ubuntu 18/20(Seen on multiple machines)
- System Model Name: Macbook Pro 2019 Intel & AWS
- npm config:
```ini
; "user" config from /Users/<username>/.npmrc

; registry = "<internal-registry-url>" ; overridden by project

; "project" config from <project-full-path>/.npmrc

registry = "<internal-registry-url>"

; node bin location = /Users/<username>/n/bin/node
; node version = v20.8.1
; npm local prefix = <project-full-path>
; npm version = 10.1.0
; cwd = <project-full-path>
; HOME = /Users/<username>
; Run `npm config ls -l` to show all defaults.
```

**Comment by milaninfy** [comment]
@Anutrix This behaviour is by design, single level override is not possible. If you want to override only one level then You need to provide overrides for all path in your dependency graph and manually specifying override to specific version. 

something like this if it suits your use case.
```
"overrides": {
    "A": {
      "F": "1",
      "B": {
        "F": "2",
        "C": {
          "F": "3"
        }
      }
    }
  }
  ```
Checkout more on this https://github.com/npm/rfcs/blob/main/accepted/0036-overrides.md  and https://docs.npmjs.com/cli/v10/configuring-npm/package-json#overrides
