### ISSUE TITLE
view command could return deprecated versions explicitly

### ISSUE THREAD

**Issue by gustavo-m-vieira** [npm/cli#7287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Currently, when We call view command, the response includes a field called `versions`, which is an array of strings with all versions of the package.
But, the registry sends more information about this versions, like if its deprecated or not. So I am suggesting that we find a way of returning this valuable information.
Like adding a new field `deprecatedVersions` or in a future breaking change change the `versions` field format to include this data.

### Steps To Reproduce

1. run `npm view --json` inside any package repository
2. This will return something like this ```{ "name": "package-name", "versions": ["1.0.0", "1.0.1"] , ...  }```
3. What I would like to see is something like this  ```{ "name": "package-name", "versions": ["1.0.0", "1.0.1"] , "deprecatedVersions": ["1.0.0"], ...  }```

### Environment

- npm: 10.0.0
- Node.js: 20.0.0
- OS Name: Ubuntu 20.04

**Comment by ljharb** [comment]
it is already in the api, fwiw - `npx deprecations $packageName` will show it :-)

**Comment by gustavo-m-vieira** [comment]
> it is already in the api, fwiw - `npx deprecations $packageName` will show it :-)

Thanks for the quick answer but my problem with this package it's not work in private packages. You know any other way?

**Comment by wraithgar** [comment]
This repo is for npm cli bugs.  Suggestions for changes should start at https://github.com/npm/feedback/discussions.
