### ISSUE TITLE
[BUG] npm install hangs with installing puppeteer package

### ISSUE THREAD

**Issue by Sandeep-K-Khandelwal** [npm/cli#7289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

npm install command hangs while installing "puppeteer": "^20.3.0" package.

### Expected Behavior

The package should be installed without any issues.

### Steps To Reproduce

**package.json file**

`{
    "version": "1.0.0",
    "devDependencies": {
        "puppeteer": "^20.3.0"
    }
}
`

**Execute command:**
`npm install`

The command hangs with the following output and nothing happens for a long time. We have to kill the process.

`git:(master) ✗ npm install
npm WARN deprecated puppeteer@20.9.0: < 21.5.0 is no longer supported
(##################) ⠧ reify:puppeteer-core: http fetch GET 200 https://registry.npmjs.org/puppeteer-core/-/puppeteer-core-20.9.0.tgz 417ms (cache miss)`

### Environment

- npm: 10.5.0
- Node.js: v21.7.1
- System Model Name: Mac Sonoma 14.4

**Comment by Sandeep-K-Khandelwal** [comment]
Please note this issue is observed only with puppeteer < 22. With puppeteer >= 22 this issue is not observed and package install successfully.

**Comment by tlaukkanen** [comment]
This seems related: https://github.com/puppeteer/puppeteer/issues/12094

**Comment by milaninfy** [comment]
@Sandeep-K-Khandelwal This might be an issue with package and not npm cli.

**Comment by milaninfy** [comment]
**Closing:** we do not support/triage third-party libraries or tooling bugs; Please file an issue with the relevant project.
