### ISSUE TITLE
Proposal: print a warning when a user adds "dev" package

### ISSUE THREAD

**Issue by golergka** [npm/cli#7290]
`dev` package has long been abandoned, but many users accidentially install it when what they want is to use `--save-dev` flag. A warning about this package would prevent many user errors.

**Comment by wraithgar** [comment]
**Closing:** please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).

General npm feedback like this can also be submitted to https://github.com/npm/feedback/discussions

**Comment by golergka** [comment]
https://github.com/npm/feedback/discussions/1102
