### ISSUE TITLE
[BUG] npm update fails with workspace dependencies

### ISSUE THREAD

**Issue by habsfanongit** [npm/cli#7291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Running npm update in a directory where package.json contains dependencies to local workspace packages, results in a HTTP 404 error because npm tries incorrectly to install from the remote registry.

### Expected Behavior

Expecting npm update to succeed when package.json contains local workspace dependencies.
Steps To Reproduce:

### Steps To Reproduce

1. Create package.json with dependencies or devDependencies containing local workspace package.
2. Run npm update in directory.

### Environment

- npm:10.5.0
- Node.js:20.10.0
- OS Name:Sonoma 14.4
- System Model Name: M2 Max
- npm config:
```ini
; "user" config from /Users/user/.npmrc

cache = "/Users/user/.node_packages/.npmcache" 
prefix = "/Users/user/.node_packages" 

; node bin location = /Users/user/Library/Application Support/fnm/node-versions/v20.10.0/installation/bin/node
; node version = v20.10.0
; npm local prefix = /Users/user/dev/typescript/npm-monorepo
; npm version = 10.5.0
; cwd = /Users/user/dev/typescript/npm-monorepo
; HOME = /Users/user
   
```

**Comment by milaninfy** [comment]
@habsfanongit Could you please provide error logs and your project/sample package details for which it's failing?
 I tried with steps you provided, it worked without any error.

**Comment by habsfanongit** [comment]
Hi @milaninfy,
My apologies; this was a problem with the way I confirmed the workspaces in my mono repo.
I had a `*` after tools when it was initialized with npm init. removing the `*` got npm update to work
```
  "workspaces": [
    "./tools/*",
    "./packages/*",
    "./services/*",
    "./apps/*"
  ],

```
