### ISSUE TITLE
[BUG] npm pkg cli command outputs `{}` for missing entries from package.json

### ISSUE THREAD

**Issue by chenxinyanc** [npm/cli#7292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```powershell
PS> npm --version
10.5.0
# In a folder where there is `"private": true` in package.json
PS> npm pkg get private --ws=false
true
# When switched to another folder where there is no "private" field in package.json
PS> npm pkg get private --ws=false
{}
```

### Expected Behavior

If there is no "private" field in the package.json, I would expect no content or even `null` being printed out to the screen, instead of `{}`.

I'm not sure what would be the expected behavior, but there seems to be nothing related mentioned in the [documentation](https://docs.npmjs.com/cli/v10/commands/npm-pkg).

### Environment

- npm:10.5.0
- Node.js:v21.7.1
- OS Name:Microsoft Windows [Version 10.0.26080.1]
- System Model Name:x64
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by milaninfy** [comment]
@chenxinyanc 
This is not a bug and it's working as intended.

**Comment by chenxinyanc** [comment]
@milaninfy Appreciate your reply. I'm a bit curious about why, though. I mean, according to this design, doesn't it mean
```json
private: {}
```
will behave exactly the same as the case where `private` does not exist at all?

I might be a little bit dumb on such, but would you mind kindly provide some more details on this behavior? Is it due to some technical limitation? Is it for backward compatibility?
