### ISSUE TITLE
[BUG] ssl3_get_record:decryption

### ISSUE THREAD

**Issue by sysmat** [npm/cli#7293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

- when run `npm i` I get error:

```
4C2F0000:error:0A000119:SSL routines:ssl3_get_record:decryption failed or bad record mac:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:623:
```

- on system I have installed 

```
❯ openssl version
OpenSSL 3.0.13 30 Jan 2024 (Library: OpenSSL 3.0.13 30 Jan 2024)
```

- no npm openssl
- 
```
❯ npm ls -g openssl
C:\Users\tomaz\AppData\Roaming\npm
`-- (empty)
```

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 10.2.5
- Node.js:  20.11.1
- OS Name: Win 11
- System Model Name: 20N3S4FX00
- npm config:
```ini
; node bin location = C:\Program Files\nodejs\node.exe
; node version = v20.11.1
; npm local prefix = C:\Users\tomaz
; npm version = 10.2.5
; cwd = C:\Users\tomaz
; HOME = C:\Users\tomaz
```

**Comment by wraithgar** [comment]
This appears to be an issue w/ your operating system itself, or your installation of node.  This is not an npm error.  Without more steps to reproduce it's impossible to know more.
