### ISSUE TITLE
npm ERR! code E429 Too Many Requests : Publishing npm package

### ISSUE THREAD

**Issue by alexaandig** [npm/cli#7298]
Anyone here who can explain to me what this error means?

429 Too Many Requests - PUT https://registry.npmjs.org/name-of-my-package - Too Many Requests

I am logged in and using the latest nodejs version.

![2024-03-19 234620](https://github.com/npm/cli/assets/129890035/5aca38e1-41fa-4b16-96da-4134d23d6829)

**Comment by wraithgar** [comment]
It means the registry has rate limited you.  https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429

This repo is for tracking npm cli bugs. Registry support is at https://www.npmjs.com/support
