### ISSUE TITLE
[BUG] <When create new extension, cannot install using npm>

### ISSUE THREAD

**Issue by exeldtarkus** [npm/cli#7301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Steps To Reproduce

1. npx --package yo --package generator-code -- yo code
2. npm install
4. See error...

### Environment

- npm: npm@10.2.4
- Node.js: node@v20.11.1
- OS Name: mac ventura
- System Model Name:
- npm config:
```ini
; "user" config from /Users/ExelDefrisco/.npmrc

//10.12.4.129/:_authToken = (protected) 
//registry.npmjs.org/:_authToken = (protected) 
fetch-retry-maxtimeout = 120000 
fetch-retry-mintimeout = 20000 
ignore-scripts = false 
legacy-peer-deps = true 
registry = "http://10.12.4.129/" 
timeout = "6000000" 

; node bin location = /Users/ExelDefrisco/.nvm/versions/node/v20.11.1/bin/node
; node version = v20.11.1
; npm local prefix = /Users/ExelDefrisco/Documents/ExelData/explore/consul-helper
; npm version = 10.2.4
; cwd = /Users/ExelDefrisco/Documents/ExelData/explore/consul-helper
; HOME = /Users/ExelDefrisco
; Run `npm config ls -l` to show all defaults.
```

**Comment by milaninfy** [comment]
@exeldtarkus I tried to recreate the issue, it' working without any errors. Could you please share the exact error logs you are getting?
