### ISSUE TITLE
[BUG] Installation of scoped packages with specific version ignores the version

### ISSUE THREAD

**Issue by Idrinth** [npm/cli#7311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Running `npm install -g "@idrinth/api-bench@1.4.3"` installs the latest version(2.6.1)

### Expected Behavior

Running `npm install -g "@idrinth/api-bench@1.4.3"` installs the given version(1.4.3)

### Steps To Reproduce

1. Usinfg windows
2. Without any config
3. Run  `npm install -g "@idrinth/api-bench@1.4.3`
4. Check installed package.json to see version 2.6.1

### Environment

- npm: 10.5.0
- Node.js: 21.7.1
- OS Name: Alpine(Docker)
- System Model Name: Docker...
- npm config:
```ini
; node bin location = /usr/local/bin/node
; node version = v21.7.1
; npm local prefix = /
; npm version = 10.5.0
; cwd = /
; HOME = /root
; Run `npm config ls -l` to show all defaults.
```

**Comment by milaninfy** [comment]
@Idrinth I have tried with given steps and it works perfectly for me in alpine docker setup.

**Comment by Idrinth** [comment]
> @Idrinth I have tried with given steps and it works perfectly for me in alpine docker setup.

thanks for having a look - can't replicate it on my ubuntu host system either. I assume my dockerfile has an issue - will dig there more.
