### ISSUE TITLE
[BUG] `--dry-run` effectively ceases to work with `loglevel=error`

### ISSUE THREAD

**Issue by rauschma** [npm/cli#7325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

If I run `npm publish` or `npm pack` with the option `--dry-run`, the output looks like this:

```
npm notice
npm notice 📦  @rauschma/helpers@0.1.0
npm notice === Tarball Contents ===
npm notice 1.1kB LICENSE
npm notice 163B  README.md
npm notice 762B  dist/src/async/async-iteration.d.ts
npm notice 490B  dist/src/async/async-iteration.d.ts.map
npm notice 1.0kB dist/src/async/async-iteration.js
npm notice 733B  dist/src/async/async-iteration.js.map
```

If I set `loglevel=error` in `.npmrc` then I don’t see any output!

### Expected Behavior

It may make sense to use a log level higher than “notice” for the output – otherwise `--dry-run` is not very useful with lower log levels.

### Environment

- npm: 10.5.0
- Node.js: v21.7.1
- OS Name: macOS Sonoma 14.3.1
- npm config:
```ini
; node bin location = /usr/local/bin/node
; node version = v21.7.1
; npm version = 10.5.0
```

**Comment by cklim24** [comment]
[](url)

**Comment by cklim24** [comment]
`Bug`

**Comment by ljharb** [comment]
This is normal output for me - it shows with or without dry-run.

**Comment by rauschma** [comment]
With default log level (notice), I’m getting:

```
% npm pack --dry-run
npm notice
npm notice 📦  @rauschma/helpers@0.1.0
npm notice === Tarball Contents ===
npm notice 1.1kB LICENSE
npm notice 163B  README.md
[...]
```

With any log level below that, I’m only seeing one line:

```
% npm --loglevel warn pack --dry-run
rauschma-helpers-0.1.0.tgz
```

I understand why that is:

* Without `--dry-run`, the output is extra, non-essential information.
* But with `--dry-run`, the output becomes the whole point of the command.

My log level was `error` and I thought `--dry-run` didn’t do anything useful because I didn’t see any output: I was confused by documentation telling me that it could be used to check what files are going to be published.

So my question is: Should the log level of the output be higher?

But maybe you are not supposed to change your log level in `.npmrc`. Then this is not an issue.

**Comment by wraithgar** [comment]
Because of the way npm is set up now, setting loglevel to `error` is going to have side effects like this.  There is not a lot of good design or separation between normal output and logging output.  Until this is fixed, you'll need to set the loglevel back when running these commands, or not set your loglevel like this.

We do hope to eventually address this, but it would be a larger task that we are not starting right now.
