### ISSUE TITLE
[BUG] Unexpected package.json update when using `npm install --package-lock-only`

### ISSUE THREAD

**Issue by ksugawara61** [npm/cli#7330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I've encountered a behavior that seems unexpected when using the` npm install --package-lock-only package-name@version` command to update my package-lock.json.

In my recognition, I think that `--package-lock-only` option would only update the package-lock.json file without altering the package.json. 
ref: https://docs.npmjs.com/cli/v10/commands/npm-install#package-lock-only

However, in practice, both package.json and package-lock.json are being updated.

Is this correct behavior when using `--package-lock-only` option?

e.g):

- package.json

```
{
  "name": "npm-sandbox",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "date-fns": "^3.6.0"
  }
}
```

- update command

```
$ npm install --package-lock-only date-fns@3.6.0
```

- actual result

```
$ git diff
diff --git a/package-lock.json b/package-lock.json
index d4f44f4..d5fd2cb 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -9,13 +9,13 @@
       "version": "1.0.0",
       "license": "ISC",
       "dependencies": {
-        "date-fns": "^3.2.0"
+        "date-fns": "^3.6.0"
       }
     },
     "node_modules/date-fns": {
-      "version": "3.2.0",
-      "resolved": "https://registry.npmjs.org/date-fns/-/date-fns-3.2.0.tgz",
-      "integrity": "sha512-E4KWKavANzeuusPi0jUjpuI22SURAznGkx7eZV+4i6x2A+IZxAMcajgkvuDAU1bg40+xuhW1zRdVIIM/4khuIg==",
+      "version": "3.6.0",
+      "resolved": "https://registry.npmjs.org/date-fns/-/date-fns-3.6.0.tgz",
+      "integrity": "sha512-fRHTG8g/Gif+kSh50gaGEdToemgfj74aRX3swtiouboip5JDLAyDE9F11nHMIcvOaXeOC6D7SpNhi7uFyB7Uww==",
       "funding": {
         "type": "github",
         "url": "https://github.com/sponsors/kossnocorp"
diff --git a/package.json b/package.json
index 8051fc3..f06df83 100644
--- a/package.json
+++ b/package.json
@@ -9,6 +9,6 @@
   "author": "",
   "license": "ISC",
   "dependencies": {
-    "date-fns": "^3.2.0"
+    "date-fns": "^3.6.0"
   }
 }
```

### Expected Behavior

I would like to update only package-lock.json when using `--package-lock-only` option

e.g):

```
$ git diff
diff --git a/package-lock.json b/package-lock.json
index d4f44f4..bbb2cbc 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -13,9 +13,9 @@
       }
     },
     "node_modules/date-fns": {
-      "version": "3.2.0",
-      "resolved": "https://registry.npmjs.org/date-fns/-/date-fns-3.2.0.tgz",
-      "integrity": "sha512-E4KWKavANzeuusPi0jUjpuI22SURAznGkx7eZV+4i6x2A+IZxAMcajgkvuDAU1bg40+xuhW1zRdVIIM/4khuIg==",
+      "version": "3.6.0",
+      "resolved": "https://registry.npmjs.org/date-fns/-/date-fns-3.6.0.tgz",
+      "integrity": "sha512-fRHTG8g/Gif+kSh50gaGEdToemgfj74aRX3swtiouboip5JDLAyDE9F11nHMIcvOaXeOC6D7SpNhi7uFyB7Uww==",
       "funding": {
         "type": "github",
         "url": "https://github.com/sponsors/kossnocorp"
```

### Steps To Reproduce

1. Clone the repository at https://github.com/ksugawara61/npm-sandbox
2. Run `npm install --package-lock-only date-fns@3.6.0`
3. Check the differences with git diff

### Environment

- npm: 10.5.0
- Node.js: 20.12.0
- OS Name: macOS 13.6.1
- System Model Name: Macbook Pro
- npm config:
```ini
; node bin location = /Users/katsuya-sugawara/.nodenv/versions/20.12.0/bin/node
; node version = v20.12.0
; npm local prefix = /Users/katsuya-sugawara/Documents/ghq/github.com/ksugawara61/npm-sandbox
; npm version = 10.5.0
; cwd = /Users/katsuya-sugawara/Documents/ghq/github.com/ksugawara61/npm-sandbox
; HOME = /Users/katsuya-sugawara
; Run `npm config ls -l` to show all defaults.
```

**Comment by wraithgar** [comment]
That flag does not mean `ignores package.json` it means `ignores files in node_modules`.  `npm install` itself is always potentially a write operation.  It is especially a write operation when you ask it to install a package spec.

If you want to only update your tree without writing to the package.json file, use `npm update`
