### ISSUE TITLE
[BUG] npm ERR! always-auth is not a valid npm option 

### ISSUE THREAD

**Issue by abhishekkovuritw** [npm/cli#7331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

npm ERR! `always-auth` is not a valid npm option

npm ERR! A complete log of this run can be found in: /Users/abhishekkovuri/.npm/_logs/2024-04-02T14_14_32_498Z-debug-0.log

### Expected Behavior

In the older version, it was setting the property but in newer npm it doesn't set this as it is not available

### Steps To Reproduce

1. nvm install 18.20 - which installs node with npm version 10.5.0
2. npm config set always-auth true

### Environment

Do we have any alternate way to use 
`npm config set always-auth true`

**Comment by milaninfy** [comment]
This is not a bug. `always-auth` is not a valid option for latest npm. [Changelog](https://docs.npmjs.com/cli/v7/using-npm/changelog#v7111-2021-04-23)

**Comment by abhishekkovuritw** [comment]
Is there a work around for this for v10.5.0
