### ISSUE TITLE
[errr] <npm install -g expo-cli>

### ISSUE THREAD

**Issue by martinho75** [npm/cli#734]
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-29T09_03_22_031Z-debug.log
root@martinho-HP-Notebook:/home/martinho#

**Comment by DanielRuf** [comment]
Duplicate of https://github.com/npm/cli/issues/417
