### ISSUE TITLE
[BUG] npm link needs network connection 

### ISSUE THREAD

**Issue by drschwabe** [npm/cli#7344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When you run `npm link my-module` the network is used ( and [sometimes hangs indefinitely depending on if you are tethering on a hotspot for example](https://stackoverflow.com/questions/70865039/npm-install-hangs-on-sill-idealtree-build)) 

### Expected Behavior

If I'm not mistaken `npm link` is intended to aid local development and use a locally available module ie- `cd my-module; npm link`   As such,  using the command should not rely on a network connection and should work even if we are offline. 

### Steps To Reproduce

1. latest Node / npm v10 
2. have a spotty internet connection 
3. run `npm link my-module` (after doing `npm link` from my-module on your local filesystem) 
4. wait forever as it tries to connect to the network for some reason 

### Environment

node version = v20.11.1
npm version = 10.2.4

**Comment by milaninfy** [comment]
@drschwabe Not able to reproduce the issue, Even with internet disconnected completely in my system,  `npm link` still works.

**Comment by drschwabe** [comment]
Then it must be an issue when connected to a network; I was/have been using a tethered connection to my Android phone. 
In that case, npm link should still work - not sure why it gets tripped up with the network when this is a non-network operation.

**Comment by wraithgar** [comment]
`npm link` still may need to do periodic network requests.  There's not enough here to reliably reproduce in a more general sense.
