### ISSUE TITLE
[BUG] <title>Could not resolve dependency: npm WARN peer @craco/craco@"^6.0.0" from craco-less@2.0.0

### ISSUE THREAD

**Issue by Traveler001** [npm/cli#7345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

when running npm install it fails, telling me to report he issue

### Steps To Reproduce

1. Windows 11 pro running on Mac vm (Fusion) ARM
2. Installed Latest node js
3. Run 'npm install'
4. See error...
5.npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: craco-less@2.0.0
npm WARN Found: @craco/craco@7.0.0
npm WARN node_modules/@craco/craco
npm WARN   dev @craco/craco@"^7.0.0" from the root project
npm WARN   1 more (@semantic-ui-react/craco-less)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @craco/craco@"^6.0.0" from craco-less@2.0.0
npm WARN node_modules/@semantic-ui-react/craco-less/node_modules/craco-less
npm WARN   craco-less@"^2.0.0" from @semantic-ui-react/craco-less@3.0.0
npm WARN   node_modules/@semantic-ui-react/craco-less
npm WARN
npm WARN Conflicting peer dependency: @craco/craco@6.4.5
npm WARN node_modules/@craco/craco
npm WARN   peer @craco/craco@"^6.0.0" from craco-less@2.0.0
npm WARN   node_modules/@semantic-ui-react/craco-less/node_modules/craco-less
npm WARN     craco-less@"^2.0.0" from @semantic-ui-react/craco-less@3.0.0
npm WARN     node_modules/@semantic-ui-react/craco-less
npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>
[2024-04-05T15_08_20_708Z-debug-0.log](https://github.com/npm/cli/files/14886971/2024-04-05T15_08_20_708Z-debug-0.log)

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by revelt** [comment]
this line is telling us that it can't resolve the dependency `@craco/craco`:

> npm WARN Could not resolve dependency:

and `craco` seems to be called as a peer dependency by `craco-less`:

> peer @craco/craco@"^6.0.0" from craco-less@2.0.0

so, the next question is, do you have `@craco/craco` among dev dependencies in package.json? If you don't, it's a good idea to install it, `npm i -D @craco/craco`.

Also, a very handy command — you can check in npm tree, is something installed by `npm ls` — for example, `npm ls @craco/craco` can tell you is it present in the node_modules and exactly where and why.

I don't think it's an `npm` issue — we developers are responsible for installing missing dependencies and fixing any clashes.

**Comment by wraithgar** [comment]
Yes, this is not an npm issue. npm is being asked to install an impossible tree and erroring.

The `Exit handler not called` is a different issue altogether. See [here](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) for more info

**Comment by Traveler001** [comment]
Thank you, yes, after further investigation, this error was that this tool create-react-app has been deprecated for some time, and some of its dependencies too. 
I used Vite instead and it worked well.

Thanks all for the input.
