### ISSUE TITLE
Deprecate npm-lifecycle package more prominently?

### ISSUE THREAD

**Issue by jcbhmr** [npm/cli#7365]
https://www.npmjs.com/package/npm-lifecycle <-- "about to be deprecated" language; no deprecated banner
https://github.com/npm/npm-lifecycle <-- archived

should the npm-lifecycle npm package be more visibly deprecated? something like this:

![image](https://github.com/npm/cli/assets/61068799/c96c3e0b-0fc6-46ed-9a6b-d5d314a9aba9)
from https://www.npmjs.com/package/babel

**Comment by wraithgar** [comment]
![output of npm view npm-lifecycle showing it is deprecated](https://github.com/npm/cli/assets/36607/134e9537-fffd-4f21-8efc-735acc738b21)

![screenshot of npm-lifecycle package page showing it is deprecated](https://github.com/npm/cli/assets/36607/b8d65407-9141-45db-9d2b-b478c8bc4513)
