### ISSUE TITLE
[BUG] < Exit handler never called!>

### ISSUE THREAD

**Issue by Jianuo-Always-Coding** [npm/cli#7372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When I use npm install in vue2, it shows this error.

### Expected Behavior

I want to install all the packages.

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:10.5.2
- Node.js: v21.7.3
- OS Name:
- System Model Name: windows x64
- npm config:
```ini
npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in: C:\Users\Jianuo Wang\AppData\Local\npm-cache\_logs\2024-04-12T19_41_19_016Z-debug-0.log
```

**Comment by wraithgar** [comment]
Not enough here to reproduce.  More info on this error here https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22
