### ISSUE TITLE
[BUG] Random 409 and 403 errors during "npm publish" Although the publish succeeds 

### ISSUE THREAD

**Issue by davidfirst** [npm/cli#7376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [] I am using the latest npm

### Current Behavior

In the CI we publish around 200 packages. Recently, 2-4 random packages out of the 200 are failing during the publish.
The error is mostly 403, but today we got also 409. The failures are not for the same packages, it can be any package.

Here is an example from 3 hours ago:
```
npm notice Publishing to https://registry.npmjs.org/ with tag latest and public access
npm ERR! code E409
npm ERR! 409 Conflict - PUT https://registry.npmjs.org/@teambit%2fcompiler - Conflict
```
Looking into the manifest (and the email sent), the package was actually published successfully in the exact same second of the failure in the CI. Meaning, on the filesystem of the CI (CircleCI), "npm publish" exited with the error above, but in fact, the package was published. 

### Expected Behavior

Because the package was published, it should not exit with code 1 and should not print an error message 409/403.

### Steps To Reproduce

I wish I had steps to reproduce. It happens randomly on the CI during publish.

### Environment

- npm: 10.2.4
- Node.js: 20.11.1
- OS Name: Ubuntu 20.04.6 LTS
- System Model Name:

**Comment by wraithgar** [comment]
This does not appear to be a cli issue. Registry support is at https://www.npmjs.com/support
