### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by digitAI-4N6** [npm/cli#7398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Description:
When attempting to build a React project using npm install, the following build errors are encountered:

ERROR in ./node_modules/react-focus-lock/dist/es2015/index.js 1:0-38
Module not found: Error: Can't resolve './Combination' in '/path_to_project/node_modules/react-focus-lock/dist/es2015'
Did you mean 'Combination.js'?
BREAKING CHANGE: The request './Combination' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e.g., a module with JavaScript mimetype, a '.mjs' file, or a '.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/react-focus-lock/dist/es2015/index.js 2:0-21
Module not found: Error: Can't resolve './UI' in '/path_to_project/node_modules/react-focus-lock/dist/es2015'
Did you mean 'UI.js'?
BREAKING CHANGE: The request './UI' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e.g., a module with JavaScript mimetype, a '.mjs' file, or a '.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

### Expected Behavior

The module should resolve without any errors, as the error messages suggest correct file names with explicit extensions.

### Steps To Reproduce

1. VS code on MacBook Air M1
2. Create new react app
3. Run npm install.

### Environment

- npm:10.5.0
- Node.js:v21.7.3
- OS Name:MacOS Sonoma 14.4.1
- System Model Name:Macbook Air
- npm config:
```ini
; ; "builtin" config from /opt/homebrew/lib/node_modules/npm/npmrc

prefix = "/opt/homebrew" 

; node bin location = /opt/homebrew/Cellar/node/21.7.3/bin/node
; node version = v21.7.3
; npm local prefix = /Users/acehedger/Documents/GitHub/Delmar/Training/Meta Front-End Developer/Advanced React/Graded Assessment/Create your portfolio/node_modules/react-focus-lock
; npm version = 10.5.0
; cwd = /Users/acehedger/Documents/GitHub/Delmar/Training/Meta Front-End Developer/Advanced React/Graded Assessment/Create your portfolio/node_modules/react-focus-lock/dist/es2015
; HOME = /Users/acehedger
; Run `npm config ls -l` to show all defaults.
```

**Comment by wraithgar** [comment]
This appears to be an issue w/ the code being installed not with npm itself.
