### ISSUE TITLE
[BUG] Running npm i <dependency-name> --workspaces results in E401

### ISSUE THREAD

**Issue by maxevilmind** [npm/cli#7400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Dear all, 
I am trying to upgrade a dependency in all of the workspaces by running `npm i my-internal-dependency@^1.1.1 --workspaces`. However it results in a E401 error:
```shell
npm ERR! code E401
npm ERR! Incorrect or missing password.
```
Credentials are right and work just fine with `npm i` in root.

### Expected Behavior

The `npm i my-internal-dependency@^1.1.1 --workspaces` command runs and installs the dependency in each workspace

### Environment

- npm: 10.2.0
- Node.js: v18.18.0
- OS Name: OSX Sonoma 14.4.1 (23E224)
- System Model Name: Macbook Pro M1

**Comment by wraithgar** [comment]
There's not enough here to reproduce the issue locally.

Additionally, please fill out the entire issue template.
