### ISSUE TITLE
[BUG] `npm-shrinkwrap.json` is too large, should be zipped

### ISSUE THREAD

**Issue by RupertBarrow** [npm/cli#7405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When an npm-shrinkwrap.json file is included in a module, this makes it quite large.
For example, when creating small `oclif` plugins, each plugin (npm module) has its own npm-shrinkwrap.json file which, aded together, counts for up to 60% of the total size of the resulting app. 

### Expected Behavior

It would be nice for the npm protocol which creates and reads `npm-shrinkwrap.json` to be able to create a zipped version called `npm-shrinkwrap.gz`, for example.

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 10.5.0
- Node.js: 21.7.3

**Comment by ljharb** [comment]
Including a shrinkwrap file in a package is user-hostile, though, because it prevents deduping and overrides. You could consider omitting it?

**Comment by RupertBarrow** [comment]
@ljharb I'm relying on other packages which publish them (`oclif`). I would like them to have a standard option to zip these files without changing the behaviour of `npm`.

**Comment by ljharb** [comment]
they're inside a tarball already. you want the reified shrinkwrap file to be re-zipped?

**Comment by wraithgar** [comment]
This is more of a feature request.  A good place to start this discussion is at https://github.com/npm/feedback

**Comment by RupertBarrow** [comment]
Thanks @wraithgar , I looked for discussions here but didn't find them. I will post there.
