### ISSUE TITLE
[BUG] NPM 10.6.0 outputs new lines when running npx

### ISSUE THREAD

**Issue by broksonic21** [npm/cli#7419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

With NPM 10.5.2, logs are clear when running npx:

```
~/git/personal/test (main ✔) npx eslint
```

but with 10.6.0, there's new logging that shows up - this breaks tools looking for outputted strings in the results, as it's unexpected. I'm seeing this break some github actions expecting results from commands too: see https://github.com/wearerequired/lint-action/issues/789

It's happening with any and all npx commands

```
~/git/personal/test (main ✔) npx eslint

> REDACTED@0.1.0 npx
> eslint
```

### Expected Behavior

No unexpected logs being written out

### Steps To Reproduce

Using npm 10.5.2
run any command with npx - don't get the logs

Using npm 10.6.0
run any command with npx - get the log lines

### Environment

- npm: 10.6.0
- Node.js: 20.12.2
- OS Name: Mac
- System Model Name: MacBook Pro

Note: also seeing on Ubuntu on Github Actions

**Comment by wraithgar** [comment]
Looks like we missed a spot on banner suppression.

**Comment by wraithgar** [comment]
`explore` also was setting `banner: false`

**Comment by wraithgar** [comment]
Thanks for testing the latest npm so quickly @broksonic21.  `npm@10.6.0` was a complete overhaul of the display layer. We thought we got everything but obviously missed this one.

**Comment by broksonic21** [comment]
Thanks for quick response/getting a fix in action. It broke our CI when renovatebot prompted me to update (see https://github.com/wearerequired/lint-action/issues/789) so was nice and quick.

**Comment by lukekarrys** [comment]
I made #7421 to fix this. This likely won't have to wait for our typical (bi-)weekly release cycle. I think we should put out a quick patch for this a few others.
