### ISSUE TITLE
Update Deps (v7): mkdirp

### ISSUE THREAD

**Issue by mikemimik** [npm/cli#742]
### Notes
`mkdirp@1.x` introduced a large breaking change where `mkdir()` no longer accepts a callback function; it now returns a promise. All places in the codebase that have `mkdir('blahblah', function () { ... })` will need to be replaced with a promise implementation instead.

### References
- https://github.com/npm/statusboard/issues/65

**Comment by darcyclarke** [comment]
**Closing** this as we have a few duplicate issues like this now. It shoudl be covered by other tickets/epics/issues.
