### ISSUE TITLE
[BUG] npm 10.6.0 doesn't log anything while npm install

### ISSUE THREAD

**Issue by lorand-horvath** [npm/cli#7425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

The latest npm 10.6.0 doesn't log anything while installing the packages with `npm install`. It only prints the final results. So npm is working for almost 50 seconds without notifying the user whether it is doing anything at all. The behavior is similar to `npm install --loglevel silent` of the previous version 10.5.2.

### Expected Behavior

The logging should be displayed, showing the user that the installation is proceeding. It shouldn't be silenced completely.

### Steps To Reproduce

1. Environment: Command Prompt, npm 10.6.0, node 18.20.2
2. `npm install` with an existing package.json in the root directory
3. no loggin observed while installing the packages to node_modules

### Environment

- npm: 10.6.0
- Node.js: 18.20.2
- OS Name: Windows
- System Model Name: Desktop PC
```ini
; copy and paste output from `npm config ls` here
```

**Comment by wraithgar** [comment]
The progress bar in npm has been temporarily removed.  It was conflicting with logging output and was generally inaccessible.  What you are used to seeing is a mix of the progress bar and `verbose` logging (which was shown erroneously, regardless of loglevel).  If you want to see the logging messages you can use `--verbose`.

**Comment by lorand-horvath** [comment]
@wraithgar I would prefer seeing some kind of progress log while npm is actually performing some work, by default. Otherwise users might confuse the silence with the process being stalled or hanging or a bug or something. Sometimes an npm install on a large project may take several minutes. Something should be displayed (some sort of spinner, progress bar, etc) while doing work that take longer than, say, 5 seconds.
Is this total silence a temporary problem? Are you going to add back some kind of progress bar in later version?

I had to revert to 10.5.2 because this was very strange, not showing anything for long periods of time - I thought something was broken.

**Comment by wraithgar** [comment]
Yes it is temporary.

**Comment by henderea** [comment]
> I thought something was broken

Same here, so I interrupted my `npm update -gs` command and then something actually _was_ broken. As in my entire NPM install. I had to note down my global packages by looking at the contents of the install directory, then uninstall and reinstall node with NVM and install all of my stuff again.

Not a huge disaster, but definitely not great either.

So word to the wise: don't interrupt it when you have the `-g` flag, because you will probably break your NPM 😓

**Comment by lukekarrys** [comment]
We'll keep this open until we land a new "npm is actually doing something" visual. It probably won't be a progress bar initially but a simple spinner.

**Comment by lorand-horvath** [comment]
@lukekarrys @wraithgar  Thanks for taking the time to add the spinner! However, this could be improved upon, compared to how it was before in 10.5.2. My concerns are the following:
1. The spinner is there as expected, but there's a constant blinking cursor overlapping with it and it looks a bit unfinished or buggy.
2. The installation process seems slower. I could revert to 10.5.2 and time the installations to see what the difference is.
3. The spinner is not enough as default information. In previous versions I really liked the way it informed the user about what was currently doing, for example during `npm install`, so I would very much like to see something of the sort:
```
\ install react@18.3.1
| install react-dom@18.3.1
/ install styled-components@6.1.9
- update vite@5.2.10
\ update vite-plugin-eslint@1.8.1
| reify etc...
```
Wouldn't that be nicer?

**Comment by lukekarrys** [comment]
Those are good suggestions. To take them point by point:

1. There is a way to hide the cursor which should be easy enough to do only when the spinner is visible. I will look into this and any accessibility implications it might have.
2. I'd be interested in seeing benchmarks if you have any from before and now. Also if you run with `--no-progress` do you still see a performance impact?
3. The reason we moved away from how it used to work is that the progress bar showed messages that were primarily intended for logging. They weren't tailored for usability and would often show the last completed action when the current running action was hanging which led to lots of confusion. I'm in favor of bringing something similar back but we'd first need to put all the events in place in Arborist to accurately indicate what's happening in a user-friendly manner. But that will take more time.

Im going to log these in our follow up status board issue. Thanks for taking the time to provide these feedback!

**Comment by wraithgar** [comment]
You can get what you described by setting your log level to `http`, those were the logging messages "leaking" into the progress bar before.

**Comment by lorand-horvath** [comment]
@wraithgar I've tried `npm install --loglevel http` and I get a long running list with the package downloads (http fetch), which is not bad per se, but I'd like to see what is actually being installed and also other activities being performed, not only what is being downloaded (or found in cache); all of this preferably in one single progress line (the previous action needs to be overwritten to the same line), similar to how it was before in 10.5.2.

**Comment by lorand-horvath** [comment]
>     2. I'd be interested in seeing benchmarks if you have any from before and now. Also if you run with `--no-progress` do you still see a performance impact?
> 
I've run several benchmarks on a certain package (react frontend app) and the difference is not so large:
npm 10.5.2: `npm install` finished in 1:10
npm 10.7.0: `npm install` finished in 1:07
npm 10.7.0: `npm install --no-progress` finished in 0:59
>     3. The reason we moved away from how it used to work is that the progress bar showed messages that were primarily intended for logging. They weren't tailored for usability and would often show the last completed action when the current running action was hanging which led to lots of confusion. I'm in favor of bringing something similar back but we'd first need to put all the events in place in Arborist to accurately indicate what's happening in a user-friendly manner. But that will take more time.
> 
I'd very much like to see a user-friendly manner of displaying the currently performed action with `npm install`, I posted more details in my comment above to @wraithgar 
> 
> Im going to log these in our follow up status board issue. Thanks for taking the time to provide these feedback!

Thank you @lukekarrys @wraithgar for your quick and constructive responses!

**Comment by voltuer** [comment]
you should at least warn users who don't usually read docs or issues about the removal of something as iconic and important as a progress indication, why not at least copy what pnpm has achieved, which is a very clean and informative enough approach? a spinner is like a joke

**Comment by henderea** [comment]
One thing to add is that nothing shows when you use the `-s` flag. It used to show the progress stuff in older versions, just without all of the extra lines of output, so I think the spinner should show even with the `-s` flag. Because leaving off the `-s` flag means a lot of extra output that I generally don't want to see.

**Comment by DanielSharp01** [comment]
This update also coincides with this spinner getting stuck at times giving no info at all where. I thought npm is broken glad to see it was just a bad decision.

**Comment by kamalciirs** [comment]
progress bar was better

**Comment by voltuer** [comment]
let's just stop using this crap, PNPM is mopping the floor with NPM, it's about time it replaces it as the default installer.

NPM is the same as Safari on Mac or Edge on Windows: a medium to install the real software you're going to use.

**Comment by code-franklin** [comment]
i solve it before. i don't remember where i get the solution.

**Comment by pranay-dutta** [comment]
Is there any solution for this? Can we visualize it like _**pnpm**_?

**Comment by kamalciirs** [comment]
> Is there any solution for this? Can we visualize it like _**pnpm**_?

Just use `pnpm` lol..

**Comment by sebfindling** [comment]
> Is there any solution for this? Can we visualize it like _**pnpm**_?

Just wait, it's only been 10 months since they said it was temporary. 

NPM belongs to Microsoft now, so they have more resources. It's probably going to take them less than 10 years to bring back what they unnecessarily removed.

**Comment by jonataswalker** [comment]
> > Is there any solution for this? Can we visualize it like _**pnpm**_?
> 
> Just wait, it's only been 10 months since they said it was temporary.
> 
> NPM belongs to Microsoft now, so they have more resources. It's probably going to take them less than 10 years to bring back what they unnecessarily removed.

And counting

**Comment by voltuer** [comment]
> > > Is there any solution for this? Can we visualize it like _**pnpm**_?
> > 
> > Just wait, it's only been 10 months since they said it was temporary.
> > 
> > NPM belongs to Microsoft now, so they have more resources. It's probably going to take them less than 10 years to bring back what they unnecessarily removed.
> 
> And counting

as long as time exists, "temporary" will still be on rule for this, there's absolutely no reason whatsoever not to switch to pnpm. Add some husky rules to prevent other people from using npm in your pnpm project and move on. I know I did, and I'm so damn happy.

**Comment by Mupli** [comment]
omg it should not be closed. It should be closed when fiexed..

**Comment by voltuer** [comment]
> omg it should not be closed. It should be closed when fiexed..

 @Mupli it's because it's not a bug, it's a feature. NPM is only meant to be used to download PNPM, just like every Microsoft software (like Edge) is only meant for downloading Chrome, PowerShell to install WSL, etc.
