### ISSUE TITLE
[BUG]  npx in version 10.6.0 outputs info before actual command result

### ISSUE THREAD

**Issue by Balvajs** [npm/cli#7428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When a CLI package is run with `npx`, for example `npx tsc`, the output starts with info:
```

> @my-company/my-package@1.2.3 npx
> tsc

... the actual output of `tsc`
```

### Expected Behavior

When a CLI package is run with `npx`, for example `npx tsc`, the output should be only what `tsc` prints to the console, nothing else.

### Steps To Reproduce

1. In the MacOS terminal environment
2. Run `npx any-package`
3. See the output starting with a new line and `> `

### Environment

- npm: 10.6.0
- Node.js: 20.10.0
- OS Name: MacOS
- System Model Name: Macbook Pro
- npm config:
```ini
; "user" config from /Users/t.balvin/.npmrc

//registry.npmjs.org/:_authToken = (protected)
; save-exact = true ; overridden by project
; save-prefix = "" ; overridden by project

; "project" config from /Users/t.balvin/Projects/my-company/my-package/.npmrc

engine-strict = true
save-exact = true
save-prefix = ""

; node bin location = /Users/t.balvin/.nvm/versions/node/v20.10.0/bin/node
; node version = v20.10.0
; npm local prefix = /Users/t.balvin/Projects/my-company/my-package
; npm version = 10.6.0
; cwd = /Users/t.balvin/Projects/my-company/my-package
; HOME = /Users/t.balvin
; Run `npm config ls -l` to show all defaults.
```

**Comment by milaninfy** [comment]
same issue as #7419  fixed in #7419
