### ISSUE TITLE
EIntegrity error is thrown while doing npm install

### ISSUE THREAD

**Issue by sathishchandran97** [npm/cli#744]
My scenario is to unzip the published package, remove the unneeded package according to the user access, zip it again and install it for the user using verdaccio middleware plugin.
I am able to unzip,remove,zip but i am facing issue while installing it as SHA encryption key gets differed from the original package and because of that i am getting eintegrity error.

Can you please help me here as how to handle the SHA key modification?

Thanks in advance 
![Capture](https://user-images.githubusercontent.com/50132149/73458831-e6d60900-439b-11ea-8d1c-bf951d0d70fa.PNG)

**Comment by DanielRuf** [comment]
Try clearing your cache.

**Comment by sathishchandran97** [comment]
@DanielRuf , I've tried that also

**Comment by DanielRuf** [comment]
Is any sort of proxy or something else used?

What is the exact npm version that you use?
