### ISSUE TITLE
[BUG] npm audit consistently not finding any vulnerabilities

### ISSUE THREAD

**Issue by LironJit** [npm/cli#7445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Today I noticed running `npm audit` on a vulnerable environment **always** says there are 0 findings, even when there's an actual CVE/GHSA for the particular package(s)

### Expected Behavior

There should be vulnerabilities, these packages are vulnerable and alternative tools scanned the same files properly

### Steps To Reproduce

Example package.json
```json
{
  "name": "@some/repo",
  "version": "0.6.5",
  "description": "some repo",
  "main": "dist/lib/index.js",
  "dependencies": {
    "webpack": "5.0.0"
  }
}

```

Or alternatively use package 
```
"pac-resolver": "4.2.0"
```
Which is also vulnerable

Run 
```
npm audit
```

You'll get 
```
➜  test git:(main) ✗ npm audit
found 0 vulnerabilities
```

### Environment

- npm: 10.6.0 but happens with older versions for example 8.19.2
- Node.js: 20.5.0 but also happens with 16.20.2
- OS Name: macOS Sonoma 14.4.1
- System Model Name: Macbook Pro M1
- npm config:
```ini
; node bin location = /Users/lironbiam/.nvm/versions/node/v20.5.0/bin/node
; node version = v20.5.0
; npm local prefix = /Users/lironbiam/Documents/test
; npm version = 10.6.0
; cwd = /Users/lironbiam/Documents/test
; HOME = /Users/lironbiam
```

**Comment by yoieh** [comment]
Same issue with yarn audit:
https://github.com/yarnpkg/yarn/issues/9054

**Comment by yoieh** [comment]
There's something wrong with Security Audit even tho it's up and running according to the status page... 
https://status.npmjs.org/

I created a support ticket at https://www.npmjs.com/support since this feels like a bigger issue :)

**Comment by csnktms** [comment]
can confirm this issue!
```sh
curl -vd "$(cat package-lock.json)" https://registry.npmjs.org/-/npm/v1/security/audits
```

response:
```json
{"actions":[],"advisories":{},"muted":[],"metadata":{"vulnerabilities":{"info":0,"low":0,"moderate":0,"high":0,"critical":0},"dependencies":0,"devDependencies":0,"optionalDependencies":0,"totalDependencies":0}}%
```

**Comment by SageGary** [comment]
Me too. And people have begun reporting same on stackoverflow and twitter: 
https://stackoverflow.com/questions/78406511/npm-audit-always-finding-0-vulnerabilities
https://twitter.com/rjmacarthy/status/1785218995211149463

**Comment by wraithgar** [comment]
This does not appear to be an npm cli issue. npm registry support is at https://www.npmjs.com/support

**Comment by yoieh** [comment]
This has now been fixed by npm! 😄
