### ISSUE TITLE
[BUG] Scoped packages attempted to download from http and not https url as defined in npmrc file

### ISSUE THREAD

**Issue by aswinfrancis91** [npm/cli#7461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I have used npm config to setup a scoped registry that has a https path. However when I see the generated package-lock.json, it shows HTTP URL. I had the same problem when I used npm set config command to set these values which would add the npmrc file in users folder. I moved it to npmrc file within project so its common for the team. However right now I have to run `npm i --package-lock-only` to generate the lock.json file, then manually update the URL to https so that `npm install` works

### Expected Behavior

Should use the same URL defined in .npmrc file

### Steps To Reproduce

1. Add package @privateregistry/Dummy to package.json
2. Run npm install
3. Will see below errors as HTTP URL of our registry is not accessible. I have updated the path and registry name to match the one in config I shared in the 'Environment' section
```
npm error code ECONNREFUSED
npm error syscall connect
npm error errno ECONNREFUSED
npm error FetchError: request to http://privateregistry.com/npm/feedname/%40myregistry/Test.SDK/-/Test.SDK-1.0.1-beta.1.1.tgz failed, reason: connect ECONNREFUSED 1X.X.X.X:
```

### Environment

- npm: 10.7.0
- Node.js: v20.12.2
- OS Name: Windows 10 Enterprise
- System Model Name:Dell Lattitude 5400
- npm config:
```ini
; "project" config from D:\Development\Repos\Test1\ProjectName\uiproject\.npmrc

@myregistry:registry = "https://privateregistry.com/npm/feedname/"
//privateregistry.com/npm/feedname/:_auth = (protected)
registry = "https://registry.npmjs.org/"

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v20.12.2
; npm local prefix = D:\Development\Repos\Test1\ProjectName\uiproject
; npm version = 10.7.0
; cwd = D:\Development\Repos\Test1\ProjectName\uiproject
; HOME = C:\Users\username
```

**Comment by aswinfrancis91** [comment]
Found a similar issue https://github.com/npm/npm/issues/20189

**Comment by milaninfy** [comment]
This is my test `.npmrc` file 
```bash
~/workarea/rep $ cat .npmrc 
@myregistry:registry = "https://privateregistry.com/npm/feedname/"
registry = "https://registry.npmjs.org/"
```
Full output of scoped package installation. The registry is getting correctly picked up with url mentioned in .npmrc file. 
```bash
~/workarea/rep $ npm install @myregistry/test -d  
npm info using npm@10.7.0
npm info using node@v22.0.0
npm http fetch GET https://privateregistry.com/npm/feedname/@myregistry%2ftest attempt 1 failed with ECONNRESET
npm http fetch GET https://privateregistry.com/npm/feedname/@myregistry%2ftest attempt 2 failed with ECONNRESET
```
I am not able to reproduce with the steps. 

Please provide full log of `npm i --package-lock-only --ddd` with related config.

**Comment by milaninfy** [comment]
@aswinfrancis91 Can you provide output for for this ?
`npm view @scoped/package dist.tarball --registry=https://privateregistry.com/npm/feedname/`

**Comment by aswinfrancis91** [comment]
@milaninfy  The output shows http url. Is that the reason?
http://privateregistry.com/npm/feedname/%40myregistry/Test.SDK/-/Test.SDK-1.0.1-beta.1.1.tgz

I also ran npm i command you asked me to. Below are parts of the log pertaining to scoped registry
```
npm silly fetch manifest @myregistry/Test.SDK@^1.0.1-beta
npm http fetch GET 200 https://privateregistry.com/npm/feedname/@myregistry%2fTest.SDK 49962ms (cache updated)
```

**Comment by milaninfy** [comment]
@aswinfrancis91 Private Registry is giving back http url for tarball which is in http. Please check with registry support for that.
