### ISSUE TITLE
Typo in install-clean command

### ISSUE THREAD

**Issue by gaurav-goswami** [npm/cli#7469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Problem, not another kind of Docs Problem.

- [x] This is a CLI Docs Problem.

### Description of Problem

https://docs.npmjs.com/cli/v9/commands/npm-ci

Under the synopsis there's a typo in the `install-clean` command

![image](https://github.com/npm/cli/assets/122979352/d8dc2149-0569-40da-a3ee-d5521b9507d5)

install-clean is written as isntall-clean

### Potential Solution

Change the command from isntall-clean to install-clean

### Affected URL

https://docs.npmjs.com/cli/v9/commands/npm-ci

**Comment by danieldbird** [comment]
Hi @gaurav-goswami , I think what you are looking at there are examples of aliases that will still work even if the command is typed incorrectly by mistake.
ie: 
<img width="535" alt="image" src="https://github.com/npm/cli/assets/2720368/39f11c2b-6272-4ff9-9665-9838b531bfba">

Not actually a typo in the documentation.

The repo for documentation is here: https://github.com/npm/documentation

**Comment by gaurav-goswami** [comment]
@danieldbird  Hey Daniel, I've figured it out now! Thank you so much for your help. Initially, I thought it might have been a typo in the documentation. Your explanation cleared things up for me. Thanks again!
