### ISSUE TITLE
add globalDependencies to package.json

### ISSUE THREAD

**Issue by its-dibo** [npm/cli#747]
add globalDependencies to package.json whitch the project needs to be installed globally in the machine that runs the code.

use case:
when working in the project to any environment such as cloud-based IDE (ex: repl.it, google shell, ...) 
one have to manually remember and install all global packages that already installed in his local machine.

but when you move your code to a new workspace such as repl.it you suddenly find that your code stops many times because one of your global packages not installs.

for example when I run the command `npm run start` it internlly run `ng build` and other commands, but you have to remember to install the angular cli everytime you work in a new workspace.

providing globalDependencies will do the trick automatically for you, and inform the new workspace that it should install these packages globally,

**Comment by ljharb** [comment]
Why can’t these environments have a local package.json?

**Comment by its-dibo** [comment]
because it wanted to be installed globally per project.
i.e: every project needs some of these packages to be installed globally.

**Comment by ljharb** [comment]
Can you elaborate on why any global dependency is needed ever?

**Comment by ljharb** [comment]
If you're still interested in this, https://github.com/npm/rfcs is a better place to file it.
