### ISSUE TITLE
[BUG] npm install failing with ECONNRESET error

### ISSUE THREAD

**Issue by vishwajeet-hol** [npm/cli#7477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When I am running `npm i `on my repository, its failing with below error.

> npm ERR! code ECONNRESET
npm ERR! network aborted
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

Please check complete logs here:
[npm_8.log](https://github.com/npm/cli/files/15219326/npm_8.log)

### Expected Behavior

`npm i` should work perfectly

### Steps To Reproduce

1. Clone private repo
2. Run 'npm i'

### Environment

- npm:   v8.19.4
- Node.js:  v16.20.0
- OS Name: macOS sonoma v14.4
- System Model Name: Macbook Pro

**Comment by wraithgar** [comment]
This does not appear to be a problem with npm, you may want to contact whoever runs your private registry about this.

Also you checked `I am using the latest npm` but are on npm 8.  The latest npm is currently `10.7.0`

**Comment by vishwajeet-hol** [comment]
Thank you for the response @wraithgar. Will check with registry owners.
Regarding `I am using the latest npm ` check, If I don't select that I was unable to create an issue, submit issue button was disabled. Thats the reason I selected it.

**Comment by wraithgar** [comment]
That's the purpose of that checkbox.  We do not support npm 8.  Only reports that are reproducible on the latest npm that are bugs in npm itself should be made.

**Comment by wraithgar** [comment]
@vishwajeet-hol it looks like your `.npmrc` file has a misconfigured auth token, and thus npm did not know it was an auth token and didn't filter it when outputting `npm config list`.  You may want to revoke that token on your private registry.
