### ISSUE TITLE
[BUG] <title>npm EXIT handler never called

### ISSUE THREAD

**Issue by Likhithabs** [npm/cli#7481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

RUN npm install in docker file is throwing this error.
I'm trying to build docker image for a node js application

### Environment

- npm: 10.7.0
- Node.js: v20.12.2
- OS Name: Ubuntu 20.04.5 LTS
- System Model Name:
- npm config:
; node bin location = /usr/local/bin/node
; node version = v20.12.2
; npm local prefix = /home/lfi1kor/Documents/Likhitha/mars_tool/project/frontend-vite-vue
; npm version = 10.7.0
; cwd = /home/lfi1kor/Documents/Likhitha/mars_tool/project/frontend-vite-vue
; HOME = /home/lfi1kor

**Comment by milaninfy** [comment]
**Closing:** this error can arise for a number of reasons; Please read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) & refile an issue with as much information as possible if you're able to **consistently reproduce** this error.
