### ISSUE TITLE
Can we create different users and give specific access to that users to access database(add,delete,view etc) in Mongo Express

### ISSUE THREAD

**Issue by hasan13579** [npm/cli#751]
# What / Why

> n/a

## Where

* n/a

## Who

* n/a

## References

* n/a

**Comment by hasan13579** [comment]
Can we create different users and give specific access to that users to access database(add,delete,view etc) in Mongo Express ?

**Comment by DanielRuf** [comment]
Wrong repo. Please ask this at https://github.com/mongo-express/mongo-express/issues and close this issue here.
