### ISSUE TITLE
[BUG] Fatal error Check failed: VerifyChecksum(blob)

### ISSUE THREAD

**Issue by Sinan81** [npm/cli#7528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I'm build building npm using Spack package manager. The manually building of npm works fine, however the build fails in a CI/CD pipeline as shown in the link. Would appreciate any insight into what the issue might be.
https://gitlab.spack.io/spack/spack/-/jobs/11258938

### Expected Behavior

npm should build fine.

### Steps To Reproduce

Issue occurs only in CI/CD pipeline.

### Environment

- npm: 9.3.1
- Node.js: 20.12.2
- OS Name: centos7 (although it also failed for ubuntu
- System Model Name:
- npm config: not sure
```ini
; copy and paste output from `npm config ls` here
```

**Comment by Sinan81** [comment]
related to https://github.com/spack/spack/pull/43683

**Comment by wraithgar** [comment]
This does not appear to be an issue w/ npm but with the ci/build system itself.

Also, npm 9 is not the latest npm.  Please make sure you are testing things in the latest version of npm before opening an issue.

**Comment by Sinan81** [comment]
I'm not very familiar with npm, would appreciate quick tips on how to fix this, if any.
