### ISSUE TITLE
[BUG] `npm view` returning string without quotes with version 10.8.0

### ISSUE THREAD

**Issue by byCedric** [npm/cli#7537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When using `npm view <package> <selector> --json`, I expect only to receive JSON data types. Unfortunately, for `npm@10.8.0` that's not the case anymore.

Running `npm view expo-template-bare-minimum@sdk-51 dist.tarball --json` now yields the `tarball` string, without quotes, making it not a JSON result anymore.

<img width="681" alt="image" src="https://github.com/npm/cli/assets/1203991/0a704d24-b69a-4db6-b0b4-f2a7b6340be1">

### Expected Behavior

When using this same command with `npm@10.7.0`, the response is wrapped in quotes, making it a valid JSON response (or at least parsable through `JSON.parse(...)`.

<img width="689" alt="image" src="https://github.com/npm/cli/assets/1203991/330300b9-f841-463e-90d6-ccc6bbdab5c8">

### Steps To Reproduce

Result that's _not_ parsable with `JSON.parse`:
1. `$ npm i -g npm@10.8.0`
2. `$ npm -v` → Should return `10.8.0`
3. `$ npm view expo-template-bare-minimum@sdk-51 dist.tarball --json`
  → Should return `https://...` _(without quotes)_

Result that _is_ parsable with `JSON.parse`:
1. `$ npm i -g npm@10.7.0`
2. `$ npm -v` → Should return `10.7.0`
4. `$ npm view expo-template-bare-minimum@sdk-51 dist.tarball --json`
  → Should return `"https://..."` _(with quotes)_

### Environment

- npm: 10.8.0
- Node.js: 22.2.0
- OS Name: macOS Sanoma 14.4.1
- System Model Name: MacBook Pro (14" 2023)
- npm config:
```ini
; "user" config from /Users/cedric/.npmrc

//registry.npmjs.org/:_authToken = (protected)
store-dir = "/Users/cedric/.pnpm"

; node bin location = /Users/cedric/.nvm/versions/node/v22.2.0/bin/node
; node version = v22.2.0
; npm local prefix = /Users/cedric/Desktop
; npm version = 10.8.0
; cwd = /Users/cedric/Desktop
; HOME = /Users/cedric
; Run `npm config ls -l` to show all defaults.
```

**Comment by lukekarrys** [comment]
I introduced this in https://github.com/npm/cli/pull/7513. Will have a PR to fix it shortly.
