### ISSUE TITLE
I can't able to start the npm

### ISSUE THREAD

**Issue by Sasi-007** [npm/cli#754]
![npm](https://user-images.githubusercontent.com/42794655/73591885-35a9ad00-451a-11ea-92e1-887e22ed26c2.jpg)

I modified a package.json file little changes after this issue but it never solved.

**Comment by ljharb** [comment]
“start” is a script you have to manually define in your own package.json.

**Comment by Sasi-007** [comment]
Its already defined bro but not working
![npm](https://user-images.githubusercontent.com/42794655/73595588-8f24d280-4540-11ea-8157-82ba9bc33709.jpg)

**Comment by ljharb** [comment]
Please don’t call me “bro”.

Assuming that file is in the same directory (Desktop/React), that does seem strange.

**Comment by ljharb** [comment]
Closing pending further repro info.
