### ISSUE TITLE
[BUG] typeerror Error: Missing required argument #1

### ISSUE THREAD

**Issue by jvidin** [npm/cli#756]
# What / Why
 npm install -g @here/cli

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:109:7
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

[npm-debug.log](https://github.com/npm/cli/files/4142978/npm-debug.log)

**Comment by DanielRuf** [comment]
Please provide additional information about your node version and npm version.

**Comment by holger-tuerk-md** [comment]
I am seeing the same error. node is 8.10.0, npm is 3.5.2, installed using the usual Ubuntu packages.

**Comment by DanielRuf** [comment]
npm 3 is very old, please upgrade it to 6.x.
