### ISSUE TITLE
[BUG] npm pack in 10.5.0 introduces breaking change due to changed output 

### ISSUE THREAD

**Issue by falsyvalues** [npm/cli#7561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Prior to v10.5.0 there was possibility to directly redirect `npm pack` output to file and retrieve tarball file name for given package. Starting from 10.5.0 and above stdout is being polluted by prepare scripts output and command itself.
```
> library@1.0.0 prepare
> echo "Should not be visible"
library@1.0.0.tgz
```

### Expected Behavior

`npm pack` should output to std only tarball file name as it was before otherwise its a breaking change.

### Steps To Reproduce

1. In any package add prepare script which writes to stdout
2. Run `npm pack` and redirect stdout to file e.g. `npm package > package-name` 
3. Inspect `package-name` file content
4. It should contain only package tarball name

### Environment

- npm: v10.8.0
- Node.js: v20.13.1
- OS Name: macOS 14.4.1
- System Model Name: MacBook Pro

**Comment by milaninfy** [comment]
@falsyvalues This change was introduced as a fix to correct the regression. Follow discussion on this PR https://github.com/npm/cli/pull/7158 to get more background on this change. You can use this flag [foreground-scripts](https://docs.npmjs.com/cli/v10/using-npm/config#foreground-scripts) or ~~`--silent`~~ to get expected output result.

**Comment by falsyvalues** [comment]
@milaninfy Will I get the reasoning, result remains the same - breaking for end user. Also `--silent` won't help because it mutes only script call not the result.
```json
{
    "prepare": "echo \"Noise\""
}
```
```
$ npm pack --silent
Noise
library@1.0.0.tgz
```

**Comment by milaninfy** [comment]
@falsyvalues Apologies I must have thought something else when I suggested `--silent` flag 
but here is the output with `npm pack --foreground-scripts=false > test2.txt`. 
```bash
~/workarea/rep $ npm pack --foreground-scripts=false > test2.txt
npm notice
npm notice 📦  rep@1.0.0
npm notice Tarball Contents
npm notice 348B package.json
npm notice 361B rep-1.0.0.tgz
npm notice 91B test.txt
npm notice 0B test2.txt
npm notice Tarball Details
npm notice name: rep
npm notice version: 1.0.0
npm notice filename: rep-1.0.0.tgz
npm notice package size: 843 B
npm notice unpacked size: 800 B
npm notice shasum: 4c9cb5a1cdce1b1a5b8a25ea8fa8f7502693f68d
npm notice integrity: sha512-mhud3Gqlf4hPJ[...]pwBJEk6+zokgg==
npm notice total files: 4
npm notice

~/workarea/rep $ cat test2.txt 
rep-1.0.0.tgz
```
with `--silent` flag 

```bash
~/workarea/rep $ npm pack --foreground-scripts=false --silent
rep-1.0.0.tgz
```

**Comment by milaninfy** [comment]
This is currently working as intended,
