### ISSUE TITLE
[BUG] How do I know that which version of nodeJS and npm are using a mern stack project

### ISSUE THREAD

**Issue by salmanansari14** [npm/cli#7577]
*Question*

How do I know which version of nodeJS and npm are using a mern stack project.

because my mern project is too old and I did not recognize which version of npm is used in that project so that I can install that version of npm to run that project.

**Comment by ljharb** [comment]
If it's not listed in package.json, or package-lock.json, or the CI config, or documentation, then you'll just have to guess.

**Comment by milaninfy** [comment]
**Closing:** this looks to be a general support question which is outside the scope of the repo. For support please post your question to [github.community](https://github.community).
