### ISSUE TITLE
[BUG] `npm ci` doesn't properly compare `package.json` with `package-lock.json`

### ISSUE THREAD

**Issue by s100** [npm/cli#7578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Starting from a completely empty directory, I run `npm install --save-dev base65536`. This causes both `package.json` and `package-lock.json` to be created. I then manually edit `package.json` to promote `base65536` from being a development dependency to a production dependency. I then run `npm ci`.

`npm ci` exits with code 0, no errors.

### Expected Behavior

The [documentation](https://docs.npmjs.com/cli/v10/commands/npm-ci#description) for `npm ci` states:

> If dependencies in the package lock do not match those in `package.json`, `npm ci` will exit with an error, instead of updating the package lock.

In this case there is indeed a mismatch: in `package.json`, `base65536` is listed as a production dependency, but in `package-lock.json`, `base65536` is still listed as a development dependency. Therefore, I would expect `npm ci` to exit with an error.

I'm not totally certain what the scope of "dependencies [...] do not match" is, but my expectation is that if running `npm install` right now would cause `package-lock.json` to change, then `npm ci` should consider that `package.json` and `package-lock.json` currently do not match, and error out. If this isn't correct then perhaps this could be considered a documentation issue.

### Steps To Reproduce

1. Start from an empty directory
2. `npm install --save-dev base65536`
3. Observe that both `package.json` and `package-lock.json` have been created - both list `base65536` under `"devDependencies"`
4. Manually edit `package.json` from

```json
{
  "devDependencies": {
    "base65536": "^4.0.3"
  }
}
```

to

```json
{
  "dependencies": {
    "base65536": "^4.0.3"
  }
}
```

5. `npm ci`
6. `echo $?` - output is 0, would expect 1 due to the mismatch
7. (Optionally) Run `npm install` and note that the `package-lock.json` is now updated to reflect the changes in `package.json`

### Environment

- npm: 10.8.1
- Node.js: v18.20.3
- OS Name: Windows
- System Model Name: ThinkPad P15
- npm config:
```ini
; "user" config from C:\Users\s100\.npmrc
engine-strict = false
; package-lock = false ; overridden by project

; "project" config from C:\Users\s100\Downloads\.npmrc

package-lock = true

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v18.20.3
; npm local prefix = C:\Users\s100\Downloads
; npm version = 10.8.1
; cwd = C:\Users\s100\Downloads
; HOME = C:\Users\s100
; Run `npm config ls -l` to show all defaults.
```

**Comment by reggi** [comment]
@s100 Thank you for this report. I've looked into it myself and I agree, it's strange behavior at first. It's important to note that `npm ci` doesn't ensure that `package-lock.json` is an exact match with its ideal state (or a freshly generated package-lock.json). Its main role is to verify that all packages in `node_modules` are accounted for in `package-lock.json`. This is evident when you strip down the lock file to a minimal state, and `npm ci` still returns a `0` exit code. So, from the perspective of the lock file, whether a package is in `devDependencies` or `dependencies` doesn't make a significant difference, as they're installed in the same location on the disk, with the same version and SHA.

```json
{
  "packages": {
    "node_modules/base65536": {
      "resolved": "https://registry.npmjs.org/base65536/-/base65536-4.0.3.tgz",
      "integrity": "sha512-4VLZP1tOlE4YoZ2T+qlNXbbes3/YOo1HAVWt41uUOn9ZSIQlEhlxaCd5eL9hCz4nX3omfQgco/Tvi2eVgJFyNw=="
    }
  }
}
```

I'm gonna close this out for now, as I believe this isn't an issue.

<details>
<summary>Script to recreate</summary>

```bash
# Initialize a new npm project
npm init -y

# Install base65536 as a dev dependency
npm install --save-dev base65536

# Promote base65536 from devDependencies to dependencies in package.json
jq '.dependencies = .devDependencies | .devDependencies = {}' package.json > temp.json && mv temp.json package.json

# Run npm ci
npm ci
```

</details>
