### ISSUE TITLE
[BUG] If the project name is node_modules, this error will be reported

### ISSUE THREAD

**Issue by weijiyang** [npm/cli#7581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

If the project name is node_modules, this error will be reported

### Expected Behavior

install successfully

### Steps To Reproduce

1. try many node npm version, all can be reproduced
2. use Vue-cli create a new project
3. Run 'npm install'
4. See error...
![image](https://github.com/npm/cli/assets/23150533/e9fabc9e-8251-4866-9ea5-92e7de802e8c)

error details:
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path /Users/username/GIT/node_modules/node_modules/yorkie
npm ERR! command failed
npm ERR! command sh -c node bin/install.js
npm ERR! node:internal/modules/cjs/loader:1080
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module 'is-ci'
npm ERR! Require stack:
npm ERR! - /Users/username/GIT/node_modules/node_modules/yorkie/bin/install.js
npm ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:922:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1143:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:119:18)
npm ERR!     at Object.<anonymous> (/Users/username/GIT/node_modules/node_modules/yorkie/bin/install.js:5:14)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1256:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1119:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:960:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     '/Users/username/GIT/node_modules/node_modules/yorkie/bin/install.js'
npm ERR!   ]
npm ERR! }
npm ERR!
npm ERR! Node.js v18.18.2

### Environment

; node bin location = /Users/username/.nvm/versions/node/v18.18.2/bin/node
; node version = v18.18.2
; npm local prefix = /Users/username/GIT/node_modules
; npm version = 9.8.1
; cwd = /Users/username/GIT/student
; HOME = /Users/username
; Run `npm config ls -l` to show all defaults.

**Comment by milaninfy** [comment]
`node_modules` is not a valid name for a project.
