### ISSUE TITLE
[Feature request] Support overriding `main`, `exports` and other package.json fields with `publishConfig`

### ISSUE THREAD

**Issue by remorses** [npm/cli#7586]
Currently `publishConfig` can only override .npmrc fields, other package managers like yarn and pnpm instead let you override exports and main for example.

Adding support for this feature would allow using typescript files in development and javascript dist files when publishing, making package development much easier. https://github.com/isaacs/tshy/issues/65

It would also make npm behaviour consistent with other package managers.

**Comment by wraithgar** [comment]
That is not the purpose of the field. It is to change `config` during publish.  Changing the package.json during publish is the source of what some folks are calling "dependency confusion" and moves us in the opposite direction than we want.  Ultimately the package.json on disk needs to match the manifest in the registry.  This is a bad security decision and npm is currently not planning on supporting it.
