### ISSUE TITLE
Should npm init emit type=module?

### ISSUE THREAD

**Issue by bcherny** [npm/cli#7594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When I run `npm init`, the generated package.json does not include a `type` field.

### Expected Behavior

NodeJS has supported ES Modules since version ~12 ([link](https://nodejs.org/api/packages.html#type)). If using ES Modules is the recommended approach for JS packages targeting Node/browsers, then it may make sense to update `npm init` to enable ES Modules by default.

Adoption of `type=module` is around [10%](https://github.com/bcherny/es-module-stats/blob/main/data/totals.json) today. By making `type=module` the default, I expect many more projects to use ES Modules going forward.

**Comment by ljharb** [comment]
This has been discussed many times, and would be a bad default, and is not required for usage of ESM. The best way to use ESM is .mjs files.

**Comment by bcherny** [comment]
@ljharb my search skills must be failing me. I'd be curious to see some of those previous discussions.

**Comment by ljharb** [comment]
- https://github.com/npm/rfcs/issues/620
 - https://github.com/npm/rfcs/discussions/75
 - https://github.com/npm/rfcs/issues/347

**Comment by wraithgar** [comment]
This is a pretty significant feature request and the discussions are happening in the other issues listed.
