### ISSUE TITLE
[BUG] npm install progress bar not showing

### ISSUE THREAD

**Issue by Blink29** [npm/cli#7597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

when i do npm install the progress bar is not showing 
<img width="1470" alt="Screenshot 2024-06-16 at 12 00 54 PM" src="https://github.com/npm/cli/assets/115066832/0e15abbf-5d4d-485a-84d9-eee366021045">

### Expected Behavior

the progress bar should show 

### Steps To Reproduce

1.just do npm i anything 

### Environment

- npm: 10.7.0
- Node.js: 21.14.0
- OS Name: MacOS14.5
- System Model Name: Macbook Air M2
- npm config:
```ini
paurushkumar@Paurushs-MacBook-Air ~ % npm config ls
; node bin location = /usr/local/bin/node
; node version = v20.14.0
; npm local prefix = /Users/paurushkumar
; npm version = 10.7.0
; cwd = /Users/paurushkumar
; HOME = /Users/paurushkumar
; Run `npm config ls -l` to show all defaults.
paurushkumar@Paurushs-MacBook-Air ~ % 
```
```[tasklist]
### Tasks
```

**Comment by Blink29** [comment]
i checked npm config get progress and its true but the progress bar still won't come

**Comment by milaninfy** [comment]
@Blink29 Please checkout this issue thread to for reasons for this change. https://github.com/npm/cli/issues/7425

**Comment by Blink29** [comment]
thanks for the reply, is the spinner fixed or can expect a progress bar in the future?

**Comment by milaninfy** [comment]
For now the spinner is the indicator of "npm is doing something", as I mentioned in previous comment you can check https://github.com/npm/cli/issues/7425 this issue discussions for more information, also you can use various log levels `verbose`, `silly` or `http` to get those logging output like before.
