### ISSUE TITLE
[BUG] npm audit signatures returns a 500 Internal Server Error - Buffer is not defined

### ISSUE THREAD

**Issue by Tzinov15** [npm/cli#7623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [x] I am using the latest npm

### Current Behavior

`npm audit signatures` returns a 500 Internal Server Error with `Buffer is not defined`

### Expected Behavior

`npm audit signatures` does not error

Existing issue (that was closed) exists here
https://github.com/npm/cli/issues/7266

### Steps To Reproduce

```bash
mkdir test # create new directory
npm init # create new project
npm install tailwind-merge # currently installs 2.3.0
npm audit signatures # run signatures
```
See error

> npm error code E500
npm error 500 Internal Server Error - GET https://registry.npmjs.org/-/npm/v1/attestations/tailwind-merge@2.3.0 - Buffer is not defined
npm error A complete log of this run can be found in: /Users/alextzinov/.npm/_logs/2024-07-02T15_21_54_484Z-debug-0.log

### Environment

- `npm -v` : **npm:** 10.8.1
- `node -v` : **node:** v20.11.0
- `OS Name:` **MacOS 14.1 (23B2073)**
- `System Model Name` Macbook Pro - Apple M3 Pro

**Comment by wraithgar** [comment]
This repo is for tracking issues w/ the npm cli itself. Registry support does not monitor this repo.

For registry issues please use https://www.npmjs.com/support.  

I pinged them about this, but you should still open your own support ticket so that you can be notified when it's fixed.

**Comment by Tzinov15** [comment]
Good to know, thanks for the note
