### ISSUE TITLE
[BUG] <title>New version of NPM for ADO (v1.124.1) generating warnings that v1.138.3 didn't

### ISSUE THREAD

**Issue by dbhaigh** [npm/cli#7626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

As the title states - the latest and greatest version of NPM for ADO pipelines (v1.124.1) that has only just been released, is generating noise in our Data pipeline that the last version (v1.138.3) wasn't generating

The error is "##[warning]Can't find loc string for key: Info_GotAndMaskAuth" and I can find NO information regarding this online

Is there anyway to set the version of NPM to be used to be the quiet version?  Or is this a known bug that is actively being squashed?

Any information leading to the silencing of this noise is most welcome

Cheers

-=A=-

.

### Expected Behavior

I expect the stages in the pipeline where NPM is being used to not generate the above-mentioned error

### Steps To Reproduce

        - task: Npm@1
          inputs:
            command: 'install'
            workingDir: '$(Build.Repository.LocalPath)'
            verbose: true
          displayName: 'Install npm package'

### Environment

- npm: 1.124.1
- Node.js: 18.x
- OS Name: ADO pipeline

**Comment by milaninfy** [comment]
@dbhaigh I am not familiar with npm on ADO pipelines, but Did you try removing `verbose` or setting it to `false` ?

**Comment by ljharb** [comment]
What is “ADO pipelines”? those version numbers don’t match up to npm itself, so you may need to file an issue on whatever that software is.

**Comment by dbhaigh** [comment]
@milaninfy I haven't, no - I'd rather run with a version of npm that doesn't generate the warnings in the first place than suppress warning s from a version that appears to need the "loc string for key: Info_GotAndMaskAuth" - My pipeline has been happy until this new version showed up

@ljharb ADO Pipelines == Software pipelines run via the Azure DevOps portal 

As for the version numbers?  This is what I'm seeing when the pipeline runs

When it was running quietly
¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬
Task         : npm
Description  : Install and publish npm packages, or run an npm command. Supports npmjs.com and authenticated registries like Azure Artifacts.
Version      : 1.238.3
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/npm
¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬

And now
¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬
Task         : npm
Description  : Install and publish npm packages, or run an npm command. Supports npmjs.com and authenticated registries like Azure Artifacts.
Version      : 1.241.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/npm
¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬

It certainly looks to me like the problem lies with npm, and that problem is that the new version(v1.241.1) wants the "loc string for key: Info_GotAndMaskAuth" and the older version(1.238.2) didn't

Thank you both for your input, now perhaps we can get some from someone who knows more about the subject?

**Comment by ljharb** [comment]
Those versions aren’t for npm - maybe they’re for the azure devops npm package. In which case, you’d need to file the issue with them, not here.

**Comment by milaninfy** [comment]
**Closing:** we do not support/triage third-party libraries or tooling bugs; Please file an issue with the relevant project. However if you still think this is an npm cli issue, please provide npm cli specific logs, and npm cli version that is being used and feel free to reopen this issue or create a new one with all these details.  Just fyi latest version of npm cli is 10.8.1.
