### ISSUE TITLE
[BUG] nx release publish fails when package does not have `latest` tag

### ISSUE THREAD

**Issue by ColinRhodes** [npm/cli#7627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`nx release publish` fails when the package does not have the `latest` tag.  This is because `npm view {package-name}` returns empty output when there is no `latest` tag.

I am using versions that are fixed to the same value across all packages, so when I add a new lib to test locally, I don't want to set the `latest` tag, since that would impact all of my packages.  Instead, I want to publish a prerelease for all packages.

### Expected Behavior

I'd expect subsequent calls to `npx nx release publish` to successfully publish additional versions of the package.

### Steps To Reproduce

1. NodeJS nx project, with version tags initialized
2. Add new NodeJS publishable library
3. `npx nx release version prerelease --preid=alpha --git-tag=true && npx nx release publish` -- works as expected
4. `npx nx release version prerelease --preid=alpha --git-tag=true && npx nx release publish` -- error below

```
Something unexpected went wrong when checking for existing dist-tags.
   SyntaxError: Unexpected end of JSON input
      at JSON.parse (<anonymous>)
      at runExecutor (/home/runner/work/roadmunk/roadmunk/node_modules/@nx/js/src/executors/release-publish/release-publish.impl.js:75:37)
```

### Environment

- npm: 10.2.4
- Node.js: 18.19.1
- OS Name: Ubuntu 22.04

**Comment by ljharb** [comment]
This seems like an nx issue and not an npm one.

**Comment by ColinRhodes** [comment]
@ljharb Oops, my bad.  I intended on filing this as an `nx` bug.  Thanks for catching my error :)
