### ISSUE TITLE
[BUG]  ENOENT: no such file or directory, mkdir 'H:\blog\public\:'

### ISSUE THREAD

**Issue by 2176608** [npm/cli#7632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

![image](https://github.com/npm/cli/assets/90504717/c84060fe-5d42-4cf1-a2e3-3b040563d27e)

### Expected Behavior

It should go as expected, but obviously.

### Steps To Reproduce

When I execute "hexo g"

### Environment

![image](https://github.com/npm/cli/assets/90504717/8181f1c1-c33d-4fc9-871c-3491a188599f)
![image](https://github.com/npm/cli/assets/90504717/05670883-d42a-41e9-a88b-6f8f3a6c5d4b)

**Comment by 2176608** [comment]
I tried to reinstall it, but it still does.

**Comment by milaninfy** [comment]
**Closing:** we do not support/triage third-party libraries or tooling bugs; Please file an issue with the relevant project.
