### ISSUE TITLE
[BUG] regression? "license" key in lockfile is never populated

### ISSUE THREAD

**Issue by chrisdlangton** [npm/cli#7648]
Regression? Seems to be fixed in `v10.8.2` according to [issue 5532 comment](https://github.com/npm/cli/issues/5532#issuecomment-2105178819) by @lukekarrys 

But is occurring today:

```
nvm use --lts
node --version
// 10.8.2
npm --version
// v20.15.1
```

I narrowed it down to the difference between:

`npm install` works as expected

`npm update` strips licenses as described in #5532

**Comment by kchindam-infy** [comment]
HI @chrisdlangton  Could you list exact cmd you ran that led to license being stripped from lockfile?
If possible could you share a minimal example of your package.json and pakcage.lock.json before and after npm update?

**Comment by chrisdlangton** [comment]
> HI @chrisdlangton Could you list exact cmd you ran that led to license being stripped from lockfile? If possible could you share a minimal example of your package.json and pakcage.lock.json before and after npm update?

I have, and the results of the update vs install command is obvious if you run it

**Comment by wraithgar** [comment]
Please use the issue template when making new issues.  We get a LOT of issues opened and unless there is a very clearly defined reproduction case we simply do not have the time to try to find out how to reproduce them with limited info.  Thanks.

**Comment by HonkingGoose** [comment]
Duplicate of:

- https://github.com/npm/cli/issues/7384

**Comment by chrisdlangton** [comment]
@HonkingGoose not a duplicate 
The linked issue is closed and related to install

This is new, distinctly related to update not install, and the lock file not package.json, as described, very clearly..

And clearly reproductive too, so your comment is ingenuous 

Besides, the install issue couldn't have been a duplicate if you had read the report, so it's clear you also didn't read the reproduction steps.

So, I created the identical content of this issue in the template, just in case layout was the cause of quick/sloppy triage - sorry for being concise and missing this layout requirement, I can be a bit too efficient sometimes and only realise others have trouble with it afterwards

**Comment by HonkingGoose** [comment]
I apologize for getting it wrong! I'm hiding my comment as "off-topic". 😉

I'll let the maintainers figure things out.
