### ISSUE TITLE
context.document.insertFileFromBase64 Word JavaScript API is not availabe in the latest npm package

### ISSUE THREAD

**Issue by vaishnavi29OT** [npm/cli#7649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

context.document.insertFileFromBase64 Word JavaScript API is working with online CDN Url but not working with npm package
we are on LTS node version and latest office-js npm package.

### Expected Behavior

context.document.insertFileFromBase64 Word JavaScript API should be available with npm package also

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 10.7.0
- Node.js: 20.14.0
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by milaninfy** [comment]
**Closing:** we do not support/triage third-party libraries or tooling bugs; Please file an issue with the relevant project.
If you believe this is npm cli bug, create a new issue or reopen this with all the details in issues template like logs, configs and steps to reproduce the actual npm cli issue.
