### ISSUE TITLE
[BUG] Cannot install dependency defined with `git+file`

### ISSUE THREAD

**Issue by cdoublev** [npm/cli#7658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Installing a dependency defined with [`git+file`](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#git-urls-as-dependencies) fails with this error:

```
npm error code 128
npm error An unknown git error occurred
npm error command git --no-replace-objects ls-remote file:../repo
npm error ssh: Could not resolve hostname file: Name or service not known
npm error fatal: Could not read from remote repository.
npm error
npm error Please make sure you have the correct access rights
npm error and the repository exists.
```

### Expected Behavior

The package should be installed.

### Steps To Reproduce

1. `mkdir -p npm-git-file/{repo,project}`
2. In `npm-git-file/repo`: `npm init -y && git init && git add . && git commit -m "Initial commit"`
3. In `npm-git-file/project`: `npm init -y && npm i -S git+file:../repo`

### Environment

- npm: 10.8.2
- Node.js: v22.1.0
- OS Name: Debian GNU/Linux 12 (bookworm)
- System Model Name: VirtualBox
- npm config:
```ini
; "user" config from /home/vagrant/.npmrc

@cdoublev:registry = "https://registry.npmjs.org/"
//registry.npmjs.org/:_authToken = (protected)

; node bin location = /usr/bin/node
; node version = v22.1.0
; npm local prefix = /var/www/debug/npm-git-file/project
; npm version = 10.8.2
; cwd = /var/www/debug/npm-git-file/project
; HOME = /home/vagrant
```

**Comment by kchindam-infy** [comment]
@cdoublev  The default behavior frpm npm 9 is to install linked dependencies instead of crating symlinks. If you need file dependencies to be links you need, then use --install-links=false.

**Comment by cdoublev** [comment]
I want files and dependencies to be installed. I find this more convenient than stashing unstaged files and checking out the desired ref.

Thanks for the tip!

**Comment by kchindam-infy** [comment]
@cdoublev As i mentioned you could use --install-links=false for files.

**Comment by cdoublev** [comment]
`npm i ../repo` creates a symlink `node_modules/repo -> ../repo`. Assuming `repo` has a dependency, it is not installed in `node_modules`.

`npm i --install-links ../repo` creates `node_modules/repo` with all files from `../repo`. Assuming `repo` has a dependency, it is also installed in `node_modules`.

But I need files and dependencies from `../repo#<commit-or-tag>` to be installed in `node_modules`, not the current files in `../repo`.

Sorry if I misunderstand you.

**Comment by kchindam-infy** [comment]
Thanks for the clarification, based on your requirement you can install the contents and dependencies from a specific commit or tag in your local repo and you can use the following command
npm install git+file:///path/to/repo#commit-or-tag

This will clone the repo at the specified commit or tag and install the dependencies as per the package.json for that commit.

**Comment by cdoublev** [comment]
Ah, it works with `git+file:///absolute-path`, thansk!

This [SO answer](https://stackoverflow.com/a/59982227/7947839) suggests that `git ls-remote <relative-path>` works inexpectedly, and that `git -C <relative-path> rev-parser` should be used instead. Not sure what happens under the hood of `npm` when using `git+file:///absolute-path` vs. `git+file:relative-path`.

Might be worth adding a note about this, isn't it?

**Comment by cdoublev** [comment]
~~Actually, it does not work: `npm` creates a symlink `node_modules/repo -> ../^git+file:/absolute-path/repo`.~~

Never mind, I made a typo in the dependency version.

**Comment by kchindam-infy** [comment]
Thanks for confirming, glad the provided solution worked for you.

**Comment by cdoublev** [comment]
Ah, too bad, leaving this bug unfixed and this requirement (`git+file` only accepts absolute paths - starting with `/` - preceded by `git+file://`) undocumented seem to favor a poor user experience.
