### ISSUE TITLE
npm installation issues

### ISSUE THREAD

**Issue by spyadav14699** [npm/cli#7661]

**Comment by Skyost** [comment]
Same problem here.

**Comment by milaninfy** [comment]
@spyadav14699 Could you please provide docker file, which image was used,  what was the used image node and npm version ? also the pacakge.json file or dependencies used in them would give us idea on how to reproduce this.

**Comment by milaninfy** [comment]
**Closing**. Not sure why the issue description have been removed. Feel free to reopen with all the details or create a new one.

**Comment by spyadav14699** [comment]
it's resolved now the problem was with docker's node js version
