### ISSUE TITLE
[BUG] Symlinks are not present in the released source code

### ISSUE THREAD

**Issue by alitas** [npm/cli#7662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

The `node_modules/@npmcli` folder in released source code at https://github.com/npm/cli/releases/tag/v10.8.2 does not include the symlinks that are in the original project. This causes `Cannot find module '@npmcli/config'` errors when you try to run the cli from that release.

### Expected Behavior

Symlinks should be preserved in the zip / tar.gz files in the release. They are preserved in https://github.com/npm/cli/releases/tag/v8.19.4, but not in https://github.com/npm/cli/releases/tag/v10.8.2.

### Steps To Reproduce

1. Download and extract the source code asset from https://github.com/npm/cli/releases/tag/v10.8.2
2. Navigate to `node_modules/@npmcli`
3. See that `config` folder / symlink doesn't exist

### Environment

- npm: 10.8.2
- Node.js: ALL
- OS Name: ALL
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by wraithgar** [comment]
This is intentional. symlinks are not identical across all systems.  Folks running npm from source will always need to run `node ./scripts/resetdeps.js` to set up symlinks.

**Comment by alitas** [comment]
> This is intentional. symlinks are not identical across all systems.  Folks running npm from source will always need to run `node ./scripts/resetdeps.js` to set up symlinks.

The resetdeps script depends on the git repository existing in the current folder, which is not true for packed source code.
