### ISSUE TITLE
[BUG] npm install jest not working on gitlab saas runners as well as self hosted machine runners 

### ISSUE THREAD

**Issue by theabubakkar** [npm/cli#7670]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I am using node:latest docker image and having following error. 

$ npm install jest
npm warn deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm warn deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm warn deprecated superagent@7.1.6: Please upgrade to v9.0.0+ as we have fixed a public vulnerability with formidable dependency. Note that v9.0.0+ requires Node.js v14.18.0+. See https://github.com/ladjs/superagent/pull/1800 for insight. This project is supported and maintained by the team at Forward Email @ https://forwardemail.net
npm error Exit handler never called!
npm error This is an error with npm itself. Please report this error at:
npm error   <https://github.com/npm/cli/issues>
npm error A complete log of this run can be found in: /root/.npm/_logs/2024-07-[19](https://gitlab.com/mrs-technologies/mtronic-homeautomation/homeautomation_serverlessbackend/-/jobs/7382008765#L19)T10_16_53_646Z-debug-0.log

### Expected Behavior

should install jest successfully

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node.js: docker image node:latest
- OS Name: Linux (Gitlab SAAS Runners)
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by milaninfy** [comment]
Closing Seems similer if not duplicate of https://github.com/npm/cli/issues/7657.
Try node 22.4.1 with npm 10.8.2.

**Comment by milaninfy** [comment]
Fixed in Node.js v22.5.1 https://github.com/nodejs/node/issues/53902#issuecomment-2239263377

**Comment by theabubakkar** [comment]
thank you
