### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by sanjeevanlikestocode** [npm/cli#7688]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I am not able to run this react app: [https://github.com/sanjeevarasa-satkunarasa/React-Router-Adopt-Pets](https://github.com/npm/installed-package-contents/issues/url)

### Expected Behavior

I wanted to to run this react app: [https://github.com/sanjeevarasa-satkunarasa/React-Router-Adopt-Pets](https://github.com/npm/installed-package-contents/issues/url) with the command npm start

### Steps To Reproduce

 In this environment Node
    With this config...
    Run 'npm install & npm start'
    See error

npm install:
npm warn old lockfile
npm warn old lockfile The package-lock.json file was created with an old version of npm,
npm warn old lockfile so supplemental metadata must be fetched from the registry.
npm warn old lockfile
npm warn old lockfile This is a one-time fix-up, please be patient...
npm warn old lockfile
npm error code ENOTDIR
npm error syscall mkdir
npm error path G:\My Drive\Personal\Programming\Projects\Codeacademy\react_router_v6_project_starting_code\node_modules@babel\highlight\node_modules
npm error errno -4052
npm error ENOTDIR: not a directory, mkdir 'G:\My Drive\Personal\Programming\Projects\Codeacademy\react_router_v6_project_starting_code\node_modules@babel\highlight\node_modules'

npm error A complete log of this run can be found in: C:\Users\ssanj\AppData\Local\npm-cache_logs\2024-07-26T06_53_29_603Z-debug-0.log

npm start:
$ npm start

    cute-pets-website@0.1.0 start
    react-scripts start

'react-scripts' is not recognized as an internal or external command,
operable program or batch file.

### Environment

npm: 10.7.0
Node: 20.15.1
OS: Windows
platform: ThinkPad
- npm config:
```ini
; "builtin" config from C:\Program Files\nodejs\node_modules\npm\npmrc

prefix = "C:\\Users\\ssanj\\AppData\\Roaming\\npm"

; "user" config from C:\Users\ssanj\.npmrc

ignore-scripts = false

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v20.15.1
; npm local prefix = C:\Users\ssanj
; npm version = 10.7.0
; cwd = C:\Users\ssanj
; HOME = C:\Users\ssanj
; Run `npm config ls -l` to show all defaults.
```

**Comment by wraithgar** [comment]
There is not enough here to reproduce the issue.  Based on the error message it looks like the install is failing.  Please try removing the yarn lock and package lock.
