### ISSUE TITLE
[BUG] When using the npm command in MacOS 15.0 Beta, the node icon appears in the Dock

### ISSUE THREAD

**Issue by vientorepublic** [npm/cli#7690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

After updating your MacOS system to 15.0 Beta (24A5298h), if you use the npm command, an icon with the name "node" will appear in the Dock and will remain in a loading state. This icon disappears when the process ends.

https://github.com/user-attachments/assets/cfbbdde2-83eb-46f2-8b3b-cb1074c52bf6

### Expected Behavior

Previously, when using the npm command, no icon was displayed in the Dock.
The expected behavior is that no icon is displayed in the Dock when using this command.

### Steps To Reproduce

1. In MacOS 15.0 Beta (24A5298h)
2. Run any npm command
3. An icon will now appear in your Dock

### Environment

- npm: 10.8.2
- Node.js: v20.15.1
- OS Name: MacOS Sequoia
- System Model Name: MacBook Pro 2020 (Apple M1)
- npm config:
```ini
; "builtin" config from /opt/homebrew/Cellar/node@20/20.15.1/lib/node_modules/npm/npmrc

prefix = "/opt/homebrew"

; "user" config from /Users/doyeonkim/.npmrc

@OWNER:registry = "https://npm.pkg.github.com/"
//npm.pkg.github.com/:_authToken = (protected)
//npm.viento.me/:_authToken = (protected)
//registry.npmjs.org/:_authToken = (protected)
registry = "https://registry.npmjs.org/"

; node bin location = /opt/homebrew/Cellar/node@20/20.15.1/bin/node
; node version = v20.15.1
; npm local prefix = /Users/doyeonkim
; npm version = 10.7.0
; cwd = /Users/doyeonkim
; HOME = /Users/doyeonkim
; Run `npm config ls -l` to show all defaults.
```

**Comment by ljharb** [comment]
Seems like more of a Mac OS behavior to me. There’s a setting that makes terminal apps show in the dock, and I’d bet it’s enabled by default on beta OS releases. Does it happen with other cli programs?

**Comment by vientorepublic** [comment]
No, I manage my nodejs version with nvm, but when I use this command, the icon doesn't show up in the dock.
Also, if you run the script with the node command instead of npm, the icon does not appear in the dock.

**Comment by ljharb** [comment]
nvm is a sourced shell function and doesn’t invoke any binaries, so that wouldn’t cause anything. Noted, though.

**Comment by vientorepublic** [comment]
However, since the node command is binary, the same problem does not occur, so it appears that there is some problem between npm and MacOS 15 Beta.

**Comment by leandronn** [comment]
Same problem here.

Environment:

- System: MacBook Pro 16" 2019 (Intel)
- OS: Version 15.0 Beta (24A5298h)
- NodeJS: v20.9.0
- NPM: v10.1.0

![Screenshot 2024-07-28 at 23 02 09](https://github.com/user-attachments/assets/410b56ee-f240-438c-85f6-df8bb373dc34)

![Screenshot 2024-07-28 at 23 02 21](https://github.com/user-attachments/assets/b09bf303-d8b8-40ae-836e-4183a3620183)

**Comment by ixqbar** [comment]
+1

**Comment by matheusmaculan** [comment]
+1

**Comment by wraithgar** [comment]
This isn't anything that npm has any control over.  npm itself is a node script, and always has been.  It's up to the OS to determine what to display to the user when it runs.

**Comment by CJohnSnow** [comment]
I think maybe it's a compatibility issue with the node process in the Apple operating system 👀

**Comment by kanbykanby** [comment]
🙏: Wow, it's amazing. Only Apple can do.

**Comment by xkeyC** [comment]
The same issue happened with dart and fvm (flutter version manager), sharing it here just because it’s crazy!
 
https://github.com/user-attachments/assets/1a3413f6-6367-4874-a44c-cac4c21869eb 

### Only Apple can do!  🤣

**Comment by abdulmannan1** [comment]
> The same issue happened with dart and fvm (flutter version manager), sharing it here just because it’s crazy!
> 
>  Jietu20240803-114254-HD.mp4 
> 
> ### Only Apple can do! 🤣

Same

**Comment by davidsuarezcdo** [comment]
> The same issue happened with dart and fvm (flutter version manager), sharing it here just because it’s crazy!
> 
>  Jietu20240803-114254-HD.mp4 
> ### Only Apple can do! 🤣

Same issue here

**Comment by ixqbar** [comment]
<img width="329" alt="image" src="https://github.com/user-attachments/assets/6748873c-42a7-49a7-9b69-9a618a82aee1">

upgrade os  fixed!

**Comment by truediogo** [comment]
Sequoia Developer Beta 5 fixes this issue

**Comment by AbdulwadoodZawity** [comment]
Update to beta 3 and it will disappear

I just updated mine and its not showing on dock

**Comment by IlayBokobza** [comment]
I just updated to 15.1, and got this bug.
<img width="299" alt="Screenshot 2024-08-08 at 15 23 36" src="https://github.com/user-attachments/assets/908de381-20d2-4f55-9193-c25384427e7f">

**Comment by leandronn** [comment]
Updated to this Version 15.0 Beta (24A5309e) and the problem is gone.

**Comment by AbdulwadoodZawity** [comment]
> Updated to this Version 15.0 Beta (24A5309e) and the problem is gone.

For anyone wondering that's public beta and not developer beta

**Comment by leandronn** [comment]
> > Updated to this Version 15.0 Beta (24A5309e) and the problem is gone.
> 
> For anyone wondering that's public beta and not developer beta

It's developer beta. It's not 15.1 developer beta.

![Screenshot 2024-08-08 at 10 36 05](https://github.com/user-attachments/assets/26c1fc66-7795-4c3f-be3e-dd8bb9a56cb6)

**Comment by ctoautista** [comment]
Same here, and with a LOT of other issues: when sharing screen on Discord, Google, etc., it opens thousands of 'popups' to 'allow' sharing permission AGAIN and AGAIN.

**Comment by ctoautista** [comment]
Upgrading OS today fixed!

**Comment by hudianlao48** [comment]
very good……it come again on macOS 26 Developer beta

![Image](https://github.com/user-attachments/assets/bfb76cdc-d60d-4423-8b29-3aef0d55c6cf)

**Comment by Eveeifyeve** [comment]
You might want to consider pinning and renaming this to the macOS 26 that way any confusion with macos 26 to see if it's a nodejs problem.

I might also considering to open an issue on nodejs about this.

**Comment by Eveeifyeve** [comment]
> very good……it come again on macOS 26 Developer beta
> 
> ![Image](https://github.com/user-attachments/assets/bfb76cdc-d60d-4423-8b29-3aef0d55c6cf)

This seems to be a node issue not just npm it is for all package managers that use node under the hood from my finding so I have made an issue about it in their repo https://github.com/nodejs/node/issues/58798.

**Comment by xkeyC** [comment]
> The same issue happened with dart and fvm (flutter version manager), sharing it here just because it’s crazy!
> 
>  Jietu20240803-114254-HD.mp4 
> ### Only Apple can do! 🤣


I'm back, this time I am sharing: **Docker Desktop**

https://github.com/user-attachments/assets/4677de3c-18b4-47de-8f4a-a3355e59122e
