### ISSUE TITLE
[BUG]  Npm progress bar is missing

### ISSUE THREAD

**Issue by ThePlenkov** [npm/cli#7694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

when i run npm i - nothing happens - it just hangs. It started after my devcontainer rebuilding , most likely newer npm version appeared. I see now some progress indicator but for large projects it's annyning. We do not understand what is happening!
How to return it back to how it looked before? 
Thanks!

### Expected Behavior

I run 'npm i' and progress bar is visible

### Environment

- npm: 10.7.0
- Node.js: v20.15.0
- OS Name: Debian GNU/Linux 12 (bookworm) basically is image mcr.microsoft.com/devcontainers/typescript-node:1-20

**Comment by milaninfy** [comment]
Progress bar in npm is temporarily removed. You can use log-level `verbose` or `silly` to get desired logging for progress indication. Checkout this https://github.com/npm/cli/issues/7425#issuecomment-2079452766 to know more
