### ISSUE TITLE
corp-jones-damarcus:patch-1

### ISSUE THREAD

**Issue by corp-jones-damarcus** [npm/cli#7699]
corp-jones-damarcus:patch-1

_Originally posted by @corp-jones-damarcus in https://github.com/npm/cli/pull/7698#pullrequestreview-2218320650_
            
```[tasklist]
### Tasks
- [ ] https://github.com/npm/cli/pull/7697
```

**Comment by milaninfy** [comment]
**Closing:** please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).
