### ISSUE TITLE
ISSUE AT FIRST TIME TRYING TO INSTALL IONIC

### ISSUE THREAD

**Issue by nihatt** [npm/cli#770]
when i try to npm install -g ionic ;
i get these fails .

https://i.hizliresim.com/0rjbRB.png

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

my node version v12.14.1
my npm version 6.13.4
MY LOG IS HERE , PLEASE HELP ME

**Comment by DanielRuf** [comment]
Duplicate of https://github.com/npm/cli/issues/417
