### ISSUE TITLE
[BUG] npm dist-tag rm only removes the last recently deleted tag

### ISSUE THREAD

**Issue by poteto** [npm/cli#7705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

My script accidentally published too many superfluous dist-tags for my [npm package](https://www.npmjs.com/package/babel-plugin-react-compiler?activeTab=versions). When trying to remove them via `npm dist-tag rm babel-plugin-react-compiler <tag>`, only the last recently deleted tag stays deleted. 

As a result I can only effectively remove one tag, but what I really want is to delete all these extra tags I accidentally pushed.

### Expected Behavior

`npm dist-tag rm` should fully delete a tag and not restore previously deleted tags.

### Steps To Reproduce

```
$ npm dist-tag ls babel-plugin-react-compiler

a: 0.0.0-experimental-0725353-20240806
e: 0.0.0-experimental-0725353-20240806
experimental: 0.0.0-experimental-0725353-20240806
i: 0.0.0-experimental-0725353-20240806
l: 0.0.0-experimental-0725353-20240806
latest: 0.0.0-experimental-334f00b-20240725
m: 0.0.0-experimental-0725353-20240806
n: 0.0.0-experimental-0725353-20240806
p: 0.0.0-experimental-0725353-20240806
r: 0.0.0-experimental-0725353-20240806
```

```
$ npm dist-tag rm babel-plugin-react-compiler a --otp=******

-a: babel-plugin-react-compiler@0.0.0-experimental-0725353-20240806
```

```
$ npm dist-tag ls babel-plugin-react-compiler

e: 0.0.0-experimental-0725353-20240806
experimental: 0.0.0-experimental-0725353-20240806
i: 0.0.0-experimental-0725353-20240806
l: 0.0.0-experimental-0725353-20240806
latest: 0.0.0-experimental-334f00b-20240725
m: 0.0.0-experimental-0725353-20240806
n: 0.0.0-experimental-0725353-20240806
p: 0.0.0-experimental-0725353-20240806
r: 0.0.0-experimental-0725353-20240806
t: 0.0.0-experimental-0725353-20240806 # <-- was previously deleted
```

```
$ npm dist-tag rm babel-plugin-react-compiler e --otp=******

-e: babel-plugin-react-compiler@0.0.0-experimental-0725353-20240806
```

```
$ npm dist-tag ls babel-plugin-react-compiler

a: 0.0.0-experimental-0725353-20240806 # <-- was previously deleted
experimental: 0.0.0-experimental-0725353-20240806
i: 0.0.0-experimental-0725353-20240806
l: 0.0.0-experimental-0725353-20240806
latest: 0.0.0-experimental-334f00b-20240725
m: 0.0.0-experimental-0725353-20240806
n: 0.0.0-experimental-0725353-20240806
p: 0.0.0-experimental-0725353-20240806
r: 0.0.0-experimental-0725353-20240806
t: 0.0.0-experimental-0725353-20240806 # <-- was previously deleted
```

### Environment

- npm: 10.8.2
- Node.js: v18.20.1
- OS Name: Darwin 23.5.0
- System Model Name: Macbook Pro
- npm config:
```ini
; "user" config from .npmrc

//registry.npmjs.org/:_authToken = (protected)

; node bin location = .asdf/installs/nodejs/18.20.1/bin/node
; node version = v18.20.1
; npm local prefix = [redacted]
; npm version = 10.8.2
; cwd = [redacted]
; HOME = [redacted]
; Run `npm config ls -l` to show all defaults.
```

**Comment by kchindam-infy** [comment]
@poteto  npm dist-tag  rm <package-spec> <tag> command is designed to remove a single specified distribution tag from a package. refer : https://docs.npmjs.com/cli/v10/commands/npm-dist-tag

You can write a script for the removal of multiple tags sequentially.

**Comment by poteto** [comment]
@kchindam-infy thanks for commenting, but you have misunderstood my bug report. this is about deleted tags not staying deleted.

**Comment by frolic** [comment]
I'm also seeing this! I kind of suspect this is a registry issue rather than a CLI issue. I wrote to npm support about it.

**Comment by ijkml** [comment]
I think this is a registry issue, too.
Deleting a dist-tag only removes it for a few hours.

**Comment by RomanHotsiy** [comment]
I'm also seeing it. I suspect it may be related to some kind of caching.

@holic let us know when you get a response please.

**Comment by milaninfy** [comment]
**Closing:** this looks to be an issue with the registry which is outside the scope of this repo. As done by @holic, writing to the registry support was the right option. [npmjs.com/support](https://www.npmjs.com/support)

**Comment by graynorton** [comment]
@holic Have you heard anything from npm support yet?

**Comment by frolic** [comment]
This is the last I've heard:
<img width="978" alt="image" src="https://github.com/user-attachments/assets/caeaabeb-2f9a-45c9-b08f-fd8795d6d9ee">

**Comment by graynorton** [comment]
> This is the last I've heard

Thanks! If it looks like having other folks report the same issue would prove useful, let me know.

**Comment by jbmaisner** [comment]
we have the same issue here, hope they'll find a solution soon :)

**Comment by jbmaisner** [comment]
> This is the last I've heard

still no news ?

**Comment by frolic** [comment]
I'd recommend writing into npm support.

**Comment by poteto** [comment]
As an update I recently tried deleting these tags again and it's working as expected now.

**Comment by frolic** [comment]
Can confirm I was able to remove tags!

**Comment by jbmaisner** [comment]
Confirm here too ! It's now working again.
Thanks for the feedback @poteto 😉
