### ISSUE TITLE
[Enchancement] Check files that import the package before uninstalling

### ISSUE THREAD

**Issue by CC52-dev** [npm/cli#7708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Above

### Expected Behavior

Above

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by kchindam-infy** [comment]
No that's outside the scope of what npm does. It will not and should not inspect the source of the code being installed.

You can discuss the feedback here: https://github.com/npm/feedback/discussions
