### ISSUE TITLE
[BUG] No README.md on npmjs ?

### ISSUE THREAD

**Issue by tanishqmanuja** [npm/cli#7711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

No readme

![image](https://github.com/user-attachments/assets/bccc35d1-2157-447b-8499-c7733881eb7f)

It is clearly there

![image](https://github.com/user-attachments/assets/40118ba4-3679-4e5c-84bf-081e9a3459ce)

### Expected Behavior

Readme should be displayed

### Steps To Reproduce

N/A

### Environment

package: https://www.npmjs.com/package/apkmirror-downloader

**Comment by davidbonnet** [comment]
Looks like a problem with the NPM website itself and not the CLI tool. I used an older version of `npm` (10.2.4) and the same happened.

**Comment by tanishqmanuja** [comment]
Thanks for confirming, What's the repo for website and registry, i would transfer the issue in that case

**Comment by tanishqmanuja** [comment]
It's fixed automatically somehow, for future readers - the moral of the story is try to wait 4-5 hrs to see if readme updates.

This could be a caching server issue or some server was down or something entirely different, couldn't be sure as there is no clarity from npm devs.

Closing this for now.

**Comment by tada-js** [comment]
I had the [same issue](https://github.com/tada-js/react-tada/issues/1), but it has been resolved now.
