### ISSUE TITLE
[BUG] Problem / error links are incorrect when path contains prefix before space

### ISSUE THREAD

**Issue by Korne127** [npm/cli#7712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When you run `npm run build` or `npm run format` and the path in which the file, e.g. `/Users/example/first second/file.js` contains a space and the prefix (part in front of the space) is also a valid path, e.g. `/Users/example/first` exists as a folder, only that part is linked instead of the full file path and the link also links to the prefix path and not the real file.

### Expected Behavior

The complete file path should be linked and it should link to the real file and not the prefix path.

### Environment

- npm: 10.8.2
- Node.js: 22.5.1
- OS Name: macOS 14.3
- System Model Name: MacBook Air
```[tasklist]
### Tasks
```

**Comment by milaninfy** [comment]
@Korne127 It's not very clear on how to reproduce the issue and what is the exact error/issue being reported here. Cloud you please fill out the complete issue template and provide reproduction steps, configs etc ?

**Comment by milaninfy** [comment]
**Closing**. If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Comment by Korne127** [comment]
Yeah, sorry that I didn't answer, I had a lot to do in the last days and forgot about this.
I'm sorry that I didn't explain it good enough. The reproduction steps would have just been the same as what I wrote in current behaviour. ~~But anyways, when I tried to elaborate on it better, I noticed that it's actually due to an underlying issue in `tsc`, so I would have closed it as well. I think you can remove the Cannot Reproduce label though.~~ (Edit: I actually just glanced over it while trying to create a minimal reproducible example but it actually turns out I was wrong: It was an npm bug after all.)

**Comment by Korne127** [comment]
Hey, @milaninfy can you reopen this? Today was the first day I had more time to finally open the issue, and when I really tried to reproduce it, I realized this is an `npm` bug after all (last time I just glanced over it).

So, here are better **reproduction steps**:

So, first you have to create the project folder. It is necessary that the folder contains one space and that the parent folder also contains a folder with the part of the folder name in front of the space. In this example, the folder is called `test project` and the parent folder also contains a different folder called `test`.

Then, you have to put a `package.json` file with a script (in this example called `script`) which will return an error. A minimal reproductive example of a file that works is this:
```json
{
  "scripts": {
    "script": "exit 1"
  }
}
```

If you then run `npm run script --verbose`, npm will print some error logging, including one line like this:

> npm verbose cwd ~/Downloads/test project

The whole file path should be a link and link towards the folder (in this case test project). However, only the part before the space is a link, and that (completely independent) folder is linked instead:

<img width="190" alt="image" src="https://github.com/user-attachments/assets/58609906-864b-4418-9fc9-63c4277441d7">

(While this may be irrelevant in this situation, this is just a minimal reproductive example. In a real application, this link can be displayed without the verbose mode (when using several packages) and can be supposed to link towards a file causing an error (which is not properly linked).
