### ISSUE TITLE
[BUG] npm version -ws never update dependencies in package.json

### ISSUE THREAD

**Issue by tnovas** [npm/cli#7713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`npm version` doesn't update internal dependency version wich as linked in workspaces. But the package-lock.json in the root is updated.

Ej:
```
packages
  package-a (1.0.0)
      dep -> package-b (1.0.0)
  package-b (1.0.0)
```

`npm version -ws 1.0.1`

result:
```
packages
  package-a (1.0.1)
      dep -> package-b (1.0.0)
  package-b (1.0.1)
```

### Expected Behavior

The package-lock was updated I hope the dependencies of package.json on each package is also updated.

Ej:
```
packages
  package-a (1.0.0)
      dep -> package-b (1.0.0)
  package-b (1.0.0)
```

`npm version -ws 1.0.1`

result:
```
packages
  package-a (1.0.1)
      dep -> package-b (1.0.1) <--- this
  package-b (1.0.1)
```

### Steps To Reproduce

1. Make similar scaffolding with two repos (A and B), when B is a dependency of A, and configure workspaces in the package.json root
2. Run 'npm version -ws 1.0.1'
3. Version of B in A package.json never change.

### Environment

- npm: 10.8.1
- Node.js: 20.16.0
- OS Name: macOS Sonoma 14.4.1
- System Model Name: Macbook Pro
- npm config:
```ini
; "user" config from /Users/test/.npmrc

detect_chromedriver_version = true

; node bin location = /Users/test/.nvm/versions/node/v20.16.0/bin/node
; node version = v20.16.0
; npm local prefix = /Users/test/Documents/develop/test-npm
; npm version = 10.8.1
; cwd = /Users/test/Documents/develop/test-npm
; HOME = /Users/test
```

**Comment by milaninfy** [comment]
@tnovas `npm version` command is used for bumping package version and not the dependencies version inside a package. in-order to update dependencies version use `npm install` or `npm update` command.

**Comment by tnovas** [comment]
Thanks for response @milaninfy , so do I have to modify each dependency manually?

**Comment by milaninfy** [comment]
Yes, Just like how you update the other dependencies in your package.
