### ISSUE TITLE
[BUG] npm install --save three: No matching version found for three@^0.777.1.

### ISSUE THREAD

**Issue by hkunz** [npm/cli#7717]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I tried all options in https://stackabuse.com/bytes/solving-npm-err-code-etarget-no-matching-version-found-error/ but all commands still give me the same error.

I was running some tests on a software project where I cache the `package.json` file for different directories I visit, to avoid reloading the file every time I revisit the same directory. As part of the test, I modified the version number in `package.json` to easily distinguish between different directories' `package.json`. Unfortunately, this has led to an issue where I can no longer install three.js. Despite my efforts, I haven't been able to resolve this problem. So basically the bug is that if you change the version in the package.json file, this version suddenly gets cached and you can no longer do any clean three.js installs in any empty clean folder. It somehow saved this modified version somewhere.
[2024-08-11T16_45_37_421Z-debug-0.log](https://github.com/user-attachments/files/16575503/2024-08-11T16_45_37_421Z-debug-0.log)

### Expected Behavior

Command `npm cache clean --force` should clear the cache. 

### Steps To Reproduce

1. Create an empty directory and navigate to it
2. Execute `npm install --save three`
3. Tamper with the `package.json` file by changing the three version to ^0.777.1
4. Again execute `npm install --save three` 
5. And then create a folder somewhere else. Empty folder
6. Navigate to this empty folder and execute `npm install --save three`
7. Now notice error

```
PS C:\Users\harry\OneDrive\Documents\deletethis> npm install --save three
npm error code ETARGET
npm error notarget No matching version found for three@^0.777.1.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.
npm error A complete log of this run can be found in: C:\Users\harry\AppData\Local\npm-cache\_logs\2024-08-11T16_45_37_421Z-debug-0.log
PS C:\Users\harry\OneDrive\Documents\deletethis>
```

Now no matter where you try to install in any empty folder, it will always be stuck with this error. Also executing `npm update express` will give the error.

### Environment

- npm: 10.8.1
- Node.js: 20.16.0
- OS Name: Windows 11
- System Model Name:
- npm config:
```ini
PS C:\Users\harry\OneDrive\Documents\deletethis> npm config ls
; "builtin" config from C:\Program Files\nodejs\node_modules\npm\npmrc

prefix = "C:\\Users\\harry\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v20.16.0
; npm local prefix = C:\Users\harry\OneDrive\Documents\deletethis
; npm version = 10.8.1
; cwd = C:\Users\harry\OneDrive\Documents\deletethis
; HOME = C:\Users\harry
; Run `npm config ls -l` to show all defaults.
PS C:\Users\harry\OneDrive\Documents\deletethis> 
```

**Comment by kchindam-infy** [comment]
@hkunz did you try the same setup on latest npm ? 
Need more details about how to reproduce the issue and it would help if you can share the folder structure of your test setup.

**Comment by Tayvon** [comment]
@hkunz do you mind filling out the `Environment` portion of this issue? Thanks in advance!

**Comment by hkunz** [comment]
Hi sorry I was following the guide on the official Three.js documentation on the[ installation of Three.js guide ](https://threejs.org/docs/#manual/en/introduction/Installation) and they failed to mention that you have to first run `npm init -y` which will generate the `package.json` file. They were assuming that the package.json file gets generated by `npm install --save three` which apparently is not the right way to do it since it introduced this bug. So by doing `npm init -y` first and then followed by `npm install --save three` I was able to successfully install the latest version of Three.js.
