### ISSUE TITLE
(npm error Exit handler never called!:String) [], RemoteException + FullyQualifiedErrorId : NativeCommandError

### ISSUE THREAD

**Issue by ozcaredo89** [npm/cli#7718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

npm install is showing the below command:

node.exe : npm error Exit handler never called!
At C:\Users\OHINCAPIE\AppData\Roaming\npm\npm.ps1:24 char:5
+     & "node$exe"  "$basedir/node_modules/npm/bin/npm-cli.js" $args
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (npm error Exit handler never called!:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
npm error This is an error with npm itself. Please report this error at:
npm error   <https://github.com/npm/cli/issues>

### Expected Behavior

I need that npm install completes successfully

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...
[2024-08-10T23_08_08_380Z-debug-0.log](https://github.com/user-attachments/files/16575702/2024-08-10T23_08_08_380Z-debug-0.log)

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by milaninfy** [comment]
Fixed in Node.js v22.5.1 https://github.com/nodejs/node/issues/53902#issuecomment-2239263377
