### ISSUE TITLE
[BUG] package binaries with .hidden folders don't install globally

### ISSUE THREAD

**Issue by thepiwo** [npm/cli#7728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

With nodejs 20.16.0 (npm 10.8.1) global install seems to not install binaries from hidden folders.

e.g. 
```
"bin": {
    "debug-bin": ".build/cli.js"
  },
```

### Expected Behavior

With nodejs 20.15.1 (npm 10.7.0) it still worked.

### Steps To Reproduce

I described steps to reproduce the issue in a repository with an example: https://github.com/thepiwo/nodejs-debug-bin

### Environment

- npm: 10.8.1
- node: 20.16.0

**Comment by milaninfy** [comment]
Reproduced the issue locally with 10.8.1. works fine on 10.8.0.

**Comment by milaninfy** [comment]
fixed in https://github.com/npm/package-json/pull/119
