### ISSUE TITLE
[BUG] No lifecycle hooks are run at all

### ISSUE THREAD

**Issue by func0der** [npm/cli#7730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

No livecycle hooks (https://docs.npmjs.com/cli/v10/using-npm/scripts#life-cycle-operation-order) are run at all.

### Expected Behavior

Livecycle hooks are run

### Steps To Reproduce

1. Create package.json
    ```
    {
      "name": "failing",
      "version": "1.0.0",
      "main": "index.js",
      "scripts": {
        "preinstall": "echo pre",
        "postinstall": "echo post",
      },
      "author": "",
      "license": "ISC",
      "description": ""
    }
    ```

3. Run 'npm install license-checker --foreground-scripts --verbose'
4. See nothing. No postinstall or preinstall or any hooks are executed.

Actually all hooks seem to not be working. Tested it with the `version` hooks, too.

### Environment

- npm: 10.8.2
- Node.js: v22.6.0
- OS Name: Fedora 40
- System Model Name: -
- npm config:
```inisub
; node bin location = /home/user/.nvm/versions/node/v22.6.0/bin/node
; node version = v22.6.0
; npm local prefix = /home/user/Projects
; npm version = 10.8.2
; cwd = /home/user/Projects
; HOME = /home/user
; Run `npm config ls -l` to show all defaults.
```

**Comment by milaninfy** [comment]
for this package.json version hook runs fine. 
```javascript
{
  "name": "rep",
  "version": "1.0.3",
  "main": "index.js",
  "scripts": {
    "version": "echo \"testing version hook\""
  },
  "author": "",
  "license": "ISC",
  "keywords": [],
  "description": ""
}
```
```sh
~/workarea/rep $ npm version patch

> version
> echo "testing version hook"

testing version hook
v1.0.3
~/workarea/rep $ npm -v
10.8.2
```

**Comment by milaninfy** [comment]
@func0der when you install a `pacakge` then scripts mentioned inside that `pacakge`'s package.json file will execute, in your case it should run the scripts of `license-checker` when you install that package, but I believe that you are expecting that `npm install license-checker` will run the script of `failing` which it will not execute, as mentioned in my previous comment the version script is working fine. If you still think there is something I missed, please provide your test setup, complete re-production steps, logs etc.

**Comment by milaninfy** [comment]
**Closing**. If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.
