### ISSUE TITLE
[BUG] outdated does not report packages in unnamed workspaces

### ISSUE THREAD

**Issue by textbook** [npm/cli#7741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I'm trying to use workspaces to manage a web application (https://github.com/textbook/starter-kit/tree/v2), where the individual workspace packages (`api/`, `e2e/`, `web/`) don't have semantically sensible names or versions distinct from the overall application (root workspace).

Most functionality works just fine when the individual workspaces' `package.json` files don't have a name or version property, except that `npm outdated` simply ignores them. This leads to confusing behaviour: for example, `npm outdated` can show nothing needs updating, then `npm update --save` actually _does_ make several changes to the various `package*.json` files (for semver-compatible updates - it becomes very difficult to tell if any major version updates are needed to workspace packages).

### Expected Behavior

I expected the outdated packages to still be shown (ideally as "Depended by" the name that appears in the `"workspaces"` array in the root `package.json`, to be consistent with `outdated --all`).

### Steps To Reproduce

Run this script with a directory name of your choice:
```shell
#!/usr/bin/env bash
set -euo pipefail
if [[ $# -ne 1 ]]; then
  echo 'Usage: create.sh [dirname]'
  exit 1
fi
echo "Using Node $(node --version) [npm $(npm --version)]"
rm -rf "$1"
mkdir "$1"
cd "$1"
npm init --yes
npm --workspace demo init --yes
npm --workspace demo pkg delete name
npm --workspace demo pkg delete version
npm --workspace demo install eslint@8  # and/or other outdated package
echo '### Running `npm outdated`:'
npm outdated
echo "Exit code: $?"
echo '### Running `npm --workspace demo outdated`:'
npm --workspace demo outdated
echo "Exit code: $?"
echo '### Running `npm outdated --all`:'
npm outdated --all
echo "Exit code: $?"
```

You'll see e.g.:
```
eslint                        8.57.0   8.57.0   9.9.0  node_modules/eslint                       demo
```
among the output for `outdated --all`, but nothing for the other two `outdated` commands

### Environment

- npm: v10.8.1 (also tried in v8.19.4, v10.7.0, v10.8.2)
- Node.js: v20.16.0 (also tried in v16.20.2, v18.20.3, v22.6.0)
- OS Name: macOS Sonoma 14.6.1 (23G93)
- System Model Name: MacBook Pro 14-inch, 2021 (M1 Pro)
- npm config:
```ini
; "user" config from [home]/.npmrc

//registry.npmjs.org/:_authToken = (protected)
access = "public"
engine-strict = true
fund = "0"
init-author-email = "..."
init-author-name = "..."
init-version = "0.1.0"
lockfile-version = "3"

; node bin location = [home]/.nvm/versions/node/v20.16.0/bin/node
; node version = v20.16.0
; npm local prefix = [home]/workspace/npm-outdated-example
; npm version = 10.8.1
; cwd = [home]/workspace/npm-outdated-example
; HOME = [home]
; Run `npm config ls -l` to show all defaults.
```

**Comment by milaninfy** [comment]
@textbook The workspace directories should have a package.json with name field, as cli doesn't guarantee the behaviour if it does not have name field in workspace package.json.
