### ISSUE TITLE
Error: The programmatic API was removed in npm v8.0.0

### ISSUE THREAD

**Issue by candide85** [npm/cli#7760]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Problem, not another kind of Docs Problem.

- [X] This is a CLI Docs Problem.

### Description of Problem

![Screenshot from 2024-08-29 13-21-54](https://github.com/user-attachments/assets/d3e4921f-2825-4014-83b1-a871fba9280d)

### Potential Solution

if (require.main === module) {
  require('./lib/cli.js')(process)
} else {
  throw new Error('The programmatic API was removed in npm v8.0.0')
}

var __commonJS = (cb, mod) => function __require2() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};

### Affected URL

the code is not on github yet is a personal project

**Comment by ljharb** [comment]
The current behavior was intentional - you're not supposed to use npm programmatically, only by shelling out to the command line.

**Comment by candide85** [comment]
I don’t know what is happening I don’t even know about nom programmatically.
If you can’t help me I will try create a new project
Thank you

**Comment by ljharb** [comment]
It looks like line 5 of index.js in your project is requiring npm. What's in that file?

**Comment by candide85** [comment]
My React vite havent that file but my node Js have it
I’m using a proxy server from vite to connect it

**Comment by ljharb** [comment]
Sounds like it's a vite issue.

**Comment by candide85** [comment]
look at this

Le jeu. 29 août 2024 à 18:08, Jordan Harband ***@***.***> a
écrit :

**Comment by milaninfy** [comment]
as stated by @ljharb. npm should not be used programmatically. However, if you think this is a bug related specifically to npm cli, feel free to create an issue with all the details like logs, steps to reproduce the issue at our end, environment detail and configs. Please use our [issue template](https://github.com/npm/cli/issues/new/choose). 

For support please post your question to [github.community](https://github.community).
