### ISSUE TITLE
[BUG] Failed to publish package to `registry.npmjs.org`

### ISSUE THREAD

**Issue by SukkaW** [npm/cli#7770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```
npm notice Publishing to https://registry.npmjs.org/ with tag latest and public access
npm error code CA_CREATE_SIGNING_CERTIFICATE_ERROR
npm error error creating signing certificate - (502) Bad Gateway
npm error cause (502) Bad Gateway
```

### Expected Behavior

npm should be published normally.

### Steps To Reproduce

https://github.com/SukkaW/foxact/actions/runs/10762545052/job/29843165244

### Environment

- npm: 10.8.2
- Node.js: 20.17.0
- OS Name: Ubuntu
- System Model Name: GitHub Actions Ubuntu Latest
- npm config:
```ini
```

**Comment by milaninfy** [comment]
@SukkaW Is this still happening ? If yes and if you have a reproduction steps that can consistently reproduce this error locally then please provide.

**Comment by SukkaW** [comment]
> @SukkaW Is this still happening ? If yes and if you have a reproduction steps that can consistently reproduce this error locally then please provide.

I guess the issue is related to the registry server, not the cli. Closing.
