### ISSUE TITLE
[BUG] script file `.ps1` in `\AppData\Roaming\npm` does not explicitly invoke `node`

### ISSUE THREAD

**Issue by SanderPs** [npm/cli#7775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When I do `npm link` on a project which has 
```
  "bin": {
    "mytool": "./dist/index.js"
  },
```
And then run `mytool.ps1`, the `.js` file is opened in VS-Code.

### Expected Behavior

It should just run the code.

When I look into the `.ps1` file I see this:
```
  & "$basedir/node_modules/@my-org/my-package/index.js"   $args
```

And I can fix the problem when I just add `node` at the beginning, like this:
```
  & node "$basedir/node_modules/@my-org/my-package/index.js"   $args
```

I wonder, if the reason of this script is to start `node` with a path to a `.js` file, then why is `node` not explicitly invoked?

### Steps To Reproduce

See the steps I described above. I don't know enough about this mechanism to figure out why this problem is happening and how to reproduce it. 

I did find a similar report on stackoverflow: [When i try to run my global npm package, visual studio code opening](https://stackoverflow.com/questions/76793764/)

Anyway, why not just explicitly run `node`?

### Environment

- npm: v8.4.1
- Node.js: v22.8.0
- OS Name: Windows 11
- System Model Name:
- npm config:
```ini
; "builtin" config from C:\Users\xyz\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\xyz\\AppData\\Roaming\\npm"

; "user" config from C:\Users\xyz\.npmrc

strict-ssl = true

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\xyz\Documents\abc
; HOME = C:\Users\xyz
; Run `npm config ls -l` to show all defaults.
```

**Comment by milaninfy** [comment]
@SanderPs do you have `#!/usr/bin/env node` line in your `index.js` ?

**Comment by SanderPs** [comment]
Yes... After doing some more research I realized I have add that shebang line to my index.ts.

A bit weird but also understandable. That way you can have some control on what app is being used to start

I will close this issue

**Comment by SanderPs** [comment]
Not really a bug, but a feature  :-)
