### ISSUE TITLE
Unhandled rejection Error

### ISSUE THREAD

**Issue by beanilsson** [npm/cli#778]
# What / Why
```
Unhandled rejection Error: EACCES: permission denied, rename '/home/user/.npm/_cacache/tmp/208e6f65' -> '/home/user/.npm/_cacache/content-v2/sha512/e9/de/ea008414fcf4d2034b5f9750731f73394c239d6775eb7dd25503f31e4e080373077e2043b1e172b5c6e7b4f3462801f1a9eae2234459133f1afd8f40040f'
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bea/.npm/_logs/2020-02-07T08_52_13_130Z-debug.log
```

## When
Trying to install a global package when forgetting to provide `sudo` on Ubuntu 18.10.

## Current Behavior
Se What/Why section above

## Steps to Reproduce
run `npm install {package} -g`
npm version 6.9.2

## Expected Behavior
A more graceful fail, no internal failure.

**Comment by DanielRuf** [comment]
It seems the owner is not correct. You can fix that with `chown` and `whoami`.

**Comment by DanielRuf** [comment]
It seems the owner is not correct. You can fix that with `chown -R` and `whoami`.
