### ISSUE TITLE
[BUG] npm install --offline fails with ENOTCACHED even if dependencies are installed

### ISSUE THREAD

**Issue by zwang20** [npm/cli#7781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Currently, running `npm install --offline` on a tarball fails with ENOTCACHED even if dependencies are installed.

### Expected Behavior

Installing from a tarball offline if all its dependencies are present should just install the package.

### Steps To Reproduce

```
# npm install -g meow supports-color @types/minimist camelcase-keys
# npm list -g
/usr/lib
├── @types/minimist@1.2.5
├── camelcase-keys@9.1.3
├── corepack@0.29.3
├── meow@13.2.0
├── node-gyp@10.2.0
├── nopt@7.2.0
├── npm@10.8.3
├── semver@7.6.3
└── supports-color@9.4.0
# npm cache clean -f
# npm pack supports-color-cli
# npm install -g --offline supports-color-cli-3.0.0.tgz
npm error code ENOTCACHED
npm error request to https://registry.npmjs.org/meow failed: cache mode is 'only-if-cached' but no cached response is available.
npm error A complete log of this run can be found in: /root/.npm/_logs/2024-09-13T03_19_04_529Z-debug-0.log
```

### Environment

- npm: 10.8.3
- Node.js: 22.8.0
- OS Name: Arch Linux x86_64
- System Model Name: Macbook Air
- npm config:
```ini
; copy and paste output from `npm config ls` here
; node bin location = /usr/bin/node
; node version = v22.8.0
; npm local prefix = /home/michael
; npm version = 10.8.3
; cwd = /home/michael
; HOME = /home/michael
; Run `npm config ls -l` to show all defaults
```

**Comment by milaninfy** [comment]
I believe this is not an issue with npm cli. npm will need to fetch package specific data to install appropriate version of it's dependencies. If the calls are not cached ( since you are manually clearing cache ) `--offline` will restrict npm to fetch these details and fail. if you are running it with `--offline` they needs to be available in cache.
