### ISSUE TITLE
Changes to package.json when running fix during publishe are not saved to filesystem

### ISSUE THREAD

**Issue by ItamarGronich** [npm/cli#7782]
## The problem
When running publish npm will run auto fix on package.json.

However, the `pkg.save()` method is not called so the actual file is not updated.

This causes NPM to publish the package with a possible wrong version.

https://github.com/npm/cli/blob/366c07e2f3cb9d1c6ddbd03e624a4d73fbd2676e/lib/commands/publish.js#L199

## Example case
Consider the following package.json:
```json
{
  "name": "foo", 
  "version": "1.0.0-rc.042932104"
}
```

The pre-release version is invalid SemVer because [numbered prerelease tags are not allowed to have a leading zero](https://semver.org/#spec-item-9).
Therefore, during publish, the fix command which runs `semver.clean()` will fix this automatically to `1.0.0-rc.42932104`
The npm publish logs will all show this fixed version  `1.0.0-rc.42932104`

Howver, the package will actually get published with the leading zero  `1.0.0-rc.042932104` because the `save()` method wasn't called to actually write the fix to the package.json file.

**Comment by milaninfy** [comment]
@ItamarGronich while publishing a package, npm do warn about these automatic fix that happens and instruct to run `npm pkg fix` to have it applied locally and clean up things. https://github.com/npm/cli/issues/7299#issuecomment-2010009355

**Comment by milaninfy** [comment]
**Closing** as the documentation changes related to this behaviour will be tracked at https://github.com/npm/cli/issues/7299

**Comment by ItamarGronich** [comment]
> [@ItamarGronich](https://github.com/ItamarGronich) while publishing a package, npm do warn about these automatic fix that happens and instruct to run `npm pkg fix` to have it applied locally and clean up things. [#7299 (comment)](https://github.com/npm/cli/issues/7299#issuecomment-2010009355)

@milaninfy An error would be way better.
