### ISSUE TITLE
[BUG] <title>write EPROTO 101057795:error:04091068

### ISSUE THREAD

**Issue by TriF-px** [npm/cli#7787]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### This issue exists in the latest npm version

- [ ] I am using the latest npm

### Current Behavior

npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code EPROTO
npm ERR! errno EPROTO
npm ERR! syscall write

npm ERR! write EPROTO 101057795:error:04091068:rsa routines:INT_RSA_VERIFY:bad signature:openssl\crypto\rsa\rsa_sign.c:278:
npm ERR! 101057795:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:openssl\ssl\s3_clnt.c:2032:

### Expected Behavior

npm install error

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:v4.2.0
- Node.js: v7.8.0
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by milaninfy** [comment]
npm `v4` is very old version of npm.

If your bug is preproducible on `npm@latest`, please re-file this using our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).

**Comment by travispaul** [comment]
@TriF-px (or anyone else that might find themselves here) try setting this env var before running `npm install`: 

```sh
export OPENSSL_ia32cap="~0x1000000000000000:~0"
```

This worked for me.

See: nodejs/node/issues/12691

Yes, I know this is an ancient version of node and npm, but I'm trying to rebuild an ancient project, as-is before I can go updating anything.
