### ISSUE TITLE
[DOCS] Document --timing flag in man pages and command usage.

### ISSUE THREAD

**Issue by sebastiancarlos** [npm/cli#7788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Enhancement, not another kind of Docs Enhancement.

- [X] This is a CLI Docs Enhancement.

### Description of Problem

The `--timing` flag is described in the documentation (`using-npm/logging.md`). But it's not to be found in the man pages (`commands/npm-install.md`) or in the `npm install --help` usage.

### Docs URL

commands/npm-install.md

**Comment by milaninfy** [comment]
Just like other logging flags like `--verbose`, `--silent` etc,   `--timing` is not specific to any command. It can be used with almost all the commands and that's why it's not a part of any specific command's documentation.

**Comment by sebastiancarlos** [comment]
@milaninfy Got it. Would you consider documenting this fact somewhere that is available from the CLI? I'm asking because I think a CLI user would like to know that there is a set of flags which can be used with any command.

Note that it is also not documented on the `npm(1)` man page, which would be a fine place, I think, for such generic information.
