### ISSUE TITLE
[BUG] unable to run script

### ISSUE THREAD

**Issue by ghost** [npm/cli#7792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

gives errors

### Expected Behavior

after the npm command the build should start and complete without errors

### Steps To Reproduce

1. I downloaded a node.js script from https://github.com/shikoshib/winerr
2. Extract to Downloads folder
3. Go to folder
4. Cut files and paste to the root of the folder
5. Rename winerr-main to winerr
6. Go to node.js command prompt
7. Go to Downloads folder with scripts and copy the path
8. In node.js command prompt enter path to node.js script
9. After entering to folder with node.js scripts, enter npm i command and hit Enter
10. Wait until the error is displayed
11. When finishes I see errors (logs see in Environment with word "logs:")

### Environment

- npm: 10.8.3
- Node.js: 20.17.0
- OS Name: Windows 11
- System Model Name:
- npm config:
; "builtin" config from C:\Users\VM6.COLLABNET\AppData\Roaming\npm\node_modules\npm\npmrc
 
prefix = "C:\\Users\\VM6.COLLABNET\\AppData\\Roaming\\npm"
 
; node bin location = C:\Program Files\nodejs\node.exe
; node version = v20.17.0
; npm local prefix = C:\Users\VM6.COLLABNET\Downloads\winerr
; npm version = 10.8.3
; cwd = C:\Users\VM6.COLLABNET\Downloads\winerr
; HOME = C:\Users\VM6.COLLABNET
; Run `npm config ls -l` to show all defaults.

logs:
[npm warn deprecated inflight@1.0.6.txt](https://github.com/user-attachments/files/17113132/npm.warn.deprecated.inflight%401.0.6.txt)
[2024-09-24T13_17_58_102Z-debug-0.log](https://github.com/user-attachments/files/17113133/2024-09-24T13_17_58_102Z-debug-0.log)

**Comment by milaninfy** [comment]
@Iliya5digital Based on the error logs it seems you would need python installed in your system, Please check `node-gyp` documentation for that. This doesn't seems to be the issue with npm-cli, and also I was able to install the project in windows system without any error. 
**Closing:** For support please post your question to [github.community](https://github.community).
