### ISSUE TITLE
[BUG] NPM fails to publish workspace packages

### ISSUE THREAD

**Issue by manchuck** [npm/cli#7812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When you run `npm publish -ws`, it will go through and publish all those packages. However, if one of those packages is not updated, the command will fail since NPM rejects publishing the same version.

### Expected Behavior

Running `npm publish -ws` will keep publishing the other packages even if one fails

### Steps To Reproduce

Create a workspace with three packages (A, B, C)
Bump the versions for A and C 
Run `npm publish -ws`
B will fail to publish and npm will not try to publish C 

### Environment

- npm: 10.8.3
- Node.js: v22.9.0
- OS Name: MacOS
- System Model Name: Macbook Pro
- npm config:
```ini
; "user" config from /Users/manchuck/.npmrc

//registry.npmjs.org/:_authToken = (protected)
save-exact = true
save-prefix = ""

; node bin location = /Users/manchuck/.nvm/versions/node/v22.9.0/bin/node
; node version = v22.9.0
; npm local prefix = /Users/manchuck/Projects/vonage/node-sdk
; npm version = 10.8.3
; cwd = /Users/manchuck/Projects/vonage/node-sdk/packages
; HOME = /Users/manchuck
; Run `npm config ls -l` to show all defaults.

```

**Comment by milaninfy** [comment]
Thanks for filing this! This is currently working as intended and it's by design changing this would be a breaking change.

**Comment by manchuck** [comment]
OK, I will put this in as an enhancement for the next version.  When this happens (because I have all but one package getting a version bump), I need to go into my workspace folder loop though, and then publish:

```bash
for i in $(ls -d *)                                                                                                                          ─╯
(cd $i && npm publish)
```

Otherwise NPM stops after that package fails to publish

**Comment by manchuck** [comment]
Also, how is this a breaking change? Can't we add a flag something like `--ignore-publish-fail`? Adding a new flag is not a Breaking change

`npm -ws publish --ignore-publish-fail`
