### ISSUE TITLE
[BUG] Multiple quirks around dependency resolution

### ISSUE THREAD

**Issue by mcandre** [npm/cli#7816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

The NPM system has several quirks that complicate dependency resolution.

* NPM's design damages `npm ls --all`'s ability to show the true, full dependency tree whenever any of the packages involved are unable to install. This makes it more difficult to diagnose problems installing packages.
* Duplicated packages in the tree listing don't show subtrees consistently. I'm seeing only one of the duped parents show its subtree.
* When npm install fails, it doesn't always show the most relevant information. Instead of showing a failing leaf, it shows an ancestor. It should show the leaf and the chain of ancestors together.
* When npm install fails to locate a package, I want to see the specific HTTP response code it got from the repository, so that I can examine whether the official NPM service or downstream caching repository are operating correctly.
* The NPM website would be a great place to show each package's full dependency tree, on a per-version basis, as a convenient, reliable way to gather this important information.
* I'd like a download TGZ button on each version, of each package, on the NPM website. Many packages fail to link to a VCS source code repository, making it more cumbersome to analyze the source code. Currently, the website provides individual downloads for each file asset of the package, but no convenient aggregate download URL. Presumably, the REST API has this option. So, use that to fulfill a Web download button feature.

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by milaninfy** [comment]
@mcandre Thanks for taking the time to share your idea! New ideas are always appreciated and are better suited for [our RFC repo](https://github.com/npm/rfcs) instead since that's the right place in order to get more attention from the rest of the team and the community.
