### ISSUE TITLE
[BUG] npm run script doesn't exit automatically when using the & operator to run installs in parallel

### ISSUE THREAD

**Issue by bruce-c-liu** [npm/cli#7823]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

You have to press enter in the terminal to exit the script.

### Expected Behavior

The `npm run setup` command should exit when complete.

Btw, running `npm ci & npm --prefix ./server ci` directly in the terminal exits as expected.

### Steps To Reproduce

Directory structure:
```
src/
├── package.json
├── package-lock.json
└── server/
    ├── package.json
    └── package-lock.json
```

Script in `src/package.json`:
```
// I want to use `&` so that both `npm ci` can be run in parallel.
"setup": "npm ci & npm --prefix ./server ci" 
```

### Repro
Execute `npm run setup`

### Environment

- npm: 10.8.3
- Node.js: 22.9.0
- OS Name: Apple Sonoma 14.7
- System Model Name: Macbook Pro
- npm config:
```ini
; "user" config from /Users/bruce.liu/.npmrc

; audit = false ; overridden by project

; "project" config from /Users/bruce.liu/Desktop/ai-search/.npmrc

audit = false
fund = false
prefer-dedupe = true
save-exact = true
save-prefix = ""
script-shell = "/bin/bash"

; node bin location = /Users/bruce.liu/.nvm/versions/node/v22.9.0/bin/node
; node version = v22.9.0
; npm local prefix = /Users/bruce.liu/Desktop/ai-search
; npm version = 10.8.3
; cwd = /Users/bruce.liu/Desktop/ai-search
; HOME = /Users/bruce.liu
```

**Comment by milaninfy** [comment]
It works fine and also exits normally... it does not seem to be an issue with npm cli. 

``` bash
~/workarea/rep/test $ npm run setup

> test@1.0.0 setup
> npm ci && npm --prefix ./srv ci


added 12 packages in 4s

added 155 packages, and audited 156 packages in 1s

33 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
~/workarea/rep/test $ npm pkg get scripts
{
  "setup": "npm ci && npm --prefix ./srv ci"
}
```

**Comment by bruce-c-liu** [comment]
Thank for you looking into this, @milaninfy! Turns out the issue only happens with the `patch-package` [package](https://github.com/ds300/patch-package). 

```
{
  "scripts": {
    "setup": "npm ci & npm --prefix server ci",
    "postinstall": "patch-package"
  },
  "dependencies": {
    "patch-package": "^8.0.0"
  }
}
```

This issue isn't related to NPM cli, so going to close it. However, any insight on how to fix `patch-package` to automatically exit would be appreciated. 😝

**Comment by bruce-c-liu** [comment]
For posterity, this seems like a general bash problem.
https://stackoverflow.com/questions/23125527/how-to-return-to-bash-prompt-after-printing-output-from-backgrounded-function/23125687#23125687
