### ISSUE TITLE
[BUG] npm hangs forever literally for hours and I had to kill it. 

### ISSUE THREAD

**Issue by mai1x9** [npm/cli#7826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`npm install ` is taking life long time probably, its never ending and gets hanged. 

### Expected Behavior

To successfully run the command. 

### Steps To Reproduce

I dont think its environment issue, rather some sort of blocking of IP address due to continously pulling the packages from the npm. I am not sure if that's the reason.

It gets hanged at a point as shown in the logs,
```
(##################) ⠧ reify:geoip-lite: (##################) ⠧ reify:geoip-lite: http fetch GET 200 https://registry.npmjs.org/geoip-lite/-/geoip-lite-1.4.10.tgz 35198ms (cache miss)
```

Now I remove `geoip-lite` from package.json, Now it gets hanged at `aws-sdk`. If i remove aws-sdk from package.json, now it gets hanged at some other module.

So apparently, I am thinking as my package.json have many modules, the npm registry might be blocking it or something like that.

When i have only a few of 10-15 of module its working fine.

### Environment

- npm: 8.11.0 tried even 9.8.-
- Node.js: 16.16.0
- OS Name: Ubuntu 20.05
- System Model Name:
- npm config:
```ini
; node bin location = /usr/local/bin/node
; node version = v16.16.0
; npm local prefix = /home/ubuntu/build-admin
; npm version = 8.11.0
; cwd = /home/ubuntu/build-admin
; HOME = /home/ubuntu
; Run `npm config ls -l` to show all defaults.
```

**Comment by milaninfy** [comment]
Check with latest npm and appropriate node version for latest npm ( 10.9.0 ) 
Also, if possible please provide package.json, logs, minimum reproduction case to reproduce this issue

**Comment by riceyrice** [comment]
I've seen something like this with npm 10.9.0 when run by docker build. Doesn't occur on the host machine. Doesn't occur with npm 10.8.3. Workaround was to pin npm to 10.8.

**Comment by mai1x9** [comment]
> Check with latest npm and appropriate node version for latest npm ( 10.9.0 ) Also, if possible please provide package.json, logs, minimum reproduction case to reproduce this issue

The issue exists with all versions of npm no matter what it is. After lot of debugging and use of yarn install, finally the culprit was found. Its related to `puppeteer ` which is hanging the npm install. A lot of issues where raised on it, and work around was found. 


But I could able to only figure it out with `yarn`, I dont know why npm could not pin point where it got blocked.
