### ISSUE TITLE
[BUG] `--no-bin-links` and `npm set bin-links=false` does not work at all

### ISSUE THREAD

**Issue by zhenlige** [npm/cli#7827]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

The program still tries to create symlinks.

### Expected Behavior

The program should intall packages without trying to create symlinks.

### Steps To Reproduce

1. Launch npm v10.9.0 on Windows 11
2. Open a project in exFAT file system
3. Run either of below:
* `npm install --no-bin-links`
* `npm set bin-links=false` and then `npm install`
4. See error: `EISDIR: illegal operation on a directory, symlink '` (some path) `' -> '` (some path) `'`

### Environment

- npm: 10.9.0
- Node.js: 20.18.0
- OS Name: Windows 11
- System Model Name: Legion R9000P2021H
- npm config:
```ini
; "builtin" config from C:\Users\zhenlige\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\zhenlige\\AppData\\Roaming\\npm"

; "user" config from C:\Users\zhenlige\.npmrc

bin-links = false
registry = "https://registry.npmmirror.com/"

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v20.18.0
; npm local prefix = E:\fonts\src\Iosevka-main
; npm version = 10.9.0
; cwd = E:\fonts\src\Iosevka-main
; HOME = C:\Users\zhenlige
; Run `npm config ls -l` to show all defaults.
```

**Comment by kchindam-infy** [comment]
This is not an issue.
