### ISSUE TITLE
I've been waiting for almost 2 months for a name dispute!

### ISSUE THREAD

**Issue by AllanOricil** [npm/cli#7829]
Why are you not responding to tickets for name disputes? I submitted 2 tickets and none were answered. Is this process broken?

**Comment by wraithgar** [comment]
**Closing:** this looks to be an issue with the registry which is outside the scope of this repo. For registry support please go to [npmjs.com/support](https://www.npmjs.com/support). If you believe this is a bug with the cli, please provide further clarifying details.

**Comment by AllanOricil** [comment]
Hire people to answer tickets, then
