### ISSUE TITLE
Performance issue with Node js version 20

### ISSUE THREAD

**Issue by richakhosla** [npm/cli#7844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

we are facing with respect to Node js application deployed on BTP Cloud foundry Canada region.
Please find more details below :
 

This application internally calls https REST endpoint in Convergent mediation system(On premise)
we are on Node js version 20 and  using sap-cf-axios latest to send request to convergent mediation system(On premise ) via cloud connector .The connectivity is made using Destination which is maintained in BTP subaccount.

Issue :  The performance is bad when we use Node js version 20 with stated axios Library.
However, if we switch to Node js version 18 and same current libabry  performance is way better.

For comparison, please find stats below :

Node js 20 with sap-cf-axios
![image](https://github.com/user-attachments/assets/6001caad-bb95-4e81-8ce0-ddc3b92c6ef5)

Node js 18 with sap-cf-axios
![image](https://github.com/user-attachments/assets/7ba37d3f-4fce-4406-816e-c5a084b958f7)

Sample code below

let SapCfAxios = require('sap-cf-axios').default;

let callSoapApi = async (data, req, res) => {
    try {
        let axios = SapCfAxios("Destination_name");
        let dataResp = await axios({
            method: "POST",
            url: req.url,
            data: data,
            headers: {
                SOAPAction: "SOAP ACTION NAME", // Replace with your SOAP action
            }
        });
        res.status(200).send(dataResp.data);
    } catch (error) {
        generateErrorMessage(req,res,error); //Separate function for error handling
    }
}

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:>=10.3.0
- Node.js:v20.x.x
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by milaninfy** [comment]
If i understand it correctly, It's a performance issue with node and not with npm-cli. I think it's better to file this issue on node js project repository.
