### ISSUE TITLE
[BUG] Problem custom config npm

### ISSUE THREAD

**Issue by agusconde18** [npm/cli#7846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Hello, using the `npm config set customprop 1` command it tells me that  customprop is not valid.

Here it's the log:
npm config set customprop 1
npm error `customprop` is not a valid npm option
npm error A complete log of this run can be found in: [changed for privacity]/2024-10-17T03_53_12_211Z-debug-0.log

### Expected Behavior

It is expected that custom variables can be set

### Steps To Reproduce

1. In this environment windows/linux
2. Using node 22.3.0 or higher
3. Run 'npm config set customprop 1'
4. npm error `customprop` is not a valid npm option

### Environment

- npm: 10.8.1
- Node.js: 22.3.0
- OS Name: Ubuntu 24.04.1 LTS
- System Model Name: Ubuntu

**Comment by ljharb** [comment]
That was an intentional breaking change in v10 (or perhaps v9). You can't set arbitrary config anymore.

**Comment by agusconde18** [comment]
Ok sorry I missed it
