### ISSUE TITLE
Is there a way to run `npm install` while preventing the installation of extraneous packages?

### ISSUE THREAD

**Issue by vctqs1** [npm/cli#7864]
Hi, in my case, I’d like to avoid installing **extraneous** packages because it goes against what we want to achieve with our **SCA tool**.

Is there any way to prevent them from appearing in the `package-lock.json` file when running npm install (without needing to run `npm prune`)?

**Comment by milaninfy** [comment]
Please explain, provide example or link to similer issue where this is reproducible. 

**Closing:** please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).
