### ISSUE TITLE
[FEAT]: implement "npm uninstall" command to uninstall all the dependencies

### ISSUE THREAD

**Issue by SuperGrut** [npm/cli#7866]
I faced a problem where I wanted to uninstall all the dependencies from my project. I tried `npm uninstall` turns out it doesn't exist
I found following ways but they don't seem clean and is complex
`rm -rf node_modules package-lock.json`
`npm uninstall $(npm ls --depth=0 --parseable=true | grep node_modules | sed 's/.*node_modules\///')`

**Comment by milaninfy** [comment]
@akash19coder  Thanks for taking the time to share your idea!.

Another approach/command you can use is `npm pkg delete dependencies` which will remove dependencies entry from your package.json and `npm install` to sync node_modules after deletion. Use these commands with caution as they change package.json. Checkout documentaion related to `npm pkg` command at https://docs.npmjs.com/cli/v10/commands/npm-pkg
