### ISSUE TITLE
[BUG] Overrides with local dependencies produces different result depending on install-links flag

### ISSUE THREAD

**Issue by rH4rtinger** [npm/cli#7867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

**Note:** The used dependency is irrelevant. 

I have a `child` and a `project` npm project. 

In my `child` project have the following dependencies:
```json
"dependencies": {
  "@types/semver": "^6.x"
}
```

In my `project` project I have this dependencies and an override:
```json
"overrides": {
   "@types/semver": "^7.x"
  },
  "dependencies": {
    "@types/semver": "^7.x",
    "child": "../child"
  }
```

When I run `npm i --install-links=true` in my `project` and validating my installed dependencies with `npm list --all`, I only get version 7.x.

```
project_links_true@1.0.0 C:\dev\overrides_example\project_links_true
├── @types/semver@7.5.8 overridden
└─┬ child@1.0.0
  └── @types/semver@7.5.8 deduped
```

When I run `npm i --install-links=false` in my `project` and validating my installed dependencies with `npm list --all`, I get version 6.x from my child.

```
 project_links_false@1.0.0 C:\dev\overrides_example\project_links_false
├── @types/semver@7.5.8 overridden
└─┬ child@1.0.0 -> .\..\child
  └── @types/semver@6.2.7
```

### Expected Behavior

I was expecting that `overrides` will work also for local dependencies  as described in the [documentation](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#overrides).

I expected that the dependency tree will only have version 7.x for my given dependency.

However, they only work so, when using the `install-links=true` flag.

I expected them to work as well with `install-links=false`.

### Steps To Reproduce

I made also an example project, see https://github.com/rH4rtinger/override_example.

1. Create a child project with the dependency stated above and run `npm install` in it.
2. Create a parent project with the dependencies and override stated above and run `npm install --install-links=false`.
3. Run `npm list --all` to show the dependency tree.

### Environment

- npm: 10.9.0
- Node.js: 22.4.0
- OS Name: Windows 10
- System Model Name: Vostro 15 7510
- npm config:
```ini
; "builtin" config from C:\Users\r.hartinger\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\r.hartinger\\AppData\\Roaming\\npm"

; "user" config from C:\Users\r.hartinger\.npmrc

loglevel = "info"

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v22.4.0
; npm local prefix = C:\dev\overrides_example
; npm version = 10.9.0
; cwd = C:\dev\overrides_example
; HOME = C:\Users\r.hartinger
```

**Comment by kchindam-infy** [comment]
This is working as expected.

**Comment by wglanzer** [comment]
@kchindam-infy Can you explain this behaviour a little bit deeper? 
I do not understand, why this feature is working as expected  - what is the "expected situation" here and why?
