### ISSUE TITLE
Question about .npmrc

### ISSUE THREAD

**Issue by tzvetelin-vassilev** [npm/cli#7869]
I can't find a way how to configure and install my project. I need your assistance.
I read all the documentation provided here - https://docs.npmjs.com/cli/v10/configuring-npm/npmrc and still can't handle it.

The scenario that I have looks like this:

```
package.json

{
  ...
  "dependencies": {
    // packages available in https://npm.company-a.com
    "package-a": "^1.0.0",
    "@package-a/plugin-a": "^1.0.0",
    "@company-a/package-c": "^1.0.0",

    // packages available in https://npm.company-b.com
    "package-x": "^1.0.0",
    "@package-x/plugin-y": "^1.0.0",
    "@company-b/package-z": "^1.0.0",

    // packages available in https://registry.npmjs.org
    ...
  },
  ...
}
```

These packages targets 2 private registries.
From the documentation I assume the .npmrc should looks like this:

```
registry=https://npm.company-a.com
//npm.company-a.com/:_authToken=MYTOKEN1

registry=https://npm.company-b.com
//npm.company-b.com/:_authToken=MYTOKEN2
```

But for some reason this is not working. I will appreciate any help from your side soon as possible.

**Comment by mbtools** [comment]
The npmrc entries come into play if you switch npm to a different registry. To get dependencies from different sources, you need to change your package.json (see [deps](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#dependencies)). 

You could for example point to a tarball on your npm.company-a.com registry. However, that would be a fixed version.

If you want more flexibility, take a look at [Verdaccio](https://verdaccio.org/) where you can define uplinks to several registry servers.

**Comment by milaninfy** [comment]
**Closing:** this looks to be a general support question which is outside the scope of the repo. For support please post your question to [github.community](https://github.community).

**Comment by tzvetelin-vassilev** [comment]
I have taken some time to investigate Verdaccio, and I found it to be quite easy to configure and use. In a development environment, this solution seems acceptable; however, in a production environment, I believe it may not be fully justified.

From my experience with various package management systems such as pip, Conan, Maven, NuGet, and Swift, their primary responsibility is to resolve dependencies effectively. These systems do not require an additional tool like Verdaccio for dependency resolution. However, it seems that npm is still facing challenges in resolving package.json dependencies in similar scenarios.

I would like to kindly inquire if the npm team has any plans to enhance the dependency resolution capabilities in upcoming versions. Perhaps a solution that incorporates a pool of registries, similar to those found in modern package management systems, could help address this issue.
