### ISSUE TITLE
[BUG] `npm install <name>` does not install latest tag if it is deprecated, and pre-release

### ISSUE THREAD

**Issue by everett1992** [npm/cli#7873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```
npx npm@10.9.0 install @aws-sdk/add-glacier-checksum-headers-browser
npm error code ETARGET
npm error notarget No matching version found for @aws-sdk/add-glacier-checksum-headers-browser@*.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.
```

### Expected Behavior

I would expect this to succeed and install 0.1.0-preview.2, because it is the `latest` dist-tag.

```
$ npx npm@10.9 info @aws-sdk/add-glacier-checksum-headers-browser deprecated version dist-tags.latest
deprecated = 'The package @aws-sdk/add-glacier-checksum-headers-browser was released in Developer Preview. It is no longer supported.'
version = '0.1.0-preview.2'
dist-tags.latest = '0.1.0-preview.2'
```

Or,  the command should error with a clear message because the version is deprecated and prerelease, which should be strongly discouraged from being used. However, ETARGET error is wrong.

It appears to only happen with deprecated prerelease versions. If the latest tag is 1.0.0 and deprecated npm will install it.
npm will even install a different, non prerelease, version   

| package | latest | deprecated | other versions | behavior |
| --- | --- | --- | --- | --- |
| calebev-prerelease-test-a | 1.0.0 | yes | none | install 1.0.0, no issue |
| calebev-prerelease-test-b | 1.0.0-prerelease | yes | none | errors ETARGET |
| calebev-prerelease-test-c | 1.0.0-prerelease | yes | 1.0.0 | install 1.0.0 |

### Steps To Reproduce

1. In an empty npm package
2. With this config `{}`
3. Run npx npm@10.9.0 install calebev-prerelease-test-b''
4. See error...

Or ` @aws-sdk/add-glacier-checksum-headers-browser`
```
npm error code ETARGET
npm error notarget No matching version found for calebev-prerelease-test-b@*.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.
```

### Environment

- npm: 10.9.0
- Node.js: 22.8.0
- OS Name: Ubuntu
- System Model Name: N/A
- npm config:
```ini
; none
```

**Comment by milaninfy** [comment]
**Closing:** this appears to be working as expected.

**Comment by everett1992** [comment]
Is there any corresponding documentation change? This changed since npm 10.8 and I didn't see it in any change log. It's not explained by the npm install documentation, and the error message is not informative.

**Comment by shazron** [comment]
I believe this new behavior started with `npm@10.8.2` or greater (bundled starting with `node@20.17.0`)
Note item 3 in the list below, there are three new clauses in the check, plus one new clause in the enclosing if statement.

Supporting info:

1. https://docs.npmjs.com/cli/v10/using-npm/changelog#1082-2024-07-09
2. https://github.com/npm/npm-pick-manifest/releases/tag/v9.1.0
3. https://github.com/npm/npm-pick-manifest/commit/9f5560ff8a21a83323fa188b44db8545ac8bd55d
4. https://github.com/nodejs/nodejs.org/issues/6913
5. node version to npm version mappings: https://nodejs.org/dist/index.json

I couldn't find the documentation change either -- but from item 4 it appears that the intent is the corrected behavior, so it's a bug fix, thus we might have relied on a bug before.
