### ISSUE TITLE
[BUG] `npm install` writes to `node_modules` when installing zero packages

### ISSUE THREAD

**Issue by ojacobson** [npm/cli#7874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When `npm install` runs and finds nothing to do, it sometimes modifies files in `node_modules`, even though the contents of those files have not changed.

This makes it impractical to point any tool that relies on `mtime` (`make`, `cargo build`, etc) at `node_modules` if that tool might also run `npm install`: downstream tools will always consider `node_modules` to contain changes if `npm install` has run, regardless of the outcome.

### Expected Behavior

`npm install` is not documented as to when and how it updates `node_modules`, but it seems reasonable to expect that it does not write to this directory if all packages are installed and up to date. This is the behaviour of most build and project management tools.

### Steps To Reproduce

Given

```json
{
  "name": "npm-install-issue",
  "private": "true",
  "dependencies": {
    "vite": "^5.4.9"
  }
}
```

1. Run `npm install` once, to install `vite` and its dependencies.
2. Note the modification times of files in `node_modules` (eg. with `find node_modules -ls > before`).
3. Then run `npm install` again. No new packages will be installed.
4. Note the modification times of files again (eg. with `find node_modules -ls > after`).

Expected: both lists should be indentical.

Actual: several files (in my tests, consistently including `node_modules/@rollup`, `node_modules/@esbuild`, and `node_modules/.package-lock.json`) will have their modification times updated.

Running a similar test with `shasum` instead of `find -ls` shows that the contents of these files have not changed; it's just the mtime that updates.

### Environment

```shell
% npm -v
10.8.2

% node -v
v22.8.0

% uname -a
Darwin Boule 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6030 arm64

% npm config ls
; node bin location = /opt/local/bin/node
; node version = v22.8.0
; npm local prefix = /Users/owen/Projects/grimoire.ca/npm-install
; npm version = 10.8.2
; cwd = /Users/owen/Projects/grimoire.ca/npm-install
; HOME = /Users/owen
; Run `npm config ls -l` to show all defaults.
```

**Comment by ojacobson** [comment]
On further testing, `npm install` also changes the `mtime` of `package-lock.json` even on a no-op.

**Comment by kchindam-infy** [comment]
HI @ojacobson npm install can and will change files, this is working as expected.
