### ISSUE TITLE
[BUG] Unpublish a package version  not possible if it has dependencies with other packages

### ISSUE THREAD

**Issue by aryamohanan** [npm/cli#7875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Not able to unpublish a package version if it has dependencies with other packages.
 I attempted to use `npm unpublish package@version`, but encountered the following error. 

> You can no longer unpublish this package.
> npm ERR! Failed criteria: 
> npm ERR! has dependent packages in the registry

I would like to unpublish the specific version  a package, that have dependents.

**Comment by milaninfy** [comment]
@aryamohanan Please checkout this `unpublish` policy https://docs.npmjs.com/policies/unpublish

Generally if other package in registry depends on the package you are trying to unpublish then it will throw this error, as logically once you unpublish the package, the other dependent packages will break. This is a measure to prevent that. 
 

**Closing:** this looks to be an support question with the registry which is outside the scope of this repo. For registry support please go to [npmjs.com/support](https://www.npmjs.com/support). If you believe this is a bug with the cli, please provide further clarifying details.

**Comment by aryamohanan** [comment]
@milaninfy I need to unpublish the dependent package as well. The dependent packages are also part of our monorepo and were published using Lerna. However, the versions were mistakenly updated by one version too high, so I need to revert all the packages in the repository.
