### ISSUE TITLE
http://stackoverflow.com/questions/6880232/disable-check-for-mock-location-prevent-gps-spoofing

### ISSUE THREAD

**Issue by doni108108doni** [npm/cli#7877]
https://github.com/smarques84/MockLocationDetector/blob/48962c329d4fb291a19474ffdda8bbc8cc5516d7/library%2Fsrc%2Fmain%2Fjava%2Fcom%2Finforoeste%2Fmocklocationdetector%2FMockLocationDetector.java#L١-L٩١

**Comment by milaninfy** [comment]
**Closing**: Please use and fill our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).
