### ISSUE TITLE
git.launchpad.net/ubuntu/+source/upgrade-system/plain/upgrade-system?h=applied/ubuntu/oracular-devel&id=5c5a4dfd7e8835f0e170e557510b5989387e2670

### ISSUE THREAD

**Issue by doni108108doni** [npm/cli#7878]
https://git.launchpad.net/ubuntu/+source/upgrade-system/plain/upgrade-system?h=applied/ubuntu/oracular-devel&id=5c5a4dfd7e8835f0e170e557510b5989387e2670

**Comment by milaninfy** [comment]
**Closing**: Please use and fill our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).
