### ISSUE TITLE
[BUG] Exit handler never called problem while installing node dependencies.

### ISSUE THREAD

**Issue by bishalthapa2055** [npm/cli#7881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I have created new folder for my projects and then want to install the node dependencies then error occured while installing the dependencies. Errors says exit handler never called !. My error logs says this ;

npm ERR! Exit handler never called!
npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

```[tasklist]
### Tasks
```

**Comment by JulianJJ** [comment]
Seem to get this issue suddenly.

**Comment by mfaghfoory** [comment]
We are having the same issue. by adding --loglevel verbose to npm install, I could see these errors:

```
76.03 npm http fetch GET https://registry.npmjs.org/write-file-atomic/-/write-file-atomic-3.0.3.tgz attempt 3 failed with UNABLE_TO_GET_ISSUER_CERT_LOCALLY
76.03 npm http fetch GET https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz attempt 3 failed with UNABLE_TO_GET_ISSUER_CERT_LOCALLY
76.03 npm http fetch GET https://registry.npmjs.org/ws/-/ws-7.5.9.tgz attempt 3 failed with UNABLE_TO_GET_ISSUER_CERT_LOCALLY
76.03 npm http fetch GET https://registry.npmjs.org/yaml/-/yaml-2.3.1.tgz attempt 3 failed with UNABLE_TO_GET_ISSUER_CERT_LOCALLY
76.04 npm http fetch GET https://registry.npmjs.org/yallist/-/yallist-3.1.1.tgz attempt 3 failed with UNABLE_TO_GET_ISSUER_CERT_LOCALLY
.
.
.
```

**Comment by kchindam-infy** [comment]
Hi @bishalthapa2055 , please share the steps to reproduce and system configuration information.

**Comment by nitinchavan01** [comment]
@bishalthapa2055 I see this is issue is marked closed but dont see a resolution here. DO you mind sharing what was to resolve this issue and reason for the issue? Thanks

**Comment by ojob** [comment]
Hi, I faced the same symptoms while working with `pre-commit` in Gitlab-CI (see [pre-commit#3516](https://github.com/pre-commit/pre-commit/issues/3516)), so maybe this could help:

- the CI job fails with message `error Exit handler never called!`
- no related warning or error is displayed before in the CI log.

After retrieving the npm log file (by a copy from `/root/npm/_logs/` to a subfolder of `$CI_PROJECT_DIR`), I can see what causes my issue:

```log
(...)
1946 verbose audit error FetchError: request to https://registry.npmjs.org/-/npm/v1/security/advisories/bulk failed, reason: self-signed certificate in certificate chain
1946 verbose audit error     at ClientRequest.<anonymous> (/builds/si-interne/kaizen-etl/.cache/pre-commit/repozkvt4_f6/node_env-default/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:130:14)
1946 verbose audit error     at ClientRequest.emit (node:events:508:28)
1946 verbose audit error     at emitErrorEvent (node:_http_client:107:11)
1946 verbose audit error     at _destroy (node:_http_client:954:9)
1946 verbose audit error     at onSocketNT (node:_http_client:974:5)
1946 verbose audit error     at process.processTicksAndRejections (node:internal/process/task_queues:91:21) {
1946 verbose audit error   code: 'SELF_SIGNED_CERT_IN_CHAIN',
1946 verbose audit error   errno: 'SELF_SIGNED_CERT_IN_CHAIN',
1946 verbose audit error   type: 'system'
1946 verbose audit error }
1947 silly audit error undefined
1948 silly audit report null
(...)
1992 verbose os Linux 5.10.0-35-amd64
1993 verbose node v24.6.0
1994 verbose npm  v11.5.1
1995 error Exit handler never called!
1996 error This is an error with npm itself. Please report this error at:
1997 error   <https://github.com/npm/cli/issues>
1998 verbose exit 1
1999 verbose code 1
2000 error A complete log of this run can be found in: /root/.npm/_logs/2025-08-20T09_09_17_260Z-debug-0.log
```

So here I’ve got an issue with Self-Signed Root CA, which is sadly not reported to stderr.

Hope this helps!
