### ISSUE TITLE
error Exit handler never called!

### ISSUE THREAD

**Issue by wbsadriana** [npm/cli#7882]
verbose os Windows_NT 10.0.19045
verbose node v20.10.0
verbose npm  v10.9.0
error Exit handler never called!

**Comment by milaninfy** [comment]
**Closing:** this error can arise for a number of reasons; Please read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) & refile an issue with as much information as possible if you're able to **consistently reproduce** this error.    

please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).
