### ISSUE TITLE
[BUG] npm fails install of any packages - TAR_BAD_ARCHIVE

### ISSUE THREAD

**Issue by gsario** [npm/cli#7893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`npm` fails to install any packages, downloading any dependency related to `eslint` causes `TAR_BAD_ARCHIVE` error.

Here's what I tried:

- clean npm caches - doesn't help!
- `npm audit verify` , `npm audit fix`, `npm audit fix --force`
- delete & reinstall npm (various attempts with various protocols for deletion and installation)
- tried to disable `eslint`, but react app creation scripts contain it by default
- tried to upgrade `eslint` version, but I get the same `TAR_BAD_ARCHIVE` when `eslint` is being installed

Here are the failed downloads from the logs after running `npm install`, `npm init @eslint/config@latest` or any other package install that has dependencies on `eslint`:

```
7097 http fetch GET 304 https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-3.1.3.tgz 864ms (cache skip)
7098 warn tar TAR_BAD_ARCHIVE: Unrecognized archive format
7099 silly tar Error: TAR_BAD_ARCHIVE: Unrecognized archive format
7099 silly tar     at Unpack.warn (/usr/local/lib/node_modules/npm/node_modules/tar/lib/warn-mixin.js:21:40)
7099 silly tar     at Unpack.warn (/usr/local/lib/node_modules/npm/node_modules/tar/lib/unpack.js:236:18)
7099 silly tar     at Unpack.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:83:14)
7099 silly tar     at Unpack.emit (node:events:530:35)
7099 silly tar     at [emit] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:313:12)
7099 silly tar     at [maybeEnd] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:468:17)
7099 silly tar     at [consumeChunk] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:476:21)
7099 silly tar     at Unpack.write (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:427:25)
7099 silly tar     at Unpack.end (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:548:14)
7099 silly tar     at Pipe.end (/usr/local/lib/node_modules/npm/node_modules/minipass/dist/commonjs/index.js:116:23) {
7099 silly tar   recoverable: false,
7099 silly tar   cwd: '/Users/gevorg.sargsyan/Projects/dev/js/fireship-memento/node_modules/fast-deep-equal',
7099 silly tar   code: 'TAR_BAD_ARCHIVE',
7099 silly tar   tarCode: 'TAR_BAD_ARCHIVE'
7099 silly tar }
```

```
7146 silly packumentCache corgi:https://registry.npmjs.org/@svgr%2fwebpack cache-miss
7147 http fetch GET 200 https://registry.npmjs.org/@svgr%2fwebpack 68ms (cache hit)
7148 silly packumentCache corgi:https://registry.npmjs.org/@svgr%2fwebpack set size:85201 disposed:false
7149 warn deprecated workbox-core@6.6.1: this package has been deprecated
7150 warn deprecated workbox-core@6.6.1: this package has been deprecated
7151 warn deprecated workbox-core@6.6.1: this package has been deprecated
7152 warn deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
7153 verbose stack Error: TAR_BAD_ARCHIVE: Unrecognized archive format
7153 verbose stack     at Unpack.warn (/usr/local/lib/node_modules/npm/node_modules/tar/lib/warn-mixin.js:21:40)
7153 verbose stack     at Unpack.warn (/usr/local/lib/node_modules/npm/node_modules/tar/lib/unpack.js:236:18)
7153 verbose stack     at Unpack.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:83:14)
7153 verbose stack     at Unpack.emit (node:events:530:35)
7153 verbose stack     at [emit] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:313:12)
7153 verbose stack     at [maybeEnd] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:468:17)
7153 verbose stack     at [consumeChunk] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:476:21)
7153 verbose stack     at Unpack.write (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:427:25)
7153 verbose stack     at Unpack.end (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:548:14)
7153 verbose stack     at Pipe.end (/usr/local/lib/node_modules/npm/node_modules/minipass/dist/commonjs/index.js:116:23)
7154 error code TAR_BAD_ARCHIVE
7155 error TAR_BAD_ARCHIVE: Unrecognized archive format
7156 silly unfinished npm timer reify 1730736384828
7157 silly unfinished npm timer reify:unpack 1730736388377
7158 silly unfinished npm timer reifyNode:node_modules/fast-deep-equal 1730736388382
```

### Expected Behavior

The packages should be installed, and .tgz archives normally downloaded. 

### Environment

- npm: 10.9.0
- Node.js: v22.11.0
- OS Name: MacOS Sonoma 14.5

**Comment by armantsaturian** [comment]
I had a similar issue getting `304` with `fast-deep-equal` on public wifi, which was fixed after I switched to different wifi. 
Not sure if this will help, but worth giving a try:)

**Comment by gsario** [comment]
Fixed using Claude. 

1. Cleared npm cache completely: 
```
rm -rf ~/.npm
mkdir ~/.npm
```

2. Install latest eslint globally: 
```
npm install -g eslint@latest
```

**Comment by gsario** [comment]
Fixed using Claude. 

1. Cleared npm cache completely: 
```
rm -rf ~/.npm
mkdir ~/.npm
```

2. Installed the latest `eslint` globally: 
```
npm install -g eslint@latest
```

**Comment by skuill** [comment]
Thank you @Arxtage!
Changing Wi-Fi really helped right away. I don’t know what kind of magic is hidden behind this..
![image](https://github.com/user-attachments/assets/8759b10e-9c81-4080-afd4-f71683358989)

**Comment by Verbinmay** [comment]
I don’t understand what kind of magic it is, but I’ve been looking for an answer to this problem for two days, but it was solved by changing Wi-Fi

**Comment by Grach90** [comment]
> I had a similar issue getting `304` with `fast-deep-equal` on public wifi, which was fixed after I switched to different wifi. Not sure if this will help, but worth giving a try:)

Thank you very much @Arxtage for solution!!

**Comment by ardmn** [comment]
How it can be related to Wifi/network if problem only with specific packages like `fast-deep-equal` - looks like npm infra problem

**Comment by Verbinmay** [comment]
https://github.com/eslint/eslint/issues/19106#issuecomment-2488354745
here u can find same info

**Comment by MohammedAslam106** [comment]
> I had a similar issue getting `304` with `fast-deep-equal` on public wifi, which was fixed after I switched to different wifi. Not sure if this will help, but worth giving a try:)

What kind of weird issue is this? 
Fixed when changing the network.

**Comment by novjean** [comment]
I was trying to install expo-cli, the network change didn't work for me in npm with the same error but it worked when I installed using yarn which was also failing before. Thank you @Arxtage !

**Comment by ItzHarshXD** [comment]
It worked after I used VPN. Haha! 😅

**Comment by Kp4103** [comment]
TRY USING VPN, IT SHOULD SOLVE THE ISSUE!!!!

**Comment by prashantgupta123** [comment]
This issue is occurring globally in AWS servers.

**Comment by ganeshthirumani-wavemaker** [comment]
even after changing the network, not working, 

and what if the AWS servers are facing the same issue?. can't be change the network right?

**Comment by jainmohit535** [comment]
this issue can be track here- https://github.com/npm/cli/issues/7986

**Comment by AdityaBirangal** [comment]
I'm facing same issue :(

**Comment by manjeet8562** [comment]
I had the same issue with dockerfile on step npm install

I have added `RUN npm config set registry https://registry.npmmirror.com/ --global` before `npm install` 

it worked for me :)

**Comment by anubhavmalik** [comment]
Happening for GCP as well when using cloudbuild

**Comment by devanshdalmia01** [comment]
Facing the same issue on Azure when building static web app with Nextjs

**Comment by rc-tech-admin** [comment]
Not working for AWS as well

**Comment by NaimishBET** [comment]
@manjeet8562 

         ↳   I have added RUN npm config set registry https://registry.npmmirror.com/ --global before npm install

Thank you, it worked for me as well!

**Comment by yawar-manzoor** [comment]
npm warn tar TAR_BAD_ARCHIVE: Unrecognized archive format
npm error code TAR_BAD_ARCHIVE
npm error TAR_BAD_ARCHIVE: Unrecognized archive format
npm error A complete log of this run can be found in: /home/vsts/.npm/_logs/2024-12-17T11_33_17_845Z-debug-0.log
##[warning]Couldn't find a debug log in the cache or working directory
##[error]Error: Npm failed with return code: 1
Finishing: Install dependencies

  this error while building the react project using azuredevops but on ms hosted agent what can be the cause ?

**Comment by Aki0x137** [comment]
> I had the same issue with dockerfile on step npm install
> 
> I have added `RUN npm config set registry https://registry.npmmirror.com/ --global` before `npm install`
> 
> it worked for me :)

folks, this is an untrusted Chinese mirror, Please use it with caution and definitely don't use this on your companies CI/CD pipeline and workstations.

**Comment by rc-tech-admin** [comment]
The NPM registry is down in APAC

**Comment by ganeshthirumani-wavemaker** [comment]
I have added RUN npm config set registry https://registry.npmmirror.com/ --global before npm install

how can I publish?, 
how can I use old auth token?

**Comment by Hitesh0413** [comment]
```
npm WARN tar TAR_BAD_ARCHIVE: Unrecognized archive format
npm WARN tar TAR_BAD_ARCHIVE: Unrecognized archive format
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
npm WARN deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm WARN deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
npm ERR! code TAR_BAD_ARCHIVE
npm ERR! TAR_BAD_ARCHIVE: Unrecognized archive format
```

Facing same in my Jenkin's pipeline

**Comment by mx-nordem** [comment]
> ```
> 
> npm WARN tar TAR_BAD_ARCHIVE: Unrecognized archive format
> 
> npm WARN tar TAR_BAD_ARCHIVE: Unrecognized archive format
> 
> npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
> 
> npm WARN deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
> 
> npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
> 
> npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
> 
> npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
> 
> npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
> 
> npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
> 
> npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
> 
> npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
> 
> npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
> 
> npm WARN deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
> 
> npm WARN deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
> 
> npm WARN deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
> 
> npm WARN deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
> 
> npm ERR! code TAR_BAD_ARCHIVE
> 
> npm ERR! TAR_BAD_ARCHIVE: Unrecognized archive format
> 
> ```
> 
> 
> 
> Facing same in my Jenkin's pipeline

Had the same issue on my jenkins pipeline, Follow this : https://github.com/npm/cli/issues/7893#issuecomment-2548195340

**Comment by shubham-solytics** [comment]
Facing similar issues with Jenkins pipeline on AWS. 
NPM appears to be UP.

**Comment by thanecoder** [comment]
Facing same issue during NPM Install, npm WARN tar TAR_BAD_ARCHIVE: Unrecognized archive format

**Comment by Hitesh0413** [comment]
> > ```
> > 
> > npm WARN tar TAR_BAD_ARCHIVE: Unrecognized archive format
> > 
> > npm WARN tar TAR_BAD_ARCHIVE: Unrecognized archive format
> > 
> > npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
> > 
> > npm WARN deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
> > 
> > npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
> > 
> > npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
> > 
> > npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
> > 
> > npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
> > 
> > npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
> > 
> > npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
> > 
> > npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
> > 
> > npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
> > 
> > npm WARN deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
> > 
> > npm WARN deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
> > 
> > npm WARN deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
> > 
> > npm WARN deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
> > 
> > npm ERR! code TAR_BAD_ARCHIVE
> > 
> > npm ERR! TAR_BAD_ARCHIVE: Unrecognized archive format
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Facing same in my Jenkin's pipeline
> 
> Had the same issue on my jenkins pipeline, Follow this : [#7893 (comment)](https://github.com/npm/cli/issues/7893#issuecomment-2548195340)

Private packages are not installing , If I am doing this.

**Comment by sanketwankhadeaurionpro** [comment]
Facing similar issue 
npm error code TAR_BAD_ARCHIVE
npm error TAR_BAD_ARCHIVE: Unreco
nized archive format

Guys give fast solution production deployment pending

**Comment by prajyot-tote** [comment]
npm WARN deprecated @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated gauge@4.0.4: This package is no longer supported.
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated vis@4.21.0-EOL: Please consider using https://github.com/visjs
npm ERR! code TAR_BAD_ARCHIVE
npm ERR! TAR_BAD_ARCHIVE: Unrecognized archive format

Facing similar issue. Anyone knows any updates on why this is happening?

**Comment by rutujagaikar** [comment]
getting error code EINTEGRITY on npm install

**Comment by sohail46** [comment]
npm warn tar TAR_BAD_ARCHIVE: Unrecognized archive format
npm warn deprecated npmlog@5.0.1: This package is no longer supported.
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated gauge@3.0.2: This package is no longer supported.
npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.
npm warn deprecated glob@7.2.0: Glob versions prior to v9 are no longer supported
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm error code TAR_BAD_ARCHIVE
npm error TAR_BAD_ARCHIVE: Unrecognized archive format
npm error A complete log of this run can be found in: /root/.npm/_logs/2024-12-17T11_46_27_194Z-debug-0.log
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 1


issue occurring for all node versions - 18 20 22

**Comment by rayudu-drivex** [comment]
> I had the same issue with dockerfile on step npm install
> 
> I have added `RUN npm config set registry https://registry.npmmirror.com/ --global` before `npm install`
> 
> it worked for me :)

its woking ...thanks

**Comment by divyansh-joshi** [comment]
cli command: **npx create-react-app new-app**   

Creating a new React app in /Users/divyanshjoshi/Desktop/new-app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...

**npm error code TAR_BAD_ARCHIVE**
npm error TAR_BAD_ARCHIVE: Unrecognized archive format
npm error A complete log of this run can be found in: /Users/divyanshjoshi/.npm/_logs/2024-12-17T12_12_39_061Z-debug-0.log

Facing similar issue, kindly suggest. Tried changing Wifis but still not working. 

https://registry.npmmirror.com/ doesnot seem to be a reliable site.

**Comment by Adheesh1107** [comment]
> @manjeet8562
> 
> ```
>      ↳   I have added RUN npm config set registry https://registry.npmmirror.com/ --global before npm install
> ```
> 
> Thank you, it worked for me as well!

Yup, this resolved the blocker. Thanks!

**Comment by ZotaNexTech** [comment]
its not working for me 
![image](https://github.com/user-attachments/assets/9eda92bb-92d6-47e0-87d2-bac2909cb4a5)
root@zotac31870:~# npm config set registry https://registry.npmmirror.com/ --global
root@zotac31870:~# cd zota-cpos-backend-ts/
root@zotac31870:~/zota-cpos-backend-ts# npm i
npm WARN tar TAR_BAD_ARCHIVE: Unrecognized archive format
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated npmlog@5.0.1: This package is no longer supported.
npm WARN deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated are-we-there-yet@2.0.0: This package is no longer supported.
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated gauge@3.0.2: This package is no longer supported.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated fstream@1.0.12: This package is no longer supported.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code TAR_BAD_ARCHIVE
npm ERR! TAR_BAD_ARCHIVE: Unrecognized archive format

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-12-17T12_41_32_476Z-debug-0.log
root@zotac31870:~/zota-cpos-backend-ts#

**Comment by ganeshthirumani-wavemaker** [comment]
> > @manjeet8562
> > ```
> >      ↳   I have added RUN npm config set registry https://registry.npmmirror.com/ --global before npm install
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thank you, it worked for me as well!
> 
> Yup, this resolved the blocker. Thanks!

how to add auth token for npm publish?
npm config set //replicate.npmjs.com/:_authToken "12345677777777777777777777", 

this not working, 
the token is one that used in npmjs.org

**Comment by jainamsMagneto** [comment]
how can i publish private package in npmmirror and get package

**Comment by dharaniakitra** [comment]
> > @manjeet8562
> > ```
> >      ↳   I have added RUN npm config set registry https://registry.npmmirror.com/ --global before npm install
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thank you, it worked for me as well!
> 
> Yup, this resolved the blocker. Thanks!

With this also its failing. 

18:44:03  #10 47.78 npm error code ECONNRESET
18:44:03  #10 47.78 npm error network aborted
18:44:03  #10 47.78 npm error network This is a problem related to network connectivity.

**Comment by aryanjagarwal** [comment]
npm WARN tar TAR_BAD_ARCHIVE: Unrecognized archive format
npm ERR! code TAR_BAD_ARCHIVE
npm ERR! TAR_BAD_ARCHIVE: Unrecognized archive format


still getting error after switching to another network

**Comment by harshadprajapati17** [comment]
Any update on this?

**Comment by dharaniakitra** [comment]
> Any update on this?

Now its working with this
     ↳   I have added RUN npm config set registry https://registry.npmmirror.com/ --global before npm install

**Comment by thoilemba** [comment]
For me, it worked when using VPN.
The error for me is "304 https://registry.npmjs.org/cssesc/-/cssesc-3.0.0.tgz 1607ms". You can check it in the log file.
The error occurred because the network connection was likely causing issues while downloading the cssesc package from the npm registry.
Or try using the npmmirror: `npm config set registry https://registry.npmmirror.com`

**Comment by duhbhavesh** [comment]
Using VPN worked for me.

https://status.npmjs.org/
![Screenshot 2024-12-17 at 7 42 34 PM](https://github.com/user-attachments/assets/f75bb279-d02f-4a70-a5b8-3e0ba6beb6e8)

**Comment by Abdullahxz** [comment]
They fixed the issue.

https://status.npmjs.org/incidents/bxvmmvlqzfds

**Comment by ayushsshukla** [comment]
I still am facing the issue?
Have cleant the cache. Anyone else?

**Comment by pavanpra** [comment]
It's fixed for me.

**Comment by Adinarayana142** [comment]
npm install failing, any one facing this today

**Comment by dharaniakitra** [comment]
No its working

**Comment by Suhan38** [comment]
anyone facing same issue today

**Comment by atpznn** [comment]
@Suhan38 
Me facing this problem
my local machine and  gitlab ci can't install package and show 

npm ERR! code TAR_BAD_ARCHIVE
npm ERR! TAR_BAD_ARCHIVE: Unrecognized archive format

npm ERR! A complete log of this run can be found in:
npm ERR! xxxxxxxx

**Comment by atpznn** [comment]
to others facing this problem
in my case i use my internal library in gitlab 
npm i failed because some version is error maybe build error and your project called this error version 

i go to delete my registry package in gitlab project and delete all error version 
after i deleted all . i cleaned cache and install again with specific version example npm install @xxx/xxx@1.2.3 
and it worked now i solved 

maybe some case you facing about TAR_BAD_ARCHIVE 
some dependencies on your project has error 

good luck!!

**Comment by AndreiDiaconovici** [comment]
Having the same issue, both on local and on GitLab CI

**Comment by Suhan38** [comment]
any solution for this anyone

**Comment by AndreiDiaconovici** [comment]
@Suhan38 for some reason, changing the domain inside the package.json did the trick. Someone from my team found the lucky change, not sure what is happening. I am starting to think is something related to GitLab managing the packages.

Example of working package:
"@package/core-types": "git+ssh://git@GitLab.com/<our-group>/core-types.git#v1.0.0",

GitLab.com must be camel case for the lucky reason.

Example of how I had it before:
"@package/core-types": "gitlab:<our-group>/core-types#v1.0.0",

I hope it helps

**Comment by Suhan38** [comment]
did they fix it i am getting error in deployment again friday i have changed the spelling and deployed @AndreiDiaconovici

**Comment by AndreiDiaconovici** [comment]
@Suhan38 looks like the issue is still present https://gitlab.com/gitlab-org/gitlab/-/work_items/595699
