### ISSUE TITLE
[BUG] `npm ls --all --omit=dev` includes dev dependencies of dependencies

### ISSUE THREAD

**Issue by hybridherbst** [npm/cli#7895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Potentially related:
- https://github.com/npm/cli/issues/3382

When using the --omit=dev flag, my expectation is that _all_ dev dependencies are excluded. However, what seems to happen is that only the dev dependencies of the root package are excluded – dev dependencies of local dependency packages are still included. This is unexpected.

### Expected Behavior

All devDependencies should be omitted when --omit=dev is used. Not just the devDependencies from the root package.

### Steps To Reproduce

1. Go to https://stackblitz.com/edit/vitejs-vite-jsxtyx?file=packages%2Fmy-package%2Fpackage.json&terminal=dev
2. Run `npm ls --all --omit=dev`
3. Note that `typescript`, a devDependency of a child package, is included in the list but shouldn't

Output:
```
❯ npm ls --all --omit=dev
vite-starter@0.0.0 /home/projects/vitejs-vite-jsxtyx
`-- my-package@1.0.0 -> ./packages/my-package
  `-- typescript@5.6.3
```

package.json of my-package:
```json
{
  "name": "my-package",
  "version": "1.0.0",
  "displayName": "My Package",
  "devDependencies": {
    "typescript": "^5.6.3"
  }
}
```

### Environment

- npm: 10.8.2
- Node.js: v20.9.0
- OS Name: MacOS 15.1
- System Model Name: Macbook Pro
- npm config:
```ini
; "user" config from /Users/herbst/.npmrc
registry = "https://registry.npmjs.org"
; node bin location = /usr/local/bin/node
; node version = v20.9.0
; npm local prefix = /Users/herbst/git/...../js/package~
; npm version = 10.8.2
; cwd = /Users/herbst/git/....../js/package~
; HOME = /Users/herbst
; Run `npm config ls -l` to show all defaults.
```

**Comment by kchindam-infy** [comment]
@hybridherbst  --omit=dev will not install dev dependencies on the file system but the dependencies will be still resolved. (Documentation [npm ci --omit=dev](https://docs.npmjs.com/cli/v10/commands/npm-ci#omit) )

**Comment by hybridherbst** [comment]
@kchindam-infy the issue I opened is about the behaviour of `npm ls`, not about installation of dependencies. `npm ls` lists the existing dependencies of a package tree, and currently incorrectly only omits the devDependencies of the root package. The devDependencies of local dependencies are included despite `--omit=dev`, which I think is a bug.

**Comment by wraithgar** [comment]
This is not a bug, it's a side effect of using linked dependencies.  Normally the dev dependencies of your packages are not installed, so anything in the tree that exists under one of your `dependencies` is also a `dependency`.

Because you've linked in a package, that assumption breaks.  This is just a side effect of using linked deps and it is not something we plan on changing.

**Comment by hybridherbst** [comment]
I think this is very misleading, and there is no workaround to this bug.

If `ls --all --omit=dev` does not actually omit dev dependencies I'm not sure how this can be anything else but a bug. 
Would I run `ls --all --omit=dev` in the linked dependency, it would _exclude_ aka omit the dev dependencies. Just because I run it in the root package it does not omit the dev dependencies. Why would --omit=dev not also exclude the dev dependencies of linked packages?

**Comment by RedCMD** [comment]
> Normally the dev dependencies of your packages are not installed

@wraithgar 
what are you talking about?
why are you saying to not install `devDependencies`?
you need `devDependencies` if you are ***dev***eloping a package
`npm i` will install all dependencies, including `devDependencies`

> that exists under one of your dependencies is also a dependency

again we are talking about `devDependencies`; not `dependencies`

and when we want to publish or include said package somewhere else
we don't want the devDependencies
and thus `npm ls --all --omit=dev` should work in ***omit***ting the ***dev***Dependencies

please reopen this and fix the bug thanks

**Comment by RedCMD** [comment]
@kchindam-infy why did you link `npm ci`?
what does that have to do with this bug report?
> Documentation [npm ci --omit=dev](https://docs.npmjs.com/cli/v10/commands/npm-ci#omit)
