### ISSUE TITLE
[DOCS] Clarify Requirements and Installation section

### ISSUE THREAD

**Issue by GervaseFT** [npm/cli#7913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Enhancement, not another kind of Docs Enhancement.

- [X] This is a CLI Docs Enhancement.

### Description of Problem

README.md is displayed when going to "https://github.com/npm/cli".

Currently, README.md is the following:

> ### Requirements
> 
> One of the following versions of [Node.js](https://nodejs.org/en/download/) must be installed to run npm:
> 
>     18.x.x >= 18.17.0
>     20.5.0 or higher
> 
> ### Installation
> npm comes bundled with [node](https://nodejs.org/), & most third-party distributions, by default.
> 

This confused me because according to the Requirements section, I thought I needed to pre-install 'Node.js'.  But, according to the Installation section, it gets automatically installed when I install 'npm'.

Is it possible to make the wording clearer?

### Potential Solution

I had to search around a little to find the following comment from "https://stackoverflow.com/a/25232555":

> Only node.js [installation] packages comes with npm. so if you are installing using an .msi, .exe, .dmg .pkg, .deb or using a package installer like apt-get, yum or brew, then you'll have both node and npm.
> 
> However,npm is not part of the node core. if you are installing node and using a method where you are using ./configure or make install || make link, then npm will not be installed

Would it be OK to have something similar to the above be put into the "README.md"?

If the above stackoverflow.com comment were in "README.md", it would have saved about 30 minutes of my time.

### Docs URL

https://github.com/npm/cli/blob/latest/README.md

**Comment by GervaseFT** [comment]
I just followed the below instruction on MacOS...

`curl -qL https://www.npmjs.com/install.sh | sh`

...and got...

`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3755  100  3755    0     0   4671      0 --:--:-- --:--:-- --:--:--  4705
npm cannot be installed without node.js.
install node first, and then try again.`

It would be nice to add to the clarification that "install.sh" is not an installation package.  Though really I suppose I should have known...

**Comment by Idiakeosemoahu** [comment]
@osemoahu idiake

**Comment by Idiakeosemoahu** [comment]
###
![FB_IMG_1731517582292](https://github.com/user-attachments/assets/eb79f28e-e15b-4b66-8be2-64cfafde7934)

**Comment by Idiakeosemoahu** [comment]
Me

**Comment by milaninfy** [comment]
As clearly mentioned in readme that you need to have node.js installed, yes npm comes with node js by default but for some reasons e.g. by user action or some side effects if it's not accessible or removed then the direct download script will help reinstall npm. This doesn't seem to be issue with docs.
