### ISSUE TITLE
Help with diskusage

### ISSUE THREAD

**Issue by MHS5706** [npm/cli#7914]
currently, i cant install Diskusage.node, and i cant open unity hub cuz of it.
Idk what to do
[2024-11-15T13_27_55_740Z-debug-0.log](https://github.com/user-attachments/files/17776196/2024-11-15T13_27_55_740Z-debug-0.log)

**Comment by milaninfy** [comment]
**Closing:** please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).
