### ISSUE TITLE
[BUG] Release v9.9.4 is marked as latest

### ISSUE THREAD

**Issue by harryzcy** [npm/cli#7935]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

The release v9.9.4 is marked as latest.

### Expected Behavior

[v10.9.1](https://github.com/npm/cli/releases/tag/v10.9.1) should be the latest version

### Steps To Reproduce

See `latest` label:
<img width="1163" alt="image" src="https://github.com/user-attachments/assets/3f1ea1df-ab45-4dda-94d7-fcf5048eb8ed">

**Comment by kchindam-infy** [comment]
@harryzcy  I can see the correct tag for the latest on npm cli. I dont see an issue, hence closing it. If you still find an issue with tag feel free to reopen the ticket. 
<img width="1521" alt="Screenshot 2024-11-25 at 10 49 36 AM" src="https://github.com/user-attachments/assets/56c9c1d0-ca0d-4531-ab87-bf43a8f02a17">
