### ISSUE TITLE
[BUG] unable to install any package on m1 mac

### ISSUE THREAD

**Issue by scarf005** [npm/cli#7936]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

i'm unable to install any packages.

### Expected Behavior

npm works.

### Steps To Reproduce

1. run `npm install -g pnpm`
```
nemo@ip-192-168-20-209 ~/r/quotabook-frontend (feat/security-sign-fixes) [SIGABRT]> npm install -g pnpm
(node:17357) ExperimentalWarning: CommonJS module /opt/homebrew/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /opt/homebrew/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
⠙dyld[17357]: missing symbol called
fish: Job 1, 'npm install -g pnpm' terminated by signal SIGABRT (Abort)
```

### Environment

- npm: 10.9.0
- Node.js: v23.3.0
- OS Name: macOS Sequoia 15.1.1 arm64
- System Model Name: MacBook Pro
- npm config:
```ini
; "builtin" config from /opt/homebrew/lib/node_modules/npm/npmrc

prefix = "/opt/homebrew"

; node bin location = /opt/homebrew/Cellar/node/23.3.0/bin/node
; node version = v23.3.0
; npm local prefix = /Users/nemo/repo/quotabook-frontend
; npm version = 10.9.0
; cwd = /Users/nemo/repo/quotabook-frontend
; HOME = /Users/nemo
; Run `npm config ls -l` to show all defaults.
```

**Comment by kchindam-infy** [comment]
@scarf005  I tried it on my mac and i was able to install pnpm without an issue 

kchindam-infy@kalyankumars-MacBook-Pro test % uname -m                 
arm64
kchindam-infy@kalyankumars-MacBook-Pro test % node -v
v23.3.0
kchindam-infy@kalyankumars-MacBook-Pro test % npm -v
10.9.1
kchindam-infy@kalyankumars-MacBook-Pro test % npm install -g pnpm      
(node:75398) ExperimentalWarning: CommonJS module /Users/kchindam-infy/.nvm/versions/node/v23.3.0/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /Users/kchindam-infy/.nvm/versions/node/v23.3.0/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

added 1 package in 979ms

1 package is looking for funding
  run `npm fund` for details

**Comment by kchindam-infy** [comment]
Closing the issue due to inactivity, feel free to reopen if you still need assistance or you think this is a an issue.
