### ISSUE TITLE
[BUG] npx but use version in package.json

### ISSUE THREAD

**Issue by apoorva-sriv** [npm/cli#7946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Could you please confirm whether https://stackoverflow.com/questions/67319671/npx-but-use-version-in-package-json has been implemented in the latest version of `npx`?

**Comment by milaninfy** [comment]
**Closing:** this looks to be a general support question which is outside the scope of the repo. For support please post your question to [github.community](https://github.community).
