### ISSUE TITLE
[BUG] NPM Doesn't allow me to install any package. '<package>' is not in this registry.

### ISSUE THREAD

**Issue by SolindekDev** [npm/cli#7964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When I try to install any existing npm package i get this crazy error

```
bruno@MacBook-Air-Bruno project % npm install     
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/@eslint%2feslintrc - Not found
npm error 404
npm error 404  '@eslint/eslintrc@3.1.0' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
npm error A complete log of this run can be found in: /Users/bruno/.npm/_logs/2024-12-08T18_52_10_967Z-debug-0.log
```

### Expected Behavior

It should install me my package...

### Steps To Reproduce

```npm install <any package```

Output
```
bruno@MacBook-Air-Bruno project % npm install     
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/@eslint%2feslintrc - Not found
npm error 404
npm error 404  '@eslint/eslintrc@3.1.0' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
npm error A complete log of this run can be found in: /Users/bruno/.npm/_logs/2024-12-08T18_52_10_967Z-debug-0.log
```

### Environment

- npm: 10.9.0
- Node.js: 22.12.0
- OS Name: MacOS Sequoia 15.2
- npm config:
```ini
; "user" config from /Users/bruno/.npmrc

registry = "https://registry.npmjs.org/"

; node bin location = /Users/bruno/.nvm/versions/node/v22.12.0/bin/node
; node version = v22.12.0
; npm local prefix = /Users/bruno/Documents/Programming/project
; npm version = 10.9.0
; cwd = /Users/bruno/Documents/Programming/project
; HOME = /Users/bruno
; Run `npm config ls -l` to show all defaults.
```

**Comment by SolindekDev** [comment]
I don't have an absolute idea what happend i just decided to try `sudo npm install` and it suddenly worked..

**Comment by robert-westenberger** [comment]
probably due to scheduled maintenance
https://status.npmjs.org/

**Comment by SolindekDev** [comment]
> probably due to scheduled maintenance https://status.npmjs.org/

oh that's probably why everything didn't worked.. that makes a lot of sense now

**Comment by Slauh** [comment]
yea  some npm pages give a 404 now although on the 404 page you can search the name of the package and click it and it goes back to normal? you might be able to download it when you do that not to certain though



seems to be maintenance https://status.npmjs.org/

> Package installation Under Maintenance
