### ISSUE TITLE
[DOCS] Why isn't there the section for `type` property in the package.json page?

### ISSUE THREAD

**Issue by rinarakaki** [npm/cli#7965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Problem, not another kind of Docs Problem.

- [X] This is a CLI Docs Problem.

### Description of Problem

Setting `type` as `module` or `commonjs` is a common practice and I thought it should be described in the 'package-json' page https://docs.npmjs.com/cli/v10/configuring-npm/package-json.

**Comment by milaninfy** [comment]
@rinarakaki  Thank you for this report. We already have an open PRs to add this in the documentation also there is a similer issue associated with that PRs (https://github.com/npm/cli/pull/7897, https://github.com/npm/cli/pull/7962) at https://github.com/npm/documentation/issues/1204. In order for not to track the issue at multiple places I'll close this as duplicate.
