### ISSUE TITLE
After NPM publish it shows : This package does not have a README

### ISSUE THREAD

**Issue by sanjayc208** [npm/cli#7966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I have published my npm package and it was working all good till yesterday but now it shows . This package does not have README , but i do have READEM file if you check .

npm published package :- https://www.npmjs.com/package/react-fox-toast

### Expected Behavior

It should have shown README after NPM publish

### Steps To Reproduce

Just go to this link and you will issue saying ADD Readme but there is README in my code https://www.npmjs.com/package/react-fox-toast

### Environment

- npm: 10.9.0

**Comment by milaninfy** [comment]
**Closing:** this looks to be an issue with the registry which is outside the scope of this repo. For registry support please go to [npmjs.com/support](https://www.npmjs.com/support). If you believe this is a bug with the cli, please provide further clarifying details.
