### ISSUE TITLE
[BUG] error-ex is not in the npm registry in the Asia/Pacific (SIN) region

### ISSUE THREAD

**Issue by shazron** [npm/cli#797]
# What / Why

error-ex is not in the npm registry.
It does exist: 
https://www.npmjs.com/package/error-ex

## When

today (see timestamp)
I'm connecting from Singapore.

## Where
  * npm public registry

## How

npm info error-ex

### Current Behavior
 404 package not found

### Steps to Reproduce
```
git clone https://github.com/sindresorhus/parse-json.git
cd parse-json
npm install
```

### Expected Behavior
* error-ex package found

## Who
  * @npm/<team>

## Log
```
$ npm info error-ex
npm ERR! code E404
npm ERR! 404 'error-ex' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! 404
npm ERR! 404  'error-ex@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by shazron** [comment]
My colleague in Vancouver, Canada, cannot repro this issue, and when I VPN to San Jose, California, I cannot repro this issue as well. Thus I believe it might be a regional issue, whichever mirror that I'm connecting to in Singapore.

**Comment by shazron** [comment]
Checked https://status.npmjs.org/, looks like I might be in the Asia/Pacific (SIN) region

**Comment by ahmadnassri** [comment]
thank you for reporting this @shazron since this repo is for the CLI OSS project, please send any registry issues to support@npmjs.com

**Comment by jcugmas** [comment]
The problem is still persisting on my side, I'm located in France btw.

> pm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/error-ex
npm ERR! 404 
npm ERR! 404  'error-ex@^1.3.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'parse-json'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by prabathgem** [comment]
Even though ticket is closed ,the  issue still  exists

**Comment by nomadtechie** [comment]
Hi all - we're very sorry about the `404`'s you are experiencing. 

We have identified the issue on our end and rolled out the fix. Unfortunately, its going take some time to propagate through all our nodes in our CDN layer.

You can follow along for progress via the [incident on our status page](https://status.npmjs.org/incidents/lvgmcrfvrvsh)

Also, you if you have other packages affected then please feel free to [contact our support team directly.](https://www.npmjs.com/support)
