### ISSUE TITLE
If there a workaround for a dual package-lock files in in one root

### ISSUE THREAD

**Issue by Cecil0o0** [npm/cli#7975]
I meet a rare case, in my project, I have to handle with very unstable dependencies for a long time which could be one year or more, and I know it sounds like wired, so I want to get a shot for just workaround for this case.

I own more than two webpages for more than two user interface, and those are independent to install before build for strongly various reason, it means that those webpages built with totally different dependencies.

Is there any workaround or some ideas for that?

If not, I could do it in a terrible way which is wrapping some disgust logic in my project...

**Comment by milaninfy** [comment]
`package-lock` represents `node_module` and exact version of dependencies installed... I don't see a feasible case when there are needs for multiple package-lock at same level

**Closing:** this looks to be a general support question which is outside the scope of the repo. For support please post your question to [github.community](https://github.community).

**Comment by ljharb** [comment]
I'd go further to say that if you have two sets of deps, you actually have two separate projects.

**Comment by Cecil0o0** [comment]
Thanks for your closing guidance and your identify in this conversation!
