### ISSUE TITLE
Error when I run npm install Error: 404 Not Found: 7zip-bin@~4.1.0

### ISSUE THREAD

**Issue by karthik22061993** [npm/cli#798]
When I run npm install I see this error
```
3 verbose stack Error: 404 Not Found: 7zip-bin@~4.1.0
2293 verbose stack     at fetch.then.res (C:\cygwin64\home\licbuild\ANSYSDev\LicensingPortal\node\node-v8.12.0-win-x64\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
2293 verbose stack     at tryCatcher (C:\cygwin64\home\licbuild\ANSYSDev\LicensingPortal\node\node-v8.12.0-win-x64\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
2293 verbose stack     at Promise._settlePromiseFromHandler (C:\cygwin64\home\licbuild\ANSYSDev\LicensingPortal\node\node-v8.12.0-win-x64\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
2293 verbose stack     at Promise._settlePromise (C:\cygwin64\home\licbuild\ANSYSDev\LicensingPortal\node\node-v8.12.0-win-x64\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
2293 verbose stack     at Promise._settlePromise0 (C:\cygwin64\home\licbuild\ANSYSDev\LicensingPortal\node\node-v8.12.0-win-x64\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
2293 verbose stack     at Promise._settlePromises (C:\cygwin64\home\licbuild\ANSYSDev\LicensingPortal\node\node-v8.12.0-win-x64\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
2293 verbose stack     at Async._drainQueue (C:\cygwin64\home\licbuild\ANSYSDev\LicensingPortal\node\node-v8.12.0-win-x64\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
2293 verbose stack     at Async._drainQueues (C:\cygwin64\home\licbuild\ANSYSDev\LicensingPortal\node\node-v8.12.0-win-x64\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
2293 verbose stack     at Immediate.Async.drainQueues (C:\cygwin64\home\licbuild\ANSYSDev\LicensingPortal\node\node-v8.12.0-win-x64\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
2293 verbose stack     at runCallback (timers.js:810:20)
2293 verbose stack     at tryOnImmediate (timers.js:768:5)
2293 verbose stack     at processImmediate [as _immediateCallback] (timers.js:745:5)
```
As workaround I tried

npm i 7zip-bin@4.1.0, this didn't solve this issue
npm install https://npmjs.org/7zip-bin/v/4.1.0
This is npm repo for this package enter link description here

Has anyone seen this kind of error before? Any suggestion will really be appreciated, thank you :)

**Comment by EricGeigerQ** [comment]
This appears to be an issue with yarn, as reported on issue [7902](https://github.com/yarnpkg/yarn/issues/7902). However, it's still occurring even though it was reported over 15 hours ago.

**Comment by florent-souliere-smile** [comment]
I just got the same error on https://registry.npmjs.org/error-ex/-/error-ex-1.3.2.tgz less than 3 hours ago. And I am sure the package was downloadable during the last 2 hours before that incident.

**Comment by karthik22061993** [comment]
Hi EricGeigerQ I don't use yarn, I use npm.  when is this expected to be fixed and does anyone throw more light on cause of this issue

**Comment by nomadtechie** [comment]
We're very sorry about the 404's you are experiencing. I'm going to close this issue it not related to a problem in the npm cli.

We have identified the issue on our end and rolled out the fix in the npm registry. Unfortunately, its going take some time to propagate through all our nodes in our CDN layer.

You can follow along for progress via the [incident on our status page](https://status.npmjs.org/incidents/lvgmcrfvrvsh)

Also, you if you have other packages affected then please feel free to [contact our support team directly.](https://www.npmjs.com/support)

**Comment by karthik22061993** [comment]
Hi Everyone I am seeing new issue when I run npm install ,though previous error doesn't appear

> > node-pty@0.9.0 install C:\agent\_work\1\s\clientsettings\node_modules\node-pty
> node scripts/install.js

internal/child_process.js:313
    throw errnoException(err, 'spawn');
    ^

Error: spawn EPERM
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:503:9)
    at Object.<anonymous> (C:\agent\_work\1\s\clientsettings\node_modules\node-pty\scripts\install.js:11:20)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
