### ISSUE TITLE
Add an option to manage the npm version specified in devEngines

### ISSUE THREAD

**Issue by trivikr** [npm/cli#8003]
### Is your feature request related to a problem? Please describe.

User needs to manually install the npm version specified in devEngines.

Install node version which contains `npm@>10.9.0`
The below example uses [nvm](https://github.com/nvm-sh/nvm) to use `node@23.5.0` which contains `npm@10.8.2`
```console
$ nvm install 23.5.0                                    
Downloading and installing node v23.5.0...
Downloading https://nodejs.org/dist/v23.5.0/node-v23.5.0-darwin-arm64.tar.xz...
###################################################################################################################################################################################### 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v23.5.0 (npm v10.9.2)
```

Create a package.json which states `devEngines` configuration for `npm@10.9.0`.
In real-life projects, this might have happened if developer used Node.js version which `npm@10.9.0`, like `node@22.12.0`
```console
$ test-devEngines> echo '{ "name": "test-devEngines", "version": "0.0.1", "devEngines": { "packageManager": { "name": "npm", "version": "10.9.0", "onFail": "error" } } }' > package.json
```

npm install fails as the npm version is different from what's specified in the repo
```console
$ test-devEngines> npm install
npm error code EBADDEVENGINES
npm error EBADDEVENGINES The developer of this package has specified the following through devEngines
npm error EBADDEVENGINES Invalid engine "packageManager"
npm error EBADDEVENGINES Invalid semver version "10.9.0" does not match "10.9.2" for "packageManager"
npm error EBADDEVENGINES {
npm error EBADDEVENGINES   current: { name: 'npm', version: '10.9.2' },
npm error EBADDEVENGINES   required: { name: 'npm', version: '10.9.0', onFail: 'error' }
npm error EBADDEVENGINES }
```

Developer has to globally install the requested npm version
```console
$ npm install -g npm@10.9.0
```

### Describe the solution you'd like

Ask runner if they want to install the version mentioned in `devEngines` and install it - like it's done by [corepack](https://github.com/nodejs/corepack)

```console
$ test-corepack> corepack enable

$ test-corepack> echo '{ "name": "test-corepack", "version": "0.0.1", "packageManager": "yarn@4.6.0" }' > package.json

$ test-corepack> yarn
! Corepack is about to download https://repo.yarnpkg.com/4.6.0/packages/yarnpkg-cli/bin/yarn.js
? Do you want to continue? [Y/n] Y
```

In CI environments, corepack automatically downloads the package manager defined in devEngines field.

### Describe alternatives you've considered
Switch to alternative package manager (like yarn or pnpm) which either manages the version through corepack or self-manages its version.

**Comment by trivikr** [comment]
The equivalent in npm may look like

```console
$ test-devEngines> npm install
! The developer of this package has specified npm@10.9.0, while the current version is npm@10.9.2
? Do you want to download and switch to npm@10.9.0? [Y/n]
```

**Comment by ljharb** [comment]
A prompt is tricky, because npm isn't usually used on a tty. `npm init` and `npm publish` and `npx`, i think, are the only exceptions.

**Comment by trivikr** [comment]
What would be a good alternative to ensure npm version specified in `devEngines` is downloaded smoothly without manual intervention?

**Comment by ljharb** [comment]
The simplest alternative is to not automate any downloading at all - rather, create a config option ("strict" or something) that causes npm to fail when devEngines is not satisfied.

**Comment by trivikr** [comment]
I just noticed that the behavior of npm mentioned in this report is accurate as per specification for `onFail`. It prints error and exits.

However, it doesn't download the package manager version when `onFail=download`
I've created a bug report for it at https://github.com/npm/cli/issues/8004

**Comment by ljharb** [comment]
That was by design; npm chose not to implement `download` because it's a security concern.
