### ISSUE TITLE
[BUG] `npm run` doesn't parse glob pattern file path correctly

### ISSUE THREAD

**Issue by yq314** [npm/cli#801]
# What / Why

When the script is executed by `npm run`, it parses glob pattern incorrectly. But if I run the command directly the glob pattern file path is parsed correctly. See examples below.

## When

For example, I have a project in the below structure:
- src/a/b/classB.js
- src/a/classA.js
- src/a/b/c/classC.js
- src/index.js

And a `test.js` that simply does this `console.log(process.argv);`

In package.json I have 
```
"scripts": {
     "test": "node test.js src/**/*.js"
 }
```

## Where

Now if I run `npm run test`

### Current Behavior

I get this output:

```
[
  '/Users/qingye/.nvm/versions/node/v12.14.0/bin/node',
  '/Users/qingye/dev/test_npm/test.js',
  'src/a/classA.js'
]
```

### Steps to Reproduce

* n/a

### Expected Behavior

But if I run `node test.js src/**/*.js` directly I get this:

```
[
  '/Users/qingye/.nvm/versions/node/v12.14.0/bin/node',
  '/Users/qingye/dev/test_npm/test.js',
  'src/a/b/c/classC.js',
  'src/a/b/classB.js',
  'src/a/classA.js',
  'src/index.js'
]
```

## Who

* npm version 6.13.4
* node version v12.14.0

## References

* n/a

**Comment by ljharb** [comment]
Globs have to be quoted to prevent the shell from expanding them.

**Comment by yq314** [comment]
> Globs have to be quoted to prevent the shell from expanding them.

I actually expect it to be expanded as I want to pass in a list of files, but it just works differently with and without npm. Is this expected?

**Comment by ljharb** [comment]
It will work differently in different shells unless it’s quoted. npm run might be using a shell that’s different from your login shell.

**Comment by yq314** [comment]
> It will work differently in different shells unless it’s quoted. npm run might be using a shell that’s different from your login shell.

ah that makes sense, I'll close this issue. Thank you for your prompt help!
