### ISSUE TITLE
[BUG] ERR 404 error-inject Not Found

### ISSUE THREAD

**Issue by annelorraineuy** [npm/cli#803]
# What / Why
`error-inject@^1.0.0` is a dependency in one of our packages. It exists on the registry as per https://www.npmjs.com/package/error-inject but when trying to `npm i` I am getting the 404 error not found. 

## When
* noticed this just today, Feb 12 around 12PM Mountain Time.
* thought this might have been related to the recent 404 issue, but this looks to be resolved and I still get the 404 issue - https://status.npmjs.org/incidents/lvgmcrfvrvsh

## Where
Currently https://registry.npmjs.org/error-inject returns 404 page

### Current Behavior
Running `npm install error-inject` returns:

```
npm ERR! code E404
npm ERR! 404 Not Found: error-inject@^1.0.0
```

### Steps to Reproduce
`npm install error-inject`

### Expected Behavior
Installs error-inject successfully, since it exists based on https://www.npmjs.com/package/error-inject

## Who
* n/a

## References
Possibly related to https://status.npmjs.org/incidents/lvgmcrfvrvsh

**Comment by annelorraineuy** [comment]
Update from NPM: https://status.npmjs.org/incidents/00tlqc4fzj14

> We are investigating a separate issue where some users are noticing 404's, and we're noticing different results depending on location.
> 
> It seems like this occurs on packages with `error` in their name, and it is likely something to do with our Content Delivery Network.
> 
> Thank you for your patience while we investigate further.

**Comment by DanielRuf** [comment]
I guess this issue can be closed.
