### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by TheUncas** [npm/cli#804]
Hello, i'm just creating this issue to inform that the problem is not solved : 

```
PS ... > yarn add error-ex
yarn add v1.22.0
info No lockfile found.
[1/4] Resolving packages...
error Couldn't find package "error-stack-parser" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Error: Couldn't find package "error-ex" on the "npm" registry.
    at MessageError.ExtendableBuiltin (C:\Program Files (x86)\Yarn\lib\cli.js:721:66)
    at new MessageError (C:\Program Files (x86)\Yarn\lib\cli.js:750:123)
    at NpmResolver.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:50302:15)
    at Generator.next (<anonymous>)
    at step (C:\Program Files (x86)\Yarn\lib\cli.js:310:30)
    at C:\Program Files (x86)\Yarn\lib\cli.js:321:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by jcodlingcc** [comment]
Also this:
```
npm ERR! code E404
npm ERR! 404 Not Found: errorhandler@^1.5.0
```

And if you go to [https://registry.npmjs.org/errorhandler](https://registry.npmjs.org/errorhandler) that's a 404.

If your CND is still having errors the issue is not resolved.

**Comment by dhewer** [comment]
Not solved here (Toronto) either. Can't install due to "error-ex"

**Comment by andrewwiebe** [comment]
Also in Toronto and errorhandler still throwing 404.

npm ERR! code E404
npm ERR! 404 Not Found: errorhandler@^1.5.1

**Comment by TheUncas** [comment]
stil same error, check this for real time resolution : https://registry.npmjs.org/error-ex
;)

**Comment by awran5** [comment]
Here is a workaround solution:

https://github.com/facebook/create-react-app/issues/8465#issuecomment-585427049

**Comment by jcodlingcc** [comment]
No work around needed. It's fixed for me.

**Comment by DanielRuf** [comment]
It was probably not yet propagated. There may have been issues with the registry.

https://registry.npmjs.org/errorhandler and https://registry.npmjs.org/error-ex work

This issue can be closed.
