### ISSUE TITLE
[QUESTION] <title>sgmf-scripts' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by FaizenR** [npm/cli#806]
# What / Why

> n/a

## Where

* n/a

## Who

* n/a

## References

* n/a

**Comment by FaizenR** [comment]
sgmf-scripts' is not recognized as an internal or external command,
operable program or batch file.

**Comment by DanielRuf** [comment]
This is not a bug with npm. Please report this at Salesforce or whoever is responsible.

You might have installed the package locally but wanted to install it globally using `npm i -g sgmf-scripts`.

**Comment by surendra5** [comment]
Either install the sgmf-scripts globally using `-g` or while using them, give local reference to the directory in which they are installed. 
Example - 
`node node_modules/sgmf-scripts --createCartridge app_custom_mybrand
`
