### ISSUE TITLE
This is an error with npm itself. Please report this error

### ISSUE THREAD

**Issue by kumarvvin** [npm/cli#825]
# What / Why
error cb() never called!
10 error This is an error with npm itself. Please report this error at:
> n/a

## When

* n/a

## Where

* n/a

### Current Behavior

* n/a

### Steps to Reproduce

* n/a

### Expected Behavior

* n/a

## Who

* n/a

## References

* n/a

![npm install error](https://user-images.githubusercontent.com/35554498/74563092-9e892000-4f31-11ea-9193-0a2cf17cbb6f.png)

**Comment by DanielRuf** [comment]
Please try opening https://registry.npmjs.org/pm2 in your browser. There seems to be an issue.

**Comment by kumarvvin** [comment]
it worked. There was a proxy setting issue, even when we set the proxy it
was not downloading. after adding the domain before the username resolved
proxy and it was installed successfully.

if the error message in log shows issue with connecting to internet it will
be good instead of a generic message.

Regards
Vaibav

**Comment by DanielRuf** [comment]
Right. But I think this issue is resolved and can be closed.
