### ISSUE TITLE
[BUG] can you add "npm installed"

### ISSUE THREAD

**Issue by titoBouzout** [npm/cli#833]
# What / Why

> Because is very annoying having to google, copy paste and remember all this thing `npm list -g --depth=0` . Seems logical that you have `npm install` and `npm remove` to have `npm installed`. 

## When

* every time we need to check whats installed

## Where

* everywhere

### Current Behavior

* https://s.draw.uy/d8534bc937.png

### Steps to Reproduce

* type `npm installed`

### Expected Behavior

* to output the same as  `npm list (-g) --depth=0` 

## Who

* Like a lot of people https://stackoverflow.com/questions/17937960/how-to-list-npm-user-installed-packages

## References

* n/a

**Comment by DanielRuf** [comment]
> npm installed

This would need the global flag and more. All relevant npmjs clients use `ls` to list installed packages. You can create an alias in your .bashrc or similar.

Also this is not a bug but a feature request.
