### ISSUE TITLE
UTIF.js - 3.1.0 version issue

### ISSUE THREAD

**Issue by nischalashashidhar** [npm/cli#835]
# What / Why
The latest version of UTIF.js(3.1.0) is not appending width, height and data to the IFD when we use decodeImage i.e. UTIF.decodeImage(buffer, ifd). But the decodeImages(buffer, ifd) method of lower version(2.0.1) is working fine.

## When
I am trying to decode the Tiff image using an arrayBuffer of the same.

## Where
https://www.npmjs.com/package/utif

### Current Behavior
Use of UTIF.decodeImage(e.target.response, ifds[0]) is not adding height, width and data to the IFD.
But the 2.0.1 version works perfectly fine.

### Expected Behavior
Use of UTIF.decodeImage(e.target.response, ifds[0]) should add three new properties to the IFD.

## Who

* n/a

## References

* n/a

**Comment by DanielRuf** [comment]
This is not an error with npm. Please open the issue in the repo of the package and close this one here.

https://github.com/photopea/UTIF.js/issues
