### ISSUE TITLE
E429 npm ERR! 429 Too Many Requests - GET https://registry.npmjs.org/aws4[BUG]

### ISSUE THREAD

**Issue by nikiamnik** [npm/cli#837]
# What / Why
While installing npm packages 

## When
npm install request@latest
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code E429
npm ERR! 429 Too Many Requests - GET https://registry.npmjs.org/aws4

## Where
npm public registry

### Current Behavior
unable to install packages

### Steps to Reproduce
npm i request@latest

### Expected Behavior
module should install

## References
npm install request@latest
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code E429
npm ERR! 429 Too Many Requests - GET https://registry.npmjs.org/aws4

**Comment by janhocevar** [comment]
Confirmed.

```
npm ERR! code E429
npm ERR! 429 Too Many Requests - GET https://registry.npmjs.org/@types/webappsec-credential-management/-/webappsec-credential-management-0.5.1.tgz
```

**Comment by marphi** [comment]
The same issue.
```
npm ERR! code E429
npm ERR! 429 Too Many Requests - GET https://registry.npmjs.org/archy/-/archy-1.0.0.tgz
```

**Comment by Rohaq** [comment]
Duplicate of #836

**Comment by jphw** [comment]
Same here, "Too Many Requests" when trying to pull deps

**Comment by massi-ang** [comment]
I am getting Too Many Requests on several modules, which started 10-20min ago

**Comment by calmacroi** [comment]
same :-|, no matter if logged or not logged in

**Comment by ntnbrtnkv** [comment]
Why https://status.npmjs.org/ says everything is ok?

**Comment by nikiamnik** [comment]
> Why https://status.npmjs.org/ says everything is ok?

Because It's just an assumption page 💃

**Comment by nikiamnik** [comment]
They updated the status page
https://status.npmjs.org/

**Comment by MaxOlsson** [comment]
This should be closed as DUPLICATE - https://github.com/npm/cli/issues/836

**Comment by riker09** [comment]
The memes in #836 are waaaay better
