### ISSUE TITLE
[BUG?] Circular dep checker seems overly restrictive for dev dependencies

### ISSUE THREAD

**Issue by pygy** [npm/cli#839]
# What / Why

`ospec` is a testing library that up to this point ran its own tests. This is annoying because when you break the lib, you also break the test harness... So I'm in the process of adding `ospec` version N-1 as a dev dependency to `ospec` version N, and porting the test suite accordingly. 

`npm install -D` refused to let me do it without using `--force`. I understand why you need to be careful for plain deps, but this seems overly restrictive, since dev dependencies can't recurse.

## When / Where / How / etc...

* n/a

**Comment by ljharb** [comment]
Why can't dev deps recurse?

**Comment by pygy** [comment]
Here's my understanding of what happens, but maybe I'm wrong (given your reply, I suppose I am ;-)...

1) When you `npm install some-package`, it installs `some-package` and recursively does so for all its `dependencies`. The `devDependencies` are ignored. 

2) When you run `npm install` from a project it will do step 1) for both the `dependencies`, and the `devDependencies` in the `package.json`.

So, even if we assume a long chain of dev deps from version `N+1` to version `N`, if I run `npm install` from my repo at version `N+1` or in a dev branch, the buck will stop at version `N`, and packages who (dev-)depend on my lib will only one version of the package.

**Comment by ljharb** [comment]
I believe you can run `npm install --dev` at the top level, though, which recursively installs the dev deps of all your deps.

**Comment by pygy** [comment]
[From the look of it](https://github.com/npm/cli/blob/b829d62c98506325d2afb2d85d191a8ff1c49157/lib/install.js#L200-L239) `npm i --dev`, which is deprecated, is  semantically equivalent to `--only=dev`, the only difference is a matter of precedence and interactions with how the `prod` mode is set.

The [Web site says](https://docs.npmjs.com/cli/install):

> The --only={prod[uction]|dev[elopment]} argument will cause either only devDependencies or only non-devDependencies to be installed regardless of the NODE_ENV.

However, there can be problems if someone installs from the repo directly or from a directory, rather than from the registry, and if the package has a `prepare` script.

In that case, the `devDependencies` are installed in order to run `prepare`. I suppose there could be a cycle in that scenario if there are nested non-registry dependencies. Unlikely, but not impossible...
