### ISSUE TITLE
package.json with local dependency, npm audit command returns "ELOCKVERIFY ERROR"

### ISSUE THREAD

**Issue by ale-grosselle** [npm/cli#859]
# What / Why
I have a package.json with a local dependency, "file:libs/thron-ux-helpers".
After "npm install", i run "npm run audit" and after a few seconds, I obtain "code ELOCKVERIFY" 

![image](https://user-images.githubusercontent.com/6173088/74881459-a4d22e80-536d-11ea-9397-a8e19d1fd3cf.png)

## When
* n/a

## Where
  npm local dependency

### Current Behavior
Got error when run npm audit with a local dependecy

### Steps to Reproduce
- Add local dependency in your package.json
- npm install
- now npm audit

**Comment by CherryDT** [comment]
@darcyclarke Why was this closed? It still happens.

**Comment by kouhei** [comment]
https://npm.community/t/npm-audit-fails-to-audit-packages-with-a-local-dependency-in-npm-v6-9-0/6006.html
> removing the requires block from the package-lock.json file allows npm audit to run successfully.

this solution works. But it still hasn't reached a basic resolution.
