### ISSUE TITLE
[FEATURE] update node-gyp to 5.1 at the very least

### ISSUE THREAD

**Issue by Pomax** [npm/cli#927]
As Python 2.7 was finally abandoned on January 1st of this year and should no longer be a prerequisite for anything in the computing world (except maybe folks on macos, all of whom should have python3 installed anyway now that 2.7 is dead) it would be a good idea to bump the version of `node-gyp` to 5.1.0 or higher (see https://github.com/nodejs/node-gyp/issues/2052)

**Comment by Pomax** [comment]
Correction: a decisions was made [late December of last year](https://www.python.org/psf/press-release/pr20191220/) to push the date back to April first, 2020, so there's a few weeks left before Python 2.7 EOL yet. Of course, it would still be wise to uplift `node-gyp` before then.

**Comment by ljharb** [comment]
See #771, #287.

**Comment by Pomax** [comment]
perfect, closing as duplicate.

(hopefully the PRs won't go stale over travis not passing...)
