### ISSUE TITLE
[QUESTION] What IS the recommended way to update a whole project?

### ISSUE THREAD

**Issue by kristof-mattei** [npm/cli#944]
# What / Why
1) Assume project that has been started a long while back, with a large tree, what is the recommended way to update all packages, and their sub-packages, and so on?

2) There's a statement somewhere that doing this may break your project, but so can any update.  Or is there something else? https://github.com/npm/npm/issues/17111#issuecomment-307490551

3) Then there's the difference between doing `npm --depth 9999 update` and doing an `rm -rf node_modules ; rm package-lock.json`. 

    The first one takes forever, the second one generates a different `package-lock.json`, which is fine if it was just the order, but for a lot of packages it just pulls in NEWER versions that it wouldn't do when doing `npm --depth 9999 update`. 

https://blog.cloudflare.com/javascript-libraries-are-almost-never-updated/

There is a reason for that. `npm` is incredibly convoluted when it comes to updating packages. 

For example, to update a package one needs to use `npm update`, unless you want to either specify the version or do `latest`, then you have to use `npm install`.

To update all packages (within semver) one needs to use an arbitrary number `9999`... What does that mean? Is there code somewhere that's like: 

```
if (9999 === depth) {
    activateEndlessMode();
}
```

Or will it actually stop at `9999`? Will it not update my package if it sits at a depth of `10,000`? This is the epitome of a magic number. 

And lastly, if you want to update ALL your packages to the latest major version, you can't. You have to use a 3rd party tool.

**Comment by ljharb** [comment]
You only need `npm install`, unless you have a lockfile - in which case, removing it and running `npm install` seems simplest.

You're right that you can't do the dangerous thing of updating everything across breaking changes without a separate tool, but that's a good thing.

**Comment by kristof-mattei** [comment]
The problem I have is that intrinsically doing an `npm --depth 9999 update` should be identical to deletion of the lock file and doing `npm install`. It is not. Newer versions get installed with the latter. And  I am trying to trace that down.

**Comment by ljharb** [comment]
What exact differences are you seeing? Can you diff the two lockfiles?

**Comment by pahan35** [comment]
@ljharb I'm not totally sure about @Kristof-Mattei's case but I noticed that `npm update --depth <number>` causes bug: it loses `dev: true` for devDependencies dependencies.

I'm preparing issue for it
