### ISSUE TITLE
[FEATURE] Support `binDependencies`

### ISSUE THREAD

**Issue by Raynos** [npm/cli#949]
# What / Why

Add a new top level `binDependencies` to the `package.json`.

This is like `devDependencies` except they are not installed into `./node_modules` but instead installed into `~/.npm/bin-deps/${pkg.name}/node_modules`.

When running scripts with `npm run {name}` we should add `~/.npm/bin-deps/${pkg.name}/node_modules/.bin` to $PATH

## Where

npm cli

### Current Behavior

When I want to run a binary like `browserify` or `nyc` ; All of it's dependencies exist in `./node_modules` and `npm ls`.

I do not care about the dependencies of these binary only modules. Really when I want to run `nyc` from the CLI or in an npm script, I'd love to treat as an opaque zero dependency binary.

### Expected Behavior

I want my `./node_modules` to only contain code that I actually use in my library / app ; not from binary dependencies that are part of my toolchain for building or running tests.

## References

I've implemented this in http://github.com/Raynos/npm-bin-deps

To use it in npm scripts you have to do `npr tap` or `npr nyc` instead of a plain `tap` or `nyc` since npm does not know about `npm-bin-deps` and does not add `~/.config/npm-bin-deps/{pkg.name}/node_modules/.bin` to $PATH .

**Comment by Raynos** [comment]
## Caveats

I didn't care enough to implement `package-lock` or `shrinkwrap` for `binDependencies`. 

This is probably bad in not having reproducible artifacts but I am ok with that for now. 

Also there's no way to do `npm ls --bin` or something like that, I'd have to go to the magic dir where the modules actually are and run `npm ls` ; If I want to hand edit one of my binary dependencies I again have to go to that directory or temporarily re-install it as a devDependency for local editing.

This does work on CI by just writing to whatever `~` is on CI machines like travis / github actions.

**Comment by ljharb** [comment]
I think this needs to be an RFC on that repo, rather than here?

**Comment by Raynos** [comment]
If there’s interest in an RFC, I can go ahead and propose one.

**Comment by ljharb** [comment]
I think the point of the rfc is to generate interest :-)

(note tho that storing it in the npm cache like that wouldn’t work well, since that spans node versions, and installed packages can’t be reliably shared across node versions due to compilation - but there’s probably alternatives that could be explored)

**Comment by ruyadorno** [comment]
closing this issue in favor of following up with the discussion in the RFC: https://github.com/npm/rfcs/issues/115

thanks @Raynos!
