### ISSUE TITLE
running npm publish from package.json scripts gives 401 Unauthorized

### ISSUE THREAD

**Issue by sayjeyhi** [npm/cli#966]
If I run `npm publish` in cli directly package will publish without any error but when I add it in a script inside `package.json` file it says :
```bash
npm ERR! 401 Unauthorized - PUT https://registry.yarnpkg.com/@someWhere/package - You must be logged in to publish packages.
```

I tried to delete `.npmrc` , relogin, generate authToken and add it on npmrc but could not solve it

**Comment by ljharb** [comment]
You’re running npm publish but it’s trying to contact yarnpkg.com?

**Comment by sayjeyhi** [comment]
excuse me my `lerna` config was using yarn as npmClient , but I thought yarn and npm loging in is shared, `yarn login` just ask user name and email in version 1.x , version 2 has `yarn npm login`

by the way I set my lerna npm client to npm and my problem is solved , thanks
