### ISSUE TITLE
4 verbose npm-session 969d6a1e9502aade 5 silly install loadCurrentTree 6 silly install readLocalPackageData 7

### ISSUE THREAD

**Issue by muazzamkha95** [npm/cli#972]
4 verbose npm-session 969d6a1e9502aade
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 warn registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ERR_STREAM_DESTROYED: Cannot call write after a stream was destroyed
8 warn registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
9 HTTP fetch GET 200 https://registry.npmjs.org/cordova-android 727ms (from cache)
10 timing npm Completed in 3491ms

**Comment by DanielRuf** [comment]
Please try it again. There might have been a network related issue.
