### ISSUE TITLE
Links for "npm install" in https://docs.npmjs.com/cli-commands/update.html go to the wrong page

### ISSUE THREAD

**Issue by domenic** [npm/cli#976]
# What / Why

https://docs.npmjs.com/cli-commands/update.html has links for "npm install", "npm outdated", "npm shrinkwrap", and "npm ls" at the bottom, under "See also".

These go to URLs of the form https://docs.npmjs.com/cli-commands/npm-install, which seem to give some kind of landing page. They do not give the documentation requested.

## When

I click on those links on the https://docs.npmjs.com/cli-commands/update.html page

## Where

The npm documentation website

### Current Behavior

These go to URLs of the form https://docs.npmjs.com/cli-commands/npm-install, which seem to give some kind of landing page.

### Steps to Reproduce

1. Go to https://docs.npmjs.com/cli-commands/update.html
2. Scroll down to "See also"
3. Click on one of the links for "npm install", "npm outdated", "npm shrinkwrap", or "npm ls"

### Expected Behavior

They should go to documentation pages describing these commands.

## Who

I don't know what this is asking.

## References

I am coming to this page via the link "Found a typo? Let us know!" in the footer.

**Comment by tarunbatra** [comment]
+1 to this. Have seen this on the docs, but the code here seems to have the right URL. Is anyone looking at this issue or can point me to the right direction to fix it?
