### ISSUE TITLE
[FEATURE] cli should have a --save-peer flag

### ISSUE THREAD

**Issue by mikemimik** [npm/cli#978]
# What / Why

Adding dependencies to a project (`package.json`) is done by default with `npm install`, however it's possible to pass `--save-dev` or `--save-prod` to tell the cli where to save the particular item. Additionally there should be `--save-peer` to save the item into the `peerDependencies` map.

## When

While running `npm install` the flag should exist.

## Where

* `package.json`

### Current Behavior

* This feature doesn't exist.

### Expected Behavior

* `npm install --save-peer react@16`

## References

* https://github.com/npm/rfcs/issues/95

**Comment by ruyadorno** [comment]
This has already been implemented in [arborist](https://github.com/npm/arborist) and is expected to land in **npm@7** 😊
