### ISSUE TITLE
NPM ERROR

### ISSUE THREAD

**Issue by emmanueladeola** [npm/cli#981]
# What / Why
I get this error any time i run npm install
npm WARN registry Using stale data from https://registry.npmjs.org/ because the host is inaccessible -- are you offline?  
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of 
issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
<https://npm.community>
 
is there away to solve this issue

## Where
  * npm public registry
  * npm/<repository>

## Who
  * @npm/<team>
  * @<username>

## References

* n/a

**Comment by DanielRuf** [comment]
Please check if you can access registry.npmjs.org.
