### ISSUE TITLE
[QUESTION] Use ENV/value inside version of dependency

### ISSUE THREAD

**Issue by mbielecki2-rtbh** [npm/cli#983]
Example package.json file:
```
{
  "paths": {
      "lib_a": "./path/to/lib/a"
   },
   "scripts": {
      "lib_a:build": "tsc -p $npm_package_paths_lib_a",
      "lib_a:publish": "npm publish $npm_package_paths_lib_a"
   },
   "devDependencies": {
      "@my-org/lib-a": "file:$npm_package_paths_lib_a",
   }
}
```
As you can see, we have definied variable `$npm_package_paths_lib_a` because path to the lib is used in 3 places, but for some reason i can not use variable inside version of dependency. Is there any other syntax for this or this feature is not supported?

Big picture:
I have multiple packages inside single repository because i do not want to duplicate build and deploy process, which is same for multiple UI components. Also those components are using different dependencies, so when i use lib_a i do not want to install libraries required for lib_b etc (to make `npm install` much faster when someone is using only few components).

**Comment by ljharb** [comment]
No, scripts are shell commands, but everything else in package.json is static, and afaik must remain so.
