### ISSUE TITLE
[BUG] Permision issue with npm install

### ISSUE THREAD

**Issue by Huluti** [npm/cli#984]
* **Version**: v13.10.1
* **Platform**: Linux localhost.localdomain 5.6.0-0.rc3.git0.1.fc32.x86_64 #1 SMP Mon Feb 24 21:29:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* **Subsystem**: 

### What steps will reproduce the bug?

    npm install

### How often does it reproduce? Is there a required condition?

Always.

### What is the expected behavior?

installation of the modules.

### What do you see instead?

    instruction non permisepostinstall: sill install executeActions

![image](https://user-images.githubusercontent.com/5782198/76022973-81d87a80-5f28-11ea-8893-4000f130d13d.png)

### Aditional details

Already tried to reinstall nodejs, remove the package-lock.json and clean the cache...

**Comment by DanielRuf** [comment]
Hi @Huluti,

which npm version do you use?

**Comment by Huluti** [comment]
@DanielRuf Hi! the 6.13.7 version.

**Comment by Huluti** [comment]
I've tried that but it doesn't change the version.
![image](https://user-images.githubusercontent.com/5782198/76211751-3ca59880-6207-11ea-8d19-4d338b66a9e9.png)

**Comment by DanielRuf** [comment]
Please check your PATH. Do you also use yarn and maybe some npm version was installed by it or there is some other npm binary loaded before the right one?

**Comment by ljharb** [comment]
See that “npm-global” thing? Delete the “prefix” line from your ~/.npmrc

**Comment by Huluti** [comment]
I've this because of [this guide](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally#manually-change-npms-default-directory).

Without this, I can't install npm globally:

    npm ERR! The operation was rejected by your operating system.
    npm ERR! It is likely you do not have the permissions to access this file as the current user

**Comment by ljharb** [comment]
You'd need to use `sudo npm install -g` to install things globally; separately, you don't install npm, it comes with node - at that point you can use npm to update npm.

**Comment by DanielRuf** [comment]
> You'd need to use `sudo npm install -g` to install things globally;

I thought this isn't recommended (anymore) and there were fixes and recommendations to chown it to the current user?

**Comment by DanielRuf** [comment]
https://twitter.com/npmjs/status/1151288592674590720

**Comment by ljharb** [comment]
I've seen nothing but problems from the guide linked above; that tweet just says "run `sudo chown -R $USER ~/.npm` if you *do* use sudo to install npm globally".

**Comment by Huluti** [comment]
Thank's for your responses. I've remove what the guide said. I have reverted nodejs to 12.16.1 LTS instead of the latest version. And it reworks.
