### ISSUE TITLE
[v7] Complete `npm install` command

### ISSUE THREAD

**Issue by mikemimik** [npm/cli#995]
Current Behaviour:
```
> npm i abbrev taxes undefined
npm WARN deprecated undefined@0.1.0: this package has been deprecated
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN nocommit@1.0.0 No description
npm WARN nocommit@1.0.0 No repository field.

+ undefined@0.1.0
+ abbrev@1.1.1
+ taxes@1.0.0
added 3 packages from 2 contributors and audited 3 packages in 0.734s
found 0 vulnerabilities
```

We're trying to reproduce this _kind_ of output now that we're using `arborist` to do tree related things.

- [x] Find the list of added dependencies (one or many), and output them
- [x] Create function to turn `arborist` tree into an `archy` tree for outputing

#### Branches
- https://github.com/npm/cli/tree/mikemimik/feature/npm-install

#### References
- https://github.com/npm/cli/issues/971

**Comment by isaacs** [comment]
Closed by #1245
